"""Hand-authored alignment triples for Bamidbar chapter 19."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן", "ת'ם כלם אללה מוסי' והרון",
         "Then God spoke to Moses and Aaron"),
        ("לֵאמֹר", "תכלימא", "directly."),
    ],
    2: [
        ("זֹאת חֻקַּת הַתּוֹרָה", "הד'א רסם אלשריעה", "This is the statute of the law"),
        ("אֲשֶׁר-צִוָּה יְהוָה לֵאמֹר", "אלתי אמר אללה בהא קאילא", "which God commanded, saying"),
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "מר בני אסראיל", "'Instruct the sons of Israel"),
        ("וְיִקְחוּ אֵלֶיךָ פָרָה אֲדֻמָּה תְּמִימָה", "באן יאתוך בבקרה צפרא צחיחה",
         "that they bring you a yellow cow, sound"),
        ("אֲשֶׁר אֵין-בָּהּ מוּם", "מא ליס פיהא עיב", "in which there is no blemish"),
        ("אֲשֶׁר לֹא-עָלָה עָלֶיהָ עֹל", "מא לם יטלע עליה ניר", "upon which no yoke has come up.'"),
    ],
    3: [
        ("וּנְתַתֶּם אֹתָהּ אֶל-אֶלְעָזָר הַכֹּהֵן", "ואדפעוהא לאלעזר אלאמאם",
         "'And deliver her to Eleazar the priest"),
        ("וְהוֹצִיא אֹתָהּ אֶל-מִחוּץ לַמַּחֲנֶה", "ויכ'רגהא אלי' כ'ארג אלעסכר",
         "and he shall bring her out to outside the camp"),
        ("וְשָׁחַט אֹתָהּ לְפָנָיו", "ויד'בחהא בחצ'רתה", "and he shall slaughter her in his presence.'"),
    ],
    4: [
        ("וְלָקַח אֶלְעָזָר הַכֹּהֵן מִדָּמָהּ--בְּאֶצְבָּעוֹ", "ויאכד' מן דמהא באצבעה",
         "'And he shall take of her blood with his finger"),
        ("וְהִזָּה אֶל-נֹכַח פְּנֵי אֹהֶל-מוֹעֵד", "וינצח מקאבל וגה כ'בא אלמחצ'ר",
         "and shall sprinkle, facing the entrance of the tent of the appointed meeting"),
        ("מִדָּמָהּ--שֶׁבַע פְּעָמִים", "מנה סבע מראר", "from it, seven times.'"),
    ],
    5: [
        ("וְשָׂרַף אֶת-הַפָּרָה לְעֵינָיו", "ויאמר באחראקהא בחצ'רתה",
         "'And he shall give the order that she be burned in his presence"),
        ("אֶת-עֹרָהּ וְאֶת-בְּשָׂרָהּ", "מע גלדהא ולחמהא", "with her hide and her flesh"),
        ("וְאֶת-דָּמָהּ עַל-פִּרְשָׁהּ יִשְׂרֹף", "ודמהא ופרת'הא", "and her blood and her dung.'"),
    ],
    6: [
        ("וְלָקַח הַכֹּהֵן עֵץ אֶרֶז וְאֵזוֹב", "ויאכד' עוד ארז. וצעתר",
         "'And the priest shall take a cedar-wood staff, and hyssop"),
        ("וּשְׁנִי תוֹלָעַת", "וצבג' קרמז", "and scarlet dye"),
        ("וְהִשְׁלִיךְ אֶל-תּוֹךְ שְׂרֵפַת הַפָּרָה", "וירמי ד'אלך פי וסט חריקהא",
         "and shall cast these into the midst of her burning.'"),
    ],
    7: [
        ("וְכִבֶּס בְּגָדָיו הַכֹּהֵן וְרָחַץ בְּשָׂרוֹ בַּמַּיִם",
         "ויג'סל הד'א אלאמאם ת'יאבה. וירחץ' בדנה באלמא",
         "'And this priest shall wash his garments, and shall rinse his body with water"),
        ("וְאַחַר יָבֹא אֶל-הַמַּחֲנֶה", "ובעד ד'אלך ידכ'ל אלי' אלעסכר",
         "and after that he shall enter into the camp"),
        ("וְטָמֵא הַכֹּהֵן עַד-הָעָרֶב", "וינגס אלי' אלליל",
         "and he shall be impure until the evening.'"),
    ],
    8: [
        ("וְהַשֹּׂרֵף אֹתָהּ", "ואלמחרקהא", "'And he who burns her"),
        ("יְכַבֵּס בְּגָדָיו בַּמַּיִם וְרָחַץ בְּשָׂרוֹ בַּמָּיִם",
         "יג'סל ת'איבה. וירחץ' בדנה באלמא",
         "shall wash his garments, and shall rinse his body with water"),
        ("וְטָמֵא עַד-הָעָרֶב", "וינגס אלי' אלמג'יב", "and shall be impure until sunset.'"),
    ],
    9: [
        ("וְאָסַף אִישׁ טָהוֹר אֵת אֵפֶר הַפָּרָה", "ויגמע רגל טאהר. רמאד אלבקרה",
         "'And a ritually pure man shall gather the ashes of the cow"),
        ("וְהִנִּיחַ מִחוּץ לַמַּחֲנֶה בְּמָקוֹם טָהוֹר",
         "ויצ'עה כ'ארג אלעסכר פי מוצ'ע טאהר",
         "and shall place them outside the camp in a pure place"),
        ("וְהָיְתָה לַעֲדַת בְּנֵי-יִשְׂרָאֵל לְמִשְׁמֶרֶת",
         "ותכון לגמאעה' בני אסראיל מחפוצ'א",
         "and it shall be kept for the congregation of the sons of Israel"),
        ("לְמֵי נִדָּה--חַטָּאת הִוא", "למא אלנצ'ח והי ד'כוה",
         "for the water of sprinkling — it is a purification-offering.'"),
    ],
    10: [
        ("וְכִבֶּס הָאֹסֵף אֶת-אֵפֶר הַפָּרָה אֶת-בְּגָדָיו",
         "ויג'סל אלגאמע רמאדהא ת'יאבה",
         "'And he who gathers her ashes shall wash his garments"),
        ("וְטָמֵא עַד-הָעָרֶב", "וינגס אלי' אלליל", "and shall be impure until the evening.'"),
        ("וְהָיְתָה לִבְנֵי יִשְׂרָאֵל וְלַגֵּר הַגָּר בְּתוֹכָם",
         "ותכון לבני אסראיל. ולאלג'ריב. אלדכ'יל פי מא בינהם",
         "And it shall be for the sons of Israel, and for the stranger who dwells among them"),
        ("לְחֻקַּת עוֹלָם", "רסם אלדהר", "a perpetual statute forever."),
    ],
    11: [
        ("הַנֹּגֵעַ בְּמֵת לְכָל-נֶפֶשׁ אָדָם", "ומן דנא במיית מן גמיע אנפס אלנאס",
         "And whoever approaches a dead person from among all the souls of mankind"),
        ("וְטָמֵא שִׁבְעַת יָמִים", "פלינגס סבעה' אייאם", "shall be impure for seven days."),
    ],
    12: [
        ("הוּא יִתְחַטָּא-בוֹ בַּיּוֹם הַשְּׁלִישִׁי וּבַיּוֹם הַשְּׁבִיעִי--יִטְהָר",
         "והו יתד'כא מנה. פי אליום אלת'אלת' ואלסאבע פיטהר",
         "He shall purify himself from it on the third day and the seventh day, and then he shall be pure"),
        ("וְאִם-לֹא יִתְחַטָּא בַּיּוֹם הַשְּׁלִישִׁי וּבַיּוֹם הַשְּׁבִיעִי--לֹא יִטְהָר",
         "ואן לם יתד'כא מנה. פיהמא לא יטהר",
         "but if he does not purify himself from it on both of them, he shall not be pure."),
    ],
    13: [
        ("כָּל-הַנֹּגֵעַ בְּמֵת בְּנֶפֶשׁ הָאָדָם אֲשֶׁר-יָמוּת",
         "פכל מן דנא. במיית מן נפוס אלנאס אלד'י ימות",
         "So every one who approaches a dead person from among the souls of mankind who dies"),
        ("וְלֹא יִתְחַטָּא אֶת-מִשְׁכַּן יְהוָה טִמֵּא",
         "ולא יתד'כא. פקד נגס מסכן אללה אד' דכ'לה",
         "and does not purify himself — he has defiled the dwelling of God when he entered it"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִיִּשְׂרָאֵל",
         "וינקטע ד'אלך אלאנסאן מן אל אסראיל",
         "and that person shall be cut off from the house of Israel"),
        ("כִּי מֵי נִדָּה לֹא-זֹרַק עָלָיו טָמֵא יִהְיֶה--עוֹד טֻמְאָתוֹ בוֹ",
         "אד' מא אלנצ'ח. לם ירש עלי'ה פהו נגס לד'אלך. ונגאסתה עלי'ה אבדא",
         "since the water of sprinkling was not sprinkled upon him, and he is therefore impure, and his impurity remains upon him always."),
    ],
    14: [
        ("זֹאת הַתּוֹרָה אָדָם כִּי-יָמוּת בְּאֹהֶל",
         "והד'ה אלשריעה. אי אנסאן מאת פי כ'בא",
         "And this is the law: any person who dies in a tent"),
        ("כָּל-הַבָּא אֶל-הָאֹהֶל וְכָל-אֲשֶׁר בָּאֹהֶל יִטְמָא שִׁבְעַת יָמִים",
         "פכל מא פיה וכל מן דכ'ל אלי'ה. ינגס סבעה' אייאם",
         "all that is in it and all who enter into it shall be impure for seven days."),
    ],
    15: [
        ("וְכֹל כְּלִי פָתוּחַ", "וכל אנא כ'זף מפתוח", "And every open earthenware vessel"),
        ("אֲשֶׁר אֵין-צָמִיד פָּתִיל עָלָיו--טָמֵא הוּא",
         "אלד'י ליס לה צ'מאם מקייד. פהו נגס",
         "that has no stopper fastened upon it is impure."),
    ],
    16: [
        ("וְכֹל אֲשֶׁר-יִגַּע עַל-פְּנֵי הַשָּׂדֶה",
         "וכל מן דנא עלי' וגה אלצחרא",
         "And every one who approaches upon the face of the wilderness"),
        ("בַּחֲלַל-חֶרֶב אוֹ בְמֵת", "בקתיל סיף או מיית", "— one slain by the sword, or a dead person"),
        ("אוֹ-בְעֶצֶם אָדָם אוֹ בְקָבֶר", "או עצ'ם אנסאן או קבר",
         "or a human bone, or a grave"),
        ("יִטְמָא שִׁבְעַת יָמִים", "ינגס סבעה' אייאם", "shall be impure for seven days."),
    ],
    17: [
        ("וְלָקְחוּ לַטָּמֵא מֵעֲפַר שְׂרֵפַת הַחַטָּאת",
         "וליוכ'ד' לה. מן רמאד חריק אלבקרה",
         "And there shall be taken for him some of the ashes of the burning of the cow"),
        ("וְנָתַן עָלָיו מַיִם חַיִּים אֶל-כֶּלִי", "ויצב עלי'ה. מא נביע פי אנא",
         "and spring water shall be poured over it into a vessel."),
    ],
    18: [
        ("וְלָקַח אֵזוֹב וְטָבַל בַּמַּיִם אִישׁ טָהוֹר",
         "ואליאכ'ד' רגל טאהר שייא מן צעתר. ויג'מסה פי ד'אלך אלמא",
         "And a ritually pure man shall take some hyssop, and dip it in that water"),
        ("וְהִזָּה עַל-הָאֹהֶל וְעַל-כָּל-הַכֵּלִים",
         "וינצ'ח עלי' אלכ'בא ועלי' גמיע אלאניה",
         "and shall sprinkle upon the tent, and upon all the vessels"),
        ("וְעַל-הַנְּפָשׁוֹת אֲשֶׁר הָיוּ-שָׁם", "ועלי' אלנפוס אלד'י כאנת ת'ם",
         "and upon the persons who were there"),
        ("וְעַל-הַנֹּגֵעַ בַּעֶצֶם אוֹ בֶחָלָל אוֹ בַמֵּת אוֹ בַקָּבֶר",
         "ועלי' אלדאני. באל עצ'ם או באלקתיל. או אלמיית או אלקבר",
         "and upon the one who drew near to a bone, or to the slain, or to the dead, or to the grave."),
    ],
    19: [
        ("וְהִזָּה הַטָּהֹר עַל-הַטָּמֵא בַּיּוֹם הַשְּׁלִישִׁי וּבַיּוֹם הַשְּׁבִיעִי",
         "כדאך ינצ'ח אלטאהר עלי' אלנגס. פי אליום אלת'לאת' ואלסאבע",
         "So the pure man shall sprinkle upon the impure on the third day and the seventh day"),
        ("וְחִטְּאוֹ בַּיּוֹם הַשְּׁבִיעִי", "פאד'א ד'כאה פי אליום אלסאבע",
         "and when he has purified him on the seventh day"),
        ("וְכִבֶּס בְּגָדָיו וְרָחַץ בַּמַּיִם", "ג'סל ת'יאבה. ורחץ' באלמא",
         "he shall wash his garments and rinse himself with water"),
        ("וְטָהֵר בָּעָרֶב", "וטהר באלעשי", "and shall be pure at evening."),
    ],
    20: [
        ("וְאִישׁ אֲשֶׁר-יִטְמָא וְלֹא יִתְחַטָּא",
         "ואי רגל תנגס בד'אלך ולם יתד'כא",
         "But any man who has become impure by this and has not purified himself"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִתּוֹךְ הַקָּהָל",
         "פינקטע ד'אלך אלאנסאן מן בין אלגוק",
         "— that person shall be cut off from among the assembly"),
        ("כִּי אֶת-מִקְדַּשׁ יְהוָה טִמֵּא", "למא נגס מקדס אללה אד' דכ'לה",
         "since he has defiled the sanctuary of God when he entered it"),
        ("מֵי נִדָּה לֹא-זֹרַק עָלָיו--טָמֵא הוּא",
         "ולם ינצ'ח עלי'ה מן מא אלנצ'ח פהו נגס",
         "and the water of sprinkling was not sprinkled upon him; he is impure."),
    ],
    21: [
        ("וְהָיְתָה לָהֶם לְחֻקַּת עוֹלָם", "ויכון להם דא'לך רסם אלדהר",
         "And this shall be for them a perpetual statute forever."),
        ("וּמַזֵּה מֵי-הַנִּדָּה יְכַבֵּס בְּגָדָיו",
         "ונאצ'ח מא אלנצ'ח יג'סל ת'יאבה",
         "And the one who sprinkles the water of sprinkling shall wash his garments"),
        ("וְהַנֹּגֵעַ בְּמֵי הַנִּדָּה יִטְמָא עַד-הָעָרֶב",
         "ומן לאמס מא אלנצ'ח. ינגס אלי' אלליל",
         "and whoever touches the water of sprinkling shall be impure until the evening."),
    ],
    22: [
        ("וְכֹל אֲשֶׁר-יִגַּע-בּוֹ הַטָּמֵא יִטְמָא",
         "וכל מא לאמסה אלנגס ינגס",
         "And whatever the impure person touches shall become impure"),
        ("וְהַנֶּפֶשׁ הַנֹּגַעַת תִּטְמָא עַד-הָעָרֶב",
         "פאן כאן אנסאן דנא בה ינגס אלי' אלליל",
         "and if a person approached it, he shall be impure until the evening."),
    ],
}
