"""Hand-authored alignment triples for Bamidbar chapter 30."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-בְּנֵי יִשְׂרָאֵל", "ת'ם קאל מוסי' לבני אסראיל",
         "Then Moses said to the sons of Israel"),
        ("כְּכֹל אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה", "כגמיע מא אמרה אללה בה",
         "all that God had commanded him"),
    ],
    2: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-רָאשֵׁי הַמַּטּוֹת לִבְנֵי יִשְׂרָאֵל לֵאמֹר",
         "ת'ם כלם מוסי' רויסא אלאסבאט. אלד'י לבני אסראיל קאילא",
         "Then Moses spoke to the heads of the tribes of the sons of Israel, saying"),
        ("זֶה הַדָּבָר אֲשֶׁר צִוָּה יְהוָה", "הד'א אלאמר. אלד'י אמר אללה בה",
         "'This is the matter which God has commanded"),
    ],
    3: [
        ("אִישׁ כִּי-יִדֹּר נֶדֶר לַיהוָה", "אי רגל נד'ר נד'רא ללה",
         "Any man who vows a vow to God"),
        ("אוֹ-הִשָּׁבַע שְׁבֻעָה לֶאְסֹר אִסָּר עַל-נַפְשׁוֹ",
         "או חלף ימינא ליעקד עקדא עלי' נפסה",
         "or swears an oath to bind a commitment upon himself"),
        ("לֹא יַחֵל דְּבָרוֹ", "פלא יבד'ל קולה", "he shall not dishonor his word"),
        ("כְּכָל-הַיֹּצֵא מִפִּיו יַעֲשֶׂה", "פכל מא כ'רג מן פאה יעמל",
         "all that came out of his mouth he shall do"),
    ],
    4: [
        ("וְאִשָּׁה כִּי-תִדֹּר נֶדֶר לַיהוָה", "ואייה' אמראה נד'רת נד'רא ללה",
         "And any woman who vows a vow to God"),
        ("וְאָסְרָה אִסָּר בְּבֵית אָבִיהָ בִּנְעֻרֶיהָ",
         "או עקדת עקדא. פי בית אביהא פי חאל צבאיהא",
         "or binds a commitment, while in her father's house, in the time of her youth"),
    ],
    5: [
        ("וְשָׁמַע אָבִיהָ אֶת-נִדְרָהּ וֶאֱסָרָהּ אֲשֶׁר אָסְרָה עַל-נַפְשָׁהּ",
         "פסמע אביהא נד'רהא. ועקדהא אלד'י עקדתה עלי' נפסהא",
         "and her father hears her vow and her commitment which she has bound upon herself"),
        ("וְהֶחֱרִישׁ לָהּ אָבִיהָ--וְקָמוּ כָּל-נְדָרֶיהָ",
         "ואמסך ענהא. פקד ת'בת גמיע נד'ורהא",
         "and holds back from her — then all her vows are established"),
        ("וְכָל-אִסָּר אֲשֶׁר-אָסְרָה עַל-נַפְשָׁהּ יָקוּם",
         "וכל עקד עקדתה עלי' נפסהא",
         "and every commitment she has bound upon herself stands"),
    ],
    6: [
        ("וְאִם-הֵנִיא אָבִיהָ אֹתָהּ בְּיוֹם שָׁמְעוֹ",
         "ואן אנתהרהא אביהא פי יום סמע בד'אלך",
         "But if her father rebukes her on the day he hears of it"),
        ("כָּל-נְדָרֶיהָ וֶאֱסָרֶיהָ אֲשֶׁר-אָסְרָה עַל-נַפְשָׁהּ לֹא יָקוּם",
         "פכל נדורהא ועקודהא. אלד'י עקדתה עלי' נפסהא גי'ר ת'אבת",
         "then all her vows and her commitments which she has bound upon herself are not established"),
        ("וַיהוָה יִסְלַח-לָהּ", "ואללה יג'פר להא", "and God will forgive her"),
        ("כִּי-הֵנִיא אָבִיהָ אֹתָהּ", "אד' אנתהרהא אביהא",
         "since her father rebuked her"),
    ],
    7: [
        ("וְאִם-הָיוֹ תִהְיֶה לְאִישׁ", "ואן צארת לרגל",
         "And if she becomes a man's wife"),
        ("וּנְדָרֶיהָ עָלֶיהָ", "ונד'ורהא עליהא", "while her vows are upon her"),
        ("אוֹ מִבְטָא שְׂפָתֶיהָ אֲשֶׁר אָסְרָה עַל-נַפְשָׁהּ",
         "או לפץ' שפתיהא. אלד'י עקדתה עלי' נפסהא",
         "or the utterance of her lips which she has bound upon herself"),
    ],
    8: [
        ("וְשָׁמַע אִישָׁהּ בְּיוֹם שָׁמְעוֹ", "פסמע בעלהא. פי יום סמע",
         "and her husband hears, on the day he hears of it"),
        ("וְהֶחֱרִישׁ לָהּ", "ואמסך ענהא", "and holds back from her"),
        ("וְקָמוּ נְדָרֶיהָ וֶאֱסָרֶהָ אֲשֶׁר-אָסְרָה עַל-נַפְשָׁהּ--יָקֻמוּ",
         "פקד ת'בת נד'ורהא ועקודהא. אלד'י עקדת עלי' נפסהא",
         "then her vows and her commitments which she has bound upon herself are established"),
    ],
    9: [
        ("וְאִם בְּיוֹם שְׁמֹעַ אִישָׁהּ יָנִיא אוֹתָהּ",
         "ואן אנתהרהא בעלהא פי יום סמע בד'אלך",
         "But if her husband rebukes her on the day he hears of it"),
        ("וְהֵפֵר אֶת-נִדְרָהּ אֲשֶׁר עָלֶיהָ וְאֵת מִבְטָא שְׂפָתֶיהָ אֲשֶׁר אָסְרָה עַל-נַפְשָׁהּ",
         "ופסך' נד'ורהא אלד'י עליהא. ולפץ' שפתיהא. אלד'י עקדתה עלי' נפסהא",
         "and annuls her vows which are upon her and the utterance of her lips which she has bound upon herself"),
        ("וַיהוָה יִסְלַח-לָהּ", "ואללה יג'פר להא", "then God will forgive her"),
    ],
    10: [
        ("וְנֵדֶר אַלְמָנָה וּגְרוּשָׁה", "ונד'ר אלארמלה ואלמטלקה",
         "And the vow of a widow or a divorced woman"),
        ("כֹּל אֲשֶׁר-אָסְרָה עַל-נַפְשָׁהּ יָקוּם עָלֶיהָ",
         "פגמיע מא עקדתה עלי' נפסהא פת'אבת עליהא",
         "all that she has bound upon herself is established upon her"),
    ],
    11: [
        ("וְאִם-בֵּית אִישָׁהּ נָדָרָה", "ואן כאן פי בית זוגהא נד'רת",
         "And if she was in her husband's house when she vowed"),
        ("אוֹ-אָסְרָה אִסָּר עַל-נַפְשָׁהּ בִּשְׁבֻעָה",
         "או עקדת עקדא. עלי' נפסהא בימין",
         "or bound a commitment upon herself by oath"),
    ],
    12: [
        ("וְשָׁמַע אִישָׁהּ וְהֶחֱרִשׁ לָהּ לֹא הֵנִיא אֹתָהּ",
         "פסמע בעלהא ואמסך ענהא. ולם ינתהרהא",
         "and her husband heard, and held back from her, and did not rebuke her"),
        ("וְקָמוּ כָּל-נְדָרֶיהָ וְכָל-אִסָּר אֲשֶׁר-אָסְרָה עַל-נַפְשָׁהּ יָקוּם",
         "פקד ת'בת גמיע נדורהא. וכל עקד עקדתה עלי' נפסהא",
         "then all her vows and every commitment she has bound upon herself are established"),
    ],
    13: [
        ("וְאִם-הָפֵר יָפֵר אֹתָם אִישָׁהּ בְּיוֹם שָׁמְעוֹ",
         "ואן פסך' ד'אלך בעלהא פי יום סמע בה",
         "But if her husband annuls that on the day he hears of it"),
        ("כָּל-מוֹצָא שְׂפָתֶיהָ לִנְדָרֶיהָ וּלְאִסַּר נַפְשָׁהּ לֹא יָקוּם",
         "פכל מא כ'רג מן שפתיהא. מן נד'ור ועקוד עלי' נפסהא פג'יר ת'אבת",
         "then all that came forth from her lips, of vows and commitments upon herself, is not established"),
        ("אִישָׁהּ הֲפֵרָם", "ולמא פסכ'הם בעלהא", "for her husband has annulled them"),
        ("וַיהוָה יִסְלַח-לָהּ", "פאללה יג'פר להא", "and God will forgive her"),
    ],
    14: [
        ("כָּל-נֵדֶר וְכָל-שְׁבֻעַת אִסָּר לְעַנֹּת נָפֶשׁ",
         "כד'אך כל נד'ר. וכל ימין בעקד לעד'אב אלנפס",
         "So it is with every vow and every sworn oath of commitment for the affliction of the soul"),
        ("אִישָׁהּ יְקִימֶנּוּ", "בעלהא ית'בת ד'אלך", "her husband may establish it"),
        ("וְאִישָׁהּ יְפֵרֶנּוּ", "ובעלהא יבטלה", "or her husband may annul it"),
    ],
    15: [
        ("וְאִם-הַחֲרֵשׁ יַחֲרִישׁ לָהּ אִישָׁהּ מִיּוֹם אֶל-יוֹם",
         "ואן אמסך ענהא מן יום אלי' יום",
         "And if he holds back from her from day to day"),
        ("וְהֵקִים אֶת-כָּל-נְדָרֶיהָ אוֹ אֶת-כָּל-אֱסָרֶיהָ אֲשֶׁר עָלֶיהָ--הֵקִים אֹתָם",
         "פקד ת'בת גמיע נד'ורהא ועקודהא אלד'י עליהא. ת'בתהם",
         "then he has established all her vows and commitments which are upon her — has established them"),
        ("כִּי-הֶחֱרִשׁ לָהּ בְּיוֹם שָׁמְעוֹ", "למא אמסך ענהא. פי יום סמע בד'אלך",
         "by virtue of his holding back from her on the day he heard of it"),
    ],
    16: [
        ("וְאִם-הָפֵר יָפֵר אֹתָם אַחֲרֵי שָׁמְעוֹ", "ואן פסך' ד'אלך בעד מא סמע בה",
         "But if he annuls them after he has heard of them"),
        ("וְנָשָׂא אֶת-עֲו‍ֹנָהּ", "פקד חמל וזרהא", "then he has borne her guilt"),
    ],
    17: [
        ("אֵלֶּה הַחֻקִּים אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "הד'ה אלרסום. אלד'י אמר אללה בהא מוסי'",
         "These are the statutes which God commanded Moses"),
        ("בֵּין אִישׁ לְאִשְׁתּוֹ--בֵּין-אָב לְבִתּוֹ בִּנְעֻרֶיהָ בֵּית אָבִיהָ",
         "פי מא בין אלרגל וזוגתה דאימא. ופי מא בין אלאב ואבנתה. פי חאל צבאיהא והי פי מנזלה",
         "concerning what is between a man and his wife always, and concerning what is between a father and his daughter, in the time of her youth while she is in his household"),
    ],
}
