"""Hand-authored alignment triples for Bamidbar chapter 16."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּקַּח קֹרַח בֶּן-יִצְהָר בֶּן-קְהָת בֶּן-לֵוִי",
         "פתקדם קרח. אבן יצהר אבן קהת אבן לוי",
         "And Korah — son of Izhar, son of Kohath, son of Levi — came forward"),
        ("וְדָתָן וַאֲבִירָם בְּנֵי אֱלִיאָב וְאוֹן בֶּן-פֶּלֶת--בְּנֵי רְאוּבֵן",
         "ודתן ואבירם. אבני אליאב. ואון אבן פלת מן בני ראובן",
         "and Dathan and Abiram, sons of Eliab, and On son of Peleth, of the sons of Reuben."),
    ],
    2: [
        ("וַיָּקֻמוּ לִפְנֵי מֹשֶׁה", "פוקפו אמאם מוסי", "And they stood before Moses"),
        ("וַאֲנָשִׁים מִבְּנֵי-יִשְׂרָאֵל חֲמִשִּׁים וּמָאתָיִם",
         "ואנאס מן בני אסראיל מאיתין וכ'מסין",
         "and men of the sons of Israel, two hundred and fifty"),
        ("נְשִׂיאֵי עֵדָה קְרִאֵי מוֹעֵד אַנְשֵׁי-שֵׁם",
         "אשראף אלגמאעה. דעאת מחצ'ר ד'וי אסמא",
         "nobles of the assembly, summoned to the council, men of known names."),
    ],
    3: [
        ("וַיִּקָּהֲלוּ עַל-מֹשֶׁה וְעַל-אַהֲרֹן",
         "פתגווקו עלי' מוסי והרון",
         "And they gathered in a troop against Moses and Aaron"),
        ("וַיֹּאמְרוּ אֲלֵהֶם רַב-לָכֶם",
         "וקאלא להמא חסבכמא ריאסה",
         "and said to them: 'Enough of leadership for the two of you"),
        ("כִּי כָל-הָעֵדָה כֻּלָּם קְדֹשִׁים וּבְתוֹכָם יְהוָה",
         "אד' אלגמאעה כלהם מקדסין. ופי מא בינהם נור אללה",
         "for the whole assembly, every one of them, is holy, and the light of God is in their midst"),
        ("וּמַדּוּעַ תִּתְנַשְּׂאוּ עַל-קְהַל יְהוָה",
         "ומא באלכמא תתשרפאן עלי' גוק אללה",
         "so why do you exalt yourselves over the congregation of God?'"),
    ],
    4: [
        ("וַיִּשְׁמַע מֹשֶׁה וַיִּפֹּל עַל-פָּנָיו",
         "פסמע ד'אלך מוסי'. ווקע עלי' וגהה ילתמס אלוחי",
         "And when Moses heard this, he fell upon his face, seeking revelation."),
    ],
    5: [
        ("וַיְדַבֵּר אֶל-קֹרַח וְאֶל-כָּל-עֲדָתוֹ לֵאמֹר",
         "וכלם קרח. וכל גמועה וקאל להם",
         "And he spoke to Korah and to all his gatherings, and said to them"),
        ("בֹּקֶר וְיֹדַע יְהוָה אֶת-אֲשֶׁר-לוֹ וְאֶת-הַקָּדוֹשׁ",
         "ג'דא. יערף אללה אלד'י הו לה. ואלמקדס פיקרבה אליה",
         "'Tomorrow — God shall make known the one who is His, and the holy one He shall bring near to Him"),
        ("וְאֵת אֲשֶׁר יִבְחַר-בּוֹ יַקְרִיב אֵלָיו",
         "ומן יכ'תארה יקרבה אליה",
         "and whom He shall choose, He shall bring near to Him.'"),
    ],
    6: [
        ("זֹאת עֲשׂוּ קְחוּ-לָכֶם מַחְתּוֹת קֹרַח וְכָל-עֲדָתוֹ",
         "אצנעו כ'לה. כ'דו לכם מגאמרא. קרח וכל גמועה",
         "Do both these things: take for yourselves censers, O Korah and all his gatherings,"),
    ],
    7: [
        ("וּתְנוּ בָהֵן אֵשׁ וְשִׂימוּ עֲלֵיהֶן קְטֹרֶת לִפְנֵי יְהוָה מָחָר",
         "ואגעלו עליהא נארא. ואלקו עליהא בכורא. בין ידי אללה ג'דא",
         "and place fire upon them, and cast incense upon them, before God — tomorrow"),
        ("וְהָיָה הָאִישׁ אֲשֶׁר-יִבְחַר יְהוָה הוּא הַקָּדוֹשׁ",
         "ואי רגל אכ'תארה אללה הו אלמקדס",
         "and whichever man God shall choose, he is the holy one."),
        ("רַב-לָכֶם בְּנֵי לֵוִי", "חסבכם ד'אלך יא בני לוי",
         "Enough of this for you, O sons of Levi!'"),
    ],
    8: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-קֹרַח שִׁמְעוּ-נָא בְּנֵי לֵוִי",
         "וקאל מוסי' לקרח. אסמעו ד'אלך יא בני לוי",
         "And Moses said to Korah: 'Hear this, O sons of Levi."),
    ],
    9: [
        ("הַמְעַט מִכֶּם כִּי-הִבְדִּיל אֱלֹהֵי יִשְׂרָאֵל אֶתְכֶם מֵעֲדַת יִשְׂרָאֵל",
         "אקליל ענדכם. אד' אפרזכם אללה אלאה אסראיל מן גמאעתהם",
         "Is it too little for you that the God of Israel has separated you from their assembly"),
        ("לְהַקְרִיב אֶתְכֶם אֵלָיו--לַעֲבֹד אֶת-עֲבֹדַת מִשְׁכַּן יְהוָה",
         "פקרבכם אליה לתכ'דמו מסכנה",
         "and brought you near to Him to serve His tabernacle"),
        ("וְלַעֲמֹד לִפְנֵי הָעֵדָה לְשָׁרְתָם",
         "ותקפו. בין ידי אלגמאעה תכ'דמונהם",
         "and to stand before the assembly to serve them?"),
    ],
    10: [
        ("וַיַּקְרֵב אֹתְךָ וְאֶת-כָּל-אַחֶיךָ בְנֵי-לֵוִי אִתָּךְ",
         "פכד'אך קרבך. וסאיר אכ'ותך בני לוי מעך",
         "And so He brought you near, and all your brothers the sons of Levi with you"),
        ("וּבִקַּשְׁתֶּם גַּם-כְּהֻנָּה", "חתי' טלבתם אלאמאמה איצ'א",
         "and yet you have sought the office of imām as well?"),
    ],
    11: [
        ("לָכֵן אַתָּה וְכָל-עֲדָתְךָ--הַנֹּעָדִים עַל-יְהוָה",
         "לד'אלך. אנת וכל גמועך. אלמגתמעין עלי' אללה",
         "Therefore — you and all your gatherings, who have assembled against God"),
        ("וְאַהֲרֹן מַה-הוּא כִּי תלונו (תַלִּינוּ) עָלָיו",
         "והרון מן הו. אד' תתדמרון עליה",
         "and Aaron, what is he, that you bring your grievance against him?'"),
    ],
    12: [
        ("וַיִּשְׁלַח מֹשֶׁה לִקְרֹא לְדָתָן וְלַאֲבִירָם בְּנֵי אֱלִיאָב",
         "ת'ם בעת' מוסי. לידעו בדתן ואבירם אבני אליאב",
         "Then Moses sent to summon Dathan and Abiram, sons of Eliab"),
        ("וַיֹּאמְרוּ לֹא נַעֲלֶה", "פקאלא לא נציר אליך",
         "and they said: 'We shall not come to you."),
    ],
    13: [
        ("הַמְעַט כִּי הֶעֱלִיתָנוּ מֵאֶרֶץ זָבַת חָלָב וּדְבַשׁ לַהֲמִיתֵנוּ בַּמִּדְבָּר",
         "אקליל. מא אצעדתנא מן בלד יפיץ' אללבן ואלעסל. לתקתלנא פי אלבר",
         "Is it too little — that you brought us up from a land flowing with milk and honey, to kill us in the wilderness"),
        ("כִּי-תִשְׂתָּרֵר עָלֵינוּ גַּם-הִשְׂתָּרֵר",
         "חתי' תתרווס עלינא איצ'א תרווסא",
         "that you must lord it over us as well, lording it?"),
    ],
    14: [
        ("אַף לֹא אֶל-אֶרֶץ זָבַת חָלָב וּדְבַשׁ הֲבִיאֹתָנוּ",
         "ואיצ'א לם תדכ'לנא אלי' בלד יפיץ' אללבן ואלעסל",
         "And moreover, you have not brought us into a land flowing with milk and honey"),
        ("וַתִּתֶּן-לָנוּ נַחֲלַת שָׂדֶה וָכָרֶם",
         "ולא אעטיתנא נחלה' צ'יעה או כרם",
         "nor given us an inheritance of estate or vineyard"),
        ("הַעֵינֵי הָאֲנָשִׁים הָהֵם תְּנַקֵּר--לֹא נַעֲלֶה",
         "פלו תהדדת אולאיך אלקום. בקלע עיונהם לם נציר אליך",
         "even if you were to threaten those people with the gouging out of their eyes, we shall not come to you.'"),
    ],
    15: [
        ("וַיִּחַר לְמֹשֶׁה מְאֹד", "פאשתד עלי' מוסי ג'דא",
         "And Moses was greatly angered"),
        ("וַיֹּאמֶר אֶל-יְהוָה אַל-תֵּפֶן אֶל-מִנְחָתָם",
         "פקאל. אללהם לא תקבל בכורהם",
         "and said: 'O God, do not accept their incense"),
        ("לֹא חֲמוֹר אֶחָד מֵהֶם נָשָׂאתִי וְלֹא הֲרֵעֹתִי אֶת-אַחַד מֵהֶם",
         "וד'ל בה עלי' אני לם אסכ'ר לאחדהם חמארא. פצ'לא עלי' אן אסי אלי' אחדהם",
         "and let this testify that I have not pressed even one donkey of theirs into my service, much less that I have done wrong to any one of them.'"),
    ],
    16: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-קֹרַח", "ת'ם קאל מוסי לקרח",
         "Then Moses said to Korah"),
        ("אַתָּה וְכָל-עֲדָתְךָ הֱיוּ לִפְנֵי יְהוָה אַתָּה וָהֵם וְאַהֲרֹן מָחָר",
         "אנת וכל גמועך. אחצ'רו בין ידי אללה. מע הרון ג'דא",
         "'You and all your gatherings — present yourselves before God, with Aaron, tomorrow."),
    ],
    17: [
        ("וּקְחוּ אִישׁ מַחְתָּתוֹ וּנְתַתֶּם עֲלֵיהֶם קְטֹרֶת",
         "וליאכ'ד' כל ואחד מגמרתה. ואלקו עליהא בכ'ורא",
         "And let each man take his censer, and cast incense upon it"),
        ("וְהִקְרַבְתֶּם לִפְנֵי יְהוָה אִישׁ מַחְתָּתוֹ חֲמִשִּׁים וּמָאתַיִם מַחְתֹּת",
         "וקדמוהא בין ידי אללה. מאיתין וכ'מסין מגמרה",
         "and bring them before God — two hundred and fifty censers"),
        ("וְאַתָּה וְאַהֲרֹן אִישׁ מַחְתָּתוֹ",
         "ואנת והרון כל ואחד מגמרתה",
         "and you and Aaron, each man his censer.'"),
    ],
    18: [
        ("וַיִּקְחוּ אִישׁ מַחְתָּתוֹ וַיִּתְּנוּ עֲלֵיהֶם אֵשׁ וַיָּשִׂימוּ עֲלֵיהֶם קְטֹרֶת",
         "פאכ'ד' כל ואחד מגמרתה. וגעלו פיהא נארא. ואלקו עליהא בכורא",
         "And each man took his censer, and placed fire in it, and cast incense upon it"),
        ("וַיַּעַמְדוּ פֶּתַח אֹהֶל מוֹעֵד--וּמֹשֶׁה וְאַהֲרֹן",
         "ווקפו. עלי' באב כ'בא אלמחצ'ר ומוסי' והרון",
         "and they stood at the entrance of the tent of the assembly — and Moses and Aaron."),
    ],
    19: [
        ("וַיַּקְהֵל עֲלֵיהֶם קֹרַח אֶת-כָּל-הָעֵדָה אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "פגווק עליהם קרח גמיע אלגמאעה. אלי' באב כ'בא אלמחצ'ר",
         "And Korah gathered all the assembly against them, to the entrance of the tent of the assembly"),
        ("וַיֵּרָא כְבוֹד-יְהוָה אֶל-כָּל-הָעֵדָה", "פצ'הר נור אללה לגמיעהם",
         "and the light of God appeared to all of them."),
    ],
    20: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי והרון תכלימא",
         "Then God spoke to Moses and Aaron in direct speech,"),
    ],
    21: [
        ("הִבָּדְלוּ מִתּוֹךְ הָעֵדָה הַזֹּאת וַאֲכַלֶּה אֹתָם כְּרָגַע",
         "אן אנפרזתם מן בין הד'ה אלגמאעה. אפניתהם כטרפה",
         "saying: 'If you separate yourselves from among this assembly, I shall destroy them in an instant.'"),
    ],
    22: [
        ("וַיִּפְּלוּ עַל-פְּנֵיהֶם וַיֹּאמְרוּ", "פוקעא עלי' וגוההמא וקאלא",
         "And the two of them fell upon their faces and said"),
        ("אֵל אֱלֹהֵי הָרוּחֹת לְכָל-בָּשָׂר", "יא טאיק. יא אלאה ארואח כל בשרי",
         "'O Possessor of power and might! O God of the spirits of all living flesh!"),
        ("הָאִישׁ אֶחָד יֶחֱטָא וְעַל כָּל-הָעֵדָה תִּקְצֹף",
         "ארגל ואחד יכ'טי. ועלי סאיר אלגמאעה תסכ'ט",
         "shall one man err, and You be wrathful against the rest of the assembly?'"),
    ],
    23: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי תכלימא",
         "Then God spoke to Moses in direct speech,"),
    ],
    24: [
        ("דַּבֵּר אֶל-הָעֵדָה לֵאמֹר הֵעָלוּ מִסָּבִיב לְמִשְׁכַּן-קֹרַח דָּתָן וַאֲבִירָם",
         "מר אלגמאעה וקל להם. ארתפעו. ען חואלי מסכן קרח דתן ואבירם",
         "saying: 'Command the assembly and say to them: Move away from around the dwelling of Korah, Dathan, and Abiram.'"),
    ],
    25: [
        ("וַיָּקָם מֹשֶׁה וַיֵּלֶךְ אֶל-דָּתָן וַאֲבִירָם",
         "פקאם מוסי. ומצ'א אלי' דתן ואבירם",
         "And Moses arose and went to Dathan and Abiram"),
        ("וַיֵּלְכוּ אַחֲרָיו זִקְנֵי יִשְׂרָאֵל", "ומצו מעה שיוך' בני אסראיל",
         "and the elders of the sons of Israel went with him."),
    ],
    26: [
        ("וַיְדַבֵּר אֶל-הָעֵדָה לֵאמֹר סוּרוּ נָא מֵעַל אָהֳלֵי הָאֲנָשִׁים הָרְשָׁעִים הָאֵלֶּה",
         "פכלם אלגמאעה וקאל להם. אעתזלו ען אכ'ביה' הולאי אלקום אלצ'אלמין",
         "And he spoke to the assembly and said to them: 'Withdraw from the tents of these wrongdoing people"),
        ("וְאַל-תִּגְּעוּ בְּכָל-אֲשֶׁר לָהֶם פֶּן-תִּסָּפוּ בְּכָל-חַטֹּאתָם",
         "ולא תדנו בשי ממא הו להם. כלא תנסאפו בגמיע כ'טאיאהם",
         "and do not approach anything that belongs to them — lest you be swept away with all their sins.'"),
    ],
    27: [
        ("וַיֵּעָלוּ מֵעַל מִשְׁכַּן-קֹרַח דָּתָן וַאֲבִירָם--מִסָּבִיב",
         "פארתעפו. ען חואלי מסכן קרח דתן ואבירם",
         "And they moved away from around the dwelling of Korah, Dathan, and Abiram"),
        ("וְדָתָן וַאֲבִירָם יָצְאוּ נִצָּבִים פֶּתַח אָהֳלֵיהֶם",
         "והמא איצ'א כ'רגא. פאנתצבו עלא באב כ'באיהמא",
         "and the two of them also came out, and stood at the entrance of their tents"),
        ("וּנְשֵׁיהֶם וּבְנֵיהֶם וְטַפָּם", "ונסאהם ובניהם ואטפאלהם לירו מא יכון",
         "and their wives and their sons and their little ones — to see what would come to pass."),
    ],
    28: [
        ("וַיֹּאמֶר מֹשֶׁה בְּזֹאת תֵּדְעוּן כִּי-יְהוָה שְׁלָחַנִי",
         "פקאל מוסי. בהד'ה אלכ'לה. תעלמון. אן אללה בעת' בי",
         "And Moses said: 'By this resolution you shall know that God has sent me"),
        ("לַעֲשׂוֹת אֵת כָּל-הַמַּעֲשִׂים הָאֵלֶּה כִּי-לֹא מִלִּבִּי",
         "לאעמל גמיע הד'ה אלאעמאל. ליס מן תלקא נפסי",
         "to do all these deeds — not of my own accord."),
    ],
    29: [
        ("אִם-כְּמוֹת כָּל-הָאָדָם יְמֻתוּן אֵלֶּה",
         "אן מאת הולאי אלקום כמות כל אלנאס",
         "If these people die as all people die"),
        ("וּפְקֻדַּת כָּל-הָאָדָם יִפָּקֵד עֲלֵיהֶם--לֹא יְהוָה שְׁלָחָנִי",
         "וטולבו כמטאלבתהם. פליס אללה בעת' בי",
         "and are called to account as all people are called to account — then God has not sent me."),
    ],
    30: [
        ("וְאִם-בְּרִיאָה יִבְרָא יְהוָה וּפָצְתָה הָאֲדָמָה אֶת-פִּיהָ",
         "ואן כ'לק אללה כ'לקא. באן תפתח אלארץ' פאהא",
         "But if God creates a creation — that the earth opens its mouth"),
        ("וּבָלְעָה אֹתָם וְאֶת-כָּל-אֲשֶׁר לָהֶם",
         "פתבתלעהם וגמיע מאלהם",
         "and swallows them and all that belongs to them"),
        ("וְיָרְדוּ חַיִּים שְׁאֹלָה", "וינזלו אחיא אלי' אלת'רא",
         "and they go down alive into the ground"),
        ("וִידַעְתֶּם כִּי נִאֲצוּ הָאֲנָשִׁים הָאֵלֶּה אֶת-יְהוָה",
         "עלמתם. אן הולאי אלקום קד עצו אללה",
         "then you shall know that these people have transgressed against God.'"),
    ],
    31: [
        ("וַיְהִי כְּכַלֹּתוֹ לְדַבֵּר אֵת כָּל-הַדְּבָרִים הָאֵלֶּה",
         "וכאן ענד פראג'ה. מן קול הד'א אלכלאם",
         "And it came to pass, upon his finishing the saying of this speech"),
        ("וַתִּבָּקַע הָאֲדָמָה אֲשֶׁר תַּחְתֵּיהֶם",
         "אנשקת אלארץ' אלד'ין תחתהם",
         "that the earth which was beneath them split open."),
    ],
    32: [
        ("וַתִּפְתַּח הָאָרֶץ אֶת-פִּיהָ", "פפתחת אלארץ' פאהא",
         "And the earth opened its mouth"),
        ("וַתִּבְלַע אֹתָם וְאֶת-בָּתֵּיהֶם", "פאבתלעתהם וביותהם",
         "and swallowed them and their houses"),
        ("וְאֵת כָּל-הָאָדָם אֲשֶׁר לְקֹרַח וְאֵת כָּל-הָרְכוּשׁ",
         "וכל אנסאן לקרח. וגמיע אלסרח",
         "and every person belonging to Korah, and all the livestock."),
    ],
    33: [
        ("וַיֵּרְדוּ הֵם וְכָל-אֲשֶׁר לָהֶם חַיִּים--שְׁאֹלָה",
         "פנזלו הם וגמיע מאלהם. אחיא אלי' אלת'רא",
         "And they went down — they and all that was theirs — alive into the ground"),
        ("וַתְּכַס עֲלֵיהֶם הָאָרֶץ", "וג'טת עליהם אלארץ'",
         "and the earth closed over them"),
        ("וַיֹּאבְדוּ מִתּוֹךְ הַקָּהָל", "ובאדו מן בין אלגוק",
         "and they perished from among the congregation."),
    ],
    34: [
        ("וְכָל-יִשְׂרָאֵל אֲשֶׁר סְבִיבֹתֵיהֶם--נָסוּ לְקֹלָם",
         "וגמיע אל אסראיל. אלד'ין חואליהם הרבו מן שדה' אצואתהם",
         "And all the house of Israel who were around them fled at the sound of their voices"),
        ("כִּי אָמְרוּ פֶּן-תִּבְלָעֵנוּ הָאָרֶץ", "קאלו. כלא תבלענא אלארץ'",
         "saying: 'Lest the earth swallow us too.'"),
    ],
    35: [
        ("וְאֵשׁ יָצְאָה מֵאֵת יְהוָה", "ונאר כ'רגת מן ענד אללה",
         "And a fire went out from God"),
        ("וַתֹּאכַל אֵת הַחֲמִשִּׁים וּמָאתַיִם אִישׁ מַקְרִיבֵי הַקְּטֹרֶת",
         "פאחרקת אלמאיתין ואלכ'מסין אלרגל. מקרבי אלבכור",
         "and burned the two hundred and fifty men, who had offered the incense."),
    ],
}
