"""Hand-authored alignment triples for Bamidbar chapter 21."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּשְׁמַע הַכְּנַעֲנִי מֶלֶךְ-עֲרָד יֹשֵׁב הַנֶּגֶב",
         "ת'ם סמע אלכנאעני מלך ערד אלמקים פי אלדארום",
         "Then the Canaanite, king of Arad, dwelling in the south, heard"),
        ("כִּי בָּא יִשְׂרָאֵל דֶּרֶךְ הָאֲתָרִים", "באן בני אסראיל קד גאו. טריק אלאתרים",
         "that the sons of Israel had come by the way of the Atharim"),
        ("וַיִּלָּחֶם בְּיִשְׂרָאֵל", "פחארבהם", "and he fought against them"),
        ("וַיִּשְׁבְּ מִמֶּנּוּ שֶׁבִי", "וסבא מנהם סביא", "and took some of them captive."),
    ],
    2: [
        ("וַיִּדַּר יִשְׂרָאֵל נֶדֶר לַיהוָה", "פנד'ר אל אסראיל נד'רא. ללה",
         "And the house of Israel vowed a vow to God"),
        ("וַיֹּאמַר אִם-נָתֹן תִּתֵּן אֶת-הָעָם הַזֶּה בְּיָדִי",
         "קאילין. אן אסלמת הולאי אלקום פי ידי",
         "saying: 'If You deliver this people into my hand"),
        ("וְהַחֲרַמְתִּי אֶת-עָרֵיהֶם", "געלת קראהם צואפי",
         "I shall make their towns devoted property.'"),
    ],
    3: [
        ("וַיִּשְׁמַע יְהוָה בְּקוֹל יִשְׂרָאֵל", "פסמע אללה דעא אל אסראיל",
         "And God heard the prayer of the house of Israel"),
        ("וַיִּתֵּן אֶת-הַכְּנַעֲנִי", "ואסלם פי אידיהם. אלכנאעני",
         "and delivered the Canaanite into their hands"),
        ("וַיַּחֲרֵם אֶתְהֶם וְאֶת-עָרֵיהֶם", "פגעלוה וקראה צואפי",
         "and they made him and his towns devoted property"),
        ("וַיִּקְרָא שֵׁם-הַמָּקוֹם חָרְמָה", "וסמא ד'אלך אלמוצ'ע חרמה",
         "and they named that place Hormah."),
    ],
    4: [
        ("וַיִּסְעוּ מֵהֹר הָהָר דֶּרֶךְ יַם-סוּף",
         "ת'ם רחלו מן גבל הור טריק בחר אלקלזם",
         "Then they journeyed from Mount Hor by the way of the Sea of Qulzum (Red Sea)"),
        ("לִסְבֹב אֶת-אֶרֶץ אֱדוֹם", "ליסתדירו בלד אדום",
         "to go around the land of Edom"),
        ("וַתִּקְצַר נֶפֶשׁ-הָעָם בַּדָּרֶךְ", "פצ'גרת נפוס אלקום פי אלטריק",
         "and the souls of the people grew weary on the way."),
    ],
    5: [
        ("וַיְדַבֵּר הָעָם בֵּאלֹהִים וּבְמֹשֶׁה", "פתכלמו פי אללה ופי מוסי'",
         "And they spoke against God and against Moses"),
        ("לָמָה הֶעֱלִיתֻנוּ מִמִּצְרַיִם לָמוּת בַּמִּדְבָּר",
         "וקאלו לם אצעדתמונא מן מצר. לנמות פי אלבר",
         "saying: 'Why did you bring us up from Egypt to die in the wilderness"),
        ("כִּי אֵין לֶחֶם וְאֵין מַיִם", "ממא ליס כ'בז ולא מא",
         "where there is no bread and no water"),
        ("וְנַפְשֵׁנוּ קָצָה בַּלֶּחֶם הַקְּלֹקֵל", "וקד צ'גרת נפוסנא. מן אלטעאם אלכ'פיף",
         "And our souls are weary of this light food.'"),
    ],
    6: [
        ("וַיְשַׁלַּח יְהוָה בָּעָם אֵת הַנְּחָשִׁים הַשְּׂרָפִים",
         "פבעת' אללה פי אלקום. חיאת מחרקה",
         "And God sent among the people burning serpents"),
        ("וַיְנַשְּׁכוּ אֶת-הָעָם", "לסעתהם", "they bit them"),
        ("וַיָּמָת עַם-רָב מִיִּשְׂרָאֵל", "פמאת מנהם כת'ירין",
         "and many of them died."),
    ],
    7: [
        ("וַיָּבֹא הָעָם אֶל-מֹשֶׁה וַיֹּאמְרוּ חָטָאנוּ",
         "פגאו אלי' מוסי' וקאלו קד אכ'טאנא",
         "And they came to Moses and said: 'We have erred"),
        ("כִּי-דִבַּרְנוּ בַיהוָה וָבָךְ", "אד' תכלמנא פי אללה ופיך",
         "since we spoke against God and against you"),
        ("הִתְפַּלֵּל אֶל-יְהוָה וְיָסֵר מֵעָלֵינוּ אֶת-הַנָּחָשׁ",
         "אדע אלי' אללה. אן יזיל ענא אלחיאת",
         "Pray to God that He remove the serpents from us.'"),
        ("וַיִּתְפַּלֵּל מֹשֶׁה בְּעַד הָעָם", "פדעא להם מוסי'",
         "And Moses prayed for them."),
    ],
    8: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה עֲשֵׂה לְךָ שָׂרָף",
         "פקאל אללה לה. אצנע לך מחרקא",
         "And God said to him: 'Make yourself a burning image"),
        ("וְשִׂים אֹתוֹ עַל-נֵס", "וארפעה עלי' עלם",
         "and raise it upon a standard"),
        ("וְהָיָה כָּל-הַנָּשׁוּךְ וְרָאָה אֹתוֹ וָחָי",
         "פכל מלסוע. ילתפת אלי'ה תאיבא פיבקא",
         "then every one who has been bitten, if he turns toward it in repentance, shall survive.'"),
    ],
    9: [
        ("וַיַּעַשׂ מֹשֶׁה נְחַשׁ נְחֹשֶׁת וַיְשִׂמֵהוּ עַל-הַנֵּס",
         "פצנע מוסי' ת'עבאנא מן נחאס. ורפעה עלי' עלם",
         "And Moses made a serpent of bronze, and raised it upon a standard"),
        ("וְהָיָה אִם-נָשַׁךְ הַנָּחָשׁ אֶת-אִישׁ",
         "פכאן אלי' אנסאן לד'גה ת'עבאנא",
         "and it was that any person who had been bitten by a serpent"),
        ("וְהִבִּיט אֶל-נְחַשׁ הַנְּחֹשֶׁת וָחָי", "אלתפת אלי'ה תאיבא בקא חייא",
         "— if he turned toward it in repentance, he remained alive."),
    ],
    10: [
        ("וַיִּסְעוּ בְּנֵי יִשְׂרָאֵל", "פרחלו בני אסראיל",
         "And the sons of Israel journeyed"),
        ("וַיַּחֲנוּ בְּאֹבֹת", "ונזלו פי אובות", "and encamped at Oboth."),
    ],
    11: [
        ("וַיִּסְעוּ מֵאֹבֹת", "ורחלו מן אובות", "And they journeyed from Oboth"),
        ("וַיַּחֲנוּ בְּעִיֵּי הָעֲבָרִים בַּמִּדְבָּר",
         "ונזלו פי בלאקע אלמגאזאת. פי אלברייה",
         "and encamped in the open wastes of the crossings, in the wilderness"),
        ("אֲשֶׁר עַל-פְּנֵי מוֹאָב מִמִּזְרַח הַשָּׁמֶשׁ",
         "אלתי עלי'ה גהה' מואב. מן מטלע אלשמס",
         "that faces the direction of Moab, from the rising of the sun."),
    ],
    12: [
        ("מִשָּׁם נָסָעוּ וַיַּחֲנוּ בְּנַחַל זָרֶד",
         "ורחלו מן ת'ם. ונזלו פי ואד זרד",
         "And they journeyed from there, and encamped in the valley of Zared."),
    ],
    13: [
        ("מִשָּׁם נָסָעוּ וַיַּחֲנוּ מֵעֵבֶר אַרְנוֹן",
         "ורחלו מן ת'ם. ונזלו. פי גאנב ארנון",
         "And they journeyed from there, and encamped on the side of the Arnon"),
        ("אֲשֶׁר בַּמִּדְבָּר הַיֹּצֵא מִגְּבֻל הָאֱמֹרִי",
         "אלד'י פי אלברייה. אלכ'ארג ען תכ'ם אלאמוריין",
         "which is in the wilderness, that goes out beyond the border of the Amorites"),
        ("כִּי אַרְנוֹן גְּבוּל מוֹאָב בֵּין מוֹאָב וּבֵין הָאֱמֹרִי",
         "לאן ארנון פי תח'ם מואב בין מואב ובין אלאמורי",
         "for the Arnon is on the border of Moab, between Moab and the Amorite."),
    ],
    14: [
        ("עַל-כֵּן יֵאָמַר בְּסֵפֶר מִלְחֲמֹת יְהוָה",
         "לדא'לך יקאל. פי כתאב פתוח אללה",
         "Therefore it is said in the Book of the Conquests of God"),
        ("אֶת-וָהֵב בְּסוּפָה וְאֶת-הַנְּחָלִים אַרְנוֹן",
         "מן אלדראדר אלקלזם. ומן אלאודיה פארנון",
         "'From the whirlpools of Qulzum, and from the valleys — even Arnon;"),
    ],
    15: [
        ("וְאֶשֶׁד הַנְּחָלִים אֲשֶׁר נָטָה לְשֶׁבֶת עָר",
         "ומצב אלאודיה. אלד'י מאילה אלי' עמארה' ער",
         "and the outflow of the valleys, which inclines toward the inhabited place of Ar"),
        ("וְנִשְׁעַן לִגְבוּל מוֹאָב", "ומסנדה אלי' ת'כם מואב",
         "and leans upon the border of Moab.'"),
    ],
    16: [
        ("וּמִשָּׁם בְּאֵרָה הִוא הַבְּאֵר", "ורחלו מן ת'ם אלי' אלביר",
         "And they journeyed from there to the well"),
        ("אֲשֶׁר אָמַר יְהוָה לְמֹשֶׁה", "אלת'י קאל אללה למוסי' ענהא",
         "of which God had said to Moses"),
        ("אֱסֹף אֶת-הָעָם וְאֶתְּנָה לָהֶם מָיִם", "אגמע אלקום. חתי' אעטיהם מאא",
         "'Gather the people, that I may give them water.'"),
    ],
    17: [
        ("אָז יָשִׁיר יִשְׂרָאֵל אֶת-הַשִּׁירָה הַזֹּאת",
         "חיניד' אנשא אל אסראיל. הד'א אלאנשא",
         "Then the house of Israel sang this song"),
        ("עֲלִי בְאֵר עֱנוּ-לָהּ", "וקאלו. אצעדי יא ביר תגאובו להא",
         "and said: 'Rise up, O well!' — and they respond to it."),
    ],
    18: [
        ("בְּאֵר חֲפָרוּהָ שָׂרִים כָּרוּהָ נְדִיבֵי הָעָם",
         "ביר חפרוא אלרויסא. וכראהא נבל אלקום",
         "'A well which the chiefs dug, which the nobles of the people hollowed out"),
        ("בִּמְחֹקֵק בְּמִשְׁעֲנֹתָם", "רסמוהא בוכאיאתהם", "marked with their staffs.'"),
        ("וּמִמִּדְבָּר מַתָּנָה", "ת'ם רחלו מן תלך אלברייה אלי' ד'את אלעטא",
         "Then they journeyed from that wilderness to the place of bestowal."),
    ],
    19: [
        ("וּמִמַּתָּנָה נַחֲלִיאֵל", "ומן ד'את אלעטא אלי' אלואד אלאלי",
         "And from the place of bestowal to the central valley"),
        ("וּמִנַּחֲלִיאֵל בָּמוֹת", "ומן ד'אלך אלואד אלי' ד'את אלכנאיס",
         "and from that valley to the place of the assemblies."),
    ],
    20: [
        ("וּמִבָּמוֹת הַגַּיְא אֲשֶׁר בִּשְׂדֵה מוֹאָב",
         "ומן ת'ם. אלי' אלואד אלד'י פי בלד מואב",
         "And from there to the valley that is in the land of Moab"),
        ("רֹאשׁ הַפִּסְגָּה וְנִשְׁקָפָה עַל-פְּנֵי הַיְשִׁימֹן",
         "ענד ראס אלקלעה. אלמטלעה עלא וגה אלסמאוא",
         "by the summit of the fortress that overlooks the face of the open waste."),
    ],
    21: [
        ("וַיִּשְׁלַח יִשְׂרָאֵל מַלְאָכִים אֶל-סִיחֹן מֶלֶךְ-הָאֱמֹרִי",
         "ת'ם בעת' אל אסראיל ברסל. אלי' סיחון מלך אלאמוריין",
         "Then the house of Israel sent messengers to Sihon king of the Amorites"),
        ("לֵאמֹר", "קאילא", "saying:"),
    ],
    22: [
        ("אֶעְבְּרָה בְאַרְצֶךָ", "אריד אן אגוז פי בלדך",
         "'I wish to pass through your land"),
        ("לֹא נִטֶּה בְּשָׂדֶה וּבְכֶרֶם", "וליסנא נמיל אלי' צ'יעה ולא כרם",
         "and we shall not turn aside to any farm or vineyard"),
        ("לֹא נִשְׁתֶּה מֵי בְאֵר", "ולא נשרב מא צהריג",
         "nor shall we drink water from a cistern"),
        ("בְּדֶרֶךְ הַמֶּלֶךְ נֵלֵךְ עַד אֲשֶׁר-נַעֲבֹר גְּבֻלֶךָ",
         "בל פי אלטריק אלגאדה נסיר. אלי' אן נגוז תכ'מך",
         "but we shall travel by the broad road, until we pass through your border.'"),
    ],
    23: [
        ("וְלֹא-נָתַן סִיחֹן אֶת-יִשְׂרָאֵל עֲבֹר בִּגְבֻלוֹ",
         "ולם ידע סיחון בני אסראיל אן יגוזו פי תכ'מה",
         "But Sihon would not allow the sons of Israel to pass through his border"),
        ("וַיֶּאֱסֹף סִיחֹן אֶת-כָּל-עַמּוֹ", "פגמע גמיע קומה",
         "and he gathered all his people"),
        ("וַיֵּצֵא לִקְרַאת יִשְׂרָאֵל הַמִּדְבָּרָה", "וכ'רג תלקאהם אלי' אלברייה",
         "and went out to meet them into the wilderness"),
        ("וַיָּבֹא יָהְצָה וַיִּלָּחֶם בְּיִשְׂרָאֵל",
         "חתא ואפא יהץ. פחארבהם",
         "until he reached Jahaz; and he fought against them."),
    ],
    24: [
        ("וַיַּכֵּהוּ יִשְׂרָאֵל לְפִי-חָרֶב", "פקתלוה בחד אלסיף",
         "And they slew him with the edge of the sword"),
        ("וַיִּירַשׁ אֶת-אַרְצוֹ מֵאַרְנֹן עַד-יַבֹּק עַד-בְּנֵי עַמּוֹן",
         "וחאזו בלדה מן ארנון. אלי' יבוק אלי' בני עמון",
         "and took possession of his land from Arnon to Jabbok, as far as the sons of Ammon"),
        ("כִּי עַז גְּבוּל בְּנֵי עַמּוֹן", "אד' כאן תכ'מהם שדידא עלי'ה",
         "for the border of the sons of Ammon was strong and high."),
    ],
    25: [
        ("וַיִּקַּח יִשְׂרָאֵל אֵת כָּל-הֶעָרִים הָאֵלֶּה",
         "פאכ'דו גמיע הד'ה אלקרא",
         "And they took all these towns"),
        ("וַיֵּשֶׁב יִשְׂרָאֵל בְּכָל-עָרֵי הָאֱמֹרִי בְּחֶשְׁבּוֹן וּבְכָל-בְּנֹתֶיהָ",
         "וסכנו פי גמיע קרא אלאמוריין. פי חשבון ורסאתיקהא",
         "and settled in all the towns of the Amorites — in Heshbon and its surrounding districts."),
    ],
    26: [
        ("כִּי חֶשְׁבּוֹן--עִיר סִיחֹן מֶלֶךְ הָאֱמֹרִי הִוא",
         "וד'אלך אן חשבון. הי מנבר סיחון מלך אלאמוריין",
         "For Heshbon is the seat of Sihon king of the Amorites"),
        ("וְהוּא נִלְחַם בְּמֶלֶךְ מוֹאָב הָרִאשׁוֹן",
         "והו כאן קד חארב מלך מואב אלאוול",
         "and he had fought against the former king of Moab"),
        ("וַיִּקַּח אֶת-כָּל-אַרְצוֹ מִיָּדוֹ עַד-אַרְנֹן",
         "פ'אכ'ד' גמיע בלדה. מן ידה אלי' ארנון",
         "and taken all his land from his hand as far as Arnon."),
    ],
    27: [
        ("עַל-כֵּן יֹאמְרוּ הַמֹּשְׁלִים", "ולד'אלך יקולון אלממת'לין",
         "Therefore those who speak in parables say"),
        ("בֹּאוּ חֶשְׁבּוֹן תִּבָּנֶה וְתִכּוֹנֵן עִיר סִיחוֹן",
         "אדכלו אלי' חשבון חתי' תבנא ותהייא קריה' סיחון",
         "'Enter Heshbon, that the town of Sihon may be built and established.'"),
    ],
    28: [
        ("כִּי-אֵשׁ יָצְאָה מֵחֶשְׁבּוֹן לֶהָבָה מִקִּרְיַת סִיחֹן",
         "לאן נארא כ'רגת מן חשבון. ולהיב מן קריה' סיחון",
         "'For a fire went out from Heshbon, and a flame from the town of Sihon"),
        ("אָכְלָה עָר מוֹאָב בַּעֲלֵי בָּמוֹת אַרְנֹן",
         "פאכלת ער מואב. ואצחאב ביאע ארנון",
         "it consumed Ar of Moab, and the lords of the marketplaces of Arnon.'"),
    ],
    29: [
        ("אוֹי-לְךָ מוֹאָב", "פוילך יא מואב", "'Woe to you, O Moab!"),
        ("אָבַדְתָּ עַם-כְּמוֹשׁ", "כיף בדת יא עבדת כמוש",
         "How you are undone, O worshippers of Chemosh!"),
        ("נָתַן בָּנָיו פְּלֵיטִם וּבְנֹתָיו בַּשְּׁבִית",
         "לקד געל בניה אסארא ובנאתה סביא",
         "He has made his sons captives and his daughters taken prisoner"),
        ("לְמֶלֶךְ אֱמֹרִי סִיחוֹן", "למלך אלאמורי סיחון",
         "— to the Amorite king Sihon.'"),
    ],
    30: [
        ("וַנִּירָם אָבַד חֶשְׁבּוֹן עַד-דִּיבֹן",
         "וזאל סימאהם מן חשבון אלי' דיבון",
         "And their mark has departed from Heshbon as far as Dibon"),
        ("וַנַּשִּׁים עַד-נֹפַח אֲשֶׁר עַד-מֵידְבָא",
         "ותוחש אלי' נופח. אלד'י ענד מידבא",
         "and desolation has spread to Nophah, which is near Medeba."),
    ],
    31: [
        ("וַיֵּשֶׁב יִשְׂרָאֵל בְּאֶרֶץ הָאֱמֹרִי",
         "ולמא אקאם אל אסראיל. פי בלד אלאמוריין",
         "And when the house of Israel settled in the land of the Amorites,"),
    ],
    32: [
        ("וַיִּשְׁלַח מֹשֶׁה לְרַגֵּל אֶת-יַעְזֵר",
         "פבעת' מוסי' בקום ירומון יעזר",
         "Moses sent people to reconnoiter Jazer"),
        ("וַיִּלְכְּדוּ בְּנֹתֶיהָ", "פפתחו רסאתיקהא", "and they captured its surrounding districts"),
        ("ויירש (וַיּוֹרֶשׁ) אֶת-הָאֱמֹרִי אֲשֶׁר-שָׁם",
         "וקרצ'ו אלאמורי אלד'י פיהא",
         "and drove out the Amorites who were in them."),
    ],
    33: [
        ("וַיִּפְנוּ וַיַּעֲלוּ דֶּרֶךְ הַבָּשָׁן", "ת'ם ולו וצעדו. טריק אלבת'נייה",
         "Then they turned and went up by the way of the Bashan"),
        ("וַיֵּצֵא עוֹג מֶלֶךְ-הַבָּשָׁן לִקְרָאתָם הוּא וְכָל-עַמּוֹ",
         "פכ'רג עוג מלך אלבת'נייה תלקאהם הו וגמיע קומה",
         "and Og king of the Bashan came out to meet them — he and all his people"),
        ("לַמִּלְחָמָה--אֶדְרֶעִי", "לאלחרב אלי' אד'ראעאת",
         "to battle, at Edrei."),
    ],
    34: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה אַל-תִּירָא אֹתוֹ",
         "פקאל אללה למוסי' לא תכ'אפה",
         "And God said to Moses: 'Do not fear him"),
        ("כִּי בְיָדְךָ נָתַתִּי אֹתוֹ וְאֶת-כָּל-עַמּוֹ וְאֶת-אַרְצוֹ",
         "פאני מסלמה פי ידך. וגמיע קומה ובלדה",
         "for I am delivering him into your hand — and all his people and his land"),
        ("וְעָשִׂיתָ לּוֹ--כַּאֲשֶׁר עָשִׂיתָ לְסִיחֹן מֶלֶךְ הָאֱמֹרִי אֲשֶׁר יוֹשֵׁב בְּחֶשְׁבּוֹן",
         "פאצנע בה. כמא צנעת. בסיחון מלך אלאמוריין. אלמקים פי חשבון",
         "Do to him as you did to Sihon king of the Amorites who dwelt in Heshbon.'"),
    ],
    35: [
        ("וַיַּכּוּ אֹתוֹ וְאֶת-בָּנָיו וְאֶת-כָּל-עַמּוֹ",
         "פקתלוה ובניה וגמיע קומה",
         "And they slew him and his sons and all his people"),
        ("עַד-בִּלְתִּי הִשְׁאִיר-לוֹ שָׂרִיד", "חתי' לם יבק לה שרידא",
         "until not a survivor remained to him"),
        ("וַיִּירְשׁוּ אֶת-אַרְצוֹ", "וחאזו בלדה", "and they took possession of his land."),
    ],
}
