"""Hand-authored alignment triples for Bamidbar chapter 6."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, a speaking."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם", "מר בני אסראיל. וקל להם",
         "Command the sons of Israel, and say to them"),
        ("אִישׁ אוֹ-אִשָּׁה כִּי יַפְלִא לִנְדֹּר נֶדֶר נָזִיר",
         "אי רגל או אמראה. סווג' נד'רא נסך",
         "Any man or woman who has deemed a vow of devotion lawful"),
        ("לְהַזִּיר לַיהוָה", "ליתנסך לרבה", "to practice devotion to his Lord"),
    ],
    3: [
        ("מִיַּיִן וְשֵׁכָר יַזִּיר", "פמן אלכ'מר ואלמסכר מנה יתנסך",
         "from wine and from what is intoxicating he shall practice devotion"),
        ("חֹמֶץ יַיִן וְחֹמֶץ שֵׁכָר לֹא יִשְׁתֶּה", "חתא כ'ל כ'מר. וכ'ל מ'סכר לא ישרב",
         "such that even vinegar of wine and vinegar of an intoxicating drink he shall not drink"),
        ("וְכָל-מִשְׁרַת עֲנָבִים לֹא יִשְׁתֶּה", "וכל נקיע אלענב לא ישרב",
         "and every infusion of grapes he shall not drink"),
        ("וַעֲנָבִים לַחִים וִיבֵשִׁים לֹא יֹאכֵל", "וענבא רטבא ויאבסא לא יאכל",
         "and grapes, fresh or dried, he shall not eat."),
    ],
    4: [
        ("כֹּל יְמֵי נִזְרוֹ", "טול אייאם נסכה", "All the days of his devotion"),
        ("מִכֹּל אֲשֶׁר יֵעָשֶׂה מִגֶּפֶן הַיַּיִן", "מן כל מא יעמל מן גפן אלכ'מר",
         "from everything made from the vine of wine"),
        ("מֵחַרְצַנִּים וְעַד-זָג--לֹא יֹאכֵל", "מן אלפרצן אלי' אלזג לא יאכל",
         "from the seeds to the skin surrounding it — he shall not eat."),
    ],
    5: [
        ("כָּל-יְמֵי נֶדֶר נִזְרוֹ", "וטול אייאם נד'ר נסכה",
         "And all the days of the vow of his devotion"),
        ("תַּעַר לֹא-יַעֲבֹר עַל-רֹאשׁוֹ", "לא ימר חאלק עלי' ראסה",
         "no razor shall pass over his head"),
        ("עַד-מְלֹאת הַיָּמִם אֲשֶׁר-יַזִּיר לַיהוָה",
         "אלי' אן תתם אלאייאם. אלתי תנסכהא לרבה",
         "until the days he devotes to his Lord are complete"),
        ("קָדֹשׁ יִהְיֶה--גַּדֵּל פֶּרַע שְׂעַר רֹאשׁוֹ", "יכון מקדסא. וירבי פרע שער ראסה",
         "he shall be consecrated, and shall grow out the branch of the hair of his head."),
    ],
    6: [
        ("כָּל-יְמֵי הַזִּירוֹ לַיהוָה", "כד'אך טול אייאם נסכה ללה",
         "Likewise, all the days of his devotion to God"),
        ("עַל-נֶפֶשׁ מֵת לֹא יָבֹא", "אלי' חצ'רה מיית לא ידכ'ל",
         "he shall not enter into the presence of a dead person."),
    ],
    7: [
        ("לְאָבִיו וּלְאִמּוֹ לְאָחִיו וּלְאַחֹתוֹ", "חתא באביה ואמה. ואכ'יה וא'כ'תה",
         "Not even for his father or his mother, his brother or his sister"),
        ("לֹא-יִטַּמָּא לָהֶם בְּמֹתָם", "לא יתנגס בהם פי חאל מותהם",
         "he shall not defile himself through them at the time of their death"),
        ("כִּי נֵזֶר אֱלֹהָיו עַל-רֹאשׁוֹ", "לאן נסך רבה עלי'ה",
         "because the devotion to his Lord is upon him."),
    ],
    8: [
        ("כֹּל יְמֵי נִזְרוֹ", "כד'אך טול אייאם נסכה",
         "Likewise, all the days of his devotion"),
        ("קָדֹשׁ הוּא לַיהוָה", "מקדס הו לרבה", "he is consecrated to his Lord."),
    ],
    10: [
        ("וּבַיּוֹם הַשְּׁמִינִי", "ופי אליום אלתאמן", "And on the eighth day"),
        ("יָבִא שְׁתֵּי תֹרִים אוֹ שְׁנֵי בְּנֵי יוֹנָה אֶל-הַכֹּהֵן",
         "יאתי בשפנינין. או פרכ'י חמאם. אלי' אלאמאם",
         "he shall bring two sparrows or two young pigeons to the imām"),
        ("אֶל-פֶּתַח אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר",
         "to the entrance of the tent of the assembly."),
    ],
    11: [
        ("וְעָשָׂה הַכֹּהֵן אֶחָד לְחַטָּאת וְאֶחָד לְעֹלָה",
         "ויעמל אחדהמא ד'כוה. ואלאכ'ר צעידה",
         "And he shall make one of them a purification-offering, and the other a burnt-offering"),
        ("וְכִפֶּר עָלָיו מֵאֲשֶׁר חָטָא עַל-הַנָּפֶשׁ",
         "ויסתג'פר ענה. במא אכ'טא פי אמר מיית",
         "and he shall seek forgiveness for him for what he erred in the matter of the dead person"),
        ("וְקִדַּשׁ אֶת-רֹאשׁוֹ בַּיּוֹם הַהוּא", "ויקדס ראסה פי ד'אלך אלוקת",
         "and his head shall be consecrated at that time."),
    ],
    12: [
        ("וְהִזִּיר לַיהוָה אֶת-יְמֵי נִזְרוֹ", "ויתנסך ללה אייאם נסכה",
         "And he shall practice devotion to God for the days of his devotion"),
        ("וְהֵבִיא כֶּבֶשׂ בֶּן-שְׁנָתוֹ לְאָשָׁם", "ויאתי. בחמל אבן סנתה לקרבאן אלאתם",
         "and shall bring a lamb in its first year as a guilt-offering"),
        ("וְהַיָּמִים הָרִאשֹׁנִים יִפְּלוּ", "ואלאייאם אלמתקדמה תסקט",
         "and the preceding days shall lapse"),
        ("כִּי טָמֵא נִזְרוֹ", "למא אנקטע נסכה", "for his devotion was interrupted."),
    ],
    13: [
        ("וְזֹאת תּוֹרַת הַנָּזִיר", "והד'ה שריעה' אלנאסך",
         "And this is the law of the devotee"),
        ("בְּיוֹם מְלֹאת יְמֵי נִזְרוֹ", "פי יום כמאל אייאם נסכה",
         "on the day of the completion of the days of his devotion"),
        ("יָבִיא אֹתוֹ אֶל-פֶּתַח אֹהֶל מוֹעֵד", "יאתי בה. אלי' באב כ'בא אלמחצ'ר",
         "he shall bring him to the entrance of the tent of the assembly."),
    ],
    14: [
        ("וְהִקְרִיב אֶת-קָרְבָּנוֹ לַיהוָה", "פיקרב קרבאנה ללה",
         "And he shall present his offering to God"),
        ("כֶּבֶשׂ בֶּן-שְׁנָתוֹ תָמִים אֶחָד לְעֹלָה",
         "חמלא אבן סנתה צחיחא לאלצעידה",
         "a lamb in its first year, unblemished, for the burnt-offering"),
        ("וְכַבְשָׂה אַחַת בַּת-שְׁנָתָהּ תְּמִימָה לְחַטָּאת",
         "ורכ'לה אבנה' סנתהא. צחיחה לאלדכוה",
         "and a ewe-lamb in its first year, unblemished, for the purification-offering"),
        ("וְאַיִל-אֶחָד תָּמִים לִשְׁלָמִים", "וכבשא צחיחא לד'בח אלסלאמה",
         "and a ram, unblemished, for the peace-offering."),
    ],
    15: [
        ("וְסַל מַצּוֹת סֹלֶת חַלֹּת בְּלוּלֹת בַּשֶּׁמֶן",
         "וסלה' פטיר. גראדק סמד מלתותה בדהן",
         "And a basket of unleavened bread — loaves of fine flour kneaded with oil"),
        ("וּרְקִיקֵי מַצּוֹת מְשֻׁחִים בַּשָּׁמֶן", "ורקאק פטיר ממסוחה בדהן",
         "and wafers of unleavened bread anointed with oil"),
        ("וּמִנְחָתָם וְנִסְכֵּיהֶם", "ואלבר ואלמזאג אלד'י מעהא",
         "and the grain-offering and the libation that goes with them."),
    ],
    16: [
        ("וְהִקְרִיב הַכֹּהֵן לִפְנֵי יְהוָה", "ויקדמהא אלאמאם בין ידי אללה",
         "And the imām shall present them before God"),
        ("וְעָשָׂה אֶת-חַטָּאתוֹ וְאֶת-עֹלָתוֹ", "ויצנע דכותה וצעידתה",
         "and shall make his purification-offering and his burnt-offering."),
    ],
    17: [
        ("וְאֶת-הָאַיִל יַעֲשֶׂה זֶבַח שְׁלָמִים לַיהוָה עַל סַל הַמַּצּוֹת",
         "ואלכבש. יצנעה ד'בח סלאמה ללה. מע סלה' אלפטיר",
         "And the ram he shall make a peace-offering to God, together with the basket of unleavened bread"),
        ("וְעָשָׂה הַכֹּהֵן אֶת-מִנְחָתוֹ וְאֶת-נִסְכּוֹ",
         "ת'ם יצנע אלבר ואלמזאג אלד'י מעה",
         "then he shall make the grain-offering and the libation that goes with it."),
    ],
    18: [
        ("וְגִלַּח הַנָּזִיר פֶּתַח אֹהֶל מוֹעֵד--אֶת-רֹאשׁ נִזְרוֹ",
         "ויחלק אלנאסך. ענד באב כ'בא אלמחצ'ר שער ראסה",
         "And the devotee shall shave the hair of his head at the entrance of the tent of the assembly"),
        ("וְלָקַח אֶת-שְׂעַר רֹאשׁ נִזְרוֹ", "ויאכ'דה", "and shall take it"),
        ("וְנָתַן עַל-הָאֵשׁ אֲשֶׁר-תַּחַת זֶבַח הַשְּׁלָמִים",
         "וילקי עלי' אלנאר. אלד'י תחת ד'בח אלסלאמה",
         "and cast it upon the fire that is under the peace-offering."),
    ],
    19: [
        ("וְלָקַח הַכֹּהֵן אֶת-הַזְּרֹעַ בְּשֵׁלָה מִן-הָאַיִל",
         "ויאכ'ד אלאמאם. אלד'ראע מטבוכ'ה מן ד'אלך אלכבש",
         "And the imām shall take the cooked foreleg from that ram"),
        ("וְחַלַּת מַצָּה אַחַת מִן-הַסַּל וּרְקִיק מַצָּה אֶחָד",
         "וגרדקה ואחדה מן אלפטיר. ורקאקה ואחדה",
         "and one loaf from the unleavened bread, and one wafer"),
        ("וְנָתַן עַל-כַּפֵּי הַנָּזִיר אַחַר הִתְגַּלְּחוֹ אֶת-נִזְרוֹ",
         "ויצ'ע ד'אלך עלי' כפי אלנאסך. בעד חלקה שער ראסה",
         "and shall place them upon the palms of the devotee after he has shaved the hair of his head."),
    ],
    20: [
        ("וְהֵנִיף אוֹתָם הַכֹּהֵן תְּנוּפָה לִפְנֵי יְהוָה",
         "ויחרך אלגמיע תחריכא בין ידי אללה",
         "And he shall wave all of it as a waving before God"),
        ("קֹדֶשׁ הוּא לַכֹּהֵן עַל חֲזֵה הַתְּנוּפָה וְעַל שׁוֹק הַתְּרוּמָה",
         "וליכון מקדסא לאלאמאם. מע קץ אלתחריך. וסאק אלרפיעה",
         "and it shall be consecrated for the imām, together with the breast of waving and the thigh of the raised-offering"),
        ("וְאַחַר יִשְׁתֶּה הַנָּזִיר יָיִן", "ובעד ד'אלך ישרב אלנאסך כ'מר",
         "and after that the devotee may drink wine."),
    ],
    21: [
        ("זֹאת תּוֹרַת הַנָּזִיר אֲשֶׁר יִדֹּר קָרְבָּנוֹ לַיהוָה עַל-נִזְרוֹ",
         "הד'ה שריעה' אלנאסך. קרבאנה ללה ען נסכה",
         "This is the law of the devotee — his offering to God on account of his devotion"),
        ("מִלְּבַד אֲשֶׁר-תַּשִּׂיג יָדוֹ", "סוא מא תנאל ידה",
         "apart from what his hand may obtain"),
        ("כְּפִי נִדְרוֹ אֲשֶׁר יִדֹּר--כֵּן יַעֲשֶׂה עַל תּוֹרַת נִזְרוֹ",
         "וליכון ד'אלך כמקדאר מד'ה נסכה. יצ'מה אלי' שריעה' אלנסך",
         "and let that be in proportion to the period of his devotion, which he shall add to the law of devotion."),
    ],
    22: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם מוסי' תכלימא",
         "Then God spoke to Moses, a speaking."),
    ],
    23: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאֶל-בָּנָיו לֵאמֹר", "מר הרון ובניה וקל להם",
         "Command Aaron and his sons and say to them"),
        ("כֹּה תְבָרְכוּ אֶת-בְּנֵי יִשְׂרָאֵל", "כד'י' פבארכו בני אסראיל",
         "Thus shall you bless the sons of Israel"),
        ("אָמוֹר לָהֶם", "מקוולא להם", "reciting to them"),
    ],
    24: [
        ("יְבָרֶכְךָ יְהוָה", "יבארכך אללה", "May God bless you"),
        ("וְיִשְׁמְרֶךָ", "ויחפצ'ך", "and keep you."),
    ],
    25: [
        ("יָאֵר יְהוָה פָּנָיו אֵלֶיךָ", "ויצ'י וגהה אליך",
         "And may He make His face shine toward you"),
        ("וִיחֻנֶּךָּ", "וירופך", "and show you compassion."),
    ],
    26: [
        ("יִשָּׂא יְהוָה פָּנָיו אֵלֶיךָ", "ויקבל בקצדה אליך",
         "And may He turn with His purpose toward you"),
        ("וְיָשֵׂם לְךָ שָׁלוֹם", "ויצייר לך אלסלאם", "and grant you peace."),
    ],
    27: [
        ("וְשָׂמוּ אֶת-שְׁמִי עַל-בְּנֵי יִשְׂרָאֵל", "פליתלו אסמי עלי' בני אסראיל",
         "So that they recite My name over the sons of Israel"),
        ("וַאֲנִי אֲבָרְכֵם", "ואנא אבארך עלי'הם", "and I shall bless them."),
    ],
}
