"""Hand-authored alignment triples for Bamidbar chapter 28."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly"),
    ],
    2: [
        ("צַו אֶת-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל. וקל להם",
         "Command the sons of Israel, and say to them"),
        ("אֶת-קָרְבָּנִי לַחְמִי לְאִשַּׁי", "קרבאני דאימי מרצ'יי מקבולי",
         "My offering — continual, pleasing, accepted"),
        ("תִּשְׁמְרוּ לְהַקְרִיב לִי בְּמוֹעֲדוֹ", "אחפצוה. אן תקרבוה לי פי וקתה",
         "take care to bring it to Me in its appointed time"),
    ],
    3: [
        ("וְאָמַרְתָּ לָהֶם--זֶה הָאִשֶּׁה אֲשֶׁר תַּקְרִיבוּ לַיהוָה",
         "וביין להם. אן אלמרצ'י. אלד'י תקרבונה ללה",
         "And make clear to them that the pleasing offering which you bring to God"),
        ("כְּבָשִׂים בְּנֵי-שָׁנָה תְמִימִם שְׁנַיִם לַיּוֹם", "חמלין אבני סנה צחאחא. פי כל יום",
         "is two yearling male lambs without blemish — each day"),
        ("עֹלָה תָמִיד", "צעידה דאימא", "an offering, continually"),
    ],
    4: [
        ("אֶת-הַכֶּבֶשׂ אֶחָד תַּעֲשֶׂה בַבֹּקֶר", "אחדהמא באלג'דאה",
         "One of them in the morning"),
        ("וְאֵת הַכֶּבֶשׂ הַשֵּׁנִי תַּעֲשֶׂה בֵּין הָעַרְבָּיִם", "ואלאכ'ר בין אלג'רובין",
         "and the other between the two settings"),
    ],
    5: [
        ("וַעֲשִׂירִית הָאֵיפָה סֹלֶת לְמִנְחָה", "ועשר ויבה. סמד מן אלבר",
         "And a tenth of a waybah of fine wheat flour"),
        ("בְּלוּלָה בְּשֶׁמֶן כָּתִית רְבִיעִת הַהִין", "מלתות. ברבע קסט מן דהן מטחון",
         "mixed, with a quarter of a qist of pressed oil"),
    ],
    6: [
        ("עֹלַת תָּמִיד--הָעֲשֻׂיָה בְּהַר סִינַי", "צעידה דאימא. כמא צנעת פי ברייה' סיני",
         "A continual offering, as was done in the wilderness of Sinai"),
        ("לְרֵיחַ נִיחֹחַ אִשֶּׁה לַיהוָה", "מקבולה מרצ'ייה ללה",
         "accepted and pleasing to God"),
    ],
    7: [
        ("וְנִסְכּוֹ רְבִיעִת הַהִין לַכֶּבֶשׂ הָאֶחָד", "ומעה מן אלמזאג. רבע קסט לכל חמל",
         "And with it, from the mixed drink, a quarter of a qist for each lamb"),
        ("בַּקֹּדֶשׁ הַסֵּךְ נֶסֶךְ שֵׁכָר--לַיהוָה", "ירש פי אלקדס רשא. מן עתיקה ללה",
         "to be poured in the sanctuary, a pouring from its aged kind, to God"),
    ],
    8: [
        ("וְאֵת הַכֶּבֶשׂ הַשֵּׁנִי תַּעֲשֶׂה בֵּין הָעַרְבָּיִם",
         "ואד'א צנעת אלחמל אלת'אני בין אלג'רובין",
         "And when you make the second lamb between the two settings"),
        ("כְּמִנְחַת הַבֹּקֶר וּכְנִסְכּוֹ תַּעֲשֶׂה", "פכהדייה' אלג'דאה ומזאגהא איצ'א אצנעה",
         "make it like the gift of the morning and its mixed drink as well"),
        ("אִשֵּׁה רֵיחַ נִיחֹחַ לַיהוָה", "קרבאנא מקבולא מרצ'ייא ללה",
         "an offering accepted and pleasing to God"),
    ],
    9: [
        ("וּבְיוֹם הַשַּׁבָּת--שְׁנֵי-כְבָשִׂים בְּנֵי-שָׁנָה תְּמִימִם",
         "ופי יום אלסבת. חמלין אבני סנה צחאצא",
         "And on the Sabbath day: two yearling male lambs without blemish"),
        ("וּשְׁנֵי עֶשְׂרֹנִים סֹלֶת מִנְחָה בְּלוּלָה בַשֶּׁמֶן--וְנִסְכּוֹ",
         "ומעהמא מן אלבר עשרין. סמד מלתות בדהן ומזאגהם",
         "and with them two tenths of fine wheat flour mixed with oil, and their mixed drink"),
    ],
    10: [
        ("עֹלַת שַׁבַּת בְּשַׁבַּתּוֹ", "ד'אלך קרבאן סבת בסבת",
         "That is the offering of Sabbath by Sabbath"),
        ("עַל-עֹלַת הַתָּמִיד וְנִסְכָּהּ", "מע אלקרבאן אלדאים ומזאגה",
         "together with the continual offering and its mixed drink"),
    ],
    11: [
        ("וּבְרָאשֵׁי חָדְשֵׁיכֶם--תַּקְרִיבוּ עֹלָה לַיהוָה",
         "ופי רוס שהורכם. קרבו קרבאן צעידה ללה",
         "And at the heads of your months, bring an offering — a burnt-offering to God"),
        ("פָּרִים בְּנֵי-בָקָר שְׁנַיִם וְאַיִל אֶחָד", "רת'ין מן אלבקר וכבשא",
         "two bulls from the cattle, and a ram"),
        ("כְּבָשִׂים בְּנֵי-שָׁנָה שִׁבְעָה תְּמִימִם", "וסבעה' חמלאן בני סנה צחאחא",
         "and seven yearling lambs without blemish"),
    ],
    12: [
        ("וּשְׁלֹשָׁה עֶשְׂרֹנִים סֹלֶת מִנְחָה בְּלוּלָה בַשֶּׁמֶן לַפָּר הָאֶחָד",
         "ות'לאת'ה' עשור מן אלבר. סמד מלתות בדהן לכל רת'",
         "And three tenths of fine wheat flour mixed with oil for each bull"),
        ("וּשְׁנֵי עֶשְׂרֹנִים סֹלֶת מִנְחָה בְּלוּלָה בַשֶּׁמֶן לָאַיִל הָאֶחָד",
         "ועשרין לאלכבש",
         "and two tenths for the ram"),
    ],
    13: [
        ("וְעִשָּׂרֹן עִשָּׂרוֹן סֹלֶת מִנְחָה בְּלוּלָה בַשֶּׁמֶן לַכֶּבֶשׂ הָאֶחָד",
         "ועשר לכל חמל כד'אך",
         "And a tenth of fine flour mixed with oil for each lamb likewise"),
        ("עֹלָה רֵיחַ נִיחֹחַ אִשֶּׁה לַיהוָה", "אלצעידה אלמקבולה אלמרצ'ייה ללה",
         "an offering accepted and pleasing to God"),
    ],
    14: [
        ("וְנִסְכֵּיהֶם חֲצִי הַהִין יִהְיֶה לַפָּר", "ומזאגהם. יכון נצף קסט לכל ת'ור",
         "And their mixed drink shall be: half a qist for each bull"),
        ("וּשְׁלִישִׁת הַהִין לָאַיִל", "ות'לת' קסט לאלכבש", "and a third of a qist for the ram"),
        ("וּרְבִיעִת הַהִין לַכֶּבֶשׂ--יָיִן", "ורבע קסט. לאלחמל מן אלשראב",
         "and a quarter of a qist for the lamb — from the drink"),
        ("זֹאת עֹלַת חֹדֶשׁ בְּחָדְשׁוֹ לְחָדְשֵׁי הַשָּׁנָה",
         "הד'א קרבאן שהר בשהר. לשהור אלסנה",
         "This is the offering of month by month, for the months of the year"),
    ],
    15: [
        ("וּשְׂעִיר עִזִּים אֶחָד לְחַטָּאת לַיהוָה", "ועתוד מן אלמאעז ד'כוה ללה",
         "And a male goat-kid as a purification-offering to God"),
        ("עַל-עֹלַת הַתָּמִיד יֵעָשֶׂה וְנִסְכּוֹ", "מע קרבאן אלדאים. יקרב ד'אלך ומזאגה",
         "together with the continual offering, that shall be brought, with its mixed drink"),
    ],
    16: [
        ("וּבַחֹדֶשׁ הָרִאשׁוֹן בְּאַרְבָּעָה עָשָׂר יוֹם--לַחֹדֶשׁ פֶּסַח לַיהוָה",
         "ופי אלשהר אלאוול. פי אליום אלראבע עשר מנה. פסחא ללה",
         "And in the first month, on the fourteenth day of it — a Passover to God"),
    ],
    17: [
        ("וּבַחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הַזֶּה חָג", "ופי אליום אלכ'אמס עשר מנה חג",
         "And on the fifteenth day of it, a pilgrimage-festival"),
        ("שִׁבְעַת יָמִים מַצּוֹת יֵאָכֵל", "סבעה' אייאם יוכל פטירא",
         "seven days shall unleavened bread be eaten"),
    ],
    18: [
        ("בַּיּוֹם הָרִאשׁוֹן מִקְרָא-קֹדֶשׁ", "פי אליום אלאוול מנהא אסם מקדס",
         "On the first day of it — a consecrated name"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ", "כל צנעה' מכסב לא תעמלו",
         "no work for gain shall you do"),
    ],
    19: [
        ("וְהִקְרַבְתֶּם אִשֶּׁה עֹלָה לַיהוָה", "וקרבו קרבאנא צעידה ללה",
         "And bring an offering — a burnt-offering to God"),
        ("פָּרִים בְּנֵי-בָקָר שְׁנַיִם וְאַיִל אֶחָד", "רת'ין מן אלבקר וכבשא",
         "two bulls from the cattle, and a ram"),
        ("וְשִׁבְעָה כְבָשִׂים בְּנֵי שָׁנָה תְּמִימִם יִהְיוּ לָכֶם",
         "וסבעה חמלאן בני סנה. צחאחא יכונאן לכם",
         "and seven yearling lambs; they shall be without blemish for you"),
    ],
    20: [
        ("וּמִנְחָתָם--סֹלֶת בְּלוּלָה בַשָּׁמֶן", "ומעהם מן אלבר. סמד מלתות בדהן",
         "And with them from the grain: fine flour mixed with oil"),
        ("שְׁלֹשָׁה עֶשְׂרֹנִים לַפָּר וּשְׁנֵי עֶשְׂרֹנִים לָאַיִל--תַּעֲשׂוּ",
         "ת'לאת'ה' עשור לכל רת' ועשרין לאלכבש",
         "three tenths for each bull, and two tenths for the ram"),
    ],
    21: [
        ("עִשָּׂרוֹן עִשָּׂרוֹן תַּעֲשֶׂה לַכֶּבֶשׂ הָאֶחָד--לְשִׁבְעַת הַכְּבָשִׂים",
         "ועשר לכל חמל מן אלסבעה",
         "And a tenth for each lamb from the seven"),
    ],
    22: [
        ("וּשְׂעִיר חַטָּאת אֶחָד לְכַפֵּר עֲלֵיכֶם", "ועתוד לאלד'כוה. ליסתג'פר ענכם",
         "And a male goat-kid for the purification-offering, to seek forgiveness for you"),
    ],
    23: [
        ("מִלְּבַד עֹלַת הַבֹּקֶר אֲשֶׁר לְעֹלַת הַתָּמִיד", "מא כ'לא קרבאן אלג'דאה. וקרבאן אלדאים אלת'אני",
         "Apart from the morning offering and the second continual offering"),
        ("תַּעֲשׂוּ אֶת-אֵלֶּה", "תקרבו הד'ה", "these you shall bring"),
    ],
    24: [
        ("כָּאֵלֶּה תַּעֲשׂוּ לַיּוֹם שִׁבְעַת יָמִים",
         "ומת'להא קרבו פי כל יום מן אלסבעה אלאייאם",
         "And the like of it bring on each day of the seven days"),
        ("לֶחֶם אִשֵּׁה רֵיחַ-נִיחֹחַ לַיהוָה", "קרבאנא מקבולא מרצ'ייא ללה",
         "an offering accepted and pleasing to God"),
        ("עַל-עוֹלַת הַתָּמִיד יֵעָשֶׂה וְנִסְכּוֹ", "מע אלקרבאן אלדאים. יקרב ד'אלך ומזאגה",
         "together with the continual offering, that shall be brought, with its mixed drink"),
    ],
    25: [
        ("וּבַיּוֹם הַשְּׁבִיעִי--מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם",
         "ופי אליום אלסאבע. אסם מקדס יכון לכם",
         "And on the seventh day — a consecrated name shall be for you"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ", "כל צנעה' מכסב לא תעמלו",
         "no work for gain shall you do"),
    ],
    26: [
        ("וּבְיוֹם הַבִּכּוּרִים בְּהַקְרִיבְכֶם מִנְחָה חֲדָשָׁה לַיהוָה",
         "ופי יום אלבכור. פי תקריבכם. ברא גדידא ללה",
         "And on the day of first-fruits, when you bring a new grain-offering to God"),
        ("בְּשָׁבֻעֹתֵיכֶם מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם", "בעד אסאביעכם אסם מקדס יכון לכם",
         "after your weeks — a consecrated name shall be for you"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ", "כל צנעה' מכסב לא תעמלו",
         "no work for gain shall you do"),
    ],
    27: [
        ("וְהִקְרַבְתֶּם עוֹלָה לְרֵיחַ נִיחֹחַ לַיהוָה", "וקרבו צעידה. מקבולה מרצ'ייה ללה",
         "And bring a burnt-offering, accepted and pleasing to God"),
        ("פָּרִים בְּנֵי-בָקָר שְׁנַיִם אַיִל אֶחָד שִׁבְעָה כְבָשִׂים בְּנֵי שָׁנָה",
         "ר'תין מן אלבקר וכבשא. וסבעה' חמלאן בני סנה",
         "two bulls from the cattle, and a ram, and seven yearling lambs"),
    ],
    28: [
        ("וּמִנְחָתָם--סֹלֶת בְּלוּלָה בַשָּׁמֶן", "ומעהם מן אלבר. סמד מלתות בדהן",
         "And with them from the grain: fine flour mixed with oil"),
        ("שְׁלֹשָׁה עֶשְׂרֹנִים לַפָּר הָאֶחָד שְׁנֵי עֶשְׂרֹנִים לָאַיִל הָאֶחָד",
         "ת'לאת'ה' עשור לכל רת'. ועשרין לאלכבש",
         "three tenths for each bull, and two tenths for the ram"),
    ],
    29: [
        ("עִשָּׂרוֹן עִשָּׂרוֹן לַכֶּבֶשׂ הָאֶחָד--לְשִׁבְעַת הַכְּבָשִׂים",
         "ועשר לכל חמל מן אלסבעה",
         "And a tenth for each lamb from the seven"),
    ],
    30: [
        ("שְׂעִיר עִזִּים אֶחָד לְכַפֵּר עֲלֵיכֶם", "ועתוד מן אלמאעז. ליסתג'פר ענכם",
         "And a male goat-kid from the goats, to seek forgiveness for you"),
    ],
    31: [
        ("מִלְּבַד עֹלַת הַתָּמִיד וּמִנְחָתוֹ--תַּעֲשׂוּ", "מא כ'לא קרבאן אלדאים. וברה תקרבו ד'אלך",
         "Apart from the continual offering and its grain — these you shall bring"),
        ("תְּמִימִם יִהְיוּ-לָכֶם וְנִסְכֵּיהֶם", "וצחאחא תכון לכם ומזאגהא",
         "without blemish shall they be for you, and their mixed drink"),
    ],
}
