"""Hand-authored alignment triples for Bamidbar chapter 5."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("צַו אֶת-בְּנֵי יִשְׂרָאֵל", "מר בני אסראיל", "Command the sons of Israel"),
        ("וִישַׁלְּחוּ מִן-הַמַּחֲנֶה", "באן ינפו מן אלעסכר",
         "that they drive out from the camp"),
        ("כָּל-צָרוּעַ וְכָל-זָב", "כל אברץ וכל ד'איב",
         "every leper, and every one with a discharge"),
        ("וְכֹל טָמֵא לָנָפֶשׁ", "וכל נגס במיית",
         "and every one made impure by a corpse."),
    ],
    3: [
        ("מִזָּכָר עַד-נְקֵבָה תְּשַׁלֵּחוּ", "מן ד'כר אלי' אנת'י תנפוהם",
         "From male to female you shall drive them out"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה תְּשַׁלְּחוּם", "אלי' כ'ארג אלעסכר",
         "to the outside of the camp"),
        ("וְלֹא יְטַמְּאוּ אֶת-מַחֲנֵיהֶם", "ולא ינגסו עסכרהם",
         "that they not defile their camp"),
        ("אֲשֶׁר אֲנִי שֹׁכֵן בְּתוֹכָם", "אלד'י אנא סאכנה פי מא בינהם",
         "in which I dwell among them."),
    ],
    4: [
        ("וַיַּעֲשׂוּ-כֵן בְּנֵי יִשְׂרָאֵל", "פצנע כד'אך בני אסראיל",
         "And the sons of Israel did so"),
        ("וַיְשַׁלְּחוּ אוֹתָם אֶל-מִחוּץ לַמַּחֲנֶה", "ונפוהם אלי' כ'ארג אלעסכר",
         "and drove them out to the outside of the camp"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה אֶל-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses"),
        ("כֵּן עָשׂוּ בְּנֵי יִשְׂרָאֵל", "כד'אך צנעו בני אסראיל",
         "so the sons of Israel did."),
    ],
    5: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    6: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "קל לבני אסראיל",
         "Say to the sons of Israel"),
        ("אִישׁ אוֹ-אִשָּׁה כִּי יַעֲשׂוּ מִכָּל-חַטֹּאת הָאָדָם",
         "אי רגל או אמראה. יצנע שייא מן כ'טאיא אלנאס",
         "any man or woman who does something from the sins common among people"),
        ("לִמְעֹל מַעַל בַּיהוָה", "לינכת' נכת'א באללה",
         "so as to break faith with God"),
        ("וְאָשְׁמָה הַנֶּפֶשׁ הַהִוא", "פאת'ם", "and has sinned"),
    ],
    7: [
        ("וְהִתְוַדּוּ אֶת-חַטָּאתָם אֲשֶׁר עָשׂוּ", "ת'ם יקר בכ'טייתה אלד'י צנעהא",
         "then he shall confess his wrongdoing which he committed"),
        ("וְהֵשִׁיב אֶת-אֲשָׁמוֹ בְּרֹאשׁוֹ", "פלירד אלצ'לאמה בראסהא",
         "and he shall return the wrongful taking in full"),
        ("וַחֲמִישִׁתוֹ יֹסֵף עָלָיו", "ויזיד עלי'הא כמסהא", "and add a fifth part to it"),
        ("וְנָתַן לַאֲשֶׁר אָשַׁם לוֹ", "וידפעהא אלי' מן צ'למה",
         "and pay it to the one he wronged."),
    ],
    8: [
        ("וְאִם-אֵין לָאִישׁ גֹּאֵל לְהָשִׁיב הָאָשָׁם אֵלָיו",
         "ואן לם יכון לאלמצ'לום ולי. לתרד אלצ'לאמה",
         "And if the wronged one has no next of kin to whom the wrongful taking may be returned"),
        ("הָאָשָׁם הַמּוּשָׁב לַיהוָה לַכֹּהֵן", "אלמרדודה ללה והי לאלאמאם",
         "then the wrongful taking that is returned shall be for God — it belongs to the imām"),
        ("מִלְּבַד אֵיל הַכִּפֻּרִים אֲשֶׁר יְכַפֶּר-בּוֹ עָלָיו",
         "סוא כבש אלג'פראן. אלד'י יסתג'פר בה ענה",
         "apart from the ram of atonement by which he seeks forgiveness on his behalf."),
    ],
    9: [
        ("וְכָל-תְּרוּמָה לְכָל-קָדְשֵׁי בְנֵי-יִשְׂרָאֵל",
         "וכל רפיעה. מן גמיע אקדאס בני אסראיל",
         "And every contribution from all the sacred gifts of the sons of Israel"),
        ("אֲשֶׁר-יַקְרִיבוּ לַכֹּהֵן--לוֹ יִהְיֶה", "פלאי אמאם דפעוהא כאנת לה",
         "to whichever imām they hand it, it shall be his."),
    ],
    10: [
        ("וְאִישׁ אֶת-קֳדָשָׁיו לוֹ יִהְיוּ", "וכל אמר יכון לה אמר אקדאסה",
         "And every man who has disposition over his sacred things"),
        ("אִישׁ אֲשֶׁר-יִתֵּן לַכֹּהֵן לוֹ יִהְיֶה", "לאי אמאם דפעהא כאנת לה",
         "to whichever imām he gives it, it shall be his."),
    ],
    11: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    12: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם", "מר בני אסראיל. וקל להם",
         "Command the sons of Israel and say to them"),
        ("אִישׁ אִישׁ כִּי-תִשְׂטֶה אִשְׁתּוֹ", "אי רגל חאדת זוגתה",
         "any man whose wife has gone astray"),
        ("וּמָעֲלָה בוֹ מָעַל", "פכ'אנתה כ'יאנה", "and betrayed him with a betrayal"),
    ],
    13: [
        ("וְשָׁכַב אִישׁ אֹתָהּ שִׁכְבַת-זֶרַע", "באן צ'אגעהא רגל מצאגעה' אנסאל",
         "in that a man has lain with her in a lying of emission"),
        ("וְנֶעְלַם מֵעֵינֵי אִישָׁהּ", "וג'בי ד'אלך ען זוגהא",
         "and this has been hidden from her husband"),
        ("וְנִסְתְּרָה וְהִיא נִטְמָאָה", "ואנסתרת והי נגסה",
         "and she has concealed herself while being impure"),
        ("וְעֵד אֵין בָּהּ", "ושאהד ליס עלי'הא", "and there is no witness against her"),
        ("וְהִוא לֹא נִתְפָּשָׂה", "והי לם תקהר", "and she was not forced"),
    ],
    14: [
        ("וְעָבַר עָלָיו רוּחַ-קִנְאָה וְקִנֵּא אֶת-אִשְׁתּוֹ וְהִוא נִטְמָאָה",
         "וכ'טר בבאלה ראי ג'ירה. פג'אר עלי'הא והי נגסה",
         "and a thought of jealousy has entered his mind, and he is jealous over her while she is impure"),
        ("אוֹ-עָבַר עָלָיו רוּחַ-קִנְאָה וְקִנֵּא אֶת-אִשְׁתּוֹ וְהִיא לֹא נִטְמָאָה",
         "או ג'יר נגסה", "or while she is not impure"),
    ],
    15: [
        ("וְהֵבִיא הָאִישׁ אֶת-אִשְׁתּוֹ אֶל-הַכֹּהֵן",
         "פליאת ד'אלך אלרג'ל בזוגתה אלי' אלאמאם",
         "then that man shall bring his wife to the imām"),
        ("וְהֵבִיא אֶת-קָרְבָּנָהּ עָלֶיהָ עֲשִׂירִת הָאֵיפָה קֶמַח שְׂעֹרִים",
         "ויאתי בקרבאנהא מעהא. עשר ויבה מן דקיק אלשעיר",
         "and shall bring her offering with her: a tenth of a waybah of barley flour"),
        ("לֹא-יִצֹק עָלָיו שֶׁמֶן וְלֹא-יִתֵּן עָלָיו לְבֹנָה",
         "לא יצב עליה דהנא. ולא יגעל עליה לבאנא",
         "he shall not pour oil upon it, nor place frankincense upon it"),
        ("כִּי-מִנְחַת קְנָאֹת הוּא", "לאנה קרבאן אלג'ירה",
         "for it is the offering of jealousy"),
        ("מִנְחַת זִכָּרוֹן מַזְכֶּרֶת עָו‍ֹן", "קרבאן אלדכר יד'כר באלד'נוב",
         "the offering of remembrance, which calls sins to mind."),
    ],
    16: [
        ("וְהִקְרִיב אֹתָהּ הַכֹּהֵן", "ויקדמהא אלאמאם", "And the imām shall present her"),
        ("וְהֶעֱמִדָהּ לִפְנֵי יְהוָה", "ויוקפהא בין ידי אללה",
         "and station her before God."),
    ],
    17: [
        ("וְלָקַח הַכֹּהֵן מַיִם קְדֹשִׁים בִּכְלִי-חָרֶשׂ",
         "ויאכ'ד' אלאמאם. מן אלמא אלמקדס פי אניה' כ'זף",
         "And the imām shall take holy water in an earthen vessel"),
        ("וּמִן-הֶעָפָר אֲשֶׁר יִהְיֶה בְּקַרְקַע הַמִּשְׁכָּן יִקַּח הַכֹּהֵן",
         "ומן אלתראב. אלד'י יכון פי ערצה' אלמסכן. יאכ'ד' אלאמאם",
         "and from the dust that is on the floor of the tabernacle the imām shall take"),
        ("וְנָתַן אֶל-הַמָּיִם", "וילקי פי אלמא", "and cast into the water."),
    ],
    18: [
        ("וְהֶעֱמִיד הַכֹּהֵן אֶת-הָאִשָּׁה לִפְנֵי יְהוָה", "ויוקפהא בין ידי אללה",
         "And he shall station her before God"),
        ("וּפָרַע אֶת-רֹאשׁ הָאִשָּׁה", "ויכשף ראסהא", "and uncover her head"),
        ("וְנָתַן עַל-כַּפֶּיהָ אֵת מִנְחַת הַזִּכָּרוֹן מִנְחַת קְנָאֹת הִוא",
         "ויגעל עלי' ידהא. קרבאן אלד'כר קרבאן אלג'ירה",
         "and place upon her hands the offering of remembrance — the offering of jealousy"),
        ("וּבְיַד הַכֹּהֵן יִהְיוּ מֵי הַמָּרִים הַמְאָרְרִים",
         "ולימסך פי ידה אלמא אלמר אללאען",
         "and in his hand the imām shall hold the bitter, cursing water."),
    ],
    19: [
        ("וְהִשְׁבִּיעַ אֹתָהּ הַכֹּהֵן", "ויחלפהא", "And he shall adjure her"),
        ("וְאָמַר אֶל-הָאִשָּׁה", "ויקול להא", "and say to her"),
        ("אִם-לֹא שָׁכַב אִישׁ אֹתָךְ", "אן כאן לם י'צ'אגעך רג'ל",
         "'If no man has lain with you"),
        ("וְאִם-לֹא שָׂטִית טֻמְאָה תַּחַת אִישֵׁךְ", "ולם תחידי אלי' נגאסה ג'יר זוגך",
         "and you have not gone astray into impurity other than with your husband"),
        ("הִנָּקִי מִמֵּי הַמָּרִים הַמְאָרְרִים הָאֵלֶּה", "פאברי מן הד'א אלמא אלמר אללאען",
         "then be cleared of this bitter, cursing water."),
    ],
    20: [
        ("וְאַתְּ כִּי שָׂטִית תַּחַת אִישֵׁךְ", "ואן כנת חדת. אלי' ג'יר זוגך",
         "But if you have gone astray to one other than your husband"),
        ("וְכִי נִטְמֵאת", "ותנגסת בה", "and defiled yourself with him"),
        ("וַיִּתֵּן אִישׁ בָּךְ אֶת-שְׁכָבְתּוֹ מִבַּלְעֲדֵי אִישֵׁךְ",
         "וגעל ג'ירה מצ'אגעתה פיך", "and another has placed his lying with you"),
    ],
    21: [
        ("וְהִשְׁבִּיעַ הַכֹּהֵן אֶת-הָאִשָּׁה בִּשְׁבֻעַת הָאָלָה",
         "ויחלפהא עלי' ד'אלך ימין אלחרג",
         "the imām shall adjure her regarding this with a grievous oath"),
        ("וְאָמַר הַכֹּהֵן לָאִשָּׁה", "ויקול אלאמאם להא",
         "and the imām shall say to her"),
        ("יִתֵּן יְהוָה אוֹתָךְ לְאָלָה וְלִשְׁבֻעָה בְּתוֹךְ עַמֵּךְ",
         "יגעלך אללה. מסבה וימינא פי מא בין קומך",
         "'May God make you a curse and an oath among your people"),
        ("בְּתֵת יְהוָה אֶת-יְרֵכֵךְ נֹפֶלֶת וְאֶת-בִּטְנֵךְ צָבָה",
         "במא יגעל אללה ורכך סאקטא. ובטנך וארמא",
         "by God's making your thigh fall and your belly swell."),
    ],
    22: [
        ("וּבָאוּ הַמַּיִם הַמְאָרְרִים הָאֵלֶּה בְּמֵעַיִךְ",
         "וד'אלך. אד'א צאר הד'א אלמא אללאען אלי' אמעאך",
         "And this — when this cursing water enters your bowels"),
        ("לַצְבּוֹת בֶּטֶן וְלַנְפִּל יָרֵךְ", "פירם אלבטן ויסקט אלורך",
         "the belly shall swell and the thigh shall fall"),
        ("וְאָמְרָה הָאִשָּׁה אָמֵן אָמֵן", "ותקול אלאמראה אמין אמין",
         "And the woman shall say: Amen, amen."),
    ],
    23: [
        ("וְכָתַב אֶת-הָאָלֹת הָאֵלֶּה הַכֹּהֵן--בַּסֵּפֶר",
         "ויכתב אלאמאם. הד'ה אללענאת פי כתאב",
         "And the imām shall write these curses in a book"),
        ("וּמָחָה אֶל-מֵי הַמָּרִים", "וימחיה פי אלמא אלמר",
         "and dissolve it in the bitter water."),
    ],
    24: [
        ("וְהִשְׁקָה אֶת-הָאִשָּׁה אֶת-מֵי הַמָּרִים הַמְאָרְרִים",
         "ויסקיהא אלמא אלמר אללאען",
         "And he shall give her to drink the bitter, cursing water"),
        ("וּבָאוּ בָהּ הַמַּיִם הַמְאָרְרִים לְמָרִים", "ויסתחיל פיהא מרא",
         "and it shall turn bitter within her."),
    ],
    25: [
        ("וְלָקַח הַכֹּהֵן מִיַּד הָאִשָּׁה אֵת מִנְחַת הַקְּנָאֹת",
         "ויאכ'ד' אלאמאם מן ידהא. קרבאן אלג'ירה",
         "And the imām shall take the offering of jealousy from her hands"),
        ("וְהֵנִיף אֶת-הַמִּנְחָה לִפְנֵי יְהוָה", "ויחרכה בין ידי אללה",
         "and wave it before God"),
        ("וְהִקְרִיב אֹתָהּ אֶל-הַמִּזְבֵּחַ", "ויקדמה אלי' אלמד'בח",
         "and bring it forward to the altar."),
    ],
    26: [
        ("וְקָמַץ הַכֹּהֵן מִן-הַמִּנְחָה אֶת-אַזְכָּרָתָהּ",
         "ויקבץ' מנהא אלאמאם פיחהא",
         "And the imām shall take from it his handful as its memorial portion"),
        ("וְהִקְטִיר הַמִּזְבֵּחָה", "ויקתרה עלי' אלמד'בח",
         "and burn it upon the altar"),
        ("וְאַחַר יַשְׁקֶה אֶת-הָאִשָּׁה אֶת-הַמָּיִם", "ובעד ד'אלך יסקיהא אלמא",
         "and after that he shall give her the water to drink."),
    ],
    27: [
        ("וְהִשְׁקָהּ אֶת-הַמַּיִם", "פאד'י סקאהא אלמא",
         "And when he has given her the water to drink"),
        ("וְהָיְתָה אִם-נִטְמְאָה וַתִּמְעֹל מַעַל בְּאִישָׁהּ",
         "פאן כאנת קד תנגסת וכ'אנת זוגהא כ'יאנה",
         "if she had defiled herself and betrayed her husband with a betrayal"),
        ("וּבָאוּ בָהּ הַמַּיִם הַמְאָרְרִים לְמָרִים וְצָבְתָה בִטְנָהּ וְנָפְלָה יְרֵכָהּ",
         "אסתחל פיהא מרא. פירם בטנהא. ויסקט ורכהא",
         "then bitterness shall take effect within her: her belly shall swell and her thigh shall fall"),
        ("וְהָיְתָה הָאִשָּׁה לְאָלָה בְּקֶרֶב עַמָּהּ", "וצארת מסבה פי מא בין קומהא",
         "and she shall become a curse among her people."),
    ],
    28: [
        ("וְאִם-לֹא נִטְמְאָה הָאִשָּׁה וּטְהֹרָה הִוא", "ואן כאנת לם תנתגס. בל הי טאהרה",
         "But if she had not defiled herself, but is pure"),
        ("וְנִקְּתָה וְנִזְרְעָה זָרַע", "פברית וחמלת חמלא",
         "then she shall be cleared, and shall conceive a child."),
    ],
    29: [
        ("זֹאת תּוֹרַת הַקְּנָאֹת", "הד'ה שריעה' אלג'ירה",
         "This is the law of jealousy"),
        ("אֲשֶׁר תִּשְׂטֶה אִשָּׁה תַּחַת אִישָׁהּ וְנִטְמָאָה",
         "פי אן תחיד אמראה. ען זוגהא פתנתגס",
         "when a woman goes astray from her husband and defiles herself."),
    ],
    30: [
        ("אוֹ אִישׁ אֲשֶׁר תַּעֲבֹר עָלָיו רוּחַ קִנְאָה--וְקִנֵּא אֶת-אִשְׁתּוֹ",
         "או רג'ל יכ'טר בבאלה. ראי ג'ירה פיג'אר עלי' זוגתה",
         "Or a man in whose mind a thought of jealousy arises and he is jealous over his wife"),
        ("וְהֶעֱמִיד אֶת-הָאִשָּׁה לִפְנֵי יְהוָה", "פליוקפהא בין ידי אללה",
         "he shall station her before God"),
        ("וְעָשָׂה לָהּ הַכֹּהֵן אֵת כָּל-הַתּוֹרָה הַזֹּאת",
         "ויצנע בהא אלאמאם. גמיע מא פי הד'א אלשריעה",
         "and the imām shall do to her all that is in this law."),
    ],
    31: [
        ("וְנִקָּה הָאִישׁ מֵעָו‍ֹן", "חתי יברו אלרגל מן אלוזר",
         "So that the man may be cleared of guilt"),
        ("וְהָאִשָּׁה הַהִוא תִּשָּׂא אֶת-עֲו‍ֹנָהּ", "ותלך אלאמראה תחמל וזרהא",
         "and that woman shall bear her guilt."),
    ],
}
