"""Hand-authored alignment triples for Bamidbar chapter 24."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיַּרְא בִּלְעָם כִּי טוֹב בְּעֵינֵי יְהוָה לְבָרֵךְ אֶת-יִשְׂרָאֵל",
         "פלמא ראא בלעם. אן אלאצלח ענד אללה תבריך אל אסראיל",
         "And when Balaam saw that it was more fitting before God to bless Israel"),
        ("וְלֹא-הָלַךְ כְּפַעַם-בְּפַעַם לִקְרַאת נְחָשִׁים",
         "לם ימץ' כאלמרתין אלאוולתין פי טלב אלפאלאת",
         "he did not proceed as in the first two times in seeking omens"),
        ("וַיָּשֶׁת אֶל-הַמִּדְבָּר פָּנָיו", "פאקבל בקצדה אלי' ברהם",
         "but turned with his intent toward their wilderness"),
    ],
    2: [
        ("וַיִּשָּׂא בִלְעָם אֶת-עֵינָיו וַיַּרְא אֶת-יִשְׂרָאֵל שֹׁכֵן לִשְׁבָטָיו",
         "פלמא מד בצרה וראהם. נאזלין עלי' נצ'אם אסבטאהם",
         "And when he extended his gaze and saw them encamped according to the order of their tribes"),
        ("וַתְּהִי עָלָיו רוּחַ אֱלֹהִים", "חלת עלי'ה נבווה' אללה",
         "the prophecy of God rested upon him"),
    ],
    3: [
        ("וַיִּשָּׂא מְשָׁלוֹ וַיֹּאמַר", "פצ'רב מת'לה וקאל",
         "And he uttered his parable and said"),
        ("נְאֻם בִּלְעָם בְּנוֹ בְעֹר", "קל יא בלעם אבן בעור",
         "'Speak, O Balaam son of Beor!"),
        ("וּנְאֻם הַגֶּבֶר שְׁתֻם הָעָיִן", "וקל יא אייהא אלרגל אלחדיד אלבצר",
         "And speak, O man of sharp sight!'"),
    ],
    4: [
        ("נְאֻם--שֹׁמֵעַ אִמְרֵי-אֵל", "וקל יא סאמע אקואל אלטאיק",
         "'And speak, O hearer of the words of the All-Powerful"),
        ("אֲשֶׁר מַחֲזֵה שַׁדַּי יֶחֱזֶה", "ונאצ'ר מנאצ'ר אלכאפי",
         "and beholder of the visions of the All-Sufficient"),
        ("נֹפֵל וּגְלוּי עֵינָיִם", "והו נאים מפתוח אלעין",
         "who sleeps with open eyes!'"),
    ],
    5: [
        ("מַה-טֹּבוּ אֹהָלֶיךָ יַעֲקֹב", "מא אגוד אכ'ביתך יא אל יעקוב",
         "'How goodly are your tents, O house of Jacob"),
        ("מִשְׁכְּנֹתֶיךָ יִשְׂרָאֵל", "ומנאזלך יא אל אסראיל",
         "and your dwellings, O house of Israel!'"),
    ],
    6: [
        ("כִּנְחָלִים נִטָּיוּ", "פהי כאודיה ממדודה",
         "'For they are like valleys stretched out"),
        ("כְּגַנֹּת עֲלֵי נָהָר", "וכגנאן עלי' נהר", "and like gardens along a river"),
        ("כַּאֲהָלִים נָטַע יְהוָה", "וכמצ'ארב צ'רבהא אללה",
         "and like encampments pitched by God"),
        ("כַּאֲרָזִים עֲלֵי-מָיִם", "וכארוז עלי' מא", "and like cedars beside water.'"),
    ],
    7: [
        ("יִזַּל-מַיִם מִדָּלְיָו", "יהטל אלמא מן דואליה",
         "'Water drips from his branches"),
        ("וְזַרְעוֹ בְּמַיִם רַבִּים", "וג'רסה פי מא ג'זיר",
         "and his planting is in abundant water"),
        ("וְיָרֹם מֵאֲגַג מַלְכּוֹ", "וירתפע מן אגג מלכה",
         "and his king shall rise above Agag"),
        ("וְתִנַּשֵּׂא מַלְכֻתוֹ", "ותתסאנא ממלכתה", "and his kingdom shall be exalted.'"),
    ],
    8: [
        ("אֵל מוֹצִיאוֹ מִמִּצְרַיִם כְּתוֹעֲפֹת רְאֵם לוֹ",
         "אלטאיק אלמכ'רגהם מן מצר. כארק אלרים מאנע ענהם",
         "'The All-Powerful who brought them out of Egypt is like the wakefulness of the wild ox, a protection over them"),
        ("יֹאכַל גּוֹיִם צָרָיו", "והו יאכל אעדאיה מן אלאמם",
         "and He shall consume his enemies among the nations"),
        ("וְעַצְמֹתֵיהֶם יְגָרֵם--וְחִצָּיו יִמְחָץ", "ועצ'אמהם ינהש וסהאמה תדנפהם",
         "and their bones He shall gnaw, and His arrows shall strike them down.'"),
    ],
    9: [
        ("כָּרַע שָׁכַב כַּאֲרִי וּכְלָבִיא מִי יְקִימֶנּוּ",
         "ואד'י גת'א ורבץ. פהו כאסד ולבו מן ד'א יתירה",
         "'When he crouches and lies down, he is like a lion and a lioness — who shall rouse him?"),
        ("מְבָרְכֶיךָ בָרוּךְ", "מבארכך מבארך", "He who blesses you is blessed"),
        ("וְאֹרְרֶיךָ אָרוּר", "ולאענך מלעון", "and he who curses you is accursed.'"),
    ],
    10: [
        ("וַיִּחַר-אַף בָּלָק אֶל-בִּלְעָם וַיִּסְפֹּק אֶת-כַּפָּיו",
         "פאשתד ג'צ'ב בלק עלי' בלעם וספק כפיה חרדא",
         "And Balak's anger was greatly kindled against Balaam, and he clapped his two hands in fury"),
        ("וַיֹּאמֶר בָּלָק אֶל-בִּלְעָם לָקֹב אֹיְבַי קְרָאתִיךָ",
         "וקאל לה. אנמא דעותך לתסב אעדאי",
         "and said to him: 'I summoned you only to curse my enemies"),
        ("וְהִנֵּה בֵּרַכְתָּ בָרֵךְ זֶה שָׁלֹשׁ פְּעָמִים",
         "פאד'א בך תבארך פיהם. הד'ה אלמרה אלת'אלת'ה",
         "and behold, you have blessed them altogether; this is the third time!'"),
    ],
    11: [
        ("וְעַתָּה בְּרַח-לְךָ אֶל-מְקוֹמֶךָ", "ואלאן פאנצרף אלי' מוצ'עך",
         "'And now, depart to your place!"),
        ("אָמַרְתִּי כַּבֵּד אֲכַבֶּדְךָ", "לקד עזמת אן אכרמך",
         "I had resolved to honor you greatly"),
        ("וְהִנֵּה מְנָעֲךָ יְהוָה מִכָּבוֹד", "פמנעך אללה מן אלכראמה",
         "but God has withheld you from honor.'"),
    ],
    12: [
        ("וַיֹּאמֶר בִּלְעָם אֶל-בָּלָק", "קאל לה בלעם", "Balaam said to him"),
        ("הֲלֹא גַּם אֶל-מַלְאָכֶיךָ אֲשֶׁר-שָׁלַחְתָּ אֵלַי--דִּבַּרְתִּי לֵאמֹר",
         "אלם אקול לרסלך. אלד'י בעת'ת בהם אלי'י קאילא",
         "'Did I not already say to your messengers whom you sent to me, saying:'"),
    ],
    13: [
        ("אִם-יִתֶּן-לִי בָלָק מְלֹא בֵיתוֹ כֶּסֶף וְזָהָב",
         "לו אעטאני בלק. מל ביתה פצ'ה וד'הב",
         "'Were Balak to give me his house full of silver and gold"),
        ("לֹא אוּכַל לַעֲבֹר אֶת-פִּי יְהוָה", "לא אסתטיע. אן אתגאוז אמר אללה",
         "I could not transgress the command of God"),
        ("לַעֲשׂוֹת טוֹבָה אוֹ רָעָה מִלִּבִּי", "פאעמל גיידה או רדייה מן ראיי",
         "to do good or evil of my own mind"),
        ("אֲשֶׁר-יְדַבֵּר יְהוָה אֹתוֹ אֲדַבֵּר", "אנמא אלד'י יקולה אללה אקולה פקט",
         "only what God says shall I say, and nothing else.'"),
    ],
    14: [
        ("וְעַתָּה הִנְנִי הוֹלֵךְ לְעַמִּי", "ואלאן. האנא מנצרף אלי' קומי",
         "'And now, here I am departing to my people."),
        ("לְכָה אִיעָצְךָ", "תעאל חתי' אערפך", "Come, so that I may inform you"),
        ("אֲשֶׁר יַעֲשֶׂה הָעָם הַזֶּה לְעַמְּךָ בְּאַחֲרִית הַיָּמִים",
         "מא יצנע הולאי אלקום. בקומך פי אכ'ר אלאייאם",
         "of what this people shall do to your people at the end of days.'"),
    ],
    15: [
        ("וַיִּשָּׂא מְשָׁלוֹ וַיֹּאמַר", "פצ'רב מת'לה וקאל",
         "And he uttered his parable and said"),
        ("נְאֻם בִּלְעָם בְּנוֹ בְעֹר", "קל יא בלעם אבן בעור",
         "'Speak, O Balaam son of Beor!"),
        ("וּנְאֻם הַגֶּבֶר שְׁתֻם הָעָיִן", "וקל יא אייהא אלרגל אלחדיד אלבצר",
         "And speak, O man of sharp sight!'"),
    ],
    16: [
        ("נְאֻם שֹׁמֵעַ אִמְרֵי-אֵל", "וקל יא סאמע אקואל אלטאיק",
         "'And speak, O hearer of the words of the All-Powerful"),
        ("וְיֹדֵעַ דַּעַת עֶלְיוֹן", "ועארף מערפה' אלעאלי'",
         "and knower of the knowledge of the Most High"),
        ("מַחֲזֵה שַׁדַּי יֶחֱזֶה", "ונאצ'ר מנאצ'ר אלכאפי",
         "and beholder of the visions of the All-Sufficient"),
        ("נֹפֵל וּגְלוּי עֵינָיִם", "והו נאים והו מפתוח אלעין",
         "who sleeps with open eyes!'"),
    ],
    17: [
        ("אֶרְאֶנּוּ וְלֹא עַתָּה", "אמר אראה וליס הו אלאן",
         "'A matter I see, though it is not now"),
        ("אֲשׁוּרֶנּוּ וְלֹא קָרוֹב", "ואלמחה והו ג'יר קריב",
         "and I perceive it, though it is not near"),
        ("דָּרַךְ כּוֹכָב מִיַּעֲקֹב וְקָם שֵׁבֶט מִיִּשְׂרָאֵל",
         "אן יטלע כוכב מן אל יעקוב. ויקום קצ'יב מן אל אסראיל",
         "that a star shall rise from the house of Jacob, and a scepter-bearer shall arise from the house of Israel"),
        ("וּמָחַץ פַּאֲתֵי מוֹאָב", "פיוהן גהאת מואב",
         "and shall weaken the sides of Moab"),
        ("וְקַרְקַר כָּל-בְּנֵי-שֵׁת", "ויזלזל סאיר בני שת",
         "and shall shake the rest of the sons of Shet.'"),
    ],
    18: [
        ("וְהָיָה אֱדוֹם יְרֵשָׁה", "וסיכון אדום מנקרצ'א",
         "'And Edom shall be utterly destroyed"),
        ("וְהָיָה יְרֵשָׁה שֵׂעִיר--אֹיְבָיו", "וכד'אלך שעיר וסאיר אעדאיה",
         "and likewise Seir and the rest of his enemies"),
        ("וְיִשְׂרָאֵל עֹשֶׂה חָיִל", "ואסראיל יזתאד תאיידא",
         "and Israel shall grow in strength ever more.'"),
    ],
    19: [
        ("וְיֵרְדְּ מִיַּעֲקֹב", "ואלד'י יסתולי מן אל יעקוב",
         "'And he who rules from the house of Jacob"),
        ("וְהֶאֱבִיד שָׂרִיד מֵעִיר", "יביד אלשריד מן אלקרא",
         "shall destroy the remnant from the towns.'"),
    ],
    20: [
        ("וַיַּרְא אֶת-עֲמָלֵק וַיִּשָּׂא מְשָׁלוֹ וַיֹּאמַר",
         "ת'ם ראא אלעמלקיין. פצ'רב מת'לה וקאל",
         "Then he saw the Amalekites, and uttered his parable and said"),
        ("רֵאשִׁית גּוֹיִם עֲמָלֵק", "אוול חרב אלאמם עמלק",
         "'The first to make war among the nations was Amalek"),
        ("וְאַחֲרִיתוֹ עֲדֵי אֹבֵד", "ואכ'רתה אלי' אלאבאדה",
         "and its end is unto destruction.'"),
    ],
    21: [
        ("וַיַּרְא אֶת-הַקֵּינִי וַיִּשָּׂא מְשָׁלוֹ וַיֹּאמַר",
         "ת'ם ראא אלקיניין. פצ'רב מת'לה וקאל",
         "Then he saw the Kenites, and uttered his parable and said"),
        ("אֵיתָן מוֹשָׁבֶךָ", "סיכון מגלסך צלבא", "'Your seat shall be firm and strong"),
        ("וְשִׂים בַּסֶּלַע קִנֶּךָ", "ותצייר פי אלצכ'ר וכרך",
         "and you shall set your nest in the rock.'"),
    ],
    22: [
        ("כִּי אִם-יִהְיֶה לְבָעֵר קָיִן", "ואד'א יכון וקת לנפי אלקיניין",
         "'Yet there shall come a time for the exile of the Kenites"),
        ("עַד-מָה אַשּׁוּר תִּשְׁבֶּךָּ", "פכם יסבי מנהם אלמוצליין",
         "how many of them shall the people of Mosul (Asshur) take captive!'"),
    ],
    23: [
        ("וַיִּשָּׂא מְשָׁלוֹ וַיֹּאמַר", "פצ'רב מת'לה וקאל",
         "And he uttered his parable and said"),
        ("אוֹי מִי יִחְיֶה מִשֻּׂמוֹ אֵל", "אלויל למן יחיא. אד'א ציירה אלטאיק",
         "'Woe to him who shall be alive when the All-Powerful has brought this upon him!'"),
    ],
    24: [
        ("וְצִים מִיַּד כִּתִּים", "ואלדראמיין מן פרצ'ה' קברס",
         "'And the Dramians from the harbor of Cyprus"),
        ("וְעִנּוּ אַשּׁוּר וְעִנּוּ-עֵבֶר", "לתעד'ב אלמוצליין ואלעבריין",
         "shall afflict the people of Mosul and the Hebrews"),
        ("וְגַם-הוּא עֲדֵי אֹבֵד", "והם איצ'א אלי' אבאדה",
         "and they too shall come to destruction.'"),
    ],
    25: [
        ("וַיָּקָם בִּלְעָם וַיֵּלֶךְ וַיָּשָׁב לִמְקֹמוֹ",
         "ת'ם קאם בלעם ומצ'א ורגע אלי' מוצ'עה",
         "Then Balaam arose and departed and returned to his place"),
        ("וְגַם-בָּלָק הָלַךְ לְדַרְכּוֹ", "ובלק איצ'א מצ'א אלי' סבילה",
         "and Balak too went on his way."),
    ],
}
