"""Hand-authored alignment triples for Bamidbar chapter 8."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאָמַרְתָּ אֵלָיו", "מר הרון וקל לה",
         "'Command Aaron and say to him"),
        ("בְּהַעֲלֹתְךָ אֶת-הַנֵּרֹת", "אד'א אסרגת אלסרג",
         "when you light the lamp"),
        ("אֶל-מוּל פְּנֵי הַמְּנוֹרָה יָאִירוּ שִׁבְעַת הַנֵּרוֹת",
         "פאלי' מא ילי וגה אלמנארה. תצ'י סבעתהא",
         "toward what faces the front of the lampstand shall its seven lamps give light.'"),
    ],
    3: [
        ("וַיַּעַשׂ כֵּן אַהֲרֹן", "פצנע כד'אך הרון", "And so Aaron did"),
        ("אֶל-מוּל פְּנֵי הַמְּנוֹרָה הֶעֱלָה נֵרֹתֶיהָ", "ואסרג סרג אלמנארה. אלי' מא ילי וגההא",
         "he lit the lamps of the lampstand toward what faces its front"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    4: [
        ("וְזֶה מַעֲשֵׂה הַמְּנֹרָה מִקְשָׁה זָהָב", "והד'ה צנעה' אלמנארה מצמתה ד'הב",
         "And this is the workmanship of the lampstand: solid gold"),
        ("עַד-יְרֵכָהּ עַד-פִּרְחָהּ מִקְשָׁה הִוא", "חתי ארגלהא ורחארחהא מצמתה",
         "even its base and its blossoms were solid"),
        ("כַּמַּרְאֶה אֲשֶׁר הֶרְאָה יְהוָה אֶת-מֹשֶׁה", "כאלמנצ'רכ. אלד'י אורא אללה מוסי'",
         "like the appearance which God had shown to Moses"),
        ("כֵּן עָשָׂה אֶת-הַמְּנֹרָה", "כד'אך צנעהא", "so he made it."),
    ],
    5: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    6: [
        ("קַח אֶת-הַלְוִיִּם מִתּוֹךְ בְּנֵי יִשְׂרָאֵל", "קדם אלליוניין. מן בין בני אסראיל",
         "'Bring forward the Levites from among the sons of Israel"),
        ("וְטִהַרְתָּ אֹתָם", "וטהרהם", "and purify them.'"),
    ],
    7: [
        ("וְכֹה-תַעֲשֶׂה לָהֶם לְטַהֲרָם", "וכד'י אצנע להם פי תטהירהם",
         "'And thus shall you do for them in their purification"),
        ("הַזֵּה עֲלֵיהֶם מֵי חַטָּאת", "אנצ'ח עליהם מן מא אלדכוה",
         "sprinkle upon them of the water of purification"),
        ("וְהֶעֱבִירוּ תַעַר עַל-כָּל-בְּשָׂרָם", "וימרון אלמוס עלי' גמיע בדנהם",
         "and let them pass a razor over all their body"),
        ("וְכִבְּסוּ בִגְדֵיהֶם וְהִטֶּהָרוּ", "ויג'סלון ת'יאבהם ויטהרון",
         "and let them wash their garments — and they shall be purified.'"),
    ],
    8: [
        ("וְלָקְחוּ פַּר בֶּן-בָּקָר", "ויקרבו ת'ורא מן אלבקר",
         "'And they shall bring forward an ox from the herd"),
        ("וּמִנְחָתוֹ סֹלֶת בְּלוּלָה בַשָּׁמֶן", "ומעה בר סמד מלתות בדהן",
         "and with it wheat-flour, fine semolina mixed with oil"),
        ("וּפַר-שֵׁנִי בֶן-בָּקָר תִּקַּח לְחַטָּאת", "ות'ור אכ'ר מן אלבקר כ'דה לאלדכוה",
         "and a second ox from the herd — take it for the purification-offering.'"),
    ],
    9: [
        ("וְהִקְרַבְתָּ אֶת-הַלְוִיִּם לִפְנֵי אֹהֶל מוֹעֵד", "וקדם אלליוניין. בין ידי כ'בא אלמחצ'ר",
         "'And bring forward the Levites before the tent of meeting"),
        ("וְהִקְהַלְתָּ--אֶת-כָּל-עֲדַת בְּנֵי יִשְׂרָאֵל", "וגווק גמאעה' בני אסראיל",
         "and assemble the congregation of the sons of Israel.'"),
    ],
    10: [
        ("וְהִקְרַבְתָּ אֶת-הַלְוִיִּם לִפְנֵי יְהוָה", "וקדמהם בין ידי אללה",
         "'And present them before God"),
        ("וְסָמְכוּ בְנֵי-יִשְׂרָאֵל אֶת-יְדֵיהֶם עַל-הַלְוִיִּם",
         "ויסנ'ד בני אסראיל אידיהם עליהם",
         "and the sons of Israel shall lay their hands upon them.'"),
    ],
    11: [
        ("וְהֵנִיף אַהֲרֹן אֶת-הַלְוִיִּם תְּנוּפָה לִפְנֵי יְהוָה",
         "ויזפהם הרון זפא בין ידי אללה",
         "'And Aaron shall present them as a presentation before God"),
        ("מֵאֵת בְּנֵי יִשְׂרָאֵל", "מן בני אסראיל", "from the sons of Israel"),
        ("וְהָיוּ לַעֲבֹד אֶת-עֲבֹדַת יְהוָה", "פיכונו יכ'דמון כ'דמה' אללה",
         "that they may be for serving the service of God.'"),
    ],
    12: [
        ("וְהַלְוִיִּם יִסְמְכוּ אֶת-יְדֵיהֶם עַל רֹאשׁ הַפָּרִים",
         "ואלליוניין יסנדו אידיהם. עלי' רוס אלת'יראן",
         "'And the Levites shall lay their hands upon the heads of the bulls"),
        ("וַעֲשֵׂה אֶת-הָאֶחָד חַטָּאת וְאֶת-הָאֶחָד עֹלָה לַיהוָה",
         "ואצנע אחדהמא ד'כוה. ואלאכ'ר צעידה ללה",
         "and make one of them a purification-offering, and the other a burnt-offering to God"),
        ("לְכַפֵּר עַל-הַלְוִיִּם", "ואסתג'פר ענהם",
         "and seek forgiveness for them.'"),
    ],
    13: [
        ("וְהַעֲמַדְתָּ אֶת-הַלְוִיִּם לִפְנֵי אַהֲרֹן וְלִפְנֵי בָנָיו",
         "ואוקפהם בין ידי הרון ובניה",
         "'And station them before Aaron and his sons"),
        ("וְהֵנַפְתָּ אֹתָם תְּנוּפָה לַיהוָה", "וזפהם זפא ללה",
         "and present them as a presentation to God.'"),
    ],
    14: [
        ("וְהִבְדַּלְתָּ אֶת-הַלְוִיִּם מִתּוֹךְ בְּנֵי יִשְׂרָאֵל",
         "ואעזלהם מן בין בני אסראיל",
         "'And separate them from among the sons of Israel"),
        ("וְהָיוּ לִי הַלְוִיִּם", "פיכונו לי", "and they shall be Mine.'"),
    ],
    15: [
        ("וְאַחֲרֵי-כֵן יָבֹאוּ הַלְוִיִּם לַעֲבֹד אֶת-אֹהֶל מוֹעֵד",
         "ובעד ד'אלך ידכ'לון. ליכ'דמון כ'בא אלמחצ'ר",
         "'And after that they shall enter to serve the tent of meeting"),
        ("וְטִהַרְתָּ אֹתָם וְהֵנַפְתָּ אֹתָם תְּנוּפָה",
         "וקד טהרתהם. וזפיתהם זפא",
         "for you will have purified them and presented them as a presentation.'"),
    ],
    16: [
        ("כִּי נְתֻנִים נְתֻנִים הֵמָּה לִי מִתּוֹךְ בְּנֵי יִשְׂרָאֵל",
         "לאנהם מגעולין לי. מן בין בני אסראיל",
         "'For they are appointed to Me from among the sons of Israel"),
        ("תַּחַת פִּטְרַת כָּל-רֶחֶם בְּכוֹר כֹּל מִבְּנֵי יִשְׂרָאֵל",
         "בדל כל בכר. פאתח כל בטן מן בני אסראיל",
         "in place of every firstborn, the opener of every womb among the sons of Israel"),
        ("לָקַחְתִּי אֹתָם לִי", "אכ'ד'תהם לי", "I have taken them for Myself.'"),
    ],
    17: [
        ("כִּי לִי כָל-בְּכוֹר בִּבְנֵי יִשְׂרָאֵל בָּאָדָם וּבַבְּהֵמָה",
         "כמא כאן לי כל בכר. פי מא בין בני אסראיל. מן אנסאן אלי' בהימה",
         "'Just as every firstborn among the sons of Israel was Mine — of human and of beast"),
        ("בְּיוֹם הַכֹּתִי כָל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם",
         "וד'אלך פי יום אהלכת כל בכר פי בלד מצר",
         "on the day I destroyed every firstborn in the land of Egypt"),
        ("הִקְדַּשְׁתִּי אֹתָם לִי", "אקדסתהם לי", "I consecrated them to Me.'"),
    ],
    18: [
        ("וָאֶקַּח אֶת-הַלְוִיִּם תַּחַת כָּל-בְּכוֹר בִּבְנֵי יִשְׂרָאֵל",
         "כד'אלך אתכד'ת אלליוניין בדלהם",
         "'Thus I took the Levites in their stead.'"),
    ],
    19: [
        ("וָאֶתְּנָה אֶת-הַלְוִיִּם נְתֻנִים לְאַהֲרֹן וּלְבָנָיו",
         "וגעלתהם להרון ובניה",
         "'And I appointed them for Aaron and his sons"),
        ("מִתּוֹךְ בְּנֵי יִשְׂרָאֵל לַעֲבֹד אֶת-עֲבֹדַת בְּנֵי-יִשְׂרָאֵל בְּאֹהֶל מוֹעֵד",
         "מן בין בני אסראיל. ליכדמו כ'דמתהם פי כ'בא אלמחצ'ר",
         "from among the sons of Israel, to perform their service in the tent of meeting"),
        ("וּלְכַפֵּר עַל-בְּנֵי יִשְׂרָאֵל", "ויסתג'פרו ענהם",
         "and to seek forgiveness for them"),
        ("וְלֹא יִהְיֶה בִּבְנֵי יִשְׂרָאֵל נֶגֶף בְּגֶשֶׁת בְּנֵי-יִשְׂרָאֵל אֶל-הַקֹּדֶשׁ",
         "ולא יחל בהם ובא. אד' הם תקדמו אלי' אלקדס",
         "that no pestilence may come upon them when they approach the sanctuary.'"),
    ],
    20: [
        ("וַיַּעַשׂ מֹשֶׁה וְאַהֲרֹן וְכָל-עֲדַת בְּנֵי-יִשְׂרָאֵל לַלְוִיִּם",
         "וצנע מוסי' והרון. וסאיר גמאעה' בני אסראיל לאלליוניין",
         "And Moses and Aaron, and the rest of the congregation of the sons of Israel, did for the Levites"),
        ("כְּכֹל אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה לַלְוִיִּם", "כגמיע מא אמר אללה מוסי' פי סבבהם",
         "according to all that God had commanded Moses concerning them"),
        ("כֵּן-עָשׂוּ לָהֶם בְּנֵי יִשְׂרָאֵל", "כד'אך צנעו להם", "so they did for them."),
    ],
    21: [
        ("וַיִּתְחַטְּאוּ הַלְוִיִּם וַיְכַבְּסוּ בִּגְדֵיהֶם",
         "פתד'כו וג'סלו ת'יאבהם",
         "And they were purified and washed their garments"),
        ("וַיָּנֶף אַהֲרֹן אֹתָם תְּנוּפָה לִפְנֵי יְהוָה",
         "וזפהם הרון זפא בין ידי אללה",
         "and Aaron presented them as a presentation before God"),
        ("וַיְכַפֵּר עֲלֵיהֶם אַהֲרֹן לְטַהֲרָם", "ואסתג'פר ענהם וטהרהם",
         "and sought forgiveness for them and purified them."),
    ],
    22: [
        ("וְאַחֲרֵי-כֵן בָּאוּ הַלְוִיִּם לַעֲבֹד אֶת-עֲבֹדָתָם בְּאֹהֶל מוֹעֵד",
         "ובעד ד'אלך דכ'לו. ליכ'דמו כ'דמתהם פי כ'בא אלמחצ'ר",
         "And after that they entered to perform their service in the tent of meeting"),
        ("לִפְנֵי אַהֲרֹן וְלִפְנֵי בָנָיו", "בין ידי הרון ובניה",
         "before Aaron and his sons"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה עַל-הַלְוִיִּם כֵּן עָשׂוּ לָהֶם",
         "כגמיע מא אמר אללה מוסי' בסבבהם. כד'אך צנעו להם",
         "according to all that God had commanded Moses concerning them, so they did for them."),
    ],
    23: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    24: [
        ("זֹאת אֲשֶׁר לַלְוִיִּם", "הד'א רסם אלליוניין",
         "'This is the ordinance for the Levites"),
        ("מִבֶּן חָמֵשׁ וְעֶשְׂרִים שָׁנָה וָמַעְלָה", "מן אבן כ'מסה ועשרין סנה פצאעדא",
         "from twenty-five years of age and upward"),
        ("יָבוֹא לִצְבֹא צָבָא בַּעֲבֹדַת אֹהֶל מוֹעֵד", "ידכל לאלגיש. לכ'דמה' כ'בא אלמחצ'ר",
         "one shall enter the host for the service of the tent of meeting.'"),
    ],
    25: [
        ("וּמִבֶּן חֲמִשִּׁים שָׁנָה יָשׁוּב מִצְּבָא הָעֲבֹדָה", "ומן אבן כ'מסין סנה. ירגע ענה",
         "'And from fifty years of age he shall retire from it"),
        ("וְלֹא יַעֲבֹד עוֹד", "ולא יכ'דם אבדא", "and shall serve no more at all.'"),
    ],
    26: [
        ("וְשֵׁרֵת אֶת-אֶחָיו בְּאֹהֶל מוֹעֵד לִשְׁמֹר מִשְׁמֶרֶת",
         "לכן יכ'דם מע אכ'ותה. פי חפץ' כ'בא אלמחצ'ר",
         "'But he may serve alongside his brothers in guarding the tent of meeting"),
        ("וַעֲבֹדָה לֹא יַעֲבֹד", "ואמא כ'דמתה אלאוולא פלא יכ'דם",
         "as for his former service, he shall not serve."),
        ("כָּכָה תַּעֲשֶׂה לַלְוִיִּם בְּמִשְׁמְרֹתָם", "כד'אך אצנע בהם פי מחפצ'הם",
         "Thus shall you do for them in their charge.'"),
    ],
}
