"""Hand-authored alignment triples for Bamidbar chapter 14."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַתִּשָּׂא כָּל-הָעֵדָה וַיִּתְּנוּ אֶת-קוֹלָם", "ת'ם רפעת אלגמאעה אצואתהם",
         "Then the assembly raised their voices"),
        ("וַיִּבְכּוּ הָעָם בַּלַּיְלָה הַהוּא", "ובכו פי תלך אלילה",
         "and they wept in that night."),
    ],
    2: [
        ("וַיִּלֹּנוּ עַל-מֹשֶׁה וְעַל-אַהֲרֹן כֹּל בְּנֵי יִשְׂרָאֵל",
         "פתד'מרו. עלי'' מוסי' והרון. גמאעה' בני אסראיל",
         "And the congregation of the sons of Israel grumbled against Moses and Aaron"),
        ("וַיֹּאמְרוּ אֲלֵהֶם", "וקאלא להם", "and said to them"),
        ("לוּ-מַתְנוּ בְּאֶרֶץ מִצְרַיִם", "יא ליתנא מתנא פי בלד מצר",
         "'Would that we had died in the land of Egypt"),
        ("אוֹ בַּמִּדְבָּר הַזֶּה לוּ-מָתְנוּ", "או יא ליתנא מתנא פי הד'א אלבר",
         "or would that we had died in this wilderness!'"),
    ],
    3: [
        ("וְלָמָה יְהוָה מֵבִיא אֹתָנוּ אֶל-הָאָרֶץ הַזֹּאת לִנְפֹּל בַּחֶרֶב",
         "ולם ידכ'לנא אללה. תלך אלבלד פנקע באלסיף",
         "'And why would God bring us into that land, that we should fall by the sword"),
        ("נָשֵׁינוּ וְטַפֵּנוּ יִהְיוּ לָבַז", "פיציר נסאנא ואטפאלנא ג'נימה",
         "so that our wives and our children become spoil"),
        ("הֲלוֹא טוֹב לָנוּ שׁוּב מִצְרָיְמָה", "אלא אן אלאצלח לנא אלרגוע אלי' מצר",
         "Is it not better for us to return to Egypt?'"),
    ],
    4: [
        ("וַיֹּאמְרוּ אִישׁ אֶל-אָחִיו", "ת'ם קאל בעצ'הם לבעץ'",
         "Then some of them said to one another"),
        ("נִתְּנָה רֹאשׁ וְנָשׁוּבָה מִצְרָיְמָה", "נולי ריסא ונרגע אלי' מצר",
         "'Let us appoint a head, and return to Egypt.'"),
    ],
    5: [
        ("וַיִּפֹּל מֹשֶׁה וְאַהֲרֹן עַל-פְּנֵיהֶם",
         "פוקע מוסי' והרון עלי' וגוההמא",
         "And Moses and Aaron fell upon their faces"),
        ("לִפְנֵי כָּל-קְהַל עֲדַת בְּנֵי יִשְׂרָאֵל",
         "בחצ'רה' גוק גמאעה' בני אסראיל",
         "before the assembly of the congregation of the sons of Israel."),
    ],
    6: [
        ("וִיהוֹשֻׁעַ בִּן-נוּן וְכָלֵב בֶּן-יְפֻנֶּה",
         "ויהושע אבן נון. וכלב אבן יפנה",
         "And Joshua son of Nun, and Caleb son of Jephunneh"),
        ("מִן-הַתָּרִים אֶת-הָאָרֶץ", "מן ראימי אלבלד", "among those who had scouted the land"),
        ("קָרְעוּ בִּגְדֵיהֶם", "כ'רקא ת'יאבהמא", "tore their garments."),
    ],
    7: [
        ("וַיֹּאמְרוּ אֶל-כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל לֵאמֹר",
         "פקאלא. לגמאעה' בני אסראיל קאילין",
         "And they said to the congregation of the sons of Israel, saying"),
        ("הָאָרֶץ אֲשֶׁר עָבַרְנוּ בָהּ לָתוּר אֹתָהּ--טוֹבָה הָאָרֶץ מְאֹד מְאֹד",
         "אלבלד. אלד'י מררנאה לנרומה. בלד גייד גדא גדא",
         "'The land which we passed through to seek it out — it is a very, very good land.'"),
    ],
    8: [
        ("אִם-חָפֵץ בָּנוּ יְהוָה", "אן כאן ללה מראד פינא",
         "'If God has a will toward us"),
        ("וְהֵבִיא אֹתָנוּ אֶל-הָאָרֶץ הַזֹּאת וּנְתָנָהּ לָנוּ",
         "אדכ'לנאה ווהבה לנא",
         "He will bring us into it and give it to us as a gift"),
        ("אֶרֶץ אֲשֶׁר-הִוא זָבַת חָלָב וּדְבָשׁ", "בלד יפיץ' אללבן ואלעסל",
         "a land flowing with milk and honey.'"),
    ],
    9: [
        ("אַךְ בַּיהוָה אַל-תִּמְרֹדוּ", "אמא עלי' אללה פלא תתד'מרון",
         "'Only do not grumble against God"),
        ("וְאַתֶּם אַל-תִּירְאוּ אֶת-עַם הָאָרֶץ", "ולא תכ'אפון אהל אלבלד",
         "and do not fear the people of the land"),
        ("כִּי לַחְמֵנוּ הֵם", "לאנהם טעאמנא", "for they are our food"),
        ("סָר צִלָּם מֵעֲלֵיהֶם", "וסיזול צ'להם ענהם", "their shadow has already departed from them."),
        ("וַיהוָה אִתָּנוּ אַל-תִּירָאֻם", "ואללה מענא לא תכ'אפוהם",
         "And God is with us — do not fear them.'"),
    ],
    10: [
        ("וַיֹּאמְרוּ כָּל-הָעֵדָה לִרְגּוֹם אֹתָם בָּאֲבָנִים",
         "פכאד גמיע אלשעב. אן ירגמוהמא באלחגארה",
         "Then nearly all the people were about to stone the two of them."),
        ("וּכְבוֹד יְהוָה נִרְאָה בְּאֹהֶל מוֹעֵד אֶל-כָּל-בְּנֵי יִשְׂרָאֵל",
         "ת'ם צ'הר נור אללה. פי כ'בא אלמחצ'ר. לגמיע בני אסראיל",
         "Then the light of God appeared in the Tent of Meeting before all the sons of Israel."),
    ],
    11: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי", "And God said to Moses"),
        ("עַד-אָנָה יְנַאֲצֻנִי הָעָם הַזֶּה", "אלי' כם יעצוני הולאי אלקום",
         "'How long shall these people defy Me"),
        ("וְעַד-אָנָה לֹא-יַאֲמִינוּ בִי", "ואלי' כם לם יומנון בי",
         "and how long will they not believe in Me"),
        ("בְּכֹל הָאֹתוֹת אֲשֶׁר עָשִׂיתִי בְּקִרְבּוֹ",
         "מע גמיע אלאיאת. אלתי צנעתהא פי מא בינהם",
         "despite all the signs which I performed among them?'"),
    ],
    12: [
        ("אַכֶּנּוּ בַדֶּבֶר וְאוֹרִשֶׁנּוּ",
         "יסתחקון אן אצ'רבהם באלובא ואקרצ'הם",
         "'They deserve that I strike them with pestilence and wear them down"),
        ("וְאֶעֱשֶׂה אֹתְךָ לְגוֹי-גָּדוֹל וְעָצוּם מִמֶּנּוּ",
         "ואגעל מנך. אמה אכת'ר וא עצ'ם מנהם",
         "and make of you a nation more numerous and mightier than they.'"),
    ],
    13: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוָה", "פקאל מוסי' ללה", "And Moses said to God"),
        ("וְשָׁמְעוּ מִצְרַיִם כִּי-הֶעֱלִיתָ בְכֹחֲךָ אֶת-הָעָם הַזֶּה מִקִּרְבּוֹ",
         "ויסמעון אלמצריון. אלד'י אצעדת הולאי אלקום מן בינהם בקדרתך",
         "'Yet the Egyptians will hear — You who brought these people up from among them by Your power —'"),
    ],
    14: [
        ("וְאָמְרוּ אֶל-יוֹשֵׁב הָאָרֶץ הַזֹּאת שָׁמְעוּ",
         "פיקולון מע אהל הד'א אלבלד. אלד'י סמעו",
         "'and they will tell, together with the inhabitants of this land who have heard"),
        ("כִּי-אַתָּה יְהוָה בְּקֶרֶב הָעָם הַזֶּה", "אנך אללה. נורך פי מא בין הולאי אלקום",
         "that You are God: Your light is among these people"),
        ("אֲשֶׁר-עַיִן בְּעַיִן נִרְאָה אַתָּה יְהוָה", "עין בעין ירונה",
         "seen eye to eye"),
        ("וַעֲנָנְךָ עֹמֵד עֲלֵהֶם", "וג'מאמך מקים עליהם",
         "and Your clouds rest upon them"),
        ("וּבְעַמֻּד עָנָן אַתָּה הֹלֵךְ לִפְנֵיהֶם יוֹמָם וּבְעַמּוּד אֵשׁ לָיְלָה",
         "ובעמוד ג'מאם תסיר בין ידיהם נהארא. ובעמוד נאר לילא",
         "and in a pillar of cloud You go before them by day, and in a pillar of fire by night.'"),
    ],
    15: [
        ("וְהֵמַתָּה אֶת-הָעָם הַזֶּה כְּאִישׁ אֶחָד",
         "פאד'א קתלתהם אגמעין כרג'ל ואחד",
         "'And if You slay them all as one man"),
        ("וְאָמְרוּ הַגּוֹיִם אֲשֶׁר-שָׁמְעוּ אֶת-שִׁמְעֲךָ לֵאמֹר",
         "קאל גמיע אלאמם. אלד'י סמעו אכ'ברך הד'ה קאילין",
         "then all the nations who have heard these reports of You will say:'"),
    ],
    16: [
        ("מִבִּלְתִּי יְכֹלֶת יְהוָה לְהָבִיא אֶת-הָעָם הַזֶּה אֶל-הָאָרֶץ",
         "ממא לם יטיק אלרב. אן ידכ'ל הולאי אלקום. אלי' אלבלד",
         "'It was because the Lord was unable to bring these people into the land"),
        ("אֲשֶׁר-נִשְׁבַּע לָהֶם וַיִּשְׁחָטֵם בַּמִּדְבָּר",
         "אלד'י ועדהם בה. פקתלהם פי אלבר",
         "which He had promised them — so He slew them in the wilderness.'"),
    ],
    17: [
        ("וְעַתָּה יִגְדַּל-נָא כֹּחַ אֲדֹנָי", "ואלאן יתביין עצ'ם קדרתך יא רב",
         "'And now, let the greatness of Your power be made manifest, O Lord"),
        ("כַּאֲשֶׁר דִּבַּרְתָּ לֵאמֹר", "כמא קלת לי", "as You spoke to me.'"),
    ],
    18: [
        ("יְהוָה אֶרֶךְ אַפַּיִם וְרַב-חֶסֶד", "אנך אללה. טויל אלמהל כת'יר אלפצ'ל",
         "'That You are God — long in forbearance, abounding in grace"),
        ("נֹשֵׂא עָו‍ֹן וָפָשַׁע", "ג'אפר אלד'נב ואלגרם",
         "forgiving iniquity together with transgression"),
        ("וְנַקֵּה לֹא יְנַקֶּה", "ויברי ולא יברי",
         "and acquits, yet does not wholly acquit"),
        ("פֹּקֵד עֲו‍ֹן אָבוֹת עַל-בָּנִים עַל-שִׁלֵּשִׁים וְעַל-רִבֵּעִים",
         "מטאלב בד'נוב אלאבא מע אלבנין. ואלת'ואלת' ואלרואבע",
         "visiting the iniquities of the fathers upon the sons, and upon the third and upon the fourth generation.'"),
    ],
    19: [
        ("סְלַח-נָא לַעֲו‍ֹן הָעָם הַזֶּה", "אצפח ד'נב הולאי אלקום",
         "'Pardon the iniquity of these people"),
        ("כְּגֹדֶל חַסְדֶּךָ", "בכת'רה' פצ'לך", "according to the abundance of Your grace"),
        ("וְכַאֲשֶׁר נָשָׂאתָה לָעָם הַזֶּה מִמִּצְרַיִם וְעַד-הֵנָּה",
         "וכמא אחתמלת להם. מן מצר ואלי' אלאן",
         "and as You have borne with them from Egypt until now.'"),
    ],
    20: [
        ("וַיֹּאמֶר יְהוָה סָלַחְתִּי כִּדְבָרֶךָ",
         "קאל אללה. קד צפחת ענהם אלמעאגלה כמא קלת",
         "And God said: 'I have pardoned them from immediate punishment, as you have said.'"),
    ],
    21: [
        ("וְאוּלָם חַי-אָנִי", "ולכן ובקאי אלדאים", "'Yet — by My eternal existence"),
        ("וְיִמָּלֵא כְבוֹד-יְהוָה אֶת-כָּל-הָאָרֶץ",
         "ונורי אלד'י ימלא גמיע אלעאלם",
         "and by My light which fills all the world —'"),
    ],
    22: [
        ("כִּי כָל-הָאֲנָשִׁים הָרֹאִים אֶת-כְּבֹדִי וְאֶת-אֹתֹתַי",
         "אן גמיע אלרגאל. אלד'י ראו כרמי ואיאתי",
         "'Surely all the men who saw My generosity and My signs"),
        ("אֲשֶׁר-עָשִׂיתִי בְמִצְרַיִם וּבַמִּדְבָּר", "אלתי צנעתהא פי מצר ופי אלבר",
         "which I performed in Egypt and in the wilderness"),
        ("וַיְנַסּוּ אֹתִי זֶה עֶשֶׂר פְּעָמִים", "ואמתחנוני הד'ה אלמרה אלעשארה",
         "and who tested Me now this tenth time"),
        ("וְלֹא שָׁמְעוּ בְּקוֹלִי", "ולם יקבלו אמרי",
         "and did not accept My command —'"),
    ],
    23: [
        ("אִם-יִרְאוּ אֶת-הָאָרֶץ אֲשֶׁר נִשְׁבַּעְתִּי לַאֲבֹתָם",
         "אן ראו אלבלד. אלד'י אקסמת לאבאיהם",
         "'they shall not see the land which I swore to their fathers"),
        ("וְכָל-מְנַאֲצַי לֹא יִרְאוּהָ", "וכדאלך כל מן יעציני לא יראה",
         "and likewise every one who defies Me shall not see it.'"),
    ],
    24: [
        ("וְעַבְדִּי כָלֵב עֵקֶב הָיְתָה רוּחַ אַחֶרֶת עִמּוֹ",
         "ואמא עבדי כלב. פגזא מא כאן לה ראי אכ'ר",
         "'But My servant Caleb — as recompense for his having held a different view"),
        ("וַיְמַלֵּא אַחֲרָי", "אתבע בה טאעתי", "following obedience to Me thereby"),
        ("וַהֲבִיאֹתִיו אֶל-הָאָרֶץ אֲשֶׁר-בָּא שָׁמָּה",
         "לאדכ'לה אלי' אלבלד אלד'י צאר אליה",
         "him I will bring into the land which he reached"),
        ("וְזַרְעוֹ יוֹרִשֶׁנָּה", "ולנסלה יורתה",
         "and for his offspring he shall pass it on as an inheritance.'"),
    ],
    25: [
        ("וְהָעֲמָלֵקִי וְהַכְּנַעֲנִי יוֹשֵׁב בָּעֵמֶק",
         "ואלאן פאלעמלאקיין ואלכנעאניין מקימין פי אלמרג",
         "'And now, the Amalekites and the Canaanites are dwelling in the valley."),
        ("מָחָר פְּנוּ וּסְעוּ לָכֶם הַמִּדְבָּר", "פולו מן ג'ד וארחלו. אלי' אלבר",
         "Turn back tomorrow and set out into the wilderness"),
        ("דֶּרֶךְ יַם-סוּף", "טריק בחר אלקלזם", "by the way of the Sea of Qulzum.'"),
    ],
    26: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי' והרון תכלימא",
         "Then God spoke to Moses and Aaron, saying:"),
    ],
    27: [
        ("עַד-מָתַי לָעֵדָה הָרָעָה הַזֹּאת", "אלי' כם אבקי הד'ה אלגמאעה אלרדייה",
         "'How long shall I leave this wicked congregation"),
        ("אֲשֶׁר הֵמָּה מַלִּינִים עָלָי", "אלד'י ד'מרת אלאמה עליי",
         "which has incited the nation against Me?"),
        ("אֶת-תְּלֻנּוֹת בְּנֵי יִשְׂרָאֵל אֲשֶׁר הֵמָּה מַלִּינִים עָלַי--שָׁמָעְתִּי",
         "לקד סמעת תד'מר בני אסראיל. אלד'י תד'מרו עליי",
         "I have indeed heard the grumbling of the sons of Israel, who grumbled against Me.'"),
    ],
    28: [
        ("אֱמֹר אֲלֵהֶם", "אלא קל להם", "'Say to them"),
        ("חַי-אָנִי נְאֻם-יְהוָה", "ובקאי אלדאים יקול אללה",
         "By My eternal existence — says God"),
        ("אִם-לֹא כַּאֲשֶׁר דִּבַּרְתֶּם בְּאָזְנָי כֵּן אֶעֱשֶׂה לָכֶם",
         "אן לם אצנע בכם. כמא קלתם בחצ'רתי",
         "if I do not deal with you as you have said in My presence!'"),
    ],
    29: [
        ("בַּמִּדְבָּר הַזֶּה יִפְּלוּ פִגְרֵיכֶם", "ופי הד'א אלבר תקע אגסאדכם",
         "'In this wilderness shall your bodies fall"),
        ("וְכָל-פְּקֻדֵיכֶם לְכָל-מִסְפַּרְכֶם מִבֶּן עֶשְׂרִים שָׁנָה וָמָעְלָה",
         "מן כל מעדוד ומחצא מנכם. מן אבן עשרין סנה פצאעדא",
         "from every one counted and numbered among you, from twenty years of age and upward"),
        ("אֲשֶׁר הֲלִינֹתֶם עָלָי", "כמא תד'מרתם עליי",
         "even as you grumbled against Me.'"),
    ],
    30: [
        ("אִם-אַתֶּם תָּבֹאוּ אֶל-הָאָרֶץ אֲשֶׁר נָשָׂאתִי אֶת-יָדִי לְשַׁכֵּן אֶתְכֶם בָּהּ",
         "אן אנתם דכ'לתם אלבלד. אלד'י אקסמת באמרי. אן אסכנכם פיה",
         "'You shall not enter the land concerning which I swore by My word to settle you in it"),
        ("כִּי אִם-כָּלֵב בֶּן-יְפֻנֶּה וִיהוֹשֻׁעַ בִּן-נוּן",
         "אלא כלב אבן יפנה. ויהושע אבן נון",
         "except Caleb son of Jephunneh and Joshua son of Nun.'"),
    ],
    31: [
        ("וְטַפְּכֶם--אֲשֶׁר אֲמַרְתֶּם לָבַז יִהְיֶה",
         "ואטפאלכם. אלד'י קלתם אנהם יצירו ג'נימה",
         "'And your children, whom you said would become spoil"),
        ("וְהֵבֵיאתִי אֹתָם", "פאני אדכ'להם", "them I will bring in"),
        ("וְיָדְעוּ אֶת-הָאָרֶץ אֲשֶׁר מְאַסְתֶּם בָּהּ",
         "חתא יערפון פצ'ילה' אלבלד. אלד'י זהדתם פיה",
         "so that they may know the excellence of the land which you have despised.'"),
    ],
    32: [
        ("וּפִגְרֵיכֶם אַתֶּם--יִפְּלוּ בַּמִּדְבָּר הַזֶּה",
         "אמא אגסאדכם אנתם. פתקע פי הד'א אלבר",
         "'But your bodies — you yourselves — shall fall in this wilderness.'"),
    ],
    33: [
        ("וּבְנֵיכֶם יִהְיוּ רֹעִים בַּמִּדְבָּר אַרְבָּעִים שָׁנָה",
         "ובניכם. יקימון תאיהין פי אלבר ארבעין סנה",
         "'And your sons shall remain wandering in the wilderness forty years"),
        ("וְנָשְׂאוּ אֶת-זְנוּתֵיכֶם", "ויחמלון טג'יאנכם",
         "and shall bear the burden of your rebellion"),
        ("עַד-תֹּם פִּגְרֵיכֶם בַּמִּדְבָּר", "אלי'' פנא אגסאדכם פיה",
         "until the perishing of your bodies therein.'"),
    ],
    34: [
        ("בְּמִסְפַּר הַיָּמִים אֲשֶׁר-תַּרְתֶּם אֶת-הָאָרֶץ אַרְבָּעִים יוֹם",
         "באחצא אלאייאם. אלד'י רמתם אלבלד פיהא ארבעין יומא",
         "'By the count of the days in which you sought out the land — forty days"),
        ("יוֹם לַשָּׁנָה יוֹם לַשָּׁנָה תִּשְׂאוּ אֶת-עֲו‍ֹנֹתֵיכֶם אַרְבָּעִים שָׁנָה",
         "לכל יום סנה. תחמלון אוזארכם. אלי' תמאם ארבעין סנה",
         "a year for each day — you shall bear your burdens for a full forty years"),
        ("וִידַעְתֶּם אֶת-תְּנוּאָתִי", "פתערפון מוצ'ע אענאתי",
         "and you shall come to know the consequence of My displeasure.'"),
    ],
    35: [
        ("אֲנִי יְהוָה דִּבַּרְתִּי", "אנא אללה קלת ד'אלך ואצנעה",
         "'I, God, have spoken this and I will do it"),
        ("לְכָל-הָעֵדָה הָרָעָה הַזֹּאת הַנּוֹעָדִים עָלָי",
         "בגמיע הד'ה אלגמאעה אלרדייה. אלמגתמעה עליי",
         "against all this wicked congregation, gathered against Me"),
        ("בַּמִּדְבָּר הַזֶּה יִתַּמּוּ וְשָׁם יָמֻתוּ",
         "פי הד'א אלבר יפנון באלמות",
         "in this wilderness they shall perish by death.'"),
    ],
    36: [
        ("וְהָאֲנָשִׁים אֲשֶׁר-שָׁלַח מֹשֶׁה לָתוּר אֶת-הָאָרֶץ",
         "ואלרגאל אלד'י בעת' בהם מוסי' לירומו אלבלד",
         "And the men whom Moses had sent to seek out the land"),
        ("וַיָּשֻׁבוּ וילונו (וַיַּלִּינוּ) עָלָיו אֶת-כָּל-הָעֵדָה",
         "פרגעו וד'מרו עליה אלגמאעה",
         "who returned and incited the congregation against him"),
        ("לְהוֹצִיא דִבָּה עַל-הָאָרֶץ", "ואכ'רגו שנאעה עלי' אלבלד",
         "and spread a reproach upon the land —"),
    ],
    37: [
        ("וַיָּמֻתוּ הָאֲנָשִׁים מוֹצִאֵי דִבַּת-הָאָרֶץ רָעָה--בַּמַּגֵּפָה לִפְנֵי יְהוָה",
         "פמאת אולאיך אלרגאל. באלצדאם בין ידי אללה",
         "those men died by a blow before God."),
    ],
    38: [
        ("וִיהוֹשֻׁעַ בִּן-נוּן וְכָלֵב בֶּן-יְפֻנֶּה",
         "ויהושע אבן נון. וכלב אבן יפונה",
         "But Joshua son of Nun and Caleb son of Jephunneh"),
        ("חָיוּ מִן-הָאֲנָשִׁים הָהֵם הַהֹלְכִים לָתוּר אֶת-הָאָרֶץ",
         "עאשו מן ג'מלה' אלרגאל. אלד'י מצ'ו לירומו אלבלד",
         "lived, from among the men who had gone to seek out the land."),
    ],
    39: [
        ("וַיְדַבֵּר מֹשֶׁה אֶת-הַדְּבָרִים הָאֵלֶּה אֶל-כָּל-בְּנֵי יִשְׂרָאֵל",
         "ולמא כלם מוסי'' בהד'א אלכלאם. גמאעה' בני אסראיל",
         "And when Moses spoke these words to the congregation of the sons of Israel"),
        ("וַיִּתְאַבְּלוּ הָעָם מְאֹד", "פחזן אלקום גדא", "the people grieved greatly."),
    ],
    40: [
        ("וַיַּשְׁכִּמוּ בַבֹּקֶר וַיַּעֲלוּ אֶל-רֹאשׁ-הָהָר",
         "ואדלגו באלג'דאה. וצעדו אלי' ראס אלגבל",
         "And they rose early in the morning and went up to the top of the mountain"),
        ("לֵאמֹר הִנֶּנּוּ וְעָלִינוּ אֶל-הַמָּקוֹם אֲשֶׁר-אָמַר יְהוָה",
         "וקאלו. הא נחן צאעדין. אלי' אלמוצ'ע. אלד'י אמרנא אללה",
         "and said: 'Here we are, and we will go up to the place which God commanded us"),
        ("כִּי חָטָאנוּ", "פקד אכ'טאנא", "for we have indeed sinned.'"),
    ],
    41: [
        ("וַיֹּאמֶר מֹשֶׁה לָמָּה זֶּה אַתֶּם עֹבְרִים אֶת-פִּי יְהוָה",
         "קאל להם מוסי'. יא קום לא תתגאוזו אמר אללה",
         "Moses said to them: 'O people, do not transgress the command of God"),
        ("וְהִוא לֹא תִצְלָח", "פאנהא לא תנגח", "for it will not succeed.'"),
    ],
    42: [
        ("אַל-תַּעֲלוּ כִּי אֵין יְהוָה בְּקִרְבְּכֶם",
         "לא תצעדו. אן נור אללה ליס הו מעכם",
         "'Do not go up — for the light of God is not with you"),
        ("וְלֹא תִּנָּגְפוּ לִפְנֵי אֹיְבֵיכֶם", "ולא תנצדמו. בין ידי אעדאיכם",
         "lest you be struck down before your enemies.'"),
    ],
    43: [
        ("כִּי הָעֲמָלֵקִי וְהַכְּנַעֲנִי שָׁם לִפְנֵיכֶם",
         "פאן אלעמאלקה ואלכנעאניין ת'ם בין אידיכם",
         "'For the Amalekites and the Canaanites are there before you"),
        ("וּנְפַלְתֶּם בֶּחָרֶב", "פתקעון באלסיף", "and you will fall by the sword"),
        ("כִּי-עַל-כֵּן שַׁבְתֶּם מֵאַחֲרֵי יְהוָה", "לאנכם רגעתם ען טאעה' אללה",
         "because you have turned back from obedience to God"),
        ("וְלֹא-יִהְיֶה יְהוָה עִמָּכֶם", "פלא יכון אללה מעכם",
         "and God will not be with you.'"),
    ],
    44: [
        ("וַיַּעְפִּלוּ לַעֲלוֹת אֶל-רֹאשׁ הָהָר",
         "פאעתדו. וצעדו אלי' ראס אלגבל",
         "Yet they acted presumptuously and went up to the top of the mountain"),
        ("וַאֲרוֹן בְּרִית-יְהוָה וּמֹשֶׁה לֹא-מָשׁוּ מִקֶּרֶב הַמַּחֲנֶה",
         "וצנדוק עהד אללה ומוסי. לם יזולא מן וסט אלעסכר",
         "but the ark of the covenant of God and Moses did not stir from the midst of the camp."),
    ],
    45: [
        ("וַיֵּרֶד הָעֲמָלֵקִי וְהַכְּנַעֲנִי הַיֹּשֵׁב בָּהָר הַהוּא",
         "פנזל אלעמלאקיין ואלכנעאניין. אלמקימין פי ד'אלך אלגבל",
         "And the Amalekites and the Canaanites who dwelt in that mountain came down"),
        ("וַיַּכּוּם וַיַּכְּתוּם עַד-הַחָרְמָה", "פצ'רבוהם וחטמוהם אלי' חרמה",
         "and struck them and shattered them as far as Hormah."),
    ],
}
