"""Hand-authored alignment triples for Bamidbar chapter 9."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְמִדְבַּר-סִינַי", "וקבל ד'אלך כלם אללה מוסי' פי ברייה' סיני",
         "And before that, God spoke to Moses in the wilderness of Sinai"),
        ("בַּשָּׁנָה הַשֵּׁנִית לְצֵאתָם מֵאֶרֶץ מִצְרַיִם", "פי אלסנה אלתאניה. לכ'רוגהם מן בלד מצר",
         "in the second year of their departure from the land of Egypt"),
        ("בַּחֹדֶשׁ הָרִאשׁוֹן--לֵאמֹר", "פי אלשהר אלאוול קאילא", "in the first month, saying:"),
    ],
    2: [
        ("וְיַעֲשׂוּ בְנֵי-יִשְׂרָאֵל אֶת-הַפָּסַח בְּמוֹעֲדוֹ",
         "ויצנעו בני אסראיל. אלפסח פי וקתה",
         "\"Let the sons of Israel perform the Passover at its appointed time.\""),
    ],
    3: [
        ("בְּאַרְבָּעָה עָשָׂר-יוֹם בַּחֹדֶשׁ הַזֶּה", "פי אליום אלראבע עשר. מן הד'א אלשהר",
         "\"On the fourteenth day of this month"),
        ("בֵּין הָעַרְבַּיִם תַּעֲשׂוּ אֹתוֹ--בְּמֹעֲדוֹ", "בין אלג'רובין. תצנעוה פי וקתה",
         "between the two sunsets, you shall perform it at its appointed time"),
        ("כְּכָל-חֻקֹּתָיו וּכְכָל-מִשְׁפָּטָיו תַּעֲשׂוּ אֹתוֹ", "כגמיע רסומה ואחכאמה תצנעוה",
         "according to all its statutes and ordinances you shall perform it.\""),
    ],
    4: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-בְּנֵי יִשְׂרָאֵל לַעֲשֹׂת הַפָּסַח",
         "פכלם מוסי' בני אסראיל פי עמל אלפסח",
         "And Moses spoke to the sons of Israel concerning the performance of the Passover."),
    ],
    5: [
        ("וַיַּעֲשׂוּ אֶת-הַפֶּסַח בָּרִאשׁוֹן בְּאַרְבָּעָה עָשָׂר יוֹם לַחֹדֶשׁ בֵּין הָעַרְבַּיִם",
         "פעמלוה פי אלשהר אלאוול. פי אליום אלראבע עשר מנה. בין אלג'רובין",
         "And they performed it in the first month, on the fourteenth day of it, between the two sunsets"),
        ("בְּמִדְבַּר סִינָי כְּכֹל אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "פי ברייה' סיני. כגמיע מא אמר אללה מוסי'",
         "in the wilderness of Sinai — according to all that God had commanded Moses"),
        ("כֵּן עָשׂוּ בְּנֵי יִשְׂרָאֵל", "כד'אך צנעו בני אסראיל", "so did the sons of Israel."),
    ],
    6: [
        ("וַיְהִי אֲנָשִׁים אֲשֶׁר הָיוּ טְמֵאִים לְנֶפֶשׁ אָדָם",
         "פכאן פיהם אנאס. תנגסו במיית מן אלנאס",
         "And there were among them people who had become impure from a dead person"),
        ("וְלֹא-יָכְלוּ לַעֲשֹׂת-הַפֶּסַח בַּיּוֹם הַהוּא", "פלם יגוז להם אן יעמלו אלפסח פי ד'אלך אליום",
         "and it was not permitted for them to perform the Passover on that day"),
        ("וַיִּקְרְבוּ לִפְנֵי מֹשֶׁה וְלִפְנֵי אַהֲרֹן--בַּיּוֹם הַהוּא",
         "פתקדמו פיה. בין ידי מוסי' והרון",
         "so they came forward regarding it, before Moses and Aaron."),
    ],
    7: [
        ("וַיֹּאמְרוּ הָאֲנָשִׁים הָהֵמָּה אֵלָיו אֲנַחְנוּ טְמֵאִים לְנֶפֶשׁ אָדָם",
         "וקאלו. נחן אנגאס מן מיית מן אלנאס",
         "And they said: \"We are impure from a dead person"),
        ("לָמָּה נִגָּרַע לְבִלְתִּי הַקְרִיב אֶת-קָרְבַּן יְהוָה בְּמֹעֲדוֹ",
         "פלם נמנע. מן אן נקרב מת'ל קרבאן אללה פי וקתה",
         "why then should we be prevented from bringing the offering of God at its appointed time"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "פי מא בין בני אסראיל",
         "among the sons of Israel?\""),
    ],
    8: [
        ("וַיֹּאמֶר אֲלֵהֶם מֹשֶׁה עִמְדוּ", "פקאל להם מוסי'. קפו",
         "And Moses said to them: \"Wait"),
        ("וְאֶשְׁמְעָה מַה-יְצַוֶּה יְהוָה לָכֶם", "חתא אסמע. מא יאמר אללה פיכם",
         "until I hear what God will command concerning you.\""),
    ],
    9: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    10: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר", "מר בני אסראיל קאילא",
         "\"Command the sons of Israel, saying"),
        ("אִישׁ אִישׁ כִּי-יִהְיֶה-טָמֵא לָנֶפֶשׁ אוֹ בְדֶרֶךְ רְחֹקָה לָכֶם אוֹ לְדֹרֹתֵיכֶם",
         "אי אנסאן כאן נגס מן מיית. או פי ספר מנכם. או מן אגיאלכם",
         "Any person who has been impure from a dead person, or is on a journey from among you, or from your generations"),
        ("וְעָשָׂה פֶסַח לַיהוָה", "פיצנע פסחא ללה",
         "let him perform a Passover for God."),
    ],
    11: [
        ("בַּחֹדֶשׁ הַשֵּׁנִי בְּאַרְבָּעָה עָשָׂר יוֹם בֵּין הָעַרְבַּיִם",
         "פי אלשהר אלת'אני. פי אליום אלראבע עשר מנה. בין אלג'רובין",
         "In the second month, on the fourteenth day of it, between the two sunsets"),
        ("יַעֲשׂוּ אֹתוֹ עַל-מַצּוֹת וּמְרֹרִים יֹאכְלֻהוּ",
         "אצנעוה פי וקתה. מע פטיר ומראר יאכלונה",
         "perform it at its appointed time; with unleavened bread and bitter herbs they shall eat it."),
    ],
    12: [
        ("לֹא-יַשְׁאִירוּ מִמֶּנּוּ עַד-בֹּקֶר", "לא יבקו מנה אלי' אלג'דאה",
         "They shall leave none of it until the morning"),
        ("וְעֶצֶם לֹא יִשְׁבְּרוּ-בוֹ", "ולא יכסרו מנה עצ'מא",
         "nor shall they break a bone of it"),
        ("כְּכָל-חֻקַּת הַפֶּסַח יַעֲשׂוּ אֹתוֹ", "וכסאיר רסום אלפסח יצנעוה",
         "and according to the rest of the statutes of the Passover they shall perform it."),
    ],
    13: [
        ("וְהָאִישׁ אֲשֶׁר-הוּא טָהוֹר וּבְדֶרֶךְ לֹא-הָיָה וְחָדַל לַעֲשׂוֹת הַפֶּסַח",
         "ואי רגל כאן טאהר ולם יכון פי ספר. ואמתנע אן יעמל אלפסח",
         "But any man who is pure and was not on a journey, and refrained from performing the Passover"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעַמֶּיהָ", "פינקטע ד'אלך אלאנסאן מן בין קומה",
         "that person shall be cut off from among his people"),
        ("כִּי קָרְבַּן יְהוָה לֹא הִקְרִיב בְּמֹעֲדוֹ", "אד' לם יקרב קרבאן אללה פי וקתה",
         "since he did not bring the offering of God at its appointed time"),
        ("חֶטְאוֹ יִשָּׂא הָאִישׁ הַהוּא", "פקד חמל ד'אלך אלרגל וזרה",
         "that man has borne his guilt."),
    ],
    14: [
        ("וְכִי-יָגוּר אִתְּכֶם גֵּר וְעָשָׂה פֶסַח לַיהוָה", "ואן דכ'ל פיכם דכ'יל. פליצנע פסחא ללה",
         "And if a stranger enters among you, let him perform a Passover for God"),
        ("כְּחֻקַּת הַפֶּסַח וּכְמִשְׁפָּטוֹ כֵּן יַעֲשֶׂה", "כרסם אלפסח וחכמה כד'אך יצנע",
         "according to the statute of the Passover and its ordinance, so shall he perform it"),
        ("חֻקָּה אַחַת יִהְיֶה לָכֶם וְלַגֵּר וּלְאֶזְרַח הָאָרֶץ",
         "אד' שריעה ואחדה תכון לכם. לאלדכ'יל וצריח אלאמה",
         "for one law shall there be for you, for the stranger and for the native-born of the nation.\""),
    ],
    15: [
        ("וּבְיוֹם הָקִים אֶת-הַמִּשְׁכָּן כִּסָּה הֶעָנָן אֶת-הַמִּשְׁכָּן לְאֹהֶל הָעֵדֻת",
         "ומן יום נצב אלמסכן גטאה אלג'מאם עלי' כ'בא אלשהאדה",
         "And on the day of the erection of the tabernacle, the cloud covered it — over the tent of testimony"),
        ("וּבָעֶרֶב יִהְיֶה עַל-הַמִּשְׁכָּן כְּמַרְאֵה-אֵשׁ--עַד-בֹּקֶר",
         "ובאלליל יכון עליה. כרויא נאר אלי' אלג'דאה",
         "and at night it would be upon it, like the appearance of fire until the morning."),
    ],
    16: [
        ("כֵּן יִהְיֶה תָמִיד הֶעָנָן יְכַסֶּנּוּ", "כד'אך יכון דאימא. אלג'מאם יג'טיה נהארא",
         "So it would be continually: the cloud covering it by day"),
        ("וּמַרְאֵה-אֵשׁ לָיְלָה", "ורויא אלנאר לילא", "and the appearance of fire by night."),
    ],
    17: [
        ("וּלְפִי הֵעָלוֹת הֶעָנָן מֵעַל הָאֹהֶל", "ועלי' קדר ארתפאע אלג'מאם ען אלכ'בא",
         "And according to the lifting of the cloud from upon the tent"),
        ("וְאַחֲרֵי כֵן יִסְעוּ בְּנֵי יִשְׂרָאֵל", "פבעד ד'אלך ירחלון בני אסראיל",
         "after that the sons of Israel would set out"),
        ("וּבִמְקוֹם אֲשֶׁר יִשְׁכָּן-שָׁם הֶעָנָן--שָׁם יַחֲנוּ בְּנֵי יִשְׂרָאֵל",
         "ופי מוצ'ע יסכן פיה אלג'מאם. ת'ם ינזלון בני אסראיל",
         "and in the place where the cloud would settle, there the sons of Israel would encamp."),
    ],
    18: [
        ("עַל-פִּי יְהוָה יִסְעוּ בְּנֵי יִשְׂרָאֵל וְעַל-פִּי יְהוָה יַחֲנוּ",
         "עלי' קול אללה. ירחל בני אסראיל. ועלי' קולה ינזלון",
         "At the word of God the sons of Israel would set out, and at His word they would encamp"),
        ("כָּל-יְמֵי אֲשֶׁר יִשְׁכֹּן הֶעָנָן עַל-הַמִּשְׁכָּן--יַחֲנוּ",
         "פהם טול מדה' מא יסכן אלג'מאם. עלי' אלמסכן מקימין",
         "all the duration of the time that the cloud dwelt upon the tabernacle, they remained encamped."),
    ],
    19: [
        ("וּבְהַאֲרִיךְ הֶעָנָן עַל-הַמִּשְׁכָּן יָמִים רַבִּים",
         "ואן טאל אלג'מאם. אייאמא כת'ירה עלי' אלמסכן",
         "And if the cloud lingered many days upon the tabernacle"),
        ("וְשָׁמְרוּ בְנֵי-יִשְׂרָאֵל אֶת-מִשְׁמֶרֶת יְהוָה וְלֹא יִסָּעוּ",
         "פיחפץ' בני אסראיל. חפץ' אללה ולא ירחלון",
         "the sons of Israel would observe the charge of God and not set out."),
    ],
    20: [
        ("וְיֵשׁ אֲשֶׁר יִהְיֶה הֶעָנָן יָמִים מִסְפָּר--עַל-הַמִּשְׁכָּן",
         "ורבמא כאן אלג'מאם אייאמא מחצאה עלי' אלמסכן",
         "And sometimes the cloud was upon the tabernacle for a number of countable days"),
        ("עַל-פִּי יְהוָה יַחֲנוּ וְעַל-פִּי יְהוָה יִסָּעוּ",
         "פהם עלי' קול אללה ינזלו ועלי' קולה ירחלון",
         "they would encamp at the word of God, and at His word they would set out."),
    ],
    21: [
        ("וְיֵשׁ אֲשֶׁר-יִהְיֶה הֶעָנָן מֵעֶרֶב עַד-בֹּקֶר", "ורבמא כאן אלג'מאם מן אלמסא אלי' אלצבאח",
         "And sometimes the cloud was from evening until morning"),
        ("וְנַעֲלָה הֶעָנָן בַּבֹּקֶר וְנָסָעוּ", "ת'ם ירתפע באלג'דאה וירחלון",
         "then it would lift at daybreak and they would set out."),
        ("אוֹ יוֹמָם וָלַיְלָה וְנַעֲלָה הֶעָנָן וְנָסָעוּ", "או נהארא ולילא. ת'ם ירתפע וירחלון",
         "Or a day and a night — then it would lift and they would set out."),
    ],
    22: [
        ("אוֹ-יֹמַיִם אוֹ-חֹדֶשׁ אוֹ-יָמִים בְּהַאֲרִיךְ הֶעָנָן עַל-הַמִּשְׁכָּן לִשְׁכֹּן עָלָיו",
         "או יומין או שהרא או חולא. אד'א טאלת מדה' אלג'מאם עלי' אלמסכן ליסכן עליה",
         "Or two days, or a month, or a full year: whenever the duration of the cloud upon the tabernacle was prolonged, to dwell upon it"),
        ("יַחֲנוּ בְנֵי-יִשְׂרָאֵל וְלֹא יִסָּעוּ", "בני אסראיל מקימין ג'יר ראחלין",
         "the sons of Israel remained encamped and did not set out"),
        ("וּבְהֵעָלֹתוֹ יִסָּעוּ", "ופי ארתפאעה ירחלון", "and at its lifting they would set out."),
    ],
    23: [
        ("עַל-פִּי יְהוָה יַחֲנוּ וְעַל-פִּי יְהוָה יִסָּעוּ",
         "כד'אך עלי' קול אללה ינזלון. ועלי קולה ירחלון",
         "So at the word of God they would encamp, and at His word they would set out"),
        ("אֶת-מִשְׁמֶרֶת יְהוָה שָׁמָרוּ עַל-פִּי יְהוָה בְּיַד-מֹשֶׁה",
         "ויחפצון מא אסתחפצ'הם. מן קולה ביד מוסי'",
         "and they kept what He had entrusted to them to keep, of His word, by the hand of Moses."),
    ],
}
