"""Hand-authored alignment triples for Bamidbar chapter 32."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וּמִקְנֶה רַב הָיָה לִבְנֵי רְאוּבֵן וְלִבְנֵי-גָד--עָצוּם מְאֹד",
         "ומאשיה כת'ירה. כאנת לבני ראובן. ולבני גד ]עט'ימה] ]עט'ימה] עצ'ימה גדא",
         "And livestock, numerous, belonged to the sons of Reuben and to the sons of Gad — very great."),
        ("וַיִּרְאוּ אֶת-אֶרֶץ יַעְזֵר וְאֶת-אֶרֶץ גִּלְעָד",
         "פראו. בלד יעזר ובלד גרש",
         "And they saw the land of Jazer and the land of Gilead"),
        ("וְהִנֵּה הַמָּקוֹם מְקוֹם מִקְנֶה",
         "ואד'א בה מוצ'ע מאשיה",
         "and behold, it was a place for livestock."),
    ],
    2: [
        ("וַיָּבֹאוּ בְנֵי-גָד וּבְנֵי רְאוּבֵן",
         "פגאו בני גד ובני ראובן",
         "And the sons of Gad and the sons of Reuben came"),
        ("וַיֹּאמְרוּ אֶל-מֹשֶׁה וְאֶל-אֶלְעָזָר הַכֹּהֵן וְאֶל-נְשִׂיאֵי הָעֵדָה לֵאמֹר",
         "וקאלו למוסי' ואלעזר אלאמאם. ואשראף אלגמאעה קאילין",
         "and said to Moses and Eleazar the imām and to the nobles of the congregation, saying:"),
    ],
    3: [
        ("עֲטָרוֹת וְדִיבֹן וְיַעְזֵר וְנִמְרָה וְחֶשְׁבּוֹן וְאֶלְעָלֵה וּשְׂבָם וּנְבוֹ וּבְעֹן",
         "אן עטרות ודיבון ויעזב ונמרה. וחשבון ואלעלה. וסבם ונבו ובעון",
         "that Ataroth, and Dibon, and Jazer, and Nimrah, and Heshbon, and Elaleh, and Sibam, and Nebo, and Beon —"),
    ],
    4: [
        ("הָאָרֶץ אֲשֶׁר הִכָּה יְהוָה לִפְנֵי עֲדַת יִשְׂרָאֵל--אֶרֶץ מִקְנֶה הִוא",
         "אלבלד. אלד'י פתחה אללה בין ידי גמאעה' בני אסראיל. הו בלד יצלח לאלמאשיה",
         "the land which God opened before the congregation of the sons of Israel — it is a land suited for livestock"),
        ("וְלַעֲבָדֶיךָ מִקְנֶה",
         "ולעבידך מואשי",
         "and your servants have livestock."),
    ],
    5: [
        ("וַיֹּאמְרוּ אִם-מָצָאנוּ חֵן בְּעֵינֶיךָ",
         "פקאלו. אן וגדנא חצ'אא ענדך",
         "And they said: if we have found favor with you"),
        ("יֻתַּן אֶת-הָאָרֶץ הַזֹּאת לַעֲבָדֶיךָ לַאֲחֻזָּה",
         "ידפע אלינא הד'א אלבלד נחלה",
         "let this land be given over to us as an inheritance"),
        ("אַל-תַּעֲבִרֵנוּ אֶת-הַיַּרְדֵּן",
         "לא תגיזנא אלארדן",
         "do not bring us across the Jordan."),
    ],
    6: [
        ("וַיֹּאמֶר מֹשֶׁה לִבְנֵי-גָד וְלִבְנֵי רְאוּבֵן",
         "פקאל להם מוסי'",
         "And Moses said to them:"),
        ("הַאַחֵיכֶם יָבֹאוּ לַמִּלְחָמָה וְאַתֶּם תֵּשְׁבוּ פֹה",
         "הל אכ'ותכם ימצ'ון אלי' אלחרב. ואנתם תגלסון ההנא",
         "shall your brothers go forth to war while you sit here?"),
    ],
    7: [
        ("וְלָמָּה תנואון (תְנִיאוּן) אֶת-לֵב בְּנֵי יִשְׂרָאֵל",
         "ולם תגבנון קלוב בני אסראיל",
         "And why do you make the hearts of the sons of Israel faint"),
        ("מֵעֲבֹר אֶל-הָאָרֶץ אֲשֶׁר-נָתַן לָהֶם יְהוָה",
         "מן אלמציר אלי' אלבלד. אלד'י אעטאהם אללה",
         "from journeying to the land which God has given them?"),
    ],
    8: [
        ("כֹּה עָשׂוּ אֲבֹתֵיכֶם בְּשָׁלְחִי אֹתָם מִקָּדֵשׁ בַּרְנֵעַ לִרְאוֹת אֶת-הָאָרֶץ",
         "כד'א צנעו אבאיכם. חין בעת'ת בהם. מן רקים ברנע לירומו אלבלד",
         "Thus did your fathers, when I sent them from Kadesh-barnea to scout out the land."),
    ],
    9: [
        ("וַיַּעֲלוּ עַד-נַחַל אֶשְׁכּוֹל וַיִּרְאוּ אֶת-הָאָרֶץ",
         "פבלג'ו אלי' ואד אלענקוד. וראוה",
         "They reached the Valley of the Cluster and saw the land"),
        ("וַיָּנִיאוּ אֶת-לֵב בְּנֵי יִשְׂרָאֵל--לְבִלְתִּי-בֹא אֶל-הָאָרֶץ אֲשֶׁר-נָתַן לָהֶם יְהוָה",
         "וגבנו קלוב בני אסראיל. מן אן ידכ'לו אלבלד. אלד'י אעטאהם אללה",
         "and they made the hearts of the sons of Israel faint, so that they would not enter the land which God had given them."),
    ],
    10: [
        ("וַיִּחַר-אַף יְהוָה בַּיּוֹם הַהוּא וַיִּשָּׁבַע לֵאמֹר",
         "פאשתד ג'צ'ב אללה פי ד'אלך אלוקת. ואקסם קאילא",
         "And God's wrath intensified at that time, and He swore, saying:"),
    ],
    11: [
        ("אִם-יִרְאוּ הָאֲנָשִׁים הָעֹלִים מִמִּצְרַיִם מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה",
         "אן ראו אלרגאל אלד'י צעדו מן מצר. מן ן' עשרין סנה פצאעדא",
         "'The men who came up from Egypt, from twenty years old and upward, shall not see"),
        ("אֵת הָאֲדָמָה אֲשֶׁר נִשְׁבַּעְתִּי לְאַבְרָהָם לְיִצְחָק וּלְיַעֲקֹב",
         "אלבלד אלד'י אקסמת. לאברהים ויצחק ויעקוב",
         "the land which I swore to Abraham and Isaac and Jacob"),
        ("כִּי לֹא-מִלְאוּ אַחֲרָי",
         "אד' לם יתבעו טאעתי",
         "since they did not follow My obedience."),
    ],
    12: [
        ("בִּלְתִּי כָּלֵב בֶּן-יְפֻנֶּה הַקְּנִזִּי וִיהוֹשֻׁעַ בִּן-נוּן",
         "אלא כלב אבן יפנה אלקנזי. ויהושע אבן נון",
         "Except Caleb son of Jephunneh the Kenizzite and Joshua son of Nun"),
        ("כִּי מִלְאוּ אַחֲרֵי יְהוָה",
         "פאנהמא אתבעא טאעה' אללה",
         "for they followed the obedience of God.'"),
    ],
    13: [
        ("וַיִּחַר-אַף יְהוָה בְּיִשְׂרָאֵל וַיְנִעֵם בַּמִּדְבָּר אַרְבָּעִים שָׁנָה",
         "פלמא אשתד ג'צ'ב אללה עליהם. תווההם פי אלברייה ארבעין סנה",
         "And when God's wrath intensified against them, He led them astray in the wilderness forty years"),
        ("עַד-תֹּם כָּל-הַדּוֹר הָעֹשֶׂה הָרַע בְּעֵינֵי יְהוָה",
         "אלי' אן פני גמיע אלגיל. אלד'י פעל אלשר בין ידי אללה",
         "until the whole generation that had done evil before God had perished."),
    ],
    14: [
        ("וְהִנֵּה קַמְתֶּם תַּחַת אֲבֹתֵיכֶם--תַּרְבּוּת אֲנָשִׁים חַטָּאִים",
         "והד'אכם קד קמתם פי מכאן אבאיכם. עלי' תעלים אלנאס אלכ'אטיין",
         "And behold, you have risen in the place of your fathers — in the teachings of sinful people"),
        ("לִסְפּוֹת עוֹד עַל חֲרוֹן אַף-יְהוָה--אֶל-יִשְׂרָאֵל",
         "לתזידו איצ'א פי שדה' ג'צ'ב אללה עלי' אל אסראיל",
         "to add yet more to the intensity of God's wrath against the house of Israel."),
    ],
    15: [
        ("כִּי תְשׁוּבֻן מֵאַחֲרָיו",
         "לאנכם אן רגעתם ען טאעתה",
         "For if you turn back from His obedience"),
        ("וְיָסַף עוֹד לְהַנִּיחוֹ בַּמִּדְבָּר",
         "זאד פי תרכהם פי אלברייה",
         "He will increase His leaving them in the wilderness"),
        ("וְשִׁחַתֶּם לְכָל-הָעָם הַזֶּה",
         "פתהלכון הולאי אלקום אד'א אמסכו ענכם",
         "and you will bring destruction upon these people if they hold to your view."),
    ],
    16: [
        ("וַיִּגְּשׁוּ אֵלָיו וַיֹּאמְרוּ",
         "פתקדמו אליה וקאלו",
         "Then they came forward to him and said:"),
        ("גִּדְרֹת צֹאן נִבְנֶה לְמִקְנֵנוּ פֹּה וְעָרִים לְטַפֵּנוּ",
         "אנא נבני חצ'אירא למואשינא ההנא. וקרא לאטפלנא",
         "we will build enclosures for our livestock here, and towns for our children."),
    ],
    17: [
        ("וַאֲנַחְנוּ נֵחָלֵץ חֻשִׁים לִפְנֵי בְּנֵי יִשְׂרָאֵל",
         "ונחן נתגרד מסרעין. בין ידי בני אסראיל",
         "And we shall arm ourselves swiftly before the sons of Israel"),
        ("עַד אֲשֶׁר אִם-הֲבִיאֹנֻם אֶל-מְקוֹמָם",
         "אלי' אן נוצלהם אלי' מכאנהם",
         "until we bring them to their place"),
        ("וְיָשַׁב טַפֵּנוּ בְּעָרֵי הַמִּבְצָר מִפְּנֵי יֹשְׁבֵי הָאָרֶץ",
         "פיקים אטפאלנא פי קרא חצינה. מן קבל אהל אלבלד",
         "and our children shall dwell in fortified towns, on account of the inhabitants of the land."),
    ],
    18: [
        ("לֹא נָשׁוּב אֶל-בָּתֵּינוּ",
         "לא נרגע אלי' ביותנא",
         "We shall not return to our homes"),
        ("עַד הִתְנַחֵל בְּנֵי יִשְׂרָאֵל אִישׁ נַחֲלָתוֹ",
         "אלי' אן יחוז כל סבט מן בני אסראיל נחלתה",
         "until every tribe of the sons of Israel has obtained its inheritance."),
    ],
    19: [
        ("כִּי לֹא נִנְחַל אִתָּם מֵעֵבֶר לַיַּרְדֵּן וָהָלְאָה",
         "לאנא לא נחוז מעהם. מן עבר אלארדן אלי' הנאך",
         "For we shall not inherit with them from across the Jordan onward"),
        ("כִּי בָאָה נַחֲלָתֵנוּ אֵלֵינוּ מֵעֵבֶר הַיַּרְדֵּן מִזְרָחָה",
         "אד' קד קבצ'נא נחלתנא. מן עבר אלארדן שרקייא",
         "since we have already received our inheritance from the eastern side of the Jordan."),
    ],
    20: [
        ("וַיֹּאמֶר אֲלֵיהֶם מֹשֶׁה",
         "פקאל להם מוסי'",
         "And Moses said to them:"),
        ("אִם-תַּעֲשׂוּן אֶת-הַדָּבָר הַזֶּה אִם-תֵּחָלְצוּ לִפְנֵי יְהוָה לַמִּלְחָמָה",
         "אן צנעתם הד'א אלאמר. ותגרדתם בין ידי אליה לאלגיש",
         "if you do this thing, and arm yourselves before God for the host,"),
    ],
    21: [
        ("וְעָבַר לָכֶם כָּל-חָלוּץ אֶת-הַיַּרְדֵּן לִפְנֵי יְהוָה",
         "ועבר לכם כל מגרד מנכם. אלארדן בין ידיה",
         "and every armed man among you crosses the Jordan before Him"),
        ("עַד הוֹרִישׁוֹ אֶת-אֹיְבָיו מִפָּנָיו",
         "אלי' אן יקרץ' אעדאיה מן בין ידיה",
         "until He cuts off His enemies from before Him —"),
    ],
    22: [
        ("וְנִכְבְּשָׁה הָאָרֶץ לִפְנֵי יְהוָה",
         "ואד'א פתח אלבלד. בין ידיה",
         "and when the land is opened before Him"),
        ("וְאַחַר תָּשֻׁבוּ--וִהְיִיתֶם נְקִיִּם מֵיְהוָה וּמִיִּשְׂרָאֵל",
         "פבעד ד'אלך תרגעון. פתכונון אבריא. ענד אללה וענד אל אסראיל",
         "after that you shall return, and you shall be acquitted before God and before the house of Israel"),
        ("וְהָיְתָה הָאָרֶץ הַזֹּאת לָכֶם לַאֲחֻזָּה--לִפְנֵי יְהוָה",
         "ויכון הד'א אלבלד לכם. חוזא בין ידיה",
         "and this land shall be yours as a possession before Him —"),
    ],
    23: [
        ("וְאִם-לֹא תַעֲשׂוּן כֵּן הִנֵּה חֲטָאתֶם לַיהוָה",
         "ואן לם תצנעון כד'אך. פקד אכ'טאתם ללה",
         "but if you do not do thus, you have sinned against God"),
        ("וּדְעוּ חַטַּאתְכֶם אֲשֶׁר תִּמְצָא אֶתְכֶם",
         "ואעתרפו בכ'טאיאכם אד'א נאלתכם עקובתה",
         "and acknowledge your sins when His punishment reaches you."),
    ],
    24: [
        ("בְּנוּ-לָכֶם עָרִים לְטַפְּכֶם וּגְדֵרֹת לְצֹנַאֲכֶם",
         "אבנו לכם קרא לאטפאלכם. וחצ'אירא לג'נמכם",
         "Build yourselves towns for your children, and enclosures for your flocks"),
        ("וְהַיֹּצֵא מִפִּיכֶם תַּעֲשׂוּ",
         "ומא כ'רג מן פמכם אצנעוה",
         "and what has gone out of your mouth — carry it out."),
    ],
    25: [
        ("וַיֹּאמֶר בְּנֵי-גָד וּבְנֵי רְאוּבֵן אֶל-מֹשֶׁה לֵאמֹר",
         "קאלו לה",
         "They said to him:"),
        ("עֲבָדֶיךָ יַעֲשׂוּ כַּאֲשֶׁר אֲדֹנִי מְצַוֶּה",
         "עבידך יצנעון. כמא יאמרהם סיידנא",
         "your servants shall do as our lord commands them."),
    ],
    26: [
        ("טַפֵּנוּ נָשֵׁינוּ מִקְנֵנוּ וְכָל-בְּהֶמְתֵּנוּ--יִהְיוּ-שָׁם בְּעָרֵי הַגִּלְעָד",
         "אטפאלנא ונסאנא. מואשינא וסאיר בהאימנא. יקימון פי בלד גרש",
         "Our children and our women, our livestock and the rest of our beasts, shall dwell in the land of Gilead."),
    ],
    27: [
        ("וַעֲבָדֶיךָ יַעַבְרוּ כָּל-חֲלוּץ צָבָא לִפְנֵי יְהוָה--לַמִּלְחָמָה כַּאֲשֶׁר אֲדֹנִי דֹּבֵר",
         "ועבידך יעברון. כל מגרד מנהם ללגיש. בין ידי אללה לאלחרב. כמא קאל סיידנא",
         "And your servants shall cross over, every armed man among them for the host, before God, for the war — as our lord has said."),
    ],
    28: [
        ("וַיְצַו לָהֶם מֹשֶׁה אֵת אֶלְעָזָר הַכֹּהֵן וְאֵת יְהוֹשֻׁעַ בִּן-נוּן וְאֶת-רָאשֵׁי אֲבוֹת הַמַּטּוֹת לִבְנֵי יִשְׂרָאֵל",
         "פאמר להם מוסי'. אלעזר אלאמאם ויהושע אבן נון. ורויסא אבא אסבאט בני אסראיל",
         "And Moses gave instructions concerning them to Eleazar the imām and Joshua son of Nun, and to the heads of the fathers of the tribes of the sons of Israel."),
    ],
    29: [
        ("וַיֹּאמֶר מֹשֶׁה אֲלֵהֶם אִם-יַעַבְרוּ בְנֵי-גָד וּבְנֵי-רְאוּבֵן אִתְּכֶם אֶת-הַיַּרְדֵּן כָּל-חָלוּץ לַמִּלְחָמָה לִפְנֵי יְהוָה",
         "פקאל אן עברו מעכם אלארדן. כל רגל מגרד לאלחרב בין ידי אללה",
         "And he said: if every armed man among them crosses the Jordan with you for war before God"),
        ("וְנִכְבְּשָׁה הָאָרֶץ לִפְנֵיכֶם--וּנְתַתֶּם לָהֶם אֶת-אֶרֶץ הַגִּלְעָד לַאֲחֻזָּה",
         "חתי יפתח אלבלד בין אידיכם. פאעטוהם בלד גרש חוזא",
         "until the land is opened before you, then give them the land of Gilead as a possession."),
    ],
    30: [
        ("וְאִם-לֹא יַעַבְרוּ חֲלוּצִים אִתְּכֶם--וְנֹאחֲזוּ בְתֹכְכֶם בְּאֶרֶץ כְּנָעַן",
         "ואן לם יעברון מגרדין מעכם. פליחוזו פי מא בינכם פי בלד כנעאן",
         "But if they do not cross over armed with you, then let them receive a holding among you in the land of Canaan."),
    ],
    31: [
        ("וַיַּעֲנוּ בְנֵי-גָד וּבְנֵי רְאוּבֵן לֵאמֹר",
         "פאגאבוה וקאלו לה",
         "And they answered him and said to him:"),
        ("אֵת אֲשֶׁר דִּבֶּר יְהוָה אֶל-עֲבָדֶיךָ כֵּן נַעֲשֶׂה",
         "גמיע מא אמר אללה בה עבידך אנא צאנעין",
         "all that God has commanded — your servants — we shall carry out."),
    ],
    32: [
        ("נַחְנוּ נַעֲבֹר חֲלוּצִים לִפְנֵי יְהוָה אֶרֶץ כְּנָעַן",
         "נחן נעבר מגרדין. בין ידי אללה אלי' בלד כנעאן",
         "We shall cross over armed before God to the land of Canaan"),
        ("וְאִתָּנוּ אֲחֻזַּת נַחֲלָתֵנוּ מֵעֵבֶר לַיַּרְדֵּן",
         "חתי יחצל לנא חוז נחלתנא. מן עבר אלארדן",
         "so that the possession of our inheritance on the eastern side of the Jordan may be secured to us."),
    ],
    33: [
        ("וַיִּתֵּן לָהֶם מֹשֶׁה לִבְנֵי-גָד וְלִבְנֵי רְאוּבֵן וְלַחֲצִי שֵׁבֶט מְנַשֶּׁה בֶן-יוֹסֵף",
         "פאעטא מוסי' בני גד ובני ראובן. ונצף סבט מנשה אבן יוסף",
         "So Moses gave to the sons of Gad and to the sons of Reuben and to the half-tribe of Manasseh son of Joseph"),
        ("אֶת-מַמְלֶכֶת סִיחֹן מֶלֶךְ הָאֱמֹרִי וְאֶת-מַמְלֶכֶת עוֹג מֶלֶךְ הַבָּשָׁן",
         "בלד ממלכה' סיחון מלך אלאמוריין. ובלד ממלכה' עוג מלך אלבת'נייה",
         "the land of the kingdom of Sihon king of the Amorites and the land of the kingdom of Og king of Bashan"),
        ("הָאָרֶץ לְעָרֶיהָ בִּגְבֻלֹת--עָרֵי הָאָרֶץ סָבִיב",
         "כל ארץ' מע קראהא. אלד'י עלי' תכ'מהא מסתדירא",
         "the whole land with its towns, which are within its borders all around."),
    ],
    34: [
        ("וַיִּבְנוּ בְנֵי-גָד אֶת-דִּיבֹן וְאֶת-עֲטָרֹת וְאֵת עֲרֹעֵר",
         "פבנו בני גד. דיבון ועטרות וערוער",
         "And the sons of Gad built Dibon, and Ataroth, and Aroer,"),
    ],
    35: [
        ("וְאֶת-עַטְרֹת שׁוֹפָן וְאֶת-יַעְזֵר וְיָגְבְּהָה",
         "ועטרות שופן ויעזר ויגהה",
         "and Atroth-shophan, and Jazer, and Jogbehah,"),
    ],
    36: [
        ("וְאֶת-בֵּית נִמְרָה וְאֶת-בֵּית הָרָן עָרֵי מִבְצָר וְגִדְרֹת צֹאן",
         "ובית נמרה ובית הרן. קרא חצינה וחצ'איר ג'נם",
         "and Beth-nimrah and Beth-haran — fortified towns, and enclosures for flocks."),
    ],
    37: [
        ("וּבְנֵי רְאוּבֵן בָּנוּ אֶת-חֶשְׁבּוֹן וְאֶת-אֶלְעָלֵא וְאֵת קִרְיָתָיִם",
         "ובנו בני ראובן. חשבון ואלעלא וקריתים",
         "And the sons of Reuben built Heshbon, and Elaleh, and Kiriathaim,"),
    ],
    38: [
        ("וְאֶת-נְבוֹ וְאֶת-בַּעַל מְעוֹן מוּסַבֹּת שֵׁם--וְאֶת-שִׂבְמָה",
         "ונבו ובעל מעון. מנקולה אסמאיהן וסבמה",
         "and Nebo, and Baal-meon — their names being transferred — and Sibmah"),
        ("וַיִּקְרְאוּ בְשֵׁמֹת אֶת-שְׁמוֹת הֶעָרִים אֲשֶׁר בָּנוּ",
         "וד'אלך אנהם סמו אלקרא אלתי בנוהא כמא שאו",
         "for they gave names to the towns which they built as they saw fit."),
    ],
    39: [
        ("וַיֵּלְכוּ בְּנֵי מָכִיר בֶּן-מְנַשֶּׁה גִּלְעָדָה--וַיִּלְכְּדֻהָ",
         "ת'ם מצ'ו בני מכיר אבן מנשה אלי' גרש פפתחוהא",
         "Then the sons of Machir son of Manasseh went to Gilead and took it"),
        ("וַיּוֹרֶשׁ אֶת-הָאֱמֹרִי אֲשֶׁר-בָּהּ",
         "וקרצ'ו אלאמורי אלד'י פיהא",
         "and drove out the Amorite who was in it."),
    ],
    40: [
        ("וַיִּתֵּן מֹשֶׁה אֶת-הַגִּלְעָד לְמָכִיר בֶּן-מְנַשֶּׁה וַיֵּשֶׁב בָּהּ",
         "פדפע מוסי' גרש. לאל מכיר אבן מנשה. פאקאמו פיהא",
         "And Moses gave Gilead to Machir son of Manasseh, and they settled in it."),
    ],
    41: [
        ("וְיָאִיר בֶּן-מְנַשֶּׁה הָלַךְ וַיִּלְכֹּד אֶת-חַוֹּתֵיהֶם",
         "פמצ'א יאיר אבן מנשה. ופתח סואדהן",
         "And Jair son of Manasseh went and captured their villages"),
        ("וַיִּקְרָא אֶתְהֶן חַוֹּת יָאִיר",
         "וסמאהא סואד יאיר",
         "and called them the Villages of Jair."),
    ],
    42: [
        ("וְנֹבַח הָלַךְ וַיִּלְכֹּד אֶת-קְנָת וְאֶת-בְּנֹתֶיהָ",
         "ומצ'א נבח. פפתח קנת ורסאתיקהא",
         "And Nobah went and captured Kenath and its districts"),
        ("וַיִּקְרָא לָה נֹבַח בִּשְׁמוֹ",
         "וסמאהא נבח עלי' אסמה",
         "and called it Nobah after his own name."),
    ],
}
