"""Hand-authored alignment triples for Bamidbar chapter 15."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "תם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל. וקל להם",
         "Command the sons of Israel, and say to them:"),
        ("כִּי תָבֹאוּ אֶל-אֶרֶץ מוֹשְׁבֹתֵיכֶם אֲשֶׁר אֲנִי נֹתֵן לָכֶם",
         "אד'א דכ'לתם אלי' בלד סכנאכם. אלד'י אנא מעטיכם",
         "When you enter the land of your dwelling, which I am giving you,"),
    ],
    3: [
        ("וַעֲשִׂיתֶם אִשֶּׁה לַיהוָה עֹלָה אוֹ-זֶבַח",
         "פקרבתם קרבאנא ללה צעידה או ד'בחא",
         "and you offer an offering to God — a burnt offering or a sacrifice"),
        ("לְפַלֵּא-נֶדֶר אוֹ בִנְדָבָה אוֹ בְּמֹעֲדֵיכֶם",
         "תסויג' נד'רא או תברעא. או פי אעיאדכם",
         "to fulfill a vow or as a freewill gift, or at your festivals"),
        ("לַעֲשׂוֹת רֵיחַ נִיחֹחַ לַיהוָה מִן-הַבָּקָר אוֹ מִן-הַצֹּאן",
         "וארדתם אן יכון מקבולא מרצ'ייא ללה. מן אלבקר או מן אלג'נם",
         "and you intend it to be accepted and pleasing to God, from the cattle or from the flock,"),
    ],
    4: [
        ("וְהִקְרִיב הַמַּקְרִיב קָרְבָּנוֹ לַיהוָה",
         "פיקרב צאחב ד'אלך אלקרבאן ללה",
         "then the one who brings that offering shall bring with it"),
        ("מִנְחָה סֹלֶת עִשָּׂרוֹן בָּלוּל בִּרְבִעִית הַהִין שָׁמֶן",
         "מעה מן אלבר עשרא סמדא. מלתות ברבע קסט דהן",
         "from grain, a tenth of fine flour mixed with a quarter of a qist of oil;"),
    ],
    5: [
        ("וְיַיִן לַנֶּסֶךְ רְבִיעִית הַהִין תַּעֲשֶׂה עַל-הָעֹלָה אוֹ לַזָּבַח",
         "וכ'מר לאלמזאג רבע קסט. תצנעה מע אלצעידה או מע אלד'בח",
         "and wine for the libation — a quarter of a qist — you shall make it with the burnt offering or with the sacrifice"),
        ("לַכֶּבֶשׂ הָאֶחָד", "לאלחמל אלואחד", "for the one lamb."),
    ],
    6: [
        ("אוֹ לָאַיִל תַּעֲשֶׂה מִנְחָה סֹלֶת שְׁנֵי עֶשְׂרֹנִים",
         "ולאלכבש תקרב מן אלבר עשרין סמד",
         "And for the ram you shall bring, from grain, two tenths of fine flour"),
        ("בְּלוּלָה בַשֶּׁמֶן שְׁלִשִׁית הַהִין", "מלתות בת'לת' קסט דהן",
         "mixed with a third of a qist of oil;"),
    ],
    7: [
        ("וְיַיִן לַנֶּסֶךְ שְׁלִשִׁית הַהִין", "וכ'מר לאלמזאג ת'לת' קסט",
         "and wine for the libation — a third of a qist"),
        ("תַּקְרִיב רֵיחַ-נִיחֹחַ לַיהוָה", "תקרבה מרצ'י מקבול ללה",
         "you shall offer it, accepted and pleasing to God."),
    ],
    8: [
        ("וְכִי-תַעֲשֶׂה בֶן-בָּקָר עֹלָה אוֹ-זָבַח",
         "ואד'א צנעת מן אלבקר צעידה או ד'בחא",
         "And when you make from the cattle a burnt offering or a sacrifice"),
        ("לְפַלֵּא-נֶדֶר אוֹ-שְׁלָמִים לַיהוָה", "תסויג נד'רא או סלאמה ללה",
         "to fulfill a vow or as a peace-offering to God,"),
    ],
    9: [
        ("וְהִקְרִיב עַל-בֶּן-הַבָּקָר מִנְחָה סֹלֶת שְׁלֹשָׁה עֶשְׂרֹנִים",
         "פיקרב מעה מן אלבר. ת'לאת'ה' עשור סמד",
         "then he shall bring with it, from grain, three tenths of fine flour"),
        ("בָּלוּל בַּשֶּׁמֶן חֲצִי הַהִין", "מלתות בנצף קסט דהן",
         "mixed with half a qist of oil;"),
    ],
    10: [
        ("וְיַיִן תַּקְרִיב לַנֶּסֶךְ חֲצִי הַהִין", "וכ'מר קרבה לאלמזאג נצף קסט",
         "and wine — offer it for the libation — half a qist"),
        ("אִשֵּׁה רֵיחַ-נִיחֹחַ לַיהוָה", "מקבול מרצ'י ללה",
         "accepted and pleasing to God."),
    ],
    11: [
        ("כָּכָה יֵעָשֶׂה לַשּׁוֹר הָאֶחָד אוֹ לָאַיִל הָאֶחָד",
         "כד'אך יצנע. מע כל רת'. ומע כל כבש",
         "So shall it be done with every ox, and with every ram"),
        ("אוֹ-לַשֶּׂה בַכְּבָשִׂים אוֹ בָעִזִּים", "ומע כל ראס מן אלצ'אן או מן אלמאעז",
         "and with every head from the sheep or from the goats."),
    ],
    12: [
        ("כַּמִּסְפָּר אֲשֶׁר תַּעֲשׂוּ--כָּכָה תַּעֲשׂוּ לָאֶחָד כְּמִסְפָּרָם",
         "בחסב אחצא מא תקרבון מנהא. כד'אך תצנעו מע כל ואחד מן אלמחציין",
         "According to the count of what you offer of them, so shall you do with each one of those counted."),
    ],
    13: [
        ("כָּל-הָאֶזְרָח יַעֲשֶׂה-כָּכָה אֶת-אֵלֶּה",
         "כד'א יצנע כל צריח",
         "So shall every native-born do"),
        ("לְהַקְרִיב אִשֵּׁה רֵיחַ-נִיחֹחַ לַיהוָה",
         "אד'א קרב קרבאנא מקבולא מרצ'ייא ללה",
         "when he brings an offering accepted and pleasing to God."),
    ],
    14: [
        ("וְכִי-יָגוּר אִתְּכֶם גֵּר אוֹ אֲשֶׁר-בְּתוֹכְכֶם לְדֹרֹתֵיכֶם",
         "ואי דכ'יל דכ'ל מעכם. או סכן פי מא בינכם עלי' מר אגיאלכם",
         "And any sojourner who has come among you, or who has dwelt in your midst throughout the passing of your generations"),
        ("וְעָשָׂה אִשֵּׁה רֵיחַ-נִיחֹחַ לַיהוָה", "פעמל קרבאנא. ואראד אן יכון מקבול מרצ'י ללה",
         "and has made an offering and intended it to be accepted and pleasing to God"),
        ("כַּאֲשֶׁר תַּעֲשׂוּ כֵּן יַעֲשֶׂה", "פכמא תצנעון כדאך יצנע",
         "just as you do, so shall he do."),
    ],
    15: [
        ("הַקָּהָל חֻקָּה אַחַת לָכֶם וְלַגֵּר הַגָּר",
         "יא אייה' אלגוק רסם ואחד. לכם ולאלג'ריב אלדכ'יל",
         "O assembly! One ordinance for you and for the stranger who has come in"),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם", "רסם אלדהר עלי' מר אגיאלכם",
         "an eternal ordinance throughout the passing of your generations"),
        ("כָּכֶם כַּגֵּר יִהְיֶה לִפְנֵי יְהוָה", "כמא אן אלג'ריב מת'לכם בין ידי אללה",
         "for the stranger is as you are before God."),
    ],
    16: [
        ("תּוֹרָה אַחַת וּמִשְׁפָּט אֶחָד יִהְיֶה לָכֶם",
         "כד'אך שריעה ואחדה. וחכם ואחד יכון לכם",
         "So likewise: one law and one ruling shall be for you"),
        ("וְלַגֵּר הַגָּר אִתְּכֶם", "ולאלג'ריב אלדכ'יל פי מא בינכם",
         "and for the stranger who has come in among you."),
    ],
    17: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    18: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל. וקל להם",
         "Command the sons of Israel, and say to them:"),
        ("בְּבֹאֲכֶם אֶל-הָאָרֶץ אֲשֶׁר אֲנִי מֵבִיא אֶתְכֶם שָׁמָּה",
         "אד'א דכ'לתם אלי' אלבלד. אלד'י אנא מדכ'לכם אלי' ת'ם",
         "When you enter the land to which I am bringing you there,"),
    ],
    19: [
        ("וְהָיָה בַּאֲכָלְכֶם מִלֶּחֶם הָאָרֶץ", "פמתא מא אכלתם מן טעאם אלבלד",
         "then whenever you eat of the food of the land"),
        ("תָּרִימוּ תְרוּמָה לַיהוָה", "פארפעו רפיעה ללה",
         "raise up a heave-offering to God."),
    ],
    20: [
        ("רֵאשִׁית עֲרִסֹתֵכֶם--חַלָּה תָּרִימוּ תְרוּמָה",
         "אוול עגינכם. גרדקה תרפעוהא רפיעה",
         "The first of your dough — a loaf-cake you shall raise up as a heave-offering"),
        ("כִּתְרוּמַת גֹּרֶן כֵּן תָּרִימוּ אֹתָהּ",
         "כרפיעה' אלבד'אר. כד'אך תרפעונהא",
         "like the heave-offering of the threshing-floor; so shall you raise it up."),
    ],
    21: [
        ("מֵרֵאשִׁית עֲרִסֹתֵיכֶם תִּתְּנוּ לַיהוָה תְּרוּמָה--לְדֹרֹתֵיכֶם",
         "וכד'אלך אוול עגינכם. תגעלו ללה רפיעה. עלי' מר אגיאלכם",
         "And likewise, the first of your dough you shall make for God a heave-offering, throughout the passing of your generations."),
    ],
    22: [
        ("וְכִי תִשְׁגּוּ--וְלֹא תַעֲשׂוּ אֵת כָּל-הַמִּצְו‍ֹת הָאֵלֶּה",
         "ואד'י סהיתם. ולם תעמלו גמיע הד'ה אלוצאיא",
         "And if you have erred, and have not carried out all these commandments"),
        ("אֲשֶׁר-דִּבֶּר יְהוָה אֶל-מֹשֶׁה", "אלד'י אמר אללה בהא מוסי'",
         "which God commanded Moses —"),
    ],
    23: [
        ("אֵת כָּל-אֲשֶׁר צִוָּה יְהוָה אֲלֵיכֶם בְּיַד-מֹשֶׁה",
         "מת'ל גמיע מא אמרכם אללה בה עלי' יד מוסי'",
         "like all that God commanded you by the hand of Moses"),
        ("מִן-הַיּוֹם אֲשֶׁר צִוָּה יְהוָה וָהָלְאָה--לְדֹרֹתֵיכֶם",
         "מן יום אבתדא באלאמר. והלם עלי' מר אגיאלכם",
         "from the day He began the command, and onward throughout the passing of your generations —"),
    ],
    24: [
        ("וְהָיָה אִם מֵעֵינֵי הָעֵדָה נֶעֶשְׂתָה לִשְׁגָגָה",
         "פאן כאן אלסהו ען עיון אלגמאעה",
         "then if the error was away from the eyes of the assembly"),
        ("וְעָשׂוּ כָל-הָעֵדָה פַּר בֶּן-בָּקָר אֶחָד לְעֹלָה לְרֵיחַ נִיחֹחַ לַיהוָה",
         "פליצנעו רת'א מן אלבקר. צעידה מקבולא מרצ'ייא ללה",
         "they shall make a bull from the cattle — a burnt offering, accepted and pleasing to God"),
        ("וּמִנְחָתוֹ וְנִסְכּוֹ כַּמִּשְׁפָּט", "ומעה בר ומזאג כמא יגב",
         "and with it grain and libation as required"),
        ("וּשְׂעִיר-עִזִּים אֶחָד לְחַטָּת", "ועתוד מן אלמאעז לאלד'כוה",
         "and a he-goat from the goats for the purification-offering."),
    ],
    25: [
        ("וְכִפֶּר הַכֹּהֵן עַל-כָּל-עֲדַת בְּנֵי יִשְׂרָאֵל",
         "ויסתג'פר להם",
         "And he shall seek forgiveness for them"),
        ("כִּי-שְׁגָגָה הִוא", "אד' ד'אלך סהו", "since that was an error"),
        ("וְהֵם הֵבִיאוּ אֶת-קָרְבָּנָם אִשֶּׁה לַיהוָה וְחַטָּאתָם לִפְנֵי יְהוָה עַל-שִׁגְגָתָם",
         "והם פאתו בצעידתהם קרבאנא ללה. וד'כותהם עלי' סהותהם",
         "and they have brought their burnt offering as an offering to God, and their purification-offering for their lapse."),
    ],
    26: [
        ("וְנִסְלַח לְכָל-עֲדַת בְּנֵי יִשְׂרָאֵל",
         "פיג'פר לגמאעה' בני אסראיל",
         "And it shall be forgiven to the assembly of the sons of Israel"),
        ("וְלַגֵּר הַגָּר בְּתוֹכָם", "ולאלג'ריב אלדכ'יל פי מא בינהם",
         "and to the stranger who has come in among them"),
        ("כִּי לְכָל-הָעָם בִּשְׁגָגָה", "אד' גמיע אלקום עלי' סהו",
         "since all the people acted in error."),
    ],
    27: [
        ("וְאִם-נֶפֶשׁ אַחַת תֶּחֱטָא בִשְׁגָגָה",
         "ואן אכ'טא אנסאן ואחד כד'אלך סהוא",
         "And if a single person errs likewise, in error"),
        ("וְהִקְרִיבָה עֵז בַּת-שְׁנָתָהּ לְחַטָּאת",
         "פליקרב שאה אבנה' סנתהא לאלד'כוה",
         "he shall offer a ewe-lamb in its first year for the purification-offering."),
    ],
    28: [
        ("וְכִפֶּר הַכֹּהֵן עַל-הַנֶּפֶשׁ הַשֹּׁגֶגֶת בְּחֶטְאָה בִשְׁגָגָה--לִפְנֵי יְהוָה",
         "פיסתג'פר אלאמאם. ען ד'אלך אלאנסאן אלסאהי. עלי' מא אכ'טא סהוא בין ידי אללה",
         "And the imām shall seek forgiveness on behalf of that erring person, for what he erred in error before God"),
        ("לְכַפֵּר עָלָיו וְנִסְלַח לוֹ", "ויג'פר לה ויצפח ענה",
         "and it shall be forgiven him and pardoned from him."),
    ],
    29: [
        ("הָאֶזְרָח בִּבְנֵי יִשְׂרָאֵל וְלַגֵּר הַגָּר בְּתוֹכָם",
         "אלצריח מן בני אסראיל. ואלג'ריב אלדכ'יל פי מא בינהם",
         "For the native-born among the sons of Israel, and the stranger who has come in among them"),
        ("תּוֹרָה אַחַת יִהְיֶה לָכֶם לָעֹשֶׂה בִּשְׁגָגָה",
         "שריעה ואחדה תכון לכם. למן יכ'טי סהוא",
         "one law shall be for you, for whoever errs in error."),
    ],
    30: [
        ("וְהַנֶּפֶשׁ אֲשֶׁר-תַּעֲשֶׂה בְּיָד רָמָה מִן-הָאֶזְרָח וּמִן-הַגֵּר",
         "ואי אנסאן צנע ד'אלך ביד רפיעה. מן אלצריח ואלדכ'יל",
         "But any person who does that with a high hand, whether native-born or sojourner"),
        ("אֶת-יְהוָה הוּא מְגַדֵּף", "פהו קאד'ף רבה", "he is a blasphemer against his Lord"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִקֶּרֶב עַמָּהּ",
         "ינקטע ד'אלך אלאנסאן מן בין קומה",
         "that person shall be cut off from among his people."),
    ],
    31: [
        ("כִּי דְבַר-יְהוָה בָּזָה", "למא אזרא בכלאם אללה",
         "Because he has despised the word of God"),
        ("וְאֶת-מִצְוָתוֹ הֵפַר", "ופסך' עהדה", "and broken His covenant"),
        ("הִכָּרֵת תִּכָּרֵת הַנֶּפֶשׁ הַהִוא עֲו‍ֹנָה בָהּ",
         "פינקטע ד'אלך אלאנסאן אנקטאעא. ווזרה עליה",
         "that person shall surely be cut off; his iniquity is upon him."),
    ],
    32: [
        ("וַיִּהְיוּ בְנֵי-יִשְׂרָאֵל בַּמִּדְבָּר", "ולמא אקאם בני אסראיל פי אלבר",
         "And when the sons of Israel were dwelling in the wilderness"),
        ("וַיִּמְצְאוּ אִישׁ מְקֹשֵׁשׁ עֵצִים--בְּיוֹם הַשַּׁבָּת",
         "פוגדו רגלא. יחתטב חטבא פי יום אלסבת",
         "they found a man gathering wood for himself on the Sabbath day."),
    ],
    33: [
        ("וַיַּקְרִיבוּ אֹתוֹ הַמֹּצְאִים אֹתוֹ מְקֹשֵׁשׁ עֵצִים",
         "פקדמוה אלד'י וגדוה יחתטב חטבא",
         "And those who found him gathering wood brought him"),
        ("אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן וְאֶל כָּל-הָעֵדָה",
         "אלי' מוסי' והרון. וסאיר אלגמאעה",
         "to Moses and Aaron, and the rest of the assembly."),
    ],
    34: [
        ("וַיַּנִּיחוּ אֹתוֹ בַּמִּשְׁמָר", "ווצ'עוה פי אלחבס",
         "And they placed him in custody"),
        ("כִּי לֹא פֹרַשׁ מַה-יֵּעָשֶׂה לוֹ", "לאנה לם יפסר להם מא יצנע בה",
         "because it had not been made clear to them what should be done with him."),
    ],
    35: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי",
         "And God said to Moses:"),
        ("מוֹת יוּמַת הָאִישׁ", "יקתל אלרגל קתלא",
         "The man shall surely be put to death"),
        ("רָגוֹם אֹתוֹ בָאֲבָנִים כָּל-הָעֵדָה מִחוּץ לַמַּחֲנֶה",
         "וד'אלך אן ירגמוה באלחגארה גמיע אלגמאעה. כ'ארג אלעסכר",
         "and that by the whole assembly stoning him with stones, outside the camp."),
    ],
    36: [
        ("וַיֹּצִיאוּ אֹתוֹ כָּל-הָעֵדָה אֶל-מִחוּץ לַמַּחֲנֶה",
         "פאכ'רגוה כ'ארג אלעסכר",
         "And they brought him out outside the camp"),
        ("וַיִּרְגְּמוּ אֹתוֹ בָּאֲבָנִים וַיָּמֹת", "ורגמוה באלחגארה חתי' מאת",
         "and stoned him with stones until he died"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    37: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "פקאל אללה למוסי' קאילא",
         "And God said to Moses, saying:"),
    ],
    38: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל וקל להם",
         "Command the sons of Israel and say to them"),
        ("וְעָשׂוּ לָהֶם צִיצִת עַל-כַּנְפֵי בִגְדֵיהֶם לְדֹרֹתָם",
         "אן יצנעו להם ד'ואבה. עלי' אכנאף אזארהם עלי' מר אגיאלהם",
         "that they shall make for themselves a fringe upon the edges of their outer garments, throughout the passing of their generations"),
        ("וְנָתְנוּ עַל-צִיצִת הַכָּנָף פְּתִיל תְּכֵלֶת",
         "ויגעלון עלי' דואבה' אלכנף סלך אסמאנגון",
         "and they shall place upon the fringe of the edge a thread of blue-violet wool."),
    ],
    39: [
        ("וְהָיָה לָכֶם לְצִיצִת וּרְאִיתֶם אֹתוֹ וּזְכַרְתֶּם אֶת-כָּל-מִצְו‍ֹת יְהוָה",
         "פתכון תלך לכם ד'ואבה צ'אהרה. תרוהא פתד'כרו. גמיע וצאיא אללה ותעמלוהא",
         "And that shall be for you a visible fringe — you shall see it and remember all the commandments of God and do them"),
        ("וְלֹא-תָתוּרוּ אַחֲרֵי לְבַבְכֶם וְאַחֲרֵי עֵינֵיכֶם אֲשֶׁר-אַתֶּם זֹנִים אַחֲרֵיהֶם",
         "ולא תרומו אתבאע קלובכם ועיונכם. אלד'י אנתם טאג'יון וראהם",
         "and you shall not seek to follow your hearts and your eyes, after which you go astray."),
    ],
    40: [
        ("לְמַעַן תִּזְכְּרוּ וַעֲשִׂיתֶם אֶת-כָּל-מִצְו‍ֹתָי",
         "לכי תד'כרו ד'אלך דאימא. ותעמלו גמיע וצאיאי",
         "So that you may remember that always, and do all My commandments"),
        ("וִהְיִיתֶם קְדֹשִׁים לֵאלֹהֵיכֶם", "פתכונו מקדסין לרבכם",
         "and you shall be consecrated to your Lord."),
    ],
    41: [
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם אֲשֶׁר הוֹצֵאתִי אֶתְכֶם מֵאֶרֶץ מִצְרַיִם",
         "אנא אללה רבכם. אלד'י אכ'רגתכם מן בלד מצר",
         "I am God your Lord, who brought you out from the land of Egypt"),
        ("לִהְיוֹת לָכֶם לֵאלֹהִים", "לאכון לכם אלאהא",
         "to be your God."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם", "אנא אללה רבכם דאים אלבקא",
         "I am God your Lord, everlasting in existence."),
    ],
}
