"""Hand-authored alignment triples for Bamidbar chapter 3."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאֵלֶּה תּוֹלְדֹת אַהֲרֹן וּמֹשֶׁה",
         "והדא נסבה' קום הרון ומוסי'",
         "And this is the lineage of the people of Aaron and Moses"),
        ("בְּיוֹם דִּבֶּר יְהוָה אֶת-מֹשֶׁה--בְּהַר סִינָי",
         "פי וקת כ'אטב אללה מוסי' פי גבל סיני",
         "at the time God spoke to Moses on Mount Sinai"),
    ],
    2: [
        ("וְאֵלֶּה שְׁמוֹת בְּנֵי-אַהֲרֹן",
         "והד'ה אסמא בני הרון",
         "And these are the names of the sons of Aaron"),
        ("הַבְּכֹר נָדָב וַאֲבִיהוּא אֶלְעָזָר וְאִיתָמָר",
         "אלבכר נדב. ואביהוא. אלעזר ואיתמר",
         "the firstborn Nadab, and Abihu, Eleazar, and Itamar"),
    ],
    3: [
        ("אֵלֶּה שְׁמוֹת בְּנֵי אַהֲרֹן הַכֹּהֲנִים הַמְּשֻׁחִים",
         "הד'ה אסמא בני הרון. אלאימה אלממסוחין",
         "These are the names of the sons of Aaron — the anointed imāms"),
        ("אֲשֶׁר-מִלֵּא יָדָם לְכַהֵן",
         "אלד'י כמל ואגבהם לאלאמאמה",
         "whose obligation to the imāmate was fulfilled"),
    ],
    4: [
        ("וַיָּמָת נָדָב וַאֲבִיהוּא לִפְנֵי יְהוָה",
         "פמאת נדב ואביהוא. במא קרבא נארא ג'ריבה. בין ידי אללה",
         "And Nadab and Abihu died, because they offered a strange fire before God"),
        ("בְּמִדְבַּר סִינַי וּבָנִים לֹא-הָיוּ לָהֶם",
         "פי ברייה' סיני. ולם יכון להם בנין",
         "in the wilderness of Sinai, and they had no sons"),
        ("וַיְכַהֵן אֶלְעָזָר וְאִיתָמָר עַל-פְּנֵי אַהֲרֹן אֲבִיהֶם",
         "ואם אלעזר ואיתמר. בחצ'רה' הרון אביהמא",
         "and Eleazar and Itamar served in the presence of Aaron their father"),
    ],
    5: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech"),
    ],
    6: [
        ("הַקְרֵב אֶת-מַטֵּה לֵוִי",
         "קדם סבט לוי",
         "Bring forward the tribe of Levi"),
        ("וְהַעֲמַדְתָּ אֹתוֹ לִפְנֵי אַהֲרֹן הַכֹּהֵן",
         "ואוקפה. בין ידי הרון אלאמאם",
         "and station them before Aaron the imām"),
        ("וְשֵׁרְתוּ אֹתוֹ",
         "פיכ'דמוה",
         "that they may serve him"),
    ],
    7: [
        ("וְשָׁמְרוּ אֶת-מִשְׁמַרְתּוֹ וְאֶת-מִשְׁמֶרֶת כָּל-הָעֵדָה",
         "ויחפצ'ו [מחפט'ה[ מחפצ'ה. ומחפץ' אלגמאעה",
         "And they shall keep his charge and the charge of the congregation"),
        ("לִפְנֵי אֹהֶל מוֹעֵד",
         "בין ידי כ'בא אלמחצ'ר",
         "before the tent of the assembly"),
        ("לַעֲבֹד אֶת-עֲבֹדַת הַמִּשְׁכָּן",
         "ויכ'דמון כ'דמה' אלמסכן",
         "and shall perform the service of the tabernacle"),
    ],
    8: [
        ("וְשָׁמְרוּ אֶת-כָּל-כְּלֵי אֹהֶל מוֹעֵד",
         "ויחפצ'ו גמיע אניה' כ'בא אלמחצ'ר",
         "And they shall keep all the vessels of the tent of the assembly"),
        ("וְאֶת-מִשְׁמֶרֶת בְּנֵי יִשְׂרָאֵל",
         "ומחפץ' בני אסראיל",
         "and the charge of the sons of Israel"),
        ("לַעֲבֹד אֶת-עֲבֹדַת הַמִּשְׁכָּן",
         "ליכ'דמו כ'דמה' אלמסכן",
         "to perform the service of the tabernacle"),
    ],
    9: [
        ("וְנָתַתָּה אֶת-הַלְוִיִּם לְאַהֲרֹן וּלְבָנָיו",
         "ואדפע אלליואניין. להרון ובניה",
         "And deliver the Levites to Aaron and his sons"),
        ("נְתוּנִם נְתוּנִם הֵמָּה לוֹ מֵאֵת בְּנֵי יִשְׂרָאֵל",
         "מעטיין מסלמין הם לה. מן בני אסראיל",
         "given, entrusted they are to him, from the sons of Israel"),
    ],
    10: [
        ("וְאֶת-אַהֲרֹן וְאֶת-בָּנָיו תִּפְקֹד",
         "והרון ובניה תוכל",
         "And Aaron and his sons you shall appoint"),
        ("וְשָׁמְרוּ אֶת-כְּהֻנָּתָם",
         "ויחפצ'ו אמאמתהם",
         "and they shall keep their imāmate"),
        ("וְהַזָּר הַקָּרֵב יוּמָת",
         "ואי אגנבי תקדם אלי'הא פליקתל",
         "and any outsider who approaches it shall be put to death"),
    ],
    11: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech"),
    ],
    12: [
        ("וַאֲנִי הִנֵּה לָקַחְתִּי אֶת-הַלְוִיִּם מִתּוֹךְ בְּנֵי יִשְׂרָאֵל",
         "פאני קד שרפת אלליואניין. מן בין בני אסראיל",
         "For I have distinguished the Levites from among the sons of Israel"),
        ("תַּחַת כָּל-בְּכוֹר פֶּטֶר רֶחֶם מִבְּנֵי יִשְׂרָאֵל",
         "בדל כל בכר. אוול בטן מן בני אסראיל",
         "in place of every firstborn, the first of the womb from the sons of Israel"),
        ("וְהָיוּ לִי הַלְוִיִּם",
         "פיצרו לי אלליואניין",
         "so the Levites shall be Mine"),
    ],
    13: [
        ("כִּי לִי כָּל-בְּכוֹר",
         "כמא לי כל בכר",
         "As all the firstborn are Mine"),
        ("בְּיוֹם הַכֹּתִי כָל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם הִקְדַּשְׁתִּי לִי כָל-בְּכוֹר בְּיִשְׂרָאֵל",
         "פי יום אהלכת כל בכר פי בלד מצר. אקדסת לי כל בכר פי מא בין בני אסראיל",
         "on the day I destroyed every firstborn in the land of Egypt, I consecrated to Myself every firstborn among the sons of Israel"),
        ("מֵאָדָם עַד-בְּהֵמָה לִי יִהְיוּ אֲנִי יְהוָה",
         "מן אנסאן אלי' בהימה כד'אך יציר לי הולאי אנא אללה שרפתהם",
         "from human to beast; thus shall these be Mine. I am God who distinguished them"),
    ],
    14: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְּמִדְבַּר סִינַי לֵאמֹר",
         "ת'ם כלם אללה מוסי'. פי ברייה' סיני קאילא",
         "Then God spoke to Moses in the wilderness of Sinai, saying:"),
    ],
    15: [
        ("פְּקֹד אֶת-בְּנֵי לֵוִי לְבֵית אֲבֹתָם לְמִשְׁפְּחֹתָם",
         "עד בני לוי. לביות אבאיהם לעשאירהם",
         "Count the sons of Levi by the houses of their fathers, by their clans"),
        ("כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמַעְלָה תִּפְקְדֵם",
         "כל ד'כר. מן אבן שהר פצאעדא תעדהם",
         "every male from a month old and upward you shall count them"),
    ],
    16: [
        ("וַיִּפְקֹד אֹתָם מֹשֶׁה עַל-פִּי יְהוָה כַּאֲשֶׁר צֻוָּה",
         "פעדהם מוסי' עלי קול אללה. כמי' אמר",
         "And Moses counted them at the word of God, as he was commanded"),
    ],
    17: [
        ("וַיִּהְיוּ-אֵלֶּה בְנֵי-לֵוִי בִּשְׁמֹתָם",
         "והולאי כאנו בני לוי באסמאיהם",
         "And these were the sons of Levi by their names"),
        ("גֵּרְשׁוֹן וּקְהָת וּמְרָרִי",
         "גרשון. וקהת ומררי",
         "Gershon, and Kohath, and Merari"),
    ],
    18: [
        ("וְאֵלֶּה שְׁמוֹת בְּנֵי-גֵרְשׁוֹן לְמִשְׁפְּחֹתָם",
         "והד'ה אסמא בני גרשון. לעשאירהם",
         "And these are the names of the sons of Gershon by their clans"),
        ("לִבְנִי וְשִׁמְעִי",
         "לבני ושמעי",
         "Libni and Shimei"),
    ],
    19: [
        ("וּבְנֵי קְהָת לְמִשְׁפְּחֹתָם",
         "ובני קהת לעשאירהם",
         "And the sons of Kohath by their clans"),
        ("עַמְרָם וְיִצְהָר חֶבְרוֹן וְעֻזִּיאֵל",
         "עמרם ויצהר. חברון ועזיאל",
         "Amram and Izhar, Hebron and Uzziel"),
    ],
    20: [
        ("וּבְנֵי מְרָרִי לְמִשְׁפְּחֹתָם",
         "ובני מררי. לעשאירהם",
         "And the sons of Merari by their clans"),
        ("מַחְלִי וּמוּשִׁי",
         "מחלי ומושי",
         "Mahli and Mushi"),
        ("אֵלֶּה הֵם מִשְׁפְּחֹת הַלֵּוִי לְבֵית אֲבֹתָם",
         "הד'ה עשאיר אלליואניין לביות אבאיהם",
         "These are the clans of the Levites by the houses of their fathers"),
    ],
    21: [
        ("לְגֵרְשׁוֹן--מִשְׁפַּחַת הַלִּבְנִי וּמִשְׁפַּחַת הַשִּׁמְעִי",
         "לגרשון. עשירה' לבני. ועשירה' שמעי",
         "To Gershon: the clan of Libni and the clan of Shimei"),
        ("אֵלֶּה הֵם מִשְׁפְּחֹת הַגֵּרְשֻׁנִּי",
         "הד'ה עשאירה",
         "these are their clans"),
    ],
    22: [
        ("פְּקֻדֵיהֶם בְּמִסְפַּר כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמָעְלָה",
         "ועדדהם באחצא כל ד'כר. מן אבן שהר וצאעדא",
         "And their count, by the census of every male from a month old and upward"),
        ("פְּקֻדֵיהֶם שִׁבְעַת אֲלָפִים וַחֲמֵשׁ מֵאוֹת",
         "סבעה' אלאף וכ'מס מאיה",
         "was seven thousand five hundred"),
    ],
    23: [
        ("מִשְׁפְּחֹת הַגֵּרְשֻׁנִּי אַחֲרֵי הַמִּשְׁכָּן יַחֲנוּ יָמָּה",
         "ועשאירהם. ינזלון ורא אלמסכן פי אלמג'רב",
         "And their clans shall encamp behind the tabernacle in the west"),
    ],
    24: [
        ("וּנְשִׂיא בֵית-אָב לַגֵּרְשֻׁנִּי אֶלְיָסָף בֶּן-לָאֵל",
         "ושריפהם. אליסף אבן לאל",
         "And their noble is Eliasaph son of Lael"),
    ],
    25: [
        ("וּמִשְׁמֶרֶת בְּנֵי-גֵרְשׁוֹן בְּאֹהֶל מוֹעֵד",
         "וחפצ'הם מן כ'בא. אלמחצ'ר",
         "And their charge from the tent of the assembly"),
        ("הַמִּשְׁכָּן וְהָאֹהֶל מִכְסֵהוּ",
         "אלמסכן ואלכ'בא. וג'שאה",
         "the tabernacle and the tent and its covering"),
        ("וּמָסַךְ פֶּתַח אֹהֶל מוֹעֵד",
         "וסתר באב כ'בא אלמחצ'ר",
         "and the curtain of the entrance of the tent of the assembly"),
    ],
    26: [
        ("וְקַלְעֵי הֶחָצֵר וְאֶת-מָסַךְ פֶּתַח הֶחָצֵר",
         "וקלוע אלצראדק וסתר באבה",
         "And the hangings of the court and the curtain of its entrance"),
        ("אֲשֶׁר עַל-הַמִּשְׁכָּן וְעַל-הַמִּזְבֵּחַ סָבִיב",
         "אלד'י עלי אלמסכן ואלמד'בח מסתדירא",
         "which is around the tabernacle and the altar"),
        ("וְאֵת מֵיתָרָיו לְכֹל עֲבֹדָתוֹ",
         "ואטנאבהא. וסאיר כ'דמתהא",
         "and their cords, and all the rest of their service"),
    ],
    27: [
        ("וְלִקְהָת מִשְׁפַּחַת הַעַמְרָמִי וּמִשְׁפַּחַת הַיִּצְהָרִי",
         "ולקהת עשירה' עמרם ועשירה' יצהר",
         "And to Kohath: the clan of Amram and the clan of Izhar"),
        ("וּמִשְׁפַּחַת הַחֶבְרֹנִי וּמִשְׁפַּחַת הָעָזִּיאֵלִי",
         "ועשירה' חברון. ועשירה' עוזיאל",
         "and the clan of Hebron, and the clan of Uzziel"),
        ("אֵלֶּה הֵם מִשְׁפְּחֹת הַקְּהָתִי",
         "הד'ה עשאירה",
         "these are his clans"),
    ],
    28: [
        ("בְּמִסְפַּר כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמָעְלָה",
         "באחצא כל ד'כר. מן אבן שהר פצאעדא",
         "By the census of every male from a month old and upward"),
        ("שְׁמֹנַת אֲלָפִים וְשֵׁשׁ מֵאוֹת שֹׁמְרֵי מִשְׁמֶרֶת הַקֹּדֶשׁ",
         "ת'מאניה' אלאף וסת מאיה. חאפצ'י מחפץ' אלקדס",
         "eight thousand six hundred, keepers of the charge of the sanctuary"),
    ],
    29: [
        ("מִשְׁפְּחֹת בְּנֵי-קְהָת יַחֲנוּ עַל יֶרֶךְ הַמִּשְׁכָּן תֵּימָנָה",
         "ועשאירהם ינזלון. אלי' גאנב אלמסכן פי אלגנוב",
         "And their clans shall encamp beside the tabernacle to the south"),
    ],
    30: [
        ("וּנְשִׂיא בֵית-אָב לְמִשְׁפְּחֹת הַקְּהָתִי אֱלִיצָפָן בֶּן-עֻזִּיאֵל",
         "ושריפהם אליצפן אבן עוזיאל",
         "And their noble is Elizaphan son of Uzziel"),
    ],
    31: [
        ("וּמִשְׁמַרְתָּם הָאָרֹן וְהַשֻּׁלְחָן וְהַמְּנֹרָה וְהַמִּזְבְּחֹת",
         "וחפצהם. אלצנדוק ואלמאידה ואלמנארה ואלמד'אבח",
         "And their charge: the ark, and the table, and the lampstand, and the altars"),
        ("וּכְלֵי הַקֹּדֶשׁ אֲשֶׁר יְשָׁרְתוּ בָּהֶם",
         "ואניה' אלקדס. אלד'י יכ'דמון בהא",
         "and the vessels of the sanctuary with which they serve"),
        ("וְהַמָּסָךְ--וְכֹל עֲבֹדָתוֹ",
         "ואלסתר וסאיר כ'דמתה",
         "and the veil, and all the rest of its service"),
    ],
    32: [
        ("וּנְשִׂיא נְשִׂיאֵי הַלֵּוִי אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "ושריף אשראף אלליואניין אלעזר אבן הרון אלאמאם",
         "And the noble of the nobles of the Levites is Eleazar son of Aaron the imām"),
        ("פְּקֻדַּת שֹׁמְרֵי מִשְׁמֶרֶת הַקֹּדֶשׁ",
         "מוכל בחאפצ'י מחפץ' אלקדס",
         "appointed over the keepers of the charge of the sanctuary"),
    ],
    33: [
        ("לִמְרָרִי--מִשְׁפַּחַת הַמַּחְלִי וּמִשְׁפַּחַת הַמּוּשִׁי",
         "ולמררי עשירה' מחלי. ועשירה' מושי",
         "And to Merari: the clan of Mahli and the clan of Mushi"),
        ("אֵלֶּה הֵם מִשְׁפְּחֹת מְרָרִי",
         "הולאי עשאירה",
         "these are his clans"),
    ],
    34: [
        ("וּפְקֻדֵיהֶם בְּמִסְפַּר כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמָעְלָה",
         "ועדדהם באחצא כל ד'כר. מן אבן שהר פצאעדא",
         "And their count, by the census of every male from a month old and upward"),
        ("שֵׁשֶׁת אֲלָפִים וּמָאתָיִם",
         "סתה' אלאף ומאיתין",
         "six thousand two hundred"),
    ],
    35: [
        ("וּנְשִׂיא בֵית-אָב לְמִשְׁפְּחֹת מְרָרִי צוּרִיאֵל בֶּן-אֲבִיחָיִל",
         "ושריפהם. צוריאל אבן אביחיל",
         "And their noble is Zuriel son of Abihail"),
        ("עַל יֶרֶךְ הַמִּשְׁכָּן יַחֲנוּ צָפֹנָה",
         "וינזלון אלי' גאנב אלמסכן פי אלשמאל",
         "and they shall encamp beside the tabernacle to the north"),
    ],
    36: [
        ("וּפְקֻדַּת מִשְׁמֶרֶת בְּנֵי מְרָרִי",
         "ווכאלה' חפץ' בני מררי",
         "And the trusteeship of the charge of the sons of Merari"),
        ("קַרְשֵׁי הַמִּשְׁכָּן וּבְרִיחָיו וְעַמֻּדָיו וַאֲדָנָיו",
         "תכ'אתג אלמסכן. ואמהאגה ועמדה וקואעדה",
         "the planks of the tabernacle, and its bars, and its pillars, and its bases"),
        ("וְכָל-כֵּלָיו--וְכֹל עֲבֹדָתוֹ",
         "וכל אניתה וסאיר כ'דמתה",
         "and all its vessels, and all the rest of its service"),
    ],
    37: [
        ("וְעַמֻּדֵי הֶחָצֵר סָבִיב וְאַדְנֵיהֶם",
         "ועמד אלצראדק מסתדירא. וקואעדהא",
         "And the pillars of the court all around, and their bases"),
        ("וִיתֵדֹתָם וּמֵיתְרֵיהֶם",
         "ואותאדהא ואטנאבהא",
         "and their pegs and their cords"),
    ],
    38: [
        ("וְהַחֹנִים לִפְנֵי הַמִּשְׁכָּן קֵדְמָה לִפְנֵי אֹהֶל-מוֹעֵד מִזְרָחָה",
         "ואלנאזלין בין ידי אלמסכן. בין ידי כ'בא אלמחצ'ר פי אלמשרק",
         "And those encamped before the tabernacle, before the tent of the assembly to the east"),
        ("מֹשֶׁה וְאַהֲרֹן וּבָנָיו שֹׁמְרִים מִשְׁמֶרֶת הַמִּקְדָּשׁ",
         "מוסי' והרון ובניה. חאפצ'י מחפץ' אלמקדס",
         "Moses and Aaron and his sons, keepers of the charge of the sanctuary"),
        ("וְהַזָּר הַקָּרֵב יוּמָת",
         "ואי אגנבי תקדם אלי' ד'אלך פליקתל",
         "and any outsider who approaches that shall be put to death"),
    ],
    39: [
        ("כָּל-פְּקוּדֵי הַלְוִיִּם אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן עַל-פִּי יְהוָה",
         "פד'אלך גמיע עדד אלליואניין. אלד'י עדהם מוסי' והרון. עלי' קול אללה",
         "And that is the entire count of the Levites, whom Moses and Aaron counted at the word of God"),
        ("לְמִשְׁפְּחֹתָם כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמַעְלָה שְׁנַיִם וְעֶשְׂרִים אָלֶף",
         "לעשאירהם. כל ד'כר מן אבן שהר פצאעדא. את'נאן ועשרין אלפא",
         "by their clans — every male from a month old and upward: twenty-two thousand"),
    ],
    40: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה",
         "ת'ם קאל אללה למוסי'",
         "Then God said to Moses"),
        ("פְּקֹד כָּל-בְּכֹר זָכָר לִבְנֵי יִשְׂרָאֵל מִבֶּן-חֹדֶשׁ וָמָעְלָה",
         "עד כל בכר ד'כר מן בני אסראיל. מן אבן פצאעדא",
         "'Count every firstborn male of the sons of Israel, from a month old and upward"),
        ("וְשָׂא אֵת מִסְפַּר שְׁמֹתָם",
         "וארפע אחצא אסמאיהם",
         "and raise a census of their names.'"),
    ],
    41: [
        ("וְלָקַחְתָּ אֶת-הַלְוִיִּם לִי אֲנִי יְהוָה",
         "וכ'ד' אלליואניין לי אנא אללה שרפתהם",
         "'And take the Levites for Me — I am God who distinguished them"),
        ("תַּחַת כָּל-בְּכֹר בִּבְנֵי יִשְׂרָאֵל",
         "בדל כל בכר מן בני אסראיל",
         "in place of every firstborn from the sons of Israel"),
        ("וְאֵת בֶּהֱמַת הַלְוִיִּם תַּחַת כָּל-בְּכוֹר בְּבֶהֱמַת בְּנֵי יִשְׂרָאֵל",
         "ובהאים אלליואניין. בדל כל בכר. מן בהאים בני אסראיל",
         "and the beasts of the Levites in place of every firstborn from the beasts of the sons of Israel.'"),
    ],
    42: [
        ("וַיִּפְקֹד מֹשֶׁה כַּאֲשֶׁר צִוָּה יְהוָה אֹתוֹ",
         "פעד מוסי'. כמא אמרה אללה",
         "And Moses counted, as God had commanded him"),
        ("אֶת-כָּל-בְּכוֹר בִּבְנֵי יִשְׂרָאֵל",
         "כל בכר מן בני אסראיל",
         "every firstborn from the sons of Israel"),
    ],
    43: [
        ("וַיְהִי כָל-בְּכוֹר זָכָר בְּמִסְפַּר שֵׁמֹת מִבֶּן-חֹדֶשׁ וָמַעְלָה",
         "פכאן כל בכר ד'כר. באחצא אסמאיהם. מן אבן שהר פצאעדא כד'אלך",
         "And all the firstborn males, by the census of their names, from a month old and upward, came to"),
        ("שְׁנַיִם וְעֶשְׂרִים אֶלֶף שְׁלֹשָׁה וְשִׁבְעִים וּמָאתָיִם",
         "ועשרין אלפא. ומאיתין ות'לאתה וסבעין",
         "twenty-two thousand two hundred and seventy-three"),
    ],
    44: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech"),
    ],
    45: [
        ("קַח אֶת-הַלְוִיִּם תַּחַת כָּל-בְּכוֹר בִּבְנֵי יִשְׂרָאֵל",
         "כ'ד' אלליואניין. בדל כל בכר מן בני אסראיל",
         "'Take the Levites in place of every firstborn from the sons of Israel"),
        ("וְאֶת-בֶּהֱמַת הַלְוִיִּם תַּחַת בְּהֶמְתָּם",
         "ובהאים אלליואניין בדל בהאימהם",
         "and the beasts of the Levites in place of their beasts"),
        ("וְהָיוּ-לִי הַלְוִיִּם אֲנִי יְהוָה",
         "אנא אללה שרפתהם",
         "I am God who distinguished them.'"),
    ],
    46: [
        ("וְאֵת פְּדוּיֵי הַשְּׁלֹשָׁה וְהַשִּׁבְעִים וְהַמָּאתָיִם",
         "ואמא פדא אלמאיתין ואלת'לאתה ואלסבעין",
         "'And as for the redemption of the two hundred and seventy-three"),
        ("הָעֹדְפִים עַל-הַלְוִיִּם מִבְּכוֹר בְּנֵי יִשְׂרָאֵל",
         "אלזאידין עלי' אלליואניין. מן בכור בני אסראיל",
         "who exceed the Levites from the firstborn of the sons of Israel —'"),
    ],
    47: [
        ("וְלָקַחְתָּ חֲמֵשֶׁת חֲמֵשֶׁת שְׁקָלִים--לַגֻּלְגֹּלֶת",
         "פכ'ד' כ'מסה מת'אקיל לכל גמגמה",
         "'take five shekels for each head"),
        ("בְּשֶׁקֶל הַקֹּדֶשׁ תִּקָּח עֶשְׂרִים גֵּרָה הַשָּׁקֶל",
         "פצ'ה במת'אקיל אלקדס. כל מת'קאל עשרין דאנק",
         "in silver, by the shekels of the sanctuary, each shekel being twenty dāniq.'"),
    ],
    48: [
        ("וְנָתַתָּה הַכֶּסֶף לְאַהֲרֹן וּלְבָנָיו",
         "ואדפע אלפצ'ה להרון ובניה",
         "'And deliver the silver to Aaron and his sons"),
        ("פְּדוּיֵי הָעֹדְפִים בָּהֶם",
         "פדא אלפאצ'לין עליהם",
         "the redemption of those who exceed them.'"),
    ],
    49: [
        ("וַיִּקַּח מֹשֶׁה אֵת כֶּסֶף הַפִּדְיוֹם",
         "פאכ'ד' מוסי'. פצ'ה' אלפדא",
         "And Moses took the silver of the redemption"),
        ("מֵאֵת הָעֹדְפִים עַל פְּדוּיֵי הַלְוִיִּם",
         "מן אלזאידין. עלי' אלליואניין",
         "from those who exceeded the Levites"),
    ],
    50: [
        ("מֵאֵת בְּכוֹר בְּנֵי יִשְׂרָאֵל--לָקַח אֶת-הַכָּסֶף",
         "מן בכור בני אסראיל אכ'ד' תלך אלפצ'ה",
         "From the firstborn of the sons of Israel he took that silver"),
        ("חֲמִשָּׁה וְשִׁשִּׁים וּשְׁלֹשׁ מֵאוֹת וָאֶלֶף--בְּשֶׁקֶל הַקֹּדֶשׁ",
         "אלף ות'לאת' מאיה. וכ'מסה וסתין. מת'קאל במת'קאל אלקדס",
         "one thousand three hundred and sixty-five shekels, by the shekel of the sanctuary"),
    ],
    51: [
        ("וַיִּתֵּן מֹשֶׁה אֶת-כֶּסֶף הַפְּדֻיִם לְאַהֲרֹן וּלְבָנָיו",
         "פדפע מוסי' פצ'ה' אלפדא. אלי' הרון ובניה",
         "And Moses delivered the silver of the redemption to Aaron and his sons"),
        ("עַל-פִּי יְהוָה כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "עלי קול אללה. כמא אמרה",
         "at the word of God, as he was commanded"),
    ],
}
