"""Hand-authored alignment triples for Bamidbar chapter 11."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    2: [
        ("וַיִּצְעַק הָעָם אֶל-מֹשֶׁה", "פצרך' אלקום אלי' מוסי'",
         "And the people cried out to Moses"),
        ("וַיִּתְפַּלֵּל מֹשֶׁה אֶל-יְהוָה", "פדעא רבה", "and he prayed to his Lord"),
        ("וַתִּשְׁקַע הָאֵשׁ", "פג'ארת אלנאר", "and the fire died down."),
    ],
    3: [
        ("וַיִּקְרָא שֵׁם-הַמָּקוֹם הַהוּא תַּבְעֵרָה", "פסמא ד'אלך אלמוצ'ע אלמשתעלה",
         "And he called that place 'the Blazing,'"),
        ("כִּי-בָעֲרָה בָם אֵשׁ יְהוָה", "למא אשתעלת פיהם נאר אללה",
         "because the fire of God had blazed among them."),
    ],
    4: [
        ("וְהָאסַפְסֻף אֲשֶׁר בְּקִרְבּוֹ הִתְאַוּוּ תַּאֲוָה", "ואללפיף אלד'ין פי מא בינהם. תשהו שהוה",
         "And the mixed multitude who were among them craved a craving"),
        ("וַיָּשֻׁבוּ וַיִּבְכּוּ גַּם בְּנֵי יִשְׂרָאֵל", "פרגע איצ'א בני אסראיל מעהם. פבכו",
         "and the sons of Israel also turned back with them, and they wept"),
        ("וַיֹּאמְרוּ מִי יַאֲכִלֵנוּ בָּשָׂר", "וקאלו. מן יטעמנא לחמא",
         "and said: 'Who shall feed us meat?'"),
    ],
    5: [
        ("זָכַרְנוּ אֶת-הַדָּגָה אֲשֶׁר-נֹאכַל בְּמִצְרַיִם חִנָּם",
         "פד'כרנא אלסמך. אלד'י כנא נאכלה במצר מגאנא",
         "We remember the fish which we used to eat in Egypt for nothing"),
        ("אֵת הַקִּשֻּׁאִים וְאֵת הָאֲבַטִּחִים", "אלקת'א ואלבטיך'",
         "the cucumbers and the melons"),
        ("וְאֶת-הֶחָצִיר וְאֶת-הַבְּצָלִים וְאֶת-הַשּׁוּמִים", "ואלכראת' ואלבצל ואלתום",
         "and the leeks and the onions and the garlic."),
    ],
    6: [
        ("וְעַתָּה נַפְשֵׁנוּ יְבֵשָׁה אֵין כֹּל", "ואלאן. פנפוסנא יאבסה ממא ליס שי",
         "And now our souls are dried up, as though there were nothing at all"),
        ("בִּלְתִּי אֶל-הַמָּן עֵינֵינוּ", "ואנמא עיוננא אלי' אלמן ממדודה",
         "for our eyes are stretched only toward the manna."),
    ],
    7: [
        ("וְהַמָּן כִּזְרַע-גַּד הוּא", "וכאן אלמן כבזר אלכבזרה",
         "And the manna was like the seed of coriander"),
        ("וְעֵינוֹ כְּעֵין הַבְּדֹלַח", "ולונה כלון אללולו",
         "and its color was like the color of pearls."),
    ],
    8: [
        ("שָׁטוּ הָעָם וְלָקְטוּ וְטָחֲנוּ בָרֵחַיִם אוֹ דָכוּ בַּמְּדֹכָה",
         "יטוף אלקום פילקטונה ויטחנון מנה פי אלרחא. או ידקון באלמדק",
         "The people would go about and gather it, and grind it in the millstone or pound it in the mortar"),
        ("וּבִשְּׁלוּ בַּפָּרוּר וְעָשׂוּ אֹתוֹ עֻגוֹת", "ויטבכון מנה פי אלבראם. ויצנעון מנה מלילא",
         "and cook it in the pots, and make of it a roasted cake"),
        ("וְהָיָה טַעְמוֹ כְּטַעַם לְשַׁד הַשָּׁמֶן", "ויכון טעמה כחלאוה בדסם",
         "and its taste was like the sweetness of something rich with fat."),
    ],
    9: [
        ("וּבְרֶדֶת הַטַּל עַל-הַמַּחֲנֶה לָיְלָה", "וענד נזול אלטל. עלי' אלעסכר לילא",
         "And when the dew descended upon the camp at night"),
        ("יֵרֵד הַמָּן עָלָיו", "ינזל אלמן עליה", "the manna would descend upon it."),
    ],
    10: [
        ("וַיִּשְׁמַע מֹשֶׁה אֶת-הָעָם בֹּכֶה לְמִשְׁפְּחֹתָיו--אִישׁ לְפֶתַח אָהֳלוֹ",
         "פלמא סמע מוסי' אלקום. יבכון לעשאירהם. כל אמר עלי' באב כ'באיה",
         "And when Moses heard the people weeping for their clans — every man at the door of his tent"),
        ("וַיִּחַר-אַף יְהוָה מְאֹד", "פאשתד ג'צב אללה גדא",
         "God's anger was greatly intensified"),
        ("וּבְעֵינֵי מֹשֶׁה רָע", "וסא ד'אלך ענד מוסי'",
         "and it was grievous in the sight of Moses."),
    ],
    11: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוָה", "פקאל מוסי' ללה",
         "And Moses said to God"),
        ("לָמָה הֲרֵעֹתָ לְעַבְדֶּךָ", "לם אבלית עבדך",
         "'Why have You brought trial upon Your servant"),
        ("וְלָמָּה לֹא-מָצָתִי חֵן בְּעֵינֶיךָ", "ולם לם אגד חצ'אא ענדך",
         "and why have I not found favor before You"),
        ("לָשׂוּם אֶת-מַשָּׂא כָּל-הָעָם הַזֶּה--עָלָי", "אד' ציירת. גמיע כלפה' הולאי אלקום עליי",
         "since You have placed the whole burden of the management of these people upon me?'"),
    ],
    12: [
        ("הֶאָנֹכִי הָרִיתִי אֵת כָּל-הָעָם הַזֶּה--אִם-אָנֹכִי יְלִדְתִּיהוּ",
         "הל אנא חמלתהם. אם ולדתהם",
         "'Did I conceive them, or did I beget them"),
        ("כִּי-תֹאמַר אֵלַי שָׂאֵהוּ בְחֵיקֶךָ כַּאֲשֶׁר יִשָּׂא הָאֹמֵן אֶת-הַיֹּנֵק",
         "אד' קלת לי סוסהם. כאנך תחמלהם פי חגרך. כמא יחמל אלחאצ'ן אלרצ'יע",
         "that You said to me: Tend them — as though You would carry them in Your lap, as a nurse carries an infant"),
        ("עַל הָאֲדָמָה אֲשֶׁר נִשְׁבַּעְתָּ לַאֲבֹתָיו", "אלי' אלבלד. אלד'י קסמת לאבאיהם",
         "to the land which You allotted to their fathers?'"),
    ],
    13: [
        ("מֵאַיִן לִי בָּשָׂר לָתֵת לְכָל-הָעָם הַזֶּה", "מן אין לי לחם. אעטי גמיעהם",
         "'From where do I have meat to give to all of them"),
        ("כִּי-יִבְכּוּ עָלַי לֵאמֹר תְּנָה-לָּנוּ בָשָׂר וְנֹאכֵלָה",
         "אד' יבכון עליי ויקולון. אעטנא לחמא נאכלה",
         "when they weep over me and say: Give us meat that we may eat?'"),
    ],
    14: [
        ("לֹא-אוּכַל אָנֹכִי לְבַדִּי לָשֵׂאת אֶת-כָּל-הָעָם הַזֶּה",
         "לא אטיק אנא ואחדי אן אסוסהם",
         "'I alone cannot manage them"),
        ("כִּי כָבֵד מִמֶּנִּי", "בל הו ת'קיל עליי", "it is too heavy for me.'"),
    ],
    15: [
        ("וְאִם-כָּכָה אַתְּ-עֹשֶׂה לִּי הָרְגֵנִי נָא הָרֹג", "ואן כנת אלזמתניה עקובה. פאגעלהא אמאתתי",
         "'And if You have bound me to it as a punishment, then let that punishment be my death"),
        ("אִם-מָצָאתִי חֵן בְּעֵינֶיךָ", "אן וגדת חצ'אא ענדך",
         "if I have found favor before You"),
        ("וְאַל-אֶרְאֶה בְּרָעָתִי", "ולא ארא בלייתי",
         "that I may not see my affliction.'"),
    ],
    16: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה אֶסְפָה-לִּי שִׁבְעִים אִישׁ מִזִּקְנֵי יִשְׂרָאֵל",
         "פקאל אללה למוסי'. אגמע לי סבעין רגלא מן שיוך' בני אסראיל",
         "And God said to Moses: 'Gather for me seventy men from the elders of the sons of Israel"),
        ("אֲשֶׁר יָדַעְתָּ כִּי-הֵם זִקְנֵי הָעָם וְשֹׁטְרָיו", "אלד'ין תעלם אנהם שיוכ'הם וערפאהם",
         "those whom you know to be their elders and their overseers"),
        ("וְלָקַחְתָּ אֹתָם אֶל-אֹהֶל מוֹעֵד וְהִתְיַצְּבוּ שָׁם עִמָּךְ",
         "וכ'דהם אלי' כ'בא אלמחצ'ר. ויקפון ת'ם מעך",
         "and take them to the tent of the assembly, and let them stand there with you.'"),
    ],
    17: [
        ("וְיָרַדְתִּי וְדִבַּרְתִּי עִמְּךָ שָׁם", "חתי אתגלא ואכ'אטבך הנאך",
         "'Until I appear and speak with you there"),
        ("וְאָצַלְתִּי מִן-הָרוּחַ אֲשֶׁר עָלֶיךָ וְשַׂמְתִּי עֲלֵיהֶם",
         "ואפידהם מן אלנור אלד'י עלי' וגהך ואגעלה עליהם",
         "and I shall impart to them of the light which is upon your face and set it upon them"),
        ("וְנָשְׂאוּ אִתְּךָ בְּמַשָּׂא הָעָם וְלֹא-תִשָּׂא אַתָּה לְבַדֶּךָ",
         "פי'עאונונך פי סיאסה' אלקום. ולא תסוסהם אנת וחדך",
         "so they shall assist you in the governance of the people, and you shall not govern them alone.'"),
    ],
    18: [
        ("וְאֶל-הָעָם תֹּאמַר הִתְקַדְּשׁוּ לְמָחָר וַאֲכַלְתֶּם בָּשָׂר",
         "וקל לאלקום. אסתעדו אלי' ג'ד חתא תאכלון לחמא",
         "'And say to the people: Prepare yourselves until tomorrow, that you may eat meat"),
        ("כִּי בְּכִיתֶם בְּאָזְנֵי יְהוָה לֵאמֹר מִי יַאֲכִלֵנוּ בָּשָׂר",
         "לאגל מא בכיתם בין ידי אללה וקלתם. מן יטעמנא לחמא",
         "because you have wept before God and said: Who shall feed us meat?"),
        ("כִּי-טוֹב לָנוּ בְּמִצְרָיִם", "וכאן אלאצלח לנא במצר",
         "For it was better for us in Egypt."),
        ("וְנָתַן יְהוָה לָכֶם בָּשָׂר וַאֲכַלְתֶּם", "פיעטיכם אללה. לחמא תאכלונה",
         "So God shall give you meat that you shall eat.'"),
    ],
    19: [
        ("לֹא יוֹם אֶחָד תֹּאכְלוּן וְלֹא יוֹמָיִם", "לא יום ואחד. תאכלונה ולא יומין",
         "'Not one day shall you eat it, and not two days"),
        ("וְלֹא חֲמִשָּׁה יָמִים וְלֹא עֲשָׂרָה יָמִים וְלֹא עֶשְׂרִים יוֹם",
         "ולא כ'מסה ולא עשרה. ולא עשרין",
         "and not five, and not ten, and not twenty —'"),
    ],
    20: [
        ("עַד חֹדֶשׁ יָמִים", "אלא אלי' אייאם שהר",
         "'but for the days of a month"),
        ("עַד אֲשֶׁר-יֵצֵא מֵאַפְּכֶם וְהָיָה לָכֶם לְזָרָא",
         "אלי' אן יכ'רג מן אנאפכם מת'לא. ויציר לכם הזאלא",
         "until it comes out of your nostrils as a byword, and becomes a disgrace to you"),
        ("יַעַן כִּי-מְאַסְתֶּם אֶת-יְהוָה אֲשֶׁר בְּקִרְבְּכֶם",
         "לאגל מא זהדתם. פי נור אללה אלד'י פי מא בינכם",
         "because you have shown contempt for the light of God which is among you"),
        ("וַתִּבְכּוּ לְפָנָיו לֵאמֹר לָמָּה זֶּה יָצָאנוּ מִמִּצְרָיִם",
         "ובכיתם בין ידיה וקלתם. לם כ'רגנא מן מצר",
         "and you wept before Him and said: Why did we ever leave Egypt?'"),
    ],
    21: [
        ("וַיֹּאמֶר מֹשֶׁה שֵׁשׁ-מֵאוֹת אֶלֶף רַגְלִי הָעָם אֲשֶׁר אָנֹכִי בְּקִרְבּוֹ",
         "קאל מוסי'. סת מאיה' אלף רגל ראגל. אלקום אלד'י אנא פי מא בינהם",
         "Moses said: 'Six hundred thousand men on foot are the people among whom I am"),
        ("וְאַתָּה אָמַרְתָּ בָּשָׂר אֶתֵּן לָהֶם וְאָכְלוּ חֹדֶשׁ יָמִים",
         "ואנת קלת. אעטיהם לחמא. יאכלונה שהרא",
         "and You said: I shall give them meat that they shall eat for a month!'"),
    ],
    22: [
        ("הֲצֹאן וּבָקָר יִשָּׁחֵט לָהֶם וּמָצָא לָהֶם",
         "פמן אענאתהם. אג'נם ובקר תד'בח להם פתכפיהם",
         "'Then for their relief — shall flocks and herds be slaughtered for them so as to suffice them?"),
        ("אִם אֶת-כָּל-דְּגֵי הַיָּם יֵאָסֵף לָהֶם וּמָצָא לָהֶם",
         "או גמיע סמך אלבחר. יחאש להם פיקנעהם",
         "Or shall all the fish of the sea be netted for them so as to satisfy them?'"),
    ],
    23: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה הֲיַד יְהוָה תִּקְצָר",
         "פקאל אללה למוסי'. הל קדרה' אללה תקצר",
         "And God said to Moses: 'Is the power of God too short?"),
        ("עַתָּה תִרְאֶה הֲיִקְרְךָ דְבָרִי אִם-לֹא", "אלאן תנצ'ר. איואפיכם כלאמי אם לא",
         "Now you shall see whether My word comes to you or not.'"),
    ],
    24: [
        ("וַיֵּצֵא מֹשֶׁה--וַיְדַבֵּר אֶל-הָעָם אֵת דִּבְרֵי יְהוָה",
         "פכ'רג מוסי'. ואכ'בר אלקום בכלאם אללה",
         "And Moses went out and informed the people of the word of God"),
        ("וַיֶּאֱסֹף שִׁבְעִים אִישׁ מִזִּקְנֵי הָעָם", "וגמע. סבעין רגלא מן שיוכ'הם",
         "and he gathered seventy men from their elders"),
        ("וַיַּעֲמֵד אֹתָם סְבִיבֹת הָאֹהֶל", "ואוקפהם חואלי אלכ'בא",
         "and stationed them around the tent."),
    ],
    25: [
        ("וַיֵּרֶד יְהוָה בֶּעָנָן וַיְדַבֵּר אֵלָיו", "פתגלא אללה פי אלג'מאם וכ'אטבה",
         "And God appeared in the cloud and spoke with him"),
        ("וַיָּאצֶל מִן-הָרוּחַ אֲשֶׁר עָלָיו וַיִּתֵּן עַל-שִׁבְעִים אִישׁ הַזְּקֵנִים",
         "ואפאד. מן אלנור אלד'י עליה. וכסא אלסבעין אלרגל אלשיוך'",
         "and He imparted of the light which was upon him, and covered the seventy elder men with it"),
        ("וַיְהִי כְּנוֹחַ עֲלֵיהֶם הָרוּחַ וַיִּתְנַבְּאוּ וְלֹא יָסָפוּ",
         "פלמא אסתקר עליהם ד'אלך אלנור. תנבו ולם יחתאגו אלי' עודה",
         "and when that light settled upon them, they prophesied — and they had no need to return to it."),
    ],
    26: [
        ("וַיִּשָּׁאֲרוּ שְׁנֵי-אֲנָשִׁים בַּמַּחֲנֶה שֵׁם הָאֶחָד אֶלְדָּד וְשֵׁם הַשֵּׁנִי מֵידָד",
         "ובקי רגלאן פי אלעסכר. אסם אחדהמא אלדד. ואלת'אני מידד",
         "And two men remained in the camp — the name of one of them was Eldad, and the second Medad"),
        ("וַתָּנַח עֲלֵהֶם הָרוּחַ וְהֵמָּה בַּכְּתֻבִים",
         "ואסתקרת עליהם אלנבווה. והמא מן אלמכתובין",
         "and the prophecy settled upon them; and they were among those who were registered"),
        ("וְלֹא יָצְאוּ הָאֹהֱלָה וַיִּתְנַבְּאוּ בַּמַּחֲנֶה",
         "ולם יכ'רגו אלי' אלכ'בא. בל תנבו פי אלעסכר",
         "but they had not gone out to the tent; rather, they prophesied in the camp."),
    ],
    27: [
        ("וַיָּרָץ הַנַּעַר וַיַּגֵּד לְמֹשֶׁה", "פחאצ'ר אלג'לאם. ואכ'בר מוסי'",
         "And the youth came hurrying and informed Moses"),
        ("וַיֹּאמַר אֶלְדָּד וּמֵידָד מִתְנַבְּאִים בַּמַּחֲנֶה",
         "וקאל. אלדד ומידד. מתנביין פי אלעסכר",
         "and said: 'Eldad and Medad are prophesying in the camp.'"),
    ],
    28: [
        ("וַיַּעַן יְהוֹשֻׁעַ בִּן-נוּן מְשָׁרֵת מֹשֶׁה מִבְּחֻרָיו",
         "פאגאבה יהושע אבן נון. כ'אדם מוסי'. מן תלאמידה",
         "And Joshua son of Nun, Moses' attendant, one of his disciples, answered"),
        ("וַיֹּאמַר אֲדֹנִי מֹשֶׁה כְּלָאֵם", "וקאל. יא סיידי יא מוסי' אחבסהמא",
         "and said: 'My lord, O Moses — restrain them!'"),
    ],
    29: [
        ("וַיֹּאמֶר לוֹ מֹשֶׁה הַמְקַנֵּא אַתָּה לִי", "קאל לה מוסי'. הל תג'אר לי",
         "And Moses said to him: 'Are you jealous on my behalf?"),
        ("וּמִי יִתֵּן כָּל-עַם יְהוָה נְבִיאִים", "לית צאר גמיע אמה' אללה אנביא",
         "Would that all the nation of God might become prophets"),
        ("כִּי-יִתֵּן יְהוָה אֶת-רוּחוֹ עֲלֵיהֶם", "באן יגעל מן נורה ונבוותה עליהם",
         "that He might set of His light and His prophecy upon them!'"),
    ],
    30: [
        ("וַיֵּאָסֵף מֹשֶׁה אֶל-הַמַּחֲנֶה--הוּא וְזִקְנֵי יִשְׂרָאֵל",
         "פלמא אנצ'ם מוסי' אלי' אלעסכר. הו ושיוך בני אסראיל",
         "And when Moses rejoined the camp — he and the elders of the sons of Israel —"),
    ],
    31: [
        ("וְרוּחַ נָסַע מֵאֵת יְהוָה וַיָּגָז שַׂלְוִים מִן-הַיָּם",
         "והבת ריח מן ענד אללה. וקטעת סלוי מן אלבחר",
         "a wind blew from God, and it drove quail in from the sea"),
        ("וַיִּטֹּשׁ עַל-הַמַּחֲנֶה כְּדֶרֶךְ יוֹם כֹּה וּכְדֶרֶךְ יוֹם כֹּה סְבִיבוֹת הַמַּחֲנֶה",
         "ואלקתה עלי' אלעסכר שביה כמסיר יום ימנה ויסרה חואלי אלעסכר",
         "and cast them upon the camp, like a day's journey to the right and to the left around the camp"),
        ("וּכְאַמָּתַיִם עַל-פְּנֵי הָאָרֶץ", "וארתפאעה מן אלארץ' ד'ראעין",
         "and their height from the ground was two cubits."),
    ],
    32: [
        ("וַיָּקָם הָעָם כָּל-הַיּוֹם הַהוּא וְכָל-הַלַּיְלָה וְכֹל יוֹם הַמָּחֳרָת",
         "פקאם אלקום. באקי יומהם ולילתהם. וטול נהאר ג'דהם",
         "And the people rose — the remainder of their day and their night and the length of the next day"),
        ("וַיַּאַסְפוּ אֶת-הַשְּׂלָו--הַמַּמְעִיט אָסַף עֲשָׂרָה חֳמָרִים",
         "פגמעו אלסלוי. אקלהם. גמע עשרה אנאביר",
         "and gathered the quail; the least among them gathered ten heaps"),
        ("וַיִּשְׁטְחוּ לָהֶם שָׁטוֹחַ סְבִיבוֹת הַמַּחֲנֶה", "פסטחוה להם סטוחא. חואלי אלעסכר",
         "and they spread them out as layers around the camp."),
    ],
    33: [
        ("הַבָּשָׂר עוֹדֶנּוּ בֵּין שִׁנֵּיהֶם--טֶרֶם יִכָּרֵת",
         "ואלחם בעד בין אסנאנהם. קבל אן ימצ'ג'וה",
         "While the meat was still between their teeth, before they had chewed it"),
        ("וְאַף יְהוָה חָרָה בָעָם", "אד' אשתד ג'צ'ב אללה עליהם",
         "God's anger grew fierce against them"),
        ("וַיַּךְ יְהוָה בָּעָם מַכָּה רַבָּה מְאֹד", "פצ'רבהם צ'רבה ]עט'ימה] ]עט'ימה] עצ'ימה גדא",
         "and He struck them with a very great blow."),
    ],
    34: [
        ("וַיִּקְרָא אֶת-שֵׁם-הַמָּקוֹם הַהוּא קִבְרוֹת הַתַּאֲוָה",
         "וסמא ד'אלך אלמוצ'ע קבור אלשהוה",
         "And he called that place 'the Graves of Craving,'"),
        ("כִּי-שָׁם קָבְרוּ אֶת-הָעָם הַמִּתְאַוִּים", "לאנהם דפנו הנאך. אלקום אלמתשהיין",
         "because there they buried the people who had craved."),
    ],
    35: [
        ("מִקִּבְרוֹת הַתַּאֲוָה נָסְעוּ הָעָם חֲצֵרוֹת", "ורחלו מנה אלי' חצרות",
         "And they journeyed from there to Hazeroth"),
        ("וַיִּהְיוּ בַּחֲצֵרוֹת", "פלמא אקאמו בהא", "and when they settled there."),
    ],
}
