"""Hand-authored alignment triples for Bamidbar chapter 13."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "תם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("שְׁלַח-לְךָ אֲנָשִׁים", "אבעת' ברגאל", "Send forth men"),
        ("וְיָתֻרוּ אֶת-אֶרֶץ כְּנַעַן", "ירומון בלד כנעאן",
         "to scout the land of Canaan"),
        ("אֲשֶׁר-אֲנִי נֹתֵן לִבְנֵי יִשְׂרָאֵל", "אלד'י אנא מעטיה לבני אסראיל",
         "which I am giving to the sons of Israel"),
        ("אִישׁ אֶחָד אִישׁ אֶחָד לְמַטֵּה אֲבֹתָיו תִּשְׁלָחוּ", "רגל ואחד מן סבט אבאיה תבעת' בה",
         "one man from the tribe of their fathers you shall send with him"),
        ("כֹּל נָשִׂיא בָהֶם", "כל שריף מנהם", "every noble among them."),
    ],
    3: [
        ("וַיִּשְׁלַח אֹתָם מֹשֶׁה", "פבעת' בהם מוסי'", "And Moses sent them forth"),
        ("מִמִּדְבַּר פָּארָן עַל-פִּי יְהוָה", "מן ברייה' פארן עלי' קול אללה",
         "from the wilderness of Paran, at the word of God"),
        ("כֻּלָּם אֲנָשִׁים רָאשֵׁי בְנֵי-יִשְׂרָאֵל הֵמָּה",
         "כלהם רגאל. ריסא בני אסראיל",
         "all of them men, heads of the sons of Israel."),
    ],
    4: [
        ("וְאֵלֶּה שְׁמוֹתָם", "והד'ה אסמאיהם", "And these are their names"),
        ("לְמַטֵּה רְאוּבֵן", "מן סבט ראובן", "from the tribe of Reuben"),
        ("שַׁמּוּעַ בֶּן-זַכּוּר", "שמוע אבן זכור", "Shammua son of Zaccur."),
    ],
    5: [
        ("לְמַטֵּה שִׁמְעוֹן", "ומן סבט שמעון", "And from the tribe of Simeon"),
        ("שָׁפָט בֶּן-חוֹרִי", "שפט אבן חורי", "Shaphat son of Hori."),
    ],
    6: [
        ("לְמַטֵּה יְהוּדָה", "ומן סבט יהודה", "And from the tribe of Judah"),
        ("כָּלֵב בֶּן-יְפֻנֶּה", "כלב אבן יפונה", "Caleb son of Jephunneh."),
    ],
    7: [
        ("לְמַטֵּה יִשָּׂשכָר", "ומן סבט יששכר", "And from the tribe of Issachar"),
        ("יִגְאָל בֶּן-יוֹסֵף", "יגאל אבן יוסף", "Igal son of Joseph."),
    ],
    8: [
        ("לְמַטֵּה אֶפְרָיִם", "ומן סבט אפרים", "And from the tribe of Ephraim"),
        ("הוֹשֵׁעַ בִּן-נוּן", "הושע אבן נון", "Hoshea son of Nun."),
    ],
    9: [
        ("לְמַטֵּה בִנְיָמִן", "ומן סבט בנימין", "And from the tribe of Benjamin"),
        ("פַּלְטִי בֶּן-רָפוּא", "פלטי אבן רפוא", "Palti son of Raphu."),
    ],
    10: [
        ("לְמַטֵּה זְבוּלֻן", "ומן סבט זבולון", "And from the tribe of Zebulun"),
        ("גַּדִּיאֵל בֶּן-סוֹדִי", "גדיאל אבן סודי", "Gaddiel son of Sodi."),
    ],
    11: [
        ("לְמַטֵּה יוֹסֵף לְמַטֵּה מְנַשֶּׁה", "ומן סבט יוסף אלד'י הו סבט מנשה",
         "And from the tribe of Joseph — which is the tribe of Manasseh"),
        ("גַּדִּי בֶּן-סוּסִי", "גדי אבן סוסי", "Gaddi son of Susi."),
    ],
    12: [
        ("לְמַטֵּה דָן", "ומן סבט דן", "And from the tribe of Dan"),
        ("עַמִּיאֵל בֶּן-גְּמַלִּי", "עמיאל אבן גמלי", "Ammiel son of Gemalli."),
    ],
    13: [
        ("לְמַטֵּה אָשֵׁר", "ומן סבט אשר", "And from the tribe of Asher"),
        ("סְתוּר בֶּן-מִיכָאֵל", "סתור אבן מיכאל", "Sethur son of Michael."),
    ],
    14: [
        ("לְמַטֵּה נַפְתָּלִי", "ומן סבט נפתלי", "And from the tribe of Naphtali"),
        ("נַחְבִּי בֶּן-וָפְסִי", "נחבי אבן ופסי", "Nahbi son of Vophsi."),
    ],
    15: [
        ("לְמַטֵּה גָד", "ומן סבט גד", "And from the tribe of Gad"),
        ("גְּאוּאֵל בֶּן-מָכִי", "גאואל אבן מכי", "Geuel son of Machi."),
    ],
    16: [
        ("אֵלֶּה שְׁמוֹת הָאֲנָשִׁים אֲשֶׁר-שָׁלַח מֹשֶׁה לָתוּר אֶת-הָאָרֶץ",
         "והד'א אסמא אלרגאל. אלד'י בעת' בהם מוסי' לירומו אלבלד",
         "These are the names of the men whom Moses sent forth to scout the land."),
        ("וַיִּקְרָא מֹשֶׁה לְהוֹשֵׁעַ בִּן-נוּן יְהוֹשֻׁעַ",
         "וסמא מוסי'. הושע אבן נון יהושע",
         "And Moses called Hoshea son of Nun — Joshua."),
    ],
    17: [
        ("וַיִּשְׁלַח אֹתָם מֹשֶׁה לָתוּר אֶת-אֶרֶץ כְּנָעַן",
         "פבעת' בהם לירומו בלד כנעאן",
         "And he sent them forth to scout the land of Canaan"),
        ("וַיֹּאמֶר אֲלֵהֶם", "וקאל להם", "and said to them"),
        ("עֲלוּ זֶה בַּנֶּגֶב", "אצעדו אוולא אלי' אלדארום",
         "'Go up first to the south"),
        ("וַעֲלִיתֶם אֶת-הָהָר", "תם אצעדו אלי' אלגבל", "then go up to the mountain.'"),
    ],
    18: [
        ("וּרְאִיתֶם אֶת-הָאָרֶץ מַה-הִוא", "ואנצ'רו אלבלד מא הי",
         "'And observe the land — what it is"),
        ("וְאֶת-הָעָם הַיֹּשֵׁב עָלֶיהָ", "ואלקום אלמקימין פיה",
         "and the people who dwell in it"),
        ("הֶחָזָק הוּא הֲרָפֶה", "אהו שדיד אם מסתרכ'י",
         "whether it is strong or slack"),
        ("הַמְעַט הוּא אִם-רָב", "אקליל הו אם כת'יר",
         "whether it is few or many.'"),
    ],
    19: [
        ("וּמָה הָאָרֶץ אֲשֶׁר-הוּא יֹשֵׁב בָּהּ", "ומא אלארץ'. אלד'י הו סאכנהא",
         "'And what is the land in which it dwells"),
        ("הֲטוֹבָה הִוא אִם-רָעָה", "אגיידה הי אם רדייה",
         "whether it is good or poor"),
        ("וּמָה הֶעָרִים אֲשֶׁר-הוּא יוֹשֵׁב בָּהֵנָּה", "ומא אלקרא. אלד'י הו סאכנהא",
         "and what are the towns in which it dwells"),
        ("הַבְּמַחֲנִים אִם בְּמִבְצָרִים", "אפי ארבאץ' או פי חצון",
         "whether they are in open encampments or in fortresses.'"),
    ],
    20: [
        ("וּמָה הָאָרֶץ הַשְּׁמֵנָה הִוא אִם-רָזָה", "ומא הייה' אלארץ' . אהי סמינה אם הזלא",
         "'And what is the land — whether it is fat or lean"),
        ("הֲיֵשׁ-בָּהּ עֵץ אִם-אַיִן", "והל פיהא שגר מג'רוס אם לא",
         "and whether there are planted trees in it or not."),
        ("וְהִתְחַזַּקְתֶּם וּלְקַחְתֶּם מִפְּרִי הָאָרֶץ",
         "ותשדדו. וכ'דו מן ת'מרהא",
         "And be courageous, and take of its fruit.'"),
        ("וְהַיָּמִים--יְמֵי בִּכּוּרֵי עֲנָבִים", "והד'א אלפצל. אייאם בכור אלענב",
         "And behold, this season was the days of the first-ripening of the grapes."),
    ],
    21: [
        ("וַיַּעֲלוּ וַיָּתֻרוּ אֶת-הָאָרֶץ", "פצעדו וראמו אלבלד",
         "And they went up and scouted the land"),
        ("מִמִּדְבַּר-צִן עַד-רְחֹב לְבֹא חֲמָת",
         "מן ברייה' צין אלי' רחוב אלי' חמאה",
         "from the wilderness of Zin to Rehob, toward Hamath."),
    ],
    22: [
        ("וַיַּעֲלוּ בַנֶּגֶב וַיָּבֹא עַד-חֶבְרוֹן",
         "פצעדו אוולי' אלי' אלדארום וגאו אלי' חברא",
         "And they went up first to the south, and came to Hebron"),
        ("וְשָׁם אֲחִימַן שֵׁשַׁי וְתַלְמַי יְלִידֵי הָעֲנָק",
         "ות'ם אחימן ששי ותלמי. בני אלגבאברה",
         "and there were Ahiman, Sheshai, and Talmai — the children of the giants."),
        ("וְחֶבְרוֹן שֶׁבַע שָׁנִים נִבְנְתָה לִפְנֵי צֹעַן מִצְרָיִם",
         "וכאנת חברא קד בנית קבל צאן מנבר מצר בסבע סנין",
         "And Hebron had already been built before Zoan, the seat of Egypt, by seven years."),
    ],
    23: [
        ("וַיָּבֹאוּ עַד-נַחַל אֶשְׁכֹּל", "וגאו אלי' ואד אלענקוד",
         "And they came to the Valley of the Cluster"),
        ("וַיִּכְרְתוּ מִשָּׁם זְמוֹרָה וְאֶשְׁכּוֹל עֲנָבִים אֶחָד",
         "פקטעו מן ת'ם חבלה וענקוד ענב ואחד",
         "and cut from there a branch and one cluster of grapes"),
        ("וַיִּשָּׂאֻהוּ בַמּוֹט בִּשְׁנָיִם", "וחמלוה פי אלדהק פי מא בין את'נין",
         "and carried it on a pole between two"),
        ("וּמִן-הָרִמֹּנִים וּמִן-הַתְּאֵנִים", "ומן אלרמאן ומן אלתין",
         "and also some of the pomegranates and of the figs."),
    ],
    24: [
        ("לַמָּקוֹם הַהוּא קָרָא נַחַל אֶשְׁכּוֹל", "פלד'אלך סמי אלמוצ'ע ואד אלענקוד",
         "Therefore that place was named the Valley of the Cluster"),
        ("עַל אֹדוֹת הָאֶשְׁכּוֹל אֲשֶׁר-כָּרְתוּ מִשָּׁם בְּנֵי יִשְׂרָאֵל",
         "בסבב אלענקוד. אלד'י קטעו מנה בני אסראיל",
         "on account of the cluster which the sons of Israel cut from there."),
    ],
    25: [
        ("וַיָּשֻׁבוּ מִתּוּר הָאָרֶץ", "פרגעו מן ריאם אלבלד",
         "And they returned from scouting the land"),
        ("מִקֵּץ אַרְבָּעִים יוֹם", "בעד ארבעין יומא", "after forty days."),
    ],
    26: [
        ("וַיֵּלְכוּ וַיָּבֹאוּ אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן",
         "פסארו חתא גאו אלי' מוסי' והרון",
         "And they journeyed until they came to Moses and Aaron"),
        ("וְאֶל-כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל אֶל-מִדְבַּר פָּארָן",
         "וסאיר גמאעה' בני אסראיל. אלי' ברייה' פארן אלי' רקים",
         "and the rest of the congregation of the sons of Israel, to the wilderness of Paran, to Kadesh"),
        ("וַיָּשִׁיבוּ אֹתָם דָּבָר", "פאגאבוהם באלכ'בר",
         "and they answered them with the report"),
        ("וַיַּרְאוּם אֶת-פְּרִי הָאָרֶץ", "ואורוהם ת'מר אלארץ'",
         "and showed them the fruit of the land."),
    ],
    27: [
        ("וַיְסַפְּרוּ-לוֹ וַיֹּאמְרוּ", "פקצו עליה וקאלו", "And they recounted to him, and said"),
        ("בָּאנוּ אֶל-הָאָרֶץ אֲשֶׁר שְׁלַחְתָּנוּ", "צרנא אלי' אלבלד אלד'י בעת'ת בנא",
         "'We went to the land to which you sent us"),
        ("וְגַם זָבַת חָלָב וּדְבַשׁ הִוא", "וחקא אנה יפיץ' אללבן ואלעסל",
         "and indeed it flows with milk and honey"),
        ("וְזֶה-פִּרְיָהּ", "והד'א ת'מרה", "and here is its fruit.'"),
    ],
    28: [
        ("אֶפֶס כִּי-עַז הָעָם הַיֹּשֵׁב בָּאָרֶץ",
         "כלא אן אלקום אלמקימין פיה עזיזין",
         "'However, the people who dwell in it are mighty"),
        ("וְהֶעָרִים בְּצֻרוֹת גְּדֹלֹת מְאֹד", "ואלקרא. חצינה עצימה גדא",
         "and the towns are very greatly fortified"),
        ("וְגַם-יְלִדֵי הָעֲנָק רָאִינוּ שָׁם",
         "ואיצ'א אולאד אלגבאברה ראינאהם תם",
         "and moreover, the children of the giants — we saw them there.'"),
    ],
    29: [
        ("עֲמָלֵק יוֹשֵׁב בְּאֶרֶץ הַנֶּגֶב", "אלעמאלקה מקימין פי בלד אלדארום",
         "'The Amalekites dwell in the land of the south"),
        ("וְהַחִתִּי וְהַיְבוּסִי וְהָאֱמֹרִי יוֹשֵׁב בָּהָר",
         "ואלחתיין. ואליבוסיין ואלאמוריין מקימין פי אלגבל",
         "and the Hittites and the Jebusites and the Amorites dwell in the mountain"),
        ("וְהַכְּנַעֲנִי יוֹשֵׁב עַל-הַיָּם וְעַל יַד הַיַּרְדֵּן",
         "ואלכנאעניין מקימין עלי' אלבחר. ועלי שאט אלארדון",
         "and the Canaanites dwell by the sea and along the bank of the Jordan.'"),
    ],
    30: [
        ("וַיַּהַס כָּלֵב אֶת-הָעָם אֶל-מֹשֶׁה",
         "פאסכת כלב אלקום אלי' קול מוסי'",
         "And Caleb silenced the people toward what Moses had said"),
        ("וַיֹּאמֶר עָלֹה נַעֲלֶה וְיָרַשְׁנוּ אֹתָהּ",
         "וקאל. בל נצעד צעודא ונחוזה",
         "and said: 'Nay, we shall go up and seize it"),
        ("כִּי-יָכוֹל נוּכַל לָהּ", "פאנא נטיקהם",
         "for we are able to overcome them!'"),
    ],
    31: [
        ("וְהָאֲנָשִׁים אֲשֶׁר-עָלוּ עִמּוֹ אָמְרוּ",
         "ואלקום אלד'ין מצ'ו מעה קאלו",
         "But the men who had gone with him said"),
        ("לֹא נוּכַל לַעֲלוֹת אֶל-הָעָם", "לא נטיק אן נצעד אלי' אלקום",
         "'We are not able to go up to the people"),
        ("כִּי-חָזָק הוּא מִמֶּנּוּ", "לאנהם אשד מנא", "for they are stronger than us.'"),
    ],
    32: [
        ("וַיֹּצִיאוּ דִּבַּת הָאָרֶץ אֲשֶׁר תָּרוּ אֹתָהּ אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר",
         "ואכ'רגו שנאעה רדייה. עלי' אלבלד אלד'י ראמוה. לבני אסראיל וקאלו",
         "And they spread an evil slander against the land which they had scouted, to the sons of Israel, saying"),
        ("הָאָרֶץ אֲשֶׁר עָבַרְנוּ בָהּ לָתוּר אֹתָהּ אֶרֶץ אֹכֶלֶת יוֹשְׁבֶיהָ הִוא",
         "אלבלד אלד'י מררנא פיה לנרומה. הו בלד יהלך אהלה",
         "'The land through which we passed to scout it is a land that destroys its inhabitants"),
        ("וְכָל-הָעָם אֲשֶׁר-רָאִינוּ בְתוֹכָהּ אַנְשֵׁי מִדּוֹת",
         "וגמיע אלקום. אלד'י ראינאהם פיה ד'וי מסאחה",
         "and all the people whom we saw in it are of great stature.'"),
    ],
    33: [
        ("וְשָׁם רָאִינוּ אֶת-הַנְּפִילִים בְּנֵי עֲנָק", "וראינא ת'ם אלעלוג. בני אלגבאברה מן עלוגהם",
         "'And we saw there the brutes — children of the giants from among their brutes"),
        ("וַנְּהִי בְעֵינֵינוּ כַּחֲגָבִים", "וצרנא פי עיוננא כאלגראד",
         "and we were in our own eyes as locusts"),
        ("וְכֵן הָיִינוּ בְּעֵינֵיהֶם", "וכד'אך כנא פי עיונהם",
         "and so were we in their eyes.'"),
    ],
}
