"""Hand-authored alignment triples for Bamidbar chapter 31."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("נְקֹם נִקְמַת בְּנֵי יִשְׂרָאֵל מֵאֵת הַמִּדְיָנִים",
         "אנתקם נקמה' בני אסראיל. מן אלמדיאניין",
         "'Exact the vengeance of the sons of Israel upon the Midianites"),
        ("אַחַר תֵּאָסֵף אֶל-עַמֶּיךָ",
         "בעד ד'אלך תנצ'ם אלי' קומך",
         "after that, you shall be gathered to your people.'"),
    ],
    3: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-הָעָם לֵאמֹר",
         "פכלם מוסי' קומה קאילא",
         "And Moses spoke to his people, saying:"),
        ("הֵחָלְצוּ מֵאִתְּכֶם אֲנָשִׁים לַצָּבָא",
         "גרדו מנכם. רגאלא לאלגיש",
         "'Detach from among you men for the army"),
        ("וְיִהְיוּ עַל-מִדְיָן לָתֵת נִקְמַת-יְהוָה בְּמִדְיָן",
         "יג'זו אלי' מדין ליחל נקמה אללה בהם",
         "to campaign against Midian, that the vengeance of God may fall upon them.'"),
    ],
    4: [
        ("אֶלֶף לַמַּטֶּה אֶלֶף לַמַּטֶּה--לְכֹל מַטּוֹת יִשְׂרָאֵל תִּשְׁלְחוּ לַצָּבָא",
         "אלף מן כל סבט. מן אסבאט בני אסראיל. תבעתו בהם לאלג'זו",
         "'A thousand from each tribe, from the tribes of the sons of Israel, you shall send forth for the campaign.'"),
    ],
    5: [
        ("וַיִּמָּסְרוּ מֵאַלְפֵי יִשְׂרָאֵל אֶלֶף לַמַּטֶּה",
         "פאנמאז מן אלוף בני אסראיל. אלף מן כל סבט",
         "And there were singled out from the thousands of the sons of Israel, a thousand from each tribe"),
        ("שְׁנֵים-עָשָׂר אֶלֶף חֲלוּצֵי צָבָא",
         "פצארו את'ני עשר אלף מגרדין לאלג'זו",
         "and they became twelve thousand equipped for the campaign."),
    ],
    6: [
        ("וַיִּשְׁלַח אֹתָם מֹשֶׁה אֶלֶף לַמַּטֶּה לַצָּבָא",
         "פבעת' בהם מוסי'",
         "And Moses sent them forth"),
        ("אֹתָם וְאֶת-פִּינְחָס בֶּן-אֶלְעָזָר הַכֹּהֵן לַצָּבָא",
         "ובפינחס אבן אלעזר אלאמאם לאלג'זו",
         "and Phinehas son of Eleazar the imām with them for the campaign"),
        ("וּכְלֵי הַקֹּדֶשׁ וַחֲצֹצְרוֹת הַתְּרוּעָה בְּיָדוֹ",
         "ואניה' אלקדס. ואבואק אלתגליב פי ידה",
         "with the sacred vessels and the rallying trumpets in his hand."),
    ],
    7: [
        ("וַיִּצְבְּאוּ עַל-מִדְיָן כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "פג'זו אלי' מדין. כמא אמר אללה מוסי'",
         "And they campaigned against Midian, as God had commanded Moses"),
        ("וַיַּהַרְגוּ כָּל-זָכָר",
         "וקתלו כל ד'כר",
         "and they slew every male."),
    ],
    8: [
        ("וְאֶת-מַלְכֵי מִדְיָן הָרְגוּ עַל-חַלְלֵיהֶם",
         "וקתלו כ'מסה מלוך מדין מע קתלאהם",
         "And they slew the five kings of Midian together with their slain"),
        ("אֶת-אֱוִי וְאֶת-רֶקֶם וְאֶת-צוּר וְאֶת-חוּר וְאֶת-רֶבַע--חֲמֵשֶׁת מַלְכֵי מִדְיָן",
         "אוי ורקם וצור וחור ורבע",
         "Evi, and Rekem, and Zur, and Hur, and Reba"),
        ("וְאֵת בִּלְעָם בֶּן-בְּעוֹר הָרְגוּ בֶּחָרֶב",
         "ואיצ'א בלעם אבן בעור. קתלוה באלסיף",
         "and also Balaam son of Beor they slew with the sword."),
    ],
    9: [
        ("וַיִּשְׁבּוּ בְנֵי-יִשְׂרָאֵל אֶת-נְשֵׁי מִדְיָן וְאֶת-טַפָּם",
         "וסבא בני אסראיל נסא מדין ואטפאלהם",
         "And the sons of Israel took captive the women of Midian and their children"),
        ("וְאֵת כָּל-בְּהֶמְתָּם וְאֶת-כָּל-מִקְנֵהֶם וְאֶת-כָּל-חֵילָם בָּזָזוּ",
         "וגמיע בהאימהם ומואשיהם. ואת'את'הם ג'נמו",
         "and all their beasts and their livestock, and their furnishings they plundered."),
    ],
    10: [
        ("וְאֵת כָּל-עָרֵיהֶם בְּמוֹשְׁבֹתָם וְאֵת כָּל-טִירֹתָם--שָׂרְפוּ בָּאֵשׁ",
         "וגמיע קראהם. מע מסאכנהם וקצורהם. אחרקוהא באלנאר",
         "And all their towns, together with their dwellings and their palaces, they burned with fire."),
    ],
    11: [
        ("וַיִּקְחוּ אֶת-כָּל-הַשָּׁלָל וְאֵת כָּל-הַמַּלְקוֹחַ--בָּאָדָם וּבַבְּהֵמָה",
         "ואכ'דו גמיע אלסלב ואלפי. מן אלנאס ואלבהאים",
         "And they took all the spoil and the fay — from the people and the beasts."),
    ],
    12: [
        ("וַיָּבִאוּ אֶל-מֹשֶׁה וְאֶל-אֶלְעָזָר הַכֹּהֵן וְאֶל-עֲדַת בְּנֵי-יִשְׂרָאֵל",
         "וגאו אלי' מוסי'. ואלי אלעזר אלאמאם וגמאעה' בני אסראיל",
         "And they came to Moses, and to Eleazar the imām, and to the assembly of the sons of Israel"),
        ("אֶת-הַשְּׁבִי וְאֶת-הַמַּלְקוֹחַ וְאֶת-הַשָּׁלָל",
         "באלסבי ואלפי ואלנהב",
         "with the captives and the fay and the plunder"),
        ("אֶל-הַמַּחֲנֶה אֶל-עַרְבֹת מוֹאָב אֲשֶׁר עַל-יַרְדֵּן יְרֵחוֹ",
         "אלי' אלעסכר. אלי' בידאת מואב. אלתי עלי' ארדן יריחא",
         "to the encampment — to the wilderness plain of Moab, which is by the Jordan of Jericho."),
    ],
    13: [
        ("וַיֵּצְאוּ מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן וְכָל-נְשִׂיאֵי הָעֵדָה",
         "פכ'רג מוסי' ואלעזר אלאמאם. וסאיר אשראף אלגמאעה",
         "And Moses and Eleazar the imām, and the rest of the chiefs of the assembly"),
        ("לִקְרָאתָם אֶל-מִחוּץ לַמַּחֲנֶה",
         "תלקאהם. אלי' כ'ארג אלעסכר",
         "went out to meet them, outside the encampment."),
    ],
    14: [
        ("וַיִּקְצֹף מֹשֶׁה עַל פְּקוּדֵי הֶחָיִל",
         "פסכ'ט מוסי'. עלי' אלמווכלין באלגיש",
         "And Moses was wrathful with those entrusted over the army"),
        ("שָׂרֵי הָאֲלָפִים וְשָׂרֵי הַמֵּאוֹת הַבָּאִים מִצְּבָא הַמִּלְחָמָה",
         "רויסא אלאלוף ורויסא אלמיין. אלגאיין מן אלחרב",
         "the commanders of the thousands and the commanders of the hundreds — who were coming from the battle."),
    ],
    15: [
        ("וַיֹּאמֶר אֲלֵיהֶם מֹשֶׁה הַחִיִּיתֶם כָּל-נְקֵבָה",
         "פקאל להם מוסי'. הל אסתבקיתם כל אנתי'",
         "And Moses said to them: 'Have you let every female live?'"),
    ],
    16: [
        ("הֵן הֵנָּה הָיוּ לִבְנֵי יִשְׂרָאֵל בִּדְבַר בִּלְעָם",
         "אליס הן כנן לבני אסראיל בקול בלעם",
         "'Were not these the ones who were to the sons of Israel, by the word of Balaam"),
        ("לִמְסָר-מַעַל בַּיהוָה עַל-דְּבַר-פְּעוֹר",
         "חתי אוקען נכת'א באללה בסבב פעור",
         "until they brought about a breach of faith with God on account of Peor"),
        ("וַתְּהִי הַמַּגֵּפָה בַּעֲדַת יְהוָה",
         "פחל אלובא בגמאעה' אללה",
         "and so the pestilence fell upon the assembly of God?'"),
    ],
    17: [
        ("וְעַתָּה הִרְגוּ כָל-זָכָר בַּטָּף",
         "ואלאן. אקתלו כל ד'כר מן אלאטפאל",
         "'And now: kill every male among the children"),
        ("וְכָל-אִשָּׁה יֹדַעַת אִישׁ לְמִשְׁכַּב זָכָר--הֲרֹגוּ",
         "וכל אמראה. קד ערפת מצ'אגעה' אלרגאל אקתלוהא",
         "and every woman who has known the lying with men — kill her.'"),
    ],
    18: [
        ("וְכֹל הַטַּף בַּנָּשִׁים אֲשֶׁר לֹא-יָדְעוּ מִשְׁכַּב זָכָר--הַחֲיוּ לָכֶם",
         "וסאיר אטפאל אלנסא. אלד'י לם יערפן מצ'אגעה' אלרגאל. אסתבקוהן לכם",
         "'And the rest of the female children, who have not known the lying with men — let them live for yourselves.'"),
    ],
    19: [
        ("וְאַתֶּם חֲנוּ מִחוּץ לַמַּחֲנֶה--שִׁבְעַת יָמִים",
         "ואנתם. פאנזלו כ'ארג אלעסכר סבעה' אייאם",
         "'And as for you — encamp outside the encampment seven days"),
        ("כֹּל הֹרֵג נֶפֶשׁ וְכֹל נֹגֵעַ בֶּחָלָל",
         "כל מן קתל נפסא וכל מן דנא בקתיל",
         "every one who has slain a person, and every one who has approached a slain man"),
        ("תִּתְחַטְּאוּ בַּיּוֹם הַשְּׁלִישִׁי וּבַיּוֹם הַשְּׁבִיעִי--אַתֶּם וּשְׁבִיכֶם",
         "תתד'כו פי אליום אלת'אלת' ופי אליום אלסאבע. אנתם וסביכם",
         "shall be purified on the third day and on the seventh day — you and your captives.'"),
    ],
    20: [
        ("וְכָל-בֶּגֶד וְכָל-כְּלִי-עוֹר וְכָל-מַעֲשֵׂה עִזִּים וְכָל-כְּלִי-עֵץ--תִּתְחַטָּאוּ",
         "וכל ת'וב ואניה מן גלוד. ומעמול מן מרעזא ואניה' כ'שב. תד'כוה",
         "'And every garment and every vessel of leather, and anything made of fine soft wool and vessels of wood — purify them.'"),
    ],
    21: [
        ("וַיֹּאמֶר אֶלְעָזָר הַכֹּהֵן אֶל-אַנְשֵׁי הַצָּבָא הַבָּאִים לַמִּלְחָמָה",
         "ת'ם קאל אלעזר אלאמאם לאלרגאל אלג'זאה. אלגאיין מן אלחרב",
         "Then Eleazar the imām said to the men, the warriors, who were coming from the battle:"),
        ("זֹאת חֻקַּת הַתּוֹרָה אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "הד'א רסם אלשריעה. אלתי אמר אללה בהא מוסי'",
         "'This is the ordinance of the law which God commanded Moses.'"),
    ],
    22: [
        ("אַךְ אֶת-הַזָּהָב וְאֶת-הַכָּסֶף אֶת-הַנְּחֹשֶׁת אֶת-הַבַּרְזֶל אֶת-הַבְּדִיל וְאֶת-הָעֹפָרֶת",
         "אמא אלד'הב ואלפצה. ואלנחאס ואלחדיד. ואלקלעי ואלאסרב",
         "'As for the gold and the silver, the copper and the iron, the tin and the lead —'"),
    ],
    23: [
        ("כָּל-דָּבָר אֲשֶׁר-יָבֹא בָאֵשׁ תַּעֲבִירוּ בָאֵשׁ וְטָהֵר",
         "פכל שי ימכן אן ידכ'ל פי אלנאר. אמרוה באלנאר ויטהר",
         "'every thing that can enter into fire — pass it through the fire and it shall be clean"),
        ("אַךְ בְּמֵי נִדָּה יִתְחַטָּא",
         "ואיצ'א יד'כא במא אלנצ'ח",
         "and it shall also be purified with the water of sprinkling."),
        ("וְכֹל אֲשֶׁר לֹא-יָבֹא בָּאֵשׁ תַּעֲבִירוּ בַמָּיִם",
         "וכל מא לא ידכ'ל. פי אלנאר אמרוה באלמא",
         "And everything that cannot enter into fire — pass it through the water.'"),
    ],
    24: [
        ("וְכִבַּסְתֶּם בִּגְדֵיכֶם בַּיּוֹם הַשְּׁבִיעִי וּטְהַרְתֶּם",
         "ואגסלו ת'יאבכם פי אליום אלסאבע ואטהרו",
         "'And wash your garments on the seventh day, and be clean"),
        ("וְאַחַר תָּבֹאוּ אֶל-הַמַּחֲנֶה",
         "ובעד ד'אלך תדכ'לו אלי' אלעסכר",
         "and after that you shall enter the encampment.'"),
    ],
    25: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "פקאל אללה למוסי קאילא",
         "And God said to Moses, saying:"),
    ],
    26: [
        ("שָׂא אֵת רֹאשׁ מַלְקוֹחַ הַשְּׁבִי בָּאָדָם וּבַבְּהֵמָה",
         "ארפע גמלה' פי אלסבי. מן אלנאס ואלבהאים",
         "'Take up the total count of what is in the captivity — of people and of beasts"),
        ("אַתָּה וְאֶלְעָזָר הַכֹּהֵן וְרָאשֵׁי אֲבוֹת הָעֵדָה",
         "אנת ואלעזר אלאמאם. ורויסא אבא אלגמאעה",
         "you and Eleazar the imām and the heads of the fathers of the assembly.'"),
    ],
    27: [
        ("וְחָצִיתָ אֶת-הַמַּלְקוֹחַ בֵּין תֹּפְשֵׂי הַמִּלְחָמָה הַיֹּצְאִים לַצָּבָא--וּבֵין כָּל-הָעֵדָה",
         "ואקסם ד'אלך. בין אהל אלחרב. אלד'ין כ'רגו לאלג'זו. ובין סאיר אלגמאעה",
         "'And divide it between the men of war who went out for the campaign, and the rest of the assembly.'"),
    ],
    28: [
        ("וַהֲרֵמֹתָ מֶכֶס לַיהוָה מֵאֵת אַנְשֵׁי הַמִּלְחָמָה הַיֹּצְאִים לַצָּבָא",
         "וארפע מכסא ללה. מן אהל אלחרב אלכ'ארגין לאלג'זו",
         "'And levy a tax for God from the men of war who went out for the campaign"),
        ("אֶחָד נֶפֶשׁ מֵחֲמֵשׁ הַמֵּאוֹת מִן-הָאָדָם וּמִן-הַבָּקָר וּמִן-הַחֲמֹרִים וּמִן-הַצֹּאן",
         "ראסא ואחדא. מן כל כ'מס מאיה. מן אלנאס ואלבקר. ואלחמיר ואלג'נם",
         "one head from every five hundred, of the people, and of the cattle, and of the donkeys, and of the flock.'"),
    ],
    29: [
        ("מִמַּחֲצִיתָם תִּקָּחוּ",
         "כ'דו ד'אלך מן קסמהם",
         "'Take that from their portion"),
        ("וְנָתַתָּה לְאֶלְעָזָר הַכֹּהֵן תְּרוּמַת יְהוָה",
         "רפיעה ללה. ואדפעו ד'אלך לאלעזר אלאמאם",
         "as an elevation-gift for God, and deliver it to Eleazar the imām.'"),
    ],
    30: [
        ("וּמִמַּחֲצִת בְּנֵי-יִשְׂרָאֵל תִּקַּח אֶחָד אָחֻז מִן-הַחֲמִשִּׁים",
         "וכ'ד' מן קסם בני אסראיל ואחדא מן כ'מסין",
         "'And from the portion of the sons of Israel, take one from every fifty"),
        ("מִן-הָאָדָם מִן-הַבָּקָר מִן-הַחֲמֹרִים וּמִן-הַצֹּאן--מִכָּל-הַבְּהֵמָה",
         "מן אלנאס ואלבקר. ואלחמיר ואלג'נם וסאיר אלבהאים",
         "of the people, and of the cattle, and of the donkeys, and of the flock, and the rest of the beasts"),
        ("וְנָתַתָּה אֹתָם לַלְוִיִּם שֹׁמְרֵי מִשְׁמֶרֶת מִשְׁכַּן יְהוָה",
         "ואדפע ד'אלך אלי' אלליואניין. חאפצ'י מחפץ' מסכן אללה",
         "and deliver it to the Levites, the keepers of the charge of the tabernacle of God.'"),
    ],
    31: [
        ("וַיַּעַשׂ מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "פצנע מוסי'. ואלעזר אלאמאם. כמא אמר אללה מוסי'",
         "And Moses and Eleazar the imām did as God had commanded Moses."),
    ],
    32: [
        ("וַיְהִי הַמַּלְקוֹחַ--יֶתֶר הַבָּז אֲשֶׁר בָּזְזוּ עַם הַצָּבָא",
         "וכאן אלפי. ג'מלה' אלג'נימה. אלתי ג'נמהא אלקום אלג'זאה",
         "And the fay — the total of the plunder which the raiding people had plundered"),
        ("צֹאן שֵׁשׁ-מֵאוֹת אֶלֶף וְשִׁבְעִים אֶלֶף--וַחֲמֵשֶׁת אֲלָפִים",
         "עדד אלג'נם. סת מאיה' אלף. וכמסה וסבעין אלפא",
         "the number of the flock: six hundred thousand and seventy-five thousand."),
    ],
    33: [
        ("וּבָקָר שְׁנַיִם וְשִׁבְעִים אָלֶף",
         "ועדד אלבקר. את'נין וסבעין אלפא",
         "And the number of the cattle: seventy-two thousand."),
    ],
    34: [
        ("וַחֲמֹרִים אֶחָד וְשִׁשִּׁים אָלֶף",
         "ועדד אלחמיר. ואחד וסתין אלפא",
         "And the number of the donkeys: sixty-one thousand."),
    ],
    35: [
        ("וְנֶפֶשׁ אָדָם--מִן-הַנָּשִׁים אֲשֶׁר לֹא-יָדְעוּ מִשְׁכַּב זָכָר כָּל-נֶפֶשׁ שְׁנַיִם וּשְׁלֹשִׁים אָלֶף",
         "ומן אלנאס. מן אלנסא. אלתי לם יערפן מצ'אגעה' אלרגאל. את'נין ות'לאת'ין אלפא",
         "And from the people, from the women who had not known the lying with men: thirty-two thousand."),
    ],
    36: [
        ("וַתְּהִי הַמֶּחֱצָה--חֵלֶק הַיֹּצְאִים בַּצָּבָא",
         "פכאן נצף ד'אלך. והו נציב אלד'י כ'רגו לאלג'זו",
         "And the half thereof — being the portion of those who went out for the campaign"),
        ("מִסְפַּר הַצֹּאן שְׁלֹשׁ-מֵאוֹת אֶלֶף וּשְׁלֹשִׁים אֶלֶף וְשִׁבְעַת אֲלָפִים וַחֲמֵשׁ מֵאוֹת",
         "עדד אלג'נם. ת'לאת' מאיה אלף. וסבעה ות'לאת'ין אלפא וכ'מס מאיה",
         "the number of the flock: three hundred thousand and thirty-seven thousand and five hundred."),
    ],
    37: [
        ("וַיְהִי הַמֶּכֶס לַיהוָה מִן-הַצֹּאן--שֵׁשׁ מֵאוֹת חָמֵשׁ וְשִׁבְעִים",
         "פכאן עדד אלמכס ללה מן אלג'נם. סת מאיה וכמסה וסבעין ראסא",
         "And the number of the tax for God from the flock was six hundred and seventy-five head."),
    ],
    38: [
        ("וְהַבָּקָר--שִׁשָּׁה וּשְׁלֹשִׁים אָלֶף וּמִכְסָם לַיהוָה שְׁנַיִם וְשִׁבְעִים",
         "ואד' אלבקר סתה ות'לאת'ין אלפא. פמכסהם ללה את'נין וסבעין",
         "And the number of the cattle: thirty-six thousand; and their tax for God: seventy-two."),
    ],
    39: [
        ("וַחֲמֹרִים שְׁלֹשִׁים אֶלֶף וַחֲמֵשׁ מֵאוֹת וּמִכְסָם לַיהוָה אֶחָד וְשִׁשִּׁים",
         "ואד' אלחמיר. ת'לאת'ין אלפא וכ'מס מאיה. פמכסהם ללה ואחד וסתין",
         "And the number of the donkeys: thirty thousand and five hundred; and their tax for God: sixty-one."),
    ],
    40: [
        ("וְנֶפֶשׁ אָדָם שִׁשָּׁה עָשָׂר אָלֶף וּמִכְסָם לַיהוָה--שְׁנַיִם וּשְׁלֹשִׁים נָפֶשׁ",
         "ואד' נפוס אלנאס. סתה' עשר אלפא. פמכסהם ללה. את'נין ות'לאת'ין נפסא",
         "And the number of persons: sixteen thousand; and their tax for God: thirty-two persons."),
    ],
    41: [
        ("וַיִּתֵּן מֹשֶׁה אֶת-מֶכֶס תְּרוּמַת יְהוָה לְאֶלְעָזָר הַכֹּהֵן--כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "פדפע מוסי'. אלמכס אלמרפוע ללה. אלי' אלעזר אלאמאם. כמא אמרה אללה",
         "And Moses delivered the tax levied for God to Eleazar the imām, as God had commanded him."),
    ],
    42: [
        ("וּמִמַּחֲצִית בְּנֵי יִשְׂרָאֵל אֲשֶׁר חָצָה מֹשֶׁה מִן-הָאֲנָשִׁים הַצֹּבְאִים",
         "ומן קסם בני אסראיל אלד'י קסם מוסי'. מן אלקום אלג'זאה",
         "And from the count of the portion of the sons of Israel which Moses had divided from the raiding people —"),
    ],
    43: [
        ("וַתְּהִי מֶחֱצַת הָעֵדָה מִן-הַצֹּאן--שְׁלֹשׁ-מֵאוֹת אֶלֶף וּשְׁלֹשִׁים אֶלֶף שִׁבְעַת אֲלָפִים וַחֲמֵשׁ מֵאוֹת",
         "פכאן ד'אלך מן אלג'נם. ת'לאת' מאיה' אלף. וסבעה ות'לאת'ין אלפא וכ'מס מאיה",
         "that was, from the flock: three hundred thousand and thirty-seven thousand and five hundred;"),
    ],
    44: [
        ("וּבָקָר שִׁשָּׁה וּשְׁלֹשִׁים אָלֶף",
         "ומן אלבקר. סתה ות'לאת'ין אלפא",
         "and from the cattle: thirty-six thousand;"),
    ],
    45: [
        ("וַחֲמֹרִים שְׁלֹשִׁים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ומן אלחמיר. ת'לאת'ין אלפא וכ'מס מאיה",
         "and from the donkeys: thirty thousand and five hundred;"),
    ],
    46: [
        ("וְנֶפֶשׁ אָדָם שִׁשָּׁה עָשָׂר אָלֶף",
         "ומן נפוס אלנאס. סתה' עשר אלפא",
         "and from the persons: sixteen thousand —"),
    ],
    47: [
        ("וַיִּקַּח מֹשֶׁה מִמַּחֲצִת בְּנֵי-יִשְׂרָאֵל אֶת-הָאָחֻז אֶחָד מִן-הַחֲמִשִּׁים--מִן-הָאָדָם וּמִן-הַבְּהֵמָה",
         "פאכ'ד' מוסי' מן ד'אלך. ואחדא מן כל כ'מסין. מן אלנאס ואלבהאים",
         "Moses took from that one from every fifty, of the people and the beasts"),
        ("וַיִּתֵּן אֹתָם לַלְוִיִּם שֹׁמְרֵי מִשְׁמֶרֶת מִשְׁכַּן יְהוָה כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "ודפעהא אלי' אלליוניין. חאפצ'י מחפץ' מסכן אללה. כמא אמרה",
         "and delivered it to the Levites, the keepers of the charge of the tabernacle of God, as He had commanded him."),
    ],
    48: [
        ("וַיִּקְרְבוּ אֶל-מֹשֶׁה הַפְּקֻדִים אֲשֶׁר לְאַלְפֵי הַצָּבָא--שָׂרֵי הָאֲלָפִים וְשָׂרֵי הַמֵּאוֹת",
         "ת'ם תקדם אלי' מוסי' אלמווכלין באלוף אלגיש. רויסא אלאלוף ורויסא אלמיין",
         "Then those entrusted over the thousands of the army — the commanders of the thousands and the commanders of the hundreds — came forward to Moses,"),
    ],
    49: [
        ("וַיֹּאמְרוּ אֶל-מֹשֶׁה עֲבָדֶיךָ נָשְׂאוּ אֶת-רֹאשׁ אַנְשֵׁי הַמִּלְחָמָה אֲשֶׁר בְּיָדֵנוּ",
         "פקאלו למוסי. אן עבידך רפעו. ג'מלה' אהל אלחרב אלד'ין מענא",
         "and said to Moses: 'Your servants have tallied the total of the men of war who are with us"),
        ("וְלֹא-נִפְקַד מִמֶּנּוּ אִישׁ",
         "ולם י'פקד מנא רגל",
         "and not a man is missing from us.'"),
    ],
    50: [
        ("וַנַּקְרֵב אֶת-קָרְבַּן יְהוָה אִישׁ אֲשֶׁר מָצָא כְלִי-זָהָב",
         "וקד קדמנא קרבאן אללה אי רגל מנא וגד אניה' ד'הב",
         "'And we have brought forward the offering of God — every man among us who found golden vessels"),
        ("אֶצְעָדָה וְצָמִיד טַבַּעַת עָגִיל וְכוּמָז",
         "מן דמלג וסואר. וחלקה ותרכי וחקאב",
         "armlets and bracelets, rings and earrings and girdles"),
        ("לְכַפֵּר עַל-נַפְשֹׁתֵינוּ לִפְנֵי יְהוָה",
         "לנסתג'פר ען נפוסנא בין ידי אללה",
         "to seek forgiveness for our souls before God.'"),
    ],
    51: [
        ("וַיִּקַּח מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן אֶת-הַזָּהָב--מֵאִתָּם כֹּל כְּלִי מַעֲשֶׂה",
         "פקבץ' מוסי' ואלעזר אלאמאם. ד'אלך אלד'הב מנהם. כל אניה מצווג'ה",
         "And Moses and Eleazar the imām received that gold from them — every wrought vessel."),
    ],
    52: [
        ("וַיְהִי כָּל-זְהַב הַתְּרוּמָה אֲשֶׁר הֵרִימוּ לַיהוָה",
         "פכאן כל ד'הב אלרפיעה. אלד'י רפעו ללה",
         "And all the gold of the elevation-gifts which they raised up for God"),
        ("שִׁשָּׁה עָשָׂר אֶלֶף שְׁבַע-מֵאוֹת וַחֲמִשִּׁים שָׁקֶל",
         "סתה' עשר אלף. וסבע מאיה וכ'מסין מת'קאל",
         "was sixteen thousand seven hundred and fifty weights"),
        ("מֵאֵת שָׂרֵי הָאֲלָפִים וּמֵאֵת שָׂרֵי הַמֵּאוֹת",
         "מן רויסא אלאלוף. ומן רויסא אלמיין",
         "from the commanders of the thousands and from the commanders of the hundreds."),
    ],
    53: [
        ("אַנְשֵׁי הַצָּבָא בָּזְזוּ אִישׁ לוֹ",
         "אמא סאיר אהל אלג'זו. פמא ג'נמוה כל ואחד כאן לה",
         "As for the rest of the men of the campaign — whatever each one had plundered belonged to him."),
    ],
    54: [
        ("וַיִּקַּח מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן אֶת-הַזָּהָב מֵאֵת שָׂרֵי הָאֲלָפִים וְהַמֵּאוֹת",
         "ולמא אכ'ד' מוסי'. ואלעזר אלאמאם אלד'הב. מן רויסא אלאלוף ואלמיין",
         "And when Moses and Eleazar the imām had received the gold from the commanders of the thousands and the hundreds"),
        ("וַיָּבִאוּ אֹתוֹ אֶל-אֹהֶל מוֹעֵד זִכָּרוֹן לִבְנֵי-יִשְׂרָאֵל לִפְנֵי יְהוָה",
         "אתו בה אלי' כ'בא אלמחצ'ר. ד'כרא לבני אסראיל בין ידי אללה",
         "they brought it to the tent of the assembly, as a memorial for the sons of Israel before God."),
    ],
}
