"""Hand-authored alignment triples for Bamidbar chapter 2."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי' והרון קאילא",
         "Then God spoke to Moses and Aaron, saying:"),
    ],
    2: [
        ("אִישׁ עַל-דִּגְלוֹ בְאֹתֹת לְבֵית אֲבֹתָם יַחֲנוּ בְּנֵי יִשְׂרָאֵל",
         "כל סבט פי מרכזה בעלאמאת לביות אבאיהם. ינזל בני אסראיל",
         "Each tribe in its station, with signs for their fathers' houses — the sons of Israel shall encamp"),
        ("מִנֶּגֶד סָבִיב לְאֹהֶל-מוֹעֵד יַחֲנוּ",
         "חד'א כ'בא אלמחצ'ר וחאלי'ה ינזלון",
         "facing the tent of the Presence, and around it they shall encamp"),
    ],
    3: [
        ("וְהַחֹנִים קֵדְמָה מִזְרָחָה",
         "ואלנאזלין פי אלמשרק",
         "And those encamping in the east"),
        ("דֶּגֶל מַחֲנֵה יְהוּדָה לְצִבְאֹתָם",
         "מרכז עסכר יהודה לגיושהם",
         "the station of the camp of Judah, by their hosts"),
        ("וְנָשִׂיא לִבְנֵי יְהוּדָה נַחְשׁוֹן בֶּן-עַמִּינָדָב",
         "ושריפהם. נחשון אבן עמינדב",
         "and their noble is Nahshon son of Amminadab"),
    ],
    4: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--אַרְבָּעָה וְשִׁבְעִים אֶלֶף וְשֵׁשׁ מֵאוֹת",
         "ועדד גישה. ארבעה וסבעין אלפא וסת מאיה",
         "And the count of his host: seventy-four thousand six hundred"),
    ],
    5: [
        ("וְהַחֹנִים עָלָיו מַטֵּה יִשָּׂשכָר",
         "ואלנאזלין אלי' גאנבה סבט יששכר",
         "And those encamping beside him: the tribe of Issachar"),
        ("וְנָשִׂיא לִבְנֵי יִשָּׂשכָר נְתַנְאֵל בֶּן-צוּעָר",
         "ושריפהם. נתנאל אבן צוער",
         "and their noble is Nethanel son of Zuar"),
    ],
    6: [
        ("וּצְבָאוֹ וּפְקֻדָיו--אַרְבָּעָה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ועדד גישה. ארבעה וכ'מסין אלפא וארבע מאיה",
         "And the count of his host: fifty-four thousand four hundred"),
    ],
    7: [
        ("מַטֵּה זְבוּלֻן",
         "אלי' גאנבה סבט זבולון",
         "Beside him: the tribe of Zebulun"),
        ("וְנָשִׂיא לִבְנֵי זְבוּלֻן אֱלִיאָב בֶּן-חֵלֹן",
         "ושריפהם אליאב אבן חלן",
         "and their noble is Eliab son of Helon"),
    ],
    8: [
        ("וּצְבָאוֹ וּפְקֻדָיו--שִׁבְעָה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ועדד גישה. סבעה וכ'מסין אלפא וארבע מאיה",
         "And the count of his host: fifty-seven thousand four hundred"),
    ],
    9: [
        ("כָּל-הַפְּקֻדִים לְמַחֲנֵה יְהוּדָה",
         "פד'אלך גמיע עדד עסכר יהודה",
         "That, then, is the whole count of the camp of Judah"),
        ("מְאַת אֶלֶף וּשְׁמֹנִים אֶלֶף וְשֵׁשֶׁת-אֲלָפִים וְאַרְבַּע-מֵאוֹת--לְצִבְאֹתָם",
         "מאיה' אלף. וסתה ות'מאנין אלפא וארבע מאיה לגיושהם",
         "a hundred thousand, and eighty-six thousand and four hundred, by their hosts"),
        ("רִאשֹׁנָה יִסָּעוּ",
         "והם ירחלון אוולא",
         "And they shall set out first"),
    ],
    10: [
        ("דֶּגֶל מַחֲנֵה רְאוּבֵן תֵּימָנָה לְצִבְאֹתָם",
         "מרכז עסכר ראובן. פי אלגנוב לגיושהם",
         "The station of the camp of Reuben, in the south, by their hosts"),
        ("וְנָשִׂיא לִבְנֵי רְאוּבֵן אֱלִיצוּר בֶּן-שְׁדֵיאוּר",
         "ושריפהם. אליצור אבן שדיאור",
         "and their noble is Elizur son of Shedeur"),
    ],
    11: [
        ("וּצְבָאוֹ וּפְקֻדָיו--שִׁשָּׁה וְאַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ועדד גישה. סתה וארבעין אלפא וכ'מס מאיה",
         "And the count of his host: forty-six thousand five hundred"),
    ],
    12: [
        ("וְהַחוֹנִם עָלָיו מַטֵּה שִׁמְעוֹן",
         "ואלנאזלין אלי' גאנבה סבט שמעון",
         "And those encamping beside him: the tribe of Simeon"),
        ("וְנָשִׂיא לִבְנֵי שִׁמְעוֹן שְׁלֻמִיאֵל בֶּן-צוּרִישַׁדָּי",
         "ושריפהם. שלומיאל אבן צורישדי",
         "and their noble is Shelumiel son of Zurishaddai"),
    ],
    13: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--תִּשְׁעָה וַחֲמִשִּׁים אֶלֶף וּשְׁלֹשׁ מֵאוֹת",
         "ועדד גישה. תסעה וכ'מסין אלפא ות'לאת' מאיה",
         "And the count of his host: fifty-nine thousand three hundred"),
    ],
    14: [
        ("וּמַטֵּה גָּד",
         "ואלי' גאנבה סבט גד",
         "And beside him: the tribe of Gad"),
        ("וְנָשִׂיא לִבְנֵי גָד אֶלְיָסָף בֶּן-רְעוּאֵל",
         "ושריפהם. אליסף אבן רעואל",
         "and their noble is Eliasaph son of Reuel"),
    ],
    15: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--חֲמִשָּׁה וְאַרְבָּעִים אֶלֶף וְשֵׁשׁ מֵאוֹת וַחֲמִשִּׁים",
         "ועדד גישה. כ'מסה וארבעין אלפא. וסת מאיה וכ'מסין",
         "And the count of his host: forty-five thousand six hundred and fifty"),
    ],
    16: [
        ("כָּל-הַפְּקֻדִים לְמַחֲנֵה רְאוּבֵן",
         "פד'אלך גמיע עדד עסכר ראובן",
         "That, then, is the whole count of the camp of Reuben"),
        ("מְאַת אֶלֶף וְאֶחָד וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע-מֵאוֹת וַחֲמִשִּׁים--לְצִבְאֹתָם",
         "מאיה וואחד וכ'מסין לגיושהם",
         "a hundred and fifty-one thousand, and four hundred and fifty, by their hosts"),
        ("וּשְׁנִיִּם יִסָּעוּ",
         "וירחלון ת'אניהם",
         "And they shall set out second"),
    ],
    17: [
        ("וְנָסַע אֹהֶל-מוֹעֵד מַחֲנֵה הַלְוִיִּם בְּתוֹךְ הַמַּחֲנֹת",
         "וירחל כ'בא אלמחצ'ר. עסכר אלליואניין פי וסט אלעסאכר",
         "And the tent of the Presence shall set out — the camp of the Levites in the midst of the camp"),
        ("כַּאֲשֶׁר יַחֲנוּ כֵּן יִסָּעוּ",
         "וכמא הם נאזלין כד'אך ירחלון",
         "and as they encamp, so shall they set out"),
        ("אִישׁ עַל-יָדוֹ לְדִגְלֵיהֶם",
         "כל פריק פי מכאנה ומרכזה",
         "each group in its place and its station"),
    ],
    18: [
        ("דֶּגֶל מַחֲנֵה אֶפְרַיִם לְצִבְאֹתָם יָמָּה",
         "מרכז עסכר אפרים. לגיושהם פי אלמג'רב",
         "The station of the camp of Ephraim, by their hosts, in the west"),
        ("וְנָשִׂיא לִבְנֵי אֶפְרַיִם אֱלִישָׁמָע בֶּן-עַמִּיהוּד",
         "ושריפהם. אלישמע אבן עמיהוד",
         "and their noble is Elishama son of Ammihud"),
    ],
    19: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--אַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ועדד גישה. ארבעין אלפא וכ'מס מאיה",
         "And the count of his host: forty thousand five hundred"),
    ],
    20: [
        ("וְעָלָיו מַטֵּה מְנַשֶּׁה",
         "אלי' גאנבה סבט מנשה",
         "Beside him: the tribe of Manasseh"),
        ("וְנָשִׂיא לִבְנֵי מְנַשֶּׁה גַּמְלִיאֵל בֶּן-פְּדָהצוּר",
         "ושריפהם. גמליאל אבן פדהצור",
         "and their noble is Gamaliel son of Pedahzur"),
    ],
    21: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--שְׁנַיִם וּשְׁלֹשִׁים אֶלֶף וּמָאתָיִם",
         "ועדד גישה. וסתין ותלאת'ין אלפא ומאיתין",
         "And the count of his host: thirty-two thousand two hundred"),
    ],
    22: [
        ("וּמַטֵּה בִּנְיָמִן",
         "ואלי' גאנבה סבט בנימין",
         "And beside him: the tribe of Benjamin"),
        ("וְנָשִׂיא לִבְנֵי בִנְיָמִן אֲבִידָן בֶּן-גִּדְעֹנִי",
         "ושריפהם. אבידן אבן גדעוני",
         "and their noble is Abidan son of Gideoni"),
    ],
    23: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--חֲמִשָּׁה וּשְׁלֹשִׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ועדד גישה. כ'מסה ותלאת'ין אלפא וארבע מאיה",
         "And the count of his host: thirty-five thousand four hundred"),
    ],
    24: [
        ("כָּל-הַפְּקֻדִים לְמַחֲנֵה אֶפְרַיִם",
         "פד'אלך גמיע עדד עסכר אפרים",
         "That, then, is the whole count of the camp of Ephraim"),
        ("מְאַת אֶלֶף וּשְׁמֹנַת-אֲלָפִים וּמֵאָה--לְצִבְאֹתָם",
         "מאיה' אלף ותמאניה' אלאף ומאיה לגיושהם",
         "a hundred thousand and eight thousand and a hundred, by their hosts"),
        ("וּשְׁלִשִׁים יִסָּעוּ",
         "וירחלון ת'אלת'הם",
         "And they shall set out third"),
    ],
    25: [
        ("דֶּגֶל מַחֲנֵה דָן צָפֹנָה לְצִבְאֹתָם",
         "ומרכז עסכר דן. פי אלשמאל לגיושהם",
         "And the station of the camp of Dan, in the north, by their hosts"),
        ("וְנָשִׂיא לִבְנֵי דָן אֲחִיעֶזֶר בֶּן-עַמִּישַׁדָּי",
         "ושריפהם. אחיעזר אבן עמישדי",
         "and their noble is Ahiezer son of Ammishaddai"),
    ],
    26: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--שְׁנַיִם וְשִׁשִּׁים אֶלֶף וּשְׁבַע מֵאוֹת",
         "ועדד גישה את'נין וסתין אלפא וסבע מאיה",
         "And the count of his host: sixty-two thousand seven hundred"),
    ],
    27: [
        ("וְהַחֹנִים עָלָיו מַטֵּה אָשֵׁר",
         "ואלנאזלין אלי' גאנבה סבט אשר",
         "And those encamping beside him: the tribe of Asher"),
        ("וְנָשִׂיא לִבְנֵי אָשֵׁר פַּגְעִיאֵל בֶּן-עָכְרָן",
         "ושריפהם. פגעיאל אבן עכרן",
         "and their noble is Pagiel son of Ochran"),
    ],
    28: [
        ("וּצְבָאוֹ וּפְקֻדֵיהֶם--אֶחָד וְאַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ועדד גישה. ואחד וארבעין אלפא וכ'מס מאיה",
         "And the count of his host: forty-one thousand five hundred"),
    ],
    29: [
        ("וּמַטֵּה נַפְתָּלִי",
         "ואלי' גאנבה סבט נפתלי",
         "And beside him: the tribe of Naphtali"),
        ("וְנָשִׂיא לִבְנֵי נַפְתָּלִי אֲחִירַע בֶּן-עֵינָן",
         "ושריפהם. אחירע אבן עינן",
         "and their noble is Ahira son of Enan"),
    ],
    31: [
        ("כָּל-הַפְּקֻדִים לְמַחֲנֵה דָן",
         "פד'אלך גמיע עדד עסכר דן",
         "That, then, is the whole count of the camp of Dan"),
        ("מְאַת אֶלֶף וְשִׁבְעָה וַחֲמִשִּׁים אֶלֶף וְשֵׁשׁ מֵאוֹת",
         "מאיה וסבעה וכ'מסין אלפא וסת מאיה",
         "a hundred and fifty-seven thousand six hundred"),
        ("לָאַחֲרֹנָה יִסְעוּ לְדִגְלֵיהֶם",
         "וירחלון אכ'רא לגיושהם",
         "And they shall set out last, by their hosts"),
    ],
    32: [
        ("אֵלֶּה פְּקוּדֵי בְנֵי-יִשְׂרָאֵל לְבֵית אֲבֹתָם",
         "הולאי מעדודי בני אסראיל לביות אבאיהם",
         "These are those counted of the sons of Israel, by their fathers' houses"),
        ("כָּל-פְּקוּדֵי הַמַּחֲנֹת לְצִבְאֹתָם",
         "גמלה עדד אלעסכר לגיושהם",
         "the total count of the camp, by their hosts"),
        ("שֵׁשׁ-מֵאוֹת אֶלֶף וּשְׁלֹשֶׁת אֲלָפִים וַחֲמֵשׁ מֵאוֹת וַחֲמִשִּׁים",
         "סת מאיה' אלף ות'לאתה' אלאף. וכ'מס מאיה וכ'מסין",
         "six hundred thousand and three thousand, five hundred and fifty"),
    ],
    33: [
        ("וְהַלְוִיִּם--לֹא הָתְפָּקְדוּ בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "ואמא אלליואניין. לם יחצו פי גמלה בני אסראיל",
         "As for the Levites, they were not counted in the total of the sons of Israel"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "כמא אמר אללה מוסי'",
         "as God had commanded Moses"),
    ],
    34: [
        ("וַיַּעֲשׂוּ בְּנֵי יִשְׂרָאֵל כְּכֹל אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "ת'ם צנע בני אסראיל. כמא אמר אללה מוסי'",
         "And then the sons of Israel did as God had commanded Moses"),
        ("כֵּן-חָנוּ לְדִגְלֵיהֶם וְכֵן נָסָעוּ",
         "כד'אך נזלו פי מראכזהם וכד'אך רחלו",
         "thus they encamped in their stations, and thus they set out"),
        ("אִישׁ לְמִשְׁפְּחֹתָיו עַל-בֵּית אֲבֹתָיו",
         "כל סבט לעשאירה עלי' ביות אבאיהם",
         "each tribe by their clans, according to their fathers' houses"),
    ],
    36: [
        ("ּצְבָאוֹ וּפְקֻדֵיהֶם--שְׁלֹשָׁה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ועדד גישה. ת'לאת'ה וכ'מסין אלפא וארבע מאיה",
         "And the count of his host: fifty-three thousand four hundred"),
    ],
}
