"""Hand-authored alignment triples for Bamidbar chapter 12."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַתְּדַבֵּר מִרְיָם וְאַהֲרֹן בְּמֹשֶׁה", "תכלמת מרים והרון במוסי",
         "Miriam and Aaron spoke against Moses"),
        ("עַל-אֹדוֹת הָאִשָּׁה הַכֻּשִׁית אֲשֶׁר לָקָח", "בסבב אלאמראה אלחסנה אלתי תזווגהא",
         "on account of the fair woman whom he had married"),
        ("כִּי-אִשָּׁה כֻשִׁית לָקָח", "לאנה כאן קד אעתזלהא",
         "for he had kept himself apart from her."),
    ],
    2: [
        ("וַיֹּאמְרוּ הֲרַק אַךְ-בְּמֹשֶׁה דִּבֶּר יְהוָה", "פקאלו. אן כאן מן אגל אלנבווה פתראה וחדה פקט כ'אטבה אללה",
         "And they said: 'If it be on account of prophecy — was it only he alone whom God addressed?"),
        ("הֲלֹא גַּם-בָּנוּ דִבֵּר", "אליס קד כ'אטבנא אללה איצ'א",
         "Has God not addressed us as well?'"),
        ("וַיִּשְׁמַע יְהוָה", "פסמע אללה ד'אלך", "And God heard that."),
    ],
    3: [
        ("וְהָאִישׁ מֹשֶׁה עָנָו מְאֹד", "וכאן מוסי' רגלא כ'אשעא גדא",
         "Now Moses was a man exceedingly humble"),
        ("מִכֹּל הָאָדָם אֲשֶׁר עַל-פְּנֵי הָאֲדָמָה", "אכת'ר מן גמיע אלנאס. אלד'י עלי' וגה אלארץ'",
         "more than all the people who are upon the face of the earth."),
    ],
    4: [
        ("וַיֹּאמֶר יְהוָה פִּתְאֹם אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן וְאֶל-מִרְיָם",
         "פקאל אללה ג'פלה. למוסי והרון ומרים",
         "And God said suddenly to Moses and Aaron and Miriam"),
        ("צְאוּ שְׁלָשְׁתְּכֶם אֶל-אֹהֶל מוֹעֵד", "אכ'רגו ת'לאת'תכם אלי' כ'בא אלמחצ'ר",
         "'Come out, the three of you, to the tent of the assembly.'"),
        ("וַיֵּצְאוּ שְׁלָשְׁתָּם", "פכ'רגו ת'לאת'תהם", "And the three of them came out."),
    ],
    5: [
        ("וַיֵּרֶד יְהוָה בְּעַמּוּד עָנָן", "פתגלא אללה בעמוד ג'מאם",
         "And God appeared in a pillar of cloud"),
        ("וַיַּעֲמֹד פֶּתַח הָאֹהֶל", "וקאם עלי' באב אלכ'בא",
         "and stood at the door of the tent"),
        ("וַיִּקְרָא אַהֲרֹן וּמִרְיָם", "ונאדא יא הרון ויא מרים",
         "and called: 'O Aaron, and O Miriam!'"),
        ("וַיֵּצְאוּ שְׁנֵיהֶם", "פכ'רגא כליהמא", "And the two of them came out."),
    ],
    6: [
        ("וַיֹּאמֶר שִׁמְעוּ-נָא דְבָרָי", "קאל אסמעו כלאמי", "He said: 'Hear my words."),
        ("אִם-יִהְיֶה נְבִיאֲכֶם--יְהוָה בַּמַּרְאָה אֵלָיו אֶתְוַדָּע",
         "אן יכון נבייכמא. אנא אללה תערפת בה פי רויא",
         "If there be a prophet among you — I, God, make Myself known to him in a vision"),
        ("בַּחֲלוֹם אֲדַבֶּר-בּוֹ", "או כ'אטבתה פי חלם",
         "or I speak to him in a dream."),
    ],
    7: [
        ("לֹא-כֵן עַבְדִּי מֹשֶׁה", "ליס כד'אך עבדי מוסי'",
         "Not so My servant Moses"),
        ("בְּכָל-בֵּיתִי נֶאֱמָן הוּא", "בל פי גמיע אמתי מחקק הו",
         "rather, throughout all My nation he is trusted."),
    ],
    8: [
        ("פֶּה אֶל-פֶּה אֲדַבֶּר-בּוֹ וּמַרְאֶה וְלֹא בְחִידֹת",
         "אן שפאהא אכ'אטבה. ורויא ולא באחאדית",
         "Mouth to mouth I address him, and by vision and not in riddles"),
        ("וּתְמֻנַת יְהוָה יַבִּיט", "וצוור אללה אלמכ'לוקה לה יראהא",
         "and the created forms of God appointed for him — he beholds them."),
        ("וּמַדּוּעַ לֹא יְרֵאתֶם לְדַבֵּר בְּעַבְדִּי בְמֹשֶׁה",
         "ומא באלכמא לם תכ'אפא. אן תתכלמא פי עבדי מוסי'",
         "Why then were the two of you not afraid to speak against My servant Moses?'"),
    ],
    9: [
        ("וַיִּחַר-אַף יְהוָה בָּם", "פאשתד ג'צ'ב אללה עליהם",
         "And God's anger intensified against them"),
        ("וַיֵּלַךְ", "וארתפע נורה", "and His light ascended."),
    ],
    10: [
        ("וְהֶעָנָן סָר מֵעַל הָאֹהֶל", "פכמא זאל אלג'מאם ען אלכ'בא",
         "And as the cloud withdrew from the tent"),
        ("וְהִנֵּה מִרְיָם מְצֹרַעַת כַּשָּׁלֶג", "פאדא במרים ביצ'א כאלתלג",
         "behold — Miriam was white as snow."),
        ("וַיִּפֶן אַהֲרֹן אֶל-מִרְיָם וְהִנֵּה מְצֹרָעַת",
         "פלמא אלתפת הרון. אלי' מרים פאד'א בהא ברצא",
         "And when Aaron turned toward Miriam, behold, she was stricken with a skin-affliction."),
    ],
    11: [
        ("וַיֹּאמֶר אַהֲרֹן אֶל-מֹשֶׁה בִּי אֲדֹנִי", "פקאל הרון למוסי'. יא סיידי",
         "And Aaron said to Moses: 'O my lord"),
        ("אַל-נָא תָשֵׁת עָלֵינוּ חַטָּאת", "לא תגעל עלינא כ'טייה",
         "do not lay a sin upon us"),
        ("אֲשֶׁר נוֹאַלְנוּ וַאֲשֶׁר חָטָאנוּ", "פי מא גהלנא ואכ'טינא",
         "for what we did in our ignorance and in our error."),
    ],
    12: [
        ("אַל-נָא תְהִי כַּמֵּת אֲשֶׁר בְּצֵאתוֹ מֵרֶחֶם אִמּוֹ",
         "לא תכון הד'ה כסקט כ'רג מן בטן אמה",
         "Let her not be like a stillborn that comes out from its mother's womb"),
        ("וַיֵּאָכֵל חֲצִי בְשָׂרוֹ", "וקד תהרא נצף גסמה",
         "with half its body already wasted away.'"),
    ],
    13: [
        ("וַיִּצְעַק מֹשֶׁה אֶל-יְהוָה לֵאמֹר", "פדעא מוסי'. אלי' רבה קאילא",
         "And Moses cried out to his Lord, saying"),
        ("אֵל נָא רְפָא נָא לָהּ", "אללהם פאשפהא", "'O God, heal her, I pray!'"),
    ],
    14: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי",
         "And God said to Moses"),
        ("וְאָבִיהָ יָרֹק יָרַק בְּפָנֶיהָ--הֲלֹא תִכָּלֵם שִׁבְעַת יָמִים",
         "לו אן אביהא בצק פי וגההא. אלם יגב אן תסתחי מנה סבעה' אייאם",
         "'Were her father to spit in her face, would she not be obliged to feel shame before him for seven days?"),
        ("תִּסָּגֵר שִׁבְעַת יָמִים מִחוּץ לַמַּחֲנֶה", "פלתקף כד'אך כ'ארג אלעסכר",
         "Let her remain thus outside the camp"),
        ("וְאַחַר תֵּאָסֵף", "ובעד ד'אלך תנצ'ם אליה",
         "and after that she shall rejoin it.'"),
    ],
    15: [
        ("וַתִּסָּגֵר מִרְיָם מִחוּץ לַמַּחֲנֶה שִׁבְעַת יָמִים",
         "פוקפת מרים. כ'ארג אלעסכר סבעה' אייאם",
         "And Miriam remained outside the camp for seven days"),
        ("וְהָעָם לֹא נָסַע עַד-הֵאָסֵף מִרְיָם", "ולם ירחל אלקום. אלי' אנצ'מאמהא",
         "and the people did not set out until she had rejoined."),
    ],
    16: [
        ("וְאַחַר נָסְעוּ הָעָם מֵחֲצֵרוֹת", "ובעד ד'אלך רחלו מן חצרות",
         "And after that they set out from Hazeroth"),
        ("וַיַּחֲנוּ בְּמִדְבַּר פָּארָן", "ונזלו פי ברייה' פארן",
         "and encamped in the wilderness of Paran."),
    ],
}
