"""Hand-authored alignment triples for Bamidbar chapter 35."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְּעַרְבֹת מוֹאָב עַל-יַרְדֵּן יְרֵחוֹ לֵאמֹר",
         "ת'ם כלם אללה מוסי' פי בידאת מואב. עלי' ארדן יריחא תכלימא",
         "Then God spoke to Moses in the wilderness of Moab, by the Jordan of Jericho directly."),
    ],
    2: [
        ("צַו אֶת-בְּנֵי יִשְׂרָאֵל",
         "מר בני אסראיל",
         "Command the sons of Israel"),
        ("וְנָתְנוּ לַלְוִיִּם מִנַּחֲלַת אֲחֻזָּתָם עָרִים לָשָׁבֶת",
         "באן יעטו אלליואניין. מן נחלת חוזהם קרא יסכנוהא",
         "that they give to the Levites, from the inheritance of their possession, towns to dwell in"),
        ("וּמִגְרָשׁ לֶעָרִים סְבִיבֹתֵיהֶם תִּתְּנוּ לַלְוִיִּם",
         "ואפניה להם חואלי'הא",
         "and open spaces for them round about them."),
    ],
    3: [
        ("וְהָיוּ הֶעָרִים לָהֶם לָשָׁבֶת",
         "ותכון אלקרא סכנא להם",
         "And the towns shall be a dwelling for them"),
        ("וּמִגְרְשֵׁיהֶם יִהְיוּ לִבְהֶמְתָּם וְלִרְכֻשָׁם וּלְכֹל חַיָּתָם",
         "ואפניתהא. לבהאימהם וסרחהם וסאיר חיואנהם",
         "and their open spaces shall be for their beasts and their flocks and the rest of their animals."),
    ],
    4: [
        ("וּמִגְרְשֵׁי הֶעָרִים אֲשֶׁר תִּתְּנוּ לַלְוִיִּם",
         "ואפניה' אלקרא. אלתי תעטוהא לאליואניין",
         "And the open spaces of the towns which you give to the Levites"),
        ("מִקִּיר הָעִיר וָחוּצָה אֶלֶף אַמָּה סָבִיב",
         "מן כ'ארג חאיט אלקריה. אלף ד'ראע מסתדירא",
         "shall extend from outside the wall of the town one thousand cubits all around."),
    ],
    5: [
        ("וּמַדֹּתֶם מִחוּץ לָעִיר אֶת-פְּאַת-קֵדְמָה אַלְפַּיִם בָּאַמָּה",
         "ת'ם אמסחו מן כ'ארג אלקריה. אלי' גהה' אלמשרק אלפין ד'ראע",
         "Then measure from outside the town: toward the east two thousand cubits"),
        ("וְאֶת-פְּאַת-נֶגֶב אַלְפַּיִם בָּאַמָּה",
         "ואלי' גהה' אלגנוב אלפין ד'ראע",
         "and toward the south two thousand cubits"),
        ("וְאֶת-פְּאַת-יָם אַלְפַּיִם בָּאַמָּה",
         "ואלי' גהה' אלג'רב אלפין ד'ראע",
         "and toward the west two thousand cubits"),
        ("וְאֵת פְּאַת צָפוֹן אַלְפַּיִם בָּאַמָּה--וְהָעִיר בַּתָּוֶךְ",
         "ואלי' גהה' אלשמאל. אלפין ד'ראע ואלקריה פי וסטהא",
         "and toward the north two thousand cubits — with the town in the midst of them."),
        ("זֶה יִהְיֶה לָהֶם מִגְרְשֵׁי הֶעָרִים",
         "פד'אלך יכון לכם. מקדאר אפניה' אלקרא",
         "That shall be for you the measure of the open spaces of the towns."),
    ],
    6: [
        ("וְאֵת הֶעָרִים אֲשֶׁר תִּתְּנוּ לַלְוִיִּם",
         "ואלקרא אלד'י תעטוהא לאליואניין",
         "And the towns which you give to the Levites"),
        ("אֵת שֵׁשׁ-עָרֵי הַמִּקְלָט אֲשֶׁר תִּתְּנוּ לָנֻס שָׁמָּה הָרֹצֵחַ",
         "מנהא סת קרא אלחמא. אלד'י תעזלוהא. ליהרב אלי'הא אלקאתל",
         "among them shall be the six towns of refuge which you set apart, so that the killer may flee to them"),
        ("וַעֲלֵיהֶם תִּתְּנוּ אַרְבָּעִים וּשְׁתַּיִם עִיר",
         "ואצ'יפו אלי'הא. את'נין וארבעין קריה",
         "and add to them forty-two towns."),
    ],
    7: [
        ("כָּל-הֶעָרִים אֲשֶׁר תִּתְּנוּ לַלְוִיִּם--אַרְבָּעִים וּשְׁמֹנֶה עִיר אֶתְהֶן וְאֶת-מִגְרְשֵׁיהֶן",
         "פתציר גמיע אלקרא. אלד'י תעטוהם. תמאניה וארבעין קריה ואפניתהא",
         "So all the towns which you give shall be forty-eight towns, with their open spaces."),
    ],
    8: [
        ("וְהֶעָרִים אֲשֶׁר תִּתְּנוּ מֵאֲחֻזַּת בְּנֵי-יִשְׂרָאֵל",
         "ואלקרא. אלד'י תעטונהם מן חוז בני אסראיל",
         "And the towns which you give from the possession of the sons of Israel"),
        ("מֵאֵת הָרַב תַּרְבּוּ וּמֵאֵת הַמְעַט תַּמְעִיטוּ",
         "ממן אכ'ד' כת'ירא כת'רו. ומן מן אכ'ד' קלילא קללו",
         "from him who took much, give more; and from him who took little, give less"),
        ("אִישׁ כְּפִי נַחֲלָתוֹ אֲשֶׁר יִנְחָלוּ יִתֵּן מֵעָרָיו לַלְוִיִּם",
         "פליעט כל סבט עלי' קדר נחלתה",
         "each tribe shall give according to the measure of its inheritance."),
    ],
    9: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    10: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל. וקל להם",
         "Command the sons of Israel, and say to them:"),
        ("כִּי אַתֶּם עֹבְרִים אֶת-הַיַּרְדֵּן אַרְצָה כְּנָעַן",
         "אד'א אנתם. גזתם אלארדן אלי' בלד כנעאן",
         "When you have crossed the Jordan into the land of Canaan,"),
    ],
    11: [
        ("וְהִקְרִיתֶם לָכֶם עָרִים עָרֵי מִקְלָט תִּהְיֶינָה לָכֶם",
         "פאסמו לכם קרא חמא. יהרב אלי'ה",
         "then designate for yourselves towns of refuge"),
        ("וְנָס שָׁמָּה רֹצֵחַ מַכֵּה-נֶפֶשׁ בִּשְׁגָגָה",
         "אי קאתל. קתל נפסא סהוא",
         "so that any killer who has slain a person unintentionally may flee to them."),
    ],
    12: [
        ("וְהָיוּ לָכֶם הֶעָרִים לְמִקְלָט מִגֹּאֵל",
         "פתכון תלך אלקרא. תחמיה מן אלולי",
         "And those towns shall be a protection from the blood-avenger"),
        ("וְלֹא יָמוּת הָרֹצֵחַ עַד-עָמְדוֹ לִפְנֵי הָעֵדָה לַמִּשְׁפָּט",
         "ולא יקתל. חתי' יקף. בין ידי אלגמאעה פיחכמון עליה בד'אלך",
         "and he shall not be killed until he has stood before the assembly, that they may judge him in this matter."),
    ],
    13: [
        ("וְהֶעָרִים אֲשֶׁר תִּתֵּנוּ--שֵׁשׁ-עָרֵי מִקְלָט תִּהְיֶינָה לָכֶם",
         "ואלקרא אלתי תעזלונהא. סת קרא חמא תכון לכם",
         "And the towns which you set apart — six towns of refuge shall they be for you."),
    ],
    14: [
        ("אֵת שְׁלֹשׁ הֶעָרִים תִּתְּנוּ מֵעֵבֶר לַיַּרְדֵּן",
         "ת'לאת' מנהא פי עבר אלארדן",
         "Three of them shall be across the Jordan"),
        ("וְאֵת שְׁלֹשׁ הֶעָרִים תִּתְּנוּ בְּאֶרֶץ כְּנָעַן עָרֵי מִקְלָט תִּהְיֶינָה",
         "ות'לאת' מנהא פי בלד כנעאן. תכון קרא חמא",
         "and three of them shall be in the land of Canaan — they shall be towns of refuge."),
    ],
    15: [
        ("לִבְנֵי יִשְׂרָאֵל וְלַגֵּר וְלַתּוֹשָׁב בְּתוֹכָם",
         "לבני אסראיל. ולאלג'ריב אלדכ'יל פי מא בינהם",
         "For the sons of Israel and for the stranger and for the guest who has entered among them"),
        ("תִּהְיֶינָה שֵׁשׁ-הֶעָרִים הָאֵלֶּה לְמִקְלָט--לָנוּס שָׁמָּה כָּל-מַכֵּה-נֶפֶשׁ בִּשְׁגָגָה",
         "יהרב אלי'הא. כל מן קתל נפסא סהוא",
         "every one who has slain a person unintentionally may flee to them."),
    ],
    16: [
        ("וְאִם-בִּכְלִי בַרְזֶל הִכָּהוּ וַיָּמֹת",
         "ואמא אן כאן צ'רבה. באנא חדיד פקתלה",
         "But if he struck him with an iron implement and killed him"),
        ("רֹצֵחַ הוּא מוֹת יוּמַת הָרֹצֵחַ",
         "פהו קאתל יסתחק אלקתל",
         "he is a killer who deserves to be put to death."),
    ],
    17: [
        ("וְאִם בְּאֶבֶן יָד אֲשֶׁר-יָמוּת בָּהּ הִכָּהוּ וַיָּמֹת",
         "או צ'רבה בחגר. מקבוץ' מקדאר מא ימות בהא פקתלה",
         "Or if he struck him with a stone held in the hand, of a size sufficient to cause death, and killed him"),
        ("רֹצֵחַ הוּא מוֹת יוּמַת הָרֹצֵחַ",
         "פהו קאתל יסתחק אלקתל",
         "he is a killer who deserves to be put to death."),
    ],
    18: [
        ("אוֹ בִּכְלִי עֵץ-יָד אֲשֶׁר-יָמוּת בּוֹ הִכָּהוּ וַיָּמֹת",
         "או צ'רבה באנא כ'שב. מקבוץ' מקדאר מא ימות בה פקתלה",
         "Or if he struck him with a wooden implement held in the hand, of a size sufficient to cause death, and killed him"),
        ("רֹצֵחַ הוּא מוֹת יוּמַת הָרֹצֵחַ",
         "פהו קאתל יסתחק אלקתל",
         "he is a killer who deserves to be put to death."),
    ],
    19: [
        ("גֹּאֵל הַדָּם הוּא יָמִית אֶת-הָרֹצֵחַ בְּפִגְעוֹ-בוֹ הוּא יְמִתֶנּוּ",
         "ולי אלדם הו יקתלה אד'א פאגאה בחק",
         "The blood-avenger — he shall put him to death when he encounters him, rightfully."),
    ],
    20: [
        ("וְאִם-בְּשִׂנְאָה יֶהְדֳּפֶנּוּ אוֹ-הִשְׁלִיךְ עָלָיו בִּצְדִיָּה וַיָּמֹת",
         "ואן דפעה בשנאה. או טרח עלי'ה שייא. בתעמד פקתלה",
         "And if he shoved him out of hatred, or hurled something at him deliberately, and killed him,"),
    ],
    21: [
        ("אוֹ בְאֵיבָה הִכָּהוּ בְיָדוֹ וַיָּמֹת--מוֹת-יוּמַת הַמַּכֶּה רֹצֵחַ הוּא",
         "או צ'רבה בידה בעדאוה פקתלה. פליקתל אלצ'ארב קתלא לאנה קאתל",
         "or struck him with his hand out of enmity and killed him — then the striker shall surely be put to death, for he is a killer"),
        ("גֹּאֵל הַדָּם יָמִית אֶת-הָרֹצֵחַ--בְּפִגְעוֹ-בוֹ",
         "פולי אלדם יקתלה אד'א פאגאה בחק",
         "the blood-avenger shall put him to death when he encounters him, rightfully."),
    ],
    22: [
        ("וְאִם-בְּפֶתַע בְּלֹא-אֵיבָה הֲדָפוֹ אוֹ-הִשְׁלִיךְ עָלָיו כָּל-כְּלִי בְּלֹא צְדִיָּה",
         "ואן דפעה בג'תה בלא בג'צ'ה. או טרח עלי'ה. אייה' אניה בלא תעמד",
         "But if he pushed him suddenly without hatred, or threw any implement at him without intent,"),
    ],
    23: [
        ("אוֹ בְכָל-אֶבֶן אֲשֶׁר-יָמוּת בָּהּ בְּלֹא רְאוֹת וַיַּפֵּל עָלָיו וַיָּמֹת",
         "או אוקע עלי'ה. אי חגר כאן בלא תעמד פמאת",
         "or dropped upon him any stone — without intent — and he died"),
        ("וְהוּא לֹא-אוֹיֵב לוֹ וְלֹא מְבַקֵּשׁ רָעָתוֹ",
         "והו פי ד'אלך ליס בעדו לה. ולא טאלב שרה",
         "and he was not his enemy and was not seeking his harm,"),
    ],
    24: [
        ("וְשָׁפְטוּ הָעֵדָה בֵּין הַמַּכֶּה וּבֵין גֹּאֵל הַדָּם--עַל הַמִּשְׁפָּטִים הָאֵלֶּה",
         "פלתחכם אלגמאעה. בין אלקאתל ובין אלולי. בהד'א אלאחכאם",
         "then the assembly shall judge between the killer and the blood-avenger, according to these ordinances."),
    ],
    25: [
        ("וְהִצִּילוּ הָעֵדָה אֶת-הָרֹצֵחַ מִיַּד גֹּאֵל הַדָּם",
         "ותכ'לץ. אלגמאעה הד'א אלקאתל. מן יד אלולי",
         "And the assembly shall deliver this killer from the hand of the blood-avenger"),
        ("וְהֵשִׁיבוּ אֹתוֹ הָעֵדָה אֶל-עִיר מִקְלָטוֹ אֲשֶׁר-נָס שָׁמָּה וְיָשַׁב בָּהּ",
         "ותרדה אלי' קריה' חמאה אלתי הרב אלי'הא ויקים ת'ם",
         "and shall return him to the town of refuge to which he fled; and he shall remain there"),
        ("עַד-מוֹת הַכֹּהֵן הַגָּדֹל אֲשֶׁר-מָשַׁח אֹתוֹ בְּשֶׁמֶן הַקֹּדֶשׁ",
         "אלי' מות אלאמאם אלכביר. אלד'י מסח בדהן אלקדס",
         "until the death of the great imām who was anointed with the oil of holiness."),
    ],
    26: [
        ("וְאִם-יָצֹא יֵצֵא הָרֹצֵחַ אֶת-גְּבוּל עִיר מִקְלָטוֹ אֲשֶׁר יָנוּס שָׁמָּה",
         "פאן הו כ'רג ען חד קריה חמאה. אלתי הרב אלי'הא",
         "But if he goes out beyond the boundary of the town of refuge to which he fled,"),
    ],
    27: [
        ("וּמָצָא אֹתוֹ גֹּאֵל הַדָּם מִחוּץ לִגְבוּל עִיר מִקְלָטוֹ",
         "פוגדה אלולי. כ'ארג ען חד קריה' חמאה",
         "and the blood-avenger finds him outside the boundary of the town of refuge"),
        ("וְרָצַח גֹּאֵל הַדָּם אֶת-הָרֹצֵחַ--אֵין לוֹ דָּם",
         "פקתלה. פלא ת'יאר לה",
         "and kills him — there is no vengeance for him."),
    ],
    28: [
        ("כִּי בְעִיר מִקְלָטוֹ יֵשֵׁב עַד-מוֹת הַכֹּהֵן הַגָּדֹל",
         "בל יגלס פי קריה' חמאה. אלי' מות אלאמאם אלכביר",
         "Rather, he must stay in the town of refuge until the death of the great imām"),
        ("וְאַחֲרֵי מוֹת הַכֹּהֵן הַגָּדֹל--יָשׁוּב הָרֹצֵחַ אֶל-אֶרֶץ אֲחֻזָּתוֹ",
         "ובעד מותה. ירגע אלי' ארץ' חוזה",
         "and after his death he may return to the land of his possession."),
    ],
    29: [
        ("וְהָיוּ אֵלֶּה לָכֶם לְחֻקַּת מִשְׁפָּט לְדֹרֹתֵיכֶם בְּכֹל מוֹשְׁבֹתֵיכֶם",
         "פתכון הד'ה לכם חכם עלי' מר אגיאלכם פי גמיע מסאכנכם",
         "And these shall be ordinances for you throughout the passing of your generations, in all your dwellings."),
    ],
    30: [
        ("כָּל-מַכֵּה-נֶפֶשׁ--לְפִי עֵדִים יִרְצַח אֶת-הָרֹצֵחַ",
         "כל מן קתל נפסא עאמדא. פבקול שאהדין אקתלוה",
         "Every one who has slain a person intentionally — by the word of two witnesses put him to death"),
        ("וְעֵד אֶחָד לֹא-יַעֲנֶה בְנֶפֶשׁ לָמוּת",
         "ואמא שאהד ואחד. פלא ישהד עלי'ה פיקתל",
         "but a single witness shall not testify against him so that he be put to death."),
    ],
    31: [
        ("וְלֹא-תִקְחוּ כֹפֶר לְנֶפֶשׁ רֹצֵחַ אֲשֶׁר-הוּא רָשָׁע לָמוּת",
         "ולא תאכדו דיה ען נפס קאתל. יגב עלי'ה אלקתל",
         "And you shall not accept blood-money as ransom for the life of a killer who is liable to be put to death"),
        ("כִּי-מוֹת יוּמָת",
         "אלא יקתל קתלא",
         "he shall surely be put to death."),
    ],
    32: [
        ("וְלֹא-תִקְחוּ כֹפֶר לָנוּס אֶל-עִיר מִקְלָטוֹ",
         "ולא תאכדו מנה איצ'א דיה. לתהרבוה אלי' בעץ' קרא אלחמא",
         "Nor shall you accept from him blood-money to allow him to flee to one of the towns of refuge"),
        ("לָשׁוּב לָשֶׁבֶת בָּאָרֶץ עַד-מוֹת הַכֹּהֵן",
         "ליעוד ויסכן אלבלד. בעד מות אלאמאם",
         "so that he may return and dwell in the land after the death of the imām."),
    ],
    33: [
        ("וְלֹא-תַחֲנִיפוּ אֶת-הָאָרֶץ אֲשֶׁר אַתֶּם בָּהּ",
         "ולא תדנסו אלבלד. אלד'י אנתם פיה",
         "And you shall not defile the land in which you are"),
        ("כִּי הַדָּם הוּא יַחֲנִיף אֶת-הָאָרֶץ",
         "לאן אלדם ידנסה",
         "for blood defiles it"),
        ("וְלָאָרֶץ לֹא-יְכֻפַּר לַדָּם אֲשֶׁר שֻׁפַּךְ-בָּהּ כִּי-אִם בְּדַם שֹׁפְכוֹ",
         "ולא יג'פר לכם. ען אלדם אלד'י ספך פיה. אלא בדם סאפכה",
         "and atonement cannot be made for you concerning the blood that was shed in it, except by the blood of him who shed it."),
    ],
    34: [
        ("וְלֹא תְטַמֵּא אֶת-הָאָרֶץ אֲשֶׁר אַתֶּם יֹשְׁבִים בָּהּ",
         "ולא תנגסו אלבלד. אלד'י אנתם מקימין פיה",
         "And you shall not make impure the land in which you are dwelling"),
        ("אֲשֶׁר אֲנִי שֹׁכֵן בְּתוֹכָהּ",
         "אלד'י נורי סאכן פיה",
         "in which My light dwells"),
        ("כִּי אֲנִי יְהוָה--שֹׁכֵן בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "פאני אללה. נורי סאכן. פי מא בין בני אסראיל",
         "for I am God, My light dwelling in the midst of the sons of Israel."),
    ],
}
