"""Hand-authored alignment triples for Bamidbar chapter 4."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי' והרון תכלימא",
         "Then God spoke to Moses and Aaron directly"),
    ],
    2: [
        ("נָשֹׂא אֶת-רֹאשׁ בְּנֵי קְהָת מִתּוֹךְ בְּנֵי לֵוִי",
         "ארפעא גמלה' בני קהת. מן בין בני לוי",
         "Raise up the sum of the sons of Kohath from among the sons of Levi"),
        ("לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "לעשאירהם וביות אבאיהם",
         "by their clans and their fathers' houses"),
    ],
    3: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' אבן כ'מסין סנה",
         "From thirty years of age and upward, up to fifty years of age"),
        ("כָּל-בָּא לַצָּבָא לַעֲשׂוֹת מְלָאכָה בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. ליעמל צנאעה פי כ'בא אלמחצ'ר",
         "every one who enters the host, to perform a craft in the tent of the assembly"),
    ],
    4: [
        ("זֹאת עֲבֹדַת בְּנֵי-קְהָת בְּאֹהֶל מוֹעֵד",
         "הד'ה כ'דמה' בני קהת פי כ'בא אלמחצ'ר",
         "This is the service of the sons of Kohath in the tent of the assembly"),
        ("קֹדֶשׁ הַקֳּדָשִׁים",
         "כ'אץ אלאקדאס",
         "the choicest of the holy things"),
    ],
    5: [
        ("וּבָא אַהֲרֹן וּבָנָיו בִּנְסֹעַ הַמַּחֲנֶה",
         "ויד'כל הרון ובניה ענד רחיל אלעסכר",
         "And Aaron and his sons shall come in at the setting out of the camp"),
        ("וְהוֹרִדוּ אֵת פָּרֹכֶת הַמָּסָךְ",
         "ויהיו אלסגף אלמסתור",
         "and they shall take down the concealing veil"),
        ("וְכִסּוּ-בָהּ--אֵת אֲרֹן הָעֵדֻת",
         "ויג'טו בה צנדוק אלשהאדה",
         "and cover with it the ark of the testimony"),
    ],
    6: [
        ("וְנָתְנוּ עָלָיו כְּסוּי עוֹר תַּחַשׁ",
         "ויגעלו עליה. ג'שא גלוד דארש",
         "And they shall place upon it a covering of darash-hides"),
        ("וּפָרְשׂוּ בֶגֶד-כְּלִיל תְּכֵלֶת מִלְמָעְלָה",
         "ויבסטו ת'וב גמלתה אסמאנגון פוקה",
         "and spread a cloth wholly of blue over it"),
        ("וְשָׂמוּ בַּדָּיו",
         "ויצלחו אקואבה",
         "and fit its poles"),
    ],
    7: [
        ("וְעַל שֻׁלְחַן הַפָּנִים יִפְרְשׂוּ בֶּגֶד תְּכֵלֶת",
         "ועלי' מאידה' אלמווגה. יבסטו ת'וב אסמאנגון",
         "And upon the table of the Presence they shall spread a cloth of blue"),
        ("וְנָתְנוּ עָלָיו אֶת-הַקְּעָרֹת וְאֶת-הַכַּפֹּת וְאֶת-הַמְּנַקִּיֹּת וְאֵת קְשׂוֹת הַנָּסֶךְ",
         "ויגעלו עליה. אלקצאע ואלדרוג ואלמלאעק ואלמדאהן ואלמזאג",
         "and place upon it the dishes and the drawers and the spoons and the flagons for the libation"),
        ("וְלֶחֶם הַתָּמִיד עָלָיו יִהְיֶה",
         "ואלכ'בז אלדאים יכון עליה",
         "and the perpetual bread shall be upon it"),
    ],
    8: [
        ("וּפָרְשׂוּ עֲלֵיהֶם בֶּגֶד תּוֹלַעַת שָׁנִי",
         "ויבס'טו עליהא. ת'וב צבג קרמז",
         "And they shall spread over them a cloth dyed scarlet"),
        ("וְכִסּוּ אֹתוֹ בְּמִכְסֵה עוֹר תָּחַשׁ",
         "ויג'טוהא בג'טא ג'לוד דארש",
         "and cover it with a covering of darash-hides"),
        ("וְשָׂמוּ אֶת-בַּדָּיו",
         "ויצלחו אקואבה",
         "and fit its poles"),
    ],
    9: [
        ("וְלָקְחוּ בֶּגֶד תְּכֵלֶת וְכִסּוּ אֶת-מְנֹרַת הַמָּאוֹר",
         "ויאכדו ת'וב אסמאנגון. ויג'טו בה מנארה' אלאצ'אה",
         "And they shall take a cloth of blue, and cover with it the lampstand of light"),
        ("וְאֶת-נֵרֹתֶיהָ וְאֶת-מַלְקָחֶיהָ וְאֶת-מַחְתֹּתֶיהָ",
         "וסרגהא. וכלבאתהא ומגאמרהא",
         "and its lamps, and its tongs and its fire-pans"),
        ("וְאֵת כָּל-כְּלֵי שַׁמְנָהּ אֲשֶׁר יְשָׁרְתוּ-לָהּ בָּהֶם",
         "וגמיע אניה' דהנהא. אלד'י יכ'דמונהא בהא",
         "and all the vessels of its oil with which they tend it"),
    ],
    10: [
        ("וְנָתְנוּ אֹתָהּ וְאֶת-כָּל-כֵּלֶיהָ אֶל-מִכְסֵה עוֹר תָּחַשׁ",
         "ויגעלונהא וגמיע אניתהא. פי ג'שא גלוד דארש",
         "And they shall place it and all its vessels within a covering of darash-hides"),
        ("וְנָתְנוּ עַל-הַמּוֹט",
         "ויצ'עו ד'אלך עלי' אלדהק",
         "and set that upon the carrying-pole"),
    ],
    11: [
        ("וְעַל מִזְבַּח הַזָּהָב יִפְרְשׂוּ בֶּגֶד תְּכֵלֶת",
         "ועלי מד'בח אלדהב. יבס'טו ת'וב אסמאנגון",
         "And upon the golden altar they shall spread a cloth of blue"),
        ("וְכִסּוּ אֹתוֹ בְּמִכְסֵה עוֹר תָּחַשׁ",
         "ויג'טוה בג'טא גלוד דארש",
         "and cover it with a covering of darash-hides"),
        ("וְשָׂמוּ אֶת-בַּדָּיו",
         "ויצלחו אקואבה",
         "and fit its poles"),
    ],
    12: [
        ("וְלָקְחוּ אֶת-כָּל-כְּלֵי הַשָּׁרֵת אֲשֶׁר יְשָׁרְתוּ-בָם בַּקֹּדֶשׁ",
         "ויאכ'דון. גמיע אניה' אלכ'דמה אלד'י יכ'דמון בהא פי אלק'דס",
         "And they shall take all the vessels of service with which they serve in the sanctuary"),
        ("וְנָתְנוּ אֶל-בֶּגֶד תְּכֵלֶת",
         "פיגעלונהא פי ת'וב אסמאנגון",
         "and place them in a cloth of blue"),
        ("וְכִסּוּ אוֹתָם בְּמִכְסֵה עוֹר תָּחַשׁ וְנָתְנוּ עַל-הַמּוֹט",
         "ויג'טוהא בג'טא גלוד דארש. ויצ'עוה פי אלדהק",
         "and cover them with a covering of darash-hides, and set them upon the carrying-pole"),
    ],
    13: [
        ("וְדִשְּׁנוּ אֶת-הַמִּזְבֵּחַ",
         "וירמדו אלמד'בח",
         "And they shall clear the ashes from the altar"),
        ("וּפָרְשׂוּ עָלָיו בֶּגֶד אַרְגָּמָן",
         "ויבסטו עליה. ת'וב ארגואן",
         "and spread upon it a cloth of purple"),
    ],
    14: [
        ("וְנָתְנוּ עָלָיו אֶת-כָּל-כֵּלָיו אֲשֶׁר יְשָׁרְתוּ עָלָיו בָּהֶם",
         "ויגעלון עליה גמיע אניתה אלד'י יכ'דמון בהא עליה",
         "And they shall place upon it all its vessels with which they serve upon it"),
        ("אֶת-הַמַּחְתֹּת אֶת-הַמִּזְלָגֹת וְאֶת-הַיָּעִים וְאֶת-הַמִּזְרָקֹת",
         "אלמגאמר ואלמנאשל ואלמג'ארף ואלכ'ראנב",
         "the fire-pans and the flesh-hooks and the shovels and the basins"),
        ("וּפָרְשׂוּ עָלָיו כְּסוּי עוֹר תַּחַשׁ--וְשָׂמוּ בַדָּיו",
         "ויבסטו עליה ג'טא גלוד דארש. ויצלחו דהוקה",
         "and they shall spread over it a covering of darash-hides, and fit its carrying-poles"),
    ],
    15: [
        ("וְכִלָּה אַהֲרֹן-וּבָנָיו לְכַסֹּת אֶת-הַקֹּדֶשׁ וְאֶת-כָּל-כְּלֵי הַקֹּדֶשׁ בִּנְסֹעַ הַמַּחֲנֶה",
         "פאד'א פ'רג' הרון ובניה. מן תג'טיה' אלקדס. וגמיע אניתה ענד רחיל אלעסכר",
         "And when Aaron and his sons have finished covering the sanctuary and all its vessels at the setting out of the camp"),
        ("וְאַחֲרֵי-כֵן יָבֹאוּ בְנֵי-קְהָת לָשֵׂאת",
         "פבעד ד'אלך ידכ'ל בני קהת פיחמלונהא",
         "then after that those of them who are counted — the sons of Kohath — shall come in and carry them"),
        ("וְלֹא-יִגְּעוּ אֶל-הַקֹּדֶשׁ וָמֵתוּ",
         "ולא ידנו מן אלקדס פיהלכון",
         "but they shall not approach the holy things, lest they be destroyed"),
    ],
    16: [
        ("וּפְקֻדַּת אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "ווכאלה' אלעזר אבן הרון אלאמאם",
         "And the charge of Eleazar son of Aaron the priest"),
        ("שֶׁמֶן הַמָּאוֹר וּקְטֹרֶת הַסַּמִּים וּמִנְחַת הַתָּמִיד וְשֶׁמֶן הַמִּשְׁחָה",
         "דהן אלאצ'אה ובכור אלצמוג'. ואלבר אלדאים ודהן אלמסח",
         "is the oil of the light, and the incense of resins, and the perpetual grain-offering and the oil of anointing"),
        ("פְּקֻדַּת כָּל-הַמִּשְׁכָּן וְכָל-אֲשֶׁר-בּוֹ",
         "פד'אלך וכאלה' אלמסכן וגמיע מא פיה",
         "that is the charge of the tabernacle and all that is in it"),
    ],
    17: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה. מוסי' והרון תכלימא",
         "Then God spoke to Moses and Aaron directly"),
    ],
    18: [
        ("אַל-תַּכְרִיתוּ אֶת-שֵׁבֶט מִשְׁפְּחֹת הַקְּהָתִי מִתּוֹךְ הַלְוִיִּם",
         "לא תקטעו עשאיר סבט קהת. מן בין אלליואניין",
         "Do not cut off the clans of the tribe of Kohath from among the Levites"),
    ],
    19: [
        ("וְזֹאת עֲשׂוּ לָהֶם וְחָיוּ וְלֹא יָמֻתוּ",
         "בל אצנעו להם הד'א אלכ'לה. חתא יחיון ולא יהלכון",
         "But do this for them as a remedy, so that they may live and not be destroyed"),
        ("בְּגִשְׁתָּם אֶת-קֹדֶשׁ הַקֳּדָשִׁים",
         "בדנווהם אלי' כ'אץ אלאקדאס",
         "by their approaching the choicest of the holy things"),
        ("אַהֲרֹן וּבָנָיו יָבֹאוּ וְשָׂמוּ אוֹתָם אִישׁ אִישׁ עַל-עֲבֹדָתוֹ וְאֶל-מַשָּׂאוֹ",
         "ידכלון הרון ובניה. ויולונהם. כל פריק עלי כ'דמתה וחמלה",
         "Aaron and his sons shall come in and assign them, each group to its service and its burden"),
    ],
    20: [
        ("וְלֹא-יָבֹאוּ לִרְאוֹת כְּבַלַּע אֶת-הַקֹּדֶשׁ וָמֵתוּ",
         "ולא ידכ'לון פינצ'רון. ענד תג'טיה' אלקדס ולא יהלכון",
         "And they shall not come in and look at the time of the covering of the holy things, lest they be destroyed"),
    ],
    21: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly"),
    ],
    22: [
        ("נָשֹׂא אֶת-רֹאשׁ בְּנֵי גֵרְשׁוֹן--גַּם-הֵם לְבֵית אֲבֹתָם לְמִשְׁפְּחֹתָם",
         "ארפע גמלה' בני גרשון הם איצ'א. לביות אבאיהם לעשאירהם",
         "Raise up the sum of the sons of Gershon — they too — by their fathers' houses and by their clans"),
    ],
    23: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה עַד בֶּן-חֲמִשִּׁים שָׁנָה--תִּפְקֹד אוֹתָם",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' אבן כ'מסין סנה תעדהם",
         "From thirty years of age and upward, up to fifty years of age, you shall count them"),
        ("כָּל-הַבָּא לִצְבֹא צָבָא לַעֲבֹד עֲבֹדָה בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. לכדמה' כ'בא אלמחצ'ר",
         "every one who enters the host for service in the tent of the assembly"),
    ],
    24: [
        ("זֹאת עֲבֹדַת מִשְׁפְּחֹת הַגֵּרְשֻׁנִּי--לַעֲבֹד וּלְמַשָּׂא",
         "והד'ה כ'דמתהם. עמלא וחמלא",
         "And this is their service — labor and burden"),
    ],
    25: [
        ("וְנָשְׂאוּ אֶת-יְרִיעֹת הַמִּשְׁכָּן וְאֶת-אֹהֶל מוֹעֵד",
         "יחמלון שקאק אלמסכן וכ'בא אלמחצ'ר",
         "They shall carry the curtains of the tabernacle and the tent of the assembly"),
        ("מִכְסֵהוּ וּמִכְסֵה הַתַּחַשׁ אֲשֶׁר-עָלָיו מִלְמָעְלָה",
         "וג'שאה. וג'שא אלדארש אלד'י עלי'ה מן פוק",
         "its covering, and the covering of darash-hide that is upon it from above"),
        ("וְאֶת-מָסַךְ--פֶּתַח אֹהֶל מוֹעֵד",
         "וסתר באב כ'בא אלמחצ'ר",
         "and the screen of the entrance of the tent of the assembly"),
    ],
    26: [
        ("וְאֵת קַלְעֵי הֶחָצֵר וְאֶת-מָסַךְ פֶּתַח שַׁעַר הֶחָצֵר",
         "וקלוע אלצראדק וסתר באבה",
         "and the hangings of the enclosure and the screen of its entrance"),
        ("אֲשֶׁר עַל-הַמִּשְׁכָּן וְעַל-הַמִּזְבֵּחַ סָבִיב",
         "אלד'י עלי' אלמסכן ואלמד'בח מסתדירא",
         "which is around the tabernacle and the altar"),
        ("וְאֵת מֵיתְרֵיהֶם וְאֶת-כָּל-כְּלֵי עֲבֹדָתָם וְאֵת כָּל-אֲשֶׁר יֵעָשֶׂה לָהֶם וְעָבָדוּ",
         "ואטנאבהא. וסאיר אניה' כ'דמתהא. וכל מא יצלח להא הם יכ'דמון",
         "and their cords, and the rest of the vessels of its service — and everything that pertains to them, they shall serve"),
    ],
    27: [
        ("עַל-פִּי אַהֲרֹן וּבָנָיו תִּהְיֶה כָּל-עֲבֹדַת בְּנֵי הַגֵּרְשֻׁנִּי",
         "עלי' קול הרון ובניה יכון. גמיע כדמה' בני גרשון",
         "At the word of Aaron and his sons shall be all the service of the sons of Gershon"),
        ("לְכָל-מַשָּׂאָם וּלְכֹל עֲבֹדָתָם",
         "מן חמלהם. וסאיר עמלהם",
         "both their burden and the rest of their labor"),
        ("וּפְקַדְתֶּם עֲלֵהֶם בְּמִשְׁמֶרֶת אֵת כָּל-מַשָּׂאָם",
         "ועדו עלי'הם בחפץ' . גמיע חמלהם",
         "and you shall register upon them in keeping all their burden"),
    ],
    28: [
        ("זֹאת עֲבֹדַת מִשְׁפְּחֹת בְּנֵי הַגֵּרְשֻׁנִּי--בְּאֹהֶל מוֹעֵד",
         "הד'ה כ'דמה' עשאיר בני גרשון פי כ'בא אלמחצ'ר",
         "This is the service of the clans of the sons of Gershon in the tent of the assembly"),
        ("וּמִשְׁמַרְתָּם--בְּיַד אִיתָמָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "וחפצ'הם. עלי' יד איתמר. אבן הרון אלאמאם",
         "and their charge, under the hand of Ithamar son of Aaron the priest"),
    ],
    29: [
        ("בְּנֵי מְרָרִי--לְמִשְׁפְּחֹתָם לְבֵית-אֲבֹתָם תִּפְקֹד אֹתָם",
         "בני מררי. לעשאירהם וביות אבאיהם תעדהם",
         "The sons of Merari, by their clans and their fathers' houses, you shall count them"),
    ],
    30: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה--תִּפְקְדֵם",
         "מן אבן ת'לאת'ין סנה פצאעדא. ואלי' כ'מסין סנה תעדהם",
         "From thirty years of age and upward, up to fifty years of age, you shall count them"),
        ("כָּל-הַבָּא לַצָּבָא לַעֲבֹד אֶת-עֲבֹדַת אֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. לכדמה' כ'בא אלמחצ'ר",
         "every one who enters the host for service in the tent of the assembly"),
    ],
    31: [
        ("וְזֹאת מִשְׁמֶרֶת מַשָּׂאָם לְכָל-עֲבֹדָתָם בְּאֹהֶל מוֹעֵד",
         "והד'א חפץ' חמלהם. וסאיר עמלהם פי כ'בא אלמחצ'ר",
         "And this is the charge of their burden, and the rest of their labor in the tent of the assembly"),
        ("קַרְשֵׁי הַמִּשְׁכָּן וּבְרִיחָיו וְעַמּוּדָיו וַאֲדָנָיו",
         "תכ'אתג אלמסכן. ואמהאגה ועמדה וקואעדה",
         "the planks of the tabernacle, and its bars and its pillars and its bases"),
    ],
    32: [
        ("וְעַמּוּדֵי הֶחָצֵר סָבִיב וְאַדְנֵיהֶם וִיתֵדֹתָם וּמֵיתְרֵיהֶם",
         "ועמד אלצראדק מסתדירא. וקואעדהא ואותאדהא ואטנאבהא",
         "and the pillars of the enclosure all around, and their bases and their pegs and their cords"),
        ("וּבְשֵׁמֹת תִּפְקְדוּ אֶת-כְּלֵי מִשְׁמֶרֶת מַשָּׂאָם",
         "ועדו באסמא. גמיע אניה' חפץ' חמלהא",
         "and you shall register by name all the vessels of the charge of their burden"),
    ],
    33: [
        ("זֹאת עֲבֹדַת מִשְׁפְּחֹת בְּנֵי מְרָרִי לְכָל-עֲבֹדָתָם בְּאֹהֶל מוֹעֵד",
         "הד'ה כדמה' בני מררי. פי כ'בא אלמחצ'ר",
         "This is the service of the sons of Merari in the tent of the assembly"),
        ("בְּיַד אִיתָמָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "עלי' יד איתמר אבן הרון אלאמאם",
         "under the hand of Ithamar son of Aaron the priest"),
    ],
    34: [
        ("וַיִּפְקֹד מֹשֶׁה וְאַהֲרֹן וּנְשִׂיאֵי הָעֵדָה",
         "פעד מוסי' והרון. ואשראף אלגמאעה",
         "And Moses and Aaron and the nobles of the congregation counted"),
        ("אֶת-בְּנֵי הַקְּהָתִי לְמִשְׁפְּחֹתָם וּלְבֵית אֲבֹתָם",
         "בני קהת. לעשאירהם וביות אבאיהם",
         "the sons of Kohath, by their clans and their fathers' houses"),
    ],
    35: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' כ'מסין סנה",
         "from thirty years of age and upward, up to fifty years of age"),
        ("כָּל-הַבָּא לַצָּבָא לַעֲבֹדָה בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. לכדמה' כ'בא אלמחצ'ר",
         "every one who enters the host for service in the tent of the assembly"),
    ],
    36: [
        ("וַיִּהְיוּ פְקֻדֵיהֶם לְמִשְׁפְּחֹתָם--אַלְפַּיִם שְׁבַע מֵאוֹת וַחֲמִשִּׁים",
         "פצאר גמיע עדדהם לעשאירהם. אלפין וסבע מאיה וכ'מסין",
         "And their count by their clans was two thousand seven hundred and fifty"),
    ],
    37: [
        ("אֵלֶּה פְקוּדֵי מִשְׁפְּחֹת הַקְּהָתִי כָּל-הָעֹבֵד בְּאֹהֶל מוֹעֵד",
         "הד'ה אעדאד עשאיר אלקהתי. כל מן יכ'דם פי כ'בא אלמחצ'ר",
         "These are the counts of the clans of the Kohathites — all who serve in the tent of the assembly"),
        ("אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן עַל-פִּי יְהוָה בְּיַד-מֹשֶׁה",
         "אלד'י עד מוסי' והרון. באמר אללה עלי' יד מוסי'",
         "whom Moses and Aaron counted by the command of God, by the hand of Moses"),
    ],
    38: [
        ("וּפְקוּדֵי בְּנֵי גֵרְשׁוֹן לְמִשְׁפְּחוֹתָם וּלְבֵית אֲבֹתָם",
         "ועדד בני גרשון. לעשאירהם וביות אבאיהם",
         "And the count of the sons of Gershon, by their clans and their fathers' houses"),
    ],
    39: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' כ'מסין סנה",
         "from thirty years of age and upward, up to fifty years of age"),
        ("כָּל-הַבָּא לַצָּבָא לַעֲבֹדָה בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. לכדמה' כ'בא אלמחצ'ר",
         "every one who enters the host for service in the tent of the assembly"),
    ],
    40: [
        ("וַיִּהְיוּ פְּקֻדֵיהֶם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם--אַלְפַּיִם וְשֵׁשׁ מֵאוֹת וּשְׁלֹשִׁים",
         "צאר עדדהם. לעשאירהם וביות אבאיהם. אלפין וסת מאיה ות'לאת'ין",
         "Their count by their clans and their fathers' houses was two thousand six hundred and thirty"),
    ],
    41: [
        ("אֵלֶּה פְקוּדֵי מִשְׁפְּחֹת בְּנֵי גֵרְשׁוֹן כָּל-הָעֹבֵד בְּאֹהֶל מוֹעֵד",
         "הולאי מעדודי עשאיר בני גרשון. כל מן יכ'דם פי כ'בא אלמחצ'ר",
         "These are the counted ones of the clans of the sons of Gershon — all who serve in the tent of the assembly"),
        ("אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן עַל-פִּי יְהוָה",
         "אלד'י עד מוסי'. והרון עלי' קול אללה",
         "whom Moses and Aaron counted by the word of God"),
    ],
    42: [
        ("וּפְקוּדֵי מִשְׁפְּחֹת בְּנֵי מְרָרִי לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ועדד עשאיר בני מררי. לעשאירהם וביות אבאיהם",
         "And the count of the clans of the sons of Merari, by their clans and their fathers' houses"),
    ],
    43: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' כ'מסין סנה",
         "from thirty years of age and upward, up to fifty years of age"),
        ("כָּל-הַבָּא לַצָּבָא לַעֲבֹדָה בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל לאלגיש. לכדמה' כ'בא אלמחצ'ר",
         "every one who enters the host for service in the tent of the assembly"),
    ],
    44: [
        ("וַיִּהְיוּ פְקֻדֵיהֶם לְמִשְׁפְּחֹתָם--שְׁלֹשֶׁת אֲלָפִים וּמָאתָיִם",
         "פכאן עדדהם לעשאירהם. ת'לאתה' אלאף ומאיתין",
         "And their count by their clans was three thousand two hundred"),
    ],
    45: [
        ("אֵלֶּה פְקוּדֵי מִשְׁפְּחֹת בְּנֵי מְרָרִי",
         "הולאי מעדודי עשאיר בני מררי",
         "These are the counted ones of the clans of the sons of Merari"),
        ("אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן עַל-פִּי יְהוָה בְּיַד-מֹשֶׁה",
         "אלד'י עד מוסי' והרון. עלי' קול אללה ביד מוסי'",
         "whom Moses and Aaron counted by the command of God, by the hand of Moses"),
    ],
    46: [
        ("כָּל-הַפְּקֻדִים אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן וּנְשִׂיאֵי יִשְׂרָאֵל",
         "וגמיע אלמעדודין. אלד'י עד מוסי' והרון. ואשראף בני אסראיל",
         "All those who were counted, whom Moses and Aaron and the nobles of the sons of Israel counted"),
        ("אֶת-הַלְוִיִּם לְמִשְׁפְּחֹתָם וּלְבֵית אֲבֹתָם",
         "אלליואניין. לעשאירהם וביות אבאיהם",
         "the Levites — by their clans and their fathers' houses"),
    ],
    47: [
        ("מִבֶּן שְׁלֹשִׁים שָׁנָה וָמַעְלָה וְעַד בֶּן-חֲמִשִּׁים שָׁנָה",
         "מן אבן ת'לאת'ין סנה פצאעדא. אלי' כ'מסין סנה",
         "from thirty years of age and upward, up to fifty years of age"),
        ("כָּל-הַבָּא לַעֲבֹד עֲבֹדַת עֲבֹדָה וַעֲבֹדַת מַשָּׂא--בְּאֹהֶל מוֹעֵד",
         "כל מן ידכ'ל. ליכ'דם כדמה' עמל. וחמל פי כ'בא אלמחצ'ר",
         "every one who enters to serve the service of labor and the service of burden in the tent of the assembly"),
    ],
    48: [
        ("וַיִּהְיוּ פְּקֻדֵיהֶם--שְׁמֹנַת אֲלָפִים וַחֲמֵשׁ מֵאוֹת וּשְׁמֹנִים",
         "פכאן עדדהם. ת'מאניה' אלאף. וכ'מס מאיה ות'מאניין",
         "And their count was eight thousand five hundred and eighty"),
    ],
    49: [
        ("עַל-פִּי יְהוָה פָּקַד אוֹתָם בְּיַד-מֹשֶׁה",
         "עלי' קול אללה עדהם מוסי'",
         "By the command of God Moses counted them"),
        ("אִישׁ אִישׁ עַל-עֲבֹדָתוֹ וְעַל-מַשָּׂאוֹ",
         "כל פריק פי עמלה וחמלה",
         "each group in its labor and its burden"),
        ("וּפְקֻדָיו אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "ועדדה. כמא אמר אללה מוסי'",
         "and its number — as God commanded Moses"),
    ],
}
