"""Hand-authored alignment triples for Bamidbar chapter 26."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְהִי אַחֲרֵי הַמַּגֵּפָה", "ולמא כאן בעד אלובא",
         "And it was after the plague"),
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן לֵאמֹר",
         "קאל אללה למוסי'. ואלעזר. אבן הרון אלאמאם קאילא",
         "God spoke to Moses and Eleazar son of Aaron the priest, saying"),
    ],
    2: [
        ("שְׂאוּ אֶת-רֹאשׁ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל",
         "ארפעא גמלה' גמאעה' בני אסראיל",
         "'Take up the count of the whole congregation of the sons of Israel"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה", "מן אבן עשרין סנה. פצאעדא",
         "from twenty years of age and upward"),
        ("לְבֵית אֲבֹתָם כָּל-יֹצֵא צָבָא בְּיִשְׂרָאֵל",
         "לביות אבאיהם. כל מן יכ'רג פי גיושהם",
         "by their fathers' houses, every one who goes forth in their armies"),
    ],
    3: [
        ("וַיְדַבֵּר מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן אֹתָם", "פאמר מוסי'. ואלעזר אלאמאם באחצאיהם",
         "And Moses and Eleazar the priest ordered their counting"),
        ("בְּעַרְבֹת מוֹאָב עַל-יַרְדֵּן יְרֵחוֹ", "פי בידאת מואב. עלי' ארדן יריחא",
         "in the wilderness plain of Moab, by the Jordan of Jericho"),
    ],
    4: [
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמָעְלָה", "מן אבן עשרין סנה פצאעדא",
         "From twenty years of age and upward"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא כאן אמר אללה מוסי'",
         "as God had commanded Moses"),
        ("וּבְנֵי יִשְׂרָאֵל הַיֹּצְאִים מֵאֶרֶץ מִצְרָיִם",
         "ובני אסראיל. אלכ'ארגין מן בלד מצר",
         "and the sons of Israel, those going forth from the land of Egypt"),
    ],
    5: [
        ("רְאוּבֵן בְּכוֹר יִשְׂרָאֵל", "וכאן בני ראובן בכר אסראיל",
         "And the sons of Reuben, the firstborn of Israel"),
        ("מִשְׁפַּחַת הַחֲנֹכִי לְפַלּוּא מִשְׁפַּחַת הַפַּלֻּאִי",
         "עשירה' אלחנוכיין. ועשירה' אלפלואיין",
         "the clan of the Hanochites, and the clan of the Palluites"),
    ],
    6: [
        ("לְחֶצְרֹן מִשְׁפַּחַת הַחֶצְרוֹנִי לְכַרְמִי מִשְׁפַּחַת הַכַּרְמִי",
         "ועשירה' אלחצרוניין. ועשירה' אלכרמיין",
         "and the clan of the Hezronites, and the clan of the Carmites"),
    ],
    7: [
        ("אֵלֶּה מִשְׁפְּחֹת הָראוּבֵנִי", "פכאן עדד עשאיר ראובן",
         "And the count of the clans of Reuben"),
        ("שְׁלֹשָׁה וְאַרְבָּעִים אֶלֶף וּשְׁבַע מֵאוֹת וּשְׁלֹשִׁים",
         "ת'לאת'ה וארבעין אלפא. וסבע מאיה ות'לאת'ין",
         "was forty-three thousand, seven hundred and thirty"),
    ],
    8: [
        ("וּבְנֵי פַלּוּא אֱלִיאָב", "ובני פלוא אליאב", "And the sons of Pallu: Eliab"),
    ],
    9: [
        ("וּבְנֵי אֱלִיאָב נְמוּאֵל וְדָתָן וַאֲבִירָם",
         "ובני אליאב נמואל ודתן ואבירם",
         "And the sons of Eliab: Nemuel, and Dathan, and Abiram"),
        ("אֲשֶׁר הִצּוּ עַל-מֹשֶׁה וְעַל-אַהֲרֹן בַּעֲדַת-קֹרַח",
         "אלד'י תלפפו. עלי' מוסי' והרון פי גמאעה' קרח",
         "who rallied against Moses and Aaron within the congregation of Korah"),
        ("בְּהַצֹּתָם עַל-יְהוָה", "וכאן ד'אלך בין ידי אללה",
         "and that was before God"),
    ],
    10: [
        ("וַתִּפְתַּח הָאָרֶץ אֶת-פִּיהָ וַתִּבְלַע אֹתָם וְאֶת-קֹרַח",
         "פפתחת אלארץ' פאהא. פאבתלעתהם מע קרח",
         "And the earth opened its mouth and swallowed them along with Korah"),
        ("בְּמוֹת הָעֵדָה בַּאֲכֹל הָאֵשׁ אֵת חֲמִשִּׁים וּמָאתַיִם אִישׁ",
         "פי וקת מות אלגמאעה. ואכל אלנאר. אלמאיתין ואלכ'מסין אלרגל",
         "at the time of the death of the congregation — and fire consumed the two hundred and fifty men"),
        ("וַיִּהְיוּ לְנֵס", "פצארו עלמא", "and they became a sign"),
    ],
    11: [
        ("וּבְנֵי-קֹרַח לֹא-מֵתוּ", "ובני קרח כ'סף בהם ולם ימותו",
         "But as for the sons of Korah — the earth sank with them, and they did not die"),
    ],
    12: [
        ("בְּנֵי שִׁמְעוֹן לְמִשְׁפְּחֹתָם", "בני שמעון לעשאירהם",
         "The sons of Simeon by their clans"),
        ("לִנְמוּאֵל מִשְׁפַּחַת הַנְּמוּאֵלִי לְיָמִין מִשְׁפַּחַת הַיָּמִינִי לְיָכִין מִשְׁפַּחַת הַיָּכִינִי",
         "עשירה' אלנמואליין. ועשירה' אלימיניין. ועשירה' אליכיניין",
         "the clan of the Nemuelites, and the clan of the Jaminites, and the clan of the Jachinites"),
    ],
    13: [
        ("לְזֶרַח מִשְׁפַּחַת הַזַּרְחִי לְשָׁאוּל מִשְׁפַּחַת הַשָּׁאוּלִי",
         "ועשירה' אלזרחיין. ועשירה' אלשאוליין",
         "and the clan of the Zerahites, and the clan of the Shaulites"),
    ],
    14: [
        ("אֵלֶּה מִשְׁפְּחֹת הַשִּׁמְעֹנִי", "פכאן עדד עשאיר שמעון",
         "And the count of the clans of Simeon"),
        ("שְׁנַיִם וְעֶשְׂרִים אֶלֶף וּמָאתָיִם", "את'נין ועשרין אלפא ומאיתין",
         "was twenty-two thousand and two hundred"),
    ],
    15: [
        ("בְּנֵי גָד לְמִשְׁפְּחֹתָם", "בני גד לעשאירהם", "The sons of Gad by their clans"),
        ("לִצְפוֹן מִשְׁפַּחַת הַצְּפוֹנִי לְחַגִּי מִשְׁפַּחַת הַחַגִּי לְשׁוּנִי מִשְׁפַּחַת הַשּׁוּנִי",
         "עשירה' אלצפוניין. ועשירה' אלחגיין. ועשירה' אלשוניין",
         "the clan of the Zephonites, and the clan of the Haggites, and the clan of the Shunites"),
    ],
    16: [
        ("לְאָזְנִי מִשְׁפַּחַת הָאָזְנִי לְעֵרִי מִשְׁפַּחַת הָעֵרִי",
         "ועשירה' אלאזניין. ועשירה' אלעיריין",
         "and the clan of the Oznites, and the clan of the Erites"),
    ],
    17: [
        ("לַאֲרוֹד מִשְׁפַּחַת הָאֲרוֹדִי לְאַרְאֵלִי--מִשְׁפַּחַת הָאַרְאֵלִי",
         "ועשירה' אלארודיין. ועשירה' אלאראליין",
         "and the clan of the Arodites, and the clan of the Arelites"),
    ],
    18: [
        ("אֵלֶּה מִשְׁפְּחֹת בְּנֵי-גָד", "וכאן עדד עשאיר גד",
         "And the count of the clans of Gad"),
        ("אַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת", "ארבעין אלפא וכמס מאיה",
         "was forty thousand and five hundred"),
    ],
    19: [
        ("בְּנֵי יְהוּדָה עֵר וְאוֹנָן", "בני יהודה אוולא ער ואונן",
         "The sons of Judah — first Er and Onan"),
        ("וַיָּמָת עֵר וְאוֹנָן בְּאֶרֶץ כְּנָעַן", "ומאתא פי בלד כנעאן",
         "and they died in the land of Canaan"),
    ],
    20: [
        ("וַיִּהְיוּ בְנֵי-יְהוּדָה לְמִשְׁפְּחֹתָם", "פצאר בני יהודה לעשאירהם",
         "And the sons of Judah became, by their clans"),
        ("לְשֵׁלָה מִשְׁפַּחַת הַשֵּׁלָנִי לְפֶרֶץ מִשְׁפַּחַת הַפַּרְצִי לְזֶרַח מִשְׁפַּחַת הַזַּרְחִי",
         "עשירה' אלשילניין. ועשירה' אלפרציין. ועשירה' אלזרחיין",
         "the clan of the Shelanites, and the clan of the Parzites, and the clan of the Zerahites"),
    ],
    21: [
        ("וַיִּהְיוּ בְנֵי-פֶרֶץ", "ובני פרץ", "And the sons of Perez"),
        ("לְחֶצְרֹן מִשְׁפַּחַת הַחֶצְרֹנִי לְחָמוּל מִשְׁפַּחַת הֶחָמוּלִי",
         "עשירה' אלחצרוניין. ועשירה' אלחמוליין",
         "the clan of the Hezronites, and the clan of the Hamulites"),
    ],
    22: [
        ("אֵלֶּה מִשְׁפְּחֹת יְהוּדָה", "פכאן עדד עשאיר יהודה",
         "And the count of the clans of Judah"),
        ("שִׁשָּׁה וְשִׁבְעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת", "סתה וסבעין אלפא וכמס מאיה",
         "was seventy-six thousand and five hundred"),
    ],
    23: [
        ("בְּנֵי יִשָּׂשכָר לְמִשְׁפְּחֹתָם", "בני יששכר לעשאירהם",
         "The sons of Issachar by their clans"),
        ("תּוֹלָע מִשְׁפַּחַת הַתּוֹלָעִי לְפֻוָה מִשְׁפַּחַת הַפּוּנִי",
         "עשירה' אלתולעיין. ועשירה' אלפוניין",
         "the clan of the Tolaites, and the clan of the Punites"),
    ],
    24: [
        ("לְיָשׁוּב מִשְׁפַּחַת הַיָּשֻׁבִי לְשִׁמְרֹן מִשְׁפַּחַת הַשִּׁמְרֹנִי",
         "ועשירה' אלישוביין. ועשירה' אלשמרוניין",
         "and the clan of the Jashubites, and the clan of the Shimronites"),
    ],
    25: [
        ("אֵלֶּה מִשְׁפְּחֹת יִשָּׂשכָר", "וכאן עדד עשאיר יששכר",
         "And the count of the clans of Issachar"),
        ("אַרְבָּעָה וְשִׁשִּׁים אֶלֶף וּשְׁלֹשׁ מֵאוֹת", "ארבעה וסתין אלפא ות'לאת' מאיה",
         "was sixty-four thousand and three hundred"),
    ],
    26: [
        ("בְּנֵי זְבוּלֻן לְמִשְׁפְּחֹתָם", "בני זבולון לעשאירהם",
         "The sons of Zebulun by their clans"),
        ("לְסֶרֶד מִשְׁפַּחַת הַסַּרְדִּי לְאֵלוֹן מִשְׁפַּחַת הָאֵלֹנִי לְיַחְלְאֵל--מִשְׁפַּחַת הַיַּחְלְאֵלִי",
         "עשירה' אלסרדיין. ועשירה' אלאילוניין. ועשירה' אליחלאליין",
         "the clan of the Sardites, and the clan of the Elonites, and the clan of the Jahleelites"),
    ],
    27: [
        ("אֵלֶּה מִשְׁפְּחֹת הַזְּבוּלֹנִי", "פכאן עדד עשאיר זבולון",
         "And the count of the clans of Zebulun"),
        ("שִׁשִּׁים אֶלֶף וַחֲמֵשׁ מֵאוֹת", "סתין אלפא וכמס מאיה",
         "was sixty thousand and five hundred"),
    ],
    28: [
        ("בְּנֵי יוֹסֵף לְמִשְׁפְּחֹתָם--מְנַשֶּׁה וְאֶפְרָיִם",
         "בני יוסף לעשאירהם. מנשה ואפרים",
         "The sons of Joseph by their clans: Manasseh and Ephraim"),
    ],
    29: [
        ("בְּנֵי מְנַשֶּׁה לְמָכִיר מִשְׁפַּחַת הַמָּכִירִי",
         "בני מנשה. עשירה' אלמכיריין",
         "The sons of Manasseh: the clan of the Machrites"),
        ("וּמָכִיר הוֹלִיד אֶת-גִּלְעָד לְגִלְעָד מִשְׁפַּחַת הַגִּלְעָדִי",
         "ועשירה' אלגלעדיין. מן גלעד אבן מכיר",
         "and the clan of the Gileadites — from Gilead son of Machir"),
    ],
    30: [
        ("אֵלֶּה בְּנֵי גִלְעָד", "הולאי בני גלעד", "These are the sons of Gilead"),
        ("אִיעֶזֶר מִשְׁפַּחַת הָאִיעֶזְרִי לְחֵלֶק מִשְׁפַּחַת הַחֶלְקִי",
         "עשירה' אלאיעזריין. ועשירה' אלחלקיין",
         "the clan of the Iezerites, and the clan of the Helekites"),
    ],
    31: [
        ("וְאַשְׂרִיאֵל--מִשְׁפַּחַת הָאַשְׂרִאֵלִי וְשֶׁכֶם מִשְׁפַּחַת הַשִּׁכְמִי",
         "ועשירה' אלאסראיליין. ועשירה' אלשכמיין",
         "and the clan of the Asrielites, and the clan of the Shechemites"),
    ],
    32: [
        ("וּשְׁמִידָע מִשְׁפַּחַת הַשְּׁמִידָעִי וְחֵפֶר מִשְׁפַּחַת הַחֶפְרִי",
         "ועשירה' אלשמידעיין. ועשירה' אלחפריין",
         "and the clan of the Shemidaites, and the clan of the Hepherites"),
    ],
    33: [
        ("וּצְלָפְחָד בֶּן-חֵפֶר לֹא-הָיוּ לוֹ בָּנִים--כִּי אִם-בָּנוֹת",
         "וצלפחד אבן חפר. לם יכון לה בנין אלא בנאת",
         "And Zelophehad son of Hepher had no sons, only daughters"),
        ("וְשֵׁם בְּנוֹת צְלָפְחָד--מַחְלָה וְנֹעָה חָגְלָה מִלְכָּה וְתִרְצָה",
         "ואסמאיהן. מחלה ונועה. חגלה מלכה ותרצה",
         "and their names were Mahlah, and Noah, Hoglah, Milcah, and Tirzah"),
    ],
    34: [
        ("אֵלֶּה מִשְׁפְּחֹת מְנַשֶּׁה", "פכאן עדד עשאיר מנשה",
         "And the count of the clans of Manasseh"),
        ("שְׁנַיִם וַחֲמִשִּׁים אֶלֶף וּשְׁבַע מֵאוֹת", "את'נין וכ'מסין אלפא וסבע מאיה",
         "was fifty-two thousand and seven hundred"),
    ],
    35: [
        ("אֵלֶּה בְנֵי-אֶפְרַיִם לְמִשְׁפְּחֹתָם", "הולאי בני אפרים לעשאירהם",
         "These are the sons of Ephraim by their clans"),
        ("לְשׁוּתֶלַח מִשְׁפַּחַת הַשֻּׁתַלְחִי לְבֶכֶר מִשְׁפַּחַת הַבַּכְרִי לְתַחַן מִשְׁפַּחַת הַתַּחֲנִי",
         "עשירה' אלשותלחיין. ועשירה' אלבכ'ריין. ועשירה' אלתחניין",
         "the clan of the Shutalhites, and the clan of the Becherites, and the clan of the Tahanites"),
    ],
    36: [
        ("וְאֵלֶּה בְּנֵי שׁוּתָלַח--לְעֵרָן מִשְׁפַּחַת הָעֵרָנִי",
         "ועשירה' אלעירניין. מן עירן אבן שותלח",
         "and the clan of the Eranites, from Eran son of Shutelah"),
    ],
    37: [
        ("אֵלֶּה מִשְׁפְּחֹת בְּנֵי-אֶפְרַיִם", "פכאן עדד עשאיר בני אפרים",
         "And the count of the clans of the sons of Ephraim"),
        ("שְׁנַיִם וּשְׁלֹשִׁים אֶלֶף וַחֲמֵשׁ מֵאוֹת", "את'נין ות'לאת'ין אלפא וכ'מס מאיה",
         "was thirty-two thousand and five hundred"),
        ("אֵלֶּה בְנֵי-יוֹסֵף לְמִשְׁפְּחֹתָם", "הולאי בני יוסף לעשאירהם",
         "These are the sons of Joseph by their clans"),
    ],
    38: [
        ("בְּנֵי בִנְיָמִן לְמִשְׁפְּחֹתָם", "בני בנימין לעשאירהם",
         "The sons of Benjamin by their clans"),
        ("לְבֶלַע מִשְׁפַּחַת הַבַּלְעִי לְאַשְׁבֵּל מִשְׁפַּחַת הָאַשְׁבֵּלִי לַאֲחִירָם מִשְׁפַּחַת הָאֲחִירָמִי",
         "עשירה' אלבלעיין. ועשירה' אלאשבליין. ועשירה' אלאחירמיין",
         "the clan of the Belaites, and the clan of the Ashbelites, and the clan of the Ahiramites"),
    ],
    39: [
        ("לִשְׁפוּפָם מִשְׁפַּחַת הַשּׁוּפָמִי לְחוּפָם מִשְׁפַּחַת הַחוּפָמִי",
         "ועשירה' אלשופמיין. ועשירה' אלחופמיין",
         "and the clan of the Shuphamites, and the clan of the Huphamites"),
    ],
    40: [
        ("וַיִּהְיוּ בְנֵי-בֶלַע אַרְדְּ וְנַעֲמָן", "ועשירה' אלארדיין. ועשירה' אלנעמיין. מן בלע",
         "and the clan of the Ardites, and the clan of the Naamites — from Bela"),
    ],
    41: [
        ("אֵלֶּה בְנֵי-בִנְיָמִן לְמִשְׁפְּחֹתָם", "פכאן עדד עשאיר בנימין",
         "And the count of the clans of Benjamin"),
        ("חֲמִשָּׁה וְאַרְבָּעִים אֶלֶף וְשֵׁשׁ מֵאוֹת", "כמסה וארבעין אלפא וסת מאיה",
         "was forty-five thousand and six hundred"),
    ],
    42: [
        ("אֵלֶּה בְנֵי-דָן לְמִשְׁפְּחֹתָם", "ובני דן לעשאירהם",
         "And the sons of Dan by their clans"),
        ("לְשׁוּחָם מִשְׁפַּחַת הַשּׁוּחָמִי", "עשירה' אלשוחמיין. ומא תעשר מנהא",
         "the clan of the Shuhamites, and what branched out from it"),
    ],
    43: [
        ("כָּל-מִשְׁפְּחֹת הַשּׁוּחָמִי לִפְקֻדֵיהֶם", "פכאן עדדהם",
         "And their count"),
        ("אַרְבָּעָה וְשִׁשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת", "ארבעה וסתין אלפא וארבע מאיה",
         "was sixty-four thousand and four hundred"),
    ],
    44: [
        ("בְּנֵי אָשֵׁר לְמִשְׁפְּחֹתָם", "בני אשר לעשאירהם",
         "The sons of Asher by their clans"),
        ("לְיִמְנָה מִשְׁפַּחַת הַיִּמְנָה לְיִשְׁוִי מִשְׁפַּחַת הַיִּשְׁוִי לִבְרִיעָה מִשְׁפַּחַת הַבְּרִיעִי",
         "עשירה' אלימניין. ועשירה' אלישויין. ועשירה' אלבריעיין",
         "the clan of the Imnites, and the clan of the Ishvites, and the clan of the Beriites"),
    ],
    45: [
        ("לִבְנֵי בְרִיעָה--לְחֶבֶר מִשְׁפַּחַת הַחֶבְרִי לְמַלְכִּיאֵל--מִשְׁפַּחַת הַמַּלְכִּיאֵלִי",
         "ועשירה' אלחבריין. ועשירה' אלמלכיאליין. מן בריעה",
         "the clan of the Heberites, and the clan of the Malchielites — from the clan of the Beriites"),
    ],
    46: [
        ("וְשֵׁם בַּת-אָשֵׁר שָׂרַח", "וכאן אסם אבנה' אשר שרח",
         "And the name of the daughter of Asher was Serah"),
    ],
    47: [
        ("אֵלֶּה מִשְׁפְּחֹת בְּנֵי-אָשֵׁר", "פכאן עדד עשאיר אשר",
         "And the count of the clans of Asher"),
        ("שְׁלֹשָׁה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת", "ת'לאת'ה וכמסין אלפא וארבע מאיה",
         "was fifty-three thousand and four hundred"),
    ],
    48: [
        ("בְּנֵי נַפְתָּלִי לְמִשְׁפְּחֹתָם", "בני נפתלי לעשאירהם",
         "The sons of Naphtali by their clans"),
        ("לְיַחְצְאֵל מִשְׁפַּחַת הַיַּחְצְאֵלִי לְגוּנִי מִשְׁפַּחַת הַגּוּנִי",
         "עשירה' אליחצאליין. ועשירה' אלגוניין",
         "the clan of the Jahzeelites, and the clan of the Gunites"),
    ],
    49: [
        ("לְיֵצֶר מִשְׁפַּחַת הַיִּצְרִי לְשִׁלֵּם מִשְׁפַּחַת הַשִּׁלֵּמִי",
         "ועשירה' אליצריין. ועשירה' אלשלמיין",
         "and the clan of the Jezerites, and the clan of the Shillemites"),
    ],
    50: [
        ("אֵלֶּה מִשְׁפְּחֹת נַפְתָּלִי", "פכאן עדד עשאיר נפתלי",
         "And the count of the clans of Naphtali"),
        ("חֲמִשָּׁה וְאַרְבָּעִים אֶלֶף וְאַרְבַּע מֵאוֹת", "כמסה וארבעין אלפא וארבע מאיה",
         "was forty-five thousand and four hundred"),
    ],
    51: [
        ("אֵלֶּה פְּקוּדֵי בְּנֵי יִשְׂרָאֵל", "פד'אלך עדד בני אסראיל",
         "That, then, is the count of the sons of Israel"),
        ("שֵׁשׁ-מֵאוֹת אֶלֶף וָאָלֶף שְׁבַע מֵאוֹת וּשְׁלֹשִׁים",
         "סת מאיה' אלף ואלפא ואחדא. וסבע מאיה ות'לאת'ין",
         "six hundred thousand and one thousand, seven hundred and thirty"),
    ],
    52: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, addressing him"),
    ],
    53: [
        ("לָאֵלֶּה תֵּחָלֵק הָאָרֶץ בְּנַחֲלָה", "ולהולאי יגב אן יקסם אלבלד נחלה",
         "'To these it is required that the land be apportioned as an inheritance"),
        ("בְּמִסְפַּר שֵׁמוֹת", "באחצא אסמאיהם", "by the count of their names"),
    ],
    54: [
        ("לָרַב תַּרְבֶּה נַחֲלָתוֹ", "פלאלכתיר תכת'ר נחלתה",
         "To the numerous you shall enlarge his inheritance"),
        ("וְלַמְעַט תַּמְעִיט נַחֲלָתוֹ", "ולאלקליל תקללהא",
         "and to the few you shall diminish his inheritance"),
        ("אִישׁ לְפִי פְקֻדָיו יֻתַּן נַחֲלָתוֹ", "כל סבט עלי' קדר עדדה. יעטא נחלתה",
         "each tribe according to the measure of its number shall its inheritance be given"),
    ],
    55: [
        ("אַךְ-בְּגוֹרָל יֵחָלֵק אֶת-הָאָרֶץ", "לכן באסהם יקסם אלבלד",
         "But by lots shall the land be apportioned"),
        ("לִשְׁמוֹת מַטּוֹת-אֲבֹתָם יִנְחָלוּ", "באסמא אסבאט אבאיהם",
         "by the names of the tribes of their fathers"),
    ],
    56: [
        ("עַל-פִּי הַגּוֹרָל תֵּחָלֵק נַחֲלָתוֹ", "ועלי קדר אלסהם. תקסם נחלתהם",
         "According to the measure of the lots shall their inheritance be apportioned"),
        ("בֵּין רַב לִמְעָט", "בין כת'יר. וקליל", "between the numerous and the few"),
    ],
    57: [
        ("וְאֵלֶּה פְקוּדֵי הַלֵּוִי לְמִשְׁפְּחֹתָם", "והד'ה אעדאד לוי לעשאירהם",
         "And these are the counts of Levi by their clans"),
        ("לְגֵרְשׁוֹן מִשְׁפַּחַת הַגֵּרְשֻׁנִּי לִקְהָת מִשְׁפַּחַת הַקְּהָתִי לִמְרָרִי מִשְׁפַּחַת הַמְּרָרִי",
         "עשירה' אלגרשוניין. ועשירה' אלקהתיין. ועשירה' אלמרריין",
         "the clan of the Gershonites, and the clan of the Kohathites, and the clan of the Merarites"),
    ],
    58: [
        ("אֵלֶּה מִשְׁפְּחֹת לֵוִי מִשְׁפַּחַת הַלִּבְנִי מִשְׁפַּחַת הַחֶבְרֹנִי מִשְׁפַּחַת הַמַּחְלִי מִשְׁפַּחַת הַמּוּשִׁי מִשְׁפַּחַת הַקָּרְחִי",
         "וסאיר עשאירהם. עשירה' אללבניין. ועשירה' אלחברוניין ועשירה' אלמחליין ועשירה' אלמושיין. ועשירה' אלקרחיין",
         "And the rest of their clans: the clan of the Libnites, and the clan of the Hebronites, and the clan of the Mahlites, and the clan of the Mushites, and the clan of the Korahites"),
        ("וּקְהָת הוֹלִד אֶת-עַמְרָם", "ואולד קהת עמרם", "and Kohath begot Amram"),
    ],
    59: [
        ("וְשֵׁם אֵשֶׁת עַמְרָם יוֹכֶבֶד בַּת-לֵוִי", "וכאן אסם זוגה' עמרם. יוכבד אבנה' לוי",
         "And the name of the wife of Amram was Jochebed, daughter of Levi"),
        ("אֲשֶׁר יָלְדָה אֹתָהּ לְלֵוִי בְּמִצְרָיִם", "אלד'י ולדת ללוי במצר",
         "who was born to Levi in Egypt"),
        ("וַתֵּלֶד לְעַמְרָם אֶת-אַהֲרֹן וְאֶת-מֹשֶׁה וְאֵת מִרְיָם אֲחֹתָם",
         "פולדת לעמרם. הרון ומוסי. ומרים אכ'תהם",
         "and she bore to Amram: Aaron and Moses, and Miriam their sister"),
    ],
    60: [
        ("וַיִּוָּלֵד לְאַהֲרֹן אֶת-נָדָב וְאֶת-אֲבִיהוּא אֶת-אֶלְעָזָר וְאֶת-אִיתָמָר",
         "פולד להרון. נדב ואביהוא. אלעזר ואיתמר",
         "And there were born to Aaron: Nadab and Abihu, Eleazar and Ithamar"),
    ],
    61: [
        ("וַיָּמָת נָדָב וַאֲבִיהוּא", "פמאת נדב ואביהוא", "And Nadab and Abihu died"),
        ("בְּהַקְרִיבָם אֵשׁ-זָרָה לִפְנֵי יְהוָה", "חין קרבא נארא ג'ריבא בין ידי אללה",
         "when the two of them offered strange fire before God"),
    ],
    62: [
        ("וַיִּהְיוּ פְקֻדֵיהֶם שְׁלֹשָׁה וְעֶשְׂרִים אֶלֶף", "פכאן עדדהם. ת'לאת'ה ועשרין אלפא",
         "And their count was twenty-three thousand"),
        ("כָּל-זָכָר מִבֶּן-חֹדֶשׁ וָמָעְלָה", "כל ד'כר מן אבן שהר פצאעדא",
         "every male from a month of age and upward"),
        ("כִּי לֹא הָתְפָּקְדוּ בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "אד' לם יעדו. פי גמלה' בני אסראיל",
         "since they were not counted among the total of the sons of Israel"),
        ("כִּי לֹא-נִתַּן לָהֶם נַחֲלָה בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "אד' לם יעטו נחלה פי וסטהם",
         "since no inheritance was given to them in their midst"),
    ],
    63: [
        ("אֵלֶּה פְּקוּדֵי מֹשֶׁה וְאֶלְעָזָר הַכֹּהֵן", "הולאי מעדודי מוסי'. ואלעזר אלאמאם",
         "These are the counts of Moses and Eleazar the priest"),
        ("אֲשֶׁר פָּקְדוּ אֶת-בְּנֵי יִשְׂרָאֵל", "אלד'י עדא בני אסראיל",
         "who counted the sons of Israel"),
        ("בְּעַרְבֹת מוֹאָב עַל יַרְדֵּן יְרֵחוֹ", "פי בידאת מואב. עלי' ארדן יריחא",
         "in the wilderness plain of Moab, by the Jordan of Jericho"),
    ],
    64: [
        ("וּבְאֵלֶּה לֹא-הָיָה אִישׁ מִפְּקוּדֵי מֹשֶׁה וְאַהֲרֹן הַכֹּהֵן",
         "ופי הולאי לם יכון רגל. מן מעדודי מוסי'. והרון אלאמאם",
         "And among these there was not a man from among those counted by Moses and Aaron the priest"),
        ("אֲשֶׁר פָּקְדוּ אֶת-בְּנֵי יִשְׂרָאֵל בְּמִדְבַּר סִינָי",
         "אלד'י עדא בני אסראיל פי ברייה' סיני",
         "who had counted the sons of Israel in the wilderness of Sinai"),
    ],
    65: [
        ("כִּי-אָמַר יְהוָה לָהֶם מוֹת יָמֻתוּ בַּמִּדְבָּר", "לאן אללה חכם עליהם. אן יתמאותון פי אלברייה",
         "for God had decreed upon them that they should die one by one in the wilderness"),
        ("וְלֹא-נוֹתַר מֵהֶם אִישׁ", "ולם יבק מנהם רגל",
         "and not a man remained of them"),
        ("כִּי אִם-כָּלֵב בֶּן-יְפֻנֶּה וִיהוֹשֻׁעַ בִּן-נוּן",
         "אלא כלב אבן יפנה. ויהושע אבן נון",
         "save Caleb son of Jephunneh, and Joshua son of Nun"),
    ],
}
