"""Hand-authored alignment triples for Bamidbar chapter 22."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּסְעוּ בְּנֵי יִשְׂרָאֵל וַיַּחֲנוּ בְּעַרְבוֹת מוֹאָב",
         "ת'ם רחלו בני אסראיל. ונזלו פי בידאת מואב",
         "Then the sons of Israel journeyed, and encamped in the wilderness of Moab"),
        ("מֵעֵבֶר לְיַרְדֵּן יְרֵחוֹ", "אלתי עלי' ארדן יריחא",
         "which is by the Jordan of Jericho."),
    ],
    2: [
        ("וַיַּרְא בָּלָק בֶּן-צִפּוֹר", "ולמא ראא בלק אבן צפור",
         "And when Balak son of Zippor saw"),
        ("אֵת כָּל-אֲשֶׁר-עָשָׂה יִשְׂרָאֵל לָאֱמֹרִי",
         "גמיע מא צנע אל אסראיל באלאמוריין",
         "all that the people of Israel had done to the Amorites,"),
    ],
    3: [
        ("וַיָּגָר מוֹאָב מִפְּנֵי הָעָם מְאֹד--כִּי רַב-הוּא",
         "פחד'ר אלמואביין. מן קבל אלקום. גדא אד' הם כ'תירין",
         "the Moabites were greatly wary of the people, since they are numerous"),
        ("וַיָּקָץ מוֹאָב מִפְּנֵי בְּנֵי יִשְׂרָאֵל", "וצ'גרו מנהם",
         "and they were filled with dread because of them."),
    ],
    4: [
        ("וַיֹּאמֶר מוֹאָב אֶל-זִקְנֵי מִדְיָן", "פקאל לשיוך' מדין",
         "And they said to the elders of Midian"),
        ("עַתָּה יְלַחֲכוּ הַקָּהָל אֶת-כָּל-סְבִיבֹתֵינוּ",
         "אלאן סילחס הולאי אלגוק כל נאס חואלינא",
         "'Now this horde will lick up all the people around us"),
        ("כִּלְחֹךְ הַשּׁוֹר אֵת יֶרֶק הַשָּׂדֶה",
         "כמא ילחס אלת'ור כ'צ'ר אלצחרא",
         "as the ox licks up the green of the wilderness.'"),
        ("וּבָלָק בֶּן-צִפּוֹר מֶלֶךְ לְמוֹאָב בָּעֵת הַהִוא",
         "וכאן בלק אבן צפור. מלכהם פי ד'אלך אלוקת",
         "And Balak son of Zippor was their king at that time."),
    ],
    5: [
        ("וַיִּשְׁלַח מַלְאָכִים אֶל-בִּלְעָם בֶּן-בְּעֹר פְּתוֹרָה",
         "פבעת' ברסל אלי' בלעם אבן בעור. אלי' פאתורא",
         "And he sent messengers to Balaam son of Beor, to Pethor"),
        ("אֲשֶׁר עַל-הַנָּהָר אֶרֶץ בְּנֵי-עַמּוֹ", "אלד'י עלי' אלפראת. בלד קומה",
         "which is on the Euphrates, the land of his people"),
        ("לִקְרֹא-לוֹ לֵאמֹר", "לידעו בה. וקאל לה",
         "to invite him; and said to him"),
        ("הִנֵּה עַם יָצָא מִמִּצְרַיִם הִנֵּה כִסָּה אֶת-עֵין הָאָרֶץ",
         "הוד'א קום כ'רג מן מצר קד ג'טא צ'אהר אלארץ'",
         "'Behold, a people has come out of Egypt — it has already covered the face of the land"),
        ("וְהוּא יֹשֵׁב מִמֻּלִי", "והו גאלס מקאבלי",
         "and it sits encamped opposite me."),
    ],
    6: [
        ("וְעַתָּה לְכָה-נָּא אָרָה-לִּי אֶת-הָעָם הַזֶּה",
         "ואלאן פתעאל אלענה לי",
         "And now, come and curse it for me"),
        ("כִּי-עָצוּם הוּא מִמֶּנִּי", "אד' הם א עצ'ם מני",
         "since they are stronger than I"),
        ("אוּלַי אוּכַל נַכֶּה-בּוֹ וַאֲגָרְשֶׁנּוּ מִן-הָאָרֶץ",
         "פלעלי' אסתטיע אן אחארבה. ואטרדה מן אלבלד",
         "perhaps I shall be able to fight against it and drive it out of the land"),
        ("כִּי יָדַעְתִּי אֵת אֲשֶׁר-תְּבָרֵךְ מְבֹרָךְ וַאֲשֶׁר תָּאֹר יוּאָר",
         "לאני אעלם. אן מן תבארכה מבארך. ומן תלענה ילען",
         "for I know that he whom you bless is blessed, and he whom you curse is cursed.'"),
    ],
    7: [
        ("וַיֵּלְכוּ זִקְנֵי מוֹאָב וְזִקְנֵי מִדְיָן וּקְסָמִים בְּיָדָם",
         "פמצ'ו שיוך' מואב ושיוך' מדין. ופאלאת מעהם",
         "And the elders of Moab and the elders of Midian went, with divination-fees with them"),
        ("וַיָּבֹאוּ אֶל-בִּלְעָם", "חתי' ואפו בלעם",
         "until they reached Balaam"),
        ("וַיְדַבְּרוּ אֵלָיו דִּבְרֵי בָלָק", "פאכ'ברוה בכלאם בלק",
         "and told him the words of Balak."),
    ],
    8: [
        ("וַיֹּאמֶר אֲלֵיהֶם לִינוּ פֹה הַלַּיְלָה", "פקאל להם. ביתו ההנא אללילה",
         "And he said to them: 'Lodge here tonight"),
        ("וַהֲשִׁבֹתִי אֶתְכֶם דָּבָר כַּאֲשֶׁר יְדַבֵּר יְהוָה אֵלָי",
         "וארד עלי'כם גואבא. כמא יקול אללה לי",
         "and I shall bring you back an answer, as God shall say to me.'"),
        ("וַיֵּשְׁבוּ שָׂרֵי-מוֹאָב עִם-בִּלְעָם", "פאקאם רויסא מואב ענד בלעם",
         "And the officers of Moab stayed with Balaam."),
    ],
    9: [
        ("וַיָּבֹא אֱלֹהִים אֶל-בִּלְעָם", "פואפא אמר אללה בלעם",
         "And the decree of God came to Balaam"),
        ("וַיֹּאמֶר מִי הָאֲנָשִׁים הָאֵלֶּה עִמָּךְ",
         "וקאל מפתתחא. מן הולאי אלקום אלד'ין מעך",
         "and said, opening the speech: 'Who are these people that are with you?'"),
    ],
    10: [
        ("וַיֹּאמֶר בִּלְעָם אֶל-הָאֱלֹהִים", "קאל",
         "He said"),
        ("בָּלָק בֶּן-צִפֹּר מֶלֶךְ מוֹאָב שָׁלַח אֵלָי",
         "אן בלק אבן צפור. מלך מואב בעת' בהם אלי'י",
         "'Balak son of Zippor, king of Moab, has sent them to me,"),
    ],
    11: [
        ("הִנֵּה הָעָם הַיֹּצֵא מִמִּצְרַיִם וַיְכַס אֶת-עֵין הָאָרֶץ",
         "יקול אן אלקום אלד'י כ'רג מן מצר. קד ג'טא צ'אהר אלארץ'",
         "saying: Behold, the people that came out of Egypt has already covered the face of the land."),
        ("עַתָּה לְכָה קָבָה-לִּי אֹתוֹ", "אלאן תעאל סבה לי",
         "Now come, curse it for me"),
        ("אוּלַי אוּכַל לְהִלָּחֶם בּוֹ וְגֵרַשְׁתִּיו",
         "לעלי' אסתטיע אן אחארבה ואטרדה",
         "perhaps I shall be able to fight against it and drive it out.'"),
    ],
    12: [
        ("וַיֹּאמֶר אֱלֹהִים אֶל-בִּלְעָם לֹא תֵלֵךְ עִמָּהֶם",
         "קאל לה לא תמץ' מעהם",
         "He said to him: 'Do not go with them"),
        ("לֹא תָאֹר אֶת-הָעָם כִּי בָרוּךְ הוּא", "ולא תלען אלקום. פאנה מבארך",
         "and do not curse the people — for it is blessed.'"),
    ],
    13: [
        ("וַיָּקָם בִּלְעָם בַּבֹּקֶר", "פקאם באלג'דאה",
         "And he rose in the morning"),
        ("וַיֹּאמֶר אֶל-שָׂרֵי בָלָק לְכוּ אֶל-אַרְצְכֶם",
         "פקאל לרויסא בלק. אמצ'ו אלי' בלדכם",
         "and said to the officers of Balak: 'Go back to your land"),
        ("כִּי מֵאֵן יְהוָה לְתִתִּי לַהֲלֹךְ עִמָּכֶם",
         "לאן אללה נהאני. אן אמצ'י מעכם",
         "for God has forbidden me to go with you.'"),
    ],
    14: [
        ("וַיָּקוּמוּ שָׂרֵי מוֹאָב וַיָּבֹאוּ אֶל-בָּלָק",
         "פקאם רויסא מואב. וגאו אלי' בלק",
         "And the officers of Moab arose, and came to Balak"),
        ("וַיֹּאמְרוּ מֵאֵן בִּלְעָם הֲלֹךְ עִמָּנוּ",
         "וקאלו. קד אבא בלעם אן יגי מענא",
         "and said: 'Balaam has refused to come with us.'"),
    ],
    15: [
        ("וַיֹּסֶף עוֹד בָּלָק שְׁלֹחַ שָׂרִים רַבִּים וְנִכְבָּדִים מֵאֵלֶּה",
         "פעאוד בלק איצ'א. בעת' רויסא. א עצ'ם ואגל מן אולאיך",
         "And Balak again sent officers — greater and more honored than those."),
    ],
    16: [
        ("וַיָּבֹאוּ אֶל-בִּלְעָם וַיֹּאמְרוּ לוֹ", "פגאו אלי' בלעם. וקאלו לה",
         "And they came to Balaam, and said to him"),
        ("כֹּה אָמַר בָּלָק בֶּן-צִפּוֹר", "כד'א קאל בלק אבן צפור",
         "'Thus says Balak son of Zippor"),
        ("אַל-נָא תִמָּנַע מֵהֲלֹךְ אֵלָי", "לא תמתנע מן אלמציר אלי'י",
         "Do not hold yourself back from journeying to me."),
    ],
    17: [
        ("כִּי-כַבֵּד אֲכַבֶּדְךָ מְאֹד", "פאני סאכרמך גדא",
         "For I will honor you greatly"),
        ("וְכֹל אֲשֶׁר-תֹּאמַר אֵלַי אֶעֱשֶׂה", "וכל מא תקול לי אצנעה",
         "and whatever you say to me I will do"),
        ("וּלְכָה-נָּא קָבָה-לִּי אֵת הָעָם הַזֶּה", "ותעאל אלען לי הולאי אלקום",
         "— come, curse this people for me.'"),
    ],
    18: [
        ("וַיַּעַן בִּלְעָם וַיֹּאמֶר אֶל-עַבְדֵי בָלָק",
         "פאגאב בלעם קואד בלק וקאל להם",
         "And Balaam answered the commanders of Balak, and said to them"),
        ("אִם-יִתֶּן-לִי בָלָק מְלֹא בֵיתוֹ כֶּסֶף וְזָהָב",
         "לו אעטאני בלק. מל ביתה פצ'ה וד'הב",
         "'Even if Balak were to give me his houseful of silver and gold"),
        ("לֹא אוּכַל לַעֲבֹר אֶת-פִּי יְהוָה אֱלֹהָי",
         "לא אסתטיע אן אתגאוז אמר אללה רבי",
         "I cannot transgress the command of God my Lord"),
        ("לַעֲשׂוֹת קְטַנָּה אוֹ גְדוֹלָה", "פאעמל צג'ירה או כבירה",
         "to do a small thing or a great thing."),
    ],
    19: [
        ("וְעַתָּה שְׁבוּ נָא בָזֶה גַּם-אַתֶּם--הַלָּיְלָה",
         "ואלאן אקימו אנתם איצ'א. ההנא אללילה",
         "And now, stay here also tonight"),
        ("וְאֵדְעָה מַה-יֹּסֵף יְהוָה דַּבֵּר עִמִּי",
         "חתי' אנצ'ר מא יעאוד אללה אן יכ'אטבני בה",
         "that I may see what God will again address to me.'"),
    ],
    20: [
        ("וַיָּבֹא אֱלֹהִים אֶל-בִּלְעָם לַיְלָה", "פואפא אמר אללה בלעם לילא",
         "And the decree of God came to Balaam at night"),
        ("וַיֹּאמֶר לוֹ אִם-לִקְרֹא לְךָ בָּאוּ הָאֲנָשִׁים",
         "וקאל. אן כאן הולאי אלקום גאו לידעוך",
         "and said: 'If these people have come to invite you"),
        ("קוּם לֵךְ אִתָּם", "פקום אמץ' מעהם", "arise, go with them"),
        ("וְאַךְ אֶת-הַדָּבָר אֲשֶׁר-אֲדַבֵּר אֵלֶיךָ--אֹתוֹ תַעֲשֶׂה",
         "לכן אלאמר. אלד'י אקולה לך אצנעה פקט",
         "— but only the word that I shall tell you, that alone do.'"),
    ],
    21: [
        ("וַיָּקָם בִּלְעָם בַּבֹּקֶר וַיַּחֲבֹשׁ אֶת-אֲתֹנוֹ",
         "פקאם באלג'דאה. ואסרג אתאנה",
         "And he rose in the morning, and saddled his she-donkey"),
        ("וַיֵּלֶךְ עִם-שָׂרֵי מוֹאָב", "ומצ'א מע רויסא מואב",
         "and went with the officers of Moab."),
    ],
    22: [
        ("וַיִּחַר-אַף אֱלֹהִים כִּי-הוֹלֵךְ הוּא",
         "ת'ם אשתד ג'צ'ב אללה למצ'יה טאמעא",
         "Then God's anger intensified at his going in greed"),
        ("וַיִּתְיַצֵּב מַלְאַךְ יְהוָה בַּדֶּרֶךְ לְשָׂטָן לוֹ",
         "פוקף מלך אללה פי אלטריק ליחידה ען ד'אלך",
         "and the angel of God stood in the road to turn him away from that"),
        ("וְהוּא רֹכֵב עַל-אֲתֹנוֹ וּשְׁנֵי נְעָרָיו עִמּוֹ",
         "והו ראכב עלי' אתאנה. ומעה ג'לאמיה",
         "while he was riding on his she-donkey and his two youths were with him."),
    ],
    23: [
        ("וַתֵּרֶא הָאָתוֹן אֶת-מַלְאַךְ יְהוָה נִצָּב בַּדֶּרֶךְ וְחַרְבּוֹ שְׁלוּפָה בְּיָדוֹ",
         "פלמא ראת אלאתאן מלך אללה קאימא פי אלטריק. וסיפה מצלת פי ידה",
         "And when the she-donkey saw the angel of God standing in the road, with his sword drawn in his hand"),
        ("וַתֵּט הָאָתוֹן מִן-הַדֶּרֶךְ וַתֵּלֶךְ בַּשָּׂדֶה",
         "מאלת ען אלטריק. וסארת פי אלצ'יאע",
         "she turned aside from the road and went through the fields"),
        ("וַיַּךְ בִּלְעָם אֶת-הָאָתוֹן לְהַטֹּתָהּ הַדָּרֶךְ",
         "פצ'רבהא בלעם. לירדהא אלי' אלטריק",
         "so Balaam struck her, to turn her back to the road."),
    ],
    24: [
        ("וַיַּעֲמֹד מַלְאַךְ יְהוָה בְּמִשְׁעוֹל הַכְּרָמִים",
         "ת'ם וקף מלך אללה. פי זקאק אלכרום",
         "Then the angel of God stood in the narrow lane of the vineyards"),
        ("גָּדֵר מִזֶּה וְגָדֵר מִזֶּה", "והנאך גדאר ימנה ויסרה",
         "with a wall on the right and on the left."),
    ],
    25: [
        ("וַתֵּרֶא הָאָתוֹן אֶת-מַלְאַךְ יְהוָה", "פלמא ראתה",
         "And when she saw him"),
        ("וַתִּלָּחֵץ אֶל-הַקִּיר וַתִּלְחַץ אֶת-רֶגֶל בִּלְעָם אֶל-הַקִּיר",
         "אזדחמת מע אלחאיט. פצ'ג'טת רגל בלעם אלי' אלחאיט",
         "she pressed herself against the wall and crushed Balaam's foot against the wall"),
        ("וַיֹּסֶף לְהַכֹּתָהּ", "פזאד פי צ'רבהא", "so he added to his striking of her."),
    ],
    26: [
        ("וַיּוֹסֶף מַלְאַךְ-יְהוָה עֲבוֹר וַיַּעֲמֹד בְּמָקוֹם צָר",
         "ת'ם עאוד מלך אללה פגאז. ווקף פי מוצ'ע מצ'יק",
         "And the angel of God passed on again, and stood in a narrow place"),
        ("אֲשֶׁר אֵין-דֶּרֶךְ לִנְטוֹת יָמִין וּשְׂמֹאול",
         "מא ליס טריק אן ימיל ענה ימנה ולא יסרה",
         "where there was no way to turn aside from it right or left."),
    ],
    27: [
        ("וַתֵּרֶא הָאָתוֹן אֶת-מַלְאַךְ יְהוָה", "ולמא ראתה",
         "And when she saw him"),
        ("וַתִּרְבַּץ תַּחַת בִּלְעָם", "רבצת תחת בלעם",
         "she lay down beneath Balaam"),
        ("וַיִּחַר-אַף בִּלְעָם וַיַּךְ אֶת-הָאָתוֹן בַּמַּקֵּל",
         "פאשתד ג'צ'ב בלעם. פצ'רבהא באלעצא",
         "and Balaam's anger intensified, and he struck her with the staff."),
    ],
    28: [
        ("וַיִּפְתַּח יְהוָה אֶת-פִּי הָאָתוֹן", "פפתח אללה פאהא",
         "And God opened her mouth"),
        ("וַתֹּאמֶר לְבִלְעָם מֶה-עָשִׂיתִי לְךָ",
         "פקאלת לבלעם מא ד'א צנעת בך",
         "and she said to Balaam: 'What have I done to you"),
        ("כִּי הִכִּיתַנִי זֶה שָׁלֹשׁ רְגָלִים", "אד' צ'רבתני. הד'ה אלמרה אלת'אלת'ה",
         "that you have struck me — this third time?'"),
    ],
    29: [
        ("וַיֹּאמֶר בִּלְעָם לָאָתוֹן כִּי הִתְעַלַּלְתְּ בִּי",
         "קאל. לאנך תמרדת בי",
         "He said: 'Because you have defied me"),
        ("לוּ יֶשׁ-חֶרֶב בְּיָדִי כִּי עַתָּה הֲרַגְתִּיךְ",
         "ולו אן פי ידי סיף לקתלתך",
         "— had I a sword in my hand, I would kill you now.'"),
    ],
    30: [
        ("וַתֹּאמֶר הָאָתוֹן אֶל-בִּלְעָם", "קאלת",
         "She said"),
        ("הֲלוֹא אָנֹכִי אֲתֹנְךָ אֲשֶׁר-רָכַבְתָּ עָלַי מֵעוֹדְךָ עַד-הַיּוֹם הַזֶּה",
         "אלי'ס אנא אתאנך אלד'י רכבתני. מנד' כנת אלי' הד'א אליום",
         "'Am I not your she-donkey on which you have ridden since I came to be until this day"),
        ("הַהַסְכֵּן הִסְכַּנְתִּי לַעֲשׂוֹת לְךָ כֹּה", "הל עוודתך אן אצנע בך כד'א",
         "Have I been accustomed to doing such a thing to you?'"),
        ("וַיֹּאמֶר לֹא", "קאל לא", "He said: 'No.'"),
    ],
    31: [
        ("וַיְגַל יְהוָה אֶת-עֵינֵי בִלְעָם", "ת'ם כשף אללה ען בצר בלעם",
         "Then God uncovered Balaam's sight"),
        ("וַיַּרְא אֶת-מַלְאַךְ יְהוָה נִצָּב בַּדֶּרֶךְ וְחַרְבּוֹ שְׁלֻפָה בְּיָדוֹ",
         "פראא מלך אללה ואקפא פי אלטריק. וסיפה מצלת פי ידה",
         "and he saw the angel of God standing in the road, with his sword drawn in his hand"),
        ("וַיִּקֹּד וַיִּשְׁתַּחוּ לְאַפָּיו", "פכ'ר בין ידיה סאגדא",
         "and he fell down before him prostrating."),
    ],
    32: [
        ("וַיֹּאמֶר אֵלָיו מַלְאַךְ יְהוָה עַל-מָה הִכִּיתָ אֶת-אֲתֹנְךָ זֶה שָׁלוֹשׁ רְגָלִים",
         "פקאל לה מלך אללה. לם צ'רבת אתאנך. הד'ה אלמרה אלת'אלת'ה",
         "And the angel of God said to him: 'Why have you struck your she-donkey this third time?"),
        ("הִנֵּה אָנֹכִי יָצָאתִי לְשָׂטָן", "ואנא כ'רגת אן אחידך",
         "I have come out to turn you aside"),
        ("כִּי-יָרַט הַדֶּרֶךְ לְנֶגְדִּי", "אד' תורטת אלטריק חד'אי",
         "— for the road before me has become an entanglement.'"),
    ],
    33: [
        ("וַתִּרְאַנִי הָאָתוֹן וַתֵּט לְפָנַי זֶה שָׁלֹשׁ רְגָלִים",
         "חתי' ראתני פמאלת עני. הד'ה אלמרה אלת'אלת'ה",
         "Until she saw me and turned aside from me — this third time."),
        ("אוּלַי נָטְתָה מִפָּנַי כִּי עַתָּה גַּם-אֹתְכָה הָרַגְתִּי וְאוֹתָהּ הֶחֱיֵיתִי",
         "פלו לם תמיל עני. לקתלתך אלאן ובקיתהא",
         "Had she not turned aside from me, I would have killed you now and let her live.'"),
    ],
    34: [
        ("וַיֹּאמֶר בִּלְעָם אֶל-מַלְאַךְ יְהוָה חָטָאתִי",
         "קאל לה קד אכ'טית",
         "He said to him: 'I have erred"),
        ("כִּי לֹא יָדַעְתִּי כִּי אַתָּה נִצָּב לִקְרָאתִי בַּדָּרֶךְ",
         "אד' לם אעלם. אנך ואקף תלקאי פי אלטריק",
         "for I did not know that you were standing to meet me in the road"),
        ("וְעַתָּה אִם-רַע בְּעֵינֶיךָ אָשׁוּבָה לִּי",
         "ואלאן פאן סאך מצ'יי רגעת",
         "And now, if my going is displeasing to you, I shall turn back.'"),
    ],
    35: [
        ("וַיֹּאמֶר מַלְאַךְ יְהוָה אֶל-בִּלְעָם לֵךְ עִם-הָאֲנָשִׁים",
         "קאל לה. אמץ' מע אלקום",
         "He said to him: 'Go with the people"),
        ("וְאֶפֶס אֶת-הַדָּבָר אֲשֶׁר-אֲדַבֵּר אֵלֶיךָ אֹתוֹ תְדַבֵּר",
         "ועדא אלקול. אלד'י אקולה לך קולה פקט",
         "— but only the word that I shall tell you, speak that alone.'"),
        ("וַיֵּלֶךְ בִּלְעָם עִם-שָׂרֵי בָלָק", "פמצ'א מעהם",
         "And he went with them."),
    ],
    36: [
        ("וַיִּשְׁמַע בָּלָק כִּי בָא בִלְעָם", "פלמא סמע בלק במגי בלעם",
         "And when Balak heard of the coming of Balaam"),
        ("וַיֵּצֵא לִקְרָאתוֹ אֶל-עִיר מוֹאָב", "כ'רג תלקאה אלי' קריה' מואב",
         "he went out to meet him at the town of Moab"),
        ("אֲשֶׁר עַל-גְּבוּל אַרְנֹן אֲשֶׁר בִּקְצֵה הַגְּבוּל",
         "אלד'י עלי' תכ'ם ארנון. אלד'י פי טרפה",
         "which is on the border of the Arnon, which is at its edge."),
    ],
    37: [
        ("וַיֹּאמֶר בָּלָק אֶל-בִּלְעָם הֲלֹא שָׁלֹחַ שָׁלַחְתִּי אֵלֶיךָ לִקְרֹא-לָךְ",
         "קאל בלק לבלעם. אלי'ס ארסלת אלי'ך מרה קבל הד'ה לאדעוך",
         "Balak said to Balaam: 'Did I not send to you once before this to invite you?"),
        ("לָמָּה לֹא-הָלַכְתָּ אֵלָי", "לם לם תצאל אליי",
         "Why did you not come to me?"),
        ("הַאֻמְנָם לֹא אוּכַל כַּבְּדֶךָ", "אתרא. ליס אקדר אן אכרמך",
         "Do you suppose I am unable to honor you?'"),
    ],
    38: [
        ("וַיֹּאמֶר בִּלְעָם אֶל-בָּלָק הִנֵּה-בָאתִי אֵלֶיךָ",
         "קאל. ואלאן קד צרת אלי'ך",
         "He said: 'And now I have indeed come to you"),
        ("עַתָּה הֲיָכֹל אוּכַל דַּבֵּר מְאוּמָה",
         "אתראני אסתטיע אן אקול שייא",
         "— but do you suppose I am able to say anything"),
        ("הַדָּבָר אֲשֶׁר יָשִׂים אֱלֹהִים בְּפִי--אֹתוֹ אֲדַבֵּר",
         "אלא מא ילקנניה אללה פקט",
         "except only what God will prompt me with?'"),
    ],
    39: [
        ("וַיֵּלֶךְ בִּלְעָם עִם-בָּלָק וַיָּבֹאוּ קִרְיַת חֻצוֹת",
         "ומצ'יא גמיעא. אלי' אן גאא אלי' קריה' חוצות",
         "And the two of them went together, until they came to the town of Hutzoth."),
    ],
    40: [
        ("וַיִּזְבַּח בָּלָק בָּקָר וָצֹאן", "פד'בח בלק בקרא וג'נמא",
         "And Balak slaughtered cattle and sheep"),
        ("וַיְשַׁלַּח לְבִלְעָם וְלַשָּׂרִים אֲשֶׁר אִתּוֹ",
         "ובעת' בד'אלך אלי' בלעם. ואלי' אלרויסא אלד'ין מעה",
         "and sent of that to Balaam and to the officers who were with him."),
    ],
    41: [
        ("וַיְהִי בַבֹּקֶר", "פלמא כאן באלג'דאה", "And it was in the morning"),
        ("וַיִּקַּח בָּלָק אֶת-בִּלְעָם וַיַּעֲלֵהוּ בָּמוֹת בָּעַל",
         "אכ'ד בלק בלעם. פאצעדה אלי' בעץ' ביאע מעבודה",
         "Balak took Balaam and brought him up to some of the high-places of his deity"),
        ("וַיַּרְא מִשָּׁם קְצֵה הָעָם", "פנצ'ר מן ת'ם בעץ' אלקום",
         "and from there he saw a portion of the people."),
    ],
}
