"""Hand-authored alignment triples for Bamidbar chapter 33."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("אֵלֶּה מַסְעֵי בְנֵי-יִשְׂרָאֵל אֲשֶׁר יָצְאוּ מֵאֶרֶץ מִצְרַיִם",
         "והד'א מראחל בני אסראיל. אד' כ'רגו מן בלד מצר",
         "And these are the stages of the sons of Israel when they went out from the land of Egypt"),
        ("לְצִבְאֹתָם בְּיַד-מֹשֶׁה וְאַהֲרֹן",
         "עלי' גיושהם. ביד מוסי' והרון",
         "according to their hosts, by the hand of Moses and Aaron."),
    ],
    2: [
        ("וַיִּכְתֹּב מֹשֶׁה אֶת-מוֹצָאֵיהֶם לְמַסְעֵיהֶם--עַל-פִּי יְהוָה",
         "פכתב מוסי' כ'רוגהם. עלי' מראחלהם עלי' קול אללה",
         "And Moses wrote down their going out, stage by stage, at the word of God."),
        ("וְאֵלֶּה מַסְעֵיהֶם לְמוֹצָאֵיהֶם",
         "והד'א מראחלהם לכ'רוגהם",
         "And these are their stages of their going out."),
    ],
    3: [
        ("וַיִּסְעוּ מֵרַעְמְסֵס בַּחֹדֶשׁ הָרִאשׁוֹן בַּחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הָרִאשׁוֹן",
         "ורחלו מן עין שמס פי אלשהר אלאוול. פי אליום אלכ'אמס עשר",
         "And they set out from Ein Shams (Raamses) in the first month, on the fifteenth day"),
        ("מִמָּחֳרַת הַפֶּסַח יָצְאוּ בְנֵי-יִשְׂרָאֵל בְּיָד רָמָה",
         "וד'אלך מן ג'ד אלפסח. כ'רגו בני אסראיל ביד רפיעה",
         "that being the day after the Passover. The sons of Israel went out with a raised hand"),
        ("לְעֵינֵי כָּל-מִצְרָיִם",
         "בחצ'רה' גמיע אלמצריון",
         "in the presence of all the Egyptians,"),
    ],
    4: [
        ("וּמִצְרַיִם מְקַבְּרִים אֵת אֲשֶׁר הִכָּה יְהוָה בָּהֶם--כָּל-בְּכוֹר",
         "והם ידפנון. אלד'י קתל אללה פיהם כל בכר",
         "while they were burying those whom God had slain among them — every firstborn"),
        ("וּבֵאלֹהֵיהֶם עָשָׂה יְהוָה שְׁפָטִים",
         "וצנע אחכאמא במעבודאתהם",
         "and He had executed judgments upon their deities."),
    ],
    5: [
        ("וַיִּסְעוּ בְנֵי-יִשְׂרָאֵל מֵרַעְמְסֵס וַיַּחֲנוּ בְּסֻכֹּת",
         "ורחלו בני אסראיל מן עין שמס. ונזלו פי סכות",
         "And the sons of Israel set out from Ein Shams and encamped at Sukkoth."),
    ],
    6: [
        ("וַיִּסְעוּ מִסֻּכֹּת וַיַּחֲנוּ בְאֵתָם אֲשֶׁר בִּקְצֵה הַמִּדְבָּר",
         "ורחלו מן ת'ם. ונזלו פי איתם. פי טרף אלברייה",
         "And they set out from Sukkoth and encamped at Etham, at the edge of the wilderness."),
    ],
    7: [
        ("וַיִּסְעוּ מֵאֵתָם וַיָּשָׁב עַל-פִּי הַחִירֹת אֲשֶׁר עַל-פְּנֵי בַּעַל צְפוֹן",
         "ורחלו מנהא. ורגעו אלי' פואה' אלחירות. אלתי בחצ'רה' בעל צפון",
         "And they set out from Etham and turned back to the mouth of the Hiroth, which is before Baal-Zephon"),
        ("וַיַּחֲנוּ לִפְנֵי מִגְדֹּל",
         "ונזלו בין ידי מגדול",
         "and they encamped before Migdol."),
    ],
    8: [
        ("וַיִּסְעוּ מִפְּנֵי הַחִירֹת וַיַּעַבְרוּ בְתוֹךְ-הַיָּם הַמִּדְבָּרָה",
         "ורחלו מן ת'ם. ועברו פי וסט אלבחר פי אלברייה",
         "And they set out from the mouth of the Hiroth and crossed through the midst of the sea into the wilderness"),
        ("וַיֵּלְכוּ דֶּרֶךְ שְׁלֹשֶׁת יָמִים בְּמִדְבַּר אֵתָם וַיַּחֲנוּ בְּמָרָה",
         "ת'ם סארו. מסאפה' ת'לאת'ה' אייאם פי ברייה' איתם. ונזלו פי אלמרירה",
         "then they traveled a distance of three days in the wilderness of Etham, and encamped at the Bitterness."),
    ],
    9: [
        ("וַיִּסְעוּ מִמָּרָה וַיָּבֹאוּ אֵילִמָה",
         "ורחלו מנהא. וגאו אלי' אילים",
         "And they set out from the Bitterness and came to Elim"),
        ("וּבְאֵילִם שְׁתֵּים עֶשְׂרֵה עֵינֹת מַיִם וְשִׁבְעִים תְּמָרִים--וַיַּחֲנוּ-שָׁם",
         "וכאן פיהא. את'ני עשר עין מא. וסבעין נכ'לה פנזלו הנאך",
         "and in it were twelve springs of water and seventy palm-trees — and they encamped there."),
    ],
    10: [
        ("וַיִּסְעוּ מֵאֵילִם וַיַּחֲנוּ עַל-יַם-סוּף",
         "ורחלו מנהא. ונזלו עלי' בחר אלקלזם",
         "And they set out from Elim and encamped by the Sea of Qulzum (Red Sea)."),
    ],
    11: [
        ("וַיִּסְעוּ מִיַּם-סוּף וַיַּחֲנוּ בְּמִדְבַּר-סִין",
         "ורחלו מנהא. ונזלו פי ברייה' סין",
         "And they set out from the Sea of Qulzum and encamped in the wilderness of Sin."),
    ],
    12: [
        ("וַיִּסְעוּ מִמִּדְבַּר-סִין וַיַּחֲנוּ בְּדָפְקָה",
         "פרחלו מנהא. ונזלו פי דפקה",
         "And they set out from the wilderness of Sin and encamped at Dophkah."),
    ],
    13: [
        ("וַיִּסְעוּ מִדָּפְקָה וַיַּחֲנוּ בְּאָלוּשׁ",
         "ורחלו מנהא. ונזלו פי אלוש",
         "And they set out from Dophkah and encamped at Alush."),
    ],
    14: [
        ("וַיִּסְעוּ מֵאָלוּשׁ וַיַּחֲנוּ בִּרְפִידִם",
         "ורחלו מנהא. ונזלו פי רפידים",
         "And they set out from Alush and encamped at Rephidim"),
        ("וְלֹא-הָיָה שָׁם מַיִם לָעָם לִשְׁתּוֹת",
         "ולם יכון ת'ם מאא. לאלקום ישרבונה",
         "and there was no water there for the people to drink."),
    ],
    15: [
        ("וַיִּסְעוּ מֵרְפִידִם וַיַּחֲנוּ בְּמִדְבַּר סִינָי",
         "ורחלו מנהא. ונזלו פי ברייה' סיני",
         "And they set out from Rephidim and encamped in the wilderness of Sinai."),
    ],
    16: [
        ("וַיִּסְעוּ מִמִּדְבַּר סִינָי וַיַּחֲנוּ בְּקִבְרֹת הַתַּאֲוָה",
         "ורחלו מנהא. ונזלו פי קבור אלמתשהיין",
         "And they set out from the wilderness of Sinai and encamped at the Graves of the Desirous."),
    ],
    17: [
        ("וַיִּסְעוּ מִקִּבְרֹת הַתַּאֲוָה וַיַּחֲנוּ בַּחֲצֵרֹת",
         "ורחלו מנהא. ונזלו פי חצרות",
         "And they set out from the Graves of the Desirous and encamped at Hazeroth."),
    ],
    18: [
        ("וַיִּסְעוּ מֵחֲצֵרֹת וַיַּחֲנוּ בְּרִתְמָה",
         "ורחלו מנהא. ונזלו פי רתמה",
         "And they set out from Hazeroth and encamped at Rithmah."),
    ],
    19: [
        ("וַיִּסְעוּ מֵרִתְמָה וַיַּחֲנוּ בְּרִמֹּן פָּרֶץ",
         "ורחלו מנהא. ונזלו פי רמון פרץ",
         "And they set out from Rithmah and encamped at Rimmon-Perez."),
    ],
    20: [
        ("וַיִּסְעוּ מֵרִמֹּן פָּרֶץ וַיַּחֲנוּ בְּלִבְנָה",
         "ורחלו מנהא. ונזלו פי לבנה",
         "And they set out from Rimmon-Perez and encamped at Libnah."),
    ],
    21: [
        ("וַיִּסְעוּ מִלִּבְנָה וַיַּחֲנוּ בְּרִסָּה",
         "ורחלו מנהא. ונזלו פי רסה",
         "And they set out from Libnah and encamped at Rissah."),
    ],
    22: [
        ("וַיִּסְעוּ מֵרִסָּה וַיַּחֲנוּ בִּקְהֵלָתָה",
         "ורחלו מנהא. ונזלו פי קהלת",
         "And they set out from Rissah and encamped at Kehelath."),
    ],
    23: [
        ("וַיִּסְעוּ מִקְּהֵלָתָה וַיַּחֲנוּ בְּהַר-שָׁפֶר",
         "ורחלו מנהא. ונזלו פי גבל שפר",
         "And they set out from Kehelath and encamped at Mount Shepher."),
    ],
    24: [
        ("וַיִּסְעוּ מֵהַר-שָׁפֶר וַיַּחֲנוּ בַּחֲרָדָה",
         "ורחלו מנהא. ונזלו פי חרדה",
         "And they set out from Mount Shepher and encamped at Haradah."),
    ],
    25: [
        ("וַיִּסְעוּ מֵחֲרָדָה וַיַּחֲנוּ בְּמַקְהֵלֹת",
         "ורחלו מנהא. ונזלו פי מקהלות",
         "And they set out from Haradah and encamped at Makheloth."),
    ],
    26: [
        ("וַיִּסְעוּ מִמַּקְהֵלֹת וַיַּחֲנוּ בְּתָחַת",
         "ורחלו מנהא. ונזלו פי תחת",
         "And they set out from Makheloth and encamped at Tahath."),
    ],
    27: [
        ("וַיִּסְעוּ מִתָּחַת וַיַּחֲנוּ בְּתָרַח",
         "ורחלו מנהא. ונזלו פי תרח",
         "And they set out from Tahath and encamped at Terah."),
    ],
    28: [
        ("וַיִּסְעוּ מִתָּרַח וַיַּחֲנוּ בְּמִתְקָה",
         "ורחלו מנהא. ונזלו פי מתקה",
         "And they set out from Terah and encamped at Mithkah."),
    ],
    29: [
        ("וַיִּסְעוּ מִמִּתְקָה וַיַּחֲנוּ בְּחַשְׁמֹנָה",
         "ורחלו מנהא. ונזלו פי חשמונה",
         "And they set out from Mithkah and encamped at Hashmonah."),
    ],
    30: [
        ("וַיִּסְעוּ מֵחַשְׁמֹנָה וַיַּחֲנוּ בְּמֹסֵרוֹת",
         "ורחלו מנהא. ונזלו פי מוסרות",
         "And they set out from Hashmonah and encamped at Moseroth."),
    ],
    31: [
        ("וַיִּסְעוּ מִמֹּסֵרוֹת וַיַּחֲנוּ בִּבְנֵי יַעֲקָן",
         "ורחלו מנהא. ונזלו פי בני יעקן",
         "And they set out from Moseroth and encamped at Bene-Yaakan."),
    ],
    32: [
        ("וַיִּסְעוּ מִבְּנֵי יַעֲקָן וַיַּחֲנוּ בְּחֹר הַגִּדְגָּד",
         "ורחלו מנהא. ונזלו פי חור גדגד",
         "And they set out from Bene-Yaakan and encamped at Hor-Haggidgad."),
    ],
    33: [
        ("וַיִּסְעוּ מֵחֹר הַגִּדְגָּד וַיַּחֲנוּ בְּיָטְבָתָה",
         "ורחלו מנהא. ונזלו פי יטבתא",
         "And they set out from Hor-Haggidgad and encamped at Yotbathah."),
    ],
    34: [
        ("וַיִּסְעוּ מִיָּטְבָתָה וַיַּחֲנוּ בְּעַבְרֹנָה",
         "ורחלו מנהא. ונזלו פי עברונה",
         "And they set out from Yotbathah and encamped at Abronah."),
    ],
    35: [
        ("וַיִּסְעוּ מֵעַבְרֹנָה וַיַּחֲנוּ בְּעֶצְיֹן גָּבֶר",
         "ורחלו מנהא. ונזלו פי עציון גבר",
         "And they set out from Abronah and encamped at Ezion-Gaber."),
    ],
    36: [
        ("וַיִּסְעוּ מֵעֶצְיֹן גָּבֶר וַיַּחֲנוּ בְמִדְבַּר-צִן הִוא קָדֵשׁ",
         "ורחלו מנהא. ונזלו פי ברייה' צין הי רקים",
         "And they set out from Ezion-Gaber and encamped in the wilderness of Zin — that is Reqem."),
    ],
    37: [
        ("וַיִּסְעוּ מִקָּדֵשׁ וַיַּחֲנוּ בְּהֹר הָהָר בִּקְצֵה אֶרֶץ אֱדוֹם",
         "ורחלו מנהא. ונזלו פי גבל הור. פי טרף בלד אדום",
         "And they set out from Reqem and encamped at Mount Hor, at the edge of the land of Edom."),
    ],
    38: [
        ("וַיַּעַל אַהֲרֹן הַכֹּהֵן אֶל-הֹר הָהָר עַל-פִּי יְהוָה--וַיָּמָת שָׁם",
         "פצעד הרון אלאמאם. אלי' גבל הור. ומאת ת'ם באמר אללה",
         "And Aaron the imām ascended to Mount Hor, and died there at the command of God"),
        ("בִּשְׁנַת הָאַרְבָּעִים לְצֵאת בְּנֵי-יִשְׂרָאֵל מֵאֶרֶץ מִצְרַיִם",
         "פי סנה' אלארבעין. לכ'רוג בני אסראיל מן בלד מצר",
         "in the fortieth year of the going out of the sons of Israel from the land of Egypt"),
        ("בַּחֹדֶשׁ הַחֲמִישִׁי בְּאֶחָד לַחֹדֶשׁ",
         "פי אליום אלאוול מן אלשהר אלכ'אמס",
         "on the first day of the fifth month."),
    ],
    39: [
        ("וְאַהֲרֹן בֶּן-שָׁלֹשׁ וְעֶשְׂרִים וּמְאַת שָׁנָה בְּמֹתוֹ בְּהֹר הָהָר",
         "וכאן להרון. מאיה ות'לאת'ה ועשרין סנה. למא מאת הנאך",
         "And Aaron was a hundred and twenty-three years old when he died there."),
    ],
    40: [
        ("וַיִּשְׁמַע הַכְּנַעֲנִי מֶלֶךְ עֲרָד וְהוּא-יֹשֵׁב בַּנֶּגֶב בְּאֶרֶץ כְּנָעַן--בְּבֹא בְּנֵי יִשְׂרָאֵל",
         "ת'ם סמע אלכנאעני מלך ערד. והו סאכן פי אלדארום פי בלד כנעאן במגי בני אסראיל",
         "Then the Canaanite, the king of Arad — who was dwelling in the south in the land of Canaan — heard of the coming of the sons of Israel."),
    ],
    41: [
        ("וַיִּסְעוּ מֵהֹר הָהָר וַיַּחֲנוּ בְּצַלְמֹנָה",
         "ת'ם רחלו מן גבל הור. ונזלו פי צלמונה",
         "Then they set out from Mount Hor and encamped at Zalmonah."),
    ],
    42: [
        ("וַיִּסְעוּ מִצַּלְמֹנָה וַיַּחֲנוּ בְּפוּנֹן",
         "ורחלו מנהא. ונזלו פי פונון",
         "And they set out from Zalmonah and encamped at Punon."),
    ],
    43: [
        ("וַיִּסְעוּ מִפּוּנֹן וַיַּחֲנוּ בְּאֹבֹת",
         "ורחלו מנהא. ונזלו פי אובות",
         "And they set out from Punon and encamped at Oboth."),
    ],
    44: [
        ("וַיִּסְעוּ מֵאֹבֹת וַיַּחֲנוּ בְּעִיֵּי הָעֲבָרִים בִּגְבוּל מוֹאָב",
         "ורחלו מנהא. ונזלו פי עיי אלמגאז. פי תכ'ם מואב",
         "And they set out from Oboth and encamped at Iye ha-Maʿaz, on the border of Moab."),
    ],
    45: [
        ("וַיִּסְעוּ מֵעִיִּים וַיַּחֲנוּ בְּדִיבֹן גָּד",
         "ורחלו מנהא. ונזלו פי דיבון גד",
         "And they set out from Iye ha-Maʿaz and encamped at Dibon-Gad."),
    ],
    46: [
        ("וַיִּסְעוּ מִדִּיבֹן גָּד וַיַּחֲנוּ בְּעַלְמֹן דִּבְלָתָיְמָה",
         "ורחלו מנהא. ונזלו פי עלמון דבלתים",
         "And they set out from Dibon-Gad and encamped at Almon-Diblathaimah."),
    ],
    47: [
        ("וַיִּסְעוּ מֵעַלְמֹן דִּבְלָתָיְמָה וַיַּחֲנוּ בְּהָרֵי הָעֲבָרִים לִפְנֵי נְבוֹ",
         "ורחלו מנהא. ונזלו פי גבאל אלעבריין. בין ידי נבו",
         "And they set out from Almon-Diblathaimah and encamped at the mountains of the Hebrews, before Nebo."),
    ],
    48: [
        ("וַיִּסְעוּ מֵהָרֵי הָעֲבָרִים וַיַּחֲנוּ בְּעַרְבֹת מוֹאָב עַל יַרְדֵּן יְרֵחוֹ",
         "ורחלו מנהא. ונזלו פי בידאת מואב. עלי' ארדן יריחא",
         "And they set out from the mountains of the Hebrews and encamped in the open country of Moab, by the Jordan of Jericho."),
    ],
    49: [
        ("וַיַּחֲנוּ עַל-הַיַּרְדֵּן מִבֵּית הַיְשִׁמֹת עַד אָבֵל הַשִּׁטִּים בְּעַרְבֹת מוֹאָב",
         "פנזלו עלי' אלארדן מן בית ישימות. אלי' מרג שטין. וד'אלך פי בידאת מואב",
         "And they encamped by the Jordan, from Beth-Jeshimoth to the meadow of the Acacias — that being in the open country of Moab."),
    ],
    50: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְּעַרְבֹת מוֹאָב עַל-יַרְדֵּן יְרֵחוֹ לֵאמֹר",
         "פכלם אללה מוסי' פי בידאת מואב. עלי' ארדן יריחא תכלימא",
         "And God spoke to Moses in the open country of Moab, by the Jordan of Jericho directly."),
    ],
    51: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל וקל להם",
         "Command the sons of Israel and say to them:"),
        ("כִּי אַתֶּם עֹבְרִים אֶת-הַיַּרְדֵּן אֶל-אֶרֶץ כְּנָעַן",
         "אנכם גאיזין אלארדן אלי' בלד כנעאן",
         "You are crossing the Jordan into the land of Canaan."),
    ],
    52: [
        ("וְהוֹרַשְׁתֶּם אֶת-כָּל-יֹשְׁבֵי הָאָרֶץ מִפְּנֵיכֶם",
         "פאקרצ'ו גמיע אהל אלבלד מן בין ידיכם",
         "And drive out all the inhabitants of the land from before you"),
        ("וְאִבַּדְתֶּם אֵת כָּל-מַשְׂכִּיֹּתָם וְאֵת כָּל-צַלְמֵי מַסֵּכֹתָם תְּאַבֵּדוּ",
         "ואבידו גמיע מזכ'רפאתהם. ואצנאם מסבוכאתהם",
         "and destroy all their ornaments and their graven idols"),
        ("וְאֵת כָּל-בָּמוֹתָם תַּשְׁמִידוּ",
         "וביעהם תנפד'ון",
         "and their temples of worship you shall demolish."),
    ],
    53: [
        ("וְהוֹרַשְׁתֶּם אֶת-הָאָרֶץ וִישַׁבְתֶּם-בָּהּ",
         "פאד'א קרצ'תמוהם אסכנו אלבלד",
         "And when you have driven them out, settle the land"),
        ("כִּי לָכֶם נָתַתִּי אֶת-הָאָרֶץ לָרֶשֶׁת אֹתָהּ",
         "פקד אעטיתכם אייאה לתחוזוהו",
         "for I have given it to you that you may possess it."),
    ],
    54: [
        ("וְהִתְנַחַלְתֶּם אֶת-הָאָרֶץ בְּגוֹרָל לְמִשְׁפְּחֹתֵיכֶם",
         "ותווזעוה באסהם לעשאירכם",
         "And you shall apportion it by equal shares among your clans"),
        ("לָרַב תַּרְבּוּ אֶת-נַחֲלָתוֹ וְלַמְעַט תַּמְעִיט אֶת-נַחֲלָתוֹ",
         "לאלכת'יר כת'רו נחלתה ולאלקליל קללוהא",
         "for the numerous enlarge his portion, and for the few reduce it."),
        ("אֶל אֲשֶׁר-יֵצֵא לוֹ שָׁמָּה הַגּוֹרָל לוֹ יִהְיֶה לְמַטּוֹת אֲבֹתֵיכֶם תִּתְנֶחָלוּ",
         "מן כ'רג לה אלסהם פי אי מוצ'ע כאן לה. ועלי' אסבאט אבאיכם תתוזעונה",
         "To whomever his share falls, in whatever place it may be, that shall be his; according to the tribes of your fathers you shall apportion it."),
    ],
    55: [
        ("וְאִם-לֹא תוֹרִישׁוּ אֶת-יֹשְׁבֵי הָאָרֶץ מִפְּנֵיכֶם",
         "ואן לם תקרצ'ו אהל אלבלד מן בין ידיכם",
         "But if you do not drive out the inhabitants of the land from before you"),
        ("וְהָיָה אֲשֶׁר תּוֹתִירוּ מֵהֶם לְשִׂכִּים בְּעֵינֵיכֶם וְלִצְנִינִם בְּצִדֵּיכֶם",
         "פיציר מא תבקונה מנהם. כאבר פי עיונכם. וכמסאל פי גנובכם",
         "then whatever you leave of them shall become like fine needles in your eyes and like thick thorns in your sides"),
        ("וְצָרְרוּ אֶתְכֶם--עַל-הָאָרֶץ אֲשֶׁר אַתֶּם יֹשְׁבִים בָּהּ",
         "ויצ'איקונכם פי אלבלד. אלד'י אנתם מקימין פיה",
         "and they shall press hard upon you in the land in which you are settled."),
    ],
    56: [
        ("וְהָיָה כַּאֲשֶׁר דִּמִּיתִי לַעֲשׂוֹת לָהֶם--אֶעֱשֶׂה לָכֶם",
         "פאכון כמא קצדת. אן אצנע בהם אצנע בכם",
         "And it shall be: just as I intended to do to them, so shall I do to you."),
    ],
}
