"""Hand-authored alignment triples for Bamidbar chapter 10."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("עֲשֵׂה לְךָ שְׁתֵּי חֲצוֹצְרֹת כֶּסֶף--מִקְשָׁה תַּעֲשֶׂה אֹתָם",
         "אצנע לך בוקין מן פצה מצמתה",
         "'Make for yourself two trumpets of solid silver"),
        ("וְהָיוּ לְךָ לְמִקְרָא הָעֵדָה וּלְמַסַּע אֶת-הַמַּחֲנוֹת",
         "יכונאן לך לדעוה' אלגמאעה ותרחיל אלעסאכר",
         "they shall be for you for summoning the assembly and for setting out the camp.'"),
    ],
    3: [
        ("וְתָקְעוּ בָּהֵן--וְנוֹעֲדוּ אֵלֶיךָ כָּל-הָעֵדָה",
         "פאן צרב בהמא. אגתמע אליך כל אלגמאעה",
         "'And if both are sounded, all the assembly shall gather to you"),
        ("אֶל-פֶּתַח אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר",
         "at the entrance of the tent of the assembly.'"),
    ],
    4: [
        ("וְאִם-בְּאַחַת יִתְקָעוּ--וְנוֹעֲדוּ אֵלֶיךָ הַנְּשִׂיאִים",
         "ואן צרב באחדהמא אגתמע אליך אלאשראף",
         "'And if one of them is sounded, the nobles shall gather to you"),
        ("רָאשֵׁי אַלְפֵי יִשְׂרָאֵל", "רויסא אלוף בני אסראיל",
         "the heads of the thousands of the sons of Israel.'"),
    ],
    5: [
        ("וּתְקַעְתֶּם תְּרוּעָה--וְנָסְעוּ הַמַּחֲנוֹת הַחֹנִים קֵדְמָה",
         "ואנפכ'ו נפכ'א מגלבא. ירחל בהא אלעסאכר. אלנאזלין פי אלמשרק",
         "'And blow a rousing blast, and the camp encamped in the east shall set out by it.'"),
    ],
    6: [
        ("וּתְקַעְתֶּם תְּרוּעָה שֵׁנִית--וְנָסְעוּ הַמַּחֲנוֹת הַחֹנִים תֵּימָנָה",
         "ואנפכ'ו נפכ'א מגלבא ת'אניא. ירחל בהא אלעסאכר. אלנאזלין פי אלגנוב",
         "'And blow a rousing blast a second time, and the camp encamped in the south shall set out by it"),
        ("תְּרוּעָה יִתְקְעוּ לְמַסְעֵיהֶם", "כד'אך ינפכ'ו נפכ'א לרחילהם",
         "thus shall they blow a blast for their setting out.'"),
    ],
    7: [
        ("וּבְהַקְהִיל אֶת-הַקָּהָל--תִּתְקְעוּ וְלֹא תָרִיעוּ",
         "ופי תגויק אלגוק. אנפכ'ו נפכ'א ולא תגלבו",
         "'And when the congregation assembles, blow a steady blast and do not rouse.'"),
    ],
    8: [
        ("וּבְנֵי אַהֲרֹן הַכֹּהֲנִים יִתְקְעוּ בַּחֲצֹצְרוֹת",
         "ובני הרון אלאימה. יצ'רבו באלאבואק",
         "'And the sons of Aaron, the imāms, shall sound the trumpets"),
        ("וְהָיוּ לָכֶם לְחֻקַּת עוֹלָם לְדֹרֹתֵיכֶם",
         "ויכון לכם ד'אלך. רסם אלדהר לאגיאלכם",
         "and that shall be for you an ordinance forever throughout your generations.'"),
    ],
    9: [
        ("וְכִי-תָבֹאוּ מִלְחָמָה בְּאַרְצְכֶם עַל-הַצַּר הַצֹּרֵר אֶתְכֶם",
         "ואד'א צרתם אלי' חרב פי בלדכם. מע אלעדו אלמעאדיכם",
         "'And when you go to war in your land against the enemy who opposes you"),
        ("וַהֲרֵעֹתֶם בַּחֲצֹצְרֹת", "פגלבו באלאבואק",
         "sound a rousing blast on the trumpets"),
        ("וְנִזְכַּרְתֶּם לִפְנֵי יְהוָה אֱלֹהֵיכֶם וְנוֹשַׁעְתֶּם מֵאֹיְבֵיכֶם",
         "פאד'א בווקתם בין ידי אללה רבכם. תג'אתון מן אעדאיכם",
         "and when you trumpet before God your Lord, you shall be aided against your enemies.'"),
    ],
    10: [
        ("וּבְיוֹם שִׂמְחַתְכֶם וּבְמוֹעֲדֵיכֶם וּבְרָאשֵׁי חָדְשֵׁיכֶם",
         "ופי יום פרחכם ואעיאדכם ורוס שהורכם",
         "'And on the day of your rejoicing, and at your festivals, and at your new months"),
        ("וּתְקַעְתֶּם בַּחֲצֹצְרֹת עַל עֹלֹתֵיכֶם וְעַל זִבְחֵי שַׁלְמֵיכֶם",
         "פאצ'רבו באלאבואק. עלי' צואעדכם. ודבאיח סלאמתכם",
         "sound the trumpets over your ascent-offerings and your peace-offerings"),
        ("וְהָיוּ לָכֶם לְזִכָּרוֹן לִפְנֵי אֱלֹהֵיכֶם",
         "פתכון לכם ד'כרא בין ידי רבכם",
         "and it shall be a remembrance for you before God your Lord."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם", "אנא אללה רבכם אמרת בד'אלך",
         "I am God your Lord — I have commanded this.'"),
    ],
    11: [
        ("וַיְהִי בַּשָּׁנָה הַשֵּׁנִית בַּחֹדֶשׁ הַשֵּׁנִי--בְּעֶשְׂרִים בַּחֹדֶשׁ",
         "פלמא כאן פי אלשהר אלת'אני. מן אלסנה אלת'אניה פי עשרין מנה",
         "And it was in the second month of the second year, on the twentieth of it"),
        ("נַעֲלָה הֶעָנָן מֵעַל מִשְׁכַּן הָעֵדֻת", "ארתפע אלג'מאם. ען מסכן אלשהאדה",
         "that the cloud rose from the tabernacle of the testimony."),
    ],
    12: [
        ("וַיִּסְעוּ בְנֵי-יִשְׂרָאֵל לְמַסְעֵיהֶם מִמִּדְבַּר סִינָי",
         "פרחל בני אסראיל עלי' מראחלהם מן ברייה' סיני",
         "And the sons of Israel set out on their journeys from the wilderness of Sinai"),
        ("וַיִּשְׁכֹּן הֶעָנָן בְּמִדְבַּר פָּארָן", "פסכן אלג'מאם פי ברייה' פארן",
         "and the cloud settled in the wilderness of Paran."),
    ],
    13: [
        ("וַיִּסְעוּ בָּרִאשֹׁנָה עַל-פִּי יְהוָה בְּיַד-מֹשֶׁה",
         "פכאן אוול רחילהם. עלי' קול אללה ביד מוסי'",
         "And the first of their setting out was by the command of God, by the hand of Moses."),
    ],
    14: [
        ("וַיִּסַּע דֶּגֶל מַחֲנֵה בְנֵי-יְהוּדָה בָּרִאשֹׁנָה--לְצִבְאֹתָם",
         "באן רחל מרכז עסכר בני יהודה. עלי' אלמקדמה לגיושהם",
         "Then the division of the camp of the sons of Judah set out at the head, by their hosts"),
        ("וְעַל-צְבָאוֹ--נַחְשׁוֹן בֶּן-עַמִּינָדָב", "ועלי' גישה נחשון אבן עמינדב",
         "and over his host was Nahshon son of Amminadab."),
    ],
    15: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי יִשָּׂשכָר נְתַנְאֵל בֶּן-צוּעָר",
         "ועלי' גיש סבט יששכר. נתנאל אבן צוער",
         "And over the host of the tribe of Issachar was Nethanel son of Zuar."),
    ],
    16: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי זְבוּלֻן אֱלִיאָב בֶּן-חֵלֹן",
         "ועלי' גיש סבט זבולון. אליאב אבן חלון",
         "And over the host of the tribe of Zebulun was Eliab son of Helon."),
    ],
    17: [
        ("וְהוּרַד הַמִּשְׁכָּן וְנָסְעוּ בְנֵי-גֵרְשׁוֹן וּבְנֵי מְרָרִי נֹשְׂאֵי הַמִּשְׁכָּן",
         "ת'ם פצל אלמסכן. פרחל בני גרשון ובני מררי. חאמלוה",
         "Then the tabernacle was taken apart, and the sons of Gershon and the sons of Merari set out, carrying it."),
    ],
    18: [
        ("וְנָסַע דֶּגֶל מַחֲנֵה רְאוּבֵן--לְצִבְאֹתָם", "ת'ם רחל מרכז עסכר ראובן לגיושהם",
         "Then the division of the camp of Reuben set out by their hosts"),
        ("וְעַל-צְבָאוֹ--אֱלִיצוּר בֶּן-שְׁדֵיאוּר", "ועלי' גישה. אליצור אבן שדאור",
         "and over his host was Elizur son of Shedeur."),
    ],
    19: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי שִׁמְעוֹן שְׁלֻמִיאֵל בֶּן-צוּרִישַׁדָּי",
         "ועלי' גיש סבט שמעון. שלומיאל אבן צורישדי",
         "And over the host of the tribe of Simeon was Shelumiel son of Zurishaddai."),
    ],
    20: [
        ("וְעַל-צְבָא מַטֵּה בְנֵי-גָד אֶלְיָסָף בֶּן-דְּעוּאֵל",
         "ועלי' גיש סבט גד. אליסף אבן דעואל",
         "And over the host of the tribe of Gad was Eliasaph son of Deuel."),
    ],
    21: [
        ("וְנָסְעוּ הַקְּהָתִים נֹשְׂאֵי הַמִּקְדָּשׁ", "ת'ם רחל אלקהתיין. חאמלי אלמקדס",
         "Then the Kohathites set out, carrying the sanctuary"),
        ("וְהֵקִימוּ אֶת-הַמִּשְׁכָּן עַד-בֹּאָם", "וקד נצב אלמסכן אלי' מגייהם",
         "and the tabernacle was erected before their arrival."),
    ],
    22: [
        ("וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי-אֶפְרַיִם--לְצִבְאֹתָם",
         "ת'ם רחל מרכז עסכר אפרים לגיושהם",
         "Then the division of the camp of Ephraim set out by their hosts"),
        ("וְעַל-צְבָאוֹ--אֱלִישָׁמָע בֶּן-עַמִּיהוּד", "ועלי' גישה. אלישמע אבן עמיהוד",
         "and over his host was Elishama son of Ammihud."),
    ],
    23: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי מְנַשֶּׁה גַּמְלִיאֵל בֶּן-פְּדָהצוּר",
         "ועלי' גיש סבט מנשה. גמליאל אבן פדהצור",
         "And over the host of the tribe of Manasseh was Gamliel son of Pedahzur."),
    ],
    24: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי בִנְיָמִן אֲבִידָן בֶּן-גִּדְעוֹנִי",
         "ועלי' גיש סבט בנימן. אבידן אבן גדעוני",
         "And over the host of the tribe of Benjamin was Abidan son of Gideoni."),
    ],
    25: [
        ("וְנָסַע דֶּגֶל מַחֲנֵה בְנֵי-דָן--מְאַסֵּף לְכָל-הַמַּחֲנֹת לְצִבְאֹתָם",
         "ת'ם רחל מרכז עסכר בני דן. עלי' סאקה' סאיר אלעסאכר לגיושהם",
         "Then the division of the camp of the sons of Dan set out, at the rear of all the camp, by their hosts"),
        ("וְעַל-צְבָאוֹ--אֲחִיעֶזֶר בֶּן-עַמִּישַׁדָּי", "ועלי' גישה. אחיעזר אבן עמישדי",
         "and over his host was Ahiezer son of Ammishaddai."),
    ],
    26: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי אָשֵׁר פַּגְעִיאֵל בֶּן-עָכְרָן",
         "ועלי' גיש סבט אשר. פגעיאל אבן עכרן",
         "And over the host of the tribe of Asher was Pagiel son of Ochran."),
    ],
    27: [
        ("וְעַל-צְבָא--מַטֵּה בְּנֵי נַפְתָּלִי אֲחִירַע בֶּן-עֵינָן",
         "ועלי' גיש סבט נפתלי. אחירע אבן עינן",
         "And over the host of the tribe of Naphtali was Ahira son of Enan."),
    ],
    28: [
        ("אֵלֶּה מַסְעֵי בְנֵי-יִשְׂרָאֵל לְצִבְאֹתָם", "הד'ה מראחל בני אסראיל לגיושהם",
         "These are the journeys of the sons of Israel by their hosts"),
        ("וַיִּסָּעוּ", "פלמא רחלו", "whenever they set out."),
    ],
    29: [
        ("וַיֹּאמֶר מֹשֶׁה לְחֹבָב בֶּן-רְעוּאֵל הַמִּדְיָנִי חֹתֵן מֹשֶׁה",
         "קאל מוסי'. לחובב. אבן רעואל אלמדיאני חמוה",
         "Moses said to Hobab son of Reuel the Midianite, his father-in-law"),
        ("נֹסְעִים אֲנַחְנוּ אֶל-הַמָּקוֹם אֲשֶׁר אָמַר יְהוָה אֹתוֹ אֶתֵּן לָכֶם",
         "אנא ראחלין. אלי' אלמוצ'ע אלד'י קאל אללה. אייאהא אעטיכם",
         "'We are setting out to the place which God has said — that very one I will give to you."),
        ("לְכָה אִתָּנוּ וְהֵטַבְנוּ לָךְ", "תעאל מענא ונחסן אליך",
         "Come with us and we will deal well with you"),
        ("כִּי-יְהוָה דִּבֶּר-טוֹב עַל-יִשְׂרָאֵל", "לאן אללה קד ועד אל אסראיל בכ'יר",
         "for God has promised the house of Israel with good.'"),
    ],
    30: [
        ("וַיֹּאמֶר אֵלָיו לֹא אֵלֵךְ כִּי אִם-אֶל-אַרְצִי וְאֶל-מוֹלַדְתִּי אֵלֵךְ",
         "קאל לא אמצ'י. אלא אלי' ארצ'י ומולדי",
         "He said: 'I will not go, but only to my own land and my birthplace.'"),
    ],
    31: [
        ("וַיֹּאמֶר אַל-נָא תַּעֲזֹב אֹתָנוּ", "קאל יא הד'א לא תתרכנא",
         "He said: 'O good man, do not leave us"),
        ("כִּי עַל-כֵּן יָדַעְתָּ חֲנֹתֵנוּ בַּמִּדְבָּר", "פאנך תעלם. אן פי טול מקאמנא פי אלבר",
         "for you know that throughout the length of our sojourn in the open country"),
        ("וְהָיִיתָ לָּנוּ לְעֵינָיִם", "כנת לנא כאבצארנא",
         "you have been for us as our eyesight.'"),
    ],
    32: [
        ("וְהָיָה כִּי-תֵלֵךְ עִמָּנוּ", "פאן סרת מענא",
         "'And if you journey with us"),
        ("וְהָיָה הַטּוֹב הַהוּא אֲשֶׁר יֵיטִיב יְהוָה עִמָּנוּ--וְהֵטַבְנוּ לָךְ",
         "פאי כ'יר יחסן אללה בה אלינא. נחסן אליך מנה",
         "then whatever good God shall deal well to us with, we will deal well with you from it.'"),
    ],
    33: [
        ("וַיִּסְעוּ מֵהַר יְהוָה דֶּרֶךְ שְׁלֹשֶׁת יָמִים",
         "פרחלו מן גבל אללה. מסאפה' ת'לאת'ה אייאם",
         "And they set out from the mountain of God a distance of three days' journey"),
        ("וַאֲרוֹן בְּרִית-יְהוָה נֹסֵעַ לִפְנֵיהֶם דֶּרֶךְ שְׁלֹשֶׁת יָמִים",
         "וצנדוק עהד אללה סאיר בין אידיהם. מסאפה' תלך אלת'לאת'ה' אלאייאם",
         "and the ark of the covenant of God was moving before them a distance of those three days"),
        ("לָתוּר לָהֶם מְנוּחָה", "לי'כתאר להם מסתקרא",
         "to choose a resting-place for them."),
    ],
    34: [
        ("וַעֲנַן יְהוָה עֲלֵיהֶם יוֹמָם בְּנָסְעָם מִן-הַמַּחֲנֶה",
         "וג'מאם אללה עליהם נהארא. אד' רחלו מן אלעסכר",
         "And the cloud of God was over them by day, when they set out from the camp."),
    ],
    36: [
        ("וּבְנֻחֹה יֹאמַר שׁוּבָה יְהוָה רִבְבוֹת אַלְפֵי יִשְׂרָאֵל",
         "וענד נזולה אן יקול. רד יא רב נורך. אלי' רבוואת אלוף אל אסראיל",
         "And at its coming to rest, he would say: 'Return, O Lord, Your light, to the ten-thousands of the thousands of the house of Israel.'"),
    ],
}
