"""Hand-authored alignment triples for Bamidbar chapter 17."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("אֱמֹר אֶל-אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן", "מר אלעזר אבן הרון אלאמאם",
         "Command Eleazar son of Aaron the priest"),
        ("וְיָרֵם אֶת-הַמַּחְתֹּת מִבֵּין הַשְּׂרֵפָה", "באן ירפע אלמגאמר מן בין אלמחרקין",
         "that he lift the fire-pans from among the burned ones"),
        ("וְאֶת-הָאֵשׁ זְרֵה-הָלְאָה", "ויד'רי אלנאר הנאך", "and scatter the fire there"),
        ("כִּי קָדֵשׁוּ", "לאנהא קד תקדסת", "for they have become consecrated."),
    ],
    3: [
        ("אֵת מַחְתּוֹת הַחַטָּאִים הָאֵלֶּה בְּנַפְשֹׁתָם",
         "אמא מגאמר הולאי אלמכ'טיין עלי' נפוסהם",
         "As for the fire-pans of these men who sinned against their own souls"),
        ("וְעָשׂוּ אֹתָם רִקֻּעֵי פַחִים צִפּוּי לַמִּזְבֵּחַ",
         "פיצנעוהא צפאיחא רקאק ג'שאא לאלמד'בח",
         "let them be made into thin beaten plates, a covering for the altar"),
        ("כִּי-הִקְרִיבֻם לִפְנֵי-יְהוָה וַיִּקְדָּשׁוּ",
         "פאנהא למא קדמוהא בין ידי אללה קד תקדסת",
         "for since they presented them before God they have become consecrated"),
        ("וְיִהְיוּ לְאוֹת לִבְנֵי יִשְׂרָאֵל", "ותציר עלאמה לבני אסראיל",
         "and they shall be a sign for the sons of Israel."),
    ],
    4: [
        ("וַיִּקַּח אֶלְעָזָר הַכֹּהֵן אֵת מַחְתּוֹת הַנְּחֹשֶׁת אֲשֶׁר הִקְרִיבוּ הַשְּׂרֻפִים",
         "פאכ'ד' אלעזר אלאמאם. מגאמר אלנחאס. אלד'י קדמוהא אלמחרקין",
         "And Eleazar the priest took the copper fire-pans which the burned ones had presented"),
        ("וַיְרַקְּעוּם צִפּוּי לַמִּזְבֵּחַ", "פארקוהא צפאיחא לאלמד'בח",
         "and they beat them into plates for the altar"),
    ],
    5: [
        ("זִכָּרוֹן לִבְנֵי יִשְׂרָאֵל", "ד'כרא לבני אסראיל",
         "a memorial for the sons of Israel"),
        ("לְמַעַן אֲשֶׁר לֹא-יִקְרַב אִישׁ זָר אֲשֶׁר לֹא מִזֶּרַע אַהֲרֹן הוּא לְהַקְטִיר קְטֹרֶת לִפְנֵי יְהוָה",
         "לכי לא יתקדם רגל אגנבי. מן ליס הו מן נסל הרון. ליבכ'ר בכ'ורא בין ידי אללה",
         "so that no outsider who is not of the lineage of Aaron shall draw near to burn incense before God"),
        ("וְלֹא-יִהְיֶה כְקֹרַח וְכַעֲדָתוֹ", "ולא יכון כקרח וכגמועה",
         "and that none be like Korah and his assembly"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה בְּיַד-מֹשֶׁה לוֹ", "כמא נזל אללה. עלי' יד מוסי פיה",
         "as God laid down by the hand of Moses concerning him."),
    ],
    6: [
        ("וַיִּלֹּנוּ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל מִמָּחֳרָת עַל-מֹשֶׁה וְעַל-אַהֲרֹן",
         "פתד'מר. גמאעה' בני אסראיל מן ג'ד. עלי' מוסי' והרון",
         "And the whole congregation of the sons of Israel complained on the next day against Moses and Aaron"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("אַתֶּם הֲמִתֶּם אֶת-עַם יְהוָה", "אנתמא קתלתמא מן אמה' אללה",
         "'You two have killed from the nation of God.'"),
    ],
    7: [
        ("וַיְהִי בְּהִקָּהֵל הָעֵדָה עַל-מֹשֶׁה וְעַל-אַהֲרֹן", "פלמא תגווקו עליהמא",
         "And when they had gathered against the two of them"),
        ("וַיִּפְנוּ אֶל-אֹהֶל מוֹעֵד", "אלתפתו אלי' כ'בא אלמחצ'ר",
         "they turned toward the tent of the assembly"),
        ("וְהִנֵּה כִסָּהוּ הֶעָנָן וַיֵּרָא כְּבוֹד יְהוָה", "פאד'א בנור אללה. צהר פי אלג'מאם",
         "and behold, the light of God appeared in the cloud."),
    ],
    8: [
        ("וַיָּבֹא מֹשֶׁה וְאַהֲרֹן אֶל-פְּנֵי אֹהֶל מוֹעֵד",
         "פתקדם מוסי' והרון. בין ידי כ'בא אלמחצ'ר",
         "And Moses and Aaron came forward before the tent of the assembly."),
    ],
    9: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה. מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    10: [
        ("הֵרֹמּוּ מִתּוֹךְ הָעֵדָה הַזֹּאת", "אן ארתפעתם מן בין הד'א אלגמאעה",
         "'If you remove yourselves from among this congregation"),
        ("וַאֲכַלֶּה אֹתָם כְּרָגַע", "אפניתהם כטרפה",
         "I shall destroy them in the twinkling of an eye.'"),
        ("וַיִּפְּלוּ עַל-פְּנֵיהֶם", "פוקעא עלי' וגוההמא",
         "And the two of them fell upon their faces."),
    ],
    11: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן", "פקאל מוסי' להרון",
         "And Moses said to Aaron"),
        ("קַח אֶת-הַמַּחְתָּה וְתֶן-עָלֶיהָ אֵשׁ מֵעַל הַמִּזְבֵּחַ",
         "כ'ד' אלמגמרה. ואגעל עליהא נארא. מן פוק אלמד'בח",
         "'Take the fire-pan, and place upon it fire from the altar"),
        ("וְשִׂים קְטֹרֶת", "ואלקי בכורא", "and cast incense upon it"),
        ("וְהוֹלֵךְ מְהֵרָה אֶל-הָעֵדָה וְכַפֵּר עֲלֵיהֶם",
         "ואד'הב בה מסרעא. אלי' אלגמאעה ואסתג'פר ענהם",
         "and go with it quickly to the congregation, and seek forgiveness for them"),
        ("כִּי-יָצָא הַקֶּצֶף מִלִּפְנֵי יְהוָה הֵחֵל הַנָּגֶף",
         "פאן אלסכ'ט. קד כ'רג מן בין ידי אללה. וקד בדא בהם אלצדאם",
         "for the wrath has gone forth from before God, and the plague has already begun among them.'"),
    ],
    12: [
        ("וַיִּקַּח אַהֲרֹן כַּאֲשֶׁר דִּבֶּר מֹשֶׁה", "פאכ'ד' ד'אלך הרון. כמא קאל מוסי",
         "And Aaron took it, just as Moses had said"),
        ("וַיָּרָץ אֶל-תּוֹךְ הַקָּהָל", "וחאצ'ר אלי' וסט אלגוק",
         "and he came to the midst of the assembly"),
        ("וְהִנֵּה הֵחֵל הַנֶּגֶף בָּעָם", "פאד'א באלובא קד אבתדא בהם",
         "and behold, the pestilence had already begun among them"),
        ("וַיִּתֵּן אֶת-הַקְּטֹרֶת וַיְכַפֵּר עַל-הָעָם", "פבכ'ר אלבכור. ואסתג'פר ענהם",
         "and he burned the incense, and sought forgiveness for them."),
    ],
    13: [
        ("וַיַּעֲמֹד בֵּין-הַמֵּתִים וּבֵין הַחַיִּים", "פוקף בין אלמותא ואלאחיא",
         "And he stood between the dead and the living"),
        ("וַתֵּעָצַר הַמַּגֵּפָה", "ואנחבס אלובא", "and the pestilence was held back."),
    ],
    14: [
        ("וַיִּהְיוּ הַמֵּתִים בַּמַּגֵּפָה אַרְבָּעָה עָשָׂר אֶלֶף וּשְׁבַע מֵאוֹת",
         "פכאן עדד מן מאת בד'אלך אלובא. ארבעה' עשר אלף וסבע מאיה",
         "And the number of those who died in that pestilence was fourteen thousand and seven hundred"),
        ("מִלְּבַד הַמֵּתִים עַל-דְּבַר-קֹרַח", "סוא מן מאת בסבב קרח",
         "besides those who died on account of Korah."),
    ],
    15: [
        ("וַיָּשָׁב אַהֲרֹן אֶל-מֹשֶׁה אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "פרגע הרון אלי' מוסי. אלי' באב כ'בא אלמחצ'ר",
         "Then Aaron returned to Moses, to the entrance of the tent of the assembly"),
        ("וְהַמַּגֵּפָה נֶעֱצָרָה", "וקד אנחבס אלובא",
         "and the pestilence had been held back."),
    ],
    16: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    17: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "מר בני אסראיל",
         "'Command the sons of Israel"),
        ("וְקַח מֵאִתָּם מַטֶּה מַטֶּה לְבֵית אָב מֵאֵת כָּל-נְשִׂיאֵהֶם לְבֵית אֲבֹתָם",
         "וכ'ד' מנהם. עצא עצא לכל בית אב. מן אשראפהם לביות אבאיהם",
         "and take from them a staff, one staff for each father's house, from their nobles, for the houses of their fathers"),
        ("שְׁנֵים עָשָׂר מַטּוֹת", "את'ני עשר עצא", "twelve staves"),
        ("אִישׁ אֶת-שְׁמוֹ תִּכְתֹּב עַל-מַטֵּהוּ", "ואכתב אסם כל רגל עלי' עצאה",
         "and write the name of each man upon his staff"),
    ],
    18: [
        ("וְאֵת שֵׁם אַהֲרֹן תִּכְתֹּב עַל-מַטֵּה לֵוִי", "ואסם הרון. אכתב עלי' עצא לוי",
         "And Aaron's name — write it upon the staff of Levi"),
        ("כִּי מַטֶּה אֶחָד לְרֹאשׁ בֵּית אֲבוֹתָם",
         "אנך אנמא תאכ'ד' עצא ואחד. לגמלה' ביות אבאיהם",
         "for you are to take but one staff for the whole body of the houses of their fathers.'"),
    ],
    19: [
        ("וְהִנַּחְתָּם בְּאֹהֶל מוֹעֵד--לִפְנֵי הָעֵדוּת",
         "וצ'עהא פי כ'בא אלמחצ'ר. בין ידי אלשהאדה",
         "'And place them in the tent of the assembly, before the testimony"),
        ("אֲשֶׁר אִוָּעֵד לָכֶם שָׁמָּה", "אלד'י אחצ'רך הנאך",
         "where I shall meet you there.'"),
    ],
    20: [
        ("וְהָיָה הָאִישׁ אֲשֶׁר אֶבְחַר-בּוֹ--מַטֵּהוּ יִפְרָח",
         "פאלרג'ל אלד'י אכ'תארה תפרע עצאה",
         "'And the man whom I shall choose — his staff shall put forth branches"),
        ("וַהֲשִׁכֹּתִי מֵעָלַי אֶת-תְּלֻנּוֹת בְּנֵי יִשְׂרָאֵל",
         "חתא אהדי עני. תדמר בני אסראיל",
         "so that I may quiet away from Me the complaining of the sons of Israel"),
        ("אֲשֶׁר הֵם מַלִּינִם עֲלֵיכֶם", "אלד'י הם מתד'מרין עליכם",
         "which they are complaining against you.'"),
    ],
    21: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-בְּנֵי יִשְׂרָאֵל", "פכלם מוסי' בדאלך בני אסראיל",
         "And Moses spoke this to the sons of Israel"),
        ("וַיִּתְּנוּ אֵלָיו כָּל-נְשִׂיאֵיהֶם מַטֶּה לְנָשִׂיא אֶחָד מַטֶּה לְנָשִׂיא אֶחָד לְבֵית אֲבֹתָם",
         "פדפע אליה כל אשראפהם. עצא מן כל שריף לביות אבאיהם",
         "and all their nobles gave to him a staff, one staff for each noble, for the houses of their fathers"),
        ("שְׁנֵים עָשָׂר מַטּוֹת", "את'ני עשר עצא", "twelve staves"),
        ("וּמַטֵּה אַהֲרֹן בְּתוֹךְ מַטּוֹתָם", "ועצא הרון פי מא בין עציהם",
         "and Aaron's staff was among their staves"),
    ],
    22: [
        ("וַיַּנַּח מֹשֶׁה אֶת-הַמַּטֹּת לִפְנֵי יְהוָה", "פוצ'עהא מוסי' בין ידי אללה",
         "And Moses placed them before God"),
        ("בְּאֹהֶל הָעֵדֻת", "פי כ'בא אלשהאדה", "in the tent of the testimony."),
    ],
    23: [
        ("וַיְהִי מִמָּחֳרָת", "ולמא כאן מן ג'ד", "And when the next day came"),
        ("וַיָּבֹא מֹשֶׁה אֶל-אֹהֶל הָעֵדוּת", "דכ'ל מוסי אלי' כ'בא אלשהאדה",
         "Moses entered the tent of the testimony"),
        ("וְהִנֵּה פָּרַח מַטֵּה-אַהֲרֹן לְבֵית לֵוִי",
         "פאד'א קד פרעת עצא הרון אלתי הי לבית לוי",
         "and behold, the staff of Aaron, which was for the house of Levi, had put forth branches"),
        ("וַיֹּצֵא פֶרַח וַיָּצֵץ צִיץ וַיִּגְמֹל שְׁקֵדִים",
         "פאכ'רגת פרועא ונוורת נוארא. ועקדת לוזא",
         "it had brought out branches, and had burst into blossom, and had formed almonds."),
    ],
    24: [
        ("וַיֹּצֵא מֹשֶׁה אֶת-כָּל-הַמַּטֹּת מִלִּפְנֵי יְהוָה אֶל-כָּל-בְּנֵי יִשְׂרָאֵל",
         "פאכ'רג מוסי. גמיע אלעצי מן בין ידי אללה. אלי' גמיע בני אסראיל",
         "And Moses brought out all the staves from before God to all the sons of Israel"),
        ("וַיִּרְאוּ וַיִּקְחוּ אִישׁ מַטֵּהוּ", "פנצ'ר כל ואחד אלי' עצאה פאכ'ד'הא",
         "and each one looked at his own staff and took it."),
    ],
    25: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי'",
         "Then God said to Moses"),
        ("הָשֵׁב אֶת-מַטֵּה אַהֲרֹן לִפְנֵי הָעֵדוּת לְמִשְׁמֶרֶת לְאוֹת לִבְנֵי-מֶרִי",
         "רד עצא הרון בין ידי אלשהאדה. תכון חפץ' עלאמה לד'וי אלכ'לף",
         "'Return Aaron's staff before the testimony, to be kept as a sign for those who are rebellious"),
        ("וּתְכַל תְּלוּנֹּתָם מֵעָלַי וְלֹא יָמֻתוּ", "פיפנא תד'מרהם עליי ולא יהלכון",
         "that their complaining against Me may be brought to an end, and they shall not perish.'"),
    ],
    26: [
        ("וַיַּעַשׂ מֹשֶׁה כַּאֲשֶׁר צִוָּה יְהוָה אֹתוֹ כֵּן עָשָׂה",
         "פצנע מוסי'. כמא אמרה אללה מן ד'אלך",
         "And Moses did as God had commanded him in this."),
    ],
    27: [
        ("וַיֹּאמְרוּ בְּנֵי יִשְׂרָאֵל אֶל-מֹשֶׁה לֵאמֹר", "ת'ם קאל בני אסראיל למוסי'",
         "Then the sons of Israel said to Moses"),
        ("הֵן גָּוַעְנוּ אָבַדְנוּ", "הוד'א קד תופא מנא ובאד מנא",
         "'Behold, some of us have died and some of us have perished"),
        ("כֻּלָּנוּ אָבָדְנוּ", "פכלנא האלכין", "so we are all doomed.'"),
    ],
    28: [
        ("כֹּל הַקָּרֵב הַקָּרֵב אֶל-מִשְׁכַּן יְהוָה יָמוּת",
         "ואד'א כאן כל מתקדם. אלי' מסכן אללה יהלך",
         "And if every one who draws near to the dwelling of God is destroyed"),
        ("הַאִם תַּמְנוּ לִגְו‍ֹעַ", "פהוד'א נחן פאנון מתופון",
         "then behold — we are perishing, we are dying.'"),
    ],
}
