"""Hand-authored alignment triples for Bamidbar chapter 18."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-אַהֲרֹן", "פקאל אללה להרון", "And God said to Aaron"),
        ("אַתָּה וּבָנֶיךָ וּבֵית-אָבִיךָ אִתָּךְ תִּשְׂאוּ אֶת-עֲו‍ֹן הַמִּקְדָּשׁ",
         "אנת ובניך ובית אביך מעך. תחמלון וזר אלקדס",
         "'You and your sons and your father's house with you shall bear the burden of the sanctuary"),
        ("וְאַתָּה וּבָנֶיךָ אִתָּךְ תִּשְׂאוּ אֶת-עֲו‍ֹן כְּהֻנַּתְכֶם",
         "ואנת. ובניך מעך תחמלון וזר אמאמתכם",
         "and you and your sons with you shall bear the burden of your priesthood"),
    ],
    2: [
        ("וְגַם אֶת-אַחֶיךָ מַטֵּה לֵוִי שֵׁבֶט אָבִיךָ הַקְרֵב אִתָּךְ",
         "ואיצ'א אכ'ותך בני לוי. סבט אביך קדמהם אליך",
         "And likewise your brothers, the sons of Levi — the tribe of your father — bring them forward to you"),
        ("וְיִלָּווּ עָלֶיךָ וִישָׁרְתוּךָ", "וינצ'אפון אליך ויכ'דמונך",
         "that they may be joined to you and serve you"),
        ("וְאַתָּה וּבָנֶיךָ אִתָּךְ לִפְנֵי אֹהֶל הָעֵדֻת",
         "ואנת ובניך מעך. פקט. בין ידי כ'בא אלשהאדה",
         "while you and your sons with you alone shall be before the tent of the testimony"),
    ],
    3: [
        ("וְשָׁמְרוּ מִשְׁמַרְתְּךָ וּמִשְׁמֶרֶת כָּל-הָאֹהֶל",
         "ויחפצון מחפצך. וחפץ' גמיע אלכ'בא",
         "And they shall keep your charge and the charge of the whole tent"),
        ("אַךְ אֶל-כְּלֵי הַקֹּדֶשׁ וְאֶל-הַמִּזְבֵּחַ לֹא יִקְרָבוּ",
         "מא כ'לא אניה' אלקדס ואלמד'בח לא יתקדמו",
         "except that they shall not approach the vessels of the sanctuary and the altar"),
        ("וְלֹא-יָמֻתוּ גַם-הֵם גַּם-אַתֶּם", "ללא יהלכון אנתם והם אגמעין",
         "lest both you and they perish together."),
    ],
    4: [
        ("וְנִלְווּ עָלֶיךָ--וְשָׁמְרוּ אֶת-מִשְׁמֶרֶת אֹהֶל מוֹעֵד לְכֹל עֲבֹדַת הָאֹהֶל",
         "ואלמנצ'אפין אליך. יחפצון חפץ' כ'בא אלמחצ'ר וכ'דמתה",
         "And those joined to you shall keep the charge of the tent of assembly and all its service"),
        ("וְזָר לֹא-יִקְרַב אֲלֵיכֶם", "ואגנבי לא יתקדם אליכם",
         "but an outsider shall not approach you."),
    ],
    5: [
        ("וּשְׁמַרְתֶּם אֵת מִשְׁמֶרֶת הַקֹּדֶשׁ וְאֵת מִשְׁמֶרֶת הַמִּזְבֵּחַ",
         "ותחפצ'ו חפץ' אלקד'ס וחפץ' אלמד'בח",
         "And you shall keep the charge of the sanctuary and the charge of the altar"),
        ("וְלֹא-יִהְיֶה עוֹד קֶצֶף עַל-בְּנֵי יִשְׂרָאֵל",
         "ולא יכון זיאדה' סכ'ט. עלי' בני אסראיל",
         "so that there be no further outburst of wrath upon the sons of Israel."),
    ],
    6: [
        ("וַאֲנִי הִנֵּה לָקַחְתִּי אֶת-אֲחֵיכֶם הַלְוִיִּם מִתּוֹךְ בְּנֵי יִשְׂרָאֵל",
         "פאני קד אכ'ד'ת אכ'ותכם אלליואניין. מן בין בני אסראיל",
         "For I have taken your brothers, the Levites, from among the sons of Israel"),
        ("לָכֶם מַתָּנָה נְתֻנִים לַיהוָה", "וגעלתהם הבה לכם ללה",
         "I have made them a gift to you, dedicated to God"),
        ("לַעֲבֹד אֶת-עֲבֹדַת אֹהֶל מוֹעֵד", "ליכ'דמו כ'דמה' כ'בא אלמחצ'ר",
         "to serve the service of the tent of assembly."),
    ],
    7: [
        ("וְאַתָּה וּבָנֶיךָ אִתְּךָ תִּשְׁמְרוּ אֶת-כְּהֻנַּתְכֶם לְכָל-דְּבַר הַמִּזְבֵּחַ וּלְמִבֵּית לַפָּרֹכֶת--וַעֲבַדְתֶּם",
         "ואנת ובניך מעך. תחפצון אמאמתכם. לגמיע אמור אלמד'בח. ודאכ'ל אלסגף ותכ'דמונה",
         "And you and your sons with you shall keep your priesthood for all matters of the altar and what is within the veil, and you shall serve them"),
        ("עֲבֹדַת מַתָּנָה אֶתֵּן אֶת-כְּהֻנַּתְכֶם", "פקד געלת כ'דמתכם כ'דמה מוהובה",
         "for I have made your service a gifted service"),
        ("וְהַזָּר הַקָּרֵב יוּמָת", "ואי אגנבי תקדם אליהא פליקתל",
         "and any outsider who approaches it shall be put to death.'"),
    ],
    8: [
        ("וַיְדַבֵּר יְהוָה אֶל-אַהֲרֹן", "ת'ם כלם אללה הרון. וקאל",
         "Then God spoke to Aaron, and said"),
        ("וַאֲנִי הִנֵּה נָתַתִּי לְךָ אֶת-מִשְׁמֶרֶת תְּרוּמֹתָי לְכָל-קָדְשֵׁי בְנֵי-יִשְׂרָאֵל",
         "אני קד אעטיתך חפץ' רפאיעי. מן גמיע אקדאס בני אסראיל",
         "'I have indeed given you the charge of My raised-offerings, from all the holy things of the sons of Israel"),
        ("לְךָ נְתַתִּים לְמָשְׁחָה וּלְבָנֶיךָ--לְחָק-עוֹלָם",
         "אעטיתהא לך מסחא. ולבניך רסם אלדהר",
         "I have given them to you as an anointing, and to your sons as a perpetual ordinance"),
    ],
    9: [
        ("זֶה-יִהְיֶה לְךָ מִקֹּדֶשׁ הַקֳּדָשִׁים מִן-הָאֵשׁ",
         "הד'א יכון לך. מן כ'ואץ אלאקדאס מן בעד אלמחרק",
         "This shall be yours from the choicest of the holy things, after the burning"),
        ("כָּל-קָרְבָּנָם לְכָל-מִנְחָתָם וּלְכָל-חַטָּאתָם וּלְכָל-אֲשָׁמָם אֲשֶׁר יָשִׁיבוּ לִי",
         "מן גמיע קראבינהם וברהם ודכותהם. וקרבאן אלאת'ם אלד'י יאתוני בה",
         "from all their offerings and their grain-offerings and their purification-offerings, and the guilt-offering which they bring to Me"),
        ("קֹדֶשׁ קָדָשִׁים לְךָ הוּא וּלְבָנֶיךָ", "פהו מן כ'ואץ אלאקדאס. לך ולבניך",
         "it is from the choicest of the holy things, for you and for your sons."),
    ],
    10: [
        ("בְּקֹדֶשׁ הַקֳּדָשִׁים תֹּאכְלֶנּוּ", "ובכ'אץ אלט'הר תאכלה",
         "You shall eat it in the choicest of purity"),
        ("כָּל-זָכָר יֹאכַל אֹתוֹ", "כל ד'כר יאכל מנה", "every male shall eat of it"),
        ("קֹדֶשׁ יִהְיֶה-לָּךְ", "כד'אך יכון לך קדסא", "thus shall it be holy to you."),
    ],
    11: [
        ("וְזֶה-לְּךָ תְּרוּמַת מַתָּנָם לְכָל-תְּנוּפֹת בְּנֵי יִשְׂרָאֵל",
         "והד'ה לך רפאיע עטאיאהם. מן גמיע מחרכאת בני אסראיל",
         "And these are yours — the raised-offerings of their gifts, from all the wave-offerings of the sons of Israel"),
        ("לְךָ נְתַתִּים וּלְבָנֶיךָ וְלִבְנֹתֶיךָ אִתְּךָ לְחָק-עוֹלָם",
         "לך אעטיתהא. ולבניך ולבנאתך. מעך רסם אלדהר",
         "I have given them to you, and to your sons and to your daughters with you, as a perpetual ordinance"),
        ("כָּל-טָהוֹר בְּבֵיתְךָ יֹאכַל אֹתוֹ", "כל טאהר פי מנזלך יאכלהא",
         "every one who is pure in your household may eat it."),
    ],
    12: [
        ("כֹּל חֵלֶב יִצְהָר וְכָל-חֵלֶב תִּירוֹשׁ וְדָגָן",
         "וגמיע אגוד אלדהן ואלעציר ואלבר",
         "And all the choicest of the oil and of the juice and of the grain"),
        ("רֵאשִׁיתָם אֲשֶׁר-יִתְּנוּ לַיהוָה", "אואילהא. אלד'י יגעלונהא ללה",
         "their firstfruits which they set apart for God"),
        ("לְךָ נְתַתִּים", "קד געלתהא לך", "I have given them to you."),
    ],
    13: [
        ("בִּכּוּרֵי כָּל-אֲשֶׁר בְּאַרְצָם אֲשֶׁר-יָבִיאוּ לַיהוָה--לְךָ יִהְיֶה",
         "ובכור מא פי ריאצ'הם. אלד'י יאתון בה ללה יכון לך",
         "And the firstfruits of all that is in their gardens, which they bring to God, shall be yours"),
        ("כָּל-טָהוֹר בְּבֵיתְךָ יֹאכְלֶנּוּ", "וכל טאהר פי מנזלך יאכלה",
         "every one who is pure in your household may eat it."),
    ],
    14: [
        ("כָּל-חֵרֶם בְּיִשְׂרָאֵל לְךָ יִהְיֶה", "וכל צ'ואף פי אל אסראיל יכון לך",
         "And every devoted thing in the house of Israel shall be yours."),
    ],
    15: [
        ("כָּל-פֶּטֶר רֶחֶם לְכָל-בָּשָׂר אֲשֶׁר-יַקְרִיבוּ לַיהוָה בָּאָדָם וּבַבְּהֵמָה--יִהְיֶה-לָּךְ",
         "וכל אוול בטן. מן כל בשרי. אלד'י יקדמונה ללה. מן אנסאן ובהימה יכון לך",
         "Every firstborn of the womb, of all flesh, which they present to God — of human and of beast — shall be yours"),
        ("אַךְ פָּדֹה תִפְדֶּה אֵת בְּכוֹר הָאָדָם", "לכן יגב אן תפדי בכור אלנאס",
         "yet you are required to redeem the firstborn of people"),
        ("וְאֵת בְּכוֹר-הַבְּהֵמָה הַטְּמֵאָה תִּפְדֶּה", "ובכור אלבהימה אלנגסה",
         "and the firstborn of unclean beasts you shall redeem."),
    ],
    16: [
        ("וּפְדוּיָו מִבֶּן-חֹדֶשׁ תִּפְדֶּה", "ופדא אלנאס מן אבן שהר",
         "And the redemption of people shall be from one month of age"),
        ("בְּעֶרְכְּךָ כֶּסֶף חֲמֵשֶׁת שְׁקָלִים בְּשֶׁקֶל הַקֹּדֶשׁ",
         "בקימתה. כ'מסה מת'אקיל פצ'ה אלקדס",
         "at its valuation: five shekels of silver of the sanctuary"),
        ("עֶשְׂרִים גֵּרָה הוּא", "והו עשרין דאנק", "which is twenty daniq."),
    ],
    17: [
        ("אַךְ בְּכוֹר-שׁוֹר אוֹ-בְכוֹר כֶּשֶׂב אוֹ-בְכוֹר עֵז לֹא תִפְדֶּה--קֹדֶשׁ הֵם",
         "פאמא בכר אלבקר ואלצ'אן ואלמאעז. פלא תפדהא פאנהא מקדסה",
         "But the firstborn of oxen and of sheep and of goats you shall not redeem, for they are holy"),
        ("אֶת-דָּמָם תִּזְרֹק עַל-הַמִּזְבֵּחַ", "רש דמהא עלי' אלמד'בח",
         "sprinkle their blood upon the altar"),
        ("וְאֶת-חֶלְבָּם תַּקְטִיר--אִשֶּׁה לְרֵיחַ נִיחֹחַ לַיהוָה",
         "וקתר שחמהא. קרבאן מקבול מרצ'י ללה",
         "and burn their fat — an accepted and pleasing offering to God."),
    ],
    18: [
        ("וּבְשָׂרָם יִהְיֶה-לָּךְ", "ולחמהא יכון לך", "And their flesh shall be yours"),
        ("כַּחֲזֵה הַתְּנוּפָה וּכְשׁוֹק הַיָּמִין לְךָ יִהְיֶה",
         "כקץ אלתחריך. וכאלסאק אלימני יכון לך",
         "as the breast of the wave-offering and as the right thigh, it shall be yours."),
    ],
    19: [
        ("כֹּל תְּרוּמֹת הַקֳּדָשִׁים אֲשֶׁר יָרִימוּ בְנֵי-יִשְׂרָאֵל לַיהוָה",
         "וסאיר רפאיע אלאקדאס. אלתי ירפעוהא בני אסראיל ללה",
         "And the rest of the raised-offerings of the holy things which the sons of Israel give to God"),
        ("נָתַתִּי לְךָ וּלְבָנֶיךָ וְלִבְנֹתֶיךָ אִתְּךָ לְחָק-עוֹלָם",
         "געלתהא לך. ולבניך ולבנאתך. מעך רסם אלדהר",
         "I have given them to you, and to your sons and to your daughters with you, as a perpetual ordinance"),
        ("בְּרִית מֶלַח עוֹלָם הִוא לִפְנֵי יְהוָה לְךָ וּלְזַרְעֲךָ אִתָּךְ",
         "עהד ת'באת אלעאלם הו ללה. לך ולנסלך בעדך",
         "it is a covenant of the world's enduring stability before God, for you and for your offspring after you.'"),
    ],
    20: [
        ("וַיֹּאמֶר יְהוָה אֶל-אַהֲרֹן", "ת'ם קאל אללה לה", "Then God said to him"),
        ("בְּאַרְצָם לֹא תִנְחָל וְחֵלֶק לֹא-יִהְיֶה לְךָ בְּתוֹכָם",
         "פי ריאצ'הם לא תנחל. ולא יכון לך נציב פי מא בינהם",
         "'In their gardens you shall not inherit, nor shall you have a portion among them"),
        ("אֲנִי חֶלְקְךָ וְנַחֲלָתְךָ בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "פאני קד געלת קראביני קסמך ונחלתך. פי מא בין בני אסראיל",
         "for I have made My offerings your portion and your inheritance among the sons of Israel.'"),
    ],
    21: [
        ("וְלִבְנֵי לֵוִי הִנֵּה נָתַתִּי כָּל-מַעֲשֵׂר בְּיִשְׂרָאֵל לְנַחֲלָה",
         "ולבני לוי. קד געלת כל עשר מן אל אסראיל נחלה",
         "And to the sons of Levi — I have given every tithe from the house of Israel as an inheritance"),
        ("חֵלֶף עֲבֹדָתָם אֲשֶׁר-הֵם עֹבְדִים אֶת-עֲבֹדַת אֹהֶל מוֹעֵד",
         "בדל כ'דמתהם. אלד'י יכ'דמון כ'בא אלמחצ'ר",
         "in exchange for their service which they serve at the tent of assembly."),
    ],
    22: [
        ("וְלֹא-יִקְרְבוּ עוֹד בְּנֵי יִשְׂרָאֵל אֶל-אֹהֶל מוֹעֵד",
         "ולא יתקדם בני אסראיל איצ'א אלי' כ'בא אלמחצ'ר",
         "And the sons of Israel shall no longer approach the tent of assembly"),
        ("לָשֵׂאת חֵטְא לָמוּת", "פיחמלון וזרא פיהלכון",
         "lest they bear a burden and perish."),
    ],
    23: [
        ("וְעָבַד הַלֵּוִי הוּא אֶת-עֲבֹדַת אֹהֶל מוֹעֵד",
         "ויכ'דמון אלליואניין וחדהם כ'בא אלמחצ'ר",
         "And the Levites alone shall serve the tent of assembly"),
        ("וְהֵם יִשְׂאוּ עֲו‍ֹנָם", "והם יחמלון וזרהם", "and they shall bear their burden"),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם", "רסם אלדהר עלא מר אגיאלכם",
         "a perpetual ordinance throughout your generations"),
        ("וּבְתוֹךְ בְּנֵי יִשְׂרָאֵל לֹא יִנְחֲלוּ נַחֲלָה",
         "ופי מא בין בני אסראיל. לא ינחלו נחלה",
         "and among the sons of Israel they shall not inherit an inheritance."),
    ],
    24: [
        ("כִּי אֶת-מַעְשַׂר בְּנֵי-יִשְׂרָאֵל אֲשֶׁר יָרִימוּ לַיהוָה תְּרוּמָה נָתַתִּי לַלְוִיִּם לְנַחֲלָה",
         "פאן עשור בני אסראיל. אלתי ירפעונהא ללה רפיעה. געלתהא לאלליואניין נחלה",
         "For the tithes of the sons of Israel, which they raise up to God as a raised-offering, I have given to the Levites as an inheritance"),
        ("עַל-כֵּן אָמַרְתִּי לָהֶם", "פלד'אלך קלת להם",
         "therefore I have said to them"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל לֹא יִנְחֲלוּ נַחֲלָה",
         "פי מא בין בני אסראיל. לא ינחלון נחלה",
         "among the sons of Israel they shall not inherit an inheritance.'"),
    ],
    25: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, saying:"),
    ],
    26: [
        ("וְאֶל-הַלְוִיִּם תְּדַבֵּר וְאָמַרְתָּ אֲלֵהֶם", "ומר אלליואניין וקל להם",
         "'Command the Levites and say to them"),
        ("כִּי-תִקְחוּ מֵאֵת בְּנֵי-יִשְׂרָאֵל אֶת-הַמַּעֲשֵׂר אֲשֶׁר נָתַתִּי לָכֶם מֵאִתָּם בְּנַחֲלַתְכֶם",
         "אד'א אכ'דתם מן בני אסראיל אלעשר. אלד'י געלתה לכם מנהם בנחלתכם",
         "when you take from the sons of Israel the tithe which I have given you from them as your inheritance"),
        ("וַהֲרֵמֹתֶם מִמֶּנּוּ תְּרוּמַת יְהוָה מַעֲשֵׂר מִן-הַמַּעֲשֵׂר",
         "פארפעו מנה רפיעה ללה. עשרא מן אלעשר",
         "then raise up from it a raised-offering for God — a tenth of the tenth."),
    ],
    27: [
        ("וְנֶחְשַׁב לָכֶם תְּרוּמַתְכֶם", "וד'אלך אן תחסב לכם רפאיעכם",
         "And this shall be reckoned for you as your raised-offerings"),
        ("כַּדָּגָן מִן-הַגֹּרֶן", "כאלבר לבני אסראיל מן אלבד'אר",
         "like the grain of the sons of Israel from the threshing-seed"),
        ("וְכַמְלֵאָה מִן-הַיָּקֶב", "וכאלסלאפה מן אלת'ג'אר",
         "and like the first-pressing from the vats."),
    ],
    28: [
        ("כֵּן תָּרִימוּ גַם-אַתֶּם תְּרוּמַת יְהוָה מִכֹּל מַעְשְׂרֹתֵיכֶם אֲשֶׁר תִּקְחוּ מֵאֵת בְּנֵי יִשְׂרָאֵל",
         "כד'אך תרפעו אנתם איצ'א רפיעה ללה. מן גמיע עשורכם. אלתי תאכ'ד'והא מן בני אסראיל",
         "So shall you also raise up a raised-offering for God from all your tithes which you take from the sons of Israel"),
        ("וּנְתַתֶּם מִמֶּנּוּ אֶת-תְּרוּמַת יְהוָה לְאַהֲרֹן הַכֹּהֵן",
         "ואעטו ד'אלך להרון אלאמאם",
         "and give that to Aaron the imām."),
    ],
    29: [
        ("מִכֹּל מַתְּנֹתֵיכֶם תָּרִימוּ אֵת כָּל-תְּרוּמַת יְהוָה",
         "וליכון מא תרפעונה. מן גמיע עטאיאכם ללה",
         "And let what you raise up from all your gifts for God"),
        ("מִכָּל-חֶלְבּוֹ--אֶת-מִקְדְּשׁוֹ מִמֶּנּוּ", "אגודהא ואכ'צהא מנהא",
         "be the choicest and most select of them."),
    ],
    30: [
        ("וְאָמַרְתָּ אֲלֵהֶם", "וקל להם", "And say to them"),
        ("בַּהֲרִימְכֶם אֶת-חֶלְבּוֹ מִמֶּנּוּ", "אד'א רפעתם אגודה מנה",
         "when you have raised up the choicest of it"),
        ("וְנֶחְשַׁב לַלְוִיִּם כִּתְבוּאַת גֹּרֶן וְכִתְבוּאַת יָקֶב",
         "צאר אלבאקי לכם יא ליואניין. כג'לה' בני אסראיל מן אלבד'אר ואלת'ג'אר",
         "the remainder shall count as yours, O Levites, as the yield of the sons of Israel from threshing-seed and from the vats."),
    ],
    31: [
        ("וַאֲכַלְתֶּם אֹתוֹ בְּכָל-מָקוֹם אַתֶּם וּבֵיתְכֶם",
         "וגאיז אן תאכלוה פי כל מוצ'ע. אנתם ואלכם",
         "And it is permitted that you eat it in every place — you and your households"),
        ("כִּי-שָׂכָר הוּא לָכֶם חֵלֶף עֲבֹדַתְכֶם בְּאֹהֶל מוֹעֵד",
         "לאנה אגרתכם. בדל כ'דמתכם פי כ'בא אלמחצ'ר",
         "for it is your wages in exchange for your service in the tent of assembly."),
    ],
    32: [
        ("וְלֹא-תִשְׂאוּ עָלָיו חֵטְא בַּהֲרִימְכֶם אֶת-חֶלְבּוֹ מִמֶּנּוּ",
         "ולא תחמלון עליה וזרא. ענד רפעכם אגודה מנה",
         "And you shall bear no burden on account of it when you raise up the choicest of it"),
        ("וְאֶת-קָדְשֵׁי בְנֵי-יִשְׂרָאֵל לֹא תְחַלְּלוּ", "ואקדאס בני אסראיל. לא תבד'לוהא",
         "and the holy things of the sons of Israel you shall not treat lightly"),
        ("וְלֹא תָמוּתוּ", "ולא תהלכון", "lest you perish.'"),
    ],
}
