"""Hand-authored alignment triples for Bamidbar chapter 25."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֵּשֶׁב יִשְׂרָאֵל בַּשִּׁטִּים", "ת'ם אקאם אל אסראיל פי שטין",
         "Then Israel settled in Shittim"),
        ("וַיָּחֶל הָעָם לִזְנוֹת", "פבדא אלקום. אן יזאנו",
         "and the people began to commit fornication"),
        ("אֶל-בְּנוֹת מוֹאָב", "בנאת מואב", "with the daughters of Moab"),
    ],
    2: [
        ("וַתִּקְרֶאןָ לָעָם לְזִבְחֵי אֱלֹהֵיהֶן", "פדעין באלקום. לד'באיח מעבודאתהן",
         "And they invited the people to the sacrifices of their objects of worship"),
        ("וַיֹּאכַל הָעָם", "פאכלו מנהא", "and they ate of them"),
        ("וַיִּשְׁתַּחֲווּ לֵאלֹהֵיהֶן", "וסגדו להא", "and bowed down to them"),
    ],
    3: [
        ("וַיִּצָּמֶד יִשְׂרָאֵל לְבַעַל פְּעוֹר", "פלאזם אל אסראיל פעור אלצנם",
         "And the house of Israel attached itself to Pe'or the idol"),
        ("וַיִּחַר-אַף יְהוָה בְּיִשְׂרָאֵל", "פאשתד ג'צ'ב אללה עלי'הם",
         "and the anger of God intensified against them"),
    ],
    4: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי",
         "And God said to Moses"),
        ("קַח אֶת-כָּל-רָאשֵׁי הָעָם", "כ'ד' גמיע רויסא אלקום",
         "'Take all the chiefs of the people"),
        ("וְהוֹקַע אוֹתָם לַיהוָה נֶגֶד הַשָּׁמֶשׁ", "ואצלבהם ללה חד'א אלשמס",
         "and crucify them before God facing the sun"),
        ("וְיָשֹׁב חֲרוֹן אַף-יְהוָה מִיִּשְׂרָאֵל", "וירגע שדה' ג'צ'ב אללה מן אל אסראיל",
         "that the intensity of God's anger may turn away from the house of Israel"),
    ],
    5: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-שֹׁפְטֵי יִשְׂרָאֵל", "פקאל מוסי' לחכאמהם",
         "And Moses said to their judges"),
        ("הִרְגוּ אִישׁ אֲנָשָׁיו הַנִּצְמָדִים לְבַעַל פְּעוֹר",
         "יקתל כל רגל מן פי נאחיתה. מן מלאזמי פעור אלצנם",
         "'Let every man in his district kill whoever is attached to Pe'or the idol"),
    ],
    6: [
        ("וְהִנֵּה אִישׁ מִבְּנֵי יִשְׂרָאֵל בָּא", "ואד'א ברגל מן בני אסראיל קד אקבל",
         "And behold, a man from the sons of Israel had come forward"),
        ("וַיַּקְרֵב אֶל-אֶחָיו אֶת-הַמִּדְיָנִית", "וקדם אלי' מא בינהם אמראה מדיאנייה",
         "and brought among them a Midianite woman"),
        ("לְעֵינֵי מֹשֶׁה וּלְעֵינֵי כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל", "בחצ'רה' מוסי' וגמאעתהם",
         "in the presence of Moses and their whole assembly"),
        ("וְהֵמָּה בֹכִים פֶּתַח אֹהֶל מוֹעֵד", "והם יבכון. ענד באב כ'בא אלמחצ'ר",
         "who were weeping at the door of the tent of the convocation"),
    ],
    7: [
        ("וַיַּרְא פִּינְחָס בֶּן-אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "פלמא ראא פינחס אבן אלעזר. אבן הרון אלאמאם",
         "And when Phinehas son of Eleazar son of Aaron the priest saw"),
        ("וַיָּקָם מִתּוֹךְ הָעֵדָה", "קאם מן וסט אלגמאעה",
         "he arose from the midst of the assembly"),
        ("וַיִּקַּח רֹמַח בְּיָדוֹ", "ואכ'ד' רמחא פי ידה",
         "and took a spear in his hand"),
    ],
    8: [
        ("וַיָּבֹא אַחַר אִישׁ-יִשְׂרָאֵל אֶל-הַקֻּבָּה", "פדכ'ל וראה אלי' אלקבה",
         "And he went in after him into the chamber"),
        ("וַיִּדְקֹר אֶת-שְׁנֵיהֶם", "וטענהמא גמיעא", "and thrust both of them through"),
        ("אֵת אִישׁ יִשְׂרָאֵל וְאֶת-הָאִשָּׁה אֶל-קֳבָתָהּ",
         "אלרגל ואלאמראה פי בטנהא",
         "the man and the woman through her belly"),
        ("וַתֵּעָצַר הַמַּגֵּפָה מֵעַל בְּנֵי יִשְׂרָאֵל", "ואנחבס אלובא. ען בני אסראיל",
         "and the pestilence was checked from the sons of Israel"),
    ],
    9: [
        ("וַיִּהְיוּ הַמֵּתִים בַּמַּגֵּפָה", "וכאן עדד מן מאת בד'אלך אלובא",
         "And the number of those who died in that pestilence"),
        ("אַרְבָּעָה וְעֶשְׂרִים אָלֶף", "ארבעה ועשרין אלפא", "was twenty-four thousand"),
    ],
    10: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה . מוסי' תכלימא",
         "Then God spoke to Moses, saying"),
    ],
    11: [
        ("פִּינְחָס בֶּן-אֶלְעָזָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "אן פנחס אבן אלעזר אבן הרון אלאמאם",
         "'Phinehas son of Eleazar son of Aaron the priest"),
        ("הֵשִׁיב אֶת-חֲמָתִי מֵעַל בְּנֵי-יִשְׂרָאֵל", "רד חמייתי ען בני אסראיל",
         "has turned back My wrath from the sons of Israel"),
        ("בְּקַנְאוֹ אֶת-קִנְאָתִי בְּתוֹכָם", "במא ג'אר לי פי מא בינהם",
         "in that he was zealous for My sake among them"),
        ("וְלֹא-כִלִּיתִי אֶת-בְּנֵי-יִשְׂרָאֵל בְּקִנְאָתִי", "חתי' לא אפניהם בעקאבי",
         "so that I did not destroy them with My punishment"),
    ],
    12: [
        ("לָכֵן אֱמֹר", "לד'אלך קל לה", "Therefore say to him"),
        ("הִנְנִי נֹתֵן לוֹ אֶת-בְּרִיתִי שָׁלוֹם", "האנא מעטיה עהדי סלאמא",
         "Behold, I am giving him My covenant of peace"),
    ],
    13: [
        ("וְהָיְתָה לּוֹ וּלְזַרְעוֹ אַחֲרָיו", "ותכון לה ולנסלה בעדה",
         "And it shall be for him and for his offspring after him"),
        ("בְּרִית כְּהֻנַּת עוֹלָם", "עהד אמאמה' אלדהר",
         "a covenant of everlasting priesthood"),
        ("תַּחַת אֲשֶׁר קִנֵּא לֵאלֹהָיו", "בדל מא ג'אר לרבה",
         "in recompense for his zeal for his Lord"),
        ("וַיְכַפֵּר עַל-בְּנֵי יִשְׂרָאֵל", "וכפר ען בני אסראיל",
         "whereby he made atonement for the sons of Israel"),
    ],
    14: [
        ("וְשֵׁם אִישׁ יִשְׂרָאֵל הַמֻּכֶּה", "וכאן אסם אלרגל אלאסראילי אלמקתול",
         "And the name of the Israelite man who was slain"),
        ("זִמְרִי בֶּן-סָלוּא", "זמרי אבן סלוא", "was Zimri son of Salu"),
        ("נְשִׂיא בֵית-אָב לַשִּׁמְעֹנִי", "שריף בית אביה אלשמעוני",
         "a noble of his father's house among the Simeonites"),
    ],
    15: [
        ("וְשֵׁם הָאִשָּׁה הַמֻּכָּה הַמִּדְיָנִית", "ואסם אלאמראה אלמקתולה. אלמדיאנייה",
         "And the name of the slain Midianite woman"),
        ("כָּזְבִּי בַת-צוּר", "כזבי אבנה' צור", "was Cozbi daughter of Zur"),
        ("רֹאשׁ אֻמּוֹת בֵּית-אָב בְּמִדְיָן הוּא", "והו רייס אהל בית אמתה במדין",
         "he being the head of the people of his nation's household in Midian"),
    ],
    16: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, saying"),
    ],
    17: [
        ("צָרוֹר אֶת-הַמִּדְיָנִים", "חאצר אלמדיאניין",
         "'Besiege the Midianites"),
        ("וְהִכִּיתֶם אוֹתָם", "חתי תקתלהם", "until you have killed them"),
    ],
    18: [
        ("כִּי צֹרְרִים הֵם לָכֶם בְּנִכְלֵיהֶם", "לאנהם אעדא לכם. באג'תיאלהם",
         "for they are enemies to you, through their treachery"),
        ("אֲשֶׁר-נִכְּלוּ לָכֶם עַל-דְּבַר-פְּעוֹר", "אלד'י אג'תאלוכם בסבב פעור",
         "with which they have treacherously dealt against you by reason of Pe'or"),
        ("וְעַל-דְּבַר כָּזְבִּי בַת-נְשִׂיא מִדְיָן אֲחֹתָם",
         "ובסבב כזבי אבנה' שריף מדין אכ'תהם",
         "and by reason of Cozbi daughter of the noble of Midian their kinswoman"),
        ("הַמֻּכָּה בְיוֹם-הַמַּגֵּפָה עַל-דְּבַר-פְּעוֹר",
         "אלמקתולה פי יום אלובא בסבב פעור",
         "who was slain on the day of the pestilence on account of Pe'or"),
    ],
}
