"""Hand-authored alignment triples for Bamidbar chapter 1."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    2: [
        ("שְׂאוּ אֶת-רֹאשׁ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל",
         "ארפעו גמלה' גמאעה' בני אסראיל",
         "Raise the total count of the congregation of the sons of Israel"),
        ("לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "לעשאירהם וביות אבאיהם",
         "by their clans and their fathers' houses"),
        ("בְּמִסְפַּר שֵׁמוֹת כָּל-זָכָר לְגֻלְגְּלֹתָם",
         "באחצא אסמא. כל ד'כר לגמאגמהם",
         "by the enumeration of names — every male according to their heads"),
    ],
    3: [
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה",
         "מן אבן עשרין סנה פצאעדא",
         "From twenty years of age and upward"),
        ("כָּל-יֹצֵא צָבָא בְּיִשְׂרָאֵל",
         "כל מן יכ'רג אלי' גיוש בני אסראיל",
         "all who go forth to the hosts of the sons of Israel"),
        ("תִּפְקְדוּ אֹתָם לְצִבְאֹתָם אַתָּה וְאַהֲרֹן",
         "תחצוהם לגיושהם אנת והרון",
         "you shall count them by their hosts, you and Aaron"),
    ],
    4: [
        ("וְאִתְּכֶם יִהְיוּ אִישׁ אִישׁ לַמַּטֶּה",
         "וליכון מעכם. מן כל סבט רגל",
         "And there shall be with you, from each tribe, a man"),
        ("אִישׁ רֹאשׁ לְבֵית-אֲבֹתָיו הוּא",
         "וד'אלך אלרגל הו רייס בית אביה",
         "and that man is the chief of his father's house"),
    ],
    5: [
        ("וְאֵלֶּה שְׁמוֹת הָאֲנָשִׁים אֲשֶׁר יַעַמְדוּ אִתְּכֶם",
         "והד'ה אסמא אלרגאל אלד'י יקומון מעכם",
         "And these are the names of the men who shall stand with you"),
        ("לִרְאוּבֵן אֱלִיצוּר בֶּן-שְׁדֵיאוּר",
         "פמן ראובן. אליצור אבן שדיאור",
         "from Reuben — Elizur son of Shedeur"),
    ],
    6: [
        ("לְשִׁמְעוֹן שְׁלֻמִיאֵל בֶּן-צוּרִישַׁדָּי",
         "ומן שמעון. שלומיאל אבן צורישדי",
         "and from Simeon — Shelumiel son of Zurishaddai"),
    ],
    7: [
        ("לִיהוּדָה נַחְשׁוֹן בֶּן-עַמִּינָדָב",
         "ומן יהודה. נחשון אבן עמינדב",
         "and from Judah — Nahshon son of Amminadab"),
    ],
    8: [
        ("לְיִשָּׂשכָר נְתַנְאֵל בֶּן-צוּעָר",
         "ומן יששכר. נתנאל אבן צוער",
         "and from Issachar — Nethanel son of Zuar"),
    ],
    9: [
        ("לִזְבוּלֻן אֱלִיאָב בֶּן-חֵלֹן",
         "ומן זבולון. אלי'אב אבן חלן",
         "and from Zebulun — Eliab son of Helon"),
    ],
    10: [
        ("לִבְנֵי יוֹסֵף--לְאֶפְרַיִם אֱלִישָׁמָע בֶּן-עַמִּיהוּד",
         "ומן בני יוסף. פמן אפרים. אלי'שמע אבן עמיהוד",
         "and from the sons of Joseph: from Ephraim — Elishama son of Ammihud"),
        ("לִמְנַשֶּׁה גַּמְלִיאֵל בֶּן-פְּדָהצוּר",
         "ומן מנשה. גמליאל אבן פדהצור",
         "and from Manasseh — Gamliel son of Pedahzur"),
    ],
    11: [
        ("לְבִנְיָמִן אֲבִידָן בֶּן-גִּדְעֹנִי",
         "ומן בנימין. אבידן אבן גדעוני",
         "and from Benjamin — Abidan son of Gideoni"),
    ],
    12: [
        ("לְדָן אֲחִיעֶזֶר בֶּן-עַמִּישַׁדָּי",
         "ומן דן. אחיעזר אבן עמישדי",
         "and from Dan — Ahiezer son of Ammishaddai"),
    ],
    13: [
        ("לְאָשֵׁר פַּגְעִיאֵל בֶּן-עָכְרָן",
         "ומן אשר. פגעיאל אבן עכרן",
         "and from Asher — Pagiel son of Ochran"),
    ],
    14: [
        ("לְגָד אֶלְיָסָף בֶּן-דְּעוּאֵל",
         "ומן גד. אליסף אבן דעואל",
         "and from Gad — Eliasaph son of Deuel"),
    ],
    15: [
        ("לְנַפְתָּלִי אֲחִירַע בֶּן-עֵינָן",
         "ומן נפתלי. אחירע אבן עינן",
         "and from Naphtali — Ahira son of Enan"),
    ],
    16: [
        ("אֵלֶּה קריאי (קְרוּאֵי) הָעֵדָה",
         "הולאי דעאה' אלגמאעה",
         "These are the summoners of the congregation"),
        ("נְשִׂיאֵי מַטּוֹת אֲבוֹתָם",
         "אשראף אסבאט אבאיהם",
         "the nobles of the tribes of their fathers"),
        ("רָאשֵׁי אַלְפֵי יִשְׂרָאֵל הֵם",
         "ריסא אלוף בני אסראיל",
         "the heads of the thousands of the sons of Israel"),
    ],
    17: [
        ("וַיִּקַּח מֹשֶׁה וְאַהֲרֹן אֵת הָאֲנָשִׁים הָאֵלֶּה",
         "פאכ'ד' מוסי' והרון הולאי אלרגאל",
         "And Moses and Aaron took these men"),
        ("אֲשֶׁר נִקְּבוּ בְּשֵׁמֹת",
         "אלד'י שרחת אסמאיהם",
         "whose names had been set forth"),
    ],
    18: [
        ("וְאֵת כָּל-הָעֵדָה הִקְהִילוּ בְּאֶחָד לַחֹדֶשׁ הַשֵּׁנִי",
         "וגווקו סאיר אלגמאעה. פי אליום אלאוול מן אלשהר אלת'אני",
         "And they assembled the rest of the congregation on the first day of the second month"),
        ("וַיִּתְיַלְדוּ עַל-מִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "פתנאסבו לעשאירהם וביות אבאיהם",
         "and they registered themselves by their clans and their fathers' houses"),
        ("בְּמִסְפַּר שֵׁמוֹת מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה",
         "באחצא אסמא. מן אבן עשרין סנה. פצאעדא לגמאגמהם",
         "by the enumeration of names, from twenty years of age and upward, according to their heads"),
    ],
    19: [
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "כמא אמר אללה מוסי'",
         "As God had commanded Moses"),
        ("וַיִּפְקְדֵם בְּמִדְבַּר סִינָי",
         "עדהם פי ברייה' סיני",
         "he counted them in the wilderness of Sinai"),
    ],
    20: [
        ("וַיִּהְיוּ בְנֵי-רְאוּבֵן בְּכֹר יִשְׂרָאֵל",
         "פכאן בני ראובן בכר אסראיל",
         "And the sons of Reuben, the firstborn of Israel"),
        ("תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "תיאלידהם לעשאירהם לביות אבאיהם",
         "their generations by their clans, by their fathers' houses"),
        ("כָּל-זָכָר מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה כֹּל יֹצֵא צָבָא",
         "כל ד'כר. מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "every male from twenty years of age and upward, all who go forth in their hosts"),
    ],
    21: [
        ("פְּקֻדֵיהֶם לְמַטֵּה רְאוּבֵן",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("שִׁשָּׁה וְאַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "סתה וארבעין אלפא וכ'מס מאיה",
         "forty-six thousand and five hundred"),
    ],
    22: [
        ("לִבְנֵי שִׁמְעוֹן תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "לבני שמעון. תיאלידהם לעשאירהם לביות אבאיהם",
         "For the sons of Simeon — their generations by their clans, by their fathers' houses"),
        ("כָּל-זָכָר מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה כֹּל יֹצֵא צָבָא",
         "כל ד'כר. מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "every male from twenty years of age and upward, all who go forth in their hosts"),
    ],
    23: [
        ("פְּקֻדֵיהֶם לְמַטֵּה שִׁמְעוֹן",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("תִּשְׁעָה וַחֲמִשִּׁים אֶלֶף וּשְׁלֹשׁ מֵאוֹת",
         "תסעה וכ'מסין אלפא ות'לאת מאיה",
         "fifty-nine thousand and three hundred"),
    ],
    24: [
        ("לִבְנֵי גָד תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "לבני גד. תיאלידהם לעשאירהם לביות אבאיהם",
         "For the sons of Gad — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    25: [
        ("פְּקֻדֵיהֶם לְמַטֵּה גָד",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("חֲמִשָּׁה וְאַרְבָּעִים אֶלֶף וְשֵׁשׁ מֵאוֹת וַחֲמִשִּׁים",
         "כ'מסה וארבעין אלפא. וסת מאיה וכ'מסין",
         "forty-five thousand, six hundred and fifty"),
    ],
    26: [
        ("לִבְנֵי יְהוּדָה תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני יהודה. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Judah — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    27: [
        ("פְּקֻדֵיהֶם לְמַטֵּה יְהוּדָה",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("אַרְבָּעָה וְשִׁבְעִים אֶלֶף וְשֵׁשׁ מֵאוֹת",
         "ארבעה וסבעין אלפא וסת מאיה",
         "seventy-four thousand and six hundred"),
    ],
    28: [
        ("לִבְנֵי יִשָּׂשכָר תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני יששכר. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Issachar — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    29: [
        ("פְּקֻדֵיהֶם לְמַטֵּה יִשָּׂשכָר",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("אַרְבָּעָה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ארבעה וכ'מסין אלפא וארבע מאיה",
         "fifty-four thousand and four hundred"),
    ],
    30: [
        ("לִבְנֵי זְבוּלֻן תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני זבולון. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Zebulun — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    31: [
        ("פְּקֻדֵיהֶם לְמַטֵּה זְבוּלֻן",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("שִׁבְעָה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "סבעה וכ'מסין אלפא וארבע מאיה",
         "fifty-seven thousand and four hundred"),
    ],
    32: [
        ("לִבְנֵי יוֹסֵף לִבְנֵי אֶפְרַיִם תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "לבני יוסף לבני אפרים. תיאלידהם לעשאירהם לביות אבאיהם",
         "For the sons of Joseph, for the sons of Ephraim — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    33: [
        ("פְּקֻדֵיהֶם לְמַטֵּה אֶפְרָיִם",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("אַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ארבעין אלפא וכ'מס מאיה",
         "forty thousand and five hundred"),
    ],
    34: [
        ("לִבְנֵי מְנַשֶּׁה תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני מנשה. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Manasseh — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    35: [
        ("פְּקֻדֵיהֶם לְמַטֵּה מְנַשֶּׁה",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("שְׁנַיִם וּשְׁלֹשִׁים אֶלֶף וּמָאתָיִם",
         "וסתין ותלאת'ין אלפא ומאיתין",
         "thirty-six thousand and two hundred"),
    ],
    36: [
        ("לִבְנֵי בִנְיָמִן תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני בנימין. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Benjamin — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    37: [
        ("פְּקֻדֵיהֶם לְמַטֵּה בִנְיָמִן",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("חֲמִשָּׁה וּשְׁלֹשִׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "כ'מסה ותלאת'ין אלפא וארבע מאיה",
         "thirty-five thousand and four hundred"),
    ],
    38: [
        ("לִבְנֵי דָן תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני דן. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Dan — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    39: [
        ("פְּקֻדֵיהֶם לְמַטֵּה דָן",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("שְׁנַיִם וְשִׁשִּׁים אֶלֶף וּשְׁבַע מֵאוֹת",
         "את'נין אלפא וסבע מאיה",
         "sixty-two thousand and seven hundred"),
    ],
    40: [
        ("לִבְנֵי אָשֵׁר תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "ובני אשר. תיאלידהם לעשאירהם לביות אבאיהם",
         "And the sons of Asher — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג' פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    41: [
        ("פְּקֻדֵיהֶם לְמַטֵּה אָשֵׁר",
         "ואלמעדודין כד'אלך מנהם",
         "those counted accordingly from them"),
        ("אֶחָד וְאַרְבָּעִים אֶלֶף וַחֲמֵשׁ מֵאוֹת",
         "ואחד וארבעין אלפא וכ'מס מאיה",
         "forty-one thousand and five hundred"),
    ],
    42: [
        ("בְּנֵי נַפְתָּלִי תּוֹלְדֹתָם לְמִשְׁפְּחֹתָם לְבֵית אֲבֹתָם",
         "בני נפתלי. תיאלידהם לעשאירהם לביות אבאיהם",
         "The sons of Naphtali — their generations by their clans, by their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה--כֹּל יֹצֵא צָבָא",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    43: [
        ("פְּקֻדֵיהֶם לְמַטֵּה נַפְתָּלִי",
         "ואלמעדודין . כד'אלך מנהם",
         "those counted accordingly from them"),
        ("שְׁלֹשָׁה וַחֲמִשִּׁים אֶלֶף וְאַרְבַּע מֵאוֹת",
         "ת'לאת'ה וכ'מסין אלפא וארבע מאיה",
         "fifty-three thousand and four hundred"),
    ],
    44: [
        ("אֵלֶּה הַפְּקֻדִים אֲשֶׁר פָּקַד מֹשֶׁה וְאַהֲרֹן",
         "הולאי אלמעדודין. אלד'י עדהם מוסי' והרון",
         "These are those counted, whom Moses and Aaron"),
        ("וּנְשִׂיאֵי יִשְׂרָאֵל--שְׁנֵים עָשָׂר אִישׁ",
         "ואשראף אל אסראיל. אלאת'ני עשר אלרגל",
         "and the nobles of the house of Israel counted — twelve men"),
        ("אִישׁ-אֶחָד לְבֵית-אֲבֹתָיו הָיוּ",
         "כל ואחד מנהם שריף בית אביה",
         "each one of them the noble of his father's house"),
    ],
    45: [
        ("וַיִּהְיוּ כָּל-פְּקוּדֵי בְנֵי-יִשְׂרָאֵל לְבֵית אֲבֹתָם",
         "וכאן מן עדה מנהם. מנסובא אלי' בית אבאיה",
         "And those who were counted from them — traced to their fathers' houses"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה כָּל-יֹצֵא צָבָא בְּיִשְׂרָאֵל",
         "מן אבן עשרין סנה פצאעדא. כל מן יכ'רג פי גיושהם",
         "from twenty years of age and upward, all who go forth in their hosts"),
    ],
    46: [
        ("וַיִּהְיוּ כָּל-הַפְּקֻדִים",
         "פכאן גמלת אלמעדודין",
         "the total of those counted was"),
        ("שֵׁשׁ-מֵאוֹת אֶלֶף וּשְׁלֹשֶׁת אֲלָפִים וַחֲמֵשׁ מֵאוֹת וַחֲמִשִּׁים",
         "סת מאיה' אלף ות'לאתה' אלאף. וכ'מס מאיה וכ'מסין",
         "six hundred thousand and three thousand, and five hundred and fifty"),
    ],
    47: [
        ("וְהַלְוִיִּם לְמַטֵּה אֲבֹתָם--לֹא הָתְפָּקְדוּ בְּתוֹכָם",
         "ואמא אלליואניין. פלם יעדו מעהם לסבט אבאיהם",
         "But the Levites were not counted among them, by the tribe of their fathers"),
    ],
    48: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly"),
    ],
    49: [
        ("אַךְ אֶת-מַטֵּה לֵוִי לֹא תִפְקֹד",
         "אמא סבט לוי פלא תעדה",
         "'As for the tribe of Levi — do not count it"),
        ("וְאֶת-רֹאשָׁם לֹא תִשָּׂא בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "ולא תרפע גמלתהם. פי מא בין בני אסראיל",
         "and do not raise their total among the sons of Israel"),
    ],
    50: [
        ("וְאַתָּה הַפְקֵד אֶת-הַלְוִיִּם עַל-מִשְׁכַּן הָעֵדֻת",
         "ואנת פוכל אלליואניין עלי' מסכן אלשהאדה",
         "But you — appoint the Levites over the tabernacle of testimony"),
        ("הֵמָּה יִשְׂאוּ אֶת-הַמִּשְׁכָּן וְאֶת-כָּל-כֵּלָיו",
         "פהם יחמלון אלמסכן וגמיע אניתה",
         "they shall carry the tabernacle and all its vessels"),
        ("וְהֵם יְשָׁרְתֻהוּ וְסָבִיב לַמִּשְׁכָּן יַחֲנוּ",
         "והם יכ'דמונה. וחאלי'ה ינזלון",
         "and they shall serve it, and around it they shall encamp"),
    ],
    51: [
        ("וּבִנְסֹעַ הַמִּשְׁכָּן יוֹרִידוּ אֹתוֹ הַלְוִיִּם",
         "ופי רחילה הם יפצלונה",
         "And when it sets out, they shall take it apart"),
        ("וּבַחֲנֹת הַמִּשְׁכָּן יָקִימוּ אֹתוֹ הַלְוִיִּם",
         "ופי נזולה הם ינצבונה",
         "and when it encamps, they shall set it up"),
        ("וְהַזָּר הַקָּרֵב יוּמָת",
         "ואי אגנבי תקדם אלי' ד'אלך פליקתל",
         "and any outsider who approaches it shall be put to death"),
    ],
    52: [
        ("וְחָנוּ בְּנֵי יִשְׂרָאֵל אִישׁ עַל-מַחֲנֵהוּ",
         "וינזל בני אסראיל. כל סבט פי עסכרה",
         "And the sons of Israel shall encamp — each tribe in its encampment"),
        ("וְאִישׁ עַל-דִּגְלוֹ לְצִבְאֹתָם",
         "ופי מרכזה עלי' גיושהם",
         "and in its position — by their hosts"),
    ],
    53: [
        ("וְהַלְוִיִּם יַחֲנוּ סָבִיב לְמִשְׁכַּן הָעֵדֻת",
         "ואלליואניין. ינזלון חואלי מסכן אלשהאדה",
         "And the Levites shall encamp around the tabernacle of testimony"),
        ("וְלֹא-יִהְיֶה קֶצֶף עַל-עֲדַת בְּנֵי יִשְׂרָאֵל",
         "ולא יכון סכ'ט. עלי' גמאעה' בני אסראיל",
         "so that there be no wrath upon the congregation of the sons of Israel"),
        ("וְשָׁמְרוּ הַלְוִיִּם אֶת-מִשְׁמֶרֶת מִשְׁכַּן הָעֵדוּת",
         "ויחפצון חפץ' מסכן אלשהאדה",
         "and the Levites shall keep the charge of the tabernacle of testimony"),
    ],
    54: [
        ("וַיַּעֲשׂוּ בְּנֵי יִשְׂרָאֵל כְּכֹל אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "פצנע בני אסראיל. כגמיע מא אמר אללה מוסי'",
         "And the sons of Israel did according to all that God had commanded Moses"),
        ("כֵּן עָשׂוּ",
         "כד'אך צנעו",
         "so they did"),
    ],
}
