"""Hand-authored alignment triples for Bamidbar chapter 20."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיָּבֹאוּ בְנֵי-יִשְׂרָאֵל כָּל-הָעֵדָה מִדְבַּר-צִן בַּחֹדֶשׁ הָרִאשׁוֹן",
         "ת'ם גאו בני אסראיל אגמעין. אלי' ברייה' צין פי אלשהר אלאוול",
         "Then the sons of Israel, all of them, came to the wilderness of Zin in the first month"),
        ("וַיֵּשֶׁב הָעָם בְּקָדֵשׁ", "ואקאם אלקום פי רקים",
         "and the people settled in Raqim"),
        ("וַתָּמָת שָׁם מִרְיָם וַתִּקָּבֵר שָׁם", "ומאתת הנאך מרים. ודפנת ת'ם",
         "And Miriam died there, and was buried there."),
    ],
    2: [
        ("וְלֹא-הָיָה מַיִם לָעֵדָה", "ולם יכון מאא לאלגמאעה",
         "And there was no water for the congregation"),
        ("וַיִּקָּהֲלוּ עַל-מֹשֶׁה וְעַל-אַהֲרֹן", "פתגווקו עלי' מוסי' והרון",
         "and they assembled against Moses and Aaron."),
    ],
    3: [
        ("וַיָּרֶב הָעָם עִם-מֹשֶׁה", "פלמא כ'אצם אלקום מוסי'",
         "And when the people quarreled with Moses"),
        ("וַיֹּאמְרוּ לֵאמֹר", "וקאלו", "they said"),
        ("וְלוּ גָוַעְנוּ בִּגְוַע אַחֵינוּ לִפְנֵי יְהוָה",
         "יא ליתנא תופינא. בופאה' אכ'ותנא בין ידי אללה",
         "'Would that we had perished at the death of our brothers before God!'"),
    ],
    4: [
        ("וְלָמָה הֲבֵאתֶם אֶת-קְהַל יְהוָה אֶל-הַמִּדְבָּר הַזֶּה",
         "ולם גיתמא בגוק אללה. אלי' הד'א אלבר",
         "'And why have you two brought the congregation of God to this desolate wilderness"),
        ("לָמוּת שָׁם אֲנַחְנוּ וּבְעִירֵנוּ", "נמות פיה. נחן ובהאימנא",
         "that we should die in it — we and our beasts?'"),
    ],
    5: [
        ("וְלָמָה הֶעֱלִיתֻנוּ מִמִּצְרַיִם", "ולם אצעדתמונא מן מצר",
         "'And why have you two brought us up from Egypt"),
        ("לְהָבִיא אֹתָנוּ אֶל-הַמָּקוֹם הָרָע הַזֶּה", "פגיתם בנא. אלי' הד'א אלמוצ'ע אלרדי",
         "and led us to this wretched place"),
        ("לֹא מְקוֹם זֶרַע וּתְאֵנָה וְגֶפֶן וְרִמּוֹן",
         "לא זרע ולא תין. ולא גפן ולא רמאן",
         "— no sown crop, and no figs, and no vines, and no pomegranates"),
        ("וּמַיִם אַיִן לִשְׁתּוֹת", "חתי' מאא ליס לאלשרב", "and there is not even water to drink.'"),
    ],
    6: [
        ("וַיָּבֹא מֹשֶׁה וְאַהֲרֹן מִפְּנֵי הַקָּהָל", "פאקבל מוסי' והרון הארבין. מן בין ידי אלגוק",
         "And Moses and Aaron came fleeing from before the congregation"),
        ("אֶל-פֶּתַח אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר",
         "to the entrance of the tent of the assembly"),
        ("וַיִּפְּלוּ עַל-פְּנֵיהֶם", "פוקעא עלי' וגוההמא",
         "and the two of them fell upon their faces"),
        ("וַיֵּרָא כְבוֹד-יְהוָה אֲלֵיהֶם", "פצ'הר נור אללה להמא",
         "And the light of God appeared to them."),
    ],
    7: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses with speech."),
    ],
    8: [
        ("קַח אֶת-הַמַּטֶּה", "כ'ד' אלעצא", "'Take the staff"),
        ("וְהַקְהֵל אֶת-הָעֵדָה אַתָּה וְאַהֲרֹן אָחִיךָ",
         "וגווק אלגמאעה אנת והרון אכ'יך",
         "and assemble the congregation — you and Aaron your brother"),
        ("וְדִבַּרְתֶּם אֶל-הַסֶּלַע לְעֵינֵיהֶם וְנָתַן מֵימָיו",
         "וקולא עלי' אלצכר בחצ'רתהם ויכ'רג מאה",
         "and speak to the rock in their presence, and it will yield its water"),
        ("וְהוֹצֵאתָ לָהֶם מַיִם מִן-הַסֶּלַע", "פתכ'רג להם מאא מן אלצכר",
         "so you shall bring forth for them water from the rock"),
        ("וְהִשְׁקִיתָ אֶת-הָעֵדָה וְאֶת-בְּעִירָם", "אסקיהם ובהאימהם",
         "Give them and their beasts to drink.'"),
    ],
    9: [
        ("וַיִּקַּח מֹשֶׁה אֶת-הַמַּטֶּה מִלִּפְנֵי יְהוָה",
         "פאכ'ד' מוסי'. אלעצא מן בין ידי אללה",
         "And Moses took the staff from before God"),
        ("כַּאֲשֶׁר צִוָּהוּ", "כמא אמרה", "as He had commanded him."),
    ],
    10: [
        ("וַיַּקְהִלוּ מֹשֶׁה וְאַהֲרֹן אֶת-הַקָּהָל--אֶל-פְּנֵי הַסָּלַע",
         "וגווקו מוסי' והרון. אלגוק אלי' חצ'רה' אלצכר",
         "And Moses and Aaron assembled the congregation before the rock"),
        ("וַיֹּאמֶר לָהֶם שִׁמְעוּ-נָא הַמֹּרִים", "וקאל להם. אסמעו יא עצאה",
         "and he said to them: 'Hear, O rebels"),
        ("הֲמִן-הַסֶּלַע הַזֶּה נוֹצִיא לָכֶם מָיִם", "אמן הד'א אלצכר. נכ'רג לכם מאא",
         "— shall we bring out water for you from this rock?'"),
    ],
    11: [
        ("וַיָּרֶם מֹשֶׁה אֶת-יָדוֹ", "פרפע ידה", "And he raised his hand"),
        ("וַיַּךְ אֶת-הַסֶּלַע בְּמַטֵּהוּ--פַּעֲמָיִם",
         "וצ'רב אלצכר בעצאה מרתין",
         "and struck the rock with his staff twice"),
        ("וַיֵּצְאוּ מַיִם רַבִּים", "פכ'רג מא כת'יר", "and much water came out"),
        ("וַתֵּשְׁתְּ הָעֵדָה וּבְעִירָם", "ושרבת מנה אלגמאעה ובהאימהם",
         "and the congregation and their beasts drank from it."),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן",
         "פקאל אללה למוסי' והרון",
         "And God said to Moses and Aaron"),
        ("יַעַן לֹא-הֶאֱמַנְתֶּם בִּי לְהַקְדִּישֵׁנִי לְעֵינֵי בְּנֵי יִשְׂרָאֵל",
         "כמא לם תומנוהם בי. ותקדסוני בחצ'רה' בני אסראיל",
         "'Just as you did not make them trust in Me, and sanctify Me in the presence of the sons of Israel"),
        ("לָכֵן לֹא תָבִיאוּ אֶת-הַקָּהָל הַזֶּה אֶל-הָאָרֶץ אֲשֶׁר-נָתַתִּי לָהֶם",
         "כד'אך לא תדכ'לא הד'א אלגוק. אלי' אלבלד אלד'י אעטיתהם",
         "— so shall you two not bring this congregation into the land which I have given them.'"),
    ],
    13: [
        ("הֵמָּה מֵי מְרִיבָה", "ד'אלך מא אלכ'צומה",
         "That is the water of strife"),
        ("אֲשֶׁר-רָבוּ בְנֵי-יִשְׂרָאֵל אֶת-יְהוָה", "אלד'י כא'צם בני אסראיל אלרסול בסבבה",
         "over which the sons of Israel quarreled with the messenger"),
        ("וַיִּקָּדֵשׁ בָּם", "פת עצ'ם פיהם", "and He was magnified among them."),
    ],
    14: [
        ("וַיִּשְׁלַח מֹשֶׁה מַלְאָכִים מִקָּדֵשׁ אֶל-מֶלֶךְ אֱדוֹם",
         "ת'ם בעת' מוסי' ברסל. מן רקים אלי' מלך אדום",
         "Then Moses sent messengers from Raqim to the king of Edom, saying"),
        ("כֹּה אָמַר אָחִיךָ יִשְׂרָאֵל", "כד'א קאל אכ'יך אסראיל",
         "'Thus says your brother Israel"),
        ("אַתָּה יָדַעְתָּ אֵת כָּל-הַתְּלָאָה אֲשֶׁר מְצָאָתְנוּ",
         "אנת עאלם. בגמיע אלמצאיב אלתי נאלתנא",
         "You know all the calamities that have befallen us —"),
    ],
    15: [
        ("וַיֵּרְדוּ אֲבֹתֵינוּ מִצְרַיְמָה", "אן אבאינא נזלו מצרא",
         "that our fathers went down to Egypt"),
        ("וַנֵּשֶׁב בְּמִצְרַיִם יָמִים רַבִּים", "פאקמנא במצר מדה טוילה",
         "and we dwelt in Egypt a long time"),
        ("וַיָּרֵעוּ לָנוּ מִצְרַיִם וְלַאֲבֹתֵינוּ", "ואסא אלמצריון. בנא ובאבאינא",
         "and the Egyptians dealt evilly with us and with our fathers."),
    ],
    16: [
        ("וַנִּצְעַק אֶל-יְהוָה וַיִּשְׁמַע קֹלֵנוּ", "פדעינא אלי' אללה פסמע צותנא",
         "And we cried out to God, and He heard our voice"),
        ("וַיִּשְׁלַח מַלְאָךְ וַיֹּצִאֵנוּ מִמִּצְרָיִם", "ובעת' ברסול. ואכ'רגנא מן מצר",
         "and He sent a messenger, and brought us out of Egypt"),
        ("וְהִנֵּה אֲנַחְנוּ בְקָדֵשׁ עִיר קְצֵה גְבוּלֶךָ",
         "והוד'א נחן פי קריה' רקים. פי טרף תכ'מך",
         "And behold, we are now in the town of Raqim, at the edge of your border."),
    ],
    17: [
        ("נַעְבְּרָה-נָּא בְאַרְצֶךָ", "נריד אן נגוז פי בלדך",
         "We wish to pass through your land"),
        ("לֹא נַעֲבֹר בְּשָׂדֶה וּבְכֶרֶם", "וליסנא נמיל אלי' צ'יעה ולא כרם",
         "we will not turn aside to any farmstead or vineyard"),
        ("וְלֹא נִשְׁתֶּה מֵי בְאֵר", "ולא נשרב מא צהריג", "nor will we drink cistern water"),
        ("דֶּרֶךְ הַמֶּלֶךְ נֵלֵךְ לֹא נִטֶּה יָמִין וּשְׂמֹאול",
         "לכנא נסיר פי אלטריק אלגאדה. לא נמיל ימנה ולא יסרה",
         "but we will travel along the main road, turning neither right nor left"),
        ("עַד אֲשֶׁר-נַעֲבֹר גְּבֻלֶךָ", "אלי' אן נגוז תכ'מך",
         "until we have passed through your territory.'"),
    ],
    18: [
        ("וַיֹּאמֶר אֵלָיו אֱדוֹם", "קאל לה אלאחמרי", "The Red One (Edom) said to him"),
        ("לֹא תַעֲבֹר בִּי", "לא תגוז בי", "'You shall not pass through me"),
        ("פֶּן-בַּחֶרֶב אֵצֵא לִקְרָאתֶךָ", "כלא באלסיף אכ'ר'ג תלקאך",
         "— lest I come out against you with the sword.'"),
    ],
    19: [
        ("וַיֹּאמְרוּ אֵלָיו בְּנֵי-יִשְׂרָאֵל בַּמְסִלָּה נַעֲלֶה",
         "וקאלו לה בני אסראיל נצעד פי אלמחגה",
         "And the sons of Israel said to him: 'We will go up by the highway"),
        ("וְאִם-מֵימֶיךָ נִשְׁתֶּה אֲנִי וּמִקְנַי וְנָתַתִּי מִכְרָם",
         "ואן שרבנא לך מא נחן ומאשיתנא. דפענא ת'מנה",
         "and if we or our livestock drink any of your water, we will pay its price"),
        ("רַק אֵין-דָּבָר בְּרַגְלַי אֶעֱבֹרָה", "וליס אמר אלא נגוז פקט",
         "There is no matter at all — only let us pass through.'"),
    ],
    20: [
        ("וַיֹּאמֶר לֹא תַעֲבֹר", "קאל לא תגוז כד'אך", "He said: 'You shall not pass, not even so.'"),
        ("וַיֵּצֵא אֱדוֹם לִקְרָאתוֹ בְּעַם כָּבֵד וּבְיָד חֲזָקָה",
         "פכ'רג אדום תלקאהם. בשעב עצ'ים ויד שדידה",
         "And Edom came out to meet them with a great host and a mighty hand."),
    ],
    21: [
        ("וַיְמָאֵן אֱדוֹם נְתֹן אֶת-יִשְׂרָאֵל עֲבֹר בִּגְבֻלוֹ",
         "פלמא אבא אדום. אן יתרך אל אסראיל. אן יגוזו פי תכ'מה",
         "And when Edom refused to allow the house of Israel to pass through his territory"),
        ("וַיֵּט יִשְׂרָאֵל מֵעָלָיו", "פמלו ענה", "they turned away from him."),
    ],
    22: [
        ("וַיִּסְעוּ מִקָּדֵשׁ", "פרחלו מן רקים", "And they departed from Raqim"),
        ("וַיָּבֹאוּ בְנֵי-יִשְׂרָאֵל כָּל-הָעֵדָה הֹר הָהָר",
         "וגאת גמאעתהם. אלי' גבל הור",
         "and the whole of their congregation came to Mount Hor."),
    ],
    23: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן בְּהֹר הָהָר",
         "פקאל אללה. למוסי' והרון פי גבל הור",
         "And God said to Moses and Aaron at Mount Hor"),
        ("עַל-גְּבוּל אֶרֶץ-אֱדוֹם לֵאמֹר", "ענד תכ'ם בלד אדום קאילא",
         "at the border of the land of Edom, saying:"),
    ],
    24: [
        ("יֵאָסֵף אַהֲרֹן אֶל-עַמָּיו", "ינצ'ם הרון אלי' קומה",
         "'Aaron shall be gathered to his people"),
        ("כִּי לֹא יָבֹא אֶל-הָאָרֶץ אֲשֶׁר נָתַתִּי לִבְנֵי יִשְׂרָאֵל",
         "פאנה לא יד'כל אלבלד. אלד'י אעטיתה לבני אסראיל",
         "for he shall not enter the land which I have given to the sons of Israel"),
        ("עַל אֲשֶׁר-מְרִיתֶם אֶת-פִּי לְמֵי מְרִיבָה",
         "כמא קלת חין כ'אלפתמא אמרי פי מא אלכ'צומה",
         "— as I said when the two of you transgressed My command at the water of strife.'"),
    ],
    25: [
        ("קַח אֶת-אַהֲרֹן וְאֶת-אֶלְעָזָר בְּנוֹ", "כ'ד' הרון. ואלעזר אבנה",
         "'Take Aaron and Eleazar his son"),
        ("וְהַעַל אֹתָם הֹר הָהָר", "ואצעדהמא אלי' גבל הור",
         "and bring the two of them up to Mount Hor.'"),
    ],
    26: [
        ("וְהַפְשֵׁט אֶת-אַהֲרֹן אֶת-בְּגָדָיו", "ואסלך' הרון ת'יאבה",
         "'And strip Aaron of his garments"),
        ("וְהִלְבַּשְׁתָּם אֶת-אֶלְעָזָר בְּנוֹ", "ואלבסהא אלעזר אבנה",
         "and put them upon Eleazar his son"),
        ("וְאַהֲרֹן יֵאָסֵף וּמֵת שָׁם", "והרון ינצ'ם וימות הנאך",
         "and Aaron shall be gathered and shall die there.'"),
    ],
    27: [
        ("וַיַּעַשׂ מֹשֶׁה כַּאֲשֶׁר צִוָּה יְהוָה", "פצנע מוסי'. כמא אמרה אללה",
         "And Moses did as God had commanded him"),
        ("וַיַּעֲלוּ אֶל-הֹר הָהָר לְעֵינֵי כָּל-הָעֵדָה",
         "וצעדוא אלי' גבל הור. בחצ'רה' אלגמאעה",
         "and they went up to Mount Hor in the presence of the congregation."),
    ],
    28: [
        ("וַיַּפְשֵׁט מֹשֶׁה אֶת-אַהֲרֹן אֶת-בְּגָדָיו", "וסלך' מוסי' ת'יאב הרון",
         "And Moses stripped Aaron of his garments"),
        ("וַיַּלְבֵּשׁ אֹתָם אֶת-אֶלְעָזָר בְּנוֹ", "ואלבסהא אלעזר אבנה",
         "and put them upon Eleazar his son"),
        ("וַיָּמָת אַהֲרֹן שָׁם בְּרֹאשׁ הָהָר", "ומאת הרון. הנאך פי ראס אלגבל",
         "and Aaron died there at the summit of the mountain"),
        ("וַיֵּרֶד מֹשֶׁה וְאֶלְעָזָר מִן-הָהָר", "ונזל מוסי'. ואלעזר מן אלגבל",
         "And Moses and Eleazar came down from the mountain."),
    ],
    29: [
        ("וַיִּרְאוּ כָּל-הָעֵדָה כִּי גָוַע אַהֲרֹן",
         "פלמא ראת אלגמאעה. אן הרון קד מאת",
         "And when the congregation saw that Aaron had indeed died"),
        ("וַיִּבְכּוּ אֶת-אַהֲרֹן שְׁלֹשִׁים יוֹם כֹּל בֵּית יִשְׂרָאֵל",
         "בכא עלי'ה ת'לאתין יומא. גמיע אל אסראיל",
         "all the house of Israel wept for him thirty days."),
    ],
}
