"""Hand-authored alignment triples for Bamidbar chapter 36."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּקְרְבוּ רָאשֵׁי הָאָבוֹת לְמִשְׁפַּחַת בְּנֵי-גִלְעָד בֶּן-מָכִיר בֶּן-מְנַשֶּׁה--מִמִּשְׁפְּחֹת בְּנֵי יוֹסֵף",
         "ת'ם תקדם. רויסא אבא עשירה' בני גלעד אבן מכיר אבן מנשה. מן עשאיר בני יוסף",
         "Then the heads of the fathers of the clan of the sons of Gilead son of Makir son of Manasseh, from the clans of the sons of Joseph, came forward"),
        ("וַיְדַבְּרוּ לִפְנֵי מֹשֶׁה וְלִפְנֵי הַנְּשִׂאִים--רָאשֵׁי אָבוֹת לִבְנֵי יִשְׂרָאֵל",
         "וקאלו בין ידי מוסי' ואלאשראף. רויסא אבא בני אסראיל",
         "and spoke before Moses and the nobles — the heads of the fathers of the sons of Israel"),
    ],
    2: [
        ("וַיֹּאמְרוּ", "ננוקאלו", "And they said"),
        ("אֶת-אֲדֹנִי צִוָּה יְהוָה לָתֵת אֶת-הָאָרֶץ בְּנַחֲלָה בְּגוֹרָל לִבְנֵי יִשְׂרָאֵל",
         "אן אללה אמר סיידנא. באן יעטא אלבלד נחלה. באסהם לבני אסראיל",
         "'God commanded our lord to give the land as an inheritance by equal portions to the sons of Israel"),
        ("וַאדֹנִי צֻוָּה בַיהוָה לָתֵת אֶת-נַחֲלַת צְלָפְחָד אָחִינוּ לִבְנֹתָיו",
         "ואמרה איצ'א. באן ידפע נחלה' צלפחד אכ'ינא אלי' בנאתה",
         "and He also commanded him to transfer the inheritance of Zelophehad our brother to his daughters"),
    ],
    3: [
        ("וְהָיוּ לְאֶחָד מִבְּנֵי שִׁבְטֵי בְנֵי-יִשְׂרָאֵל לְנָשִׁים",
         "פנכ'אף אן יצרן נסאא. לואחד מן אסבאט בני אסראיל",
         "And we fear that they may become wives of one from the other tribes of the sons of Israel"),
        ("וְנִגְרְעָה נַחֲלָתָן מִנַּחֲלַת אֲבֹתֵינוּ", "פתנקץ חצתהן מן נחלה' אבאינא",
         "so that their portion will be diminished from the inheritance of our fathers"),
        ("וְנוֹסַף עַל נַחֲלַת הַמַּטֶּה אֲשֶׁר תִּהְיֶינָה לָהֶם",
         "ותזאד עלי' חצה' אלסבט. אלד'י יתזווגן מנה",
         "and will be added to the portion of the tribe into which they marry"),
        ("וּמִגֹּרַל נַחֲלָתֵנוּ יִגָּרֵעַ", "ויכון סהם נחלתנא מנקוצא",
         "and the allotted share of our inheritance shall be reduced"),
    ],
    4: [
        ("וְאִם-יִהְיֶה הַיֹּבֵל לִבְנֵי יִשְׂרָאֵל", "ולו חתי יואפי סנה' אלאטלאק לבני אסראיל",
         "And even when the year of release comes for the sons of Israel"),
        ("וְנוֹסְפָה נַחֲלָתָן עַל נַחֲלַת הַמַּטֶּה אֲשֶׁר תִּהְיֶינָה לָהֶם",
         "לבקית חצתהן מזאדה. עלי' חצה' אלסבט. אלד'י יתזווגן מנה",
         "their portion will remain added to the portion of the tribe into which they marry"),
        ("וּמִנַּחֲלַת מַטֵּה אֲבֹתֵינוּ יִגָּרַע נַחֲלָתָן", "ונאקצה מן חצתנא",
         "and diminished from our portion.'"),
    ],
    5: [
        ("וַיְצַו מֹשֶׁה אֶת-בְּנֵי יִשְׂרָאֵל עַל-פִּי יְהוָה לֵאמֹר",
         "פאמר מוסי' בני אסראיל. ען קול אללה קאילא",
         "And Moses gave an order to the sons of Israel, according to the word of God, saying"),
        ("כֵּן מַטֵּה בְנֵי-יוֹסֵף דֹּבְרִים", "נעמא קאל סבט ולד יוסף",
         "'The tribe of the sons of Joseph speaks rightly"),
    ],
    6: [
        ("זֶה הַדָּבָר אֲשֶׁר-צִוָּה יְהוָה לִבְנוֹת צְלָפְחָד לֵאמֹר",
         "הד'א אלאמר אלד'י אמר אללה. פי חכם בנאת צלפחד",
         "This is the matter which God has commanded concerning the case of the daughters of Zelophehad"),
        ("לַטּוֹב בְּעֵינֵיהֶם תִּהְיֶינָה לְנָשִׁים", "אן יתזווגן למן חסן ענדהן",
         "let them marry whomever seems good to them"),
        ("אַךְ לְמִשְׁפַּחַת מַטֵּה אֲבִיהֶם--תִּהְיֶינָה לְנָשִׁים",
         "לכן יכון מן עשירה' סבט אביהן",
         "but they shall be from the clan of the tribe of their father"),
    ],
    7: [
        ("וְלֹא-תִסֹּב נַחֲלָה לִבְנֵי יִשְׂרָאֵל מִמַּטֶּה אֶל-מַטֶּה",
         "חתי' לא תדור הד'ה אלנחלה לבני אסראיל. מן סבט אלי' סבט",
         "So that this inheritance shall not pass among the sons of Israel from tribe to tribe"),
        ("כִּי אִישׁ בְּנַחֲלַת מַטֵּה אֲבֹתָיו יִדְבְּקוּ בְּנֵי יִשְׂרָאֵל",
         "אלא ילזם כל סבט מנהם נחלה אבאיה",
         "rather, every tribe among them shall cleave to the inheritance of its fathers"),
    ],
    8: [
        ("וְכָל-בַּת יֹרֶשֶׁת נַחֲלָה מִמַּטּוֹת בְּנֵי יִשְׂרָאֵל",
         "וכד'א חכם כל בנת תרת' נחלה",
         "And likewise is the ruling for every daughter who inherits an inheritance"),
        ("לְאֶחָד מִמִּשְׁפַּחַת מַטֵּה אָבִיהָ תִּהְיֶה לְאִשָּׁה",
         "מן בעץ' עשירה' סבט אביהא תכון זוגה",
         "she shall become wife to one of the clan of the tribe of her father"),
        ("לְמַעַן יִירְשׁוּ בְּנֵי יִשְׂרָאֵל אִישׁ נַחֲלַת אֲבֹתָיו",
         "לכי ירת' כל סבט מנהם נחלה' אבאיה",
         "so that every tribe among them shall inherit the inheritance of its fathers"),
    ],
    10: [
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה כֵּן עָשׂוּ בְּנוֹת צְלָפְחָד",
         "פצנען בנאת צלפחד. כמא אמר אללה מוסי'",
         "And the daughters of Zelophehad did as God commanded Moses."),
    ],
    11: [
        ("וַתִּהְיֶינָה מַחְלָה תִרְצָה וְחָגְלָה וּמִלְכָּה וְנֹעָה--בְּנוֹת צְלָפְחָד",
         "פצארתא מחלה תרצה וחגלה ומלכה ונועה בנאת צלפחד",
         "And Mahlah, Tirzah, Hoglah, Milkah, and Noah — the daughters of Zelophehad"),
        ("לִבְנֵי דֹדֵיהֶן לְנָשִׁים", "נסאא לבני אעמאמהן",
         "became wives to the sons of their paternal uncles"),
    ],
    12: [
        ("מִמִּשְׁפְּחֹת בְּנֵי-מְנַשֶּׁה בֶן-יוֹסֵף הָיוּ לְנָשִׁים",
         "מן עשירה' סבט מנשה אבן יוסף צארן נסאא",
         "From the clan of the tribe of Manasseh son of Joseph they became wives"),
        ("וַתְּהִי נַחֲלָתָן עַל-מַטֵּה מִשְׁפַּחַת אֲבִיהֶן",
         "פכאנת נחלתהן. לעשירה סבט אביהן",
         "and their inheritance remained with the clan of the tribe of their father"),
    ],
    13: [
        ("אֵלֶּה הַמִּצְו‍ֹת וְהַמִּשְׁפָּטִים אֲשֶׁר צִוָּה יְהוָה בְּיַד-מֹשֶׁה--אֶל-בְּנֵי יִשְׂרָאֵל",
         "הד'א אלוצאיא ואלאחכאם אלתי אמר מוסי' אלי' בני אסראיל",
         "These are the commandments and the ordinances which Moses gave to the sons of Israel"),
        ("בְּעַרְבֹת מוֹאָב עַל יַרְדֵּן יְרֵחוֹ", "פי בידאת מואב. עלי' ארדן יריחא",
         "in the arid wilderness of Moab, on the Jordan of Jericho"),
    ],
    15: [
        ("ְלֹא-תִסֹּב נַחֲלָה מִמַּטֶּה לְמַטֶּה אַחֵר",
         "ולא תדור אייה' נחלה כאנת. מן סבט אלי' סבט אכ'ר",
         "And no inheritance, whatever it may be, shall pass from one tribe to another tribe"),
        ("כִּי-אִישׁ בְּנַחֲלָתוֹ יִדְבְּקוּ מַטּוֹת בְּנֵי יִשְׂרָאֵל",
         "בל ילזם כל סבט. מן בני אסראיל נחלתה",
         "rather, every tribe of the sons of Israel shall cleave to its inheritance"),
    ],
}
