"""Hand-authored alignment triples for Devarim chapter 20.

Word-level: each JA (Saadia) word or tight group is mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings. Words Saadia adds with no Hebrew source (glosses, expansions) carry
he=None and link JA↔English only.

This chapter covers the laws of war: the priest's pre-battle exhortation
(vv. 1–4), the officers' exemption announcements (vv. 5–8), appointment of
commanders (v. 9), the peace-offer rule (vv. 10–12), treatment of distant vs.
Canaanite towns (vv. 13–17), prohibition against corrupting idolaters (v. 18),
and the siege-tree laws (vv. 19–20).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("כִּי-תֵצֵא", "ואד'א כ'רגת", "And when you go out"),
        ("לַמִּלְחָמָה", "לאלחרב", "to war"),
        ("עַל-אֹיְבֶךָ", "עלי' אעדאיך", "against your enemies"),
        ("וְרָאִיתָ", "פראית", "and you see"),
        ("סוּס", "כ'ילא", "horses"),
        ("וָרֶכֶב", "ומראכבא", "and chariots"),
        ("עַם רַב", "קום אכת'ר", "a people more numerous"),
        ("מִמְּךָ", "מנך", "than you"),
        ("לֹא תִירָא", "פלא תכ'אפהם", "do not fear them"),
        ("כִּי-יְהוָה", "אן אללה", "for God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("עִמָּךְ", "מעך", "is with you"),
        ("הַמַּעַלְךָ", "אלמצעדך", "who brought you up"),
        ("מֵאֶרֶץ מִצְרָיִם", "מן בלד מצר", "from the land of Egypt"),
    ],
    2: [
        ("וְהָיָה כְּקָרָבְכֶם", "וענד תקדמכם", "And at your advance"),
        ("אֶל-הַמִּלְחָמָה", "אלי' אלחרב", "to battle"),
        ("וְנִגַּשׁ הַכֹּהֵן", "פליתקדם אלאמאם", "the imām shall come forward"),
        ("וְדִבֶּר", "ויכ'אטב", "and address"),
        ("אֶל-הָעָם", "אלקום", "the people"),
    ],
    3: [
        ("וְאָמַר אֲלֵהֶם", "ויקול להם", "And he shall say to them"),
        ("שְׁמַע יִשְׂרָאֵל", "אסמעו יא אסראיל", "Hear, O Israel"),
        ("אַתֶּם", "אנתם", "you are"),
        ("קְרֵבִים", "מתקדמין", "advancing"),
        ("הַיּוֹם", "אליום", "today"),
        ("לַמִּלְחָמָה", "לאלחרב", "to battle"),
        ("עַל-אֹיְבֵיכֶם", "עלי' אעדאיכם", "against your enemies"),
        ("אַל-יֵרַךְ לְבַבְכֶם", "פלא תרק קלובכם", "Let not your hearts grow faint"),
        ("אַל-תִּירְאוּ", "לא תכ'אפו", "do not fear"),
        ("וְאַל-תַּחְפְּזוּ", "ולא תחפזו", "and do not be driven back"),
        ("וְאַל-תַּעַרְצוּ", "ולא תרהבו", "and do not be overawed"),
        ("מִפְּנֵיהֶם", "מנהם", "by them"),
    ],
    4: [
        ("כִּי יְהוָה", "לאן אללה", "For God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלסאיר נורה", "whose light goes"),
        ("הַהֹלֵךְ עִמָּכֶם", "מעכם", "with you"),
        ("לְהִלָּחֵם לָכֶם עִם-אֹיְבֵיכֶם", "ליחארב לכם אעדאיכם", "shall fight your enemies on your behalf"),
        ("לְהוֹשִׁיעַ אֶתְכֶם", "ויג'יתכם", "and deliver you"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        ("וְדִבְּרוּ הַשֹּׁטְרִים", "יכלמו אלערפא", "the overseers shall address"),
        ("אֶל-הָעָם", "אלקום", "the people"),
        (None, "קאילין", "saying"),
        ("מִי-הָאִישׁ", "אי רגל", "Which man"),
        ("אֲשֶׁר בָּנָה", "בנא", "has built"),
        ("בַיִת-חָדָשׁ", "ביתא גדידא", "a new house"),
        ("וְלֹא חֲנָכוֹ", "ולם ידשנה", "and has not inaugurated it"),
        ("יֵלֵךְ", "פלימץ'", "Let him go"),
        ("וְיָשֹׁב", "וירגע", "and return"),
        ("לְבֵיתוֹ", "אלי' מנזלה", "to his home"),
        ("פֶּן-יָמוּת", "כלא יקתל", "lest he be killed"),
        ("בַּמִּלְחָמָה", "פי אלחרב", "in the battle"),
        ("וְאִישׁ אַחֵר", "ידשנה רגל אכ'ר", "and another man inaugurate it"),
    ],
    6: [
        ("וּמִי-הָאִישׁ", "ואי רגל", "And which man"),
        ("אֲשֶׁר-נָטַע", "ג'רס", "has planted"),
        ("כֶּרֶם", "כרמא", "a vineyard"),
        ("וְלֹא חִלְּלוֹ", "ולם יבד'לה", "and has not yet made it available"),
        ("יֵלֵךְ", "פלימץ'", "Let him go"),
        ("וְיָשֹׁב", "וירגע", "and return"),
        ("לְבֵיתוֹ", "אלי' מנזלה", "to his home"),
        ("פֶּן-יָמוּת", "כלא יקתל", "lest he be killed"),
        ("בַּמִּלְחָמָה", "פי אלחרב", "in the battle"),
        ("וְאִישׁ אַחֵר יְחַלְּלֶנּוּ", "ויבד'לה רגל אכ'ר", "and another man make it available"),
    ],
    7: [
        ("וּמִי-הָאִישׁ", "ואי רגל", "And which man"),
        ("אֲשֶׁר-אֵרַשׂ אִשָּׁה", "אמלך באמראה", "has betrothed a woman"),
        ("וְלֹא לְקָחָהּ", "ולם יזפהא", "and has not yet escorted her to the bridal chamber"),
        ("יֵלֵךְ", "פלימץ'", "Let him go"),
        ("וְיָשֹׁב", "וירגע", "and return"),
        ("לְבֵיתוֹ", "אלי' מנזלה", "to his home"),
        ("פֶּן-יָמוּת", "כלא יקתל", "lest he be killed"),
        ("בַּמִּלְחָמָה", "פי אלחרב", "in the battle"),
        ("וְאִישׁ אַחֵר יִקָּחֶנָּה", "ויזפהא רגל אכ'ר", "and another man escort her"),
    ],
    8: [
        (None, "ת'ם", "Then"),
        ("וְיָסְפוּ הַשֹּׁטְרִים", "יזיד אלערפא", "the overseers shall continue"),
        ("לְדַבֵּר אֶל-הָעָם", "פי מכ'אטבה' אלקום", "to address the people"),
        ("וְאָמְרוּ", "ויקולו", "and say"),
        ("מִי-הָאִישׁ הַיָּרֵא", "אי רגל כ'איף", "Which man is fearful"),
        ("וְרַךְ הַלֵּבָב", "ורקיק אלקלב", "and faint of heart"),
        ("יֵלֵךְ", "פלימץ'", "Let him go"),
        ("וְיָשֹׁב", "וירגע", "and return"),
        ("לְבֵיתוֹ", "אלי' מנזלה", "to his home"),
        ("וְלֹא יִמַּס אֶת-לְבַב אֶחָיו", "ולא ירק קלוב אכ'ותה", "and not cause the hearts of his brothers to grow faint"),
        ("כִּלְבָבוֹ", "כקלבה", "as his own heart"),
    ],
    9: [
        ("וְהָיָה כְּכַלֹּת הַשֹּׁטְרִים", "פענד פראג'הם", "And upon their finishing"),
        ("לְדַבֵּר אֶל-הָעָם", "מן מכ'אטבה' אלקום", "to address the people"),
        (None, "בד'אלך", "with this"),
        ("וּפָקְדוּ שָׂרֵי צְבָאוֹת", "פיוכלו בהם רויסא אלגיוש", "commanders of the armies shall be appointed over them"),
    ],
    10: [
        ("כִּי-תִקְרַב", "ואד'א תקדמת", "And when you advance"),
        ("אֶל-עִיר", "אלי' קריה", "against a town"),
        ("לְהִלָּחֵם עָלֶיהָ", "לתחארבהא", "to make war upon it"),
        ("וְקָרָאתָ אֵלֶיהָ", "פנאדהא אוולא", "you shall first call out to it"),
        ("לְשָׁלוֹם", "בסלאם", "with an offer of peace"),
    ],
    11: [
        ("וְהָיָה אִם-שָׁלוֹם תַּעַנְךָ", "פאן אגאבתך באלסלאם", "And if it answers you with peace"),
        ("וּפָתְחָה לָךְ", "ופתחת לך", "and opens to you"),
        ("וְהָיָה כָּל-הָעָם", "פגמיע אלקום", "then all the people"),
        ("הַנִּמְצָא-בָהּ", "אלמוגודין פיהא", "found in it"),
        ("יִהְיוּ לְךָ לָמַס", "יכונו לך ד'מה", "shall be a protected tributary to you"),
        ("וַעֲבָדוּךָ", "ויכ'דמונך", "and shall serve you"),
    ],
    12: [
        ("וְאִם-לֹא תַשְׁלִים עִמָּךְ", "ואן לם תסאלמך", "But if it does not make peace with you"),
        (None, "בל", "and instead"),
        ("וְעָשְׂתָה עִמְּךָ מִלְחָמָה", "חארבתך", "makes war against you"),
        ("וְצַרְתָּ עָלֶיהָ", "פחאצרהא", "then besiege it"),
    ],
    13: [
        ("וּנְתָנָהּ יְהוָה אֱלֹהֶיךָ", "ויסלמהא אללה רבך", "And God your Lord shall deliver it"),
        ("בְּיָדֶךָ", "פי ידך", "into your hand"),
        ("וְהִכִּיתָ", "פאקתל", "and you shall kill"),
        ("אֶת-כָּל-זְכוּרָהּ", "רגאלהא", "its men"),
        ("לְפִי-חָרֶב", "בחד אלסיף", "by the edge of the sword"),
    ],
    14: [
        ("רַק הַנָּשִׁים", "ואמא אלנסא", "But as for the women"),
        ("וְהַטַּף", "ואלאטפאל", "and the children"),
        ("וְהַבְּהֵמָה", "ואלבהאים", "and the beasts"),
        ("וְכֹל אֲשֶׁר יִהְיֶה בָעִיר", "וסאיר מא פי אלקריה", "and the rest of what is in the town"),
        ("כָּל-שְׁלָלָהּ", "מן סלבהא", "all its spoil"),
        ("תָּבֹז לָךְ", "פאג'נמה לך", "take it for yourself as plunder"),
        ("וְאָכַלְתָּ אֶת-שְׁלַל אֹיְבֶיךָ", "וכל סלב אעדאיאך", "and consume all the spoil of your enemies"),
        ("אֲשֶׁר נָתַן יְהוָה אֱלֹהֶיךָ לָךְ", "אלד'י רזקך אללה רבך", "which God your Lord has provided you"),
    ],
    15: [
        (None, "כד'אך", "Thus"),
        ("כֵּן תַּעֲשֶׂה", "אצנע", "shall you do"),
        ("לְכָל-הֶעָרִים הָרְחֹקֹת", "באלקרא", "to the towns"),
        (None, "אלבעידה", "very far"),
        ("מִמְּךָ מְאֹד", "מנך גדא", "from you"),
        ("אֲשֶׁר לֹא-מֵעָרֵי הַגּוֹיִם-הָאֵלֶּה הֵנָּה", "אלתי ליס הי מן קרא הולאי אלאמם", "which are not among the towns of these nations"),
    ],
    16: [
        ("רַק מֵעָרֵי הָעַמִּים הָאֵלֶּה", "ואמא מן קרא הולאי אלאמם", "But as for the towns of these nations"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלד'י אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ נַחֲלָה", "מעטיך נחלה", "is giving you as an inheritance"),
        ("לֹא תְחַיֶּה כָּל-נְשָׁמָה", "פלא תבקי מנהם נסמה", "you shall not leave alive in them a single soul"),
    ],
    17: [
        (None, "בל", "Rather"),
        ("כִּי-הַחֲרֵם תַּחֲרִימֵם", "אתלפהם אתלאפא", "destroy them utterly"),
        ("הַחִתִּי", "אלחתיין", "the Hittites"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("הַכְּנַעֲנִי", "אלכנעאניין", "the Canaanites"),
        ("וְהַפְּרִזִּי", "ואלפרזיין", "and the Perizzites"),
        ("הַחִוִּי", "ואלחויין", "and the Hivites"),
        ("וְהַיְבוּסִי", "ואליבוסיין", "and the Jebusites"),
        ("כַּאֲשֶׁר צִוְּךָ יְהוָה אֱלֹהֶיךָ", "כמא אמרך אללה רבך", "as God your Lord has commanded you"),
    ],
    18: [
        ("לְמַעַן אֲשֶׁר לֹא-יְלַמְּדוּ אֶתְכֶם", "לכי לא יעלמוכם", "So that they do not teach you"),
        ("לַעֲשׂוֹת", "אן תצנעו", "to do"),
        ("כְּכֹל תּוֹעֲבֹתָם", "כגמיע מכארההם", "according to all their abominations"),
        ("אֲשֶׁר עָשׂוּ", "אלד'י צנעוהא", "which they performed"),
        ("לֵאלֹהֵיהֶם", "למעבודאתהם", "for their idols"),
        ("וַחֲטָאתֶם", "פתכ'טו", "and you would thereby sin"),
        ("לַיהוָה אֱלֹהֵיכֶם", "ללה רבכם", "against God your Lord"),
    ],
    19: [
        ("כִּי-תָצוּר", "ואד'א חאצרת", "And when you besiege"),
        ("אֶל-עִיר", "קריה", "a town"),
        ("יָמִים רַבִּים", "אייאם כתירה", "many days"),
        ("לְהִלָּחֵם עָלֶיהָ", "לתחארבהא", "fighting against it"),
        ("לְתָפְשָׂהּ", "לתפתחהא", "to open it"),
        ("לֹא-תַשְׁחִית אֶת-עֵצָהּ", "פלא תפסד שגרהא", "do not destroy its trees"),
        ("לִנְדֹּחַ עָלָיו גַּרְזֶן", "באן תחרך עליה אלחדיד", "by raising an axe against them"),
        ("כִּי מִמֶּנּוּ תֹאכֵל", "אד' מנה תאכל", "for from them you eat"),
        ("וְאֹתוֹ לֹא תִכְרֹת", "פלא תקטעה", "do not cut them down"),
        (None, "]ט'נא] צ'נא מנך", "Do you suppose"),
        ("כִּי הָאָדָם עֵץ הַשָּׂדֶה", "אן שגר אלצחרא כאלאנסאן", "that the trees of the wilderness are like a man"),
        ("לָבֹא מִפָּנֶיךָ בַּמָּצוֹר", "אלד'י קד אכ'תפא מן בין ידיך פי אלחצאר", "who has taken cover before you in the siege"),
    ],
    20: [
        (None, "לכן", "However"),
        ("רַק עֵץ", "אי שגר", "any tree"),
        ("אֲשֶׁר-תֵּדַע", "עלמתה", "that you know"),
        ("כִּי-לֹא-עֵץ מַאֲכָל הוּא", "אנה ליס במטעם", "is not a food-bearing tree"),
        ("אֹתוֹ תַשְׁחִית", "פאפסדה", "that you may destroy"),
        ("וְכָרָתָּ", "ואקטעה", "and cut down"),
        ("וּבָנִיתָ מָצוֹר", "ואבן אלאת אלחצאר", "and build the siege-works"),
        ("עַל-הָעִיר", "עלי' אייה' קריה", "against whichever town"),
        ("אֲשֶׁר-הִוא עֹשָׂה עִמְּךָ מִלְחָמָה", "חארבתך", "has made war against you"),
        ("עַד רִדְתָּהּ", "אלי' אן תהדהא", "until you bring it down"),
    ],
}
