"""Hand-authored alignment triples for Devarim chapter 28.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the full Tochecha: blessings (vv. 1–14) with the recurring
בָּרוּךְ formula, followed by curses (vv. 15–68) with the אָרוּר / affliction
sequence — diseases, exile, siege, and famine — and closes with the covenant
summary (v. 69). Aligned with care for the blessing/curse parallelism, the
disease vocabulary (שַׁחֶפֶת, קַדַּחַת, שְׁחִין, etc.), and Saadia's frequent
interpretive expansions.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואעלם", "And know"),
        (None, "אנך", "that"),
        ("וְהָיָה אִם-שָׁמוֹעַ תִּשְׁמַע", "אן סמעת ואטעת", "if you hear and obey"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אמר אללה רבך", "the command of God your Lord"),
        ("לִשְׁמֹר", "לתחפץ'", "to keep"),
        ("לַעֲשׂוֹת", "ותעמל", "and to do"),
        ("אֶת-כָּל-מִצְו‍ֹתָיו", "גמיע וצאיאה", "all His commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלתי אנא אמרך בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "today"),
        ("וּנְתָנְךָ יְהוָה אֱלֹהֶיךָ", "געלך אללה רבך", "God your Lord shall set you"),
        ("עֶלְיוֹן", "עאליא", "high"),
        ("עַל כָּל-גּוֹיֵי הָאָרֶץ", "עלי' סאיר אמם אלארץ'", "above all the rest of the nations of the earth"),
    ],
    2: [
        ("וּבָאוּ עָלֶיךָ", "חלת בך", "shall come upon you"),
        ("כָּל-הַבְּרָכוֹת הָאֵלֶּה", "גמיע הד'ה אלברכאת", "All these blessings"),
        ("וְהִשִּׂיגֻךָ", "ואדרכתך", "and overtake you"),
        ("כִּי תִשְׁמַע", "אד' סמעת", "since you have heard"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אמר אללה רבך", "the command of God your Lord"),
    ],
    3: [
        ("בָּרוּךְ", "וצרת מבארכא", "And you shall be blessed"),
        ("בָּעִיר", "פי אלחצ'ר", "in the settlement"),
        ("וּבָרוּךְ", "ומבארכא", "and blessed"),
        ("בַּשָּׂדֶה", "פי אלבר", "in the open wilderness"),
    ],
    4: [
        ("בָּרוּךְ", "ומבארכא", "Blessed shall be"),
        ("פְּרִי-בִטְנְךָ", "ת'מר גסמך", "the fruit of your body"),
        ("וּפְרִי אַדְמָתְךָ", "ות'מר ריאצ'ך", "and the fruit of your gardens"),
        ("וּפְרִי בְהֶמְתֶּךָ", "ות'מר בהאימך", "and the fruit of your beasts"),
        ("שְׁגַר אֲלָפֶיךָ", "נתאג בקרך", "the offspring of your cattle"),
        ("וְעַשְׁתְּרוֹת צֹאנֶךָ", "וגפראת ג'נמך", "and the young of your flocks"),
    ],
    5: [
        ("בָּרוּךְ", "ומבארכא", "And blessed shall be"),
        ("טַנְאֲךָ", "מא פי בנאיגך", "what is in your panniers"),
        ("וּמִשְׁאַרְתֶּךָ", "ומשאורך", "and your kneading-troughs"),
    ],
    6: [
        ("בָּרוּךְ", "וצרת מבארכא", "And you shall be blessed"),
        ("בְּבֹאֶךָ", "פי דכ'ולך", "in your entering"),
        ("וּבָרוּךְ", "ומבארכא", "and blessed"),
        ("בְּצֵאתֶךָ", "פי כ'רוגך", "in your going out"),
    ],
    7: [
        ("יִתֵּן יְהוָה", "ויגעל אללה", "And God shall make"),
        ("אֶת-אֹיְבֶיךָ", "אעדאיך", "your enemies"),
        ("הַקָּמִים עָלֶיךָ", "אלמקאומין לך", "who rise up against you"),
        ("נִגָּפִים", "מצדומין", "to be stricken"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("בְּדֶרֶךְ אֶחָד", "פי טריק ואחדה", "by one road"),
        ("יֵצְאוּ אֵלֶיךָ", "יכ'רגון אליך", "they shall come out against you"),
        ("וּבְשִׁבְעָה דְרָכִים", "ופי סבע טרק", "and by seven roads"),
        ("יָנוּסוּ לְפָנֶיךָ", "יהרבון מן בין ידיך", "they shall flee from before you"),
    ],
    8: [
        ("יְצַו יְהוָה אִתְּךָ", "ויאמר אללה לך", "And God shall command"),
        ("אֶת-הַבְּרָכָה", "בברכתה", "His blessing upon you"),
        ("בַּאֲסָמֶיךָ", "פי אהראיך", "in your granaries"),
        ("וּבְכֹל מִשְׁלַח יָדֶךָ", "ופי גמיע ממד ידך", "and in all the work of your hand"),
        ("וּבֵרַכְךָ", "ויבארך לך", "and He shall bless you"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-יְהוָה אֱלֹהֶיךָ נֹתֵן לָךְ", "אלד'י אללה רבך מעטיך", "which God your Lord is giving you"),
    ],
    9: [
        ("יְקִימְךָ יְהוָה", "וינצבך אללה", "And God shall establish you"),
        ("לוֹ לְעַם קָדוֹשׁ", "לה שעבא מקדסא", "for Himself as a holy people"),
        ("כַּאֲשֶׁר נִשְׁבַּע-לָךְ", "כמא ועדך", "as He promised you"),
        ("כִּי תִשְׁמֹר", "אד' תחפץ'", "when you keep"),
        ("אֶת-מִצְו‍ֹת יְהוָה אֱלֹהֶיךָ", "וצאיאה", "His commandments"),
        ("וְהָלַכְתָּ בִּדְרָכָיו", "ותסיר פי טרקה", "and walk in His ways"),
    ],
    10: [
        ("וְרָאוּ", "פינצ'ר", "shall see"),
        ("כָּל-עַמֵּי הָאָרֶץ", "גמיע אמם אלארץ'", "And all the nations of the earth"),
        ("כִּי שֵׁם יְהוָה", "אן אסם אללה", "that the name of God"),
        ("נִקְרָא עָלֶיךָ", "קד סמי עליך", "has been called upon you"),
        ("וְיָרְאוּ מִמֶּךָּ", "ויכ'אפונך", "and they shall fear you"),
    ],
    11: [
        ("וְהוֹתִרְךָ יְהוָה לְטוֹבָה", "ויזידך אללה כ'ירא", "And God shall increase your good"),
        ("בִּפְרִי בִטְנְךָ", "פי ת'מר גסמך", "in the fruit of your body"),
        ("וּבִפְרִי בְהֶמְתְּךָ", "ות'מר בהאימך", "and the fruit of your beasts"),
        ("וּבִפְרִי אַדְמָתֶךָ", "ות'מר ריאצ'ך", "and the fruit of your gardens"),
        ("עַל הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר נִשְׁבַּע יְהוָה לַאֲבֹתֶיךָ", "אלד'י קסם לאבאיך", "which He swore to your fathers"),
        ("לָתֶת לָךְ", "אן יעטיך", "that He would give you"),
    ],
    12: [
        ("יִפְתַּח יְהוָה לְךָ", "ויפתח אללה לך", "And God shall open for you"),
        ("אֶת-אוֹצָרוֹ הַטּוֹב", "כ'זאין כ'ירה", "His good treasuries"),
        ("אֶת-הַשָּׁמַיִם", "מן אלסמא", "from the sky"),
        ("לָתֵת מְטַר-אַרְצְךָ בְּעִתּוֹ", "וינזל מטר בלדך פי וקתה", "to send down the rain of your land in its season"),
        ("וּלְבָרֵךְ אֵת כָּל-מַעֲשֵׂה יָדֶךָ", "ויבארך לך פי גמיע עמל ידך", "and to bless you in all the work of your hand"),
        ("וְהִלְוִיתָ גּוֹיִם רַבִּים", "חתי' תקרץ' אממא כת'ירה", "so that you shall lend to many nations"),
        ("וְאַתָּה לֹא תִלְוֶה", "ואנת פלא תקתרץ'", "and you shall not borrow"),
    ],
    13: [
        ("וּנְתָנְךָ יְהוָה לְרֹאשׁ", "ויגעלך אללה ראסא", "And God shall make you a head"),
        ("וְלֹא לְזָנָב", "ולא ד'נבא", "and not a tail"),
        ("וְהָיִיתָ רַק לְמַעְלָה", "ותכון עאליא מחצ'א", "and you shall be only on top"),
        ("וְלֹא תִהְיֶה לְמָטָּה", "ולא תכון מסתספלא", "and not be brought low"),
        ("כִּי-תִשְׁמַע אֶל-מִצְו‍ֹת יְהוָה אֱלֹהֶיךָ", "אד' תקבל וצאיא אללה רבך", "when you accept the commandments of God your Lord"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", "אלד'י אנא אמרך בהא אליום", "which I command you today"),
        ("לִשְׁמֹר", "לתחפצ'הא", "to keep them"),
        ("וְלַעֲשׂוֹת", "ותעמל בהא", "and to do by them"),
    ],
    14: [
        ("וְלֹא תָסוּר", "ולא תזול", "And do not deviate"),
        ("מִכָּל-הַדְּבָרִים", "מן גמיע אלאמור", "from any of the things"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם הַיּוֹם", "אלד'י אנא אמרך בהא. אליום", "which I command you today"),
        ("יָמִין", "ימנה", "right"),
        ("וּשְׂמֹאול", "ולא יסרה", "or left"),
        ("לָלֶכֶת אַחֲרֵי אֱלֹהִים אֲחֵרִים", "פתתבע מעבודאת אכ'ר", "so as to follow other objects of worship"),
        ("לְעָבְדָם", "פתעבדהא", "and serve them"),
    ],
    15: [
        ("וְהָיָה אִם-לֹא תִשְׁמַע", "ואן לם תקבל", "But if you do not accept"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אמר אללה רבך", "the command of God your Lord"),
        ("לִשְׁמֹר", "לתחפץ'", "to keep"),
        ("לַעֲשׂוֹת", "ותעמל", "and to do"),
        ("אֶת-כָּל-מִצְו‍ֹתָיו", "גמיע וצאיאה", "all His commandments"),
        ("וְחֻקֹּתָיו", "ורסומה", "and statutes"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", "אלתי אמרך בהא אליום", "which I command you today"),
        ("וּבָאוּ עָלֶיךָ", "חלת בך", "shall come upon you"),
        ("כָּל-הַקְּלָלוֹת הָאֵלֶּה", "גמיע הד'ה אללענאת", "then all these curses"),
        ("וְהִשִּׂיגוּךָ", "ואדרכתך", "and overtake you"),
    ],
    16: [
        ("אָרוּר", "וכנת מלעונא", "And you shall be cursed"),
        ("בָּעִיר", "פי אלחצ'ר", "in the settlement"),
        ("וְאָרוּר", "ומלעונא", "and cursed"),
        ("בַּשָּׂדֶה", "פי אלבר", "in the open wilderness"),
    ],
    17: [
        ("אָרוּר", "ומלעונא", "And cursed shall be"),
        ("טַנְאֲךָ", "מא פי בנאיגך", "what is in your panniers"),
        ("וּמִשְׁאַרְתֶּךָ", "ומשאורך", "and your kneading-troughs"),
    ],
    18: [
        ("אָרוּר", "ומלעון", "And cursed shall be"),
        ("פְּרִי-בִטְנְךָ", "ת'מר גסמך", "the fruit of your body"),
        ("וּפְרִי אַדְמָתֶךָ", "ות'מר ארצ'ך", "and the fruit of your land"),
        ("שְׁגַר אֲלָפֶיךָ", "נתאג בקרך", "the offspring of your cattle"),
        ("וְעַשְׁתְּרֹת צֹאנֶךָ", "וגפראת ג'נמך", "and the young of your flocks"),
    ],
    19: [
        ("אָרוּר", "וצרת מלעון", "And you shall be cursed"),
        ("בְּבֹאֶךָ", "פי דכ'ולך", "in your entering"),
        ("וְאָרוּר", "ומלעון", "and cursed"),
        ("בְּצֵאתֶךָ", "פי כ'רוגך", "in your going out"),
    ],
    20: [
        ("יְשַׁלַּח יְהוָה בְּךָ", "ויבעת' אללה עליך", "And God shall send upon you"),
        ("אֶת-הַמְּאֵרָה", "אלמחק", "ruin"),
        ("אֶת-הַמְּהוּמָה", "ואלאהאמה", "and confusion"),
        ("וְאֶת-הַמִּגְעֶרֶת", "ואלזגרה", "and rebuke"),
        ("בְּכָל-מִשְׁלַח יָדְךָ אֲשֶׁר תַּעֲשֶׂה", "פי גמיע ממד ידך אלד'י תצנעה", "in all the work of your hand that you do"),
        ("עַד הִשָּׁמֶדְךָ", "אלי' אנפאד'ך", "until your destruction"),
        ("וְעַד-אֲבָדְךָ מַהֵר", "ואבאדתך סריעא", "and your swift annihilation"),
        (None, "ויקול", "and they shall say"),
        ("מִפְּנֵי רֹעַ מַעֲלָלֶיךָ", "מן קבל סו שמאילך", "because of the evil of your ways"),
        ("אֲשֶׁר עֲזַבְתָּנִי", "אד' תרכתני", "in that you have forsaken Me"),
    ],
    21: [
        ("יַדְבֵּק יְהוָה בְּךָ", "וילזמך אללה", "And God shall fasten upon you"),
        ("אֶת-הַדָּבֶר", "אלובא", "the pestilence"),
        ("עַד כַּלֹּתוֹ אֹתְךָ", "אלי' אן יפניך", "until He has consumed you"),
        ("מֵעַל הָאֲדָמָה", "מן אלארץ'", "from the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה לְרִשְׁתָּהּ", "אלד'י אנת דאכ'ל אליה לתחוזה", "which you are entering to possess"),
    ],
    22: [
        ("יַכְּכָה יְהוָה", "ויצ'רבך אללה", "And God shall strike you"),
        ("בַּשַּׁחֶפֶת", "בחמא אלסל", "with the fever of consumption"),
        ("וּבַקַּדַּחַת", "ואלחארה", "and with burning heat"),
        ("וּבַדַּלֶּקֶת", "ואלרבע", "and with quartan fever"),
        ("וּבַחַרְחֻר", "ואלפאלג", "and with palsy"),
        ("וּבַחֶרֶב", "ואלגפאף", "and with drought"),
        ("וּבַשִּׁדָּפוֹן", "ואלשוב", "and with scorching wind"),
        ("וּבַיֵּרָקוֹן", "ואלירקאן", "and with jaundice"),
        ("וּרְדָפוּךָ עַד אָבְדֶךָ", "פיכלבונך אלי' אבאדתך", "they shall pursue you until your destruction"),
    ],
    23: [
        ("וְהָיוּ שָׁמֶיךָ", "ותכון סמאך", "And your sky"),
        ("אֲשֶׁר עַל-רֹאשְׁךָ", "אלד'י פוק ראסך", "which is above your head"),
        ("נְחֹשֶׁת", "כאלנחאס", "shall be like copper"),
        ("וְהָאָרֶץ אֲשֶׁר-תַּחְתֶּיךָ", "ואלארץ' אלד'י תחתך", "and the earth which is beneath you"),
        ("בַּרְזֶל", "כאלחדיד", "like iron"),
    ],
    24: [
        ("יִתֵּן יְהוָה", "ויגעל אללה", "And God shall make"),
        ("אֶת-מְטַר אַרְצְךָ", "מא ימטרה עלי' ארצ'ך", "the water of His rain upon your land"),
        ("אָבָק", "ג'בארא", "into dust"),
        ("וְעָפָר", "ותראבא", "and earth"),
        ("מִן-הַשָּׁמַיִם יֵרֵד עָלֶיךָ", "מן אלסמא ירד עליך", "from the sky it shall scatter down upon you"),
        ("עַד הִשָּׁמְדָךְ", "אלי' אנפאד'ך", "until your destruction"),
    ],
    25: [
        ("יִתֶּנְךָ יְהוָה נִגָּף", "ויגעלך אללה. מצדומא", "And God shall make you to be stricken"),
        ("לִפְנֵי אֹיְבֶיךָ", "בין ידי אעדאיך", "before your enemies"),
        ("בְּדֶרֶךְ אֶחָד תֵּצֵא אֵלָיו", "חתי' תכ'רג אליהם פי טריק ואחדה", "by one road you shall go out against them"),
        ("וּבְשִׁבְעָה דְרָכִים תָּנוּס לְפָנָיו", "ותהרב מן בין ידיהם פי סבע טרק", "and by seven roads you shall flee from before them"),
        ("וְהָיִיתָ לְזַעֲוָה", "ותציר עברה", "and you shall become a lesson"),
        ("לְכֹל מַמְלְכוֹת הָאָרֶץ", "לגמיע ממאלך אלארץ'", "to all the kingdoms of the earth"),
    ],
    26: [
        ("וְהָיְתָה נִבְלָתְךָ", "ותציר גת'תך", "And your corpse shall become"),
        ("לְמַאֲכָל", "מאכלא", "food"),
        ("לְכָל-עוֹף הַשָּׁמַיִם", "לטאיר אלסמא", "for the bird of the sky"),
        ("וּלְבֶהֱמַת הָאָרֶץ", "ובהאים אלארץ'", "and the beasts of the earth"),
        ("וְאֵין מַחֲרִיד", "וליס מזעג להא", "with none to frighten them away"),
    ],
    27: [
        ("יַכְּכָה יְהוָה", "ויצ'רבך אללה", "And God shall strike you"),
        ("בִּשְׁחִין מִצְרַיִם", "בקרח מצר", "with the boil of Egypt"),
        ("ובעפלים", "ואלבואסיר", "and with hemorrhoids"),
        ("וּבַגָּרָב", "ואלגרב", "and with scab"),
        ("וּבֶחָרֶס", "ואלחכה", "and with itch"),
        ("אֲשֶׁר לֹא-תוּכַל לְהֵרָפֵא", "מא לם תסתטיע מדאואתה", "which you shall not be able to cure"),
    ],
    28: [
        ("יַכְּכָה יְהוָה", "ויצ'רבך אללה", "And God shall strike you"),
        ("בְּשִׁגָּעוֹן", "באלגנאן", "with madness"),
        ("וּבְעִוָּרוֹן", "ואלעמא", "and with blindness"),
        ("וּבְתִמְהוֹן לֵבָב", "ובהתה' אלקלב", "and with bewilderment of heart"),
    ],
    29: [
        ("וְהָיִיתָ מְמַשֵּׁשׁ", "באן תציר כאלמגסס", "So that you shall grope about like one feeling his way"),
        ("בַּצָּהֳרַיִם", "פי אלצ'הירה", "at noon"),
        ("כַּאֲשֶׁר יְמַשֵּׁשׁ הַעִוֵּר", "כמא יגסס אלאעמא", "as the blind man gropes"),
        ("בָּאֲפֵלָה", "וכ'אצה פי אלאפל", "and especially in darkness"),
        ("וְלֹא תַצְלִיחַ אֶת-דְּרָכֶיךָ", "ולא תנגח טרקך", "and your ways shall not prosper"),
        ("וְהָיִיתָ אַךְ עָשׁוּק", "ותציר מג'שומא", "and you shall be only oppressed"),
        ("וְגָזוּל", "מג'צובא", "and plundered"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "all the time"),
        ("וְאֵין מוֹשִׁיעַ", "וליס מג'ית'", "with no one to save you"),
    ],
    30: [
        ("אִשָּׁה תְאָרֵשׂ", "באן תתזווג אמראה", "If you marry a woman"),
        ("וְאִישׁ אַחֵר ישגלנה", "פיאתיהא רגל אכ'ר", "another man shall come to her"),
        ("בַּיִת תִּבְנֶה", "ותבני ביתא", "and you shall build a house"),
        ("וְלֹא-תֵשֵׁב בּוֹ", "ולא תגלס פיה", "but not dwell in it"),
        ("כֶּרֶם תִּטַּע", "ותג'רס כרמא", "and you shall plant a vineyard"),
        ("וְלֹא תְחַלְּלֶנּוּ", "ולא תתבד'לה", "but not use its fruit"),
    ],
    31: [
        ("שׁוֹרְךָ טָבוּחַ", "ויכון ת'ורך מד'בוח", "And your ox shall be slaughtered"),
        ("לְעֵינֶיךָ", "חד'א עינאך", "before your eyes"),
        ("וְלֹא תֹאכַל מִמֶּנּוּ", "ולא תאכל מנה", "and you shall not eat of it"),
        ("חֲמֹרְךָ גָּזוּל", "וחמארך מג'צוב", "and your donkey shall be plundered"),
        ("מִלְּפָנֶיךָ", "מן בין ידיך", "from before you"),
        ("וְלֹא יָשׁוּב לָךְ", "ולא ירגע אליך", "and shall not return to you"),
        ("צֹאנְךָ נְתֻנוֹת לְאֹיְבֶיךָ", "וג'נמך מסלמה לאעדאיך", "and your flock shall be given over to your enemies"),
        ("וְאֵין לְךָ מוֹשִׁיעַ", "וליס לך מג'ית'", "with no one to save you"),
    ],
    32: [
        ("בָּנֶיךָ וּבְנֹתֶיךָ", "ובניך ובנאתך", "Your sons and your daughters"),
        ("נְתֻנִים לְעַם אַחֵר", "מדפועין אלי' קום אכ'רין", "shall be handed over to another people"),
        ("וְעֵינֶיךָ רֹאוֹת", "ועינאך תראהם", "and your eyes shall see them"),
        ("וְכָלוֹת אֲלֵיהֶם", "ושאכ'צה אליהם", "staring toward them"),
        ("כָּל-הַיּוֹם", "טול אלזמאן", "all the time"),
        ("וְאֵין לְאֵל יָדֶךָ", "ולא טאקה פי ידך", "with no power in your hand"),
    ],
    33: [
        ("פְּרִי אַדְמָתְךָ", "ות'מר ארצ'ך", "And the fruit of your land"),
        ("וְכָל-יְגִיעֲךָ", "וסאיר כסבך", "and the rest of your earnings"),
        ("יֹאכַל עַם", "יאכלה קום", "shall be eaten by a people"),
        ("אֲשֶׁר לֹא-יָדָעְתָּ", "לא תערפהם", "you do not know"),
        ("וְהָיִיתָ רַק עָשׁוּק", "ותציר כד'אך. מג'שומא", "and you shall be thus — oppressed"),
        ("וְרָצוּץ", "מעסופא", "and crushed"),
        ("כָּל-הַיָּמִים", "טול אלזמן", "all the time"),
    ],
    34: [
        ("וְהָיִיתָ מְשֻׁגָּע", "חתי' תציר מעתוהא", "Until you become demented"),
        ("מִמַּרְאֵה עֵינֶיךָ", "מן נצ'ר עינאך", "from the sight of your eyes"),
        ("אֲשֶׁר תִּרְאֶה", "אלד'י תראה", "that you see"),
    ],
    35: [
        ("יַכְּכָה יְהוָה", "ויצ'רבך אללה", "And God shall strike you"),
        ("בִּשְׁחִין רָע", "בקרח רדי", "with a malignant boil"),
        ("עַל-הַבִּרְכַּיִם", "עלי אלרכבתין", "on the knees"),
        ("וְעַל-הַשֹּׁקַיִם", "ואלסאקין", "and on the legs"),
        ("אֲשֶׁר לֹא-תוּכַל לְהֵרָפֵא", "מא לם תסתטיע מדאואתה", "which you shall not be able to cure"),
        ("מִכַּף רַגְלְךָ", "ובמא יולמך מן קדמך", "and that which pains you from your foot"),
        ("וְעַד קָדְקֳדֶךָ", "אלי' האמתך", "to the crown of your head"),
    ],
    36: [
        ("יוֹלֵךְ יְהוָה אֹתְךָ", "ויגליך אללה", "And God shall exile you"),
        ("וְאֶת-מַלְכְּךָ", "ומלכך", "and your king"),
        ("אֲשֶׁר תָּקִים עָלֶיךָ", "אלד'י תנצבה עליך", "whom you shall set over you"),
        ("אֶל-גּוֹי אֲשֶׁר לֹא-יָדַעְתָּ", "אלי' קום לם תערפהם", "to a people whom neither you"),
        ("אַתָּה וַאֲבֹתֶיךָ", "אנת ואבאיך", "nor your fathers have known"),
        ("וְעָבַדְתָּ שָּׁם", "פתכ'דם הנאך", "and there you shall serve"),
        ("אֱלֹהִים אֲחֵרִים", "מעבודאת אכ'ר", "other objects of worship"),
        ("עֵץ וָאָבֶן", "מן כ'שב וחגארה", "of wood and stone"),
    ],
    37: [
        ("וְהָיִיתָ לְשַׁמָּה", "ותציר וחשה", "And you shall become a desolation"),
        ("לְמָשָׁל", "ומת'לה", "a byword"),
        ("וְלִשְׁנִינָה", "וחכאיה", "and a tale"),
        ("בְּכֹל הָעַמִּים", "פי גמיע אלאמם", "among all the nations"),
        ("אֲשֶׁר-יְנַהֶגְךָ יְהוָה שָׁמָּה", "אלד'י יסוקך אללה אלי' ת'ם", "to which God shall drive you"),
    ],
    38: [
        ("זֶרַע רַב תּוֹצִיא הַשָּׂדֶה", "ואד'א תכ'רג אלצחרא בד'רא כת'ירא", "When the open land brings forth much seed"),
        ("וּמְעַט תֶּאֱסֹף", "פקליל מא תגמע מנה", "little shall you gather from it"),
        ("כִּי יַחְסְלֶנּוּ הָאַרְבֶּה", "בל יקצמה אלגראד", "for the locusts shall devour it"),
    ],
    39: [
        ("כְּרָמִים תִּטַּע", "פאד'א תג'רס כרמא", "If you plant a vineyard"),
        ("וְעָבָדְתָּ", "ותפלחהא", "and till it"),
        ("וְיַיִן לֹא-תִשְׁתֶּה", "פלא תשרב מנה כמרא", "you shall not drink wine from it"),
        ("וְלֹא תֶאֱגֹר", "ולא תועיה", "nor store it"),
        ("כִּי תֹאכְלֶנּוּ הַתֹּלָעַת", "בל יאכלה אלדוד", "for the worm shall eat it"),
    ],
    40: [
        ("זֵיתִים יִהְיוּ לְךָ", "פאד'א יכון לך זיאתין", "If you have olive trees"),
        ("בְּכָל-גְּבוּלֶךָ", "פי גמיע תכ'מך", "throughout all your territory"),
        ("וְשֶׁמֶן לֹא תָסוּךְ", "ולא תדהן מנה", "you shall not anoint yourself with the oil"),
        ("כִּי יִשַּׁל זֵיתֶךָ", "בל תנת'רה נתרא", "for it shall scatter its fruit"),
    ],
    41: [
        ("בָּנִים וּבָנוֹת תּוֹלִיד", "ואד'א תולד בנין או בנאת", "And if you beget sons or daughters"),
        ("וְלֹא-יִהְיוּ לָךְ", "פלא יבקון לך", "they shall not remain yours"),
        ("כִּי יֵלְכוּ בַּשֶּׁבִי", "בל יגלון פי אלסבי", "for they shall go into captivity"),
    ],
    42: [
        ("כָּל-עֵצְךָ", "וגמיע שגרך", "And all your trees"),
        ("וּפְרִי אַדְמָתֶךָ", "ות'מר ארצ'ך", "and the fruit of your land"),
        ("יְיָרֵשׁ הַצְּלָצַל", "יקרצ'ה אלפראש", "the locust shall gnaw away"),
    ],
    43: [
        ("הַגֵּר אֲשֶׁר בְּקִרְבְּךָ", "ואלג'ריב אלד'י פי מא בינכם", "The stranger who is among you"),
        ("יַעֲלֶה עָלֶיךָ מַעְלָה מָּעְלָה", "ירתפע עליך עלאוא כבירא", "shall rise above you higher and higher"),
        ("וְאַתָּה תֵרֵד מַטָּה מָּטָּה", "ואנת תנחט ספלא הויא", "while you shall sink lower and lower"),
    ],
    44: [
        ("הוּא יַלְוְךָ", "חתי' אנה יקרצ'ך", "Until he shall lend to you"),
        ("וְאַתָּה לֹא תַלְוֶנּוּ", "ואנת פלא תקרצ'ה", "and you shall not lend to him"),
        ("הוּא יִהְיֶה לְרֹאשׁ", "הו יציר ראסא", "he shall become a head"),
        ("וְאַתָּה תִּהְיֶה לְזָנָב", "ואנת תציר ד'נבא", "and you shall become a tail"),
    ],
    45: [
        ("וּבָאוּ עָלֶיךָ", "ותחל בך", "shall come upon you"),
        ("כָּל-הַקְּלָלוֹת הָאֵלֶּה", "גמיע הד'ה אללענאת", "And all these curses"),
        ("וּרְדָפוּךָ", "ותכלבך", "and pursue you"),
        ("וְהִשִּׂיגוּךָ", "ותדרכך", "and overtake you"),
        ("עַד הִשָּׁמְדָךְ", "אלי' אנפאד'ך", "until your destruction"),
        ("כִּי-לֹא שָׁמַעְתָּ בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אד' לם תקבל אמר אללה רבך", "since you did not accept the command of God your Lord"),
        ("לִשְׁמֹר מִצְו‍ֹתָיו", "ותחפץ' וצאיאה", "and keep His commandments"),
        ("וְחֻקֹּתָיו אֲשֶׁר צִוָּךְ", "ורסומה אלתי אמרך בהא", "and His statutes which I command you"),
    ],
    46: [
        ("וְהָיוּ בְךָ", "ותציר פיך", "And they shall be among you"),
        ("לְאוֹת", "איה", "a sign"),
        ("וּלְמוֹפֵת", "וברהאנא", "and a proof"),
        ("וּבְזַרְעֲךָ", "ובנסלך", "and among your offspring"),
        ("עַד-עוֹלָם", "אלמשאבהין לך אלי' אלדהר", "who resemble you — forever"),
    ],
    47: [
        ("תַּחַת אֲשֶׁר לֹא-עָבַדְתָּ", "בדל מא לם תעבד", "In return for the fact that you did not serve"),
        ("אֶת-יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord"),
        ("בְּשִׂמְחָה", "בפרח", "with joy"),
        ("וּבְטוּב לֵבָב", "וגודה' קלב", "and goodness of heart"),
        ("מֵרֹב כֹּל", "מן כת'רה' אלאשיא", "out of the abundance of all things"),
    ],
    48: [
        ("וְעָבַדְתָּ אֶת-אֹיְבֶיךָ", "פתכ'דם עדווך", "you shall therefore serve your enemy"),
        ("אֲשֶׁר יְשַׁלְּחֶנּוּ יְהוָה בָּךְ", "אלד'י יסלטה אללה עליך", "whom God shall set over you"),
        ("בְּרָעָב", "בגוע", "in hunger"),
        ("וּבְצָמָא", "ועטש", "and in thirst"),
        ("וּבְעֵירֹם", "וערי", "and in nakedness"),
        ("וּבְחֹסֶר כֹּל", "ועוז כל שי", "and in want of everything"),
        ("וְנָתַן עֹל בַּרְזֶל", "ויצ'ע אצרא מן חדיד", "and he shall place a yoke of iron"),
        ("עַל-צַוָּארֶךָ", "עלי' ענקך", "upon your neck"),
        ("עַד הִשְׁמִידוֹ אֹתָךְ", "אלי' אן ינפד'ך", "until he has destroyed you"),
    ],
    49: [
        ("יִשָּׂא יְהוָה עָלֶיךָ", "ויג'זיך אללה", "And God shall send against you"),
        ("גּוֹי מֵרָחֹק", "בקביל מן בעיד", "a nation from afar"),
        ("מִקְצֵה הָאָרֶץ", "מן טרף אלארץ'", "from the end of the earth"),
        ("כַּאֲשֶׁר יִדְאֶה הַנָּשֶׁר", "כמא יתחלק אלנסר", "as the eagle circles"),
        ("גּוֹי אֲשֶׁר לֹא-תִשְׁמַע לְשֹׁנוֹ", "קביל לא תפהם לג'תה", "a nation whose language you shall not understand"),
    ],
    50: [
        ("גּוֹי עַז פָּנִים", "קביל וקיח אלוגה", "A brazen nation"),
        ("אֲשֶׁר לֹא-יִשָּׂא פָנִים לְזָקֵן", "מא לם יחאבי וגה אלשיך'", "which shall show no favor to the old"),
        ("וְנַעַר לֹא יָחֹן", "ולא ירוף עלי צבי", "and shall not have compassion on the young"),
    ],
    51: [
        ("וְאָכַל פְּרִי בְהֶמְתְּךָ", "פיאכל ת'מר בהאימך", "And it shall eat the fruit of your beasts"),
        ("וּפְרִי-אַדְמָתְךָ", "ות'מר ארצ'ך", "and the fruit of your land"),
        ("עַד הִשָּׁמְדָךְ", "אלי' אנפאד'ך", "until your destruction"),
        ("אֲשֶׁר לֹא-יַשְׁאִיר לְךָ דָּגָן", "ולא יבקי לך ברא", "leaving you no grain"),
        ("תִּירוֹשׁ", "ולא עצירא", "no juice"),
        ("וְיִצְהָר", "ולא דהנא", "and no oil"),
        ("שְׁגַר אֲלָפֶיךָ", "ולא נתאג בקרך", "and no offspring of your cattle"),
        ("וְעַשְׁתְּרֹת צֹאנֶךָ", "וגפראת ג'נמך", "and young of your flocks"),
        ("עַד הַאֲבִידוֹ אֹתָךְ", "אלי' אן יבידך", "until it has annihilated you"),
    ],
    52: [
        ("וְהֵצַר לְךָ", "ויחאצרך", "And it shall besiege you"),
        ("בְּכָל-שְׁעָרֶיךָ", "פי גמיע מחאלך", "in all your quarters"),
        ("עַד רֶדֶת חֹמֹתֶיךָ הַגְּבֹהֹת", "אלי' אן יהדם אסוארך אלשאמכ'ה", "until it has broken down your high"),
        ("וְהַבְּצֻרוֹת", "ואלחצינה", "and fortified walls"),
        ("אֲשֶׁר אַתָּה בֹּטֵחַ בָּהֵן", "אלד'י אנת ואת'ק בהא", "in which you trust"),
        ("בְּכָל-אַרְצֶךָ", "פי גמיע בלדך", "throughout all your land"),
        ("וְהֵצַר לְךָ", "ויצ'איקך", "and it shall press you hard"),
        ("בְּכָל-שְׁעָרֶיךָ", "פי גמיע מחאלך", "in all your quarters"),
        ("בְּכָל-אַרְצְךָ אֲשֶׁר נָתַן יְהוָה אֱלֹהֶיךָ לָךְ", "אלד'י אעטאך אללה רבך", "throughout all the land which God your Lord has given you"),
    ],
    53: [
        ("וְאָכַלְתָּ פְרִי-בִטְנְךָ", "חתי' תאכל מן ת'מר בטנך", "Until you eat the fruit of your womb"),
        ("בְּשַׂר בָּנֶיךָ וּבְנֹתֶיךָ", "מן לחם בניך ובנאתך", "the flesh of your sons and your daughters"),
        ("אֲשֶׁר נָתַן-לְךָ יְהוָה אֱלֹהֶיךָ", "אלד'י רזקך אללה רבך", "which God your Lord has provided for you"),
        ("בְּמָצוֹר", "בחצאר", "in the siege"),
        ("וּבְמָצוֹק", "וצ'יק", "and the distress"),
        ("אֲשֶׁר-יָצִיק לְךָ אֹיְבֶךָ", "ממא יחאצרך עדווך", "with which your enemy shall besiege you"),
    ],
    54: [
        ("הָאִישׁ הָרַךְ בְּךָ", "חתי' אן אלרג'ל אלרכ'ץ' מנכם", "So that even the most tender and delicate man among you"),
        ("וְהֶעָנֹג מְאֹד", "ואלמדלל גדא", "shall begrudge"),
        ("תֵּרַע עֵינוֹ בְאָחִיו", "ישח עלי' אכ'יה", "his brother"),
        ("וּבְאֵשֶׁת חֵיקוֹ", "ועלי' חרמתה", "and the wife of his bosom"),
        ("וּבְיֶתֶר בָּנָיו אֲשֶׁר יוֹתִיר", "ובאקי בניה אלד'י יבקיהם", "and the rest of his children whom he has left surviving"),
    ],
    55: [
        ("מִתֵּת לְאַחַד מֵהֶם", "מן אן יעטי אחד מנהם", "from giving any of them"),
        ("מִבְּשַׂר בָּנָיו אֲשֶׁר יֹאכֵל", "מן לחם בניה אלד'י יאכל", "of the flesh of his children that he eats"),
        ("מִבְּלִי הִשְׁאִיר-לוֹ כֹּל", "ממא לם יבק לה שייא", "since nothing has been left to him"),
        ("בְּמָצוֹר", "בחצאר", "in the siege"),
        ("וּבְמָצוֹק", "וצ'יק", "and the distress"),
        ("אֲשֶׁר יָצִיק לְךָ אֹיִבְךָ", "ממא יצ'ייק עליך. עדווך", "with which your enemy shall press you hard"),
        ("בְּכָל-שְׁעָרֶיךָ", "פי גמיע מחאלך", "in all your quarters"),
    ],
    56: [
        ("הָרַכָּה בְךָ", "חתי' אן אלאמראה אלרכ'צ'ה מנכם", "So that even the most tender and delicate woman among you"),
        ("וְהָעֲנֻגָּה", "ואלמדללה", "who has never accustomed her foot"),
        ("אֲשֶׁר לֹא-נִסְּתָה כַף-רַגְלָהּ הַצֵּג עַל-הָאָרֶץ", "אלתי לם תעוד קדמהא אן תצעהא עלי' אלארץ'", "to be set upon the ground"),
        ("מֵהִתְעַנֵּג וּמֵרֹךְ", "מן אלדלאל ואלרכ'צ'ה", "out of delicacy and tenderness"),
        ("תֵּרַע עֵינָהּ בְּאִישׁ חֵיקָהּ", "תשח עלי' זוגהא", "shall begrudge her husband"),
        ("וּבִבְנָהּ", "ואבנהא", "and her son"),
        ("וּבְבִתָּהּ", "ואבנתהא", "and her daughter"),
    ],
    57: [
        ("וּבְשִׁלְיָתָהּ הַיּוֹצֵת מִבֵּין רַגְלֶיהָ", "ובמשימתהא אלסאקטה מנהא", "and her afterbirth that falls from her"),
        ("וּבְבָנֶיהָ אֲשֶׁר תֵּלֵד", "ואגנתהא אלד'י תרמי", "and the infants she delivers"),
        ("כִּי-תֹאכְלֵם", "פתנפרד בהם פתאכלהם", "so that she hoards them to herself and eats them"),
        ("בְּחֹסֶר-כֹּל", "מן עוז אלכל", "out of want of everything"),
        ("בַּסָּתֶר", "פי אלסתר", "in secret"),
        ("בְּמָצוֹר", "בחצאר", "in the siege"),
        ("וּבְמָצוֹק", "וציק", "and the distress"),
        ("אֲשֶׁר יָצִיק לְךָ אֹיִבְךָ", "ממא יצ'ייק עליך. עדווך", "with which your enemy shall press you hard"),
        ("בִּשְׁעָרֶיךָ", "פי מחאלך", "in your quarters"),
    ],
    58: [
        ("אִם-לֹא תִשְׁמֹר לַעֲשׂוֹת", "ואן לם תחפץ' ותעמל", "And if you do not keep and do"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע כלאם הד'ה אלתורייה", "all the words of this Torah"),
        ("הַכְּתֻבִים בַּסֵּפֶר הַזֶּה", "אלמכתובה פי הד'א אלספר", "written in this book"),
        ("לְיִרְאָה", "ותכ'אף", "and do not fear"),
        ("אֶת-הַשֵּׁם הַנִּכְבָּד וְהַנּוֹרָא הַזֶּה", "הד'א אלאסם אלכרים אלמהיוב", "this noble and awe-inspiring Name"),
        ("אֵת יְהוָה אֱלֹהֶיךָ", "הו אללה רבך", "He is God your Lord"),
    ],
    59: [
        ("וְהִפְלָא יְהוָה", "פיגעל אללה", "then God shall make"),
        ("אֶת-מַכֹּתְךָ", "צ'רבאתך", "your plagues"),
        ("וְאֵת מַכּוֹת זַרְעֶךָ", "וצרבאת נסלך אלמד'כורין", "and the plagues of your offspring aforementioned"),
        ("מַכּוֹת גְּדֹלֹת", "צ'רבאת כבאר", "great"),
        ("וְנֶאֱמָנוֹת", "דארה", "and harmful plagues"),
        ("וָחֳלָיִם רָעִים", "ואמראץ' רדייה", "and malignant harmful diseases"),
        ("וְנֶאֱמָנִים", "דארה", "wondrous"),
    ],
    60: [
        ("וְהֵשִׁיב בְּךָ", "וירד עליך", "And He shall bring back upon you"),
        ("אֵת כָּל-מַדְוֵה מִצְרַיִם", "גמיע אדוא מצר", "all the ailments of Egypt"),
        ("אֲשֶׁר יָגֹרְתָּ מִפְּנֵיהֶם", "אלד'י חד'רתהא", "which you dreaded"),
        ("וְדָבְקוּ בָּךְ", "פתלזמך", "and they shall cling to you"),
    ],
    61: [
        ("גַּם כָּל-חֳלִי", "ואיצ'א כל מרץ'", "Also every disease"),
        ("וְכָל-מַכָּה", "וכל צ'רבה", "and every plague"),
        ("אֲשֶׁר לֹא כָתוּב", "ממא ליס הו מכתוב", "that is not written"),
        ("בְּסֵפֶר הַתּוֹרָה הַזֹּאת", "פי ספר הד'ה אלתורייה", "in the book of this Torah"),
        ("יַעְלֵם יְהוָה עָלֶיךָ", "יסלטהא אללה עליך", "God shall set them over you"),
        ("עַד הִשָּׁמְדָךְ", "אלי' אן ינפד'ך", "until He has destroyed you"),
    ],
    62: [
        ("וְנִשְׁאַרְתֶּם בִּמְתֵי מְעָט", "פתבקון רהט דו אחצא", "And you shall be left a numbered band"),
        ("תַּחַת אֲשֶׁר הֱיִיתֶם", "בעד מא כנתם", "after you had been"),
        ("כְּכוֹכְבֵי הַשָּׁמַיִם לָרֹב", "ככואכב אלסמא כת'רה", "as the stars of the sky in multitude"),
        ("כִּי-לֹא שָׁמַעְתָּ", "אד' לם תקבל", "since you did not accept"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אמר אללה רבך", "the command of God your Lord"),
    ],
    63: [
        ("וְהָיָה כַּאֲשֶׁר-שָׂשׂ יְהוָה עֲלֵיכֶם", "פיכון כמא קצד אללה בכם", "And it shall be: just as God intended for you"),
        ("לְהֵיטִיב אֶתְכֶם", "אן יחסן אליכם", "to deal well with you"),
        ("וּלְהַרְבּוֹת אֶתְכֶם", "ואן יכת'רכם", "and to multiply you"),
        ("כֵּן יָשִׂישׂ יְהוָה עֲלֵיכֶם", "כד'אך יקצד בכם", "so shall He intend for you"),
        ("לְהַאֲבִיד אֶתְכֶם", "אן יבידכם", "to destroy you"),
        ("וּלְהַשְׁמִיד אֶתְכֶם", "ואן ינפד'כם", "and to annihilate you"),
        ("וְנִסַּחְתֶּם מֵעַל הָאֲדָמָה", "פתנדרסון ען אלבלד", "and you shall be obliterated from the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה לְרִשְׁתָּהּ", "אלד'י אנת דאכ'ל אליה לתחוזה", "which you are entering to possess"),
    ],
    64: [
        ("וֶהֱפִיצְךָ יְהוָה", "ויבדדך אללה", "And God shall scatter you"),
        ("בְּכָל-הָעַמִּים", "פי מא בין גמיע אלשעוב", "among all the peoples"),
        ("מִקְצֵה הָאָרֶץ", "מן טרף אלארץ'", "from one end of the earth"),
        ("וְעַד-קְצֵה הָאָרֶץ", "אלי' טרפהא", "to the other"),
        ("וְעָבַדְתָּ שָּׁם", "פתכ'דם ת'ם", "and there you shall serve"),
        ("אֱלֹהִים אֲחֵרִים", "מעבודאת אכ'ר", "other objects of worship"),
        ("אֲשֶׁר לֹא-יָדַעְתָּ", "מא לם תערפהא", "which neither you"),
        ("אַתָּה וַאֲבֹתֶיךָ", "אנת ואבאיך", "nor your fathers have known"),
        ("עֵץ וָאָבֶן", "מן כ'שב וחגארה", "of wood and stone"),
    ],
    65: [
        ("וּבַגּוֹיִם הָהֵם", "ופי תלך אלאמם", "And among those nations"),
        ("לֹא תַרְגִּיעַ", "לא תטמאן", "you shall find no rest"),
        ("וְלֹא-יִהְיֶה מָנוֹחַ לְכַף-רַגְלֶךָ", "ולא יכון קרארא לקדמך", "and there shall be no resting-place for your foot"),
        ("וְנָתַן יְהוָה לְךָ שָׁם", "בל יגעל אללה לך ת'ם", "but God shall give you there"),
        ("לֵב רַגָּז", "קלבא רגזא", "a trembling heart"),
        ("וְכִלְיוֹן עֵינַיִם", "ושכוץ אלעיון", "and staring eyes"),
        ("וְדַאֲבוֹן נָפֶשׁ", "ודבול אלנפוס", "and withering of soul"),
    ],
    66: [
        ("וְהָיוּ חַיֶּיךָ תְּלֻאִים לְךָ", "ותכון חיאתך מעלקה חד'אך", "And your life shall be hanging before you"),
        ("וּפָחַדְתָּ לַיְלָה וְיוֹמָם", "ותפזע לילא ונהארא", "and you shall be terrified night and day"),
        ("וְלֹא תַאֲמִין בְּחַיֶּיךָ", "ולא תצאדק בחיאתך", "and shall not trust in your life"),
    ],
    67: [
        ("בַּבֹּקֶר תֹּאמַר", "תקול באלגדאה", "In the morning you shall say"),
        ("מִי-יִתֵּן עֶרֶב", "יא ליתני אמסי", "'Would that it were evening!'"),
        ("וּבָעֶרֶב תֹּאמַר", "ותקול באלעשי", "and in the evening you shall say"),
        ("מִי-יִתֵּן בֹּקֶר", "יא ליתני אצבח", "'Would that it were morning!'"),
        ("מִפַּחַד לְבָבְךָ אֲשֶׁר תִּפְחָד", "מן פזע קלבך אלד'י תפזע", "out of the dread of your heart which you shall dread"),
        ("וּמִמַּרְאֵה עֵינֶיךָ אֲשֶׁר תִּרְאֶה", "ומע רויא עינאך אלד'י תראה", "and from the sight of your eyes which you shall see"),
    ],
    68: [
        ("וֶהֱשִׁיבְךָ יְהוָה מִצְרַיִם", "וירדך אללה אלי' חאל מצר", "And God shall bring you back to the condition of Egypt"),
        ("בָּאֳנִיּוֹת", "פי ספן", "in ships"),
        ("בַּדֶּרֶךְ אֲשֶׁר אָמַרְתִּי לְךָ", "עלי' אלחאל אלד'י קלת לך", "along the way of which I said to you"),
        ("לֹא-תֹסִיף עוֹד לִרְאֹתָהּ", "לא תעוד אן תראהא אבדא", "you shall never see it again"),
        ("וְהִתְמַכַּרְתֶּם שָׁם", "ותערצון הנאך לאלביע", "and you shall be offered there for sale"),
        ("לְאֹיְבֶיךָ לַעֲבָדִים", "לאעדאיכם. עבידא", "to your enemies as slaves"),
        ("וְלִשְׁפָחוֹת", "ואמא", "and maidservants"),
        ("וְאֵין קֹנֶה", "וליס משתרי", "with no buyer"),
    ],
    69: [
        ("אֵלֶּה דִבְרֵי הַבְּרִית", "הד'א כלאם אלעהד", "These are the words of the covenant"),
        ("אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה", "אלד'י אמר אללה מוסי'", "which God commanded Moses"),
        ("לִכְרֹת אֶת-בְּנֵי יִשְׂרָאֵל", "אן יעהדה מע בני אסראיל", "to make with the sons of Israel"),
        ("בְּאֶרֶץ מוֹאָב", "פי בלד מואב", "in the land of Moab"),
        ("מִלְּבַד הַבְּרִית", "מא כ'לא אלעהד", "apart from the covenant"),
        ("אֲשֶׁר-כָּרַת אִתָּם בְּחֹרֵב", "אלד'י עהדה מעהם פי גבל חריב", "which He made with them at Mount Horeb"),
    ],
}
