"""Hand-authored alignment triples for Devarim chapter 16.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the three pilgrimage festivals — Pesach/Matzot (vv. 1–8),
Shavuot (vv. 9–12), Sukkot (vv. 13–15) — the thrice-annual appearance command
(vv. 16–17), and the appointment of judges and the pursuit of justice (vv. 18–22).
Aligned with care for Saadia's distinctive renderings: אלפריך (ripening grain),
אלמצ'אל (Booths), חג אלאסאבע (festival of Weeks), חכאמא וערפא (judges and overseers).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("שָׁמוֹר", "ואחפץ'", "And observe"),
        ("אֶת-חֹדֶשׁ הָאָבִיב", "שהר אלפריך", "the month of the ripening grain"),
        ("וְעָשִׂיתָ", "אן תצנע", "that you make"),
        ("פֶּסַח", "פסחא", "a Passover"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("כִּי", "כמא", "as"),
        ("בְּחֹדֶשׁ הָאָבִיב", "אטלקך פיה", "He released you in it"),
        ("הוֹצִיאֲךָ", "לאלכ'רוג", "to go forth"),
        ("מִמִּצְרַיִם", "מן מצר", "from Egypt"),
        ("לָיְלָה", "לילא", "by night"),
    ],
    2: [
        ("וְזָבַחְתָּ", "ואדבח", "And slaughter"),
        ("פֶּסַח", "אלפסח", "the Passover"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("צֹאן", "מן אלג'נם", "from the flock"),
        ("וּבָקָר", "ומעה מן אלבקר", "and with it from the cattle"),
        ("בַּמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר-יִבְחַר", "אלד'י יכ'תארה", "which"),
        ("יְהוָה", "אללה", "God shall choose"),
        ("לְשַׁכֵּן שְׁמוֹ", "ליחל נורה", "that He may let His light dwell"),
        ("שָׁם", "פיה", "therein"),
    ],
    3: [
        ("לֹא-תֹאכַל", "לא תאכל", "Do not eat"),
        ("חָמֵץ", "כ'מירא", "leavened bread"),
        (None, "מעה", "with it"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        (None, "בל כל בעדה", "rather, eat after it"),
        ("מַצּוֹת", "פטירא", "unleavened bread"),
        ("לֶחֶם עֹנִי", "טעאם אלצ'עיף", "the food of the weak"),
        ("כִּי", "לאנך", "for you"),
        ("בְחִפָּזוֹן", "בחפז", "in haste"),
        ("יָצָאתָ", "כ'רגת", "went forth"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן מצר", "from Egypt"),
        ("לְמַעַן תִּזְכֹּר", "ואד'כר", "And remember"),
        ("אֶת-יוֹם צֵאתְךָ", "יום כ'רוגך", "the day of your going forth"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן מצר", "from Egypt"),
        ("כֹּל יְמֵי חַיֶּיךָ", "טול זמאנך", "all the length of your time"),
    ],
    4: [
        ("וְלֹא-יֵרָאֶה", "ולא י'רא", "And let no"),
        ("לְךָ", "לך", "be seen for you"),
        ("שְׂאֹר", "כ'מיר", "leaven"),
        ("בְּכָל-גְּבֻלְךָ", "פי גמיע תכ'מך", "in all your territory"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("וְלֹא-יָלִין", "ולא יבית", "and let none"),
        ("מִן-הַבָּשָׂר", "מן אללחם", "of the flesh"),
        ("אֲשֶׁר תִּזְבַּח", "אלד'י תדבחה", "which you slaughter"),
        ("בָּעֶרֶב", "באלעשי", "in the evening"),
        ("בַּיּוֹם הָרִאשׁוֹן", "אלי' ג'דאה' אליום אלאוול", "until the morning of the first day"),
    ],
    5: [
        ("לֹא תוּכַל", "ולא יגוז", "It is not permitted"),
        ("לִזְבֹּחַ", "אן תד'בח", "that you slaughter"),
        ("אֶת-הַפָּסַח", "אלפסח", "the Passover"),
        ("בְּאַחַד שְׁעָרֶיךָ", "פי בעץ' מחלך", "in any of your settlements"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
    ],
    6: [
        (None, "אלא", "But only"),
        ("אֶל-הַמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר-יִבְחַר", "אלד'י יכתארה", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("לְשַׁכֵּן שְׁמוֹ", "ליחל נורה", "that He may let His light dwell"),
        (None, "הנאך", "therein"),
        ("תִּזְבַּח", "תד'בח", "there you shall slaughter"),
        ("אֶת-הַפֶּסַח", "אלפסח", "the Passover"),
        ("בָּעָרֶב", "ענד אלמסא", "at the evening"),
        ("כְּבוֹא הַשֶּׁמֶשׁ", "קבל מג'יב אלשמס", "before the setting of the sun"),
        ("מוֹעֵד צֵאתְךָ", "פי פצל כ'רוגך", "at the season of your going forth"),
        ("מִמִּצְרָיִם", "מן מצר", "from Egypt"),
    ],
    7: [
        ("וּבִשַּׁלְתָּ", "ואנצ'גה", "And cook it"),
        ("וְאָכַלְתָּ", "וכלה", "and eat it"),
        ("בַּמָּקוֹם", "פי ד'אלך אלמוצ'ע", "in that place"),
        ("אֲשֶׁר יִבְחַר", "אלד'י יכ'תארה", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("וּפָנִיתָ", "ת'ם ולי", "then turn away"),
        ("בַבֹּקֶר", "באלג'דאה", "in the morning"),
        ("וְהָלַכְתָּ", "ואמץ'", "and go"),
        ("לְאֹהָלֶיךָ", "אלי' מנזלך", "to your dwelling"),
    ],
    8: [
        ("שֵׁשֶׁת יָמִים", "סתה' אייאם", "six days"),
        ("תֹּאכַל מַצּוֹת", "וכל בעדה פטיר", "And eat after it unleavened bread"),
        ("וּבַיּוֹם הַשְּׁבִיעִי", "ופי אליום אלסאבע", "and on the seventh day"),
        ("עֲצֶרֶת", "מכת'א", "an abiding"),
        ("לַיהוָה אֱלֹהֶיךָ", "פי קדס אללה רבך", "in the holiness of God your Lord"),
        ("לֹא תַעֲשֶׂה מְלָאכָה", "לא תצנע פיה צנאעה", "you shall do no work therein"),
    ],
    9: [
        ("שִׁבְעָה שָׁבֻעֹת", "סבעה אסאביע", "seven weeks"),
        ("תִּסְפָּר-לָךְ", "ואחץ", "And count"),
        ("מֵהָחֵל חֶרְמֵשׁ", "מן וקת אבתדא אלמנגל", "from the time the sickle begins"),
        ("בַּקָּמָה", "פי אלסנבל", "among the ears of grain"),
        ("תָּחֵל לִסְפֹּר", "אבתדי בהא", "begin the count"),
    ],
    10: [
        ("וְעָשִׂיתָ", "ואצנע", "And make"),
        ("חַג שָׁבֻעוֹת", "חג אלאסאבע", "the festival of Weeks"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מִסַּת נִדְבַת יָדְךָ", "עלי' מקדאר מא תנאל ידך", "according to the measure of what your hand attains"),
        ("אֲשֶׁר תִּתֵּן", "ומא תתברע בה", "and what you offer voluntarily"),
        ("כַּאֲשֶׁר יְבָרֶכְךָ", "כמא רזקך", "as"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord has provided for you"),
    ],
    11: [
        ("וְשָׂמַחְתָּ", "ואפרח", "And rejoice"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידיה", "before Him"),
        ("אַתָּה", "אנת", "you"),
        ("וּבִנְךָ", "ואבנך", "and your son"),
        ("וּבִתֶּךָ", "ואבנתך", "and your daughter"),
        ("וְעַבְדְּךָ", "ועבדך", "and your manservant"),
        ("וַאֲמָתֶךָ", "ואמתך", "and your maidservant"),
        ("וְהַלֵּוִי", "ואללוי", "and the Levite"),
        ("אֲשֶׁר בִּשְׁעָרֶיךָ", "אלד'י פי מחאלך", "who is in your settlements"),
        ("וְהַגֵּר", "ואלג'ריב", "and the stranger"),
        ("וְהַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְהָאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("אֲשֶׁר בְּקִרְבֶּךָ", "אלד'י פי מא בינכם", "who are in your midst"),
        ("בַּמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר יִבְחַר", "אלד'י יכ'תארה", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("לְשַׁכֵּן שְׁמוֹ", "ליחל נורה", "that He may let His light dwell"),
        ("שָׁם", "פיה", "therein"),
    ],
    12: [
        ("וְזָכַרְתָּ", "ואד'כר", "And remember"),
        ("כִּי-עֶבֶד הָיִיתָ", "אנך כנת עבדא", "that you were a slave"),
        ("בְּמִצְרָיִם", "במצר", "in Egypt"),
        ("וְשָׁמַרְתָּ", "ואחפץ'", "and observe"),
        ("וְעָשִׂיתָ", "ואעמל בהא", "and act by them"),
        ("אֶת-הַחֻקִּים הָאֵלֶּה", "הד'ה אלרסום", "these statutes"),
    ],
    13: [
        ("תַּעֲשֶׂה", "ואצנע", "And make"),
        ("חַג הַסֻּכֹּת", "חג אלמצ'אל", "the festival of Booths"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("בְּאָסְפְּךָ", "ענד גמעך", "at the time of your gathering"),
        ("מִגָּרְנְךָ", "מן בד'ארך", "from your sowing"),
        ("וּמִיִּקְבֶךָ", "ותג'ארך", "and your produce"),
        (None, "ג'לתך", "your harvest"),
    ],
    14: [
        ("וְשָׂמַחְתָּ", "ואפרח", "And rejoice"),
        ("בְּחַגֶּךָ", "פי חגך הד'א", "at this festival of yours"),
        ("אַתָּה", "אנת", "you"),
        ("וּבִנְךָ", "ואבנך", "and your son"),
        ("וּבִתֶּךָ", "ואבנתך", "and your daughter"),
        ("וְעַבְדְּךָ", "ועבדך", "and your manservant"),
        ("וַאֲמָתֶךָ", "ואמתך", "and your maidservant"),
        ("וְהַלֵּוִי", "ואללוי", "and the Levite"),
        ("וְהַגֵּר", "ואלג'ריב", "and the stranger"),
        ("וְהַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְהָאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("אֲשֶׁר בִּשְׁעָרֶיךָ", "אלד'י פי מחאלך", "who are in your settlements"),
    ],
    15: [
        (None, "כד'אך", "So shall you"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("תָּחֹג", "תחג", "make pilgrimage"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בַּמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר-יִבְחַר", "אלד'י יכ'תארה", "which He shall choose"),
        ("יְהוָה", "לכי יבארך לך", "so that God your Lord may bless you"),
        ("בְּכֹל תְּבוּאָתְךָ", "פי גמיע ג'לתך", "in all your harvest"),
        ("וּבְכֹל מַעֲשֵׂה יָדֶיךָ", "וסאיר מא תמד ידך אליה", "and the rest of what you put your hand to"),
        ("וְהָיִיתָ אַךְ שָׂמֵחַ", "ותכון פארחא מחצא", "and you shall be in wholly pure joy"),
    ],
    16: [
        ("שָׁלוֹשׁ פְּעָמִים", "ת'לאת' מראר", "Three times"),
        ("בַּשָּׁנָה", "פי אלסנה", "in the year"),
        ("יֵרָאֶה", "יחצ'ר", "shall appear"),
        ("כָל-זְכוּרְךָ", "גמיע רגאלך", "all your men"),
        ("אֶת-פְּנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
        ("בַּמָּקוֹם אֲשֶׁר יִבְחָר", "פי אלמוצ'ע אלד'י יכ'תארה", "in the place which He shall choose"),
        ("בְּחַג הַמַּצּוֹת", "פי חג אלפטיר", "at the pilgrimage of unleavened bread"),
        ("וּבְחַג הַשָּׁבֻעוֹת", "וחג אלאסאבע", "and the pilgrimage of Weeks"),
        ("וּבְחַג הַסֻּכּוֹת", "וחג אלמצ'אל", "and the pilgrimage of Booths"),
        ("וְלֹא יֵרָאֶה", "ולא יחצ'רו", "and they shall not appear"),
        ("אֶת-פְּנֵי יְהוָה", "בין ידי", "before Me"),
        ("רֵיקָם", "פרג'א", "empty-handed"),
    ],
    17: [
        (None, "בל", "But"),
        ("אִישׁ", "יאת כל רגל", "each man shall come"),
        ("כְּמַתְּנַת יָדוֹ", "כמא תנאל ידה", "according to what his hand attains"),
        ("כְּבִרְכַּת יְהוָה", "כרזק אללה", "according to the provision of God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲשֶׁר נָתַן-לָךְ", "אלד'י אעטאך", "which He has given you"),
    ],
    18: [
        ("שֹׁפְטִים", "חכאמא", "judges"),
        ("וְשֹׁטְרִים", "וערפא", "and overseers"),
        ("תִּתֶּן-לְךָ", "ואגעל לך", "And appoint for yourself"),
        ("בְּכָל-שְׁעָרֶיךָ", "פי גמיע מחאלך", "in all your settlements"),
        ("אֲשֶׁר יְהוָה", "אלד'י יעטי אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לְךָ", "אסבאטך", "gives to your tribes"),
        ("לִשְׁבָטֶיךָ", "יחכמו", "and they shall judge"),
        ("וְשָׁפְטוּ אֶת-הָעָם", "פי מא בין אלנאס", "among the people"),
        ("מִשְׁפַּט-צֶדֶק", "בחכם עדל", "with a just judgment"),
    ],
    19: [
        ("לֹא-תַטֶּה מִשְׁפָּט", "לא תמייל אלחכם", "Do not skew the judgment"),
        ("לֹא תַכִּיר פָּנִים", "ולא תחאבי אלוגוה", "and do not show partiality to persons"),
        ("וְלֹא-תִקַּח שֹׁחַד", "ולא תאכ'ד' אלרשא", "and do not take a bribe"),
        ("כִּי הַשֹּׁחַד", "לאן אלרשא", "for the bribe"),
        ("יְעַוֵּר", "יעמי", "blinds"),
        ("עֵינֵי חֲכָמִים", "עיון אלעלמא", "the eyes of the learned"),
        (None, "ען אלחק", "to the truth"),
        ("וִיסַלֵּף", "ויזיף", "and corrupts"),
        ("דִּבְרֵי צַדִּיקִם", "אלאקואל אלעאדלה", "words that are just"),
    ],
    20: [
        ("צֶדֶק צֶדֶק", "אלחק אלמחץ", "pure justice"),
        ("תִּרְדֹּף", "ואכלב", "And pursue"),
        ("לְמַעַן תִּחְיֶה", "לכי תחיא", "so that you may live"),
        ("וְיָרַשְׁתָּ", "ותחוז", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
    ],
    21: [
        ("לֹא-תִטַּע", "ולא תג'רס", "And do not plant"),
        ("לְךָ", "לך", "for yourself"),
        ("אֲשֵׁרָה כָּל-עֵץ", "סאריה מן אלשגר", "a tree-pole"),
        ("אֵצֶל מִזְבַּח", "אלי' גאנב מד'בח", "beside the altar of"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲשֶׁר תַּעֲשֶׂה-לָּךְ", "אלד'י תצנעה", "which you shall make"),
    ],
    22: [
        ("וְלֹא-תָקִים", "ולא תנצב", "And do not erect"),
        ("לְךָ", "לך", "for yourself"),
        ("מַצֵּבָה", "דכה", "a platform-stone"),
        ("אֲשֶׁר שָׂנֵא", "עלי' מא ישנאה", "that which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord abhors"),
    ],
}
