"""Hand-authored alignment triples for Devarim chapter 7.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the command to destroy the seven Canaanite nations, the
prohibition of intermarriage, and God's election and love of Israel — aligned
with care to the proper nouns (Hittites, Girgashites, Amorites, Canaanites,
Perizzites, Hivites, Jebusites) and the theological vocabulary of ḥerem.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואזא", "And when"),
        ("כִּי יְבִיאֲךָ", "אדכ'לך", "brings you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה", "אלזי אנת דאכ'ל אליה", "which you are entering"),
        ("לְרִשְׁתָּהּ", "לתחוזוה", "to possess it"),
        ("וְנָשַׁל", "פיטחטח", "and shatters"),
        ("גּוֹיִם-רַבִּים", "אממא כת'ירא", "many nations"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
        ("הַחִתִּי", "אלחתיין", "the Hittites"),
        ("וְהַגִּרְגָּשִׁי", "ואלגרגשיין", "and the Girgashites"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("וְהַכְּנַעֲנִי", "ואלכנעאניין", "and the Canaanites"),
        ("וְהַפְּרִזִּי", "ואלפרזיין", "and the Perizzites"),
        ("וְהַחִוִּי", "ואלחויין", "and the Hivites"),
        ("וְהַיְבוּסִי", "ואליבוסיין", "and the Jebusites"),
        ("שִׁבְעָה גוֹיִם", "סבעה' אממא", "seven nations"),
        ("רַבִּים וַעֲצוּמִים", "אכת'ר וא עצ'ם", "more numerous and stronger"),
        ("מִמֶּךָּ", "מנך", "than you"),
    ],
    2: [
        ("וּנְתָנָם יְהוָה אֱלֹהֶיךָ", "פיסלמהם אללה רבך", "God your Lord will deliver them"),
        ("לְפָנֶיךָ", "פי ידך", "into your hands"),
        ("וְהִכִּיתָם", "פאקתלהמ", "so kill them"),
        ("הַחֲרֵם תַּחֲרִים אֹתָם", "ואתלפהם תלפא", "and destroy them utterly"),
        ("לֹא-תִכְרֹת לָהֶם בְּרִית", "ולא תעהד מעהם עהדא", "and do not make a covenant with them"),
        ("וְלֹא תְחָנֵּם", "ולא תרוף עליהמ", "and do not show compassion upon them"),
    ],
    3: [
        ("וְלֹא תִתְחַתֵּן בָּם", "ולא תצאהרהמ", "And do not intermarry with them"),
        ("בִּתְּךָ", "אבנתך", "your daughter"),
        ("לֹא-תִתֵּן", "פתעטי", "do not give"),
        ("לִבְנוֹ", "לאבנה", "to his son"),
        ("וּבִתּוֹ לֹא-תִקַּח לִבְנֶךָ", "ולא תאכ'זאבנתה לאבנך", "and do not take his daughter for your son"),
    ],
    4: [
        ("כִּי-יָסִיר", "פאנהם יזילון", "For they will turn"),
        ("אֶת-בִּנְךָ", "אבנך", "your son"),
        ("מֵאַחֲרַי", "ען טאעתי", "away from obedience to Me"),
        ("וְעָבְדוּ", "ויעבדון", "and they will serve"),
        ("אֱלֹהִים אֲחֵרִים", "אלאהה' אכ'ר", "other objects of worship"),
        ("וְחָרָה אַף-יְהוָה", "וישתד ג'צ'ב אללה", "and the anger of God will grow fierce"),
        ("בָּכֶם", "עליך", "against you"),
        ("וְהִשְׁמִידְךָ", "וינפזך", "and He will destroy you"),
        ("מַהֵר", "סריעא", "swiftly"),
    ],
    5: [
        (None, "בל", "Rather"),
        (None, "כזא", "thus"),
        ("כִּי-אִם-כֹּה תַעֲשׂוּ לָהֶם", "פאצנעו להמ", "shall you do to them"),
        ("מִזְבְּחֹתֵיהֶם", "מזאבחהם", "their altars"),
        ("תִּתֹּצוּ", "פאנקצ'ו", "demolish"),
        ("וּמַצֵּבֹתָם", "ודכאכהם", "and their pillars"),
        ("תְּשַׁבֵּרוּ", "פכסרו", "shatter"),
        ("וַאֲשֵׁירֵהֶם", "וסואריהם", "and their sacred poles"),
        ("תְּגַדֵּעוּן", "תגדעו", "cut down"),
        ("וּפְסִילֵיהֶם", "ופסולהם", "and their carved idols"),
        ("תִּשְׂרְפוּן בָּאֵשׁ", "פאחרקוהא באלנאר", "burn with fire"),
    ],
    6: [
        ("כִּי", "לאנך", "For"),
        ("עַם קָדוֹשׁ", "שעב מקדס", "you are a people consecrated"),
        ("אַתָּה", "ללה רבך", "to God your Lord"),
        ("לַיהוָה אֱלֹהֶיךָ", "ובך אכ'תאר", "and He chose you"),
        ("בְּךָ בָּחַר", "אן תכון לה", "to be for Him"),
        ("לִהְיוֹת לוֹ לְעַם סְגֻלָּה", "אמה כ'אצה", "a special nation"),
        ("מִכֹּל הָעַמִּים", "מן גמיע אלשעוב", "from among all the peoples"),
        ("אֲשֶׁר עַל-פְּנֵי הָאֲדָמָה", "אלזי עלי' וגה אלארץ'", "who are upon the face of the earth"),
    ],
    7: [
        ("לֹא", "וליס", "It was not"),
        ("מֵרֻבְּכֶם", "מן כת'רתכם", "because of your being more numerous"),
        ("מִכָּל-הָעַמִּים", "מן גמיע אלאממ", "than all the nations"),
        ("חָשַׁק יְהוָה בָּכֶם", "אצטפאכם אללה", "that God selected"),
        ("וַיִּבְחַר בָּכֶם", "ואכ'תארכמ", "and chose you"),
        (None, "בל", "rather"),
        ("כִּי-אַתֶּם הַמְעַט", "אנתם אקל", "you are the fewest"),
        ("מִכָּל-הָעַמִּים", "מנהם מגמועין", "of them all together"),
    ],
    8: [
        (None, "לכן", "But"),
        ("כִּי מֵאַהֲבַת יְהוָה", "מן מחבה' אללה", "from God's love"),
        ("אֶתְכֶם", "לכמ", "for you"),
        ("וּמִשָּׁמְרוֹ", "ומן חפצ'ה", "and from His keeping"),
        ("אֶת-הַשְּׁבֻעָה", "אלימין", "the oath"),
        ("אֲשֶׁר נִשְׁבַּע", "אלזי קסם בה", "which He swore"),
        ("לַאֲבֹתֵיכֶם", "לאבאיכמ", "to your fathers"),
        ("הוֹצִיא יְהוָה אֶתְכֶם", "אכ'רגכם אללה", "God brought you out"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a mighty hand"),
        ("וַיִּפְדְּךָ", "ופדאך", "and redeemed you"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה", "from the house of bondage"),
        ("מִיַּד פַּרְעֹה", "מן יד פרעון", "from the hand of Pharaoh"),
        ("מֶלֶךְ-מִצְרָיִם", "מלך מצר", "king of Egypt"),
    ],
    9: [
        ("וְיָדַעְתָּ", "פאעלמ", "Know, then"),
        ("כִּי-יְהוָה", "אן אללה", "that God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("הוּא הָאֱלֹהִים", "הו אלאלאה", "He is the God"),
        ("הָאֵל הַנֶּאֱמָן", "אלטאיק אלאמין", "the Capable, the Faithful"),
        ("שֹׁמֵר הַבְּרִית", "חאפץ אלעהד", "who keeps the covenant"),
        ("וְהַחֶסֶד", "ואלאחסאן", "and the kindness"),
        ("לְאֹהֲבָיו", "למחביה", "for those who love Him"),
        ("וּלְשֹׁמְרֵי מִצְו‍ֹתָו", "וחאפצ'י וצאיאה", "and keep His commandments"),
        ("לְאֶלֶף דּוֹר", "לאלף גיל", "unto a thousand generations"),
    ],
    10: [
        ("וּמְשַׁלֵּם", "ומכאפי", "and who requites"),
        ("לְשֹׂנְאָיו", "שאניה", "His enemy"),
        ("אֶל-פָּנָיו", "בחצ'רתה", "in His presence"),
        ("לְהַאֲבִידוֹ", "לאנפאזה", "to destroy him"),
        ("לֹא יְאַחֵר", "ולא י'וכ'ר לה שייא", "He will not delay anything for him"),
        (None, "בל", "rather"),
        ("אֶל-פָּנָיו יְשַׁלֶּם-לוֹ", "בחצ'רתה יכאפיה", "in his presence He requites him"),
    ],
    11: [
        ("וְשָׁמַרְתָּ", "ואחפץ'", "And keep"),
        ("אֶת-הַמִּצְוָה", "אלוצאיא", "the commandments"),
        ("וְאֶת-הַחֻקִּים", "ואלרסום", "and the statutes"),
        ("וְאֶת-הַמִּשְׁפָּטִים", "ואלאחכאמ", "and the ordinances"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלתי אנא אמרך בהא", "which I am commanding you"),
        ("הַיּוֹם", "אליום", "today"),
        ("לַעֲשׂוֹתָם", "ואעמל בהא", "and act by them"),
    ],
    12: [
        ("וְהָיָה עֵקֶב", "פיכון גזא", "And it shall be, as recompense"),
        ("תִּשְׁמְעוּן", "מא תסמעון", "for your heeding"),
        ("אֵת הַמִּשְׁפָּטִים הָאֵלֶּה", "הד'ה אלאחכאם", "these ordinances"),
        ("וּשְׁמַרְתֶּם", "ותחפצוהא", "and keeping them"),
        ("וַעֲשִׂיתֶם אֹתָם", "ותעמלוהא", "and acting by them"),
        ("וְשָׁמַר יְהוָה", "יחפץ' אללה", "that God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord will keep"),
        ("לְךָ", "לך", "for you"),
        ("אֶת-הַבְּרִית", "אלעהד", "the covenant"),
        ("וְאֶת-הַחֶסֶד", "ואלפצ'ל", "and the grace"),
        ("אֲשֶׁר נִשְׁבַּע לַאֲבֹתֶיךָ", "אלד'י קסם לאבאיך", "which He swore to your fathers"),
    ],
    13: [
        ("וַאֲהֵבְךָ", "פיחבבך", "And He will love you"),
        ("וּבֵרַכְךָ", "ויבארך פיך", "and bless you"),
        ("וְהִרְבֶּךָ", "ויכת'רך", "and multiply you"),
        ("וּבֵרַךְ", "ויבארך פי", "and He will bless"),
        ("פְּרִי-בִטְנְךָ", "ת'מרך", "your fruit"),
        ("וּפְרִי-אַדְמָתֶךָ", "ות'מר ארצ'ך", "and the fruit of your land"),
        ("דְּגָנְךָ", "ברך", "your grain"),
        ("וְתִירֹשְׁךָ", "ועצירך", "and your juice"),
        ("וְיִצְהָרֶךָ", "וד'הנך", "and your oil"),
        ("שְׁגַר-אֲלָפֶיךָ", "נתאג בקרך", "the offspring of your cattle"),
        ("וְעַשְׁתְּרֹת צֹאנֶךָ", "וגפראת ג'נמך", "and the increase of your flock"),
        ("עַל הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-נִשְׁבַּע לַאֲבֹתֶיךָ", "אלד'י קסם לאבאיך", "which He swore to your fathers"),
        ("לָתֶת לָךְ", "אן יעטיכהא", "to give you"),
    ],
    14: [
        ("בָּרוּךְ תִּהְיֶה", "ותכון מבארך", "And you shall be blessed"),
        ("מִכָּל-הָעַמִּים", "מן גמיע אלאמם", "above all nations"),
        ("לֹא-יִהְיֶה בְךָ עָקָר", "ולא יכון פיך עאקר", "there shall remain among you neither barren man"),
        ("וַעֲקָרָה", "ולא עאקרה", "nor barren woman"),
        ("וּבִבְהֶמְתֶּךָ", "ולא פי בהאימך", "nor among your beasts"),
    ],
    15: [
        ("וְהֵסִיר יְהוָה", "ויזיל אללה", "And God will remove"),
        ("מִמְּךָ", "מנך", "from you"),
        ("כָּל-חֹלִי", "כל מרץ'", "every illness"),
        ("וְכָל-מַדְוֵי מִצְרַיִם הָרָעִים", "וגמיע אדוי מצר אלרדייה", "and all the evil afflictions of Egypt"),
        ("אֲשֶׁר יָדַעְתָּ", "אלתי תערפהא", "which you know"),
        ("לֹא יְשִׂימָם בָּךְ", "לא יחל בך שייא מנהא", "He will not bring any of them upon you"),
        (None, "בל", "but"),
        ("וּנְתָנָם בְּכָל-שֹׂנְאֶיךָ", "יחלהא בשאניך", "will bring them upon those who hate you"),
    ],
    16: [
        ("וְאָכַלְתָּ", "פתפני", "And you shall destroy"),
        ("אֶת-כָּל-הָעַמִּים", "גמיע אלשעוב", "all the peoples"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ נֹתֵן לָךְ", "אלד'י יעטיך אללה רבך", "whom God your Lord gives you"),
        ("לֹא-תָחוֹס עֵינְךָ עֲלֵיהֶם", "לא תשפק עליהם", "do not show compassion upon them"),
        ("וְלֹא תַעֲבֹד אֶת-אֱלֹהֵיהֶם", "ולא תעבד מעבודאתהם", "and do not serve their objects of worship"),
        ("כִּי-מוֹקֵשׁ הוּא לָךְ", "פיכונו לך והקא", "for they would become a noose for you"),
    ],
    17: [
        (None, "פאן", "If"),
        ("כִּי תֹאמַר", "קלת", "you say"),
        ("בִּלְבָבְךָ", "פי נפסך", "to yourself"),
        ("רַבִּים הַגּוֹיִם הָאֵלֶּה", "הולאי אלאמם אכת'ר", "These nations are more numerous"),
        ("מִמֶּנִּי", "מני", "than I"),
        ("אֵיכָה אוּכַל", "פכיף אטיק", "how can I manage"),
        ("לְהוֹרִישָׁם", "אן אקרצ'הם", "to gnaw them away"),
    ],
    18: [
        ("לֹא תִירָא", "לא תכ'אפהם", "do not fear them"),
        (None, "בל", "rather"),
        ("זָכֹר תִּזְכֹּר", "אד'כר", "remember"),
        ("אֵת אֲשֶׁר-עָשָׂה", "מא צנע", "what"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord did"),
        ("לְפַרְעֹה", "לפרעון", "to Pharaoh"),
        ("וּלְכָל-מִצְרָיִם", "וסאיר אלמצריון", "and to the rest of the Egyptians"),
    ],
    19: [
        ("הַמַּסֹּת הַגְּדֹלֹת", "אלאעלאם אלעצי'מה", "the great signs"),
        ("אֲשֶׁר-רָאוּ עֵינֶיךָ", "אלתי ראתהא עינאך", "which your eyes saw"),
        ("וְהָאֹתֹת", "ואלאיאת", "and the wonders"),
        ("וְהַמֹּפְתִים", "ואלבראהין", "and the proofs"),
        ("וְהַיָּד הַחֲזָקָה", "ואליד אלשדידה", "and the mighty hand"),
        ("וְהַזְּרֹעַ הַנְּטוּיָה", "ואלדראע אלממדודה", "and the outstretched arm"),
        ("אֲשֶׁר הוֹצִאֲךָ", "כמא אכ'רגך", "just as"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord brought you out"),
        ("כֵּן-יַעֲשֶׂה יְהוָה אֱלֹהֶיךָ", "כד'אך יצנע", "so He will do"),
        ("לְכָל-הָעַמִּים", "בגמיע אלאמם", "to all the nations"),
        ("אֲשֶׁר-אַתָּה יָרֵא מִפְּנֵיהֶם", "אלד'ין תכ'אפהם", "whom you fear"),
    ],
    20: [
        ("וְגַם אֶת-הַצִּרְעָה", "ויבעת' באלעאהה", "And He will send the plague"),
        ("יְשַׁלַּח יְהוָה אֱלֹהֶיךָ בָּם", "פיהם", "among them"),
        ("עַד-אֲבֹד הַנִּשְׁאָרִים", "חתי' יביד אלבאקיון", "until those remaining"),
        ("וְהַנִּסְתָּרִים", "ואלמנסתרון", "and those hidden"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you are destroyed"),
    ],
    21: [
        ("לֹא תַעֲרֹץ", "לא תרהבהם", "Do not be in dread of them"),
        ("כִּי-יְהוָה אֱלֹהֶיךָ", "לאן נור אללה רבך", "for the light of God your Lord"),
        ("בְּקִרְבֶּךָ", "פי מא בינך", "is in your midst"),
        ("אֵל גָּדוֹל", "אלטאיק אל עצ'ים", "the Capable, the great"),
        ("וְנוֹרָא", "אלמכ'יף", "the awe-inspiring"),
    ],
    22: [
        ("וְנָשַׁל יְהוָה אֱלֹהֶיךָ", "והו יטחטח", "And He will shatter"),
        ("אֶת-הַגּוֹיִם הָאֵל", "אולאיך אלאמם", "those nations"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
        ("מְעַט מְעָט", "קלילא קלילא", "little by little"),
        ("לֹא תוּכַל", "אד' לא תטיק", "since you cannot manage"),
        ("כַּלֹּתָם מַהֵר", "אן תפניהם סריעא", "to destroy them quickly"),
        ("פֶּן-תִּרְבֶּה עָלֶיךָ", "כלא יכת'ר עליך", "lest"),
        ("חַיַּת הַשָּׂדֶה", "וחש אלצחרא", "the wild creatures of the wilderness multiply upon you"),
    ],
    23: [
        (None, "פאד'א", "But when"),
        ("וּנְתָנָם יְהוָה אֱלֹהֶיךָ לְפָנֶיךָ", "אסלמהם אללה רבך פי ידך", "God your Lord delivers them into your hand"),
        ("וְהָמָם", "פאהאמהם", "He will throw them"),
        (None, "אהאמה", "into"),
        ("מְהוּמָה גְדֹלָה", "עצ'ימה", "great confusion"),
        ("עַד הִשָּׁמְדָם", "אלי' אנפאד'הם", "until they are destroyed"),
    ],
    24: [
        ("וְנָתַן מַלְכֵיהֶם", "ויסלם מלוכהם", "And He will deliver their kings"),
        ("בְּיָדֶךָ", "פי ידך", "into your hand"),
        ("וְהַאֲבַדְתָּ אֶת-שְׁמָם", "פאבד אסמאיהם", "and you shall blot out their names"),
        ("מִתַּחַת הַשָּׁמָיִם", "מן תחת אלסמא", "from under the sky"),
        ("לֹא-יִתְיַצֵּב אִישׁ בְּפָנֶיךָ", "לא יקף אנסאן בין ידיך", "no man shall stand before you"),
        ("עַד הִשְׁמִדְךָ אֹתָם", "אלי' אן תנפד'הם", "until you have destroyed them"),
    ],
    25: [
        ("פְּסִילֵי אֱלֹהֵיהֶם", "ואחרקו פסול מעבודאתהם", "And burn the carved idols of their objects of worship"),
        ("תִּשְׂרְפוּן בָּאֵשׁ", "באלנאר", "with fire"),
        ("לֹא-תַחְמֹד", "ולא תתמן שייא", "and do not covet any"),
        ("כֶּסֶף וְזָהָב", "מן אלפצ'ה ואלד'הב", "of the silver and gold"),
        ("עֲלֵיהֶם", "אלד'י עליהם", "that is upon them"),
        ("וְלָקַחְתָּ לָךְ", "ותאכ'ד'ה לך", "so as to take it for yourself"),
        ("פֶּן תִּוָּקֵשׁ בּוֹ", "כלא תוהק בה", "lest you be ensnared by it"),
        ("כִּי תוֹעֲבַת יְהוָה אֱלֹהֶיךָ הוּא", "לאנה כריהה ללה רבך", "for it is something abhorrent to God your Lord"),
    ],
    26: [
        ("וְלֹא-תָבִיא", "ולא תדכ'ל", "And do not bring"),
        ("תוֹעֵבָה", "מא יכרהה אללה", "what God abhors"),
        ("אֶל-בֵּיתֶךָ", "אלי' ביתך", "into your house"),
        ("וְהָיִיתָ חֵרֶם כָּמֹהוּ", "ותציר מתלופא מת'לה", "lest you become doomed like it"),
        (None, "בל", "rather"),
        ("שַׁקֵּץ תְּשַׁקְּצֶנּוּ", "רגסה תרגיסא", "utterly abominate it"),
        ("וְתַעֵב תְּתַעֲבֶנּוּ", "ואכרהה כריהה", "and utterly abhor it"),
        ("כִּי-חֵרֶם הוּא", "אד' הו מתלוף", "for it is doomed"),
    ],
}
