"""Hand-authored alignment triples for Devarim chapter 4.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואלאן", "And now"),
        (None, "יא", "O"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("שְׁמַע", "אסמע", "hear"),
        ("הַחֻקִּים", "אלרסום", "the statutes"),
        ("וְאֶל-הַמִּשְׁפָּטִים", "ואלאחכאמ", "and the ordinances"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("אָנֹכִי", "אנא", "I"),
        ("מְלַמֵּד", "מעלמכם", "am teaching you"),
        ("לַעֲשׂוֹת", "לתעמלו בהא", "to do them"),
        ("לְמַעַן", "לכי", "so that"),
        ("תִּחְיוּ", "תחיון", "you may live"),
        ("וּבָאתֶם", "ותדכ'לו", "and enter"),
        ("וִירִשְׁתֶּם", "פתחוזו", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר יְהוָה", "אלזי אללה", "which God"),
        ("אֱלֹהֵי אֲבֹתֵיכֶם", "אלאה אביאיכם", "the God of your fathers"),
        ("נֹתֵן לָכֶם", "מעטיכמ", "is giving you"),
    ],
    2: [
        ("לֹא תֹסִפוּ", "לא תזידו", "You shall not add"),
        (None, "שייא", "anything"),
        ("עַל-הַדָּבָר", "עלי' מא", "to what"),
        ("אֲשֶׁר אָנֹכִי", "אמרכם בה", "I command you"),
        ("וְלֹא תִגְרְעוּ", "ולא תנקצו", "nor diminish"),
        ("מִמֶּנּוּ", "מנה", "from it"),
        (None, "בל", "but"),
        ("לִשְׁמֹר", "אחפצ'ו", "keep"),
        ("מִצְו‍ֹת", "וצאיא", "the commandments of"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכמ", "your Lord"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם", "אלזי אנא אמרכם אליומ", "which I command you today"),
    ],
    3: [
        ("עֵינֵיכֶם", "ועיונכם", "And your eyes"),
        ("הָרֹאוֹת", "קד ראת", "have seen"),
        ("אֵת אֲשֶׁר-עָשָׂה", "גמיע מא צנע", "all that"),
        ("יְהוָה", "אללה", "God"),
        ("בְּבַעַל פְּעוֹר", "בפעור אלצנמ", "with Peor the idol"),
        ("כִּי", "אן", "that"),
        ("כָל-הָאִישׁ אֲשֶׁר הָלַךְ אַחֲרֵי בַעַל-פְּעוֹר", "כל רגל אתבעה", "every man who followed it"),
        ("הִשְׁמִידוֹ", "אנפזה", "drove out"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבכם", "God your Lord"),
        ("מִקִּרְבֶּךָ", "מן בינכמ", "from among you"),
    ],
    4: [
        ("וְאַתֶּם", "ואנתם", "And you"),
        ("הַדְּבֵקִים", "אללאזמין", "who hold fast"),
        ("בַּיהוָה", "טאעה' אללה", "in obedience to God"),
        ("אֱלֹהֵיכֶם", "רבכמ", "your Lord"),
        ("חַיִּים כֻּלְּכֶם", "כלכם אחיא", "you are all alive"),
        ("הַיּוֹם", "אליומ", "today"),
    ],
    5: [
        (None, "אנצ'רו", "See"),
        ("לִמַּדְתִּי", "קד עלמתכמ", "I have taught you"),
        ("חֻקִּים", "רסומא", "statutes"),
        ("וּמִשְׁפָּטִים", "ואחכאמא", "and ordinances"),
        ("כַּאֲשֶׁר צִוַּנִי יְהוָה אֱלֹהָי", "כמא אמרני אללה רבי", "as God my Lord commanded me"),
        ("לַעֲשׂוֹת כֵּן", "לתצנעוהא", "that you should do them"),
        ("בְּקֶרֶב הָאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אַתֶּם", "אלזי אנתמ", "to which you are"),
        ("בָּאִים שָׁמָּה", "צאירין אליה", "going"),
        ("לְרִשְׁתָּהּ", "לתחוזוה", "to possess it"),
    ],
    6: [
        (None, "פאחפצ'והא", "So keep them"),
        ("וַעֲשִׂיתֶם", "ואעמלו בהא", "and act by them"),
        ("כִּי", "לאנהא", "for"),
        ("הִוא חָכְמַתְכֶם", "חכמתכם", "that is your wisdom"),
        ("וּבִינַתְכֶם", "ופהמכמ", "and your understanding"),
        ("לְעֵינֵי הָעַמִּים", "בחצ'רה' אלאממ", "before the nations"),
        ("אֲשֶׁר יִשְׁמְעוּן", "אזהם סמעו", "for when they hear"),
        ("אֵת כָּל-הַחֻקִּים הָאֵלֶּה", "הזה אלרסומ", "these statutes"),
        ("וְאָמְרוּ", "יקולון", "they will surely say"),
        (None, "איקינא", "indeed"),
        ("הַגּוֹי הַגָּדוֹל הַזֶּה", "הזא אלקביל אלכביר", "this great assembly"),
        ("עַם-חָכָם", "שעב חכים", "a wise"),
        ("וְנָבוֹן", "פהימ", "and understanding people"),
    ],
    7: [
        ("כִּי", "לאן", "For"),
        ("מִי-גוֹי גָּדוֹל", "אייה' אמה כבירה", "what great nation"),
        ("אֲשֶׁר-לוֹ", "להא", "is there that has"),
        ("אֱלֹהִים קְרֹבִים", "אלאה קריב", "a god so near"),
        ("אֵלָיו", "מנהא", "to it"),
        ("כַּיהוָה אֱלֹהֵינוּ", "כאללה רבנא", "as God our Lord"),
        ("בְּכָל-קָרְאֵנוּ אֵלָיו", "מתא מא דעונאה", "whenever we call upon Him"),
    ],
    8: [
        ("וּמִי גּוֹי גָּדוֹל", "ואייה' אמה כבירה", "And what great nation"),
        ("אֲשֶׁר-לוֹ", "להא", "is there that has"),
        ("חֻקִּים", "רסום", "statutes"),
        ("וּמִשְׁפָּטִים", "ואחכאם", "and ordinances"),
        ("צַדִּיקִם", "עאדלה", "as just"),
        ("כְּכֹל הַתּוֹרָה הַזֹּאת", "כגמיע הזה אלתורייה", "as all this Torah"),
        ("אֲשֶׁר אָנֹכִי", "אלזי אנא", "which I"),
        ("נֹתֵן לִפְנֵיכֶם", "תאליהא עליכם", "am reciting before you"),
        ("הַיּוֹם", "אליומ", "today"),
    ],
    9: [
        (None, "וכ'אצה", "Only"),
        ("הִשָּׁמֶר לְךָ", "אחתרז", "take heed"),
        ("וּשְׁמֹר נַפְשְׁךָ", "ואחפץ' נפסך", "and guard yourself"),
        ("מְאֹד", "גדא", "exceedingly"),
        ("פֶּן-תִּשְׁכַּח", "כלא תנסא", "lest you forget"),
        ("אֶת-הַדְּבָרִים", "אלכלאם", "the things"),
        ("אֲשֶׁר-רָאוּ עֵינֶיךָ", "אלזי ראתה עינאך", "which your eyes have seen"),
        ("וּפֶן-יָסוּרוּ", "ולא יזול", "and lest they depart"),
        ("מִלְּבָבְךָ", "מן קלבך", "from your heart"),
        ("כֹּל יְמֵי חַיֶּיךָ", "טול אייאם חיאתך", "all the days of your life"),
        (None, "בל", "but"),
        ("וְהוֹדַעְתָּם לְבָנֶיךָ", "ערפה לאבנך", "make them known to your son"),
        ("וְלִבְנֵי בָנֶיךָ", "ואבן אבנך", "and to your son's son"),
    ],
    10: [
        ("יוֹם", "פי יום", "on the day"),
        ("אֲשֶׁר עָמַדְתָּ", "וקפת", "you stood"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
        ("בְּחֹרֵב", "ענד חריב", "at Horeb"),
        ("בֶּאֱמֹר יְהוָה אֵלַי", "חין קאלאללה לי", "when God said to me"),
        ("הַקְהֶל-לִי", "אגמע לי", "Gather the people to me"),
        ("אֶת-הָעָם", "אלקומ", "that"),
        ("וְאַשְׁמִעֵם", "חתי' אסמעהם", "I may let them hear"),
        ("אֶת-דְּבָרָי", "כלאמי", "my words"),
        ("אֲשֶׁר יִלְמְדוּן", "לכי יתעלמו", "so that they may learn"),
        ("לְיִרְאָה אֹתִי", "אן יכ'אפוני", "to fear me"),
        ("כָּל-הַיָּמִים", "טול אלאיאם", "all the days"),
        ("אֲשֶׁר הֵם חַיִּים", "אלזי הם מקימין אחיא", "that they live"),
        ("עַל-הָאֲדָמָה", "עלי' אלארץ'", "upon the earth"),
        ("וְאֶת-בְּנֵיהֶם יְלַמֵּדוּן", "ויעלמון בניהמ", "and that they may teach their children"),
    ],
    11: [
        ("וַתִּקְרְבוּן", "ותקדמתם", "And you came forward"),
        ("וַתַּעַמְדוּן", "ווקפתם", "and stood"),
        ("תַּחַת הָהָר", "אספל אלגבל", "at the foot of the mountain"),
        ("וְהָהָר", "והו", "while it"),
        ("בֹּעֵר בָּאֵשׁ", "משתעל באלנר", "blazed with fire"),
        ("עַד-לֵב הַשָּׁמַיִם", "אלי' כבד אלסמא", "to the very heart of the sky"),
        ("חֹשֶׁךְ", "יחיט בה סואד", "enveloped in the blackness of"),
        ("עָנָן", "אלג'ים", "cloud"),
        ("וַעֲרָפֶל", "ואלצבאב", "and mist"),
    ],
    12: [
        ("וַיְדַבֵּר יְהוָה", "פכלמכם אללה", "And God spoke to you"),
        ("אֲלֵיכֶם", "מן לדן", "from"),
        ("מִתּוֹךְ הָאֵשׁ", "אלנר", "within the fire"),
        ("קוֹל דְּבָרִים", "פכנתם סאמעין אלכלאמ", "you were hearing the words"),
        ("וּתְמוּנָה אֵינְכֶם רֹאִים", "ושבהא לם תרון", "and any likeness you did not see"),
        ("זוּלָתִי קוֹל", "סוא אלצות פקט", "only the voice alone"),
    ],
    13: [
        ("וַיַּגֵּד לָכֶם", "ואכ'ברכם", "And He declared to you"),
        ("אֶת-בְּרִיתוֹ", "בעהדה", "His covenant"),
        ("אֲשֶׁר צִוָּה אֶתְכֶם", "אלזי אמרכם", "which He commanded you"),
        ("לַעֲשׂוֹת", "אן תעמלו בה", "to observe"),
        ("עֲשֶׂרֶת הַדְּבָרִים", "אלעשר אלכלמאת", "the Ten Words"),
        ("וַיִּכְתְּבֵם", "וכתבהא", "and He wrote them"),
        ("עַל-שְׁנֵי לֻחוֹת אֲבָנִים", "עלי' לוחי אלחגארה", "upon two tablets of stone"),
    ],
    14: [
        ("וְאֹתִי צִוָּה", "ואמרני", "And He commanded me"),
        ("בָּעֵת הַהִוא", "פי זאלך אלוקת", "at that time"),
        ("לְלַמֵּד אֶתְכֶם", "באן אעלמכם", "to teach you"),
        ("חֻקִּים", "רסומא", "statutes"),
        ("וּמִשְׁפָּטִים", "ואחכאמא", "and ordinances"),
        ("לַעֲשֹׂתְכֶם אֹתָם", "אעמלוהא", "that you should do them"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אַתֶּם עֹבְרִים", "אלזי אנתם גאיזין", "to which you are crossing over"),
        ("שָׁמָּה לְרִשְׁתָּהּ", "אליה לתחוזוה", "to possess it"),
    ],
    15: [
        (None, "פאחזרו", "Take great heed"),
        ("מְאֹד", "גדא", "therefore"),
        ("לְנַפְשֹׁתֵיכֶם", "עלי' נפוסכמ", "for your souls"),
        ("כִּי לֹא רְאִיתֶם", "פאנכם לם תרון", "for you saw no"),
        ("כָּל-תְּמוּנָה", "שבהא", "likeness"),
        ("בְּיוֹם דִּבֶּר יְהוָה", "פי יום כ'אטבכם אללה", "on the day God spoke to you"),
        ("בְּחֹרֵב", "פי חריב", "at Horeb"),
        ("מִתּוֹךְ הָאֵשׁ", "מן וסט אלנר", "from within the fire"),
    ],
    16: [
        ("פֶּן-תַּשְׁחִתוּן", "כלא תהלכוהא", "lest you corrupt yourselves"),
        ("וַעֲשִׂיתֶם לָכֶם", "פתצענו לכם", "and make for yourselves"),
        ("פֶּסֶל", "פסלא", "a graven image"),
        ("תְּמוּנַת כָּל-סָמֶל", "עלי' שכל כל שכ'ץ", "in the form of any figure"),
        ("תַּבְנִית זָכָר", "מן זכר", "whether male"),
        ("אוֹ נְקֵבָה", "או אנת'י", "or female"),
    ],
    17: [
        ("תַּבְנִית כָּל-בְּהֵמָה", "או שכל מן בהאים", "or in the form of any beast"),
        ("אֲשֶׁר בָּאָרֶץ", "אלארץ'", "of the earth"),
        ("תַּבְנִית כָּל-צִפּוֹר כָּנָף", "או שכל מן טאיר זו גנאח", "or in the form of any winged bird"),
        ("אֲשֶׁר תָּעוּף", "אלזי יטיר", "that flies"),
        ("בַּשָּׁמָיִם", "פי אלסמא", "in the sky"),
    ],
    18: [
        ("תַּבְנִית כָּל-רֹמֵשׂ", "או שכל ממא ידב", "or in the form of anything that creeps"),
        ("בָּאֲדָמָה", "עלי' אלארץ'", "upon the earth"),
        ("תַּבְנִית כָּל-דָּגָה", "או שכל מן אלסמך", "or in the form of any fish"),
        ("אֲשֶׁר-בַּמַּיִם", "אלזי פי אלמא", "that is in the water"),
        ("מִתַּחַת לָאָרֶץ", "תחת אלארץ'", "beneath the earth"),
    ],
    19: [
        ("וּפֶן-תִּשָּׂא עֵינֶיךָ", "וכלא תרפע עינאך", "and lest you lift up your eyes"),
        ("הַשָּׁמַיְמָה", "אלי' אלסמא", "to the sky"),
        ("וְרָאִיתָ", "ותנצ'ר", "and behold"),
        ("אֶת-הַשֶּׁמֶשׁ", "אלשמס", "the sun"),
        ("וְאֶת-הַיָּרֵחַ", "ואלקמר", "and the moon"),
        ("וְאֶת-הַכּוֹכָבִים", "ואלכואכב", "and the planets"),
        ("כֹּל צְבָא הַשָּׁמַיִם", "וסאיר נגום אלסמא", "and the rest of the stars of the sky"),
        ("וְנִדַּחְתָּ", "ותזול", "and be led astray"),
        ("וְהִשְׁתַּחֲוִיתָ לָהֶם", "ותסגד להא", "and bow down to them"),
        ("וַעֲבַדְתָּם", "ותעבדהא", "and serve them"),
        ("אֲשֶׁר חָלַק יְהוָה אֱלֹהֶיךָ", "אלזי בת' נורהא אללה רבך", "those whose light God your Lord has spread abroad"),
        ("לְכֹל הָעַמִּים", "לגמיע אלשעוב", "for all the peoples"),
        ("תַּחַת כָּל-הַשָּׁמָיִם", "אלזי תחת גמיע אלסמא", "that are under all the sky"),
    ],
    20: [
        ("וְאֶתְכֶם", "ואנתם", "But you"),
        ("יְהוָה", "אצטפאכם אללה", "God chose you out"),
        ("לָקַח", "ואכ'רגכם", "and brought you forth"),
        ("מִכּוּר הַבַּרְזֶל", "מן שביה בכור אלחדיד", "from what resembles a smelting furnace of iron"),
        ("מִמִּצְרָיִם", "מן מצר", "out of Egypt"),
        ("לִהְיוֹת לוֹ", "לתכונו לה", "to be for Him"),
        ("לְעַם נַחֲלָה", "שעב צפוה", "a chosen people"),
        ("כַּיּוֹם הַזֶּה", "כהזא אליומ", "as on this day"),
    ],
    21: [
        (None, "ואזקד", "Now"),
        ("וַיהוָה הִתְאַנַּף-בִּי", "וגד אללה עליי", "God was greatly angered with me"),
        ("עַל-דִּבְרֵיכֶם", "בסבבכם", "on your account"),
        ("וַיִּשָּׁבַע", "וקסם", "and swore"),
        ("לְבִלְתִּי עָבְרִי", "ללא אעבר", "that I should not cross"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("וּלְבִלְתִּי-בֹא", "וללא אדכ'ל", "and that I should not enter"),
        ("אֶל-הָאָרֶץ הַטּוֹבָה", "אלבלד אלגייד", "the good land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלזי אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ נַחֲלָה", "מעטיך נחלה", "is giving you as an inheritance"),
    ],
    22: [
        ("כִּי אָנֹכִי", "ואנא", "For I"),
        ("מֵת", "מאית", "am dying"),
        ("בָּאָרֶץ הַזֹּאת", "פי הזא אלבלד", "in this land"),
        ("אֵינֶנִּי עֹבֵר", "לא אעבר", "I shall not cross"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("וְאַתֶּם עֹבְרִים", "ואנתם עאברוה", "but you are crossing it"),
        ("וִירִשְׁתֶּם", "פתחוזו", "and you shall possess"),
        ("אֶת-הָאָרֶץ הַטּוֹבָה הַזֹּאת", "זאלך אלבלד אלגייד", "that good land"),
    ],
    23: [
        ("הִשָּׁמְרוּ לָכֶם", "אחזרו", "Take heed"),
        ("פֶּן-תִּשְׁכְּחוּ", "אן תנסו", "lest you forget"),
        ("אֶת-בְּרִית יְהוָה אֱלֹהֵיכֶם", "עהד אללה רבכמ", "the covenant of God your Lord"),
        ("אֲשֶׁר כָּרַת עִמָּכֶם", "אלזי עהדה מעכמ", "which He made with you"),
        ("וַעֲשִׂיתֶם לָכֶם פֶּסֶל", "פתצנעו לכם פסלא", "and make for yourselves a graven image"),
        ("תְּמוּנַת כֹּל אֲשֶׁר", "שבה כל מא", "in the likeness of anything that"),
        ("צִוְּךָ יְהוָה אֱלֹהֶיךָ", "נהאך ענה אללה רבך", "God your Lord has forbidden you"),
    ],
    24: [
        ("כִּי", "לאן", "For"),
        ("יְהוָה אֱלֹהֶיךָ", "עקאב אללה רבך", "the punishment of God your Lord"),
        ("אֵשׁ אֹכְלָה", "נאר אכאלה", "is a consuming fire"),
        ("הוּא", "הו", "He is"),
        ("אֵל קַנָּא", "אלטאיק אלמעאקב", "the one possessed of power, the Punisher"),
    ],
    25: [
        ("כִּי-תוֹלִיד", "ואזא אולדתם", "When you beget"),
        ("בָּנִים", "בנין", "sons"),
        ("וּבְנֵי בָנִים", "ובני בנין", "and grandsons"),
        ("וְנוֹשַׁנְתֶּם בָּאָרֶץ", "ועתקתם פי אלבלד", "and grow old in the land"),
        ("וְהִשְׁחַתֶּם", "פאפסדתמ", "and you corrupt yourselves"),
        ("וַעֲשִׂיתֶם פֶּסֶל", "באן עמלתם פסלא", "by making a graven image"),
        ("תְּמוּנַת כֹּל", "מן כל שבה", "of any likeness"),
        ("וַעֲשִׂיתֶם הָרַע", "ופעלתם אלשר", "and do evil"),
        ("בְּעֵינֵי יְהוָה-אֱלֹהֶיךָ", "בין ידי אללה רבכם", "before God your Lord"),
        ("לְהַכְעִיסוֹ", "ואסכ'טתמוה", "and provoke Him"),
    ],
    26: [
        ("הַעִידֹתִי בָכֶם", "קד אשהדת עליכם", "I call to witness against you"),
        ("הַיּוֹם", "מן אליום", "today"),
        ("אֶת-הַשָּׁמַיִם", "אלסמאואת", "the heavens"),
        ("וְאֶת-הָאָרֶץ", "ואלארץ'", "and the earth"),
        ("כִּי-אָבֹד תֹּאבֵדוּן", "אנכם סתבידון", "you shall surely perish"),
        ("מַהֵר", "סריעא", "swiftly"),
        ("מֵעַל הָאָרֶץ", "ען אלבלד", "from the land"),
        ("אֲשֶׁר אַתֶּם עֹבְרִים", "אלזי אנתם עאברין", "to which you are crossing"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("שָׁמָּה לְרִשְׁתָּהּ", "אליה לתחוזוה", "to possess it"),
        ("לֹא-תַאֲרִיכֻן יָמִים עָלֶיהָ", "ולא תטול מדתכם פיה", "you shall not prolong your time in it"),
        ("כִּי הִשָּׁמֵד תִּשָּׁמֵדוּן", "בל אנפאזא תנפזון", "but shall utterly be wiped out"),
    ],
    27: [
        ("וְהֵפִיץ יְהוָה אֶתְכֶם", "ויבדדכם", "And He will scatter you"),
        ("בָּעַמִּים", "פי מא בין אלאממ", "among the nations"),
        ("וְנִשְׁאַרְתֶּם", "ותבקון", "and you shall remain"),
        ("מְתֵי מִסְפָּר", "רהט זו אחצא", "a group that can be counted"),
        ("בַּגּוֹיִם", "פי מא בין אלאממ", "among the nations"),
        ("אֲשֶׁר יְנַהֵג יְהוָה אֶתְכֶם שָׁמָּה", "אלזי יסוקכם אללה אלי' ת'מ", "to which God drives you"),
    ],
    28: [
        ("וַעֲבַדְתֶּם-שָׁם", "ותכ'דמון ת'ם", "And there you shall serve"),
        ("אֱלֹהִים", "מעבודאת", "objects of worship"),
        ("מַעֲשֵׂה יְדֵי אָדָם", "מן צנעה' אידי אלנאס", "made by human hands"),
        ("עֵץ", "מן כ'שב", "of wood"),
        ("וָאֶבֶן", "וחגארה", "and stone"),
        ("אֲשֶׁר לֹא-יִרְאוּן", "מא לם תבצר", "which neither see"),
        ("וְלֹא יִשְׁמְעוּן", "ולא תסמע", "nor hear"),
        ("וְלֹא יֹאכְלוּן", "ולא תאכל", "neither eat"),
        ("וְלֹא יְרִיחֻן", "ולא תשתמ", "nor smell"),
    ],
    29: [
        ("וּבִקַּשְׁתֶּם", "פתטלבו", "And"),
        ("מִשָּׁם", "מן ת'ם", "from there you shall seek"),
        ("אֶת-יְהוָה אֱלֹהֶיךָ", "אללה רבכם", "God your Lord"),
        ("וּמָצָאתָ", "ותגדוה", "and find Him"),
        ("כִּי תִדְרְשֶׁנּוּ", "אזתלתמסוה", "when you search for Him"),
        ("בְּכָל-לְבָבְךָ", "מכ'לצא בכל קלבך", "with a whole heart"),
        ("וּבְכָל-נַפְשֶׁךָ", "ונפסך", "and soul"),
    ],
    30: [
        ("בַּצַּר לְךָ", "ואזא צ'אק בך", "When you are in distress"),
        ("וּמְצָאוּךָ", "ונאלתך", "come upon you"),
        ("כֹּל הַדְּבָרִים הָאֵלֶּה", "גמיע הזה אלאמור", "and all these things"),
        ("בְּאַחֲרִית הַיָּמִים", "פי אכ'ר אלאייאמ", "in the end of days"),
        ("וְשַׁבְתָּ", "פתוב", "then turn back"),
        ("עַד-יְהוָה אֱלֹהֶיךָ", "אלי' אללה רבך", "to God your Lord"),
        ("וְשָׁמַעְתָּ בְּקֹלוֹ", "ואקבל אמרה", "and accept His command"),
    ],
    31: [
        ("כִּי", "לאן", "For"),
        ("אֵל רַחוּם", "טאיק רחומ", "possessed of power, compassionate"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord is"),
        ("לֹא יַרְפְּךָ", "לא יכ'ליך", "He will not forsake you"),
        ("וְלֹא יַשְׁחִיתֶךָ", "ולא יתרכך", "nor abandon you"),
        ("וְלֹא יִשְׁכַּח", "ולא ינסא", "and He will not forget"),
        ("אֶת-בְּרִית אֲבֹתֶיךָ", "עהד אבאיך", "the covenant of your fathers"),
        ("אֲשֶׁר נִשְׁבַּע לָהֶם", "אלזי קסם בה להמ", "which He swore to them"),
    ],
    32: [
        (None, "ואלאן", "And now"),
        ("שְׁאַל-נָא", "פאסאלען", "inquire"),
        ("לְיָמִים רִאשֹׁנִים", "אלאייאם אלאואיל", "about the former days"),
        ("אֲשֶׁר-הָיוּ לְפָנֶיךָ", "אלזי סלפת מן קבלך", "that were before your time"),
        ("לְמִן-הַיּוֹם", "מן יום", "from the day"),
        ("אֲשֶׁר בָּרָא אֱלֹהִים אָדָם", "כ'לק אללה אדם", "God created Adam"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
        ("וּלְמִקְצֵה הַשָּׁמַיִם", "ומן טרף אלסמא", "and from one end of the sky"),
        ("וְעַד-קְצֵה הַשָּׁמָיִם", "אלי' טרפהא", "to the other"),
        ("הֲנִהְיָה כַּדָּבָר הַגָּדוֹל הַזֶּה", "הל כאן קט מת'ל הזא אלאמר אלעצימ", "has there ever been anything like this great thing"),
        ("אוֹ הֲנִשְׁמַע כָּמֹהוּ", "או סמע מתלה", "or has the like of it been heard"),
    ],
    33: [
        ("הֲשָׁמַע", "והל סמעת", "Has"),
        ("עָם", "אמה", "a nation ever heard"),
        ("קוֹל אֱלֹהִים", "צות אללה", "the voice of God"),
        ("מְדַבֵּר", "מכלמהא", "speaking to it"),
        ("מִתּוֹךְ-הָאֵשׁ", "מן וסט אלנר", "from within fire"),
        ("כַּאֲשֶׁר-שָׁמַעְתָּ אַתָּה", "כמא סמעת אנת", "as you heard"),
        ("וַיֶּחִי", "פעאשת", "and lived"),
    ],
    34: [
        ("אוֹ הֲנִסָּה אֱלֹהִים", "או רפע אללה לה", "Or has God raised a banner for anyone"),
        (None, "על מא", "appearing"),
        ("לָבוֹא לָקַחַת לוֹ", "באן צ'הר פתכ'לץ לה", "in order to deliver for him"),
        ("גוֹי", "אמה", "a nation"),
        ("מִקֶּרֶב גּוֹי", "מן בין אכ'רא", "from the midst of another"),
        ("בְּמַסֹּת", "באעלאם", "by signs"),
        ("בְּאֹתֹת", "ואיאת", "and wonders"),
        ("וּבְמוֹפְתִים", "ובראהין", "and proofs"),
        ("וּבְמִלְחָמָה", "ומלחמה", "and by battle"),
        ("וּבְיָד חֲזָקָה", "ויד שדידה", "and a mighty hand"),
        ("וּבִזְרוֹעַ נְטוּיָה", "ודראע ממדודה", "and an outstretched arm"),
        ("וּבְמוֹרָאִים גְּדֹלִים", "ומכ'אוף ]עט'ימה] עצ'ימה", "and great terrors"),
        ("כְּכֹל אֲשֶׁר-עָשָׂה", "כמא צנע", "as all that"),
        ("לָכֶם יְהוָה אֱלֹהֵיכֶם", "לכם אללה רבכמ", "God your Lord did for you"),
        ("בְּמִצְרַיִם", "במצר", "in Egypt"),
        ("לְעֵינֶיךָ", "בחצ'רתכמ", "before your eyes"),
    ],
    35: [
        ("אַתָּה הָרְאֵתָ", "פאנת יגב עליך", "You are therefore obliged"),
        ("לָדַעַת", "אן תעלמ", "to know"),
        ("כִּי יְהוָה הוּא הָאֱלֹהִים", "אן אללה הו אלאלאה", "that God is the God"),
        ("אֵין עוֹד", "לא ג'ירה", "there is no other"),
        ("מִלְּבַדּוֹ", "ולא סואה", "beside Him, and none beside Him"),
    ],
    36: [
        ("מִן-הַשָּׁמַיִם", "ומן אלסמא", "From the sky"),
        ("הִשְׁמִיעֲךָ", "אסמעך", "He let you hear"),
        ("אֶת-קֹלוֹ", "צותה", "His voice"),
        ("לְיַסְּרֶךָּ", "ליודבך", "to instruct you"),
        ("וְעַל-הָאָרֶץ", "ועלי' אלארץ'", "and upon the earth"),
        ("הֶרְאֲךָ", "אוראך", "He showed you"),
        ("אֶת-אִשּׁוֹ הַגְּדוֹלָה", "נארה אל]עט'ימה] עצ'ימה", "His great fire"),
        ("וּדְבָרָיו שָׁמַעְתָּ", "וסמעת כלאמה", "and you heard His words"),
        ("מִתּוֹךְ הָאֵשׁ", "מן דאכ'להא", "from within it"),
    ],
    37: [
        ("וְתַחַת כִּי", "וזאלך בעד מא", "And that was because"),
        ("אָהַב אֶת-אֲבֹתֶיךָ", "אחב אבאיך", "He loved your fathers"),
        ("וַיִּבְחַר בְּזַרְעוֹ", "ואכ'תאר נסלהם", "and chose their offspring"),
        ("אַחֲרָיו", "מן בעדהמ", "after them"),
        ("וַיּוֹצִאֲךָ", "ואכ'רגך", "and brought you out"),
        ("בְּפָנָיו", "ברצ'אה", "by His will"),
        ("בְּכֹחוֹ הַגָּדֹל", "בקוותה אל]עט'ימה] ]עט'ימה] עצ'ימה", "in His great power"),
        ("מִמִּצְרָיִם", "מן מצר", "from Egypt"),
    ],
    38: [
        ("לְהוֹרִישׁ גּוֹיִם", "ליקרץ' אממא", "to dispossess nations"),
        ("גְּדֹלִים", "אכת'ר", "greater"),
        ("וַעֲצֻמִים", "ואעצ'ם", "and mightier"),
        ("מִמְּךָ", "מנך", "than you"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "before you"),
        ("לַהֲבִיאֲךָ", "לידכ'לך", "to bring you in"),
        ("לָתֶת-לְךָ", "ליעטיך", "and give you"),
        ("אֶת-אַרְצָם", "בלדהמ", "their land"),
        ("נַחֲלָה", "נחלה", "as an inheritance"),
        ("כַּיּוֹם הַזֶּה", "כמא תרי אליומ", "as you see this day"),
    ],
    39: [
        (None, "פאעלם", "Know this therefore"),
        ("וְיָדַעְתָּ הַיּוֹם", "זאלך", "and"),
        ("וַהֲשֵׁבֹתָ אֶל-לְבָבֶךָ", "וארדדה פי קלבך", "turn it over in your heart"),
        ("כִּי יְהוָה הוּא הָאֱלֹהִים", "אן אללה הוא אלאלאה", "that God is the God"),
        ("בַּשָּׁמַיִם מִמַּעַל", "פי אלסמאואת אלעליא", "in the heavens above"),
        ("וְעַל-הָאָרֶץ מִתָּחַת", "ואלארץ' אלספלא", "and the earth below"),
        ("אֵין עוֹד", "לא סואה", "there is none other"),
    ],
    40: [
        ("וְשָׁמַרְתָּ", "ואחפץ'", "And keep"),
        ("אֶת-חֻקָּיו", "רסומה", "His statutes"),
        ("וְאֶת-מִצְו‍ֹתָיו", "ווצאיאה", "and His commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", "אלתי אנא אמרך בהא אליומ", "which I command you today"),
        ("אֲשֶׁר יִיטַב לְךָ", "לכי יכ'אר לך", "so that it may go well for you"),
        ("וּלְבָנֶיךָ אַחֲרֶיךָ", "ולבניך מן בעדך", "and for your children after you"),
        ("וּלְמַעַן תַּאֲרִיךְ יָמִים", "ולכי תטול מדתך", "and so that your span of days may be long"),
        ("עַל-הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלזי אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ כָּל-הַיָּמִים", "מעטיך טול אלזמאן", "is giving you for all time"),
    ],
    41: [
        (None, "חיניזאפרז", "At that time"),
        ("אָז יַבְדִּיל מֹשֶׁה", "מוסי'", "Moses"),
        ("שָׁלֹשׁ עָרִים", "ת'לאת' קרא", "set apart three towns"),
        ("בְּעֵבֶר הַיַּרְדֵּן מִזְרְחָה שָׁמֶשׁ", "פי גאנב אלארדן אלשרקי", "on the eastern side of the Jordan"),
    ],
    42: [
        ("לָנֻס שָׁמָּה", "ליהרב אליה", "so that every slayer"),
        ("רוֹצֵחַ", "כל קאתל", "who kills"),
        ("אֲשֶׁר יִרְצַח אֶת-רֵעֵהוּ", "יקתל צאחבה", "his fellow"),
        ("בִּבְלִי-דַעַת", "בג'יר קצד", "without intent"),
        ("וְהוּא לֹא-שֹׂנֵא לוֹ", "והוא ג'יר שאני לה", "he not having been hostile to him"),
        ("מִתְּמֹל שִׁלְשֹׁם", "מן אמס ומא קבלה", "from yesterday and before"),
        ("וְנָס אֶל-אַחַת מִן-הֶעָרִים הָאֵל", "פיהרב אלי' ואחדה מנהא", "might flee to one of them"),
        ("וָחָי", "פיחיא", "and live"),
    ],
    43: [
        ("אֶת-בֶּצֶר בַּמִּדְבָּר", "פבצר פי אלבר", "Bostra in the wilderness"),
        ("בְּאֶרֶץ הַמִּישֹׁר", "פי בלד אלסהל", "in the land of the plain"),
        ("לָראוּבֵנִי", "מן בלד ראובן", "from the land of Reuben"),
        ("וְאֶת-רָאמֹת בַּגִּלְעָד", "ורמות פי גרש", "and Ramoth in Gerash"),
        ("לַגָּדִי", "מן בלד גד", "from the land of Gad"),
        ("וְאֶת-גּוֹלָן בַּבָּשָׁן", "וגולן פי אלבת'נייה", "and Golan in Bathaniyya"),
        ("לַמְנַשִּׁי", "מן בלד מנשה", "from the land of Manasseh"),
    ],
    44: [
        ("וְזֹאת הַתּוֹרָה", "והזה אלשריעה", "And this is the teaching"),
        ("אֲשֶׁר-שָׂם מֹשֶׁה", "אלתי תלאהא מוסי'", "which Moses recited"),
        ("לִפְנֵי בְּנֵי יִשְׂרָאֵל", "בחצ'רה' בני אסראיל", "before the sons of Israel"),
    ],
    45: [
        ("אֵלֶּה הָעֵדֹת", "והזה אלשואהד", "These are the testimonies"),
        ("וְהַחֻקִּים", "ואלרסום", "and the statutes"),
        ("וְהַמִּשְׁפָּטִים", "ואלאחכאמ", "and the ordinances"),
        ("אֲשֶׁר דִּבֶּר מֹשֶׁה", "אלזי אמר בהא מוסי'", "which Moses commanded"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "to the sons of Israel"),
        ("בְּצֵאתָם מִמִּצְרָיִם", "פי כ'רוגהם מן מצר", "at their going forth from Egypt"),
    ],
    46: [
        ("בְּעֵבֶר הַיַּרְדֵּן", "פי זאך גאנב אלארדן", "on that side of the Jordan"),
        ("בַּגַּיְא", "פי אלואד", "in the valley"),
        ("מוּל בֵּית פְּעוֹר", "ממא ילי בית פעור", "facing Beth Peor"),
        ("בְּאֶרֶץ סִיחֹן", "פי בלד סיחון", "in the land of Sihon"),
        ("מֶלֶךְ הָאֱמֹרִי", "מלך אלאמוריין", "king of the Amorites"),
        ("אֲשֶׁר יוֹשֵׁב", "אלמקים", "who dwelt"),
        ("בְּחֶשְׁבּוֹן", "פי חשבון", "in Heshbon"),
        ("אֲשֶׁר הִכָּה מֹשֶׁה", "אלזי קתלה מוסי'", "whom Moses"),
        ("וּבְנֵי יִשְׂרָאֵל", "ובני אסראיל", "and the sons of Israel struck down"),
        ("בְּצֵאתָם מִמִּצְרָיִם", "פי כ'רוגהם מן מצר", "at their going forth from Egypt"),
    ],
    47: [
        ("וַיִּירְשׁוּ אֶת-אַרְצוֹ", "פחאזו בלדה", "And they took possession of his land"),
        ("וְאֶת-אֶרֶץ עוֹג", "ובלד עוג", "and the land of Og"),
        ("מֶלֶךְ-הַבָּשָׁן", "מלך אלבת'נייה", "king of Bathaniyya"),
        ("שְׁנֵי מַלְכֵי הָאֱמֹרִי", "והמא מלכי אלאמוריין", "the two kings of the Amorites"),
        ("אֲשֶׁר בְּעֵבֶר הַיַּרְדֵּן--מִזְרַח שָׁמֶשׁ", "אלזי פי גאנב אלארדן אלשרקי", "who were on the eastern side of the Jordan"),
    ],
    48: [
        ("מֵעֲרֹעֵר", "מן ערוער", "From Aroer"),
        ("אֲשֶׁר עַל-שְׂפַת-נַחַל אַרְנֹן", "אלזי עלי' שאט ואד ארנון", "which is on the bank of the valley of Arnon"),
        ("וְעַד-הַר שִׂיאֹן", "ואלי' גבל שיאון", "as far as Mount Sion"),
        ("הוּא חֶרְמוֹן", "הו חרמון", "that is Hermon"),
    ],
    49: [
        ("וְכָל-הָעֲרָבָה", "וגמיע אלג'ור", "and all the Ghor"),
        ("עֵבֶר הַיַּרְדֵּן מִזְרָחָה", "גאנב אלארדן אלשרקי", "on the eastern side of the Jordan"),
        ("וְעַד יָם הָעֲרָבָה", "ואלי' בחירה' טבריה", "as far as the Sea of Tiberias"),
        ("תַּחַת אַשְׁדֹּת הַפִּסְגָּה", "תחת מצב אלקלעה", "below the outlet of the fortress"),
    ],
}
