"""Hand-authored alignment triples for Devarim (Deuteronomy) chapter 5.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיִּקְרָא", "דעא", "summoned"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-כָּל", "בגמיע", "all"),
        ("יִשְׂרָאֵל", "אלאסראיל", "of Israel"),
        ("וַיֹּאמֶר", "וקאל", "and said"),
        ("אֲלֵהֶם", "להמ", "to them"),
        ("שְׁמַע", "אסמעו", "Hear"),
        ("אֶת-הַחֻקִּים", "אלרסום", "the statutes"),
        ("וְאֶת-הַמִּשְׁפָּטִים", "ואלאחכאמ", "and the ordinances"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("אָנֹכִי", "אנא", "I"),
        ("דֹּבֵר", "אמרכם", "command"),
        ("הַיּוֹם", "אליומ", "today"),
        ("וּלְמַדְתֶּם", "פתעלמוהא", "then learn them"),
        ("וּשְׁמַרְתֶּם", "ואחפצוהא", "and keep them"),
        ("לַעֲשֹׂתָם", "ואעמלו בהא", "and act by them"),
    ],
    2: [
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        ("כָּרַת", "עהד", "made"),
        ("עִמָּנוּ", "מענא", "with us"),
        ("בְּרִית", "עהדא", "a covenant"),
        ("בְּחֹרֵב", "פי חריב", "at Horeb"),
    ],
    3: [
        ("לֹא", "וליס", "And it was not"),
        ("אֶת-אֲבֹתֵינוּ", "מע אבאינא", "with our fathers"),
        (None, "פקט", "alone"),
        ("כָּרַת יְהוָה", "עהד אללה", "that God made"),
        ("אֶת-הַבְּרִית הַזֹּאת", "זאלך אלעהד", "that covenant"),
        ("כִּי", "בל", "but"),
        ("אִתָּנוּ", "מענא", "with us"),
        (None, "איצ'א", "also"),
        ("אֲנַחְנוּ", "ונחן", "and we"),
        ("פֹה", "ההנא", "here"),
        ("כֻּלָּנוּ", "כלנא", "all of us"),
        ("חַיִּים", "אחיא", "alive"),
        ("הַיּוֹם", "אליומ", "today"),
    ],
    4: [
        (None, "וזאלך", "And that was"),
        (None, "אן", ":"),
        ("פָּנִים בְּפָנִים", "שפאהא", "directly by word of mouth"),
        ("דִּבֶּר", "כלמכם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("עִמָּכֶם", "פי", "to you"),
        ("בָּהָר", "אלגבל", "on the mountain"),
        ("מִתּוֹךְ", "מן וסט", "from within"),
        ("הָאֵשׁ", "אלנר", "the fire"),
    ],
    5: [
        ("אָנֹכִי", "ואנא", "And I"),
        ("עֹמֵד", "כנת קאים", "was standing"),
        ("בֵּין-יְהוָה", "בין נור אללה", "between the light of God"),
        ("וּבֵינֵיכֶם", "ובינכם", "and between you"),
        ("בָּעֵת הַהִוא", "פי זאלך אלוקת", "at that time"),
        ("לְהַגִּיד", "לאכ'ברכם", "to inform you"),
        ("אֶת-דְּבַר יְהוָה", "בכלאם אללה", "of the word of God"),
        ("כִּי", "לאנכם", "for you"),
        ("יְרֵאתֶם", "כ'פתם", "feared"),
        ("מִפְּנֵי הָאֵשׁ", "אלנאר", "the fire"),
        ("וְלֹא-עֲלִיתֶם", "ולם תצעדו", "and did not ascend"),
        ("בָּהָר", "אלגבל", "the mountain"),
        ("לֵאמֹר", "פקאללכמ", "and He said to you"),
    ],
    6: [
        ("אָנֹכִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲשֶׁר", "אלזי", "who"),
        ("הוֹצֵאתִיךָ", "אכ'רגתך", "brought you out"),
        ("מֵאֶרֶץ", "מן בלד", "from the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("מִבֵּית", "מן בית", "from the house of"),
        ("עֲבָדִים", "אלעבודייה", "bondage"),
    ],
    7: [
        ("לֹא-יִהְיֶה", "לא יכון", "You shall have no"),
        ("לְךָ", "לך", "other"),
        ("אֱלֹהִים אֲחֵרִים", "מעבוד אכ'ר", "object of worship"),
        ("עַל-פָּנָי", "מן דוני", "apart from Me"),
    ],
    8: [
        ("לֹא-תַעֲשֶׂה", "ולא תצנע", "And you shall not make"),
        ("לְךָ", "לך", "for yourself"),
        ("פֶסֶל", "פסלא", "a graven image"),
        ("כָּל-תְּמוּנָה", "ולא שבהא", "nor a likeness"),
        ("אֲשֶׁר בַּשָּׁמַיִם", "ממא פי אלסמא", "of anything that is in the sky"),
        ("מִמַּעַל", "פי אלעלו", "above"),
        ("וַאֲשֶׁר בָּאָרֶץ", "וממא פי אלארץ'", "or that is in the earth"),
        ("מִתָּחַת", "פי אלספל", "below"),
        ("וַאֲשֶׁר בַּמַּיִם", "וממא פי אלמא", "or that is in the water"),
        ("מִתַּחַת לָאָרֶץ", "אלזי תחת אלארץ'", "which is beneath the earth"),
    ],
    9: [
        ("לֹא-תִשְׁתַּחֲוֶה", "לא תסגד", "You shall not bow down"),
        ("לָהֶם", "להא", "to them"),
        ("וְלֹא תָעָבְדֵם", "ולא תעבדהא", "nor worship them"),
        ("כִּי אָנֹכִי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֵל קַנָּא", "אלטאיק אלמעאקב", "the powerful, the punishing"),
        ("פֹּקֵד עֲו‍ֹן אָבוֹת", "מטאלב בזנוב אלאבא", "who calls to account the sins of the fathers"),
        ("עַל-בָּנִים", "מע אלבנין", "together with the children"),
        ("וְעַל-שִׁלֵּשִׁים", "ואלת'ואלת'", "and the third"),
        ("וְעַל-רִבֵּעִים", "ואלרואבע", "and fourth generations"),
        ("לְשֹׂנְאָי", "לשאניי", "for those who hate Me"),
    ],
    10: [
        ("וְעֹשֶׂה חֶסֶד", "ומגאזי באלאחסאן", "and who rewards with goodness"),
        ("לַאֲלָפִים", "לאלאלוף", "thousands"),
        ("לְאֹהֲבַי", "מן מחבי", "of those who love Me"),
        ("וּלְשֹׁמְרֵי", "וחאפצ'י", "and keep"),
        ("מצותו", "וצאיאי", "My commandments"),
    ],
    11: [
        ("לֹא תִשָּׂא", "לא תחלף", "You shall not swear"),
        ("אֶת-שֵׁם-יְהוָה", "באסם אללה", "by the name of God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לַשָּׁוְא", "זורא", "falsely"),
        ("כִּי", "לאן", "for"),
        ("לֹא יְנַקֶּה", "לא יברי", "will not acquit"),
        ("יְהוָה", "אללה", "God"),
        ("אֵת אֲשֶׁר-יִשָּׂא", "מן יחלף", "one who swears"),
        ("אֶת-שְׁמוֹ", "באסמה", "by His name"),
        ("לַשָּׁוְא", "זורא", "falsely"),
    ],
    12: [
        ("שָׁמוֹר", "אחפץ'", "Keep"),
        ("אֶת-יוֹם הַשַּׁבָּת", "יום אלסבת", "the Sabbath day"),
        ("לְקַדְּשׁוֹ", "וקדסה", "and sanctify it"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוְּךָ", "אמרך", "has commanded you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
    ],
    13: [
        ("שֵׁשֶׁת", "סתה'", "Six"),
        ("יָמִים", "איאם", "days"),
        ("תַּעֲבֹד", "תעמל", "you shall labor"),
        ("וְעָשִׂיתָ", "ותצנע", "and do"),
        ("כָּל-מְלַאכְתֶּךָ", "גמיע צנאיעך", "all your craft"),
    ],
    14: [
        ("וְיוֹם הַשְּׁבִיעִי", "ואליום אלסאבע", "But the seventh day"),
        ("שַׁבָּת", "סבת", "is a Sabbath"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לֹא תַעֲשֶׂה", "לא תעמל", "you shall do no"),
        ("כָל-מְלָאכָה", "שייא מן אלצנאיע", "craft whatsoever"),
        ("אַתָּה", "אנת", "you"),
        ("וּבִנְךָ", "ואבנך", "and your son"),
        ("וּבִתֶּךָ", "ואבנתך", "and your daughter"),
        ("וְעַבְדְּךָ", "ועבדך", "and your male slave"),
        ("וַאֲמָתֶךָ", "ואמתך", "and your female slave"),
        ("וְשׁוֹרְךָ", "ות'ורך", "and your ox"),
        ("וַחֲמֹרְךָ", "וחמארך", "and your donkey"),
        ("וְכָל-בְּהֶמְתֶּךָ", "וסאיר בהאימך", "and the rest of your beasts"),
        ("וְגֵרְךָ", "וצ'יפך", "and your guest"),
        ("אֲשֶׁר בִּשְׁעָרֶיךָ", "אלזי פי מחאלך", "who is in your dwelling"),
        ("לְמַעַן יָנוּחַ", "לכי יסתריח", "so that"),
        ("עַבְדְּךָ", "עבדך", "your male slave"),
        ("וַאֲמָתְךָ", "ואמתך", "and your female slave may rest"),
        ("כָּמוֹךָ", "מת'לך", "like yourself"),
    ],
    15: [
        ("וְזָכַרְתָּ", "ואזכר", "And remember"),
        ("כִּי", "אנך", "that you"),
        ("עֶבֶד", "כנת עבדא", "were a slave"),
        ("בְּאֶרֶץ", "פי בלד", "in the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("וַיֹּצִאֲךָ", "ואכ'רגך", "brought you out"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מִשָּׁם", "מן ת'ם", "from there"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a strong hand"),
        ("וּבִזְרֹעַ נְטוּיָה", "וזראע ממדודה", "and an outstretched arm"),
        ("עַל-כֵּן", "ולזאלך", "and for that reason"),
        ("צִוְּךָ", "אמרך", "He commanded you"),
        ("לַעֲשׂוֹת", "אן תקים פי", "to observe"),
        ("אֶת-יוֹם הַשַּׁבָּת", "יום אלסבת", "the Sabbath day"),
    ],
    16: [
        ("כַּבֵּד", "אכרם", "Honor"),
        ("אֶת-אָבִיךָ", "אביך", "your father"),
        ("וְאֶת-אִמֶּךָ", "ואמך", "and your mother"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוְּךָ", "אמרך", "has commanded you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְמַעַן יַאֲרִיכֻן", "לכי תטול", "so that"),
        ("יָמֶיךָ", "מדתך", "your term of life may be long"),
        ("וּלְמַעַן יִיטַב לָךְ", "ויכ'אר לך", "and that it may go well for you"),
        ("עַל הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-יְהוָה", "אלזי אללה", "which"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
    ],
    17: [
        ("לֹא תִרְצָח", "לא תקתל אלנפס", "You shall not kill a person"),
        ("וְלֹא תִנְאָף", "ולא תזן", "And you shall not commit adultery"),
        ("וְלֹא תִגְנֹב", "ולא תסרק", "And you shall not steal"),
        ("וְלֹא-תַעֲנֶה", "ולא תשהד", "And you shall not bear"),
        ("בְרֵעֲךָ", "עלי' צאחבך", "against your fellow"),
        ("עֵד שָׁוְא", "שהאדה' זור", "false witness"),
    ],
    18: [
        ("וְלֹא תַחְמֹד", "ולא תתמן", "And you shall not desire"),
        ("אֵשֶׁת", "זוגה'", "the wife of"),
        ("רֵעֶךָ", "צאחבך", "your fellow"),
        ("וְלֹא תִתְאַוֶּה", "ולא תתשה", "and you shall not covet"),
        ("בֵּית", "מנזלה", "his dwelling"),
        ("רֵעֶךָ", "וצ'יעתה", "his estate"),
        ("וְעַבְדּוֹ", "ועבדה", "his male slave"),
        ("וַאֲמָתוֹ", "ואמתה", "and his female slave"),
        ("שׁוֹרוֹ", "ת'ורה", "his ox"),
        ("וַחֲמֹרוֹ", "וחמארה", "and his donkey"),
        ("וְכֹל אֲשֶׁר לְרֵעֶךָ", "וגמיע מאלה", "and all that is his"),
    ],
    19: [
        ("אֶת-הַדְּבָרִים הָאֵלֶּה", "הזה אלכלמאת", "These words"),
        ("דִּבֶּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        (None, "בהא", "to"),
        ("אֶל-כָּל-קְהַלְכֶם", "גמיע קומכם", "all your people"),
        ("בָּהָר", "פי אלגבל", "on the mountain"),
        ("מִתּוֹךְ הָאֵשׁ", "מן לדן אלנר", "from within the fire"),
        ("הֶעָנָן", "ואלג'מאם", "and the cloud"),
        ("וְהָעֲרָפֶל", "ואלצ'באב", "and the mist"),
        ("קוֹל גָּדוֹל", "בצות עצ'ם", "with a great voice"),
        ("וְלֹא יָסָף", "ג'יר מעאוד", "not to be repeated"),
        ("וַיִּכְתְּבֵם", "וכתבהא", "and He wrote them"),
        ("עַל-שְׁנֵי לֻחֹת", "עלי' לוחי", "upon two tablets of"),
        ("אֲבָנִים", "אלגוהר", "crystal"),
        ("וַיִּתְּנֵם", "ודפעהמא", "and delivered them"),
        ("אֵלָי", "אליי", "to me"),
    ],
    20: [
        ("וַיְהִי כְּשָׁמְעֲכֶם", "פלמא סמעתם", "And when you heard"),
        ("אֶת-הַקּוֹל", "אלצות", "the voice"),
        ("מִתּוֹךְ הַחֹשֶׁךְ", "מן לדן צ'לאם", "from within the darkness"),
        ("וְהָהָר", "אלג'ימ. ואלגבל", "of the cloud, and the mountain"),
        ("בֹּעֵר בָּאֵשׁ", "משתעל באלנר", "was ablaze with fire"),
        ("וַתִּקְרְבוּן אֵלַי", "פתקדם אליי", "came forward to me"),
        ("כָּל-רָאשֵׁי שִׁבְטֵיכֶם", "רויסא אסבאטכם", "the heads of your tribes"),
        ("וְזִקְנֵיכֶם", "ומשאיכ'כמ", "and your elders"),
    ],
    21: [
        ("וַתֹּאמְרוּ", "פקלת'מ", "and you said"),
        (None, "הוזא", "Behold"),
        ("הֶרְאָנוּ", "קד אוראנא", "has shown us"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        ("אֶת-כְּבֹדוֹ", "כרמה", "His glory"),
        ("וְאֶת-גָּדְלוֹ", "ועצ'מתה", "and His greatness"),
        ("וְאֶת-קֹלוֹ", "וסמענא צותה", "and we heard His voice"),
        ("מִתּוֹךְ הָאֵשׁ", "מן דאכ'ל אלנאר", "from within the fire"),
        ("הַיּוֹם הַזֶּה", "אליומ", "today"),
        ("רָאִינוּ", "פעלמנא", "and we have known"),
        ("כִּי-יְדַבֵּר", "אנה יגוז אן יכלם", "that it is possible"),
        ("אֱלֹהִים", "אללה", "speak"),
        ("אֶת-הָאָדָם", "אנסאנא", "to a human being"),
        ("וָחָי", "ויחיא", "and that he live"),
    ],
    22: [
        ("וְעַתָּה", "ואלאן", "And now"),
        ("לָמָּה נָמוּת", "פלא נהלך", "lest we perish"),
        ("כִּי תֹאכְלֵנוּ", "ולא תאכלנא", "and lest this great fire"),
        ("הָאֵשׁ הַגְּדֹלָה הַזֹּאת", "הזה אלנאר אלעצי'מה", "consume us"),
        ("אִם-יֹסְפִים", "פאנא אן עאודנא", "for if we were"),
        ("לִשְׁמֹעַ", "אסתמאע", "to hear"),
        ("אֶת-קוֹל יְהוָה", "כלאם אללה", "the word of God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        (None, "איצ'א", "directly"),
        ("וָמָתְנוּ", "מתנא", "we would die"),
    ],
    23: [
        ("כִּי", "לאנה", "For"),
        ("מִי", "אי", "what"),
        ("כָל-בָּשָׂר", "בשרי", "mortal being"),
        ("אֲשֶׁר שָׁמַע", "סמע", "has heard"),
        ("קוֹל", "צות", "the voice"),
        ("אֱלֹהִים", "אללה", "God"),
        ("חַיִּים", "אלחי", "living"),
        ("מְדַבֵּר", "מכ'אטבה", "addressing him"),
        ("מִתּוֹךְ-הָאֵשׁ", "מן וסט אלנאר", "from within the fire"),
        ("כָּמֹנוּ", "מת'לנא", "as we did"),
        ("וַיֶּחִי", "פעאש", "and yet lived"),
    ],
    24: [
        ("קְרַב", "תקדם", "Go forward"),
        ("אַתָּה", "אנת", "yourself"),
        ("וּשְׁמָע", "ואסמע", "and hear"),
        ("אֵת כָּל-אֲשֶׁר יֹאמַר", "גמיע מא יקולה", "will say"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        ("וְאַתְּ תְּדַבֵּר", "ואנת תכלמנא", "and you speak to us"),
        ("אֵת כָּל-אֲשֶׁר יְדַבֵּר", "בגמיעה", "all of it"),
        ("וְשָׁמַעְנוּ", "ונסמעה", "and we shall hear it"),
        ("וְעָשִׂינוּ", "ונעמל בה", "and act by it"),
    ],
    25: [
        ("וַיִּשְׁמַע", "פסמע", "And God"),
        ("יְהוָה", "אללה", "heard"),
        ("אֶת-קוֹל דִּבְרֵיכֶם", "כלאמכמ", "your words"),
        ("בְּדַבֶּרְכֶם", "אזכלמתמוני", "when you spoke to me"),
        ("וַיֹּאמֶר יְהוָה", "פקאלאללה", "and God said"),
        ("אֵלַי", "לי", "to me"),
        ("שָׁמַעְתִּי", "סמעת", "I have heard"),
        ("אֶת-קוֹל דִּבְרֵי", "כלאם", "the words of"),
        ("הָעָם הַזֶּה", "הולאי אלקום", "these people"),
        ("אֲשֶׁר דִּבְּרוּ", "אלזי כלמוך", "who spoke to you"),
        ("הֵיטִיבוּ", "קד אחסנו", "they have spoken well"),
        ("כָּל-אֲשֶׁר דִּבֵּרוּ", "פי גמיע מא קאלו", "in all that they have said"),
    ],
    26: [
        ("מִי-יִתֵּן", "פליתמנו", "Would that"),
        ("וְהָיָה לְבָבָם זֶה לָהֶם", "אן יבקא להם הזא אלקלב", "they remain possessed of this heart"),
        ("לְיִרְאָה אֹתִי", "אן יכ'אפוני", "to fear Me"),
        ("וְלִשְׁמֹר", "ויחפצו", "and to keep"),
        ("אֶת-כָּל-מִצְו‍ֹתַי", "וצאיאי", "My commandments"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "all the time"),
        ("לְמַעַן יִיטַב לָהֶם", "לכי יכ'אר להמ", "so that it may go well for them"),
        ("וְלִבְנֵיהֶם", "ולבניהם", "and for their children"),
        ("לְעֹלָם", "אלי' אלדהר", "forever"),
    ],
    27: [
        ("לֵךְ", "אמץ'", "Go"),
        ("אֱמֹר", "קל", "tell"),
        ("לָהֶם", "להמ", "them"),
        ("שׁוּבוּ", "ארגעו", "Return"),
        ("לָכֶם", "אלי'", "to"),
        ("לְאָהֳלֵיכֶם", "אכ'ביתכמ", "your tents"),
    ],
    28: [
        ("וְאַתָּה", "ואנת", "But you"),
        ("פֹּה עֲמֹד עִמָּדִי", "פקם ההנא בין ידיי", "stand here before Me"),
        ("וַאֲדַבְּרָה", "חתי' אכלמך", "until I speak to you"),
        ("אֵת כָּל-הַמִּצְוָה", "בגמיע אלוצאיא", "all the commandments"),
        ("וְהַחֻקִּים", "ואלרסום", "and the statutes"),
        ("וְהַמִּשְׁפָּטִים", "ואלאחכאם", "and the ordinances"),
        ("אֲשֶׁר תְּלַמְּדֵם", "אלזי תעלמהמ", "which you shall teach them"),
        ("וְעָשׂוּ", "ויצנעון", "that they may do"),
        ("בָאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אָנֹכִי נֹתֵן לָהֶם", "אלזי אנא מעטיהם", "which I am giving them"),
        ("לְרִשְׁתָּהּ", "יחוזונה", "to possess"),
    ],
    29: [
        ("וּשְׁמַרְתֶּם", "ואחפצו", "So keep"),
        ("לַעֲשׂוֹת", "ואעמלו", "and do"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמרכם", "has commanded you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכמ", "your Lord"),
        ("לֹא תָסֻרוּ", "לא תזולו", "do not turn aside"),
        ("יָמִין", "ימנה", "to the right"),
        ("וּשְׂמֹאל", "ולא יסרה", "or to the left"),
    ],
}
