"""Hand-authored alignment triples for Devarim chapter 8.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "וגמיע", "And all"),
        ("כָּל-הַמִּצְוָה", "אלוצאיא", "the commandments"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("אָנֹכִי", "אמרך", "I charge"),
        ("מְצַוְּךָ", "בהא", "you with"),
        ("הַיּוֹם", "אליום", "today"),
        ("תִּשְׁמְרוּן", "אחפצוהא", "keep them"),
        ("לַעֲשׂוֹת", "ואעמלו בהא", "and act upon them"),
        ("לְמַעַן", "לכי", "that"),
        ("תִּחְיוּן", "תחיון", "you may live"),
        ("וּרְבִיתֶם", "ותכת'רון", "and multiply"),
        ("וּבָאתֶם", "ותדכ'לו", "and enter"),
        ("וִירִשְׁתֶּם", "ותחוזו", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-נִשְׁבַּע יְהוָה", "אלד'י קסם אללה", "which God swore"),
        ("לַאֲבֹתֵיכֶם", "לאבאיכם", "to your fathers"),
    ],
    2: [
        (None, "ואד'כר", "And remember"),
        ("אֶת-כָּל-הַדֶּרֶךְ", "גמיע אלטריק", "all the way"),
        ("אֲשֶׁר", "אלד'י", "along which"),
        ("הוֹלִיכְךָ", "סיירך", "made you journey"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
        ("זֶה", "הד'ה", "these"),
        ("אַרְבָּעִים שָׁנָה", "ארבעין", "forty years"),
        ("לְמַעַן עַנֹּתְךָ", "ליתעבך", "to weary you"),
        ("לְנַסֹּתְךָ", "וימתחנך", "and test you"),
        ("לָדַעַת", "ליצ'הר", "to make known"),
        (None, "לאלנאס", "to the people"),
        ("אֶת-אֲשֶׁר בִּלְבָבְךָ", "מא פי קלבך", "what is in your heart"),
        ("הֲתִשְׁמֹר מִצְו‍ֹתָו", "אתחפץ' וצאיאה", "whether you keep His commandments"),
        ("אִם-לֹא", "אם לא", "or not"),
    ],
    3: [
        ("וַיְעַנְּךָ", "ואתעבך", "And He wearied you"),
        ("וַיַּרְעִבֶךָ", "ואגאעך", "and made you hungry"),
        ("וַיַּאֲכִלְךָ", "ואטעמך", "and fed you"),
        ("אֶת-הַמָּן", "אלמן", "the manna"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("לֹא-יָדַעְתָּ", "לם תערפה", "you had not known"),
        ("וְלֹא יָדְעוּן", "ולם יערפה", "and your fathers had not known"),
        ("אֲבֹתֶיךָ", "אבאיך", "your fathers"),
        ("לְמַעַן הוֹדִיעֲךָ", "לכי יערפך", "that He might make known to you"),
        ("כִּי", "אנה", "that"),
        ("לֹא", "ליס", "it is not"),
        ("עַל-הַלֶּחֶם", "עלי' אלכ'בז", "on bread"),
        ("לְבַדּוֹ", "וחדה", "alone"),
        ("יִחְיֶה", "יחיא", "lives"),
        ("הָאָדָם", "אלאנסאן", "a person"),
        ("כִּי", "בל", "but"),
        ("עַל-כָּל-מוֹצָא", "עלי' גמיע מא אכ'רגה", "on all that issues from"),
        ("פִי-יְהוָה", "קול אללה", "the word of God"),
        ("יִחְיֶה", "יעיש", "shall a person live"),
    ],
    4: [
        ("שִׂמְלָתְךָ", "ות'יאבך", "Your garments"),
        ("לֹא בָלְתָה", "לם תבל", "did not wear out"),
        ("וְרַגְלְךָ", "ורגלך", "and your foot"),
        ("לֹא בָצֵקָה", "לם תחף", "did not go bare"),
        ("זֶה", "פי הד'ה", "in these"),
        ("אַרְבָּעִים שָׁנָה", "אלארבעין אלסנה", "forty years"),
    ],
    5: [
        (None, "ואעלם", "And know"),
        (None, "פי נפסך", "within yourself"),
        ("כִּי", "אנה", "that"),
        ("כַּאֲשֶׁר", "כמא", "just as"),
        ("יְיַסֵּר", "יאדב", "disciplines"),
        ("אִישׁ", "אלמר", "a man"),
        ("אֶת-בְּנוֹ", "ולדה", "his child"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מְיַסְּרֶךָּ", "מודבך", "is disciplining you"),
    ],
    6: [
        (None, "ואחפץ'", "And keep"),
        ("אֶת-מִצְו‍ֹת יְהוָה אֱלֹהֶיךָ", "וצאיאה", "His commandments"),
        ("לָלֶכֶת", "וסיר", "and walk"),
        ("בִּדְרָכָיו", "פי טרקה", "in His ways"),
        ("וּלְיִרְאָה אֹתוֹ", "וכ'פה", "and fear Him"),
    ],
    7: [
        ("כִּי", "לאן", "For"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מְבִיאֲךָ", "מדכ'לך", "is bringing you"),
        ("אֶל-אֶרֶץ", "אלי' בלד", "into a land"),
        ("טוֹבָה", "גייד", "good"),
        ("אֶרֶץ", "בלד", "a land of"),
        ("נַחֲלֵי", "אודייה'", "water-courses"),
        ("מָיִם", "מא", "water"),
        ("עֲיָנֹת", "ועיון", "springs"),
        ("וּתְהֹמֹת", "וג'מר", "and deeps"),
        ("יֹצְאִים", "תפגר", "that burst forth"),
        ("בַּבִּקְעָה", "פי בקאעה", "in its valleys"),
        ("וּבָהָר", "וגבאלה", "and its mountains"),
    ],
    8: [
        ("אֶרֶץ", "ארץ'", "a land of"),
        ("חִטָּה", "חנטה", "wheat"),
        ("וּשְׂעֹרָה", "ושעיר", "and barley"),
        ("וְגֶפֶן", "וגפן", "and vine"),
        ("וּתְאֵנָה", "ותין", "and fig"),
        ("וְרִמּוֹן", "ורמאן", "and pomegranate"),
        ("אֶרֶץ-זֵית", "בלד זיתון", "a land of olive"),
        ("שֶׁמֶן", "זית", "oil"),
        ("וּדְבָשׁ", "ועסל", "and honey"),
    ],
    9: [
        ("אֶרֶץ", "בלד", "a land"),
        ("אֲשֶׁר", "לא", "in which"),
        ("לֹא", "תאכל", "you shall not eat"),
        ("בְמִסְכֵּנֻת", "פיה טעאמך בתקתיר", "your food in short measure"),
        ("תֹּאכַל-בָּהּ לֶחֶם", "ולא יעוזך", "and nothing shall be lacking"),
        ("לֹא-תֶחְסַר כֹּל", "פיה שייא", "to you therein"),
        ("אֶרֶץ", "בלד", "a land of"),
        ("אֲשֶׁר אֲבָנֶיהָ", "מן חגארתה", "of which its stones are"),
        ("בַרְזֶל", "אלחדיד", "iron"),
        ("וּמֵהֲרָרֶיהָ", "ומן גבאלה", "and from its mountains"),
        ("תַּחְצֹב נְחֹשֶׁת", "אלנחאס", "copper"),
    ],
    10: [
        ("וְאָכַלְתָּ", "פאד'א אכלת", "And when you have eaten"),
        ("וְשָׂבָעְתָּ", "ושבעת", "and are satisfied"),
        (None, "פבארך", "bless"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("עַל-הָאָרֶץ", "עלי' אלבלד", "for the land"),
        ("הַטֹּבָה", "אלגייד", "good"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("נָתַן-לָךְ", "אעטאך", "He has given you"),
    ],
    11: [
        (None, "פאחד'ר", "Beware"),
        ("פֶּן-תִּשְׁכַּח", "אן תנסא", "lest you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְבִלְתִּי שְׁמֹר", "ללא תחפץ'", "by not keeping"),
        ("מִצְו‍ֹתָיו", "וצאיאה", "His commandments"),
        ("וּמִשְׁפָּטָיו", "ואחכאמה", "and His ordinances"),
        ("וְחֻקֹּתָיו", "ורסומה", "and His statutes"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("אָנֹכִי", "אנא", "I"),
        ("מְצַוְּךָ", "אמרך بهא", "charge you with"),
        ("הַיּוֹם", "אליום", "today"),
    ],
    12: [
        ("פֶּן-תֹּאכַל", "כלא תאכל", "Lest you eat"),
        ("וְשָׂבָעְתָּ", "ותשבע", "and be satisfied"),
        ("וּבָתִּים", "וביות", "and build houses"),
        ("טֹבִים", "חסאנא", "fine"),
        ("תִּבְנֶה", "תבניהא", "build"),
        ("וְיָשָׁבְתָּ", "ותסכנהא", "and dwell in them"),
    ],
    13: [
        ("וּבְקָרְךָ", "ובקרך", "and your cattle"),
        ("וְצֹאנְךָ", "וג'נמך", "and your flocks"),
        ("יִרְבְּיֻן", "יכת'ר", "multiply"),
        ("וְכֶסֶף", "ופצ'ה", "and silver"),
        ("וְזָהָב", "וד'הב", "and gold"),
        ("יִרְבֶּה-לָּךְ", "יכת'ר לך", "multiply for you"),
        ("וְכֹל אֲשֶׁר-לְךָ", "וגמיע מאלך", "and all that you have"),
        ("יִרְבֶּה", "יכת'ר", "multiplies"),
    ],
    14: [
        ("וְרָם", "פירפעך", "becomes lifted up"),
        ("לְבָבֶךָ", "קלבך", "and your heart"),
        ("וְשָׁכַחְתָּ", "ותנסא", "and you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("הַמּוֹצִיאֲךָ", "אלד'י אכ'רגך", "who brought you out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן בלד מצר", "from the land of Egypt"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה", "from the house of bondage"),
    ],
    15: [
        ("הַמּוֹלִיכְךָ", "אלמסלכך", "who led you through"),
        ("בַּמִּדְבָּר", "פי אלבר", "the wilderness"),
        ("הַגָּדֹל", "אלכביר", "great"),
        ("וְהַנּוֹרָא", "אלמכ'יף", "and fearful"),
        ("נָחָשׁ שָׂרָף", "חית' אלחיאת אלמחרקה", "where there are burning serpents"),
        ("וְעַקְרָב", "ואלעקארב", "and scorpions"),
        ("וְצִמָּאוֹן", "ועטש", "and thirst"),
        ("אֲשֶׁר אֵין-מָיִם", "חית' ליס מא", "where there is no water"),
        ("הַמּוֹצִיא", "אלמכ'רג", "who brought out"),
        ("לְךָ", "לך", "for you"),
        ("מַיִם", "אלמא", "water"),
        ("מִצּוּר הַחַלָּמִישׁ", "מן אלצואן אלצלד", "from the hard flint-rock"),
    ],
    16: [
        ("הַמַּאֲכִלְךָ", "אלמטעמך", "who fed you"),
        ("מָן", "אלמן", "manna"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
        ("אֲשֶׁר לֹא-יָדְעוּן", "מא לם יערפה", "which had not known"),
        ("אֲבֹתֶיךָ", "אבאיך", "your fathers"),
        ("לְמַעַן עַנֹּתְךָ", "ליעד'בך", "to afflict you"),
        ("וּלְמַעַן נַסֹּתֶךָ", "וימתחנך", "and test you"),
        ("לְהֵיטִבְךָ", "ויעווצך כ'ירא", "and reward you with good"),
        ("בְּאַחֲרִיתֶךָ", "פי אכ'רתך", "in your latter end"),
    ],
    17: [
        (None, "פלא תקול", "And you shall not say"),
        (None, "פי נפסך", "within yourself"),
        ("כֹּחִי", "אן קוותי", "My strength"),
        ("וְעֹצֶם", "ועצם", "and the greatness of"),
        ("יָדִי", "קדרתי", "my power"),
        ("עָשָׂה", "אכתסבת", "have gained"),
        ("לִי", "לי", "me"),
        ("אֶת-הַחַיִל הַזֶּה", "הד'א אליסאר", "this prosperity"),
    ],
    18: [
        (None, "בל", "But"),
        (None, "אדכר", "remember"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("כִּי", "פאנה", "for it is He"),
        ("הוּא", "אלמעטיך", "who gives you"),
        ("הַנֹּתֵן לְךָ", "קווה", "the power"),
        ("כֹּחַ לַעֲשׂוֹת חָיִל", "תכתסב בהא אליסאר", "by which you gain prosperity"),
        ("לְמַעַן הָקִים", "לכי יאפי", "that He may fulfill"),
        ("אֶת-בְּרִיתוֹ", "בעהדה", "His covenant"),
        ("אֲשֶׁר-נִשְׁבַּע", "אלד'י קסם בה", "which He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
        ("כַּיּוֹם הַזֶּה", "כיומנא הד'א", "as on this day of ours"),
    ],
    19: [
        (None, "פאן", "And if"),
        ("וְהָיָה אִם-שָׁכֹחַ תִּשְׁכַּח", "נסית", "you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְהָלַכְתָּ", "ומצ'ית", "and go off"),
        ("וַעֲבַדְתָּם", "ועבדת", "and worship"),
        ("אֱלֹהִים אֲחֵרִים", "מעבודאת אכ'ר", "other objects of worship"),
        ("וְהִשְׁתַּחֲוִיתָ לָהֶם", "וסגדת להא", "and bow down to them"),
        ("הַעִדֹתִי בָכֶם", "פקד ערפתכם", "I make known to you"),
        ("הַיּוֹם", "מן אליום", "today"),
        ("כִּי אָבֹד תֹּאבֵדוּן", "אנכם סתבידון", "that you shall surely perish"),
    ],
    20: [
        ("כַּגּוֹיִם", "כאלאמם", "Like the nations"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("יְהוָה", "אללה", "God"),
        ("מַאֲבִיד", "מבידהם", "is destroying"),
        ("מִפְּנֵיכֶם", "מן בין ידיכם", "from before you"),
        ("כֵּן תֹּאבֵדוּן", "כד'אך תבידון", "so shall you perish"),
        ("עֵקֶב", "אד'", "since"),
        ("לֹא תִשְׁמְעוּן", "לם תקבלו", "you did not accept"),
        ("בְּקוֹל", "אמר", "the command of"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
    ],
}
