"""Hand-authored alignment triples for Devarim chapter 14.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the prohibition of mourning rites (vv. 1-2), the abhorrence
rule (v. 3), the permitted/forbidden land animals (vv. 4-8), water creatures
(vv. 9-10), birds (vv. 11-20), carcasses and the prohibition of meat-in-milk
(v. 21), the second tithe law (vv. 22-27), and the triennial tithe for the poor
(vv. 28-29) — aligned with particular care for each species name in the animal
and bird lists.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואד'", "And since"),
        ("בָּנִים", "אנתם אוליא", "you are the devotees"),
        ("לַיהוָה", "אללה", "of God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "כאלבנין", "like children"),
        ("לֹא תִתְגֹּדְדוּ", "פלא תתואגו", "do not gash yourselves"),
        ("וְלֹא-תָשִׂימוּ", "ולא תגעלו", "and do not make"),
        ("קָרְחָה", "נתפא", "a bare patch"),
        ("בֵּין עֵינֵיכֶם", "בין עיונכם", "between your eyes"),
        ("לָמֵת", "עלי' אמואתכם", "for your dead"),
    ],
    2: [
        ("כִּי עַם קָדוֹשׁ אַתָּה", "לאנך שעב מקדס", "For you are a people consecrated"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וּבְךָ בָּחַר", "ואכ'תארך", "and He has chosen you"),
        ("לִהְיוֹת", "אן תכון", "to be"),
        ("לוֹ", "לה", "His"),
        ("לְעַם סְגֻלָּה", "אמה כ'אצה", "own particular nation"),
        ("מִכֹּל הָעַמִּים", "מן גמיע אלאמם", "from all the nations"),
        ("אֲשֶׁר עַל-פְּנֵי הָאֲדָמָה", "אלד'י עלי' וגה אלארץ'", "that are upon the face of the earth"),
    ],
    3: [
        ("לֹא תֹאכַל", "לא תאכל", "You shall not eat"),
        ("כָּל-תּוֹעֵבָה", "כל מכרוה", "anything abhorrent"),
    ],
    4: [
        (None, "הד'א", "This is"),
        ("זֹאת הַבְּהֵמָה אֲשֶׁר תֹּאכֵלוּ", "מא תאכלוה", "what you may eat"),
        (None, "מן אלבאהים", "of the beasts"),
        ("שׁוֹר", "אלבקר", "the cattle"),
        ("שֵׂה כְשָׂבִים", "ואלצ'אן", "the sheep"),
        ("וְשֵׂה עִזִּים", "ואלמאעז", "and the goats"),
    ],
    5: [
        ("אַיָּל", "ואלאיל", "and the deer"),
        (None, "וי", "and"),
        ("וּצְבִי", "אלצ'בי", "the gazelle"),
        ("וְיַחְמוּר", "ואליחמור", "and the roebuck"),
        ("וְאַקּוֹ", "ואלועל", "and the ibex"),
        ("וְדִישֹׁן", "ואלארוי", "and the mountain goat"),
        ("וּתְאוֹ", "ואלתיתל", "and the tebel"),
        ("וָזָמֶר", "ואלזראפה", "and the giraffe"),
    ],
    6: [
        ("וְכָל-בְּהֵמָה", "וכל בהימה", "And every beast"),
        ("מַפְרֶסֶת פַּרְסָה", "מצ'לפה בצ'לף", "that is hoofed with a hoof"),
        ("וְשֹׁסַעַת שֶׁסַע שְׁתֵּי פְרָסוֹת", "ומפרקה אצ'לאפהא תפריקא", "and has its hooves split in a full split"),
        ("מַעֲלַת גֵּרָה", "ומצעדה אגתראר", "and that brings up cud"),
        ("בַּבְּהֵמָה", "מן אלבאהים", "from among the beasts"),
        ("אֹתָהּ תֹּאכֵלוּ", "פכלוהא", "eat it"),
    ],
    7: [
        (None, "כלא", "But"),
        ("אַךְ אֶת-זֶה", "הד'ה אלאשכ'אץ", "these creatures"),
        ("לֹא תֹאכְלוּ", "פלא תאכלוהא", "do not eat them"),
        ("מִמַּעֲלֵי הַגֵּרָה", "מן אלמצעדי אלאגתראר", "from among those that bring up cud"),
        ("וּמִמַּפְרִיסֵי הַפַּרְסָה הַשְּׁסוּעָה", "ואלמצ'לפין באצ'לאף מפרקה", "and those that are hoofed with split hooves"),
        ("אֶת-הַגָּמָל", "אלגמל", "the camel"),
        ("וְאֶת-הָאַרְנֶבֶת", "ואלארנב", "and the hare"),
        ("וְאֶת-הַשָּׁפָן", "ואלובר", "and the hyrax"),
        ("כִּי-מַעֲלֵה גֵרָה הֵמָּה", "פאנהמא מצעדה אגתראר", "for they bring up cud"),
        ("וּפַרְסָה לֹא הִפְרִיסוּ", "ג'יר מצ'לפה בצח*'ל'ף", "but are not hoofed with a hoof"),
        ("טְמֵאִים הֵם לָכֶם", "פהי מחרמה עליכם", "they are forbidden to you"),
    ],
    8: [
        ("וְאֶת-הַחֲזִיר", "ואלכ'נזיר", "And the pig"),
        ("כִּי-מַפְרִיס פַּרְסָה הוּא", "פאנה מצ'לף בצ'לף", "it is hoofed with a hoof"),
        ("וְלֹא גֵרָה", "ולא יגתר", "but does not chew cud"),
        ("טָמֵא הוּא לָכֶם", "פהו מחרם עליכם", "it is forbidden to you"),
        ("מִבְּשָׂרָם לֹא תֹאכֵלוּ", "לא תאכלו מן לחומהא", "do not eat of their flesh"),
        ("וּבְנִבְלָתָם לֹא תִגָּעוּ", "ולא תדנו מן נבאילהא ללא תנגסכם", "and do not approach their carcasses lest they make you impure"),
    ],
    9: [
        (None, "והד'א", "And this is"),
        ("אֶת-זֶה תֹּאכְלוּ", "מא תאכלוה", "what you may eat"),
        ("מִכֹּל אֲשֶׁר בַּמָּיִם", "מן גמיע מא פי אלמא", "from all that is in the water"),
        ("כֹּל אֲשֶׁר-לוֹ סְנַפִּיר", "כל מא לה אגנחה", "everything that has fins"),
        ("וְקַשְׂקֶשֶׂת", "ופלוס", "and scales"),
        ("תֹּאכֵלוּ", "פכלוה", "eat it"),
    ],
    10: [
        ("וְכֹל אֲשֶׁר אֵין-לוֹ", "וכל מא ליס לה", "And everything that has no"),
        ("סְנַפִּיר", "אגנחה", "fins"),
        ("וְקַשְׂקֶשֶׂת", "ופלוס", "and scales"),
        ("לֹא תֹאכֵלוּ", "לא תאכלוה", "do not eat it"),
        ("טָמֵא הוּא לָכֶם", "לאנה נגס לכם", "for it is impure for you"),
    ],
    11: [
        ("כָּל-צִפּוֹר טְהֹרָה", "וכל טאיר טאהר", "And every pure bird"),
        ("תֹּאכֵלוּ", "פכלוה", "eat it"),
    ],
    12: [
        (None, "והד'ה אלאשכ'אץ", "And these are the creatures"),
        ("וְזֶה אֲשֶׁר לֹא-תֹאכְלוּ מֵהֶם", "לא תאכלוהא מנהם", "you shall not eat from among them"),
        ("הַנֶּשֶׁר", "אלנסר", "the vulture"),
        ("וְהַפֶּרֶס", "ואלעקאב", "the eagle"),
        ("וְהָעָזְנִיָּה", "ואלענקא", "and the great bird of prey"),
    ],
    13: [
        ("וְהָרָאָה", "ואלגארח", "and the kite"),
        ("וְאֶת-הָאַיָּה", "ואלצדא", "and the screech-bird"),
        ("וְהַדַּיָּה", "ואלחדא", "and the falcon"),
        ("לְמִינָהּ", "לאצנאפהא", "according to its kinds"),
    ],
    14: [
        ("וְאֵת כָּל-עֹרֵב", "וגמיע אלג'ראביב", "and all the ravens"),
        ("לְמִינוֹ", "לאצנאפהא", "according to their kinds"),
    ],
    15: [
        ("וְאֵת בַּת הַיַּעֲנָה", "ואלנעאמה", "and the ostrich"),
        ("וְאֶת-הַתַּחְמָס", "ואלכ'טאף", "and the swallow"),
        ("וְאֶת-הַשָּׁחַף", "ואלסאף", "and the gull"),
        ("וְאֶת-הַנֵּץ", "ואלבאז", "and the hawk"),
        ("לְמִינֵהוּ", "לאצנאפה", "according to its kinds"),
    ],
    16: [
        ("אֶת-הַכּוֹס", "ואלבום", "and the owl"),
        ("וְאֶת-הַיַּנְשׁוּף", "ואלבאשק", "and the sparrowhawk"),
        ("וְהַתִּנְשָׁמֶת", "ואלשאהין", "and the falcon"),
    ],
    17: [
        ("וְהַקָּאָת", "ואלקוק", "and the pelican"),
        ("וְאֶת-הָרָחָמָה", "ואלרכ'ם", "and the carrion-vulture"),
        ("וְאֶת-הַשָּׁלָךְ", "ואלזמג", "and the cormorant"),
    ],
    18: [
        ("וְהַחֲסִידָה", "ואלצקר", "and the stork"),
        ("וְהָאֲנָפָה", "ואלבג'בג'ה", "and the parrot"),
        ("לְמִינָהּ", "באצנאפהא", "according to its kinds"),
        ("וְהַדּוּכִיפַת", "ואלהדהד", "and the hoopoe"),
        ("וְהָעֲטַלֵּף", "ואלכ'פאש", "and the bat"),
    ],
    19: [
        ("וְכֹל שֶׁרֶץ הָעוֹף", "וגמיע דביב אלטאיר", "And all creeping flying creatures"),
        ("טָמֵא הוּא לָכֶם", "אלד'י הו מחרם עליכם", "that are forbidden to you"),
        ("לֹא יֵאָכֵלוּ", "לא תאכלוה", "do not eat them"),
    ],
    20: [
        ("כָּל-עוֹף טָהוֹר", "וכל מא הו טאהר מנה", "And everything that is pure from among them"),
        ("תֹּאכֵלוּ", "פכלוה", "eat it"),
    ],
    21: [
        ("לֹא תֹאכְלוּ", "ולא תאכלו", "And do not eat"),
        ("כָל-נְבֵלָה", "שייא מן אלנבאיל", "anything from the carcasses"),
        (None, "בל", "rather"),
        ("לַגֵּר", "אעטהא לאלג'ריב", "give it to the stranger"),
        ("אֲשֶׁר-בִּשְׁעָרֶיךָ", "אלד'י פי מחאלך", "who is in your localities"),
        ("וַאֲכָלָהּ", "פיאכלהא", "that he may eat it"),
        ("אוֹ מָכֹר", "או תביעהא", "or sell it"),
        ("לְנָכְרִי", "לאגנבי", "to a foreigner"),
        ("כִּי עַם קָדוֹשׁ אַתָּה", "לאנך שעב מקדס", "for you are a people consecrated"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לֹא-תְבַשֵּׁל", "ולא תטבך'", "And do not cook"),
        ("גְּדִי", "לחמא", "meat"),
        ("בַּחֲלֵב אִמּוֹ", "בלבן", "in milk"),
    ],
    22: [
        ("עַשֵּׂר תְּעַשֵּׂר", "ועשר תעשירא", "You shall tithe a full tithe"),
        ("אֵת כָּל-תְּבוּאַת זַרְעֶךָ", "גמיע גלה' זרעך", "of all the yield of your sowing"),
        ("הַיֹּצֵא הַשָּׂדֶה", "מא תנבתה אלצחרא", "that which the open country brings forth"),
        ("שָׁנָה שָׁנָה", "סנה סנה", "year by year"),
    ],
    23: [
        ("וְאָכַלְתָּ", "וכל", "And eat"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בַּמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר-יִבְחַר", "אלד'י יכ'תארה", "which He shall choose"),
        ("לְשַׁכֵּן שְׁמוֹ שָׁם", "ליחל נורה פיה", "for His light to dwell therein"),
        ("מַעְשַׂר דְּגָנְךָ", "עשור ברך", "the tithes of your grain"),
        ("תִּירֹשְׁךָ", "ועצירך", "and your press-produce"),
        ("וְיִצְהָרֶךָ", "ודהנך", "and your oil"),
        ("וּבְכֹרֹת בְּקָרְךָ", "ובכור בקרך", "and the firstlings of your cattle"),
        ("וְצֹאנֶךָ", "וג'נמך", "and your flock"),
        ("לְמַעַן תִּלְמַד", "לכי תתעלם", "so that you may learn"),
        ("לְיִרְאָה אֶת-יְהוָה", "כיף תעבדה", "how to serve Him"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "all the length of time"),
    ],
    24: [
        ("וְכִי-יִרְבֶּה מִמְּךָ הַדֶּרֶךְ", "ואן טאל עליך אלטריק", "And if the way be too long for you"),
        ("כִּי לֹא תוּכַל שְׂאֵתוֹ", "ולם תטיק אן תחמלה", "and you are unable to carry it"),
        ("כִּי-יִרְחַק מִמְּךָ הַמָּקוֹם", "ובעד ענך אלמוצ'ע", "and the place is far from you"),
        ("אֲשֶׁר יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "the place which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("לָשׂוּם שְׁמוֹ שָׁם", "אן יחל נורה פיה", "for His light to dwell therein"),
        ("כִּי יְבָרֶכְךָ יְהוָה אֱלֹהֶיךָ", "ובארך לך מע ד'אלך", "and He has blessed you through all of this"),
    ],
    25: [
        ("וְנָתַתָּה בַּכָּסֶף", "פבעה בת'מן", "then sell it for a price"),
        ("וְצַרְתָּ הַכֶּסֶף", "וצרה", "and tie it up"),
        ("בְּיָדְךָ", "וכ'ד'ה פי ידך", "and take it in your hand"),
        ("וְהָלַכְתָּ", "ואמץ' אלי'", "and go to"),
        ("אֶל-הַמָּקוֹם", "אלמוצ'ע", "the place"),
        ("אֲשֶׁר יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
    ],
    26: [
        ("וְנָתַתָּה הַכֶּסֶף", "ואצרפה", "And spend it"),
        ("בְּכֹל אֲשֶׁר-תְּאַוֶּה נַפְשְׁךָ", "פי גמיע מא תשתהי נפסך", "on whatever your soul desires"),
        ("בַּבָּקָר", "מן בקר", "cattle"),
        ("וּבַצֹּאן", "וג'נם", "and flock"),
        ("וּבַיַּיִן", "וכ'מר", "and wine"),
        ("וּבַשֵּׁכָר", "ונביד'", "and strong drink"),
        ("וּבְכֹל אֲשֶׁר תִּשְׁאָלְךָ נַפְשֶׁךָ", "וגמיע מא תחבה נפסך", "and whatever your soul wishes"),
        ("וְאָכַלְתָּ שָּׁם", "וכלה הנאך", "and eat it there"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְשָׂמַחְתָּ", "ואפרח", "and rejoice"),
        ("אַתָּה", "אנת", "you"),
        ("וּבֵיתֶךָ", "ואלך", "and your household"),
    ],
    27: [
        ("וְהַלֵּוִי", "ואללוי", "And the Levite"),
        ("אֲשֶׁר-בִּשְׁעָרֶיךָ", "אלד'י פי מחלך", "who is in your localities"),
        ("לֹא תַעַזְבֶנּוּ", "לא תתרכה", "do not forsake him"),
        ("כִּי אֵין לוֹ", "אד' ליס לה", "since he has no"),
        ("חֵלֶק", "נציב", "portion"),
        ("וְנַחֲלָה", "ולא נחלה", "nor inheritance"),
        ("עִמָּךְ", "מעך", "with you"),
    ],
    28: [
        ("מִקְצֵה שָׁלֹשׁ שָׁנִים", "ופי כל ת'לאת' סנין", "And at the end of every three years"),
        ("תּוֹצִיא", "תכ'רג", "bring out"),
        ("אֶת-כָּל-מַעְשַׂר תְּבוּאָתְךָ", "גמיע עשור ג'לתך", "all the tithes of your yield"),
        ("בַּשָּׁנָה הַהִוא", "פי תלך אלסנה", "in that year"),
        ("וְהִנַּחְתָּ בִּשְׁעָרֶיךָ", "וצ'עה פי מחלך", "and set it down in your localities"),
    ],
    29: [
        ("וּבָא הַלֵּוִי", "פיאתי אללוי", "And the Levite shall come"),
        ("כִּי אֵין-לוֹ חֵלֶק", "אד' ליס לה נציב", "since he has no portion"),
        ("וְנַחֲלָה", "ולא נחלה", "nor inheritance"),
        ("עִמָּךְ", "מעך", "with you"),
        ("וְהַגֵּר", "ואלג'ריב", "and the stranger"),
        ("וְהַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְהָאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("אֲשֶׁר בִּשְׁעָרֶיךָ", "אלד'י' פי מחלך", "who are in your localities"),
        ("וְאָכְלוּ", "פיאכלון", "and they shall eat"),
        ("וְשָׂבֵעוּ", "וישבעון", "and be satisfied"),
        ("לְמַעַן יְבָרֶכְךָ", "לכי יבארך לך", "so that"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord may bless you"),
        ("בְּכָל-מַעֲשֵׂה יָדְךָ אֲשֶׁר תַּעֲשֶׂה", "פי גמיע מא תצנעה", "in all that you do"),
    ],
}
