"""Hand-authored alignment triples for Devarim chapter 31.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the transfer of leadership to Joshua, the command for
septennial Torah reading (hakhel), God's prediction of apostasy, the command to
write the song, and the placing of the Torah beside the ark.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֵּלֶךְ מֹשֶׁה", "פמצ'א מוסי", "And Moses went on"),
        ("וַיְדַבֵּר", "וכלם", "and spoke"),
        ("אֶל-כָּל-יִשְׂרָאֵל", "בני אסראיל", "to the sons of Israel"),
        ("אֶת-הַדְּבָרִים הָאֵלֶּה", "בגמיע הד'א אלכלאם", "all of this discourse"),
    ],
    2: [
        ("וַיֹּאמֶר אֲלֵהֶם", "פקאל להם", "And he said to them"),
        ("בֶּן-מֵאָה וְעֶשְׂרִים שָׁנָה", "אבן מאיה ועשרין סנה", "a son of a hundred and twenty years"),
        ("אָנֹכִי הַיּוֹם", "אנא אליום", "I am today"),
        ("לֹא-אוּכַל", "לא אטיק", "I am no longer able"),
        ("עוֹד", "זיאדה עלי'", "to go"),
        ("לָצֵאת", "אלכ'רוג", "out"),
        ("וְלָבוֹא", "ואלדכ'ול", "and come in"),
        ("וַיהוָה", "ואללה", "and God"),
        ("אָמַר אֵלַי", "פקד קאל לי", "has already said to me"),
        ("לֹא תַעֲבֹר", "לא תעבר", "You shall not cross"),
        ("אֶת-הַיַּרְדֵּן הַזֶּה", "הד'א אלארדן", "this Jordan"),
    ],
    3: [
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord"),
        (None, "אלד'י נורה", "whose light"),
        ("הוּא עֹבֵר לְפָנֶיךָ", "יסיר בין ידיך", "goes before you"),
        ("הוּא-יַשְׁמִיד", "הו ינפד'", "He shall destroy"),
        ("אֶת-הַגּוֹיִם הָאֵלֶּה", "הולאי אלאמם", "these nations"),
        ("מִלְּפָנֶיךָ", "מן בין ידיך", "from before you"),
        ("וִירִשְׁתָּם", "ותרת'הם", "and you shall inherit them"),
        ("יְהוֹשֻׁעַ", "יהושע", "Joshua"),
        ("הוּא עֹבֵר לְפָנֶיךָ", "הו יעבר בין ידיך", "he shall cross before you"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה", "כמא קאל אללה", "as God has said"),
    ],
    4: [
        ("וְעָשָׂה יְהוָה לָהֶם", "פיצנע אללה בהם", "And God shall do to them"),
        ("כַּאֲשֶׁר עָשָׂה", "כמא צנע", "as He did"),
        ("לְסִיחוֹן", "בסיחון", "to Sihon"),
        ("וּלְעוֹג", "ועוג", "and Og"),
        ("מַלְכֵי הָאֱמֹרִי", "מלכי אלאמורי", "the two kings of the Amorites"),
        ("וּלְאַרְצָם", "ובאהל בלדהם", "and to the people of their land"),
        ("אֲשֶׁר הִשְׁמִיד אֹתָם", "אלד'י אנפד'הם", "whom He destroyed"),
    ],
    5: [
        ("וּנְתָנָם יְהוָה לִפְנֵיכֶם", "פיסלמהם אללה בין ידיכם", "And God shall deliver them into your hands"),
        ("וַעֲשִׂיתֶם לָהֶם", "ותצנעון בהם", "and you shall do to them"),
        ("כְּכָל-הַמִּצְוָה", "כגמיע אלוצייה", "according to all the commandments"),
        ("אֲשֶׁר צִוִּיתִי אֶתְכֶם", "אלד'י אוציתכם", "which I commanded you"),
    ],
    6: [
        ("חִזְקוּ", "אשתדו", "Be strong"),
        ("וְאִמְצוּ", "ותאיידו", "and firm"),
        ("אַל-תִּירְאוּ", "לא תכ'אפוהם", "do not fear them"),
        ("וְאַל-תַּעַרְצוּ מִפְּנֵיהֶם", "ולא תרהבוהם", "nor be in dread of them"),
        ("כִּי יְהוָה אֱלֹהֶיךָ", "פאן אללה רבך", "for God your Lord"),
        (None, "נורה", "whose light"),
        ("הוּא הַהֹלֵךְ עִמָּךְ", "אלסאיר מעך", "goes with you"),
        ("לֹא יַרְפְּךָ", "לא ידעך", "will not leave you"),
        ("וְלֹא יַעַזְבֶךָּ", "ולא יתרכך", "nor forsake you"),
    ],
    7: [
        (None, "ת'ם", "Then"),
        ("וַיִּקְרָא מֹשֶׁה", "דעא מוסי'", "Moses called"),
        ("לִיהוֹשֻׁעַ", "ביהושע", "Joshua"),
        ("וַיֹּאמֶר אֵלָיו", "וקאל לה", "and said to him"),
        ("לְעֵינֵי כָל-יִשְׂרָאֵל", "בחצ'רה' גמיע אל אסראיל", "in the presence of all the house of Israel"),
        ("חֲזַק", "אשתד", "Be strong"),
        ("וֶאֱמָץ", "ותאייד", "and firm"),
        ("כִּי אַתָּה תָּבוֹא", "פאנך תדכ'ל", "for you shall enter"),
        ("אֶת-הָעָם הַזֶּה", "מע הולאי אלקום", "with these people"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר נִשְׁבַּע יְהוָה", "אלד'י קסם אללה", "which God swore"),
        ("לַאֲבֹתָם", "לאבאיהם", "to their fathers"),
        ("לָתֵת לָהֶם", "אן יעטיהם", "to give them"),
        ("וְאַתָּה תַּנְחִילֶנָּה אוֹתָם", "ואנת תנחלה להם", "and you shall cause them to inherit it"),
    ],
    8: [
        ("וַיהוָה", "ואללה", "And God"),
        (None, "אלד'י נורה", "whose light"),
        ("הוּא הַהֹלֵךְ לְפָנֶיךָ", "סאיר בין ידיך", "goes before you"),
        ("הוּא יִהְיֶה עִמָּךְ", "הו יכון מעך", "He shall be with you"),
        ("לֹא יַרְפְּךָ", "לא ידעך", "He will not leave you"),
        ("וְלֹא יַעַזְבֶךָּ", "ולא יתרכך", "nor forsake you"),
        ("לֹא תִירָא", "לא תכ'אף", "Do not fear"),
        ("וְלֹא תֵחָת", "ולא תד'ער", "and do not be dismayed"),
    ],
    9: [
        (None, "ת'ם", "Then"),
        ("וַיִּכְתֹּב מֹשֶׁה", "כתב מוסי'", "Moses wrote"),
        ("אֶת-הַתּוֹרָה הַזֹּאת", "הד'ה אלתורייה", "this Torah"),
        ("וַיִּתְּנָהּ", "ודפעהא", "and delivered it"),
        ("אֶל-הַכֹּהֲנִים", "אלי' אלאימה", "to the imāms"),
        ("בְּנֵי לֵוִי", "בני לוי", "the sons of Levi"),
        ("הַנֹּשְׂאִים", "אלחאמלין", "who bear"),
        ("אֶת-אֲרוֹן בְּרִית יְהוָה", "צנדוק עהד אללה", "the ark of the covenant of God"),
        ("וְאֶל-כָּל-זִקְנֵי יִשְׂרָאֵל", "ולסאיר שיוך' אל אסראיל", "and to the rest of the elders of the house of Israel"),
    ],
    10: [
        ("וַיְצַו מֹשֶׁה אוֹתָם", "ואמרהם", "And he commanded them"),
        ("לֵאמֹר", "וקאל להם", "saying"),
        ("מִקֵּץ שֶׁבַע שָׁנִים", "פי כל מדה' סבע סנין", "At every period of seven years"),
        ("בְּמֹעֵד שְׁנַת הַשְּׁמִטָּה", "פי וקת סנה אלתסייב", "at the time of the year of release"),
        ("בְּחַג הַסֻּכּוֹת", "פי חג אלמצ'אל", "at the festival of Tabernacles"),
    ],
    11: [
        ("בְּבוֹא כָל-יִשְׂרָאֵל", "פי מגי גמיע אל אסראיל", "when all the house of Israel comes"),
        ("לֵרָאוֹת", "לאלחצור", "to present themselves"),
        ("אֶת-פְּנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבכם", "your Lord"),
        ("בַּמָּקוֹם אֲשֶׁר יִבְחָר", "פי אלמוצ'ע אלד'י יכ'תארה", "in the place which He shall choose"),
        ("תִּקְרָא", "תקרא עליהם", "you shall read"),
        ("אֶת-הַתּוֹרָה הַזֹּאת", "הד'ה אלתורייה", "this Torah"),
        ("נֶגֶד כָּל-יִשְׂרָאֵל", "בחד'אהם", "before them"),
        ("בְּאָזְנֵיהֶם", "חית' יסמעונהא", "within their hearing, so that they may hear it"),
    ],
    12: [
        ("הַקְהֵל אֶת-הָעָם", "וד'אך באן תגווק אלקום", "And that is by assembling the people"),
        ("הָאֲנָשִׁים", "אלרגאל", "the men"),
        ("וְהַנָּשִׁים", "ואלנסא", "the women"),
        ("וְהַטַּף", "ואלאטפאל", "the children"),
        ("וְגֵרְךָ", "ואלג'ריב", "and the stranger"),
        ("אֲשֶׁר בִּשְׁעָרֶיךָ", "אלד'י פי מחאלך", "who is in your settlements"),
        ("לְמַעַן יִשְׁמְעוּ", "לכי יסמעו", "so that they may hear"),
        ("וּלְמַעַן יִלְמְדוּ", "ויתעלמו", "and learn"),
        ("וְיָרְאוּ אֶת-יְהוָה אֱלֹהֵיכֶם", "ויכ'אפו אללה רבכם", "and fear God your Lord"),
        ("וְשָׁמְרוּ", "ויחפצו", "and keep"),
        ("לַעֲשׂוֹת", "ויעמלו", "and act upon"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "בגמיע כלאם הד'ה אלתוריה", "all the words of this Torah"),
    ],
    13: [
        ("וּבְנֵיהֶם", "חתי' בניהם", "And so too their children"),
        ("אֲשֶׁר לֹא-יָדְעוּ", "אלד'י לם יבלגו", "who have not yet come of age"),
        ("יִשְׁמְעוּ", "יסמעו", "they shall hear"),
        ("וְלָמְדוּ", "ויתעלמו", "and learn"),
        ("לְיִרְאָה אֶת-יְהוָה אֱלֹהֵיכֶם", "ויכ'אפו אללה רבכם", "and fear God your Lord"),
        ("כָּל-הַיָּמִים", "טול זמאנהם", "for all the length of their days"),
        ("אֲשֶׁר אַתֶּם חַיִּים", "אלד'י הם אחיא", "in which they live"),
        ("עַל-הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אַתֶּם עֹבְרִים אֶת-הַיַּרְדֵּן", "אלד'י אנתם גאיזין אלארדן", "which you are crossing the Jordan"),
        ("לְרִשְׁתָּהּ", "לתדכ'לון אליה לתחוזוה", "to enter and to possess"),
    ],
    14: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'", "And God said to Moses"),
        ("הֵן קָרְבוּ יָמֶיךָ לָמוּת", "הוד'א קד קרבת אייאמך לאלמות", "Behold, your days have drawn near to death"),
        ("קְרָא אֶת-יְהוֹשֻׁעַ", "אדע ביהושע", "Summon Joshua"),
        ("וְהִתְיַצְּבוּ בְּאֹהֶל מוֹעֵד", "וקפא פי כ'בא אלמחצ'ר", "and both of you stand in the tent of the assembly"),
        ("וַאֲצַוֶּנּוּ", "חתי אסתכ'לפה", "so that I may appoint him as successor"),
        ("וַיֵּלֶךְ מֹשֶׁה וִיהוֹשֻׁעַ", "פמצ'א מוסי' ויהושע", "And Moses and Joshua went"),
        ("וַיִּתְיַצְּבוּ בְּאֹהֶל מוֹעֵד", "ווקפא פי כ'בא אלמחצ'ר", "and stood in the tent of the assembly"),
    ],
    15: [
        ("וַיֵּרָא יְהוָה", "פתגלא אללה", "And God appeared"),
        ("בָּאֹהֶל", "פי אלכ'בא", "in the tent"),
        ("בְּעַמּוּד עָנָן", "בעמוד מן ג'מאם", "in a pillar of cloud"),
        ("וַיַּעֲמֹד עַמּוּד הֶעָנָן", "ווקף", "and it stood"),
        ("עַל-פֶּתַח הָאֹהֶל", "עלי' באבה", "at its entrance"),
    ],
    16: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה אולא למוסי'", "And God said first to Moses"),
        ("הִנְּךָ שֹׁכֵב עִם-אֲבֹתֶיךָ", "אנך סתנצ'גע מע אבאיך", "You shall presently lie down with your fathers"),
        ("וְקָם הָעָם הַזֶּה", "וסיקום הד'א אלשעב", "and this people shall arise"),
        ("וְזָנָה אַחֲרֵי", "ויטגי פי תבע", "and go astray, following"),
        ("אֱלֹהֵי נֵכַר-הָאָרֶץ", "מעבודאת אהל אלבלד", "the objects of worship of the people of the land"),
        ("אֲשֶׁר הוּא בָא-שָׁמָּה", "אלד'י הו צאיר אלי' ת'ם", "to which it is going"),
        ("בְּקִרְבּוֹ", "פי מא בינהם", "in their midst"),
        ("וַעֲזָבַנִי", "ויתרכני", "and it shall forsake Me"),
        ("וְהֵפֵר אֶת-בְּרִיתִי", "ויפסך' עהדי", "and break My covenant"),
        ("אֲשֶׁר כָּרַתִּי אִתּוֹ", "אלד'י עהדתה מעה", "which I made with it"),
    ],
    17: [
        ("וְחָרָה אַפִּי בוֹ", "וישתד ג'צ'בי עליהם", "And My anger shall intensify against them"),
        (None, "פי ד'אלך אלזמאן", "at that time"),
        ("וַעֲזַבְתִּים", "פאתרכהם", "and I shall leave them"),
        ("וְהִסְתַּרְתִּי פָנַי מֵהֶם", "ואחגב רחמתי ענהם", "and I shall withhold My mercy from them"),
        ("וְהָיָה לֶאֱכֹל", "פיצירון מאכלא", "so that they shall become prey"),
        ("וּמְצָאֻהוּ", "ותציבהם", "shall befall them"),
        ("רָעוֹת רַבּוֹת", "שרור כת'ירה", "many evils"),
        ("וְצָרוֹת", "ושדאיד", "and hardships"),
        ("וְאָמַר בַּיּוֹם הַהוּא", "פיקולון פי ד'אלך אלזמאן", "And they shall say at that time"),
        ("הֲלֹא עַל כִּי-אֵין", "אלא אן ממא ליס", "Is it not because"),
        ("אֱלֹהַי בְּקִרְבִּי", "ענאיה' רבי מעי", "the providence of my Lord is not with me"),
        ("מְצָאוּנִי הָרָעוֹת הָאֵלֶּה", "אצאבתני הד'ה אלבלאיא", "that these afflictions have befallen me"),
    ],
    18: [
        (None, "ומע ד'אלך", "And yet"),
        ("וְאָנֹכִי הַסְתֵּר אַסְתִּיר פָּנַי", "אנא מקים עלי' חגב רחמתי ענהם", "I persist in withholding My mercy from them"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אלזמאן", "at that time"),
        ("עַל כָּל-הָרָעָה אֲשֶׁר עָשָׂה", "בסבב אלשר אלד'י צנעוה", "on account of the evil which they have done"),
        ("כִּי פָנָה", "אד' ולא", "since they have turned"),
        ("אֶל-אֱלֹהִים אֲחֵרִים", "אלי' מעבודאת אכ'ר", "to other objects of worship"),
    ],
    19: [
        ("וְעַתָּה", "ואלאן", "And now"),
        ("כִּתְבוּ לָכֶם", "פאכתבו לכם", "write down for yourselves"),
        ("אֶת-הַשִּׁירָה הַזֹּאת", "הד'ה אלתסבחה", "this song of praise"),
        ("וְלַמְּדָהּ", "ולקנהא", "and teach it"),
        ("אֶת-בְּנֵי-יִשְׂרָאֵל", "בני אסראיל", "to the sons of Israel"),
        ("שִׂימָהּ בְּפִיהֶם", "חתי תסתמלהא מן אפואהם", "until you receive it in full from their mouths"),
        ("לְמַעַן תִּהְיֶה-לִּי הַשִּׁירָה הַזֹּאת לְעֵד", "לכי תכון לי שאהדא עליהם", "so that it may be a witness for Me against them"),
    ],
    20: [
        ("כִּי-אֲבִיאֶנּוּ", "אד' אדכ'להם", "For when I bring them"),
        ("אֶל-הָאֲדָמָה", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-נִשְׁבַּעְתִּי לַאֲבֹתָיו", "אלד'י אקסמת לאבאיהם", "which I swore to their fathers"),
        ("זָבַת חָלָב", "והו בלד יפיץ' לבנא", "a land flowing with milk"),
        ("וּדְבַשׁ", "ועסלא", "and honey"),
        ("וְאָכַל", "פיאכל קומהם", "their people shall eat"),
        ("וְשָׂבַע", "וישבע", "and be satisfied"),
        ("וְדָשֵׁן", "וידסם", "and grow fat"),
        (None, "ת'ם", "then"),
        ("וּפָנָה אֶל-אֱלֹהִים אֲחֵרִים", "יולי' אלי' מעבודאת אכ'ר", "they shall turn to other objects of worship"),
        ("וַעֲבָדוּם", "פיעבדהא", "and serve them"),
        ("וְנִאֲצוּנִי", "וירפצ'ני", "and they shall reject Me"),
        ("וְהֵפֵר אֶת-בְּרִיתִי", "ויפסך עהדי", "and break My covenant"),
    ],
    21: [
        ("וְהָיָה כִּי-תִמְצֶאןָ אֹתוֹ", "פאדא אצאבתהם", "And when"),
        ("רָעוֹת רַבּוֹת", "בלאיא כת'ירה", "many afflictions"),
        ("וְצָרוֹת", "ושדאיד", "and hardships befall them"),
        ("וְעָנְתָה הַשִּׁירָה הַזֹּאת לְפָנָיו לְעֵד", "חצ'רת הד'ה אלתסבחה בין ידיי כשאהד עליהם", "this song of praise shall be present before Me as a witness against them"),
        ("כִּי לֹא תִשָּׁכַח", "אד' יגב אן לא תנסא", "for it must not be forgotten"),
        ("מִפִּי זַרְעוֹ", "מן אפואת נסלהם", "from the mouths of their offspring"),
        ("כִּי יָדַעְתִּי אֶת-יִצְרוֹ", "לאני עאלם בכ'אטרהם", "since I know their thoughts"),
        ("אֲשֶׁר הוּא עֹשֶׂה הַיּוֹם", "ובמא סיצנעוה מן אליום", "and what they are about to do, from this very day"),
        ("בְּטֶרֶם אֲבִיאֶנּוּ", "מן קבל אן אדכ'להם", "before I bring them"),
        ("אֶל-הָאָרֶץ אֲשֶׁר נִשְׁבַּעְתִּי", "אלי' אלבלד אלד'י קסמת", "into the land which I have sworn"),
    ],
    22: [
        ("וַיִּכְתֹּב מֹשֶׁה", "פכתב מוסי'", "So Moses wrote"),
        ("אֶת-הַשִּׁירָה הַזֹּאת", "הד'ה אלתסבחה", "this song of praise"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אליום", "on that day"),
        ("וַיְלַמְּדָהּ אֶת-בְּנֵי יִשְׂרָאֵל", "ועלמהא לבני אסראיל", "and taught it to the sons of Israel"),
    ],
    23: [
        (None, "ת'ם", "Then"),
        ("וַיְצַו אֶת-יְהוֹשֻׁעַ", "אסתכ'לף יהושע", "He appointed Joshua"),
        ("בִּן-נוּן", "אבן נון", "son of Nun"),
        (None, "וקאל לה", "as successor, and said to him"),
        ("חֲזַק", "אשתד", "Be strong"),
        ("וֶאֱמָץ", "ותאייד", "and firm"),
        ("כִּי אַתָּה תָּבִיא", "לאנך תד'כל", "for you shall bring"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-נִשְׁבַּעְתִּי לָהֶם", "אלד'י קסמת להם", "which I have sworn to them"),
        ("וְאָנֹכִי אֶהְיֶה עִמָּךְ", "ואנא אכון מעך", "and I shall be with you"),
    ],
    24: [
        (None, "ת'ם", "Then"),
        ("וַיְהִי כְּכַלּוֹת מֹשֶׁה", "למא פרג' מוסי'", "when Moses had finished"),
        ("לִכְתֹּב", "מן כתב", "writing"),
        ("אֶת-דִּבְרֵי הַתּוֹרָה-הַזֹּאת", "גמיע כלאם הד'ה אלתורייה", "all the words of this Torah"),
        ("עַל-סֵפֶר", "פי ספר", "in a scroll"),
        ("עַד תֻּמָּם", "אלי' אן כמלת", "until they were complete"),
    ],
    25: [
        ("וַיְצַו מֹשֶׁה", "פאמר מוסי'", "Moses commanded"),
        ("אֶת-הַלְוִיִּם", "אלליואניין", "the Levites"),
        ("נֹשְׂאֵי אֲרוֹן בְּרִית-יְהוָה", "חאמלי צנדוק עהד אללה", "the bearers of the ark of the covenant of God"),
        ("לֵאמֹר", "וקאל להם", "and said to them"),
    ],
    26: [
        ("לָקֹחַ", "כ'דו", "Take"),
        ("אֵת סֵפֶר הַתּוֹרָה הַזֶּה", "הד'א ספר אלתורייה", "this scroll of the Torah"),
        ("וְשַׂמְתֶּם אֹתוֹ", "וציירוה", "and place it"),
        ("מִצַּד אֲרוֹן בְּרִית-יְהוָה אֱלֹהֵיכֶם", "אלי' גאנב צנדוק עהד אללה רבכם", "beside the ark of the covenant of God your Lord"),
        ("וְהָיָה-שָׁם", "יכון ת'ם", "it shall be there"),
        ("בְּךָ לְעֵד", "עליך שאהדא", "as a witness against you"),
    ],
    27: [
        ("כִּי אָנֹכִי יָדַעְתִּי", "לאני עאלם", "For I know"),
        ("אֶת-מֶרְיְךָ", "בכ'לאפך", "your contrariness"),
        ("וְאֶת-עָרְפְּךָ הַקָּשֶׁה", "וצעובה' רקבתך", "and the stubbornness of your neck"),
        ("הֵן בְּעוֹדֶנִּי חַי", "הוד'א ואנא פי אלחיאה", "Behold — while I am yet alive"),
        ("עִמָּכֶם הַיּוֹם", "מעכם אליום", "with you this day"),
        ("מַמְרִים הֱיִתֶם", "לם תזאלו מכ'אלפין", "you have not ceased to be disobedient"),
        ("עִם-יְהוָה", "ללה", "to God"),
        ("וְאַף כִּי-אַחֲרֵי מוֹתִי", "פכיף בעד מותי", "how much more so after my death"),
    ],
    28: [
        ("הַקְהִילוּ אֵלַי", "גווקו אליי", "Assemble to me"),
        ("אֶת-כָּל-זִקְנֵי שִׁבְטֵיכֶם", "גמיע שיוך' אסבאטכם", "all the elders of your tribes"),
        ("וְשֹׁטְרֵיכֶם", "וערפאכם", "and your overseers"),
        ("וַאֲדַבְּרָה בְאָזְנֵיהֶם", "חתי' אכלמהם", "so that I may speak to them"),
        ("אֵת הַדְּבָרִים הָאֵלֶּה", "בהד'א אלכלאם", "these words"),
        ("וְאָעִידָה בָּם", "ואשהד עליהם", "and call"),
        ("אֶת-הַשָּׁמַיִם", "אלסמאואת", "the heavens"),
        ("וְאֶת-הָאָרֶץ", "ואלארץ'", "and the earth"),
    ],
    29: [
        ("כִּי יָדַעְתִּי", "פאני אעלם", "For I know"),
        ("אַחֲרֵי מוֹתִי", "בעד מותי", "that after my death"),
        ("כִּי-הַשְׁחֵת תַּשְׁחִתוּן", "אנכם סתפסדון", "you shall act corruptly"),
        ("וְסַרְתֶּם מִן-הַדֶּרֶךְ", "ותזולון ען אלטריק", "and deviate from the path"),
        ("אֲשֶׁר צִוִּיתִי אֶתְכֶם", "אלד'י אמרתכם", "which I commanded you"),
        ("וְקָרָאת אֶתְכֶם הָרָעָה", "פיואפיכם אלבלא", "and affliction shall come upon you"),
        ("בְּאַחֲרִית הַיָּמִים", "פי אכ'ר הד'ה אלאיאם", "in the end of these days"),
        ("כִּי-תַעֲשׂוּ אֶת-הָרַע", "אד' תצנעון אלשר", "since you shall do evil"),
        ("בְּעֵינֵי יְהוָה", "בין ידי אללה", "before God"),
        ("לְהַכְעִיסוֹ", "לתגיצ'וה", "provoking Him to anger"),
        ("בְּמַעֲשֵׂה יְדֵיכֶם", "בעמל ידיכם", "by the work of your hands"),
    ],
    30: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר מֹשֶׁה", "כלמהם מוסי'", "Moses spoke to them"),
        ("אֶת-דִּבְרֵי הַשִּׁירָה הַזֹּאת", "בגמיע כלאם הד'ה אלתסבחה", "all the words of this song of praise"),
        ("עַד תֻּמָּם", "אלי' אן כמלת", "until they were complete"),
    ],
}
