"""Hand-authored alignment triples for Devarim chapter 3.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַנֵּפֶן", "ולינא", "we turned"),
        ("וַנַּעַל", "וצעדנא", "and went up"),
        ("דֶּרֶךְ", "טריק", "the road of"),
        ("הַבָּשָׁן", "אלבת'נייה", "the Bashan"),
        ("וַיֵּצֵא", "פכ'רג", "came out"),
        ("עוֹג", "עוג", "Og"),
        ("מֶלֶךְ-הַבָּשָׁן", "מלך אלבת'נייה", "king of the Bashan"),
        ("לִקְרָאתֵנוּ", "תלקאנא", "to meet us"),
        ("הוּא", "הו", "he"),
        ("וְכָל-עַמּוֹ", "וגמיע קומה", "and all his people"),
        ("לַמִּלְחָמָה", "לאלחרב", "for battle"),
        ("אֶדְרֶעִי", "אלי' אד'ראעאת", "at Edrei"),
    ],
    2: [
        ("וַיֹּאמֶר", "פקאל", "And"),
        ("יְהוָה", "אללה", "God said"),
        ("אֵלַי", "לי", "to me"),
        ("אַל-תִּירָא", "לא תכ'אפה", "Fear him not"),
        ("כִּי", "פאני", "for"),
        ("נָתַתִּי אֹתוֹ", "קד אסלמתה", "I have already delivered him"),
        ("בְיָדְךָ", "פי ידך", "into your hand"),
        ("וְאֶת-כָּל-עַמּוֹ", "וגמיע קומה", "and all his people"),
        ("וְאֶת-אַרְצוֹ", "ובלדה", "and his land"),
        ("וְעָשִׂיתָ", "ואצנע", "and do"),
        ("לּוֹ", "בה", "to him"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("עָשִׂיתָ", "צנעת", "you did"),
        ("לְסִיחֹן", "בסיחון", "to Sihon"),
        ("מֶלֶךְ", "מלך", "king of"),
        ("הָאֱמֹרִי", "אלאמוריין", "the Amorites"),
        ("אֲשֶׁר יוֹשֵׁב", "אלמקים", "who dwelt"),
        ("בְּחֶשְׁבּוֹן", "פי חשבון", "in Heshbon"),
    ],
    3: [
        ("וַיִּתֵּן", "פאסלם", "delivered"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        ("בְּיָדֵנוּ", "פי אידינא", "into our hands"),
        ("גַּם", "איצ'א", "also"),
        ("אֶת-עוֹג", "עוג", "Og"),
        ("מֶלֶךְ-הַבָּשָׁן", "מלך אלבת'נייה", "king of the Bashan"),
        ("וְאֶת-כָּל-עַמּוֹ", "וגמיע קומ", "and all his people"),
        ("וַנַּכֵּהוּ", "פקתלנאהם", "and we struck them down"),
        ("עַד-בִּלְתִּי", "חתי'", "until"),
        ("הִשְׁאִיר-לוֹ", "לם נבק לה", "we left him"),
        ("שָׂרִיד", "שרידא", "no survivor"),
    ],
    4: [
        ("וַנִּלְכֹּד", "ופתחנא", "And we took"),
        ("אֶת-כָּל-עָרָיו", "גמיע קראה", "all his towns"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("לֹא הָיְתָה", "לם תבק", "there remained"),
        ("קִרְיָה", "קריה", "no town"),
        ("אֲשֶׁר לֹא-לָקַחְנוּ", "לם נאכ'ד'הא", "we did not take"),
        ("מֵאִתָּם", "מנהם", "from them"),
        (None, "מן ד'אלך", "Among those"),
        ("שִׁשִּׁים", "סתין", "sixty"),
        ("עִיר", "קריה", "towns"),
        ("כָּל-חֶבֶל", "כל כ'ט", "the entire line of"),
        ("אַרְגֹּב", "אלמוגב", "the wave"),
        ("מַמְלֶכֶת", "ממלכה'", "the kingdom of"),
        ("עוֹג", "עוג", "Og"),
        ("בַּבָּשָׁן", "פי אלבת'נייה", "in the Bashan"),
    ],
    5: [
        ("כָּל-אֵלֶּה", "כל הולאי", "All these"),
        ("עָרִים", "קרא", "towns"),
        ("בְּצֻרֹת", "חצינה", "were fortified"),
        ("חוֹמָה", "בסור", "with a"),
        ("גְבֹהָה", "שאמך'", "lofty wall"),
        ("דְּלָתַיִם", "ומצארע", "and with gates"),
        ("וּבְרִיחַ", "ונגור", "and bars"),
        ("לְבַד", "סוא", "besides"),
        ("מֵעָרֵי", "קרא", "the towns of"),
        ("הַפְּרָזִי", "אלארבאץ'", "the open settlements"),
        ("הַרְבֵּה מְאֹד", "פאנהא כת'ירה גדא", "which were very many"),
    ],
    6: [
        ("וַנַּחֲרֵם", "וכמא צנענא", "And as we did"),
        ("כַּאֲשֶׁר עָשִׂינוּ", "כד'אך אתלפנא", "so we destroyed"),
        ("לְסִיחֹן", "בסיחון", "to Sihon"),
        ("מֶלֶךְ", "מלך", "king of"),
        ("חֶשְׁבּוֹן", "חשבון", "Heshbon"),
        ("כָּל-עִיר", "מן כל קריה", "from every one of his towns"),
        ("מְתִם", "אלרהט", "the men"),
        ("הַנָּשִׁים", "ואלנסא", "and the women"),
        ("וְהַטָּף", "ואלאטפאל", "and the children"),
    ],
    7: [
        ("וְכָל-הַבְּהֵמָה", "וכל בהימה", "And all the livestock"),
        ("וּשְׁלַל", "וסלב", "and the spoil of"),
        ("הֶעָרִים", "אלקרא", "the towns"),
        ("בַּזּוֹנוּ לָנוּ", "ג'נמנאהא", "these we took as our gain"),
    ],
    8: [
        (None, "פחצל לנא", "And there came into our possession"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("אֶת-הָאָרֶץ", "בלד", "the land of"),
        ("שְׁנֵי מַלְכֵי", "מלכי", "the two kings of"),
        ("הָאֱמֹרִי", "אלאמוריין", "the Amorites"),
        ("מִיַּד", "אלד'ין", "who were"),
        ("אֲשֶׁר בְּעֵבֶר", "פי הד'א גאנב", "on this side of"),
        ("הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("מִנַּחַל", "מן ואד", "from the valley of"),
        ("אַרְנֹן", "ארנון", "Arnon"),
        ("עַד-הַר", "אלי' גבל", "to Mount"),
        ("חֶרְמוֹן", "חרמון", "Hermon"),
    ],
    9: [
        ("צִידֹנִים", "אלצידאניין", "the Sidonians"),
        ("יִקְרְאוּ", "יסמונה", "call"),
        ("לְחֶרְמוֹן", "אלד'י", "Which"),
        ("שִׂרְיֹן", "סריון", "Siryon"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("יִקְרְאוּ-לוֹ שְׂנִיר", "סניר", "call Senir"),
    ],
    10: [
        ("כֹּל עָרֵי", "וגמיע קרא", "And all the towns of"),
        ("הַמִּישֹׁר", "אלסהל", "the plain"),
        ("וְכָל-הַגִּלְעָד", "וגרש", "and Jarash"),
        ("וְכָל-הַבָּשָׁן", "אלי' אלבת'נייה", "as far as the Bashan"),
        ("עַד-סַלְכָה", "אלי' סלכה", "to Salkhah"),
        ("וְאֶדְרֶעִי", "ואד'ראעאת", "and Edrei"),
        ("עָרֵי", "הי איצ'א מן קרא", "these too were among the towns of"),
        ("מַמְלֶכֶת", "ממלכה'", "the kingdom of"),
        ("עוֹג", "עוג", "Og"),
        ("בַּבָּשָׁן", "פי אלבת'נייה", "in the Bashan"),
    ],
    11: [
        ("כִּי", "לאנה", "For"),
        ("רַק-עוֹג", "בקי", "he alone remained"),
        ("נִשְׁאַר", "מן בקייה'", "of the remnant of"),
        ("מִיֶּתֶר", "אלגבאברה", "the giants"),
        ("הָרְפָאִים", "והוד'א", "and behold"),
        ("הִנֵּה", "לה", "his"),
        ("עַרְשׂוֹ", "סריר", "bed"),
        ("עֶרֶשׂ בַּרְזֶל", "מן חדיד", "is of iron"),
        (None, "פי", "in"),
        ("בְּרַבַּת", "אלראביה", "the hill-country"),
        ("בְּנֵי עַמּוֹן", "אלתי לבני עמון", "that belongs to the children of Ammon"),
        ("תֵּשַׁע אַמּוֹת אָרְכָּהּ", "טולה תסעה' אד'רע", "its length is nine cubits"),
        ("וְאַרְבַּע אַמּוֹת רָחְבָּהּ", "וערצה ארבעה' אד'רע", "and its breadth four cubits"),
        ("בְּאַמַּת-אִישׁ", "בד'ראע אלמלך", "by the cubit of the king"),
    ],
    12: [
        (None, "והד'א", "And this is"),
        ("הָאָרֶץ", "אלבלד", "the land"),
        ("הַזֹּאת", "אלד'י", "which"),
        ("יָרַשְׁנוּ", "חזנאה", "we took possession of"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("מֵעֲרֹעֵר", "פמן ערוער", "from Aroer"),
        ("אֲשֶׁר-עַל-נַחַל", "אלד'י עלי' ואד", "which is on the valley of"),
        ("אַרְנֹן", "ארנון", "Arnon"),
        ("וַחֲצִי", "ונצף", "and half"),
        ("הַר-הַגִּלְעָד", "גבל גרש", "the hill-country of Jarash"),
        ("וְעָרָיו", "בקראה", "with its towns"),
        ("נָתַתִּי", "דפעת ד'אלך", "this I assigned"),
        ("לָראוּבֵנִי", "אלי' אלראובניין", "to the Reubenites"),
        ("וְלַגָּדִי", "ואלי' אלגדיין", "and to the Gadites"),
    ],
    13: [
        ("וְיֶתֶר", "ובאקי", "And the remainder of"),
        ("הַגִּלְעָד", "גרש", "Jarash"),
        ("וְכָל-הַבָּשָׁן", "וגמיע אלבת'נייה", "and all the Bashan"),
        ("מַמְלֶכֶת עוֹג", "ממלכה' עוג", "the kingdom of Og"),
        ("נָתַתִּי", "דפעתה", "I assigned it"),
        ("לַחֲצִי", "אלי' נצף", "to the half"),
        ("שֵׁבֶט", "סבט", "tribe of"),
        ("הַמְנַשֶּׁה", "מנשה", "Manasseh"),
        ("כֹּל חֶבֶל", "וכל כ'ט", "and the entire line of"),
        ("הָאַרְגֹּב", "אלמוגב", "the Argob"),
        ("לְכָל-הַבָּשָׁן", "ואלבת'נייה", "and the Bashan"),
        ("יִקָּרֵא", "ד'אלך יסמיאן", "they call"),
        ("אֶרֶץ רְפָאִים", "בלד אלשגעא", "the land of the courageous"),
    ],
    14: [
        ("יָאִיר", "ויאיר", "And Jair"),
        ("בֶּן-מְנַשֶּׁה", "אבן מנשה", "son of Manasseh"),
        ("לָקַח", "אכ'ד'", "took"),
        ("אֶת-כָּל-חֶבֶל", "גמיע כ'ט", "all the line of"),
        ("אַרְגֹּב", "אלמוגב", "the Argob"),
        ("עַד-גְּבוּל", "אלי' חד", "as far as the border of"),
        ("הַגְּשׁוּרִי", "אלגשוריין", "the Geshurites"),
        ("וְהַמַּעֲכָתִי", "ואלמעכתיין", "and the Maacathites"),
        ("וַיִּקְרָא אֹתָם", "פסמאהא", "and he named them"),
        ("עַל-שְׁמוֹ", "באסמה", "after himself"),
        ("אֶת-הַבָּשָׁן חַוֹּת יָאִיר", "סואד יאיר", "the villages of Jair"),
        ("עַד הַיּוֹם הַזֶּה", "אלי' יומנא הד'א", "unto this day"),
    ],
    15: [
        ("וּלְמָכִיר", "ודפעת אלי' מכיר", "And to Machir I assigned"),
        ("אֶת-הַגִּלְעָד", "אלגרש", "Jarash"),
    ],
    16: [
        ("וְלָראוּבֵנִי", "ודפעת אלי' אלראובניין", "And to the Reubenites"),
        ("וְלַגָּדִי", "ואלגדיין", "and the Gadites"),
        ("מִן-הַגִּלְעָד", "מן גרש", "from Jarash"),
        ("וְעַד-נַחַל", "אלי' ואד", "to the valley of"),
        ("אַרְנֹן", "ארנון", "Arnon"),
        ("תּוֹךְ הַנַּחַל", "ווסט אלואד", "the middle of the valley"),
        ("וּגְבֻל", "וחדה", "alone"),
        ("וְעַד יַבֹּק הַנַּחַל", "ואלי' ואד יבק", "and as far as the valley of Jabbok"),
        ("גְּבוּל בְּנֵי עַמּוֹן", "תכ'ם בני עמון", "the border of the children of Ammon"),
    ],
    17: [
        ("וְהָעֲרָבָה", "ואלג'ור", "And the rift-valley"),
        ("וְהַיַּרְדֵּן", "ואלארדן", "and the Jordan"),
        ("וּגְבֻל", "וחדה", "alone"),
        ("מִכִּנֶּרֶת", "מן גניסר", "from Gennesaret"),
        ("וְעַד יָם הָעֲרָבָה", "אלי' בחר אלג'ור", "to the Sea of the Rift"),
        ("יָם הַמֶּלַח", "ואלבחירה אלמייתה", "and to the Dead Sea"),
        ("תַּחַת אַשְׁדֹּת הַפִּסְגָּה", "ומצב אלקלעה", "and the outlet of the"),
        ("מִזְרָחָה", "אלשרקייא", "eastern fortress."),
    ],
    18: [
        ("וָאֲצַו", "פאמרת", "And I commanded"),
        ("אֶתְכֶם", "הולאי מנכם", "those among you"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("נָתַן", "קד אעטאכם", "has given you"),
        ("לָכֶם", "אד'", "Since"),
        ("אֶת-הָאָרֶץ הַזֹּאת", "הד'א אלבלד", "this land"),
        ("לְרִשְׁתָּהּ", "פחזתמוה", "and you have taken possession of it"),
        ("חֲלוּצִים", "מגרדין", "armed"),
        ("תַּעַבְרוּ", "פאעברו", "cross over"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("אֲחֵיכֶם", "אכ'ותכם", "your brothers"),
        ("בְּנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("כָּל-בְּנֵי-חָיִל", "כל ד'וי חיל", "every one of martial strength"),
    ],
    19: [
        ("רַק", "עדא", "Except"),
        ("נְשֵׁיכֶם", "נסאכם", "your wives"),
        ("וְטַפְּכֶם", "ואטפאלכם", "and your children"),
        ("וּמִקְנֵכֶם", "ומואשיכם", "and your livestock"),
        ("כִּי-מִקְנֶה", "אן לכם מאשיה", "that you have"),
        ("יָדַעְתִּי", "פאני אעלם", "for I know"),
        ("רַב", "כת'ירה", "many"),
        ("יֵשְׁבוּ", "פליקימו", "they shall remain"),
        ("בְּעָרֵיכֶם", "פי קראכם", "in your towns"),
        ("אֲשֶׁר נָתַתִּי לָכֶם", "אלד'י אעטיתכם", "which I have given you"),
    ],
    20: [
        ("עַד אֲשֶׁר-יָנִיחַ יְהוָה", "אלי' אן יקרר אללה", "Until God settles"),
        ("לַאֲחֵיכֶם", "אכ'ותכם", "your brothers"),
        ("כָּכֶם", "מת'לכם", "as He has settled you"),
        ("וְיָרְשׁוּ", "פיחוזו", "take possession of"),
        ("גַם-הֵם", "הם איצ'א", "they too"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("נֹתֵן לָהֶם", "מעטיהם", "is giving them"),
        ("בְּעֵבֶר הַיַּרְדֵּן", "פי ד'אלך גאנב אלארדן", "on that side of the Jordan"),
        ("וְשַׁבְתֶּם אִישׁ", "פתרגעו כל אמר", "then each man shall return"),
        ("לִירֻשָּׁתוֹ", "אלי' חוזה", "to his holding"),
        ("אֲשֶׁר נָתַתִּי לָכֶם", "אלד'י אעטיתכם", "which I have given you"),
    ],
    21: [
        ("וְאֶת-יְהוֹשׁוּעַ", "ואמרת יהושע", "And I charged Joshua"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time,"),
        ("לֵאמֹר", "וקלת לה", "and said to him:"),
        ("עֵינֶיךָ הָרֹאֹת", "עינאך קד ראת", "Your eyes have seen"),
        ("אֵת כָּל-אֲשֶׁר", "גמיע מא", "all that"),
        ("עָשָׂה יְהוָה אֱלֹהֵיכֶם", "צנע אללה רבכם", "God your Lord did"),
        ("לִשְׁנֵי הַמְּלָכִים הָאֵלֶּה", "בהד'אן אלמלכאן", "to these two kings"),
        ("כֵּן-יַעֲשֶׂה יְהוָה", "כד'אך יצנע אללה", "so shall God do"),
        ("לְכָל-הַמַּמְלָכוֹת", "בגמיע אלממאלך", "to all the kingdoms"),
        ("אֲשֶׁר אַתָּה", "אלד'י אנת", "to which you are"),
        ("עֹבֵר שָׁמָּה", "גאיז אלי' ת'ם", "crossing over there"),
    ],
    22: [
        ("לֹא תִּירָאוּם", "לא תכ'אפוהם", "Fear them not"),
        ("כִּי", "פאן", "for"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("הוּא הַנִּלְחָם", "יחארב", "shall do battle"),
        ("לָכֶם", "ענכם", "on your behalf"),
    ],
    23: [
        (None, "ת'ם", "Then"),
        ("וָאֶתְחַנַּן", "תחננת", "I implored"),
        ("אֶל-יְהוָה", "בין ידי אללה", "before God"),
        ("בָּעֵת הַהִוא", "פי זאלך אלוקת", "at that time"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    24: [
        ("אֲדֹנָי", "אללהם", "O God"),
        ("יְהוִה", "יא רבי", "my Lord"),
        ("אַתָּה", "אנת", "You"),
        ("הַחִלּוֹתָ", "אבתדית", "have begun"),
        ("לְהַרְאוֹת", "אן תורי", "to show"),
        ("אֶת-עַבְדְּךָ", "עבדך", "Your servant"),
        ("אֶת-גָּדְלְךָ", "עצ'מתך", "Your greatness"),
        ("וְאֶת-יָדְךָ", "וקדרתך", "and Your"),
        ("הַחֲזָקָה", "אלשדידה", "mighty power"),
        ("אֲשֶׁר מִי-אֵל", "לא אלאה", "There is no god"),
        ("בַּשָּׁמַיִם", "פי אלסמא", "in the heaven"),
        ("וּבָאָרֶץ", "ולא פי אלארץ'", "nor in the earth"),
        ("אֲשֶׁר-יַעֲשֶׂה", "יצנע", "that can do"),
        ("כְמַעֲשֶׂיךָ", "כצנאיעך", "as Your works"),
        ("וְכִגְבוּרֹתֶךָ", "וגברוותך", "and Your might"),
    ],
    25: [
        ("אֶעְבְּרָה-נָּא", "אסאלך אן אגוז", "I ask of You that I may cross over"),
        ("וְאֶרְאֶה", "ואנצ'ר", "and behold"),
        ("אֶת-הָאָרֶץ הַטּוֹבָה", "אלי' זאלך אלבלד אלגייד", "that good land"),
        ("אֲשֶׁר בְּעֵבֶר", "אלזי מן זאך גאנב", "which is on that side of"),
        ("הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("הָהָר הַטּוֹב הַזֶּה", "וזאלך אלגבל גייד", "that good mountain"),
        ("וְהַלְּבָנֹן", "ואלבנאן", "and Lebanon"),
    ],
    26: [
        ("וַיִּתְעַבֵּר יְהוָה", "פוגד אללה", "But God was angered"),
        ("בִּי", "עליי", "with me"),
        ("לְמַעַנְכֶם", "בסבבכם", "on your account"),
        ("וְלֹא שָׁמַע", "ולם יסמע", "and did not hearken"),
        ("אֵלָי", "לי", "to me"),
        (None, "בל", "rather"),
        ("וַיֹּאמֶר יְהוָה אֵלַי", "קאללי", "He said to me:"),
        ("רַב-לָךְ", "חסבך", "Enough for you"),
        ("אַל-תּוֹסֶף", "לא תזיד", "do not add further"),
        ("דַּבֵּר", "פי מסאלתי", "petitions to Me"),
        ("בַּדָּבָר הַזֶּה", "פי הזא אלבאב", "in this matter"),
    ],
    27: [
        (None, "לכן", "But"),
        ("עֲלֵה", "אצעד", "go up"),
        ("רֹאשׁ הַפִּסְגָּה", "אלי' ראס אלקלעה", "to the summit of the fortress"),
        ("וְשָׂא", "וארפע", "and lift up"),
        ("עֵינֶיךָ", "עינאך", "your eyes"),
        ("יָמָּה", "ג'רבא", "westward"),
        ("וְצָפֹנָה", "ושמאלא", "and northward"),
        ("וְתֵימָנָה", "וגנובא", "and southward"),
        ("וּמִזְרָחָה", "ושרקא", "and eastward"),
        ("וּרְאֵה", "ואנצ'רהא", "and behold it"),
        ("בְעֵינֶיךָ", "בעינאך", "with your eyes"),
        ("כִּי-לֹא תַעֲבֹר", "פאנך לא תגוז", "for you shall not cross"),
        ("אֶת-הַיַּרְדֵּן הַזֶּה", "הזא אלארדן", "this Jordan"),
    ],
    28: [
        ("וְצַו", "ומר", "And command"),
        ("אֶת-יְהוֹשֻׁעַ", "יהושע", "Joshua"),
        ("וְחַזְּקֵהוּ", "ושדדה", "and strengthen him"),
        ("וְאַמְּצֵהוּ", "ואיידה", "and support him"),
        ("כִּי-הוּא", "פאנה", "for he"),
        ("יַעֲבֹר", "יעבר", "shall cross"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("הָעָם הַזֶּה", "הולאי אלקום", "this people"),
        ("וְהוּא", "והו", "and he"),
        ("יַנְחִיל אוֹתָם", "ינחלהם", "shall give them as inheritance"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר תִּרְאֶה", "אלזי תראה", "which you see"),
    ],
    29: [
        (None, "ת'ם", "Then"),
        ("וַנֵּשֶׁב", "גלסנא", "we settled"),
        ("בַּגָּיְא", "פי אלואד", "in the valley"),
        ("מוּל", "ממא ילי", "toward"),
        ("בֵּית פְּעוֹר", "בית פעור", "Beth Peor"),
    ],
}
