"""Hand-authored alignment triples for Devarim chapter 2.

Word-level: each JA (Saadia) word/unit is its own group, mapped to the Hebrew
word it renders and its English counterpart. The runtime resolver matches each
side independently (lib/alignment.ts), so words link correctly even across
word-order crossings — verb-subject inversions, English-fronted negations, and
Hebrew construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions, connectives) carry he=None and link JA↔English only.

Chapter content: skirting Edom (Seir), Moab, and Ammon; the war with Sihon
king of Heshbon; geographic parentheses on the Emim, Horites, and Zamzummim.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַנֵּפֶן", "ולינא", "we turned"),
        ("וַנִּסַּע", "ורחלנא", "and journeyed"),
        ("הַמִּדְבָּרָה", "פי אלבר", "through the wilderness"),
        ("דֶּרֶךְ", "טריק", "by the way of"),
        ("יַם-סוּף", "בחר אלקלזם", "the Sea of Qulzum"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה אֵלָי", "כמא אמרני אללה", "as God commanded me"),
        ("וַנָּסָב", "ואסתדרנא", "and we circled"),
        ("אֶת-הַר-שֵׂעִיר", "גבל סעיר", "Mount Seir"),
        ("יָמִים רַבִּים", "מדה טוילה", "for a long while"),
    ],
    2: [
        ("וַיֹּאמֶר יְהוָה", "פקאל אללה", "And God said"),
        ("אֵלַי", "לי", "to me"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    3: [
        ("רַב-לָכֶם", "חסבכם", "Enough of your"),
        ("סֹב", "מן אלאחאטה", "circling"),
        ("אֶת-הָהָר הַזֶּה", "בהד'א אלגבל", "of this mountain"),
        ("פְּנוּ לָכֶם", "ולו ענה", "turn away from it"),
        ("צָפֹנָה", "שמאלא", "northward"),
    ],
    4: [
        ("וְאֶת-הָעָם צַו", "ומר קומך", "And command your people"),
        ("לֵאמֹר", "וקל להם", "and say to them"),
        ("אַתֶּם", "אנתם", "You are"),
        ("עֹבְרִים", "גאיזין", "passing"),
        ("בִּגְבוּל", "פי תכם", "through the territory of"),
        ("אֲחֵיכֶם", "אכ'ותכם", "your brothers"),
        ("בְּנֵי-עֵשָׂו", "בני עשו", "the sons of Esau"),
        ("הַיֹּשְׁבִים", "אלמקימין", "who dwell"),
        ("בְּשֵׂעִיר", "בסעיר", "in Seir"),
        ("וְיִירְאוּ מִכֶּם", "פיכ'אפוכם", "they will fear you"),
        ("וְנִשְׁמַרְתֶּם מְאֹד", "ואחדרו גדא", "so be very much on your guard"),
    ],
    5: [
        ("אַל-תִּתְגָּרוּ בָם", "לא תתחרשו בהם", "Do not provoke them"),
        ("כִּי", "לאני", "for"),
        ("לֹא-אֶתֵּן לָכֶם", "ליס אעטיכם", "I will not give you"),
        ("מֵאַרְצָם", "מן בלדהם", "of their land"),
        ("עַד מִדְרַךְ כַּף-רָגֶל", "ולא וטי קדם", "not so much as a footstep"),
        ("כִּי-יְרֻשָּׁה", "וראת'ה", "as an inheritance"),
        ("לְעֵשָׂו", "לעשו", "to Esau"),
        ("נָתַתִּי", "קד אעטיתה", "I have already given"),
        ("אֶת-הַר שֵׂעִיר", "גבל סעיר", "Mount Seir"),
    ],
    6: [
        (None, "בל", "Rather"),
        ("אֹכֶל", "טעאמא", "food"),
        ("תִּשְׁבְּרוּ מֵאִתָּם", "אשתרו מנהם", "buy"),
        ("בַּכֶּסֶף", "בת'מן", "for a price"),
        ("וַאֲכַלְתֶּם", "פכלוה", "and eat it"),
        ("וְגַם-מַיִם", "ואיצ'א מאא", "and likewise water"),
        ("תִּכְרוּ מֵאִתָּם בַּכֶּסֶף--וּשְׁתִיתֶם", "פאשרבוה", "and drink it"),
    ],
    7: [
        ("כִּי", "לאן", "For"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בֵּרַכְךָ", "קד בארך לך", "has already blessed you"),
        ("בְּכֹל מַעֲשֵׂה יָדֶךָ", "פי גמיע אעמלך", "in all your works"),
        ("יָדַע לֶכְתְּךָ", "ואחסן אליך ענד מסירך", "and dealt well with you during your journey"),
        ("אֶת-הַמִּדְבָּר הַגָּדֹל הַזֶּה", "פי הד'א אלבר אל עצ'ים", "through this great and terrible wilderness"),
        ("זֶה אַרְבָּעִים שָׁנָה", "פהד'א ארבעין סנה", "these forty years"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord"),
        ("עִמָּךְ", "מעך", "has been with you"),
        ("לֹא חָסַרְתָּ דָּבָר", "לם יעוזך שייא", "you have lacked nothing"),
    ],
    8: [
        (None, "פ", "So"),
        ("וַנַּעֲבֹר", "גזנא", "we passed by"),
        ("מֵאֵת אַחֵינוּ", "מן אכ'ותנא", "our brothers"),
        ("בְנֵי-עֵשָׂו", "בני עשו", "the sons of Esau"),
        ("הַיֹּשְׁבִים בְּשֵׂעִיר", "אלמקימין בסעיר", "who dwell in Seir"),
        ("מִדֶּרֶךְ הָעֲרָבָה", "מן טריק אלבידא", "by the way of the open desert"),
        ("מֵאֵילַת", "ואילת", "and Elath"),
        ("וּמֵעֶצְיֹן גָּבֶר", "ועציון גבר", "and Ezion-Geber"),
        ("וַנֵּפֶן", "וולינא", "and we turned"),
        ("וַנַּעֲבֹר", "ורחלנא", "and journeyed"),
        ("דֶּרֶךְ מִדְבַּר מוֹאָב", "טריק ברייה' מואב", "by the way of the wilderness of Moab"),
    ],
    9: [
        ("וַיֹּאמֶר יְהוָה", "פקאל אללה", "And God said"),
        ("אֵלַי", "לי", "to me"),
        ("אַל-תָּצַר", "לא תחאצר", "Do not lay siege to"),
        ("אֶת-מוֹאָב", "אלמואביין", "the Moabites"),
        ("וְאַל-תִּתְגָּר בָּם", "ולא תתחרש בהם", "and do not provoke them"),
        ("מִלְחָמָה", "לאלחרב", "to war"),
        ("כִּי", "פאני", "for"),
        ("לֹא-אֶתֵּן לְךָ מֵאַרְצוֹ יְרֻשָּׁה", "לא אעטיכם מן בלדהם חוזא", "I will not give you any possession of their land"),
        ("כִּי לִבְנֵי-לוֹט", "אד' לבני לוט", "since to the sons of Lot"),
        ("נָתַתִּי", "קד געלת", "I have already given"),
        ("אֶת-עָר יְרֻשָּׁה", "ער וראת'ה", "Ar as an inheritance"),
    ],
    10: [
        (None, "וכאן", "Now"),
        ("הָאֵמִים", "אלהיוביין", "the Hayubians"),
        ("לְפָנִים", "קבלהם", "had formerly"),
        ("יָשְׁבוּ בָהּ", "אקאמו בהא", "dwelt in it"),
        ("עַם גָּדוֹל", "קום כביר", "a great"),
        ("וְרַב", "כת'יר", "numerous"),
        ("וָרָם", "ורפיע", "and tall people"),
        ("כָּעֲנָקִים", "כאלגבארין", "like the mighty ones"),
    ],
    11: [
        ("רְפָאִים", "שגעא", "bold warriors"),
        ("יֵחָשְׁבוּ", "יחסבון", "are reckoned as"),
        ("אַף-הֵם", "והם איצ'א", "They too"),
        ("כָּעֲנָקִים", "כאלגבארין", "like the mighty ones"),
        ("וְהַמֹּאָבִים", "ואלמואביין", "and the Moabites"),
        ("יִקְרְאוּ לָהֶם", "יסמונהם", "call them"),
        ("אֵמִים", "אלהיוביין", "the Hayubians"),
    ],
    12: [
        (None, "ואמא", "And"),
        ("וּבְשֵׂעִיר", "פי סעיר", "in Seir"),
        ("יָשְׁבוּ הַחֹרִים", "פאקאם אלחוריין", "the Horites dwelt"),
        ("לְפָנִים", "קבל בני עשו", "before the sons of Esau"),
        ("וּבְנֵי עֵשָׂו יִירָשׁוּם", "חתי אתו פקרצ'והם", "until they came and devoured them"),
        ("וַיַּשְׁמִידוּם", "ואנפד'והם", "and drove them out"),
        ("מִפְּנֵיהֶם", "מן בין ידיהם", "from before them"),
        ("וַיֵּשְׁבוּ תַּחְתָּם", "ואקאמו מכאנהם", "and settled in their place"),
        ("כַּאֲשֶׁר עָשָׂה", "כמא צנע", "just as"),
        ("יִשְׂרָאֵל", "אל אסראיל", "Israel did"),
        ("לְאֶרֶץ יְרֻשָּׁתוֹ", "בבעץ' חוזה", "to part of its territory"),
        ("אֲשֶׁר-נָתַן יְהוָה לָהֶם", "אלד'י אעטאהם אללה", "which God gave it"),
    ],
    13: [
        (None, "אלאן", "And now"),
        ("עַתָּה קֻמוּ", "קומו", "arise"),
        ("וְעִבְרוּ לָכֶם", "ואעברו", "and cross"),
        ("אֶת-נַחַל זָרֶד", "ואד זרד", "the wadi Zared"),
        ("וַנַּעֲבֹר אֶת-נַחַל זָרֶד", "פעברנאה", "So we crossed it"),
    ],
    14: [
        (None, "וכאנת גמל'ה", "And the sum of"),
        ("וְהַיָּמִים", "אלאייאם", "the days"),
        ("אֲשֶׁר-הָלַכְנוּ", "מנד' סרנא", "from when we journeyed"),
        ("מִקָּדֵשׁ בַּרְנֵעַ", "מן רקים ברנע", "from Kadesh-Barnea"),
        ("עַד אֲשֶׁר-עָבַרְנוּ", "אלי' אן עברנא", "until we crossed"),
        ("אֶת-נַחַל זֶרֶד", "ואד זרד", "the wadi Zared"),
        ("שְׁלֹשִׁים וּשְׁמֹנֶה שָׁנָה", "ת'מאניה ות'לאת'ין סנה", "was thirty-eight years"),
        ("עַד-תֹּם", "אלי' אן פני", "until"),
        ("כָּל-הַדּוֹר", "גמיע אלקום", "all"),
        ("אַנְשֵׁי הַמִּלְחָמָה", "אלמחארבין", "the fighting men"),
        ("מִקֶּרֶב הַמַּחֲנֶה", "מן אלמעסכר", "had perished from the camp"),
        ("כַּאֲשֶׁר נִשְׁבַּע יְהוָה לָהֶם", "כמא קסם אללה עליהם", "as God had sworn concerning them"),
    ],
    15: [
        (None, "ו", "And"),
        ("וְגַם יַד-יְהוָה", "אפה מן ענד אללה", "a plague from God"),
        ("הָיְתָה בָּם", "חלת בהם", "came upon them"),
        ("לְהֻמָּם", "לאהאמתהם", "to rout them"),
        ("מִקֶּרֶב הַמַּחֲנֶה", "מן אלמעסכר", "from the camp"),
        ("עַד תֻּמָּם", "אלי' אן פניו", "until they perished"),
    ],
    16: [
        ("וַיְהִי כַאֲשֶׁר-תַּמּוּ כָּל-אַנְשֵׁי הַמִּלְחָמָה לָמוּת--מִקֶּרֶב הָעָם", "פלמא פני גמיעהם מן בין אלאמה", "And when they had all perished from among the nation"),
    ],
    17: [
        ("וַיְדַבֵּר יְהוָה", "פקאל אללה", "God said"),
        ("אֵלַי", "לי", "to me"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    18: [
        ("אַתָּה", "אנת", "You are"),
        ("עֹבֵר", "גאיז", "crossing"),
        ("הַיּוֹם", "אליום", "today"),
        ("אֶת-גְּבוּל", "תכם", "the border of"),
        ("מוֹאָב", "מואב", "Moab"),
        ("אֶת-עָר", "אלד'י הו ער", "which is Ar"),
    ],
    19: [
        ("וְקָרַבְתָּ", "ותקרב", "And as you approach"),
        ("מוּל בְּנֵי עַמּוֹן", "מן בני עמון", "the sons of Ammon"),
        ("אַל-תְּצֻרֵם", "פלא תחאצרהם", "do not lay siege to them"),
        ("וְאַל-תִּתְגָּר בָּם", "ולא תתחרש בהם", "and do not provoke them"),
        ("כִּי", "פאני", "for"),
        ("לֹא-אֶתֵּן מֵאֶרֶץ בְּנֵי-עַמּוֹן לְךָ יְרֻשָּׁה", "לא אעטיך מן בלדהם חוזא", "I will not give you any possession of their land"),
        ("כִּי לִבְנֵי-לוֹט", "אד' געלתהא לבני לוט", "since I have assigned it to the sons of Lot"),
        ("נְתַתִּיהָ יְרֻשָּׁה", "חוזא", "as a possession"),
    ],
    20: [
        ("אֶרֶץ-רְפָאִים תֵּחָשֵׁב אַף-הִוא", "והי תחסב איצ'א", "It too is reckoned as"),
        (None, "מן בלד אלגבארין", "the land of the mighty ones"),
        ("רְפָאִים", "אלגבאברה", "the mighty ones"),
        ("יָשְׁבוּ-בָהּ", "אקאמו בהא", "dwelt in it"),
        ("לְפָנִים", "קבלהם", "before them"),
        ("וְהָעַמֹּנִים", "ואלעמוניין", "and the Ammonites"),
        ("יִקְרְאוּ לָהֶם", "יסמונהם", "call them"),
        ("זַמְזֻמִּים", "ד'וי אלהמם", "the men of great spirit"),
    ],
    21: [
        ("עַם גָּדוֹל", "קום כביר", "A great"),
        ("וְרַב וָרָם", "רפיע כאלגבארין", "and tall people, like the mighty ones"),
        ("וַיַּשְׁמִידֵם יְהוָה", "אנפד'הם אללה", "God drove them out"),
        ("מִפְּנֵיהֶם", "מן בין ידיהם", "from before them"),
        ("וַיִּירָשֻׁם", "פקרצ'והם", "and they devoured them"),
        ("וַיֵּשְׁבוּ תַחְתָּם", "ואקאמו מכאנהם", "and settled in their place"),
    ],
    22: [
        ("כַּאֲשֶׁר עָשָׂה", "כמא צנע", "Just as He did"),
        ("לִבְנֵי עֵשָׂו", "לבני עשו", "for the sons of Esau"),
        ("הַיֹּשְׁבִים בְּשֵׂעִיר", "אלמקימין בסעיר", "who dwell in Seir"),
        ("אֲשֶׁר הִשְׁמִיד אֶת-הַחֹרִי", "אד' אנפד' אלחוריין", "since the Horites were driven out"),
        ("מִפְּנֵיהֶם", "מן בין ידיהם", "from before them"),
        ("וַיִּירָשֻׁם", "פקרצ'והם", "and they devoured them"),
        ("וַיֵּשְׁבוּ תַחְתָּם", "ואקאמו מכאנהם", "and settled in their place"),
        ("עַד הַיּוֹם הַזֶּה", "אלי' הד'א אליום", "until this day"),
    ],
    23: [
        ("וְהָעַוִּים", "ואלעויין", "And the Avvites"),
        ("הַיֹּשְׁבִים", "אלמקימין", "who dwelt"),
        ("בַּחֲצֵרִים", "ברפח", "in Raphah"),
        ("עַד-עַזָּה", "אלי' ג'זה", "as far as Gaza"),
        ("כַּפְתֹּרִים", "ואלדמיאטיין", "the Dumyatians"),
        ("הַיֹּצְאִים", "אלד'י כ'רגו", "who came out"),
        ("מִכַּפְתֹּר", "מן דמיאט", "of Dumyat"),
        ("הִשְׁמִידֻם", "קרצ'והם", "devoured them"),
        ("וַיֵּשְׁבוּ תַחְתָּם", "ואקאמו מכאנהם", "and settled in their place"),
    ],
    24: [
        ("קוּמוּ", "פקומו", "Arise"),
        ("סְּעוּ", "וארחלו", "and journey"),
        ("וְעִבְרוּ", "ואעברו", "and cross"),
        ("אֶת-נַחַל אַרְנֹן", "ואד ארנון", "the wadi Arnon"),
        (None, "אנצ'ר", "See"),
        ("נָתַתִּי", "קד אסלמת", "I have delivered"),
        ("בְיָדְךָ", "פי ידך", "into your hand"),
        ("אֶת-סִיחֹן", "סיחון", "Sihon"),
        ("מֶלֶךְ-חֶשְׁבּוֹן", "מלך חשבון", "king of Heshbon"),
        ("הָאֱמֹרִי", "אלאמורי", "the Amorite"),
        ("וְאֶת-אַרְצוֹ", "ובלדה", "and his land"),
        ("הָחֵל רָשׁ", "פאבד בקרצ'ה", "begin to devour it"),
        ("וְהִתְגָּר בּוֹ מִלְחָמָה", "ותחרש במחארבתה", "and provoke him to battle"),
    ],
    25: [
        (None, "ומן", "And from"),
        ("הַיּוֹם הַזֶּה", "הד'א אליום", "this day"),
        (None, "אבתדי", "I shall begin"),
        ("אָחֵל תֵּת", "באיקאע", "to cast"),
        ("פַּחְדְּךָ", "פזעך", "your dread"),
        ("וְיִרְאָתְךָ", "וכ'ופך", "and your fear"),
        ("עַל-פְּנֵי הָעַמִּים", "פי קלוב אלאמם", "into the hearts of the nations"),
        ("תַּחַת כָּל-הַשָּׁמָיִם", "אלד'ין תחת גמיע אלסמא", "that are under all the sky"),
        ("אֲשֶׁר יִשְׁמְעוּן שִׁמְעֲךָ", "פאד'א הם סמעו כ'ברך", "and when they hear news of you"),
        ("וְרָגְזוּ", "רגזו", "they shall be convulsed"),
        ("וְחָלוּ מִפָּנֶיךָ", "וארתעדו מן בין ידיך", "and shall tremble before you"),
    ],
    26: [
        (None, "פ", "So"),
        ("וָאֶשְׁלַח", "בעתת", "I sent"),
        ("מַלְאָכִים", "ברסל", "messengers"),
        ("מִמִּדְבַּר קְדֵמוֹת", "מן ברייה' קדמות", "from the wilderness of Kedemoth"),
        ("אֶל-סִיחוֹן", "אלי' סיחון", "to Sihon"),
        ("מֶלֶךְ חֶשְׁבּוֹן", "מלך חשבון", "king of Heshbon"),
        ("דִּבְרֵי שָׁלוֹם", "בסלאם", "with words of peace"),
        ("לֵאמֹר", "וכלאם קאלו לה", "saying to him"),
    ],
    27: [
        ("אֶעְבְּרָה", "אריד אן אגוז", "I wish to pass"),
        ("בְאַרְצֶךָ", "פי בלדך", "through your land"),
        ("בַּדֶּרֶךְ בַּדֶּרֶךְ", "פי אלטריק אלגאדה", "along the main road"),
        ("אֵלֵךְ", "נסיר", "we shall travel"),
        ("לֹא אָסוּר", "לא אמיל", "turning neither"),
        ("יָמִין", "ימנה", "right"),
        ("וּשְׂמֹאול", "ולא יסרה", "nor left"),
    ],
    28: [
        ("אֹכֶל", "טעאמא", "Food"),
        ("בַּכֶּסֶף", "בת'מן", "for a price"),
        ("תַּשְׁבִּרֵנִי", "תמירני", "you shall provision me"),
        ("וְאָכַלְתִּי", "פאכלה", "so that I may eat it"),
        ("וּמַיִם", "ומאא", "and water"),
        ("בַּכֶּסֶף", "בת'מן", "for a price"),
        ("תִּתֶּן-לִי", "תביעני", "you shall provision me"),
        ("וְשָׁתִיתִי", "פאשרבה", "so that I may drink it"),
        ("רַק אֶעְבְּרָה בְרַגְלָי", "ואעבר ברגלי פקט", "only let me pass on foot"),
    ],
    29: [
        ("כַּאֲשֶׁר עָשׂוּ-לִי", "כמא צנעו לי", "Just as"),
        ("בְּנֵי עֵשָׂו", "בעץ' בני עשו", "some of the sons of Esau"),
        ("הַיֹּשְׁבִים בְּשֵׂעִיר", "אלמקימין בסעיר", "who dwell in Seir did for me"),
        ("וְהַמּוֹאָבִים", "ואלמואביין", "and the Moabites"),
        ("הַיֹּשְׁבִים בְּעָר", "אלמקימין בער", "who dwell in Ar"),
        ("עַד אֲשֶׁר-אֶעֱבֹר", "אלי' אן אעבר", "until I cross"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "to the land"),
        ("אֲשֶׁר-יְהוָה אֱלֹהֵינוּ", "אלד'י אללה רבנא", "which God our Lord"),
        ("נֹתֵן לָנוּ", "מעטינאה", "is giving us"),
    ],
    30: [
        ("וְלֹא אָבָה סִיחֹן מֶלֶךְ חֶשְׁבּוֹן", "ולם ישא סיחון מלך חשבון", "But Sihon king of Heshbon was not willing"),
        ("הַעֲבִרֵנוּ בּוֹ", "אגאזתנא פי בלדה", "to let us pass through his land"),
        ("כִּי-הִקְשָׁה יְהוָה אֱלֹהֶיךָ", "לאן אללה רבך צעב", "because God your Lord had made"),
        ("אֶת-רוּחוֹ", "רוחה", "his spirit unyielding"),
        ("וְאִמֵּץ אֶת-לְבָבוֹ", "ושדד קלבה", "and had hardened his heart"),
        ("לְמַעַן תִּתּוֹ", "לכי יסלמה", "so that He might deliver him"),
        ("בְיָדְךָ", "בידך", "into your hand"),
        ("כַּיּוֹם הַזֶּה", "כמא תרי' אליום", "as you see this day"),
    ],
    31: [
        ("וַיֹּאמֶר יְהוָה", "פקאל אללה", "And God said"),
        ("אֵלַי", "לי", "to me"),
        (None, "אנצ'ר", "See"),
        ("הַחִלֹּתִי", "קד בדית", "I have begun"),
        ("תֵּת לְפָנֶיךָ", "אן אסלם פי ידך", "to deliver into your hand"),
        ("אֶת-סִיחֹן", "סיחון", "Sihon"),
        ("וְאֶת-אַרְצוֹ", "ובלדה", "and his land"),
        ("הָחֵל רָשׁ", "פאבד בקרצ'ה", "begin to devour it"),
        ("לָרֶשֶׁת אֶת-אַרְצוֹ", "וחז בלדה", "and take his land"),
    ],
    32: [
        ("וַיֵּצֵא סִיחֹן", "פכ'רג סיחון", "And Sihon came out"),
        ("לִקְרָאתֵנוּ", "תלקאנא", "to meet us"),
        ("הוּא", "הו", "he"),
        ("וְכָל-עַמּוֹ", "וגמיע קומה", "and all his people"),
        ("לַמִּלְחָמָה", "לאלחרב", "for battle"),
        ("יָהְצָה", "אלי' י'הץ", "at Yahaz"),
    ],
    33: [
        ("וַיִּתְּנֵהוּ", "פאסלמה", "delivered him"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵינוּ", "רבנא", "our Lord"),
        ("לְפָנֵינוּ", "פי ידנא", "into our hand"),
        ("וַנַּךְ אֹתוֹ", "פקתלנאה", "and we struck him"),
        ("וְאֶת-בָּנָו", "ובניה", "and his sons"),
        ("וְאֶת-כָּל-עַמּוֹ", "וסאיר קומה", "and the rest of his people"),
    ],
    34: [
        ("וַנִּלְכֹּד", "ופתחנא", "And we captured"),
        ("אֶת-כָּל-עָרָיו", "גמיע קראה", "all his towns"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("וַנַּחֲרֵם", "ואתלפנא", "and we destroyed"),
        ("אֶת-כָּל-עִיר", "מן כל קריה", "from every town"),
        ("מְתִם", "אלרהט", "the men"),
        ("וְהַנָּשִׁים", "ואלנסא", "the women"),
        ("וְהַטָּף", "ואלאטפאל", "and the children"),
        ("לֹא הִשְׁאַרְנוּ שָׂרִיד", "לם נבק שרידא", "we left not a single survivor"),
    ],
    35: [
        ("רַק", "ו", "Only"),
        ("הַבְּהֵמָה", "כל בהימה", "all the livestock"),
        ("בָּזַזְנוּ לָנוּ", "ג'נמנא", "we took as spoil"),
        ("וּשְׁלַל", "וסלב", "and the plunder of"),
        ("הֶעָרִים", "אלקרא", "the towns"),
        ("אֲשֶׁר לָכָדְנוּ", "אלד'י פתחנאהא", "which we had captured"),
    ],
    36: [
        ("מֵעֲרֹעֵר", "מן ערוער", "From Aroer"),
        ("אֲשֶׁר עַל-שְׂפַת-נַחַל אַרְנֹן", "אלד'י עלי' שאט ואד ארנון", "which is upon the bank of the wadi Arnon"),
        ("וְהָעִיר אֲשֶׁר בַּנַּחַל", "ואלקריה אלד'י פי אלואד", "and the town which is in the valley"),
        ("וְעַד-הַגִּלְעָד", "ואלי' גרש", "and as far as Jerash"),
        ("לֹא הָיְתָה קִרְיָה", "לם תבק קריה", "not a town remained"),
        ("אֲשֶׁר שָׂגְבָה מִמֶּנּוּ", "מנעת מנא", "that was withheld from us"),
        (None, "בל", "rather"),
        ("אֶת-הַכֹּל", "אלכל", "all of it"),
        ("נָתַן יְהוָה אֱלֹהֵינוּ לְפָנֵינוּ", "אסלמה אללה רבנא פי אידינא", "God our Lord delivered into our hands"),
    ],
    37: [
        ("רַק", "עדא", "Except"),
        ("אֶל-אֶרֶץ בְּנֵי-עַמּוֹן", "אלי' בלד בני עמון", "the land of the sons of Ammon"),
        ("לֹא קָרָבְתָּ", "פאנך לם תקרבה", "you did not approach it"),
        ("כָּל-יַד נַחַל יַבֹּק", "פגמיע שאט ואד יבק", "namely the whole bank of the wadi Jabbok"),
        ("וְעָרֵי הָהָר", "וקרא אלגבל", "and the towns of the hill country"),
        ("וְכֹל אֲשֶׁר-צִוָּה יְהוָה אֱלֹהֵינוּ", "וסאיר מא נהאנא ענה אללה רבנא", "and all else that God our Lord had forbidden us"),
    ],
}
