"""Hand-authored alignment triples for Devarim chapter 18.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the priestly portions (vv. 1–8), forbidden divination
practices (vv. 9–14), the promise of a prophet like Moses (vv. 15–19), the
false prophet who speaks presumptuously (vv. 20–22) — aligned with particular
care for Saadia's expansion of the priestly-due vocabulary and his paraphrase
of the divination terms.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואד'", "And since"),
        ("לֹא-יִהְיֶה", "לא יכון", "shall have no"),
        ("לַכֹּהֲנִים", "לאלאיימה", "the priests"),
        ("הַלְוִיִּם", "ואלליואניין", "the Levites"),
        (None, "אלד'י הם סאיר", "who are the rest of"),
        ("כָּל-שֵׁבֶט לֵוִי", "סבט לוי", "the tribe of Levi"),
        ("חֵלֶק", "קסם", "portion"),
        ("וְנַחֲלָה", "ולא נחלה", "nor inheritance"),
        ("עִם-יִשְׂרָאֵל", "מע אל אסראיל", "with the house of Israel"),
        ("אִשֵּׁי יְהוָה", "פמן קראבין אללה", "it is from the offerings of God"),
        ("וְנַחֲלָתוֹ", "ומן נחלתה", "and from His inheritance"),
        ("יֹאכֵלוּן", "יאכלון", "that they shall eat"),
    ],
    2: [
        ("וְנַחֲלָה", "ונחלה", "And an inheritance"),
        ("לֹא-יִהְיֶה-לּוֹ", "לא תכון לה", "shall not be his"),
        ("בְּקֶרֶב אֶחָיו", "פי מא בין אכ'ותה", "among his brothers"),
        ("יְהוָה הוּא נַחֲלָתוֹ", "אד' פראיץ' אללה נחלתה", "for the prescribed dues of God are his inheritance"),
        ("כַּאֲשֶׁר דִּבֶּר-לוֹ", "כמא אמר לה בהא", "as He has decreed for him"),
    ],
    3: [
        ("וְזֶה", "והד'ה", "And this is"),
        ("יִהְיֶה", "מא יכון", "what shall be"),
        ("מִשְׁפַּט הַכֹּהֲנִים", "רסם אלאימה", "the customary due of the priests"),
        ("מֵאֵת הָעָם", "עלי' אלקום", "from the people"),
        ("מֵאֵת זֹבְחֵי הַזֶּבַח", "מן ד'אבחי אי ד'בח כאן", "from whoever slaughters any slaughter"),
        ("אִם-שׁוֹר אִם-שֶׂה", "מן אלבקר ואלג'נם", "whether of cattle or of flocks"),
        ("וְנָתַן", "אן יעטוהם", "they shall give them"),
        ("הַזְּרֹעַ", "אלד'ראע", "the foreleg"),
        ("וְהַלְּחָיַיִם", "ואללחיין", "and the two jaws"),
        ("וְהַקֵּבָה", "ואלאקבה", "and the stomach"),
    ],
    4: [
        ("רֵאשִׁית דְּגָנְךָ", "אוול ברך", "The first of your grain"),
        ("תִּירֹשְׁךָ", "ועצירך", "your juice"),
        ("וְיִצְהָרֶךָ", "ודהנך", "and your oil"),
        ("וְרֵאשִׁית גֵּז צֹאנְךָ", "ואוול גז ג'נמך", "and the first of the shearing of your flock"),
        ("תִּתֶּן-לוֹ", "תעטיה", "you shall give him"),
    ],
    5: [
        ("כִּי", "לאן", "For"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בָּחַר", "קד אכ'תארה", "has chosen him"),
        ("מִכָּל-שְׁבָטֶיךָ", "מן גמיע אסבטאך", "from all your tribes"),
        ("לַעֲמֹד", "ליקום", "to stand"),
        ("לְשָׁרֵת", "ויכ'דם", "and to serve"),
        ("בְּשֵׁם-יְהוָה", "באסם אללה", "in the name of God"),
        ("הוּא", "הו", "he"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "for the length of time"),
    ],
    6: [
        ("וְכִי-יָבֹא", "ואד'א חג", "And when"),
        ("הַלֵּוִי", "אי לוי", "any Levite makes pilgrimage"),
        ("מֵאַחַד שְׁעָרֶיךָ", "מן בעץ' מחאלך", "from some of your settlements"),
        ("מִכָּל-יִשְׂרָאֵל", "אלתי לגמיע אל אסראיל", "belonging to all the house of Israel"),
        ("אֲשֶׁר-הוּא גָּר שָׁם", "אלד'י הו מקים בהא", "in which he is residing"),
        ("וּבָא", "פלידכ'ל", "he may enter"),
        ("בְּכָל-אַוַּת נַפְשׁוֹ", "פי אי וקת שא", "at whatever time he wishes"),
        ("אֶל-הַמָּקוֹם", "אלי' אלמוצ'ע", "to the place"),
        ("אֲשֶׁר-יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God shall choose"),
    ],
    7: [
        ("וְשֵׁרֵת", "ויכ'דם", "And he shall serve"),
        ("בְּשֵׁם יְהוָה", "באסם אללה", "in the name of God"),
        ("אֱלֹהָיו", "רבה", "his Lord"),
        ("כְּכָל-אֶחָיו הַלְוִיִּם", "כגמיע אכ'ותה אלליואניין", "like all his Levite brothers"),
        ("הָעֹמְדִים שָׁם", "אלואקפין ת'ם", "who stand there"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    8: [
        ("חֵלֶק כְּחֵלֶק יֹאכֵלוּ", "וליקתסמו אנצבה מתסאויה", "And they shall share equal portions"),
        ("לְבַד מִמְכָּרָיו", "מא כ'לא מא את'בתה", "save for what the forefathers"),
        ("עַל-הָאָבוֹת", "אלאבא מן אלנווב", "established from the rotations"),
    ],
    9: [
        (None, "ואעלם", "And know"),
        ("אַתָּה בָּא", "אנך דאכ'ל", "that you are entering"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
        ("לֹא-תִלְמַד", "פלא תתעלם", "do not learn"),
        ("לַעֲשׂוֹת", "אן תעמל", "to do"),
        ("כְּתוֹעֲבֹת", "כמכארה'", "after the manner of the abominations of"),
        ("הַגּוֹיִם הָהֵם", "אולאיך אלאמם", "those nations"),
    ],
    10: [
        ("לֹא-יִמָּצֵא בְךָ", "ולא יוגד פיכם", "Let there not be found among you"),
        ("מַעֲבִיר בְּנוֹ-וּבִתּוֹ בָּאֵשׁ", "מן ישעל אבנה או אבנתה באלנאר", "one who burns his son or his daughter in the fire"),
        ("קֹסֵם קְסָמִים", "וקאסם קאסומאת", "nor a diviner of divinations"),
        ("מְעוֹנֵן", "ומתפאול", "nor one who takes omens"),
        ("וּמְנַחֵשׁ", "ומתטייר", "nor one who reads signs"),
        ("וּמְכַשֵּׁף", "וסאחר", "nor a sorcerer"),
    ],
    11: [
        ("וְחֹבֵר חָבֶר", "וראקי רקאא", "nor a reciter of incantations"),
        ("וְשֹׁאֵל אוֹב", "וסאל משעוד'", "nor one who consults a conjurer"),
        ("וְיִדְּעֹנִי", "או עראף", "or a soothsayer"),
        ("וְדֹרֵשׁ אֶל-הַמֵּתִים", "ומלתמס מן אלמותא", "nor one who seeks answers from the dead"),
    ],
    12: [
        ("כִּי-תוֹעֲבַת יְהוָה", "לאן אללה יכרה", "For God abhors"),
        ("כָּל-עֹשֵׂה אֵלֶּה", "כל מן יצנע הד'ה אלמכארה", "all who do these abominations"),
        ("וּבִגְלַל הַתּוֹעֵבֹת הָאֵלֶּה", "ובגרירתהא", "and it is on account of them"),
        ("יְהוָה אֱלֹהֶיךָ", "הו", "that He is"),
        ("מוֹרִישׁ אוֹתָם", "קארצ'הם", "cutting them off"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
    ],
    13: [
        (None, "בל", "But"),
        ("תָּמִים תִּהְיֶה", "כן סאדגא", "be simple"),
        ("עִם יְהוָה", "ללה", "toward God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
    ],
    14: [
        ("כִּי הַגּוֹיִם הָאֵלֶּה", "לאן הולאי אלאמם", "For these nations"),
        ("אֲשֶׁר אַתָּה יוֹרֵשׁ אוֹתָם", "אלד'י אנת וארת'הם", "whom you are to dispossess"),
        ("אֶל-מְעֹנְנִים", "מן אלמתפאולין", "it is to those who take omens"),
        ("וְאֶל-קֹסְמִים", "ואלקאסומין", "and to diviners"),
        ("יִשְׁמָעוּ", "יסמעון", "that they listen"),
        ("וְאַתָּה", "ואנת", "but as for you"),
        ("לֹא כֵן", "פלם יטלק לך", "has not permitted you"),
        ("נָתַן לְךָ", "אללה רבך", "God your Lord"),
        ("יְהוָה אֱלֹהֶיךָ", "מת'ל ד'אלך", "anything like that"),
    ],
    15: [
        (None, "לכן", "Rather"),
        ("נָבִיא", "אי נבי", "any prophet"),
        ("מִקִּרְבְּךָ", "מן בינכם", "from among you"),
        ("מֵאַחֶיךָ", "מן בעץ' אכ'ותך", "from some of your brothers"),
        ("כָּמֹנִי", "מת'לי", "like me"),
        ("יָקִים לְךָ", "ינצבה לך", "shall appoint him for you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֵלָיו תִּשְׁמָעוּן", "מנה פאקבלו", "from him you shall accept"),
    ],
    16: [
        ("כְּכֹל אֲשֶׁר-שָׁאַלְתָּ", "כגמיע מא סאלת", "In accordance with all that you asked"),
        ("יְהוָה", "אללה", "of God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בְּחֹרֵב", "פי גבל חריב", "at Mount Horeb"),
        ("בְּיוֹם הַקָּהָל", "פי יום אלגוק", "on the day of the assembly"),
        ("לֵאמֹר", "וקלת", "when you said"),
        ("לֹא אֹסֵף לִשְׁמֹעַ", "לא אעוד אן אסמע", "I will no longer hear"),
        ("אֶת-קוֹל יְהוָה אֱלֹהָי", "צות אללה רבי", "the voice of God my Lord"),
        ("וְאֶת-הָאֵשׁ הַגְּדֹלָה הַזֹּאת", "ולא ארא הד'ה אלנאר", "nor will I see this"),
        (None, "עצ'ימה", "great fire"),
        ("וְלֹא אָמוּת", "ללא אמות", "lest I die"),
    ],
    17: [
        ("וַיֹּאמֶר יְהוָה", "פקאל אללה", "And God said"),
        ("אֵלָי", "לי", "to me"),
        ("הֵיטִיבוּ", "קד אחסנו", "They have done well"),
        ("אֲשֶׁר דִּבֵּרוּ", "פי גמיע מא קאלו", "in all that they have said"),
    ],
    18: [
        ("נָבִיא", "ואי נבי", "And whatever prophet"),
        ("אָקִים לָהֶם", "אנצבה להם", "I appoint for them"),
        ("מִקֶּרֶב אֲחֵיהֶם", "מן בעץ' אכ'ותהם", "from some of their brothers"),
        ("כָּמוֹךָ", "מת'לך", "like you"),
        ("וְנָתַתִּי דְבָרַי בְּפִיו", "אלקנה כלאמי", "I shall teach him My word"),
        ("וְדִבֶּר אֲלֵיהֶם", "פיכ'אטבהם", "and he shall address them"),
        ("אֵת כָּל-אֲשֶׁר אֲצַוֶּנּוּ", "בגמיע מא אמרה בה", "with all that I command him"),
    ],
    19: [
        ("וְהָיָה הָאִישׁ", "ואי אנסאן", "And whatever person"),
        ("אֲשֶׁר לֹא-יִשְׁמַע", "לם יקבל", "does not accept"),
        ("אֶל-דְּבָרַי", "כלאמי", "My word"),
        ("אֲשֶׁר יְדַבֵּר בִּשְׁמִי", "אלד'י י'ודי עני", "which he conveys on My behalf"),
        ("אָנֹכִי אֶדְרֹשׁ מֵעִמּוֹ", "פאני אטאלבה", "I shall call him to account"),
    ],
    20: [
        ("אַךְ הַנָּבִיא", "ואי מתנבי", "But whatever false prophet"),
        ("אֲשֶׁר יָזִיד לְדַבֵּר", "תווקח פתקוול", "has been brazen and has fabricated"),
        ("דָּבָר בִּשְׁמִי", "קולא עני", "a saying on My behalf"),
        ("אֵת אֲשֶׁר לֹא-צִוִּיתִיו לְדַבֵּר", "מא לם אמרה אן יקולה", "what I have not commanded him to say"),
        ("וַאֲשֶׁר יְדַבֵּר בְּשֵׁם אֱלֹהִים אֲחֵרִים", "ומן יתנבא למעבודאת אכ'ר", "and whoever prophesies in the name of other objects of worship"),
        ("וּמֵת הַנָּבִיא הַהוּא", "פליקתל ד'אלך אלמתנבי", "that false prophet shall be put to death"),
    ],
    21: [
        ("וְכִי תֹאמַר", "ואן קלת", "And if you say"),
        ("בִּלְבָבֶךָ", "פי נפסך", "to yourself"),
        ("אֵיכָה נֵדַע", "כיף נעלם", "How shall we know"),
        ("אֶת-הַדָּבָר", "אלקול", "the saying"),
        ("אֲשֶׁר לֹא-דִבְּרוֹ יְהוָה", "אלד'י לם יקולה אללה", "which God has not spoken"),
    ],
    22: [
        (None, "פאנה", "Then:"),
        ("אֲשֶׁר יְדַבֵּר הַנָּבִיא", "מא יקולה אלמתנבי", "that which the false prophet speaks"),
        ("בְּשֵׁם יְהוָה", "ען אללה", "in the name of God"),
        ("וְלֹא-יִהְיֶה הַדָּבָר", "ולא יגוז ד'אלך אלקול", "if that saying neither comes to pass"),
        ("וְלֹא יָבֹא", "ולא יגב", "nor proves necessary"),
        ("הוּא הַדָּבָר אֲשֶׁר לֹא-דִבְּרוֹ יְהוָה", "פהו אלקול אלד'י לם יקולה אללה", "it is the saying which God has not spoken"),
        ("בְּזָדוֹן דִּבְּרוֹ הַנָּבִיא", "ואנמא קאלה אלמתנבי בקחה", "the false prophet has said it out of brazenness"),
        ("לֹא תָגוּר מִמֶּנּוּ", "פלא תחד'רה", "Do not be wary of him"),
    ],
}
