"""Hand-authored alignment triples for Devarim chapter 9.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the "not for your righteousness" discourse, the Anakim,
the stiff-necked people (עַם-קְשֵׁה-עֹרֶף), the golden calf at Horeb, Moses'
two forty-day fasts, and his intercession — aligned with particular care for
the recurring "provoke / anger / stiff-necked / defying" vocabulary.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("שְׁמַע", "אעלם", "Know"),
        ("יִשְׂרָאֵל", "יא אסראיל", "O Israel"),
        (None, "אנך", "that you are"),
        ("עֹבֵר", "גאיז", "crossing"),
        ("הַיּוֹם", "פי הד'א אלמרה", "this day"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("לָבֹא", "לתדכל", "to enter"),
        ("לָרֶשֶׁת", "ותחוז", "and possess"),
        ("גּוֹיִם", "אממא", "nations"),
        ("גְּדֹלִים", "אכ'תר", "more numerous"),
        ("וַעֲצֻמִים", "וא עצ'ם", "and stronger"),
        ("מִמֶּךָּ", "מנך", "than you"),
        ("עָרִים גְּדֹלֹת", "פי קרא כבירה", "in great"),
        ("וּבְצֻרֹת", "חצינה", "fortified towns"),
        ("בַּשָּׁמָיִם", "תדאני אלסמא", "that reach close to the sky"),
    ],
    2: [
        ("עַם-גָּדוֹל", "קום כביר", "A great"),
        ("וָרָם", "רפיע", "and tall people"),
        ("בְּנֵי עֲנָקִים", "בני אלגבאברה", "sons of the mighty"),
        ("אֲשֶׁר אַתָּה יָדַעְתָּ", "כמא עלמת", "as you have known"),
        ("וְאַתָּה שָׁמַעְתָּ", "וסמעת", "and heard"),
        ("מִי יִתְיַצֵּב", "מן ד'א יקום", "who can stand"),
        ("לִפְנֵי בְּנֵי עֲנָק", "בין ידי אלגבאברה", "before the mighty"),
    ],
    3: [
        ("וְיָדַעְתָּ", "ואעלם", "And know"),
        ("הַיּוֹם", "מן אליום", "from this day"),
        ("כִּי", "אן", "that"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        (None, "נורה", "His light"),
        ("הוּא-הָעֹבֵר", "גאיז", "passes"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("אֵשׁ אֹכְלָה", "כנאר אכאלה", "like a consuming fire"),
        ("הוּא יַשְׁמִידֵם", "הו ינפדהם", "He shall destroy them"),
        ("וְהוּא יַכְנִיעֵם", "ויהזמהם", "and rout them"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("וְהוֹרַשְׁתָּם", "פתקרצ'הם", "and you shall dispossess them"),
        ("וְהַאֲבַדְתָּם", "ותבידהם", "and annihilate them"),
        ("מַהֵר", "סריעא", "swiftly"),
        ("כַּאֲשֶׁר דִּבֶּר", "כמא ועדך", "as"),
        ("יְהוָה", "אללה", "God has promised you"),
    ],
    4: [
        ("אַל-תֹּאמַר", "ולא תקול", "And do not say"),
        ("בִּלְבָבְךָ", "פי נפסך", "in your heart"),
        ("בַּהֲדֹף", "אד'א דפעהם", "when"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord has driven them out"),
        ("אֹתָם", "מן בין ידיך", "from before you"),
        ("לֵאמֹר", "אד'", "It is"),
        ("בְּצִדְקָתִי", "בצלאחי", "because of my righteousness"),
        ("הֱבִיאַנִי", "אדכ'לני", "that"),
        ("יְהוָה", "אללה", "God has brought me in"),
        ("לָרֶשֶׁת", "אחוז", "to possess"),
        ("אֶת-הָאָרֶץ הַזֹּאת", "הד'א אלבלד", "this land"),
        ("וּבְרִשְׁעַת", "ובצ'לם", "'because of the wickedness"),
        ("הַגּוֹיִם הָאֵלֶּה", "אולאיך אלאמם", "of those nations"),
        ("יְהוָה", "אללה", "God"),
        ("מוֹרִישָׁם", "קארצ'הם", "has dispossessed them"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
    ],
    5: [
        ("לֹא", "בל ליס", "Rather, it is not"),
        ("בְצִדְקָתְךָ", "בצלאחך", "by your righteousness"),
        ("וּבְיֹשֶׁר לְבָבְךָ", "וצחה' קלבך", "nor the soundness of your heart"),
        (None, "פקט", "alone"),
        ("אַתָּה בָא", "אנת צאיר", "that you are going"),
        ("לָרֶשֶׁת", "לתחוז", "to possess"),
        ("אֶת-אַרְצָם", "בלדהם", "their land"),
        (None, "לכן", "but rather"),
        ("כִּי בְּרִשְׁעַת", "מע צ'לם", "together with the wickedness"),
        ("הַגּוֹיִם הָאֵלֶּה", "אולאיך אלאמם", "of those nations"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        ("מוֹרִישָׁם", "קארצ'הם", "is dispossessing them"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
        ("וּלְמַעַן הָקִים", "ולכי יאפי", "and so that He may fulfil"),
        ("אֶת-הַדָּבָר", "באלקול", "the word"),
        ("אֲשֶׁר נִשְׁבַּע", "אלד'י קאלה", "which He spoke"),
        ("יְהוָה", "לאבאיך", "to your fathers"),
        ("לַאֲבֹתֶיךָ", "אברהים", "Abraham"),
        ("לְאַבְרָהָם", "ויצחק", "and Isaac"),
        ("לְיִצְחָק וּלְיַעֲקֹב", "ויעקוב", "and Jacob"),
    ],
    6: [
        (None, "פתיקן", "Know, then"),
        ("כִּי לֹא", "אנה ליס", "that it is not"),
        ("בְצִדְקָתְךָ", "בצלאחך", "by your righteousness"),
        ("יְהוָה", "אללה", "that the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("אֶת-הָאָרֶץ הַטּוֹבָה הַזֹּאת", "הד'א אלבלד אלגייד", "this good land"),
        ("לְרִשְׁתָּהּ", "לתחוזוה", "to possess it"),
        ("כִּי עַם-קְשֵׁה-עֹרֶף אָתָּה", "אד' אנת שעב צעב אלרקאב", "for you are a stiff-necked people"),
    ],
    7: [
        ("זְכֹר", "פאדכר", "Remember"),
        ("אַל-תִּשְׁכַּח", "ולא תנסא", "and do not forget"),
        ("אֵת אֲשֶׁר-הִקְצַפְתָּ", "מא אסכ'טת", "how you provoked"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
        ("לְמִן-הַיּוֹם", "מן יום", "from the day"),
        ("אֲשֶׁר-יָצָאתָ", "כ'רגת", "you went out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן מצר", "of Egypt"),
        ("עַד-בֹּאֲכֶם", "ואלי' אן גיתם", "until you came"),
        ("עַד-הַמָּקוֹם הַזֶּה", "אלי' הד'א אלמוצ'ע", "to this place"),
        ("מַמְרִים הֱיִיתֶם", "לם תזאלו מכ'אלפין", "you have not ceased defying"),
        ("עִם-יְהוָה", "ללה", "God"),
    ],
    8: [
        ("וּבְחֹרֵב", "ופי חריב", "And at Horeb"),
        ("הִקְצַפְתֶּם", "אסכ'טתם", "you provoked"),
        ("אֶת-יְהוָה", "אללה", "God"),
        ("וַיִּתְאַנַּף יְהוָה", "פג'צ'ב אללה", "and God was greatly angered"),
        ("בָּכֶם", "עליכם", "with you"),
        ("לְהַשְׁמִיד אֶתְכֶם", "וכאד אן ינפד'כם", "and came near to destroying you"),
    ],
    9: [
        ("בַּעֲלֹתִי", "חין צעדת", "When I went up"),
        ("הָהָרָה", "אלגבל", "the mountain"),
        ("לָקַחַת", "לאכ'ד'", "to receive"),
        ("לוּחֹת הָאֲבָנִים", "לוחי אלגוהר", "the two tablets of gems"),
        ("לוּחֹת הַבְּרִית", "לוחי אלשהאדה", "the tablets of the testimony"),
        ("אֲשֶׁר-כָּרַת", "אלד'י עהדהא", "which"),
        ("יְהוָה", "אללה", "God had covenanted"),
        ("עִמָּכֶם", "מעכם", "with you"),
        ("וָאֵשֵׁב בָּהָר", "פאקמת פיה", "I stayed there"),
        ("אַרְבָּעִים יוֹם", "ארבעין יומא", "forty days"),
        ("וְאַרְבָּעִים לַיְלָה", "וארבעין לילה", "and forty nights"),
        ("לֶחֶם לֹא אָכַלְתִּי", "לם אכל טעאמא", "I ate no food"),
        ("וּמַיִם לֹא שָׁתִיתִי", "ולם אשרב מאא", "and drank no water"),
    ],
    10: [
        ("וַיִּתֵּן יְהוָה", "אלי' אן דפע אללה", "Until God delivered"),
        ("אֵלַי", "אליי", "to me"),
        ("אֶת-שְׁנֵי לוּחֹת הָאֲבָנִים", "לוחי אלגוהר", "the two tablets of gems"),
        ("כְּתֻבִים", "אלמכתובין", "written"),
        ("בְּאֶצְבַּע אֱלֹהִים", "בקדרה' אללה", "by the power of God"),
        ("וַעֲלֵיהֶם", "ועליהמא", "and upon them"),
        ("כְּכָל-הַדְּבָרִים", "מת'ל גמיע אלכלמאת", "the like of all the words"),
        ("אֲשֶׁר דִּבֶּר", "אלד'י כלמכם", "which"),
        ("יְהוָה", "אללה", "God had spoken"),
        ("עִמָּכֶם", "בהא", "to you"),
        ("בָּהָר", "פי אלגבל", "on the mountain"),
        ("מִתּוֹךְ הָאֵשׁ", "מן וסט אלנאר", "from the midst of the fire"),
        ("בְּיוֹם הַקָּהָל", "פי יום אלגוק", "on the day of the assembly"),
    ],
    11: [
        ("וַיְהִי מִקֵּץ", "וכאן ד'אלך בעד", "And it was after"),
        ("אַרְבָּעִים יוֹם", "ארבעין יומא", "forty days"),
        ("וְאַרְבָּעִים לָיְלָה", "וארבעין לילה", "and forty nights"),
        ("נָתַן יְהוָה אֵלַי", "דפעהמא אליי", "that He delivered them to me"),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה", "פקאל אללה", "And God said"),
        ("אֵלַי", "לי", "to me"),
        ("קוּם", "קום", "Arise"),
        ("רֵד", "אנחדר", "go down"),
        ("מַהֵר", "סריעא", "quickly"),
        ("מִזֶּה", "מן ההנא", "from here"),
        ("כִּי", "לאן", "for"),
        ("שִׁחֵת עַמְּךָ", "קומך קד אפסד", "your people"),
        ("אֲשֶׁר הוֹצֵאתָ", "אלד'י אכ'רגתהם", "whom you brought out"),
        ("מִמִּצְרָיִם", "מן מצר", "of Egypt have become corrupt"),
        ("סָרוּ", "זאלו", "they have turned aside"),
        ("מַהֵר", "סריעא", "quickly"),
        ("מִן-הַדֶּרֶךְ", "ען אלטריק", "from the way"),
        ("אֲשֶׁר צִוִּיתִם", "אלד'י אמרתהם", "which I commanded them"),
        ("עָשׂוּ לָהֶם מַסֵּכָה", "וצנעו להם מסבוכא", "and have made for themselves a molten image"),
    ],
    13: [
        (None, "ת'ם", "Then"),
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("יְהוָה אֵלַי", "לי", "to me"),
        ("רָאִיתִי", "עלמת", "I have known"),
        ("אֶת-הָעָם הַזֶּה", "הולאי אלקום", "that these people"),
        ("עַם-קְשֵׁה-עֹרֶף הוּא", "אנהם צעאב אלרקאב", "are stiff-necked"),
    ],
    14: [
        ("הֶרֶף מִמֶּנִּי", "ואן כפאת ען אלתשפע פיהם", "And if you hold back from interceding for them"),
        ("וְאַשְׁמִידֵם", "אנפד'תהם", "I shall destroy them"),
        ("וְאֶמְחֶה", "ומחית", "and blot out"),
        ("אֶת-שְׁמָם", "אסמאיהם", "their names"),
        ("מִתַּחַת הַשָּׁמָיִם", "מן תחת אלסמא", "from beneath the sky"),
        ("וְאֶעֱשֶׂה אוֹתְךָ לְגוֹי-עָצוּם וָרָב", "וגעלת מנך אמה", "and make of you a nation"),
        ("מִמֶּנּוּ", "אכת'ר וא עצ'ם מנהם", "more numerous and stronger than they"),
    ],
    15: [
        ("וָאֵפֶן", "פולית", "So I turned"),
        ("וָאֵרֵד", "ונזלת", "and came down"),
        ("מִן-הָהָר", "מן אלגבל", "from the mountain"),
        ("וְהָהָר בֹּעֵר", "והו משתעל", "while it was ablaze"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
        ("וּשְׁנֵי לוּחֹת הַבְּרִית", "ולוחי אלשהאדה", "and the two tablets of testimony"),
        ("עַל שְׁתֵּי יָדָי", "עלי' ידיי", "were in my hands"),
    ],
    16: [
        ("וָאֵרֶא", "פנצ'רת", "And I looked"),
        ("וְהִנֵּה", "ואד'א", "and behold"),
        ("חֲטָאתֶם", "בכם קד אכ'טאתם", "you had sinned"),
        ("לַיהוָה אֱלֹהֵיכֶם", "ללה רבכם", "against the Lord your God"),
        ("עֲשִׂיתֶם לָכֶם", "ואתכ'ד'תם", "you had taken for yourselves"),
        ("עֵגֶל מַסֵּכָה", "עגלא מסבוכא", "a molten calf"),
        ("סַרְתֶּם", "וזלתם", "and had turned aside"),
        ("מַהֵר", "סריעא", "quickly"),
        ("מִן-הַדֶּרֶךְ", "ען אלטריק", "from the way"),
        ("אֲשֶׁר-צִוָּה יְהוָה אֶתְכֶם", "אלד'י אמרכם", "He had commanded you"),
    ],
    17: [
        ("וָאֶתְפֹּשׂ", "וצ'בטת", "And I seized"),
        ("בִּשְׁנֵי הַלֻּחֹת", "אללוחין", "the two tablets"),
        ("וָאַשְׁלִכֵם", "וטרחתהמא", "and threw them"),
        ("מֵעַל שְׁתֵּי יָדָי", "ען ידיי", "from my hands"),
        ("וָאֲשַׁבְּרֵם", "וכסרתהמא", "and broke them"),
        ("לְעֵינֵיכֶם", "בחצ'רתכם", "before your eyes"),
    ],
    18: [
        ("וָאֶתְנַפַּל", "פשפעת", "And I interceded"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("כָּרִאשֹׁנָה", "כאלמרה אלאולא", "as the first time"),
        ("אַרְבָּעִים יוֹם", "ארבעין יום", "forty days"),
        ("וְאַרְבָּעִים לַיְלָה", "וארבעין לילה", "and forty nights"),
        ("לֶחֶם לֹא אָכַלְתִּי", "לם אכל טעאמא", "I ate no food"),
        ("וּמַיִם לֹא שָׁתִיתִי", "ולם אשרב מאא", "and I drank no water"),
        ("עַל כָּל-חַטַּאתְכֶם", "בסבב כטייתכם", "on account of your sin"),
        ("אֲשֶׁר חֲטָאתֶם", "אלד'י אכ'טאתם", "which you had committed"),
        ("לַעֲשׂוֹת הָרַע", "וצנעתם אלשר", "you had done evil"),
        ("בְּעֵינֵי יְהוָה", "בין ידי אללה", "before God"),
        ("לְהַכְעִיסוֹ", "ואסכ'טתמוה", "and provoked Him"),
    ],
    19: [
        ("כִּי יָגֹרְתִּי", "לאני חד'רת", "For I feared"),
        ("מִפְּנֵי הָאַף", "אלג'צ'ב", "the anger"),
        ("וְהַחֵמָה", "ואלחמייה", "and the fury"),
        ("אֲשֶׁר קָצַף", "אלד'י סכ'ט", "with which"),
        ("יְהוָה", "אללה", "God was wrathful"),
        ("עֲלֵיכֶם", "עליכם", "against you"),
        ("לְהַשְׁמִיד אֶתְכֶם", "לינפדכם", "to destroy you"),
        ("וַיִּשְׁמַע יְהוָה", "פסמע אללה", "and God heeded"),
        ("אֵלַי", "לי", "me"),
        ("גַּם בַּפַּעַם הַהִוא", "פי ד'אלך אלוקת", "at that time"),
    ],
    20: [
        ("וּבְאַהֲרֹן", "ועלי' הרון", "And against Aaron"),
        ("הִתְאַנַּף יְהוָה מְאֹד", "וגד אללה גדא", "God was greatly angered"),
        ("לְהַשְׁמִידוֹ", "וכאד אן ינפדה", "coming near to destroying him"),
        ("וָאֶתְפַּלֵּל", "פאסתג'פרת", "and I sought forgiveness"),
        ("גַּם-בְּעַד אַהֲרֹן", "לה איצ'א", "for him also"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
    ],
    21: [
        ("וְאֶת-חַטַּאתְכֶם", "ואמא כ'טייתכם", "And as for your sin"),
        ("אֲשֶׁר-עֲשִׂיתֶם", "אלד'י אתכ'ד'תמוה", "which you had made"),
        ("אֶת-הָעֵגֶל", "והו אלעגל", "that is, the calf"),
        ("לָקַחְתִּי", "פאני אכ'דתה", "I took it"),
        ("וָאֶשְׂרֹף אֹתוֹ בָּאֵשׁ", "ואחרקתה באלנאר", "and burned it with fire"),
        ("וָאֶכֹּת אֹתוֹ טָחוֹן הֵיטֵב", "וברדתה באלמברד נעמא", "and ground it fine"),
        ("עַד אֲשֶׁר-דַּק לְעָפָר", "חתי דק כאלתראב", "until it was ground to dust"),
        ("וָאַשְׁלִךְ אֶת-עֲפָרוֹ", "וטרחת תראבה", "and I cast its dust"),
        ("אֶל-הַנַּחַל", "פי ואד אלמא", "into the stream of water"),
        ("הַיֹּרֵד מִן-הָהָר", "אלמנחדר מן אלגבל", "that flows down from the mountain"),
    ],
    22: [
        ("וּבְתַבְעֵרָה", "ופי דאת אלאשתעאל", "And at the Place of Burning"),
        ("וּבְמַסָּה", "וד'את אלמחנה", "and at the Place of Trial"),
        ("וּבְקִבְרֹת הַתַּאֲוָה", "וקבור אלמתשהיין", "and at the Graves of the Craving"),
        ("מַקְצִפִים הֱיִיתֶם", "לם תזאלו מסכ'טין", "you were continually provoking"),
        ("אֶת-יְהוָה", "ללה", "God"),
    ],
    23: [
        ("וּבִשְׁלֹחַ יְהוָה", "ולמא בעת' אללה", "And when God sent"),
        ("אֶתְכֶם", "בעצ'כם", "some of you"),
        ("מִקָּדֵשׁ בַּרְנֵעַ", "מן רקים ברנע", "from Kadesh-barnea"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("עֲלוּ", "אצעדו", "Go up"),
        ("וּרְשׁוּ", "וחוזו", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר נָתַתִּי לָכֶם", "אלד'י אעטיתכם", "which I have given you"),
        ("וַתַּמְרוּ", "פכ'אלפתם", "you defied"),
        ("אֶת-פִּי יְהוָה", "אמר אללה", "the command of the Lord"),
        ("אֱלֹהֵיכֶם", "רבכם", "your God"),
        ("וְלֹא הֶאֱמַנְתֶּם לוֹ", "ולם תומנו בה", "and did not believe in Him"),
        ("וְלֹא שְׁמַעְתֶּם בְּקֹלוֹ", "ולם תקבלו אמרה", "and did not accept His command"),
    ],
    24: [
        (None, "ובאלגמלה", "And in sum"),
        ("מַמְרִים הֱיִיתֶם", "לם תזאלו מכ'אלפין", "you have not ceased defying"),
        ("עִם-יְהוָה", "ללה", "God"),
        ("מִיּוֹם דַּעְתִּי אֶתְכֶם", "מן יום ערפתכם", "from the day I have known you"),
    ],
    25: [
        ("וָאֶתְנַפַּל", "פשפעת", "And I interceded"),
        (None, "ענדה", "before Him"),
        ("אֵת אַרְבָּעִים הַיּוֹם", "תלך אלארבעין אליום", "those forty days"),
        ("וְאֶת-אַרְבָּעִים הַלַּיְלָה", "ואלארבעין אללילה", "and forty nights"),
        ("אֲשֶׁר הִתְנַפָּלְתִּי", "אד'", "since"),
        ("כִּי-אָמַר יְהוָה לְהַשְׁמִיד אֶתְכֶם", "אראד אללה אן ינפד'כם", "God had willed to destroy you"),
    ],
    26: [
        ("וָאֶתְפַּלֵּל", "צלית", "I prayed"),
        ("אֶל-יְהוָה", "בין ידי אללה", "before God"),
        ("וָאֹמַר", "וקלת", "and said"),
        ("אֲדֹנָי יְהוִה", "אללהם יא רבי", "O God, my Lord"),
        ("אַל-תַּשְׁחֵת", "לא תהלך", "Do not destroy"),
        ("עַמְּךָ", "קומך", "Your people"),
        ("וְנַחֲלָתְךָ", "וצפותך", "and Your chosen ones"),
        ("אֲשֶׁר פָּדִיתָ", "אלד'ין פככתהם", "whom You redeemed"),
        ("בְּגָדְלֶךָ", "בעצ'מתך", "by Your greatness"),
        ("אֲשֶׁר-הוֹצֵאתָ", "ואכ'רגתהם", "and brought out"),
        ("מִמִּצְרַיִם", "מן מצר", "of Egypt"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a mighty hand"),
    ],
    27: [
        ("זְכֹר", "אד'כר", "Remember"),
        ("לַעֲבָדֶיךָ", "אוליאך", "Your devoted ones"),
        ("לְאַבְרָהָם", "אברהים", "Abraham"),
        ("לְיִצְחָק", "ויצחק", "Isaac"),
        ("וּלְיַעֲקֹב", "ויעקוב", "and Jacob"),
        ("אַל-תֵּפֶן", "לא תנצ'ר", "do not look upon"),
        ("אֶל-קְשִׁי הָעָם הַזֶּה", "אלי' צעובה' הד'א אלשעב", "the hardness of this people"),
        ("וְאֶל-רִשְׁעוֹ", "וטלאחה", "nor their wickedness"),
        ("וְאֶל-חַטָּאתוֹ", "וכ'טייתה", "and their sin"),
    ],
    28: [
        ("פֶּן-יֹאמְרוּ", "כלא יקול", "Lest"),
        ("הָאָרֶץ", "אהל אלבלד", "the people of the land"),
        ("אֲשֶׁר הוֹצֵאתָנוּ מִשָּׁם", "אלד'י אכ'רגתנא מנה", "from which You brought us out should say"),
        ("מִבְּלִי יְכֹלֶת יְהוָה", "ממא לם יטיק רבהם", "because their Lord was unable"),
        ("לַהֲבִיאָם", "אן יד'כלהם", "to bring them into"),
        ("אֶל-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-דִּבֶּר לָהֶם", "אלד'י ועדהם בה", "which He promised them"),
        ("וּמִשִּׂנְאָתוֹ אוֹתָם", "ומן שנאתה להם", "and out of His hatred of them"),
        ("הוֹצִיאָם", "אכ'רגהם", "He brought them out"),
        ("לַהֲמִתָם", "ליקתלהם", "to slay them"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
    ],
    29: [
        ("וְהֵם", "והם", "For they are"),
        ("עַמְּךָ", "קומך", "Your people"),
        ("וְנַחֲלָתֶךָ", "וצפותך", "and Your chosen ones"),
        ("אֲשֶׁר הוֹצֵאתָ", "אלד'י אכ'רגתהם", "whom You brought out"),
        ("בְּכֹחֲךָ הַגָּדֹל", "בקוותך אל]עט'ימה] עצ'ימה", "by Your great power"),
        ("וּבִזְרֹעֲךָ הַנְּטוּיָה", "וד'ראעך אלממדודה", "and Your outstretched arm"),
    ],
}
