"""Hand-authored alignment triples for Devarim chapter 21.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the broken-necked heifer (eglah arufah), the captive
woman, the firstborn's double portion, the rebellious son (ben sorer u-moreh),
and the law of the hanged body — aligned with particular care for the
ritual-legal and narrative vocabulary throughout.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("כִּי-יִמָּצֵא חָלָל", "ואן וגד קתיל", "And if a slain man be found"),
        ("בָּאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("לְרִשְׁתָּהּ", "לתחוזה", "to take possession of"),
        ("נֹפֵל", "מטרוח", "lying"),
        ("בַּשָּׂדֶה", "פי אלצחרא", "in the open country"),
        ("לֹא נוֹדַע", "לם יערף", "and it is not known"),
        ("מִי הִכָּהוּ", "מן קתלה", "who killed him"),
    ],
    2: [
        ("וְיָצְאוּ", "פליכ'רג", "then"),
        ("זְקֵנֶיךָ", "בעץ' שיוכ'ך", "some of your elders"),
        ("וְשֹׁפְטֶיךָ", "וחכאמך", "and your judges"),
        ("וּמָדְדוּ", "וימסחון", "shall go out and measure"),
        ("אֶל-הֶעָרִים", "אלי' אלקרא", "toward the towns"),
        ("אֲשֶׁר סְבִיבֹת הֶחָלָל", "אלדין חואלי אלקתיל", "that are around the slain man"),
    ],
    3: [
        ("וְהָיָה הָעִיר הַקְּרֹבָה", "פאייה' קריה כאנת אלאקרב", "and whichever town is nearest"),
        ("אֶל-הֶחָלָל", "אליה", "to him"),
        ("וְלָקְחוּ זִקְנֵי", "פליאכ'ד' אהלהא", "the people of that town shall take"),
        ("עֶגְלַת בָּקָר", "עגלה מן אלבקר", "a heifer from the cattle"),
        ("אֲשֶׁר לֹא-עֻבַּד בָּהּ", "מא לם תפלח", "one that has not been worked"),
        ("אֲשֶׁר לֹא-מָשְׁכָה בְּעֹל", "ולא תמד אלניר", "and has not drawn a yoke"),
    ],
    4: [
        ("וְהוֹרִדוּ", "ויחדרונהא", "and they shall bring it down"),
        ("אֶל-נַחַל אֵיתָן", "אלי' ואד צעב", "to a rugged valley"),
        ("אֲשֶׁר לֹא-יֵעָבֵד בּוֹ", "מא לם יפלח", "that has neither been tilled"),
        ("וְלֹא יִזָּרֵעַ", "ולא יזרע", "nor sown"),
        ("וְעָרְפוּ-שָׁם אֶת-הָעֶגְלָה בַּנָּחַל", "ויקפוהא פיה", "and shall break its neck there"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        ("וְנִגְּשׁוּ הַכֹּהֲנִים", "יתקדם בעץ' אלאימה", "some of the imāms"),
        ("בְּנֵי לֵוִי", "בני לוי", "the sons of Levi, shall come forward"),
        ("כִּי בָם בָּחַר", "לאן אללה רבך אכ'תארהם", "for God your Lord has chosen them"),
        ("לְשָׁרְתוֹ", "ליכ'דמוה", "to serve Him"),
        ("וּלְבָרֵךְ בְּשֵׁם יְהוָה", "ויבארכו באסמה", "and to bestow blessing in His name"),
        ("וְעַל-פִּיהֶם יִהְיֶה", "ועלי' קולהם יפצל", "and by their word shall"),
        ("כָּל-רִיב", "כל כ'צומה", "every dispute"),
        ("וְכָל-נָגַע", "וכל בלא", "and every affliction be decided"),
    ],
    6: [
        ("וְכֹל זִקְנֵי הָעִיר הַהִוא", "פאד'א ג'סל גמיע שיוך' תלך אלקריה", "And when all the elders of that town"),
        ("הַקְּרֹבִים אֶל-הֶחָלָל", "אלקריבה מן אלקתיל", "nearest to the slain man"),
        ("יִרְחֲצוּ אֶת-יְדֵיהֶם", "אידיהם", "have washed their hands"),
        ("עַל-הָעֶגְלָה הָעֲרוּפָה", "עלי' אלעגלה אלמקפאה", "over the heifer whose neck was broken"),
        ("בַנָּחַל", "פי אלואד", "in the valley"),
    ],
    7: [
        ("וְעָנוּ וְאָמְרוּ", "ויבתדו ויקולו", "they shall begin and say"),
        ("יָדֵינוּ", "אידינא", "Our hands"),
        ("לֹא שפכה (שָׁפְכוּ)", "לם תספך", "did not shed"),
        ("אֶת-הַדָּם הַזֶּה", "הד'א אלדם", "this blood"),
        ("וְעֵינֵינוּ לֹא רָאוּ", "ועיוננא לם תרא ד'אלך", "and our eyes did not see that"),
    ],
    8: [
        (None, "ת'נוהם וקאלו", "And they shall respond to them and say"),
        ("כַּפֵּר", "אללהם אג'פר", "O God, forgive"),
        ("לְעַמְּךָ יִשְׂרָאֵל", "לקומך אל אסראיל", "Your people, the house of Israel"),
        ("אֲשֶׁר-פָּדִיתָ", "אלד'י פככתהם", "whom You redeemed"),
        ("וְאַל-תִּתֵּן", "ולא תדע", "and do not place"),
        ("דָּם נָקִי", "עקובה' תואני פי דם ברי", "the punishment of negligence in the blood of one innocent of guilt"),
        ("בְּקֶרֶב עַמְּךָ יִשְׂרָאֵל", "עליהם", "upon them"),
        ("וְנִכַּפֵּר לָהֶם הַדָּם", "פיג'פר להם מא תואנו פי. ד'אלך אלדם", "and so they shall be forgiven for what they were negligent in concerning that blood"),
    ],
    9: [
        ("וְאַתָּה", "ואנת", "And you"),
        ("תְּבַעֵר הַדָּם הַנָּקִי", "פאנף קאתל אלברי", "banish the killer of the innocent"),
        ("מִקִּרְבֶּךָ", "מן בינכם", "from your midst"),
        ("כִּי-תַעֲשֶׂה", "אד' תצנע", "for you are doing"),
        ("הַיָּשָׁר", "אלמסתקים", "what is right"),
        ("בְּעֵינֵי יְהוָה", "ענד אללה", "before God"),
    ],
    10: [
        ("כִּי-תֵצֵא", "ואדי' כ'רגת", "And when you go out"),
        ("לַמִּלְחָמָה", "לאלחרב", "to war"),
        ("עַל-אֹיְבֶיךָ", "עלי' אעדאיך", "against your enemies"),
        ("וּנְתָנוֹ יְהוָה אֱלֹהֶיךָ", "פאסלמה אללה רבך", "and God your Lord delivers them"),
        ("בְּיָדֶךָ", "פי ידך", "into your hand"),
        ("וְשָׁבִיתָ שִׁבְיוֹ", "וסבית סביה", "and you take captives"),
    ],
    11: [
        ("וְרָאִיתָ", "וראית", "and you see"),
        ("בַּשִּׁבְיָה", "פי אלסבי", "among the captives"),
        ("אֵשֶׁת יְפַת-תֹּאַר", "אמראה חסנה' אלחלייה", "a woman fair of appearance"),
        ("וְחָשַׁקְתָּ בָהּ", "פשעפת בהא", "and your heart is captivated by her"),
        ("וְלָקַחְתָּ לְךָ לְאִשָּׁה", "ואתכ'ד'תהא לך זוגה", "and you take her for yourself as a wife"),
    ],
    12: [
        ("וַהֲבֵאתָהּ", "באן תדכ'להא", "it shall be by your bringing her"),
        ("אֶל-תּוֹךְ בֵּיתֶךָ", "אלי וסט מנזלך", "into your home"),
        ("וְגִלְּחָה אֶת-רֹאשָׁהּ", "ותחלק ראסהא", "and she shall shave her head"),
        ("וְעָשְׂתָה אֶת-צִפָּרְנֶיהָ", "ותרבי אצ'פארהא", "and let her nails grow"),
    ],
    13: [
        ("וְהֵסִירָה אֶת-שִׂמְלַת שִׁבְיָהּ", "ותנזע ת'יאב סביהא", "and she shall remove her captive's garments"),
        ("מֵעָלֶיהָ", "ענהא", "from upon her"),
        ("וְיָשְׁבָה בְּבֵיתֶךָ", "ותקים כד'אך פי מנזלך", "and shall remain thus in your home"),
        ("וּבָכְתָה", "ותבכי", "and weep"),
        ("אֶת-אָבִיהָ וְאֶת-אִמָּהּ", "עלי' מד'הב אביהא ואמהא", "for the departure of her father and her mother"),
        ("יֶרַח יָמִים", "שהרא", "a full month"),
        (None, "ובעד ד'אלך", "and after that"),
        ("וְאַחַר כֵּן תָּבוֹא אֵלֶיהָ", "תדכ'ל אליהא", "you shall go in to her"),
        ("וּבְעַלְתָּהּ", "פתבן בהא", "and be wed to her"),
        ("וְהָיְתָה לְךָ לְאִשָּׁה", "ותכון לך זוגה", "and she shall be your wife"),
    ],
    14: [
        ("וְהָיָה אִם-לֹא חָפַצְתָּ בָּהּ", "ואן לם תרידהא", "And if you do not desire her"),
        (None, "בעד ד'אלך", "after that"),
        ("וְשִׁלַּחְתָּהּ לְנַפְשָׁהּ", "פאטלקהא חרא לנפסהא", "then release her free for herself"),
        ("וּמָכֹר לֹא-תִמְכְּרֶנָּה", "וביעא לא תביעהא", "you shall not sell her"),
        ("בַּכָּסֶף", "בת'מן", "for a price"),
        ("לֹא-תִתְעַמֵּר בָּהּ", "לא תסתרקהא", "you shall not enslave her"),
        ("תַּחַת אֲשֶׁר עִנִּיתָהּ", "בעד מא אתיתהא", "after you have been intimate with her"),
    ],
    15: [
        ("כִּי-תִהְיֶיןָ לְאִישׁ שְׁתֵּי נָשִׁים", "ואן כאנת זוגתין לרגל ואחד", "And if a man has two wives"),
        ("הָאַחַת אֲהוּבָה", "אחדהמא מחבובה", "one beloved"),
        ("וְהָאַחַת שְׂנוּאָה", "ואלאכ'רא משנייה", "and the other disfavored"),
        ("וְיָלְדוּ-לוֹ בָנִים", "פולדא לה בנין", "and both have borne him sons"),
        ("הָאֲהוּבָה", "אלמחבובה", "the beloved"),
        ("וְהַשְּׂנוּאָה", "ואלמשנייה", "and the disfavored"),
        ("וְהָיָה הַבֵּן הַבְּכֹר לַשְּׂנִיאָה", "וכאן אלאבן אלבכר לאלמשנייה מנהמא", "and the firstborn son belongs to the disfavored of them"),
    ],
    16: [
        ("וְהָיָה בְּיוֹם הַנְחִילוֹ", "פפי יום ינחל", "then on the day he bequeaths"),
        ("אֶת-בָּנָיו", "בניה", "to his sons"),
        ("אֵת אֲשֶׁר-יִהְיֶה לוֹ", "מא יכון לה", "what belongs to him"),
        ("לֹא יוּכַל לְבַכֵּר", "פלא יגוז לה", "it is not permitted for him"),
        ("אֶת-בֶּן-הָאֲהוּבָה", "אן יפצ'ל אבן אלמחבובה", "to give preference to the son of the beloved"),
        ("עַל-פְּנֵי בֶן-הַשְּׂנוּאָה הַבְּכֹר", "עלי' אבן אלמשנייה אלבכר", "over the son of the disfavored who is the firstborn"),
    ],
    17: [
        (None, "בל", "Rather"),
        ("כִּי אֶת-הַבְּכֹר", "יגב עליה אן יערף אלנאס באלבכר", "he is obligated to make known to the people the firstborn"),
        ("בֶּן-הַשְּׂנוּאָה יַכִּיר", "אבן אלמשנייה", "the son of the disfavored"),
        ("לָתֶת לוֹ פִּי שְׁנַיִם", "ליעטא לה סהמין", "so that two shares be given to him"),
        ("בְּכֹל אֲשֶׁר-יִמָּצֵא לוֹ", "מן גמיע מא יוגד לה", "from all that belongs to him"),
        ("כִּי-הוּא רֵאשִׁית אֹנוֹ", "אד' הו אוול נילה", "since he is the first of his begetting"),
        ("לוֹ מִשְׁפַּט הַבְּכֹרָה", "לה חכם אלבכורייה", "the right of the firstborn belongs to him"),
    ],
    18: [
        ("כִּי-יִהְיֶה לְאִישׁ", "ואן כאן לרגל", "And if a man has"),
        ("בֵּן סוֹרֵר", "אבן זאיל", "a son who is wayward"),
        ("וּמוֹרֶה", "מכ'אלף", "and defiant"),
        ("אֵינֶנּוּ שֹׁמֵעַ", "ליס יקבל", "who does not accept"),
        ("בְּקוֹל אָבִיו", "אמר אביה", "the command of his father"),
        ("וּבְקוֹל אִמּוֹ", "ואמה", "and his mother"),
        ("וְיִסְּרוּ אֹתוֹ", "ויודבאנה", "and they discipline him"),
        ("וְלֹא יִשְׁמַע אֲלֵיהֶם", "ולם יקבל מנהמא", "yet he does not accept it from them"),
    ],
    19: [
        ("וְתָפְשׂוּ בוֹ", "פליקבץ' עליה", "then"),
        ("אָבִיו", "אביה", "his father"),
        ("וְאִמּוֹ", "ואמה", "and his mother shall seize him"),
        ("וְהוֹצִיאוּ אֹתוֹ", "ויכ'רגוה", "and bring him out"),
        ("אֶל-זִקְנֵי עִירוֹ", "אלי' שיוך' קריתה", "to the elders of his town"),
        ("וְאֶל-שַׁעַר מְקֹמוֹ", "ואלי' באב חאכם מוצ'עה", "and to the gate of the judge of his place"),
    ],
    20: [
        ("וְאָמְרוּ אֶל-זִקְנֵי עִירוֹ", "פיקולא להם", "and they shall say to them"),
        ("בְּנֵנוּ זֶה", "אבננא הד'א", "This son of ours"),
        ("סוֹרֵר", "זאיל", "is wayward"),
        ("וּמֹרֶה", "מכ'אלף", "and defiant"),
        ("אֵינֶנּוּ שֹׁמֵעַ בְּקֹלֵנוּ", "ליס יקבל אמרנא", "he does not accept our command"),
        ("זוֹלֵל", "והו מסרף", "and he is excessive"),
        ("וְסֹבֵא", "ומפרט פי אלחראם", "and immoderate in what is forbidden"),
    ],
    21: [
        ("וּרְגָמֻהוּ", "וירגמוה", "And"),
        ("כָּל-אַנְשֵׁי עִירוֹ", "גמיע אהל קריתה", "all the people of his town shall stone him"),
        ("בָאֲבָנִים", "באלחגארה", "with stones"),
        ("וָמֵת", "חתי' ימות", "until he dies"),
        ("וּבִעַרְתָּ הָרָע", "ואנף אהל אלשר", "and banish the people of wickedness"),
        ("מִקִּרְבֶּךָ", "מן בינכם", "from your midst"),
        ("וְכָל-יִשְׂרָאֵל יִשְׁמְעוּ", "וסאיר אל אסראיל יסמעון", "and the rest of Israel shall hear"),
        ("וְיִרָאוּ", "ויכ'אפון", "and be afraid"),
    ],
    22: [
        ("וְכִי-יִהְיֶה בְאִישׁ", "ואד'א וגבת עלי' אנסאן", "And when there is found against a person"),
        ("חֵטְא מִשְׁפַּט-מָוֶת", "כ'טייה חכמהא אלקתל", "a sin whose judgment is death"),
        ("וְהוּמָת", "פקתל", "and he is put to death"),
        ("וְתָלִיתָ אֹתוֹ עַל-עֵץ", "פאצלבה עלי' כ'שבה", "then hang him upon a wooden post"),
    ],
    23: [
        ("לֹא-תָלִין נִבְלָתוֹ עַל-הָעֵץ", "ולא תבית גת'תה עליה", "But do not leave his body on it overnight"),
        (None, "בל", "rather"),
        ("כִּי-קָבוֹר תִּקְבְּרֶנּוּ", "אדפנה דפנא", "bury him in burial"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אליום", "on that same day"),
        ("כִּי-קִלְלַת אֱלֹהִים תָּלוּי", "אד' צלב למא אפתרא עלי' אללה", "for he was hanged because he fabricated falsehood against God"),
        ("וְלֹא תְטַמֵּא", "ולא תנגס", "and do not defile"),
        ("אֶת-אַדְמָתְךָ", "בד'אלך בלדך", "thereby your land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלד'י אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("נַחֲלָה", "נחלה", "as an inheritance"),
    ],
}
