"""Hand-authored alignment triples for Devarim chapter 23.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings. Words Saadia adds with no Hebrew source (glosses, expansions) carry
he=None and link JA↔English only.

This chapter covers who may enter the assembly of God (forbidden marriages,
physical disqualification, mamzer, Ammonite/Moabite forever, Edomite/Egyptian
with limits), war-camp purity rules, the runaway slave, forbidden harlotry and
usury, vows, and the worker eating in a neighbour's vineyard or standing grain.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא-יִקַּח", "לא יתזווג", "shall not marry"),
        ("אִישׁ", "רגל", "A man"),
        ("אֶת-אֵשֶׁת אָבִיו", "זוגה' אביה", "his father's wife"),
        (None, "כד'אך", "likewise"),
        ("וְלֹא יְגַלֶּה", "ולא יכשף", "shall he not uncover"),
        ("כְּנַף אָבִיו", "כנף אביה", "his father's skirt"),
    ],
    2: [
        ("לֹא-יָבֹא", "לא ידכל", "shall not enter"),
        ("פְצוּעַ-דַּכָּא", "מפדוג' אלכ'צי", "He who has crushed testicles"),
        ("וּכְרוּת שָׁפְכָה", "ומקטוע אלאחליל", "or whose member is cut off"),
        ("בִּקְהַל יְהוָה", "פי גוק אללה", "the assembly of God"),
    ],
    3: [
        ("לֹא-יָבֹא", "לא ידכל", "shall not enter"),
        ("מַמְזֵר", "אלזנים", "One of unknown lineage"),
        ("בִּקְהַל יְהוָה", "פי גוק אללה", "the assembly of God"),
        ("גַּם דּוֹר עֲשִׂירִי", "חתי' אלגיל אלעאשר", "even the tenth generation"),
        ("לֹא-יָבֹא לוֹ", "מנה. לא ידכל", "from him shall not enter"),
        ("בִּקְהַל יְהוָה", "פי גוק אללה", "the assembly of God"),
    ],
    4: [
        ("לֹא-יָבֹא", "לא ידכל", "shall not enter"),
        ("עַמּוֹנִי", "עמני", "An Ammonite"),
        ("וּמוֹאָבִי", "ולא מאבי", "and a Moabite"),
        ("בִּקְהַל יְהוָה", "פי גוק אללה", "the assembly of God"),
        ("גַּם דּוֹר עֲשִׂירִי", "חתי' אלגיל אלעאשר", "even the tenth generation"),
        ("לֹא-יָבֹא לָהֶם", "מנהם. לא ידכל", "from them shall not enter"),
        ("בִּקְהַל יְהוָה", "פי גוק אללה", "the assembly of God"),
        ("עַד-עוֹלָם", "אלי' אלאבד", "forever"),
    ],
    5: [
        ("עַל-דְּבַר", "בסבב", "This is because"),
        ("אֲשֶׁר לֹא-קִדְּמוּ", "מא לם ילתקונכם", "they did not meet you"),
        ("בַּלֶּחֶם", "באלכ'בז", "with bread"),
        ("וּבַמַּיִם", "ואלמא", "and water"),
        ("בַּדֶּרֶךְ", "פי אלטריק", "on the road"),
        ("בְּצֵאתְכֶם", "פי כ'רוגכם", "at the time of your going out"),
        ("מִמִּצְרָיִם", "מן מצר", "from Egypt"),
        ("וַאֲשֶׁר שָׂכַר", "ולמא אסתאגר", "and because he hired"),
        ("עָלֶיךָ", "עליך", "against you"),
        ("אֶת-בִּלְעָם", "בלעם", "Balaam"),
        ("בֶּן-בְּעוֹר", "אבן בעור", "son of Beor"),
        ("מִפְּתוֹר", "מן פאתור", "from Pethor"),
        ("אֲרַם נַהֲרַיִם", "ארם נהרים", "of Aram-Naharaim"),
        ("לְקַלְלֶךָּ", "לילענך", "to curse you"),
    ],
    6: [
        ("וְלֹא-אָבָה", "ולם ישא", "did not will"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לִשְׁמֹעַ אֶל-בִּלְעָם", "אן יקבל מן בלעם", "to accept from Balaam"),
        (None, "בל", "rather"),
        ("וַיַּהֲפֹךְ", "קלב", "He turned"),
        ("לְּךָ", "לך", "for you"),
        ("אֶת-הַקְּלָלָה", "אללענה", "the curse"),
        ("לִבְרָכָה", "ברכה", "into a blessing"),
        ("כִּי אֲהֵבְךָ", "למא אחבך", "because He loved you"),
    ],
    7: [
        (None, "פלא", "Therefore do not"),
        ("לֹא-תִדְרֹשׁ", "תלתמס", "seek"),
        ("שְׁלֹמָם", "סלאמתהם", "their welfare"),
        ("וְטֹבָתָם", "וכ'ירהם", "and their good"),
        ("כָּל-יָמֶיךָ", "טול זמאנך", "for the length of your time"),
        ("לְעוֹלָם", "אבדא", "ever"),
    ],
    8: [
        ("לֹא-תְתַעֵב", "לא תכרה", "Do not despise"),
        ("אֲדֹמִי", "אלאדומי", "the Edomite"),
        ("כִּי אָחִיךָ הוּא", "פאנה אכי'ך", "for he is your brother"),
        ("לֹא-תְתַעֵב", "לא תכרה", "do not despise"),
        ("מִצְרִי", "אלמצרי", "the Egyptian"),
        ("כִּי-גֵר הָיִיתָ", "לאנך כנת ג'ריבא", "for you were a stranger"),
        ("בְאַרְצוֹ", "פי בלדה", "in his land"),
    ],
    9: [
        ("דּוֹר שְׁלִישִׁי", "אלגיל אלת'אלת'", "The third generation"),
        ("בָּנִים אֲשֶׁר-יִוָּלְדוּ לָהֶם", "מן אלבנין אלד'י יולדו להם", "of the sons who are born to them"),
        ("יָבֹא לָהֶם בִּקְהַל יְהוָה", "ידכלו פי גוק אללה", "may enter the assembly of God"),
    ],
    10: [
        ("כִּי-תֵצֵא", "ואד'א כ'רגת", "And when you go out"),
        ("מַחֲנֶה", "פי מעסכר", "in a camp"),
        ("עַל-אֹיְבֶיךָ", "עלי' אעדאיך", "against your enemies"),
        (None, "פאחתרז", "guard yourself"),
        (None, "פצ'לא", "especially"),
        ("מִכֹּל דָּבָר רָע", "מן כל אמר קביח", "from every vile matter"),
    ],
    11: [
        ("כִּי-יִהְיֶה בְךָ אִישׁ", "ואן כאן פיכם רגל", "And if there be among you a man"),
        ("אֲשֶׁר לֹא-יִהְיֶה טָהוֹר", "ליס בטאהר", "who is not clean"),
        ("מִקְּרֵה-לָיְלָה", "מן עארץ' אלליל", "on account of a nocturnal occurrence"),
        ("וְיָצָא", "פליכ'רג", "he shall go out"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "to the outside of the camp"),
        ("לֹא יָבֹא אֶל-תּוֹךְ הַמַּחֲנֶה", "מן חית' לא ידכל אלי' וסטה", "that is, he shall not enter into its midst"),
    ],
    12: [
        ("וְהָיָה", "פאד'א כאן", "And when"),
        ("לִפְנוֹת-עֶרֶב", "ענד אתגאה אלליל", "the time comes at the turning toward night"),
        ("יִרְחַץ בַּמָּיִם", "ירחץ' באלמא", "he shall wash with water"),
        ("וּכְבֹא הַשֶּׁמֶשׁ", "וענד מג'יב אלשמס", "and at the setting of the sun"),
        ("יָבֹא אֶל-תּוֹךְ הַמַּחֲנֶה", "ידכל אליה", "he shall enter into it"),
    ],
    13: [
        ("וְיָד תִּהְיֶה לְךָ", "וליכון לך מכאן", "And there shall be a place for you"),
        ("מִחוּץ לַמַּחֲנֶה", "כ'ארג אלעסכר", "outside the camp"),
        ("וְיָצָאתָ שָּׁמָּה חוּץ", "תברז הנאך כ'ארג מנה", "where you may go out there, outside of it"),
    ],
    14: [
        ("וְיָתֵד תִּהְיֶה לְךָ", "וליכון לך ותד", "And there shall be a peg for you"),
        ("עַל-אֲזֵנֶךָ", "מע סלאחך", "along with your weapons"),
        ("וְהָיָה בְּשִׁבְתְּךָ חוּץ", "פאד'א תברזת כ'ארגא מנה", "and when you go out there"),
        ("וְחָפַרְתָּה בָהּ", "פאחפר בה", "you shall dig with it"),
        ("וְשַׁבְתָּ", "ועד", "and return"),
        ("וְכִסִּיתָ אֶת-צֵאָתֶךָ", "וג'טי ד'אלך אלרגיע", "and cover that excrement"),
    ],
    15: [
        ("כִּי יְהוָה", "לאן אללה", "For God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "נורה", "His light"),
        ("מִתְהַלֵּךְ", "סאלך", "moves"),
        ("בְּקֶרֶב מַחֲנֶךָ", "פי וסט עסכרך", "within the midst of your camp"),
        ("לְהַצִּילְךָ", "ליכ'לצך", "to deliver you"),
        ("וְלָתֵת אֹיְבֶיךָ לְפָנֶיךָ", "ויסלם אעדאיך פי ידך", "and to deliver your enemies into your hand"),
        ("וְהָיָה מַחֲנֶיךָ קָדוֹשׁ", "פיכון עסכרך מקדסא", "and so your camp shall be consecrated"),
        ("וְלֹא-יִרְאֶה בְךָ עֶרְוַת דָּבָר", "ולא ירא פיך אמרא קביחא", "and let no vile matter be seen among you"),
        ("וְשָׁב מֵאַחֲרֶיךָ", "פינצרף ענך", "that He turn away from you"),
    ],
    16: [
        ("לֹא-תַסְגִּיר", "ולא תסלם", "You shall not deliver"),
        ("עֶבֶד", "עבדא", "a slave"),
        ("אֶל-אֲדֹנָיו", "אלי' מולאה", "to his master"),
        ("אֲשֶׁר-יִנָּצֵל אֵלֶיךָ", "אלד'י יתכ'לץ אליך", "who escapes to you"),
        ("מֵעִם אֲדֹנָיו", "מן דינה", "on account of his debt"),
        (None, "בל תמנה", "rather you shall be generous to him"),
    ],
    17: [
        ("עִמְּךָ יֵשֵׁב", "וליגלס ענדך", "And he shall dwell beside you"),
        ("בְּקִרְבְּךָ", "פי מא בינך", "among you"),
        ("בַּמָּקוֹם אֲשֶׁר-יִבְחַר", "פי אלמוצ'ע אלד'י יכ'תארה", "in the place which he chooses"),
        ("בְּאַחַד שְׁעָרֶיךָ", "פי אחדא מחאלך", "in one of your localities"),
        ("בַּטּוֹב לוֹ", "פי אלאצלח לה", "in what is best for him"),
        ("לֹא תּוֹנֶנּוּ", "ולא תצ'הדה", "and you shall not oppress him"),
    ],
    18: [
        ("לֹא-תִהְיֶה קְדֵשָׁה", "ולא תכון", "There shall not be"),
        ("מִבְּנוֹת יִשְׂרָאֵל", "מן בנאת אסראיל", "among the daughters of Israel"),
        (None, "ממתעה", "a woman who gives pleasure for hire"),
        ("וְלֹא-יִהְיֶה קָדֵשׁ", "ולא מן בני אסראיל", "nor among the sons of Israel"),
        (None, "ממתע", "a man who gives pleasure for hire"),
    ],
    19: [
        ("לֹא-תָבִיא", "ולא תדכ'ל", "And do not bring"),
        (None, "שייא", "anything"),
        ("אֶתְנַן זוֹנָה", "מן אגעאל אלזואני", "from the hire of harlots"),
        ("וּמְחִיר כֶּלֶב", "ואת'מאן אלכלאב", "or the price of dogs"),
        ("בֵּית יְהוָה אֱלֹהֶיךָ", "אלי' בית אללה רבך", "into the house of God your Lord"),
        ("לְכָל-נֶדֶר", "פי שי מן גמיע אלנד'ור", "for any of all vows"),
        ("כִּי תוֹעֲבַת יְהוָה אֱלֹהֶיךָ", "לאן אללה רבך יכרה", "for God your Lord loathes"),
        ("גַּם-שְׁנֵיהֶם", "המא גמיעא", "them both"),
    ],
    20: [
        ("לֹא-תַשִּׁיךְ", "ולא תעיין", "You shall not charge"),
        ("לְאָחִיךָ", "אכי'ך", "your brother"),
        (None, "עיינה'", "interest"),
        ("נֶשֶׁךְ כֶּסֶף", "דראהם", "interest of money"),
        ("נֶשֶׁךְ אֹכֶל", "ולא טעאם", "nor of food"),
        ("נֶשֶׁךְ כָּל-דָּבָר אֲשֶׁר יִשָּׁךְ", "ולא כל אמר יעיין", "nor of any matter that may bear interest"),
    ],
    21: [
        ("לַנָּכְרִי תַשִּׁיךְ", "בל אלג'ריב תעאיין", "From the stranger you may charge interest"),
        ("וּלְאָחִיךָ לֹא תַשִּׁיךְ", "ואכי'ך לא תעאיין", "but from your brother you shall not charge interest"),
        ("לְמַעַן יְבָרֶכְךָ", "לכי יבארך לך", "so that"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord may bless you"),
        ("בְּכֹל מִשְׁלַח יָדֶךָ", "פי גמיע ממד ידך", "in all the reach of your hand"),
        ("עַל-הָאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה לְרִשְׁתָּהּ", "אלד'י אנת דאכ'ל אליה לתחוזה", "which you are entering to take possession of it"),
    ],
    22: [
        ("כִּי-תִדֹּר נֶדֶר", "ואן נד'רת נד'רא", "And if you vow a vow"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("לֹא תְאַחֵר", "לא ת'ווכ'ר", "do not delay"),
        ("לְשַׁלְּמוֹ", "אלופא בה", "fulfilling it"),
        ("כִּי-דָרֹשׁ יִדְרְשֶׁנּוּ", "פאנה יטאלבך בה מטאלבה", "for He will demand it of you with demand"),
        ("יְהוָה אֱלֹהֶיךָ מֵעִמָּךְ", "פתחל בך", "and a punishment shall befall"),
        ("וְהָיָה בְךָ חֵטְא", "עקובה", "you"),
    ],
    23: [
        ("וְכִי תֶחְדַּל לִנְדֹּר", "מא לו אנתהית אוולא מנה", "Whereas had you refrained from it at the outset"),
        ("לֹא-יִהְיֶה בְךָ חֵטְא", "לם תחל בך עקובה", "no punishment would have befallen you"),
    ],
    24: [
        ("מוֹצָא שְׂפָתֶיךָ", "בל מא כ'רג מן שפתיך", "Rather, what has gone forth from your lips"),
        ("תִּשְׁמֹר", "אחפצה", "guard it"),
        ("וְעָשִׂיתָ", "ואעמל בה", "and act upon it"),
        ("כַּאֲשֶׁר נָדַרְתָּ", "כמא נד'רת", "as you vowed"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("נְדָבָה", "מתברעא", "voluntarily"),
        ("אֲשֶׁר דִּבַּרְתָּ בְּפִיךָ", "כמא קלתאה בפאך", "as you spoke it with your mouth"),
    ],
    25: [
        ("כִּי תָבֹא", "ואד'א אסתאגרת", "And when you are hired"),
        ("בְּכֶרֶם רֵעֶךָ", "פי כרם צאחבך", "in your fellow's vineyard"),
        ("וְאָכַלְתָּ עֲנָבִים", "פכל מן אלענב", "you may eat of the grapes"),
        ("כְּנַפְשְׁךָ שָׂבְעֶךָ", "כשהותך שבעך", "as your appetite satisfies you"),
        ("וְאֶל-כֶּלְיְךָ לֹא תִתֵּן", "ולא תצ'ע מנה שי פי אניתך", "but you shall not place anything from them into your vessel"),
    ],
    26: [
        ("כִּי תָבֹא", "ואד'א אסתאגרת", "And when you are hired"),
        ("בְּקָמַת רֵעֶךָ", "פי סנבל צאחבך", "among your fellow's standing grain"),
        ("וְקָטַפְתָּ מְלִילֹת בְּיָדֶךָ", "פאקטף מא תפרכה בידך", "you may pluck what you can rub with your hand"),
        ("וְחֶרְמֵשׁ לֹא תָנִיף", "ולא תחרך אלמנגל", "but you shall not swing the sickle"),
        ("עַל קָמַת רֵעֶךָ", "עלי' סנבל צאחבך", "over your fellow's standing grain"),
        (None, "לנפסך", "for yourself"),
    ],
}
