"""Hand-authored alignment triples for Devarim chapter 13.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the prohibition of following false prophets and seducers
to idolatry — the claimant-prophet (vv. 2–6), the intimate inciter (vv. 7–12),
and the apostate city (vv. 13–19) — aligned with care for Saadia's expansions:
מדעי נבווה for נָבִיא, מעבודאת for אֱלֹהִים אֲחֵרִים, and the ir ha-nidahat laws.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "פגמיע", "And all"),
        ("אֵת כָּל-הַדָּבָר", "אלאמר", "the commandment"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם", "אלד'י אמרכם בה", "which I command you"),
        ("אֹתוֹ תִשְׁמְרוּ", "אחפצוה", "keep it"),
        ("לַעֲשׂוֹת", "ואעמלו בה", "and do it"),
        ("לֹא-תֹסֵף עָלָיו", "לא תזידון עליה שיא", "you shall not add to it anything"),
        ("וְלֹא תִגְרַע מִמֶּנּוּ", "ולא תנקצו מנה", "nor diminish from it"),
    ],
    2: [
        ("כִּי-יָקוּם", "ואד'א קאם", "And if there arise"),
        ("בְּקִרְבְּךָ", "פי מא בינכם", "among you"),
        ("נָבִיא", "מדעי נבווה", "a claimant of prophecy"),
        ("אוֹ חֹלֵם חֲלוֹם", "או חאלם חלם", "or one who dreams a dream"),
        ("וְנָתַן", "פאעטאך", "and he gives you"),
        ("אֵלֶיךָ אוֹת", "איה", "a sign"),
        ("אוֹ מוֹפֵת", "או ברהאנא", "or a proof"),
    ],
    3: [
        ("וּבָא הָאוֹת וְהַמּוֹפֵת", "פלו אתת אלאיה או אלברהן", "and the sign or the proof should come to pass"),
        ("אֲשֶׁר-דִּבֶּר אֵלֶיךָ", "ממן קאל לך", "as he said to you"),
        ("לֵאמֹר נֵלְכָה", "תעאל בנא", "Come, let us go"),
        ("אַחֲרֵי אֱלֹהִים אֲחֵרִים", "אלי' מעבודאת אכ'ר", "to other objects of worship"),
        ("אֲשֶׁר לֹא-יְדַעְתָּם", "מא לם תערפהא", "which you have not known"),
        ("וְנָעָבְדֵם", "פנעבדהא", "that we may serve them"),
    ],
    4: [
        ("לֹא תִשְׁמַע", "פלא תקבלו", "do not accept"),
        ("אֶל-דִּבְרֵי הַנָּבִיא הַהוּא", "מן ד'אלך אלמדעי אלנבווה", "from that claimant of prophecy"),
        ("אוֹ אֶל-חוֹלֵם הַחֲלוֹם הַהוּא", "או אלחאלם אלחלם", "or that dreamer of dreams"),
        ("כִּי", "פאן", "for"),
        ("יְהוָה אֱלֹהֵיכֶם", "אללה רבכם", "God your Lord"),
        ("מְנַסֶּה", "ממתחנכם", "is testing you"),
        ("לָדַעַת", "ליצ'הר", "to make manifest"),
        ("הֲיִשְׁכֶם אֹהֲבִים", "הל אנתם מחבוה", "whether you love Him"),
        (None, "מכ'לצין", "and are devoted"),
        ("בְּכָל-לְבַבְכֶם", "בכל קלובכם", "with all your hearts"),
        ("וּבְכָל-נַפְשְׁכֶם", "ונפוסכם", "and your souls"),
    ],
    5: [
        (None, "בל", "Rather"),
        ("אַחֲרֵי יְהוָה אֱלֹהֵיכֶם", "תבע אללה רבכם", "in the footsteps of God your Lord"),
        ("תֵּלֵכוּ", "תסירו", "shall you walk"),
        ("וְאֹתוֹ תִירָאוּ", "ואיאה פארהבו", "and Him alone hold in awe"),
        ("וְאֶת-מִצְו‍ֹתָיו תִּשְׁמֹרוּ", "ווצאיאה תחפצו", "and His commandments keep"),
        ("וּבְקֹלוֹ תִשְׁמָעוּ", "ואמרה תקבלו", "and His decree accept"),
        ("וְאֹתוֹ תַעֲבֹדוּ", "ואיאה פאעבדו", "and Him alone serve"),
        ("וּבוֹ תִדְבָּקוּן", "וטאעתה פאלזמוהא", "and to His obedience cleave"),
    ],
    6: [
        ("וְהַנָּבִיא הַהוּא", "וד'אלך אלמדעי אלנבווה", "And that claimant of prophecy"),
        ("אוֹ חֹלֵם הַחֲלוֹם הַהוּא", "או חאלם אלחלם", "or dreamer of dreams"),
        ("יוּמָת", "פליקתל", "shall be put to death"),
        ("כִּי דִבֶּר-סָרָה", "למא תקוול אלמחאל", "for he speaks an impossible thing"),
        ("עַל-יְהוָה אֱלֹהֵיכֶם", "עלי' אללה רבכם", "against God your Lord"),
        ("הַמּוֹצִיא אֶתְכֶם", "אלמכ'רגכם", "who brought you out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן בלד מצר", "from the land of Egypt"),
        ("וְהַפֹּדְךָ", "ואלפאדיכם", "and redeemed you"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה", "from the house of bondage"),
        ("לְהַדִּיחֲךָ", "לידחו בך", "to thrust you away"),
        ("מִן-הַדֶּרֶךְ", "ען אלטריק", "from the path"),
        ("אֲשֶׁר צִוְּךָ יְהוָה אֱלֹהֶיךָ", "אלד'י אמרך אללה רבך", "which God your Lord commanded you"),
        ("לָלֶכֶת בָּהּ", "אן תסיר פיה", "to walk"),
        ("וּבִעַרְתָּ הָרָע מִקִּרְבֶּךָ", "ואנף אהל אלשר מן וסטך", "and purge the people of evil from your midst"),
    ],
    7: [
        ("כִּי יְסִיתְךָ", "ואד'א אטג'אך", "should incite you"),
        ("אָחִיךָ בֶן-אִמֶּךָ", "אכ'יך אבן אמך", "your brother, the son of your mother"),
        ("אוֹ-בִנְךָ", "או אבנך", "or your son"),
        ("אוֹ-בִתְּךָ", "או אבנתך", "or your daughter"),
        ("אוֹ אֵשֶׁת חֵיקֶךָ", "או אמראתך אלתי הי חרמתך", "or your wife who is your bond"),
        ("אוֹ רֵעֲךָ", "או צאחבך", "or your companion"),
        ("אֲשֶׁר כְּנַפְשְׁךָ", "אלד'י הו כנפסך", "who is as your own soul"),
        ("בַּסֵּתֶר", "פי סתר", "in secret"),
        ("לֵאמֹר", "קאילא", "saying:"),
        ("נֵלְכָה", "תעאל", "Come"),
        ("וְנַעַבְדָה אֱלֹהִים אֲחֵרִים", "נעבד מעבודאת אכ'ר", "let us serve other objects of worship"),
        ("אֲשֶׁר לֹא יָדַעְתָּ", "מא לם תערפהא", "which you have not known"),
        ("אַתָּה וַאֲבֹתֶיךָ", "אנת ואבאיך", "you and your fathers"),
    ],
    8: [
        ("מֵאֱלֹהֵי הָעַמִּים", "מן מעבודאת אלאמם", "from among the objects of worship of the nations"),
        ("אֲשֶׁר סְבִיבֹתֵיכֶם", "אלד'ין חואליכם", "that are around you"),
        ("הַקְּרֹבִים אֵלֶיךָ", "אלאקרבין אליך", "the nearest to you"),
        ("אוֹ הָרְחֹקִים מִמֶּךָּ", "או אלאבעדין מנך", "or the farthest from you"),
        ("מִקְצֵה הָאָרֶץ", "מן טרף אלארץ'", "from one end of the earth"),
        ("וְעַד-קְצֵה הָאָרֶץ", "אלי' טרפהא", "to the other"),
    ],
    9: [
        ("לֹא-תֹאבֶה לוֹ", "פלא תשא ד'אלך", "do not consent to that"),
        ("וְלֹא תִשְׁמַע אֵלָיו", "ולא תקבל מנה", "and do not accept it from him"),
        ("וְלֹא-תָחוֹס עֵינְךָ עָלָיו", "ולא תשפק עליה", "and do not show compassion toward him"),
        ("וְלֹא-תַחְמֹל", "ולא תרת' לה", "and do not take pity on him"),
        ("וְלֹא-תְכַסֶּה עָלָיו", "ולא תסתר עליה", "and do not conceal it on his behalf"),
    ],
    10: [
        (None, "בל", "Rather"),
        ("הָרֹג תַּהַרְגֶנּוּ", "אקתלה קתלא", "slay him with slaying"),
        ("יָדְךָ תִּהְיֶה-בּוֹ בָרִאשׁוֹנָה", "וידך אוול מא תקע עליה", "and your hand shall be the first to fall upon him"),
        ("לַהֲמִיתוֹ", "פתקתלה", "to kill him"),
        ("וְיַד כָּל-הָעָם בָּאַחֲרֹנָה", "ויד סאיר אלאמה אכ'ירא", "and the hand of the rest of the nation last"),
    ],
    11: [
        ("וּסְקַלְתּוֹ בָאֲבָנִים", "וארגמה באלחגארה", "And stone him with stones"),
        ("וָמֵת", "חתי' ימות", "until he dies"),
        ("כִּי בִקֵּשׁ לְהַדִּיחֲךָ", "למא קצד אדחאך", "for he sought to thrust you away"),
        ("מֵעַל יְהוָה אֱלֹהֶיךָ", "ען אללה רבך", "from God your Lord"),
        ("הַמּוֹצִיאֲךָ", "אלמכ'רגך", "who brought you out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן בלד מצר", "from the land of Egypt"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה", "from the house of bondage"),
    ],
    12: [
        ("וְכָל-יִשְׂרָאֵל", "וסאיר אל אסראיל", "And the rest of the house of Israel"),
        ("יִשְׁמְעוּ", "יסמעון", "shall hear"),
        ("וְיִרָאוּן", "ויכ'אפון", "and be afraid"),
        ("וְלֹא-יוֹסִפוּ", "ולא יעאודון", "and shall not repeat"),
        ("לַעֲשׂוֹת", "אן יצנעון", "doing"),
        ("כַּדָּבָר הָרָע הַזֶּה", "מת'ל הד'א אלאמר אלרדי", "the like of this evil thing"),
        ("בְּקִרְבֶּךָ", "פי וסטך", "in your midst"),
    ],
    13: [
        ("כִּי-תִשְׁמַע", "ואן סמעת", "And if you should hear"),
        ("בְּאַחַת עָרֶיךָ", "ען בעץ' קראך", "concerning one of your towns"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ נֹתֵן לְךָ", "אלד'י אללה רבך מעטיך", "which God your Lord is giving you"),
        ("לָשֶׁבֶת שָׁם", "אן תסכן פיהא", "to dwell in"),
        (None, "קול קאיל", "the saying of one who says"),
    ],
    14: [
        ("יָצְאוּ אֲנָשִׁים", "אן קד כ'רג קום", "There have gone out a band"),
        ("בְּנֵי-בְלִיַּעַל", "כפאר", "of unbelieving men"),
        ("מִקִּרְבֶּךָ", "מנהא", "from it"),
        ("וַיַּדִּיחוּ", "פאצ'לו", "and they have led astray"),
        ("אֶת-יֹשְׁבֵי עִירָם", "אהל קריתהם", "the people of their town"),
        ("לֵאמֹר", "קאילין", "saying:"),
        ("נֵלְכָה", "תעאלו", "Come"),
        ("וְנַעַבְדָה אֱלֹהִים אֲחֵרִים", "נעבד מעבודאת אכ'ר", "let us serve other objects of worship"),
        ("אֲשֶׁר לֹא-יְדַעְתֶּם", "מא לם תערפוהא", "which you have not known"),
    ],
    15: [
        ("וְדָרַשְׁתָּ", "פאלתמס ד'אלך", "then seek it out"),
        ("וְחָקַרְתָּ", "ואסתברה", "and investigate it"),
        ("וְשָׁאַלְתָּ הֵיטֵב", "ואסאל ענה נעמא", "and inquire concerning it thoroughly"),
        ("וְהִנֵּה אֱמֶת", "פאן כאן אלאמר חקא", "and if the matter be true"),
        ("נָכוֹן הַדָּבָר", "ת'אבתא", "and confirmed"),
        ("נֶעֶשְׂתָה הַתּוֹעֵבָה הַזֹּאת", "קד צנעת הד'ה אלכריהה", "that this abomination has been done"),
        ("בְּקִרְבֶּךָ", "פי וסטך", "in your midst"),
    ],
    16: [
        ("הַכֵּה תַכֶּה", "פאקתל קתלא", "slay with slaying"),
        ("אֶת-יֹשְׁבֵי הָעִיר הַהִוא", "אהל תלך אלקריה", "the people of that town"),
        ("לְפִי-חָרֶב", "בחד אלסיף", "by the edge of the sword"),
        ("הַחֲרֵם אֹתָהּ", "ואתלפהא", "and destroy it"),
        ("וְאֶת-כָּל-אֲשֶׁר-בָּהּ", "וגמיע מא פיהא", "and all that is in it"),
        ("וְאֶת-בְּהֶמְתָּהּ", "חתי' בהאימהא", "even its beasts"),
        ("לְפִי-חָרֶב", "בחד אלסיף", "by the edge of the sword"),
    ],
    17: [
        ("וְאֶת-כָּל-שְׁלָלָהּ", "וגמיע סלבהא", "And all its spoil"),
        ("תִּקְבֹּץ", "אגמעה", "gather it"),
        ("אֶל-תּוֹךְ רְחֹבָהּ", "אלי' וסט רחבתהא", "to the center of its square"),
        ("וְשָׂרַפְתָּ בָאֵשׁ", "ואחרק באלנאר", "and burn with fire"),
        ("אֶת-הָעִיר", "תלך אלקריה", "that town"),
        ("וְאֶת-כָּל-שְׁלָלָהּ", "וגמיע סלבהא", "and all its spoil"),
        ("כָּלִיל", "גמלה", "as a whole offering"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("וְהָיְתָה תֵּל עוֹלָם", "ותכון תלא אלי' אלדהר", "and it shall be a ruin forever"),
        ("לֹא תִבָּנֶה עוֹד", "לא תבנא אבדא", "never to be rebuilt"),
    ],
    18: [
        ("מִן-הַחֵרֶם", "מן אלמתלוף", "of the destroyed thing"),
        ("וְלֹא-יִדְבַּק בְּיָדְךָ מְאוּמָה", "ולא ילתזק בידך שייא", "cling to your hand"),
        ("לְמַעַן יָשׁוּב יְהוָה", "לכי ירגע אללה", "so that God may turn back"),
        ("מֵחֲרוֹן אַפּוֹ", "מן שדה ג'צ'בה", "from the intensity of His anger"),
        ("וְנָתַן-לְךָ רַחֲמִים", "ויעטיך רחמתה", "and give you His mercy"),
        ("וְרִחַמְךָ", "וירחמך", "and have mercy on you"),
        ("וְהִרְבֶּךָ", "ויכת'רך", "and multiply you"),
        ("כַּאֲשֶׁר נִשְׁבַּע לַאֲבֹתֶיךָ", "כמא קסם לאבאיך", "as He swore to your fathers"),
    ],
    19: [
        ("כִּי תִשְׁמַע", "אד' תקבל", "when you accept"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "אמר אללה רבך", "the command of God your Lord"),
        ("לִשְׁמֹר", "ותחפץ", "and keep"),
        ("אֶת-כָּל-מִצְו‍ֹתָיו", "ותעמל בגמיע וצאיאה", "and do all His commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלתי אמרך בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "today"),
        ("לַעֲשׂוֹת הַיָּשָׁר", "באן תצנע אלמסתקים", "doing what is upright"),
        ("בְּעֵינֵי יְהוָה אֱלֹהֶיךָ", "ענדה", "in His sight"),
    ],
}
