"""Hand-authored alignment triples for Devarim chapter 26.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the first-fruits (bikkurim) declaration and ritual
(vv. 1–11), the tithe confession (vv. 12–15), the covenant affirmation
(vv. 16–19) — including the "My father was a wandering Aramean" pericope
(v. 5) where Saadia reads לָבָן הָאֲרַמִּי rather than the traditional אֲרַמִּי
אֹבֵד אָבִי. Verse 3 uses אִמָּם (imām) for כֹּהֵן; נְחֲלָה/נַחֲלָה is rendered נחלה.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְהָיָה כִּי-תָבוֹא", "ואד'א דכ'לת", "And when you enter"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("נַחֲלָה", "נחלה", "as a heritage"),
        ("וִירִשְׁתָּהּ", "וחזתה", "and you possess it"),
        ("וְיָשַׁבְתָּ בָּהּ", "ואקמת פיה", "and settle in it"),
    ],
    2: [
        ("וְלָקַחְתָּ", "פכ'ד'", "then take"),
        ("מֵרֵאשִׁית", "מן אואיל", "from the first-fruits"),
        ("כָּל-פְּרִי הָאֲדָמָה", "ת'מר אלארץ'", "of the earth's produce"),
        ("אֲשֶׁר תָּבִיא", "אלד'י תדכ'לה", "which you bring in"),
        ("מֵאַרְצְךָ", "מן ריאצ'ך", "from your gardens"),
        ("אֲשֶׁר יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
        ("וְשַׂמְתָּ בַטֶּנֶא", "וציירה פי בניגה", "and place it in a basket"),
        ("וְהָלַכְתָּ", "ואמץ' בה", "and go with it"),
        ("אֶל-הַמָּקוֹם", "אלי' אלמוצ'ע", "to the place"),
        ("אֲשֶׁר יִבְחַר", "אלד'י יכ'תארה", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("לְשַׁכֵּן שְׁמוֹ שָׁם", "ליחל נורה פיה", "for His light to dwell therein"),
    ],
    3: [
        ("וּבָאתָ", "וציר בה", "and go with it"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the imām"),
        ("אֲשֶׁר יִהְיֶה", "אלד'י ילי", "who serves"),
        ("בַּיָּמִים הָהֵם", "פי דאלך אלזמאן", "in that time"),
        ("וְאָמַרְתָּ אֵלָיו", "וקל לה", "and say to him"),
        ("הִגַּדְתִּי הַיּוֹם", "קד שכרת אליום", "I have today given thanks"),
        ("לַיהוָה אֱלֹהֶיךָ", "אללה רבך", "to God your Lord"),
        ("כִּי-בָאתִי", "אד' דכ'לת", "in that I have entered"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("אֲשֶׁר נִשְׁבַּע יְהוָה", "אלד'י קסם אללה", "which God swore"),
        ("לַאֲבֹתֵינוּ", "לאבאינא", "to our fathers"),
        ("לָתֶת לָנוּ", "אן יעטינאה", "that He would give to us"),
    ],
    4: [
        ("וְלָקַח הַכֹּהֵן", "ויאכ'ד' אלאמאם", "And the imām shall take"),
        ("הַטֶּנֶא", "תלך אלבניגה", "that basket"),
        ("מִיָּדֶךָ", "מן ידך", "from your hand"),
        ("וְהִנִּיחוֹ", "ויצ'עהא", "and set it"),
        ("לִפְנֵי מִזְבַּח", "בין ידי מד'בח", "before the altar of"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "God your Lord"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        (None, "אבתדי", "begin"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
        ("אֲרַמִּי", "אן לבן אלארמי", "Laban the Aramean"),
        ("אֹבֵד אָבִי", "כאד אן יביד אבי", "nearly destroyed my father"),
        ("וַיֵּרֶד מִצְרַיְמָה", "פנזל מצרא", "and he went down to Egypt"),
        ("וַיָּגָר שָׁם", "וסכן ת'ם", "and settled there"),
        ("בִּמְתֵי מְעָט", "ברהט קליל", "with a small company"),
        ("וַיְהִי-שָׁם", "וצאר ת'ם", "and became there"),
        ("לְגוֹי גָּדוֹל", "אמה כבירה", "a great"),
        ("עָצוּם", "]עט'ימה] עצ'ימה", "mighty"),
        ("וָרָב", "כת'ירה", "and numerous nation"),
    ],
    6: [
        ("וַיָּרֵעוּ אֹתָנוּ הַמִּצְרִים", "פאסא בנא אלמצריון", "And the Egyptians dealt evil with us"),
        ("וַיְעַנּוּנוּ", "ועד'בונא", "and tormented us"),
        ("וַיִּתְּנוּ עָלֵינוּ", "וגעלו עלינא", "and laid upon us"),
        ("עֲבֹדָה קָשָׁה", "כ'דמה צעבה", "a hard service"),
    ],
    7: [
        ("וַנִּצְעַק", "פצרכ'נא", "And we cried out"),
        ("אֶל-יְהוָה", "אלי' אללה", "to God"),
        ("אֱלֹהֵי אֲבֹתֵינוּ", "אלאה אביאינא", "the God of our fathers"),
        ("וַיִּשְׁמַע יְהוָה", "וסמע", "and He heard"),
        ("אֶת-קֹלֵנוּ", "צותנא", "our voice"),
        ("וַיַּרְא", "ונצ'ר", "and looked upon"),
        ("אֶת-עָנְיֵנוּ", "לצ'עפנא", "our weakness"),
        ("וְאֶת-עֲמָלֵנוּ", "ושקאנא", "and our toil"),
        ("וְאֶת-לַחֲצֵנוּ", "וצ'ג'טנאכ", "and our oppression"),
    ],
    8: [
        ("וַיּוֹצִאֵנוּ יְהוָה", "ואכ'רגנא אללה", "And God brought us out"),
        ("מִמִּצְרַיִם", "מן מצר", "of Egypt"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a mighty hand"),
        ("וּבִזְרֹעַ נְטוּיָה", "וד'ראע ממדודה", "and an outstretched arm"),
        ("וּבְמֹרָא גָּדֹל", "ותכ'ויף עצ'ים", "and with great awe"),
        ("וּבְאֹתוֹת", "ואיאת", "and with signs"),
        ("וּבְמֹפְתִים", "ובראהין", "and proofs"),
    ],
    9: [
        ("וַיְבִאֵנוּ", "פאגא בנא", "And He brought us"),
        ("אֶל-הַמָּקוֹם הַזֶּה", "אלי' הד'א אלמוצ'ע", "to this place"),
        ("וַיִּתֶּן-לָנוּ", "ואעטאנא", "and gave us"),
        ("אֶת-הָאָרֶץ הַזֹּאת", "הד'א אלבלד", "this land"),
        ("אֶרֶץ זָבַת חָלָב", "בלד יפיץ' אללבן", "a land flowing with milk"),
        ("וּדְבָשׁ", "ואלעסל", "and honey"),
    ],
    10: [
        ("וְעַתָּה", "ואלאן", "And now"),
        ("הִנֵּה", "הוד'א", "behold"),
        ("הֵבֵאתִי", "קד גית", "I have brought"),
        ("אֶת-רֵאשִׁית פְּרִי הָאֲדָמָה", "באואיל ת'מר אלארץ'", "the first-fruits of the earth's produce"),
        ("אֲשֶׁר-נָתַתָּה לִּי", "אלד'י רזקתניהא", "which You have provided me"),
        ("יְהוָה", "יא רב", "O Lord"),
        (None, "ת'ם", "Then"),
        ("וְהִנַּחְתּוֹ", "צ'עה", "place it"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְהִשְׁתַּחֲוִיתָ", "ואסגד", "and bow down"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
    ],
    11: [
        ("וְשָׂמַחְתָּ", "ואפרח", "And rejoice"),
        ("בְכָל-הַטּוֹב", "בכל אלכ'יר", "in all the good"),
        ("אֲשֶׁר נָתַן-לְךָ", "אלד'י רזקך", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord has provided you"),
        ("אַתָּה", "אנת ואלך", "you and your household"),
        ("וְהַלֵּוִי", "ואלוי", "and the Levite"),
        ("וְהַגֵּר", "ואלג'ריב", "and the stranger"),
        ("אֲשֶׁר בְּקִרְבֶּךָ", "אלד'י פי מחאלך", "who is in your settlements"),
    ],
    12: [
        ("כִּי תְכַלֶּה", "ואד'א פרג'ת", "And when you have finished"),
        ("לַעְשֵׂר", "מן תעשיר", "tithing"),
        ("אֶת-כָּל-מַעְשַׂר תְּבוּאָתְךָ", "גמיע עשור ג'לתך", "all the tithes of your yield"),
        ("בַּשָּׁנָה הַשְּׁלִישִׁת", "פי אלסנה אלת'אלת'ה", "in the third year"),
        ("שְׁנַת הַמַּעֲשֵׂר", "סנה' כמאל אלעשור", "the year of the completion of the tithes"),
        ("וְנָתַתָּה לַלֵּוִי", "ודפעת דאלך לאללוי", "and you have given it to the Levite"),
        ("לַגֵּר", "ואלג'ריב", "and the stranger"),
        ("לַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְלָאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("וְאָכְלוּ בִשְׁעָרֶיךָ", "פאכלו מנה פי מחאלך", "and they have eaten of it in your settlements"),
        ("וְשָׂבֵעוּ", "ושבעו", "and been satisfied"),
    ],
    13: [
        ("וְאָמַרְתָּ", "פקל", "then say"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
        ("בִּעַרְתִּי הַקֹּדֶשׁ", "קד אנפית אלאקדאס", "I have removed the consecrated things"),
        ("מִן-הַבַּיִת", "מן ביתי", "from my house"),
        ("וְגַם נְתַתִּיו", "וקד דפעתהא", "and I have given them"),
        ("לַלֵּוִי", "לאללוי", "to the Levite"),
        ("וְלַגֵּר", "ואלג'ריב", "and the stranger"),
        ("לַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְלָאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("כְּכָל-מִצְוָתְךָ", "כגמיע וצאיאך", "according to all Your commandments"),
        ("אֲשֶׁר צִוִּיתָנִי", "אלד'י אוציתני", "which You commanded me"),
        ("לֹא-עָבַרְתִּי מִמִּצְו‍ֹתֶיךָ", "לם אתגאוז שייא מנהא", "I have not transgressed any of them"),
        ("וְלֹא שָׁכָחְתִּי", "ולם אנס ד'אלך", "nor have I forgotten that"),
    ],
    14: [
        ("לֹא-אָכַלְתִּי בְאֹנִי מִמֶּנּוּ", "ואלעשר אלד'י הו לי לם אכל מנה פי חזני", "And the tithe which is mine — I did not eat of it in my grief"),
        ("וְלֹא-בִעַרְתִּי מִמֶּנּוּ בְּטָמֵא", "ולם אצרף מנה אלי' נגס", "nor did I divert any of it to anything impure"),
        ("וְלֹא-נָתַתִּי מִמֶּנּוּ לְמֵת", "ולא פי חואיג מיית", "nor for the needs of a dead person"),
        ("שָׁמַעְתִּי בְּקוֹל יְהוָה אֱלֹהָי", "בל קבלת אמר אללה רבי", "rather, I accepted the command of God my Lord"),
        ("עָשִׂיתִי כְּכֹל אֲשֶׁר צִוִּיתָנִי", "וצנעת כגמיע מא אמרתני", "and I acted according to all that You commanded me"),
    ],
    15: [
        ("הַשְׁקִיפָה", "אטלע", "Look out"),
        ("מִמְּעוֹן קָדְשְׁךָ", "מן מוטן קדסך", "from the abode of Your holiness"),
        ("מִן-הַשָּׁמַיִם", "מן אלסמא", "from the heavens"),
        ("וּבָרֵךְ", "ובארך", "and bestow Your blessing"),
        ("אֶת-עַמְּךָ", "פי שעבך", "upon Your people"),
        ("אֶת-יִשְׂרָאֵל", "אל אסראיל", "the house of Israel"),
        ("וְאֵת הָאֲדָמָה", "ופי אלארץ'", "and upon the land"),
        ("אֲשֶׁר נָתַתָּה לָנוּ", "אלד'י אעטיתנא", "which You gave us"),
        ("כַּאֲשֶׁר נִשְׁבַּעְתָּ לַאֲבֹתֵינוּ", "כמא קסמת לאבאינא", "as You swore to our fathers"),
        ("אֶרֶץ זָבַת חָלָב", "אן תכון ארצ'א תפיץ' לבנא", "that it be a land flowing with milk"),
        ("וּדְבָשׁ", "ועסלא", "and honey"),
    ],
    16: [
        (None, "ואעלם", "And know"),
        ("הַיּוֹם הַזֶּה", "הד'א אליום", "this day"),
        ("יְהוָה אֱלֹהֶיךָ", "אללה רבך", "that God your Lord"),
        ("מְצַוְּךָ", "יאמרך", "commands you"),
        ("לַעֲשׂוֹת", "באן תצנע", "to perform"),
        ("אֶת-הַחֻקִּים הָאֵלֶּה", "הד'ה אלרסום", "these statutes"),
        ("וְאֶת-הַמִּשְׁפָּטִים", "ואלאחכאם", "and ordinances"),
        ("וְשָׁמַרְתָּ", "פאחפצ'הא", "so keep them"),
        ("וְעָשִׂיתָ אוֹתָם", "ואעמל בהא", "and act by them"),
        ("בְּכָל-לְבָבְךָ", "בכל קלבך", "with all your heart"),
        ("וּבְכָל-נַפְשֶׁךָ", "ונפסך", "and your soul"),
    ],
    17: [
        ("אֶת-יְהוָה הֶאֱמַרְתָּ הַיּוֹם", "ואנת כמא ומרת אללה רבך", "And you, even as you have made God your Lord sovereign over you"),
        ("לִהְיוֹת לְךָ לֵאלֹהִים", "אן יכון לך אלאהא", "that He be your God"),
        ("וְלָלֶכֶת בִּדְרָכָיו", "ואן תסיר פי טרקה", "and that you walk in His ways"),
        ("וְלִשְׁמֹר חֻקָּיו", "ותחפץ' רסומה", "and keep His statutes"),
        ("וּמִצְו‍ֹתָיו", "ווצאיאה", "and His commandments"),
        ("וּמִשְׁפָּטָיו", "ואחכאמה", "and His ordinances"),
        ("וְלִשְׁמֹעַ בְּקֹלוֹ", "ותקבל אמרה", "and accept His command"),
    ],
    18: [
        ("וַיהוָה הֶאֱמִירְךָ הַיּוֹם", "פכד'אך ומרך אללה", "so likewise has God made you sovereign"),
        ("לִהְיוֹת לוֹ לְעַם סְגֻלָּה", "לתכון לה אמה כ'אצה", "to be for Him a particular nation"),
        ("כַּאֲשֶׁר דִּבֶּר-לָךְ", "כמא ועדך", "as He promised you"),
        ("וְלִשְׁמֹר כָּל-מִצְו‍ֹתָיו", "ותחפץ' גמיע וצאיאה", "and that you keep all His commandments"),
    ],
    19: [
        ("וּלְתִתְּךָ עֶלְיוֹן", "ואן יגעלך עאליא", "and that He set you high"),
        ("עַל כָּל-הַגּוֹיִם", "עלי' סאיר אלאמם", "above the rest of the nations"),
        ("אֲשֶׁר עָשָׂה", "אלד'י כ'לקהם", "whom He created"),
        ("לִתְהִלָּה", "מדחא", "in praise"),
        ("וּלְשֵׁם", "ואסמא", "and in renown"),
        ("וּלְתִפְאָרֶת", "ופכ'רא", "and in glory"),
        ("וְלִהְיֹתְךָ עַם-קָדֹשׁ", "ואן תכון שעב מקדס", "and that you be a holy people"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("כַּאֲשֶׁר דִּבֵּר", "כמא ועדך", "as He promised you"),
    ],
}
