"""Hand-authored alignment triples for Devarim chapter 10.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the second tablets and the ark (vv. 1–5), the death of
Aaron and Levi's set-apart role (vv. 6–9), Moses' second forty-day fast
(v. 10), the command to resume the journey (v. 11), and the great hortatory
section: fear / love / serve God with all one's heart, the "circumcise the
foreskin of your heart" call (v. 16), the divine-attribute catalogue (v. 17),
the care for orphan / widow / stranger (vv. 18–19), the "fear / serve / cleave
/ swear" formula (v. 20), and the numerical miracle of 70→stars (v. 22).
Recurring vocabulary (heart, fear, serve, portion/inheritance, gems-tablets)
is aligned consistently throughout.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "At that time"),
        ("אָמַר יְהוָה", "קאל אללה", "God said"),
        ("אֵלַי", "לי", "to me"),
        ("פְּסָל-לְךָ", "אנחת", "Hew"),
        ("שְׁנֵי-לוּחֹת אֲבָנִים", "לוחי גוהר", "two tablets of gems"),
        ("כָּרִאשֹׁנִים", "כאלאוולין", "like the first ones"),
        ("וַעֲלֵה", "ואצעד", "and ascend"),
        ("אֵלַי", "בהמא", "with them"),
        ("הָהָרָה", "אלי' אלגבל", "to the mountain"),
        ("וְעָשִׂיתָ לְּךָ אֲרוֹן עֵץ", "וקד צנעת צנדוקא מן כ'שב", "after you have made a chest of wood"),
    ],
    2: [
        ("וְאֶכְתֹּב", "חתי אכתב", "So that I may write"),
        ("עַל-הַלֻּחֹת", "עליהמא", "upon them"),
        ("אֶת-הַדְּבָרִים", "אלכלמאת", "the words"),
        ("אֲשֶׁר הָיוּ", "אלד'י כאנת", "that were"),
        ("עַל-הַלֻּחֹת הָרִאשֹׁנִים", "עלי' אללוחין אלאוולין", "upon the first two tablets"),
        ("אֲשֶׁר שִׁבַּרְתָּ", "אלד'י כסרתהמא", "which you broke"),
        ("וְשַׂמְתָּם בָּאָרוֹן", "וציירהמא פי אלצנדוק", "and place them in the chest"),
    ],
    3: [
        ("וָאַעַשׂ אֲרוֹן", "פצנעת צנדוקא", "And I made a chest"),
        ("עֲצֵי שִׁטִּים", "מן כ'שב אלסנט", "of acacia wood"),
        ("וָאֶפְסֹל", "ונחתת", "and I hewed"),
        ("שְׁנֵי-לֻחֹת אֲבָנִים", "לוחי גוהר", "two tablets of gems"),
        ("כָּרִאשֹׁנִים", "כאלאוולין", "like the first ones"),
        ("וָאַעַל הָהָרָה", "וצעדת אלי' אלגבל", "and I ascended to the mountain"),
        ("וּשְׁנֵי הַלֻּחֹת בְּיָדִי", "והמא פי ידיי", "with the two of them in my hands"),
    ],
    4: [
        ("וַיִּכְתֹּב", "פכתב", "And He wrote"),
        ("עַל-הַלֻּחֹת", "עליהמא", "upon them"),
        ("כַּמִּכְתָּב הָרִאשׁוֹן", "כאלכתאב אלאוול", "according to the first writing"),
        ("אֵת עֲשֶׂרֶת הַדְּבָרִים", "והי אלעשר אלכלמאת", "they are the Ten Words"),
        ("אֲשֶׁר דִּבֶּר יְהוָה", "אלד'י כלמכם אללה", "which God had spoken to you"),
        ("בָּהָר", "פי אלגבל", "on the mountain"),
        ("מִתּוֹךְ הָאֵשׁ", "מן וסט אלנאר", "from within the fire"),
        ("בְּיוֹם הַקָּהָל", "פי יום אלגוק", "on the day of the assembly"),
        ("וַיִּתְּנֵם יְהוָה אֵלָי", "ודפעהמא אליי", "and He delivered them to me"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        ("וָאֵפֶן", "ולית", "I turned"),
        ("וָאֵרֵד", "ונזלת", "and descended"),
        ("מִן-הָהָר", "מן אלגבל", "from the mountain"),
        ("וָאָשִׂם אֶת-הַלֻּחֹת", "וציירת אלוחין", "and I placed the two tablets"),
        ("בָּאָרוֹן", "פי אלצנדוק", "in the chest"),
        ("אֲשֶׁר עָשִׂיתִי", "אלד'י צנעתה", "that I had made"),
        ("וַיִּהְיוּ שָׁם", "ובקיא הנאך", "and they remained there"),
        ("כַּאֲשֶׁר צִוַּנִי יְהוָה", "כמא אמרני אללה", "as God had commanded me"),
    ],
    6: [
        (None, "ולמא שפעני פי הרון", "And when He accepted my intercession concerning Aaron"),
        (None, "אקאם", "he endured"),
        ("וּבְנֵי יִשְׂרָאֵל נָסְעוּ", "אלי' אן רחלו בני אסראיל", "until the sons of Israel journeyed"),
        ("מִבְּאֵרֹת בְּנֵי-יַעֲקָן", "מן בארות בני יעקן", "from Beeroth Bene-Yaakan"),
        ("מוֹסֵרָה", "אלי' מוסרה", "to Moserah"),
        (None, "ת'ם", "there"),
        ("שָׁם מֵת אַהֲרֹן", "מאת הרון", "Aaron died"),
        ("וַיִּקָּבֵר שָׁם", "ודפן ת'ם", "and was buried there"),
        ("וַיְכַהֵן אֶלְעָזָר בְּנוֹ תַּחְתָּיו", "ואם אלעזר אבנה מכאנה", "and Eleazar his son served in his place"),
    ],
    7: [
        ("מִשָּׁם נָסְעוּ", "ורחלו מן ת'ם", "And they journeyed from there"),
        ("הַגֻּדְגֹּדָה", "אלי גדגוד", "to Gudgod"),
        ("וּמִן-הַגֻּדְגֹּדָה", "ומן גדגוד", "and from Gudgod"),
        ("יָטְבָתָה", "אלי' יטבת", "to Yotbath"),
        ("אֶרֶץ נַחֲלֵי מָיִם", "ארץ' ד'את אודיה' מא", "a land with valleys of water"),
    ],
    8: [
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "At that time"),
        ("הִבְדִּיל יְהוָה", "אפרז אללה", "God set apart"),
        ("אֶת-שֵׁבֶט הַלֵּוִי", "סבט לוי", "the tribe of Levi"),
        ("לָשֵׂאת", "ליחמלו", "to carry"),
        ("אֶת-אֲרוֹן בְּרִית-יְהוָה", "צנדוק עהדה", "the ark of His covenant"),
        ("לַעֲמֹד לִפְנֵי יְהוָה", "ויקומו בין ידיה", "and to stand before Him"),
        ("לְשָׁרְתוֹ", "ליכ'דמוה", "to serve Him"),
        ("וּלְבָרֵךְ בִּשְׁמוֹ", "ויבארכו באסמה", "and to bless in His name"),
        ("עַד הַיּוֹם הַזֶּה", "אלי' יומנא הד'א", "unto this day of ours"),
        (None, "למא אסעפוני", "because they came to my aid"),
    ],
    9: [
        ("עַל-כֵּן", "ולד'אלך", "And therefore"),
        ("לֹא-הָיָה לְלֵוִי", "לם יכון לאליואניין", "the Levites had no"),
        ("חֵלֶק וְנַחֲלָה", "נציב ונחלה", "portion and inheritance"),
        ("עִם-אֶחָיו", "מע אכ'ותהם", "together with their brothers"),
        (None, "בל", "rather"),
        ("יְהוָה הוּא נַחֲלָתוֹ", "הבאת אללה הי נציבהם", "the gifts of God are their portion"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה אֱלֹהֶיךָ לוֹ", "כמא אמר בהא להם", "as He decreed for them"),
    ],
    10: [
        ("וְאָנֹכִי עָמַדְתִּי", "ואנא אקמת", "And I stayed"),
        ("בָהָר", "פי אלגבל", "on the mountain"),
        ("כַּיָּמִים הָרִאשֹׁנִים", "מת'ל אלמרה אלאוולא", "like the first time"),
        ("אַרְבָּעִים יוֹם", "ארבעין יומא", "forty days"),
        ("וְאַרְבָּעִים לָיְלָה", "וארבעין לילה", "and forty nights"),
        ("וַיִּשְׁמַע יְהוָה אֵלַי", "פסמע אללה לי", "and God hearkened to me"),
        ("גַּם בַּפַּעַם הַהִוא", "פי ד'אלך אלוקת", "at that time"),
        ("לֹא-אָבָה יְהוָה הַשְׁחִיתֶךָ", "ולם ישא אללה אן יהלכך", "and God did not will to destroy you"),
    ],
    11: [
        ("וַיֹּאמֶר יְהוָה אֵלַי", "פקאל אללה לי", "And God said to me"),
        ("קוּם", "קום", "Arise"),
        ("לֵךְ לְמַסַּע", "אמץ'", "go"),
        ("לִפְנֵי הָעָם", "בין ידי אלקום", "before the people"),
        (None, "ורחלהם", "and set them journeying"),
        ("וְיָבֹאוּ", "חתי' ימצ'ון", "that they may go"),
        ("וְיִירְשׁוּ", "פירת'ון", "and inherit"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-נִשְׁבַּעְתִּי לַאֲבֹתָם", "אלד'י קסמת לאבאיהם", "which I have sworn to their fathers"),
        ("לָתֵת לָהֶם", "אן אעטיהם", "that I would give them"),
    ],
    12: [
        (None, "ואלאן", "And now"),
        ("יִשְׂרָאֵל", "יא אסראיל", "O Israel"),
        ("מָה יְהוָה אֱלֹהֶיךָ שֹׁאֵל", "מא אלד'י יטלבה מנך אללה רבך", "what is it that God your Lord requires of you"),
        ("לְיִרְאָה", "אלא אן תכ'אפה", "but that you fear Him"),
        ("לָלֶכֶת בְּכָל-דְּרָכָיו", "ותסיר פי טרקה", "and walk in His ways"),
        ("וּלְאַהֲבָה אֹתוֹ", "ותחבבה", "and love Him"),
        ("וְלַעֲבֹד אֶת-יְהוָה אֱלֹהֶיךָ", "ותעבדה מכ'לצא", "and serve Him wholeheartedly"),
        ("בְּכָל-לְבָבְךָ", "בכל קלבך", "with all your heart"),
        ("וּבְכָל-נַפְשֶׁךָ", "ונפסך", "and your soul"),
    ],
    13: [
        ("לִשְׁמֹר אֶת-מִצְו‍ֹת יְהוָה", "ואחפץ' וצאיאה", "and keep His commandments"),
        ("וְאֶת-חֻקֹּתָיו", "ורסומה", "and His statutes"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלתי אמרך בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "today"),
        ("לְטוֹב לָךְ", "ליכ'אר לך", "that it may go well for you"),
    ],
    14: [
        (None, "הוד'א", "Behold"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("הַשָּׁמַיִם וּשְׁמֵי הַשָּׁמָיִם", "אלסמאואת כלהא", "belong all the heavens"),
        ("הָאָרֶץ", "ואלארץ'", "and the earth"),
        ("וְכָל-אֲשֶׁר-בָּהּ", "וכל מא פיהא", "and all that is in it"),
    ],
    15: [
        ("רַק", "לכנה", "Yet"),
        ("בַּאֲבֹתֶיךָ חָשַׁק יְהוָה", "אצטפא אבאיך", "He chose your fathers"),
        ("לְאַהֲבָה אוֹתָם", "פאחבהם", "and loved them"),
        ("וַיִּבְחַר בְּזַרְעָם אַחֲרֵיהֶם", "ואכ'תאר נסלהם מן בעדהם", "and chose their offspring after them"),
        ("בָּכֶם", "ואנתם הם", "and affiliated them to Himself"),
        ("מִכָּל-הָעַמִּים", "מן בין אלשעוב", "from among the peoples"),
        ("כַּיּוֹם הַזֶּה", "כמא תשאהדון", "as you can see"),
    ],
    16: [
        ("וּמַלְתֶּם", "פאזילו", "So remove"),
        ("אֵת עָרְלַת לְבַבְכֶם", "ג'ש קלובכם", "the covering of your hearts"),
        ("וְעָרְפְּכֶם", "ורקאבכם", "and your necks"),
        ("לֹא תַקְשׁוּ עוֹד", "לא תצעבוהא אבדא", "do not stiffen them ever"),
    ],
    17: [
        ("כִּי יְהוָה אֱלֹהֵיכֶם", "לאן אללה רבכם", "For God your Lord"),
        ("הוּא אֱלֹהֵי הָאֱלֹהִים", "הו רב אלארבאב", "is the Lord of lords"),
        ("וַאֲדֹנֵי הָאֲדֹנִים", "וסייד אלסאדה", "and Master of masters"),
        ("הָאֵל הַגָּדֹל", "אלטאיק אל עצ'ים", "the mighty, the great"),
        ("הַגִּבֹּר", "אלגבאר", "the powerful"),
        ("וְהַנּוֹרָא", "אלמכ'יף", "the awe-inspiring"),
        ("אֲשֶׁר לֹא-יִשָּׂא פָנִים", "אלד'י לא יחאבי אלוגוה", "who shows no partiality"),
        ("וְלֹא יִקַּח שֹׁחַד", "ולא יאכ'ד' אלרשא", "and takes no bribe"),
    ],
    18: [
        ("עֹשֶׂה מִשְׁפַּט", "צאנע חכם", "who renders judgment"),
        ("יָתוֹם", "אליתים", "for the orphan"),
        ("וְאַלְמָנָה", "ואלארמלה", "and the widow"),
        ("וְאֹהֵב גֵּר", "ומחב אלג'ריב", "and who loves the stranger"),
        ("לָתֶת לוֹ", "ירזקה", "providing him"),
        ("לֶחֶם", "טעאמא", "food"),
        ("וְשִׂמְלָה", "וכסוה", "and clothing"),
    ],
    19: [
        ("וַאֲהַבְתֶּם אֶת-הַגֵּר", "פאחבבו אלג'ריב", "So love the stranger"),
        ("כִּי-גֵרִים הֱיִיתֶם", "פטאל מא כנתם ג'רבא", "for long you were strangers"),
        ("בְּאֶרֶץ מִצְרָיִם", "פי בלד מצר", "in the land of Egypt"),
    ],
    20: [
        ("אֶת-יְהוָה אֱלֹהֶיךָ תִּירָא", "וכ'ף אללה רבך", "Fear God your Lord"),
        ("אֹתוֹ תַעֲבֹד", "ואעבדה", "serve Him"),
        ("וּבוֹ תִדְבָּק", "ואלזם טאעתה", "cleave to His obedience"),
        ("וּבִשְׁמוֹ תִּשָּׁבֵעַ", "ואחלף באסמה", "and swear by His name"),
        (None, "בארא", "uprightly"),
    ],
    21: [
        ("הוּא תְהִלָּתְךָ", "הו מדחתך", "He is your praise"),
        ("וְהוּא אֱלֹהֶיךָ", "והו אלאהך", "and He is your God"),
        ("אֲשֶׁר-עָשָׂה אִתְּךָ", "כמא צנע מעך", "who did with you"),
        ("אֶת-הַגְּדֹלֹת", "תלך אלכבאיר", "those great"),
        ("וְאֶת-הַנּוֹרָאֹת הָאֵלֶּה", "ואלמהאיב", "and awesome things"),
        ("אֲשֶׁר רָאוּ עֵינֶיךָ", "אלתי ראתהא עינאך", "which your own eyes have seen"),
    ],
    22: [
        (None, "פמנהא", "Among them"),
        ("יָרְדוּ אֲבֹתֶיךָ מִצְרָיְמָה", "אן אבאיך", "your fathers went down to Egypt"),
        ("בְּשִׁבְעִים נֶפֶשׁ", "בסבעין נפסא", "with seventy souls"),
        (None, "ואלאן", "and now"),
        ("וְעַתָּה שָׂמְךָ יְהוָה אֱלֹהֶיךָ", "פקד ציירך אללה רבך", "God your Lord has made you"),
        ("כְּכוֹכְבֵי הַשָּׁמַיִם לָרֹב", "ככואכב אלסמא כת'רה", "as numerous as the stars of the sky"),
    ],
}
