"""Hand-authored alignment triples for Devarim chapter 19.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the cities of refuge (vv. 1–13), the boundary marker law
(v. 14), the two-witness rule (v. 15), and the false-witness (עֵד-חָמָס)
procedure including the lex talionis closing (vv. 16–21). Particular care
was taken for Saadia's paraphrastic expansions of the manslayer scenarios
(vv. 4–6) and the avenger-of-blood passage.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("כִּי-יַכְרִית", "ואד'א קטע", "cuts off"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶת-הַגּוֹיִם", "אלאמם", "the nations"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ נֹתֵן לְךָ אֶת-אַרְצָם", "אלד'י הו מעטיך בלדהם", "whose land He is giving you"),
        ("וִירִשְׁתָּם", "פורת'תהם", "and you inherit them"),
        ("וְיָשַׁבְתָּ", "וסכנת", "and settle"),
        ("בְעָרֵיהֶם", "פי קראהם", "in their towns"),
        ("וּבְבָתֵּיהֶם", "ומנאזלהם", "and their dwellings"),
    ],
    2: [
        ("שָׁלוֹשׁ עָרִים", "ת'לאת' קרא", "three towns"),
        ("תַּבְדִּיל", "אפרז", "set apart"),
        ("לָךְ", "לך", "for yourself"),
        ("בְּתוֹךְ", "פי וסט", "in the midst of"),
        ("אַרְצְךָ", "בלדך", "your land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלד'י אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("לְרִשְׁתָּהּ", "לתחוזה", "to possess"),
    ],
    3: [
        ("תָּכִין לְךָ", "אצלח", "and make"),
        ("הַדֶּרֶךְ", "טרקהא", "their roads ready"),
        (None, "עלי'", "according to"),
        ("וְשִׁלַּשְׁתָּ", "תת'לית", "the division into thirds of"),
        ("אֶת-גְּבוּל", "תכ'ם", "the bounds of"),
        ("אַרְצְךָ", "ארצך", "your land"),
        ("אֲשֶׁר יַנְחִילְךָ", "אלד'י ינחלך", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord is granting you as inheritance"),
        ("וְהָיָה", "תכון מעדה", "they shall be prepared"),
        ("לָנוּס", "ליהרב", "to flee"),
        ("שָׁמָּה", "אליהא", "to them"),
        ("כָּל-רֹצֵחַ", "כל קאתל", "for every slayer"),
    ],
    4: [
        ("וְזֶה", "והד'א", "and this is"),
        ("דְּבַר", "כ'בר", "the account of"),
        ("הָרֹצֵחַ", "אלקאתל", "the slayer"),
        ("אֲשֶׁר-יָנוּס", "אלד'י יהרב", "who flees"),
        ("שָׁמָּה", "אליהא", "to them"),
        ("וָחָי", "פיחיא", "and lives"),
        ("אֲשֶׁר יַכֶּה", "מן קתל", "one who slew"),
        ("אֶת-רֵעֵהוּ", "צאחבה", "his fellow"),
        ("בִּבְלִי-דַעַת", "בלא מערפה", "without intent"),
        ("וְהוּא לֹא-שֹׂנֵא לוֹ", "והו ג'יר שאני לה", "and he was not one who bore hatred toward him"),
        ("מִתְּמֹל שִׁלְשֹׁם", "מן אמס ומא קבלה", "from yesterday or before it"),
    ],
    5: [
        ("וַאֲשֶׁר יָבֹא", "וד'אלך כמן ידכ'ל", "as one who enters"),
        ("אֶת-רֵעֵהוּ", "מע צאחבה", "with his fellow"),
        ("בַיַּעַר", "אלי' אלשערא", "into the thicket"),
        ("לַחְטֹב עֵצִים", "ליקטע חטבא", "to cut wood"),
        ("וְנִדְּחָה יָדוֹ בַגַּרְזֶן", "פתמיל ידה באלחדיד", "and his hand swings with the iron"),
        ("לִכְרֹת הָעֵץ", "ליקטע אלעוד", "to cut the beam"),
        ("וְנָשַׁל הַבַּרְזֶל מִן-הָעֵץ", "או ינסל אלחדיד מן אלעוד", "or the iron slips from the beam"),
        ("וּמָצָא אֶת-רֵעֵהוּ", "פיציב צאחבה", "and strikes his fellow"),
        ("וָמֵת", "וימות", "and he dies"),
        ("הוּא יָנוּס", "הו יהרב", "he shall flee"),
        ("אֶל-אַחַת הֶעָרִים-הָאֵלֶּה", "אלי' ואחדה מן הד'ה אלקרא", "to one of these towns"),
        ("וָחָי", "פיחיא", "and live"),
    ],
    6: [
        ("פֶּן-יִרְדֹּף", "כילא יכלב", "Lest"),
        ("גֹּאֵל הַדָּם", "ולי אלדם", "the avenger of blood"),
        ("אַחֲרֵי הָרֹצֵחַ", "אלקאתל", "pursue the slayer"),
        ("כִּי-יֵחַם לְבָבוֹ", "ממא יחמא קלבה", "when his heart is inflamed"),
        ("וְהִשִּׂיגוֹ", "פילחקה", "and overtake him"),
        ("כִּי-יִרְבֶּה הַדֶּרֶךְ", "לכת'רה' אלטריק", "because the road is long"),
        ("וְהִכָּהוּ נָפֶשׁ", "פיקתלה", "and slay him"),
        ("וְלוֹ אֵין מִשְׁפַּט-מָוֶת", "וליס עליה חכם אלקתל", "though no judgment of death rests upon him"),
        ("כִּי לֹא שֹׂנֵא הוּא לוֹ", "אד' ליס הו שאני לה", "since he was not one who bore hatred toward him"),
        ("מִתְּמוֹל שִׁלְשׁוֹם", "מן אמס ומא קבלה", "from yesterday or before it"),
    ],
    7: [
        ("עַל-כֵּן", "פלד'אלך", "Therefore"),
        ("אָנֹכִי מְצַוְּךָ", "אנא אמרך", "I command you"),
        (None, "אליום", "today"),
        ("שָׁלֹשׁ עָרִים תַּבְדִּיל לָךְ", "באן תפרז לך ת'לאת' קרא", "that you set apart three towns for yourself"),
    ],
    8: [
        ("וְאִם-יַרְחִיב", "ואן אוסע", "And if"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶת-גְּבֻלְךָ", "תכ'מך", "widens your bounds"),
        ("כַּאֲשֶׁר נִשְׁבַּע", "כמא קסם", "as He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
        ("וְנָתַן לְךָ", "פאעטאך", "and gives you"),
        ("אֶת-כָּל-הָאָרֶץ", "גמיע אלבלד", "all the land"),
        ("אֲשֶׁר דִּבֶּר לָתֵת לַאֲבֹתֶיךָ", "אלד'י ועד באן יעטיה לאבאיך", "which He promised to give to your fathers"),
    ],
    9: [
        (None, "וד'אלך", "and that is"),
        ("כִּי-תִשְׁמֹר", "אד'א חפצ'ת", "if you observe"),
        ("אֶת-כָּל-הַמִּצְוָה הַזֹּאת", "גמיע הד'ה אלשריעה", "all this law"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלד'י אנא אמרך בהא", "which I command you in it"),
        ("הַיּוֹם", "אליום", "today"),
        ("לַעֲשֹׂתָהּ", "ותעמל בהא", "and act according to it"),
        ("לְאַהֲבָה אֶת-יְהוָה אֱלֹהֶיךָ", "באן תחבב אללה רבך", "to love God your Lord"),
        ("וְלָלֶכֶת בִּדְרָכָיו", "ותסיר פי טרקה", "and to walk in His ways"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "all the time"),
        ("וְיָסַפְתָּ לְךָ", "פזד לך", "then add for yourself"),
        ("עוֹד שָׁלֹשׁ עָרִים", "ת'לאת' קרא", "three towns more"),
        ("עַל הַשָּׁלֹשׁ הָאֵלֶּה", "עלי' הד'ה אלת'לאת'", "beyond these three"),
    ],
    10: [
        ("וְלֹא יִשָּׁפֵךְ דָּם נָקִי", "ללא יספך דם ברי", "so that innocent blood not be shed"),
        ("בְּקֶרֶב אַרְצְךָ", "פי בלדך", "in your land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלד'י אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ נַחֲלָה", "מעטיך נחלה", "is giving you as an inheritance"),
        ("וְהָיָה עָלֶיךָ דָּמִים", "פיכון עליך דמה", "and its blood be upon you"),
    ],
    11: [
        ("וְכִי-יִהְיֶה אִישׁ", "ואן כאן רגלא", "But if a man"),
        ("שֹׂנֵא לְרֵעֵהוּ", "שאניא לצאחבה", "bears hatred toward his fellow"),
        ("וְאָרַב לוֹ", "פכמן לה", "and lies in wait for him"),
        ("וְקָם עָלָיו", "וקאם עליה", "and rises against him"),
        ("וְהִכָּהוּ נֶפֶשׁ וָמֵת", "חתי' צרבה פמאת", "and strikes him so that he dies"),
        ("וְנָס אֶל-אַחַת הֶעָרִים הָאֵל", "והרב אלי' ואחדה מן הד'ה אלקרא", "and flees to one of these towns"),
    ],
    12: [
        ("וְשָׁלְחוּ זִקְנֵי עִירוֹ", "פליבעתו שיוך' קריתה", "then the elders of his town shall send"),
        ("וְלָקְחוּ אֹתוֹ", "ויאכ'דוה", "and take him"),
        ("מִשָּׁם", "מן ת'ם", "from there"),
        ("וְנָתְנוּ אֹתוֹ", "ויסלמוה", "and deliver him"),
        ("בְּיַד גֹּאֵל הַדָּם", "אלי' ולי אלדם", "to the avenger of blood"),
        ("וָמֵת", "חתי' יקתל", "so that he be slain"),
    ],
    13: [
        ("לֹא-תָחוֹס עֵינְךָ עָלָיו", "ולא תשפק עליה", "And you shall not have compassion on him"),
        (None, "בל", "rather"),
        ("וּבִעַרְתָּ", "אנף", "banish"),
        ("דַם-הַנָּקִי", "קאתלי אלברי", "the slayer of the innocent"),
        ("מִיִּשְׂרָאֵל", "מן בין אל אסראיל", "from among the house of Israel"),
        ("וְטוֹב לָךְ", "לכי יכ'אר לך", "so that it may go well for you"),
    ],
    14: [
        ("לֹא תַסִּיג", "לא תזייג'", "Do not falsify"),
        ("גְּבוּל רֵעֲךָ", "תכם צאחבך", "the boundary of your fellow"),
        ("אֲשֶׁר גָּבְלוּ רִאשֹׁנִים", "אלד'י תכ'מה אלאוולין", "which the ancients have bounded"),
        ("בְּנַחֲלָתְךָ", "בנחלתך", "within your inheritance"),
        ("אֲשֶׁר תִּנְחַל", "אלד'י תנחלהא", "that you inherit"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ", "אלד'י אללה רבך", "which God your Lord"),
        ("נֹתֵן לְךָ", "מעטיך", "is giving you"),
        ("לְרִשְׁתָּהּ", "לתחוזה", "to possess"),
    ],
    15: [
        ("לֹא-יָקוּם עֵד אֶחָד", "לא יקום שאהד ואחד", "A single witness shall not stand"),
        ("בְּאִישׁ", "עלי' אנסאן", "against a person"),
        ("לְכָל-עָו‍ֹן וּלְכָל-חַטָּאת", "פי שי מן אלד'נוב ואלכ'טאיא", "in any matter of transgressions and sins"),
        ("בְּכָל-חֵטְא אֲשֶׁר יֶחֱטָא", "ואלגנאיאת אלד'י יגניהא", "and the offenses which he commits"),
        ("עַל-פִּי שְׁנֵי עֵדִים", "בל עלי' קול שאהדין", "but on the word of two witnesses"),
        ("אוֹ עַל-פִּי שְׁלֹשָׁה-עֵדִים", "או ת'לאתה", "or on the word of three"),
        ("יָקוּם דָּבָר", "תקום אלאמור", "shall matters be established"),
    ],
    16: [
        ("כִּי-יָקוּם", "ואן קאם", "And if"),
        ("עֵד-חָמָס", "שאהד צ'לם", "a witness of wrongdoing"),
        ("בְּאִישׁ", "עלי' אנסאן", "rises against a person"),
        ("לַעֲנוֹת בּוֹ סָרָה", "לישהד עליה במחאל", "to testify against him in an impossible matter"),
    ],
    17: [
        ("וְעָמְדוּ", "פליקף", "then"),
        ("שְׁנֵי-הָאֲנָשִׁים", "אלרגלאן", "the two men"),
        ("אֲשֶׁר-לָהֶם הָרִיב", "אלד'ין אלכ'צומה להם", "who have the dispute"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("לִפְנֵי הַכֹּהֲנִים וְהַשֹּׁפְטִים", "בין ידי אלאיממה ואלחכאם", "before the imāms and the judges"),
        ("אֲשֶׁר יִהְיוּ בַּיָּמִים הָהֵם", "אלד'י ילו פי ד'אלך אלזמאן", "who serve in that time"),
    ],
    18: [
        ("וְדָרְשׁוּ הַשֹּׁפְטִים", "פלילתמסו ד'אלך אלחכם", "and they shall examine that judgment"),
        ("הֵיטֵב", "גיידא", "thoroughly"),
        ("וְהִנֵּה עֵד-שֶׁקֶר הָעֵד", "פאן כאן אלשאהד שאהד זור", "and if the witness is a false witness"),
        ("שֶׁקֶר עָנָה בְאָחִיו", "וקד שהד בבאטל עלי' אכ'יה", "and has testified falsely against his brother"),
    ],
    19: [
        ("וַעֲשִׂיתֶם לוֹ", "פאצנעו לה", "then do to him"),
        ("כַּאֲשֶׁר זָמַם לַעֲשׂוֹת לְאָחִיו", "מת'ל מא הם אן יצנע באכ'יה", "as he intended to do to his brother"),
        ("וּבִעַרְתָּ הָרָע מִקִּרְבֶּךָ", "ואנף אהל אלשר מן וסטך", "and banish the doers of evil from your midst"),
    ],
    20: [
        ("וְהַנִּשְׁאָרִים", "ואלבאקיון", "And the remainder"),
        ("יִשְׁמְעוּ", "יסמעון", "shall hear"),
        ("וְיִרָאוּ", "ויכ'אפון", "and be afraid"),
        ("וְלֹא-יֹסִפוּ לַעֲשׂוֹת", "ולא יעודו אן יצנעו", "and shall not again do"),
        ("כַּדָּבָר הָרָע הַזֶּה", "מת'ל הד'א אלאמר אלרדי", "the like of this vile matter"),
        ("בְּקִרְבֶּךָ", "פי מא בינכם", "in your midst"),
    ],
    21: [
        ("וְלֹא תָחוֹס עֵינֶךָ", "ולא תשפק", "And you shall not have compassion"),
        (None, "פי אלקצאץ", "in retribution"),
        ("נֶפֶשׁ בְּנֶפֶשׁ", "נפס בנפס", "life for life"),
        ("עַיִן בְּעַיִן", "ודיה' עין בעין", "and the compensation of eye for eye"),
        ("שֵׁן בְּשֵׁן", "וסן בסן", "and tooth for tooth"),
        ("יָד בְּיָד", "ויד ביד", "hand for hand"),
        ("רֶגֶל בְּרָגֶל", "ורגל ברגל", "and foot for foot"),
    ],
}
