"""Hand-authored alignment triples for Devarim chapter 8.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter is the "remember the wilderness" discourse — forty years of manna
and testing, the good land with its seven species (wheat/barley/vine/fig/
pomegranate/olive-oil/honey), and the warning not to forget God in prosperity.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "וגמיע", "And all"),
        ("כָּל-הַמִּצְוָה", "אלוצאיא", "the commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלד'י אמרך בהא", "which I charge you with"),
        ("הַיּוֹם", "אליום", "today"),
        ("תִּשְׁמְרוּן", "אחפצוהא", "keep them"),
        ("לַעֲשׂוֹת", "ואעמלו בהא", "and act upon them"),
        ("לְמַעַן תִּחְיוּן", "לכי תחיון", "that you may live"),
        ("וּרְבִיתֶם", "ותכת'רון", "and multiply"),
        ("וּבָאתֶם", "ותדכ'לו", "and enter"),
        ("וִירִשְׁתֶּם", "ותחוזו", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-נִשְׁבַּע", "אלד'י קסם", "which"),
        ("יְהוָה", "אללה", "God"),
        ("לַאֲבֹתֵיכֶם", "לאבאיכם", "swore to your fathers"),
    ],
    2: [
        ("וְזָכַרְתָּ", "ואד'כר", "And remember"),
        ("אֶת-כָּל-הַדֶּרֶךְ", "גמיע אלטריק", "all the way"),
        ("אֲשֶׁר הוֹלִיכְךָ", "אלד'י סיירך", "along which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בַּמִּדְבָּר", "פי אלבר", "made you journey in the wilderness"),
        ("זֶה אַרְבָּעִים שָׁנָה", "הד'ה ארבעין", "these forty years"),
        ("לְמַעַן עַנֹּתְךָ", "ליתעבך", "to weary you"),
        ("לְנַסֹּתְךָ", "וימתחנך", "and test you"),
        ("לָדַעַת", "ליצ'הר", "to make known"),
        (None, "לאלנאס", "to the people"),
        ("אֶת-אֲשֶׁר בִּלְבָבְךָ", "מא פי קלבך", "what is in your heart"),
        ("הֲתִשְׁמֹר מִצְו‍ֹתָו", "אתחפץ' וצאיאה", "whether you keep His commandments"),
        ("אִם-לֹא", "אם לא", "or not"),
    ],
    3: [
        ("וַיְעַנְּךָ", "ואתעבך", "And He wearied you"),
        ("וַיַּרְעִבֶךָ", "ואגאעך", "and made you hungry"),
        ("וַיַּאֲכִלְךָ", "ואטעמך", "and fed you"),
        ("אֶת-הַמָּן", "אלמן", "the manna"),
        ("אֲשֶׁר לֹא-יָדַעְתָּ", "אלד'י לם תערפה", "which you had not known"),
        ("וְלֹא יָדְעוּן אֲבֹתֶיךָ", "ולם יערפה אבאיך", "and your fathers had not known"),
        ("לְמַעַן הוֹדִיעֲךָ", "לכי יערפך", "that He might make known to you"),
        ("כִּי לֹא עַל-הַלֶּחֶם", "אנה ליס עלי' אלכ'בז", "that it is not on bread"),
        ("לְבַדּוֹ", "וחדה", "alone"),
        ("יִחְיֶה הָאָדָם", "יחיא אלאנסאן", "that a person lives"),
        ("כִּי עַל-כָּל-מוֹצָא", "בל עלי' גמיע מא אכ'רגה", "but on all that issues from"),
        ("פִי-יְהוָה", "קול אללה", "the word of God"),
        ("יִחְיֶה הָאָדָם", "יעיש", "shall a person live"),
    ],
    4: [
        ("שִׂמְלָתְךָ", "ות'יאבך", "Your garments"),
        ("לֹא בָלְתָה", "לם תבל", "did not wear out"),
        ("וְרַגְלְךָ", "ורגלך", "and your foot"),
        ("לֹא בָצֵקָה", "לם תחף", "did not go bare"),
        ("זֶה אַרְבָּעִים שָׁנָה", "פי הד'ה אלארבעין אלסנה", "in these forty years"),
    ],
    5: [
        ("וְיָדַעְתָּ", "ואעלם", "And know"),
        ("עִם-לְבָבֶךָ", "פי נפסך", "within yourself"),
        ("כִּי", "אנה", "that"),
        ("כַּאֲשֶׁר יְיַסֵּר אִישׁ", "כמא יאדב אלמר", "just as a man disciplines"),
        ("אֶת-בְּנוֹ", "ולדה", "his child"),
        ("יְהוָה", "אללה", "so God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מְיַסְּרֶךָּ", "מודבך", "is disciplining you"),
    ],
    6: [
        ("וְשָׁמַרְתָּ", "ואחפץ'", "And keep"),
        ("אֶת-מִצְו‍ֹת יְהוָה", "וצאיאה", "His commandments"),
        ("אֱלֹהֶיךָ", "וסיר", "and walk"),
        ("לָלֶכֶת בִּדְרָכָיו", "פי טרקה", "in His ways"),
        ("וּלְיִרְאָה אֹתוֹ", "וכ'פה", "and fear Him"),
    ],
    7: [
        ("כִּי", "לאן", "For"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מְבִיאֲךָ", "מדכ'לך", "is bringing you"),
        ("אֶל-אֶרֶץ טוֹבָה", "אלי' בלד גייד", "into a good land"),
        ("אֶרֶץ נַחֲלֵי מָיִם", "בלד אודייה' מא", "a land of water-courses"),
        ("עֲיָנֹת", "ועיון", "springs"),
        ("וּתְהֹמֹת", "וג'מר", "and deeps"),
        ("יֹצְאִים", "תפגר", "that burst forth"),
        ("בַּבִּקְעָה", "פי בקאעה", "in its valleys"),
        ("וּבָהָר", "וגבאלה", "and its mountains"),
    ],
    8: [
        ("אֶרֶץ חִטָּה", "ארץ' חנטה", "a land of wheat"),
        ("וּשְׂעֹרָה", "ושעיר", "and barley"),
        ("וְגֶפֶן", "וגפן", "and vine"),
        ("וּתְאֵנָה", "ותין", "and fig"),
        ("וְרִמּוֹן", "ורמאן", "and pomegranate"),
        ("אֶרֶץ-זֵית שֶׁמֶן", "בלד זיתון זית", "a land of olive-oil"),
        ("וּדְבָשׁ", "ועסל", "and honey"),
    ],
    9: [
        ("אֶרֶץ אֲשֶׁר לֹא", "בלד לא", "a land in which you shall not"),
        ("בְמִסְכֵּנֻת", "בתקתיר", "in short measure"),
        ("תֹּאכַל-בָּהּ לֶחֶם", "תאכל פיה טעאמך", "eat your food"),
        ("לֹא-תֶחְסַר כֹּל בָּהּ", "ולא יעוזך פיה שייא", "and nothing shall be lacking to you therein"),
        ("אֶרֶץ אֲשֶׁר אֲבָנֶיהָ בַרְזֶל", "בלד מן חגארתה אלחדיד", "a land of which its stones are iron"),
        ("וּמֵהֲרָרֶיהָ תַּחְצֹב נְחֹשֶׁת", "ומן גבאלה אלנחאס", "and from its mountains, copper"),
    ],
    10: [
        (None, "פאד'א", "And when"),
        ("וְאָכַלְתָּ", "אכלת", "you have eaten"),
        ("וְשָׂבָעְתָּ", "ושבעת", "and are satisfied"),
        ("וּבֵרַכְתָּ", "פבארך", "bless"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("עַל-הָאָרֶץ הַטֹּבָה", "עלי' אלבלד אלגייד", "for the good land"),
        ("אֲשֶׁר נָתַן-לָךְ", "אלד'י אעטאך", "which He has given you"),
    ],
    11: [
        ("הִשָּׁמֶר לְךָ", "פאחד'ר", "Beware"),
        ("פֶּן-תִּשְׁכַּח", "אן תנסא", "lest you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְבִלְתִּי שְׁמֹר", "ללא תחפץ'", "by not keeping"),
        ("מִצְו‍ֹתָיו", "וצאיאה", "His commandments"),
        ("וּמִשְׁפָּטָיו", "ואחכאמה", "and His ordinances"),
        ("וְחֻקֹּתָיו", "ורסומה", "and His statutes"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלד'י אנא אמרך בהא", "which I charge you with"),
        ("הַיּוֹם", "אליום", "today"),
    ],
    12: [
        ("פֶּן-תֹּאכַל", "כלא תאכל", "Lest you eat"),
        ("וְשָׂבָעְתָּ", "ותשבע", "and be satisfied"),
        ("תִּבְנֶה", "תבניהא", "and build"),
        ("וּבָתִּים טֹבִים", "וביות חסאנא", "fine houses"),
        ("וְיָשָׁבְתָּ", "ותסכנהא", "and dwell in them"),
    ],
    13: [
        ("וּבְקָרְךָ", "ובקרך", "and your cattle"),
        ("וְצֹאנְךָ יִרְבְּיֻן", "וג'נמך יכת'ר", "and your flocks multiply"),
        ("וְכֶסֶף", "ופצ'ה", "and silver"),
        ("וְזָהָב יִרְבֶּה-לָּךְ", "וד'הב יכת'ר לך", "and gold multiply for you"),
        ("וְכֹל אֲשֶׁר-לְךָ יִרְבֶּה", "וגמיע מאלך יכת'ר", "and all that you have multiplies"),
    ],
    14: [
        ("וְרָם לְבָבֶךָ", "פירפעך קלבך", "and your heart becomes lifted up"),
        ("וְשָׁכַחְתָּ", "ותנסא", "and you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("הַמּוֹצִיאֲךָ", "אלד'י אכ'רגך", "who brought you out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן בלד מצר", "from the land of Egypt"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה", "from the house of bondage"),
    ],
    15: [
        ("הַמּוֹלִיכְךָ", "אלמסלכך", "who led you through"),
        ("בַּמִּדְבָּר הַגָּדֹל", "פי אלבר אלכביר", "the great"),
        ("וְהַנּוֹרָא", "אלמכ'יף", "and fearful wilderness"),
        ("נָחָשׁ שָׂרָף", "חית' אלחיאת אלמחרקה", "where there are burning serpents"),
        ("וְעַקְרָב", "ואלעקארב", "and scorpions"),
        ("וְצִמָּאוֹן", "ועטש", "and thirst"),
        ("אֲשֶׁר אֵין-מָיִם", "חית' ליס מא", "where there is no water"),
        ("הַמּוֹצִיא לְךָ מַיִם", "אלמכ'רג לך אלמא", "who brought out water for you"),
        ("מִצּוּר הַחַלָּמִישׁ", "מן אלצואן אלצלד", "from the hard flint-rock"),
    ],
    16: [
        ("הַמַּאֲכִלְךָ מָן", "אלמטעמך אלמן", "who fed you manna"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
        ("אֲשֶׁר לֹא-יָדְעוּן אֲבֹתֶיךָ", "מא לם יערפה אבאיך", "which your fathers had not known"),
        ("לְמַעַן עַנֹּתְךָ", "ליעד'בך", "to afflict you"),
        ("וּלְמַעַן נַסֹּתֶךָ", "וימתחנך", "and test you"),
        ("לְהֵיטִבְךָ בְּאַחֲרִיתֶךָ", "ויעווצך כ'ירא פי אכ'רתך", "and reward you with good in your latter end"),
    ],
    17: [
        (None, "פלא תקול", "And you shall not say"),
        ("בִּלְבָבֶךָ", "פי נפסך", "within yourself"),
        ("כֹּחִי", "אן קוותי", "'My strength"),
        ("וְעֹצֶם יָדִי", "ועצם קדרתי", "and the greatness of my power"),
        ("עָשָׂה לִי", "אכתסבת לי", "have gained me"),
        ("אֶת-הַחַיִל הַזֶּה", "הד'א אליסאר", "this prosperity.'"),
    ],
    18: [
        (None, "בל", "But"),
        ("וְזָכַרְתָּ", "אדכר", "remember"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("כִּי הוּא", "פאנה", "for it is He"),
        ("הַנֹּתֵן לְךָ כֹּחַ", "אלמעטיך קווה", "who gives you the power"),
        ("לַעֲשׂוֹת חָיִל", "תכתסב בהא אליסאר", "by which you gain prosperity"),
        ("לְמַעַן הָקִים אֶת-בְּרִיתוֹ", "לכי יאפי בעהדה", "that He may fulfill His covenant"),
        ("אֲשֶׁר-נִשְׁבַּע", "אלד'י קסם בה", "which He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
        ("כַּיּוֹם הַזֶּה", "כיומנא הד'א", "as on this day of ours"),
    ],
    19: [
        (None, "פאן", "And if"),
        ("וְהָיָה אִם-שָׁכֹחַ תִּשְׁכַּח", "נסית", "you forget"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְהָלַכְתָּ", "ומצ'ית", "and go off"),
        ("וַעֲבַדְתָּם", "ועבדת", "and worship"),
        ("אַחֲרֵי אֱלֹהִים אֲחֵרִים", "מעבודאת אכ'ר", "other objects of worship"),
        ("וְהִשְׁתַּחֲוִיתָ לָהֶם", "וסגדת להא", "and bow down to them"),
        ("הַעִדֹתִי בָכֶם", "פקד ערפתכם", "I make known to you"),
        ("הַיּוֹם", "מן אליום", "today"),
        ("כִּי אָבֹד תֹּאבֵדוּן", "אנכם סתבידון", "that you shall surely perish"),
    ],
    20: [
        ("כַּגּוֹיִם", "כאלאמם", "Like the nations"),
        ("אֲשֶׁר יְהוָה", "אלד'י אללה", "which God"),
        ("מַאֲבִיד מִפְּנֵיכֶם", "מבידהם מן בין ידיכם", "is destroying from before you"),
        ("כֵּן תֹּאבֵדוּן", "כד'אך תבידון", "so shall you perish"),
        ("עֵקֶב לֹא תִשְׁמְעוּן", "אד' לם תקבלו", "since you did not accept"),
        ("בְּקוֹל יְהוָה", "אמר אללה", "the command of God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
    ],
}
