"""Hand-authored alignment triples for Devarim chapter 7.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצאהרהם" ↔ "do not intermarry"), and Hebrew construct reorderings.
Words Saadia adds with no Hebrew source (glosses, expansions) carry he=None and
link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואזא", "And when"),
        ("כִּי יְבִיאֲךָ", "אדכ'לך", "brings you"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה", "אלזי אנת דאכ'ל אליה", "which you are entering"),
        ("לְרִשְׁתָּהּ", "לתחוזוה", "to possess it"),
        ("וְנָשַׁל", "פיטחטח", "and shatters"),
        ("גּוֹיִם-רַבִּים", "אממא כת'ירא", "many nations"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
        ("הַחִתִּי", "אלחתיין", "the Hittites"),
        ("וְהַגִּרְגָּשִׁי", "ואלגרגשיין", "and the Girgashites"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("וְהַכְּנַעֲנִי", "ואלכנעאניין", "and the Canaanites"),
        ("וְהַפְּרִזִּי", "ואלפרזיין", "and the Perizzites"),
        ("וְהַחִוִּי", "ואלחויין", "and the Hivites"),
        ("וְהַיְבוּסִי", "ואליבוסיין", "and the Jebusites"),
        ("שִׁבְעָה גוֹיִם", "סבעה' אממא", "seven nations"),
        ("רַבִּים", "אכת'ר", "more numerous"),
        ("וַעֲצוּמִים", "וא עצ'ם", "and stronger"),
        ("מִמֶּךָּ", "מנך", "than you"),
    ],
    2: [
        ("וּנְתָנָם", "פיסלמהם", "will deliver them"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְפָנֶיךָ", "פי ידך", "into your hands"),
        ("וְהִכִּיתָם", "פאקתלהמ", "so kill them"),
        ("הַחֲרֵם תַּחֲרִים", "ואתלפהם תלפא", "and destroy them utterly"),
        ("לֹא-תִכְרֹת", "ולא תעהד", "and do not make"),
        ("לָהֶם", "מעהם", "with them"),
        ("בְּרִית", "עהדא", "a covenant"),
        ("וְלֹא תְחָנֵּם", "ולא תרוף עליהמ", "and do not show compassion upon them"),
    ],
    3: [
        ("וְלֹא תִתְחַתֵּן", "ולא תצאהרהמ", "And do not intermarry with them"),
        ("בִּתְּךָ", "פתעטי אבנתך", "do not give your daughter"),
        ("לִבְנוֹ", "לאבנה", "to his son"),
        ("וּבִתּוֹ", "ולא תאכ'זאבנתה", "and do not take his daughter"),
        ("לִבְנֶךָ", "לאבנך", "for your son"),
    ],
    4: [
        ("כִּי-יָסִיר", "פאנהם יזילון", "For they will turn"),
        ("אֶת-בִּנְךָ", "אבנך", "your son"),
        ("מֵאַחֲרַי", "ען טאעתי", "away from obedience to Me"),
        ("וְעָבְדוּ", "ויעבדון", "and they will serve"),
        ("אֱלֹהִים אֲחֵרִים", "אלאהה' אכ'ר", "other objects of worship"),
        ("וְחָרָה אַף-יְהוָה", "וישתד ג'צ'ב אללה", "and the anger of God will grow fierce"),
        ("בָּכֶם", "עליך", "against you"),
        ("וְהִשְׁמִידְךָ", "וינפזך", "and He will destroy you"),
        ("מַהֵר", "סריעא", "swiftly"),
    ],
    5: [
        ("כִּי-אִם-כֹּה", "בל כזא", "Rather, thus"),
        ("תַעֲשׂוּ", "פאצנעו", "shall you do"),
        ("לָהֶם", "להמ", "to them"),
        ("מִזְבְּחֹתֵיהֶם", "מזאבחהם", "their altars"),
        ("תִּתֹּצוּ", "פאנקצ'ו", "demolish"),
        ("וּמַצֵּבֹתָם", "ודכאכהם", "and their pillars"),
        ("תְּשַׁבֵּרוּ", "פכסרו", "shatter"),
        ("וַאֲשֵׁירֵהֶם", "וסואריהם", "and their sacred poles"),
        ("תְּגַדֵּעוּן", "תגדעו", "cut down"),
        ("וּפְסִילֵיהֶם", "ופסולהם", "and their carved idols"),
        ("תִּשְׂרְפוּן", "פאחרקוהא", "burn"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
    ],
    6: [
        ("כִּי", "לאנך", "For you"),
        ("עַם", "שעב", "are a people"),
        ("קָדוֹשׁ", "מקדס", "consecrated"),
        ("אַתָּה", "ללה", "to God"),
        ("לַיהוָה", "רבך", "your Lord"),
        ("אֱלֹהֶיךָ", "ובך", "and He"),
        ("בְּךָ בָּחַר", "אכ'תאר", "chose you"),
        ("לִהְיוֹת לוֹ לְעַם", "אן תכון לה אמה", "to be for Him a special nation"),
        ("סְגֻלָּה", "כ'אצה", "a special nation"),
        ("מִכֹּל הָעַמִּים", "מן גמיע אלשעוב", "from among all the peoples"),
        ("אֲשֶׁר עַל-פְּנֵי הָאֲדָמָה", "אלזי עלי' וגה אלארץ'", "who are upon the face of the earth"),
    ],
    7: [
        ("לֹא", "וליס", "It was not"),
        ("מֵרֻבְּכֶם", "מן כת'רתכם", "because of your being more numerous"),
        ("מִכָּל-הָעַמִּים", "מן גמיע אלאממ", "than all the nations"),
        ("חָשַׁק", "אצטפאכם", "selected"),
        ("יְהוָה", "אללה", "God"),
        ("בָּכֶם", "ואכ'תארכמ", "and chose you"),
        (None, "בל", "rather"),
        ("כִּי-אַתֶּם", "אנتم", "you are"),
        ("הַמְעַט", "אقل", "the fewest"),
        ("מִכָּל-הָעַמִּים", "منهم", "of them"),
        (None, "מגמועין", "all together"),
    ],
    8: [
        (None, "לכן", "But"),
        ("כִּי מֵאַהֲבַת", "מן מחבה'", "from God's love"),
        ("יְהוָה", "אללה", "God"),
        ("אֶתְכֶם", "לכמ", "for you"),
        ("וּמִשָּׁמְרוֹ", "ומן חפצ'ה", "and from His keeping"),
        ("אֶת-הַשְּׁבֻעָה", "לכם אלימין", "for you the oath"),
        ("אֲשֶׁר נִשְׁבַּע", "אלזי קסם בה", "which He swore"),
        ("לַאֲבֹתֵיכֶם", "לאבאיכמ", "to your fathers"),
        ("הוֹצִיא", "אכ'רגכם", "brought you out"),
        ("יְהוָה", "אללה", "God"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a mighty hand"),
        ("וַיִּפְדְּךָ", "ופדאך", "and redeemed you"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעبودייה", "from the house of bondage"),
        ("מִיַּד פַּרְעֹה", "מן יד פרעון", "from the hand of Pharaoh"),
        ("מֶלֶךְ-מִצְרָיִם", "מלך מצר", "king of Egypt"),
    ],
    9: [
        ("וְיָדַעְתָּ", "פאעלמ", "Know"),
        (None, "אן", "then"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("הוּא", "הו", "He is"),
        ("הָאֱלֹהִים", "אלאלאה", "the God"),
        ("הָאֵל הַנֶּאֱמָן", "אלטאיק אלאמין", "the Capable, the Faithful"),
        ("שֹׁמֵר הַבְּרִית", "חאפץ אלעהד", "who keeps the covenant"),
        ("וְהַחֶסֶד", "ואלאחסאן", "and the kindness"),
        ("לְאֹהֲבָיו", "למחביה", "for those who love Him"),
        ("וּלְשֹׁמְרֵי מִצְו‍ֹתָו", "וחאפצ'י וצאיאה", "and keep His commandments"),
        ("לְאֶלֶף דּוֹר", "לאלף גיל", "unto a thousand generations"),
    ],
    10: [
        ("וּמְשַׁלֵּם", "ומכאפי", "and who requites"),
        ("לְשֹׂנְאָיו", "שאניה", "His enemy"),
        ("אֶל-פָּנָיו", "בחצ'רתה", "in His presence"),
        ("לְהַאֲבִידוֹ", "לאנפאזה", "to destroy him"),
        ("לֹא יְאַחֵר", "ולא י'וכ'ר", "He will not delay"),
        (None, "לה שייא", "anything for him"),
        ("אֶל-פָּנָיו", "בל בחצ'רתה", "rather, in his presence"),
        ("יְשַׁלֶּם-לוֹ", "יכאפיה", "He requites him"),
    ],
    11: [
        ("וְשָׁמַרְתָּ", "ואחפץ'", "And keep"),
        ("אֶת-הַמִּצְוָה", "אלוצאיא", "the commandments"),
        ("וְאֶת-הַחֻקִּים", "ואלרסום", "and the statutes"),
        ("וְאֶת-הַמִּשְׁפָּטִים", "ואלאחכאמ", "and the ordinances"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("אָנֹכִי מְצַוְּךָ", "אנא אמרך", "I am commanding you"),
        ("הַיּוֹם", "בהא", "today"),
        ("לַעֲשׂוֹתָם", "אליום ואعمل בהא", "and act by them"),
    ],
    12: [
        ("וְהָיָה", "פיכון", "And it shall be"),
        ("עֵקֶב", "גזא", "as recompense"),
        ("תִּשְׁמְעוּן", "מא תסמעון", "for your heeding"),
        ("אֵת הַמִּשְׁפָּטִים הָאֵלֶּה", "הד'ה אלאחכאם", "these ordinances"),
        ("וּשְׁמַרְתֶּם", "ותחפצוהא", "and keeping them"),
        ("וַעֲשִׂיתֶם אֹתָם", "ותعمלוהא", "and acting by them"),
        ("וְשָׁמַר", "יחפץ'", "will keep"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְךָ", "לך", "for you"),
        ("אֶת-הַבְּרִית", "אלעהד", "the covenant"),
        ("וְאֶת-הַחֶסֶד", "ואלפצ'ל", "and the grace"),
        ("אֲשֶׁר נִשְׁבַּע", "אלד'י קסם", "which He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
    ],
    13: [
        ("וַאֲהֵבְךָ", "פיחבבך", "And He will love you"),
        ("וּבֵרַכְךָ", "ויבארך פיך", "and bless you"),
        ("וְהִרְבֶּךָ", "ויכת'רך", "and multiply you"),
        ("וּבֵרַךְ", "ויבארך", "and He will bless"),
        ("פְּרִי-בִטְנְךָ", "פי ת'מרך", "your fruit"),
        ("וּפְרִי-אַדְמָתֶךָ", "ות'מר ארצ'ך", "and the fruit of your land"),
        ("דְּגָנְךָ", "ברך", "your grain"),
        ("וְתִירֹשְׁךָ", "ועצירך", "and your juice"),
        ("וְיִצְהָרֶךָ", "וד'הנך", "and your oil"),
        ("שְׁגַר-אֲלָפֶיךָ", "נתאג בקרך", "the offspring of your cattle"),
        ("וְעַשְׁתְּרֹת צֹאנֶךָ", "וגפראת ג'נמך", "and the increase of your flock"),
        ("עַל הָאֲדָמָה", "פי אלبלד", "in the land"),
        ("אֲשֶׁר-נִשְׁבַּע", "אלד'י קסם", "which He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
        ("לָתֶת לָךְ", "אן יعטיכהא", "to give you"),
    ],
    14: [
        ("בָּרוּךְ תִּהְיֶה", "ותכון מבארך", "And you shall be blessed"),
        ("מִכָּל-הָעַמִּים", "מן גמיע אלאמם", "above all nations"),
        ("לֹא-יִהְיֶה", "ולא יכון", "there shall remain"),
        ("בְךָ", "פיך", "among you"),
        ("עָקָר", "עאקר", "neither barren man"),
        ("וַעֲקָרָה", "ולא עاקרה", "nor barren woman"),
        ("וּבִבְהֶמְתֶּךָ", "ולא פי בهاימך", "nor among your beasts"),
    ],
    15: [
        ("וְהֵסִיר", "ויزיل", "And God will remove"),
        ("יְהוָה", "אللה", "God"),
        ("מִמְּךָ", "מנك", "from you"),
        ("כָּל-חֹלִי", "כل מרץ'", "every illness"),
        ("וְכָל-מַדְוֵי", "וגמיع אדוי", "and all the evil afflictions"),
        ("מִצְרַיִם", "מצר", "of Egypt"),
        ("הָרָעִים", "אלرדייה", "the evil"),
        ("אֲשֶׁר יָדַעְתָּ", "אلتי תערפהא", "which you know"),
        ("לֹא יְשִׂימָם", "לא יחל", "He will not bring"),
        ("בָּךְ", "בך שייא מנהא", "any of them upon you"),
        ("וּנְתָנָם", "בל יחלהא", "but will bring them"),
        ("בְּכָל-שֹׂנְאֶיךָ", "בשאניך", "upon those who hate you"),
    ],
    16: [
        ("וְאָכַלְתָּ", "פתפני", "And you shall destroy"),
        ("אֶת-כָּל-הָעַמִּים", "גמיע אלשעוב", "all the peoples"),
        ("אֲשֶׁר", "אלד'י", "whom"),
        ("יְהוָה", "יعطيك אллה", "God your Lord gives you"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לֹא-תָחוֹס", "לא תשפק", "do not show compassion"),
        ("עֵינְךָ עֲלֵיהֶם", "עליهم", "upon them"),
        ("וְלֹא תַעֲבֹד", "ולا תعبد", "and do not serve"),
        ("אֶת-אֱלֹהֵיהֶם", "מعבודאتهם", "their objects of worship"),
        ("כִּי-מוֹקֵשׁ הוּא לָךְ", "פيכونו לך והקא", "for they would become a noose for you"),
    ],
    17: [
        ("כִּי תֹאמַר", "פאן קלת", "If you say"),
        ("בִּלְבָבְךָ", "פי נפסך", "to yourself"),
        ("רַבִּים", "הولاי אלאמם אكת'ר", "These nations are more numerous"),
        ("הַגּוֹיִם הָאֵלֶּה", "מני", "than I"),
        ("מִמֶּנִּי", "פכיף", "how"),
        ("אֵיכָה אוּכַל", "אطיק אן", "can I manage"),
        ("לְהוֹרִישָׁם", "אקרצ'הם", "to gnaw them away"),
    ],
    18: [
        ("לֹא תִירָא", "לא תك'אפהם", "do not fear them"),
        (None, "בל", "rather"),
        ("זָכֹר תִּזְכֹּר", "אד'כר", "remember"),
        ("אֵת אֲשֶׁר-עָשָׂה", "מא צנע", "what did"),
        ("יְהוָה", "אللה", "God"),
        ("אֱלֹהֶיךָ", "רبך", "your Lord"),
        ("לְפַרְעֹה", "לפרعון", "to Pharaoh"),
        ("וּלְכָל-מִצְרָיִם", "וسאיר אלמצריון", "and to the rest of the Egyptians"),
    ],
    19: [
        ("הַמַּסֹּת הַגְּדֹלֹת", "אלאعלאם אלعצי'מה", "the great signs"),
        ("אֲשֶׁר-רָאוּ עֵינֶיךָ", "אلتי ראתהא עינאך", "which your eyes saw"),
        ("וְהָאֹתֹת", "ואלאיאת", "and the wonders"),
        ("וְהַמֹּפְתִים", "ואלבראהין", "and the proofs"),
        ("וְהַיָּד הַחֲזָקָה", "ואליד אלשדידה", "and the mighty hand"),
        ("וְהַזְּרֹעַ הַנְּטוּיָה", "ואלדראع אלממדודה", "and the outstretched arm"),
        ("אֲשֶׁר הוֹצִיאֲךָ", "כמא אכ'רגך", "just as brought you out"),
        ("יְהוָה", "אللה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("כֵּן-יַעֲשֶׂה", "כד'אך יצנע", "so He will do"),
        ("יְהוָה אֱלֹהֶיךָ", "בגמיع אלאמם", "to all the nations"),
        ("לְכָל-הָעַמִּים", "אלד'ין", "whom"),
        ("אֲשֶׁר-אַתָּה יָרֵא מִפְּנֵיהֶם", "תכ'אפהם", "you fear"),
    ],
    20: [
        ("וְגַם אֶת-הַצִּרְעָה", "ויבعת' באלعאהה", "And He will send the plague"),
        ("יְשַׁלַּח יְהוָה אֱלֹהֶיךָ", "פיהם", "among them"),
        ("עַד-אֲבֹד", "חתי' יביד", "until are destroyed"),
        ("הַנִּשְׁאָרִים", "אלבאקיון", "those remaining"),
        ("וְהַנִּסְתָּרִים", "ואלמנסתרון", "and those hidden"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
    ],
    21: [
        ("לֹא תַעֲרֹץ", "לא תرهבהם", "Do not be in dread of them"),
        ("כִּי", "לان", "for"),
        (None, "נור", "the light of"),
        ("יְהוָה", "אللה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בְּקִרְבֶּךָ", "פי מא בינך", "is in your midst"),
        ("אֵל גָּדוֹל", "אלطאיק אל עצ'ים", "the Capable, the great"),
        ("וְנוֹרָא", "אלמכ'יף", "the awe-inspiring"),
    ],
    22: [
        ("וְנָשַׁל", "והو יطחטח", "And He will shatter"),
        ("יְהוָה אֱלֹהֶיךָ", "אולאיך אלאמם", "those nations"),
        ("אֶת-הַגּוֹיִם הָאֵל", "מן בין ידיך", "from before you"),
        ("מִפָּנֶיךָ", "קלילא קלילא", "little by little"),
        ("מְעַט מְעָט", "אד'", "since"),
        ("לֹא תוּכַל", "לא תطيق אן", "you cannot manage"),
        ("כַּלֹּתָם", "תفניהם", "to destroy them"),
        ("מַהֵר", "סריעא", "quickly"),
        ("פֶּן-תִּרְבֶּה", "כלא יכت'ר", "lest multiply"),
        ("עָלֶיךָ", "עليך", "upon you"),
        ("חַיַּת הַשָּׂדֶה", "וחش אלצחרא", "the wild creatures of the wilderness"),
    ],
    23: [
        ("וּנְתָנָם", "פאד'א אסלמהם", "But when delivers"),
        ("יְהוָה", "אللה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לְפָנֶיךָ", "פי ידך", "into your hand"),
        ("וְהָמָם", "פאהאמהם", "He will throw them"),
        ("מְהוּמָה גְדֹלָה", "אהאמה ]עط'ימה] עצ'ימה", "into great confusion"),
        ("עַד הִשָּׁמְדָם", "אלי' אנפאד'הם", "until they are destroyed"),
    ],
    24: [
        ("וְנָתַן", "ויסלم", "And He will deliver"),
        ("מַלְכֵיהֶם", "מלוכהם", "their kings"),
        ("בְּיָדֶךָ", "פי ידך", "into your hand"),
        ("וְהַאֲבַדְתָּ", "פאבד", "and you shall blot out"),
        ("אֶת-שְׁמָם", "אסמאיהם", "their names"),
        ("מִתַּחַת הַשָּׁמָיִם", "מן תחת אלسما", "from under the sky"),
        ("לֹא-יִתְיַצֵּב", "לא יקף", "no man shall stand"),
        ("אִישׁ בְּפָנֶיךָ", "אנسאן בין ידיך", "before you"),
        ("עַד הִשְׁמִדְךָ אֹתָם", "אלי' אן תנפד'הם", "until you have destroyed them"),
    ],
    25: [
        ("פְּסִילֵי אֱלֹהֵיהֶם", "ואחרקו פסול מעبודאתهם", "And burn the carved idols of their objects of worship"),
        ("תִּשְׂרְפוּן בָּאֵשׁ", "באלنאר", "with fire"),
        ("לֹא-תַחְמֹד", "ולא תتمן שייא", "and do not covet any"),
        ("כֶּסֶף", "מן אלפצ'ה", "of the silver"),
        ("וְזָהָב", "ואלד'הב", "and gold"),
        ("עֲלֵיהֶם", "אלד'י עליهם", "that is upon them"),
        ("וְלָקַחְתָּ לָךְ", "ותאك'ד'ה לך", "so as to take it for yourself"),
        ("פֶּן תִּוָּקֵשׁ בּוֹ", "כלא תوהק בה", "lest you be ensnared by it"),
        ("כִּי תוֹעֲבַת יְהוָה אֱלֹהֶיךָ הוּא", "לאנה כריהה ללה רبך", "for it is something abhorrent to God your Lord"),
    ],
    26: [
        ("וְלֹא-תָבִיא", "ולא תדכ'ل", "And do not bring"),
        ("תוֹעֵבָה", "מא יכרהه אللה", "what God abhors"),
        ("אֶל-בֵּיתֶךָ", "אלי' ביتך", "into your house"),
        ("וְהָיִיתָ", "ותציר", "lest you become"),
        ("חֵרֶם כָּמֹהוּ", "מתلופא מت'לה", "doomed like it"),
        ("שַׁקֵּץ תְּשַׁקְּצֶנּוּ", "בל רגسה תרגיסא", "rather, utterly abominate it"),
        ("וְתַעֵב תְּתַעֲבֶנּוּ", "ואכרهه כריהה", "and utterly abhor it"),
        ("כִּי-חֵרֶם הוּא", "אד' הو מתלוף", "for it is doomed"),
    ],
}
