"""Hand-authored alignment triples for Devarim chapter 24.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers divorce and remarriage (vv. 1–4), the new groom's
exemption (v. 5), the millstone pledge (v. 6), kidnapping (v. 7), leprosy
(vv. 8–9), pledge laws (vv. 10–13), the hired hand (vv. 14–15), individual
liability (v. 16), justice for the vulnerable (v. 17), the Egypt-memory
motive (vv. 18, 22), and gleanings for the stranger/orphan/widow (vv. 19–21).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("כִּי-יִקַּח אִישׁ", "ואד'א תזווג רגל", "And when a man marries"),
        ("אִשָּׁה", "אמראה", "a woman"),
        ("וּבְעָלָהּ", "ומלכהא", "and takes possession of her"),
        (None, "ת'ם", "then"),
        ("אִם-לֹא תִמְצָא-חֵן", "אנהא לם תגד חצ'אא", "if she has not found favour"),
        ("בְּעֵינָיו", "ענדה", "with him"),
        ("כִּי-מָצָא", "או וגד", "or he has found"),
        ("בָהּ עֶרְוַת דָּבָר", "עליהא אמרא קביחא", "upon her an unseemly matter"),
        ("וְכָתַב לָהּ", "פליכתב להא", "let him write her"),
        ("סֵפֶר כְּרִיתֻת", "כתאב קטעה", "a bill of severance"),
        ("וְנָתַן", "וידפעה", "and deliver it"),
        ("בְּיָדָהּ", "אליהא", "to her"),
        ("וְשִׁלְּחָהּ", "ויטלקהא", "and release her"),
        ("מִבֵּיתוֹ", "מנה", "from him"),
    ],
    2: [
        ("וְיָצְאָה", "ואן כ'רגת", "And if she departs"),
        ("מִבֵּיתוֹ", "מן מנזלה", "from his dwelling"),
        ("וְהָלְכָה", "ומצ'ת", "and goes"),
        ("וְהָיְתָה", "וצארת", "and becomes"),
        ("לְאִישׁ-אַחֵר", "לרגל אכ'ר", "another man's"),
    ],
    3: [
        ("וּשְׂנֵאָהּ", "פשנאהא", "then the other man rejects her"),
        ("הָאִישׁ הָאַחֲרוֹן", "אלרגל אלאכ'ר", "the other man"),
        ("וְכָתַב לָהּ", "וכתב להא", "and writes her"),
        ("סֵפֶר כְּרִיתֻת", "כתאב קטעה", "a bill of severance"),
        ("וְנָתַן בְּיָדָהּ", "ודפעה אליהא", "and delivers it to her"),
        ("וְשִׁלְּחָהּ מִבֵּיתוֹ", "וטלקהא", "and divorces her"),
        ("אוֹ כִי יָמוּת", "או מאת", "dies —"),
        ("הָאִישׁ הָאַחֲרוֹן", "אלרגל אלאכ'ר", "who took her"),
        ("אֲשֶׁר-לְקָחָהּ לוֹ לְאִשָּׁה", "אלד'י אתכ'דהא לה זוגה", "as his wife"),
    ],
    4: [
        ("לֹא-יוּכַל", "פלא יחל", "it is not permitted"),
        ("בַּעְלָהּ הָרִאשׁוֹן", "לבעלהא אלאוול", "for her first husband"),
        ("אֲשֶׁר-שִׁלְּחָהּ", "אלד'י טלקהא", "who divorced her"),
        ("לָשׁוּב לְקַחְתָּהּ", "ליעוד יתזווג בהא", "to return and marry her again"),
        ("לִהְיוֹת לוֹ לְאִשָּׁה", "לתכון לה זוגה", "so that she should be his wife"),
        ("אַחֲרֵי אֲשֶׁר הֻטַּמָּאָה", "בעד מא אתאהא ג'ירה", "after another has come to her"),
        ("כִּי-תוֹעֵבָה הִוא", "פאנהא כריהה", "for she is loathsome"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("וְלֹא תַחֲטִיא", "ולא תוקע כ'טא", "And do not bring sin"),
        ("אֶת-הָאָרֶץ", "עלי' בלדך", "upon your land"),
        ("אֲשֶׁר יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לְךָ נַחֲלָה", "מעטיך נחלה", "is giving you as an inheritance"),
    ],
    5: [
        ("כִּי-יִקַּח אִישׁ", "ואד'א תזווג רגל", "And when a man marries"),
        ("אִשָּׁה חֲדָשָׁה", "אמראה גדידה", "a new woman"),
        ("לֹא יֵצֵא", "פלא יכ'רג", "he shall not go out"),
        ("בַּצָּבָא", "פי אלגיש", "in the army"),
        ("וְלֹא-יַעֲבֹר עָלָיו לְכָל-דָּבָר", "ולא י'מר בה שייא מן אמורה", "nor shall any matter of his affairs pass over him"),
        ("נָקִי יִהְיֶה", "בל יכון פארג'א", "rather, he shall be free"),
        ("לְבֵיתוֹ", "לביתה", "for his household"),
        ("שָׁנָה אֶחָת", "סנה ואחדה", "for one year"),
        ("וְשִׂמַּח", "ויפרח", "and shall gladden"),
        ("אֶת-אִשְׁתּוֹ", "זוגתה", "his wife"),
        ("אֲשֶׁר-לָקָח", "אלתי אתכ'ד'הא", "whom he has taken"),
    ],
    6: [
        ("לֹא-יַחֲבֹל רֵחַיִם", "ולא יסתרהן אחד אלרחא", "And no one shall take as pledge"),
        ("וָרָכֶב", "אלספלא ואלעליא", "the lower and upper millstones"),
        ("כִּי-נֶפֶשׁ הוּא חֹבֵל", "פאנה יסתרהן קות אלנפוס", "for he would be taking the sustenance of life as pledge"),
    ],
    7: [
        ("כִּי-יִמָּצֵא אִישׁ", "ואן וגד אנסאן", "And if a person is found"),
        ("גֹּנֵב נֶפֶשׁ", "קד סרק נפסא", "who has stolen a soul"),
        ("מֵאֶחָיו", "מן אכ'ותה", "from his brothers"),
        ("מִבְּנֵי יִשְׂרָאֵל", "מן בני אסראיל", "among the sons of Israel"),
        ("וְהִתְעַמֶּר-בּוֹ", "ואסתרקהא", "and enslaved him"),
        ("וּמְכָרוֹ", "ובאעהא", "or sold him"),
        ("וּמֵת הַגַּנָּב הַהוּא", "פאקתל ד'אלך אלסארק", "execute that thief"),
        ("וּבִעַרְתָּ הָרָע מִקִּרְבֶּךָ", "ואנף אהל אלשר מן בינכם", "and banish the people of evil from among you"),
    ],
    8: [
        ("הִשָּׁמֶר", "ואחתרז", "And be on guard"),
        ("בְּנֶגַע-הַצָּרַעַת", "מן בלא אלברץ", "against the affliction of leprosy"),
        ("לִשְׁמֹר מְאֹד", "ואחפץ' רסומה גדא", "and observe its ordinances very carefully"),
        ("וְלַעֲשׂוֹת", "ואעמל פיה", "and act accordingly"),
        ("כְּכֹל אֲשֶׁר-יוֹרוּ אֶתְכֶם", "כמא יפתוכם", "shall instruct you"),
        ("הַכֹּהֲנִים הַלְוִיִּם", "אלאימה אלליואניין", "the Levitical imāms"),
        ("כַּאֲשֶׁר צִוִּיתִם", "כמא אמרתהם", "as I commanded them"),
    ],
    9: [
        ("זָכוֹר", "ואד'כר", "And remember"),
        ("אֵת אֲשֶׁר-עָשָׂה", "עלי' מא צנע", "what"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord did"),
        (None, "מת'לה", "in like manner"),
        ("לְמִרְיָם", "במרים", "to Miriam"),
        ("בַּדֶּרֶךְ", "פי אלטריק", "on the way"),
        ("בְּצֵאתְכֶם", "פי כ'רוגכם", "when you went out"),
        ("מִמִּצְרָיִם", "מן מצר", "of Egypt"),
    ],
    10: [
        ("כִּי-תַשֶּׁה", "ואד'א אנסית", "And when you lend"),
        ("בְרֵעֲךָ", "צאחבך", "your fellow"),
        ("מַשַּׁאת מְאוּמָה", "נסייה", "a loan"),
        ("לֹא-תָבֹא", "פלא תדכ'ל", "do not enter"),
        ("אֶל-בֵּיתוֹ", "אלי' מנזלה", "his dwelling"),
        ("לַעֲבֹט עֲבֹטוֹ", "פתאכ'ד' עוצ'הא", "to take its pledge"),
    ],
    11: [
        ("בַּחוּץ תַּעֲמֹד", "בל קף כ'ארגא", "Rather, stand outside"),
        ("וְהָאִישׁ", "ואלרג'ל", "and the man"),
        ("אֲשֶׁר אַתָּה נֹשֶׁה בוֹ", "אלד'י אנסיתה", "to whom you have given the loan"),
        ("יוֹצִיא אֵלֶיךָ", "יכ'רג לך", "shall bring"),
        ("אֶת-הַעֲבוֹט הַחוּצָה", "אלעווץ' אלי' ברא", "the pledge out to you"),
    ],
    12: [
        ("וְאִם-אִישׁ עָנִי הוּא", "ואן כאן רגלא צ'עיפא", "And if he is a man of meagre means"),
        ("לֹא תִשְׁכַּב בַּעֲבֹטוֹ", "פלא תבית ועוצה ענדך", "do not spend the night with his pledge in your possession"),
    ],
    13: [
        (None, "בל", "Rather"),
        ("הָשֵׁב תָּשִׁיב לוֹ", "רדה אליה רדא", "return it to him"),
        ("כְּבוֹא הַשֶּׁמֶשׁ", "ענד מגיב אלשמס", "at the setting of the sun"),
        ("וְשָׁכַב בְּשַׂלְמָתוֹ", "אד' ינאם פיה", "that he may sleep in it"),
        ("וּבֵרְכֶךָּ", "פידעו לך", "and pray for you"),
        ("וּלְךָ תִּהְיֶה צְדָקָה", "ותכון לך חסנה", "and it shall be accounted a good deed for you"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
    ],
    14: [
        ("לֹא-תַעֲשֹׁק", "לא תג'שם", "Do not defraud"),
        ("שָׂכִיר", "אגירא", "a hired hand"),
        ("עָנִי", "וכ'אצה צ'עיף", "and especially one who is poor"),
        ("וְאֶבְיוֹן", "או מסכין", "or needy"),
        ("מֵאַחֶיךָ", "מן אכ'ותך", "whether from your brothers"),
        ("אוֹ מִגֵּרְךָ", "או מן צ'יפך", "or from your guest"),
        ("אֲשֶׁר בְּאַרְצְךָ", "אלד'י פי בלדך", "who is in your land"),
        ("בִּשְׁעָרֶיךָ", "פי מחאלך", "in your settlements"),
    ],
    15: [
        ("בְּיוֹמוֹ תִתֵּן שְׂכָרוֹ", "בל אדפע אליה אגרתה פי יומה", "Rather, pay him his wage on the same day"),
        ("וְלֹא-תָבוֹא עָלָיו הַשֶּׁמֶשׁ", "מן קבל אן תג'יב אלשמס", "before the sun sets"),
        ("כִּי עָנִי הוּא", "פאנה צ'עיף", "for he is poor"),
        ("וְאֵלָיו הוּא נֹשֵׂא אֶת-נַפְשׁוֹ", "ועליה קד כ'אטר בנפסה", "and for this he has risked himself"),
        ("וְלֹא-יִקְרָא עָלֶיךָ", "ולא ידעו עליך", "lest he call out against you"),
        ("אֶל-יְהוָה", "אלי' אללה", "to God"),
        ("וְהָיָה בְךָ חֵטְא", "פתחל בך עקובה", "and a penalty befall you"),
    ],
    16: [
        ("לֹא-יוּמְתוּ אָבוֹת עַל-בָּנִים", "ולא יקתל אלאבא ען אלבנין", "Fathers shall not be put to death for sons"),
        ("וּבָנִים לֹא-יוּמְתוּ עַל-אָבוֹת", "ולא אלבנין עלי' אלאבא", "nor sons for fathers"),
        ("אִישׁ בְּחֶטְאוֹ יוּמָתוּ", "בל יקתל כל אמר בכ'טייתה", "rather, every person shall be put to death for his own transgression"),
    ],
    17: [
        ("לֹא תַטֶּה", "ולא תמייל", "And do not pervert"),
        ("מִשְׁפַּט גֵּר", "חכם ג'ריב", "the judgement of a stranger"),
        ("יָתוֹם", "או יתים", "or an orphan"),
        ("וְלֹא תַחֲבֹל", "ולא תסתרהן", "and do not take"),
        ("בֶּגֶד אַלְמָנָה", "ת'וב אלארמלה", "the garment of a widow as pledge"),
    ],
    18: [
        ("וְזָכַרְתָּ", "ואד'כר", "And remember"),
        ("כִּי עֶבֶד הָיִיתָ", "אנך כנת עבדא", "that you were a slave"),
        ("בְּמִצְרַיִם", "במצר", "in Egypt"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וַיִּפְדְּךָ", "ופכך", "redeemed you"),
        ("מִשָּׁם", "מן ת'ם", "from there"),
        ("עַל-כֵּן", "ולדאלך", "and therefore"),
        ("אָנֹכִי מְצַוְּךָ", "אנא אמרך", "I command you"),
        ("לַעֲשׂוֹת", "באן תצנע", "to do"),
        ("אֶת-הַדָּבָר הַזֶּה", "הד'ה אלאמור", "these things"),
    ],
    19: [
        ("כִּי תִקְצֹר", "ואד'א חצדת", "And when you reap"),
        ("קְצִירְךָ", "חצאדך", "your harvest"),
        ("בְשָׂדֶךָ", "פי צ'יעתך", "in your field"),
        ("וְשָׁכַחְתָּ", "ונסית", "and you forget"),
        ("עֹמֶר", "כפה", "a sheaf"),
        ("בַּשָּׂדֶה", "פי אלצחרא", "in the open country"),
        ("לֹא תָשׁוּב לְקַחְתּוֹ", "פלא תרגע פתאכ'ד'הא", "do not go back to take it"),
        ("לַגֵּר", "בל יכון לאלג'ריב", "rather, let it be for the stranger"),
        ("לַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְלָאַלְמָנָה יִהְיֶה", "ואלארמלה", "and the widow"),
        ("לְמַעַן יְבָרֶכְךָ יְהוָה אֱלֹהֶיךָ", "לכי יבארך לך אללה רבך", "so that God your Lord may bless you"),
        ("בְּכֹל מַעֲשֵׂה יָדֶיךָ", "פי גמיע עמל ידך", "in all the work of your hands"),
    ],
    20: [
        ("כִּי תַחְבֹּט זֵיתְךָ", "ואד'א כ'רטת זיתונך", "And when you beat your olive trees"),
        ("לֹא תְפַאֵר אַחֲרֶיךָ", "פלא תסתקצה בעד ד'אלך", "do not go over them again afterwards"),
        ("לַגֵּר", "בל יכון לאלג'ריב", "rather, let it be for the stranger"),
        ("לַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְלָאַלְמָנָה יִהְיֶה", "ואלארמלה", "and the widow"),
    ],
    21: [
        ("כִּי תִבְצֹר כַּרְמְךָ", "ואד'א קטפת כרמך", "And when you harvest your vineyard"),
        ("לֹא תְעוֹלֵל אַחֲרֶיךָ", "פלא תמושה בעד ד'אלך", "do not glean it afterwards"),
        ("לַגֵּר", "בל יכון לאלג'ריב", "rather, let it be for the stranger"),
        ("לַיָּתוֹם", "ואליתים", "and the orphan"),
        ("וְלָאַלְמָנָה יִהְיֶה", "ואלארמלה", "and the widow"),
    ],
    22: [
        ("וְזָכַרְתָּ", "ואד'כר", "And remember"),
        ("כִּי-עֶבֶד הָיִיתָ", "אנך כנת עבדא", "that you were a slave"),
        ("בְּאֶרֶץ מִצְרָיִם", "פי בלד מצר", "in the land of Egypt"),
        ("עַל-כֵּן", "ולדאלך", "and therefore"),
        ("אָנֹכִי מְצַוְּךָ", "אנא אמרך", "I command you"),
        ("לַעֲשׂוֹת", "באן תצנע", "to do"),
        ("אֶת-הַדָּבָר הַזֶּה", "הד'ה אלאמור", "these things"),
    ],
}
