"""Hand-authored alignment triples for Devarim chapter 32.

Ha'azinu — the Song of Moses (52 verses). Highly poetic with parallelism,
divine epithets (הַצּוּר rendered by Saadia as אלכ'אלק / אלמעתמד), and vivid
imagery of rain, eagle, rock-honey, divine wrath, and eschatological vengeance.

Saadia frequently paraphrases the poetry rather than translating word-for-word:
  • הַצּוּר ("the Rock") → אלכ'אלק ("the Creator") or אלמעתמד ("the Mainstay")
  • יְהוָה → אללה throughout
  • יְשֻׁרוּן → אלמוצוף ("the one thus described," i.e., Israel)
  • Construct chains are often rendered as a single JA phrase
  • The period `.` in JA is a clause separator; no span crosses it.

Judgment calls noted inline below.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("הַאֲזִינוּ", "ינצת", "Let the inhabitants"),
        ("הַשָּׁמַיִם", "אהל אלסמאואת", "of the heavens be silent"),
        (None, "חתי'", "that"),
        ("וַאֲדַבֵּרָה", "אתכלם", "I may speak"),
        ("וְתִשְׁמַע", "ויסמע", "and let"),
        ("הָאָרֶץ", "אהל אלארץ'", "the inhabitants of the earth hear"),
        ("אִמְרֵי-פִי", "אקואל פאי", "the words of my mouth"),
    ],
    2: [
        ("יַעֲרֹף כַּמָּטָר לִקְחִי", "וידר כאלמטר בת'י", "My discourse shall pour forth like rain"),
        ("תִּזַּל", "ויהטל", "shall fall"),
        ("כַּטַּל", "כאלטל", "like dew"),
        ("אִמְרָתִי", "מקאלתי", "my utterance"),
        ("כִּשְׂעִירִם", "כאלטש", "like a shower"),
        ("עֲלֵי-דֶשֶׁא", "עלי' אלכלא", "upon open spaces"),
        ("וְכִרְבִיבִים", "וכאלרד'אד'", "and like drizzle"),
        ("עֲלֵי-עֵשֶׂב", "עלי' אלעשב", "upon the grasses"),
    ],
    3: [
        ("כִּי", "לאני", "For"),
        ("שֵׁם יְהוָה", "אדעוכם באסם אללה", "I call you by the name of God"),
        ("אֶקְרָא", "פאעטו", "so give"),
        ("הָבוּ גֹדֶל", "אלכברייא", "greatness"),
        ("לֵאלֹהֵינוּ", "לרבנא", "to our Lord"),
    ],
    4: [
        ("הַצּוּר", "אלכ'אלק", "The Creator"),
        ("תָּמִים פָּעֳלוֹ", "אלצחיח פעלה", "upright is His work"),
        ("כִּי כָל-דְּרָכָיו", "אלד'י כל סיירה", "all His conduct"),
        ("מִשְׁפָּט", "באלחכם", "is by judgment"),
        ("אֵל אֱמוּנָה", "אלטאיק דו אלאמאנה", "the Capable One, possessed of faithfulness"),
        ("וְאֵין עָוֶל", "לא גור ענדה", "no wrong is with Him"),
        ("צַדִּיק", "הו אלעדל", "He is the just"),
        ("וְיָשָׁר הוּא", "אלמסתקים", "the upright"),
    ],
    5: [
        ("שִׁחֵת לוֹ", "אפסד אמאמה", "They corrupted before Him"),
        ("לֹא בָּנָיו", "לא כאוליאה", "not like His faithful ones"),
        (None, "לכן", "rather"),
        ("מוּמָם", "אלמעיבין", "they are the fault-finders"),
        ("דּוֹר עִקֵּשׁ", "אלגיל אלעסר", "a generation that is stubborn"),
        ("וּפְתַלְתֹּל", "אלמנפתל", "and twisted"),
    ],
    6: [
        ("הַ לְיְהוָה", "אלאלאה", "Is it to God"),
        ("תִּגְמְלוּ-זֹאת", "תכאפון בהד'ה אלאפעאל", "that you repay with these deeds"),
        ("עַם נָבָל", "יא שעב גאהל", "O people ignorant"),
        ("וְלֹא חָכָם", "ג'יר חכים", "and unwise"),
        ("הֲלוֹא-הוּא", "אליס הו", "Is He not"),
        ("אָבִיךָ קָּנֶךָ", "מנשיך קאניך", "your Originator, who possesses you"),
        ("הוּא עָשְׂךָ", "הו צנעך", "He made you"),
        ("וַיְכֹנְנֶךָ", "פאתקנך", "and perfected you"),
    ],
    7: [
        (None, "בל", "Nay"),
        ("זְכֹר", "אד'כר", "remember"),
        ("יְמוֹת עוֹלָם", "אייאם אלדהר", "the days of eternity"),
        ("בִּינוּ", "ותפהם", "and understand"),
        ("שְׁנוֹת דֹּר-וָדֹר", "סני גיל וגיל", "the years of generation upon generation"),
        ("שְׁאַל אָבִיךָ", "אסאל אביך", "ask your father"),
        ("וְיַגֵּדְךָ", "יכ'ברך", "and he will inform you"),
        ("זְקֵנֶיךָ", "אשיאכ'ך", "your elders"),
        ("וְיֹאמְרוּ לָךְ", "ויקולון לך", "and they will tell you"),
    ],
    8: [
        (None, "אן", "That"),
        ("עֶלְיוֹן", "אלעאלי", "the Most High"),
        ("בְּהַנְחֵל", "מן חית אנחל", "when He allotted"),
        ("גּוֹיִם", "אלאמם", "the nations"),
        ("בְּהַפְרִידוֹ", "ופרק", "and dispersed"),
        ("בְּנֵי אָדָם", "בני אדם", "the sons of Adam"),
        ("יַצֵּב גְּבֻלֹת עַמִּים", "אוקף מן תכ'ום אלאמם", "set the boundaries of the nations"),
        ("לְמִסְפַּר בְּנֵי יִשְׂרָאֵל", "באחצא בני אסראיל", "according to the count of the sons of Israel"),
    ],
    9: [
        ("כִּי", "לאן", "For"),
        ("חֵלֶק יְהוָה", "צפוה' אללה", "the chosen portion of God"),
        ("עַמּוֹ", "שעבה", "is His people"),
        ("יַעֲקֹב", "ואל יעקוב", "and the house of Jacob"),
        ("חֶבֶל נַחֲלָתוֹ", "מפצ'לה וכ'אצתה", "is His preferred one and His special possession"),
    ],
    10: [
        ("יִמְצָאֵהוּ", "כפאה", "He sustained him"),
        ("בְּאֶרֶץ מִדְבָּר", "פי ארץ' אלבר", "in the land of the wilderness"),
        ("וּבְתֹהוּ יְלֵל יְשִׁמֹן", "ופי תיה פלאה' אלסמאוא", "and in the wandering waste of the open expanse"),
        ("יְסֹבְבֶנְהוּ", "אחאט בה", "He encompassed him"),
        ("יְבוֹנְנֵהוּ", "ופהמה", "and enlightened him"),
        ("יִצְּרֶנְהוּ", "וחפצ'ה", "and kept him"),
        ("כְּאִישׁוֹן עֵינוֹ", "כגנין עינה", "as the pupil of His eye"),
    ],
    11: [
        ("כְּנֶשֶׁר", "וכאלנסר", "And like the eagle"),
        ("יָעִיר קִנּוֹ", "אד' ית'יר וכרה", "when it stirs its nest"),
        ("עַל-גּוֹזָלָיו יְרַחֵף", "ועלי' גואזלה ירף", "and hovers over its fledglings"),
        ("יִפְרֹשׂ כְּנָפָיו", "פיבסט גנאחיה", "it spreads its wings"),
        ("יִקָּחֵהוּ", "פיאכ'דהם", "and takes them up"),
        ("יִשָּׂאֵהוּ", "ויחמלהם", "and bears them"),
        ("עַל-אֶבְרָתוֹ", "עלי' רישה", "upon its plumage"),
    ],
    12: [
        (None, "כדאך", "So"),
        ("יְהוָה", "אללה", "God"),
        ("בָּדָד", "פרדא", "alone"),
        ("יַנְחֶנּוּ", "סיירה", "guided him"),
        ("וְאֵין עִמּוֹ", "וליס מעה", "and there were no"),
        ("אֵל נֵכָר", "מעבודאת אכ'ר", "other objects of worship with Him"),
    ],
    13: [
        ("יַרְכִּבֵהוּ", "וארכבה", "And He mounted him"),
        ("עַל-במותי (בָּמֳתֵי) אָרֶץ", "עלי' קמאקם אלארץ'", "upon the heights of the earth"),
        ("וַיֹּאכַל תְּנוּבֹת שָׂדָי", "חתי' אכל מן נמו אלריאץ'", "until he ate of the produce of the meadows"),
        (None, "וכאנה", "and as if"),
        ("וַיֵּנִקֵהוּ", "ארצ'עה", "He had suckled him"),
        ("דְבַשׁ מִסֶּלַע", "אללבן ען אלצכ'ר", "with milk from the rock"),
        ("וְשֶׁמֶן מֵחַלְמִישׁ צוּר", "ואלעסל מן אלצואן אלצלד", "and honey from the hard flint"),
    ],
    14: [
        ("חֶמְאַת בָּקָר", "וסמן אלבקר", "And the butter of cattle"),
        ("וַחֲלֵב צֹאן", "ולבן אלג'נם", "and the milk of the flock"),
        ("עִם-חֵלֶב כָּרִים", "מע שחם אלכ'ראף", "together with the fat of lambs"),
        ("וְאֵילִים בְּנֵי-בָשָׁן", "וכבאש בני אלבת'נייה", "and rams of the breed of Bashan"),
        ("וְעַתּוּדִים", "ועתדאן", "and he-goats"),
        ("עִם-חֵלֶב כִּלְיוֹת חִטָּה", "מע לב דרמך אלחנטה", "together with the finest of ground wheat"),
        ("וְדַם-עֵנָב תִּשְׁתֶּה-חָמֶר", "וכאן דם אלענב ישרבה כ'מרא", "and the blood of the grape he would drink as an intoxicating drink"),
    ],
    15: [
        ("וַיִּשְׁמַן יְשֻׁרוּן", "פלמא סמן אלמוצוף כדאך", "And when the one thus described grew fat"),
        ("וַיִּבְעָט", "בטר", "he gave himself over to excess"),
        ("שָׁמַנְתָּ עָבִיתָ כָּשִׂיתָ", "אד' קיל לה קד סמנת וג'לצ'ת וגסות", "for it was said to him: 'You have grown fat, and become thick, and become coarse'"),
        ("וַיִּטֹּשׁ אֱלוֹהַּ עָשָׂהוּ", "פתרך אלאה אלד'י צנעה", "and he forsook the God who made him"),
        ("וַיְנַבֵּל צוּר יְשֻׁעָתוֹ", "ואמתחן מעתמד ג'ותה", "and put to the test the One he relied upon for his deliverance"),
    ],
    16: [
        ("יַקְנִאֻהוּ", "ואכ'ד'ו אן יכאידונה", "And they set about provoking Him"),
        ("בְּזָרִים", "באגנביין", "with foreigners"),
        ("בְּתוֹעֵבֹת", "ובמכארה", "and with abominations"),
        ("יַכְעִיסֻהוּ", "יגצבונה", "they angered Him"),
    ],
    17: [
        ("יִזְבְּחוּ לַשֵּׁדִים", "יד'בחון לאלשיאטין", "They sacrifice to demons"),
        ("לֹא אֱלֹהַּ", "וליסת באלאהאת", "which are no divinities"),
        ("אֱלֹהִים לֹא יְדָעוּם", "והי מעבודאת לם יערפונהא", "objects of worship that they did not know"),
        ("חֲדָשִׁים מִקָּרֹב בָּאוּ", "גדד גאת מן קריב", "things new, that came from nearby"),
        ("לֹא שְׂעָרוּם אֲבֹתֵיכֶם", "ולם יעב בהא כ'יאר אבאיכם", "and which the worthy men of your fathers did not regard"),
    ],
    18: [
        (None, "פאקיל לה", "And so it was said to him"),
        ("צוּר יְלָדְךָ", "אלכ'אלק אלמנשיך", "The Creator, your Originator"),
        ("תֶּשִׁי", "תנסא", "you forget"),
        ("וַתִּשְׁכַּח", "ואלטאיק", "and the Capable One"),
        ("אֵל מְחֹלְלֶךָ", "אלמבתדיך", "your Begetter"),
    ],
    19: [
        ("וַיַּרְא יְהוָה", "פלמא ראי דאלך אללה", "And when God saw that"),
        ("וַיִּנְאָץ", "רפצ'הם", "He rejected them"),
        ("מִכַּעַס", "ממא אג'צ'בוה", "on account of what had angered Him"),
        ("בָּנָיו וּבְנֹתָיו", "מנהם אלבנין ואלבנאת", "from them: the sons and the daughters"),
    ],
    20: [
        ("וַיֹּאמֶר", "פקאל", "And He said"),
        ("אַסְתִּירָה פָנַי", "אחגב רחמתי", "I shall conceal My mercy"),
        ("מֵהֶם", "ענהם", "from them"),
        ("אֶרְאֶה מָה אַחֲרִיתָם", "אוריהם מא עאקבתהם", "I shall show them what their end shall be"),
        ("כִּי דוֹר תַּהְפֻּכֹת הֵמָּה", "לאנהם גיל מתקלב", "for they are a generation of reversals"),
        ("בָּנִים לֹא-אֵמֻן בָּם", "בנין לא אמאנה פיהם", "sons in whom there is no faithfulness"),
    ],
    21: [
        ("הֵם קִנְאוּנִי", "וכמא אנהם אכאדוני", "And just as they provoked Me"),
        ("בְלֹא-אֵל", "בג'יר אלאה", "with what is no god"),
        ("כִּעֲסוּנִי", "ואג'צ'בוני", "and angered Me"),
        ("בְּהַבְלֵיהֶם", "בג'רוראתהם", "with their vanities"),
        (None, "כד'אך", "so"),
        ("וַאֲנִי אַקְנִיאֵם", "אנא אכידהם", "I shall provoke them"),
        ("בְּלֹא-עָם", "בלא שעב", "with what is no people"),
        ("בְּגוֹי נָבָל", "ובקביל גאהל", "and with a clan devoid of knowledge"),
        ("אַכְעִיסֵם", "אג'צ'בהם", "I shall anger them"),
    ],
    22: [
        ("כִּי-אֵשׁ", "לאן אלנאר", "For fire"),
        ("קָדְחָה בְאַפִּי", "תנקדח מן ג'צ'בי", "is kindled from My anger"),
        ("וַתִּיקַד", "פתתוקד", "and it burns"),
        ("עַד-שְׁאוֹל תַּחְתִּית", "אלי' אספל אלת'רי", "down to the lowest depth of the earth"),
        ("וַתֹּאכַל אֶרֶץ וִיבֻלָהּ", "ותאכל אלארץ' ונבאתהא", "and it consumes the earth and its vegetation"),
        ("וַתְּלַהֵט מוֹסְדֵי הָרִים", "חתי' תסטע אסאסאה' אלגבאל", "until it reaches the foundations of the mountains"),
    ],
    23: [
        (None, "כדאך", "So shall"),
        ("אַסְפֶּה עָלֵימוֹ רָעוֹת", "אזיד עליהם שרורא", "I increase upon them evils"),
        ("חִצַּי אֲכַלֶּה-בָּם", "וסהאמי אפרקהא פיהם", "and My arrows I shall scatter among them"),
    ],
    24: [
        ("מְזֵי רָעָב", "סגאר אלגוע", "the fever of hunger"),
        ("וּלְחֻמֵי רֶשֶׁף", "וחמא אלוהג", "and burning heat"),
        ("וְקֶטֶב מְרִירִי", "וחתף מר", "and bitter sudden death"),
        ("וְשֶׁן-בְּהֵמֹת", "ואסנאן אלבהאים", "and the teeth of beasts"),
        ("אֲשַׁלַּח-בָּם", "אטלקהא פיהם", "I shall loose upon them"),
        ("עִם-חֲמַת זֹחֲלֵי עָפָר", "מע חמייה' זואחל אלתראב", "together with the venom of the crawling things of the dust"),
    ],
    25: [
        ("מִחוּץ תְּשַׁכֶּל-חֶרֶב", "וסיף מת'כל מן כ'ארג", "And outside, the bereaving sword"),
        ("וּמֵחֲדָרִים אֵימָה", "והיבה מן אלכ'דור", "and dread from within the chambers"),
        ("גַּם-בָּחוּר", "חתי' אלשאב", "striking down youth"),
        ("גַּם-בְּתוּלָה", "חתי' אלעאתק", "and maiden alike"),
        ("יוֹנֵק", "ואלרצ'יע", "the suckling"),
        ("עִם-אִישׁ שֵׂיבָה", "מע ד'וי אלשיבה כאפה", "together with all those of hoary age"),
    ],
    26: [
        ("אָמַרְתִּי", "ולקד קלת", "And I had said"),
        ("אַפְאֵיהֶם", "אתקצאהם", "I shall reduce their number"),
        (None, "באסתחקאק", "as they deserve"),
        ("אַשְׁבִּיתָה", "ואעטל", "and cause"),
        ("מֵאֱנוֹשׁ זִכְרָם", "מן בין אלנאס ד'כרהם", "their memory to cease from among the people"),
    ],
    27: [
        (None, "לולא אני", "But for My"),
        ("לוּלֵי כַּעַס אוֹיֵב", "אחד'ר להם כיד אלעדו", "taking precaution against the scheming of the enemy"),
        ("פֶּן-יְנַכְּרוּ צָרֵימוֹ", "ללא ינכרו ד'אלך אעדאיהם", "lest their enemies deny this"),
        ("פֶּן-יֹאמְרוּ", "כלא יקולו", "lest they say"),
        ("יָדֵנוּ רָמָה", "ידנא קד עלת", "Our hand has prevailed"),
        ("וְלֹא יְהוָה", "וליס אללה", "and it was not God"),
        ("פָּעַל כָּל-זֹאת", "פעל בהם גמיע הד'ה אלאמור", "who did all these things to them"),
    ],
    28: [
        ("כִּי-גוֹי", "לאנהם קביל", "for they are a clan"),
        ("אֹבַד עֵצוֹת", "מצ'ייע אלחכמה", "that has squandered wisdom"),
        ("וְאֵין בָּהֶם תְּבוּנָה", "וליס פיהם פהם", "and there is no understanding in them"),
    ],
    29: [
        ("לוּ חָכְמוּ", "ולו תחכמו", "And would that they were wise"),
        ("יַשְׂכִּילוּ", "לעקלו כ'לה", "they would have comprehended both"),
        ("יָבִינוּ לְאַחֲרִיתָם", "יפהמון בהא עאקבתהם", "and by those two things would understand their fate"),
    ],
    30: [
        (None, "והו אן יקולו", "And that is for them to say"),
        ("אֵיכָה יִרְדֹּף אֶחָד אֶלֶף", "כיף יכלב אלואחד אלפא", "How could one pursue a thousand"),
        ("וּשְׁנַיִם יָנִיסוּ רְבָבָה", "ואת'נין יהרבון רבווה", "and two put a myriad to flight"),
        ("אִם-לֹא כִּי-צוּרָם מְכָרָם", "לולא אן מעתמדהם אסלמהם", "were it not that their mainstay had delivered them over"),
        ("וַיהוָה הִסְגִּירָם", "ואללה אמכן מנהם", "and God had made it possible to overpower them"),
    ],
    31: [
        ("כִּי לֹא כְצוּרֵנוּ צוּרָם", "אנה ליס כמעתמדנא מעתמדהם", "For their mainstay is not like our mainstay"),
        ("וְאֹיְבֵינוּ פְּלִילִים", "ולא אעדאינא יפקהון", "nor do our enemies comprehend this"),
    ],
    32: [
        (None, "לאנהם יעאקבון", "For they are punished"),
        ("כִּי-מִגֶּפֶן סְדֹם גַּפְנָם", "כאן מן גפן סדום גפנהם", "as though their vine were from the vine of Sodom"),
        ("וּמִשַּׁדְמֹת עֲמֹרָה", "ומן דואלי עמורה", "and from the tendrils of Gomorrah"),
        (None, "כד'אך", "so"),
        ("עֲנָבֵמוֹ עִנְּבֵי-רוֹשׁ", "ענבהם ענב אלסם", "their grapes are grapes of poison"),
        ("אַשְׁכְּלֹת מְרֹרֹת לָמוֹ", "וענאקידהם מרה להם", "and their clusters are bitter to them"),
    ],
    33: [
        ("חֲמַת תַּנִּינִם יֵינָם", "וכחמייה' אלתנאנין כ'מרהם", "And like the venom of serpents is their wine"),
        ("וְרֹאשׁ פְּתָנִים אַכְזָר", "וסם אלרקש מנהא אלצ'אריה", "and the poison of the spotted viper — the ferocious among them"),
    ],
    34: [
        (None, "אלא אן", "Yet"),
        ("הֲלֹא-הוּא כָּמֻס עִמָּדִי", "גמיע ד'אלך מכנוז ענדי", "all that is treasured away with Me"),
        ("חָתוּם בְּאוֹצְרֹתָי", "ומכ'תום פי כ'זאיני", "and sealed in My storehouses"),
    ],
    35: [
        ("לִי נָקָם וְשִׁלֵּם", "ולי אלאנתקאם ואלתופיה", "Mine is the vengeance and the full recompense"),
        ("לְעֵת תָּמוּט רַגְלָם", "פי וקת אן תזול קדמהם", "at the time when their foot shall slip"),
        ("כִּי קָרוֹב יוֹם אֵידָם", "אנה מא אקרב יום תעסהם", "for how near is the day of their misery"),
        ("וְחָשׁ עֲתִדֹת לָמוֹ", "ואסרע אלמעדאת להם", "and how swiftly come are the things prepared for them"),
    ],
    36: [
        ("כִּי-יָדִין יְהוָה עַמּוֹ", "אד' יחכם אללה לשעבה", "When God shall render judgment for His people"),
        ("וְעַל-עֲבָדָיו יִתְנֶחָם", "וען עבאדה יצפח", "and grant pardon to His servants"),
        ("כִּי יִרְאֶה כִּי-אָזְלַת יָד", "אד'א ראי אן אלמקדרה ד'הבת ענהם", "when He shall see that the power has gone from them"),
        ("וְאֶפֶס עָצוּר וְעָזוּב", "וכלא אלמחבוס ואלמתרוך גמיע מן צ'ג'טהם", "and those left, whether confined or abandoned, are all broken under their oppression"),
    ],
    37: [
        ("וְאָמַר", "חין קאל אלעדו", "When the enemy shall say"),
        ("אֵי אֱלֹהֵימוֹ", "אין אלאהתהם", "Where is their God"),
        ("צוּר חָסָיוּ בוֹ", "אלמעתמד אלד'י אסתכנו עליה", "the Mainstay upon whom they relied"),
    ],
    38: [
        ("אֲשֶׁר חֵלֶב זְבָחֵימוֹ יֹאכֵלוּ", "אלד'ין כאנו יאכלון שחום ד'באיחהם", "Those who would eat the fat of their sacrifices"),
        ("יִשְׁתּוּ יֵין נְסִיכָם", "וישרבון כ'מר מזאגהם", "and drink the wine of their libations"),
        ("יָקוּמוּ וְיַעְזְרֻכֶם", "יקומון אלאן פיעינוכם", "let them arise now and help you"),
        ("יְהִי עֲלֵיכֶם סִתְרָה", "יכונו עליכם גנה", "let them be a shield over you"),
    ],
    39: [
        ("רְאוּ עַתָּה", "אנצרו אלאן", "Look now"),
        ("כִּי אֲנִי אֲנִי הוּא", "אני הו וחדי", "I am He alone"),
        ("וְאֵין אֱלֹהִים עִמָּדִי", "וליס אלאה אכ'ר מעי", "and there is no other god with Me"),
        ("אֲנִי אָמִית וַאֲחַיֶּה", "אנא אמית ואחיי", "I put to death and I give life"),
        ("מָחַצְתִּי", "כמא טאל מא אוהנת", "however long I have weakened"),
        ("וַאֲנִי אֶרְפָּא", "ולם אזאל אשפי", "I have ever been healing"),
        ("וְאֵין מִיָּדִי מַצִּיל", "וליס מן ידי מכ'לץ", "and there is none who can deliver from My hand"),
    ],
    40: [
        ("כִּי-אֶשָּׂא אֶל-שָׁמַיִם יָדִי", "ואנא אקסם באלסמא", "And I swear by the heavens"),
        ("וְאָמַרְתִּי", "ואקול", "and I say"),
        ("חַי אָנֹכִי לְעֹלָם", "ובקאי אלדאים", "by My everlasting continuance"),
    ],
    41: [
        ("אִם-שַׁנּוֹתִי בְּרַק חַרְבִּי", "לאסנן בריק סיפי", "I shall whet the gleam of My sword"),
        ("וְתֹאחֵז בְּמִשְׁפָּט יָדִי", "ותמסך אלחכם ידי", "and My hand shall hold judgment"),
        ("אָשִׁיב נָקָם לְצָרָי", "וארד אלאנתקאם עלי' אעדאי", "and I shall bring vengeance upon My enemies"),
        ("וְלִמְשַׂנְאַי אֲשַׁלֵּם", "ואלמכאפאה עלי' שאניי", "and the dread upon those who hate Me"),
    ],
    42: [
        ("אַשְׁכִּיר חִצַּי מִדָּם", "פכאני אסכר סהאמי מן דמאהם", "As if I were making My arrows drunk from their blood"),
        ("וְחַרְבִּי תֹּאכַל בָּשָׂר", "וסיפי יאכל לחומהם", "and My sword were consuming their flesh"),
        ("מִדַּם חָלָל וְשִׁבְיָה", "פירוא מן דם אלצריע ואלסבי", "that it may be sated from the blood of the slain and the captive"),
        ("מֵרֹאשׁ פַּרְעוֹת אוֹיֵב", "מן רוס פראענה' אלאעדא", "from the heads of the rulers of the enemy nations"),
    ],
    43: [
        ("הַרְנִינוּ גוֹיִם", "אמדחו יא איהא אלאמם", "Praise, O you nations"),
        ("עַמּוֹ", "שעבה", "His people"),
        ("כִּי דַם-עֲבָדָיו יִקּוֹם", "פאנה ינתקם דמא עבידה", "for He shall avenge the blood of His servants"),
        ("וְנָקָם יָשִׁיב לְצָרָיו", "פירד תלך אלנקמה עלי' אעדאיה", "and shall return that vengeance upon His enemies"),
        ("וְכִפֶּר אַדְמָתוֹ עַמּוֹ", "ויג'פר לבלאדה ושעבה", "and shall grant forgiveness to His land and His people"),
    ],
    44: [
        ("וַיָּבֹא מֹשֶׁה", "וכאן מוסי'", "And it was Moses"),
        ("וַיְדַבֵּר אֶת-כָּל-דִּבְרֵי הַשִּׁירָה-הַזֹּאת", "למא כלם אלקום בהד'ה אלתסבחה", "when he addressed the people with this hymn of praise"),
        ("הוּא", "הו", "he"),
        ("וְהוֹשֵׁעַ בִּן-נוּן", "והושע אבן נון", "and Hoshea son of Nun"),
    ],
    45: [
        ("וַיְכַל מֹשֶׁה", "פלמא פרג' מוסי'", "And when Moses had finished"),
        ("לְדַבֵּר אֶת-כָּל-הַדְּבָרִים הָאֵלֶּה", "מן מכ'אטבתהם בהד'א אלכלאם", "addressing them with this speech"),
    ],
    46: [
        ("וַיֹּאמֶר אֲלֵהֶם", "קאל להם", "he said to them"),
        ("שִׂימוּ לְבַבְכֶם", "רדו באלכם", "Turn your minds"),
        ("לְכָל-הַדְּבָרִים", "לגמיע אלכלאם", "to all the words"),
        ("אֲשֶׁר אָנֹכִי מֵעִיד בָּכֶם הַיּוֹם", "אלד'י אנאשדכם בה אליום", "by which I solemnly charge you today"),
        ("אֲשֶׁר תְּצַוֻּם אֶת-בְּנֵיכֶם", "לתאמרון בה בניכם", "that you command your children"),
        ("לִשְׁמֹר לַעֲשׂוֹת", "ליחפצו ויעמלו", "to observe and to perform"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע אמור הד'ה אלתורייה", "all the matters of this Torah"),
    ],
    47: [
        ("כִּי לֹא-דָבָר רֵק הוּא מִכֶּם", "לאנה ליס בכלאם פארג' הו ענכם", "for it is no empty speech for you"),
        ("כִּי-הוּא חַיֵּיכֶם", "בל הו חיותכם", "rather it is your very life"),
        ("וּבַדָּבָר הַזֶּה תַּאֲרִיכוּ יָמִים", "ובה תטול מדתכם", "and by it your span of days shall be lengthened"),
        ("עַל-הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אַתֶּם עֹבְרִים אֶת-הַיַּרְדֵּן", "אלד'י אנתם גאיזין אלארדן", "which you are crossing the Jordan"),
        ("שָׁמָּה לְרִשְׁתָּהּ", "אליה לתחוזוה", "to possess"),
    ],
    48: [
        ("וַיְדַבֵּר יְהוָה", "ת'ם כלם אללה", "Then God spoke"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("בְּעֶצֶם הַיּוֹם הַזֶּה", "פי ד'את דאלך אליום", "on that very same day"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    49: [
        ("עֲלֵה", "אצעד", "Go up"),
        ("אֶל-הַר הָעֲבָרִים הַזֶּה", "אלי' גבל אלעבריין הד'א", "to this mountain of the Hebrews"),
        ("הַר-נְבוֹ", "גבל נבו", "Mount Nebo"),
        ("אֲשֶׁר בְּאֶרֶץ מוֹאָב", "אלד'י פי בלד מואב", "which is in the land of Moab"),
        ("אֲשֶׁר עַל-פְּנֵי יְרֵחוֹ", "אלד'י בחצ'רה' יריחו", "which faces Jericho"),
        ("וּרְאֵה אֶת-אֶרֶץ", "ואנצ'ר אלבלד", "and behold the land"),
        ("אֲשֶׁר אֲנִי נֹתֵן", "אלד'י אנא מעטיה", "which I am giving"),
        ("לִבְנֵי יִשְׂרָאֵל", "לבני אסראיל", "to the sons of Israel"),
        ("לַאֲחֻזָּה", "חוזא", "as a possession"),
    ],
    50: [
        ("וּמֻת", "ומות", "And die"),
        ("בָּהָר אֲשֶׁר אַתָּה עֹלֶה שָׁמָּה", "פי אלגבל אלד'י אנת צאעד אליה", "on the mountain to which you are ascending"),
        ("וְהֵאָסֵף אֶל-עַמֶּיךָ", "ואנצ'ם אלי' קומך", "and be gathered to your people"),
        ("כַּאֲשֶׁר-מֵת אַהֲרֹן אָחִיךָ", "כמא מאת הרון אכי'ך", "just as Aaron your brother died"),
        ("בְּהֹר הָהָר", "פי גבל הור", "on Mount Hor"),
        ("וַיֵּאָסֶף אֶל-עַמָּיו", "ואנצ'ם אלי' קומה", "and was gathered to his people"),
    ],
    51: [
        ("עַל אֲשֶׁר מְעַלְתֶּם בִּי", "עלי' מא נכת'תמא אלאמה בי", "on account of what you two caused: the nation's breach of faith in Me"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "פי מא בין בני אסראיל", "in the midst of the sons of Israel"),
        ("בְּמֵי-מְרִיבַת קָדֵשׁ מִדְבַּר-צִן", "פי מא כ'צומה' רקים בריה' צין", "at the contention of Raqim in the wilderness of Zin"),
        ("עַל אֲשֶׁר לֹא-קִדַּשְׁתֶּם אוֹתִי", "ולם תקדסאני", "in that you did not sanctify Me"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "פי מא בינהם", "in their midst"),
    ],
    52: [
        ("כִּי מִנֶּגֶד תִּרְאֶה אֶת-הָאָרֶץ", "לדאלך תנצר אלארץ'", "Therefore you shall behold the land"),
        ("אֲשֶׁר-אֲנִי נֹתֵן לִבְנֵי יִשְׂרָאֵל", "אלד'י אעטיתהא לבני אסראיל", "which I am giving to the sons of Israel"),
        (None, "מן אלמקאבלה", "from the opposite side"),
        ("וְשָׁמָּה לֹא תָבוֹא", "ולא תדכ'ל אליהא", "but you shall not enter it"),
    ],
}
