"""Hand-authored alignment triples for Devarim chapter 9.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("שְׁמַע", "אעלם", "Know"),
        (None, "יא", "O"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("אַתָּה", "אנך", "that you"),
        ("עֹבֵר", "גאיז", "are crossing"),
        ("הַיּוֹם", "פי הד'א אלמרה", "this day"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("לָבֹא", "לתדכל", "to enter"),
        ("לָרֶשֶׁת", "ותחוז", "and possess"),
        ("גּוֹיִם", "אממא", "nations"),
        ("גְּדֹלִים", "אכ'תר", "more numerous"),
        ("וַעֲצֻמִים", "וא עצ'ם", "and stronger"),
        ("מִמֶּךָּ", "מנך", "than you"),
        ("עָרִים", "פי קרא", "in great"),
        ("גְּדֹלֹת", "כבירה", "fortified"),
        ("וּבְצֻרֹת", "חצינה", "towns"),
        ("בַּשָּׁמָיִם", "תדאני אלסמא", "that reach close to the sky"),
    ],
    2: [
        ("עַם-גָּדוֹל", "קום כביר", "A great"),
        ("וָרָם", "רפיע", "and tall people"),
        ("בְּנֵי עֲנָקִים", "בני אלגבאברה", "sons of the mighty"),
        ("אֲשֶׁר אַתָּה יָדַעְתָּ", "כמא עלמת", "as you have known"),
        ("וְאַתָּה שָׁמַעְתָּ", "וסמעת", "and heard"),
        ("מִי יִתְיַצֵּב", "מן ד'א יקום", "who can stand"),
        ("לִפְנֵי בְּנֵי עֲנָק", "בין ידי אלגבאברה", "before the mighty"),
    ],
    3: [
        ("וְיָדַעְתָּ", "ואעלם", "And know"),
        ("הַיּוֹם", "מן אליום", "from this day"),
        ("כִּי", "אן", "that"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        (None, "נורה", "His light"),
        ("הוּא-הָעֹבֵר", "גאיז", "passes"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("אֵשׁ אֹכְלָה", "כנאר אכאלה", "like a consuming fire"),
        ("הוּא יַשְׁמִידֵם", "הו ינפדהם", "He shall destroy them"),
        ("וְהוּא יַכְנִיעֵם", "ויהזמהם", "and rout them"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("וְהוֹרַשְׁתָּם", "פתקרצ'הם", "and you shall dispossess them"),
        ("וְהַאֲבַדְתָּם", "ותבידהם", "and annihilate them"),
        ("מַהֵר", "סריעא", "swiftly"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("דִּבֶּר יְהוָה", "ועדך אללה", "God has promised you"),
    ],
    4: [
        ("אַל-תֹּאמַר", "ולא תקול", "And do not say"),
        ("בִּלְבָבְךָ", "פי נפסך", "in your heart"),
        ("בַּהֲדֹף", "אד'א דפעהם", "when"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֹתָם", "מן בין ידיך", "has driven them out from before you"),
        ("לֵאמֹר", "אד'", "saying"),
        ("בְּצִדְקָתִי", "בצלאחי", "because of my righteousness"),
        ("הֱבִיאַנִי", "אדכ'לני", "has brought me in"),
        ("יְהוָה", "אללה", "God"),
        ("לָרֶשֶׁת", "אחוז", "to possess"),
        ("אֶת-הָאָרֶץ", "הד'א אלבלד", "this land"),
        ("הַזֹּאת", "ובצ'לם", "and because of the wickedness"),
        ("וּבְרִשְׁעַת", "אולאיך", "of those"),
        ("הַגּוֹיִם", "אלאמם", "nations"),
        ("הָאֵלֶּה", "אללה", "God"),
        ("יְהוָה", "קארצ'הם", "has dispossessed them"),
        ("מוֹרִישָׁם", "מן בין ידיך", "from before you"),
    ],
    5: [
        ("לֹא", "בל ליס", "Rather, it is not"),
        ("בְצִדְקָתְךָ", "בצלאחך", "by your righteousness"),
        ("וּבְיֹשֶׁר", "וצחה'", "nor the soundness of"),
        ("לְבָבְךָ", "קלבך", "your heart"),
        (None, "פקט", "alone"),
        ("אַתָּה", "אנת", "that you"),
        ("בָא", "צאיר", "are going"),
        ("לָרֶשֶׁת", "לתחוז", "to possess"),
        ("אֶת-אַרְצָם", "בלדהם", "their land"),
        ("כִּי", "לכן", "but rather"),
        ("בְּרִשְׁעַת", "מع צ'לם", "together with the wickedness of"),
        ("הַגּוֹיִם", "אולאיך אלאמם", "those nations"),
        ("הָאֵלֶּה", "אללה", "the Lord"),
        ("יְהוָה", "רבך", "your God"),
        ("אֱלֹהֶיךָ", "קארצ'הם", "is dispossessing them"),
        ("מוֹרִישָׁם", "מן בין ידיך", "from before you"),
        ("מִפָּנֶיךָ", "ולכי", "and so that"),
        ("וּלְמַעַן הָקִים", "יאפי", "He may fulfil"),
        ("אֶת-הַדָּבָר", "באלקול", "the word"),
        ("אֲשֶׁר נִשְׁבַּע", "אלד'י קאלה", "which He spoke"),
        ("יְהוָה", "לאבאיך", "to your fathers"),
        ("לַאֲבֹתֶיךָ", "אברהים", "Abraham"),
        ("לְאַבְרָהָם", "ויצחק", "and Isaac"),
        ("לְיִצְחָק", "ויעקוב", "and Jacob"),
    ],
    6: [
        ("וְיָדַעְתָּ", "פתיקן", "Know, then"),
        ("כִּי", "אנה", "that"),
        ("לֹא", "ליס", "it is not"),
        ("בְצִדְקָתְךָ", "בצלאחך", "by your righteousness"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        ("נֹתֵן", "מعطيך", "is giving you"),
        ("לְךָ", "הד'א", "this"),
        ("אֶת-הָאָרֶץ", "אלבלד", "land"),
        ("הַטּוֹבָה", "אלגייד", "good"),
        ("הַזֹּאת", "לתحوزوه", "to possess it"),
        ("לְרִשְׁתָּהּ", "אד'", "for"),
        ("כִּי", "אנت", "you"),
        ("עַם-קְשֵׁה-עֹרֶף", "شعب صعب الرقاب", "are a stiff-necked people"),
        ("אָתָּה", "אנت", "you"),
    ],
    7: [
        ("זְכֹר", "פاذكر", "Remember"),
        ("אַל-תִּשְׁכַּח", "ولا تنسا", "and do not forget"),
        ("אֵת אֲשֶׁר-הִקְצַפְתָּ", "מא אסכ'טת", "how you provoked"),
        ("אֶת-יְהוָה", "אللה", "the Lord"),
        ("אֱלֹהֶיךָ", "رבך", "your God"),
        ("בַּמִּדְבָּר", "פי אלبر", "in the wilderness"),
        ("לְמִן-הַיּוֹם", "וד'אלך מן יום", "from the day"),
        ("אֲשֶׁר-יָצָאתָ", "כ'רגת", "you went out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן مצر", "of Egypt"),
        ("עַד-בֹּאֲכֶם", "ואלי' אן גיتم", "until you came"),
        ("עַד-הַמָּקוֹם", "אלי' הד'א אלמوצ'ע", "to this place"),
        ("הַזֶּה", "לם תזאלו", "you have not ceased"),
        ("מַמְרִים הֱיִיתֶם", "מכ'אלפין", "defying"),
        ("עִם-יְהוָה", "ללה", "God"),
    ],
    8: [
        ("וּבְחֹרֵב", "ופי חריב", "And at Horeb"),
        ("הִקְצַפְתֶּם", "אסכ'טתם", "you provoked"),
        ("אֶת-יְהוָה", "אללה", "God"),
        ("וַיִּתְאַנַּף", "פג'צ'ב", "and"),
        ("יְהוָה", "אללה", "God was"),
        ("בָּכֶם", "עליכם", "greatly angered with you"),
        ("לְהַשְׁמִיד אֶתְכֶם", "וכאד אן ינפד'כם", "and came near to destroying you"),
    ],
    9: [
        ("בַּעֲלֹתִי", "חין צעדת", "When I went up"),
        ("הָהָרָה", "אלגבל", "the mountain"),
        ("לָקַחַת", "לאכ'ד'", "to receive"),
        ("לוּחֹת הָאֲבָנִים", "לוחי אלגוהר", "the two tablets of gems"),
        ("לוּחֹת הַבְּרִית", "לוחי אלשהאדה", "the tablets of the testimony"),
        ("אֲשֶׁר-כָּרַת", "אלד'י עהדהא", "which"),
        ("יְהוָה", "אללה", "God"),
        ("עִמָּכֶם", "מעכם", "had covenanted with you"),
        ("וָאֵשֵׁב", "פאקמת", "I stayed"),
        ("בָּהָר", "פיה", "there"),
        ("אַרְבָּעִים יוֹם", "ארבעין יומא", "forty days"),
        ("וְאַרְבָּעִים לַיְלָה", "וארבעין לילה", "and forty nights"),
        ("לֶחֶם לֹא אָכַלְתִּי", "לם אכל טעאמא", "I ate no food"),
        ("וּמַיִם לֹא שָׁתִיתִי", "ולם אשרב מאא", "and drank no water"),
    ],
    10: [
        ("וַיִּתֵּן", "אלי' אן דפע", "Until"),
        ("יְהוָה", "אללה", "God"),
        ("אֵלַי", "אליי", "delivered to me"),
        ("אֶת-שְׁנֵי לוּחֹת הָאֲבָנִים", "לוחי אלגוהר", "the two tablets of gems"),
        ("כְּתֻבִים", "אלמכתובין", "written"),
        ("בְּאֶצְבַּע אֱלֹהִים", "בקדרה' אללה", "by the power of God"),
        ("וַעֲלֵיהֶם", "ועליהמא", "and upon them"),
        ("כְּכָל-הַדְּבָרִים", "מת'ל גמיע אלכלמאת", "the like of all the words"),
        ("אֲשֶׁר דִּבֶּר", "אלד'י כלמכם", "which"),
        ("יְהוָה", "אללה", "God"),
        ("עִמָּכֶם", "בהא", "had spoken to you"),
        ("בָּהָר", "פי אלגבל", "on the mountain"),
        ("מִתּוֹךְ הָאֵשׁ", "מן וסט אלנאר", "from the midst of the fire"),
        ("בְּיוֹם הַקָּהָל", "פי יום אלגוק", "on the day of the assembly"),
    ],
    11: [
        ("וַיְהִי", "וכאן ד'אלך", "And it was"),
        ("מִקֵּץ", "בעד", "after"),
        ("אַרְבָּעִים יוֹם", "ארבעין יומא", "forty days"),
        ("וְאַרְבָּעִים לָיְלָה", "וארבעין לילה", "and forty nights"),
        ("נָתַן יְהוָה", "דפעהמא", "that He delivered them"),
        ("אֵלַי", "אליי", "to me"),
    ],
    12: [
        ("וַיֹּאמֶר", "פקאל", "And"),
        ("יְהוָה", "אללה", "God said"),
        ("אֵלַי", "לי", "to me"),
        ("קוּם", "קום", "Arise"),
        ("רֵד", "אנחדר", "go down"),
        ("מַהֵר", "סריעא", "quickly"),
        ("מִזֶּה", "מן ההנא", "from here"),
        ("כִּי", "לאן", "for"),
        ("שִׁחֵת", "קד אפסד", "have become corrupt"),
        ("עַמְּךָ", "קומך", "your people"),
        ("אֲשֶׁר הוֹצֵאתָ", "אלד'י אכ'רגתהם", "whom you brought out"),
        ("מִמִּצְרָיִם", "מן מצר", "of Egypt"),
        ("סָרוּ", "זאלו", "they have turned aside"),
        ("מַהֵר", "סריעא", "quickly"),
        ("מִן-הַדֶּרֶךְ", "ען אלטריק", "from the way"),
        ("אֲשֶׁר צִוִּיתִם", "אלד'י אמרתהם", "which I commanded them"),
        ("עָשׂוּ לָהֶם", "וצנעו להם", "and have made for themselves"),
        ("מַסֵּכָה", "מסבוכא", "a molten image"),
    ],
    13: [
        (None, "ת'ם", "Then"),
        ("וַיֹּאמֶר יְהוָה", "קאל לי", "He said to me"),
        ("לֵאמֹר", "עלמת", "I have known"),
        ("רָאִיתִי", "הולאי אלקום", "that these people"),
        ("אֶת-הָעָם", "אנהם", "are"),
        ("הַזֶּה", "צעאב אלרקאב", "stiff-necked"),
        ("וְהִנֵּה עַם-קְשֵׁה-עֹרֶף הוּא", "צעאב אלרקאב", "stiff-necked"),
    ],
    14: [
        ("הֶרֶף", "ואן כפאת", "And if you hold back"),
        ("מִמֶּנִּי", "ען אלתשפע פיהם", "from interceding for them"),
        ("וְאַשְׁמִידֵם", "אנפד'תהם", "I shall destroy them"),
        ("וְאֶמְחֶה", "ומחית", "and blot out"),
        ("אֶת-שְׁמָם", "אסמאיהם", "their names"),
        ("מִתַּחַת הַשָּׁמָיִם", "מן תחת אלסמא", "from beneath the sky"),
        ("וְאֶעֱשֶׂה אוֹתְךָ", "וגעלת מנך", "and make of you"),
        ("לְגוֹי-עָצוּם", "אמה", "a nation"),
        ("וָרָב", "אכ'תר", "more numerous"),
        ("מִמֶּנּוּ", "וא עצ'ם מנהם", "and stronger than they"),
    ],
    15: [
        ("וָאֵפֶן", "פولית", "So I turned"),
        ("וָאֵרֵד", "ونزلت", "and came down"),
        ("מִן-הָהָר", "מן אלגبל", "from the mountain"),
        ("וְהָהָר", "והو", "while it was"),
        ("בֹּעֵר", "משتعל", "ablaze"),
        ("בָּאֵשׁ", "بالنار", "with fire"),
        ("וּשְׁנֵי לוּחֹת הַבְּרִית", "ולوحי אלשהאדה", "and the two tablets of testimony"),
        ("עַל שְׁתֵּי יָדָי", "עלי' ידיי", "were in my hands"),
    ],
    16: [
        ("וָאֵרֶא", "פנצ'רت", "And I looked"),
        ("וְהִנֵּה", "ואד'א", "and behold"),
        ("חֲטָאתֶם", "בכם קד אכ'טאתם", "you had sinned"),
        ("לַיהוָה", "ללה", "against the Lord"),
        ("אֱלֹהֵיכֶם", "רבכم", "your God"),
        ("עֲשִׂיתֶם לָכֶם", "ואתכ'ד'תם", "you had taken for yourselves"),
        ("עֵגֶל", "עגלא", "a molten"),
        ("מַסֵּכָה", "מסبוكا", "calf"),
        ("סַרְתֶּם", "וזלتم", "and had turned aside"),
        ("מַהֵר", "סريعا", "quickly"),
        ("מִן-הַדֶּרֶךְ", "ען אלطريق", "from the way"),
        ("אֲשֶׁר-צִוָּה", "אלד'י אמרכם", "He had commanded you"),
    ],
    17: [
        ("וָאֶתְפֹּשׂ", "וצ'בטת", "And I seized"),
        ("בִּשְׁנֵי הַלֻּחֹת", "אللوחין", "the two tablets"),
        ("וָאַשְׁלִכֵם", "وطرحتهما", "and threw them"),
        ("מֵעַל שְׁתֵּי יָדָי", "ען ידיי", "from my hands"),
        ("וָאֲשַׁבְּרֵם", "وكسرتهما", "and broke them"),
        ("לְעֵינֵיכֶם", "בحضرتكم", "before your eyes"),
    ],
    18: [
        ("וָאֶתְנַפַּל", "פשפעת", "And I interceded"),
        ("לִפְנֵי יְהוָה", "בין ידי אللה", "before God"),
        ("כָּרִאשֹׁנָה", "כאלמרה אלاولا", "as the first time"),
        ("אַרְבָּעִים יוֹם", "ארבעין יום", "forty days"),
        ("וְאַרְבָּעִים לַיְלָה", "וארבעין לילה", "and forty nights"),
        ("לֶחֶם לֹא אָכַלְתִּי", "לם אכל טעאמא", "I ate no food"),
        ("וּמַיִם לֹא שָׁתִיתִי", "ולם אשרב מאא", "and I drank no water"),
        ("עַל כָּל-חַטַּאתְכֶם", "בסבב כטייתכם", "on account of your sin"),
        ("אֲשֶׁר חֲטָאתֶם", "אלד'י אכ'טאתם", "which you had committed"),
        ("לַעֲשׂוֹת הָרַע", "וצנעתם אלשר", "you had done evil"),
        ("בְּעֵינֵי יְהוָה", "בין ידי אللה", "before God"),
        ("לְהַכְעִיסוֹ", "ואסכ'טתמוה", "and provoked Him"),
    ],
    19: [
        ("כִּי", "לאני", "For"),
        ("יָגֹרְתִּי", "חד'רת", "I feared"),
        ("מִפְּנֵי הָאַף", "אלג'צ'ב", "the anger"),
        ("וְהַחֵמָה", "ואלחמייה", "and the fury"),
        ("אֲשֶׁר קָצַף", "אלד'י סכ'ט", "with which"),
        ("יְהוָה", "אللה", "God was wrathful"),
        ("עֲלֵיכֶם", "עليכם", "against you"),
        ("לְהַשְׁמִיד אֶתְכֶם", "לינפדכم", "to destroy you"),
        ("וַיִּשְׁמַע", "פסمع", "and"),
        ("יְהוָה", "אللה", "God heeded"),
        ("אֵלַי", "לי", "me"),
        ("גַּם בַּפַּעַם הַהִוא", "פי ד'אלך אלוקת", "at that time"),
    ],
    20: [
        ("וּבְאַהֲרֹן", "ועلي' הרון", "And against Aaron"),
        ("הִתְאַנַּף יְהוָה", "וגד אللה", "God was"),
        ("מְאֹד", "גדא", "greatly angered"),
        ("לְהַשְׁמִידוֹ", "וכאד אן ינפדה", "coming near to destroying him"),
        ("וָאֶתְפַּלֵּל", "פאסתג'פרת", "and I sought forgiveness"),
        ("גַּם-בְּעַד אַהֲרֹן", "לה איצ'א", "for him also"),
        ("בָּעֵת הַהִוא", "פי ד'אלך אלוקת", "at that time"),
    ],
    21: [
        ("וְאֶת-חַטַּאתְכֶם", "ואמא כ'טייתכם", "And as for your sin"),
        ("אֲשֶׁר-עֲשִׂיתֶם", "והו אלעגל אלד'י אתכ'ד'תמוה", "that is, the calf which you had made"),
        ("אֶת-הָעֵגֶל", "פאני", "I"),
        ("לָקַחְתִּי", "אכ'דתה", "took it"),
        ("וָאֶשְׂרֹף אֹתוֹ", "ואחרקתה", "and burned it"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
        ("וָאֶכֹּת אֹתוֹ", "וברדתה באלמברד", "and ground it fine"),
        ("טָחוֹן הֵיטֵב", "נעמא", "until it was ground to dust"),
        ("עַד אֲשֶׁר-דַּק לְעָפָר", "חתי דק כאלתראב", "and I cast its dust"),
        ("וָאַשְׁלִךְ אֶת-עֲפָרוֹ", "וטרחת תראבה", "into the stream of water"),
        ("אֶל-הַנַּחַל", "פי ואד אלמא", "that flows down"),
        ("הַיֹּרֵד", "אלמנחדר", "from the mountain"),
        ("מִן-הָהָר", "מן אלגבל", "from the mountain"),
    ],
    22: [
        ("וּבְתַבְעֵרָה", "ופי דאת אלאשתעאל", "And at the Place of Burning"),
        ("וּבְמַסָּה", "וד'את אלמחנה", "and at the Place of Trial"),
        ("וּבְקִבְרֹת הַתַּאֲוָה", "וקבור אלמתשהיין", "and at the Graves of the Craving"),
        ("מַקְצִפִים הֱיִיתֶם", "לם תזאלו מסכ'טין", "you were continually provoking"),
        ("אֶת-יְהוָה", "ללה", "God"),
    ],
    23: [
        ("וּבִשְׁלֹחַ יְהוָה", "ולמא בעת' אللה", "And when God sent"),
        ("אֶתְכֶם", "בעצ'כם", "some of you"),
        ("מִקָּדֵשׁ בַּרְנֵעַ", "מן רקים ברנע", "from Kadesh-barnea"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("עֲלוּ", "אצעדו", "Go up"),
        ("וּרְשׁוּ", "וחוזו", "and possess"),
        ("אֶת-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר נָתַתִּי לָכֶם", "אלד'י אעטיתכם", "which I have given you"),
        ("וַתַּמְרוּ", "פכ'אלפתם", "you defied"),
        ("אֶת-פִּי יְהוָה", "אמר אललה", "the command of the Lord"),
        ("אֱלֹהֵיכֶם", "רבכם", "your God"),
        ("וְלֹא הֶאֱמַנְתֶּם", "ולם תומנו", "and did not believe"),
        ("לוֹ", "בה", "in Him"),
        ("וְלֹא שְׁמַעְתֶּם בְּקֹלוֹ", "ולם תקבלו אמרה", "and did not accept His command"),
    ],
    24: [
        (None, "ובאלגמלה", "And in sum"),
        ("מַמְרִים הֱיִיתֶם", "לם תזאלו מכ'אלפין", "you have not ceased defying"),
        ("עִם-יְהוָה", "ללה", "God"),
        ("מִיּוֹם", "מן יום", "from the day"),
        ("דַּעְתִּי אֶתְכֶם", "ערפתכם", "I have known you"),
    ],
    25: [
        ("וָאֶתְנַפַּל", "פשפעת", "And I interceded"),
        ("לִפְנֵי יְהוָה", "ענדה", "before Him"),
        ("אֵת אַרְבָּעִים הַיּוֹם", "תלך אלארבעין אליום", "those forty days"),
        ("וְאֶת-אַרְבָּעִים הַלַּיְלָה", "ואלארבעין אללילה", "and the forty nights"),
        ("אֲשֶׁר הִתְנַפָּלְתִּי", "אד'", "since"),
        ("כִּי-אָמַר יְהוָה", "אראד אللה", "God had willed"),
        ("לְהַשְׁמִיד אֶתְכֶם", "אן ינפד'כم", "to destroy you"),
    ],
    26: [
        ("וָאֶתְפַּלֵּל", "צלית", "I prayed"),
        ("אֶל-יְהוָה", "בין ידי אللה", "before God"),
        ("וָאֹמַר", "וקלת", "and said"),
        ("אֲדֹנָי יְהוִה", "אللהم יא רבי", "O God, my Lord"),
        ("אַל-תַּשְׁחֵת", "לא תהלך", "Do not destroy"),
        ("עַמְּךָ", "קومך", "Your people"),
        ("וְנַחֲלָתְךָ", "וצפותך", "and Your chosen ones"),
        ("אֲשֶׁר פָּדִיתָ", "אלד'ין פككتהם", "whom You redeemed"),
        ("בְּגָדְלֶךָ", "בעצ'מתך", "by Your greatness"),
        ("אֲשֶׁר-הוֹצֵאתָ", "ואכ'רגתהם", "and brought out"),
        ("מִמִּצְרַיִם", "מן מצר", "of Egypt"),
        ("בְּיָד חֲזָקָה", "ביד שדידה", "with a mighty hand"),
    ],
    27: [
        ("זְכֹר", "אד'כר", "Remember"),
        ("לַעֲבָדֶיךָ", "אוליאך", "Your devoted ones"),
        ("לְאַבְרָהָם", "אברהים", "Abraham"),
        ("לְיִצְחָק", "ויצחק", "Isaac"),
        ("וּלְיַעֲקֹב", "ויעקוב", "and Jacob"),
        ("אַל-תֵּפֶן", "לא תנצ'ר", "do not look upon"),
        ("אֶל-קְשִׁי", "אלי' צעובה'", "the hardness of"),
        ("הָעָם", "הד'א אלשעב", "this people"),
        ("הַזֶּה", "וטלאחה", "nor their wickedness"),
        ("וְאֶל-רִשְׁעוֹ", "וכ'טייתה", "and their sin"),
        ("וְאֶל-חַטָּאתוֹ", "וכ'טייתה", "and their sin"),
    ],
    28: [
        ("פֶּן-יֹאמְרוּ", "כלא יקול", "Lest"),
        ("הָאָרֶץ", "אהל אלבלד", "the people of the land"),
        ("אֲשֶׁר הוֹצֵאתָנוּ", "אלד'י אכ'רגתנא", "from which You brought us out"),
        ("מִשָּׁם", "מنה", "should say"),
        ("מִבְּלִי יְכֹלֶת יְהוָה", "ממא לם יطيق רבהם", "because their Lord was unable"),
        ("לַהֲבִיאָם", "אן יד'כ'להם", "to bring them into"),
        ("אֶל-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-דִּבֶּר לָהֶם", "אלד'י ועדהם בה", "which He promised them"),
        ("וּמִשִּׂנְאָתוֹ", "ומן שנאתה", "and out of His hatred"),
        ("אוֹתָם", "להם", "of them"),
        ("הוֹצִיאָם", "אכ'רגהם", "He brought them out"),
        ("לַהֲמִתָם", "ליקתלהם", "to slay them"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
    ],
    29: [
        ("וְהֵם", "והם", "For they are"),
        ("עַמְּךָ", "קومך", "Your people"),
        ("וְנַחֲלָתֶךָ", "וצפותך", "and Your chosen ones"),
        ("אֲשֶׁר הוֹצֵאתָ", "אלד'י אכ'רגתהם", "whom You brought out"),
        ("בְּכֹחֲךָ הַגָּדֹל", "בקوותך אל]עט'ימה] עצ'ימה", "by Your great power"),
        ("וּבִזְרֹעֲךָ הַנְּטוּיָה", "וד'ראעך אלממדודה", "and Your outstretched arm"),
    ],
}
