"""Hand-authored alignment triples for Devarim chapter 17.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the prohibition on blemished sacrifices (v. 1), capital
trials for idolaters (vv. 2–7), the supreme court in Jerusalem (vv. 8–13),
and the law of the king — selection, restraint, and the Torah scroll
obligation (vv. 14–20).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא-תִזְבַּח", "לא תד'בח", "You shall not sacrifice"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("שׁוֹר", "ת'ורא", "an ox"),
        ("וָשֶׂה", "או שאה", "or a sheep"),
        ("אֲשֶׁר יִהְיֶה בוֹ מוּם", "ממא פיה עיב", "in which there is a blemish"),
        ("כֹּל דָּבָר רָע", "מן אלאמור אלפאחשה", "of the sort of shameful matters"),
        ("כִּי תוֹעֲבַת יְהוָה אֱלֹהֶיךָ הוּא", "ממא יכרהה אללה רבך", "that God your Lord abhors"),
    ],
    2: [
        ("כִּי-יִמָּצֵא", "ואן וגד", "And if there be found"),
        ("בְקִרְבְּךָ", "פי מא בינכם", "among you"),
        ("בְּאַחַד שְׁעָרֶיךָ", "פי בעץ' קראך", "in any of your towns"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
        ("אִישׁ", "רגל", "a man"),
        ("אוֹ-אִשָּׁה", "או אמראה", "or a woman"),
        ("אֲשֶׁר יַעֲשֶׂה אֶת-הָרַע", "צנע אלשר", "who has done evil"),
        ("בְּעֵינֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לַעֲבֹר בְּרִיתוֹ", "פתגאוז עהדה", "and transgressed His covenant"),
    ],
    3: [
        ("וַיֵּלֶךְ", "פמצ'א", "and went"),
        ("וַיַּעֲבֹד", "ועבד", "and worshipped"),
        ("אֱלֹהִים אֲחֵרִים", "מעבודאת אכ'ר", "other objects of worship"),
        ("וַיִּשְׁתַּחוּ לָהֶם", "וסגד להא", "and bowed down to them"),
        ("וְלַשֶּׁמֶשׁ", "או לאלשמס", "or to the sun"),
        ("אוֹ לַיָּרֵחַ", "או לאלקמר", "or to the moon"),
        ("אוֹ לְכָל-צְבָא הַשָּׁמַיִם", "או לסאיר נגום אלסמא", "or to the rest of the stars of the sky"),
        ("אֲשֶׁר לֹא-צִוִּיתִי", "מא לם אטלק לה", "which I have not permitted to him"),
    ],
    4: [
        (None, "פאד'א אכ'ברת בד'אלך", "then when you are informed of that"),
        ("וְשָׁמָעְתָּ", "אסתמעה", "hear it out"),
        ("וְדָרַשְׁתָּ הֵיטֵב", "ואלתמסה גיידא", "and examine it well"),
        ("וְהִנֵּה אֱמֶת נָכוֹן הַדָּבָר", "פאד'א כאן אלאמר חקא ת'אבתא", "and if the matter is true and established"),
        ("נֶעֶשְׂתָה הַתּוֹעֵבָה הַזֹּאת", "קד צנעת הד'ה אלכריהה", "that this abhorrent thing has been done"),
        ("בְּיִשְׂרָאֵל", "פי מא בינכם", "among you"),
    ],
    5: [
        ("וְהוֹצֵאתָ", "פאכ'רג", "you shall bring out"),
        ("אֶת-הָאִישׁ הַהוּא", "ד'אלך אלרגל", "that man"),
        ("אוֹ אֶת-הָאִשָּׁה הַהִוא", "או תלך אלאמראה", "or that woman"),
        ("אֲשֶׁר עָשׂוּ אֶת-הַדָּבָר הָרָע הַזֶּה", "אלד'י צנעו הד'א אלאמר אלרדי", "who did this wicked thing"),
        ("אֶל-שְׁעָרֶיךָ", "אלי' מחלך", "to your localities"),
        ("אֶת-הָאִישׁ", "אלרגל", "the man"),
        (None, "וחדה", "alone"),
        ("אוֹ אֶת-הָאִשָּׁה", "או תלך אלאמראה", "or that woman"),
        (None, "וחדהא", "alone"),
        ("וּסְקַלְתָּם בָּאֲבָנִים", "באן תרגמוהמא באלחגארה", "and you shall stone them with stones"),
        ("וָמֵתוּ", "אלי' אן ימותא", "until they die"),
    ],
    6: [
        ("עַל-פִּי שְׁנַיִם עֵדִים", "בקול שאהדין", "By the word of two witnesses"),
        ("אוֹ שְׁלֹשָׁה עֵדִים", "או ת'לאת'ה", "or three"),
        ("יוּמַת הַמֵּת", "יקתל מן יקתל", "shall the one to be put to death be put to death"),
        ("לֹא יוּמַת", "ולא יקתל", "he shall not be put to death"),
        ("עַל-פִּי עֵד אֶחָד", "בקול שאהד ואחד", "by the word of one witness alone"),
    ],
    7: [
        ("יַד הָעֵדִים", "ואידי אלשאהדין", "And the hands of the witnesses"),
        ("תִּהְיֶה-בּוֹ בָרִאשֹׁנָה", "תבטש בה אוולא", "shall strike him first"),
        ("לַהֲמִיתוֹ", "לתקתלה", "to put him to death"),
        ("וְיַד כָּל-הָעָם", "ואידי סאיר אלנאס", "and the hands of the rest of the people"),
        ("בָּאַחֲרֹנָה", "אכ'ירא", "last"),
        ("וּבִעַרְתָּ הָרָע", "ואנף אהל אלשר", "And purge those who do evil"),
        ("מִקִּרְבֶּךָ", "מן וסטך", "from your midst"),
    ],
    8: [
        ("כִּי יִפָּלֵא מִמְּךָ דָבָר לַמִּשְׁפָּט", "ואד'א כ'פי ענך אמר מן אלאחכאם", "And when a matter of judgments is obscure to you"),
        ("בֵּין-דָּם לְדָם", "בין דם לדם", "between blood and blood"),
        ("בֵּין-דִּין לְדִין", "ובין דין לדין", "between ruling and ruling"),
        ("וּבֵין נֶגַע לָנֶגַע", "וחכם בלא אלי' בלא", "between affliction and affliction"),
        ("דִּבְרֵי רִיבֹת", "ואמר כ'צומאת", "matters of disputes"),
        ("בִּשְׁעָרֶיךָ", "פי מחאלך", "in your localities"),
        ("וְקַמְתָּ", "פקום", "then arise"),
        ("וְעָלִיתָ", "ואצע'ד", "and go up"),
        ("אֶל-הַמָּקוֹם", "אלי' אלמוצ'ע", "to the place"),
        ("אֲשֶׁר יִבְחַר יְהוָה אֱלֹהֶיךָ בּוֹ", "אלד'י יכ'תארה אללה רבך", "which God your Lord shall choose"),
    ],
    9: [
        ("וּבָאתָ", "וציר", "And go"),
        ("אֶל-הַכֹּהֲנִים הַלְוִיִּם", "אלי' אלאימה אלליואניין", "to the Levitical imāms"),
        ("וְאֶל-הַשֹּׁפֵט", "ואלי' אלחאכם", "and to the judge"),
        ("אֲשֶׁר יִהְיֶה בַּיָּמִים הָהֵם", "אלד'י ילי פי ד'אלך אלזמאן", "who holds office in that time"),
        ("וְדָרַשְׁתָּ", "פאלתמס מנהם", "and seek from them"),
        ("אֵת דְּבַר הַמִּשְׁפָּט", "אמר ד'אלך אלחכם", "the ruling of that judgment"),
        (None, "יפתונך בה", "they shall issue a legal opinion to you"),
    ],
    10: [
        ("וְעָשִׂיתָ", "ואעמל", "And act"),
        ("עַל-פִּי הַדָּבָר", "בחסב אלאמר", "according to the matter"),
        ("אֲשֶׁר יַגִּידוּ לְךָ", "אלד'י יפתונך בה", "upon which they issue a legal opinion for you"),
        ("מִן-הַמָּקוֹם הַהוּא", "מן ד'אלך אלמוצ'ע", "from that place"),
        ("אֲשֶׁר יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God shall choose"),
        ("וְשָׁמַרְתָּ לַעֲשׂוֹת", "ואחפץ' לתעמל", "and take care to do"),
        ("כְּכֹל אֲשֶׁר יוֹרוּךָ", "כגמיע מא י'דלונך בה", "according to all that they direct you"),
    ],
    11: [
        ("עַל-פִּי הַתּוֹרָה", "ובחסב אלדלאלה", "And according to the guidance"),
        ("אֲשֶׁר יוֹרוּךָ", "אלד'י ידלונך", "they direct you"),
        ("וְעַל-הַמִּשְׁפָּט", "ואלחכם", "and the ruling"),
        ("אֲשֶׁר-יֹאמְרוּ לְךָ", "אלד'י יקולון לך", "they pronounce to you"),
        ("תַּעֲשֶׂה", "תצנע", "you shall do"),
        ("לֹא תָסוּר", "לא תזול", "you shall not deviate"),
        ("מִן-הַדָּבָר", "מן אלאמר", "from the matter"),
        ("אֲשֶׁר-יַגִּידוּ לְךָ", "אלד'י יפתונך בה", "upon which they issue their legal opinion"),
        ("יָמִין", "ימנה", "neither right"),
        ("וּשְׂמֹאל", "ולא יסרה", "nor left"),
    ],
    12: [
        ("וְהָאִישׁ", "ואי רגל", "And any man"),
        ("אֲשֶׁר-יַעֲשֶׂה בְזָדוֹן", "יסתעמל אלקחה", "who acts with insolence"),
        ("לְבִלְתִּי שְׁמֹעַ", "פלא יקבל", "and will not accept"),
        ("אֶל-הַכֹּהֵן הָעֹמֵד לְשָׁרֶת שָׁם", "מן אלאמאם אלמקים הנאך", "from the imām who stands there"),
        ("אֶת-יְהוָה אֱלֹהֶיךָ", "ליכ'דם אללה רבך", "to serve God your Lord"),
        ("אוֹ אֶל-הַשֹּׁפֵט", "או מן אלחאכם", "or from the judge"),
        ("וּמֵת הָאִישׁ הַהוּא", "פליקתל ד'אלך אלרגל", "that man shall be put to death"),
        ("וּבִעַרְתָּ הָרָע", "ואנף אהל אלשר", "and purge those who do evil"),
        ("מִיִּשְׂרָאֵל", "מן אל אסראיל", "from among Israel"),
    ],
    13: [
        ("וְכָל-הָעָם", "וסאיר אלנאס", "And the rest of the people"),
        ("יִשְׁמְעוּ", "יסמעון", "shall hear"),
        ("וְיִרָאוּ", "ויכ'אפון", "and be afraid"),
        ("וְלֹא יְזִידוּן עוֹד", "ולא יתקחון איצ'א", "and shall not act insolently likewise"),
    ],
    14: [
        ("כִּי-תָבֹא", "ואד'א דכ'לת", "And when you enter"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ נֹתֵן לָךְ", "אלד'י אללה רבך מעטיך", "which God your Lord is giving you"),
        ("וִירִשְׁתָּהּ", "וחזתה", "and you possess it"),
        ("וְיָשַׁבְתָּה בָּהּ", "ואקמת פיה", "and settle in it"),
        ("וְאָמַרְתָּ", "פקלת", "and you say"),
        ("אָשִׂימָה עָלַי מֶלֶךְ", "אנצב לי מלכא", "I will appoint over me a king"),
        ("כְּכָל-הַגּוֹיִם", "כסאיר אלאמם", "like the rest of the nations"),
        ("אֲשֶׁר סְבִיבֹתָי", "אלד'ין חואלי", "that are around me"),
    ],
    15: [
        ("שׂוֹם תָּשִׂים עָלֶיךָ מֶלֶךְ", "פיגוז אן תנצב לך מלכא", "it is permitted that you appoint over yourself a king"),
        ("אֲשֶׁר יִבְחַר יְהוָה אֱלֹהֶיךָ בּוֹ", "אלד'י יכ'תארה אללה רבך", "whom God your Lord shall choose"),
        ("מִקֶּרֶב אַחֶיךָ", "מן בעץ' אכ'ותך", "from among your brothers"),
        ("תָּשִׂים עָלֶיךָ מֶלֶךְ", "וליכון אלמלך אלד'י תנצבה", "and the king whom you appoint"),
        ("לֹא תוּכַל לָתֵת עָלֶיךָ", "ולא יגוז אן תנצב לך", "you may not appoint over yourself"),
        ("אִישׁ נָכְרִי", "רגלא ג'ריבא", "a foreign man"),
        ("אֲשֶׁר לֹא-אָחִיךָ הוּא", "מן ליס הו אכ'יך", "who is not your brother"),
    ],
    16: [
        ("רַק לֹא-יַרְבֶּה-לּוֹ סוּסִים", "לכן לא יסתכת'ר לה מן אלכ'יל", "Only he shall not accumulate for himself many horses"),
        ("וְלֹא-יָשִׁיב אֶת-הָעָם מִצְרַיְמָה", "ללא ירד אלקום אלי' מצר", "lest he return the people to Egypt"),
        ("לְמַעַן הַרְבּוֹת סוּס", "לאסתכת'אר אלכ'יל", "to acquire many horses"),
        ("וַיהוָה אָמַר לָכֶם", "ואללה פקד קאל לכם", "and God has already said to you"),
        ("לֹא תֹסִפוּן לָשׁוּב", "לא תעאודו אלרגוע", "You shall not again return"),
        ("בַּדֶּרֶךְ הַזֶּה עוֹד", "פי ד'אלך אלטריק אבדא", "by that road, ever"),
    ],
    17: [
        ("וְלֹא יַרְבֶּה-לּוֹ נָשִׁים", "ולא יסתכת'ר לה מן אלנסא", "And he shall not accumulate for himself many women"),
        ("וְלֹא יָסוּר לְבָבוֹ", "ללא יזול קלבה", "lest his heart go astray"),
        ("וְכֶסֶף וְזָהָב", "ומן אלפצ'ה ואלד'הב", "and silver and gold"),
        ("לֹא יַרְבֶּה-לּוֹ מְאֹד", "לא יסתכת'ר לה גדא", "he shall not accumulate for himself greatly"),
    ],
    18: [
        ("וְהָיָה כְשִׁבְתּוֹ", "וכמא יגלס", "And when he sits"),
        ("עַל כִּסֵּא מַמְלַכְתּוֹ", "עלי' כרסי מלכה", "upon the throne of his kingship"),
        ("וְכָתַב לוֹ", "יסתכתב לה", "he shall have copied out for himself"),
        ("אֶת-מִשְׁנֵה הַתּוֹרָה הַזֹּאת", "נסכ'ה' הד'ה אלתוריה", "a copy of this Torah"),
        ("עַל-סֵפֶר", "פי ספר", "in a book"),
        ("מִלִּפְנֵי הַכֹּהֲנִים הַלְוִיִּם", "מן חצרה' אלאימה ואלליואניין", "from the presence of the Levitical imāms"),
    ],
    19: [
        ("וְהָיְתָה עִמּוֹ", "תכון מעה", "It shall be with him"),
        ("וְקָרָא בוֹ", "יקרא פיהא", "and he shall read in it"),
        ("כָּל-יְמֵי חַיָּיו", "טול אייאם חיאתה", "all the days of his life"),
        ("לְמַעַן יִלְמַד", "לכי יתעלם", "so that he may learn"),
        ("לְיִרְאָה", "אן יכ'אף", "to fear"),
        ("אֶת-יְהוָה אֱלֹהָיו", "אללה רבה", "God his Lord"),
        ("לִשְׁמֹר", "ויחפץ'", "and observe"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע כלאם הד'ה אלתוריה", "all the words of this Torah"),
        ("וְאֶת-הַחֻקִּים הָאֵלֶּה", "והד'ה אלרסום", "and these ordinances"),
        ("לַעֲשֹׂתָם", "ליעמל בהא", "to act by them"),
    ],
    20: [
        ("לְבִלְתִּי רוּם-לְבָבוֹ", "ללא ירתפע קלבה", "so that his heart not be lifted up"),
        ("מֵאֶחָיו", "עלי' אכ'ותה", "above his brothers"),
        ("וּלְבִלְתִּי סוּר מִן-הַמִּצְוָה", "וללא יזול מן אלשריעה", "and so that he not deviate from the law"),
        ("יָמִין", "ימנה", "to the right"),
        ("וּשְׂמֹאול", "ולא יסרה", "or to the left"),
        ("לְמַעַן יַאֲרִיךְ יָמִים", "לכי תטול אייאמה", "in order that his days be prolonged"),
        ("עַל-מַמְלַכְתּוֹ", "עלי' ממלכתה", "over his kingdom"),
        ("הוּא", "הו", "he"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("בְּקֶרֶב יִשְׂרָאֵל", "פי מא בין בני אסראיל", "among the sons of Israel"),
    ],
}
