"""Hand-authored alignment triples for Devarim chapter 27.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers Moses and the elders commanding inscription of the Torah on
plastered stones at Mount Ebal, construction of an altar, the tribal stations on
Gerizim (blessing) and Ebal (curse), and the twelve Levitical curse-formulas
(vv. 15–26) each closed by the congregational "Amen."
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְצַו", "אמר", "commanded"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("וְזִקְנֵי יִשְׂרָאֵל", "ושיוך' אל אסראיל", "and the elders of the house of Israel"),
        ("אֶת-הָעָם", "אלקום", "the people"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("שָׁמֹר", "אחפצ'ו", "Observe"),
        ("אֶת-כָּל-הַמִּצְוָה", "גמיע אלוצייה", "all the commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם", "אלד'י אמרכם בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "today"),
    ],
    2: [
        ("וְהָיָה", "פיכון", "And it shall be"),
        ("בַּיּוֹם", "פי יום", "on the day"),
        ("אֲשֶׁר תַּעַבְרוּ", "תעברון", "that you cross"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-יְהוָה אֱלֹהֶיךָ נֹתֵן לָךְ", "אלד'י אללה רבך מעטיך", "which God your Lord is giving you"),
        ("וַהֲקֵמֹתָ לְךָ אֲבָנִים גְּדֹלוֹת", "אנצב לך חגארה ]עט'ימה] עצ'ימה", "set up for yourself great stones"),
        ("וְשַׂדְתָּ אֹתָם בַּשִּׂיד", "ובייצ'הא באספידאג", "and whitewash them with white lead"),
    ],
    3: [
        ("וְכָתַבְתָּ עֲלֵיהֶן", "ואכתב עליהא", "And write upon them"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע עיון הד'ה אלתורייה", "all the essentials of this Torah"),
        ("בְּעָבְרֶךָ", "בעד עבורך", "after your crossing"),
        ("לְמַעַן אֲשֶׁר תָּבֹא", "לכי תפתח", "so that you may enter"),
        ("אֶל-הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר-יְהוָה אֱלֹהֶיךָ נֹתֵן לְךָ", "אלד'י אללה רבך מעטיך", "which God your Lord is giving you"),
        ("אֶרֶץ זָבַת חָלָב", "בלד יפיץ' לבנא", "a land flowing with milk"),
        ("וּדְבַשׁ", "ועסלא", "and honey"),
        ("כַּאֲשֶׁר דִּבֶּר", "כמא ועדך", "as"),
        ("יְהוָה אֱלֹהֵי-אֲבֹתֶיךָ", "אללה אלאה אבאיך", "God the God of your fathers promised you"),
    ],
    4: [
        ("וְהָיָה בְּעָבְרְכֶם", "פמן אוול מא תעברון", "And so, from the first of your crossing"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("תָּקִימוּ", "תנצבו", "you shall erect"),
        ("אֶת-הָאֲבָנִים הָאֵלֶּה", "הד'ה אלחגארה", "these stones"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם הַיּוֹם", "אלד'י אמרתכם בהא אליום", "which I have commanded you today"),
        ("בְּהַר עֵיבָל", "פי גבל עיבל", "on Mount Ebal"),
        ("וְשַׂדְתָּ אוֹתָם בַּשִּׂיד", "ובייצ'הא באספיד'אג", "and whitewash them with white lead"),
    ],
    5: [
        ("וּבָנִיתָ שָּׁם", "ואבן ת'ם", "And build there"),
        ("מִזְבֵּחַ", "מד'בחא", "an altar"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
        ("מִזְבַּח אֲבָנִים", "מד'בח מן חגארה", "an altar of stones"),
        ("לֹא-תָנִיף עֲלֵיהֶם בַּרְזֶל", "לא תחרך עליהא חדידא", "do not move iron upon it"),
    ],
    6: [
        ("אֲבָנִים שְׁלֵמוֹת", "ולתכון מע ד'אלך חגארה צחיחה", "And let there be alongside that whole stones"),
        ("וְהַעֲלִיתָ עָלָיו", "וקרב עליהא", "and offer upon it"),
        ("עוֹלֹת", "צואעדא", "ascent-offerings"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "to God your Lord"),
    ],
    7: [
        ("וְזָבַחְתָּ שְׁלָמִים", "ואד'בח ד'באיח סלאמה", "And slaughter peace-offerings"),
        ("וְאָכַלְתָּ שָּׁם", "וכלהא הנאך", "and eat them there"),
        ("וְשָׂמַחְתָּ", "ואפרח", "and rejoice"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
    ],
    8: [
        ("וְכָתַבְתָּ", "וקד כתבת", "And you shall write"),
        ("עַל-הָאֲבָנִים", "עלי' אלחגארה", "upon the stones"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע עיון הד'ה אלתורייה", "all the essentials of the words of this Torah"),
        ("בַּאֵר הֵיטֵב", "שרחא גיידא", "as a clear and good exposition"),
    ],
    9: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר מֹשֶׁה", "כלם מוסי'", "Moses"),
        ("וְהַכֹּהֲנִים", "ואלאימה", "and the imāms"),
        ("הַלְוִיִּם", "ואלליואניין", "and the Levites spoke"),
        ("אֶל כָּל-יִשְׂרָאֵל", "אל אסראיל", "to the house of Israel"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("הַסְכֵּת", "ארכן", "Be attentive"),
        ("וּשְׁמַע", "ואסמע", "and hear"),
        ("יִשְׂרָאֵל", "יא אל אסראיל", "O house of Israel"),
        ("הַיּוֹם הַזֶּה", "יומך הד'א", "this very day"),
        ("נִהְיֵיתָ לְעָם", "קד' צרת שעבא", "have become a people"),
        ("לַיהוָה אֱלֹהֶיךָ", "ללה רבך", "of God your Lord"),
    ],
    10: [
        ("וְשָׁמַעְתָּ", "פאקבל", "Accept"),
        ("בְּקוֹל יְהוָה אֱלֹהֶיךָ", "קולה", "His word"),
        ("וְעָשִׂיתָ", "ואעמל", "and do"),
        ("אֶת-מִצְו‍ֹתָו", "וצאיאה", "His commandments"),
        ("וְאֶת-חֻקָּיו", "ורסומה", "and His statutes"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם", "אלד'י אמרך בהא אליום", "which I command you today"),
    ],
    11: [
        (None, "ת'ם", "Then"),
        ("וַיְצַו מֹשֶׁה", "אמר מוסי'", "Moses commanded"),
        ("אֶת-הָעָם", "קומה", "his people"),
        ("בַּיּוֹם הַהוּא", "פי דאלך אליום", "on that day"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    12: [
        ("אֵלֶּה יַעַמְדוּ", "הולאי יקומון", "These shall stand"),
        ("לְבָרֵךְ", "ליבארכו", "to bless"),
        ("אֶת-הָעָם", "אלאמה", "the nation"),
        ("עַל-הַר גְּרִזִים", "ענד גבל גריזים", "at Mount Gerizim"),
        ("בְּעָבְרְכֶם אֶת-הַיַּרְדֵּן", "בעד עבורכם אלארדן", "after your crossing the Jordan"),
        ("שִׁמְעוֹן", "אל שמעון", "the house of Simeon"),
        ("וְלֵוִי", "ולוי", "and Levi"),
        ("וִיהוּדָה", "ויהודה", "and Judah"),
        ("וְיִשָּׂשכָר", "ויששכר", "and Issachar"),
        ("וְיוֹסֵף", "ויוסף", "and Joseph"),
        ("וּבִנְיָמִן", "ובנימין", "and Benjamin"),
    ],
    13: [
        ("וְאֵלֶּה יַעַמְדוּ", "והולאי יקומון", "And these shall stand"),
        ("עַל-הַקְּלָלָה", "עלי' אללענה", "over the curse"),
        ("בְּהַר עֵיבָל", "עלי' גבל עיבל", "upon Mount Ebal"),
        ("רְאוּבֵן", "אל ראובן", "the house of Reuben"),
        ("גָּד", "וגד", "and Gad"),
        ("וְאָשֵׁר", "ואשר", "and Asher"),
        ("וּזְבוּלֻן", "וזבולון", "and Zebulun"),
        ("דָּן", "דן", "Dan"),
        ("וְנַפְתָּלִי", "ונפתלי", "and Naphtali"),
    ],
    14: [
        ("וְעָנוּ הַלְוִיִּם", "פיבתדו אלליואניין", "Then the Levites shall begin"),
        ("וְאָמְרוּ", "ויקולון", "and say"),
        ("אֶל-כָּל-אִישׁ יִשְׂרָאֵל", "לגמיע אל אסראיל", "to all the house of Israel"),
        ("קוֹל רָם", "בצות עאל", "with a loud voice"),
    ],
    15: [
        ("אָרוּר", "מלעון", "Cursed is"),
        ("הָאִישׁ", "רגל", "the man"),
        ("אֲשֶׁר יַעֲשֶׂה פֶסֶל", "יצנע פסלא", "who makes a graven image"),
        ("וּמַסֵּכָה", "או מסבוכא", "or a cast image"),
        ("תּוֹעֲבַת יְהוָה", "ממא יכרהה אללה", "of what God abhors"),
        ("מַעֲשֵׂה יְדֵי חָרָשׁ", "או יתכ'ד'ה מן צנעה' צאנע", "or takes one from the craft of an artisan"),
        ("וְשָׂם בַּסָּתֶר", "ויציירה פי סתר", "and sets it in secret"),
        ("וְעָנוּ כָל-הָעָם", "פיגיבהם גמיע אלקום", "And all the people shall answer them"),
        ("וְאָמְרוּ אָמֵן", "ויקולון אמין", "and say: 'Amen.'"),
    ],
    16: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("מַקְלֶה אָבִיו", "מסתכ'ף באביה", "he who treats his father"),
        ("וְאִמּוֹ", "ואמה", "and his mother with contempt"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    17: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("מַסִּיג גְּבוּל רֵעֵהוּ", "מן יזייג' תכ'ם צאחבה", "he who shifts the boundary of his neighbor"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    18: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("מַשְׁגֶּה עִוֵּר בַּדָּרֶךְ", "מצ'ל גאהל פי אלטריק", "he who leads one who is unknowing astray on the road"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    19: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("מַטֶּה מִשְׁפַּט", "מן ימייל", "he who perverts the judgment"),
        ("גֵּר-יָתוֹם", "חכם ג'ריב או יתים", "of a stranger, or an orphan"),
        ("וְאַלְמָנָה", "או ארמלה", "or a widow"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    20: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("שֹׁכֵב עִם-אֵשֶׁת אָבִיו", "מן יצ'אגע זוג'ה אביה", "he who lies with the wife of his father"),
        ("כִּי גִלָּה כְּנַף אָבִיו", "למא כשף כנף אביה", "for he has uncovered the skirt of his father"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    21: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("שֹׁכֵב עִם-כָּל-בְּהֵמָה", "מן יצ'אגע שייא מן אלבהאים", "he who lies with anything of the beasts"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    22: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("שֹׁכֵב עִם-אֲחֹתוֹ", "מן יצ'אגע אכ'תה", "he who lies with his sister"),
        ("בַּת-אָבִיו", "אבנה' אביה", "the daughter of his father"),
        ("אוֹ בַת-אִמּוֹ", "או אבנה' אמה", "or the daughter of his mother"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    23: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("שֹׁכֵב עִם-חֹתַנְתּוֹ", "מן יצ'אגע חמאתה", "he who lies with his mother-in-law"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    24: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("מַכֵּה רֵעֵהוּ בַּסָּתֶר", "מן יסעי בצאחבה סרא", "he who acts treacherously against his neighbor in secret"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    25: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("לֹקֵחַ שֹׁחַד", "מן יאכ'ד' רשוה", "he who takes a bribe"),
        ("לְהַכּוֹת נֶפֶשׁ דָּם נָקִי", "ליקתל נפסא זכייא", "to kill an innocent soul"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
    26: [
        ("אָרוּר", "ומלעון", "Cursed is"),
        ("אֲשֶׁר לֹא-יָקִים", "מן לם י'ת'בת", "he who does not uphold"),
        ("אֶת-דִּבְרֵי הַתּוֹרָה-הַזֹּאת", "כלאם הד'ה אלתורייה", "the words of this Torah"),
        ("לַעֲשׂוֹת אוֹתָם", "ליעמל בהא", "so as to act by them"),
        ("וְאָמַר כָּל-הָעָם", "ויקול גמיע אלקום", "And all the people shall say"),
        ("אָמֵן", "אמין", "Amen"),
    ],
}
