"""Hand-authored alignment triples for Devarim chapter 30.

Word-level: each JA (Saadia) word or short phrase is its own group, mapped to
the Hebrew word it renders and its English counterpart. The runtime resolver
matches each side independently (lib/alignment.ts), so words link correctly
even across word-order crossings. Words Saadia adds with no Hebrew source
(glosses, expansions) carry he=None and link JA↔English only.

This chapter covers the return from exile and regathering (vv. 1–5), the
circumcision / opening of the heart (v. 6), the "it is not in heaven" passage
(vv. 11–13), and the climactic "choose life" call (vv. 19–20).

Note: verse 9 is absent from the source data file; only vv. 1–8, 10–20 are
present.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואד'א", "And when"),
        ("כִי-יָבֹאוּ", "חלת", "befall"),
        ("עָלֶיךָ", "בך", "you"),
        ("כָּל-הַדְּבָרִים הָאֵלֶּה", "גמיע הד'ה אלאמור", "all these things"),
        ("הַבְּרָכָה", "מן אלברכאת", "the blessings"),
        ("וְהַקְּלָלָה", "ואללענאת", "and the curses"),
        ("אֲשֶׁר נָתַתִּי", "אלתי תלותהא", "which I have recited aloud"),
        ("לְפָנֶיךָ", "עליך", "over you"),
        ("וַהֲשֵׁבֹתָ", "פארגע", "take it"),
        ("אֶל-לְבָבֶךָ", "אלי' נפסך", "to heart"),
        (None, "ועלי' אנך", "that you are"),
        ("בְּכָל-הַגּוֹיִם", "פי מא בין גמיע אלאמם", "in the midst of all the nations"),
        ("אֲשֶׁר הִדִּיחֲךָ", "אלד'י דחאך", "to which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord has driven you"),
        ("שָׁמָּה", "אלי' ת'ם", "there"),
    ],
    2: [
        ("וְשַׁבְתָּ", "פתוב", "Then return"),
        ("עַד-יְהוָה", "אלי' אללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְשָׁמַעְתָּ בְקֹלוֹ", "ואקבל אמרה", "and accept His command"),
        ("כְּכֹל אֲשֶׁר-אָנֹכִי מְצַוְּךָ", "מת'ל גמיע מא אנא אמרך בה", "like all that I command you"),
        ("הַיּוֹם", "אליום", "this day"),
        ("אַתָּה", "אנת", "you"),
        ("וּבָנֶיךָ", "ובניך", "and your sons"),
        ("בְּכָל-לְבָבְךָ", "בכל קלבך", "with all your heart"),
        ("וּבְכָל-נַפְשֶׁךָ", "ונפסך", "and all your soul"),
    ],
    3: [
        (None, "פאן", "For"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְשָׁב", "יתוב", "will return"),
        ("וְרִחֲמֶךָ", "עליך וירחמך", "to you in mercy and have compassion on you"),
        ("וְשָׁב", "ויעוד", "and will return"),
        ("וְקִבֶּצְךָ", "ויגמעך", "and gather you"),
        ("מִכָּל-הָעַמִּים", "מן גמיע אלשעוב", "from all the peoples"),
        ("אֲשֶׁר הֱפִיצְךָ", "אלד'י בדדך", "among whom He has scattered you"),
        ("שָׁמָּה", "הנאך", "there"),
    ],
    4: [
        (None, "חתי'", "So that even"),
        ("נִדַּחֲךָ", "אלמנדחי מנך", "one of yours who has been driven away"),
        ("אִם-יִהְיֶה", "לו כאן", "were he"),
        ("בִּקְצֵה הַשָּׁמָיִם", "פי אקצא אלסמא", "at the farthest reaches of the sky"),
        ("יְקַבֶּצְךָ", "לגמע שמלך", "would gather your scattered ones"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "מן ת'ם", "from there"),
        ("וּמִשָּׁם יִקָּחֶךָ", "ולקדמך", "and bring you forward"),
    ],
    5: [
        ("וֶהֱבִיאֲךָ", "וידכ'לך", "And"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord will bring you"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "into the land"),
        ("אֲשֶׁר-יָרְשׁוּ אֲבֹתֶיךָ", "אלד'י חאזוה אבאיך", "which your fathers possessed"),
        ("וִירִשְׁתָּהּ", "ותחוזה", "and you shall possess it"),
        ("וְהֵיטִבְךָ", "ויחסן אליך", "and He will deal well with you"),
        ("וְהִרְבְּךָ", "ויכת'רך", "and make you more numerous"),
        ("מֵאֲבֹתֶיךָ", "מן אבאיך", "than your fathers"),
    ],
    6: [
        ("וּמָל", "וישרח", "And"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord will open wide"),
        ("אֶת-לְבָבְךָ", "צדרך", "your heart"),
        ("וְאֶת-לְבַב זַרְעֶךָ", "וצדר נסלך", "and the heart of your offspring"),
        ("לְאַהֲבָה", "לתחב", "for love of"),
        ("אֶת-יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בְּכָל-לְבָבְךָ", "בכל קלבך", "with all your heart"),
        ("וּבְכָל-נַפְשְׁךָ", "וכל נפסך", "and all your soul"),
        ("לְמַעַן חַיֶּיךָ", "לכי תחיא", "that you may live"),
    ],
    7: [
        ("וְנָתַן", "ויחל", "And"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord will bring down"),
        ("אֵת כָּל-הָאָלוֹת הָאֵלֶּה", "גמיע הד'א אלחרג", "all this distress"),
        ("עַל-אֹיְבֶיךָ", "באעדאיך", "upon your enemies"),
        ("וְעַל-שֹׂנְאֶיךָ", "ובשאנייך", "and upon those who hate you"),
        ("אֲשֶׁר רְדָפוּךָ", "אלד'י כלבוך", "who have been ferocious toward you"),
    ],
    8: [
        ("וְאַתָּה", "ואנת", "And you"),
        ("תָשׁוּב", "תתוב", "shall return"),
        ("וְשָׁמַעְתָּ בְּקוֹל יְהוָה", "ותקבל אמר אללה", "and accept the command of God"),
        ("וְעָשִׂיתָ", "ותעמל", "and do"),
        ("אֶת-כָּל-מִצְו‍ֹתָיו", "גמיע וצאיאה", "all His commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלד'י אמרך בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "this day"),
    ],
    10: [
        ("כִּי תִשְׁמַע בְּקוֹל יְהוָה", "אד' תקבל אמר אללה", "When you accept the command of God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לִשְׁמֹר", "פתחפץ'", "and keep"),
        ("מִצְו‍ֹתָיו", "גמיע וצאיאה", "all His commandments"),
        ("וְחֻקֹּתָיו", "ורסומה", "and His statutes"),
        ("הַכְּתוּבָה", "אלמכתובה", "written"),
        ("בְּסֵפֶר הַתּוֹרָה הַזֶּה", "פי הד'א ספר אלתורייה", "in this book of the Torah"),
        ("כִּי תָשׁוּב", "אד' תתוב", "when you return"),
        ("אֶל-יְהוָה", "אלי' אללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("בְּכָל-לְבָבְךָ", "בכל קלבך", "with all your heart"),
        ("וּבְכָל-נַפְשֶׁךָ", "וכל נפסך", "and all your soul"),
    ],
    11: [
        (None, "ואעלם", "And know"),
        (None, "אן", "that"),
        ("הַמִּצְוָה הַזֹּאת", "הד'ה אלוצייה", "these commandments"),
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "אלד'י אמרך בהא", "which I command you"),
        ("הַיּוֹם", "אליום", "this day"),
        ("לֹא-נִפְלֵאת", "ליס בכ'פייה", "are not hidden"),
        ("מִמְּךָ", "ענך", "from you"),
        ("וְלֹא רְחֹקָה", "ולא בעידה", "nor are they distant"),
    ],
    12: [
        ("לֹא בַשָּׁמַיִם", "ליסהא פי אלסמא", "They are not in the sky"),
        ("לֵאמֹר", "פיקול קאיל", "so that one might say"),
        ("מִי יַעֲלֶה-לָּנוּ", "מן ד'א יצעד לנא", "who shall ascend for us"),
        ("הַשָּׁמַיְמָה", "אלי' אלסמא", "to the sky"),
        ("וְיִקָּחֶהָ לָּנוּ", "וינזלהא לנא", "and bring them down to us"),
        ("וְיַשְׁמִעֵנוּ אֹתָהּ", "ויסמענאהא", "and make us hear them"),
        ("וְנַעֲשֶׂנָּה", "ונעמל בהא", "that we may act by them"),
    ],
    13: [
        ("וְלֹא-מֵעֵבֶר לַיָּם", "וליס הי פי ד'אך גאנב אלבחר", "Nor are they on that far side of the sea"),
        ("לֵאמֹר", "פיקול קאיל", "so that one might say"),
        ("מִי יַעֲבָר-לָנוּ", "מן ד'א יעבר לנא", "who shall cross over for us"),
        ("אֶל-עֵבֶר הַיָּם", "אלי ד'אך גאנב אלבחר", "to that far side of the sea"),
        ("וְיִקָּחֶהָ לָּנוּ", "פיאכ'דהא לנא", "and fetch them for us"),
        ("וְיַשְׁמִעֵנוּ אֹתָהּ", "ויסמענאהא", "and make us hear them"),
        ("וְנַעֲשֶׂנָּה", "ונעמל בהא", "that we may act by them"),
    ],
    14: [
        (None, "בל", "Rather"),
        ("הַדָּבָר", "אלאמר", "the matter"),
        ("קָרוֹב", "קריב", "is very near"),
        ("אֵלֶיךָ", "אליך", "to you"),
        ("מְאֹד", "גדא", "— it is possible"),
        (None, "ימכנך", "for you"),
        ("בְּפִיךָ", "בפאך", "by your mouth"),
        ("וּבִלְבָבְךָ", "ובקלבך", "and by your heart"),
        ("לַעֲשֹׂתוֹ", "אן תעמל בה", "to act by it"),
    ],
    15: [
        ("רְאֵה", "אנצ'ר", "See"),
        (None, "אני", "I"),
        ("נָתַתִּי", "קד געלת", "have placed"),
        ("לְפָנֶיךָ", "בין ידיך", "before you"),
        ("הַיּוֹם", "אליום", "this day"),
        ("אֶת-הַחַיִּים", "אלחיאה", "life"),
        ("וְאֶת-הַטּוֹב", "ואלכ'יר", "and good"),
        ("וְאֶת-הַמָּוֶת", "ואלמות", "and death"),
        ("וְאֶת-הָרָע", "ואלשר", "and evil"),
    ],
    16: [
        ("אֲשֶׁר אָנֹכִי מְצַוְּךָ", "עלי' מא אמרך בה", "In accordance with what I command you"),
        ("הַיּוֹם", "אליום", "this day"),
        ("לְאַהֲבָה", "אן תחבב", "that you love"),
        ("אֶת-יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לָלֶכֶת בִּדְרָכָיו", "ותסיר פי טרקה", "and walk in His ways"),
        ("וְלִשְׁמֹר מִצְו‍ֹתָיו", "ותחפץ' וצאיאה", "and keep His commandments"),
        ("וְחֻקֹּתָיו", "ורסומה", "and His statutes"),
        ("וּמִשְׁפָּטָיו", "ואחכאמה", "and His ordinances"),
        ("וְחָיִיתָ", "פתחיא", "so that you may live"),
        ("וְרָבִיתָ", "ותכת'ר", "and multiply"),
        ("וּבֵרַכְךָ", "ויבארך לך", "and"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord may bless you"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-אַתָּה בָא-שָׁמָּה", "אלד' אנת צאיר אליה", "to which you are journeying"),
        ("לְרִשְׁתָּהּ", "לתחוזה", "to possess it"),
    ],
    17: [
        ("וְאִם-יִפְנֶה לְבָבְךָ", "ואן תולא קלבך", "But if your heart turns away"),
        ("וְלֹא תִשְׁמָע", "ולם תקבל ד'אלך", "and you do not accept that"),
        ("וְנִדַּחְתָּ", "ומלת", "and you incline"),
        ("וְהִשְׁתַּחֲוִיתָ", "וסגדת", "and bow down"),
        ("לֵאלֹהִים אֲחֵרִים", "למעבודאת אכ'ר", "to other objects of worship"),
        ("וַעֲבַדְתָּם", "ועבדתהא", "and serve them"),
    ],
    18: [
        (None, "פקד", "I declare"),
        ("הִגַּדְתִּי", "אכ'ברתכם", "to you"),
        ("לָכֶם", "מן אליום", "this day"),
        ("הַיּוֹם", "אנכם", "that you"),
        ("כִּי אָבֹד תֹּאבֵדוּן", "סתבידון", "shall surely perish"),
        ("לֹא-תַאֲרִיכֻן יָמִים", "ולא תטול מדתכם", "and your days shall not be long"),
        ("עַל-הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר אַתָּה עֹבֵר", "אלד'י אנת עאבר", "to which you are crossing"),
        ("אֶת-הַיַּרְדֵּן", "אלארדן", "the Jordan"),
        ("לָבוֹא שָׁמָּה", "לתציר אליה", "to go"),
        ("לְרִשְׁתָּהּ", "לתחוזה", "to possess it"),
    ],
    19: [
        ("הַעִדֹתִי", "וקד אשהדת", "And I have called to witness"),
        ("בָכֶם", "עליכם", "against you"),
        ("הַיּוֹם", "אליום", "this day"),
        ("אֶת-הַשָּׁמַיִם", "אלסמא", "the sky"),
        ("וְאֶת-הָאָרֶץ", "ואלארץ'", "and the earth"),
        ("הַחַיִּים", "אלחיאה", "life"),
        ("וְהַמָּוֶת", "ואלמות", "and death"),
        ("נָתַתִּי", "באני קד געלת", "I have placed"),
        ("לְפָנֶיךָ", "בין ידיכם", "before you"),
        ("הַבְּרָכָה", "ואלברכאת", "and blessings"),
        ("וְהַקְּלָלָה", "ואללענאת", "and curses"),
        (None, "וארא לך", "and it is my counsel to you"),
        ("וּבָחַרְתָּ בַּחַיִּים", "אן תכ'תאר אלחיאה", "that you choose life"),
        ("לְמַעַן תִּחְיֶה", "לכי תחיא", "so that you may live"),
        ("אַתָּה", "אנת", "you"),
        ("וְזַרְעֶךָ", "ונסלך", "and your offspring"),
    ],
    20: [
        (None, "וד'אלך", "And that is"),
        ("לְאַהֲבָה", "באן תחבב", "by loving"),
        ("אֶת-יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("לִשְׁמֹעַ בְּקֹלוֹ", "ותקבל אמרה", "accepting His command"),
        ("וּלְדָבְקָה-בוֹ", "ותלזם טאעתה", "and cleaving to obedience of Him"),
        ("כִּי הוּא חַיֶּיךָ", "אד' הו חיותך", "for He is your life"),
        ("וְאֹרֶךְ יָמֶיךָ", "וטול מדתך", "and the length of your days"),
        ("לָשֶׁבֶת", "אן תקים", "by remaining"),
        ("עַל-הָאֲדָמָה", "פי אלבלד", "in the land"),
        ("אֲשֶׁר נִשְׁבַּע", "אלד'י קסם", "which"),
        ("יְהוָה", "אללה", "God"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "apportioned to your fathers"),
        ("לְאַבְרָהָם", "לאברהים", "to Abraham"),
        ("לְיִצְחָק", "ויצחק", "and Isaac"),
        ("וּלְיַעֲקֹב", "ויעקוב", "and Jacob"),
        ("לָתֵת לָהֶם", "אן יעטיהם", "to give to them"),
    ],
}
