"""Hand-authored alignment triples for Devarim chapter 22.

Word-level: each JA (Saadia) word or tight phrase is its own group, mapped to
the Hebrew word it renders and its English counterpart. The runtime resolver
matches each side independently (lib/alignment.ts), so words link correctly
even across word-order crossings. Words Saadia adds with no Hebrew source
(glosses, expansions) carry he=None and link JA↔English only.

This chapter covers returning lost property, the bird's nest mitzvah, the
parapet (מַעֲקֶה), kilayim / shaatnez / tzitzit (vv. 9–12), and the slandered
bride and sexual-offense laws (vv. 13–29) — aligned with particular care for
Saadia's legal expansions (בראה "proof of innocence" for בְּתוּלִים, דרהם for
כֶסֶף, etc.).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא-תִרְאֶה", "ולא תרא", "And you shall not see"),
        ("אֶת-שׁוֹר אָחִיךָ", "ת'ור אכי'ך", "your brother's ox"),
        ("אוֹ אֶת-שֵׂיוֹ", "או שאתה", "or his sheep"),
        ("נִדָּחִים", "צ'אלין", "going astray"),
        ("וְהִתְעַלַּמְתָּ מֵהֶם", "פתתג'אפל ענהמא", "and ignore them"),
        (None, "בל", "rather"),
        ("הָשֵׁב תְּשִׁיבֵם לְאָחִיךָ", "רדהמא אליה רדא", "return them to him with a returning"),
    ],
    2: [
        ("וְאִם-לֹא", "ואן לם יכון", "And if"),
        ("אָחִיךָ", "אכי'ך", "your brother"),
        ("קָרוֹב", "קריבא", "is not near"),
        ("אֵלֶיךָ", "אליך", "to you"),
        ("וְלֹא יְדַעְתּוֹ", "ולם תערפה", "and you do not know him"),
        ("וַאֲסַפְתּוֹ", "פצ'ם ד'אלך", "then gather it"),
        ("אֶל-תּוֹךְ בֵּיתֶךָ", "אלי' מנזלך", "into your dwelling"),
        ("וְהָיָה עִמְּךָ", "יכון ענדך", "it shall be with you"),
        ("עַד דְּרֹשׁ אָחִיךָ אֹתוֹ", "אלי' אן ילתמסה אכי'ך", "until your brother seeks it"),
        ("וַהֲשֵׁבֹתוֹ לוֹ", "פתרדה עליה", "and then you shall return it to him"),
    ],
    3: [
        ("וְכֵן תַּעֲשֶׂה", "וכד'א פאצנע", "And so shall you do"),
        ("לַחֲמֹרוֹ", "בחמארה", "with his donkey"),
        ("וְכֵן תַּעֲשֶׂה לְשִׂמְלָתוֹ", "ובת'ובה", "and with his garment"),
        ("וְכֵן תַּעֲשֶׂה לְכָל-אֲבֵדַת אָחִיךָ", "ובסאיר צ'ואל אכי'ך", "and with the rest of the lost things of your brother"),
        ("אֲשֶׁר-תֹּאבַד מִמֶּנּוּ", "אלד'י תצ'יע מנה", "that are lost from him"),
        ("וּמְצָאתָהּ", "פתגדהא", "and you find"),
        ("לֹא תוּכַל לְהִתְעַלֵּם", "לא יחל לך אן תתג'אפל ענהא", "it is not permitted for you to ignore them"),
    ],
    4: [
        ("לֹא-תִרְאֶה", "ולא תרא", "And you shall not see"),
        ("אֶת-חֲמוֹר אָחִיךָ", "חמאר אכי'ך", "your brother's donkey"),
        ("אוֹ שׁוֹרוֹ", "או ת'ורה", "or his ox"),
        ("נֹפְלִים בַּדֶּרֶךְ", "ואקעין פי אלטריק", "fallen on the road"),
        ("וְהִתְעַלַּמְתָּ מֵהֶם", "פתתג'אפל ענהמא", "and ignore them"),
        (None, "בל", "rather"),
        ("הָקֵם תָּקִים עִמּוֹ", "אקמהמא מעה אקאמה", "raise them up with him with a raising"),
    ],
    5: [
        ("לֹא-יִהְיֶה כְלִי-גֶבֶר עַל-אִשָּׁה", "לא תכון אלאת אלרגאל עלי' אלנסא", "The implements of men shall not be upon women"),
        ("וְלֹא-יִלְבַּשׁ גֶּבֶר", "ולא ילבס אלרגאל", "nor shall men wear"),
        ("שִׂמְלַת אִשָּׁה", "זיי אלנסא", "the attire of women"),
        ("כִּי", "לאן", "for"),
        ("יְהוָה", "אללה", "the Lord"),
        ("אֱלֹהֶיךָ", "רבך", "your God"),
        ("תוֹעֲבַת", "יכרה", "abhors"),
        ("כָּל-עֹשֵׂה אֵלֶּה", "כל מן יצנע ד'אלך", "all who do this"),
    ],
    6: [
        ("כִּי יִקָּרֵא", "ואן ואפית", "And if you come upon"),
        ("קַן-צִפּוֹר", "וכרא מן אלטאיר", "a bird's nest"),
        ("לְפָנֶיךָ", "קדאמך", "before you"),
        ("בַּדֶּרֶךְ", "פי אלטריק", "on the road"),
        ("בְּכָל-עֵץ", "או פי שגרה", "or in a tree"),
        ("אוֹ עַל-הָאָרֶץ", "או עלי' אלארץ'", "or on the ground"),
        ("אֶפְרֹחִים", "פראכ'א", "chicks"),
        ("אוֹ בֵיצִים", "או ביצ'א", "or eggs"),
        ("וְהָאֵם רֹבֶצֶת עַל-הָאֶפְרֹחִים", "ואלאם ראבצה עליהם", "and the mother is roosting upon them"),
        ("לֹא-תִקַּח הָאֵם", "פלא תאכ'ד' אלאם", "you shall not take the mother"),
        ("עַל-הַבָּנִים", "מע אלבנין", "together with the young"),
    ],
    7: [
        (None, "בל", "Rather"),
        ("שַׁלֵּחַ תְּשַׁלַּח אֶת-הָאֵם", "א'טלק אלאם אטלאקא", "release the mother with a releasing"),
        ("וְאֶת-הַבָּנִים תִּקַּח-לָךְ", "וכ'ד' אלבנין לנפסך", "and take the young for yourself"),
        ("לְמַעַן יִיטַב לָךְ", "לכי יכ'אר לך", "so that it may go well for you"),
        ("וְהַאֲרַכְתָּ יָמִים", "ותטול אייאמך", "and your days may be prolonged"),
    ],
    8: [
        ("כִּי תִבְנֶה", "ואד'א בנית", "And when you build"),
        ("בַּיִת חָדָשׁ", "ביתא גדידא", "a new house"),
        ("וְעָשִׂיתָ מַעֲקֶה", "פאצנע דראבזין", "make a railing"),
        ("לְגַגֶּךָ", "עלי' סטחך", "upon your roof"),
        ("וְלֹא-תָשִׂים דָּמִים", "ולא תגעל ג'דרא", "and do not place a hidden danger"),
        ("בְּבֵיתֶךָ", "פי מנזלך", "in your dwelling"),
        ("כִּי-יִפֹּל הַנֹּפֵל מִמֶּנּוּ", "יסקט מנה מן יסקט", "that one who falls may fall from it"),
    ],
    9: [
        ("לֹא-תִזְרַע", "לא תזרע", "Do not sow"),
        ("כַּרְמְךָ", "כרמך", "your vineyard"),
        ("כִּלְאָיִם", "מן נועין", "with two kinds"),
        ("פֶּן-תִּקְדַּשׁ", "כילא תחרם עליך", "lest there be forbidden to you"),
        ("הַמְלֵאָה", "סלאפה'", "the first-yield"),
        ("הַזֶּרַע אֲשֶׁר תִּזְרָע", "אלזרע אלד'י תזרעה", "of the seed that you sow"),
        ("וּתְבוּאַת הַכָּרֶם", "מע ג'לה' אלכרם", "together with the produce of the vineyard"),
    ],
    10: [
        ("לֹא-תַחֲרֹשׁ", "לא תצ'מד", "Do not yoke"),
        ("בְּשׁוֹר", "אלת'ור", "the ox"),
        ("וּבַחֲמֹר", "ואלחמאר", "and the donkey"),
        ("יַחְדָּו", "גמיעא", "together"),
    ],
    11: [
        ("לֹא תִלְבַּשׁ שַׁעַטְנֵז", "לא תלבס ת'ובא מכ'תלטא", "Do not wear a garment of mixed material"),
        ("צֶמֶר", "מן צוף", "of wool"),
        ("וּפִשְׁתִּים", "וכתאן", "and linen"),
        ("יַחְדָּו", "גמיעא", "together"),
    ],
    12: [
        ("גְּדִלִים תַּעֲשֶׂה-לָּךְ", "ואצנע לך גדאילא", "And make for yourself braided cords"),
        ("עַל-אַרְבַּע", "פי ארבע", "on the four"),
        ("כַּנְפוֹת", "אטראף", "corners of"),
        ("כְּסוּתְךָ", "אזארך", "your garment"),
        ("אֲשֶׁר תְּכַסֶּה-בָּהּ", "אלד'י תג'טא בהא", "with which you cover yourself"),
    ],
    13: [
        ("כִּי-יִקַּח אִישׁ אִשָּׁה", "ואן תזווג רגל באמראה", "And if a man takes a woman in marriage"),
        ("וּבָא אֵלֶיהָ", "ודכל אליהא", "and enters in to her"),
        ("וּשְׂנֵאָהּ", "ת'ם שנאהא", "and then comes to hate her"),
    ],
    14: [
        ("וְשָׂם לָהּ עֲלִילֹת דְּבָרִים", "פגעל להא עללא מן אלכלאם", "and he fabricates pretextual charges against her"),
        ("וְהוֹצִא עָלֶיהָ שֵׁם רָע", "ואכ'רג עליהא אסמא רדייא", "and puts out evil names concerning her"),
        (None, "וקאל", "and says:"),
        (None, "אני", "'I"),
        ("לָקַחְתִּי", "תזווגת", "took"),
        ("אֶת-הָאִשָּׁה הַזֹּאת", "הד'ה אלאמראה", "this woman in marriage"),
        ("וָאֶקְרַב אֵלֶיהָ", "פדנות מנהא", "and when I drew near to her"),
        ("וְלֹא-מָצָאתִי לָהּ בְּתוּלִים", "ולם אגד להא בראה", "I did not find for her a proof of innocence'"),
    ],
    15: [
        ("וְלָקַח אֲבִי הַנַּעֲרָ וְאִמָּהּ", "ת'ם יאכ'ד' אביהא ואמהא", "then her father and her mother shall take"),
        ("אֶת-בְּתוּלֵי הַנַּעֲרָ", "אלבראה", "that proof of innocence"),
        ("וְהוֹצִיאוּ", "ויכ'רגוהא", "and bring it out"),
        ("אֶל-זִקְנֵי הָעִיר", "אלי' שיוך' אלקריה", "to the elders of the town"),
        ("הַשָּׁעְרָה", "ואלי' באב אלחאכם", "and to the gate of the judge"),
    ],
    16: [
        ("וְאָמַר אֲבִי הַנַּעֲרָ", "פקאל אביהא", "And her father shall say"),
        ("אֶל-הַזְּקֵנִים", "לאלש'יוך'", "to the elders:"),
        (None, "אני", "'I"),
        ("נָתַתִּי", "זווגת", "gave"),
        ("אֶת-בִּתִּי", "אבנתי", "my daughter"),
        ("לָאִישׁ הַזֶּה לְאִשָּׁה", "להד'א אלרג'ל", "in marriage to this man"),
        ("וַיִּשְׂנָאֶהָ", "פשנאהא", "and he came to hate her.'"),
    ],
    17: [
        ("וְהִנֵּה-הוּא שָׂם עֲלִילֹת דְּבָרִים", "והוד'א הו קד געל להא עללא מן אלכלאם", "And this very one has fabricated pretextual charges against her"),
        ("לֵאמֹר", "וקאל", "saying:"),
        ("לֹא-מָצָאתִי לְבִתְּךָ בְּתוּלִים", "לם אגד להא בראה", "'I did not find for her a proof of innocence'"),
        ("וְאֵלֶּה בְּתוּלֵי בִתִּי", "והד'א בראתהא", "but here is her proof of innocence.'"),
        ("וּפָרְשׂוּ הַשִּׂמְלָה", "ובסטו אלמנדיל", "And they shall spread out the cloth"),
        (None, "או מקאמה", "or its equivalent"),
        ("לִפְנֵי זִקְנֵי הָעִיר", "בין ידיהם", "before them"),
    ],
    18: [
        ("וְלָקְחוּ זִקְנֵי הָעִיר-הַהִוא", "פליאכ'ד' שיוך' תלך אלקריה", "Then the elders of that town shall take"),
        ("אֶת-הָאִישׁ", "ד'אלך אלרגל", "that man"),
        ("וְיִסְּרוּ אֹתוֹ", "ויוד'בוה", "and discipline him"),
    ],
    19: [
        ("וְעָנְשׁוּ אֹתוֹ", "ויג'רמוה", "And they shall fine him"),
        ("מֵאָה כֶסֶף", "מאיה' דרהם", "a hundred dirhams"),
        ("וְנָתְנוּ", "וידפעוהא", "and pay them"),
        ("לַאֲבִי הַנַּעֲרָה", "לאבו אלגאריה", "to the girl's father"),
        ("כִּי הוֹצִיא שֵׁם רָע", "למא אכ'רג אסמא רדייא", "because he put out an evil name"),
        ("עַל בְּתוּלַת יִשְׂרָאֵל", "עלי' בכר מן אל אסראיל", "against a virgin of the house of Israel"),
        ("וְלוֹ-תִהְיֶה לְאִשָּׁה", "ותכון לה זוגה", "and she shall be his wife"),
        ("לֹא-יוּכַל לְשַׁלְּחָהּ", "ולא יגוז לה טלאקהא", "and it is not permitted for him to divorce her"),
        ("כָּל-יָמָיו", "טול עמרה", "all his days"),
    ],
    20: [
        ("וְאִם-אֱמֶת הָיָה הַדָּבָר הַזֶּה", "ואן כאן אלאמר חקא", "But if the matter is true"),
        ("לֹא-נִמְצְאוּ בְתוּלִים לַנַּעֲרָ", "ולם תוגד לאלגאריה בראה", "and no proof of innocence is found for the girl"),
    ],
    21: [
        ("וְהוֹצִיאוּ אֶת-הַנַּעֲרָ", "פאלתכ'רג", "then let her be brought out"),
        ("אֶל-פֶּתַח בֵּית-אָבִיהָ", "אלי' באב בית אביהא", "to the door of her father's house"),
        ("וּסְקָלוּהָ", "וירגמוהא", "shall stone her"),
        ("אַנְשֵׁי עִירָהּ", "גמיע אהל קריתהא", "all the people of her town"),
        ("בָּאֲבָנִים", "באלחגארה", "with stones"),
        ("וָמֵתָה", "אלי' אן תמות", "until she dies"),
        ("כִּי-עָשְׂתָה נְבָלָה בְּיִשְׂרָאֵל", "למא צנעת כ'סאסה פי אל אסראיל", "because she committed a vile act among the house of Israel"),
        ("לִזְנוֹת בֵּית אָבִיהָ", "פפגרת מחצנה פי בית אביהא", "fornicating while under the protection of her father's house"),
        ("וּבִעַרְתָּ הָרָע מִקִּרְבֶּךָ", "ואנף אהל אלשר מן בינכם", "And purge those who do evil from among you"),
    ],
    22: [
        ("כִּי-יִמָּצֵא אִישׁ", "ואן וגד רגל", "And if a man is found"),
        ("שֹׁכֵב עִם-אִשָּׁה", "מצ'אגע אמראה", "lying with a woman"),
        ("בְעֻלַת-בַּעַל", "ד'את בעל", "who has a husband"),
        ("וּמֵתוּ גַּם-שְׁנֵיהֶם", "פליקתלא גמיעא", "then both of them shall be put to death"),
        ("הָאִישׁ הַשֹּׁכֵב עִם-הָאִשָּׁה", "אלרגל אלמצ'אגעהא", "the man who lay with her"),
        ("וְהָאִשָּׁה", "והי", "and she"),
        ("וּבִעַרְתָּ הָרָע מִיִּשְׂרָאֵל", "ואנף אהל אלשר מן אל אסראיל", "And purge those who do evil from the house of Israel"),
    ],
    23: [
        ("כִּי יִהְיֶה נַעֲרָ בְתוּלָה", "ואד'א כאנת' גאריה בכר", "And if there is a young virgin girl"),
        ("מְאֹרָשָׂה לְאִישׁ", "ממלכה לרגל", "who has been betrothed to a man"),
        ("וּמְצָאָהּ אִישׁ", "פוגדהא רגל אכ'ר", "and another man finds her"),
        ("בָּעִיר", "פי אלקריה", "in the town"),
        ("וְשָׁכַב עִמָּהּ", "וצ'אגעהא", "and lies with her"),
    ],
    24: [
        ("וְהוֹצֵאתֶם אֶת-שְׁנֵיהֶם", "פאכ'רגוהמא גמיעא", "then bring the two of them out"),
        ("אֶל-שַׁעַר הָעִיר הַהִוא", "אלי' באב תלך אלקריה", "to the gate of that town"),
        ("וּסְקַלְתֶּם אֹתָם בָּאֲבָנִים", "ותרגמוהמא באלחגארה", "and stone them both with stones"),
        ("וָמֵתוּ", "אלי' אן ימותא", "until they die"),
        ("אֶת-הַנַּעֲרָ", "אמא אלגאריה", "as for the girl"),
        ("עַל-דְּבַר אֲשֶׁר לֹא-צָעֲקָה בָעִיר", "פבסבב מא לם תצרך' והי פי אלקריה", "because she did not cry out while she was in the town"),
        ("וְאֶת-הָאִישׁ", "ואמא אלרגל", "and as for the man"),
        ("עַל-דְּבַר אֲשֶׁר-עִנָּה אֶת-אֵשֶׁת רֵעֵהוּ", "בסבב מא אתא זוגה' צאחבה", "because he came upon the wife of his fellow"),
        ("וּבִעַרְתָּ הָרָע מִקִּרְבֶּךָ", "ואנף אהל אלשר מן בינכם", "And purge those who do evil from among you"),
    ],
    25: [
        ("וְאִם-בַּשָּׂדֶה יִמְצָא הָאִישׁ", "ואן וגד אלרגל", "But if the man finds"),
        ("אֶת-הַנַּעֲרָ הַמְאֹרָשָׂה", "אלגאריה אלממלכה", "the betrothed girl"),
        (None, "פי אלצחרא", "in the wilderness"),
        ("וְהֶחֱזִיק-בָּהּ הָאִישׁ", "ואמסכהא", "and seizes her"),
        ("וְשָׁכַב עִמָּהּ", "וצ'אגעהא", "and lies with her"),
        ("וּמֵת הָאִישׁ אֲשֶׁר-שָׁכַב עִמָּהּ", "פליקתל ד'אלך אלרגל אלמצ'אגעהא", "then that man who lay with her"),
        ("לְבַדּוֹ", "וחדה", "alone shall be put to death"),
    ],
    26: [
        ("וְלַנַּעֲרָ לֹא-תַעֲשֶׂה דָבָר", "ואמא אלגאריה פלא תצנע בהא שייא", "But as for the girl, do nothing to her"),
        ("אֵין לַנַּעֲרָ חֵטְא מָוֶת", "אד' ליס להא כ'טייה תוגב אלקתל", "for she has no sin warranting death"),
        (None, "ואנמא", "For"),
        ("כֵּן הַדָּבָר הַזֶּה", "מת'ל אמרהא הד'א", "this matter"),
        ("כִּי כַּאֲשֶׁר יָקוּם אִישׁ עַל-רֵעֵהוּ", "כמן יקום עלי' צאחבה", "is like one who rises up against his fellow"),
        ("וּרְצָחוֹ נֶפֶשׁ", "פיקתלה", "and kills him"),
        (None, "ויפיתה נפסה", "thereby taking his life from him"),
    ],
    27: [
        ("כִּי בַשָּׂדֶה מְצָאָהּ", "ואן וגדהא פי אלצחרא", "For he found her in the wilderness"),
        ("צָעֲקָה הַנַּעֲרָ הַמְאֹרָשָׂה", "פימכן אן יכון קד צרכת", "it is possible that she cried out"),
        ("וְאֵין מוֹשִׁיעַ לָהּ", "ולם יכון להא מג'ית'", "but there was no rescuer for her"),
    ],
    28: [
        ("כִּי-יִמְצָא אִישׁ", "ואן וגד רגל", "And if a man finds"),
        ("נַעֲרָ בְתוּלָה", "גאריה בכר", "a young virgin girl"),
        ("אֲשֶׁר לֹא-אֹרָשָׂה", "מא לם תמלך", "who has not been betrothed"),
        ("וּתְפָשָׂהּ", "פצ'בטהא", "and he seizes her"),
        ("וְשָׁכַב עִמָּהּ", "וצ'אגעהא", "and lies with her"),
        ("וְנִמְצָאוּ", "ווגדא", "and they are found"),
    ],
    29: [
        ("וְנָתַן הָאִישׁ הַשֹּׁכֵב עִמָּהּ", "פליעט ד'אלך אלרגל", "then that man shall give"),
        ("לַאֲבִי הַנַּעֲרָ", "לאביהא", "to her father"),
        ("חֲמִשִּׁים כָּסֶף", "כ'מסין דרהם", "fifty dirhams"),
        ("וְלוֹ-תִהְיֶה לְאִשָּׁה", "ותכון לה זוגה", "and she shall be his wife"),
        ("תַּחַת אֲשֶׁר עִנָּהּ", "בדל מא אתאהא", "in recompense for what he did to her"),
        ("לֹא-יוּכַל שַׁלְּחָהּ", "לא יגוז לה טלאקהא", "it is not permitted for him to divorce her"),
        ("כָּל-יָמָיו", "טול עמרה", "all his days"),
    ],
}
