"""Hand-authored alignment triples for Devarim chapter 12.

Word-level: each JA (Saadia) word or close group is mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers destroying the Canaanite cult sites (altars, pillars,
asherim), the central "place that God will choose" (המקום אשר יבחר) for all
offerings, the contrast of that unified worship with "every man what is right
in his own eyes," the permission for non-sacral slaughter away from the
sanctuary, and the strong repeated prohibition on eating blood ("be firm not
to eat the blood… pour it on the earth like water"). Saadia renders the
Tetragrammaton as אללה and "your Lord" as רבכם/רבך throughout; שם as "His
light" (נורה); and the sacrifice-types (עלה → צואעד, זבח → ד'באיח, מעשר → עשור,
תרומה → רפאיע, נדר → נדור, נדבה → תברע, בכור → בכור) are kept consistent
across the chapter.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "הד'ה אואיל", "These are the first"),
        ("אֵלֶּה הַחֻקִּים", "אלרסום", "of the statutes"),
        ("וְהַמִּשְׁפָּטִים", "ואלאחכאם", "and ordinances"),
        ("אֲשֶׁר תִּשְׁמְרוּן", "אלד'י תחפצוהא", "which you shall keep"),
        ("לַעֲשׂוֹת", "ותעמלו בהא", "and act by"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר נָתַן", "אלד'י אעטאך", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵי אֲבֹתֶיךָ", "אלאה אבאיך", "the Lord of your fathers, has given you"),
        ("לְרִשְׁתָּהּ", "אן תחוזוה", "to possess"),
        ("כָּל-הַיָּמִים", "טול אלזמאן", "for all the length of time"),
        ("אֲשֶׁר-אַתֶּם חַיִּים", "אלד'י אנתם אחיא", "that you are alive"),
        ("עַל-הָאֲדָמָה", "עלא אלארץ'", "upon the earth"),
    ],
    2: [
        (None, "והו אן", "And it is that"),
        ("אַבֵּד תְּאַבְּדוּן", "תבידו", "you shall destroy"),
        ("אֶת-כָּל-הַמְּקֹמוֹת", "גמיע אלמואצ'ע", "all the places"),
        ("אֲשֶׁר עָבְדוּ-שָׁם", "אלד'י עבד ת'ם", "where"),
        ("הַגּוֹיִם", "אלאמם", "the nations"),
        ("אֲשֶׁר אַתֶּם יֹרְשִׁים", "אלד'י אנתם קארצ'והם", "whom you are dispossessing by your power"),
        ("אֹתָם", "מע מעבודאתהם", "with their objects of worship"),
        ("עַל-הֶהָרִים הָרָמִים", "עלי' אלגבל אלרפאע", "upon the high mountains"),
        ("וְעַל-הַגְּבָעוֹת", "ועלי' אליפאע", "and upon the hillocks"),
        ("וְתַחַת כָּל-עֵץ רַעֲנָן", "ותחת כל שגר ריאן", "and beneath every lush tree"),
    ],
    3: [
        ("וְנִתַּצְתֶּם", "ואנקצ'ו", "And pull down"),
        ("אֶת-מִזְבְּחֹתָם", "מד'אבחהם", "their altars"),
        ("וְשִׁבַּרְתֶּם", "וכסרו", "and shatter"),
        ("אֶת-מַצֵּבֹתָם", "דכאכהם", "their stone pillars"),
        ("וַאֲשֵׁרֵיהֶם", "וסואריהם", "and their cultic poles"),
        ("תִּשְׂרְפוּן בָּאֵשׁ", "אחרקוהא באלנאר", "burn them with fire"),
        ("וּפְסִילֵי אֱלֹהֵיהֶם", "ופסול מעבודאתהם", "and the graven images of their objects of worship"),
        ("תְּגַדֵּעוּן", "תגדעוהא", "hew them down"),
        ("וְאִבַּדְתֶּם", "ואבידו", "and destroy"),
        ("אֶת-שְׁמָם", "אסמאיהם", "their names"),
        ("מִן-הַמָּקוֹם הַהוּא", "מן ד'אלך אלמוצ'ע", "from that place"),
    ],
    4: [
        ("לֹא-תַעֲשׂוּן", "לא תצנעו", "You shall not do"),
        (None, "כד'אך", "so"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
    ],
    5: [
        (None, "בל", "But"),
        ("אֶל-הַמָּקוֹם", "אלי' אלמוצ'ע", "to the place"),
        ("אֲשֶׁר-יִבְחַר", "אלד'י יכ'תארה", "which"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord shall choose"),
        ("מִכָּל-שִׁבְטֵיכֶם", "מן גמיע אסבאטכם", "from among all your tribes"),
        ("לָשׂוּם אֶת-שְׁמוֹ שָׁם", "ליחל נורה פיה", "to let His light dwell therein"),
        ("לְשִׁכְנוֹ תִדְרְשׁוּ", "אלתמסו מסכנה", "seek out His dwelling"),
        ("וּבָאתָ שָּׁמָּה", "חתי' תצירו אליה", "until you make your way thither"),
    ],
    6: [
        ("וַהֲבֵאתֶם שָׁמָּה", "פתחמלו אליה", "And you shall bring there"),
        ("עֹלֹתֵיכֶם", "צואעדכם", "your burnt-offerings"),
        ("וְזִבְחֵיכֶם", "וד'באיחכם", "and your sacrifices"),
        ("וְאֵת מַעְשְׂרֹתֵיכֶם", "ועשורכם", "and your tithes"),
        ("וְאֵת תְּרוּמַת יֶדְכֶם", "ורפאיעכם", "and your raised-offerings"),
        ("וְנִדְרֵיכֶם", "ונדורכם", "and your votive-offerings"),
        ("וְנִדְבֹתֵיכֶם", "ותברעכם", "and your freewill-offerings"),
        ("וּבְכֹרֹת בְּקַרְכֶם", "ובכור בקרכם", "and the firstborn of your cattle"),
        ("וְצֹאנְכֶם", "וג'נמכם", "and of your flock"),
    ],
    7: [
        ("וַאֲכַלְתֶּם-שָׁם", "פתאכלוהא ת'ם", "And you shall eat them there"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("וּשְׂמַחְתֶּם", "ואפרחו", "and rejoice"),
        ("בְּכֹל מִשְׁלַח יֶדְכֶם", "בגמיע מא אנבסטת בה אידיכם", "in all to which your hands have been extended"),
        ("אַתֶּם", "אנתם", "you"),
        ("וּבָתֵּיכֶם", "וביותכם", "and your households"),
        ("אֲשֶׁר בֵּרַכְךָ", "כמא רזקך", "as"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord has provided for you"),
    ],
    8: [
        ("לֹא תַעֲשׂוּן", "לא תצנעו", "You shall not do"),
        (None, "מן הד'א אלאמור", "from these matters"),
        ("כְּכֹל אֲשֶׁר אֲנַחְנוּ עֹשִׂים", "כמא נחן צאנעין", "as we are doing"),
        ("הַיּוֹם", "אליום", "today"),
        ("אִישׁ", "כל אנסאן", "every person"),
        ("כָּל-הַיָּשָׁר בְּעֵינָיו", "מא חסן ענדה", "according to what seems good to him"),
    ],
    9: [
        ("כִּי לֹא-בָאתֶם", "פאנכם לם תצירו", "For you have not"),
        ("עַד-עָתָּה", "בעד", "yet come"),
        ("אֶל-הַמְּנוּחָה", "אלי' אלמסתקר", "to the resting-place"),
        ("וְאֶל-הַנַּחֲלָה", "ואלנחלה", "and the inheritance"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("נֹתֵן לָךְ", "מעטיך", "is giving you"),
    ],
    10: [
        ("וַעֲבַרְתֶּם אֶת-הַיַּרְדֵּן", "פאד'א עברתם אלארדן", "But when you have crossed the Jordan"),
        ("וִישַׁבְתֶּם", "וגלסתם", "and settled"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("אֲשֶׁר-יְהוָה", "אלד'י אללה", "which God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("מַנְחִיל אֶתְכֶם", "מנחלכם", "is granting you as inheritance"),
        ("וְהֵנִיחַ לָכֶם", "ואראחכם", "and He has given you rest"),
        ("מִכָּל-אֹיְבֵיכֶם", "מן גמיע אעדאיכם", "from all your enemies"),
        ("מִסָּבִיב", "אלמחיטין בכם", "round about you"),
        ("וִישַׁבְתֶּם-בֶּטַח", "וגלסתם ואת'קין", "and you have settled in security"),
    ],
    11: [
        (None, "ואי", "then, whatever"),
        ("וְהָיָה הַמָּקוֹם", "מוצ'ע", "place"),
        ("אֲשֶׁר-יִבְחַר", "יכ'תארה", "shall choose"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("לְשַׁכֵּן שְׁמוֹ שָׁם", "ליחל נורה פיה", "to let His light dwell therein"),
        ("שָׁמָּה תָבִיאוּ", "אליה תאתו", "thither shall you come"),
        ("אֵת כָּל-אֲשֶׁר אָנֹכִי מְצַוֶּה אֶתְכֶם", "בגמיע מא אנא אמרכם", "accompanied by all that I command you"),
        ("עוֹלֹתֵיכֶם", "מן צואעדכם", "your burnt-offerings"),
        ("וְזִבְחֵיכֶם", "וד'באיחכם", "and your sacrifices"),
        ("מַעְשְׂרֹתֵיכֶם", "ועשורכם", "and your tithes"),
        ("וּתְרֻמַת יֶדְכֶם", "ורפאיעכם", "and your raised-offerings"),
        ("וְכֹל מִבְחַר נִדְרֵיכֶם", "וכ'יאר נדורכם", "and the choicest of your votive-offerings"),
        ("אֲשֶׁר תִּדְּרוּ לַיהוָה", "אלד'י תנד'רוהא ללה", "which you vow"),
    ],
    12: [
        ("וּשְׂמַחְתֶּם", "ואפרחו בהא", "And rejoice in them"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("אַתֶּם", "אנתם", "you"),
        ("וּבְנֵיכֶם", "ובניכם", "and your sons"),
        ("וּבְנֹתֵיכֶם", "ובנאתכם", "and your daughters"),
        ("וְעַבְדֵיכֶם", "ועבידכם", "and your male servants"),
        ("וְאַמְהֹתֵיכֶם", "ואמאכם", "and your maidservants"),
        ("וְהַלֵּוִי", "ואללוי", "and the Levite"),
        ("אֲשֶׁר בְּשַׁעֲרֵיכֶם", "אלד'י פי מחאלכם", "who is in your settlements"),
        ("כִּי אֵין לוֹ", "אד' ליס לה", "for he has no"),
        ("חֵלֶק", "נציב", "portion"),
        ("וְנַחֲלָה", "ונחלה", "and inheritance"),
        ("אִתְּכֶם", "מעכם", "with you"),
    ],
    13: [
        ("הִשָּׁמֶר לְךָ", "אחד'ר", "Take heed"),
        ("פֶּן-תַּעֲלֶה עֹלֹתֶיךָ", "אן תקרב קראבינך", "lest you offer your offering"),
        ("בְּכָל-מָקוֹם", "פי אי מוצ'ע", "in whatever place"),
        ("אֲשֶׁר תִּרְאֶה", "ראיתה", "you see fit"),
    ],
    14: [
        (None, "אלא", "But only"),
        ("בַּמָּקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר-יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God shall choose"),
        ("בְּאַחַד שְׁבָטֶיךָ", "באחד אסבאטך", "among one of your tribes"),
        ("שָׁם תַּעֲלֶה עֹלֹתֶיךָ", "ת'ם תקרב קראבינך", "there you shall offer your offering"),
        ("וְשָׁם תַּעֲשֶׂה", "ותצנע ת'ם", "and there you shall do"),
        ("כֹּל אֲשֶׁר אָנֹכִי מְצַוֶּךָּ", "גמיע מא אמרך בה", "all that I command you"),
    ],
    15: [
        (None, "לכן", "However"),
        ("רַק בְּכָל-אַוַּת נַפְשְׁךָ", "מתא מא אשתהת נפסך", "whenever your soul desires"),
        ("תִּזְבַּח", "אללחם", "meat"),
        (None, "פאד'בח", "slaughter"),
        ("וְאָכַלְתָּ בָשָׂר", "וכל", "and eat"),
        ("כְּבִרְכַּת יְהוָה", "כרזק אללה", "according to the provision which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲשֶׁר נָתַן-לְךָ", "אלד'י אעטאך", "has given you"),
        ("בְּכָל-שְׁעָרֶיךָ", "פי סאיר קראך", "in all your other towns"),
        ("הַטָּמֵא וְהַטָּהוֹר", "אלטאהר ואלנגס", "and it is permitted that the clean and the unclean"),
        ("יֹאכְלֶנּוּ", "יאכל מנה", "may eat of it"),
        ("כַּצְּבִי וְכָאַיָּל", "כמא יוכלאן לחם י אלצ'בי ואלאיל", "just as one eats the meat of the gazelle and the deer"),
    ],
    16: [
        ("רַק הַדָּם", "כ'לא אלדם", "Except the blood"),
        ("לֹא תֹאכֵלוּ", "לא תאכלוה", "you shall not eat it"),
        (None, "בל", "rather"),
        ("עַל-הָאָרֶץ תִּשְׁפְּכֶנּוּ", "צבה עלי' אלארץ", "pour it upon the earth"),
        ("כַּמָּיִם", "כאלמא", "like water"),
    ],
    17: [
        ("לֹא-תוּכַל לֶאֱכֹל", "ולא יגוז אן תאכל", "And it is not permitted that you eat"),
        ("בִּשְׁעָרֶיךָ", "פי מחאלך", "in your settlements"),
        ("מַעְשַׂר דְּגָנְךָ", "עשור ברך", "the tithes of your grain"),
        ("וְתִירֹשְׁךָ", "ועצירך", "and your juice"),
        ("וְיִצְהָרֶךָ", "ודהנך", "and your oil"),
        ("וּבְכֹרֹת בְּקָרְךָ", "ובכור בקרך", "and the firstborn of your cattle"),
        ("וְצֹאנֶךָ", "וג'נמך", "and your flock"),
        ("וְכָל-נְדָרֶיךָ אֲשֶׁר תִּדֹּר", "ונדורך אלד'י תנדרהא", "and your vows which you vow"),
        ("וְנִדְבֹתֶיךָ", "ותברעך", "and your freewill-offerings"),
        ("וּתְרוּמַת יָדֶךָ", "ורפאיעך", "and your raised-offerings"),
    ],
    18: [
        (None, "אלא", "But"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("תֹּאכְלֶנּוּ", "תאכלה", "shall you eat them"),
        ("בַּמָּקוֹם אֲשֶׁר יִבְחַר", "פי אלמוצ'ע אלד'י יכ'תארה", "in the place which He shall choose"),
        ("יְהוָה אֱלֹהֶיךָ בּוֹ", "אנת", "— you"),
        ("אַתָּה", "ואבנך", "and your son"),
        ("וּבִנְךָ", "ואבנתך", "and your daughter"),
        ("וּבִתֶּךָ", "ועבדך", "and your male servant"),
        ("וְעַבְדְּךָ", "ואמתך", "and your maidservant"),
        ("וַאֲמָתֶךָ", "ואללוי", "and the Levite"),
        ("וְהַלֵּוִי אֲשֶׁר בִּשְׁעָרֶיךָ", "אלד'י פי מחלך", "who is in your settlements"),
        ("וְשָׂמַחְתָּ", "ואפרח", "and rejoice"),
        ("לִפְנֵי יְהוָה אֱלֹהֶיךָ", "בין ידי אללה רבך", "before God your Lord"),
        ("בְּכֹל מִשְׁלַח יָדֶךָ", "במא אנבסטת בה ידך", "in all to which your hand has been extended"),
    ],
    19: [
        ("הִשָּׁמֶר לְךָ", "ואחד'ר", "And take heed"),
        ("פֶּן-תַּעֲזֹב אֶת-הַלֵּוִי", "אן תגפו אללוי", "lest you neglect the Levite"),
        ("כָּל-יָמֶיךָ", "טול מקאמך", "all the length of your sojourn"),
        ("עַל-אַדְמָתֶךָ", "פי בלדך", "in your land"),
    ],
    20: [
        ("כִּי-יַרְחִיב", "ואד'א אוסע", "And when"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶת-גְּבֻלְךָ", "תכ'מך", "enlarges your territory"),
        ("כַּאֲשֶׁר דִּבֶּר-לָךְ", "כמא ועדך", "as He has promised you"),
        ("וְאָמַרְתָּ", "פקלת", "and you say"),
        ("אֹכְלָה בָשָׂר", "אכל לחמא", "I would eat meat"),
        ("כִּי-תְאַוֶּה נַפְשְׁךָ", "ען שהוה מן נפסך לה", "out of your soul's desire for it"),
        ("לֶאֱכֹל בָּשָׂר", "פכלה", "then eat it"),
        ("בְּכָל-אַוַּת נַפְשְׁךָ תֹּאכַל בָּשָׂר", "מתא מא אשתהיתה", "whenever you desire"),
    ],
    21: [
        ("כִּי-יִרְחַק מִמְּךָ הַמָּקוֹם", "ואן בעד ענך אלמוצ'ע", "And if the place"),
        ("אֲשֶׁר יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord shall choose"),
        ("לָשׂוּם שְׁמוֹ שָׁם", "ליחל נורה פיה", "to let His light dwell therein"),
        (None, "פאד'בח", "be far from you, then slaughter"),
        ("מִבְּקָרְךָ", "מן בקרך", "from your cattle"),
        ("וּמִצֹּאנְךָ", "וג'נמך", "and your flock"),
        ("אֲשֶׁר נָתַן יְהוָה לְךָ", "אלד'י רזקך אללה רבך", "which God your Lord has provided for you"),
        ("כַּאֲשֶׁר צִוִּיתִךָ", "כמא אמרתך", "as I have commanded you"),
        ("וְאָכַלְתָּ בִּשְׁעָרֶיךָ", "וכלה פי מחלך", "and eat it in your settlements"),
        ("בְּכֹל אַוַּת נַפְשֶׁךָ", "מתא מא אשתהתה נפסך", "whenever your soul desires it"),
    ],
    22: [
        (None, "לכן", "But"),
        ("אַךְ כַּאֲשֶׁר יֵאָכֵל", "כמא יוכל י", "just as"),
        ("אֶת-הַצְּבִי", "אלצ'בי", "the gazelle"),
        ("וְאֶת-הָאַיָּל", "ואלאיל", "and the deer are eaten"),
        ("כֵּן תֹּאכְלֶנּוּ", "כד'אך תאכלה", "so shall you eat it"),
        (None, "אן יגוז", "it being permitted"),
        ("הַטָּמֵא", "לאלנגס", "for the unclean"),
        ("וְהַטָּהוֹר", "ואלטאהר", "and the clean alike"),
        ("יַחְדָּו יֹאכְלֶנּוּ", "אן יאכלאן מנה", "to eat of it"),
    ],
    23: [
        (None, "לכן", "Only"),
        ("רַק חֲזַק", "תשדד", "be firm"),
        ("לְבִלְתִּי אֲכֹל הַדָּם", "פי אן לא תאכל אלדם", "in not eating the blood"),
        ("כִּי הַדָּם הוּא הַנָּפֶשׁ", "פאנה מסכן אלנפס", "for it is the dwelling of the soul"),
        ("וְלֹא-תֹאכַל הַנֶּפֶשׁ", "ולא תאכל אלנפס", "and you shall not eat the soul"),
        ("עִם-הַבָּשָׂר", "מע אללחם", "together with the meat"),
    ],
    24: [
        ("לֹא תֹּאכְלֶנּוּ", "ואד' לא תאכלה", "Since you shall not eat it"),
        (None, "בל", "rather"),
        ("עַל-הָאָרֶץ תִּשְׁפְּכֶנּוּ", "צבה עלי' אלארץ'", "pour it upon the earth"),
        ("כַּמָּיִם", "כאלמא", "like water"),
    ],
    25: [
        ("לֹא תֹּאכְלֶנּוּ", "ואד' לא תאכלה", "And since you shall not eat it"),
        (None, "כד'אך", "in this manner"),
        ("לְמַעַן יִיטַב לְךָ", "לכי יכ'אר לך", "it shall go well for you"),
        ("וּלְבָנֶיךָ אַחֲרֶיךָ", "ולבניך מן בעדך", "and for your children after you"),
        ("כִּי-תַעֲשֶׂה הַיָּשָׁר", "אד' תצנע אלמסתקים", "when you do what is right"),
        ("בְּעֵינֵי יְהוָה", "ענד אללה", "before God"),
    ],
    26: [
        (None, "עדא", "Except"),
        ("רַק קָדָשֶׁיךָ", "אקדאסך", "your holy-things"),
        ("אֲשֶׁר-יִהְיוּ לְךָ", "מא כאן לך מנהא", "whatever you may have of them"),
        ("וּנְדָרֶיךָ", "ונדורך", "and your vows"),
        ("תִּשָּׂא", "פאחמלהא", "carry them"),
        ("וּבָאתָ", "ואת בהא", "and bring them"),
        ("אֶל-הַמָּקוֹם", "אלי' אלמוצ'ע", "to the place"),
        ("אֲשֶׁר-יִבְחַר יְהוָה", "אלד'י יכ'תארה אללה", "which God shall choose"),
    ],
    27: [
        ("וְעָשִׂיתָ עֹלֹתֶיךָ", "פאצנע צואעדך", "And offer your burnt-offerings"),
        ("הַבָּשָׂר", "לחומהא", "their flesh"),
        ("וְהַדָּם", "ודמאהא", "and their blood"),
        (None, "כמאלא", "complete"),
        ("עַל-מִזְבַּח יְהוָה", "עלי' מד'בח אללה", "upon the altar of God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("וְדַם-זְבָחֶיךָ", "ומן דם ד'באיחך", "and of the blood of your sacrifices"),
        ("יִשָּׁפֵךְ", "יצב", "it shall be poured"),
        ("עַל-מִזְבַּח יְהוָה אֱלֹהֶיךָ", "עלי' מד'בחה", "upon His altar"),
        ("וְהַבָּשָׂר תֹּאכֵל", "וכל לחומהא", "and you shall eat their flesh"),
    ],
    28: [
        ("שְׁמֹר", "אחפץ'", "Keep"),
        ("וְשָׁמַעְתָּ", "ואקבל", "and accept"),
        ("אֵת כָּל-הַדְּבָרִים הָאֵלֶּה", "גמיע הד'ה אלאמור", "all these matters"),
        ("אֲשֶׁר אָנֹכִי מְצַוֶּךָּ", "אלד'י אמרך בהא", "which I command you"),
        ("לְמַעַן יִיטַב לְךָ", "לכי יכ'אר לך", "so that it may go well for you"),
        ("וּלְבָנֶיךָ אַחֲרֶיךָ", "ולבניך מן בעדך", "and for your children after you"),
        ("עַד-עוֹלָם", "אלי' אלדהר", "forever"),
        ("כִּי תַעֲשֶׂה הַטּוֹב", "אד' תצנע אלגייד", "since you do what is good"),
        ("וְהַיָּשָׁר", "ואלמסתקים", "and right"),
        ("בְּעֵינֵי יְהוָה", "ענד אללה", "before God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
    ],
    29: [
        ("כִּי-יַכְרִית", "ואד'א קטע", "And when"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֶת-הַגּוֹיִם", "אלאמם", "cuts off the nations"),
        ("אֲשֶׁר אַתָּה בָא-שָׁמָּה", "אלד'י אנת דאכ'ל אלי' ת'ם", "into whose midst you are entering"),
        ("לָרֶשֶׁת אוֹתָם", "לתקרצ'הם", "to dispossess them"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "by your power"),
        ("וְיָרַשְׁתָּ אֹתָם", "פאד'א קרצ'תהם", "and when you have dispossessed them"),
        ("וְיָשַׁבְתָּ בְּאַרְצָם", "וסכנת מכאנהם", "and settled in their place"),
    ],
    30: [
        ("הִשָּׁמֶר לְךָ", "פאחד'ר", "take heed"),
        ("פֶּן-תִּנָּקֵשׁ אַחֲרֵיהֶם", "אן תוהק פי תבעהם", "lest you be ensnared into following them"),
        ("אַחֲרֵי הִשָּׁמְדָם", "בעד אנפאד'הם", "after they have been destroyed"),
        ("מִפָּנֶיךָ", "מן בין ידיך", "from before you"),
        ("וּפֶן-תִּדְרֹשׁ לֵאלֹהֵיהֶם", "וכלא תלתמס מן מעבודאתהם", "and do not seek after their objects of worship"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("אֵיכָה יַעַבְדוּ הַגּוֹיִם הָאֵלֶּה אֶת-אֱלֹהֵיהֶם", "כיף כאן יעבדהא הולאי אלאמם", "How did these nations worship them"),
        ("וְאֶעֱשֶׂה-כֵּן גַּם-אָנִי", "פאצנע אנא איצ'א כד'אך", "I too shall do likewise"),
    ],
    31: [
        ("לֹא-תַעֲשֶׂה כֵן", "לא תצנע כד'אך", "You shall not do so"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "פאנה כת'ירא", "for many"),
        ("כִּי כָל-תּוֹעֲבַת יְהוָה", "ממא יכרהה אללה", "of the things that God abhors"),
        ("אֲשֶׁר שָׂנֵא", "וישנאה", "and loathes"),
        ("עָשׂוּ לֵאלֹהֵיהֶם", "צנעוה למעבודאתהם", "those they did for their objects of worship"),
        ("כִּי גַם אֶת-בְּנֵיהֶם", "חתי' בניהם", "even their sons"),
        ("וְאֶת-בְּנֹתֵיהֶם", "ובנאתהם", "and their daughters"),
        ("יִשְׂרְפוּ בָאֵשׁ", "קד יחרקוהא באלנאר", "they would burn in fire"),
        ("לֵאלֹהֵיהֶם", "להם", "for them"),
    ],
}
