"""Hand-authored alignment triples for Devarim chapter 29.

Word-level: each JA (Saadia) word/unit is mapped to the Hebrew word it
renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across
word-order crossings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.

This chapter covers the covenant in Moab: recalling the Exodus miracles and
the wilderness journey (vv. 1–7), the assembly of all Israel to enter the
covenant (vv. 8–14), the warning against anyone whose heart turns to idolatry
and against the "root bearing poisonous or bitter fruit" (vv. 15–17), the
consequences for the secret rebel (vv. 18–19), the future generation's
question and the answer about abandoning the covenant (vv. 20–27), and the
closing enigma of the hidden and revealed things (v. 28).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיִּקְרָא", "דעא", "called together"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        (None, "בגמיע", "all"),
        ("אֶל-כָּל-יִשְׂרָאֵל", "אל אסראיל", "the house of Israel"),
        ("וַיֹּאמֶר", "וקאל", "and said"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("אַתֶּם", "אנתם", "You"),
        ("רְאִיתֶם", "שאהדתם", "have witnessed"),
        ("אֵת כָּל-אֲשֶׁר עָשָׂה יְהוָה", "גמיע מא צנע אללה", "all that God did"),
        ("לְעֵינֵיכֶם", "בחצ'רתכם", "in your presence"),
        ("בְּאֶרֶץ מִצְרַיִם", "פי בלד מצר", "in the land of Egypt"),
        ("לְפַרְעֹה", "בפרעון", "with Pharaoh"),
        ("וּלְכָל-עֲבָדָיו", "וגמיע קואדה", "and with all his officers"),
        ("וּלְכָל-אַרְצוֹ", "ובסאיר אהל בלדה", "and with the rest of the people of his land"),
    ],
    2: [
        ("הַמַּסּוֹת הַגְּדֹלֹת", "אלאעלם אל]עט'ימה] עצ'ימה", "the great signs"),
        ("אֲשֶׁר רָאוּ עֵינֶיךָ", "אלד'י ראתהא עינאך", "which your eyes beheld"),
        ("הָאֹתֹת", "ותלך אלאיאת", "and those wonders"),
        ("וְהַמֹּפְתִים הַגְּדֹלִים הָהֵם", "ואלבראהין אל]עט'ימה] עצ'ימה", "and the great proofs"),
    ],
    3: [
        ("וְלֹא-נָתַן יְהוָה", "ולם יעטיכם אללה", "yet God has not given you"),
        ("לָכֶם", "קלבא", "a heart"),
        ("לֵב לָדַעַת", "תעלמון מת'להא", "to know the like of them"),
        ("וְעֵינַיִם לִרְאוֹת", "ולא תנצ'רון בעיונכם", "nor do you see with your eyes"),
        ("וְאָזְנַיִם לִשְׁמֹעַ", "ולא תסמעון באד'אנכם", "nor hear with your ears"),
        ("עַד הַיּוֹם הַזֶּה", "אלי' יומנא הד'א", "unto this our day"),
    ],
    4: [
        ("וָאוֹלֵךְ אֶתְכֶם", "וסיירתכם", "And I led you"),
        ("אַרְבָּעִים שָׁנָה", "ארבעין סנה", "forty years"),
        ("בַּמִּדְבָּר", "פי אלבר", "through the wilderness"),
        ("לֹא-בָלוּ שַׂלְמֹתֵיכֶם", "לם תבל תיאבכם", "your garments did not wear out"),
        ("מֵעֲלֵיכֶם", "עליכם", "upon you"),
        ("וְנַעַלְךָ", "ונעאלכם", "and your sandals"),
        ("לֹא-בָלְתָה מֵעַל רַגְלֶךָ", "עלי' ארגלכם", "upon your feet"),
    ],
    5: [
        ("לֶחֶם לֹא אֲכַלְתֶּם", "וטעאמכם אלד'י אעתדתמוה לם תאכלוה", "and the food which you were accustomed to — you did not eat it"),
        ("וְיַיִן", "וכ'מר", "and wine"),
        ("וְשֵׁכָר לֹא שְׁתִיתֶם", "ומסכר לם תשרבו", "and strong drink you did not drink"),
        (None, "פיקול לכם", "so that He might say to you"),
        ("לְמַעַן תֵּדְעוּ", "לכי תערפו", "so that you may know"),
        ("כִּי אֲנִי יְהוָה", "אני אללה", "that I am God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
    ],
    6: [
        (None, "חתי'", "Until"),
        ("וַתָּבֹאוּ", "ואפיתם", "you arrived"),
        ("אֶל-הַמָּקוֹם הַזֶּה", "הד'א אלמוצ'ע", "at this place"),
        ("וַיֵּצֵא", "וכ'רג", "came out"),
        ("סִיחֹן מֶלֶךְ-חֶשְׁבּוֹן", "סיחון מלך חשבון", "Sihon king of Heshbon"),
        ("וְעוֹג מֶלֶךְ-הַבָּשָׁן", "ועוג מלך אלבת'נייה", "and Og king of the Bashan"),
        ("לִקְרָאתֵנוּ", "תלקאנא", "to meet us"),
        ("לַמִּלְחָמָה", "לאלחרב", "for battle"),
        ("וַנַּכֵּם", "פקתלנאהמא", "and we slew them both"),
    ],
    7: [
        ("וַנִּקַּח", "פאכ'דנא", "And we took"),
        ("אֶת-אַרְצָם", "בלדהמא", "their lands"),
        (None, "ת'ם", "then"),
        ("וַנִּתְּנָהּ", "דפענאהא", "gave them"),
        ("לְנַחֲלָה", "נחלה", "as a possession"),
        ("לָראוּבֵנִי", "לאל ראובן", "to the Reubenites"),
        ("וְלַגָּדִי", "ואל גד", "and the Gadites"),
        ("וְלַחֲצִי שֵׁבֶט הַמְנַשִּׁי", "ונצף סבט מנשה", "and half the tribe of Manasseh"),
    ],
    8: [
        (None, "פאחפצו", "So keep"),
        ("אֶת-דִּבְרֵי הַבְּרִית הַזֹּאת", "גמיע כלאם הד'א אלעהד", "all the words of this covenant"),
        ("וַעֲשִׂיתֶם אֹתָם", "ואעמלו בה", "and act by it"),
        ("לְמַעַן תַּשְׂכִּילוּ", "לכי תנגחון", "so that you may succeed"),
        ("אֵת כָּל-אֲשֶׁר תַּעֲשׂוּן", "פי גמיע מא תצנעון", "in all that you do"),
    ],
    9: [
        ("אַתֶּם", "אנתם", "You"),
        ("נִצָּבִים", "וקוף", "are standing"),
        ("הַיּוֹם", "אליום", "today"),
        ("כֻּלְּכֶם", "כלכם", "all of you"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("רָאשֵׁיכֶם", "רויסאכם", "your chiefs"),
        ("שִׁבְטֵיכֶם", "ואסבאטכם", "and your tribes"),
        ("זִקְנֵיכֶם", "ושיוכ'כם", "and your elders"),
        ("וְשֹׁטְרֵיכֶם", "וערפאכם", "and your overseers"),
        ("כֹּל אִישׁ יִשְׂרָאֵל", "וסאיר רגאל אל אסראיל", "and the rest of the men of the house of Israel"),
    ],
    10: [
        ("טַפְּכֶם", "ואטפאלכם", "your children"),
        ("נְשֵׁיכֶם", "ונסאכם", "and your women"),
        ("וְגֵרְךָ", "ואלג'ריב", "and the stranger"),
        ("אֲשֶׁר בְּקֶרֶב מַחֲנֶיךָ", "אלד'י פי וסט עסכרך", "who is in the midst of your camp"),
        ("מֵחֹטֵב עֵצֶיךָ", "מן מחתטב חטבך", "from the hewer of your wood"),
        ("עַד שֹׁאֵב מֵימֶיךָ", "אלי מסתקי מאך", "to the drawer of your water"),
    ],
    11: [
        ("לְעָבְרְךָ", "לאדכ'אלך", "to enter you"),
        ("בִּבְרִית יְהוָה אֱלֹהֶיךָ", "פי עהד אללה רבך", "into the covenant of God your Lord"),
        ("וּבְאָלָתוֹ", "ופי חרגה", "and into His obligation"),
        ("אֲשֶׁר יְהוָה אֱלֹהֶיךָ כֹּרֵת עִמְּךָ", "אלד'י עהדה מעך", "which He is making with you"),
        ("הַיּוֹם", "אליום", "today"),
    ],
    12: [
        ("לְמַעַן הָקִים-אֹתְךָ", "לכי יתבתך", "so that He may establish you"),
        ("הַיּוֹם", "אליום", "today"),
        ("לוֹ לְעָם", "לה אמה", "as a nation for Him"),
        ("וְהוּא יִהְיֶה-לְּךָ לֵאלֹהִים", "והו יכון לך אלאהא", "and He may be your God"),
        ("כַּאֲשֶׁר דִּבֶּר-לָךְ", "כמא ועדך", "as He promised you"),
        ("וְכַאֲשֶׁר נִשְׁבַּע", "וכמא קסם", "and as He swore"),
        ("לַאֲבֹתֶיךָ", "לאבאיך", "to your fathers"),
        ("לְאַבְרָהָם", "לאברהים", "to Abraham"),
        ("לְיִצְחָק", "ליצחק", "to Isaac"),
        ("וּלְיַעֲקֹב", "וליעקוב", "and to Jacob"),
    ],
    13: [
        ("וְלֹא אִתְּכֶם", "וליס מעכם", "And it is not with you"),
        ("לְבַדְּכֶם", "וחדכם", "alone"),
        ("אָנֹכִי כֹּרֵת", "אנא עאהד", "that I am making"),
        ("אֶת-הַבְּרִית הַזֹּאת", "הד'א אלעהד", "this covenant"),
        ("וְאֶת-הָאָלָה הַזֹּאת", "והד'א אלחרג", "and this obligation"),
    ],
    14: [
        (None, "אלא", "but"),
        ("אֶת-אֲשֶׁר יֶשְׁנוֹ פֹּה עִמָּנוּ", "מע מן הו מוגוד מענא", "with whoever is present with us"),
        ("עֹמֵד הַיּוֹם", "חאצ'ר", "standing"),
        ("לִפְנֵי יְהוָה אֱלֹהֵינוּ", "בין ידי אללה רבנא", "before God our Lord"),
        ("וְאֵת אֲשֶׁר אֵינֶנּוּ פֹּה עִמָּנוּ הַיּוֹם", "ומע מן ליס הו חאצ'ר מענא אליום", "and with whoever is not present with us today"),
        (None, "אד' נקל אליה", "since it is being transmitted to him"),
    ],
    15: [
        ("כִּי-אַתֶּם יְדַעְתֶּם", "ואנתם עאלמין", "And you are well aware"),
        ("אֵת אֲשֶׁר-יָשַׁבְנוּ", "מא אקמנא", "of what we dwelt through"),
        ("בְּאֶרֶץ מִצְרָיִם", "פי בלד מצר", "in the land of Egypt"),
        ("וְאֵת אֲשֶׁר-עָבַרְנוּ", "ומא סרנא", "and how we journeyed"),
        ("בְּקֶרֶב הַגּוֹיִם", "פי מא בין אלאמם", "among the nations"),
        ("אֲשֶׁר עֲבַרְתֶּם", "אלד'ין גזתם בינהם", "through whom you passed"),
    ],
    16: [
        ("וַתִּרְאוּ", "וקד ראיתם", "and you have seen"),
        ("אֶת-שִׁקּוּצֵיהֶם", "ארגאסהם", "their abominations"),
        ("וְאֵת גִּלֻּלֵיהֶם", "וטואג'יתהם", "and their idols"),
        ("עֵץ וָאֶבֶן", "מן כ'שב וחגארה", "of wood and stone"),
        ("כֶּסֶף וְזָהָב", "ומן פצ'ה וד'הב", "of silver and gold"),
        ("אֲשֶׁר עִמָּהֶם", "אלד'י הי מעהם", "which are with them"),
    ],
    17: [
        ("פֶּן-יֵשׁ בָּכֶם", "כילא יוגד פיכם", "Lest there be found among you"),
        ("אִישׁ", "רגל", "a man"),
        ("אוֹ-אִשָּׁה", "או אמראה", "or a woman"),
        ("אוֹ מִשְׁפָּחָה", "או עשירה", "or a clan"),
        ("אוֹ-שֵׁבֶט", "או סבט", "or a tribe"),
        ("אֲשֶׁר לְבָבוֹ פֹנֶה הַיּוֹם", "מן קלבה מתולי אליום", "whose heart is turning away today"),
        ("מֵעִם יְהוָה אֱלֹהֵינוּ", "ען אללה רבנא", "from God our Lord"),
        ("לָלֶכֶת", "לימצ'י", "to go"),
        ("לַעֲבֹד", "ויעבד", "and worship"),
        ("אֶת-אֱלֹהֵי הַגּוֹיִם הָהֵם", "מעבודאת אולאיך אלאמם", "the objects of worship of those nations"),
        ("פֶּן-יֵשׁ בָּכֶם שֹׁרֶשׁ פֹּרֶה רֹאשׁ", "כילא יכון פיכם. אצל מת'מר סם", "lest there be among you a root bearing poisonous"),
        ("וְלַעֲנָה", "או עלקם", "or bitter fruit"),
    ],
    18: [
        ("וְהָיָה בְּשָׁמְעוֹ", "פאד'א סמע", "And if such a one hears"),
        ("אֶת-דִּבְרֵי הָאָלָה הַזֹּאת", "כלאם הד'א אלחרג", "the words of this obligation"),
        ("וְהִתְבָּרֵךְ בִּלְבָבוֹ", "קדר פי נפסה", "he reckons within himself"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("שָׁלוֹם יִהְיֶה-לִּי", "לא יכון לי אלא סלאם", "I shall have nothing but peace"),
        ("כִּי בִּשְׁרִרוּת לִבִּי אֵלֵךְ", "ואנמא אסיר פי הוא קלבי", "though he walks in the desire of his heart"),
        ("לְמַעַן סְפוֹת הָרָוָה אֶת-הַצְּמֵאָה", "לכי אמר באלרוא אלעטש", "so that he passes through in satiety while others thirst"),
    ],
    19: [
        ("לֹא-יֹאבֶה יְהוָה סְלֹחַ לוֹ", "פלא ישא אללה אן יצפח לה ד'אלך", "God will not will to pardon him for that"),
        (None, "בל", "rather"),
        (None, "חיניד'", "at that time"),
        ("כִּי אָז יֶעְשַׁן אַף-יְהוָה", "ישתד ג'צ'ב אללה", "God's anger"),
        ("וְקִנְאָתוֹ", "וחמייתה", "and His wrath shall intensify"),
        ("בָּאִישׁ הַהוּא", "עליה", "against him"),
        ("כָּל-הָאָלָה הַכְּתוּבָה בַּסֵּפֶר הַזֶּה", "גמיע אלחרג", "and all the obligation written in this book"),
        ("וְרָבְצָה בּוֹ", "אלמכתוב פי הד'א אלספר", "shall cling to him"),
        ("וּמָחָה יְהוָה אֶת-שְׁמוֹ", "חתי ימחי אללה אסמה", "until God blots out his name"),
        ("מִתַּחַת הַשָּׁמָיִם", "מן תחת אלסמא", "from beneath the sky"),
    ],
    20: [
        ("וְהִבְדִּילוֹ יְהוָה", "ויפרזה אללה", "And God shall set him apart"),
        ("לְרָעָה", "עלי' שר", "for evil"),
        ("מִכֹּל שִׁבְטֵי יִשְׂרָאֵל", "מן גמיע אסבאט אסראיל", "from among all the tribes of Israel"),
        ("כְּכֹל אָלוֹת הַבְּרִית", "כגמיע חרג אלעהד", "according to all the obligation of the covenant"),
        ("הַכְּתוּבָה בְּסֵפֶר הַתּוֹרָה הַזֶּה", "אלמכתוב פי ספר הד'ה אלתורייה", "written in the book of this Torah"),
    ],
    21: [
        ("וְאָמַר הַדּוֹר הָאַחֲרוֹן", "פיקול אלגיל אלאכ'ר", "And the later generation"),
        ("בְּנֵיכֶם", "מן בניכם", "from your children"),
        ("אֲשֶׁר יָקוּמוּ מֵאַחֲרֵיכֶם", "אלד'ין יקומון מן בעדכם", "who shall arise after you"),
        ("וְהַנָּכְרִי אֲשֶׁר יָבֹא מֵאֶרֶץ רְחוֹקָה", "ואלג'ריב אלד'י יאתי מן בלד בעיד", "and the stranger who comes from a distant land"),
        ("וְרָאוּ", "פינצ'רון", "when they look upon"),
        ("אֶת-מַכּוֹת הָאָרֶץ הַהִוא", "צ'רבאת תלך אלארץ'", "the plagues of that land"),
        ("וְאֶת-תַּחֲלֻאֶיהָ", "ואמראצ'הא", "and its diseases"),
        ("אֲשֶׁר-חִלָּה יְהוָה בָּהּ", "אלד'י אמרצ'הא אללה", "with which God afflicted it"),
    ],
    22: [
        (None, "חתי'", "all"),
        ("גָּפְרִית וָמֶלַח שְׂרֵפָה כָל-אַרְצָהּ", "כאן גמיע ארצ'הא מחרקה בנאר וכברית", "its soil being burned with fire and brimstone"),
        ("לֹא תִזָּרַע", "פהי לא תזרע", "so that it is not sown"),
        ("וְלֹא תַצְמִחַ", "ולא תנבת", "and does not grow"),
        ("וְלֹא-יַעֲלֶה בָהּ כָּל-עֵשֶׂב", "ולא יטלע פיהא שייא מן אלעשב", "and nothing of grass springs up from it"),
        ("כְּמַהְפֵּכַת סְדֹם", "כמקלב סדום", "like the overthrow of Sodom"),
        ("וַעֲמֹרָה", "ועמורה", "and Gomorrah"),
        ("אַדְמָה וּצְבֹיִים", "אדמה וצבוים", "Admah and Zeboiim"),
        ("אֲשֶׁר הָפַךְ יְהוָה", "אלד'י קלבהא אללה", "which God overturned"),
        ("בְּאַפּוֹ", "בג'צ'בה", "in His anger"),
        ("וּבַחֲמָתוֹ", "וחמייתה", "and His wrath"),
    ],
    23: [
        ("וְאָמְרוּ כָּל-הַגּוֹיִם", "פיקול גמיע אלאמם", "then all the nations shall say"),
        ("עַל-מֶה", "עלי' מא ד'א", "For what cause"),
        ("עָשָׂה יְהוָה כָּכָה", "צנע אללה כד'א", "did God do thus"),
        ("לָאָרֶץ הַזֹּאת", "בהד'ה אלארץ'", "to this land"),
        (None, "ומא סבב", "What is the reason for"),
        ("מֶה חֳרִי הָאַף הַגָּדוֹל הַזֶּה", "שדה' הד'א אלג'צ'ב אל עצ'ים", "the intensity of this great anger"),
    ],
    24: [
        (None, "פיגאבון", "And they shall answer"),
        (None, "באן ד'אלך", "It is because"),
        ("עַל אֲשֶׁר עָזְבוּ", "עלי' מא תרכו", "they forsook"),
        ("אֶת-בְּרִית יְהוָה", "עהד אללה", "the covenant of God"),
        ("אֱלֹהֵי אֲבֹתָם", "אלאה אבאיהם", "the God of their fathers"),
        ("אֲשֶׁר כָּרַת עִמָּם", "אלד'י עהדה מעהם", "which He made with them"),
        ("בְּהוֹצִיאוֹ אֹתָם מֵאֶרֶץ מִצְרָיִם", "באכ'ראגה להם מן בלד מצר", "when He brought them out of the land of Egypt"),
    ],
    25: [
        ("וַיֵּלְכוּ", "פמצ'ו", "and they went"),
        ("וַיַּעַבְדוּ אֱלֹהִים אֲחֵרִים", "ועבדו מעבודאת אכ'ר", "and worshipped other objects of worship"),
        ("וַיִּשְׁתַּחֲווּ לָהֶם", "וסגדו להא", "and bowed down to them"),
        ("אֱלֹהִים אֲשֶׁר לֹא-יְדָעוּם", "מעבודאת לם יערפוהא", "objects of worship that they did not know"),
        ("וְלֹא חָלַק לָהֶם", "ולם תנצבהם נציבא", "and that had not been appointed as a portion for them"),
    ],
    26: [
        ("וַיִּחַר-אַף יְהוָה", "פאשתד ג'צ'ב אללה", "And God's anger intensified"),
        ("בָּאָרֶץ הַהִוא", "עלי' תלך אלבלד", "against that land"),
        ("לְהָבִיא עָלֶיהָ", "פאחל בהא", "and He brought upon it"),
        ("אֶת-כָּל-הַקְּלָלָה הַכְּתוּבָה בַּסֵּפֶר הַזֶּה", "גמיע אללענה. אלמכתובה פי הד'א אלספר", "all the curse written in this book"),
    ],
    27: [
        ("וַיִּתְּשֵׁם יְהוָה", "פשד'ב אהלהא", "And He uprooted its inhabitants"),
        ("מֵעַל אַדְמָתָם", "ען בלדהם", "from their land"),
        ("בְּאַף", "בג'צ'ב", "with anger"),
        ("וּבְחֵמָה", "וחמייה", "and wrath"),
        ("וּבְקֶצֶף גָּדוֹל", "וסכ'ט עצ'ים", "and great indignation"),
        ("וַיַּשְׁלִכֵם", "וטרחהם", "and cast them"),
        ("אֶל-אֶרֶץ אַחֶרֶת", "אלי' בלד אכ'ר", "into another land"),
        ("כַּיּוֹם הַזֶּה", "כמי' תרונהם אליום", "as it is this day"),
    ],
    28: [
        (None, "פיעתברון", "And they shall take heed"),
        (None, "ויקולון כד'אך", "and say accordingly"),
        ("הַנִּסְתָּרֹת", "אלמסתוראת", "The hidden things"),
        ("לַיהוָה אֱלֹהֵינוּ", "ללה רבנא", "belong to God our Lord"),
        ("וְהַנִּגְלֹת", "ואלמכשופאת גמיעא", "but all the revealed things"),
        ("לָנוּ וּלְבָנֵינוּ", "אלתי הי לנא ולבנינא", "which belong to us and to our children"),
        ("עַד-עוֹלָם", "אלי' אלדהר", "forever"),
        ("לַעֲשׂוֹת", "פי אן נעמל", "are that we should do"),
        ("אֶת-כָּל-דִּבְרֵי הַתּוֹרָה הַזֹּאת", "גמיע כלאם הד'ה אלתורייה", "all the words of this Torah"),
    ],
}
