"""Hand-authored alignment triples for Shemot chapter 1.

Loaded by scripts/handalign_chapter.py. Each entry is a list of
(he|None, ja, en) tuples; `he` may be None where Saadia paraphrased
without a clean Hebrew anchor. Triples must be in left-to-right order
on every side (per-side cursor walk).
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    2: [
        ("רְאוּבֵן", "ראובן", "Reuben"),
        ("שִׁמְעוֹן", "שמעון", "Simeon"),
        ("לֵוִי", "לוי", "Levi"),
        ("וִיהוּדָה", "ויהודה", "Judah"),
    ],
    3: [
        ("יִשָּׂשכָר", "יששכר", "Issachar"),
        ("זְבוּלֻן", "זבולון", "Zebulun"),
        ("וּבִנְיָמִן", "ובנימין", "Benjamin"),
    ],
    4: [
        ("דָּן", "דן", "Dan"),
        ("וְנַפְתָּלִי", "ונפתלי", "Naphtali"),
        ("גָּד", "גד", "Gad"),
        ("וְאָשֵׁר", "ואשר", "Asher"),
    ],
    5: [
        ("וַיְהִי כָּל-נֶפֶשׁ", "פכאן גמלה' אלנפוס", "And the sum of the souls"),
        ("יֹצְאֵי יֶרֶךְ-יַעֲקֹב", "אלכ'ארגה מן צלב יעקוב",
         "those issuing from the loins of Jacob"),
        ("שִׁבְעִים נָפֶשׁ", "סבעין נפסא", "was seventy souls"),
        ("וְיוֹסֵף", "מע יוסף", "together with Joseph"),
        ("הָיָה בְמִצְרָיִם", "אלד'י כאן במצר", "who was in Egypt"),
    ],
    6: [
        ("וַיָּמָת יוֹסֵף", "פמאת יוסף", "And Joseph died"),
        ("וְכָל-אֶחָיו", "וגמיע אכ'ותה", "and all his brothers"),
        ("וְכֹל הַדּוֹר הַהוּא", "וסאיר אהל ד'אלך אלגיל",
         "and the rest of the people of that generation"),
    ],
    7: [
        ("וּבְנֵי יִשְׂרָאֵל", "ובני אסראיל", "And the sons of Israel"),
        ("פָּרוּ", "את'מרו", "bore fruit"),
        ("וַיִּשְׁרְצוּ", "וסעו", "and spread out"),
        ("וַיִּרְבּוּ", "וכת'רו", "and multiplied"),
        ("וַיַּעַצְמוּ", "ועצ'מו", "and grew strong"),
        ("בִּמְאֹד מְאֹד", "גדא גדא", "very, very"),
        ("וַתִּמָּלֵא הָאָרֶץ אֹתָם", "חתי' אמתלא ד'אלך אלבלד מנהם",
         "until that land was filled with them"),
    ],
    8: [
        ("וַיָּקָם מֶלֶךְ-חָדָשׁ", "וקאם מלך גדיד", "And a new king arose"),
        ("עַל-מִצְרָיִם", "עלי' מצר", "over Egypt"),
        ("אֲשֶׁר לֹא-יָדַע", "מא לם ישאהד", "who had not seen"),
        ("אֶת-יוֹסֵף", "יוסף", "Joseph"),
    ],
    9: [
        ("וַיֹּאמֶר אֶל-עַמּוֹ", "פקאל לקומה", "And he said to his people"),
        ("הִנֵּה", "הודא", "Behold"),
        ("עַם בְּנֵי יִשְׂרָאֵל", "קום בני אסראיל",
         "the people of the sons of Israel"),
        ("רַב", "אכת'ר", "more numerous"),
        ("וְעָצוּם", "וא עצ'ם", "and stronger"),
        ("מִמֶּנּוּ", "מנא", "than us"),
    ],
    10: [
        ("הָבָה", "תעאלו", "Come"),
        ("נִתְחַכְּמָה לוֹ", "נחתאל להם", "let us scheme against them"),
        ("פֶּן-יִרְבֶּה", "פלא יכת'רון", "so that they shall not multiply"),
        ("וְהָיָה", "ויכון", "and it shall be"),
        ("כִּי-תִקְרֶאנָה מִלְחָמָה", "אדא ואפאנא אלחרב",
         "when war comes upon us"),
        ("וְנוֹסַף גַּם-הוּא", "אנצ'אפו הם איצ'א",
         "that they too will join"),
        ("עַל-שֹׂנְאֵינוּ", "עלי . אעדאינא", "with our enemies"),
        ("וְנִלְחַם-בָּנוּ", "פיחארבונא", "and they shall war against us"),
        ("וְעָלָה מִן-הָאָרֶץ", "ויהרבונא מן אלבלד",
         "and shall drive us out from the land"),
    ],
    11: [
        ("וַיָּשִׂימוּ עָלָיו", "פציירו עליהם",
         "And they appointed over them"),
        ("שָׂרֵי מִסִּים", "ולאה' ד'מה", "guards of tribute"),
        ("לְמַעַן עַנֹּתוֹ", "לקבל אן יעד'בונהם", "so as to torment them"),
        ("בְּסִבְלֹתָם", "בנקלהם", "with their burdens"),
        ("וַיִּבֶן עָרֵי מִסְכְּנוֹת", "פבנו קרא מכ'אזין",
         "and they built fortified storehouse-towns"),
        ("לְפַרְעֹה", "לפרעון", "for Pharaoh"),
        ("אֶת-פִּתֹם", "פי אלפיום", "in al-Faiyum (Pithom)"),
        ("וְאֶת-רַעַמְסֵס", "ופי עין שמס", "and in Ein Shams (Raamses)"),
    ],
    12: [
        ("וְכַאֲשֶׁר יְעַנּוּ אֹתוֹ", "וכאן כל מא עד'בוהם",
         "And as much as they tormented them"),
        ("כֵּן יִרְבֶּה", "כדאך יכת'רון", "so they multiplied"),
        ("וְכֵן יִפְרֹץ", "וייסרון", "and prospered"),
        ("וַיָּקֻצוּ", "חתא צ'גרו",
         "until [the Egyptians] were filled with dread"),
        ("מִפְּנֵי בְּנֵי יִשְׂרָאֵל", "מן קבל בני אסראיל",
         "before the sons of Israel"),
    ],
    13: [
        ("וַיַּעֲבִדוּ מִצְרַיִם", "ואסתכ'דם אלמצריון",
         "And the Egyptians pressed"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("בְּפָרֶךְ", "באקמא", "into service with cruelty"),
    ],
    14: [
        ("וַיְמָרְרוּ אֶת-חַיֵּיהֶם", "פאמרו חיותהם",
         "And they made their lives bitter"),
        ("בַּעֲבֹדָה קָשָׁה", "בכ'דמה צעבה", "with hard labor"),
        ("בְּחֹמֶר וּבִלְבֵנִים", "באלטין ואללבן", "with mortar and brick"),
        ("וּבְכָל-עֲבֹדָה בַּשָּׂדֶה", "וסאיר אעמאל אלצחרא",
         "and with all the labors of the open country"),
        ("אֵת כָּל-עֲבֹדָתָם", "גמיע כ'דמתהם", "all their service"),
        ("אֲשֶׁר-עָבְדוּ בָהֶם", "אלד'י אסתכ'דמונהם",
         "which they pressed them into"),
        ("בְּפָרֶךְ", "באקמא", "with cruelty"),
    ],
    15: [
        ("וַיֹּאמֶר מֶלֶךְ מִצְרַיִם", "פקאל מלך מצר",
         "And the king of Egypt said"),
        ("לַמְיַלְּדֹת הָעִבְרִיֹּת", "לאלקואבל אלעבראנייאת",
         "to the Hebrew midwives"),
        ("אֲשֶׁר שֵׁם הָאַחַת", "אלד'י אסם אחדהמא",
         "the name of one of whom was"),
        ("שִׁפְרָה", "שפרה", "Shiphrah"),
        ("וְשֵׁם הַשֵּׁנִית", "ואלאכ'רי'", "and the other"),
        ("פּוּעָה", "פועה", "Puah"),
    ],
    16: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("בְּיַלֶּדְכֶן אֶת-הָעִבְרִיּוֹת", "אד'א קבלתן אלעבראנייאת",
         "When you deliver the Hebrew women"),
        ("וּרְאִיתֶן עַל-הָאָבְנָיִם", "פאנצ'רן ענד אלמת'בר",
         "look upon the birth-stool"),
        ("אִם-בֵּן הוּא", "אן כאן אבנא", "if it be a son"),
        ("וַהֲמִתֶּן אֹתוֹ", "פאקתלוה", "then kill him"),
        ("וְאִם-בַּת הִוא", "ואן כאנת אבנה", "and if it be a daughter"),
        ("וָחָיָה", "פאסתבקוהא", "then let her live"),
    ],
    17: [
        ("וַתִּירֶאןָ הַמְיַלְּדֹת", "פכ'אפת אלקואבל",
         "But the midwives feared"),
        ("אֶת-הָאֱלֹהִים", "אללה", "God"),
        ("וְלֹא עָשׂוּ", "ולם יצנען", "and did not do"),
        ("כַּאֲשֶׁר דִּבֶּר אֲלֵיהֶן מֶלֶךְ מִצְרָיִם",
         "כמא קאל להן מלך מצר", "as the king of Egypt had told them"),
        ("וַתְּחַיֶּיןָ אֶת-הַיְלָדִים", "ואסתבקין אלבנין",
         "and they let the boys live"),
    ],
    18: [
        ("וַיִּקְרָא מֶלֶךְ-מִצְרַיִם לַמְיַלְּדֹת",
         "פדעא בהן מלך מצר", "And the king of Egypt called for them"),
        ("וַיֹּאמֶר לָהֶן", "וקאל להן", "and said to them"),
        ("מַדּוּעַ", "מא באלכן", "What is your concern"),
        ("עֲשִׂיתֶן", "צנעתן", "that you have done"),
        ("הַדָּבָר הַזֶּה", "הד'א אלאמר", "this thing"),
        ("וַתְּחַיֶּיןָ אֶת-הַיְלָדִים", "ואסתבקיתן אלבנין",
         "and have let the boys live"),
    ],
    19: [
        ("וַתֹּאמַרְןָ הַמְיַלְּדֹת אֶל-פַּרְעֹה", "קאלתא לה",
         "They said to him"),
        ("כִּי לֹא כַנָּשִׁים הַמִּצְרִיֹּת", "אן ליס כאלנסא. אלמצריאת",
         "It is because — unlike the Egyptian women"),
        ("הָעִבְרִיֹּת", "אלעבראנייאת", "the Hebrew women"),
        ("כִּי-חָיוֹת הֵנָּה", "בל הן בציראת", "are skilled"),
        ("בְּטֶרֶם תָּבוֹא אֲלֵהֶן הַמְיַלֶּדֶת",
         "קבל אן תדכ'ל אליהן. אלקאבלה",
         "before the midwife comes in to them"),
        ("וְיָלָדוּ", "ילדן", "they have given birth"),
    ],
    20: [
        ("וַיֵּיטֶב אֱלֹהִים", "פאחסן אללה", "And God dealt well"),
        ("לַמְיַלְּדֹת", "אלי' אלקואבל", "with the midwives"),
        ("וַיִּרֶב הָעָם", "פכת'ר אלקום", "and the people multiplied"),
        ("וַיַּעַצְמוּ מְאֹד", "ועצמו גדא", "and grew very strong"),
    ],
    21: [
        ("וַיְהִי כִּי-יָרְאוּ הַמְיַלְּדֹת", "ולמא כ'אפת אלקואבל",
         "And when the midwives feared"),
        ("אֶת-הָאֱלֹהִים", "אללה", "God"),
        ("וַיַּעַשׂ לָהֶם", "צנע להן", "He made for them"),
        ("בָּתִּים", "ביותא חגבהן", "houses where they would be sheltered"),
    ],
    22: [
        ("וַיְצַו פַּרְעֹה", "פאמר פרעון", "And Pharaoh commanded"),
        ("לְכָל-עַמּוֹ", "גמיע קואדה", "all his officers"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("כָּל-הַבֵּן הַיִּלּוֹד", "כל אבן יולד להם",
         "Every son that is born to them"),
        ("הַיְאֹרָה תַּשְׁלִיכֻהוּ", "אטרחוה באלניל",
         "throw him into the Nile"),
        ("וְכָל-הַבַּת", "וכל אבנה", "and every daughter"),
        ("תְּחַיּוּן", "אסתבקוהא", "let her live"),
    ],
}
