"""Hand-authored alignment triples for Shemot chapter 23."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא תִשָּׂא שֵׁמַע שָׁוְא", "ולא תקבל כ'ברא זורא",
         "And do not accept a false report"),
        ("אַל-תָּשֶׁת יָדְךָ עִם-רָשָׁע", "ולא תכ'אלטן צ'אלמא",
         "and do not associate with a wrongdoer"),
        ("לִהְיֹת עֵד חָמָס", "לתכון לה שאהד צ'לם",
         "to be for him a witness of injustice"),
    ],
    2: [
        ("לֹא-תִהְיֶה אַחֲרֵי-רַבִּים לְרָעֹת", "לא תכון תבע אלכ'תיר לאלשר",
         "Do not be a follower of the many toward evil"),
        ("וְלֹא-תַעֲנֶה עַל-רִב לִנְטֹת", "ולא תגיב פי כ'צומה לתמיילהא",
         "and do not respond in a dispute so as to tilt it"),
        ("אַחֲרֵי רַבִּים--לְהַטֹּת", "בל ורא אלאכתר פמל",
         "rather, behind the majority, then incline"),
    ],
    3: [
        ("וְדָל לֹא תֶהְדַּר בְּרִיבוֹ", "ולא תחאבי אלפקיר פי כ'צומתה",
         "And do not show favor to the poor in his dispute."),
    ],
    4: [
        ("כִּי תִפְגַּע שׁוֹר אֹיִבְךָ אוֹ חֲמֹרוֹ--תֹּעֶה",
         "ואד'א פאגית ת'ור עדווך. או חמארה צ'לא",
         "And if you come upon the ox of your enemy, or his donkey, going astray"),
        ("הָשֵׁב תְּשִׁיבֶנּוּ לוֹ", "פרדה עליה רדא",
         "return it to him, a returning."),
    ],
    5: [
        ("כִּי-תִרְאֶה חֲמוֹר שֹׂנַאֲךָ רֹבֵץ תַּחַת מַשָּׂאוֹ",
         "ואד'א ראית חמאר שאניך. ראבצא תחת חמלה",
         "And if you see the donkey of one who hates you crouching under its load"),
        ("וְחָדַלְתָּ מֵעֲזֹב לוֹ", "פאנתה ען תרכה כד'אך",
         "then refrain from leaving it thus"),
        ("עָזֹב תַּעֲזֹב עִמּוֹ", "בל חטא תחט מעה",
         "rather, unload it, unload it along with him."),
    ],
    6: [
        ("לֹא תַטֶּה מִשְׁפַּט אֶבְיֹנְךָ בְּרִיבוֹ", "לא תמייל חכם מסכינך פי כ'צומתה",
         "Do not tilt the judgment of your poor in his dispute."),
    ],
    7: [
        ("מִדְּבַר-שֶׁקֶר תִּרְחָק", "מן כלאם אלבאטל פאבעד",
         "From false speech, keep far."),
        ("וְנָקִי וְצַדִּיק אַל-תַּהֲרֹג", "ואלברי ואלזכי לא תקתלהמא",
         "And the righteous and the innocent — do not kill them"),
        ("כִּי לֹא-אַצְדִּיק רָשָׁע", "פאני לא אזכי צ'אלמא",
         "for I will not acquit a wrongdoer."),
    ],
    8: [
        ("וְשֹׁחַד לֹא תִקָּח", "ולא תאכד' אלרשא", "And do not take a bribe"),
        ("כִּי הַשֹּׁחַד יְעַוֵּר פִּקְחִים", "פאן אלרשא יעמי עיון אלבצרא ען אלחק",
         "for a bribe blinds the eyes of those who see away from the truth"),
        ("וִיסַלֵּף דִּבְרֵי צַדִּיקִים", "ויזייף אלאקואל אלעאדלה",
         "and falsifies words that are just."),
    ],
    9: [
        ("וְגֵר לֹא תִלְחָץ", "ולא תצ'גט ג'ריבא", "And do not oppress a stranger"),
        ("וְאַתֶּם יְדַעְתֶּם אֶת-נֶפֶשׁ הַגֵּר", "פאנתם תערפון נפס אלג'ריב",
         "for you know the soul of the stranger"),
        ("כִּי-גֵרִים הֱיִיתֶם בְּאֶרֶץ מִצְרָיִם", "וטאל מא כנתם ג'רבא פי בלד מצר",
         "seeing how long you were strangers in the land of Egypt."),
    ],
    10: [
        ("וְשֵׁשׁ שָׁנִים תִּזְרַע אֶת-אַרְצֶךָ", "סת סנין תזרע ארצך",
         "Six years you shall sow your land"),
        ("וְאָסַפְתָּ אֶת-תְּבוּאָתָהּ", "ותגמע ג'לתהא", "and gather its produce."),
    ],
    11: [
        ("וְהַשְּׁבִיעִת תִּשְׁמְטֶנָּה וּנְטַשְׁתָּהּ", "ואסאבעה תסייבהא ולא תד'רהא",
         "But in the seventh you shall leave it and not scatter seed in it"),
        ("וְאָכְלוּ אֶבְיֹנֵי עַמֶּךָ", "ויאכל מנהא מסאכין קומך",
         "and the poor of your people shall eat from it"),
        ("וְיִתְרָם תֹּאכַל חַיַּת הַשָּׂדֶה", "ופאצ'להם יאכלה חיואן אלצחרי'",
         "and what remains of it the wild creatures of the desert shall eat"),
        ("כֵּן-תַּעֲשֶׂה לְכַרְמְךָ לְזֵיתֶךָ", "כד' תצנע לכרמך ולזיאתינך",
         "So shall you do with your vineyard and your olive grove."),
    ],
    12: [
        ("שֵׁשֶׁת יָמִים תַּעֲשֶׂה מַעֲשֶׂיךָ", "סת איאם תצנע צנאיע",
         "Six days you shall perform your labors"),
        ("וּבַיּוֹם הַשְּׁבִיעִי תִּשְׁבֹּת", "ואליום אלסאבע תסבת",
         "and on the seventh day you shall keep the Sabbath"),
        ("לְמַעַן יָנוּחַ שׁוֹרְךָ וַחֲמֹרֶךָ", "לכי יסתריח ת'ורך וחמארך",
         "that your ox and your donkey may rest"),
        ("וְיִנָּפֵשׁ בֶּן-אֲמָתְךָ וְהַגֵּר", "ויקר אבן אמתך ואלג'ריב מעך",
         "and the son of your maidservant and the stranger with you may find ease."),
    ],
    13: [
        ("וּבְכֹל אֲשֶׁר-אָמַרְתִּי אֲלֵיכֶם תִּשָּׁמֵרוּ", "וגמיע מא קלת לכם אחפצו",
         "And all that I have told you, keep"),
        ("וְשֵׁם אֱלֹהִים אֲחֵרִים לֹא תַזְכִּירוּ", "ואסם מעבודאת אכ'ר לא תד'כרון",
         "and the name of other objects of worship do not mention"),
        ("לֹא יִשָּׁמַע עַל-פִּיךָ", "ולא יסמע מן פאך",
         "and let it not be heard from your mouth."),
    ],
    14: [
        ("שָׁלֹשׁ רְגָלִים תָּחֹג לִי בַּשָּׁנָה", "ת'לאת' מראר. ת'חג לי באלסנה",
         "Three times you shall make pilgrimage to Me in the year."),
    ],
    15: [
        ("אֶת-חַג הַמַּצּוֹת תִּשְׁמֹר", "וחג אלפטיר אחפצ'ה",
         "And the festival of unleavened bread — keep it"),
        ("שִׁבְעַת יָמִים תֹּאכַל מַצּוֹת כַּאֲשֶׁר צִוִּיתִךָ",
         "סבעה' איאם תאכל פטירא כמא אמרתך",
         "seven days you shall eat unleavened bread as I commanded you"),
        ("לְמוֹעֵד חֹדֶשׁ הָאָבִיב", "פי וקת שהר אלפריך'",
         "at the time of the month of the roasting of the barley"),
        ("כִּי-בוֹ יָצָאתָ מִמִּצְרָיִם", "לאנך פיה כ'רגת מן מצר",
         "for in it you went out from Egypt"),
        ("וְלֹא-יֵרָאוּ פָנַי רֵיקָם", "ולא תחצ'רו בין ידיי פארג'א",
         "And do not appear before Me empty-handed."),
    ],
    16: [
        ("וְחַג הַקָּצִיר בִּכּוּרֵי מַעֲשֶׂיךָ אֲשֶׁר תִּזְרַע בַּשָּׂדֶה",
         "וחג אלחצאד בכור עמלך. אלד'י תזרעה פי אלצחרי'",
         "And the festival of the harvest, of the firstfruits of your labor which you sow in the open country"),
        ("וְחַג הָאָסִף בְּצֵאת הַשָּׁנָה", "וחג אלגמע ענד כ'רוג אלסנה",
         "and the festival of the ingathering, at the going out of the year"),
        ("בְּאָסְפְּךָ אֶת-מַעֲשֶׂיךָ מִן-הַשָּׂדֶה", "וגמעך אעמאלך מן אלצחרי'",
         "when you gather in your labors from the open country."),
    ],
    17: [
        ("שָׁלֹשׁ פְּעָמִים בַּשָּׁנָה", "ת'לאת' מראר פי אלסנה",
         "Three times in the year"),
        ("יֵרָאֶה כָּל-זְכוּרְךָ", "יחצ'ר גמיע רגאלך",
         "shall all your men appear"),
        ("אֶל-פְּנֵי הָאָדֹן יְהוָה", "בין ידי אלסייד אללה",
         "before the Lord God."),
    ],
    18: [
        ("לֹא-תִזְבַּח עַל-חָמֵץ דַּם-זִבְחִי", "ולא תד'בח פסחי עלי' כ'מיר",
         "And do not slaughter My Passover offering upon leavened bread"),
        ("וְלֹא-יָלִין חֵלֶב-חַגִּי עַד-בֹּקֶר", "ולא תביית שחום חגי אלי' אלג'דאה",
         "and do not let the fat of My festival offering remain until morning."),
    ],
    19: [
        ("רֵאשִׁית בִּכּוּרֵי אַדְמָתְךָ", "ואואיל בכור ארצ'ך",
         "And the first of the firstfruits of your land"),
        ("תָּבִיא בֵּית יְהוָה אֱלֹהֶיךָ", "תאתי בהא אלי' בית אללה רבך",
         "bring them to the house of God your Lord"),
        ("לֹא-תְבַשֵּׁל גְּדִי בַּחֲלֵב אִמּוֹ", "ולא תטבך' לחמא בלבן",
         "And do not cook meat with milk."),
    ],
    20: [
        ("הִנֵּה אָנֹכִי שֹׁלֵחַ מַלְאָךְ לְפָנֶיךָ", "האנא באעת' במלך בין ידיך",
         "Behold, I am sending an angel before you"),
        ("לִשְׁמָרְךָ בַּדָּרֶךְ", "יחפצך פי אלטריק", "to guard you on the way"),
        ("וְלַהֲבִיאֲךָ אֶל-הַמָּקוֹם אֲשֶׁר הֲכִנֹתִי",
         "ויאתי בך. אלי' אלמוצ'ע אלד'י אצלחתה לך",
         "and to bring you to the place which I have prepared for you."),
    ],
    21: [
        ("הִשָּׁמֶר מִפָּנָיו", "פאחד'רה", "Be wary of him"),
        ("וּשְׁמַע בְּקֹלוֹ אַל-תַּמֵּר בּוֹ", "ואקבל אמרה ולא תכאלפה",
         "and accept his command and do not oppose him"),
        ("כִּי לֹא יִשָּׂא לְפִשְׁעֲכֶם", "פאנה לא יצפח גרמכם",
         "for he will not pardon your transgression"),
        ("כִּי שְׁמִי בְּקִרְבּוֹ", "ועלי' אן אסמי מעה", "for My name is with him."),
    ],
    22: [
        ("כִּי אִם-שָׁמוֹעַ תִּשְׁמַע בְּקֹלוֹ", "פאנך אן קבלת אמרה",
         "For if you accept his command"),
        ("וְעָשִׂיתָ כֹּל אֲשֶׁר אֲדַבֵּר", "וצנעת גמיע מא אקולה",
         "and do all that I say"),
        ("וְאָיַבְתִּי אֶת-אֹיְבֶיךָ", "עאדית מעאדייך",
         "I will be an enemy to those who are enemies to you"),
        ("וְצַרְתִּי אֶת-צֹרְרֶיךָ", "וצ'אררת מצ'ארריך",
         "and I will harm those who harm you."),
    ],
    23: [
        ("כִּי-יֵלֵךְ מַלְאָכִי לְפָנֶיךָ", "ואד'א סאר מלכי בין ידיך",
         "And when My angel goes before you"),
        ("וֶהֱבִיאֲךָ אֶל-הָאֱמֹרִי וְהַחִתִּי וְהַפְּרִזִּי וְהַכְּנַעֲנִי",
         "ואדכ'לך. אלי' אלאמוריין ואלחתיין. ואלפרזיין ואלכנעאניין",
         "and brings you in to the Amorites and the Hittites and the Perizzites and the Canaanites"),
        ("הַחִוִּי וְהַיְבוּסִי", "אלחויין ואליבוסיין", "the Hivites and the Jebusites"),
        ("וְהִכְחַדְתִּיו", "ואגחדתהם", "and I annihilate them"),
    ],
    24: [
        ("לֹא-תִשְׁתַּחֲוֶה לֵאלֹהֵיהֶם וְלֹא תָעָבְדֵם",
         "לא תסגד למעבודאתהם ולא תעבדהא",
         "do not bow down to their objects of worship and do not serve them"),
        ("וְלֹא תַעֲשֶׂה כְּמַעֲשֵׂיהֶם", "ולא תעמל כאעמאלהם",
         "and do not act as their deeds"),
        ("כִּי הָרֵס תְּהָרְסֵם", "בל הדמהא הדמא",
         "rather, demolish them with a demolishing"),
        ("וְשַׁבֵּר תְּשַׁבֵּר מַצֵּבֹתֵיהֶם", "וכסר מד'אבחהם תכסירא",
         "and break their altars with a breaking."),
    ],
    25: [
        ("וַעֲבַדְתֶּם אֵת יְהוָה אֱלֹהֵיכֶם", "ואעבדו אללה רבכם",
         "And serve God your Lord"),
        ("וּבֵרַךְ אֶת-לַחְמְךָ וְאֶת-מֵימֶיךָ", "ויבארך פי טעאמך ושראבך",
         "and He will bless your food and your drink"),
        ("וַהֲסִרֹתִי מַחֲלָה מִקִּרְבֶּךָ", "ויזיל אלאמראץ' ענך",
         "and will remove diseases from you."),
    ],
    26: [
        ("לֹא תִהְיֶה מְשַׁכֵּלָה וַעֲקָרָה בְּאַרְצֶךָ", "לא תכון מת'כל ועאקר פי בלדך",
         "There shall be none who loses young and none barren in your land"),
        ("אֶת-מִסְפַּר יָמֶיךָ אֲמַלֵּא", "ואחצא איאמך אכמלהא",
         "and the count of your days — I will complete them."),
    ],
    27: [
        ("אֶת-אֵימָתִי אֲשַׁלַּח לְפָנֶיךָ", "ואבעת' בהיבתי בין ידיך",
         "And I will send My dread before you"),
        ("וְהַמֹּתִי אֶת-כָּל-הָעָם אֲשֶׁר תָּבֹא בָּהֶם",
         "ואהים גמיע אלקום. אלד'ין תציר אליהם",
         "and I will throw into confusion all the people unto whom you come"),
        ("וְנָתַתִּי אֶת-כָּל-אֹיְבֶיךָ אֵלֶיךָ עֹרֶף",
         "ואגעל אעדאך. בין ידיך מדברין",
         "and I will make your enemies turn their backs before you."),
    ],
    28: [
        ("וְשָׁלַחְתִּי אֶת-הַצִּרְעָה לְפָנֶיךָ", "ואבעת' באלעאהה בין ידיך",
         "And I will send the plague before you"),
        ("וְגֵרְשָׁה אֶת-הַחִוִּי אֶת-הַכְּנַעֲנִי וְאֶת-הַחִתִּי--מִלְּפָנֶיךָ",
         "פתטרד אלחויין ואלכנעאניין. ואלחתיין מן בין ידיך",
         "and it shall drive out the Hivites and the Canaanites and the Hittites from before you."),
    ],
    29: [
        ("לֹא אֲגָרְשֶׁנּוּ מִפָּנֶיךָ בְּשָׁנָה אֶחָת",
         "לא אטרדהם מן בין ידיך פי סנה ואחדה",
         "I will not drive them out from before you in a single year"),
        ("פֶּן-תִּהְיֶה הָאָרֶץ שְׁמָמָה", "כלא יציר אלבלד וחשא",
         "lest the land become desolate"),
        ("וְרַבָּה עָלֶיךָ חַיַּת הַשָּׂדֶה", "ויכת'ר עליך חיואן אלצחרא",
         "and the wild creatures of the desert multiply against you."),
    ],
    30: [
        ("מְעַט מְעַט אֲגָרְשֶׁנּוּ מִפָּנֶיךָ", "לכן קלילא קלילא. אטרדהם מן בין ידיך",
         "But little by little I will drive them out from before you"),
        ("עַד אֲשֶׁר תִּפְרֶה", "אלי' אן תנמו", "until you grow"),
        ("וְנָחַלְתָּ אֶת-הָאָרֶץ", "ותחוז אלבלד", "and take possession of the land."),
    ],
    31: [
        ("וְשַׁתִּי אֶת-גְּבֻלְךָ מִיַּם-סוּף וְעַד-יָם פְּלִשְׁתִּים",
         "ואגעל תכ'מך. מן בחר אלקלזם אלי' בחר פלסטין",
         "And I will set your border from the Sea of Qulzum (Red Sea) to the Sea of Philistia"),
        ("וּמִמִּדְבָּר עַד-הַנָּהָר", "ומן אלבר אלי' אלפראת",
         "and from the wilderness to the Euphrates"),
        ("כִּי אֶתֵּן בְּיֶדְכֶם אֵת יֹשְׁבֵי הָאָרֶץ",
         "באן אסלם פי אידיכם סכאן אלבלד",
         "for I will deliver into your hands the inhabitants of the land"),
        ("וְגֵרַשְׁתָּמוֹ מִפָּנֶיךָ", "ותטרדהם מן בין ידיך",
         "and you shall drive them out from before you."),
    ],
    32: [
        ("לֹא-תִכְרֹת לָהֶם וְלֵאלֹהֵיהֶם בְּרִית",
         "לא תעהד מעהם. ומע מעבודאתהם עהדא",
         "Do not make a covenant with them, nor with their objects of worship, a covenant."),
    ],
    33: [
        ("לֹא יֵשְׁבוּ בְּאַרְצְךָ", "ולא יקימון פי בלדך",
         "And they shall not dwell in your land"),
        ("פֶּן-יַחֲטִיאוּ אֹתְךָ לִי", "ללא יכ'טונך לי",
         "lest they lead you astray from Me"),
        ("כִּי תַעֲבֹד אֶת-אֱלֹהֵיהֶם", "באן תעבד מעבודאתהם",
         "by your serving their objects of worship"),
        ("כִּי-יִהְיֶה לְךָ לְמוֹקֵשׁ", "פיכונו לך והקא",
         "for they would be to you a noose."),
    ],
}
