"""Hand-authored alignment triples for Shemot chapter 9."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי", "Then God said to Moses"),
        ("בֹּא אֶל-פַּרְעֹה", "אדכ'ל אלי' פרעון", "Go in to Pharaoh"),
        ("וְדִבַּרְתָּ אֵלָיו כֹּה-אָמַר יְהוָה אֱלֹהֵי הָעִבְרִים",
         "וקל לה. כד'א קאל אללה אלאה אלעבראניין",
         "and say to him: Thus says God, the God of the Hebrews"),
        ("שַׁלַּח אֶת-עַמִּי וְיַעַבְדֻנִי", "אטלק קומי יעבדוני",
         "release my people that they may serve me"),
    ],
    2: [
        ("כִּי אִם-מָאֵן אַתָּה לְשַׁלֵּחַ", "פאנך אן אבית אן תטלקהום",
         "For if you refuse to release them"),
        ("וְעוֹדְךָ מַחֲזִיק בָּם", "ועאדך מתמסך בהם",
         "and you persist in holding them"),
    ],
    3: [
        ("הִנֵּה יַד-יְהוָה הוֹיָה בְּמִקְנְךָ אֲשֶׁר בַּשָּׂדֶה",
         "פאן אפה' אללה כאינה. פי מואשיך אלתי פי אלצחרא",
         "then a plague of God shall come upon your livestock which are in the open country"),
        ("בַּסּוּסִים בַּחֲמֹרִים בַּגְּמַלִּים", "פי אלכ'יל ואלחמיר ואלגמאל",
         "upon the horses and the donkeys and the camels"),
        ("בַּבָּקָר וּבַצֹּאן--דֶּבֶר כָּבֵד מְאֹד", "ואלבקר ואלג'נם ובא עצ'ים גדא",
         "and the cattle and the flock — a very great pestilence"),
    ],
    4: [
        ("וְהִפְלָה יְהוָה--בֵּין מִקְנֵה יִשְׂרָאֵל וּבֵין מִקְנֵה מִצְרָיִם",
         "ויביין אללה. בין מואשי בני אסראיל. ובין מואשי אלמצריון",
         "And God shall distinguish between the livestock of the sons of Israel and the livestock of the Egyptians"),
        ("וְלֹא יָמוּת מִכָּל-לִבְנֵי יִשְׂרָאֵל דָּבָר",
         "ולא ימות. מן גמיע מא הו לבני אסראיל שייא",
         "and not a single thing of all that belongs to the sons of Israel shall die"),
    ],
    5: [
        ("וַיָּשֶׂם יְהוָה מוֹעֵד לֵאמֹר", "וצייר אללה וקתא קאילא",
         "And God appointed a time, saying"),
        ("מָחָר יַעֲשֶׂה יְהוָה הַדָּבָר הַזֶּה--בָּאָרֶץ",
         "ג'דא יצנע אללה. הד'א אלאמר פי אלבלד",
         "Tomorrow God shall do this thing in the land"),
    ],
    6: [
        ("וַיַּעַשׂ יְהוָה אֶת-הַדָּבָר הַזֶּה מִמָּחֳרָת",
         "פצנע אללה הד'א אלאמר מן ג'ד",
         "And God did this thing on the morrow"),
        ("וַיָּמָת כֹּל מִקְנֵה מִצְרָיִם", "ומאת גמיע מואשי אלמצריון",
         "and all the livestock of the Egyptians died"),
        ("וּמִמִּקְנֵה בְנֵי-יִשְׂרָאֵל לֹא-מֵת אֶחָד",
         "ומן מואשי בני אסראיל לם ימות ואחד",
         "and of the livestock of the sons of Israel not one died"),
    ],
    7: [
        ("וַיִּשְׁלַח פַּרְעֹה", "פבעת' פרעון. פנצ'ר", "And Pharaoh sent and looked"),
        ("וְהִנֵּה לֹא-מֵת מִמִּקְנֵה יִשְׂרָאֵל עַד-אֶחָד",
         "פאד'י לם ימות מן מואשי בני אסראיל ואחד",
         "and behold, not one of the livestock of the sons of Israel had died"),
        ("וַיִּכְבַּד לֵב פַּרְעֹה", "פת'קל קלבה", "And his heart was hardened"),
        ("וְלֹא שִׁלַּח אֶת-הָעָם", "ולם יטלק אלקום", "and he did not release the people"),
    ],
    8: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן",
         "פקאל אללה למוסי' והרון",
         "And God said to Moses and Aaron"),
        ("קְחוּ לָכֶם מְלֹא חָפְנֵיכֶם פִּיחַ כִּבְשָׁן",
         "כ'ד'ו לכם מל חפניכמא. מן פיח אלאתון",
         "Take for yourselves your double-handful of soot from the furnace"),
        ("וּזְרָקוֹ מֹשֶׁה הַשָּׁמַיְמָה לְעֵינֵי פַרְעֹה",
         "ויהוי בה מוסי'. פי אלהוי' בחצ'רה' פרעון",
         "and Moses shall scatter it into the air in the presence of Pharaoh"),
    ],
    9: [
        ("וְהָיָה לְאָבָק עַל כָּל-אֶרֶץ מִצְרָיִם",
         "ויציר ג'בארא. פי גמיע בלד מצר",
         "and it shall become dust over all the land of Egypt"),
        ("וְהָיָה עַל-הָאָדָם וְעַל-הַבְּהֵמָה", "ויכון פי אלנאס ואלבהאים",
         "and it shall be upon the people and upon the beasts"),
        ("לִשְׁחִין פֹּרֵחַ אֲבַעְבֻּעֹת--בְּכָל-אֶרֶץ מִצְרָיִם",
         "קרח נאבת מתנפט. פי גמיע בלד מצר",
         "a boil breaking out in blisters — over all the land of Egypt"),
    ],
    10: [
        ("וַיִּקְחוּ אֶת-פִּיחַ הַכִּבְשָׁן וַיַּעַמְדוּ לִפְנֵי פַרְעֹה",
         "פאכ'ד'א מן פיח אלאתון. ווקפא בין ידי פרעון",
         "So they took from the soot of the furnace, and stood before Pharaoh"),
        ("וַיִּזְרֹק אֹתוֹ מֹשֶׁה הַשָּׁמָיְמָה", "והווא בה מוסי' פי אלהוא",
         "and Moses scattered it into the air"),
        ("וַיְהִי שְׁחִין אֲבַעְבֻּעֹת פֹּרֵחַ בָּאָדָם וּבַבְּהֵמָה",
         "פצאר קרח מתנפט. נאבת פי אלנאס ואלבהאים",
         "and there came boils breaking out in blisters, growing upon the people and upon the beasts"),
    ],
    11: [
        ("וְלֹא-יָכְלוּ הַחַרְטֻמִּים לַעֲמֹד לִפְנֵי מֹשֶׁה--מִפְּנֵי הַשְּׁחִין",
         "ולם יטיקו אלעלמא. אן יקפו בין ידי מוסי' מן קלב אלקרח",
         "And the learned men were unable to stand before Moses on account of the boil"),
        ("כִּי-הָיָה הַשְּׁחִין בַּחַרְטֻמִּם וּבְכָל-מִצְרָיִם",
         "לאנה כאן פיהום ופי סאיר אלמצריון",
         "for it was upon them and upon the rest of the Egyptians"),
    ],
    12: [
        ("וַיְחַזֵּק יְהוָה אֶת-לֵב פַּרְעֹה", "ושדד אללה קלב פרעון",
         "And God hardened the heart of Pharaoh"),
        ("וְלֹא שָׁמַע אֲלֵהֶם", "ולם יקבל מנהמא", "and he did not accept from them"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה אֶל-מֹשֶׁה", "כמי' קאל אללה למוסי'",
         "as God had said to Moses"),
    ],
    13: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה הַשְׁכֵּם בַּבֹּקֶר",
         "וקאל אללה למוסי'. אדלג באלג'דאה",
         "And God said to Moses: 'Rise early in the morning"),
        ("וְהִתְיַצֵּב לִפְנֵי פַרְעֹה", "וקף בין ידי פרעון",
         "and stand before Pharaoh"),
        ("וְאָמַרְתָּ אֵלָיו כֹּה-אָמַר יְהוָה אֱלֹהֵי הָעִבְרִים",
         "וקל לה. כד'א קאל אללה אלאה אלעבראניין",
         "and say to him: Thus says God, the God of the Hebrews"),
        ("שַׁלַּח אֶת-עַמִּי וְיַעַבְדֻנִי", "אטלק קומי יעבדוני",
         "release my people that they may serve me"),
    ],
    14: [
        ("כִּי בַּפַּעַם הַזֹּאת אֲנִי שֹׁלֵחַ אֶת-כָּל-מַגֵּפֹתַי אֶל-לִבְּךָ",
         "לאני פי הד'א אלמרה. באעת' בכת'יר מן אפאתי פי קלבך",
         "For in this instance I am sending many of my plagues into your heart"),
        ("וּבַעֲבָדֶיךָ וּבְעַמֶּךָ", "וקואדך וקומך", "and against your officers and your people"),
        ("בַּעֲבוּר תֵּדַע כִּי אֵין כָּמֹנִי בְּכָל-הָאָרֶץ",
         "לכי תעלם. אן ליס מת'לי פי גמיע אלעאלם",
         "so that you may know that there is none like me in all the world"),
    ],
    15: [
        ("כִּי עַתָּה שָׁלַחְתִּי אֶת-יָדִי", "לאני אלאן לו אטלקת אפאתי",
         "For now, had I unleashed my plagues"),
        ("וָאַךְ אוֹתְךָ וְאֶת-עַמְּךָ בַּדָּבֶר", "לקתלתך וקומך באלובא",
         "I would have struck you and your people with pestilence"),
        ("וַתִּכָּחֵד מִן-הָאָרֶץ", "ואגתחדת מן אלבלד",
         "and you would have been obliterated from the land"),
    ],
    16: [
        ("וְאוּלָם בַּעֲבוּר זֹאת הֶעֱמַדְתִּיךָ", "ולכן בסבב כ'לה בקיתך",
         "But it is for this very reason that I have kept you alive"),
        ("בַּעֲבוּר הַרְאֹתְךָ אֶת-כֹּחִי", "לכי אוריך קוותי",
         "to show you my power"),
        ("וּלְמַעַן סַפֵּר שְׁמִי בְּכָל-הָאָרֶץ", "ולכי יקץ אסמי פי גמיע אל אלעאלם",
         "and so that my name may be told throughout all the world"),
    ],
    17: [
        ("עוֹדְךָ מִסְתּוֹלֵל בְּעַמִּי", "ומהמאך מתרבץ' בקומי",
         "Yet you are still bent upon my people"),
        ("לְבִלְתִּי שַׁלְּחָם", "ללא תטלקהום", "so as not to release them"),
    ],
    18: [
        ("הִנְנִי מַמְטִיר כָּעֵת מָחָר בָּרָד כָּבֵד מְאֹד",
         "האנא ממטר פי מת'ל הד'א אלוקת מן ג'ד. ברד עצ'ים גדא",
         "Behold, I am about to rain down at about this same time tomorrow a very great hail"),
        ("אֲשֶׁר לֹא-הָיָה כָמֹהוּ בְּמִצְרַיִם", "מא לם יכון מת'לה פי מצר",
         "the like of which has not been in Egypt"),
        ("לְמִן-הַיּוֹם הִוָּסְדָה וְעַד-עָתָּה", "מן יום אססת אלי' אלאן",
         "from the day it was founded until now"),
    ],
    19: [
        ("וְעַתָּה שְׁלַח הָעֵז אֶת-מִקְנְךָ", "פאבעת' אלאן צן מאשיתך",
         "So send now — secure your livestock"),
        ("וְאֵת כָּל-אֲשֶׁר לְךָ בַּשָּׂדֶה", "וגמיע מא לך פי אלצחרי'",
         "and all that you have in the open country"),
        ("כָּל-הָאָדָם וְהַבְּהֵמָה אֲשֶׁר-יִמָּצֵא בַשָּׂדֶה וְלֹא יֵאָסֵף הַבַּיְתָה",
         "פאנה אי אנסאן או בהימה וגד פי אלצחרי'. ולם ינצ'ם אלי' אלמנאזל",
         "for any person or beast found in the open country that does not take shelter in the dwellings"),
        ("וְיָרַד עֲלֵהֶם הַבָּרָד וָמֵתוּ", "פינזל עליהום אלברד וימותון",
         "the hail shall fall upon them and they shall die"),
    ],
    20: [
        ("הַיָּרֵא אֶת-דְּבַר יְהוָה מֵעַבְדֵי פַּרְעֹה",
         "פמן כ'אף כלאם אללה. מן קואד פרעון",
         "Whoever among Pharaoh's officers feared the word of God"),
        ("הֵנִיס אֶת-עֲבָדָיו וְאֶת-מִקְנֵהוּ אֶל-הַבָּתִּים",
         "אהרב עבידה ומאשיתה אלי' אלביות",
         "drove his servants and his livestock into the houses"),
    ],
    21: [
        ("וַאֲשֶׁר לֹא-שָׂם לִבּוֹ אֶל-דְּבַר יְהוָה",
         "ומן לם ירד באלה אלי' כלאם אללה",
         "And whoever did not turn his heart to the word of God"),
        ("וַיַּעֲזֹב אֶת-עֲבָדָיו וְאֶת-מִקְנֵהוּ בַּשָּׂדֶה",
         "תרך עבידה ומאשיתה פי אלצחרי'",
         "left his servants and his livestock in the open country"),
    ],
    22: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'", "And God said to Moses"),
        ("נְטֵה אֶת-יָדְךָ עַל-הַשָּׁמַיִם", "מד ידך נחו אלסמא",
         "Stretch out your hand toward the sky"),
        ("וִיהִי בָרָד בְּכָל-אֶרֶץ מִצְרָיִם", "יכון ברד פי גמיע בלד מצר",
         "that there be hail over all the land of Egypt"),
        ("עַל-הָאָדָם וְעַל-הַבְּהֵמָה וְעַל כָּל-עֵשֶׂב הַשָּׂדֶה--בְּאֶרֶץ מִצְרָיִם",
         "עלי' אלנאס ואלבהאים. וגמיע עשב אלצחרי' פי בלד מצר",
         "upon the people and upon the beasts, and upon all the grass of the open country in the land of Egypt"),
    ],
    23: [
        ("וַיֵּט מֹשֶׁה אֶת-מַטֵּהוּ עַל-הַשָּׁמַיִם", "פמד מוסי' עצאה נחו אלסמא",
         "And Moses stretched out his staff toward the sky"),
        ("וַיהוָה נָתַן קֹלֹת וּבָרָד", "פאעלן אללה אצואתא וברדא",
         "and God proclaimed thunderclaps and hail"),
        ("וַתִּהֲלַךְ אֵשׁ אָרְצָה", "וסארת אלנאר עלי' אלארץ'",
         "and fire moved along the earth"),
        ("וַיַּמְטֵר יְהוָה בָּרָד עַל-אֶרֶץ מִצְרָיִם",
         "ואמטר אללה ברדא עלי' בלד מצר",
         "and God rained down hail upon the land of Egypt"),
    ],
    24: [
        ("וַיְהִי בָרָד--וְאֵשׁ מִתְלַקַּחַת בְּתוֹךְ הַבָּרָד",
         "פכאן אלברד. ונאר מתלכדה פי וסטה",
         "And there was hail, with fire blazing in its midst"),
        ("כָּבֵד מְאֹד", "עצ'ים גדא", "very great"),
        ("אֲשֶׁר לֹא-הָיָה כָמֹהוּ בְּכָל-אֶרֶץ מִצְרַיִם מֵאָז הָיְתָה לְגוֹי",
         "מא לם יכון מת'לה פי גמיע בלד מצר. מד' צארת לאמה",
         "the like of which had not been in all the land of Egypt since it became a nation"),
    ],
    25: [
        ("וַיַּךְ הַבָּרָד בְּכָל-אֶרֶץ מִצְרַיִם",
         "פצ'רב אלברד פי גמיע בלד מצר",
         "And the hail struck throughout all the land of Egypt"),
        ("אֵת כָּל-אֲשֶׁר בַּשָּׂדֶה מֵאָדָם וְעַד-בְּהֵמָה",
         "גמיע מא פי אלצחרי'. מן אנסאן אלי' בהימה",
         "everything that was in the open country, from person to beast"),
        ("וְאֵת כָּל-עֵשֶׂב הַשָּׂדֶה הִכָּה הַבָּרָד", "וצ'רב גמיע עשבהא",
         "and the hail struck all the grass thereof"),
        ("וְאֶת-כָּל-עֵץ הַשָּׂדֶה שִׁבֵּר", "וכסר גמיע שגרהא",
         "and shattered all the trees thereof"),
    ],
    26: [
        ("רַק בְּאֶרֶץ גֹּשֶׁן אֲשֶׁר-שָׁם בְּנֵי יִשְׂרָאֵל",
         "עדא פי בלד אלסדיר. אלד'י ת'ם בני אסראיל",
         "Except in the land of Goshen, where the sons of Israel were"),
        ("לֹא הָיָה בָּרָד", "לם יכון ברד", "there was no hail"),
    ],
    27: [
        ("וַיִּשְׁלַח פַּרְעֹה וַיִּקְרָא לְמֹשֶׁה וּלְאַהֲרֹן",
         "פבעת' פרעון. ודעא במוסי' והרון",
         "And Pharaoh sent and called for Moses and Aaron"),
        ("וַיֹּאמֶר אֲלֵהֶם חָטָאתִי הַפָּעַם", "וקאל להמא קד אכ'טאת הד'ה אלמרה",
         "and said to them: 'I have sinned this time"),
        ("יְהוָה הַצַּדִּיק", "אללה אלעדל", "God is the just one"),
        ("וַאֲנִי וְעַמִּי הָרְשָׁעִים", "ואנא וקומי אלצ'אלמין",
         "and I and my people are the wrongdoers"),
    ],
    28: [
        ("הַעְתִּירוּ אֶל-יְהוָה", "אשפעא אלי' אללה", "Intercede with God"),
        ("וְרַב מִהְיֹת קֹלֹת אֱלֹהִים וּבָרָד",
         "וחסבנא מן אן תכון אצואת אללה וברד עלינא",
         "for it is enough that there have been thunderclaps of God and hail upon us"),
        ("וַאֲשַׁלְּחָה אֶתְכֶם וְלֹא תֹסִפוּן לַעֲמֹד",
         "חתא אטלקכם. ולא תעאודו אן תקפו",
         "and I shall release you, and you need not remain any longer"),
    ],
    29: [
        ("וַיֹּאמֶר אֵלָיו מֹשֶׁה כְּצֵאתִי אֶת-הָעִיר",
         "ת'ם קאל מוסי'. אד'א כ'רגת מן אלקריה",
         "Then Moses said: 'When I go out from the town"),
        ("אֶפְרֹשׂ אֶת-כַּפַּי אֶל-יְהוָה", "אבסט ידיי אלי' אללה",
         "I shall spread out my hands to God"),
        ("הַקֹּלוֹת יֶחְדָּלוּן וְהַבָּרָד לֹא יִהְיֶה-עוֹד",
         "פתנתהי אלאצואת. ואלברד לם יכון איצ'א",
         "and the thunderclaps shall cease, and the hail shall be no more"),
        ("לְמַעַן תֵּדַע כִּי לַיהוָה הָאָרֶץ", "לכי תעלם. אן אלארץ' ללה",
         "so that you may know that the earth belongs to God"),
    ],
    30: [
        ("וְאַתָּה וַעֲבָדֶיךָ", "ואמא אנת וקואדך", "But as for you and your officers"),
        ("יָדַעְתִּי", "פאעלמו", "I know"),
        ("כִּי טֶרֶם תִּירְאוּן מִפְּנֵי יְהוָה אֱלֹהִים",
         "קבל אן תכ'אפו מן בין ידי אללה",
         "that you have yet to fear the presence of God"),
    ],
    31: [
        ("וְהַפִּשְׁתָּה וְהַשְּׂעֹרָה נֻכָּתָה", "אן אלכתאן ואלשעיר קד עטבא",
         "Now the flax and the barley had been ruined"),
        ("כִּי הַשְּׂעֹרָה אָבִיב", "לאן אלשעיר כאן פריכא",
         "for the barley was already in ear"),
        ("וְהַפִּשְׁתָּה גִּבְעֹל", "ואלכתאן משלפא", "and the flax was in bud"),
    ],
    32: [
        ("וְהַחִטָּה וְהַכֻּסֶּמֶת לֹא נֻכּוּ", "ואלחנטה ואלכרסנה לם יעטבא",
         "But the wheat and the spelt were not ruined"),
        ("כִּי אֲפִילֹת הֵנָּה", "לאנהמא אפלתאן", "for they are late-growing"),
    ],
    33: [
        ("וַיֵּצֵא מֹשֶׁה מֵעִם פַּרְעֹה אֶת-הָעִיר",
         "ולמא כ'רג מוסי' מן ענד פרעון ומן קריתה",
         "And when Moses went out from Pharaoh and from his town"),
        ("וַיִּפְרֹשׂ כַּפָּיו אֶל-יְהוָה", "בסט ידיה אלי' אללה",
         "he spread out his hands to God"),
        ("וַיַּחְדְּלוּ הַקֹּלוֹת וְהַבָּרָד", "פאנתהת אלאצואת ואלברד",
         "and the thunderclaps and the hail ceased"),
        ("וּמָטָר לֹא-נִתַּךְ אָרְצָה", "ולם ינחל מטר עלי' אלארץ'",
         "and no rain poured down upon the earth"),
    ],
    34: [
        ("וַיַּרְא פַּרְעֹה כִּי-חָדַל הַמָּטָר וְהַבָּרָד וְהַקֹּלֹת",
         "פלמא ראא פרעון. אן קד אנתהא אלמטר ואלברד. ואלאצואת",
         "And when Pharaoh saw that the rain and the hail and the thunderclaps had ceased"),
        ("וַיֹּסֶף לַחֲטֹא", "עאוד אלכ'טא", "he went back to sinning"),
        ("וַיַּכְבֵּד לִבּוֹ הוּא וַעֲבָדָיו", "פתקל קלבה הו וקואדה",
         "and he and his officers hardened their hearts"),
    ],
    35: [
        ("וַיֶּחֱזַק לֵב פַּרְעֹה", "ואשתד קלב פרעון",
         "And the heart of Pharaoh was hardened"),
        ("וְלֹא שִׁלַּח אֶת-בְּנֵי יִשְׂרָאֵל", "ולם יטלקהום",
         "and he did not release them"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה בְּיַד-מֹשֶׁה", "כמא קאל אללה למוסי'",
         "as God had said to Moses"),
    ],
}
