"""Hand-authored alignment triples for Shemot chapter 18."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּשְׁמַע יִתְרוֹ כֹהֵן מִדְיָן חֹתֵן מֹשֶׁה",
         "ת'ם סמע. יתרו אמאם מדין חמו מוסי'",
         "Then Jethro, the imām of Midian, the father-in-law of Moses, heard"),
        ("אֵת כָּל-אֲשֶׁר עָשָׂה אֱלֹהִים לְמֹשֶׁה וּלְיִשְׂרָאֵל עַמּוֹ",
         "גמיע מא צנע אללה למוסי'. ולאסראיל קומה",
         "all that God had done for Moses and for Israel his people"),
        ("כִּי-הוֹצִיא יְהוָה אֶת-יִשְׂרָאֵל מִמִּצְרָיִם",
         "אד' אכ'רג אללה בני אסראיל מן מצר",
         "since God had brought the sons of Israel out of Egypt."),
    ],
    2: [
        ("וַיִּקַּח יִתְרוֹ חֹתֵן מֹשֶׁה אֶת-צִפֹּרָה אֵשֶׁת מֹשֶׁה",
         "פאכ'ד' יתרו חמו מוסי'. צפרה זוגתה",
         "And Jethro, the father-in-law of Moses, took Zipporah, the wife of Moses"),
        ("אַחַר שִׁלּוּחֶיהָ", "בעד מא כאן קד ארסלהא לה",
         "after he had sent her back to him."),
    ],
    3: [
        ("וְאֵת שְׁנֵי בָנֶיהָ", "ואבניהא", "And her two sons"),
        ("אֲשֶׁר שֵׁם הָאֶחָד גֵּרְשֹׁם", "אלד'י אסם אחדהמא גרשום",
         "the name of one of whom was Gershom"),
        ("כִּי אָמַר גֵּר הָיִיתִי בְּאֶרֶץ נָכְרִיָּה",
         "לאנה קאל. צרת ג'ריבא פי בלד ג'רבה",
         "because he said: 'I have become a stranger in a land of strangeness'"),
    ],
    4: [
        ("וְשֵׁם הָאֶחָד אֱלִיעֶזֶר", "ואסם אלאכ'ר אליעזר",
         "and the name of the other was Eliezer"),
        ("כִּי-אֱלֹהֵי אָבִי בְּעֶזְרִי", "לאנה קאל. אן אלאה אבי כאן פי עוני",
         "because he said: 'The God of my father was in my help"),
        ("וַיַּצִּלֵנִי מֵחֶרֶב פַּרְעֹה", "וכ'לצני מן סיף פרעון",
         "and delivered me from the sword of Pharaoh."),
    ],
    5: [
        ("וַיָּבֹא יִתְרוֹ חֹתֵן מֹשֶׁה וּבָנָיו וְאִשְׁתּוֹ--אֶל-מֹשֶׁה",
         "פגא יתרו חמו מוסי'. ובניה וזוגתה אליה",
         "And Jethro, the father-in-law of Moses, came with his sons and his wife to him"),
        ("אֶל-הַמִּדְבָּר אֲשֶׁר-הוּא חֹנֶה שָׁם",
         "אלי' אלבר. אלד'י הו נאזל ת'ם",
         "into the wilderness — he who was encamped there"),
        ("הַר הָאֱלֹהִים", "אלי' גבל אללה", "at the mountain of God."),
    ],
    6: [
        ("וַיֹּאמֶר אֶל-מֹשֶׁה", "ובעת' במן קאל למוסי' ענה",
         "And he sent someone to say to Moses on his behalf"),
        ("אֲנִי חֹתֶנְךָ יִתְרוֹ בָּא אֵלֶיךָ", "אנא חמוך יתרו גאי אליך",
         "'Your father-in-law Jethro has come to you"),
        ("וְאִשְׁתְּךָ--וּשְׁנֵי בָנֶיהָ עִמָּהּ", "וזוגתך ואבניהא מעהא",
         "and your wife and her two sons with her."),
    ],
    7: [
        ("וַיֵּצֵא מֹשֶׁה לִקְרַאת חֹתְנוֹ", "פכ'רג מוסי' יתלקא חמוה",
         "And Moses went out to receive his father-in-law"),
        ("וַיִּשְׁתַּחוּ וַיִּשַּׁק-לוֹ", "פסגד ת'ם קבלה",
         "and he bowed down, then kissed him"),
        ("וַיִּשְׁאֲלוּ אִישׁ-לְרֵעֵהוּ לְשָׁלוֹם",
         "וסאל כל אמר ען סלאמה' צאחבה",
         "and each man asked after the well-being of his companion"),
        ("וַיָּבֹאוּ הָאֹהֱלָה", "ודכ'לא אלי' אלכ'בא",
         "and the two of them entered into the tent."),
    ],
    8: [
        ("וַיְסַפֵּר מֹשֶׁה לְחֹתְנוֹ", "פקץ מוסי' עלי' חמוה",
         "And Moses recounted to his father-in-law"),
        ("אֵת כָּל-אֲשֶׁר עָשָׂה יְהוָה לְפַרְעֹה וּלְמִצְרַיִם עַל אוֹדֹת יִשְׂרָאֵל",
         "גמיע מא צנע אללה בפרעון ואלמצריון בסבב בני אסראיל",
         "all that God had done to Pharaoh and the Egyptians on account of the sons of Israel"),
        ("אֵת כָּל-הַתְּלָאָה אֲשֶׁר מְצָאָתַם בַּדֶּרֶךְ",
         "וגמיע אלמציבה אלתי נאלתהם פי אלטריק",
         "and all the hardship that had befallen them on the way"),
        ("וַיַּצִּלֵם יְהוָה", "וכ'לצהם אללה",
         "and how God had delivered them."),
    ],
    9: [
        ("וַיִּחַדְּ יִתְרוֹ", "פסר יתרו", "And Jethro rejoiced"),
        ("עַל כָּל-הַטּוֹבָה אֲשֶׁר-עָשָׂה יְהוָה לְיִשְׂרָאֵל",
         "בגמיע אלכ'יר. אלד'י צנעה אללה לבני אסראיל",
         "over all the good that God had done for the sons of Israel"),
        ("אֲשֶׁר הִצִּילוֹ מִיַּד מִצְרָיִם", "וכ'לצהם מן יד אלמצריון",
         "and that He had delivered them from the hand of the Egyptians."),
    ],
    10: [
        ("וַיֹּאמֶר יִתְרוֹ", "וקאל יתרו", "And Jethro said"),
        ("בָּרוּךְ יְהוָה אֲשֶׁר הִצִּיל אֶתְכֶם מִיַּד מִצְרַיִם וּמִיַּד פַּרְעֹה",
         "תבארך אללה. אלד'י כ'לצכם. מן יד אלמצריון ומן יד פרעון",
         "'Blessed be God, who has delivered you from the hand of the Egyptians and from the hand of Pharaoh"),
        ("אֲשֶׁר הִצִּיל אֶת-הָעָם מִתַּחַת יַד-מִצְרָיִם",
         "אלד'י כ'לץ אלקום. מן תחת נקל אלמצריון",
         "who has delivered the people from under the burden of the Egyptians."),
    ],
    11: [
        ("עַתָּה יָדַעְתִּי כִּי-גָדוֹל יְהוָה מִכָּל-הָאֱלֹהִים",
         "אלאן עלמת. אן אללה אכבר מן גמיע אלמעבודאת",
         "'Now I know that God is greater than all objects of worship"),
        ("כִּי בַדָּבָר אֲשֶׁר זָדוּ עֲלֵיהֶם",
         "אד' עאקבהם באלאמר אלד'י אתקחו בה עליהם",
         "inasmuch as He requited them with the very thing by which they had acted presumptuously against them."),
    ],
    12: [
        ("וַיִּקַּח יִתְרוֹ חֹתֵן מֹשֶׁה עֹלָה וּזְבָחִים--לֵאלֹהִים",
         "וקדם יתרו חמו מוסי'. צואעדא וד'באיחא ללה",
         "And Jethro, the father-in-law of Moses, presented burnt-offerings and sacrifices to God"),
        ("וַיָּבֹא אַהֲרֹן וְכֹל זִקְנֵי יִשְׂרָאֵל",
         "פגא הרון. וגמיע שיוך' בני אסראיל",
         "and Aaron came, and all the elders of the sons of Israel"),
        ("לֶאֱכָל-לֶחֶם עִם-חֹתֵן מֹשֶׁה--לִפְנֵי הָאֱלֹהִים",
         "ליאכלו מעה טעאמא בין ידי אללה",
         "to eat a meal with him before God."),
    ],
    13: [
        ("וַיְהִי מִמָּחֳרָת", "פלמא כאן מן ג'ד",
         "And when it was on the morrow"),
        ("וַיֵּשֶׁב מֹשֶׁה לִשְׁפֹּט אֶת-הָעָם", "וקף מוסי' ליחכם ללקום",
         "Moses stood to judge the people"),
        ("וַיַּעֲמֹד הָעָם עַל-מֹשֶׁה מִן-הַבֹּקֶר עַד-הָעָרֶב",
         "פוקף אלקום אמאמה. מן אלג'דאה אלי' אלעשי",
         "and the people stood before him from morning until evening."),
    ],
    14: [
        ("וַיַּרְא חֹתֵן מֹשֶׁה אֵת כָּל-אֲשֶׁר-הוּא עֹשֶׂה לָעָם",
         "פראי' חמוה. גמיע מא הו צאנעה באלקום",
         "And his father-in-law saw all that he was doing for the people"),
        ("וַיֹּאמֶר מָה-הַדָּבָר הַזֶּה אֲשֶׁר אַתָּה עֹשֶׂה לָעָם",
         "פקאל. מא הד'א אלאמר אלד'י אנת צאנעה באלקום",
         "and he said: 'What is this thing that you are doing for the people?"),
        ("מַדּוּעַ אַתָּה יוֹשֵׁב לְבַדֶּךָ", "מא באלך אנת גאלס וחדך",
         "What is your concern that you sit alone"),
        ("וְכָל-הָעָם נִצָּב עָלֶיךָ מִן-בֹּקֶר עַד-עָרֶב",
         "וגמיע אלקום. ואקפין אמאמך מן אלג'דאה אלי' אלעשי",
         "while all the people stand before you from morning until evening?"),
    ],
    15: [
        ("וַיֹּאמֶר מֹשֶׁה לְחֹתְנוֹ", "קאל לה", "He said to him"),
        ("כִּי-יָבֹא אֵלַי הָעָם לִדְרֹשׁ אֱלֹהִים",
         "אד' יגו אליי. אלקום יטלבון אמר אללה",
         "'It is because the people come to me seeking the word of God."),
    ],
    16: [
        ("כִּי-יִהְיֶה לָהֶם דָּבָר בָּא אֵלַי", "אן כאנת להם כ'צומה גאו אליי",
         "'If they have a dispute, they come to me"),
        ("וְשָׁפַטְתִּי בֵּין אִישׁ וּבֵין רֵעֵהוּ", "חכמת בין אלרגל וצאחבה",
         "and I judge between the man and his companion"),
        ("וְהוֹדַעְתִּי אֶת-חֻקֵּי הָאֱלֹהִים וְאֶת-תּוֹרֹתָיו",
         "וערפתהם רסום אללה ושראיעה",
         "and I make known to them the ordinances of God and His laws."),
    ],
    17: [
        ("וַיֹּאמֶר חֹתֵן מֹשֶׁה אֵלָיו", "קאל לה חמוה",
         "His father-in-law said to him"),
        ("לֹא-טוֹב הַדָּבָר אֲשֶׁר אַתָּה עֹשֶׂה",
         "ליס אלאצלח הד'א אלאמר. אלד'י אנת צאנעה",
         "'What you are doing is not the best course."),
    ],
    18: [
        ("נָבֹל תִּבֹּל", "כלא תכל", "'You will surely wear out"),
        ("גַּם-אַתָּה גַּם-הָעָם הַזֶּה אֲשֶׁר עִמָּךְ", "אנת ואלקום אלד'ין מעך",
         "both you and the people who are with you"),
        ("כִּי-כָבֵד מִמְּךָ הַדָּבָר", "לאן אלאמר ת'קיל עליך",
         "for the matter is too heavy upon you"),
        ("לֹא-תוּכַל עֲשֹׂהוּ לְבַדֶּךָ", "ולא תטיק אן תצנעה וחדך",
         "and you cannot do it alone."),
    ],
    19: [
        ("עַתָּה שְׁמַע בְּקֹלִי אִיעָצְךָ", "אלאן. אקבל מני מא אשיר בה עליך",
         "'Now, accept from me what I counsel you"),
        ("וִיהִי אֱלֹהִים עִמָּךְ", "ויכון אללה מעך", "and may God be with you"),
        ("הֱיֵה אַתָּה לָעָם מוּל הָאֱלֹהִים", "כן אנת לאלקום מן גהה' אללה",
         "be you for the people the one who faces God"),
        ("וְהֵבֵאתָ אַתָּה אֶת-הַדְּבָרִים אֶל-הָאֱלֹהִים", "תרפע אמורהם אליה",
         "bring their matters up to Him;"),
    ],
    20: [
        ("וְהִזְהַרְתָּה אֶתְהֶם אֶת-הַחֻקִּים וְאֶת-הַתּוֹרֹת",
         "ותנד'רהם עלי' אלרסום ואלשראיע",
         "'and warn them concerning the ordinances and the laws"),
        ("וְהוֹדַעְתָּ לָהֶם אֶת-הַדֶּרֶךְ יֵלְכוּ בָהּ",
         "ותערפהם אלטריק אלד'י יסלכן פיה",
         "and make known to them the way in which they shall walk"),
        ("וְאֶת-הַמַּעֲשֶׂה אֲשֶׁר יַעֲשׂוּן", "ואלעמל אלד'י יעמלונה",
         "and the deeds that they shall do."),
    ],
    21: [
        ("וְאַתָּה תֶחֱזֶה מִכָּל-הָעָם", "ואנת פאנצ'ר מן גמיע אלקום",
         "'And you — look out from all the people"),
        ("אַנְשֵׁי-חַיִל", "אנאס ד'וי חיל", "for men of ability"),
        ("יִרְאֵי אֱלֹהִים", "אתקיא אללה", "who fear God"),
        ("אַנְשֵׁי אֱמֶת--שֹׂנְאֵי בָצַע", "ד'וי חק שאניי אלטמע",
         "men of integrity who hate greed"),
        ("וְשַׂמְתָּ עֲלֵהֶם שָׂרֵי אֲלָפִים שָׂרֵי מֵאוֹת שָׂרֵי חֲמִשִּׁים וְשָׂרֵי עֲשָׂרֹת",
         "וולי עליהם רויסא אלוף ומאיין. וכ'מסין ועשאראת",
         "and appoint over them heads of thousands and hundreds, and of fifties and of tens."),
    ],
    22: [
        ("וְשָׁפְטוּ אֶת-הָעָם בְּכָל-עֵת",
         "פיחכמון פי מא בין אלקום פי כל וקת",
         "'And they shall judge among the people at all times"),
        ("וְהָיָה כָּל-הַדָּבָר הַגָּדֹל יָבִיאוּ אֵלֶיךָ",
         "ויכון כל אמר עצ'ים ירפעונה אליך",
         "and every great matter they shall bring up to you"),
        ("וְכָל-הַדָּבָר הַקָּטֹן יִשְׁפְּטוּ-הֵם",
         "וכל אמר צג'יר יחכמון פיה הם",
         "while every small matter they shall judge themselves"),
        ("וְהָקֵל מֵעָלֶיךָ", "וכ'פף ען נפסך",
         "so lighten the burden from yourself"),
        ("וְנָשְׂאוּ אִתָּךְ", "ויחתמלון מעך",
         "and they shall bear it together with you."),
    ],
    23: [
        ("אִם אֶת-הַדָּבָר הַזֶּה תַּעֲשֶׂה", "אן אנת צנעת הד'א אלאמר",
         "'If you do this thing"),
        ("וְצִוְּךָ אֱלֹהִים", "ואמרך אללה בה", "and God commands you in it"),
        ("וְיָכָלְתָּ עֲמֹד", "אטקת אלקיאם", "you will be able to endure"),
        ("וְגַם כָּל-הָעָם הַזֶּה עַל-מְקֹמוֹ יָבֹא בְשָׁלוֹם",
         "ואיצ'א גמיע הד'א אלקום. אלי' מוצ'עה יציר בסלאם",
         "and likewise all this people will reach their place in peace."),
    ],
    24: [
        ("וַיִּשְׁמַע מֹשֶׁה לְקוֹל חֹתְנוֹ", "פקבל מוסי' מן חמוה",
         "And Moses accepted from his father-in-law"),
        ("וַיַּעַשׂ כֹּל אֲשֶׁר אָמָר", "וצנע גמיע מא אמרה",
         "and did all that he had commanded him."),
    ],
    25: [
        ("וַיִּבְחַר מֹשֶׁה אַנְשֵׁי-חַיִל מִכָּל-יִשְׂרָאֵל",
         "פאכ'תאר מוסי' אנאס ד'וי חיל מן גמיע אל אסראיל",
         "And Moses chose men of ability from all the house of Israel"),
        ("וַיִּתֵּן אֹתָם רָאשִׁים עַל-הָעָם", "וולאהם רויסא עליהם",
         "and appointed them as heads over them"),
        ("שָׂרֵי אֲלָפִים שָׂרֵי מֵאוֹת שָׂרֵי חֲמִשִּׁים וְשָׂרֵי עֲשָׂרֹת",
         "רויסא אלוף ומאיין. וכ'מסין ועשאראת",
         "heads of thousands and hundreds, and of fifties and of tens."),
    ],
    26: [
        ("וְשָׁפְטוּ אֶת-הָעָם בְּכָל-עֵת",
         "פצארו יחכמון פי מא בין אלקום פי כל וקת",
         "And they came to judge among the people at all times"),
        ("אֶת-הַדָּבָר הַקָּשֶׁה יְבִיאוּן אֶל-מֹשֶׁה",
         "כל אמר צעב ירפעונה אלי' מוסי'",
         "every difficult matter they would bring up to Moses"),
        ("וְכָל-הַדָּבָר הַקָּטֹן יִשְׁפּוּטוּ הֵם",
         "וכל אמר צג'יר יחכמון פיה הם",
         "and every small matter they would judge themselves."),
    ],
    27: [
        ("וַיְשַׁלַּח מֹשֶׁה אֶת-חֹתְנוֹ", "פאטלק מוסי' חמוה",
         "And Moses released his father-in-law"),
        ("וַיֵּלֶךְ לוֹ אֶל-אַרְצוֹ", "ומצ'א אלי' בלדה",
         "and he went on his way to his land."),
    ],
}
