"""Hand-authored alignment triples for Shemot chapter 40."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("בְּיוֹם-הַחֹדֶשׁ הָרִאשׁוֹן בְּאֶחָד לַחֹדֶשׁ",
         "פי אלשהר אלאוול. פי אליום אלאוול מנה",
         "In the first month, on the first day of it"),
        ("תָּקִים אֶת-מִשְׁכַּן אֹהֶל מוֹעֵד", "אנצב מסכן כ'בא אלמחצ'ר",
         "erect the tabernacle of the tent of the assembly."),
    ],
    3: [
        ("וְשַׂמְתָּ שָׁם אֵת אֲרוֹן הָעֵדוּת", "וצייר בה צנדוק אלשהאדה",
         "And place therein the ark of the testimony"),
        ("וְסַכֹּתָ עַל-הָאָרֹן אֶת-הַפָּרֹכֶת", "ואסתר עליה באלסגף",
         "and screen over it with the curtain."),
    ],
    4: [
        ("וְהֵבֵאתָ אֶת-הַשֻּׁלְחָן וְעָרַכְתָּ אֶת-עֶרְכּוֹ",
         "ת'ם אדכ'ל אלמאידה. וצף צפיהא",
         "Then bring in the table, and arrange its two rows"),
        ("וְהֵבֵאתָ אֶת-הַמְּנֹרָה וְהַעֲלֵיתָ אֶת-נֵרֹתֶיהָ",
         "ואדכ'ל אלמנארה. ואסרג סרגהא",
         "and bring in the lampstand, and light its lamps."),
    ],
    5: [
        ("וְנָתַתָּה אֶת-מִזְבַּח הַזָּהָב לִקְטֹרֶת לִפְנֵי אֲרוֹן הָעֵדֻת",
         "ת'ם אגעל מד'בח אלד'הב לאלב'כור. בין ידי צנדוק אלשהאדה",
         "Then place the altar of gold for incense before the ark of the testimony"),
        ("וְשַׂמְתָּ אֶת-מָסַךְ הַפֶּתַח לַמִּשְׁכָּן", "ועלק סתר באב כ'בא אלמסכן",
         "and hang the screen of the entrance of the tent of the tabernacle."),
    ],
    6: [
        ("וְנָתַתָּה אֵת מִזְבַּח הָעֹלָה לִפְנֵי פֶּתַח מִשְׁכַּן אֹהֶל-מוֹעֵד",
         "ת'ם אגעל מד'בח אלקראבין. בין ידי כ'בא אלמחצ'ר",
         "Then place the altar of offerings before the tent of the assembly."),
    ],
    7: [
        ("וְנָתַתָּ אֶת-הַכִּיֹּר בֵּין-אֹהֶל מוֹעֵד וּבֵין הַמִּזְבֵּחַ",
         "ת'ם אגעל אלחוץ'. בין כ'בא אלמחצ'ר ואלמד'בח",
         "Then place the basin between the tent of the assembly and the altar"),
        ("וְנָתַתָּ שָׁם מָיִם", "ואגעל פיה מאא", "and put water in it."),
    ],
    8: [
        ("וְשַׂמְתָּ אֶת-הֶחָצֵר סָבִיב", "ת'ם אצ'רב אלצראדק מסתדירא",
         "Then pitch the courtyard enclosure all around"),
        ("וְנָתַתָּ אֶת-מָסַךְ שַׁעַר הֶחָצֵר", "ועלק סתר באבה",
         "and hang the screen of its gate."),
    ],
    9: [
        ("וְלָקַחְתָּ אֶת-שֶׁמֶן הַמִּשְׁחָה וּמָשַׁחְתָּ אֶת-הַמִּשְׁכָּן",
         "ת'ם כ'ד מן דהן אלמסח. ואמסח אלמסכן",
         "Then take from the anointing oil, and anoint the tabernacle"),
        ("וְאֶת-כָּל-אֲשֶׁר-בּוֹ וְקִדַּשְׁתָּ אֹתוֹ וְאֶת-כָּל-כֵּלָיו וְהָיָה קֹדֶשׁ",
         "וגמיע מא פיה. וקדסה.",
         "and all that is in it, and consecrate it, and all its vessels — and it shall become holy."),
    ],
    10: [
        ("וּמָשַׁחְתָּ אֶת-מִזְבַּח הָעֹלָה וְאֶת-כָּל-כֵּלָיו",
         "ואמסח מד'בח אלצעידה וגמיע אניתה",
         "And anoint the altar of the offering and all its vessels"),
        ("וְקִדַּשְׁתָּ אֶת-הַמִּזְבֵּחַ וְהָיָה הַמִּזְבֵּחַ קֹדֶשׁ קָדָשִׁים",
         "וקדסה. ויציר מן כ'ואץ אלאקדאס",
         "and consecrate it — and it shall become of the choicest of the holy things."),
    ],
    11: [
        ("וּמָשַׁחְתָּ אֶת-הַכִּיֹּר וְאֶת-כַּנּוֹ", "ואמסח אלחוץ' ומקעדה",
         "And anoint the basin and its base"),
        ("וְקִדַּשְׁתָּ אֹתוֹ", "וקדסהמא", "and consecrate the two of them."),
    ],
    12: [
        ("וְהִקְרַבְתָּ אֶת-אַהֲרֹן וְאֶת-בָּנָיו אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "וקדם הרון ובניה אלי'' באב כ'בא אלמחצ'ר",
         "And bring forward Aaron and his sons to the entrance of the tent of the assembly"),
        ("וְרָחַצְתָּ אֹתָם בַּמָּיִם", "ותג'סלהם באלמא", "and wash them with water."),
    ],
    13: [
        ("וְהִלְבַּשְׁתָּ אֶת-אַהֲרֹן אֵת בִּגְדֵי הַקֹּדֶשׁ",
         "ואלבס הרון ת'יאב אלקדס",
         "And clothe Aaron in the garments of holiness"),
        ("וּמָשַׁחְתָּ אֹתוֹ וְקִדַּשְׁתָּ אֹתוֹ", "ואמסחה וקדסה",
         "and anoint him and consecrate him"),
        ("וְכִהֵן לִי", "ליאם לי", "that he may lead for Me."),
    ],
    14: [
        ("וְאֶת-בָּנָיו תַּקְרִיב", "וקדם בניה", "And bring forward his sons"),
        ("וְהִלְבַּשְׁתָּ אֹתָם כֻּתֳּנֹת", "ואלבסהם תואניא", "and clothe them in tunics."),
    ],
    15: [
        ("וּמָשַׁחְתָּ אֹתָם כַּאֲשֶׁר מָשַׁחְתָּ אֶת-אֲבִיהֶם",
         "ואמסחהם כמא מסחת אביהם",
         "And anoint them as you anointed their father"),
        ("וְכִהֲנוּ לִי", "ליאמו לי", "that they may lead for Me"),
        ("וְהָיְתָה לִהְיֹת לָהֶם מָשְׁחָתָם לִכְהֻנַּת עוֹלָם--לְדֹרֹתָם",
         "ויכון מסחהם ד'אך להם. אמאמה' אלדהר לאגיאלהם",
         "and that anointing of theirs shall be for them a priesthood forever, unto their generations."),
    ],
    16: [
        ("וַיַּעַשׂ מֹשֶׁה כְּכֹל אֲשֶׁר צִוָּה יְהוָה אֹתוֹ--כֵּן עָשָׂה",
         "וצנע מוסי''. כגמיע מא אמרה אללה בה",
         "And Moses did according to all that God had commanded him therein."),
    ],
    17: [
        ("וַיְהִי בַּחֹדֶשׁ הָרִאשׁוֹן בַּשָּׁנָה הַשֵּׁנִית--בְּאֶחָד לַחֹדֶשׁ",
         "ת'ם אנה למא כאן פי אלשהר אלאוול. מן אלסנה אלת'אניה פי אליום אלאוול מנה",
         "Then, when it was in the first month of the second year, on the first day of it"),
        ("הוּקַם הַמִּשְׁכָּן", "נצב אלמסכן", "the tabernacle was erected."),
    ],
    18: [
        ("וַיָּקֶם מֹשֶׁה אֶת-הַמִּשְׁכָּן", "פאוול מא נצבה מוסי'",
         "The first thing Moses did in erecting it"),
        ("וַיִּתֵּן אֶת-אֲדָנָיו", "וצ'ע קואעדה", "he set down its bases"),
        ("וַיָּשֶׂם אֶת-קְרָשָׁיו וַיִּתֵּן אֶת-בְּרִיחָיו", "ורכב עליה תכ'אתגה. ווצ'ע פיה אמהאגה",
         "and fitted upon them its planks, and placed in it its bars"),
        ("וַיָּקֶם אֶת-עַמּוּדָיו", "ואוקף עמדה", "and stood up its pillars."),
    ],
    19: [
        ("וַיִּפְרֹשׂ אֶת-הָאֹהֶל עַל-הַמִּשְׁכָּן", "ת'ם בסט אלכ'בא עליה",
         "Then he spread the tent over it"),
        ("וַיָּשֶׂם אֶת-מִכְסֵה הָאֹהֶל עָלָיו מִלְמָעְלָה", "וצייר אלג'טא עליה מן פוק",
         "and placed the covering over it from above"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה אללה",
         "as God had commanded him."),
    ],
    20: [
        ("וַיִּקַּח וַיִּתֵּן אֶת-הָעֵדֻת אֶל-הָאָרֹן",
         "ת'ם אכ'ד' אלשהאדה. ווצ'עהא פי אלצנדוק",
         "Then he took the testimony and placed it in the ark"),
        ("וַיָּשֶׂם אֶת-הַבַּדִּים עַל-הָאָרֹן", "וצייר עליה אלד'הוק",
         "and set the carrying-poles upon it"),
        ("וַיִּתֵּן אֶת-הַכַּפֹּרֶת עַל-הָאָרֹן מִלְמָעְלָה", "וגעל אלג'שא עליה מן פוק",
         "and placed the cover over it from above."),
    ],
    21: [
        ("וַיָּבֵא אֶת-הָאָרֹן אֶל-הַמִּשְׁכָּן", "ת'ם אדכ'לה אלי' אלמסכן",
         "Then he brought it into the tabernacle"),
        ("וַיָּשֶׂם אֵת פָּרֹכֶת הַמָּסָךְ וַיָּסֶךְ עַל אֲרוֹן הָעֵדוּת",
         "ועלק אלסגף אלמסתור. וסתרה עליה",
         "and hung the screening curtain, and screened over it"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה אללה",
         "as God had commanded him."),
    ],
    22: [
        ("וַיִּתֵּן אֶת-הַשֻּׁלְחָן בְּאֹהֶל מוֹעֵד", "ת'ם געל אלמאידה פי כ'בא אלמחצ'ר",
         "Then he placed the table in the tent of the assembly"),
        ("עַל יֶרֶךְ הַמִּשְׁכָּן צָפֹנָה מִחוּץ לַפָּרֹכֶת",
         "פי גאנב אלמסכן אלשמאלי'. כ'ארג אלסגף",
         "on the northern side of the tabernacle, outside the curtain."),
    ],
    23: [
        ("וַיַּעֲרֹךְ עָלָיו עֵרֶךְ לֶחֶם לִפְנֵי יְהוָה",
         "וצף עליה. צפין כ'בז בין ידי אללה",
         "And he arranged upon it two rows of bread before God"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה", "as He had commanded him."),
    ],
    24: [
        ("וַיָּשֶׂם אֶת-הַמְּנֹרָה בְּאֹהֶל מוֹעֵד", "ת'ם צייר אלמנארה פי כ'בא אלמחצ'ר",
         "Then he placed the lampstand in the tent of the assembly"),
        ("נֹכַח הַשֻּׁלְחָן עַל יֶרֶךְ הַמִּשְׁכָּן נֶגְבָּה",
         "חד'א אלמאידה. פי גאנב אלמסכן אלגנובי",
         "opposite the table, on the southern side of the tabernacle."),
    ],
    25: [
        ("וַיַּעַל הַנֵּרֹת לִפְנֵי יְהוָה", "ואסרג אלסרג בין ידי אללה",
         "And he lit the lamps before God"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה", "as He had commanded him."),
    ],
    26: [
        ("וַיָּשֶׂם אֶת-מִזְבַּח הַזָּהָב בְּאֹהֶל מוֹעֵד לִפְנֵי הַפָּרֹכֶת",
         "ת'ם צייר מד'בח אלד'הב פי כ'בא אלמחצ'ר. בין ידי אלסגף",
         "Then he placed the golden altar in the tent of the assembly, before the curtain."),
    ],
    27: [
        ("וַיַּקְטֵר עָלָיו קְטֹרֶת סַמִּים", "ובכ'ר עליה מן בכ'ור אלצמוג'",
         "And he burned incense upon it from the incense of resins"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה אללה",
         "as God had commanded him."),
    ],
    28: [
        ("וַיָּשֶׂם אֶת-מָסַךְ הַפֶּתַח לַמִּשְׁכָּן", "ת'ם עלק. סתר אלבאב עלי' אלמסכן",
         "Then he hung the screen of the entrance upon the tabernacle."),
    ],
    29: [
        ("וְאֵת מִזְבַּח הָעֹלָה שָׂם פֶּתַח מִשְׁכַּן אֹהֶל-מוֹעֵד",
         "וצייר מד'בח עלי' באב כ'בא אלמחצ'ר",
         "And he placed the altar at the entrance of the tent of the assembly"),
        ("וַיַּעַל עָלָיו אֶת-הָעֹלָה וְאֶת-הַמִּנְחָה",
         "וקרב עליה. אלצעידה ואלהדייה",
         "and offered upon it the offering and the gift"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמרה אללה",
         "as God had commanded him."),
    ],
    30: [
        ("וַיָּשֶׂם אֶת-הַכִּיֹּר בֵּין-אֹהֶל מוֹעֵד וּבֵין הַמִּזְבֵּחַ",
         "ת'ם צייר אלחוץ'. בין כ'בא אלמחצ'ר ואלמד'בח",
         "Then he placed the basin between the tent of the assembly and the altar"),
        ("וַיִּתֵּן שָׁמָּה מַיִם לְרָחְצָה", "וגעל פיה מאא לאלג'סל",
         "and put in it water for washing."),
    ],
    31: [
        ("וְרָחֲצוּ מִמֶּנּוּ מֹשֶׁה וְאַהֲרֹן וּבָנָיו", "פיג'סל מנה. מוסי' והרון ובניה",
         "And from it Moses and Aaron and his sons would wash"),
        ("אֶת-יְדֵיהֶם וְאֶת-רַגְלֵיהֶם", "אידיהם וארגלהם", "their hands and their feet —"),
    ],
    32: [
        ("בְּבֹאָם אֶל-אֹהֶל מוֹעֵד", "פי דכ'ולהם אלי' כ'בא אלמחצ'ר",
         "upon their entering the tent of the assembly"),
        ("וּבְקָרְבָתָם אֶל-הַמִּזְבֵּחַ--יִרְחָצוּ", "פי דכולהם אלי' אלמד'בח יג'סלון",
         "and upon their approaching the altar, they would wash"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    33: [
        ("וַיָּקֶם אֶת-הֶחָצֵר סָבִיב לַמִּשְׁכָּן וְלַמִּזְבֵּחַ",
         "ת'ם צ'רב אלצראדק. חואלי' אלמסכן ואלמד'בח",
         "Then he pitched the courtyard enclosure around the tabernacle and the altar"),
        ("וַיִּתֵּן אֶת-מָסַךְ שַׁעַר הֶחָצֵר", "ועלק סתר באבה",
         "and hung the screen of its gate"),
        ("וַיְכַל מֹשֶׁה אֶת-הַמְּלָאכָה", "ואכמל מוסי' גמיע אלצנאעה",
         "and Moses completed all the work."),
    ],
    34: [
        ("וַיְכַס הֶעָנָן אֶת-אֹהֶל מוֹעֵד", "ת'ם ג'טא אלג'מאם כ'בא אלמחצ'ר",
         "Then the cloud covered the tent of the assembly"),
        ("וּכְבוֹד יְהוָה מָלֵא אֶת-הַמִּשְׁכָּן", "ונור אללה מלא אלמסכן",
         "and the light of God filled the tabernacle."),
    ],
    35: [
        ("וְלֹא-יָכֹל מֹשֶׁה לָבוֹא אֶל-אֹהֶל מוֹעֵד",
         "ולם יטיק מוסי'. אן ידכל אלי' כ'בא אלמחצ'ר",
         "And Moses was not able to enter the tent of the assembly"),
        ("כִּי-שָׁכַן עָלָיו הֶעָנָן", "ממא סכן עליה אלג'מאם",
         "because the cloud had settled upon it"),
        ("וּכְבוֹד יְהוָה מָלֵא אֶת-הַמִּשְׁכָּן", "ונור אללה מלא אלמסכן",
         "and the light of God filled the tabernacle."),
    ],
    36: [
        ("וּבְהֵעָלוֹת הֶעָנָן מֵעַל הַמִּשְׁכָּן", "וכאן אלג'מאם אד'א ארתפע ען אלמסכן",
         "And whenever the cloud rose up from the tabernacle"),
        ("יִסְעוּ בְּנֵי יִשְׂרָאֵל בְּכֹל מַסְעֵיהֶם",
         "ירחל בני אסראיל. אלי' גמיע מראחלהם",
         "the sons of Israel would journey through all their journeyings."),
    ],
    37: [
        ("וְאִם-לֹא יֵעָלֶה הֶעָנָן--וְלֹא יִסְעוּ", "ואן לם ירתפע לם ירחלון",
         "And if it did not rise, they would not journey"),
        ("עַד-יוֹם הֵעָלֹתוֹ", "אלא יום ירתפע", "only on the day it rose."),
    ],
    38: [
        ("כִּי עֲנַן יְהוָה עַל-הַמִּשְׁכָּן יוֹמָם", "לאן ג'מאם מן ענד אללה עלי' אלמסכן נהארא",
         "For a cloud from God was upon the tabernacle by day"),
        ("וְאֵשׁ תִּהְיֶה לַיְלָה בּוֹ", "ונארא תכון פיה לילא",
         "and fire would be in it by night"),
        ("לְעֵינֵי כָל-בֵּית-יִשְׂרָאֵל בְּכָל-מַסְעֵיהֶם",
         "בחצ'רה' בני אסראיל פי גמיע מראחלהם",
         "before the sons of Israel throughout all their journeyings."),
    ],
}
