"""Hand-authored alignment triples for Shemot chapter 19."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("בַּחֹדֶשׁ הַשְּׁלִישִׁי", "פי אלשהר אלת'אלת'",
         "In the third month"),
        ("לְצֵאת בְּנֵי-יִשְׂרָאֵל מֵאֶרֶץ מִצְרָיִם", "לכרוג בני אסראיל מן בלד מצר",
         "of the departure of the sons of Israel from the land of Egypt"),
        ("בַּיּוֹם הַזֶּה", "פי ד'אלך אליום", "on that very day"),
        ("בָּאוּ מִדְבַּר סִינָי", "גאו אלי' ברייה' סיני",
         "they came to the wilderness of Sinai"),
    ],
    2: [
        ("וַיִּסְעוּ מֵרְפִידִים", "אד' רחלו מן רפידים",
         "For they had journeyed from Rephidim"),
        ("וַיָּבֹאוּ מִדְבַּר סִינַי", "וגאו אלי' ברייה' סיני",
         "and come to the wilderness of Sinai"),
        ("וַיַּחֲנוּ בַּמִּדְבָּר", "ונזלו פי אלבר", "and encamped in the open country"),
        ("וַיִּחַן-שָׁם יִשְׂרָאֵל נֶגֶד הָהָר", "ונזל ת'ם אסראיל חד'א אלגבל",
         "and Israel encamped there, facing the mountain"),
    ],
    3: [
        ("וּמֹשֶׁה עָלָה אֶל-הָאֱלֹהִים", "ומוסי' צעד אלי' אללה",
         "And Moses went up to God"),
        ("וַיִּקְרָא אֵלָיו יְהוָה מִן-הָהָר לֵאמֹר", "פנאדאה אללה מן אלגבל קאילא",
         "and God called to him from the mountain, saying"),
        ("כֹּה תֹאמַר לְבֵית יַעֲקֹב", "כד'א קל לאל יעקוב",
         "Thus say to the house of Jacob"),
        ("וְתַגֵּיד לִבְנֵי יִשְׂרָאֵל", "ואכ'בר בני אסראיל",
         "and make known to the sons of Israel"),
    ],
    4: [
        ("אַתֶּם רְאִיתֶם", "אנתם שאהדתם", "You have witnessed"),
        ("אֲשֶׁר עָשִׂיתִי לְמִצְרָיִם", "מא צנעת באלמצריון",
         "what I did to the Egyptians"),
        ("וָאֶשָּׂא אֶתְכֶם עַל-כַּנְפֵי נְשָׁרִים", "וחמלתכם שביה עלי' אגנחה' אלנסור",
         "and I carried you — likened to being upon the wings of eagles"),
        ("וָאָבִא אֶתְכֶם אֵלָי", "ואתית בכם אלי' גבלי הד'א",
         "and I brought you to this mountain of Mine"),
    ],
    5: [
        ("וְעַתָּה אִם-שָׁמוֹעַ תִּשְׁמְעוּ בְּקֹלִי", "ואלאן אן קבלתם אמרי",
         "And now, if you accept My command"),
        ("וּשְׁמַרְתֶּם אֶת-בְּרִיתִי", "וחפצ'תם עהדי", "and keep My covenant"),
        ("וִהְיִיתֶם לִי סְגֻלָּה מִכָּל-הָעַמִּים", "כנתם לי כ'אצה מן גמיע אלשעוב",
         "you shall be Mine as a special possession from among all the peoples"),
        ("כִּי-לִי כָּל-הָאָרֶץ", "עלי' אן לי גמיע אלעאלם",
         "given that all the world is Mine"),
    ],
    6: [
        ("וְאַתֶּם תִּהְיוּ-לִי מַמְלֶכֶת כֹּהֲנִים וְגוֹי קָדוֹשׁ",
         "ואנתם תכונו לי. מלוך ואיימה ושעבא מקדסא",
         "And you shall be to Me kings and imāms and a consecrated people"),
        ("אֵלֶּה הַדְּבָרִים", "הד'א אלכלאם", "This is the word"),
        ("אֲשֶׁר תְּדַבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "אלד'י תקולה לבני אסראיל",
         "which was spoken to the sons of Israel"),
    ],
    7: [
        ("וַיָּבֹא מֹשֶׁה", "פגא מוסי'", "And Moses came"),
        ("וַיִּקְרָא לְזִקְנֵי הָעָם", "ודעא שיוך' אלקום",
         "and summoned the elders of the people"),
        ("וַיָּשֶׂם לִפְנֵיהֶם אֵת כָּל-הַדְּבָרִים הָאֵלֶּה",
         "ותלא עליהם גמיע הד'א אלכלאם",
         "and recited to them all this word"),
        ("אֲשֶׁר צִוָּהוּ יְהוָה", "אלד'י אמרה אללה בה",
         "which God had commanded him with"),
    ],
    8: [
        ("וַיַּעֲנוּ כָל-הָעָם יַחְדָּו וַיֹּאמְרוּ כֹּל אֲשֶׁר-דִּבֶּר יְהוָה נַעֲשֶׂה",
         "פאגאבוה אגמעין וקאלו. גמיע מא קאל אללה נצנעה",
         "And they answered him all together and said"),
        ("וַיָּשֶׁב מֹשֶׁה אֶת-דִּבְרֵי הָעָם אֶל-יְהוָה",
         "פרד מוסי' כלאמהם אלי' אללה",
         "And Moses brought back their words to God"),
    ],
    9: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "חין קאל אללה לה",
         "When God said to him"),
        ("הִנֵּה אָנֹכִי בָּא אֵלֶיךָ בְּעַב הֶעָנָן",
         "האנא מתגלי לך בג'מאם מן סחאבי",
         "Behold, I am revealing Myself to you in a thick mass of My clouds"),
        ("בַּעֲבוּר יִשְׁמַע הָעָם בְּדַבְּרִי עִמָּךְ",
         "לכי יסמע אלקום מכ'אטבתי לך",
         "so that the people may hear My address to you"),
        ("וְגַם-בְּךָ יַאֲמִינוּ לְעוֹלָם", "וליומנו בך אבדא אלי' אלדהר",
         "and that they may trust in you forever, unto eternity"),
        ("וַיַּגֵּד מֹשֶׁה אֶת-דִּבְרֵי הָעָם אֶל-יְהוָה",
         "פאכ'בר מוסי' בכלאם אלקום אללה",
         "And Moses reported the words of the people to God"),
    ],
    10: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה לה", "And God said to him"),
        ("לֵךְ אֶל-הָעָם", "אמץ' אלי' אלקום", "Go to the people"),
        ("וְקִדַּשְׁתָּם הַיּוֹם וּמָחָר", "וטהרהם אליום וג'דא",
         "and purify them today and tomorrow"),
        ("וְכִבְּסוּ שִׂמְלֹתָם", "ויג'סלון ת'יאבהם", "and let them wash their garments"),
    ],
    11: [
        ("וְהָיוּ נְכֹנִים לַיּוֹם הַשְּׁלִישִׁי", "ויכונו מסתעדין לליום אלת'אלת'",
         "And let them be ready for the third day"),
        ("כִּי בַּיּוֹם הַשְּׁלִשִׁי יֵרֵד יְהוָה", "פאן פיה יתגלא אללה",
         "for on it God will reveal Himself"),
        ("לְעֵינֵי כָל-הָעָם", "בחצ'רתהם", "in their presence"),
        ("עַל-הַר סִינָי", "עלי' גבל סיני", "upon Mount Sinai"),
    ],
    12: [
        ("וְהִגְבַּלְתָּ אֶת-הָעָם סָבִיב לֵאמֹר", "ותכ'ם אלקום חואליה וקל להם.",
         "And set boundaries for the people all around it, and say to them"),
        ("הִשָּׁמְרוּ לָכֶם עֲלוֹת בָּהָר", "אחד'רו מן אלצעוד אלי' אלגבל",
         "Beware of ascending the mountain"),
        ("וּנְגֹעַ בְּקָצֵהוּ", "ואלדנו מן טרפה",
         "or approaching its edge"),
        ("כָּל-הַנֹּגֵעַ בָּהָר מוֹת יוּמָת", "וכל מן דנא בה פליקתל קתלא",
         "whoever approaches it shall surely be put to death"),
    ],
    13: [
        ("לֹא-תִגַּע בּוֹ יָד", "מן חית' לא תמסה יד",
         "In that no hand shall touch it"),
        ("כִּי-סָקוֹל יִסָּקֵל אוֹ-יָרֹה יִיָּרֶה", "אלא ירגם רגמא או ינשב פיה נשאבא",
         "but he shall be stoned with stones, or shot into with arrows"),
        ("אִם-בְּהֵמָה אִם-אִישׁ לֹא יִחְיֶה", "בהימה כאן אם אנסאנא לא יחיא",
         "whether it be beast or human, he shall not live"),
        ("בִּמְשֹׁךְ הַיֹּבֵל הֵמָּה יַעֲלוּ בָהָר", "ואד'א צרב באלבוק. גאיז להם אן יצעדו אלי' אלגבל",
         "And when the horn is sounded, it is permitted for them to ascend the mountain"),
    ],
    14: [
        ("וַיֵּרֶד מֹשֶׁה מִן-הָהָר אֶל-הָעָם", "פנזל מוסי'. מן אלגבל אלי' אלקום",
         "And Moses descended from the mountain to the people"),
        ("וַיְקַדֵּשׁ אֶת-הָעָם", "פטהרהם", "and he purified them"),
        ("וַיְכַבְּסוּ שִׂמְלֹתָם", "וג'סלו ת'יאבהם", "and they washed their garments"),
    ],
    15: [
        ("וַיֹּאמֶר אֶל-הָעָם", "וקאל להם", "And he said to them"),
        ("הֱיוּ נְכֹנִים לִשְׁלֹשֶׁת יָמִים", "כונו מסתעדין לת'לאת'ה' איאם",
         "Be ready for three days"),
        ("אַל-תִּגְּשׁוּ אֶל-אִשָּׁה", "לא תקרבו אמראה",
         "do not approach a woman"),
    ],
    16: [
        ("וַיְהִי בַיּוֹם הַשְּׁלִישִׁי בִּהְיֹת הַבֹּקֶר",
         "ולמא כאן פי אליום אלתאלת' באלג'דאה",
         "And when it was on the third day, in the morning"),
        ("וַיְהִי קֹלֹת וּבְרָקִים", "כאנת אצואת וברוק",
         "there were thunderclaps and lightning-flashes"),
        ("וְעָנָן כָּבֵד עַל-הָהָר", "וג'מאם עצ'ים עלי' אלגבל",
         "and a great dense cloud upon the mountain"),
        ("וְקֹל שֹׁפָר חָזָק מְאֹד", "וצות בוק שדיד גדא",
         "and the sound of a horn exceedingly loud"),
        ("וַיֶּחֱרַד כָּל-הָעָם אֲשֶׁר בַּמַּחֲנֶה",
         "פזעג גמיע אלקום אלד'י פי אלעסכר",
         "and all the people who were in the encampment were thrown into turmoil"),
    ],
    17: [
        ("וַיּוֹצֵא מֹשֶׁה אֶת-הָעָם לִקְרַאת הָאֱלֹהִים מִן-הַמַּחֲנֶה",
         "פאכ'רג מוסי' אלקום. ליתלקון אמר אללה מן אלעסכר",
         "And Moses brought out the people to receive the command of God from the encampment"),
        ("וַיִּתְיַצְּבוּ בְּתַחְתִּית הָהָר", "פוקפו אספל אלגבל",
         "and they stood at the foot of the mountain"),
    ],
    18: [
        ("וְהַר סִינַי עָשַׁן כֻּלּוֹ", "וגבל סיני מתדכ'ן כלה",
         "And Mount Sinai was all enveloped in smoke"),
        ("מִפְּנֵי אֲשֶׁר יָרַד עָלָיו יְהוָה בָּאֵשׁ",
         "מן קבל מא תגלא עליה אללה באלנאר",
         "because God had revealed Himself upon it in fire"),
        ("וַיַּעַל עֲשָׁנוֹ כְּעֶשֶׁן הַכִּבְשָׁן", "וצעד דכ'אנה כדכ'אן אלאתון",
         "and its smoke rose like the smoke of a furnace"),
        ("וַיֶּחֱרַד כָּל-הָהָר מְאֹד", "ותזעזע אלגבל גדא",
         "and the mountain shook greatly"),
    ],
    19: [
        ("וַיְהִי קוֹל הַשֹּׁפָר הוֹלֵךְ וְחָזֵק מְאֹד",
         "וכאן צות אלבוק. כל מא מר אשתד גדא",
         "And the sound of the horn — each time it passed — grew louder and louder"),
        ("מֹשֶׁה יְדַבֵּר", "וכאן מוסי' יתכלם", "and Moses would speak"),
        ("וְהָאֱלֹהִים יַעֲנֶנּוּ בְקוֹל", "ואללה יגיבה בצות",
         "and God would answer him with a voice"),
    ],
    20: [
        ("וַיֵּרֶד יְהוָה עַל-הַר סִינַי אֶל-רֹאשׁ הָהָר",
         "אד' תגלא אללה. עלי' גבל סיני אלי' ראסה",
         "When God revealed Himself upon Mount Sinai, to its summit"),
        ("וַיִּקְרָא יְהוָה לְמֹשֶׁה אֶל-רֹאשׁ הָהָר", "פנאדא במוסי' מן ראסה",
         "and He called to Moses from its summit"),
        ("וַיַּעַל מֹשֶׁה", "פצעד", "and he ascended"),
    ],
    21: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה לה", "And God said to him"),
        ("רֵד הָעֵד בָּעָם", "אנזל נאשד אלקום", "Go down, implore the people"),
        ("פֶּן-יֶהֶרְסוּ אֶל-יְהוָה לִרְאוֹת", "כלא יהגמו אלי' נור אללה פינצ'רוה",
         "lest they press forward toward the light of God to behold it"),
        ("וְנָפַל מִמֶּנּוּ רָב", "ויקע מנהם כת'ירין",
         "and many of them fall"),
    ],
    22: [
        ("וְגַם הַכֹּהֲנִים הַנִּגָּשִׁים אֶל-יְהוָה", "ואיצ'א אלאימה. אלמקרבון אלי' אללה",
         "And also the imāms who are brought near to the light of God"),
        ("יִתְקַדָּשׁוּ", "יתקדסון", "shall sanctify themselves"),
        ("פֶּן-יִפְרֹץ בָּהֶם יְהוָה", "ללא ית'לם אללה מנהם",
         "lest God cut them down"),
    ],
    23: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוָה", "פקאל מוסי' ללה", "And Moses said to God"),
        ("לֹא-יוּכַל הָעָם לַעֲלֹת אֶל-הַר סִינָי", "לא יטיק אלקום. אלצעוד אלי' גבל סיני",
         "The people are not able to ascend Mount Sinai"),
        ("כִּי-אַתָּה הַעֵדֹתָה בָּנוּ לֵאמֹר", "לאנך נאשדתנא וקלת",
         "for You implored us, saying"),
        ("הַגְבֵּל אֶת-הָהָר וְקִדַּשְׁתּוֹ", "תכ'ם אלגבל וקדסה",
         "Set a boundary around the mountain and consecrate it"),
    ],
    24: [
        ("וַיֹּאמֶר אֵלָיו יְהוָה לֶךְ-רֵד", "קאל לה אמץ' אנזל",
         "Go, descend"),
        ("וְעָלִיתָ אַתָּה וְאַהֲרֹן עִמָּךְ", "ת'ם אצעד אנת והרון מעך",
         "then ascend — you and Aaron with you"),
        ("וְהַכֹּהֲנִים וְהָעָם אַל-יֶהֶרְסוּ לַעֲלֹת אֶל-יְהוָה",
         "ואלאימה וסאיר אלקום. לא יהגמו. לאלצעוד אלי' נור אללה",
         "but the imāms and the rest of the people shall not press forward to ascend toward the light of God"),
        ("פֶּן-יִפְרָץ-בָּם", "ללא ית'לם מנהם",
         "lest He cut down from among them"),
    ],
    25: [
        ("וַיֵּרֶד מֹשֶׁה אֶל-הָעָם", "פנזל מוסי' אלי' אלקום",
         "And Moses descended to the people"),
        ("וַיֹּאמֶר אֲלֵהֶם", "וקאל להם ד'אלך", "and told them that"),
    ],
}
