"""Hand-authored alignment triples for Shemot chapter 5."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאַחַר", "ובעד ד'אלך", "And after that"),
        ("בָּאוּ מֹשֶׁה וְאַהֲרֹן", "דכ'ל מוסי והרון",
         "Moses and Aaron entered"),
        ("וַיֹּאמְרוּ אֶל-פַּרְעֹה", "וקאלא לפרעון",
         "and said to Pharaoh"),
        ("כֹּה-אָמַר יְהוָה", "כד'א קאל אללה", "Thus says God"),
        ("אֱלֹהֵי יִשְׂרָאֵל", "אלאה אסראיל", "the God of Israel"),
        ("שַׁלַּח אֶת-עַמִּי", "אטלק קומי", "Let my people go"),
        ("וְיָחֹגּוּ לִי", "יחגון לי",
         "that they may celebrate a festival to me"),
        ("בַּמִּדְבָּר", "פי אלבר", "in the wilderness"),
    ],
    2: [
        ("וַיֹּאמֶר פַּרְעֹה", "קאל פרעון", "Pharaoh said"),
        ("מִי יְהוָה", "מן אללה", "Who is God"),
        ("אֲשֶׁר אֶשְׁמַע בְּקֹלוֹ", "חתא אקבל מנה",
         "that I should accept from him"),
        ("לְשַׁלַּח אֶת-יִשְׂרָאֵל", "ואטלק בני אסראיל",
         "and let the sons of Israel go"),
        ("לֹא יָדַעְתִּי אֶת-יְהוָה", "לם אערף אללה",
         "I do not know God"),
        ("וְגַם אֶת-יִשְׂרָאֵל לֹא אֲשַׁלֵּחַ",
         "ולא אטלק בני אסראיל איצ'א",
         "and I will not let the sons of Israel go either"),
    ],
    3: [
        ("וַיֹּאמְרוּ", "קאלו", "They said"),
        ("אֱלֹהֵי הָעִבְרִים", "אלאה אלעבראניין", "The God of the Hebrews"),
        ("נִקְרָא עָלֵינוּ", "ואפאנא אמרה",
         "has caused His decree to come upon us"),
        ("נֵלְכָה נָּא דֶּרֶךְ שְׁלֹשֶׁת יָמִים",
         "נמצ'י אלאן. מסאפה' ת'לאת'ה' איאם",
         "Let us go now a distance of three days"),
        ("בַּמִּדְבָּר", "פי אלבר", "into the wilderness"),
        ("וְנִזְבְּחָה לַיהוָה אֱלֹהֵינוּ", "ונד'בח ללה רבנא",
         "and offer sacrifice to the Lord our God"),
        ("פֶּן-יִפְגָּעֵנוּ בַּדֶּבֶר אוֹ בֶחָרֶב",
         "כילא יפאגינא. בובא או בסיף",
         "lest plague or sword come suddenly upon us"),
    ],
    4: [
        ("וַיֹּאמֶר אֲלֵהֶם מֶלֶךְ מִצְרַיִם", "קאל להמא מלך מצר",
         "The king of Egypt said to them"),
        ("לָמָּה מֹשֶׁה וְאַהֲרֹן", "לם יא מוסי' והרון",
         "Why, Moses and Aaron"),
        ("תַּפְרִיעוּ אֶת-הָעָם", "תגד'באן אלקום",
         "do you distract the people"),
        ("מִמַּעֲשָׂיו", "מן אעמאלהם", "from their works"),
        ("לְכוּ לְסִבְלֹתֵיכֶם", "אמצ'ו לנקלכם", "Go to your burdens"),
    ],
    5: [
        ("וַיֹּאמֶר פַּרְעֹה", "תם קאל פרעון", "And Pharaoh said"),
        ("הֵן-רַבִּים עַתָּה עַם הָאָרֶץ", "אמן כת'רה' אהל אלבלד",
         "Now the people of the land are many"),
        ("וְהִשְׁבַּתֶּם אֹתָם מִסִּבְלֹתָם",
         "חתי' תעטלונהם מן נקלהם",
         "and you would have them rest from their burdens"),
    ],
    6: [
        ("וַיְצַו פַּרְעֹה", "פאמר פרעון", "And Pharaoh commanded"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אליום", "on that day"),
        ("אֶת-הַנֹּגְשִׂים בָּעָם", "גלאוזאת אלקום",
         "the taskmasters of the people"),
        ("וְאֶת-שֹׁטְרָיו", "וערפאהם", "and their overseers"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    7: [
        ("לֹא תֹאסִפוּן", "לא תעאודו", "You shall no longer"),
        ("לָתֵת תֶּבֶן לָעָם", "אן תעטו אלקום תבנא",
         "give the people straw"),
        ("לִלְבֹּן הַלְּבֵנִים", "לילבנון אללבן", "to mold bricks"),
        ("כִּתְמוֹל שִׁלְשֹׁם", "מת'ל אמס ומא קבלה",
         "as yesterday and before"),
        ("הֵם יֵלְכוּ", "הם ימצ'ון", "let them go"),
        ("וְקֹשְׁשׁוּ לָהֶם תֶּבֶן", "ויקמשון להם תבנא",
         "and gather straw for themselves"),
    ],
    8: [
        ("וְאֶת-מַתְכֹּנֶת הַלְּבֵנִים", "וצ'ראיב אללבן",
         "And the quota of bricks"),
        ("אֲשֶׁר הֵם עֹשִׂים", "אלד'י כאנו יצנעון",
         "which they were making"),
        ("תְּמוֹל שִׁלְשֹׁם", "אמס ומא קבלה", "yesterday and before"),
        ("תָּשִׂימוּ עֲלֵיהֶם", "ציירוהא עליהם",
         "set [the same] upon them"),
        ("לֹא תִגְרְעוּ מִמֶּנּוּ", "לא תנקצון מנהא",
         "you shall not reduce from it"),
        ("כִּי-נִרְפִּים הֵם", "לאנהם מרפהון", "For they are idle"),
        ("עַל-כֵּן הֵם צֹעֲקִים", "לד'אלך הם יצרכ'ון",
         "therefore they cry out"),
        ("לֵאמֹר", "ויקולון", "saying"),
        ("נֵלְכָה נִזְבְּחָה לֵאלֹהֵינוּ", "נמצ'י נד'בח לרבנא",
         "Let us go offer sacrifice to our Lord"),
    ],
    9: [
        ("תִּכְבַּד הָעֲבֹדָה", "ית'קל אלעמל", "Let the labor be heavy"),
        ("עַל-הָאֲנָשִׁים", "עלי' אלקום", "upon the people"),
        ("וְיַעֲשׂוּ-בָהּ", "וישתג'לון. בה",
         "and let them be occupied with it"),
        ("וְאַל-יִשְׁעוּ בְּדִבְרֵי-שָׁקֶר",
         "ולא ישתג'לון באמור באטלה",
         "and let them not be occupied with vain matters"),
    ],
    10: [
        ("וַיֵּצְאוּ נֹגְשֵׂי הָעָם", "פכרגו. גלאוזה' אלקום",
         "And the taskmasters of the people went out"),
        ("וְשֹׁטְרָיו", "וערפאהם", "and their overseers"),
        ("וַיֹּאמְרוּ אֶל-הָעָם לֵאמֹר", "וקאלו להם",
         "and said to them"),
        ("כֹּה אָמַר פַּרְעֹה", "כד'א קאל פרעון", "Thus says Pharaoh"),
        ("אֵינֶנִּי נֹתֵן לָכֶם תֶּבֶן", "ליס אעטיכם תבנא",
         "I am giving you no straw"),
    ],
    11: [
        ("אַתֶּם", "אנתם", "You"),
        ("לְכוּ", "אמצ'ו", "go"),
        ("קְחוּ לָכֶם תֶּבֶן", "כ'ד'ו לכם תבנא",
         "take straw for yourselves"),
        ("מֵאֲשֶׁר תִּמְצָאוּ", "מן חית'. תגדו",
         "from where you can find it"),
        (None, "ואעלמו", "And know that"),
        ("כִּי אֵין נִגְרָע מֵעֲבֹדַתְכֶם דָּבָר",
         "אנה ליס ינקץ מן עמלכם שייא",
         "there shall be nothing reduced from your work"),
    ],
    12: [
        ("וַיָּפֶץ הָעָם", "פתבדד אלקום", "And the people scattered"),
        ("בְּכָל-אֶרֶץ מִצְרָיִם", "פי גמיע בלד מצר",
         "throughout all the land of Egypt"),
        ("לְקֹשֵׁשׁ קַשׁ לַתֶּבֶן", "ליקמשו קשא לאלתבן",
         "to gather stubble for straw"),
    ],
    13: [
        ("וְהַנֹּגְשִׂים אָצִים", "ואלגלאוזה מלחון",
         "And the taskmasters pressed [them]"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("כַּלּוּ מַעֲשֵׂיכֶם", "כמלו עמלכם", "Finish your work"),
        ("דְּבַר-יוֹם בְּיוֹמוֹ", "אמר יום ביום",
         "the matter of each day, on its day"),
        ("כַּאֲשֶׁר בִּהְיוֹת הַתֶּבֶן", "כמא כאן פי וקת אעטא אלתבן",
         "just as it was when straw was given"),
    ],
    14: [
        ("וַיֻּכּוּ שֹׁטְרֵי בְּנֵי יִשְׂרָאֵל אֲשֶׁר-שָׂמוּ עֲלֵהֶם נֹגְשֵׂי פַרְעֹה",
         "פצ'רב ערפא בני אסראיל. אלד'י ולאהם עליהם. גלאוזה' פרעון",
         "And the overseers of the sons of Israel — whom Pharaoh's taskmasters had set over them — they beat"),
        ("לֵאמֹר", "וקאלו להם", "and said to them"),
        ("מַדּוּעַ", "מא באלכם", "What is the matter with you"),
        ("לֹא כִלִּיתֶם חָקְכֶם", "לם תכמלו צ'ראיבכם",
         "that you have not finished your quotas"),
        ("לִלְבֹּן", "אן תלבנון אללבן", "to mold bricks"),
        ("כִּתְמוֹל שִׁלְשֹׁם", "מת'ל אמס ומא קבלה",
         "as yesterday and before"),
        ("גַּם-תְּמוֹל גַּם-הַיּוֹם", "אמס ואליום",
         "both yesterday and today"),
    ],
    15: [
        ("וַיָּבֹאוּ שֹׁטְרֵי בְּנֵי יִשְׂרָאֵל", "פגאו ערפא בני אסראיל",
         "And the overseers of the sons of Israel came"),
        ("וַיִּצְעֲקוּ אֶל-פַּרְעֹה", "ואסתג'אתו אלי' פרעון",
         "and cried out to Pharaoh"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("לָמָּה תַעֲשֶׂה כֹה לַעֲבָדֶיךָ", "לם תצנע כד'א עבידך",
         "Why do you act thus toward your servants"),
    ],
    16: [
        ("תֶּבֶן אֵין נִתָּן לַעֲבָדֶיךָ", "תבן לם ידפע לעבידך",
         "No straw is supplied to your servants"),
        ("וּלְבֵנִים אֹמְרִים לָנוּ עֲשׂוּ",
         "ויקולון לנא אצ'רבו לבנא",
         "yet they are saying to us: Make bricks"),
        ("וְהִנֵּה עֲבָדֶיךָ מֻכִּים", "והוד'א עבידך. מצ'רובין",
         "And behold, your servants are beaten"),
        ("וְחָטָאת עַמֶּךָ", "ממא יכ'טי עליהם קומך",
         "because your people sin against them"),
    ],
    17: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("נִרְפִּים אַתֶּם נִרְפִּים", "אנתם מרפהון",
         "You are idle, idle"),
        ("עַל-כֵּן אַתֶּם אֹמְרִים", "לד'אלך תקולון",
         "therefore you say"),
        ("נֵלְכָה נִזְבְּחָה לַיהוָה", "נמצ'י נד'בח לרבנא",
         "Let us go and offer sacrifice to our Lord"),
    ],
    18: [
        ("וְעַתָּה", "ואלאן", "And now"),
        ("לְכוּ", "אמצ'ו", "go"),
        ("עִבְדוּ", "אעמלו", "labor"),
        ("וְתֶבֶן לֹא-יִנָּתֵן לָכֶם", "ותבן לא יטלק לכם",
         "and no straw shall be given to you"),
        ("וְתֹכֶן לְבֵנִים תִּתֵּנוּ", "וצ'ראיבכם תופון",
         "and your quotas you shall complete"),
    ],
    19: [
        ("וַיִּרְאוּ שֹׁטְרֵי בְנֵי-יִשְׂרָאֵל", "ונצ'ר ערפא בני אסראיל",
         "And the overseers of the sons of Israel saw"),
        ("אֹתָם--בְּרָע", "בשר", "[themselves] in evil"),
        ("לֵאמֹר", "קאילין", "saying"),
        ("לֹא-תִגְרְעוּ מִלִּבְנֵיכֶם", "לא תנקצו מן לבנכם",
         "You shall not reduce from your bricks"),
        ("דְּבַר-יוֹם בְּיוֹמוֹ", "אמר יום ביום",
         "the matter of each day, on its day"),
    ],
    20: [
        ("וַיִּפְגְּעוּ אֶת-מֹשֶׁה וְאֶת-אַהֲרֹן",
         "פפאגו מוסי' והרון", "And they encountered Moses and Aaron"),
        ("נִצָּבִים לִקְרָאתָם", "ואקפין תלקאהם",
         "standing to meet them"),
        ("בְּצֵאתָם מֵאֵת פַּרְעֹה",
         "ענד כ'רוגהם מן ענד פרעון",
         "at their coming out from before Pharaoh"),
    ],
    21: [
        ("וַיֹּאמְרוּ אֲלֵהֶם", "פקאלו להמא", "And they said to them"),
        ("יֵרֶא יְהוָה עֲלֵיכֶם", "ינצ'ר אללה עליכם",
         "May God look upon you"),
        ("וְיִשְׁפֹּט", "ויחכם", "and judge"),
        ("אֲשֶׁר הִבְאַשְׁתֶּם אֶת-רֵיחֵנוּ", "כמא אפסדתמא חאלנא",
         "for you have ruined our condition"),
        ("בְּעֵינֵי פַרְעֹה", "ענד פרעון", "before Pharaoh"),
        ("וּבְעֵינֵי עֲבָדָיו", "וענד קואדה", "and before his officers"),
        ("לָתֶת-חֶרֶב בְּיָדָם", "חתא לו אן סיפא פי אידיהם",
         "so that, were a sword in their hands"),
        ("לְהָרְגֵנוּ", "לקתלונא", "they would kill us"),
    ],
    22: [
        ("וַיָּשָׁב מֹשֶׁה אֶל-יְהוָה", "פרגע מוסי'. אלי' אללה",
         "And Moses returned to God"),
        ("וַיֹּאמַר", "וקאל", "and said"),
        ("אֲדֹנָי", "יא רבי", "O my Lord"),
        ("לָמָה הֲרֵעֹתָה לָעָם הַזֶּה", "לם אבלית הולאי אלקום",
         "why have You brought trial upon this people"),
        ("לָמָּה זֶּה שְׁלַחְתָּנִי", "ולמא ד'א בעת'ת בי",
         "And to what end have You sent me"),
    ],
    23: [
        ("וּמֵאָז בָּאתִי אֶל-פַּרְעֹה",
         "ומן חין דכ'לת אלי' פרעון",
         "For from the time I went in to Pharaoh"),
        ("לְדַבֵּר בִּשְׁמֶךָ", "אכ'אטבה באסמך",
         "to speak with him in Your name"),
        ("הֵרַע לָעָם הַזֶּה", "אסא אליהם",
         "he has dealt evil with them"),
        ("וְהַצֵּל לֹא-הִצַּלְתָּ אֶת-עַמֶּךָ",
         "ולם תכ'לצהם מן ד'אלך",
         "and You have not rescued them from this"),
    ],
}
