"""Hand-authored alignment triples for Shemot chapter 32."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיַּרְא הָעָם כִּי-בֹשֵׁשׁ מֹשֶׁה לָרֶדֶת מִן-הָהָר",
         "ולמא ראי' אלקום. אן מוסי' קד אבטא אן ינזל מן אלגבל",
         "And when the people saw that Moses had delayed in coming down from the mountain,"),
        ("וַיִּקָּהֵל הָעָם עַל-אַהֲרֹן", "תגווק אלקום עלי' הרון",
         "the people pressed upon Aaron,"),
        ("וַיֹּאמְרוּ אֵלָיו", "וקאלו לה", "and said to him:"),
        ("קוּם עֲשֵׂה-לָנוּ אֱלֹהִים אֲשֶׁר יֵלְכוּ לְפָנֵינוּ",
         "קם אצנע לנא מעבודא. יסיר בין ידינא",
         "Rise, make us an object of worship that shall go before us —"),
        ("כִּי-זֶה מֹשֶׁה הָאִישׁ אֲשֶׁר הֶעֱלָנוּ מֵאֶרֶץ מִצְרַיִם",
         "פאן ד'אלך אלרגל מוסי'. אלד'י אצעדנא מן בלד מצר",
         "for that man Moses, who brought us up from the land of Egypt,"),
        ("לֹא יָדַעְנוּ מֶה-הָיָה לוֹ", "לם נעלם מא כאן מן אמרה",
         "we do not know what has become of his affair.'"),
    ],
    2: [
        ("וַיֹּאמֶר אֲלֵהֶם אַהֲרֹן", "פקאל להם הרון",
         "And Aaron said to them:"),
        ("פָּרְקוּ נִזְמֵי הַזָּהָב", "פכו אשנאף אלד'הב",
         "Remove the earrings of gold"),
        ("אֲשֶׁר בְּאָזְנֵי נְשֵׁיכֶם בְּנֵיכֶם וּבְנֹתֵיכֶם",
         "אלתי פי אד'אן נסאכם. בניכם ובנאתכם",
         "which are in the ears of your wives, your sons, and your daughters,"),
        ("וְהָבִיאוּ אֵלָי", "ואיתוני בהא", "and bring them to me.'"),
    ],
    3: [
        ("וַיִּתְפָּרְקוּ כָּל-הָעָם אֶת-נִזְמֵי הַזָּהָב אֲשֶׁר בְּאָזְנֵיהֶם",
         "פפך גמיע אלקום. אשנאף אלדהב אלתי פי אד'אנהם",
         "And all the people removed the earrings of gold which were in their ears,"),
        ("וַיָּבִיאוּ אֶל-אַהֲרֹן", "ואתו בהא אלי' הרון",
         "and brought them to Aaron."),
    ],
    4: [
        ("וַיִּקַּח מִיָּדָם", "פאכ'ד' ד'אלך מנהם",
         "And he took that from them,"),
        ("וַיָּצַר אֹתוֹ בַּחֶרֶט", "ואמר מן צוורה בקאלב",
         "and ordered one to shape it with a mold,"),
        ("וַיַּעֲשֵׂהוּ עֵגֶל מַסֵּכָה", "וצנעה עגלא מסבוכא",
         "and made it into a molten calf."),
        ("וַיֹּאמְרוּ", "וקאלו", "And they said:"),
        ("אֵלֶּה אֱלֹהֶיךָ יִשְׂרָאֵל", "הד'א רבך יא אל אסראיל",
         "This is your lord, O house of Israel,"),
        ("אֲשֶׁר הֶעֱלוּךָ מֵאֶרֶץ מִצְרָיִם", "אלד'י אצעדך מן בלד מצר",
         "who brought you up from the land of Egypt.'"),
    ],
    5: [
        ("וַיַּרְא אַהֲרֹן", "פלמא ראא הרון ד'אלך",
         "And when Aaron saw that,"),
        ("וַיִּבֶן מִזְבֵּחַ לְפָנָיו", "בנא מד'בחא בין ידיה",
         "he built an altar before it,"),
        ("וַיִּקְרָא אַהֲרֹן וַיֹּאמַר חַג לַיהוָה מָחָר",
         "ונאדא וקאל. חג ללה ג'דא",
         "and called out and said: 'A festival to God tomorrow.'"),
    ],
    6: [
        ("וַיַּשְׁכִּימוּ מִמָּחֳרָת", "פאדלגו באלג'דאה",
         "And they rose early in the morning,"),
        ("וַיַּעֲלוּ עֹלֹת", "וקרבו צואעדא", "and offered up burnt-offerings,"),
        ("וַיַּגִּשׁוּ שְׁלָמִים", "וד'בחו ד'באיח סלאמה",
         "and slaughtered peace-offerings;"),
        ("וַיֵּשֶׁב הָעָם לֶאֱכֹל וְשָׁתוֹ", "וגלס אלקום ליאכלו וישרבו",
         "and the people sat down to eat and to drink,"),
        ("וַיָּקֻמוּ לְצַחֵק", "וקאמו לילעבו", "and rose up to play."),
    ],
    7: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי",
         "And God said to Moses:"),
        ("לֶךְ-רֵד", "אמץ' אנזל", "Go, descend —"),
        ("כִּי שִׁחֵת עַמְּךָ", "פאן קד אפסד קומך",
         "for your people"),
        ("אֲשֶׁר הֶעֱלֵיתָ מֵאֶרֶץ מִצְרָיִם",
         "אלד'ין אצעדתהם מן בלד מצר",
         "whom you brought up from the land of Egypt, have corrupted themselves.'"),
    ],
    8: [
        ("סָרוּ מַהֵר מִן-הַדֶּרֶךְ אֲשֶׁר צִוִּיתִם",
         "זאלו סריעא. ען אלטריק אלד'י אמרתהם בה",
         "'They have turned aside swiftly from the way which I commanded them;"),
        ("עָשׂוּ לָהֶם עֵגֶל מַסֵּכָה", "וצנעו להם עגלא מסבוכא",
         "and they made themselves a molten calf,"),
        ("וַיִּשְׁתַּחֲווּ-לוֹ וַיִּזְבְּחוּ-לוֹ", "וסגדו לה וד'בחו לה",
         "and bowed down to it and slaughtered to it,"),
        ("וַיֹּאמְרוּ", "וקאלו", "and said:"),
        ("אֵלֶּה אֱלֹהֶיךָ יִשְׂרָאֵל אֲשֶׁר הֶעֱלוּךָ מֵאֶרֶץ מִצְרָיִם",
         "הד'א רבך יא אל אסראיל. אלד'י אצעדך מן בלד מצר",
         "This is your lord, O house of Israel, who brought you up from the land of Egypt.'"),
    ],
    9: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה למוסי",
         "And God said to Moses:"),
        ("רָאִיתִי אֶת-הָעָם הַזֶּה", "קד עלמת. אן הולאי אלקום",
         "'I have known that these people"),
        ("וְהִנֵּה עַם-קְשֵׁה-עֹרֶף הוּא", "צעאב אלרקאב",
         "are stiff of neck.'"),
    ],
    10: [
        ("וְעַתָּה הַנִּיחָה לִּי", "ואלאן אן כפאת ען אלתשפע",
         "'And now, if you refrain from interceding,"),
        ("וְיִחַר-אַפִּי בָהֶם וַאֲכַלֵּם",
         "אשתד ג'צ'בי עליהם ואפניתהם",
         "My anger shall intensify against them and I shall destroy them;"),
        ("וְאֶעֱשֶׂה אוֹתְךָ לְגוֹי גָּדוֹל",
         "ואצנע מנך אמה ]עט'ימה] עצ'ימה",
         "and I will make of you a great nation.'"),
    ],
    11: [
        ("וַיְחַל מֹשֶׁה אֶת-פְּנֵי יְהוָה אֱלֹהָיו",
         "פאבתהל מוסי' אלי' אללה רבה",
         "And Moses supplicated before God his Lord,"),
        ("וַיֹּאמֶר לָמָה יְהוָה יֶחֱרֶה אַפְּךָ בְּעַמֶּךָ",
         "וקאל יא רב. לא ישתד ג'צ'בך עלי' קומך",
         "and said: 'O Lord, let not Your anger intensify against Your people,"),
        ("אֲשֶׁר הוֹצֵאתָ מֵאֶרֶץ מִצְרַיִם",
         "אלד'י אכ'רגתהם מן בלד מצר",
         "whom You brought out from the land of Egypt"),
        ("בְּכֹחַ גָּדוֹל וּבְיָד חֲזָקָה",
         "בקווה ]עט'ימה] ]עט'ימה] עצ'ימה וביד שדידה",
         "with great power and with a mighty hand —'"),
    ],
    12: [
        ("לָמָּה יֹאמְרוּ מִצְרַיִם לֵאמֹר",
         "ולא יקול אלמצריון",
         "'— lest the Egyptians say"),
        ("בְּרָעָה הוֹצִיאָם לַהֲרֹג אֹתָם בֶּהָרִים",
         "אנה אכ'רגהם בשר ליקתלהם פי מא בין אלגבאל",
         "that He brought them out with evil intent, to kill them amid the mountains"),
        ("וּלְכַלֹּתָם מֵעַל פְּנֵי הָאֲדָמָה",
         "ויפניהם ען וגה אלארץ'",
         "and to destroy them from the face of the earth."),
        ("שׁוּב מֵחֲרוֹן אַפֶּךָ", "ארגע ען שדה' ג'צ'בך",
         "Turn back from the fierceness of Your anger,"),
        ("וְהִנָּחֵם עַל-הָרָעָה לְעַמֶּךָ",
         "ואצפח ען אלבלייה לקומך",
         "and pardon the affliction for Your people.'"),
    ],
    13: [
        ("זְכֹר לְאַבְרָהָם לְיִצְחָק וּלְיִשְׂרָאֵל עֲבָדֶיךָ",
         "ואד'כר לאברהים ויצחק ואסראיל עבידך",
         "'And remember Abraham, Isaac, and Israel, Your servants,"),
        ("אֲשֶׁר נִשְׁבַּעְתָּ לָהֶם בָּךְ",
         "אלד'י אקסמת להם באסמך",
         "to whom You swore by Your name,"),
        ("וַתְּדַבֵּר אֲלֵהֶם אַרְבֶּה אֶת-זַרְעֲכֶם כְּכוֹכְבֵי הַשָּׁמָיִם",
         "וקלת להם. אכת'ר נסלכם. ככואכב אלסמא",
         "and said to them: I will multiply your offspring like the stars of the sky;"),
        ("וְכָל-הָאָרֶץ הַזֹּאת אֲשֶׁר אָמַרְתִּי אֶתֵּן לְזַרְעֲכֶם",
         "וגמיע אלבלד אלד'י אקסמת. אעטיה לנסלכם",
         "and all the land which I have sworn I will give to your offspring,"),
        ("וְנָחֲלוּ לְעֹלָם", "ויחוזונה אלי' אלדהר",
         "and they shall possess it forever.'"),
    ],
    14: [
        ("וַיִּנָּחֶם יְהוָה עַל-הָרָעָה", "פצפח אללה. ען אלבלייה",
         "And God pardoned the affliction"),
        ("אֲשֶׁר דִּבֶּר לַעֲשׂוֹת לְעַמּוֹ",
         "אלתי קאל אן יחלהא בקומה",
         "which He had said He would bring upon His people."),
    ],
    15: [
        ("וַיִּפֶן וַיֵּרֶד מֹשֶׁה מִן-הָהָר",
         "ת'ם ולא מוסי' ונזל מן אלגבל",
         "Then Moses turned and descended from the mountain,"),
        ("וּשְׁנֵי לֻחֹת הָעֵדֻת בְּיָדוֹ",
         "ולוחי אלשהאדה בידה",
         "with the two tablets of the testimony in his hand —"),
        ("לֻחֹת כְּתֻבִים מִשְּׁנֵי עֶבְרֵיהֶם--מִזֶּה וּמִזֶּה הֵם כְּתֻבִים",
         "לוחין מכתובין מן גאנביהמא. מן דאכ'ל ומן כ'ארג",
         "the tablets written on both their sides, from within and from without."),
    ],
    16: [
        ("וְהַלֻּחֹת--מַעֲשֵׂה אֱלֹהִים הֵמָּה",
         "ואללוחין המא צנעה' אללה",
         "And the two tablets — they were the workmanship of God,"),
        ("וְהַמִּכְתָּב מִכְתַּב אֱלֹהִים הוּא",
         "ואלכתאב הו כתאב אללה",
         "and the writing was the writing of God,"),
        ("חָרוּת עַל-הַלֻּחֹת", "מחפור עליהמא", "engraved upon them."),
    ],
    17: [
        ("וַיִּשְׁמַע יְהוֹשֻׁעַ אֶת-קוֹל הָעָם בְּרֵעֹה",
         "פסמע יהושע. צות אלקום פי תגליבהם",
         "And Joshua heard the sound of the people in their clamor,"),
        ("וַיֹּאמֶר אֶל-מֹשֶׁה", "פקאל למוסי'", "and said to Moses:"),
        ("קוֹל מִלְחָמָה בַּמַּחֲנֶה", "צות חרב פי אלעסכר",
         "'There is a sound of war in the camp.'"),
    ],
    18: [
        ("וַיֹּאמֶר", "וקאל", "And Moses said:"),
        ("אֵין קוֹל עֲנוֹת גְּבוּרָה", "ליס הו צות ידל עלי' צ'פר",
         "'It is not a sound that indicates victory,"),
        ("וְאֵין קוֹל עֲנוֹת חֲלוּשָׁה", "ולא צות ידל עלי' הזימה",
         "nor a sound that indicates defeat —"),
        ("קוֹל עַנּוֹת אָנֹכִי שֹׁמֵעַ", "בל צ'וצ'א. אנא סאמע",
         "rather, it is a tumult that I am hearing.'"),
    ],
    19: [
        ("וַיְהִי כַּאֲשֶׁר קָרַב אֶל-הַמַּחֲנֶה",
         "פלמא קרב מן אלעסכר",
         "And when he drew near to the camp,"),
        ("וַיַּרְא אֶת-הָעֵגֶל וּמְחֹלֹת", "ראי' אלעגל וטבול",
         "he saw the calf and the drums;"),
        ("וַיִּחַר-אַף מֹשֶׁה", "פאשתד ג'צ'ב מוסי",
         "and Moses' anger intensified,"),
        ("וַיַּשְׁלֵךְ מִיָּדָו אֶת-הַלֻּחֹת",
         "וטרח אללוחין מן ידיה",
         "and he threw the tablets from his hands"),
        ("וַיְשַׁבֵּר אֹתָם תַּחַת הָהָר",
         "וכסרהמא אספל אלגבל",
         "and shattered them at the foot of the mountain."),
    ],
    20: [
        ("וַיִּקַּח אֶת-הָעֵגֶל אֲשֶׁר עָשׂוּ וַיִּשְׂרֹף בָּאֵשׁ",
         "פאכ'ד' אלעגל אלד'י צנעו ואחרקה באלנאר",
         "And he took the calf which they had made, and burned it with fire,"),
        ("וַיִּטְחַן עַד אֲשֶׁר-דָּק",
         "וברדה באלמברד אלי' אן דק",
         "and ground it with the file until it was fine;"),
        ("וַיִּזֶר עַל-פְּנֵי הַמַּיִם", "וד'ראה עלי' וגה אלמא",
         "and he scattered it upon the face of the water,"),
        ("וַיַּשְׁקְ אֶת-בְּנֵי יִשְׂרָאֵל", "וסקא בני אסראיל אבאחה",
         "and made the sons of Israel drink it freely."),
    ],
    21: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן", "וקאל מוסי להרון",
         "And Moses said to Aaron:"),
        ("מֶה-עָשָׂה לְךָ הָעָם הַזֶּה", "מא צנע בך הולאי אלקום",
         "'What did these people do to you,"),
        ("כִּי-הֵבֵאתָ עָלָיו חֲטָאָה גְדֹלָה",
         "אד' גלבת עליהם כ'טייה ]עט'ימה] עצ'ימה",
         "that you brought upon them a great sin?'"),
    ],
    22: [
        ("וַיֹּאמֶר אַהֲרֹן", "קאל", "He said:"),
        ("אַל-יִחַר אַף אֲדֹנִי", "לא ישתד ג'צ'ב סיידי",
         "'Let not my lord's anger intensify —"),
        ("אַתָּה יָדַעְתָּ אֶת-הָעָם", "אנת עאלם באלקום",
         "you know the people,"),
        ("כִּי בְרָע הוּא", "אנהם שרירין", "that they are prone to evil.'"),
    ],
    23: [
        ("וַיֹּאמְרוּ לִי--עֲשֵׂה-לָנוּ אֱלֹהִים אֲשֶׁר יֵלְכוּ לְפָנֵינוּ",
         "פקאלו לי אצנע לנא מעבודא. יסיר בין ידינא",
         "'They said to me: Make us an object of worship that shall go before us —"),
        ("כִּי-זֶה מֹשֶׁה הָאִישׁ אֲשֶׁר הֶעֱלָנוּ מֵאֶרֶץ מִצְרַיִם",
         "פאן ד'אלך אלרגל מוסי'. אלד'י אצעדנא מן בלד מצר",
         "for that man Moses, who brought us up from the land of Egypt,"),
        ("לֹא יָדַעְנוּ מֶה-הָיָה לוֹ", "לם נעלם מא כאן מן אמרה",
         "we do not know what has become of his affair.'"),
    ],
    24: [
        ("וָאֹמַר לָהֶם לְמִי זָהָב", "פקלת להם למן ד'הב",
         "'So I said to them: Look, who has gold?"),
        ("וַיִּתְּנוּ-לִי", "פפכוה ואתוני בה",
         "bring it to me. And they removed it and gave it to me,"),
        ("וָאַשְׁלִכֵהוּ בָאֵשׁ", "פטרחתה פי אלנאר",
         "and I threw it into the fire,"),
        ("וַיֵּצֵא הָעֵגֶל הַזֶּה", "וכ'רג הד'י אלעגל",
         "and this calf came out.'"),
    ],
    25: [
        ("וַיַּרְא מֹשֶׁה אֶת-הָעָם כִּי פָרֻעַ הוּא",
         "פלמא ראי מוסי אלקום. אנהם מכשופין",
         "And when Moses saw the people — that they were exposed,"),
        ("כִּי-פְרָעֹה אַהֲרֹן לְשִׁמְצָה בְּקָמֵיהֶם",
         "אד' כשף הרון. ד'וי אלשין מן מקאומיהם",
         "since Aaron had laid bare those of standing among their adversaries —"),
    ],
    26: [
        ("וַיַּעֲמֹד מֹשֶׁה בְּשַׁעַר הַמַּחֲנֶה",
         "פוקף מוסי בבאב אלעסכר",
         "Moses stood at the gate of the camp,"),
        ("וַיֹּאמֶר מִי לַיהוָה אֵלָי",
         "וקאל. מן ללה יקבל אליי",
         "and said: 'Who is for God — let him come to me.'"),
        ("וַיֵּאָסְפוּ אֵלָיו כָּל-בְּנֵי לֵוִי",
         "פאגתמע אליה גמיע בני לוי",
         "And all the sons of Levi gathered to him."),
    ],
    27: [
        ("וַיֹּאמֶר לָהֶם", "פקאל להם", "And he said to them:"),
        ("כֹּה-אָמַר יְהוָה אֱלֹהֵי יִשְׂרָאֵל",
         "כד'א קאל אללה אלאה אסראיל",
         "'Thus says God, the God of Israel:"),
        ("שִׂימוּ אִישׁ-חַרְבּוֹ עַל-יְרֵכוֹ",
         "יתקלד כל רגל מנכם סיפה",
         "Let every man among you gird his sword,"),
        ("עִבְרוּ וָשׁוּבוּ מִשַּׁעַר לָשַׁעַר בַּמַּחֲנֶה",
         "ואמצ'ו וארגעו. מן באב אלי' באב פי אלעסכר",
         "and go and return from gate to gate within the camp,"),
        ("וְהִרְגוּ אִישׁ-אֶת-אָחִיו וְאִישׁ אֶת-רֵעֵהוּ וְאִישׁ אֶת-קְרֹבוֹ",
         "ויקתל כל רגל. חתי' אכ'יה וצאחבה וקריבה",
         "and let every man slay even his brother and his companion and his kinsman.'"),
    ],
    28: [
        ("וַיַּעֲשׂוּ בְנֵי-לֵוִי כִּדְבַר מֹשֶׁה",
         "פצנעו בני לוי כמא אמרהם מוסי'",
         "And the sons of Levi did as Moses had commanded them;"),
        ("וַיִּפֹּל מִן-הָעָם בַּיּוֹם הַהוּא כִּשְׁלֹשֶׁת אַלְפֵי אִישׁ",
         "פוקע מן אלקום פי ד'אלך אליום. שביה בת'לאת'ה' אלאף רגל",
         "and there fell of the people on that day approximately three thousand men."),
    ],
    29: [
        ("וַיֹּאמֶר מֹשֶׁה", "פקאל להם מוסי'", "And Moses said to them:"),
        ("מִלְאוּ יֶדְכֶם הַיּוֹם לַיהוָה",
         "אכמלו ואגבכם אליום ללה",
         "'Fulfill your obligation today to God —"),
        ("כִּי אִישׁ בִּבְנוֹ וּבְאָחִיו",
         "כל רגל חתי' באבנה ואכ'יה",
         "every man even against his son and his brother —"),
        ("וְלָתֵת עֲלֵיכֶם הַיּוֹם בְּרָכָה",
         "ותחל עליכם אליום ברכה",
         "and may there come upon you today a blessing.'"),
    ],
    30: [
        ("וַיְהִי מִמָּחֳרָת", "ולמא כאן מן ג'ד",
         "And it was on the morrow,"),
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָעָם", "קאל מוסי' לאלקום",
         "Moses said to the people:"),
        ("אַתֶּם חֲטָאתֶם חֲטָאָה גְדֹלָה",
         "אנתם אכ'טאתם כ'טייה ]עט'ימה] עצ'ימה",
         "'You have committed a great sin."),
        ("וְעַתָּה אֶעֱלֶה אֶל-יְהוָה", "ואלאן אצעד אלי' אללה",
         "And now I will go up to God —"),
        ("אוּלַי אֲכַפְּרָה בְּעַד חַטַּאתְכֶם",
         "לעל אסתג'פר ען כ'טייתכם",
         "perhaps I may seek forgiveness for your sin.'"),
    ],
    31: [
        ("וַיָּשָׁב מֹשֶׁה אֶל-יְהוָה", "פרגע מוסי'. אלי' אללה",
         "And Moses returned to God"),
        ("וַיֹּאמַר", "וקאל", "and said:"),
        ("אָנָּא חָטָא הָעָם הַזֶּה חֲטָאָה גְדֹלָה",
         "יא רב. קד אכ'טא הולאי אלקום כ'טייה ]עט'ימה] עצ'ימה",
         "'O Lord, these people have indeed committed a great sin,"),
        ("וַיַּעֲשׂוּ לָהֶם אֱלֹהֵי זָהָב",
         "וצנעו להם מעבודא מן ד'הב",
         "and made for themselves an object of worship of gold.'"),
    ],
    32: [
        ("וְעַתָּה אִם-תִּשָּׂא חַטָּאתָם", "ואלאן אן ג'פרת כ'טייתהם",
         "'And now, if You will forgive their sin —"),
        ("וְאִם-אַיִן--מְחֵנִי נָא מִסִּפְרְךָ אֲשֶׁר כָּתָבְתָּ",
         "ואלא פאמחיני. מן דיואנך אלד'י כתבתה פאסתריח",
         "and if not, then erase me from Your register which You have written, and I shall have rest.'"),
    ],
    33: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל לה אללה",
         "And God said to him:"),
        ("מִי אֲשֶׁר חָטָא-לִי אֶמְחֶנּוּ מִסִּפְרִי",
         "אלד'י אכ'טא לי. אמחוה מן דיואני",
         "'Whoever has sinned against Me — him I shall erase from My register.'"),
    ],
    34: [
        ("וְעַתָּה לֵךְ נְחֵה אֶת-הָעָם",
         "ואלאן פאמץ' סייר אלקום",
         "'And now, go — lead the people"),
        ("אֶל אֲשֶׁר-דִּבַּרְתִּי לָךְ",
         "אלי' אלמוצ'ע אלד'י קלת לך",
         "to the place of which I told you."),
        ("הִנֵּה מַלְאָכִי יֵלֵךְ לְפָנֶיךָ",
         "הוד'י מלכי יסיר בין ידיך",
         "Behold, My angel shall go before you;"),
        ("וּבְיוֹם פָּקְדִי וּפָקַדְתִּי עֲלֵהֶם חַטָּאתָם",
         "ופי יום מטאלבתי. אטאלבהם בכ'טאיאהם",
         "and on the day of My reckoning, I shall call them to account for their sins.'"),
    ],
    35: [
        ("וַיִּגֹּף יְהוָה אֶת-הָעָם",
         "פצדם אללה מן אלקום",
         "And God struck among the people"),
        ("עַל אֲשֶׁר עָשׂוּ אֶת-הָעֵגֶל",
         "עלי' מא אצטנעו אלעגל",
         "on account of what they had done — the calf"),
        ("אֲשֶׁר עָשָׂה אַהֲרֹן", "אלד'י צנעה הרון",
         "which Aaron had made."),
    ],
}
