"""Hand-authored alignment triples for Shemot chapter 37."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיַּעַשׂ בְּצַלְאֵל אֶת-הָאָרֹן עֲצֵי שִׁטִּים",
         "וצנע בצלאל אלצנדוק מן כ'שב אלסנט",
         "And Bezalel made the ark from acacia wood"),
        ("אַמָּתַיִם וָחֵצִי אָרְכּוֹ", "דראעין ונצף טולה",
         "two cubits and a half its length"),
        ("וְאַמָּה וָחֵצִי רָחְבּוֹ", "וד'ראע ונצף ערצ'ה",
         "and a cubit and a half its width"),
        ("וְאַמָּה וָחֵצִי קֹמָתוֹ", "וד'ראע ונצף סמכה",
         "and a cubit and a half its height"),
    ],
    2: [
        ("וַיְצַפֵּהוּ זָהָב טָהוֹר מִבַּיִת וּמִחוּץ",
         "וג'שאה בד'הב כ'אלץ. מן דאכ'ל ומן כ'ארג",
         "And he overlaid it with pure gold, from within and from without"),
        ("וַיַּעַשׂ לוֹ זֵר זָהָב סָבִיב",
         "וצנע לה. זיגא מן ד'הב מסתדירא",
         "and he made for it a border of gold, encircling all around"),
    ],
    3: [
        ("וַיִּצֹק לוֹ אַרְבַּע טַבְּעֹת זָהָב עַל אַרְבַּע פַּעֲמֹתָיו",
         "וצאג' לה ארבע חלק מן ד'הב. וגעלהא פי ארבע גהאתה",
         "And he cast for it four rings of gold, and set them on its four sides"),
        ("שְׁתֵּי טַבָּעֹת עַל-צַלְעוֹ הָאֶחָת", "חלקתין מן גאנבה אלואחד",
         "two rings on one side of it"),
        ("וּשְׁתֵּי טַבָּעֹת עַל-צַלְעוֹ הַשֵּׁנִית",
         "וחלקתין מן גאנבה אלכת'אני",
         "and two rings on the other side"),
    ],
    4: [
        ("וַיַּעַשׂ בַּדֵּי עֲצֵי שִׁטִּים", "וצנע דהוקא מן כ'שב אלסנט",
         "And he made carrying-poles from acacia wood"),
        ("וַיְצַף אֹתָם זָהָב", "וגשאהא בד'הב", "and overlaid them with gold"),
    ],
    5: [
        ("וַיָּבֵא אֶת-הַבַּדִּים בַּטַּבָּעֹת עַל צַלְעֹת הָאָרֹן",
         "ואדכ'ל אלדהוק פי אלחלק. עלי' גאנבי אלצנדוק",
         "And he inserted the poles into the rings, on the two sides of the ark"),
        ("לָשֵׂאת אֶת-הָאָרֹן", "ליחמל בהא", "so that it might be carried by them"),
    ],
    6: [
        ("וַיַּעַשׂ כַּפֹּרֶת זָהָב טָהוֹר",
         "וצנע ג'שאא מן ד'הב כ'אלץ",
         "And he made a cover of pure gold"),
        ("אַמָּתַיִם וָחֵצִי אָרְכָּהּ", "ד'ראעין ונצף טולה",
         "two cubits and a half its length"),
        ("וְאַמָּה וָחֵצִי רָחְבָּהּ", "וד'ראע ונצף ערצה",
         "and a cubit and a half its width"),
    ],
    7: [
        ("וַיַּעַשׂ שְׁנֵי כְרֻבִים זָהָב מִקְשָׁה עָשָׂה אֹתָם",
         "וצנע כרובין מן ד'הב. מצמתין צנעהמא",
         "And he made two cherubim of gold — solid he made them"),
        ("מִשְּׁנֵי קְצוֹת הַכַּפֹּרֶת", "מן טרפי אלג'שא",
         "from the two ends of the cover"),
    ],
    8: [
        ("כְּרוּב-אֶחָד מִקָּצָה מִזֶּה", "אחדהמא מן גאנבה אלאימן",
         "One of them from its right side"),
        ("וּכְרוּב-אֶחָד מִקָּצָה מִזֶּה", "ואלאכ'ר מן גאנבה אלאיסר",
         "and the other from its left side"),
        ("מִן-הַכַּפֹּרֶת עָשָׂה אֶת-הַכְּרֻבִים מִשְּׁנֵי קצוותו (קְצוֹתָיו)",
         "מן נפס אלג'שא. צנעהמא מן טרפיה",
         "from the body of the cover itself he made them, from its two ends"),
    ],
    9: [
        ("וַיִּהְיוּ הַכְּרֻבִים פֹּרְשֵׂי כְנָפַיִם לְמַעְלָה",
         "פכאנא אלכרובין באסטין אגנחתהמא אלי' פוק",
         "And the two cherubim were spreading their wings upward"),
        ("סֹכְכִים בְּכַנְפֵיהֶם עַל-הַכַּפֹּרֶת",
         "ומצ'ללין בהא עלי אלג'שא",
         "sheltering with them over the cover"),
        ("וּפְנֵיהֶם אִישׁ אֶל-אָחִיו", "וגוההמא אלואחד אלי' אלאכ'ר",
         "and the face of one was toward the other"),
        ("אֶל-הַכַּפֹּרֶת--הָיוּ פְּנֵי הַכְּרֻבִים",
         "ואלי' אלג'שא כנאת וגוההמא",
         "and toward the cover were their faces turned"),
    ],
    10: [
        ("וַיַּעַשׂ אֶת-הַשֻּׁלְחָן עֲצֵי שִׁטִּים",
         "וצנע אלמאידה מן כ'שב אלסנט",
         "And he made the table from acacia wood"),
        ("אַמָּתַיִם אָרְכּוֹ וְאַמָּה רָחְבּוֹ",
         "ד'ראעין טולהא וד'ראע ערצ'הא",
         "two cubits its length, and a cubit its width"),
        ("וְאַמָּה וָחֵצִי קֹמָתוֹ", "וד'ראע ונצף סמכהא",
         "and a cubit and a half its height"),
    ],
    11: [
        ("וַיְצַף אֹתוֹ זָהָב טָהוֹר", "וגשאהא בד'הב כ'אלץ",
         "And he overlaid it with pure gold"),
        ("וַיַּעַשׂ לוֹ זֵר זָהָב סָבִיב",
         "וצנע להא. זיגא מן ד'הב מסתדירא",
         "and made for it a border of gold, encircling all around"),
    ],
    12: [
        ("וַיַּעַשׂ לוֹ מִסְגֶּרֶת טֹפַח סָבִיב",
         "וצנע להא חאפה. מקדאר קבצ'ה מסתדירא",
         "And he made for it a rim of the breadth of a fist, encircling all around"),
        ("וַיַּעַשׂ זֵר-זָהָב לְמִסְגַּרְתּוֹ סָבִיב",
         "וצנע להא זיגא מן ד'הב. לחאפתהא מסתדירא",
         "and he made for it a border of gold for its rim, encircling all around"),
    ],
    13: [
        ("וַיִּצֹק לוֹ אַרְבַּע טַבְּעֹת זָהָב",
         "וצאג' להא ארבע חלק מן דהב",
         "And he cast for it four rings of gold"),
        ("וַיִּתֵּן אֶת-הַטַּבָּעֹת עַל אַרְבַּע הַפֵּאֹת אֲשֶׁר לְאַרְבַּע רַגְלָיו",
         "וגעל אלחלק פי ארבע גהאתהא. אלתי לארבע ארגלהא",
         "and set the rings on its four sides — which were at its four legs"),
    ],
    14: [
        ("לְעֻמַּת הַמִּסְגֶּרֶת הָיוּ הַטַּבָּעֹת",
         "אמאם אלחאפה. כנאת אלחלק",
         "Alongside the rim were the rings"),
        ("בָּתִּים לַבַּדִּים לָשֵׂאת אֶת-הַשֻּׁלְחָן",
         "מכאנא לאלדהוק. לתחמל בהא אלמאידה",
         "a place for the poles — so that the table might be carried by them"),
    ],
    15: [
        ("וַיַּעַשׂ אֶת-הַבַּדִּים עֲצֵי שִׁטִּים",
         "וצנע אלדהוק מן כ'שב אלסנט",
         "And he made the poles from acacia wood"),
        ("וַיְצַף אֹתָם זָהָב", "וגשאהא בד'הב", "and overlaid them with gold"),
        ("לָשֵׂאת אֶת-הַשֻּׁלְחָן", "לתחמל בהא אלמאידה",
         "so that the table might be carried by them"),
    ],
    16: [
        ("וַיַּעַשׂ אֶת-הַכֵּלִים אֲשֶׁר עַל-הַשֻּׁלְחָן",
         "וצנע אלאניה אלד'י עליהא",
         "And he made the vessels that were upon it"),
        ("אֶת-קְעָרֹתָיו וְאֶת-כַּפֹּתָיו",
         "אלקצאע ואלדרוג",
         "the dishes, the drawers"),
        ("וְאֵת מְנַקִּיֹּתָיו וְאֶת-הַקְּשָׂו‍ֹת אֲשֶׁר יֻסַּךְ בָּהֵן",
         "ואלמלאעק ואלמדאהין. אלד'י תג'טא בהא",
         "the spoons, and the flagons with which it is covered"),
        ("זָהָב טָהוֹר", "מן ד'הב כ'אלץ", "of pure gold"),
    ],
    17: [
        ("וַיַּעַשׂ אֶת-הַמְּנֹרָה זָהָב טָהוֹר מִקְשָׁה עָשָׂה אֶת-הַמְּנֹרָה",
         "וצנע אלמנארה מן ד'הב כ'אלץ. מצמתה צנעהא",
         "And he made the lampstand of pure gold — solid he made it"),
        ("יְרֵכָהּ וְקָנָהּ", "ארגלהא וקצבהא", "its base and its shaft"),
        ("גְּבִיעֶיהָ כַּפְתֹּרֶיהָ וּפְרָחֶיהָ מִמֶּנָּה הָיוּ",
         "וגאמאתהא. ותפאפיחהא וסואסנהא מנהא כנאת",
         "its cups, its pomegranates, and its blossoms were all of it"),
    ],
    18: [
        ("וְשִׁשָּׁה קָנִים יֹצְאִים מִצִּדֶּיהָ",
         "וסת קצבאת. כ'ארגאת מן גאנביהא",
         "And six branches extending from its sides"),
        ("שְׁלֹשָׁה קְנֵי מְנֹרָה מִצִּדָּהּ הָאֶחָד",
         "ת'לאת' קצבאת מן גאנבהא אלואחד",
         "three branches from one side of it"),
        ("וּשְׁלֹשָׁה קְנֵי מְנֹרָה מִצִּדָּהּ הַשֵּׁנִי",
         "ות'לאת' קצבאת מן גאנבהא אלת'אני",
         "and three branches from the other side"),
    ],
    19: [
        ("שְׁלֹשָׁה גְבִעִים מְשֻׁקָּדִים בַּקָּנֶה הָאֶחָד כַּפְתֹּר וָפֶרַח",
         "ת'לאת' גאמאת מלווזאת. פי כל קצבה תפאחה וסוסנה",
         "Three cups fashioned in almond-shapes on each branch, a pomegranate and a blossom"),
        ("כֵּן לְשֵׁשֶׁת הַקָּנִים הַיֹּצְאִים מִן-הַמְּנֹרָה",
         "כד'אך צנע לאלסת אלקצבאת. אלכ'ארגאת מנהא",
         "thus he made it for the six branches extending from it"),
    ],
    20: [
        ("וּבַמְּנֹרָה אַרְבָּעָה גְבִעִים מְשֻׁקָּדִים",
         "ופי נפס אלמנארה ארבע גאמאת. מלווזאת",
         "And in the body of the lampstand itself, four cups fashioned in almond-shapes"),
        ("כַּפְתֹּרֶיהָ וּפְרָחֶיהָ", "ותפאפיחהא וסואסנהא",
         "with their pomegranates and their blossoms"),
    ],
    21: [
        ("וְכַפְתֹּר תַּחַת שְׁנֵי הַקָּנִים מִמֶּנָּה",
         "ותפאחה תחת כל קצבתין מנהא",
         "And a pomegranate beneath each two branches of it"),
        ("לְשֵׁשֶׁת הַקָּנִים הַיֹּצְאִים מִמֶּנָּה",
         "כד'אך לאלסת אלקצבאת. אלכ'ארגאת מנהא",
         "thus for the six branches extending from it"),
    ],
    22: [
        ("כַּפְתֹּרֵיהֶם וּקְנֹתָם מִמֶּנָּה הָיוּ",
         "תפאפיחהא וקצבהא מנהא כנאת",
         "Its pomegranates and its shaft were of it"),
        ("כֻּלָּהּ מִקְשָׁה אַחַת זָהָב טָהוֹר",
         "כלהא מצמתה ואחדה מן ד'הב כ'אלץ",
         "all of it was one solid piece of pure gold"),
    ],
    23: [
        ("וַיַּעַשׂ אֶת-נֵרֹתֶיהָ שִׁבְעָה", "וצנע להא סבעה סרג",
         "And he made for it seven lamps"),
        ("וּמַלְקָחֶיהָ וּמַחְתֹּתֶיהָ זָהָב טָהוֹר",
         "וכלבאתהא ומגאמרהא מן ד'הב כ'אלץ",
         "and its tongs and its fire-pans of pure gold"),
    ],
    24: [
        ("כִּכָּר זָהָב טָהוֹר עָשָׂה אֹתָהּ",
         "מן בדרה' ד'הב כ'אלץ צנעהא",
         "From a talent of pure gold he made it"),
        ("וְאֵת כָּל-כֵּלֶיהָ", "הי וגמיע אניתהא",
         "it and all its vessels"),
    ],
    25: [
        ("וַיַּעַשׂ אֶת-מִזְבַּח הַקְּטֹרֶת עֲצֵי שִׁטִּים",
         "וצנע מד'בח אלב'כור מן כ'שב אלסנט",
         "And he made the altar of incense from acacia wood"),
        ("אַמָּה אָרְכּוֹ וְאַמָּה רָחְבּוֹ רָבוּעַ",
         "טולה ד'ראע וערצ'ה ד'ראע מרבעא",
         "one cubit its length and one cubit its width — square"),
        ("וְאַמָּתַיִם קֹמָתוֹ--מִמֶּנּוּ הָיוּ קַרְנֹתָיו",
         "וסמכה ד'ראעין. מנה ארכאנה",
         "and two cubits its height; its horns were of it"),
    ],
    26: [
        ("וַיְצַף אֹתוֹ זָהָב טָהוֹר אֶת-גַּגּוֹ וְאֶת-קִירֹתָיו סָבִיב",
         "וג'שאה בד'הב כ'אלץ. סטחה וחיטאנה. מסתדירא",
         "And he overlaid it with pure gold — its top and its walls all around"),
        ("וְאֶת-קַרְנֹתָיו", "וארכאנה", "and its horns"),
        ("וַיַּעַשׂ לוֹ זֵר זָהָב סָבִיב",
         "וצנע לה. זיגא מן ד'הב מסתדירא",
         "and he made for it a border of gold, encircling all around"),
    ],
    27: [
        ("וּשְׁתֵּי טַבְּעֹת זָהָב עָשָׂה-לוֹ מִתַּחַת לְזֵרוֹ עַל שְׁתֵּי צַלְעֹתָיו",
         "וחלקתין מן ד'הב צנעהמא לה תחת זיגה. פי גהתיה",
         "And two rings of gold he made for it beneath its border, on its two sides"),
        ("לְבָתִּים לְבַדִּים לָשֵׂאת אֹתוֹ בָּהֶם",
         "כד'אך עלי גאנביה מכאנא לאלד'הוק. ליחמל בהא",
         "as a place for the poles, so that it might be carried by them"),
    ],
    28: [
        ("וַיַּעַשׂ אֶת-הַבַּדִּים עֲצֵי שִׁטִּים",
         "וצנע אלדהוק. מן כ'שב אלסנט",
         "And he made the poles from acacia wood"),
        ("וַיְצַף אֹתָם זָהָב", "וגשאהא בד'הב", "and overlaid them with gold"),
    ],
    29: [
        ("וַיַּעַשׂ אֶת-שֶׁמֶן הַמִּשְׁחָה קֹדֶשׁ",
         "וצנע דהן אלמסח מקדסא",
         "And he made the consecrated anointing oil"),
        ("וְאֶת-קְטֹרֶת הַסַּמִּים טָהוֹר--מַעֲשֵׂה רֹקֵחַ",
         "ובכ'ור אלצמוג' מטהרא. צנעה' עטאר",
         "and the pure incense of resins — the work of a perfumer"),
    ],
}
