"""Hand-authored alignment triples for Shemot chapter 36."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְעָשָׂה בְצַלְאֵל וְאָהֳלִיאָב", "פליצנעו הם וסאיר אלחכמא",
         "And Bezalel and Oholiab and the rest of the skilled men"),
        ("וְכֹל אִישׁ חֲכַם-לֵב", "מן געל אללה פיהם חכמה ופהם",
         "in whom God had placed wisdom and understanding"),
        ("לָדַעַת לַעֲשֹׂת אֶת-כָּל-מְלֶאכֶת עֲבֹדַת הַקֹּדֶשׁ",
         "אן יערפו ויעמלו גמיע צנעה' עמל אלקדס",
         "that they might know and perform all the craft of the work of the sanctuary"),
        ("לְכֹל אֲשֶׁר-צִוָּה יְהוָה", "כמא אמר אללה בה",
         "as God had commanded"),
    ],
    2: [
        ("וַיִּקְרָא מֹשֶׁה אֶל-בְּצַלְאֵל וְאֶל-אָהֳלִיאָב",
         "פנאדא בהם מוסי' ובסאיר אלחכמא",
         "And Moses called out to them and to the rest of the skilled men"),
        ("אֲשֶׁר נָתַן יְהוָה חָכְמָה בְּלִבּוֹ",
         "מן געל אללה פיהם חכמה",
         "in whom God had placed wisdom"),
        ("כֹּל אֲשֶׁר נְשָׂאוֹ לִבּוֹ לְקָרְבָה אֶל-הַמְּלָאכָה לַעֲשֹׂת אֹתָהּ",
         "כל מן ראא ראיה. אן יתקדם אלי' אלצנאעה ליצנעהא",
         "every one who had seen fit in his own view to come forward to the craft to perform it"),
    ],
    3: [
        ("וַיִּקְחוּ מִלִּפְנֵי מֹשֶׁה", "פקבצ'ו מן בין ידי מוסי'",
         "And they received from before Moses"),
        ("אֵת כָּל-הַתְּרוּמָה אֲשֶׁר הֵבִיאוּ בְּנֵי יִשְׂרָאֵל לִמְלֶאכֶת עֲבֹדַת הַקֹּדֶשׁ",
         "גמיע אלרפיעה אלתי גאו בהא בני אסראיל. לצנעה עמל אלקדס לתעמל מנהא",
         "all the tribute which the sons of Israel had brought for the craft of the work of the sanctuary, to be made from it"),
        ("וְהֵם הֵבִיאוּ אֵלָיו עוֹד נְדָבָה--בַּבֹּקֶר בַּבֹּקֶר",
         "ועאד אלקום יאתונה. בבראעה פי כל ג'דאה",
         "and the people kept bringing freewill offerings every morning"),
    ],
    4: [
        ("וַיָּבֹאוּ כָּל-הַחֲכָמִים הָעֹשִׂים אֵת כָּל-מְלֶאכֶת הַקֹּדֶשׁ",
         "חתי' אתי גמיע אלחכמא. אלצאנעין גמיע צנעה' אלקדס",
         "Until all the skilled men — those performing all the craft of the sanctuary"),
        ("אִישׁ-אִישׁ מִמְּלַאכְתּוֹ אֲשֶׁר-הֵמָּה עֹשִׂים",
         "כל אמר מן פן צנעתה אלד'י הם יצנעון",
         "each man in his craft which they were performing — came forward"),
    ],
    5: [
        ("וַיֹּאמְרוּ אֶל-מֹשֶׁה לֵּאמֹר", "פקאלו למוסי'",
         "And they said to Moses"),
        ("מַרְבִּים הָעָם לְהָבִיא", "הוד'א אלקום מכת'רון אן יאתו",
         "Behold, the people are bringing more than enough"),
        ("מִדֵּי הָעֲבֹדָה לַמְּלָאכָה אֲשֶׁר-צִוָּה יְהוָה לַעֲשֹׂת אֹתָהּ",
         "באפצ'ל מן כפאיה' עמל אלצנאעה. אלד'י אמר אללה אן תעמל",
         "for the craft of the work which God has commanded to be made"),
    ],
    6: [
        ("וַיְצַו מֹשֶׁה", "פאמר מוסי'", "And Moses commanded"),
        ("וַיַּעֲבִירוּ קוֹל בַּמַּחֲנֶה לֵאמֹר", "ונודא בצות פי אלעסכר. יקול",
         "and it was proclaimed by voice throughout the camp, saying"),
        ("אִישׁ וְאִשָּׁה אַל-יַעֲשׂוּ-עוֹד מְלָאכָה לִתְרוּמַת הַקֹּדֶשׁ",
         "כל רגל ואמראה. לא יאת בשי בעד הד'א מן רפיעה' אלקדס",
         "Let no man or woman bring anything further for the tribute of the sanctuary"),
        ("וַיִּכָּלֵא הָעָם מֵהָבִיא", "פאנקטע אלקום מן אלמגי בשיי",
         "And so the people ceased from bringing anything"),
    ],
    7: [
        ("וְהַמְּלָאכָה הָיְתָה דַיָּם לְכָל-הַמְּלָאכָה",
         "פכאן מא אתו בה. כפאיה. לגמיע אלצנאעה",
         "For what they had brought was sufficient for all the craft"),
        ("לַעֲשׂוֹת אֹתָהּ וְהוֹתֵר", "אן תעמל מנהא. ופאצ'לא",
         "to be made from it — and there was surplus"),
    ],
    8: [
        ("וַיַּעֲשׂוּ כָל-חֲכַם-לֵב בְּעֹשֵׂי הַמְּלָאכָה אֶת-הַמִּשְׁכָּן",
         "פצנע כל חכים מן אלצנאיע. נפס אלמסכן",
         "And every skilled man among the craftsmen made the tabernacle itself"),
        ("עֶשֶׂר יְרִיעֹת שֵׁשׁ מָשְׁזָר", "עשר שקאק. מן עשר משזור",
         "ten panels of fine linen twisted"),
        ("וּתְכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי",
         "ואסמאנגון וארגואן וצבג' קרמז",
         "with blue and purple and scarlet dye"),
        ("כְּרֻבִים מַעֲשֵׂה חֹשֵׁב עָשָׂה אֹתָם",
         "צוורא. צנעה' חאד'ק צנעהא",
         "fashioned with figures — the work of a skilled craftsman who made them"),
    ],
    9: [
        ("אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁמֹנֶה וְעֶשְׂרִים בָּאַמָּה",
         "טול כל שקה. ת'מאניה ועשרין ד'ראע",
         "The length of each panel was twenty-eight cubits"),
        ("וְרֹחַב אַרְבַּע בָּאַמָּה הַיְרִיעָה הָאֶחָת",
         "וערצ'הא ארבעה' אד'רע",
         "and its width four cubits"),
        ("מִדָּה אַחַת לְכָל-הַיְרִיעֹת", "מסאחה ואחדה לגמיע אלשקאק",
         "one measure for all the panels"),
    ],
    10: [
        ("וַיְחַבֵּר אֶת-חֲמֵשׁ הַיְרִיעֹת אַחַת אֶל-אֶחָת",
         "וכ'ייט כל כ'מס שקאק. אלואחדה מע אלאכ'רי'",
         "And he sewed every five panels, one with the other"),
    ],
    11: [
        ("וַיַּעַשׂ לֻלְאֹת תְּכֵלֶת עַל שְׂפַת הַיְרִיעָה הָאֶחָת מִקָּצָה בַּמַּחְבָּרֶת",
         "וצנע ערי' מן אסמאנגון. פי חאשיה' אלשקה אלואחדה. פי אלטרף אלמולף",
         "And he made loops of blue upon the border of the one panel at the joining edge"),
        ("כֵּן עָשָׂה בִּשְׂפַת הַיְרִיעָה הַקִּיצוֹנָה בַּמַּחְבֶּרֶת הַשֵּׁנִית",
         "וכד'אלך צנע פי טרף אלחאשיה. אלטרפא. אלמולפה אלת'אניה",
         "and likewise he made at the edge of the border, at the outermost edge of the second joined panel"),
    ],
    12: [
        ("חֲמִשִּׁים לֻלָאֹת עָשָׂה בַּיְרִיעָה הָאֶחָת",
         "וצנע כ'מסין ערוה פי אלשקה אלואחדה",
         "And he made fifty loops in the one panel"),
        ("וַחֲמִשִּׁים לֻלָאֹת עָשָׂה בִּקְצֵה הַיְרִיעָה אֲשֶׁר בַּמַּחְבֶּרֶת הַשֵּׁנִית",
         "וכ'מסין ערוה פי טרף אלשקה. אלמולפה אלת'אניה",
         "and fifty loops at the edge of the panel of the second joining"),
        ("מַקְבִּילֹת הַלֻּלָאֹת--אַחַת אֶל-אֶחָת",
         "וגעל אלערי' מתקאבלה. אלואחדה מע אלאכ'רי'",
         "and he set the loops facing one another, one with the other"),
    ],
    13: [
        ("וַיַּעַשׂ חֲמִשִּׁים קַרְסֵי זָהָב", "וצנע כ'מסין שצ'אץ' מן ד'הב",
         "And he made fifty clasps of gold"),
        ("וַיְחַבֵּר אֶת-הַיְרִיעֹת אַחַת אֶל-אַחַת בַּקְּרָסִים",
         "כולוף אלשקאק. ואחדה מע אלאכ'רי' בלשצ'אץ'",
         "and bound the panels one with the other by the clasps"),
        ("וַיְהִי הַמִּשְׁכָּן אֶחָד", "פצאר אלמסכן ואחדא",
         "and so the tabernacle became one"),
    ],
    14: [
        ("וַיַּעַשׂ יְרִיעֹת עִזִּים לְאֹהֶל עַל-הַמִּשְׁכָּן",
         "וצנע שקאק מן מרעזא. כ'באא עלי' אלמסכן",
         "And he made panels of fine goat's wool — a tent over the tabernacle"),
        ("עַשְׁתֵּי-עֶשְׂרֵה יְרִיעֹת עָשָׂה אֹתָם",
         "אחדי' עשר שקה צנעהא",
         "eleven panels he made them"),
    ],
    15: [
        ("אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁלֹשִׁים בָּאַמָּה",
         "טול כל שקה ת'לאת'ין ד'ראע",
         "The length of each panel was thirty cubits"),
        ("וְאַרְבַּע אַמּוֹת רֹחַב הַיְרִיעָה הָאֶחָת",
         "וערצ'הא ארבעה' אד'רע",
         "and its width four cubits"),
        ("מִדָּה אַחַת לְעַשְׁתֵּי עֶשְׂרֵה יְרִיעֹת",
         "מסאחה ואחדה. לאחדי' עשר שקה",
         "one measure for the eleven panels"),
    ],
    16: [
        ("וַיְחַבֵּר אֶת-חֲמֵשׁ הַיְרִיעֹת לְבָד",
         "וכ'ייט כ'מס שקאק עלי' חדה",
         "And he sewed five panels by themselves"),
        ("וְאֶת-שֵׁשׁ הַיְרִיעֹת לְבָד", "וסת שקאק עלי חדה",
         "and six panels by themselves"),
    ],
    17: [
        ("וַיַּעַשׂ לֻלָאֹת חֲמִשִּׁים עַל שְׂפַת הַיְרִיעָה הַקִּיצֹנָה בַּמַּחְבָּרֶת",
         "וצנע כ'מסין ערוה. פי חאשיה' אלשקה. אלטרפא אלמולפה",
         "And he made fifty loops on the border of the outermost joining panel"),
        ("וַחֲמִשִּׁים לֻלָאֹת עָשָׂה עַל-שְׂפַת הַיְרִיעָה הַחֹבֶרֶת הַשֵּׁנִית",
         "וכ'מסין ערוה פי חאשיה' אלשקה. אלמולפה אלת'אניה",
         "and fifty loops on the border of the second joining panel"),
    ],
    18: [
        ("וַיַּעַשׂ קַרְסֵי נְחֹשֶׁת חֲמִשִּׁים", "וצנע כ'מסין שצ'אץ' מן נחאס",
         "And he made fifty clasps of copper"),
        ("לְחַבֵּר אֶת-הָאֹהֶל לִהְיֹת אֶחָד",
         "ליולף אלכ'בא ליציר ואחדא",
         "to join the tent so that it should become one"),
    ],
    19: [
        ("וַיַּעַשׂ מִכְסֶה לָאֹהֶל עֹרֹת אֵילִם מְאָדָּמִים",
         "וצנע ג'טאא לאלכ'בא. מן גלוד כבאש אדים",
         "And he made a covering for the tent of tanned ram skins"),
        ("וּמִכְסֵה עֹרֹת תְּחָשִׁים מִלְמָעְלָה",
         "וג'טאא. מן גלוד דארש מן פוק",
         "and a covering of fine leather above"),
    ],
    20: [
        ("וַיַּעַשׂ אֶת-הַקְּרָשִׁים לַמִּשְׁכָּן עֲצֵי שִׁטִּים עֹמְדִים",
         "וצנע אלתכ'אתג לאלמסכן. מן כ'שב אלסנט קאימא",
         "And he made the boards for the tabernacle of acacia wood, standing upright"),
    ],
    21: [
        ("עֶשֶׂר אַמֹּת אֹרֶךְ הַקָּרֶשׁ", "עשרה' אד'רע טול כל תכ'תגה",
         "Ten cubits was the length of each board"),
        ("וְאַמָּה וַחֲצִי הָאַמָּה רֹחַב הַקֶּרֶשׁ הָאֶחָד",
         "וד'ראע ונצף ערצ'הא",
         "and a cubit and a half its width"),
    ],
    22: [
        ("שְׁתֵּי יָדֹת לַקֶּרֶשׁ הָאֶחָד מְשֻׁלָּבֹת אַחַת אֶל-אֶחָת",
         "ולהא ציראן מלסנאן. אחדהמא באזא אלאכ'ר",
         "And it had two tongue-shaped pegs, one facing the other"),
        ("כֵּן עָשָׂה לְכֹל קַרְשֵׁי הַמִּשְׁכָּן",
         "כד'אך צנע. לגמיע תכ'אתג אלמסכן",
         "so he made for all the boards of the tabernacle"),
    ],
    23: [
        ("וַיַּעַשׂ אֶת-הַקְּרָשִׁים לַמִּשְׁכָּן עֶשְׂרִים קְרָשִׁים",
         "וצנע לאלמסכן עשרין תכ'תגה",
         "And he made for the tabernacle twenty boards"),
        ("לִפְאַת נֶגֶב תֵּימָנָה", "מן גהה' מהב אלגנוב",
         "on the side toward the direction of the south wind"),
    ],
    24: [
        ("וְאַרְבָּעִים אַדְנֵי-כֶסֶף--עָשָׂה תַּחַת עֶשְׂרִים הַקְּרָשִׁים",
         "וצנע ארבעין קאעדה מן פצ'ה. תחת אלעשרין אלתכ'תגה",
         "And he made forty silver bases under the twenty boards"),
        ("שְׁנֵי אֲדָנִים תַּחַת-הַקֶּרֶשׁ הָאֶחָד לִשְׁתֵּי יְדֹתָיו",
         "קאעדתין תחת כל תכ'תגה לציראהא",
         "two bases under each board for its two pegs"),
    ],
    25: [
        ("וּלְצֶלַע הַמִּשְׁכָּן הַשֵּׁנִית לִפְאַת צָפוֹן",
         "ולגאנב אלמסכן אלת'אני. מן גהה' מהב אלשמאל",
         "And for the second side of the tabernacle, on the side toward the direction of the north wind"),
        ("עָשָׂה עֶשְׂרִים קְרָשִׁים", "צנע עשרין תכ'תגה",
         "he made twenty boards"),
    ],
    26: [
        ("וְאַרְבָּעִים אַדְנֵיהֶם כָּסֶף", "ולהא ארבעין קאעדה מן פצ'ה",
         "with forty bases of silver for them"),
        ("שְׁנֵי אֲדָנִים תַּחַת הַקֶּרֶשׁ הָאֶחָד",
         "קאעדתאן תחת כל תכ'תגה",
         "two bases under each board"),
    ],
    27: [
        ("וּלְיַרְכְּתֵי הַמִּשְׁכָּן יָמָּה", "ולמוכ'ר אלמסכן ג'רבא",
         "And for the rear of the tabernacle toward the west"),
        ("עָשָׂה שִׁשָּׁה קְרָשִׁים", "צנע סת תכ'אתג",
         "he made six boards"),
    ],
    28: [
        ("וּשְׁנֵי קְרָשִׁים עָשָׂה לִמְקֻצְעֹת הַמִּשְׁכָּן--בַּיַּרְכָתָיִם",
         "ותכ'תגתין צנעהמא. לרכני אלמסכן. פי אלזאויתין",
         "And two boards he made for the corners of the tabernacle at the two corners"),
    ],
    29: [
        ("וְהָיוּ תוֹאֲמִם מִלְּמַטָּה", "פכנאת מעתדלה מן אספל",
         "And they were aligned from below"),
        ("וְיַחְדָּו יִהְיוּ תַמִּים אֶל-רֹאשׁוֹ אֶל-הַטַּבַּעַת הָאֶחָת",
         "וגמיע כנאת מעתדלה מן פוק. בחלקה ואחדה",
         "and together were aligned from above with one ring"),
        ("כֵּן עָשָׂה לִשְׁנֵיהֶם לִשְׁנֵי הַמִּקְצֹעֹת",
         "כד'אך צנע לאלרכנין כליהמא",
         "so he made for both corners, for the two of them"),
    ],
    30: [
        ("וְהָיוּ שְׁמֹנָה קְרָשִׁים", "פצארת ת'מאן תכ'אתג",
         "And there came to be eight boards"),
        ("וְאַדְנֵיהֶם כֶּסֶף שִׁשָּׁה עָשָׂר אֲדָנִים",
         "וקואעדהא מן פצ'ה. סתה עשר קאעדה",
         "and their bases of silver: sixteen bases"),
        ("שְׁנֵי אֲדָנִים שְׁנֵי אֲדָנִים תַּחַת הַקֶּרֶשׁ הָאֶחָד",
         "קאעדתאן תחת כל תכ'תגה",
         "two bases under each board"),
    ],
    31: [
        ("וַיַּעַשׂ בְּרִיחֵי עֲצֵי שִׁטִּים", "וצנע אמהאג מן כ'שב אלסנט",
         "And he made bars of acacia wood"),
        ("חֲמִשָּׁה לְקַרְשֵׁי צֶלַע-הַמִּשְׁכָּן הָאֶחָת",
         "כמסה. לתכ'אתג גאנב אלמסכן אלואחד",
         "five for the boards of one side of the tabernacle"),
    ],
    32: [
        ("וַחֲמִשָּׁה בְרִיחִם לְקַרְשֵׁי צֶלַע-הַמִּשְׁכָּן הַשֵּׁנִית",
         "וכמסה אמהאג. לתכ'אתג גאנב אלמסכן אלת'אני",
         "and five bars for the boards of the second side of the tabernacle"),
        ("וַחֲמִשָּׁה בְרִיחִם לְקַרְשֵׁי הַמִּשְׁכָּן לַיַּרְכָתַיִם יָמָּה",
         "וכמסה אמהאג לתכ'אתג אלמסכן. פי מוכ'רה ג'רבא",
         "and five bars for the boards of the tabernacle at its rear toward the west"),
    ],
    33: [
        ("וַיַּעַשׂ אֶת-הַבְּרִיחַ הַתִּיכֹן לִבְרֹחַ בְּתוֹךְ הַקְּרָשִׁים",
         "וצנע אלמהג אלאוסט. מנה. נאפד' פי גוף אלתכ'אתג",
         "And he made the middle bar to pass through the interior of the boards"),
        ("מִן-הַקָּצֶה אֶל-הַקָּצֶה", "מן אלטרף אלי' אלטרף",
         "from end to end"),
    ],
    34: [
        ("וְאֶת-הַקְּרָשִׁים צִפָּה זָהָב", "ואלתכ'אתג ג'שאהא בד'הב",
         "And the boards he overlaid with gold"),
        ("וְאֶת-טַבְּעֹתָם עָשָׂה זָהָב--בָּתִּים לַבְּרִיחִם",
         "וצנע חלקהא מן ד'הב. מכאנא לאלאמהאג",
         "and he made their rings of gold as places for the bars"),
        ("וַיְצַף אֶת-הַבְּרִיחִם זָהָב", "וג'שא אלאמהאג איצ'א בד'הב",
         "and he overlaid the bars with gold as well"),
    ],
    35: [
        ("וַיַּעַשׂ אֶת-הַפָּרֹכֶת תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר",
         "וצנע אלסגף. מן אסמאנגון וארגואן. וצבג' קרמז ועשר משזור",
         "And he made the veil of blue and purple and scarlet dye and fine linen twisted"),
        ("מַעֲשֵׂה חֹשֵׁב עָשָׂה אֹתָהּ כְּרֻבִים",
         "צנעה' חאד'ק צנעהא צוורא",
         "the work of a skilled craftsman he made it, with figures"),
    ],
    36: [
        ("וַיַּעַשׂ לָהּ אַרְבָּעָה עַמּוּדֵי שִׁטִּים",
         "וצנע להא ארבעה עמד מן סנט",
         "And he made for it four columns of acacia wood"),
        ("וַיְצַפֵּם זָהָב וָוֵיהֶם זָהָב",
         "וגשאהא בד'הב. וזראפינהא ד'הב",
         "and overlaid them with gold; their hooks were of gold"),
        ("וַיִּצֹק לָהֶם אַרְבָּעָה אַדְנֵי-כָסֶף",
         "וצאג' להא. ארבע קואעד מן פצ'ה",
         "and he cast for them four bases of silver"),
    ],
    37: [
        ("וַיַּעַשׂ מָסָךְ לְפֶתַח הָאֹהֶל",
         "וצנע סתרא לבאב אלכ'בא",
         "And he made a curtain for the entrance of the tent"),
        ("תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר מַעֲשֵׂה רֹקֵם",
         "מן אסמאנגון וארגואן. וצבג' קרמז ועשר משזור. צנעה' ראקם",
         "of blue and purple and scarlet dye and fine linen twisted — the work of an embroiderer"),
    ],
    38: [
        ("וְאֶת-עַמּוּדָיו חֲמִשָּׁה וְאֶת-וָוֵיהֶם",
         "ועמדהא כ'מסה וזראפינהא",
         "And its columns were five, with their hooks"),
        ("וְצִפָּה רָאשֵׁיהֶם וַחֲשֻׁקֵיהֶם זָהָב",
         "וג'שא רוסהם. וטלאהא ד'הב",
         "and he overlaid their tops and coated them with gold"),
        ("וְאַדְנֵיהֶם חֲמִשָּׁה נְחֹשֶׁת",
         "וקואעדהא כמסה מן נחאס",
         "and their bases were five, of copper"),
    ],
}
