"""Hand-authored alignment triples for Shemot chapter 8."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'", "And God said to Moses"),
        ("אֱמֹר אֶל-אַהֲרֹן", "קל להרון", "Say to Aaron"),
        ("נְטֵה אֶת-יָדְךָ בְּמַטֶּךָ", "מד ידך בעצאך", "stretch forth your hand with your staff"),
        ("עַל-הַנְּהָרֹת עַל-הַיְאֹרִים וְעַל-הָאֲגַמִּים",
         "עלי' אלאנהאר ואלכ'לגאן ואלאגאם",
         "over the rivers and the channels and the pools"),
        ("וְהַעַל אֶת-הַצְפַרְדְּעִים עַל-אֶרֶץ מִצְרָיִם",
         "ואצעד אלצ'פאדע עלי' בלד מצר",
         "and bring up the frogs upon the land of Egypt"),
    ],
    2: [
        ("וַיֵּט אַהֲרֹן אֶת-יָדוֹ עַל מֵימֵי מִצְרָיִם",
         "פמד הרון ידה. עלי' מיאת אלמצריון",
         "And Aaron stretched forth his hand over the waters of the Egyptians"),
        ("וַתַּעַל הַצְּפַרְדֵּעַ", "פצעד אלצ'פאדע", "and the frogs came up"),
        ("וַתְּכַס אֶת-אֶרֶץ מִצְרָיִם", "וגטא בלד מצר", "and covered the land of Egypt"),
    ],
    3: [
        ("וַיַּעֲשׂוּ-כֵן הַחַרְטֻמִּים בְּלָטֵיהֶם",
         "וצנע. כד'אך אלעלמא בכ'פיהום",
         "And the learned men did likewise with their secret arts"),
        ("וַיַּעֲלוּ אֶת-הַצְפַרְדְּעִים עַל-אֶרֶץ מִצְרָיִם",
         "ואצעדו אלצ'פאדע עלי' בלד מצר",
         "and brought up frogs upon the land of Egypt"),
    ],
    4: [
        ("וַיִּקְרָא פַרְעֹה לְמֹשֶׁה וּלְאַהֲרֹן", "פדעא פרעון במוסי' והרון",
         "And Pharaoh called for Moses and Aaron"),
        ("וַיֹּאמֶר הַעְתִּירוּ אֶל-יְהוָה", "וקאל אשפעו אלי' אללה",
         "and said: 'Intercede with God"),
        ("וְיָסֵר הַצְפַרְדְּעִים מִמֶּנִּי וּמֵעַמִּי", "יזיל אלצ'פאדע. עני וען קומי",
         "that He remove the frogs from me and from my people"),
        ("וַאֲשַׁלְּחָה אֶת-הָעָם וְיִזְבְּחוּ לַיהוָה", "חתא אטלק אלקום. ידבחו ללה",
         "and I will release the people, that they may sacrifice to God"),
    ],
    5: [
        ("וַיֹּאמֶר מֹשֶׁה לְפַרְעֹה הִתְפָּאֵר עָלַי",
         "קאל לה מוסי' אקתרח עליי",
         "Moses said to him: 'Propose to me"),
        ("לְמָתַי אַעְתִּיר לְךָ וְלַעֲבָדֶיךָ וּלְעַמְּךָ",
         "מתא תשא אן אשפע לך. ולקואדך וקומך",
         "when do you wish that I intercede for you, and for your officers and your people"),
        ("לְהַכְרִית הַצְפַרְדְּעִים מִמְּךָ וּמִבָּתֶּיךָ",
         "פינקטע אלצ'פאדע. ענך וען מנאזלך",
         "that the frogs be cut off from you and from your dwellings"),
        ("רַק בַּיְאֹר תִּשָּׁאַרְנָה", "ותבקא פי אלניל פקט",
         "and remain in the Nile only"),
    ],
    6: [
        ("וַיֹּאמֶר לְמָחָר", "קאל ג'דא", "He said: 'Tomorrow"),
        ("וַיֹּאמֶר כִּדְבָרְךָ", "קאל כמא קלת", "He said: 'As you have said it shall be"),
        ("לְמַעַן תֵּדַע כִּי-אֵין כַּיהוָה אֱלֹהֵינוּ",
         "לכי תעלם. אנה ליס מתל אללה רבנא",
         "so that you may know that there is none like God our Lord"),
    ],
    7: [
        ("וְסָרוּ הַצְפַרְדְּעִים מִמְּךָ וּמִבָּתֶּיךָ וּמֵעֲבָדֶיךָ וּמֵעַמֶּךָ",
         "אד' תזול אלצ'פאדע. ענך וען מנאזלך וקואדך וקומך",
         "For the frogs shall depart from you and from your dwellings and your officers and your people"),
        ("רַק בַּיְאֹר תִּשָּׁאַרְנָה", "ותבקא פי אלניל פקט",
         "and remain in the Nile only"),
    ],
    8: [
        ("וַיֵּצֵא מֹשֶׁה וְאַהֲרֹן מֵעִם פַּרְעֹה",
         "פלמא כ'רג מוסי' והרון מן ענד פרעון",
         "And when Moses and Aaron went out from before Pharaoh"),
        ("וַיִּצְעַק מֹשֶׁה אֶל-יְהוָה", "דעי' מוסי' אלי' אללה", "Moses called to God"),
        ("עַל-דְּבַר הַצְפַרְדְּעִים אֲשֶׁר-שָׂם לְפַרְעֹה",
         "בסבב אלצ'פאדע אלתי אחלהא בפרעון",
         "on account of the frogs which He had brought upon Pharaoh"),
    ],
    9: [
        ("וַיַּעַשׂ יְהוָה כִּדְבַר מֹשֶׁה", "פצנע אללה כמא קאל מוסי'",
         "And God did as Moses had said"),
        ("וַיָּמֻתוּ הַצְפַרְדְּעִים מִן-הַבָּתִּים מִן-הַחֲצֵרֹת וּמִן-הַשָּׂדֹת",
         "פתמאות אלצ'פאדע. מן אלביות ואלדור ואלצ'יאע",
         "and the frogs died out of the houses and the courtyards and the villages"),
    ],
    10: [
        ("וַיִּצְבְּרוּ אֹתָם חֳמָרִם חֳמָרִם", "וגמעוהא אנאבירא אנאבירא",
         "And they heaped them up in pile upon pile"),
        ("וַתִּבְאַשׁ הָאָרֶץ", "פנתנת אלארץ' מנהא", "and the land stank from them"),
    ],
    11: [
        ("וַיַּרְא פַּרְעֹה כִּי הָיְתָה הָרְוָחָה", "פלמא ראא פרעון. אן אלפרגה קד כאנת",
         "And when Pharaoh saw that relief had come"),
        ("וְהַכְבֵּד אֶת-לִבּוֹ", "תקל קלבה", "he hardened his heart"),
        ("וְלֹא שָׁמַע אֲלֵהֶם", "ולם יקבל מנהמא", "and did not accept from them"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה", "כמא קאל אללה", "as God had said"),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה למוסי'", "And God said to Moses"),
        ("אֱמֹר אֶל-אַהֲרֹן נְטֵה אֶת-מַטְּךָ", "קל להרון. מד עצאך",
         "Say to Aaron: stretch forth your staff"),
        ("וְהַךְ אֶת-עֲפַר הָאָרֶץ", "ואצ'רב תראב אלארץ'",
         "and strike the dust of the earth"),
        ("וְהָיָה לְכִנִּם בְּכָל-אֶרֶץ מִצְרָיִם", "יציר קמלא פי גמיע בלד מצר",
         "that it become lice throughout all the land of Egypt"),
    ],
    13: [
        ("וַיַּעֲשׂוּ-כֵן", "פצנעו כד'אך", "And so they did"),
        ("וַיֵּט אַהֲרֹן אֶת-יָדוֹ בְמַטֵּהוּ וַיַּךְ אֶת-עֲפַר הָאָרֶץ",
         "ומד הרון ידה בעצאה פצ'רב תראב אלארץ'",
         "Aaron stretched forth his hand with his staff and struck the dust of the earth"),
        ("וַתְּהִי הַכִּנָּם בָּאָדָם וּבַבְּהֵמָה", "פצאר אלקמל פי אלנאס ואלבהאים",
         "and the lice came upon the people and the beasts"),
        ("כָּל-עֲפַר הָאָרֶץ הָיָה כִנִּים בְּכָל-אֶרֶץ מִצְרָיִם",
         "גמיע תראב אלארץ'. צאר קמלא פי גמיע בלד מצר",
         "all the dust of the earth became lice throughout all the land of Egypt"),
    ],
    14: [
        ("וַיַּעֲשׂוּ-כֵן הַחַרְטֻמִּים בְּלָטֵיהֶם לְהוֹצִיא אֶת-הַכִּנִּים",
         "פצנע כד'אך אלעלמא בכ'פיהום. ליכ'רגו אלקמל",
         "And the learned men did likewise with their secret arts, to bring out the lice"),
        ("וְלֹא יָכֹלוּ", "ולם יטיקו", "but they could not"),
        ("וַתְּהִי הַכִּנָּם בָּאָדָם וּבַבְּהֵמָה", "פתבת אלקמל. פי אלנאס ואלבהאים",
         "and the lice remained upon the people and the beasts"),
    ],
    15: [
        ("וַיֹּאמְרוּ הַחַרְטֻמִּם אֶל-פַּרְעֹה", "פקאלת אלעלמא לפרעון",
         "And the learned men said to Pharaoh"),
        ("אֶצְבַּע אֱלֹהִים הִוא", "הד'א גריחה מן ענד אללה",
         "This is a calamity from God"),
        ("וַיֶּחֱזַק לֵב-פַּרְעֹה", "פאשתד קלבה", "But his heart grew firm"),
        ("וְלֹא-שָׁמַע אֲלֵהֶם כַּאֲשֶׁר דִּבֶּר יְהוָה",
         "ולם יקבל מנהמא. כמא קאל אללה",
         "and he did not accept from them — as God had said"),
    ],
    16: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה הַשְׁכֵּם בַּבֹּקֶר",
         "וקאל אללה למוסי. אדלג באלג'דאה",
         "And God said to Moses: 'Rise early in the morning"),
        ("וְהִתְיַצֵּב לִפְנֵי פַרְעֹה--הִנֵּה יוֹצֵא הַמָּיְמָה",
         "וקף בין ידי פרעון. הוד'אה כ'ארג אלי' אלמא",
         "and stand before Pharaoh — behold, he is going out to the water"),
        ("וְאָמַרְתָּ אֵלָיו כֹּה אָמַר יְהוָה", "וקל לה. כד'א קאל אללה",
         "and say to him: Thus says God"),
        ("שַׁלַּח עַמִּי וְיַעַבְדֻנִי", "אטלק קומי יעבדוני",
         "Release my people, that they may serve Me"),
    ],
    17: [
        ("כִּי אִם-אֵינְךָ מְשַׁלֵּחַ אֶת-עַמִּי", "לאנך אן אבית אן תטלק קומי",
         "For if you refuse to release my people"),
        ("הִנְנִי מַשְׁלִיחַ בְּךָ וּבַעֲבָדֶיךָ וּבְעַמְּךָ וּבְבָתֶּיךָ אֶת-הֶעָרֹב",
         "האנא באעת' עליך . ועלי' קודאך וסאיר קומך. ומנאזלך כלט אלוחש",
         "behold I am sending upon you, and upon your officers, and upon the rest of your people, and upon your dwellings, a mixture of wild beasts"),
        ("וּמָלְאוּ בָּתֵּי מִצְרַיִם אֶת-הֶעָרֹב", "חתא תמתלי מנה ביות אלמצריון",
         "until the houses of the Egyptians shall be filled with it"),
        ("וְגַם הָאֲדָמָה אֲשֶׁר-הֵם עָלֶיהָ", "ואלארץ' אלד'י הם עליהא",
         "and the land upon which they dwell"),
    ],
    18: [
        ("וְהִפְלֵיתִי בַיּוֹם הַהוּא אֶת-אֶרֶץ גֹּשֶׁן",
         "ואביין פי ד'אלך אליום בלד אלסדיר",
         "And I shall distinguish on that day the land of Goshen"),
        ("אֲשֶׁר עַמִּי עֹמֵד עָלֶיהָ", "אלד'י קומי מקים בה",
         "in which my people dwells"),
        ("לְבִלְתִּי הֱיוֹת-שָׁם עָרֹב", "ללא יכון ת'ם וחש",
         "so that no wild beasts shall be there"),
        ("לְמַעַן תֵּדַע כִּי אֲנִי יְהוָה בְּקֶרֶב הָאָרֶץ",
         "לכי תעלם. אני אללה מסלט עלי' גמיע אלעאלם",
         "so that you may know that I am God, sovereign over all the world"),
    ],
    19: [
        ("וְשַׂמְתִּי פְדֻת בֵּין עַמִּי וּבֵין עַמֶּךָ",
         "ואצייר פדאא לקומי ממא יחל בקומך",
         "And I shall set a ransom for my people from what shall befall your people"),
        ("לְמָחָר יִהְיֶה הָאֹת הַזֶּה", "ג'דא תכון הד'ה אלאיה",
         "Tomorrow shall this sign be"),
    ],
    20: [
        ("וַיַּעַשׂ יְהוָה כֵּן", "פצנע אללה כד'אך", "And God did so"),
        ("וַיָּבֹא עָרֹב כָּבֵד בֵּיתָה פַרְעֹה וּבֵית עֲבָדָיו",
         "ודכ'ל וחש כת'יר. אלי' בית פרעון ובית קואדה",
         "and a great multitude of wild beasts entered the house of Pharaoh and the house of his officers"),
        ("וּבְכָל-אֶרֶץ מִצְרַיִם תִּשָּׁחֵת הָאָרֶץ מִפְּנֵי הֶעָרֹב",
         "וגמיע בלד מצר. אנפסד מן קבל אלוחש",
         "and all the land of Egypt was ruined because of the wild beasts"),
    ],
    21: [
        ("וַיִּקְרָא פַרְעֹה אֶל-מֹשֶׁה וּלְאַהֲרֹן", "פדעא פרעון במוסי והרון",
         "And Pharaoh called for Moses and Aaron"),
        ("וַיֹּאמֶר לְכוּ זִבְחוּ לֵאלֹהֵיכֶם--בָּאָרֶץ",
         "וקאל. אמצ'ו אדבחו לרבכם פי אלבלד",
         "and said: 'Go, sacrifice to your Lord within the land"),
    ],
    22: [
        ("וַיֹּאמֶר מֹשֶׁה לֹא נָכוֹן לַעֲשׂוֹת כֵּן",
         "קאל מוסי'. לא נטיק אן נצנע ד'אלך",
         "Moses said: 'We cannot do that"),
        ("כִּי תּוֹעֲבַת מִצְרַיִם נִזְבַּח לַיהוָה אֱלֹהֵינוּ",
         "לאן מא יכרה אלמצריון. נדבחה ללה רבנא",
         "for what the Egyptians abhor — that we sacrifice to God our Lord"),
        ("הֵן נִזְבַּח אֶת-תּוֹעֲבַת מִצְרַיִם לְעֵינֵיהֶם--וְלֹא יִסְקְלֻנוּ",
         "פהל נדבח מא יכרהונה אלמצריון. בחצ'רתהום ולא ירגמונא",
         "Shall we then sacrifice what the Egyptians abhor in their very presence, and they not stone us"),
    ],
    23: [
        ("דֶּרֶךְ שְׁלֹשֶׁת יָמִים נֵלֵךְ בַּמִּדְבָּר", "לכן מסאפה' ת'לאת'ה' איאם. נסיר פי אלבר",
         "But a journey of three days we will go into the open country"),
        ("וְזָבַחְנוּ לַיהוָה אֱלֹהֵינוּ", "נדבח ללה רבנא",
         "and sacrifice to God our Lord"),
        ("כַּאֲשֶׁר יֹאמַר אֵלֵינוּ", "כמא יאמרנא", "as He commands us"),
    ],
    24: [
        ("וַיֹּאמֶר פַּרְעֹה אָנֹכִי אֲשַׁלַּח אֶתְכֶם",
         "קאל פרעון. אנא אטלקכם",
         "Pharaoh said: 'I will release you"),
        ("וּזְבַחְתֶּם לַיהוָה אֱלֹהֵיכֶם בַּמִּדְבָּר",
         "תד'בחו ללה רבכם פי אלבר",
         "that you may sacrifice to God your Lord in the open country"),
        ("רַק הַרְחֵק לֹא-תַרְחִיקוּ לָלֶכֶת", "עדא אבאעדא לא תבעדון פי אלמסיר",
         "only do not go far in the journey"),
        ("הַעְתִּירוּ בַּעֲדִי", "אשפעא עני", "Intercede on my behalf"),
    ],
    25: [
        ("וַיֹּאמֶר מֹשֶׁה הִנֵּה אָנֹכִי יוֹצֵא מֵעִמָּךְ",
         "קאל מוסי'. האנא כ'ארג מן ענדך",
         "Moses said: 'Behold, I am going out from before you"),
        ("וְהַעְתַּרְתִּי אֶל-יְהוָה", "ואשפע אלי' אללה", "and I shall intercede with God"),
        ("וְסָר הֶעָרֹב מִפַּרְעֹה מֵעֲבָדָיו וּמֵעַמּוֹ מָחָר",
         "פיזיל אלוחש. ען פרעון וקואדה וקומה ג'דא",
         "and He shall remove the wild beasts from Pharaoh and his officers and his people tomorrow"),
        ("רַק אַל-יֹסֵף פַּרְעֹה הָתֵל לְבִלְתִּי שַׁלַּח אֶת-הָעָם לִזְבֹּחַ לַיהוָה",
         "עדא אלסכ'רייה לא יעאודהא פרעון. ללא יטלק אלקום. ידבחון ללה",
         "only let not Pharaoh repeat the mockery, by not releasing the people to sacrifice to God"),
    ],
    26: [
        ("וַיֵּצֵא מֹשֶׁה מֵעִם פַּרְעֹה", "פלמא כ'רג מן ענדה", "And when he went out from before him"),
        ("וַיֶּעְתַּר אֶל-יְהוָה", "שפע אלי' אללה", "he interceded with God"),
    ],
    27: [
        ("וַיַּעַשׂ יְהוָה כִּדְבַר מֹשֶׁה", "פצנע אללה כמא קאל מוסי'",
         "And God did as Moses had said"),
        ("וַיָּסַר הֶעָרֹב מִפַּרְעֹה מֵעֲבָדָיו וּמֵעַמּוֹ",
         "וזאל אלוחש. מן פרעון וקואדה וקומה",
         "and the wild beasts departed from Pharaoh and his officers and his people"),
        ("לֹא נִשְׁאַר אֶחָד", "לם יבק ואחד", "not one remained"),
    ],
    28: [
        ("וַיַּכְבֵּד פַּרְעֹה אֶת-לִבּוֹ גַּם בַּפַּעַם הַזֹּאת",
         "פת'קל פרעון קלבה. הד'ה אלמרה איצ'א",
         "And Pharaoh hardened his heart this time also"),
        ("וְלֹא שִׁלַּח אֶת-הָעָם", "ולם יטלק אלקום", "and did not release the people"),
    ],
}
