"""Hand-authored alignment triples for Shemot chapter 11."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה למוסי'", "And God said to Moses"),
        ("עוֹד נֶגַע אֶחָד אָבִיא עַל-פַּרְעֹה וְעַל-מִצְרַיִם",
         "קד בקי בלא ואחד אחלה בפרעון ואלמצריון",
         "One affliction yet remains, which I shall bring upon Pharaoh and upon the Egyptians"),
        ("אַחֲרֵי-כֵן יְשַׁלַּח אֶתְכֶם מִזֶּה", "בעד ד'אלך יטלקכם מן ההנא",
         "after that he shall release you from here"),
        ("כְּשַׁלְּחוֹ--כָּלָה גָּרֵשׁ יְגָרֵשׁ אֶתְכֶם מִזֶּה",
         "וענד אטלאקה. גמלה. יטרדכם מן ההנא",
         "and at his releasing, he shall altogether drive you out from here"),
    ],
    2: [
        ("דַּבֶּר-נָא בְּאָזְנֵי הָעָם", "מר אלקום", "Command the people"),
        ("וְיִשְׁאֲלוּ אִישׁ מֵאֵת רֵעֵהוּ וְאִשָּׁה מֵאֵת רְעוּתָהּ",
         "באן יסתוהב אלרגל מן צאחבה. ואלאמראה מן צאחבתהא",
         "that each man ask as a gift from his neighbor, and each woman from her neighbor"),
        ("כְּלֵי-כֶסֶף וּכְלֵי זָהָב", "אניה' פצ'ה ואניה' ד'הב",
         "vessels of silver and vessels of gold"),
    ],
    3: [
        ("וַיִּתֵּן יְהוָה אֶת-חֵן הָעָם בְּעֵינֵי מִצְרָיִם",
         "פאעטא אללה אלקום חצ'אא ענד אלמצריון",
         "And God granted the people favor in the eyes of the Egyptians"),
        ("גַּם הָאִישׁ מֹשֶׁה גָּדוֹל מְאֹד בְּאֶרֶץ מִצְרַיִם",
         "ואמא מוסי' אלרסול. פ עצ'ם גדא פי בלד מצר",
         "And as for Moses the messenger — he was very great in the land of Egypt"),
        ("בְּעֵינֵי עַבְדֵי-פַרְעֹה וּבְעֵינֵי הָעָם",
         "ענד קואד פרעון וענד אלקום",
         "in the eyes of Pharaoh's officers and in the eyes of the people"),
    ],
    4: [
        ("וַיֹּאמֶר מֹשֶׁה", "פקאל מוסי'", "And Moses said"),
        ("כֹּה אָמַר יְהוָה", "כד'א קאל אללה", "Thus says God"),
        ("כַּחֲצֹת הַלַּיְלָה אֲנִי יוֹצֵא בְּתוֹךְ מִצְרָיִם",
         "שביה בנצף אלליל. אנא מתגלי פי בלד מצר",
         "At about the middle of the night I shall appear in the land of Egypt"),
    ],
    5: [
        ("וּמֵת כָּל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם", "וימות כל בכר פי בלד מצר",
         "and every firstborn in the land of Egypt shall die"),
        ("מִבְּכוֹר פַּרְעֹה הַיֹּשֵׁב עַל-כִּסְאוֹ",
         "מן בכר פרעון אלגאלס עלי' כרסיה",
         "from the firstborn of Pharaoh who sits upon his throne"),
        ("עַד בְּכוֹר הַשִּׁפְחָה אֲשֶׁר אַחַר הָרֵחָיִם",
         "אלי' בכר אלאמה. אלתי ורא אלרחא",
         "to the firstborn of the maidservant who is behind the millstone"),
        ("וְכֹל בְּכוֹר בְּהֵמָה", "וגמיע בכור אלבהאים",
         "and all the firstborn of the beasts"),
    ],
    6: [
        ("וְהָיְתָה צְעָקָה גְדֹלָה בְּכָל-אֶרֶץ מִצְרָיִם",
         "ויכון צראך' עצ'ים פי גמיע בלד מצר",
         "And there shall be a great outcry throughout all the land of Egypt"),
        ("אֲשֶׁר כָּמֹהוּ לֹא נִהְיָתָה", "מא לם יכון מת'לה",
         "the like of which has never been"),
        ("וְכָמֹהוּ לֹא תֹסִף", "ולא יעאוד איצ'א", "and the like of which shall not occur again"),
    ],
    7: [
        ("וּלְכֹל בְּנֵי יִשְׂרָאֵל לֹא יֶחֱרַץ-כֶּלֶב לְשֹׁנוֹ",
         "ולגמיע בני אסראיל. לא ינבח כלב בפאה",
         "But against all the sons of Israel, no dog shall bark with its mouth"),
        ("לְמֵאִישׁ וְעַד-בְּהֵמָה", "פמא פוקה מן אלאד'א. מן נסאהם אלי' בהאימהם",
         "of anything above it in harm — from their people to their beasts"),
        ("לְמַעַן תֵּדְעוּן אֲשֶׁר יַפְלֶה יְהוָה בֵּין מִצְרַיִם וּבֵין יִשְׂרָאֵל",
         "לכי תעלמון. מא יביין אללה. בין אלמצריון ובין בני אסראיל",
         "so that you may know what God distinguishes between the Egyptians and the sons of Israel"),
    ],
    8: [
        ("וְיָרְדוּ כָל-עֲבָדֶיךָ אֵלֶּה אֵלַי וְהִשְׁתַּחֲווּ-לִי",
         "פיציר אליי גמיע עבידך הולאי ויסגדון לי",
         "Then all these servants of yours shall come to me and bow down to me"),
        ("לֵאמֹר צֵא אַתָּה וְכָל-הָעָם אֲשֶׁר-בְּרַגְלֶיךָ",
         "קאילין. אכ'רג אנת וגמיע אלקום אלדין מעך",
         "saying: Go out — you and all the people who are with you"),
        ("וְאַחֲרֵי-כֵן אֵצֵא", "ובעד ד'אלך אכ'רג", "and after that I shall go out"),
        ("וַיֵּצֵא מֵעִם-פַּרְעֹה בָּחֳרִי-אָף", "ת'ם כ'רג מן ענד פרעון בשדה' ג'צ'ב מנה",
         "Then he went out from Pharaoh's presence in great intensity of anger at him"),
    ],
    9: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי'", "Then God said to Moses"),
        ("לֹא-יִשְׁמַע אֲלֵיכֶם פַּרְעֹה", "לא יקבל מנכמא פרעון",
         "Pharaoh will not accept from the two of you"),
        ("לְמַעַן רְבוֹת מוֹפְתַי בְּאֶרֶץ מִצְרָיִם",
         "לכי תכת'ר בראהיני פי בלד מצר",
         "so that My proofs may be multiplied in the land of Egypt"),
    ],
    10: [
        ("וּמֹשֶׁה וְאַהֲרֹן עָשׂוּ אֶת-כָּל-הַמֹּפְתִים הָאֵלֶּה--לִפְנֵי פַרְעֹה",
         "ומוסי' והרון. צנעא גמיע הד'ה אלבראהין בחצ'רה' פרעון",
         "And Moses and Aaron performed all these proofs in Pharaoh's presence"),
        ("וַיְחַזֵּק יְהוָה אֶת-לֵב פַּרְעֹה", "פשדד אללה קלבה",
         "and God hardened his heart"),
        ("וְלֹא-שִׁלַּח אֶת-בְּנֵי-יִשְׂרָאֵל מֵאַרְצוֹ",
         "ולם יטלק בני אסראיל מן בלדה",
         "and he did not release the sons of Israel from his land"),
    ],
}
