"""Hand-authored alignment triples for Shemot chapter 15."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("אָז יָשִׁיר-מֹשֶׁה וּבְנֵי יִשְׂרָאֵל אֶת-הַשִּׁירָה הַזֹּאת לַיהוָה",
         "חיניד' סבח מוסי' ובני אסראיל. הד'ה אלתסבחה ללה",
         "At that time Moses and the sons of Israel sang this hymn of praise to God"),
        ("וַיֹּאמְרוּ לֵאמֹר אָשִׁירָה לַיהוָה כִּי-גָאֹה גָּאָה",
         "וקאלו אגמעין. נסבח ללה אד' אקתדר אקתדארא",
         "and they all said together: 'Let us praise God, for He has triumphed mightily"),
        ("סוּס וְרֹכְבוֹ רָמָה בַיָּם", "אלכ'יל ורכאבהא רמא בהם פי אלבחר",
         "the horse and its rider He hurled into the sea.'"),
    ],
    2: [
        ("עָזִּי וְזִמְרָת יָהּ", "עזי ומגדי אלאזלי",
         "'My strength and my glory is the Eternal"),
        ("וַיְהִי-לִי לִישׁוּעָה", "אלד'י כאן לי גות'א",
         "who was my salvation"),
        ("זֶה אֵלִי וְאַנְוֵהוּ", "הד'א טאיקי אוי אליה",
         "this is my stronghold — I take refuge in Him"),
        ("אֱלֹהֵי אָבִי וַאֲרֹמְמֶנְהוּ", "אלאה אבי ארפעה",
         "the God of my father — I exalt Him.'"),
    ],
    3: [
        ("יְהוָה אִישׁ מִלְחָמָה יְהוָה שְׁמוֹ", "אללה ד'ו אלמלאחם. אללה אסמה",
         "'God is the master of battles — God is His name.'"),
    ],
    4: [
        ("מַרְכְּבֹת פַּרְעֹה וְחֵילוֹ יָרָה בַיָּם", "מראכב פרעון. וגנדה זדא בהם פי אלבחר",
         "'The chariots of Pharaoh and his army He swept away into the sea"),
        ("וּמִבְחַר שָׁלִשָׁיו טֻבְּעוּ בְיַם-סוּף", "וכ'יאר קואדה ג'רקו פי בחר אלקלזם",
         "and the choicest of his officers were drowned in the Sea of Qulzum (Red Sea).'"),
    ],
    5: [
        ("תְּהֹמֹת יְכַסְיֻמוּ", "אלג'מר ג'טאהם", "'The deep covered them"),
        ("יָרְדוּ בִמְצוֹלֹת כְּמוֹ- אָבֶן", "פנזלו פי אלקער כאלחגארה",
         "they went down to the bottom like stones.'"),
    ],
    6: [
        ("יְמִינְךָ יְהוָה נֶאְדָּרִי בַּכֹּחַ", "ימינך יא רב. גזילה' אלקווה",
         "'Your right hand, O Lord, is great in power"),
        ("יְמִינְךָ יְהוָה תִּרְעַץ אוֹיֵב", "ימינך יא רב תרהב אלאעדא",
         "Your right hand, O Lord, strikes terror into the enemies.'"),
    ],
    7: [
        ("וּבְרֹב גְּאוֹנְךָ תַּהֲרֹס קָמֶיךָ", "ובכת'רה' אקתדארך תדהם מקאומיך",
         "'And by Your abundant might You demolish Your adversaries"),
        ("תְּשַׁלַּח חֲרֹנְךָ--יֹאכְלֵמוֹ כַּקַּשׁ", "תבעת' בס'כטך. יאכלהם כאלקש",
         "You send forth Your wrath — it consumes them like stubble.'"),
    ],
    8: [
        ("וּבְרוּחַ אַפֶּיךָ נֶעֶרְמוּ מַיִם", "ובריח ג'צ'בך תערם אלמא",
         "'And by the wind of Your anger the water was heaped up"),
        ("נִצְּבוּ כְמוֹ-נֵד נֹזְלִים", "ווקפת כאלאטואד אלהואטל",
         "the flowing waters stood still like towering mountains"),
        ("קָפְאוּ תְהֹמֹת בְּלֶב-יָם", "וגמדת אלג'מר פי קלב אלבחר",
         "and the deep was frozen in the heart of the sea.'"),
    ],
    9: [
        ("אָמַר אוֹיֵב אֶרְדֹּף אַשִּׂיג", "ואד' קאל אלעדו. אכלבהם פאלחקהם",
         "'When the enemy said: I will pursue them and overtake them"),
        ("אֲחַלֵּק שָׁלָל תִּמְלָאֵמוֹ נַפְשִׁי", "ואקסם סלבהם. תשתפי מנהם נפסי",
         "and divide their spoil — my soul shall have its fill of satisfaction from them"),
        ("אָרִיק חַרְבִּי תּוֹרִישֵׁמוֹ יָדִי", "אגרד סיפי. ותקרצ'הם ידי",
         "I shall draw my sword, and my hand shall cut them down.'"),
    ],
    10: [
        ("נָשַׁפְתָּ בְרוּחֲךָ כִּסָּמוֹ יָם", "אהבבת בריחך פג'טאהם אלבחר",
         "'You blew with Your wind and the sea covered them"),
        ("צָלְלוּ כַּעוֹפֶרֶת בְּמַיִם אַדִּירִים", "ורסכו כאלרצאץ. פי אלמא אלג'זיר",
         "and they sank like lead in the mighty water.'"),
    ],
    11: [
        ("מִי-כָמֹכָה בָּאֵלִם יְהוָה", "מן מת'לך פי אלמעבודאת יא רב",
         "'Who is like You among the worshipped, O Lord"),
        ("מִי כָּמֹכָה נֶאְדָּר בַּקֹּדֶשׁ", "מן מת'לך אלגליל אלמקדס",
         "Who is like You, the majestic and the holy"),
        ("נוֹרָא תְהִלֹּת עֹשֵׂה פֶלֶא", "מכ'יף אלמדאיח צאנע אלאעגובאת",
         "awesome in praise, the maker of wonders?'"),
    ],
    12: [
        ("נָטִיתָ יְמִינְךָ--תִּבְלָעֵמוֹ אָרֶץ", "מדדת ימינך. פאבתלעתהם אלארץ'",
         "'You stretched forth Your right hand — and the earth swallowed them.'"),
    ],
    13: [
        ("נָחִיתָ בְחַסְדְּךָ עַם-זוּ גָּאָלְתָּ", "וסיירת בפצ'לך אלשעב אלד'ין פככתהם",
         "'And You led in Your grace the people whom You redeemed"),
        ("נֵהַלְתָּ בְעָזְּךָ אֶל-נְוֵה קָדְשֶׁךָ", "וסקתהם בעזך אלי' מאוא קדסך",
         "and You guided them in Your might to Your holy dwelling.'"),
    ],
    14: [
        ("שָׁמְעוּ עַמִּים יִרְגָּזוּן", "סמעת אלאמם פרגזת",
         "'The nations heard and trembled"),
        ("חִיל אָחַז יֹשְׁבֵי פְּלָשֶׁת", "ואכ'ד' אלטלק סכאן פלסטין",
         "and birth-pangs seized the inhabitants of Philistia.'"),
    ],
    15: [
        ("אָז נִבְהֲלוּ אַלּוּפֵי אֱדוֹם", "חיניד' דהשו צנאדיד אדום",
         "'At that time the chiefs of Edom were dismayed"),
        ("אֵילֵי מוֹאָב יֹאחֲזֵמוֹ רָעַד", "ואגלא מואב. אכ'ד'תהם אלרעדה",
         "and the nobles of Moab — trembling seized them"),
        ("נָמֹגוּ כֹּל יֹשְׁבֵי כְנָעַן", "ומאג גמיע סכאן כנעאן",
         "and all the inhabitants of Canaan were convulsed.'"),
    ],
    16: [
        ("תִּפֹּל עֲלֵיהֶם אֵימָתָה וָפַחַד", "תקע עליהם אלהיבה ואלפזע",
         "'May dread and terror fall upon them"),
        ("בִּגְדֹל זְרוֹעֲךָ יִדְּמוּ כָּאָבֶן", "ב עצ'ם קדרתך יסכתון כאלחגארה",
         "by the greatness of Your power may they be still as stone"),
        ("עַד- יַעֲבֹר עַמְּךָ יְהוָה", "אלי' אן יגוז שעבך יא רב",
         "until Your people pass over, O Lord"),
        ("עַד-יַעֲבֹר עַם-זוּ קָנִיתָ", "אלי' אן יגוז אלשעב אלד'י מלכתהם",
         "until the people pass over whom You have made Your own.'"),
    ],
    17: [
        ("תְּבִאֵמוֹ וְתִטָּעֵמוֹ בְּהַר נַחֲלָתְךָ", "גואזא תאתי בהם. פתג'רסהם פי גבל נחלתך",
         "'One by one You shall bring them in and plant them on the mountain of Your inheritance"),
        ("מָכוֹן לְשִׁבְתְּךָ פָּעַלְתָּ יְהוָה", "מהייא לסכינתך. צנעתה יא רב",
         "prepared as a dwelling for You; You have made it, O Lord, a holy abode"),
        ("מִקְּדָשׁ אֲדֹנָי כּוֹנְנוּ יָדֶיךָ", "מקדס. יא רב אצלחתה ידך",
         "O Lord, Your hands have established it.'"),
    ],
    18: [
        ("יְהוָה יִמְלֹךְ לְעֹלָם וָעֶד", "אללה מלך אלדהר ואלאבד",
         "'God is King for ever and ever.'"),
    ],
    19: [
        ("כִּי בָא סוּס פַּרְעֹה בְּרִכְבּוֹ וּבְפָרָשָׁיו בַּיָּם",
         "אד' דכ'ל כ'יל פרעון. ומראכבה. ופרסאנה פי אלבחר",
         "For when the horses of Pharaoh, his chariots, and his horsemen entered into the sea"),
        ("וַיָּשֶׁב יְהוָה עֲלֵהֶם אֶת-מֵי הַיָּם", "פרד אללה עליהם מא אלבחר",
         "God turned back upon them the waters of the sea"),
        ("וּבְנֵי יִשְׂרָאֵל הָלְכוּ בַיַּבָּשָׁה בְּתוֹךְ הַיָּם",
         "וסארו בני אסראיל. פי אליבאס פי וסט אלבחר",
         "and the sons of Israel walked on the dry land in the midst of the sea."),
    ],
    20: [
        ("וַתִּקַּח מִרְיָם הַנְּבִיאָה אֲחוֹת אַהֲרֹן אֶת-הַתֹּף--בְּיָדָהּ",
         "ת'ם אכד'ת מרים אלנבייה. אכת הרון. דפא פי ידהא",
         "Then Miriam the prophetess, the sister of Aaron, took a tambourine in her hand"),
        ("וַתֵּצֶאןָ כָל-הַנָּשִׁים אַחֲרֶיהָ בְּתֻפִּים וּבִמְחֹלֹת",
         "פכ'רג גמיע אלנסא וראהא. בדפוף וטבול",
         "and all the women went out after her with tambourines and drums."),
    ],
    21: [
        ("וַתַּעַן לָהֶם מִרְיָם שִׁירוּ לַיהוָה כִּי-גָאֹה גָּאָה",
         "וגאובתהן מרים. סבחו ללה אד' אקתדר אקתדארא",
         "And Miriam led them in response: 'Praise God, for He has triumphed mightily"),
        ("סוּס וְרֹכְבוֹ רָמָה בַיָּם", "אלכ'יל ורכאבהא רמא בהם פי אלבחר",
         "the horse and its rider He hurled into the sea.'"),
    ],
    22: [
        ("וַיַּסַּע מֹשֶׁה אֶת-יִשְׂרָאֵל מִיַּם-סוּף", "ורחל מוסי' בני אסראיל מן בחר אלקלזם",
         "And Moses moved the sons of Israel on from the Sea of Qulzum"),
        ("וַיֵּצְאוּ אֶל-מִדְבַּר-שׁוּר", "וכ'רגו אלי' ברייה' שור",
         "and they went out into the wilderness of Shur"),
        ("וַיֵּלְכוּ שְׁלֹשֶׁת-יָמִים בַּמִּדְבָּר וְלֹא-מָצְאוּ מָיִם",
         "וסארו ת'לאתה' איאם. פי אלברייה ולם יגדו מאא",
         "and they traveled three days in the wilderness and found no water."),
    ],
    23: [
        ("וַיָּבֹאוּ מָרָתָה--וְלֹא יָכְלוּ לִשְׁתֹּת מַיִם מִמָּרָה",
         "וגאו אלי' אלמרירה. ולם יטיקו אן ישרבו מנהא מאא",
         "And they came to the Bitterness, and they could not drink water from it"),
        ("כִּי מָרִים הֵם", "לאנה מר", "for it was bitter"),
        ("עַל-כֵּן קָרָא-שְׁמָהּ מָרָה", "ולד'אלך סמית אלמרירה",
         "and therefore it was named the Bitterness."),
    ],
    24: [
        ("וַיִּלֹּנוּ הָעָם עַל-מֹשֶׁה לֵּאמֹר מַה-נִּשְׁתֶּה",
         "פתד'מר אלקום. עלי' מוסי קאילין מא נשרב",
         "And the people murmured against Moses, saying: 'What shall we drink?'"),
    ],
    25: [
        ("וַיִּצְעַק אֶל-יְהוָה", "פדעא אלי' אללה", "And he cried out to God"),
        ("וַיּוֹרֵהוּ יְהוָה עֵץ וַיַּשְׁלֵךְ אֶל-הַמַּיִם וַיִּמְתְּקוּ הַמָּיִם",
         "פדלה עלי' שגרה. טרח מנהא פי אלמא פחלא",
         "and He directed him to a tree, and he cast branches of it into the water, and it became sweet"),
        ("שָׂם לוֹ חֹק וּמִשְׁפָּט", "ת'ם צייר לה. רסומא ואחכאמא",
         "There He established for them ordinances and laws"),
        ("וְשָׁם נִסָּהוּ", "ות'ם אמתחנה", "and there He put them to the test."),
    ],
    26: [
        ("וַיֹּאמֶר אִם-שָׁמוֹעַ תִּשְׁמַע לְקוֹל יְהוָה אֱלֹהֶיךָ",
         "וקאל אן קבלת אמר אללה רבך",
         "And He said: 'If you accept the command of God your Lord"),
        ("וְהַיָּשָׁר בְּעֵינָיו תַּעֲשֶׂה", "וצנעת אלמסתקים ענדה",
         "and do what is right in His sight"),
        ("וְהַאֲזַנְתָּ לְמִצְו‍ֹתָיו וְשָׁמַרְתָּ כָּל-חֻקָּיו",
         "ואנצתת אלי' וצאיאה. וחפצ'ת גמיע רסומה",
         "and hearken to His commandments, and keep all His ordinances"),
        ("כָּל-הַמַּחֲלָה אֲשֶׁר-שַׂמְתִּי בְמִצְרַיִם לֹא-אָשִׂים עָלֶיךָ",
         "פגמיע אלאמראץ'. אלתי אחללתהא באלמצריון לא אחל פיך שייא מנהא",
         "then all the diseases which I brought upon the Egyptians I shall bring upon you none of them"),
        ("כִּי אֲנִי יְהוָה רֹפְאֶךָ", "לאני אללה מעאפיך",
         "for I am God your healer.'"),
    ],
    27: [
        ("וַיָּבֹאוּ אֵילִמָה", "ת'ם גאו אלי' אילים", "Then they came to Elim"),
        ("וְשָׁם שְׁתֵּים עֶשְׂרֵה עֵינֹת מַיִם וְשִׁבְעִים תְּמָרִים",
         "ות'ם את'ני עשר עין מא וסבעין נכ'לה",
         "and there were twelve springs of water and seventy palm trees"),
        ("וַיַּחֲנוּ-שָׁם עַל-הַמָּיִם", "פנזלו ת'ם עלי' אלמא",
         "and they encamped there by the water."),
    ],
}
