"""Hand-authored alignment triples for Shemot chapter 28."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאַתָּה הַקְרֵב אֵלֶיךָ אֶת-אַהֲרֹן אָחִיךָ וְאֶת-בָּנָיו אִתּוֹ",
         "ואנת איצ'א. פקדם אליך הרון אכ'יך ובניה מעה",
         "And you also — bring forward to yourself Aaron your brother and his sons with him"),
        ("מִתּוֹךְ בְּנֵי יִשְׂרָאֵל", "מן בין בני אסראיל",
         "from among the sons of Israel"),
        ("לְכַהֲנוֹ-לִי", "ליאמו לי", "that they may lead worship for Me"),
        ("אַהֲרֹן--נָדָב וַאֲבִיהוּא אֶלְעָזָר וְאִיתָמָר בְּנֵי אַהֲרֹן",
         "הרון. נדב ואביהוא. אלעזר ואיתמר בניה",
         "Aaron, Nadab and Abihu, Eleazar and Ithamar, his sons."),
    ],
    2: [
        ("וְעָשִׂיתָ בִגְדֵי-קֹדֶשׁ לְאַהֲרֹן אָחִיךָ", "ואצנע ת'יאב קדס להרון אכ'יך",
         "And make garments of holiness for Aaron your brother"),
        ("לְכָבוֹד וּלְתִפְאָרֶת", "לכראמה ופכ'ר", "for honor and glory."),
    ],
    3: [
        ("וְאַתָּה תְּדַבֵּר אֶל-כָּל-חַכְמֵי-לֵב", "ואנת כלם כל חכים",
         "And you — speak to every wise of heart"),
        ("אֲשֶׁר מִלֵּאתִיו רוּחַ חָכְמָה", "אכמלת פיה עלם רוח אלחכמה",
         "in whom I have perfected the knowledge of the spirit of wisdom"),
        ("וְעָשׂוּ אֶת-בִּגְדֵי אַהֲרֹן לְקַדְּשׁוֹ", "אן יצנעו ת'יאב הרון. לתקדיסה",
         "that they make the garments of Aaron, to consecrate him"),
        ("לְכַהֲנוֹ-לִי", "ליאם לי", "that he may lead worship for Me."),
    ],
    4: [
        ("וְאֵלֶּה הַבְּגָדִים אֲשֶׁר יַעֲשׂוּ", "והד'ה אלת'יאב אלד'י יצנעוהא",
         "And these are the garments which they shall make"),
        ("חֹשֶׁן וְאֵפוֹד וּמְעִיל וּכְתֹנֶת תַּשְׁבֵּץ מִצְנֶפֶת וְאַבְנֵט",
         "בדנה וצדרה וממטר. ותוניה מושאה ועמאמה וזנאר",
         "a breastpiece and an ephod and a robe, and an embroidered tunic and a turban and a sash"),
        ("וְעָשׂוּ בִגְדֵי-קֹדֶשׁ לְאַהֲרֹן אָחִיךָ וּלְבָנָיו",
         "ויצנעו ת'יאב קדס. להרון אכ'יך. ולבניה",
         "And they shall make garments of holiness for Aaron your brother and for his sons"),
        ("לְכַהֲנוֹ-לִי", "ליאמו לי", "that they may lead worship for Me."),
    ],
    5: [
        ("וְהֵם יִקְחוּ אֶת-הַזָּהָב", "והם יאכ'דו אלד'הב",
         "And they shall take the gold"),
        ("וְאֶת-הַתְּכֵלֶת וְאֶת-הָאַרְגָּמָן", "ואלאסמאנגון ואלארגואן",
         "and the blue, and the purple"),
        ("וְאֶת-תּוֹלַעַת הַשָּׁנִי וְאֶת-הַשֵּׁשׁ", "ואלצבג' אלקרמז ואלעשר",
         "and the scarlet dye, and the fine linen."),
    ],
    6: [
        ("וְעָשׂוּ אֶת-הָאֵפֹד", "ויצנעו אלצדרה", "And they shall make the ephod"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן תּוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר",
         "מן ד'הב ואסמאנגון וארגואן. וצבג' קרמז. וע'שר משזור",
         "of gold and blue and purple, and scarlet dye, and twisted fine linen"),
        ("מַעֲשֵׂה חֹשֵׁב", "צנעה' חאד'ק", "the work of a skilled craftsman."),
    ],
    7: [
        ("שְׁתֵּי כְתֵפֹת חֹבְרֹת יִהְיֶה-לּוֹ", "ולהא גיבאן מכ'ייטאן",
         "And it shall have two sewn pockets"),
        ("אֶל-שְׁנֵי קְצוֹתָיו", "תכון עלי' טרפיהא",
         "which shall be upon its two edges."),
    ],
    8: [
        ("וְחֵשֶׁב אֲפֻדָּתוֹ אֲשֶׁר עָלָיו", "ושפשג אלצדרה אלד'י עליהא",
         "And the binding-straps of the ephod which are upon it"),
        ("כְּמַעֲשֵׂהוּ מִמֶּנּוּ יִהְיֶה", "כצנעתהא יכון מת'להא",
         "shall be like its workmanship — of the same make as it"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי--וְשֵׁשׁ מָשְׁזָר",
         "מן ד'הב ואסמאנגון וארגואן. וצבג' קרמז ועשר משזור",
         "of gold and blue and purple, and scarlet dye and twisted fine linen."),
    ],
    9: [
        ("וְלָקַחְתָּ אֶת-שְׁתֵּי אַבְנֵי-שֹׁהַם", "וכד' חגרי אלבלור",
         "And take two crystal stones"),
        ("וּפִתַּחְתָּ עֲלֵיהֶם שְׁמוֹת בְּנֵי יִשְׂרָאֵל",
         "ואנקש עליהמא אסמא בני אסראיל",
         "and engrave upon them the names of the sons of Israel —"),
    ],
    10: [
        ("שִׁשָּׁה מִשְּׁמֹתָם עַל הָאֶבֶן הָאֶחָת",
         "סתה מנהא. עלי' אלחגר אלואחד",
         "six of them upon one stone"),
        ("וְאֶת-שְׁמוֹת הַשִּׁשָּׁה הַנּוֹתָרִים עַל-הָאֶבֶן הַשֵּׁנִית",
         "ואלסתה אלאסמא אלבאקיה. עלי' אלחגר אלת'אניה",
         "and the six remaining names upon the second stone"),
        ("כְּתוֹלְדֹתָם", "כתיאלידהם", "according to their order of birth."),
    ],
    11: [
        ("מַעֲשֵׂה חָרַשׁ אֶבֶן--פִּתּוּחֵי חֹתָם", "צנעה' כ'רט אלגוהר. כנקש אלכ'אתם",
         "In the craft of gem-cutting, like the engraving of a signet-ring"),
        ("תְּפַתַּח אֶת-שְׁתֵּי הָאֲבָנִים עַל-שְׁמֹת בְּנֵי יִשְׂרָאֵל",
         "תנקש עלי' אלחגרין. אסמא בני אסראיל",
         "you shall engrave upon the two stones the names of the sons of Israel"),
        ("מֻסַבֹּת מִשְׁבְּצוֹת זָהָב תַּעֲשֶׂה אֹתָם",
         "ואצנעהא. תחיט בהא עיון מן ד'הב",
         "and make them surrounded by settings of gold."),
    ],
    12: [
        ("וְשַׂמְתָּ אֶת-שְׁתֵּי הָאֲבָנִים עַל כִּתְפֹת הָאֵפֹד",
         "וצייר אלחגרין פי גיבי אלצדרה",
         "And place the two stones in the pockets of the ephod"),
        ("אַבְנֵי זִכָּרֹן לִבְנֵי יִשְׂרָאֵל", "חגארה' ד'כרא לבני אסראיל",
         "stones of remembrance for the sons of Israel"),
        ("וְנָשָׂא אַהֲרֹן אֶת-שְׁמוֹתָם לִפְנֵי יְהוָה",
         "ויחמל הרון אסמאיהם. בין ידי אללה",
         "and Aaron shall bear their names before God"),
        ("עַל-שְׁתֵּי כְתֵפָיו--לְזִכָּרֹן", "עלי' כתפיה ד'כרא",
         "upon his two shoulders, as a remembrance."),
    ],
    13: [
        ("וְעָשִׂיתָ מִשְׁבְּצֹת זָהָב", "ואצנע עיון מן ד'הב",
         "And make settings of gold."),
    ],
    14: [
        ("וּשְׁתֵּי שַׁרְשְׁרֹת זָהָב טָהוֹר מִגְבָּלֹת",
         "וסלסלתין מן ד'הב כ'אלץ. מעתדלתין",
         "And two chains of pure gold, made even"),
        ("תַּעֲשֶׂה אֹתָם מַעֲשֵׂה עֲבֹת", "תצנעהמא צנעה' צ'פר",
         "you shall make them in the work of braiding"),
        ("וְנָתַתָּה אֶת-שַׁרְשְׁרֹת הָעֲבֹתֹת עַל-הַמִּשְׁבְּצֹת",
         "ועלק אלסלסלתין אלמצ'פורתין עלי' אלעיון",
         "and hang the two braided chains upon the settings."),
    ],
    15: [
        ("וְעָשִׂיתָ חֹשֶׁן מִשְׁפָּט מַעֲשֵׂה חֹשֵׁב",
         "ואצנע בדנה מהיאה צנעה' חאד'ק",
         "And make a prepared breastpiece, the work of a skilled craftsman"),
        ("כְּמַעֲשֵׂה אֵפֹד תַּעֲשֶׂנּוּ", "כצנעה' אלצדרה",
         "like the workmanship of the ephod"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר--תַּעֲשֶׂה אֹתוֹ",
         "מן ד'הב ואסמאנגון וארגואן. וצבג' קרמז ועשר משזור תצנעהא",
         "of gold and blue and purple, and scarlet dye and twisted fine linen you shall make it."),
    ],
    16: [
        ("רָבוּעַ יִהְיֶה כָּפוּל", "וליכון מרבעא מצ'אעפא",
         "And it shall be square, doubled"),
        ("זֶרֶת אָרְכּוֹ וְזֶרֶת רָחְבּוֹ", "טולהא שבר וערצ'הא שבר",
         "its length a span and its width a span."),
    ],
    17: [
        ("וּמִלֵּאתָ בוֹ מִלֻּאַת אֶבֶן אַרְבָּעָה טוּרִים אָבֶן",
         "ואנצם פיהא. ארבעה סטור מן נצ'אם אלגוהר",
         "And set in it four rows of gemstones in arrangement"),
        ("טוּר אֹדֶם פִּטְדָה וּבָרֶקֶת--הַטּוּר הָאֶחָד",
         "אלסטר אלאוול. יאקות אחמר וזמרד ואצפר",
         "The first row: a red ruby, and an emerald, and a yellow stone."),
    ],
    18: [
        ("וְהַטּוּר הַשֵּׁנִי--נֹפֶךְ סַפִּיר וְיָהֲלֹם",
         "ואלסטר אלת'אני. כחלי ומהא ובהרמאן",
         "And the second row: a dark blue stone, and a white gleaming stone, and a bahraman stone."),
    ],
    19: [
        ("וְהַטּוּר הַשְּׁלִישִׁי--לֶשֶׁם שְׁבוֹ וְאַחְלָמָה",
         "ואלסטר אלת'אלת'. גזע וסבג ופירוזג",
         "And the third row: an agate, and a jet stone, and a turquoise."),
    ],
    20: [
        ("וְהַטּוּר הָרְבִיעִי--תַּרְשִׁישׁ וְשֹׁהַם וְיָשְׁפֵה",
         "ואלסטר אלראבע. אזרק ובלור ויסף",
         "And the fourth row: a blue stone, and crystal, and jasper"),
        ("מְשֻׁבָּצִים זָהָב יִהְיוּ בְּמִלּוּאֹתָם",
         "ותכון מעיינה בד'הב פי נצ'אמהא",
         "And they shall be aided by gold in their arrangement."),
    ],
    21: [
        ("וְהָאֲבָנִים תִּהְיֶיןָ עַל-שְׁמֹת בְּנֵי-יִשְׂרָאֵל שְׁתֵּים עֶשְׂרֵה",
         "ולתכון אלחגארה עלי' אסמא בני אסראיל. אד' הי את'ני עשר",
         "And the stones shall be according to the names of the sons of Israel — since they are twelve"),
        ("פִּתּוּחֵי חוֹתָם אִישׁ עַל-שְׁמוֹ תִּהְיֶיןָ",
         "כנקש אלכ'אתם אסם כל ואחד עלי' חגרה",
         "like the engraving of a signet-ring, the name of each one upon its stone"),
        ("לִשְׁנֵי עָשָׂר שָׁבֶט", "תכון לאת'ני עשר סבט",
         "they shall be for the twelve tribes."),
    ],
    22: [
        ("וְעָשִׂיתָ עַל-הַחֹשֶׁן שַׁרְשֹׁת גַּבְלֻת מַעֲשֵׂה עֲבֹת",
         "ואצנע לאלבדנה. סלאסל מעתדלה צנעה' צ'פר",
         "And make for the breastpiece even chains, the work of braiding"),
        ("זָהָב טָהוֹר", "מן ד'הב כ'אלץ", "of pure gold."),
    ],
    23: [
        ("וְעָשִׂיתָ עַל-הַחֹשֶׁן שְׁתֵּי טַבְּעוֹת זָהָב",
         "ואצנע להא חלקתין מן ד'הב",
         "And make for it two rings of gold"),
        ("וְנָתַתָּ אֶת-שְׁתֵּי הַטַּבָּעוֹת עַל-שְׁנֵי קְצוֹת הַחֹשֶׁן",
         "ואגעלהמא פי טרפיהא",
         "and set them at its two edges."),
    ],
    24: [
        ("וְנָתַתָּה אֶת-שְׁתֵּי עֲבֹתֹת הַזָּהָב",
         "ועלק [י\"ג ואגעל צ'פירתי אלד'הב",
         "And hang the two golden braids"),
        ("עַל-שְׁתֵּי הַטַּבָּעֹת--אֶל-קְצוֹת הַחֹשֶׁן",
         "עלי' אלחלקתין אלתי פי טרפי אלבדנה",
         "upon the two rings which are at the two edges of the breastpiece."),
    ],
    25: [
        ("וְאֵת שְׁתֵּי קְצוֹת שְׁתֵּי הָעֲבֹתֹת",
         "וטרפי אלצפירתין, אלאכ'רתין",
         "And the other two ends of the two braids"),
        ("תִּתֵּן עַל-שְׁתֵּי הַמִּשְׁבְּצוֹת", "תעלקהמא עלי' אלעיון",
         "you shall hang upon the two settings"),
        ("וְנָתַתָּה עַל-כִּתְפוֹת הָאֵפֹד אֶל-מוּל פָּנָיו",
         "פתציר עלי' גיבי אלצדרה מן מקדמהא",
         "so that they come to rest upon the two pockets of the ephod, at its front."),
    ],
    26: [
        ("וְעָשִׂיתָ שְׁתֵּי טַבְּעוֹת זָהָב וְשַׂמְתָּ אֹתָם עַל-שְׁנֵי קְצוֹת הַחֹשֶׁן",
         "ואצנע איצ'א חלקתין מן ד'הב. ואגעלהמא פי טרפי אלבדנה",
         "And make also two rings of gold, and set them at the two edges of the breastpiece"),
        ("עַל-שְׂפָתוֹ אֲשֶׁר אֶל-עֵבֶר הָאֵפֹד בָּיְתָה",
         "פי חאשיתהא. אלתי אלי' גאנב אלצדרה מן דאכ'ל",
         "upon its border which is on the side of the ephod, from within."),
    ],
    27: [
        ("וְעָשִׂיתָ שְׁתֵּי טַבְּעוֹת זָהָב וְנָתַתָּה אֹתָם עַל-שְׁתֵּי כִתְפוֹת הָאֵפוֹד",
         "ואצנע איצ'א חלקתין מן ד'הב. ואגעלהמא באזא גיבי אלצדרה",
         "And make also two rings of gold, and set them opposite the two pockets of the ephod"),
        ("מִלְּמַטָּה מִמּוּל פָּנָיו", "מן אספל. ממא ילי וגההא",
         "from below, on the side facing its front"),
        ("לְעֻמַּת מַחְבַּרְתּוֹ--מִמַּעַל לְחֵשֶׁב הָאֵפוֹד",
         "אמאם תאליפהא. פוק שפשגהא",
         "opposite the place of its joining, above its binding-straps."),
    ],
    28: [
        ("וְיִרְכְּסוּ אֶת-הַחֹשֶׁן מִטַּבְּעֹתָו אֶל-טַבְּעֹת הָאֵפוֹד",
         "ויחבכונהא. מן חלקהא אלי' חלק אלצדרה",
         "And they shall fasten it — from its rings to the rings of the breastpiece"),
        ("בִּפְתִיל תְּכֵלֶת", "בסלך מן אסמאנגון", "with a cord of blue"),
        ("לִהְיוֹת עַל-חֵשֶׁב הָאֵפוֹד", "חתי' תציר פוק שפשגהא",
         "so that it shall rest above its binding-straps"),
        ("וְלֹא-יִזַּח הַחֹשֶׁן מֵעַל הָאֵפוֹד", "ולא תזול ענהא",
         "and not come loose from it."),
    ],
    29: [
        ("וְנָשָׂא אַהֲרֹן אֶת-שְׁמוֹת בְּנֵי-יִשְׂרָאֵל בְּחֹשֶׁן הַמִּשְׁפָּט",
         "ויחמל הרון אסמא בני אסראיל פי אלבדנה אלמהיאה",
         "And Aaron shall bear the names of the sons of Israel in the prepared breastpiece"),
        ("עַל-לִבּוֹ--בְּבֹאוֹ אֶל-הַקֹּדֶשׁ", "עלי' צדרה פי דכולה אלקדס",
         "upon his chest, when he enters the sanctuary"),
        ("לְזִכָּרֹן לִפְנֵי-יְהוָה תָּמִיד", "ד'כרא בין ידי אללה דאימא",
         "as a remembrance before God — always."),
    ],
    30: [
        ("וְנָתַתָּ אֶל-חֹשֶׁן הַמִּשְׁפָּט אֶת-הָאוּרִים וְאֶת-הַתֻּמִּים",
         "ואגעל פי אלבדנה אלמהיאה. אלאנואר ואלצחאיח",
         "And place in the prepared breastpiece the Lights and the Truths"),
        ("וְהָיוּ עַל-לֵב אַהֲרֹן בְּבֹאוֹ לִפְנֵי יְהוָה",
         "ותכון עלי' צדר הרון פי דכולה בין ידי אללה",
         "and they shall be upon Aaron's chest when he enters before God"),
        ("וְנָשָׂא אַהֲרֹן אֶת-מִשְׁפַּט בְּנֵי-יִשְׂרָאֵל עַל-לִבּוֹ",
         "ויחמל הרון. היאה' בני אסראיל עלי' קלבה",
         "and Aaron shall bear the ordinance of the sons of Israel upon his heart"),
        ("לִפְנֵי יְהוָה--תָּמִיד", "בין ידי אללה דאימא",
         "before God — always."),
    ],
    31: [
        ("וְעָשִׂיתָ אֶת-מְעִיל הָאֵפוֹד", "ואצנע ממטר אלצדרה",
         "And make the robe of the ephod"),
        ("כְּלִיל תְּכֵלֶת", "גמלתה מן אסמאנגון",
         "the work of a weaver — the whole of it of blue."),
    ],
    32: [
        ("וְהָיָה פִי-רֹאשׁוֹ בְּתוֹכוֹ", "ויכון פאה אלד'י הו ראסה פי וסטה",
         "And its opening, which is at its top, shall be in its center"),
        ("שָׂפָה יִהְיֶה לְפִיו סָבִיב מַעֲשֵׂה אֹרֵג",
         "וחאשיה תחיט בה מסתדירא צנעה' חאיך",
         "and a border shall surround it all around — the work of a weaver"),
        ("כְּפִי תַחְרָא יִהְיֶה-לּוֹ--לֹא יִקָּרֵעַ",
         "כפם אלדרע. יציר לה ללא יכ'תרק",
         "like the opening of a coat of mail it shall be for it, so that it shall not tear."),
    ],
    33: [
        ("וְעָשִׂיתָ עַל-שׁוּלָיו רִמֹּנֵי תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי",
         "ואצנע פי ד'ילה. רמאמין מן אסמאנגון וארגואן וצבג' קרמז",
         "And make upon its hem pomegranates of blue and purple and scarlet dye"),
        ("עַל-שׁוּלָיו סָבִיב", "פי ד'ילה מסתדירא", "upon its hem all around"),
        ("וּפַעֲמֹנֵי זָהָב בְּתוֹכָם סָבִיב", "וגלאגל מן ד'הב. פי מא בינהם מסתדירא",
         "and bells of gold between them all around."),
    ],
    34: [
        ("פַּעֲמֹן זָהָב וְרִמּוֹן פַּעֲמֹן זָהָב וְרִמּוֹן",
         "גלגל מן ד'הב ורמאנה. גלגל מן ד'הב ורמאנה",
         "A bell of gold and a pomegranate, a bell of gold and a pomegranate"),
        ("עַל-שׁוּלֵי הַמְּעִיל סָבִיב", "פי ד'יל אלממטר מסתדירא",
         "upon the hem of the robe all around."),
    ],
    35: [
        ("וְהָיָה עַל-אַהֲרֹן לְשָׁרֵת", "ויכון עלי' הרון אד' יכ'דם",
         "And it shall be upon Aaron when he serves"),
        ("וְנִשְׁמַע קוֹלוֹ בְּבֹאוֹ אֶל-הַקֹּדֶשׁ לִפְנֵי יְהוָה",
         "ויסמע צותה. פי ד'כולה אלקדס. בין ידי אללה",
         "and its sound shall be heard when he enters the sanctuary before God"),
        ("וּבְצֵאתוֹ--וְלֹא יָמוּת", "ופי כ'רוגה ולא יהלך",
         "and when he goes out — and he shall not perish."),
    ],
    36: [
        ("וְעָשִׂיתָ צִּיץ זָהָב טָהוֹר", "ואצנע עצאבה מן ד'הב כ'אלץ",
         "And make a diadem of pure gold"),
        ("וּפִתַּחְתָּ עָלָיו פִּתּוּחֵי חֹתָם קֹדֶשׁ לַיהוָה",
         "ואנקש עליהא כנקש אלכ'אתם. קדש ליי",
         "and engrave upon it like the engraving of a signet-ring: Holy to God."),
    ],
    37: [
        ("וְשַׂמְתָּ אֹתוֹ עַל-פְּתִיל תְּכֵלֶת", "ושדהא בסלך אסמאנגון",
         "And fasten it with a cord of blue"),
        ("וְהָיָה עַל-הַמִּצְנָפֶת אֶל-מוּל פְּנֵי-הַמִּצְנֶפֶת יִהְיֶה",
         "ותכון דון אלעמאמה מן מקדמהא",
         "and it shall be below the turban, at its front."),
    ],
    38: [
        ("וְהָיָה עַל-מֵצַח אַהֲרֹן", "ותכון עלי' גבהה' הרון",
         "And it shall be upon Aaron's forehead"),
        ("וְנָשָׂא אַהֲרֹן אֶת-עֲו‍ֹן הַקֳּדָשִׁים אֲשֶׁר יַקְדִּישׁוּ בְּנֵי יִשְׂרָאֵל",
         "אד' יסתג'פר ען ד'נוב אלאקדאס. אלד'י יקדסהא בני אסראיל",
         "when he seeks forgiveness for the sins of the holy things which the sons of Israel consecrate"),
        ("לְכָל-מַתְּנֹת קָדְשֵׁיהֶם", "לגמיע עטאיאהם ואקדאסהם",
         "for all their gifts and their holy offerings"),
        ("וְהָיָה עַל-מִצְחוֹ תָּמִיד לְרָצוֹן לָהֶם לִפְנֵי יְהוָה",
         "פתכון עלי' גבהתה דאימא. לירתצ'א ענהם בין ידי אללה",
         "and it shall be upon his forehead always, that they may find favor before God."),
    ],
    39: [
        ("וְשִׁבַּצְתָּ הַכְּתֹנֶת שֵׁשׁ", "ווש אלתוניה מן עשר",
         "And embroider the tunic of fine linen"),
        ("וְעָשִׂיתָ מִצְנֶפֶת שֵׁשׁ", "ואצנע אלעמאמה מן עשר",
         "and make the turban of fine linen"),
        ("וְאַבְנֵט תַּעֲשֶׂה מַעֲשֵׂה רֹקֵם", "ואלזנאר תצנעה צנעה' ראקם",
         "and the sash you shall make in the work of an embroiderer."),
    ],
    40: [
        ("וְלִבְנֵי אַהֲרֹן תַּעֲשֶׂה כֻתֳּנֹת", "ולבני הרון תצנע תואניא",
         "And for the sons of Aaron you shall make tunics"),
        ("וְעָשִׂיתָ לָהֶם אַבְנֵטִים", "ואצנע להם זנאנירא",
         "and make for them sashes"),
        ("וּמִגְבָּעוֹת תַּעֲשֶׂה לָהֶם לְכָבוֹד וּלְתִפְאָרֶת",
         "וקלאנס תצנעהא להם. לכראמה ופכ'ר",
         "and caps you shall make for them — for honor and glory."),
    ],
    41: [
        ("וְהִלְבַּשְׁתָּ אֹתָם אֶת-אַהֲרֹן אָחִיךָ וְאֶת-בָּנָיו אִתּוֹ",
         "ואלבסהמא הרון אכ'יך. ובניה מעה",
         "And clothe them — Aaron your brother and his sons with him"),
        ("וּמָשַׁחְתָּ אֹתָם וּמִלֵּאתָ אֶת-יָדָם", "ואמסחהם. ואכמל ואגבהם",
         "and anoint them, and complete their required investiture"),
        ("וְקִדַּשְׁתָּ אֹתָם--וְכִהֲנוּ לִי", "וקדסהם ויאמו לי",
         "and consecrate them, that they may lead worship for Me."),
    ],
    42: [
        ("וַעֲשֵׂה לָהֶם מִכְנְסֵי-בָד לְכַסּוֹת בְּשַׂר עֶרְוָה",
         "ואצנע להם סראויל מן עשר. לתג'טי מן אבדאנהם אלסווה",
         "And make for them linen trousers, to cover the nakedness of their bodies"),
        ("מִמָּתְנַיִם וְעַד-יְרֵכַיִם יִהְיוּ",
         "מן אלחקוין אלי' אלרכבתין תכון",
         "from the loins to the knees they shall reach."),
    ],
    43: [
        ("וְהָיוּ עַל-אַהֲרֹן וְעַל-בָּנָיו",
         "ותכון עלי' הרון ובניה",
         "And they shall be upon Aaron and his sons"),
        ("בְּבֹאָם אֶל-אֹהֶל מוֹעֵד אוֹ בְגִשְׁתָּם אֶל-הַמִּזְבֵּחַ לְשָׁרֵת בַּקֹּדֶשׁ",
         "פי דכ'ולהם אלי' כ'בא אלמחצ'ר. ופי תקדמהם אלי' אלמד'בח ליכ'דמון פי אלקדס",
         "when they enter the tent of the assembly, and when they draw near to the altar to serve in the sanctuary"),
        ("וְלֹא-יִשְׂאוּ עָו‍ֹן וָמֵתוּ", "ולא יחמלון ענה וזרא פיהלכון",
         "lest they bear on account of it a burden and perish"),
        ("חֻקַּת עוֹלָם לוֹ וּלְזַרְעוֹ אַחֲרָיו",
         "רסם אלדהר. לה ולנסלה בעדה",
         "This is an ordinance for all time, for him and for his offspring after him."),
    ],
}
