"""Hand-authored alignment triples for Shemot chapter 6."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי",
         "And God said to Moses"),
        ("עַתָּה תִרְאֶה", "אלאן תנצ'ר", "Now you shall see"),
        ("אֲשֶׁר אֶעֱשֶׂה לְפַרְעֹה", "מא אצנע בפרעון",
         "what I shall do to Pharaoh"),
        ("כִּי בְיָד חֲזָקָה יְשַׁלְּחֵם", "אנה סיטלקהם ביד שדידה",
         "for by a mighty hand he shall release them"),
        ("וּבְיָד חֲזָקָה יְגָרְשֵׁם מֵאַרְצוֹ",
         "ויטרדהם מן בלדה ביד שדידה",
         "and by a mighty hand he shall drive them out of his land"),
    ],
    2: [
        ("וַיְדַבֵּר אֱלֹהִים אֶל-מֹשֶׁה", "ת'ם כלם אללה מוסי'",
         "Then God spoke to Moses"),
        ("וַיֹּאמֶר אֵלָיו", "וקאל לה", "and said to him"),
        ("אֲנִי יְהוָה", "אנא אללה", "I am God"),
    ],
    3: [
        ("וָאֵרָא", "אלד'י תגלית", "who appeared"),
        ("אֶל-אַבְרָהָם אֶל-יִצְחָק וְאֶל-יַעֲקֹב", "לאברהים ליצחק וליעקב",
         "to Abraham, to Isaac, and to Jacob"),
        ("בְּאֵל שַׁדָּי", "באלטאיק אלכאפי", "as the All-Sufficient One"),
        ("וּשְׁמִי יְהוָה", "ואסמי אללה פקט", "but My name — God alone"),
        ("לֹא נוֹדַעְתִּי לָהֶם", "לם אערפהם", "I did not make known to them"),
    ],
    4: [
        ("וְגַם הֲקִמֹתִי אֶת-בְּרִיתִי אִתָּם", "ואיצ'א ת'בתת עהדי מעהם",
         "And also I confirmed My covenant with them"),
        ("לָתֵת לָהֶם אֶת-אֶרֶץ כְּנָעַן", "לאעטיהם בלד כנעאן",
         "to give them the land of Canaan"),
        ("אֵת אֶרֶץ מְגֻרֵיהֶם", "בלד סכנאהם",
         "the land of their sojourning"),
        ("אֲשֶׁר-גָּרוּ בָהּ", "אלד'י סכנוה", "which they sojourned in"),
    ],
    5: [
        ("וְגַם אֲנִי שָׁמַעְתִּי", "ואיצ'א קד סמעת", "And also I have heard"),
        ("אֶת-נַאֲקַת בְּנֵי יִשְׂרָאֵל", "שהיק בני אסראיל",
         "the groaning of the sons of Israel"),
        ("אֲשֶׁר מִצְרַיִם מַעֲבִדִים אֹתָם",
         "ממא אלמצריון יסתכדמונהם",
         "from what the Egyptians press them into as service"),
        ("וָאֶזְכֹּר אֶת-בְּרִיתִי", "ודכרת עהדי",
         "and I have remembered My covenant"),
    ],
    6: [
        ("לָכֵן אֱמֹר לִבְנֵי-יִשְׂרָאֵל", "לד'אלך קל לבני אסראיל",
         "Therefore say to the sons of Israel"),
        ("אֲנִי יְהוָה", "אנא אללה", "I am God"),
        ("וְהוֹצֵאתִי אֶתְכֶם מִתַּחַת סִבְלֹת מִצְרַיִם",
         "אקסמת לאכרגכם מן תחת נקל אלמצריון",
         "I have sworn to bring you out from under the burdens of the Egyptians"),
        ("וְהִצַּלְתִּי אֶתְכֶם מֵעֲבֹדָתָם", "ואכלצכם מן כדמתהם",
         "and to deliver you from their service"),
        ("וְגָאַלְתִּי אֶתְכֶם בִּזְרוֹעַ נְטוּיָה",
         "ואפככם בד'ראע ממדודה",
         "and to redeem you with an outstretched arm"),
        ("וּבִשְׁפָטִים גְּדֹלִים", "ואחכאם ]עט'ימה] עצ'ימה",
         "and with great judgments"),
    ],
    7: [
        ("וְלָקַחְתִּי אֶתְכֶם לִי לְעָם", "ואתכ'דכם לי אמה",
         "And I shall take you to Me as a nation"),
        ("וְהָיִיתִי לָכֶם לֵאלֹהִים", "ואכון לכם אלאהא",
         "and I shall be to you the God"),
        ("וִידַעְתֶּם כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "ותעלמון אני אללה רבכם",
         "and you shall know that I am God your Lord"),
        ("הַמּוֹצִיא אֶתְכֶם מִתַּחַת סִבְלוֹת מִצְרָיִם",
         "אלמכ'רגכם מן תחת נקל אלמצריון",
         "who brings you out from under the burdens of the Egyptians"),
    ],
    8: [
        ("וְהֵבֵאתִי אֶתְכֶם אֶל-הָאָרֶץ", "ואדכ'לכם אלי' אלבלד",
         "And I shall bring you into the land"),
        ("אֲשֶׁר נָשָׂאתִי אֶת-יָדִי", "אלד'י אקסמת באמרי",
         "which I swore by My word"),
        ("לָתֵת אֹתָהּ לְאַבְרָהָם לְיִצְחָק וּלְיַעֲקֹב",
         "אן אעטיה אבראהים יצחאק ויעקוב",
         "to give to Abraham, Isaac, and Jacob"),
        ("וְנָתַתִּי אֹתָהּ לָכֶם מוֹרָשָׁה", "פאעטיה לכם חוזא",
         "and I shall give it to you as a possession"),
        ("אֲנִי יְהוָה", "אנא אללה אפי בדאלך", "I am God, I shall fulfil this"),
    ],
    9: [
        ("וַיְדַבֵּר מֹשֶׁה כֵּן אֶל-בְּנֵי יִשְׂרָאֵל",
         "פכלם מוסי' בד'אלך בני אסראיל",
         "And Moses spoke thus to the sons of Israel"),
        ("וְלֹא שָׁמְעוּ אֶל-מֹשֶׁה", "ולם יקבלו מנה",
         "but they did not accept from him"),
        ("מִקֹּצֶר רוּחַ", "מן צ'יק ארואחהם",
         "because of the anguish of their souls"),
        ("וּמֵעֲבֹדָה קָשָׁה", "ומן כ'דמתהם אלצעבה",
         "and their hard service"),
    ],
    10: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    11: [
        ("בֹּא", "אדכל", "Go in"),
        ("דַבֵּר אֶל-פַּרְעֹה מֶלֶךְ מִצְרָיִם", "כלם פרעון מלך מצר",
         "speak to Pharaoh, king of Egypt"),
        ("וִישַׁלַּח אֶת-בְּנֵי-יִשְׂרָאֵל מֵאַרְצוֹ",
         "אן יטלק בני אסראיל מן בלדה",
         "that he release the sons of Israel from his land"),
    ],
    12: [
        ("וַיְדַבֵּר מֹשֶׁה לִפְנֵי יְהוָה לֵאמֹר", "קאל יא רבי",
         "He said: 'O my Lord"),
        ("הֵן בְּנֵי-יִשְׂרָאֵל לֹא-שָׁמְעוּ אֵלַי",
         "הוד'א בני אסראיל לם יקבלו מני",
         "behold — the sons of Israel did not accept from me"),
        ("וְאֵיךְ יִשְׁמָעֵנִי פַרְעֹה", "פכיף יקבל מני פרעון",
         "so how shall Pharaoh accept from me"),
        ("וַאֲנִי עֲרַל שְׂפָתָיִם", "ואנא אלת'ג' אלפם",
         "when I am thick of speech"),
    ],
    13: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן",
         "פכלם אללה מוסי' והרון", "And God spoke to Moses and Aaron"),
        ("וַיְצַוֵּם", "ואוצאהמא", "and charged the two of them"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בסבב בני אסראיל",
         "concerning the sons of Israel"),
        ("וְאֶל-פַּרְעֹה מֶלֶךְ מִצְרָיִם", "ובסבב פרעון מלך מצר",
         "and concerning Pharaoh, king of Egypt"),
    ],
    14: [
        ("אֵלֶּה רָאשֵׁי בֵית-אֲבֹתָם", "הולאי רויסא ביות אבאיאהם",
         "These are the heads of their fathers' houses"),
        ("בְּנֵי רְאוּבֵן בְּכֹר יִשְׂרָאֵל", "בני ראובן בכר אסראיל",
         "The sons of Reuben, the firstborn of Israel"),
        ("חֲנוֹךְ וּפַלּוּא חֶצְרֹן וְכַרְמִי", "חנוך ופלוא חצרון וכרמי",
         "Hanoch and Pallu, Hezron and Carmi"),
        ("אֵלֶּה מִשְׁפְּחֹת רְאוּבֵן", "הד'א עשאיר ראובן",
         "these are the clans of Reuben"),
    ],
    15: [
        ("וּבְנֵי שִׁמְעוֹן", "ובני שמעון", "And the sons of Simeon"),
        ("יְמוּאֵל וְיָמִין וְאֹהַד וְיָכִין וְצֹחַר",
         "ימואל וימין ואוהד ויכין וצחר",
         "Jemuel and Jamin and Ohad and Jachin and Zohar"),
        ("וְשָׁאוּל בֶּן-הַכְּנַעֲנִית", "ושאול אבן אלכנעאנייה",
         "and Shaul the son of the Canaanite woman"),
        ("אֵלֶּה מִשְׁפְּחֹת שִׁמְעוֹן", "האולי עשאיר שמעון",
         "these are the clans of Simeon"),
    ],
    16: [
        ("וְאֵלֶּה שְׁמוֹת בְּנֵי-לֵוִי לְתֹלְדֹתָם",
         "והולאי אסמא בני לוי עלי' תיאלידהם",
         "And these are the names of the sons of Levi according to their generations"),
        ("גֵּרְשׁוֹן וּקְהָת וּמְרָרִי", "גרשון. וקהת ומררי",
         "Gershon, and Kohath, and Merari"),
        ("וּשְׁנֵי חַיֵּי לֵוִי", "וסני חיוה' לוי",
         "and the years of the life of Levi"),
        ("שֶׁבַע וּשְׁלֹשִׁים וּמְאַת שָׁנָה", "מאיה וסבעה ות'לאת'ין סנה",
         "were a hundred and thirty-seven years"),
    ],
    17: [
        ("בְּנֵי גֵרְשׁוֹן", "בני גרשון", "The sons of Gershon"),
        ("לִבְנִי וְשִׁמְעִי", "לבני ושמעי", "Libni and Shimei"),
        ("לְמִשְׁפְּחֹתָם", "לעשאירהם", "according to their clans"),
    ],
    18: [
        ("וּבְנֵי קְהָת", "ובני קהת", "And the sons of Kohath"),
        ("עַמְרָם וְיִצְהָר וְחֶבְרוֹן וְעֻזִּיאֵל",
         "עמרם ויצהר. וחברון ועזיאל",
         "Amram and Izhar, and Hebron and Uzziel"),
        ("וּשְׁנֵי חַיֵּי קְהָת", "וסני חיוה' קהת",
         "and the years of the life of Kohath"),
        ("שָׁלֹשׁ וּשְׁלֹשִׁים וּמְאַת שָׁנָה",
         "מאיה ות'לאת'ה ות'לאת'ין סנה",
         "were a hundred and thirty-three years"),
    ],
    19: [
        ("וּבְנֵי מְרָרִי מַחְלִי וּמוּשִׁי", "ובני מררי מחלי ומושי",
         "And the sons of Merari: Mahli and Mushi"),
        ("אֵלֶּה מִשְׁפְּחֹת הַלֵּוִי לְתֹלְדֹתָם",
         "הולאי עשאיר אלליואניין עלי' תיאלידהם",
         "These are the clans of the Levites according to their generations"),
    ],
    20: [
        ("וַיִּקַּח עַמְרָם אֶת-יוֹכֶבֶד דֹּדָתוֹ",
         "פתזווג עמרם. יוכבד עמתה",
         "And Amram married Jochebed his aunt"),
        ("לוֹ לְאִשָּׁה", "קבל אן תחצ'ר עליה",
         "before she became forbidden to him"),
        ("וַתֵּלֶד לוֹ אֶת-אַהֲרֹן וְאֶת-מֹשֶׁה", "פולדת לה הרון ומוסי",
         "and she bore him Aaron and Moses"),
        ("וּשְׁנֵי חַיֵּי עַמְרָם שֶׁבַע וּשְׁלֹשִׁים וּמְאַת שָׁנָה",
         "וכאן סני חיאתה מאיה וסבעה ות'לאת'ין סנה",
         "And the years of his life were a hundred and thirty-seven years"),
    ],
    21: [
        ("וּבְנֵי יִצְהָר", "ובני יצהר", "And the sons of Izhar"),
        ("קֹרַח וָנֶפֶג וְזִכְרִי", "קרח ונפג וזכרי",
         "Korah and Nepheg and Zichri"),
    ],
    22: [
        ("וּבְנֵי עֻזִּיאֵל", "ובני עזיאל", "And the sons of Uzziel"),
        ("מִישָׁאֵל וְאֶלְצָפָן וְסִתְרִי", "מישאל ואלצפן וסתרי",
         "Mishael and Elzaphan and Sithri"),
    ],
    23: [
        ("וַיִּקַּח אַהֲרֹן אֶת-אֱלִישֶׁבַע", "פתזווג הרון. אלישבע",
         "And Aaron married Elisheba"),
        ("בַּת-עַמִּינָדָב", "אבנה' עמינדב", "daughter of Amminadab"),
        ("אֲחוֹת נַחְשׁוֹן", "אכ'ת נחשון", "sister of Nahshon"),
        ("וַתֵּלֶד לוֹ אֶת-נָדָב וְאֶת-אֲבִיהוּא", "פולדת לה. נדב ואביהוא",
         "and she bore him Nadab and Abihu"),
        ("אֶת-אֶלְעָזָר וְאֶת-אִיתָמָר", "אלעזר ואיתמר",
         "Eleazar and Ithamar"),
    ],
    24: [
        ("וּבְנֵי קֹרַח", "ובני קרח", "And the sons of Korah"),
        ("אַסִּיר וְאֶלְקָנָה וַאֲבִיאָסָף", "אסיר ואלקנה ואביאסף",
         "Assir and Elkanah and Abiasaph"),
        ("אֵלֶּה מִשְׁפְּחֹת הַקָּרְחִי", "הולאי עשאיר קרח",
         "these are the clans of Korah"),
    ],
    25: [
        ("וְאֶלְעָזָר בֶּן-אַהֲרֹן", "ואלעזר אבן הרון", "And Eleazar son of Aaron"),
        ("לָקַח-לוֹ מִבְּנוֹת פּוּטִיאֵל לוֹ לְאִשָּׁה",
         "תזווג באמראה מן בנאת פוטיאל",
         "married a woman from the daughters of Putiel"),
        ("וַתֵּלֶד לוֹ אֶת-פִּינְחָס", "פולדת לה פינחס",
         "and she bore him Phinehas"),
        ("אֵלֶּה רָאשֵׁי אֲבוֹת הַלְוִיִּם--לְמִשְׁפְּחֹתָם",
         "הולאי רויסא אבא אלליואניין לעשאירהם",
         "These are the heads of the fathers of the Levites according to their clans"),
    ],
    26: [
        ("הוּא אַהֲרֹן וּמֹשֶׁה", "המא הרון ומוסי",
         "They are Aaron and Moses"),
        ("אֲשֶׁר אָמַר יְהוָה לָהֶם", "אלד'י קאל אללה להמא",
         "those to whom God said"),
        ("הוֹצִיאוּ אֶת-בְּנֵי יִשְׂרָאֵל", "אכ'רגא בני אסראיל",
         "Bring out the sons of Israel"),
        ("מֵאֶרֶץ מִצְרַיִם עַל-צִבְאֹתָם", "מן בלד מצר עלי' גיושהם",
         "from the land of Egypt according to their hosts"),
    ],
    27: [
        ("הֵם הַמְדַבְּרִים אֶל-פַּרְעֹה מֶלֶךְ-מִצְרַיִם",
         "המא אלמכאטבין פרעון מלך מצר",
         "They are the ones who addressed Pharaoh, king of Egypt"),
        ("לְהוֹצִיא אֶת-בְּנֵי-יִשְׂרָאֵל מִמִּצְרָיִם",
         "ליכ'רגא בני אסראיל מן מצר",
         "that he bring out the sons of Israel from Egypt"),
        ("הוּא מֹשֶׁה וְאַהֲרֹן", "המא מוסי' והרון",
         "they are Moses and Aaron"),
    ],
    28: [
        ("וַיְהִי בְּיוֹם", "ולמא כאן פי יום", "And it was on the day"),
        ("דִּבֶּר יְהוָה אֶל-מֹשֶׁה", "כ'אטב אללה מוסי' פיה",
         "that God spoke to Moses"),
        ("בְּאֶרֶץ מִצְרָיִם", "פי בלד מצר", "in the land of Egypt"),
    ],
    29: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "קאל אללה למוסי",
         "God said to Moses"),
        ("אֲנִי יְהוָה", "אנא אללה", "I am God"),
        ("דַּבֵּר אֶל-פַּרְעֹה מֶלֶךְ מִצְרַיִם", "כלם פרעון מלך מצר",
         "speak to Pharaoh, king of Egypt"),
        ("אֵת כָּל-אֲשֶׁר אֲנִי דֹּבֵר אֵלֶיךָ", "בגמיע מא אמרה בה",
         "all that I command you"),
    ],
    30: [
        ("וַיֹּאמֶר מֹשֶׁה לִפְנֵי יְהוָה", "פקאל בין ידיה",
         "And he said before Him"),
        ("הֵן אֲנִי עֲרַל שְׂפָתַיִם", "הוד'א אנא אלתג' אלפם",
         "Behold, I am thick of speech"),
        ("וְאֵיךְ יִשְׁמַע אֵלַי פַּרְעֹה", "וכיף יסמע מני פרעון",
         "so how shall Pharaoh heed me"),
    ],
}
