"""Hand-authored alignment triples for Shemot chapter 33."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses:"),
        ("לֵךְ עֲלֵה מִזֶּה--אַתָּה וְהָעָם",
         "אמץ' אצעד מן ההנא. אנת ואלקום",
         "'Go, ascend from here — you and the people"),
        ("אֲשֶׁר הֶעֱלִיתָ מֵאֶרֶץ מִצְרָיִם",
         "אלד'י אצעדתהם מן מצר",
         "whom you brought up from Egypt —"),
        ("אֶל-הָאָרֶץ אֲשֶׁר נִשְׁבַּעְתִּי לְאַבְרָהָם לְיִצְחָק וּלְיַעֲקֹב",
         "אלי' אלבלד. אלד'י אקסמת. לאברהים ויצחק ויעקוב",
         "to the land which I swore to Abraham and Isaac and Jacob,"),
        ("לֵאמֹר לְזַרְעֲךָ אֶתְּנֶנָּה", "קאילא. לנסלכם אעטיה",
         "saying: To your offspring I shall give it.'"),
    ],
    2: [
        ("וְשָׁלַחְתִּי לְפָנֶיךָ מַלְאָךְ",
         "ואבעת' בין ידיך מלכא",
         "And I shall send before you an angel,"),
        ("וְגֵרַשְׁתִּי אֶת-הַכְּנַעֲנִי הָאֱמֹרִי",
         "אטרד בה אלכנעאניין ואלאמוריין",
         "by whom I shall drive out the Canaanites and the Amorites,"),
        ("וְהַחִתִּי וְהַפְּרִזִּי הַחִוִּי וְהַיְבוּסִי",
         "ואלחתיין ואלפרזיין. ואלחויין ואליבוסיין",
         "and the Hittites and the Perizzites, and the Hivites and the Jebusites —"),
    ],
    3: [
        ("אֶל-אֶרֶץ זָבַת חָלָב וּדְבָשׁ",
         "אלי' בלד יפיץ' לבנא ועסלא",
         "to a land flowing with milk and honey."),
        ("כִּי לֹא אֶעֱלֶה בְּקִרְבְּךָ",
         "לאני לא אצעד נורי פי מא בינכם",
         "For I shall not bring up My light in your midst,"),
        ("כִּי עַם-קְשֵׁה-עֹרֶף אַתָּה",
         "לאנכם קום צעאב אלרקאב",
         "for you are a stiff-necked people,"),
        ("פֶּן-אֲכֶלְךָ בַּדָּרֶךְ", "כלא אפניכם פי אלטריק",
         "lest I bring you to an end along the way.'"),
    ],
    4: [
        ("וַיִּשְׁמַע הָעָם אֶת-הַדָּבָר הָרָע הַזֶּה",
         "פלמא סמע אלקום. הד'א אלכ'בר אלסו",
         "And when the people heard this evil report,"),
        ("וַיִּתְאַבָּלוּ", "חזנו", "they grieved,"),
        ("וְלֹא-שָׁתוּ אִישׁ עֶדְיוֹ עָלָיו",
         "ולם יגעל כל אמר זייה עליה",
         "and no one put his distinctive attire upon himself."),
    ],
    5: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses:"),
        ("אֱמֹר אֶל-בְּנֵי-יִשְׂרָאֵל", "קל לבני אסראיל",
         "'Say to the sons of Israel:"),
        ("אַתֶּם עַם-קְשֵׁה-עֹרֶף", "אנתם קום צעאב אלרקאב",
         "You are a stiff-necked people."),
        ("רֶגַע אֶחָד אֶעֱלֶה בְקִרְבְּךָ וְכִלִּיתִיךָ",
         "פלו אני אצעדת נורי פי מא בינכם. טרפה ואחדה אפניתכם",
         "If I were to bring up My light in your midst for even a single instant, I would bring you to an end."),
        ("וְעַתָּה הוֹרֵד עֶדְיְךָ מֵעָלֶיךָ",
         "ואלאן. אדימו עלי' נזע זייכם",
         "And now — proceed to remove your distinctive attire,"),
        ("וְאֵדְעָה מָה אֶעֱשֶׂה-לָּךְ",
         "חתי' אערפכם מא אצנע בכם",
         "that I may make known to you what I shall do with you.'"),
    ],
    6: [
        ("וַיִּתְנַצְּלוּ בְנֵי-יִשְׂרָאֵל אֶת-עֶדְיָם",
         "פאקדאם בני אסראיל. עלי' נזע זייהם",
         "And the sons of Israel proceeded to remove their distinctive attire,"),
        ("מֵהַר חוֹרֵב", "מן גבל חריב", "from Mount Horeb."),
    ],
    7: [
        ("וּמֹשֶׁה יִקַּח אֶת-הָאֹהֶל", "וכאן מוסי'. יאכ'ד' אלכ'בא",
         "And Moses would take the tent"),
        ("וְנָטָה-לוֹ מִחוּץ לַמַּחֲנֶה הַרְחֵק מִן-הַמַּחֲנֶה",
         "פיצ'רבה כ'ארג אלעסכר בעידא מנה",
         "and pitch it outside the camp, far from it,"),
        ("וְקָרָא לוֹ אֹהֶל מוֹעֵד", "ויסמיה מצ'רב אלועיד",
         "and call it the tent of appointment."),
        ("וְהָיָה כָּל-מְבַקֵּשׁ יְהוָה יֵצֵא אֶל-אֹהֶל מוֹעֵד אֲשֶׁר מִחוּץ לַמַּחֲנֶה",
         "וכאן כל מן טלב עלמא מן ענד אללה. יכ'רג אלי' מצ'רב אלועיד. אלד'י כ'ארג אלעסכר",
         "And it was that whoever sought knowledge from God would go out to the tent of appointment which was outside the camp."),
    ],
    8: [
        ("וְהָיָה כְּצֵאת מֹשֶׁה אֶל-הָאֹהֶל",
         "וכאן מוסי' אד'י כ'רג אלי' אלכ'בא",
         "And it was, whenever Moses went out to the tent,"),
        ("יָקוּמוּ כָּל-הָעָם וְנִצְּבוּ אִישׁ פֶּתַח אָהֳלוֹ",
         "יקום גמיע אלקום. וינתצבון. כל אמר ענד באב כ'באיה",
         "all the people would rise and station themselves — each man at the door of his tent —"),
        ("וְהִבִּיטוּ אַחֲרֵי מֹשֶׁה עַד-בֹּאוֹ הָאֹהֱלָה",
         "וילתפתון ורא מוסי'. אלי' דכ'ולה אלי' אלכ'בא",
         "and they would look after Moses, until his entry into the tent."),
    ],
    9: [
        ("וְהָיָה כְּבֹא מֹשֶׁה הָאֹהֱלָה",
         "וכאן מוסי' אד'י דכל אלכ'בא",
         "And it was, whenever Moses entered the tent,"),
        ("יֵרֵד עַמּוּד הֶעָנָן וְעָמַד פֶּתַח הָאֹהֶל",
         "ינזל עמוד אלג'מאם. ויקף עלי' באב אלכ'בא",
         "the pillar of cloud would descend and stand at the door of the tent;"),
        ("וְדִבֶּר עִם-מֹשֶׁה", "ויכלם אללה מוסי'",
         "and God would speak with Moses."),
    ],
    10: [
        ("וְרָאָה כָל-הָעָם אֶת-עַמּוּד הֶעָנָן עֹמֵד פֶּתַח הָאֹהֶל",
         "פאד'א ראי' גמיע אלקום עמוד אלג'מאם. ואקף עלי' באב אלכ'בא",
         "And whenever all the people saw the pillar of cloud standing at the door of the tent,"),
        ("וְקָם כָּל-הָעָם", "קאמו אגמעין", "all the people would rise together,"),
        ("וְהִשְׁתַּחֲווּ אִישׁ פֶּתַח אָהֳלוֹ",
         "וסגד כל אמר עלי' באב כ'באיה",
         "and each man would bow down at the door of his tent."),
    ],
    11: [
        ("וְדִבֶּר יְהוָה אֶל-מֹשֶׁה פָּנִים אֶל-פָּנִים",
         "ויכלם אללה מוסי' שפאהא",
         "And God would speak with Moses mouth to mouth,"),
        ("כַּאֲשֶׁר יְדַבֵּר אִישׁ אֶל-רֵעֵהוּ",
         "כמא יכלם אלמר צאחבה",
         "as a man speaks with his companion."),
        ("וְשָׁב אֶל-הַמַּחֲנֶה", "וירגע אלי' אלעסכר",
         "And he would return to the camp."),
        ("וּמְשָׁרְתוֹ יְהוֹשֻׁעַ בִּן-נוּן נַעַר",
         "וכאן כ'אדמה. יהושע אבן נון שאבא",
         "And his attendant, Joshua son of Nun, a young man,"),
        ("לֹא יָמִישׁ מִתּוֹךְ הָאֹהֶל",
         "לא יזול מן אלכ'בא",
         "would not depart from the tent."),
    ],
    12: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוָה", "פקאל מוסי ללה",
         "And Moses said to God:"),
        ("רְאֵה אַתָּה אֹמֵר אֵלַי הַעַל אֶת-הָעָם הַזֶּה",
         "אנת עאלם באנך קלת לי אצעד הולאי אלקום",
         "'You know that You said to me: Bring up these people —"),
        ("וְאַתָּה לֹא הוֹדַעְתַּנִי אֵת אֲשֶׁר-תִּשְׁלַח עִמִּי",
         "ואנת פלם תערפני. במן תבעת' מעי",
         "and yet You have not made known to me whom You are sending with me."),
        ("וְאַתָּה אָמַרְתָּ יְדַעְתִּיךָ בְשֵׁם",
         "ואנת פקד קלת לי אני קד שרפת אסמך",
         "And You have said to me: I have honored your name,"),
        ("וְגַם-מָצָאתָ חֵן בְּעֵינָי",
         "ווגדת חצ'אא ענדי",
         "and you have found favor with Me.'"),
    ],
    13: [
        ("וְעַתָּה אִם-נָא מָצָאתִי חֵן בְּעֵינֶיךָ",
         "ואלאן. אן ו'גדת חצ'אא ענדך",
         "And now — if I have found favor with You,"),
        ("הוֹדִעֵנִי נָא אֶת-דְּרָכֶךָ", "ערפני סיירך",
         "make known to me Your way,"),
        ("וְאֵדָעֲךָ", "חתי' אערף בך", "that I may know You,"),
        ("לְמַעַן אֶמְצָא-חֵן בְּעֵינֶיךָ",
         "לקבל אן אגד חצ'אא ענדך",
         "so that I may find favor with You;"),
        ("וּרְאֵה כִּי עַמְּךָ הַגּוֹי הַזֶּה",
         "ואנצ'ר לשעבך הד'ה אלאמה",
         "and look upon Your people, this nation.'"),
    ],
    14: [
        ("וַיֹּאמַר פָּנַי יֵלֵכוּ", "קאל לה. נורי יסיר מעך",
         "He said to him: 'My light shall go with you,"),
        ("וַהֲנִחֹתִי לָךְ", "אלי' אן אקרך",
         "until I bring you to rest.'"),
    ],
    15: [
        ("וַיֹּאמֶר אֵלָיו", "קאל", "He said:"),
        ("אִם-אֵין פָּנֶיךָ הֹלְכִים", "אן לם יסיר נורך מענא מן אלאן",
         "'If Your light does not go with us from now,"),
        ("אַל-תַּעֲלֵנוּ מִזֶּה", "פלא תצעדנא מן ההני'",
         "do not bring us up from here.'"),
    ],
    16: [
        ("וּבַמֶּה יִוָּדַע אֵפוֹא",
         "ובמא ד'א יערף אלאן",
         "And by what shall it now be known"),
        ("כִּי-מָצָאתִי חֵן בְּעֵינֶיךָ אֲנִי וְעַמֶּךָ",
         "אן קד וגדת חצ'אא ענדך אנא וקומך",
         "that I — and Your people — have found favor with You,"),
        ("הֲלוֹא בְּלֶכְתְּךָ עִמָּנוּ",
         "אלא במסיר נורך מענא",
         "except by Your light going with us?"),
        ("וְנִפְלִינוּ אֲנִי וְעַמְּךָ מִכָּל-הָעָם אֲשֶׁר עַל-פְּנֵי הָאֲדָמָה",
         "פנבין אנא וקומך. מן גמיע אלקום. אלד'י עלי' וגה אלארץ'",
         "So that we — I and Your people — may be set apart from all the peoples who are upon the face of the earth.'"),
    ],
    17: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses:"),
        ("גַּם אֶת-הַדָּבָר הַזֶּה אֲשֶׁר דִּבַּרְתָּ אֶעֱשֶׂה",
         "הד'א אלאמר אלד'י סאלתה אצנעה איצ'א",
         "'This thing which you have asked — I shall do as well,"),
        ("כִּי-מָצָאתָ חֵן בְּעֵינַי", "לאנך קד ו'גדת חצ'אא ענדי",
         "for you have found favor with Me,"),
        ("וָאֵדָעֲךָ בְּשֵׁם", "ושרפת אסמך",
         "and I have honored your name.'"),
    ],
    18: [
        ("וַיֹּאמַר הַרְאֵנִי נָא אֶת-כְּבֹדֶךָ",
         "קאל. אוריני נורך איצ'א",
         "He said: 'Show me Your light as well.'"),
    ],
    19: [
        ("וַיֹּאמֶר אֲנִי אַעֲבִיר כָּל-טוּבִי עַל-פָּנֶיךָ",
         "קאל. אנא אמר גמיע נורי בחצ'רתך",
         "He said: 'I shall cause all My light to pass in your presence,"),
        ("וְקָרָאתִי בְשֵׁם יְהוָה לְפָנֶיךָ",
         "ואנאדי באסם אללה בין ידיך",
         "and I shall call out in the name of God before you;"),
        ("וְחַנֹּתִי אֶת-אֲשֶׁר אָחֹן", "וארוף מן ארוף",
         "and I shall show kindness to whom I show kindness,"),
        ("וְרִחַמְתִּי אֶת-אֲשֶׁר אֲרַחֵם", "וארחם מן ארחם",
         "and I shall show mercy to whom I show mercy.'"),
    ],
    20: [
        ("וַיֹּאמֶר לֹא תוּכַל לִרְאֹת אֶת-פָּנָי",
         "קאל. לא תטיק אן תרא נורי",
         "He said: 'You are not able to behold My light,"),
        ("כִּי לֹא-יִרְאַנִי הָאָדָם וָחָי",
         "לאנה לא יראה אנסאן פיחיא",
         "for no person can behold it and live.'"),
    ],
    21: [
        ("וַיֹּאמֶר יְהוָה", "קאל אללה", "And God said:"),
        ("הִנֵּה מָקוֹם אִתִּי", "הוד'י ענדי מוצ'ע",
         "'Behold, there is a place with Me —"),
        ("וְנִצַּבְתָּ עַל-הַצּוּר", "אנתצב עלי' אלצואן",
         "station yourself upon the flint.'"),
    ],
    22: [
        ("וְהָיָה בַּעֲבֹר כְּבֹדִי", "פאד'א מר בך נורי",
         "'And when My light passes by you,"),
        ("וְשַׂמְתִּיךָ בְּנִקְרַת הַצּוּר",
         "ציירתך פי נקיר אלצואן",
         "I shall place you in the cleft of the flint,"),
        ("וְשַׂכֹּתִי כַפִּי עָלֶיךָ עַד-עָבְרִי",
         "וצ'ללת כבסחאבי. עליך חתי יגוז אוולה",
         "and shall cast the shade of My cloud over you, until the first of it has passed.'"),
    ],
    23: [
        ("וַהֲסִרֹתִי אֶת-כַּפִּי", "ת'ם אזיל סחאבי",
         "'Then I shall remove My cloud,"),
        ("וְרָאִיתָ אֶת-אֲחֹרָי", "חתי' תנצ'ר אואכ'ר נורי",
         "so that you may behold the latter part of My light —"),
        ("וּפָנַי לֹא יֵרָאוּ", "ואואילה לם תרא",
         "but its beginnings you shall not behold.'"),
    ],
}
