"""Hand-authored alignment triples for Shemot chapter 14."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "מר בני אסראיל",
         "Command the sons of Israel"),
        ("וְיָשֻׁבוּ וְיַחֲנוּ לִפְנֵי פִּי הַחִירֹת", "אן ירגעון. וינזלון בין ידי פם אלחירות",
         "that they turn back and encamp before the mouth of the Hiroth"),
        ("בֵּין מִגְדֹּל וּבֵין הַיָּם", "בין מגדול ובין אלבחר",
         "between Migdol and the sea"),
        ("לִפְנֵי בַּעַל צְפֹן נִכְחוֹ תַחֲנוּ עַל-הַיָּם",
         "בין ידי בעל צפון. חיאלה תנזלון עלי' אלבחר",
         "before Baal-Zephon — opposite it you shall encamp by the sea."),
    ],
    3: [
        ("וְאָמַר פַּרְעֹה לִבְנֵי יִשְׂרָאֵל נְבֻכִים הֵם בָּאָרֶץ",
         "חתי' יקול פרעון ען בני אסראיל. אנהם מתחיירין פי אלבלד",
         "So that Pharaoh will say of the sons of Israel that they are bewildered in the land"),
        ("סָגַר עֲלֵיהֶם הַמִּדְבָּר", "ואן אלבר קד אנג'לק עליהם",
         "and that the open country has been closed upon them."),
    ],
    4: [
        ("וְחִזַּקְתִּי אֶת-לֵב-פַּרְעֹה וְרָדַף אַחֲרֵיהֶם",
         "ואשדד קלב פרעון ויכלבהם",
         "And I shall harden the heart of Pharaoh and he shall pursue them"),
        ("וְאִכָּבְדָה בְּפַרְעֹה וּבְכָל-חֵילוֹ", "ואת עצ'ם בפרעון וגמיע גנדה",
         "and I shall make Myself great through Pharaoh and all his host"),
        ("וְיָדְעוּ מִצְרַיִם כִּי-אֲנִי יְהוָה", "ויעלם אלמצריון אני אללה",
         "and the Egyptians shall know that I am God"),
        ("וַיַּעֲשׂוּ-כֵן", "פצנעו כד'אך", "And so they did."),
    ],
    5: [
        ("וַיֻּגַּד לְמֶלֶךְ מִצְרַיִם כִּי בָרַח הָעָם",
         "פאכ'בר מלך מצר. אן אלקום קד הרבו",
         "And the king of Egypt was told that the people had fled"),
        ("וַיֵּהָפֵךְ לְבַב פַּרְעֹה וַעֲבָדָיו אֶל-הָעָם",
         "אנקלב קלבה וקואדה אליהם",
         "and the heart of he and his officers turned against them"),
        ("וַיֹּאמְרוּ מַה-זֹּאת עָשִׂינוּ", "וקאלו מא ד'א צנענא",
         "and they said: 'What have we done"),
        ("כִּי-שִׁלַּחְנוּ אֶת-יִשְׂרָאֵל מֵעָבְדֵנוּ",
         "אד' אטלקנא בני אסראיל מן כ'דמתנא",
         "since we released the sons of Israel from our service?'"),
    ],
    6: [
        ("וַיֶּאְסֹר אֶת-רִכְבּוֹ", "פאסרג מרכבה", "And he readied his chariot"),
        ("וְאֶת-עַמּוֹ לָקַח עִמּוֹ", "ואכ'ד' קומה מעה",
         "and took his people with him."),
    ],
    7: [
        ("וַיִּקַּח שֵׁשׁ-מֵאוֹת רֶכֶב בָּחוּר", "ואכ'ד' סת מאיה' מרכבא מכ'תארא",
         "And he took six hundred chosen chariots"),
        ("וְכֹל רֶכֶב מִצְרָיִם", "וסאיר מראכב אלמצריון אלד'ין כד'אך",
         "and the rest of the chariots of the Egyptians who were likewise"),
        ("וְשָׁלִשִׁם עַל-כֻּלּוֹ", "וקואד עלי' גמיעהם",
         "and officers over all of them."),
    ],
    8: [
        ("וַיְחַזֵּק יְהוָה אֶת-לֵב פַּרְעֹה מֶלֶךְ מִצְרַיִם",
         "ושדד אללה. קלב פרעון מלך מצר",
         "And God hardened the heart of Pharaoh king of Egypt"),
        ("וַיִּרְדֹּף אַחֲרֵי בְּנֵי יִשְׂרָאֵל", "וכלב בני אסראיל",
         "and he pursued the sons of Israel"),
        ("וּבְנֵי יִשְׂרָאֵל יֹצְאִים בְּיָד רָמָה", "ובני אסראיל. כ'ארגין ביד רפיעה",
         "and the sons of Israel were going forth with a raised hand."),
    ],
    9: [
        ("וַיִּרְדְּפוּ מִצְרַיִם אַחֲרֵיהֶם", "וכלבוהם אלמצריון",
         "And the Egyptians pursued them"),
        ("וַיַּשִּׂיגוּ אוֹתָם חֹנִים עַל-הַיָּם", "ולחקוהם נאזלין עלי' אלבחר",
         "and overtook them encamped by the sea"),
        ("כָּל-סוּס רֶכֶב פַּרְעֹה וּפָרָשָׁיו וְחֵילוֹ",
         "גמיע כ'יל מראכב פרעון. ופראסנה וגנדה",
         "all the horses of the chariots of Pharaoh, and his horsemen, and his host"),
        ("עַל-פִּי הַחִירֹת לִפְנֵי בַּעַל צְפֹן",
         "עלי' פם אלחירות. בין ידי בעל צפון",
         "at the mouth of the Hiroth, before Baal-Zephon."),
    ],
    10: [
        ("וּפַרְעֹה הִקְרִיב", "פלמא קרב פרעון", "And when Pharaoh drew near"),
        ("וַיִּשְׂאוּ בְנֵי-יִשְׂרָאֵל אֶת-עֵינֵיהֶם", "שלו בני אסראיל עיונהם",
         "the sons of Israel lifted up their eyes"),
        ("וְהִנֵּה מִצְרַיִם נֹסֵעַ אַחֲרֵיהֶם", "פאד'א באלמצריון ראחלון וראהם",
         "and behold, the Egyptians were journeying after them"),
        ("וַיִּירְאוּ מְאֹד", "פכ'אפו גדא", "and they feared greatly"),
        ("וַיִּצְעֲקוּ בְנֵי-יִשְׂרָאֵל אֶל-יְהוָה", "וצרכ'ו אלי' אללה",
         "and they cried out to God."),
    ],
    11: [
        ("וַיֹּאמְרוּ אֶל-מֹשֶׁה", "קאלו למוסי'", "They said to Moses"),
        ("הֲמִבְּלִי אֵין-קְבָרִים בְּמִצְרַיִם לְקַחְתָּנוּ לָמוּת בַּמִּדְבָּר",
         "אמן עדם אלקבור במצר. אכ'ד'תנא לנמות פי אלבר",
         "Was it because there were no graves in Egypt that you took us to die in the open country"),
        ("מַה-זֹּאת עָשִׂיתָ לָּנוּ", "מא ד'א צנעת בנא",
         "What have you done to us"),
        ("לְהוֹצִיאָנוּ מִמִּצְרָיִם", "אד' אכ'רגתנא מן מצר",
         "since you brought us out of Egypt?'"),
    ],
    12: [
        ("הֲלֹא-זֶה הַדָּבָר אֲשֶׁר דִּבַּרְנוּ אֵלֶיךָ בְמִצְרַיִם לֵאמֹר",
         "אליס הד'א אלקול. אלד'י קלנאה לך במצר קאילא",
         "Is this not the very word which we said to you in Egypt, saying"),
        ("חֲדַל מִמֶּנּוּ וְנַעַבְדָה אֶת-מִצְרָיִם",
         "דענא נכ'דם אלמצריון",
         "Leave us that we may serve the Egyptians"),
        ("כִּי טוֹב לָנוּ עֲבֹד אֶת-מִצְרַיִם מִמֻּתֵנוּ בַּמִּדְבָּר",
         "פאן כ'דמתנא להם. אצלח לנא מן מותנא פי אלבר",
         "for our service to them is better for us than our death in the open country?'"),
    ],
    13: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָעָם אַל-תִּירָאוּ", "קאל מוסי' לאלקום לא תכ'אפו",
         "Moses said to the people: 'Do not fear"),
        ("הִתְיַצְּבוּ וּרְאוּ אֶת-יְשׁוּעַת יְהוָה", "קפו ואנצרו מג'ותה' אללה",
         "stand still and behold the salvation of God"),
        ("אֲשֶׁר-יַעֲשֶׂה לָכֶם הַיּוֹם", "אלתי יצנעהא לכם אליום",
         "which He shall work for you today"),
        ("כִּי אֲשֶׁר רְאִיתֶם אֶת-מִצְרַיִם הַיּוֹם--לֹא תֹסִפוּ לִרְאֹתָם עוֹד עַד-עוֹלָם",
         "פאנכם כמא ראיתם אלמצריון אליום. לא תעאודו אן תרוהם אבדא אלי' אלדהר",
         "for as you have seen the Egyptians today, you shall never again see them, forever.'"),
    ],
    14: [
        ("יְהוָה יִלָּחֵם לָכֶם", "אללה יחארב ענכם",
         "'God shall fight on your behalf"),
        ("וְאַתֶּם תַּחֲרִשׁוּן", "ואנתם פאמסכו",
         "and as for you, be still.'"),
    ],
    15: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה מַה-תִּצְעַק אֵלָי",
         "ת'ם קאל אללה למוסי. מא תצרך' אליי",
         "Then God said to Moses: 'Why do you cry out to Me"),
        ("דַּבֵּר אֶל-בְּנֵי-יִשְׂרָאֵל וְיִסָּעוּ", "מר בני אסראיל אן ירחלון",
         "Command the sons of Israel that they set out.'"),
    ],
    16: [
        ("וְאַתָּה הָרֵם אֶת-מַטְּךָ", "ואנת ארפע עצאך",
         "'And you — lift up your staff"),
        ("וּנְטֵה אֶת-יָדְךָ עַל-הַיָּם--וּבְקָעֵהוּ", "ומד ידך. עלי' אלבחר ושקה",
         "and stretch out your hand over the sea and split it"),
        ("וְיָבֹאוּ בְנֵי-יִשְׂרָאֵל בְּתוֹךְ הַיָּם בַּיַּבָּשָׁה",
         "וידכ'לו בני אסראיל. פי וסטה פי אליבאס",
         "and the sons of Israel shall enter into the midst of it upon dry land.'"),
    ],
    17: [
        ("וַאֲנִי הִנְנִי מְחַזֵּק אֶת-לֵב מִצְרַיִם וְיָבֹאוּ אַחֲרֵיהֶם",
         "והאנא משדד קלב אלמצריון. וידכלו וראהם",
         "'And I am hardening the heart of the Egyptians, and they shall enter after them"),
        ("וְאִכָּבְדָה בְּפַרְעֹה וּבְכָל-חֵילוֹ בְּרִכְבּוֹ וּבְפָרָשָׁיו",
         "ואתעצם בפרעון ובגמיע גנדה ומראכבה ופרסאנה",
         "and I shall make Myself great through Pharaoh and all his host and his chariots and his horsemen.'"),
    ],
    18: [
        ("וְיָדְעוּ מִצְרַיִם כִּי-אֲנִי יְהוָה", "ויעלם אלמצריון אני אללה",
         "'And the Egyptians shall know that I am God"),
        ("בְּהִכָּבְדִי בְּפַרְעֹה בְּרִכְבּוֹ וּבְפָרָשָׁיו",
         "אד' תעצמת בפרעון. ומראכבה ופרסאנה",
         "when I have made Myself great through Pharaoh, and his chariots, and his horsemen.'"),
    ],
    19: [
        ("וַיִּסַּע מַלְאַךְ הָאֱלֹהִים הַהֹלֵךְ לִפְנֵי מַחֲנֵה יִשְׂרָאֵל",
         "פרחל מלך אללה. אלסאיר בין ידי עסכר בני אסראיל",
         "And the angel of God, who was going before the camp of the sons of Israel, set out"),
        ("וַיֵּלֶךְ מֵאַחֲרֵיהֶם", "וצאר וראהם", "and moved behind them"),
        ("וַיִּסַּע עַמּוּד הֶעָנָן מִפְּנֵיהֶם", "ורחל עמוד אלג'מאם מן בין ידיהם",
         "and the pillar of cloud set out from before them"),
        ("וַיַּעֲמֹד מֵאַחֲרֵיהֶם", "ווקף וראהם", "and stood behind them."),
    ],
    20: [
        ("וַיָּבֹא בֵּין מַחֲנֵה מִצְרַיִם וּבֵין מַחֲנֵה יִשְׂרָאֵל",
         "פדכ'ל בין עסכר אלמצריון. ובין עסכר אלאסראליון",
         "And it came between the camp of the Egyptians and the camp of the Israelites"),
        ("וַיְהִי הֶעָנָן וְהַחֹשֶׁךְ", "וכאן אלג'מאם ואלצ'לאם",
         "and there were the cloud and the darkness"),
        ("וַיָּאֶר אֶת-הַלָּיְלָה", "פגשיא אלליל", "yet it lit up the night"),
        ("וְלֹא-קָרַב זֶה אֶל-זֶה כָּל-הַלָּיְלָה", "ולם יתקדם אחדהמא. אלי' אלאכ'ר טול אלליל",
         "and neither one drew near the other throughout the night."),
    ],
    21: [
        ("וַיֵּט מֹשֶׁה אֶת-יָדוֹ עַל-הַיָּם", "פמד מוסי ידה עלי' אלבחר",
         "And Moses stretched out his hand over the sea"),
        ("וַיּוֹלֶךְ יְהוָה אֶת-הַיָּם בְּרוּחַ קָדִים עַזָּה כָּל-הַלַּיְלָה",
         "וסייר אללה אלבחר. בריח קבול צעבה טול אלליל",
         "and God drove the sea back with a strong qibla-wind throughout the night"),
        ("וַיָּשֶׂם אֶת-הַיָּם לֶחָרָבָה", "חתי' ציירה גפאפא",
         "until He made it dry"),
        ("וַיִּבָּקְעוּ הַמָּיִם", "בעד מא אנשק אלמא",
         "after the water had split apart."),
    ],
    22: [
        ("וַיָּבֹאוּ בְנֵי-יִשְׂרָאֵל בְּתוֹךְ הַיָּם בַּיַּבָּשָׁה",
         "ודכ'לו בני אסראיל פי וסט אלבחר פי אליבאס",
         "And the sons of Israel entered into the midst of the sea upon dry land"),
        ("וְהַמַּיִם לָהֶם חוֹמָה מִימִינָם וּמִשְּׂמֹאלָם",
         "ואלמא להם אסוארא. ען ימינהם וען יסארהם",
         "and the water was walls for them, on their right and on their left."),
    ],
    23: [
        ("וַיִּרְדְּפוּ מִצְרַיִם וַיָּבֹאוּ אַחֲרֵיהֶם", "פכלבוהם אלמצריון ודכ'לו וראהם",
         "And the Egyptians pursued them and entered after them"),
        ("כֹּל סוּס פַּרְעֹה רִכְבּוֹ וּפָרָשָׁיו אֶל-תּוֹךְ הַיָּם",
         "גמיע כ'יל פרעון. ומראכבה ופרסאנה. אלי' וסט אלבחר",
         "all the horses of Pharaoh, and his chariots and his horsemen — into the midst of the sea."),
    ],
    24: [
        ("וַיְהִי בְּאַשְׁמֹרֶת הַבֹּקֶר", "פלמא כאן פי נובה' אלג'דאה",
         "And when it was at the turn of the morning watch"),
        ("וַיַּשְׁקֵף יְהוָה אֶל-מַחֲנֵה מִצְרַיִם בְּעַמּוּד אֵשׁ וְעָנָן",
         "אטלע אללה עלי' עסכר אלמצריון. בעמוד מן נאר וג'מאם",
         "God looked out over the camp of the Egyptians through a pillar of fire and cloud"),
        ("וַיָּהָם אֵת מַחֲנֵה מִצְרָיִם", "פאהאמה",
         "and He threw it into confusion."),
    ],
    25: [
        ("וַיָּסַר אֵת אֹפַן מַרְכְּבֹתָיו", "ואזאל לואלב מראכבהם",
         "And He removed the wheels of their chariots"),
        ("וַיְנַהֲגֵהוּ בִּכְבֵדֻת", "וסאקהם בענף",
         "and drove them with force"),
        ("וַיֹּאמֶר מִצְרַיִם אָנוּסָה מִפְּנֵי יִשְׂרָאֵל",
         "חין קאל אלמצריון. נהרב בין ידי בני אסראיל",
         "so that the Egyptians said: 'Let us flee from before the sons of Israel"),
        ("כִּי יְהוָה נִלְחָם לָהֶם בְּמִצְרָיִם",
         "לאן אללה. יחארב ענהם אלמצריון",
         "for God is fighting against the Egyptians on their behalf.'"),
    ],
    26: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה נְטֵה אֶת-יָדְךָ עַל-הַיָּם",
         "פקאל אללה למוסי'. מד ידך עלי' אלבחר",
         "And God said to Moses: 'Stretch out your hand over the sea"),
        ("וְיָשֻׁבוּ הַמַּיִם עַל-מִצְרַיִם עַל-רִכְבּוֹ וְעַל-פָּרָשָׁיו",
         "ירגע אלמא עלי' אלמצריון. ומראכבה ופרסאנה",
         "that the water may return upon the Egyptians, and upon their chariots and their horsemen.'"),
    ],
    27: [
        ("וַיֵּט מֹשֶׁה אֶת-יָדוֹ עַל-הַיָּם", "פמד מוסי' ידה עלי' אלבחר",
         "And Moses stretched out his hand over the sea"),
        ("וַיָּשָׁב הַיָּם לִפְנוֹת בֹּקֶר לְאֵיתָנוֹ", "פרגע. ענד אתגאה אלג'דאה לצעובתה",
         "and it returned, at the approach of morning, to its strength"),
        ("וּמִצְרַיִם נָסִים לִקְרָאתוֹ", "והם הארבין תלקאה",
         "while they were fleeing toward it"),
        ("וַיְנַעֵר יְהוָה אֶת-מִצְרַיִם בְּתוֹךְ הַיָּם", "פג'רקהם אללה פי וסטה",
         "and God drowned them in its midst."),
    ],
    28: [
        ("וַיָּשֻׁבוּ הַמַּיִם וַיְכַסּוּ אֶת-הָרֶכֶב וְאֶת-הַפָּרָשִׁים",
         "באן רגע אלמא. וג'טא אלמראכב ואלפרסאן",
         "In that the water returned and covered the chariots and the horsemen"),
        ("לְכֹל חֵיל פַּרְעֹה הַבָּאִים אַחֲרֵיהֶם בַּיָּם",
         "וסאיר גיוש פרעון. אלדכ'לין וראהם פי אלבחר",
         "and the rest of the hosts of Pharaoh who had entered after them into the sea"),
        ("לֹא-נִשְׁאַר בָּהֶם עַד-אֶחָד", "לם יבק מנהם ולא ואחד",
         "there did not remain among them even one."),
    ],
    29: [
        ("וּבְנֵי יִשְׂרָאֵל הָלְכוּ בַיַּבָּשָׁה בְּתוֹךְ הַיָּם",
         "ובני אסראיל. סארו פי אליבאס פי וסט אלבחר",
         "And the sons of Israel walked upon the dry land in the midst of the sea"),
        ("וְהַמַּיִם לָהֶם חֹמָה מִימִינָם וּמִשְּׂמֹאלָם",
         "ואלמא להם אסוארא. ען ימינהם וען יסארהם",
         "and the water was walls for them, on their right and on their left."),
    ],
    30: [
        ("וַיּוֹשַׁע יְהוָה בַּיּוֹם הַהוּא אֶת-יִשְׂרָאֵל--מִיַּד מִצְרָיִם",
         "ואג'את' אללה. פי ד'אלך אליום. בני אסראיל מן יד אלמצריון",
         "And God saved, on that day, the sons of Israel from the hand of the Egyptians"),
        ("וַיַּרְא יִשְׂרָאֵל אֶת-מִצְרַיִם מֵת עַל-שְׂפַת הַיָּם",
         "וראו בני אסראיל אלמצריון אמואתא עלי' שאט אלבחר",
         "and the sons of Israel saw the Egyptians dead upon the shore of the sea."),
    ],
    31: [
        ("וַיַּרְא יִשְׂרָאֵל אֶת-הַיָּד הַגְּדֹלָה אֲשֶׁר עָשָׂה יְהוָה בְּמִצְרַיִם",
         "פראו בני אסראיל אלאפה אל]עט'ימה] עצ'ימה. אלתי אחלהא אללה באלמצריון",
         "And the sons of Israel saw the great plague which God had brought upon the Egyptians"),
        ("וַיִּירְאוּ הָעָם אֶת-יְהוָה", "פכ'אפו אלקום אללה",
         "and the people feared God"),
        ("וַיַּאֲמִינוּ בַּיהוָה וּבְמֹשֶׁה עַבְדּוֹ", "ואמנו באללה. ובמוסי' רסולה",
         "and believed in God and in Moses His messenger."),
    ],
}
