"""Hand-authored alignment triples for Shemot chapter 16."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּסְעוּ מֵאֵילִם", "ורחלו מן אילים", "And they journeyed from Elim"),
        ("וַיָּבֹאוּ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל אֶל-מִדְבַּר-סִין",
         "וגאת גמאעה' בני אסראיל אלי' ברייה' סין",
         "and the congregation of the sons of Israel came to the wilderness of Sin"),
        ("אֲשֶׁר בֵּין-אֵילִם וּבֵין סִינָי", "אלד'י בין אילים ובין סיני",
         "which is between Elim and Sinai"),
        ("בַּחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הַשֵּׁנִי לְצֵאתָם מֵאֶרֶץ מִצְרָיִם",
         "מן אליום אלכ'מס עשר מן אלשהר אלת'אני. לכ'רוגהם מן בלד מצר",
         "on the fifteenth day of the second month after their departure from the land of Egypt."),
    ],
    2: [
        ("וילינו (וַיִּלּוֹנוּ) כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל עַל-מֹשֶׁה וְעַל-אַהֲרֹן--בַּמִּדְבָּר",
         "פתד'מר גמאעה' בני אסראיל. עלי' מוסי' והרון פי תלך אלבריה",
         "And the congregation of the sons of Israel voiced their discontent against Moses and Aaron in that wilderness."),
    ],
    3: [
        ("וַיֹּאמְרוּ אֲלֵהֶם בְּנֵי יִשְׂרָאֵל", "וקאלו להם בני אסראיל",
         "And the sons of Israel said to them"),
        ("מִי-יִתֵּן מוּתֵנוּ בְיַד-יְהוָה בְּאֶרֶץ מִצְרַיִם",
         "יא ליתנא מתנא באמר אללה פי בלד מצר",
         "'Would that we had died by the decree of God in the land of Egypt"),
        ("בְּשִׁבְתֵּנוּ עַל-סִיר הַבָּשָׂר בְּאָכְלֵנוּ לֶחֶם לָשֹׂבַע",
         "פי גלוסנא עלי' קדור אללחם. ואכלנא מן אלטעאם שבענא",
         "when we sat over the pots of meat, and ate of food to our fill"),
        ("כִּי-הוֹצֵאתֶם אֹתָנוּ אֶל-הַמִּדְבָּר הַזֶּה לְהָמִית אֶת-כָּל-הַקָּהָל הַזֶּה בָּרָעָב",
         "אד' אכ'רגתמונא אלי' הד'ה אלבריה. לתקתלו גמיע הד'א אלגוק פי אלגוע",
         "since you have brought us out into this wilderness to kill this entire throng by hunger.'"),
    ],
    4: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses"),
        ("הִנְנִי מַמְטִיר לָכֶם לֶחֶם מִן-הַשָּׁמָיִם", "האנא מנזל לכם טעאמא מן אלסמא",
         "'Behold, I am about to send down for you food from the sky"),
        ("וְיָצָא הָעָם וְלָקְטוּ דְּבַר-יוֹם בְּיוֹמוֹ", "יכ'רג אלקום פילקטונה אמר יום ביום",
         "the people shall go out and gather it, a day's portion each day"),
        ("לְמַעַן אֲנַסֶּנּוּ הֲיֵלֵךְ בְּתוֹרָתִי אִם-לֹא",
         "לקבל אן אמתחנהם. איסירו פי שראיעי אם לא",
         "so that I may test them — whether they will walk in my statutes or not.'"),
    ],
    5: [
        ("וְהָיָה בַּיּוֹם הַשִּׁשִּׁי", "פאד'א כאן פי אליום אלסאדס",
         "And when it is on the sixth day"),
        ("וְהֵכִינוּ אֵת אֲשֶׁר-יָבִיאוּ", "יצלחון מא יאתון בה",
         "they shall prepare what they bring in"),
        ("וְהָיָה מִשְׁנֶה עַל אֲשֶׁר-יִלְקְטוּ יוֹם יוֹם",
         "פאנה יכון צ'עף מא ילקטון פי כל יום",
         "and it shall be double what they gather on every other day."),
    ],
    6: [
        ("וַיֹּאמֶר מֹשֶׁה וְאַהֲרֹן אֶל-כָּל-בְּנֵי יִשְׂרָאֵל",
         "פקאל מוסי' והרון. לגמיע בני אסראיל",
         "And Moses and Aaron said to all the sons of Israel"),
        ("עֶרֶב--וִידַעְתֶּם כִּי יְהוָה הוֹצִיא אֶתְכֶם מֵאֶרֶץ מִצְרָיִם",
         "באלעשא תעלמו. אן אללה אכ'רגכם מן בלד מצר",
         "'At the evening you shall know that God has brought you out from the land of Egypt;"),
    ],
    7: [
        ("וּבֹקֶר וּרְאִיתֶם אֶת-כְּבוֹד יְהוָה", "ובאלג'דאה תנצ'רו כרם אללה",
         "and in the morning you shall behold the bounty of God"),
        ("בְּשָׁמְעוֹ אֶת-תְּלֻנֹּתֵיכֶם עַל-יְהוָה", "אד' סמע תד'מרכם עליה",
         "since He has heard your discontent against Him"),
        ("וְנַחְנוּ מָה כִּי תלונו (תַלִּינוּ) עָלֵינוּ", "ונחן מן. אד' תתד'מרון עלינא",
         "And who are we, that you voice your discontent against us?'"),
    ],
    8: [
        ("וַיֹּאמֶר מֹשֶׁה בְּתֵת יְהוָה לָכֶם בָּעֶרֶב בָּשָׂר לֶאֱכֹל",
         "ת'ם קאל מוסי'. ד'אך באן יעטיכם אללה באלעשא לחמא תאכלונה",
         "Then Moses said: 'This shall be when God gives you meat to eat at the evening"),
        ("וְלֶחֶם בַּבֹּקֶר לִשְׂבֹּעַ", "וטעאמא באלג'דאה תשבעונה",
         "and food to fill you in the morning"),
        ("בִּשְׁמֹעַ יְהוָה אֶת-תְּלֻנֹּתֵיכֶם אֲשֶׁר-אַתֶּם מַלִּינִם עָלָיו",
         "אד' סמע תד'מרכם אלד'י תתד'מרו עליה",
         "since He has heard your discontent which you voice against Him"),
        ("וְנַחְנוּ מָה לֹא-עָלֵינוּ תְלֻנֹּתֵיכֶם כִּי עַל-יְהוָה",
         "ונחן מן. ליס עלינא תד'מרכם בל עלי' אללה",
         "And who are we? Your discontent is not against us but against God.'"),
    ],
    9: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן", "פקאל מוסי' להרון",
         "And Moses said to Aaron"),
        ("אֱמֹר אֶל-כָּל-עֲדַת בְּנֵי יִשְׂרָאֵל קִרְבוּ לִפְנֵי יְהוָה",
         "קל לגמאעה' בני אסראיל. תקדמו בין ידי אללה",
         "'Say to the congregation of the sons of Israel: Come forward before God"),
        ("כִּי שָׁמַע אֵת תְּלֻנֹּתֵיכֶם", "פאנה קד סמע תד'מרכם",
         "for He has heard your discontent.'"),
    ],
    10: [
        ("וַיְהִי כְּדַבֵּר אַהֲרֹן אֶל-כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל",
         "פכמא כלם הרון בד'אלך גמאעה' בני אסראיל",
         "And as Aaron spoke thus to the congregation of the sons of Israel"),
        ("וַיִּפְנוּ אֶל-הַמִּדְבָּר", "אלתפתו אלי' אלבר", "they turned toward the wilderness"),
        ("וְהִנֵּה כְּבוֹד יְהוָה נִרְאָה בֶּעָנָן", "פאד'א בנור אללה. קד צ'הר פי אלג'מאם",
         "and behold, the light of God had appeared in the cloud."),
    ],
    11: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    12: [
        ("שָׁמַעְתִּי אֶת-תְּלוּנֹּת בְּנֵי יִשְׂרָאֵל", "קד סמעת תד'מר בני אסראיל",
         "'I have heard the discontent of the sons of Israel"),
        ("דַּבֵּר אֲלֵהֶם לֵאמֹר בֵּין הָעַרְבַּיִם תֹּאכְלוּ בָשָׂר",
         "קל להם בין אלגרובין תאכלון לחמא",
         "Say to them: Between the two evenings you shall eat meat"),
        ("וּבַבֹּקֶר תִּשְׂבְּעוּ-לָחֶם", "ובאלג'דאה תשבעון טעאמא",
         "and in the morning you shall be filled with food"),
        ("וִידַעְתֶּם כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם", "ותעלמון אני אללה רבכם",
         "and you shall know that I am God your Lord.'"),
    ],
    13: [
        ("וַיְהִי בָעֶרֶב--וַתַּעַל הַשְּׂלָו וַתְּכַס אֶת-הַמַּחֲנֶה",
         "פלמא כאן באלעשא. צעד אלסלוא. פג'טא אלעסכר",
         "And when it was at the evening, the quail came up and covered the camp"),
        ("וּבַבֹּקֶר הָיְתָה שִׁכְבַת הַטַּל סָבִיב לַמַּחֲנֶה",
         "ובאלג'דאה כאן סכב אלטל. חואלי אלעסכר",
         "and in the morning there was a layer of dew around the camp."),
    ],
    14: [
        ("וַתַּעַל שִׁכְבַת הַטָּל", "ולמא צעד סכב אלטל",
         "And when the layer of dew lifted"),
        ("וְהִנֵּה עַל-פְּנֵי הַמִּדְבָּר דַּק מְחֻסְפָּס", "פאד'א עלי' וגה אלבריה בשי דקיק מדחרג",
         "behold, upon the face of the wilderness was something fine and rounded"),
        ("דַּק כַּכְּפֹר עַל-הָאָרֶץ", "דקיק כאלרמק עלי' אלארץ'",
         "fine as frost upon the ground."),
    ],
    15: [
        ("וַיִּרְאוּ בְנֵי-יִשְׂרָאֵל וַיֹּאמְרוּ אִישׁ אֶל-אָחִיו מָן הוּא",
         "פנצ'רוה בני אסראיל. פקאל בעצ'הם לבעץ' הו מן",
         "And the sons of Israel saw it, and said one to another: 'It is manna'"),
        ("כִּי לֹא יָדְעוּ מַה-הוּא", "לאנהם לם יעלמו מא הו",
         "for they did not know what it was"),
        ("וַיֹּאמֶר מֹשֶׁה אֲלֵהֶם הוּא הַלֶּחֶם אֲשֶׁר נָתַן יְהוָה לָכֶם לְאָכְלָה",
         "פקאל מוסי' להם. הו אלטעאם. אלד'י אעטה אללה. ליכון לכם מאכלא",
         "And Moses said to them: 'It is the food which God has given, to be for you as food.'"),
    ],
    16: [
        ("זֶה הַדָּבָר אֲשֶׁר צִוָּה יְהוָה", "הד'א אלאמר אלד'י אמר אללה בה",
         "This is the matter which God has commanded"),
        ("לִקְטוּ מִמֶּנּוּ אִישׁ לְפִי אָכְלוֹ", "אן ילקטו מנה כל רגל עלי' קדר עיאלה",
         "let each man gather from it according to the measure of his household"),
        ("עֹמֶר לַגֻּלְגֹּלֶת מִסְפַּר נַפְשֹׁתֵיכֶם", "מרזבאן לכל גמגמה. עלי' אחצא אנפסכם",
         "a marzab for each head, by the count of your persons"),
        ("אִישׁ לַאֲשֶׁר בְּאָהֳלוֹ תִּקָּחוּ", "כל רג'ל יאכד' למן פי ביתה",
         "each man shall take for those in his house."),
    ],
    17: [
        ("וַיַּעֲשׂוּ-כֵן בְּנֵי יִשְׂרָאֵל", "פצנעו כד'אך בני אסראיל",
         "And the sons of Israel did so"),
        ("וַיִּלְקְטוּ הַמַּרְבֶּה וְהַמַּמְעִיט", "ולקטו. מן כת'ר ומן קלל",
         "and gathered — some more and some less."),
    ],
    18: [
        ("וַיָּמֹדּוּ בָעֹמֶר", "פכאלוה באלמרזבאן", "And they measured it by the marzab"),
        ("וְלֹא הֶעְדִּיף הַמַּרְבֶּה וְהַמַּמְעִיט לֹא הֶחְסִיר",
         "ולם יפצ'ל מן כת'ר ומן קלל לם ינקצה",
         "and he who had gathered more had nothing left over, and he who had gathered less lacked nothing"),
        ("אִישׁ לְפִי-אָכְלוֹ לָקָטוּ", "כל רגל עלי' קדר עיאלה לקטו",
         "each man gathered according to the measure of his household."),
    ],
    19: [
        ("וַיֹּאמֶר מֹשֶׁה אֲלֵהֶם", "פקאל להם מוסי'", "And Moses said to them"),
        ("אִישׁ אַל-יוֹתֵר מִמֶּנּוּ עַד-בֹּקֶר", "לא יבק אנסאן מנה שייא אלי' אלג'דאה",
         "'Let no person leave any of it until the morning.'"),
    ],
    20: [
        ("וְלֹא-שָׁמְעוּ אֶל-מֹשֶׁה", "פלם יקבלו מן מוסי'",
         "But they did not heed Moses"),
        ("וַיּוֹתִרוּ אֲנָשִׁים מִמֶּנּוּ עַד-בֹּקֶר", "ובקו מנה אנאס אלי' אלג'דאה",
         "and some people left of it until the morning"),
        ("וַיָּרֻם תּוֹלָעִים וַיִּבְאַשׁ", "פנתן ונג'ל דודא",
         "and it putrefied and swarmed with worms"),
        ("וַיִּקְצֹף עֲלֵהֶם מֹשֶׁה", "פסכ'ט עליהם. מוסי'",
         "and Moses was angered with them."),
    ],
    21: [
        ("וַיִּלְקְטוּ אֹתוֹ בַּבֹּקֶר בַּבֹּקֶר אִישׁ כְּפִי אָכְלוֹ",
         "וכאנו ילקטונה פי כל ג'דאה כל רגל עלי' קדר עיאלה",
         "And they would gather it each morning, every man according to the measure of his household"),
        ("וְחַם הַשֶּׁמֶשׁ וְנָמָס", "פאד'א חמית אלשמס תמאסא",
         "and when the sun grew hot, it melted away."),
    ],
    22: [
        ("וַיְהִי בַּיּוֹם הַשִּׁשִּׁי לָקְטוּ לֶחֶם מִשְׁנֶה",
         "ולמא כאן פי אליום אלסאדס. לקטו מן אלטעאם צעפא",
         "And when it was on the sixth day, they gathered food in double measure"),
        ("שְׁנֵי הָעֹמֶר לָאֶחָד", "מרזבאנין לכל ואחד",
         "two marzabs for each one"),
        ("וַיָּבֹאוּ כָּל-נְשִׂיאֵי הָעֵדָה וַיַּגִּידוּ לְמֹשֶׁה",
         "פגאו גמיע אשראף אלגמאעה. ואכ'ברו מוסי'",
         "and all the nobles of the congregation came and informed Moses."),
    ],
    23: [
        ("וַיֹּאמֶר אֲלֵהֶם הוּא אֲשֶׁר דִּבֶּר יְהוָה", "פקאל להם. הו מא קאל אללה",
         "And he said to them: 'It is what God has said"),
        ("שַׁבָּתוֹן שַׁבַּת-קֹדֶשׁ לַיהוָה מָחָר", "עטלה הי סבת מקדסא ללה ג'דא",
         "a rest — it is a Sabbath consecrated to God tomorrow"),
        ("אֵת אֲשֶׁר-תֹּאפוּ אֵפוּ וְאֵת אֲשֶׁר-תְּבַשְּׁלוּ בַּשֵּׁלוּ",
         "מא תרידו אן תכ'בזון אכ'בזו",
         "What you wish to bake, bake; and what you wish to cook, cook"),
        ("וְאֵת כָּל-הָעֹדֵף הַנִּיחוּ לָכֶם לְמִשְׁמֶרֶת עַד-הַבֹּקֶר",
         "ומא פצ'ל. דעוה לכם מחפוצ'א אלי' אלג'דאה",
         "and what remains, leave it preserved for yourselves until the morning.'"),
    ],
    24: [
        ("וַיַּנִּיחוּ אֹתוֹ עַד-הַבֹּקֶר כַּאֲשֶׁר צִוָּה מֹשֶׁה",
         "פודעוה אלי' אלג'דאה. כמא אמרהם מוסי'",
         "And they left it until the morning, as Moses had commanded them"),
        ("וְלֹא הִבְאִישׁ וְרִמָּה לֹא-הָיְתָה בּוֹ", "ולם ינתן. ורמה לם תכון פיה",
         "and it did not putrefy, and there was no worm in it."),
    ],
    25: [
        ("וַיֹּאמֶר מֹשֶׁה אִכְלֻהוּ הַיּוֹם", "פקאל מוסי' כלוה אליום",
         "And Moses said: 'Eat it today"),
        ("כִּי-שַׁבָּת הַיּוֹם לַיהוָה", "לאן אליום סבת ללה",
         "for today is a Sabbath to God"),
        ("הַיּוֹם לֹא תִמְצָאֻהוּ בַּשָּׂדֶה", "ואליום לא תגדוה פי אלצחרי'",
         "today you will not find it in the wilderness.'"),
    ],
    26: [
        ("שֵׁשֶׁת יָמִים תִּלְקְטֻהוּ", "סתה' איאם תלקטונה",
         "'Six days you shall gather it"),
        ("וּבַיּוֹם הַשְּׁבִיעִי שַׁבָּת לֹא יִהְיֶה-בּוֹ", "ואליום אלסאבע. סבת לא יכון פיה",
         "and on the seventh day — it is a Sabbath; there will be none in it.'"),
    ],
    27: [
        ("וַיְהִי בַּיּוֹם הַשְּׁבִיעִי", "פלמא כאן פי אליום אלסאבע",
         "And when it was on the seventh day"),
        ("יָצְאוּ מִן-הָעָם לִלְקֹט וְלֹא מָצָאוּ", "כ'רג אנאס מן אלקום לילתקטון. פלם יגדו שייא",
         "some people from the clan went out to gather, but they found nothing."),
    ],
    28: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses"),
        ("עַד-אָנָה מֵאַנְתֶּם לִשְׁמֹר מִצְו‍ֹתַי וְתוֹרֹתָי",
         "אלי' כם קד אביתם. אן תחפצו וצאיאי ושראיעי",
         "'How long have you refused to keep My commandments and My statutes?'"),
    ],
    29: [
        ("רְאוּ כִּי-יְהוָה נָתַן לָכֶם הַשַּׁבָּת", "אנצ'רו. אן אללה קד אעטאכם שריעה' אלסבת",
         "'See that God has given you the statute of the Sabbath"),
        ("עַל-כֵּן הוּא נֹתֵן לָכֶם בַּיּוֹם הַשִּׁשִּׁי לֶחֶם יוֹמָיִם",
         "לד'אלך הו מעטיכם. פי אליום אלסאדס טעאם יומין",
         "therefore He is giving you on the sixth day food for two days"),
        ("שְׁבוּ אִישׁ תַּחְתָּיו אַל-יֵצֵא אִישׁ מִמְּקֹמוֹ--בַּיּוֹם הַשְּׁבִיעִי",
         "פליגלס כל אמר מכאנה. ולא יכ'ר'ג אחד מן מו'צעה פי אליום אלסאבע",
         "Let every person remain in his place; let no one go out from his place on the seventh day.'"),
    ],
    30: [
        ("וַיִּשְׁבְּתוּ הָעָם בַּיּוֹם הַשְּׁבִעִי", "פאסבת אלקום פי אליום אלסאבע",
         "And the people observed the Sabbath on the seventh day."),
    ],
    31: [
        ("וַיִּקְרְאוּ בֵית-יִשְׂרָאֵל אֶת-שְׁמוֹ מָן", "וסמא אל אסראיל אסמה אלמן",
         "And the house of Israel called its name the manna"),
        ("וְהוּא כְּזֶרַע גַּד לָבָן", "והו כבזר אלכבזרה אביץ'",
         "and it was like the seed of coriander, white"),
        ("וְטַעְמוֹ כְּצַפִּיחִת בִּדְבָשׁ", "וטעמה כקטאיף בעסל",
         "and its taste was like wafers with honey."),
    ],
    32: [
        ("וַיֹּאמֶר מֹשֶׁה זֶה הַדָּבָר אֲשֶׁר צִוָּה יְהוָה",
         "פקאל מוסי. הד'א אלאמר אלד'י אמר אללה בה",
         "And Moses said: 'This is the matter which God has commanded"),
        ("מְלֹא הָעֹמֶר מִמֶּנּוּ לְמִשְׁמֶרֶת לְדֹרֹתֵיכֶם",
         "מל אלמרזבאן מנה. יכון מחפוצא לאגיאלכם",
         "a marzab-full of it shall be kept for your generations"),
        ("לְמַעַן יִרְאוּ אֶת-הַלֶּחֶם אֲשֶׁר הֶאֱכַלְתִּי אֶתְכֶם בַּמִּדְבָּר",
         "לכי ינצרון אלטעאם אלד'י אטעמתכם פי אלבר",
         "so that they may see the food with which I fed you in the wilderness"),
        ("בְּהוֹצִיאִי אֶתְכֶם מֵאֶרֶץ מִצְרָיִם", "חין אכ'רגתכם מן בלד מצר",
         "when I brought you out from the land of Egypt.'"),
    ],
    33: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן", "פקאל מוסי' להרון", "And Moses said to Aaron"),
        ("קַח צִנְצֶנֶת אַחַת וְתֶן-שָׁמָּה מְלֹא-הָעֹמֶר מָן",
         "כ'ד ברנייה ואחדה. ואגעל פיהא מל אלמרזבאן מנא",
         "'Take one jar, and put in it a marzab-full of manna"),
        ("וְהַנַּח אֹתוֹ לִפְנֵי יְהוָה לְמִשְׁמֶרֶת לְדֹרֹתֵיכֶם",
         "וצעה בין ידי אללה. מחפוצא לאגיאלכם",
         "and place it before God, preserved for their generations.'"),
    ],
    34: [
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶל-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "As God commanded Moses"),
        ("וַיַּנִּיחֵהוּ אַהֲרֹן לִפְנֵי הָעֵדֻת לְמִשְׁמָרֶת", "וצעה הרון. בין ידי אלשהאדה מחפוצא",
         "Aaron placed it before the testimony, preserved."),
    ],
    35: [
        ("וּבְנֵי יִשְׂרָאֵל אָכְלוּ אֶת-הַמָּן אַרְבָּעִים שָׁנָה",
         "ובני אסראיל. אכלו אלמן ארבעין סנה",
         "And the sons of Israel ate the manna forty years"),
        ("עַד-בֹּאָם אֶל-אֶרֶץ נוֹשָׁבֶת", "אלי' דכולהם אלי' בלד עאמר",
         "until their entry into an inhabited land"),
        ("אֶת-הַמָּן אָכְלוּ--עַד-בֹּאָם אֶל-קְצֵה אֶרֶץ כְּנָעַן",
         "אכלוה אלי' דכולהם. אלי' טרף בלד כנעאן",
         "they ate it until their entry into the border of the land of Canaan."),
    ],
    36: [
        ("וְהָעֹמֶר עֲשִׂרִית הָאֵיפָה הוּא", "וכאן אלמרזבאן עשר אלויבה",
         "And the marzab was a tenth of the waybah."),
    ],
}
