"""Hand-authored alignment triples for Shemot chapter 25."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "מר בני אסראיל",
         "Command the sons of Israel"),
        ("וְיִקְחוּ-לִי תְּרוּמָה", "באן יאכ'דו לי רפיעה",
         "that they take for Me an raised-offering"),
        ("מֵאֵת כָּל-אִישׁ אֲשֶׁר יִדְּבֶנּוּ לִבּוֹ", "מן כל רגל תסכו נפסה",
         "from every man whose soul is generous"),
        ("תִּקְחוּ אֶת-תְּרוּמָתִי", "תאכ'דו רפיעתי",
         "you shall take My raised-offering."),
    ],
    3: [
        ("וְזֹאת הַתְּרוּמָה אֲשֶׁר תִּקְחוּ מֵאִתָּם", "והד'ה אלרפיעה. אלד'י תאכ'דוהא מנהם",
         "And this is the raised-offering which you shall take from them"),
        ("זָהָב וָכֶסֶף וּנְחֹשֶׁת", "ד'הב וורק ונחאס",
         "gold, and silver, and copper;"),
    ],
    4: [
        ("וּתְכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי", "ואסמאנגון וארגואן. וצבג' קרמז",
         "and blue, and purple, and scarlet dye"),
        ("וְשֵׁשׁ וְעִזִּים", "ועשר ומרעזא",
         "and fine linen, and goat-hair;"),
    ],
    5: [
        ("וְעֹרֹת אֵילִם מְאָדָּמִים", "וגלוד כבאש אדים",
         "and the skins of tanned rams"),
        ("וְעֹרֹת תְּחָשִׁים", "וגלוד דארש", "and the skins of tahash"),
        ("וַעֲצֵי שִׁטִּים", "וכ'שב אלסנט", "and the wood of the acacia-tree;"),
    ],
    6: [
        ("שֶׁמֶן לַמָּאֹר", "ודהן לאלאצ'אה", "and oil for lighting"),
        ("בְּשָׂמִים לְשֶׁמֶן הַמִּשְׁחָה", "ואטיאב לדהן אלמסח",
         "and spices for the anointing oil"),
        ("וְלִקְטֹרֶת הַסַּמִּים", "ובכ'ור אלצמוג'", "and the incense of resins;"),
    ],
    7: [
        ("אַבְנֵי-שֹׁהַם", "חגארה' בלור", "crystal stones"),
        ("וְאַבְנֵי מִלֻּאִים לָאֵפֹד וְלַחֹשֶׁן", "וחגארה' נצ'אם. לאלצדרה ולאלבדנה",
         "and stones for setting — for the breastpiece and for the vestment."),
    ],
    8: [
        ("וְעָשׂוּ לִי מִקְדָּשׁ", "ויצנעו לי מן גמיע ד'אלך מקדסא",
         "And they shall make for Me, from all of these, a sanctuary"),
        ("וְשָׁכַנְתִּי בְּתוֹכָם", "אסכן נורי פי מא בינהם",
         "and I shall settle My light in their midst."),
    ],
    9: [
        ("כְּכֹל אֲשֶׁר אֲנִי מַרְאֶה אוֹתְךָ", "כגמיע מא אנא מוריך",
         "According to all that I am showing you"),
        ("אֵת תַּבְנִית הַמִּשְׁכָּן", "מן שכל אלמסכן",
         "of the form of the tabernacle"),
        ("וְאֵת תַּבְנִית כָּל-כֵּלָיו", "ושכל גמיע אניתה",
         "and the form of all its vessels"),
        ("וְכֵן תַּעֲשׂוּ", "כד'אך תצנעו", "so shall you make it."),
    ],
    10: [
        ("וְעָשׂוּ אֲרוֹן עֲצֵי שִׁטִּים", "ויצנעון צנדוקא מן כ'שב אלסנט",
         "And they shall make a chest of acacia wood"),
        ("אַמָּתַיִם וָחֵצִי אָרְכּוֹ", "ד'ראעין ונצף טולה",
         "two cubits and a half its length"),
        ("וְאַמָּה וָחֵצִי רָחְבּוֹ", "וד'ראע ונצף ערצה",
         "and a cubit and a half its width"),
        ("וְאַמָּה וָחֵצִי קֹמָתוֹ", "וד'ראע ונצף סמכה",
         "and a cubit and a half its height."),
    ],
    11: [
        ("וְצִפִּיתָ אֹתוֹ זָהָב טָהוֹר מִבַּיִת וּמִחוּץ תְּצַפֶּנּוּ",
         "וג'שה בד'הב כ'אלץ. מן דאכ'ל ומן כ'ארג'",
         "And overlay it with pure gold — from within it and from without it"),
        ("וְעָשִׂיתָ עָלָיו זֵר זָהָב סָבִיב", "ואצנע עלי'ה. זיגא מן ד'הב מסתדירא",
         "and make upon it a rim of gold, going around."),
    ],
    12: [
        ("וְיָצַקְתָּ לּוֹ אַרְבַּע טַבְּעֹת זָהָב", "וצג' לה ארבע חלק מן ד'הב",
         "And cast for it four rings of gold"),
        ("וְנָתַתָּה עַל אַרְבַּע פַּעֲמֹתָיו", "ואגעלהא פי ארבע גהאתה",
         "and place them on its four sides"),
        ("וּשְׁתֵּי טַבָּעֹת עַל-צַלְעוֹ הָאֶחָת", "חלקתין פי גאנבה אלואחד",
         "two rings on the one side"),
        ("וּשְׁתֵּי טַבָּעֹת עַל-צַלְעוֹ הַשֵּׁנִית", "וחלקתין פי גאנבה אלת'אני",
         "and two rings on the second side."),
    ],
    13: [
        ("וְעָשִׂיתָ בַדֵּי עֲצֵי שִׁטִּים", "ואצנע דהוקא מן כ'שב אלסנט",
         "And make poles of acacia wood"),
        ("וְצִפִּיתָ אֹתָם זָהָב", "וג'שהא בד'הב", "and overlay them with gold."),
    ],
    14: [
        ("וְהֵבֵאתָ אֶת-הַבַּדִּים בַּטַּבָּעֹת", "ואדכ'ל אלדהוק פי אלחלק",
         "And insert the poles into the rings"),
        ("עַל צַלְעֹת הָאָרֹן לָשֵׂאת אֶת-הָאָרֹן בָּהֶם",
         "עלי' גאנבי אלצנדוק.",
         "on the sides of the chest, to carry it by them."),
    ],
    15: [
        ("בְּטַבְּעֹת הָאָרֹן יִהְיוּ הַבַּדִּים", "פי חלק אלצנדוק",
         "In the rings of the chest shall the poles remain"),
        ("לֹא יָסֻרוּ מִמֶּנּוּ", "לא תזול מנה",
         "they shall not be removed from it."),
    ],
    16: [
        ("וְנָתַתָּ אֶל-הָאָרֹן", "ואגעל פי אלצנדוק",
         "And place in the chest"),
        ("אֵת הָעֵדֻת אֲשֶׁר אֶתֵּן אֵלֶיךָ", "אלשהאדה אלתי אעטיכהא",
         "the testimony which I shall give you."),
    ],
    17: [
        ("וְעָשִׂיתָ כַפֹּרֶת זָהָב טָהוֹר", "ואצנע ג'שאא מן ד'הב כ'אלץ",
         "And make a cover of pure gold"),
        ("אַמָּתַיִם וָחֵצִי אָרְכָּהּ", "ד'ראעין ונצף טולה",
         "two cubits and a half its length"),
        ("וְאַמָּה וָחֵצִי רָחְבָּהּ", "וד'ראע ונצף ערצה",
         "and a cubit and a half its width."),
    ],
    18: [
        ("וְעָשִׂיתָ שְׁנַיִם כְּרֻבִים זָהָב", "ואצנע כרובין מן ד'הב",
         "And make two cherubim of gold"),
        ("מִקְשָׁה תַּעֲשֶׂה אֹתָם", "מצמתין תצנעהמא",
         "solid shall you make them"),
        ("מִשְּׁנֵי קְצוֹת הַכַּפֹּרֶת", "מן טרפי אלג'שא",
         "from the two ends of the cover."),
    ],
    19: [
        ("וַעֲשֵׂה כְּרוּב אֶחָד מִקָּצָה מִזֶּה וּכְרוּב-אֶחָד מִקָּצָה מִזֶּה",
         "ואצנע כרובא מן הד'א אלטרף",
         "And make them: a cherub from this end and a cherub from this end"),
        ("מִן-הַכַּפֹּרֶת תַּעֲשׂוּ אֶת-הַכְּרֻבִים עַל-שְׁנֵי קְצוֹתָיו",
         "מן נפס אלג'שא. תצנע אלכרובין מן טרפיה",
         "from the cover itself shall you make the cherubim, from its two ends."),
    ],
    20: [
        ("וְהָיוּ הַכְּרֻבִים פֹּרְשֵׂי כְנָפַיִם לְמַעְלָה",
         "ויכונא אלכרובין באסטין אגנחתהמא אלי' פוק",
         "And the cherubim shall be spreading their wings upward"),
        ("סֹכְכִים בְּכַנְפֵיהֶם עַל-הַכַּפֹּרֶת", "ומצ'ללין בהא עלי' אלג'שא",
         "and overshadowing with them the cover"),
        ("וּפְנֵיהֶם אִישׁ אֶל-אָחִיו אֶל-הַכַּפֹּרֶת", "ווגוההמא אלואחד אלי' אלאכ'ר. ואלי' אלג'שא",
         "and the face of the one toward the other, and toward the cover"),
        ("יִהְיוּ פְּנֵי הַכְּרֻבִים", "תכון וגוההמא",
         "thus shall their faces be."),
    ],
    21: [
        ("וְנָתַתָּ אֶת-הַכַּפֹּרֶת עַל-הָאָרֹן מִלְמָעְלָה",
         "ואגעל אלג'שא. עלי' אלצנדוק מן פוק",
         "And place the cover upon the chest from above"),
        ("וְאֶל-הָאָרֹן--תִּתֵּן אֶת-הָעֵדֻת אֲשֶׁר אֶתֵּן אֵלֶיךָ",
         "בעד מא תגעל פי אלצנדוק. אלשהאדה אלד'י אעטיכהא",
         "after you have placed in the chest the testimony which I shall give you."),
    ],
    22: [
        ("וְנוֹעַדְתִּי לְךָ שָׁם", "פאחאצ'רך הנאך",
         "And I shall be present there with you"),
        ("וְדִבַּרְתִּי אִתְּךָ מֵעַל הַכַּפֹּרֶת מִבֵּין שְׁנֵי הַכְּרֻבִים",
         "וא'כ'אטבך מן פוק אלג'שא. מן בין אלכרובין",
         "and I shall speak to you from above the cover, from between the two cherubim"),
        ("אֲשֶׁר עַל-אֲרוֹן הָעֵדֻת", "אלד'י עלי' צנדוק אלשהאדה",
         "which are upon the chest of the testimony"),
        ("אֵת כָּל-אֲשֶׁר אֲצַוֶּה אוֹתְךָ אֶל-בְּנֵי יִשְׂרָאֵל",
         "בגמיע מא אמרך אלי' בני אסראיל",
         "with all that I command you to the sons of Israel."),
    ],
    23: [
        ("וְעָשִׂיתָ שֻׁלְחָן עֲצֵי שִׁטִּים", "ואצנע מאידה מן כ'שב אלסנט",
         "And make a table of acacia wood"),
        ("אַמָּתַיִם אָרְכּוֹ וְאַמָּה רָחְבּוֹ", "ד'ראעין טולהא וד'ראע ערצ'הא",
         "two cubits its length, and a cubit its width"),
        ("וְאַמָּה וָחֵצִי קֹמָתוֹ", "וד'ראע ונצף סמכהא",
         "and a cubit and a half its height."),
    ],
    24: [
        ("וְצִפִּיתָ אֹתוֹ זָהָב טָהוֹר", "וג'שהא בד'הב כ'אלץ",
         "And overlay it with pure gold"),
        ("וְעָשִׂיתָ לּוֹ זֵר זָהָב סָבִיב", "ואצנע להא. זיגא מן ד'הב מסתדירא",
         "and make for it a rim of gold, going around."),
    ],
    25: [
        ("וְעָשִׂיתָ לּוֹ מִסְגֶּרֶת טֹפַח סָבִיב", "ואצנע להא חאפה. מקדאר קבצ'ה מסתדירא",
         "And make for it a border, the measure of a handbreadth, going around"),
        ("וְעָשִׂיתָ זֵר-זָהָב לְמִסְגַּרְתּוֹ סָבִיב", "ואצנע זיגא מן ד'הב. לחאפתהא מסתדירא",
         "and make a rim of gold for its border, going around."),
    ],
    26: [
        ("וְעָשִׂיתָ לּוֹ אַרְבַּע טַבְּעֹת זָהָב", "וצג' להא. ארבע חלק מן ד'הב",
         "And cast for it four rings of gold"),
        ("וְנָתַתָּ אֶת-הַטַּבָּעֹת עַל אַרְבַּע הַפֵּאֹת", "ואגעל אלחלק. פי אלארבע אלזואיא",
         "and place the rings at its four corners"),
        ("אֲשֶׁר לְאַרְבַּע רַגְלָיו", "אלתי באזא ארבע ארגלהא",
         "which are opposite its four legs."),
    ],
    27: [
        ("לְעֻמַּת הַמִּסְגֶּרֶת תִּהְיֶיןָ הַטַּבָּעֹת", "אמאם אלחאפה תכון אלחלק",
         "Facing the border shall the rings be"),
        ("לְבָתִּים לְבַדִּים לָשֵׂאת אֶת-הַשֻּׁלְחָן", "מכאנא לאלדהוק. לתחמל בהא",
         "as a place for the poles, by which to carry it."),
    ],
    28: [
        ("וְעָשִׂיתָ אֶת-הַבַּדִּים עֲצֵי שִׁטִּים", "ואצנע אלדהוק מן כ'שב אלסנט",
         "And make the poles of acacia wood"),
        ("וְצִפִּיתָ אֹתָם זָהָב", "וג'שהא בד'הב", "and overlay them with gold"),
        ("וְנִשָּׂא-בָם אֶת-הַשֻּׁלְחָן", "לתחמל בהא אלמאידה",
         "so that the table may be carried by them."),
    ],
    29: [
        ("וְעָשִׂיתָ קְּעָרֹתָיו וְכַפֹּתָיו", "ואצנע קצאעהא ודרוגהא",
         "And make its dishes and its drawers"),
        ("וּקְשׂוֹתָיו וּמְנַקִּיֹּתָיו", "ומדאהנהא. אומלאעקהא",
         "and its flagons and its ladles"),
        ("אֲשֶׁר יֻסַּךְ בָּהֵן", "לד'י תג'טא בהא",
         "by which it is covered"),
        ("זָהָב טָהוֹר תַּעֲשֶׂה אֹתָם", "מן ד'הב כ'אלץ תצנעהא",
         "of pure gold shall you make them."),
    ],
    30: [
        ("וְנָתַתָּ עַל-הַשֻּׁלְחָן לֶחֶם פָּנִים לְפָנַי תָּמִיד",
         "ואגעל עלי' אלמאידה. כ'בזא מוגהא בין ידיי דאימא",
         "And place upon the table bread that is presented before Me continually."),
    ],
    31: [
        ("וְעָשִׂיתָ מְנֹרַת זָהָב טָהוֹר מִקְשָׁה תֵּעָשֶׂה הַמְּנוֹרָה",
         "ואצנע מנארה מן ד'הב כ'אלץ. מצמתה תצנעהא",
         "And make a lampstand of pure gold — solid shall the lampstand be made"),
        ("יְרֵכָהּ וְקָנָהּ", "ארגלהא וקצבהא",
         "its base and its shaft"),
        ("גְּבִיעֶיהָ כַּפְתֹּרֶיהָ וּפְרָחֶיהָ מִמֶּנָּה יִהְיוּ",
         "וגאמאתהא. ותפאפיחהא וסואסנהא מנהא יכונו",
         "and its cups, and its apples and its lilies shall be of it."),
    ],
    32: [
        ("וְשִׁשָּׁה קָנִים יֹצְאִים מִצִּדֶּיהָ", "סת קצבאת. כ'ארגאת מן גאנביהא",
         "Six branches going out from its sides"),
        ("שְׁלֹשָׁה קְנֵי מְנֹרָה מִצִּדָּהּ הָאֶחָד", "ת'לאת' קצבאת מן גאנבהא אלואחד",
         "three branches from its one side"),
        ("וּשְׁלֹשָׁה קְנֵי מְנֹרָה מִצִּדָּהּ הַשֵּׁנִי", "ות'לאת' קצבאת. מן גאנבהא אלת'אני",
         "and three branches from its second side."),
    ],
    33: [
        ("שְׁלֹשָׁה גְבִעִים מְשֻׁקָּדִים בַּקָּנֶה הָאֶחָד", "ת'לאת גאמאת. מלווזאת. פי כל קצבה",
         "Three almond-shaped cups in each branch"),
        ("כַּפְתֹּר וָפֶרַח", "תפאחה וסוסנה", "an apple and a lily"),
        ("כֵּן לְשֵׁשֶׁת הַקָּנִים הַיֹּצְאִים מִן-הַמְּנֹרָה",
         "כד'אך לאלסת אלקצבאת. אלכ'ארגאת מנהא",
         "so for the six branches going out from it."),
    ],
    34: [
        ("וּבַמְּנֹרָה אַרְבָּעָה גְבִעִים מְשֻׁקָּדִים",
         "ופי אלמנארה ארבע גאמאת. מלווזאת",
         "And in the lampstand itself four almond-shaped cups"),
        ("כַּפְתֹּרֶיהָ וּפְרָחֶיהָ", "ותפאפיחהא וסואסנהא",
         "with their apples and their lilies."),
    ],
    35: [
        ("וְכַפְתֹּר תַּחַת שְׁנֵי הַקָּנִים מִמֶּנָּה וְכַפְתֹּר תַּחַת שְׁנֵי הַקָּנִים מִמֶּנָּה וְכַפְתֹּר תַּחַת-שְׁנֵי הַקָּנִים מִמֶּנָּה",
         "ותפאחה תחת כל קצבתין מנהא",
         "And an apple beneath each two branches from it"),
        ("לְשֵׁשֶׁת הַקָּנִים הַיֹּצְאִים מִן-הַמְּנֹרָה",
         "כד'אך לאלסת אלקצבאת. אלכ'ארגאת מנהא",
         "so for the six branches going out from it."),
    ],
    36: [
        ("כַּפְתֹּרֵיהֶם וּקְנֹתָם מִמֶּנָּה יִהְיוּ", "ותפאפיחהא וקצבהא מנהא יכונו",
         "Their apples and their shaft shall be of it"),
        ("כֻּלָּהּ מִקְשָׁה אַחַת זָהָב טָהוֹר",
         "כלהא מצמתה ואחדה מן ד'הב כ'אלץ",
         "all of it one solid piece of pure gold."),
    ],
    37: [
        ("וְעָשִׂיתָ אֶת-נֵרֹתֶיהָ שִׁבְעָה", "ואצנע להא סבע סרג",
         "And make for it seven lamps"),
        ("וְהֶעֱלָה אֶת-נֵרֹתֶיהָ וְהֵאִיר עַל-עֵבֶר פָּנֶיהָ",
         "פאד'י תסרג סרגהא. תצ'י אלי' גהה' וגההא",
         "and when its lamps are lit, they shall give light toward the direction of its face."),
    ],
    38: [
        ("וּמַלְקָחֶיהָ וּמַחְתֹּתֶיהָ זָהָב טָהוֹר",
         "וכלבאתהא ומגאמרהא מן ד'הב כ'אלץ",
         "And its tongs and its fire-pans of pure gold."),
    ],
    39: [
        ("כִּכָּר זָהָב טָהוֹר יַעֲשֶׂה אֹתָהּ", "מן בדר'ה ד'הב כ'אלץ יצנעהא",
         "From a talent of pure gold shall he make it"),
        ("אֵת כָּל-הַכֵּלִים הָאֵלֶּה", "וגמיע הד'ה אלאניה",
         "and all these vessels."),
    ],
    46: [
        ("ּרְאֵה וַעֲשֵׂה בְּתַבְנִיתָם--אֲשֶׁר-אַתָּה מָרְאֶה בָּהָר",
         "ואנצ'ר ד'אלך ואצנע כשכלה. אלד'י אנת מורא פי אלגבל",
         "And look upon it and make it according to its form which you are shown on the mountain."),
    ],
}
