"""Hand-authored alignment triples for Shemot chapter 26."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאֶת-הַמִּשְׁכָּן תַּעֲשֶׂה עֶשֶׂר יְרִיעֹת",
         "ואצנע ד'את אלמסכן עשר שקאק",
         "And make the tabernacle itself of ten strips"),
        ("שֵׁשׁ מָשְׁזָר וּתְכֵלֶת וְאַרְגָּמָן וְתֹלַעַת שָׁנִי",
         "מן עשר משזור. ואסמאנגון וארגואן וצבג' קרמז",
         "of fine twisted linen — blue, purple, and scarlet dye"),
        ("כְּרֻבִים מַעֲשֵׂה חֹשֵׁב תַּעֲשֶׂה אֹתָם",
         "צורא. צנעה' חאד'ק תצנעהא",
         "with figures, the work of a skilled craftsman shall you make them."),
    ],
    2: [
        ("אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁמֹנֶה וְעֶשְׂרִים בָּאַמָּה",
         "טול כל שקה. ת'מאניה ועשרין ד'ראע",
         "The length of each strip: twenty-eight cubits"),
        ("וְרֹחַב אַרְבַּע בָּאַמָּה הַיְרִיעָה הָאֶחָת",
         "וערצ'הא ארבעה' אד'רע",
         "and its width: four cubits"),
        ("מִדָּה אַחַת לְכָל-הַיְרִיעֹת", "מסאחה ואחדה לגמיע אלשקאק",
         "one measure for all the strips."),
    ],
    3: [
        ("חֲמֵשׁ הַיְרִיעֹת תִּהְיֶיןָ חֹבְרֹת אִשָּׁה אֶל-אֲחֹתָהּ",
         "כ'מס שקאק תכון מכ'ייטה. אלואחדה מע אלאכ'רי'",
         "Five strips shall be sewn, one to the other"),
        ("וְחָמֵשׁ יְרִיעֹת חֹבְרֹת אִשָּׁה אֶל-אֲחֹתָהּ",
         "וכ'מס שקאק מכייטה. ואחדה מע אלאכ'רי'",
         "and five strips sewn, one to the other."),
    ],
    4: [
        ("וְעָשִׂיתָ לֻלְאֹת תְּכֵלֶת עַל שְׂפַת הַיְרִיעָה הָאֶחָת",
         "ואצנע ע'רי' מן אסמאנגון. פי חאשיה' אלשקה אלואחדה",
         "And make loops of blue along the edge of the one strip"),
        ("מִקָּצָה בַּחֹבָרֶת", "אלטרפא אלמתאלפה",
         "at the joining end"),
        ("וְכֵן תַּעֲשֶׂה בִּשְׂפַת הַיְרִיעָה הַקִּיצוֹנָה בַּמַּחְבֶּרֶת הַשֵּׁנִית",
         "וכד'אך אצנע פי חאשיה' אלשקה אלמתאלפה אלת'אניה",
         "and likewise make along the edge of the second joined strip."),
    ],
    5: [
        ("חֲמִשִּׁים לֻלָאֹת תַּעֲשֶׂה בַּיְרִיעָה הָאֶחָת",
         "כ'מסין ערוה. תצנע פי אלשקה אלואחדה",
         "Fifty loops shall you make on the one strip"),
        ("וַחֲמִשִּׁים לֻלָאֹת תַּעֲשֶׂה בִּקְצֵה הַיְרִיעָה אֲשֶׁר בַּמַּחְבֶּרֶת הַשֵּׁנִית",
         "וכ'מסין ערוה. תצנע פי טרף אלשקה. אלמתאלפה אלת'אניה",
         "and fifty loops shall you make on the edge of the second joined strip"),
        ("מַקְבִּילֹת הַלֻּלָאֹת אִשָּׁה אֶל-אֲחֹתָהּ",
         "ותכון אלערי' מתקאבלה. ואחדה מע אלאכ'רי'",
         "and the loops shall face one another, one opposite the other."),
    ],
    6: [
        ("וְעָשִׂיתָ חֲמִשִּׁים קַרְסֵי זָהָב", "ואצנע כ'מסין שצ'אץ' מן ד'הב",
         "And make fifty clasps of gold"),
        ("וְחִבַּרְתָּ אֶת-הַיְרִיעֹת אִשָּׁה אֶל-אֲחֹתָהּ בַּקְּרָסִים",
         "ולוף אלשקאק. ואחדה מע אלאכ'רי' באלשצ'אץ'",
         "and join the strips one to the other with the clasp"),
        ("וְהָיָה הַמִּשְׁכָּן אֶחָד", "ויציר אלמסכן ואחד",
         "and the tabernacle itself shall become one."),
    ],
    7: [
        ("וְעָשִׂיתָ יְרִיעֹת עִזִּים לְאֹהֶל עַל-הַמִּשְׁכָּן",
         "ואצנע שקאק מן מרעזא. כ'באא עלי' אלמסכן",
         "And make strips of fine wool as a tent over the tabernacle"),
        ("עַשְׁתֵּי-עֶשְׂרֵה יְרִיעֹת תַּעֲשֶׂה אֹתָם",
         "אחדי' עשר שקה תצנעהא",
         "eleven strips shall you make them."),
    ],
    8: [
        ("אֹרֶךְ הַיְרִיעָה הָאַחַת שְׁלֹשִׁים בָּאַמָּה",
         "טול כל שקה ת'לאת'ין ד'ראע",
         "The length of each strip: thirty cubits"),
        ("וְרֹחַב אַרְבַּע בָּאַמָּה הַיְרִיעָה הָאֶחָת",
         "וערצ'הא ארבעה' אד'רע",
         "and its width: four cubits"),
        ("מִדָּה אַחַת לְעַשְׁתֵּי עֶשְׂרֵה יְרִיעֹת",
         "מסאחה ואחדה. לאחדי' עשר אלשקה",
         "one measure for the eleven strips."),
    ],
    9: [
        ("וְחִבַּרְתָּ אֶת-חֲמֵשׁ הַיְרִיעֹת לְבָד",
         "וכ'ייט אלכ'מס אלשקאק עלי' חדה",
         "And sew the five strips together as one"),
        ("וְאֶת-שֵׁשׁ הַיְרִיעֹת לְבָד", "ואלסת אלשקאק עלי' חדה",
         "and the six strips together as one"),
        ("וְכָפַלְתָּ אֶת-הַיְרִיעָה הַשִּׁשִּׁית אֶל-מוּל פְּנֵי הָאֹהֶל",
         "ואת'ני אלשקה אלסאדסה. אלי' מא ילי וגה אלכ'בא",
         "and fold the sixth strip double, facing the front of the tent."),
    ],
    10: [
        ("וְעָשִׂיתָ חֲמִשִּׁים לֻלָאֹת עַל שְׂפַת הַיְרִיעָה הָאֶחָת הַקִּיצֹנָה בַּחֹבָרֶת",
         "ואצנע כ'מסין ערוה. פי חאשיה' אלשקה. אלטרפא אלמתאלפה",
         "And make fifty loops on the edge of the one strip at the joining end"),
        ("וַחֲמִשִּׁים לֻלָאֹת עַל שְׂפַת הַיְרִיעָה הַחֹבֶרֶת הַשֵּׁנִית",
         "וכ'מסין ערוה פי חאשיה' אלשקה. אלמתאלפה אלת'אניה",
         "and fifty loops on the edge of the second joined strip."),
    ],
    11: [
        ("וְעָשִׂיתָ קַרְסֵי נְחֹשֶׁת חֲמִשִּׁים", "ואצנע כ'מסין שצ'אץ' מן נחאס",
         "And make fifty clasps of copper"),
        ("וְהֵבֵאתָ אֶת-הַקְּרָסִים בַּלֻּלָאֹת", "ואדכ'ל אלשצ'אץ' פי אלערי",
         "and insert the clasps into the loops"),
        ("וְחִבַּרְתָּ אֶת-הָאֹהֶל וְהָיָה אֶחָד", "וולף. אלכ'בא ויציר ואחדה",
         "and join the tent together — and it shall become one."),
    ],
    12: [
        ("וְסֶרַח הָעֹדֵף בִּירִיעֹת הָאֹהֶל",
         "ואסבל אלפאצ'ל. מן שקאק אלכ'בא",
         "And let the surplus hang down from the strips of the tent"),
        ("חֲצִי הַיְרִיעָה הָעֹדֶפֶת תִּסְרַח עַל אֲחֹרֵי הַמִּשְׁכָּן",
         "והו נ'צף אלשקה אלפאצ'לה תסבלהא אלי' מוכר אלמסכן",
         "the half of the surplus strip you shall let hang down at the rear of the tabernacle."),
    ],
    13: [
        ("וְהָאַמָּה מִזֶּה וְהָאַמָּה מִזֶּה בָּעֹדֵף בְּאֹרֶךְ יְרִיעֹת הָאֹהֶל",
         "וד'ראע מן ההנא. וד'ראע מן ההנא אלפאצ'ל. מן טול אלשקאק",
         "And a cubit from here and a cubit from here of the surplus in the length of the strips"),
        ("יִהְיֶה סָרוּחַ עַל-צִדֵּי הַמִּשְׁכָּן מִזֶּה וּמִזֶּה--לְכַסֹּתוֹ",
         "יכון מסבלא עלי' גאנבי אלמסכן. מן ימנה ויסרה ליג'טיה",
         "shall be spread down over the sides of the tabernacle, from right and left, to cover it."),
    ],
    14: [
        ("וְעָשִׂיתָ מִכְסֶה לָאֹהֶל עֹרֹת אֵילִם מְאָדָּמִים",
         "ואצנע גטאא לאלמסכן. גלוד כבאש אדים",
         "And make a covering for the tabernacle: hides of rams, tanned"),
        ("וּמִכְסֵה עֹרֹת תְּחָשִׁים מִלְמָעְלָה",
         "וגטאא. מן גלוד דארש מן פוק",
         "and a covering of hides of tahash above."),
    ],
    15: [
        ("וְעָשִׂיתָ אֶת-הַקְּרָשִׁים לַמִּשְׁכָּן עֲצֵי שִׁטִּים עֹמְדִים",
         "ואצנע אלתכ'אתג לאלמסכן. מן כ'שב אלסנט קאימא",
         "And make the planks for the tabernacle of acacia wood, standing upright."),
    ],
    16: [
        ("עֶשֶׂר אַמּוֹת אֹרֶךְ הַקָּרֶשׁ", "טול כל תכ'תגה עשרה' אד'רע",
         "The length of each plank: ten cubits"),
        ("וְאַמָּה וַחֲצִי הָאַמָּה רֹחַב הַקֶּרֶשׁ הָאֶחָד",
         "וד'ראע ונצף ערצ'הא",
         "and a cubit and a half its width."),
    ],
    17: [
        ("שְׁתֵּי יָדוֹת לַקֶּרֶשׁ הָאֶחָד--מְשֻׁלָּבֹת אִשָּׁה אֶל-אֲחֹתָהּ",
         "ולהא ציראן מלסנאן. אחדהמא באיזא אלאכ'ר",
         "And it shall have two tenons like two tongues, one opposite the other"),
        ("כֵּן תַּעֲשֶׂה לְכֹל קַרְשֵׁי הַמִּשְׁכָּן",
         "כד'אך תצנע. בגמיע תכ'אתג אלמסכן",
         "so shall you make for all the planks of the tabernacle."),
    ],
    18: [
        ("וְעָשִׂיתָ אֶת-הַקְּרָשִׁים לַמִּשְׁכָּן עֶשְׂרִים קֶרֶשׁ",
         "ואצנע תכ'אתג אלמסכן. עשרין תכ'תגה",
         "And make the planks of the tabernacle: twenty planks"),
        ("לִפְאַת נֶגְבָּה תֵימָנָה", "מן גהה' מהב אלגנוב",
         "on the side facing the south wind."),
    ],
    19: [
        ("וְאַרְבָּעִים אַדְנֵי-כֶסֶף תַּעֲשֶׂה תַּחַת עֶשְׂרִים הַקָּרֶשׁ",
         "וארבעין קאעדה מן פצ'ה. תצנעהא תחת עשרין אלתכ'תגה",
         "And forty bases of silver shall you make beneath the twenty planks"),
        ("שְׁנֵי אֲדָנִים תַּחַת-הַקֶּרֶשׁ הָאֶחָד לִשְׁתֵּי יְדֹתָיו",
         "קאעדתין תחת כל תכ'תגה לציראהא",
         "two bases beneath each plank, for its two tenons."),
    ],
    20: [
        ("וּלְצֶלַע הַמִּשְׁכָּן הַשֵּׁנִית לִפְאַת צָפוֹן עֶשְׂרִים קָרֶשׁ",
         "ולגאנב אלמסכן אלת'אני. מן גהה' מהב אלשמאל. עשרין תכ'תגה",
         "And for the second side of the tabernacle, facing the north wind — twenty planks."),
    ],
    21: [
        ("וְאַרְבָּעִים אַדְנֵיהֶם כָּסֶף", "ולהא ארבעין קאעדה מן פצ'ה",
         "And their forty bases of silver"),
        ("שְׁנֵי אֲדָנִים תַּחַת הַקֶּרֶשׁ הָאֶחָד", "קאעדתאן תחת כל תכ'תגה",
         "two bases beneath each plank."),
    ],
    22: [
        ("וּלְיַרְכְּתֵי הַמִּשְׁכָּן יָמָּה תַּעֲשֶׂה שִׁשָּׁה קְרָשִׁים",
         "ופי מוכ'ר אלמסכן ג'רבא. תצנע סת תכ'אתג",
         "And at the rear of the tabernacle, to the west, you shall make six planks."),
    ],
    23: [
        ("וּשְׁנֵי קְרָשִׁים תַּעֲשֶׂה לִמְקֻצְעֹת הַמִּשְׁכָּן--בַּיַּרְכָתָיִם",
         "ותכ'תגתאן תצנע. פי רכני אלמסכן. פי אלזאויתין",
         "And two planks shall you make for the corners of the tabernacle, at the two angles."),
    ],
    24: [
        ("וְיִהְיוּ תֹאֲמִם מִלְּמַטָּה", "ותכון מעתדלה מן אספל",
         "And they shall be even from below"),
        ("וְיַחְדָּו יִהְיוּ תַמִּים עַל-רֹאשׁוֹ אֶל-הַטַּבַּעַת הָאֶחָת",
         "וגמיעא תכון מעתדלה מן פוק. בחלקה ואחדה",
         "and all together shall they be even from above, with a single ring"),
        ("כֵּן יִהְיֶה לִשְׁנֵיהֶם לִשְׁנֵי הַמִּקְצֹעֹת יִהְיוּ",
         "כד'אך יכון לאלרכנין כליהמא",
         "so shall it be for both corners alike."),
    ],
    25: [
        ("וְהָיוּ שְׁמֹנָה קְרָשִׁים וְאַדְנֵיהֶם כֶּסֶף שִׁשָּׁה עָשָׂר אֲדָנִים",
         "פתציר ת'מאן תכ'אתג. וקואעדהא מן פצ'ה. סת' עשר קאעדה",
         "And there shall be eight planks, with their bases of silver: sixteen bases"),
        ("שְׁנֵי אֲדָנִים תַּחַת הַקֶּרֶשׁ הָאֶחָד",
         "קאעדתאן תחת כל תכ'תגה",
         "two bases beneath each plank."),
    ],
    26: [
        ("וְעָשִׂיתָ בְרִיחִם עֲצֵי שִׁטִּים חֲמִשָּׁה לְקַרְשֵׁי צֶלַע-הַמִּשְׁכָּן הָאֶחָד",
         "ואצנע אמהאג מן כ'שב אלסנט. כ'מסה. לתכ'אתג גאנב אלמסכן אלואחד",
         "And make bars of acacia wood — five for the planks of the one side of the tabernacle,"),
    ],
    27: [
        ("וַחֲמִשָּׁה בְרִיחִם לְקַרְשֵׁי צֶלַע-הַמִּשְׁכָּן הַשֵּׁנִית",
         "וכ'מסה' אמהאג. לתכ'אתג גאנב אלמסכן אלת'אני",
         "and five bars for the planks of the second side of the tabernacle"),
        ("וַחֲמִשָּׁה בְרִיחִם לְקַרְשֵׁי צֶלַע הַמִּשְׁכָּן לַיַּרְכָתַיִם יָמָּה",
         "וכ'מסה' אמהאג לתכ'אתג גאנב אלמסכן. לאלזאויתין פי אלג'רב",
         "and five bars for the planks of the side of the tabernacle at the two corners to the west."),
    ],
    28: [
        ("וְהַבְּרִיחַ הַתִּיכֹן בְּתוֹךְ הַקְּרָשִׁים", "ואלמהג אלאוסט פי גוף אלתכ'אתג",
         "And the middle bar, within the planks"),
        ("מַבְרִחַ מִן-הַקָּצֶה אֶל-הַקָּצֶה", "נאפד'. מן אלטרף אלי' אלטרף",
         "shall pass through from end to end."),
    ],
    29: [
        ("וְאֶת-הַקְּרָשִׁים תְּצַפֶּה זָהָב", "וגש אלתכ'אתג בד'הב",
         "And overlay the planks with gold"),
        ("וְאֶת-טַבְּעֹתֵיהֶם תַּעֲשֶׂה זָהָב--בָּתִּים לַבְּרִיחִם",
         "ואצנע חלקהא מן ד'הב. מכאנא לאלאמהאג",
         "and make their rings of gold as the place for the bars"),
        ("וְצִפִּיתָ אֶת-הַבְּרִיחִם זָהָב", "וגש אלאמהאג איצ'א בד'הב",
         "and overlay the bars also with gold."),
    ],
    30: [
        ("וַהֲקֵמֹתָ אֶת-הַמִּשְׁכָּן כְּמִשְׁפָּטוֹ--אֲשֶׁר הָרְאֵיתָ בָּהָר",
         "ואנצ'ב אלמסכן. כהיאתה אלתי אורית בהא פי אלגבל",
         "And erect the tabernacle according to its form as you were shown on the mountain."),
    ],
    31: [
        ("וְעָשִׂיתָ פָרֹכֶת תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי",
         "ואצנע סגפא. מן אסמאנגון וארגואן. וצבג' קרמז",
         "And make a veil of blue and purple and scarlet dye"),
        ("וְשֵׁשׁ מָשְׁזָר מַעֲשֵׂה חֹשֵׁב יַעֲשֶׂה אֹתָהּ כְּרֻבִים",
         "ועשר משזור. צנעה' חאד'ק. יצנעה צורא",
         "and fine twisted linen — the work of a skilled craftsman — he shall make it with figures."),
    ],
    32: [
        ("וְנָתַתָּה אֹתָהּ עַל-אַרְבָּעָה עַמּוּדֵי שִׁטִּים מְצֻפִּים זָהָב",
         "ועלקה. עלי' ארבעה' עמד מן סנט. מג'שאה ד'הב",
         "And hang it upon four pillars of acacia overlaid with gold"),
        ("וָוֵיהֶם זָהָב--עַל-אַרְבָּעָה אַדְנֵי-כָסֶף",
         "וזראפינהא ד'הב. עלי' ארבעה' קואעד מן פצ'ה",
         "with their hooks of gold, upon four bases of silver."),
    ],
    33: [
        ("וְנָתַתָּה אֶת-הַפָּרֹכֶת תַּחַת הַקְּרָסִים",
         "ועלק אלסגף תחת אלשצ'ץ'",
         "And hang the veil beneath the clasps"),
        ("וְהֵבֵאתָ שָׁמָּה מִבֵּית לַפָּרֹכֶת אֵת אֲרוֹן הָעֵדוּת",
         "ואדכ'ל הנאך מן דאכ'ל אלסגף. צנדוק אלשהאדה",
         "and bring there, within the veil, the ark of the testimony"),
        ("וְהִבְדִּילָה הַפָּרֹכֶת לָכֶם בֵּין הַקֹּדֶשׁ וּבֵין קֹדֶשׁ הַקֳּדָשִׁים",
         "ויפצל אלסגף לכם. בין אלקדס. ובין כ'אץ אלאקדאס",
         "and the veil shall separate for you between the sanctuary and the innermost of the sanctuaries."),
    ],
    34: [
        ("וְנָתַתָּ אֶת-הַכַּפֹּרֶת עַל אֲרוֹן הָעֵדֻת--בְּקֹדֶשׁ הַקֳּדָשִׁים",
         "ואגעל אלג'שא. עלי' צנדוק אלשהאדה. פי כ'אץ אלאקדאס",
         "And place the cover upon the ark of the testimony, in the innermost of the sanctuaries."),
    ],
    35: [
        ("וְשַׂמְתָּ אֶת-הַשֻּׁלְחָן מִחוּץ לַפָּרֹכֶת", "ואגעל אלמאידה כ'ארג אלסגף",
         "And place the table outside the veil"),
        ("וְאֶת-הַמְּנֹרָה נֹכַח הַשֻּׁלְחָן עַל צֶלַע הַמִּשְׁכָּן תֵּימָנָה",
         "ואלמנארה בחיאלהא. אלי' גאנב אלמסכן אלג'נובי",
         "and the lampstand opposite it, on the southern side of the tabernacle"),
        ("וְהַשֻּׁלְחָן--תִּתֵּן עַל-צֶלַע צָפוֹן",
         "ואלמאידה. אגעלהא אלי' גאנב אלשמאל",
         "and the table — place it on the northern side."),
    ],
    36: [
        ("וְעָשִׂיתָ מָסָךְ לְפֶתַח הָאֹהֶל",
         "ואצנע סתרא לבאב אלכ'בא",
         "And make a curtain for the entrance of the tent"),
        ("תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר מַעֲשֵׂה רֹקֵם",
         "מן אסמאנגון וארגואן. וצבג' קרמז ועשר משזור. צנעה' ראקם",
         "of blue and purple and scarlet dye and fine twisted linen — the work of an embroiderer."),
    ],
    37: [
        ("וְעָשִׂיתָ לַמָּסָךְ חֲמִשָּׁה עַמּוּדֵי שִׁטִּים",
         "ואצנע לאלסתר. כ'מסה' עמד מן סנט",
         "And make for the curtain five pillars of acacia"),
        ("וְצִפִּיתָ אֹתָם זָהָב וָוֵיהֶם זָהָב",
         "וג'שהא בד'הב. וזראפינהא ד'הב",
         "and overlay them with gold; and their hooks of gold"),
        ("וְיָצַקְתָּ לָהֶם חֲמִשָּׁה אַדְנֵי נְחֹשֶׁת",
         "וצ'ג' להא. כ'מסה' קואעד מן נחאס",
         "and cast for them five bases of copper."),
    ],
}
