"""Hand-authored alignment triples for Shemot chapter 38."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיַּעַשׂ אֶת-מִזְבַּח הָעֹלָה עֲצֵי שִׁטִּים",
         "וצנע מד'בח אלצעידה מן כ'שב אלסנט",
         "And he made the altar of burnt-offering from acacia wood"),
        ("חָמֵשׁ אַמּוֹת אָרְכּוֹ וְחָמֵשׁ-אַמּוֹת רָחְבּוֹ רָבוּעַ",
         "כמסה אד'רע טולה. וכמסה אד'רע ערצ'ה מרבעא",
         "five cubits its length, and five cubits its width, square"),
        ("וְשָׁלֹשׁ אַמּוֹת קֹמָתוֹ", "ות'לאת'ה אד'רע סמכה",
         "and three cubits its height"),
    ],
    2: [
        ("וַיַּעַשׂ קַרְנֹתָיו עַל אַרְבַּע פִּנֹּתָיו",
         "וצנע ארכאנה. פי ארבע גהאתה",
         "And he made its horns upon its four sides"),
        ("מִמֶּנּוּ הָיוּ קַרְנֹתָיו", "וכנאת ארכאנה מנה",
         "its horns were from it"),
        ("וַיְצַף אֹתוֹ נְחֹשֶׁת", "וג'שאה בנחאס",
         "and he overlaid it with copper"),
    ],
    3: [
        ("וַיַּעַשׂ אֶת-כָּל-כְּלֵי הַמִּזְבֵּחַ",
         "וצנע גמיע אניתה",
         "And he made all its vessels"),
        ("אֶת-הַסִּירֹת וְאֶת-הַיָּעִים וְאֶת-הַמִּזְרָקֹת",
         "אלצנאן ואלמג'ארף ואלכ'ראנב",
         "the pots, and the shovels, and the basins"),
        ("אֶת-הַמִּזְלָגֹת וְאֶת-הַמַּחְתֹּת",
         "ואלמנאשל ואלמגאמר",
         "and the forks, and the fire-pans"),
        ("כָּל-כֵּלָיו עָשָׂה נְחֹשֶׁת",
         "גמיע ד'אלך צנע מן נחאס",
         "all of these he made of copper"),
    ],
    4: [
        ("וַיַּעַשׂ לַמִּזְבֵּחַ מִכְבָּר מַעֲשֵׂה רֶשֶׁת נְחֹשֶׁת",
         "וצנע לה סרדא. עלי' צנעה' אלשבכה מן נחאס",
         "And he made for it a grating, fashioned after the manner of netting, of copper"),
        ("תַּחַת כַּרְכֻּבּוֹ מִלְּמַטָּה עַד-חֶצְיוֹ",
         "דון שרגעה. מן אספל אלי'' נצפה",
         "below its ledge, from the bottom up to its midpoint"),
    ],
    5: [
        ("וַיִּצֹק אַרְבַּע טַבָּעֹת בְּאַרְבַּע הַקְּצָו‍ֹת--לְמִכְבַּר הַנְּחֹשֶׁת",
         "וצאג' ארבע חלק. פי ארבע אלאטראף לסרד אלנחאס",
         "And he cast four rings upon the four sides of the copper grating"),
        ("בָּתִּים לַבַּדִּים", "מכאנא לאלדהוק",
         "as a place for the poles"),
    ],
    6: [
        ("וַיַּעַשׂ אֶת-הַבַּדִּים עֲצֵי שִׁטִּים",
         "וצנע אלדהוק מן כ'שב אלסנט",
         "And he made the poles of acacia wood"),
        ("וַיְצַף אֹתָם נְחֹשֶׁת", "וג'שאה בנחאס",
         "and overlaid them with copper"),
    ],
    7: [
        ("וַיָּבֵא אֶת-הַבַּדִּים בַּטַּבָּעֹת עַל צַלְעֹת הַמִּזְבֵּחַ לָשֵׂאת אֹתוֹ בָּהֶם",
         "ואדכ'ל אלדהוק פי אלחלק. אלי' גאנבי אלמד'בח. ליחמל בהא",
         "And he inserted the poles into the rings upon the two sides of the altar, to carry it by them"),
        ("נְבוּב לֻחֹת עָשָׂה אֹתוֹ", "אלואחא מגוופא צנעהא",
         "hollow planks he made it"),
    ],
    8: [
        ("וַיַּעַשׂ אֵת הַכִּיּוֹר נְחֹשֶׁת וְאֵת כַּנּוֹ נְחֹשֶׁת",
         "וצנע אלחוץ'. ומקעדה מן נחאס",
         "And he made the laver and its base of copper"),
        ("בְּמַרְאֹת הַצֹּבְאֹת אֲשֶׁר צָבְאוּ פֶּתַח אֹהֶל מוֹעֵד",
         "מן מראיא' אלנסא. אלמתגיישאת ענד באב כ'בא אלמחצ'ר",
         "from the mirrors of the women who assembled at the entrance of the tent of the assembly"),
    ],
    9: [
        ("וַיַּעַשׂ אֶת-הֶחָצֵר לִפְאַת נֶגֶב תֵּימָנָה",
         "וצנע אלצראדק מן גהה' מהב אלגנוב",
         "And he made the enclosure on the side toward the direction of the south wind"),
        ("קַלְעֵי הֶחָצֵר שֵׁשׁ מָשְׁזָר מֵאָה בָּאַמָּה",
         "קלוע אלצראדק מן עשר משזור. מאיה' ד'ראע",
         "the curtains of the enclosure of fine twisted linen, one hundred cubits"),
    ],
    10: [
        ("עַמּוּדֵיהֶם עֶשְׂרִים וְאַדְנֵיהֶם עֶשְׂרִים נְחֹשֶׁת",
         "עמדהא עשרין. וקואעדהא עשרין מן נחאס",
         "Its pillars were twenty, and their bases twenty of copper"),
        ("וָוֵי הָעַמּוּדִים וַחֲשֻׁקֵיהֶם כָּסֶף",
         "וזראפין אלעמד וטלאהא פצ'ה",
         "and the clasps of the pillars and their overlay were silver"),
    ],
    11: [
        ("וְלִפְאַת צָפוֹן מֵאָה בָאַמָּה",
         "ומן גהה' אלשמאל מאיה' ד'ראע",
         "And on the side of the north, one hundred cubits"),
        ("עַמּוּדֵיהֶם עֶשְׂרִים וְאַדְנֵיהֶם עֶשְׂרִים נְחֹשֶׁת",
         "עמדהא עשרין. וקואעדהא עשרין מן נחאס",
         "its pillars were twenty, and their bases twenty of copper"),
        ("וָוֵי הָעַמּוּדִים וַחֲשֻׁקֵיהֶם כָּסֶף",
         "וזראפין אלעמד וטלאהא פצ'ה",
         "and the clasps of the pillars and their overlay were silver"),
    ],
    12: [
        ("וְלִפְאַת-יָם קְלָעִים חֲמִשִּׁים בָּאַמָּה",
         "ומן גהה' מהב אלג'רב. קלוע טולהא כ'מסין ד'ראע",
         "And on the side toward the direction of the west wind, curtains of fifty cubits in length"),
        ("עַמּוּדֵיהֶם עֲשָׂרָה וְאַדְנֵיהֶם עֲשָׂרָה",
         "עמדהא עשרה. וקואעדהא עשרה",
         "their pillars were ten, and their bases ten"),
        ("וָוֵי הָעַמֻּדִים וַחֲשׁוּקֵיהֶם כָּסֶף",
         "וזראפין אלעמד וטלאהא פצ'ה",
         "and the clasps of the pillars and their overlay were silver"),
    ],
    13: [
        ("וְלִפְאַת קֵדְמָה מִזְרָחָה חֲמִשִּׁים אַמָּה",
         "ומן גהה' אלשרק כ'מסין ד'ראע",
         "And on the side toward the direction of the east, fifty cubits"),
    ],
    14: [
        ("קְלָעִים חֲמֵשׁ-עֶשְׂרֵה אַמָּה אֶל-הַכָּתֵף",
         "מנהא קלוע. כמסה' עשר ד'ראעא לאלכם",
         "Of these, curtains of fifteen cubits for the one shoulder"),
        ("עַמּוּדֵיהֶם שְׁלֹשָׁה וְאַדְנֵיהֶם שְׁלֹשָׁה",
         "עמדהא ת'לאת'ה. וקואעדהא ת'לאת'ה",
         "their pillars were three, and their bases three"),
    ],
    15: [
        ("וְלַכָּתֵף הַשֵּׁנִית מִזֶּה וּמִזֶּה לְשַׁעַר הֶחָצֵר",
         "ולאלכם אלת'אני. ימנה ויסרה לבאב אלצראדק",
         "And for the second shoulder, right and left of the entrance of the enclosure"),
        ("קְלָעִים חֲמֵשׁ עֶשְׂרֵה אַמָּה",
         "קלוע טולהא כמסה' עשר ד'ראע",
         "curtains of fifteen cubits in length"),
        ("עַמֻּדֵיהֶם שְׁלֹשָׁה וְאַדְנֵיהֶם שְׁלֹשָׁה",
         "ועמדהא ת'לאת'ה. וקואעדהא ת'לאת'ה",
         "their pillars were three, and their bases three"),
    ],
    16: [
        ("כָּל-קַלְעֵי הֶחָצֵר סָבִיב שֵׁשׁ מָשְׁזָר",
         "גמיע קלוע אלצראדק. מסתדירא מן עשר משזור",
         "All the curtains of the enclosure, all around, were of fine twisted linen"),
    ],
    17: [
        ("וְהָאֲדָנִים לָעַמֻּדִים נְחֹשֶׁת",
         "וקואעד אלעמד מן נחאס",
         "And the bases of the pillars were of copper"),
        ("וָוֵי הָעַמּוּדִים וַחֲשׁוּקֵיהֶם כֶּסֶף",
         "וזראפין אלעמד וטלאהא פצ'ה",
         "and the clasps of the pillars and their overlay were silver"),
        ("וְצִפּוּי רָאשֵׁיהֶם כָּסֶף", "וג'שא רוסהא איצ'א",
         "and he overlaid their tops as well"),
        ("כֹּל עַמֻּדֵי הֶחָצֵר", "כמא אן גמיעהא מטלייה פצ'ה",
         "for all of them were overlaid with silver"),
    ],
    18: [
        ("וּמָסַךְ שַׁעַר הֶחָצֵר מַעֲשֵׂה רֹקֵם",
         "וסתר באב אלצראדק צנעה' ראקם",
         "And the screen of the entrance of the enclosure was the work of an embroiderer"),
        ("תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר",
         "מן אסמאנגון וארגואן. וצבג' קרמז ועשר משזור",
         "of blue and purple and scarlet dye and fine twisted linen"),
        ("וְעֶשְׂרִים אַמָּה אֹרֶךְ",
         "וטולה עשרין ד'ראע",
         "and its length was twenty cubits"),
        ("וְקוֹמָה בְרֹחַב חָמֵשׁ אַמּוֹת לְעֻמַּת קַלְעֵי הֶחָצֵר",
         "וסמכה אלד'י הו ערצ'ה כ'מסה אד'רע. באזא קלוע אלצראדק",
         "and its thickness — which is its width — five cubits, corresponding to the curtains of the enclosure"),
    ],
    19: [
        ("וְעַמֻּדֵיהֶם אַרְבָּעָה וְאַדְנֵיהֶם אַרְבָּעָה נְחֹשֶׁת",
         "ועמדהא ארבעה. וקואעדהא ארבעה מן נחאס",
         "And its pillars were four, and their bases four of copper"),
        ("וָוֵיהֶם כֶּסֶף", "וזראפינהא פצ'ה", "and their clasps were silver"),
        ("וְצִפּוּי רָאשֵׁיהֶם וַחֲשֻׁקֵיהֶם כָּסֶף",
         "וג'שא רוסהא. וטלאהא פצ'ה",
         "and he overlaid their tops and their overlay was silver"),
    ],
    20: [
        ("וְכָל-הַיְתֵדֹת לַמִּשְׁכָּן וְלֶחָצֵר סָבִיב--נְחֹשֶׁת",
         "וגמיע אותאד אלמסכן ואלצראדק. מסתדירא מן נחאס",
         "And all the pegs of the tabernacle and of the enclosure, all around, were of copper"),
    ],
    21: [
        ("אֵלֶּה פְקוּדֵי הַמִּשְׁכָּן מִשְׁכַּן הָעֵדֻת",
         "הד'א עדד מא דכ'ל פי אלמסכן מסכן אלשהאדה",
         "This is the count of what went into the tabernacle — the tabernacle of the testimony"),
        ("אֲשֶׁר פֻּקַּד עַל-פִּי מֹשֶׁה", "אלד'י עד באמר מוסי'",
         "which was reckoned by the command of Moses"),
        ("עֲבֹדַת הַלְוִיִּם בְּיַד אִיתָמָר בֶּן-אַהֲרֹן הַכֹּהֵן",
         "כ'דמה' אלליואניין. עלי' יד איתמר. אבן הרון אלאמאם",
         "as the service of the Levites, by the hand of Ithamar, son of Aaron the priest"),
    ],
    22: [
        ("וּבְצַלְאֵל בֶּן-אוּרִי בֶן-חוּר לְמַטֵּה יְהוּדָה",
         "אלד'י צנעה בצלאל. אבן אורי אבן חור מן סבט יהודה",
         "That which Bezalel, son of Uri, son of Hur, of the tribe of Judah, made"),
        ("עָשָׂה אֵת כָּל-אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "עלי' גמיע מא אמר אללה בה מוסי'",
         "according to all that God had commanded Moses"),
    ],
    23: [
        ("וְאִתּוֹ אָהֳלִיאָב בֶּן-אֲחִיסָמָךְ לְמַטֵּה-דָן",
         "ומעה אהליאב. אבן אחיסמך. מן סבט דן",
         "And with him Oholiab, son of Ahisamach, of the tribe of Dan"),
        ("חָרָשׁ וְחֹשֵׁב", "אסתאד' וחאד'ק", "a master and skilled craftsman"),
        ("וְרֹקֵם בַּתְּכֵלֶת וּבָאַרְגָּמָן וּבְתוֹלַעַת הַשָּׁנִי וּבַשֵּׁשׁ",
         "וראקם באלאסמנגון ואלארגואן. ואלצבג' אלקרמז ואלעשר",
         "and an embroiderer in blue and purple and scarlet dye and linen"),
    ],
    24: [
        ("כָּל-הַזָּהָב הֶעָשׂוּי לַמְּלָאכָה בְּכֹל מְלֶאכֶת הַקֹּדֶשׁ",
         "אמא אלד'הב. אלד'י עמל פי אלצנאעה. לגמיע צנאעה' אלקדס",
         "Now the gold that was used in the work, for all the work of the sanctuary"),
        ("וַיְהִי זְהַב הַתְּנוּפָה תֵּשַׁע וְעֶשְׂרִים כִּכָּר",
         "פכאן גמלה' ד'הב אלרפיעה תסעה ועשרין בדרה",
         "the total of the gold of the wave-offering was twenty-nine talents"),
        ("וּשְׁבַע מֵאוֹת וּשְׁלֹשִׁים שֶׁקֶל בְּשֶׁקֶל הַקֹּדֶשׁ",
         "וסבע מאיה ותלאת'ין. מת'קאל במת'קאל אלקדס",
         "and seven hundred and thirty shekels, by the shekel of the sanctuary"),
    ],
    25: [
        ("וְכֶסֶף פְּקוּדֵי הָעֵדָה מְאַת כִּכָּר",
         "ואמא אלפצ'ה. פכאן גמלה מא חצל מן מעדודי אלגמאעה מאיה' בדרה",
         "And the silver — the total of what was obtained from the counted ones of the congregation was one hundred talents"),
        ("וְאֶלֶף וּשְׁבַע מֵאוֹת וַחֲמִשָּׁה וְשִׁבְעִים שֶׁקֶל--בְּשֶׁקֶל הַקֹּדֶשׁ",
         "ואלף וסבע מאיה וכ'מסה וסבעין. מת'קאל במת'קאל אלקדס",
         "and one thousand seven hundred and seventy-five shekels, by the shekel of the sanctuary"),
    ],
    26: [
        ("בֶּקַע לַגֻּלְגֹּלֶת מַחֲצִית הַשֶּׁקֶל בְּשֶׁקֶל הַקֹּדֶשׁ",
         "מנשקה לכל גמגמה. נצף מת'קאל במת'קאל אלקדס",
         "A half-shekel for each head, half a shekel by the shekel of the sanctuary"),
        ("לְכֹל הָעֹבֵר עַל-הַפְּקֻדִים מִבֶּן עֶשְׂרִים שָׁנָה וָמַעְלָה",
         "לכל מן גאז עלי' אלעדד. מן אבן עשרין סנה פצאעדא",
         "for every one who passed through the counting, from twenty years of age and upward"),
        ("לְשֵׁשׁ-מֵאוֹת אֶלֶף וּשְׁלֹשֶׁת אֲלָפִים וַחֲמֵשׁ מֵאוֹת וַחֲמִשִּׁים",
         "לסת מאיה' אלף ות'לאת'ה' אלאף. וכ'מס מאיה וכ'מסין",
         "for six hundred thousand and three thousand and five hundred and fifty"),
    ],
    27: [
        ("וַיְהִי מְאַת כִּכַּר הַכֶּסֶף לָצֶקֶת אֵת אַדְנֵי הַקֹּדֶשׁ וְאֵת אַדְנֵי הַפָּרֹכֶת",
         "פכאן מן מאיה' בדרה' אלורק. מא צייג' כמנהא. קואעד אלקדס. וקואעד אלסגף",
         "And from the hundred talents of silver were cast the bases of the sanctuary and the bases of the veil"),
        ("מְאַת אֲדָנִים לִמְאַת הַכִּכָּר כִּכָּר לָאָדֶן",
         "וד'אלך מאיה' קאעדה. מן מאיה' בדרה. כל קאעדה מן בדרה",
         "one hundred bases from one hundred talents, one base from one talent"),
    ],
    28: [
        ("וְאֶת-הָאֶלֶף וּשְׁבַע הַמֵּאוֹת וַחֲמִשָּׁה וְשִׁבְעִים",
         "ואלאלף ואלסבע אלמאיה ואלכ'מסה ואלסבעין אלמת'קאל",
         "And the one thousand seven hundred and seventy-five shekels"),
        ("עָשָׂה וָוִים לָעַמּוּדִים", "צנע מנהא זראפין לאלעמד",
         "from them he made clasps for the pillars"),
        ("וְצִפָּה רָאשֵׁיהֶם וְחִשַּׁק אֹתָם",
         "וג'שא רוסהא וטלאהא",
         "and overlaid their tops and overlaid them"),
    ],
    29: [
        ("וּנְחֹשֶׁת הַתְּנוּפָה שִׁבְעִים כִּכָּר",
         "ואמא נחאס אלעזל פבלג' סבעין קנטאר",
         "And the copper of the wave-offering amounted to seventy talents"),
        ("וְאַלְפַּיִם וְאַרְבַּע-מֵאוֹת שָׁקֶל",
         "ואלפין וארבע מאיה' מת'קאל",
         "and two thousand and four hundred shekels"),
    ],
    30: [
        ("וַיַּעַשׂ בָּהּ אֶת-אַדְנֵי פֶּתַח אֹהֶל מוֹעֵד",
         "פצנע מנה. קואעד באב כ'בא אלמחצ'ר",
         "And from it he made the bases of the entrance of the tent of the assembly"),
        ("וְאֵת מִזְבַּח הַנְּחֹשֶׁת וְאֶת-מִכְבַּר הַנְּחֹשֶׁת אֲשֶׁר-לוֹ",
         "ומד'בח אלנחאס. ואלסרד אלנחאס אלד'י לה",
         "and the copper altar, and the copper grating that belongs to it"),
        ("וְאֵת כָּל-כְּלֵי הַמִּזְבֵּחַ", "וגמיע אניתה",
         "and all the vessels of the altar"),
    ],
    31: [
        ("וְאֶת-אַדְנֵי הֶחָצֵר סָבִיב וְאֶת-אַדְנֵי שַׁעַר הֶחָצֵר",
         "וקואעד אלצראדק מסתדירא וקואעד באבה",
         "And the bases of the enclosure all around, and the bases of its entrance"),
        ("וְאֵת כָּל-יִתְדֹת הַמִּשְׁכָּן", "וגמיע אותאד אלמסכן",
         "and all the pegs of the tabernacle"),
        ("וְאֶת-כָּל-יִתְדֹת הֶחָצֵר סָבִיב",
         "וגמיע אותאד אלצראדק מסתדירא",
         "and all the pegs of the enclosure all around"),
    ],
}
