"""Hand-authored alignment triples for Shemot chapter 4."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיַּעַן מֹשֶׁה", "פאגאב מוסי", "And Moses replied"),
        ("וַיֹּאמֶר", "וקאל", "and said"),
        ("וְהֵן לֹא-יַאֲמִינוּ לִי", "לעלהם לא יומנון בי",
         "Perhaps they will not believe me"),
        ("וְלֹא יִשְׁמְעוּ בְּקֹלִי", "ולא יקבלון מני",
         "and will not accept from me"),
        ("כִּי יֹאמְרוּ", "בל יקולו", "rather they will say"),
        ("לֹא-נִרְאָה אֵלֶיךָ יְהוָה", "לם תגלא לך אללה",
         "God did not appear to you"),
    ],
    2: [
        ("וַיֹּאמֶר אֵלָיו יְהוָה", "פקאל לה אללה",
         "And God said to him"),
        (None, "מנבהא", "prompting him"),
        ("מַה-זֶּה", "מא ד'א", "What is this"),
        ("בְיָדֶךָ", "בידך", "in your hand"),
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("מַטֶּה", "עצא", "A staff"),
    ],
    3: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("הַשְׁלִיכֵהוּ אַרְצָה", "אטרחהא עלי' אלארץ'",
         "Throw it upon the ground"),
        ("וַיַּשְׁלִכֵהוּ אַרְצָה", "פטרחהא", "And he threw it"),
        ("וַיְהִי לְנָחָשׁ", "וצארת ת'עבאנא", "and it became a serpent"),
        ("וַיָּנָס מֹשֶׁה", "פהרב מוסי'", "and Moses fled"),
        ("מִפָּנָיו", "מן בין ידיה", "from before it"),
    ],
    4: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "קאל אללה לה", "God said to him"),
        ("שְׁלַח יָדְךָ", "מד ידך", "Stretch out your hand"),
        ("וֶאֱחֹז בִּזְנָבוֹ", "ואמסך ד'נבה", "and seize its tail"),
        ("וַיִּשְׁלַח יָדוֹ", "פמד ידה", "And he stretched out his hand"),
        ("וַיַּחֲזֶק בּוֹ", "ואמסכה", "and seized it"),
        ("וַיְהִי לְמַטֶּה", "פצאר עצאא", "and it became a staff"),
        ("בְּכַפּוֹ", "פי ידה", "in his hand"),
    ],
    5: [
        ("לְמַעַן יַאֲמִינוּ", "לכי יומנון", "So that they may believe"),
        ("כִּי-נִרְאָה אֵלֶיךָ יְהוָה אֱלֹהֵי אֲבֹתָם אֱלֹהֵי אַבְרָהָם אֱלֹהֵי יִצְחָק וֵאלֹהֵי יַעֲקֹב",
         "אן קד תגלא לך. אללה אלאה אבאיהם. אלאה אברהים יצחק ויעקוב",
         "that God — the God of their fathers, the God of Abraham, Isaac, and Jacob — has appeared to you"),
    ],
    6: [
        ("וַיֹּאמֶר יְהוָה לוֹ עוֹד", "וקאל לה איצ'א",
         "And He said to him further"),
        ("הָבֵא-נָא יָדְךָ", "אדכ'ל ידך", "Put your hand"),
        ("בְּחֵיקֶךָ", "אלי' כמך", "into your bosom"),
        ("וַיָּבֵא יָדוֹ בְּחֵיקוֹ", "פאדכ'להא", "And he put it in"),
        ("וַיּוֹצִאָהּ", "ת'ם אכ'רגהא", "then he brought it out"),
        ("וְהִנֵּה יָדוֹ מְצֹרַעַת", "פאד'א בהא ביצ'א",
         "and behold, it was white"),
        ("כַּשָּׁלֶג", "כאלת'לג", "as snow"),
    ],
    7: [
        ("וַיֹּאמֶר", "פקאל", "And He said"),
        ("הָשֵׁב יָדְךָ", "ארדד ידך", "Return your hand"),
        ("אֶל-חֵיקֶךָ", "אלי' כמך", "to your bosom"),
        ("וַיָּשֶׁב יָדוֹ אֶל-חֵיקוֹ", "פארדדהא", "And he returned it"),
        ("וַיּוֹצִאָהּ מֵחֵיקוֹ", "ת'ם אכ'רגהא",
         "then he brought it out"),
        ("וְהִנֵּה-שָׁבָה כִּבְשָׂרוֹ", "וקד עאדת כסאיר בדנה",
         "and it had returned [to be] like the rest of his body"),
    ],
    8: [
        ("וְהָיָה אִם-לֹא יַאֲמִינוּ לָךְ", "פאן לם יומנון בך",
         "And if they will not believe you"),
        ("וְלֹא יִשְׁמְעוּ לְקֹל הָאֹת הָרִאשׁוֹן",
         "ולא יקבלון אלאיה אלאולי'",
         "and will not accept the first sign"),
        ("וְהֶאֱמִינוּ לְקֹל הָאֹת הָאַחֲרוֹן",
         "פיומנון באלאיה אלת'אניה",
         "then they will believe the second sign"),
    ],
    9: [
        ("וְהָיָה אִם-לֹא יַאֲמִינוּ", "פאן לם יומנון",
         "And if they will not believe"),
        ("גַּם לִשְׁנֵי הָאֹתוֹת הָאֵלֶּה", "בהאתין אלאיתין",
         "these two signs"),
        ("וְלֹא יִשְׁמְעוּן לְקֹלֶךָ", "ולם יקבלון מנך",
         "and will not accept from you"),
        ("וְלָקַחְתָּ", "פכ'ד'", "then take"),
        ("מִמֵּימֵי הַיְאֹר", "מן מא אלניל",
         "from the water of the Nile"),
        ("וְשָׁפַכְתָּ הַיַּבָּשָׁה", "ואצבבה עלי' אליבאס",
         "and pour it upon the dry ground"),
        ("וְהָיוּ הַמַּיִם אֲשֶׁר תִּקַּח מִן-הַיְאֹר", "פאנה ינקלב",
         "and it shall change"),
        ("וְהָיוּ לְדָם בַּיַּבָּשֶׁת", "ויציר דמא פי אליבאס",
         "and shall become blood upon the dry ground"),
    ],
    10: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוָה", "פקאל מוסי' לרבה",
         "And Moses said to his Lord"),
        ("בִּי אֲדֹנָי", "יא רבי", "O my Lord"),
        ("לֹא אִישׁ דְּבָרִים אָנֹכִי", "ליס אנא ד'ו נטק",
         "I am not a man of speech"),
        ("גַּם מִתְּמוֹל גַּם מִשִּׁלְשֹׁם", "מן אמס ומא קבלה",
         "neither from yesterday and before"),
        ("גַּם מֵאָז דַּבֶּרְךָ אֶל-עַבְדֶּךָ", "ולא מן חין כ'אטבת עבדך",
         "nor from the time You spoke to Your servant"),
        ("כִּי כְבַד-פֶּה וּכְבַד לָשׁוֹן אָנֹכִי",
         "אני ת'קיל אלפם ואלסאן גמיעא",
         "for I am heavy of mouth and of tongue together"),
    ],
    11: [
        ("וַיֹּאמֶר יְהוָה אֵלָיו", "קאל אללה לה", "God said to him"),
        ("מִי שָׂם פֶּה לָאָדָם", "מן כ'לק נטק לאלאנסאן",
         "Who made speech for the human"),
        ("אוֹ מִי-יָשׂוּם", "או מן יכ'לק", "Or who makes"),
        ("אִלֵּם", "אלאכ'רס", "the mute"),
        ("אוֹ חֵרֵשׁ", "או אלאצם", "or the deaf"),
        ("אוֹ פִקֵּחַ", "או אלבציר", "or the seeing"),
        ("אוֹ עִוֵּר", "או אלאעמא", "or the blind"),
        ("הֲלֹא אָנֹכִי יְהוָה", "אליס אנא אללה", "Is it not I, God"),
    ],
    12: [
        ("וְעַתָּה לֵךְ", "ואלאן אמץ'", "And now, go"),
        ("וְאָנֹכִי אֶהְיֶה עִם-פִּיךָ", "ואנא אכון מע קולך",
         "and I shall be with your speech"),
        ("וְהוֹרֵיתִיךָ", "ואדלך", "and shall direct you"),
        ("אֲשֶׁר תְּדַבֵּר", "עלי' מא תתכלם בה",
         "in what you shall say"),
    ],
    13: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("בִּי אֲדֹנָי", "יא רבי", "O my Lord"),
        ("שְׁלַח-נָא", "אבעת'", "send"),
        ("בְּיַד-תִּשְׁלָח", "במן אנת באעת'ה",
         "by whomever You will send"),
    ],
    14: [
        ("וַיִּחַר-אַף יְהוָה בְּמֹשֶׁה", "פאשתד וגד אללה עליה",
         "And God was greatly angered with him"),
        ("וַיֹּאמֶר", "וקאל", "and said"),
        ("הֲלֹא אַהֲרֹן אָחִיךָ הַלֵּוִי",
         "אליס הרון אכ'יך אלליואני",
         "Is not Aaron your brother the Levite"),
        ("יָדַעְתִּי", "אנא אעלם", "I know"),
        ("כִּי-דַבֵּר יְדַבֵּר הוּא", "באנה מתכלם",
         "that he is a speaker"),
        ("וְגַם הִנֵּה-הוּא", "והוד'א הו", "and behold, he"),
        ("יֹצֵא לִקְרָאתֶךָ", "יכ'רג תלקאך",
         "is going out to meet you"),
        ("וְרָאֲךָ", "פינצ'ר אליך", "and he will see you"),
        ("וְשָׂמַח בְּלִבּוֹ", "ויסר פי קלבה",
         "and rejoice in his heart"),
    ],
    15: [
        ("וְדִבַּרְתָּ אֵלָיו", "פכלמה", "And you shall speak to him"),
        ("וְשַׂמְתָּ אֶת-הַדְּבָרִים בְּפִיו", "וצייר אלכלאם פי פאה",
         "and shall set the words in his mouth"),
        ("וְאָנֹכִי אֶהְיֶה עִם-פִּיךָ", "ואנא אכון מע קולך",
         "and I shall be with your speech"),
        ("וְעִם-פִּיהוּ", "וקולה", "and with his speech"),
        ("וְהוֹרֵיתִי אֶתְכֶם", "ואדלכם", "and shall direct you"),
        ("אֵת אֲשֶׁר תַּעֲשׂוּן", "עלי' מא תצנעון",
         "in what you shall do"),
    ],
    16: [
        ("וְדִבֶּר-הוּא לְךָ", "פיכלם הו לך",
         "And he shall speak for you"),
        ("אֶל-הָעָם", "אלקום", "to the people"),
        ("וְהָיָה הוּא יִהְיֶה-לְּךָ לְפֶה", "ויכון לך תרגמאנא",
         "and he shall be to you a spokesman"),
        ("וְאַתָּה תִּהְיֶה-לּוֹ לֵאלֹהִים", "ואנת תכון לה אסתאדא",
         "and you shall be to him a master"),
    ],
    17: [
        ("וְאֶת-הַמַּטֶּה הַזֶּה תִּקַּח", "וכד' הד'ה אלעצא",
         "And take this staff"),
        ("בְּיָדֶךָ", "פי ידך", "in your hand"),
        ("אֲשֶׁר תַּעֲשֶׂה-בּוֹ אֶת-הָאֹתֹת", "תצנע בהא אלמעגזאת",
         "you shall perform the wonders by it"),
    ],
    18: [
        ("וַיֵּלֶךְ מֹשֶׁה", "פמצ'א מוסי", "And Moses went"),
        ("וַיָּשָׁב אֶל-יֶתֶר חֹתְנוֹ", "ורגע אלי' יתר חמוה",
         "and returned to Jether his father-in-law"),
        ("וַיֹּאמֶר לוֹ", "וקאל לה", "and said to him"),
        ("אֵלְכָה נָּא וְאָשׁוּבָה", "אמצ'י וארגע",
         "Let me go and return"),
        ("אֶל-אַחַי אֲשֶׁר-בְּמִצְרַיִם", "אלי' אכ'ותי אלד'ין במצר",
         "to my brothers who are in Egypt"),
        ("וְאֶרְאֶה הַעוֹדָם חַיִּים", "ואנצ'ר הל הם באקון",
         "and see whether they are still surviving"),
        ("וַיֹּאמֶר יִתְרוֹ לְמֹשֶׁה", "קאל לה יתרו",
         "Jethro said to him"),
        ("לֵךְ לְשָׁלוֹם", "אמץ' בסלאם", "Go in peace"),
    ],
    19: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה בְּמִדְיָן",
         "ת'ם קאל אללה למוסי במדין",
         "Then God said to Moses in Midian"),
        ("לֵךְ שֻׁב מִצְרָיִם", "אמץ' ארגע אלי' מצר",
         "Go, return to Egypt"),
        ("כִּי-מֵתוּ כָּל-הָאֲנָשִׁים הַמְבַקְשִׁים אֶת-נַפְשֶׁךָ",
         "פאן קד מאת גמיע אלקום. אלטאלבין קתלך",
         "for all the men who sought to kill you have died"),
    ],
    20: [
        ("וַיִּקַּח מֹשֶׁה", "פאכ'ד' מ'וסי'", "And Moses took"),
        ("אֶת-אִשְׁתּוֹ", "זוגתה", "his wife"),
        ("וְאֶת-בָּנָיו", "וולדיה", "and his sons"),
        ("וַיַּרְכִּבֵם עַל-הַחֲמֹר", "וארכבהם עלי' חמיר",
         "and set them upon donkeys"),
        (None, "ובעת' בהם", "and led them"),
        ("וַיָּשָׁב אַרְצָה מִצְרָיִם", "ורגע אלי' בלד מצר",
         "and he returned to the land of Egypt"),
        ("וַיִּקַּח מֹשֶׁה אֶת-מַטֵּה הָאֱלֹהִים",
         "ואכ'ד' אלעצא אלתי אמרה אללה בהא",
         "And he took the staff which God had commanded him with"),
        ("בְּיָדוֹ", "פי ידה", "in his hand"),
    ],
    21: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה לה",
         "Then God said to him"),
        ("בְּלֶכְתְּךָ", "פי מצ'ייך", "In your going"),
        ("לָשׁוּב מִצְרַיְמָה", "לתרגע אלי' מצר",
         "to return to Egypt"),
        ("רְאֵה", "אנצ'ר", "see"),
        ("כָּל-הַמֹּפְתִים", "גמיע אלבראהין", "all the proofs"),
        ("אֲשֶׁר-שַׂמְתִּי בְיָדֶךָ", "אלתי ציירתהא פי ידך",
         "which I have set in your hand"),
        ("וַעֲשִׂיתָם לִפְנֵי פַרְעֹה", "אצנעהא בין ידי פרעון",
         "perform them before Pharaoh"),
        ("וַאֲנִי אֲחַזֵּק אֶת-לִבּוֹ", "ואנא אשדד קלבה",
         "And I shall harden his heart"),
        ("וְלֹא יְשַׁלַּח אֶת-הָעָם", "ולא יטלק אלקום",
         "and he shall not let the people go"),
    ],
    22: [
        ("וְאָמַרְתָּ אֶל-פַּרְעֹה", "וקל לה", "And say to him"),
        ("כֹּה אָמַר יְהוָה", "כד'א קאל אללה", "Thus says God"),
        (None, "משרפא", "in honor"),
        ("בְּנִי בְכֹרִי יִשְׂרָאֵל", "אבני בכרי אסראיל",
         "Israel is My son, My firstborn"),
    ],
    23: [
        ("וָאֹמַר אֵלֶיךָ", "פק'לת לך", "And I have said to you"),
        ("שַׁלַּח אֶת-בְּנִי", "אטלק אבני", "Let My son go"),
        ("וְיַעַבְדֵנִי", "יעבדני", "that he may worship Me"),
        ("וַתְּמָאֵן לְשַׁלְּחוֹ", "פאן אבית אן תטלקה",
         "And if you refuse to let him go"),
        ("הִנֵּה אָנֹכִי הֹרֵג", "האנא קאתל",
         "behold, I am about to kill"),
        ("אֶת-בִּנְךָ בְּכֹרֶךָ", "אבנך בכרך",
         "your son, your firstborn"),
    ],
    24: [
        ("וַיְהִי בַדֶּרֶךְ", "ולמא כאן באלטריק",
         "And it was on the way"),
        ("בַּמָּלוֹן", "פי אלמבית", "at the lodging-place"),
        ("וַיִּפְגְּשֵׁהוּ יְהוָה", "פאגא ולדה מלך אללה",
         "the angel of God came suddenly upon his son"),
        ("וַיְבַקֵּשׁ הֲמִיתוֹ", "פטלב קתלה", "and sought to kill him"),
    ],
    25: [
        ("וַתִּקַּח צִפֹּרָה צֹר", "פאכ'ד'ת צפורה צואנא",
         "And Zipporah took a flint"),
        ("וַתִּכְרֹת אֶת-עָרְלַת בְּנָהּ", "וקטעת קלפה' אבנהא",
         "and cut off the foreskin of her son"),
        ("וַתַּגַּע לְרַגְלָיו", "וקדמתה בין ידי",
         "and presented it before [him]"),
        ("וַתֹּאמֶר", "וקאלת", "and she said"),
        ("כִּי חֲתַן-דָּמִים אַתָּה לִי", "כאד אלערוס אן יכון מקתולא",
         "The bridegroom was about to be killed"),
    ],
    26: [
        ("וַיִּרֶף מִמֶּנּוּ", "פכף ענה", "And He desisted from him"),
        ("אָז אָמְרָה", "חיניד' קאלת", "At that time she said"),
        ("חֲתַן דָּמִים לַמּוּלֹת", "צאר אלערוס אלמקתול מכ'תונא",
         "The bridegroom marked for death has become circumcised"),
    ],
    27: [
        ("וַיֹּאמֶר יְהוָה אֶל-אַהֲרֹן", "פקאל אללה להרון",
         "And God said to Aaron"),
        ("לֵךְ לִקְרַאת מֹשֶׁה", "אמץ' תלקא מוסי'",
         "Go to meet Moses"),
        ("הַמִּדְבָּרָה", "אלי' אלבר", "into the wilderness"),
        ("וַיֵּלֶךְ", "פמצ'א", "And he went"),
        ("וַיִּפְגְּשֵׁהוּ", "וואפאה", "and met him"),
        ("בְּהַר הָאֱלֹהִים", "פי גבל אללה", "at the mountain of God"),
        ("וַיִּשַּׁק-לוֹ", "וקבלה", "and kissed him"),
    ],
    28: [
        ("וַיַּגֵּד מֹשֶׁה לְאַהֲרֹן", "פאכ'ברה מוסי'",
         "And Moses informed him"),
        ("אֵת כָּל-דִּבְרֵי יְהוָה", "בגמיע כלאם אללה",
         "of all the words of God"),
        ("אֲשֶׁר שְׁלָחוֹ", "אלד'י בעת' בה",
         "which He had sent him with"),
        ("וְאֵת כָּל-הָאֹתֹת", "וגמיע אלאיאת", "and all the signs"),
        ("אֲשֶׁר צִוָּהוּ", "אלתי אמרה", "which He had commanded him"),
    ],
    29: [
        ("וַיֵּלֶךְ מֹשֶׁה וְאַהֲרֹן", "פמצ'א מוסי' והרון",
         "And Moses and Aaron went"),
        ("וַיַּאַסְפוּ", "וגמעא", "and gathered"),
        ("אֶת-כָּל-זִקְנֵי בְּנֵי יִשְׂרָאֵל", "גמיע שיוך' בני אסראיל",
         "all the elders of the sons of Israel"),
    ],
    30: [
        ("וַיְדַבֵּר אַהֲרֹן", "וכלמהם הרון", "And Aaron spoke"),
        ("אֵת כָּל-הַדְּבָרִים", "בגמיע אלכלאם", "all the words"),
        ("אֲשֶׁר-דִּבֶּר יְהוָה אֶל-מֹשֶׁה",
         "אלד'י כלם אללה מוסי'",
         "which God had spoken to Moses"),
        ("וַיַּעַשׂ הָאֹתֹת", "וצנע אלמעגזאת",
         "and performed the wonders"),
        ("לְעֵינֵי הָעָם", "בחצ'רה' אלקום",
         "in the presence of the people"),
    ],
    31: [
        ("וַיַּאֲמֵן הָעָם", "פאמן אלקום", "And the people believed"),
        ("וַיִּשְׁמְעוּ", "אד' סמעו", "and when they heard"),
        ("כִּי-פָקַד יְהוָה אֶת-בְּנֵי יִשְׂרָאֵל",
         "אן קד ד'כר אללה בני אסראיל",
         "that God had remembered the sons of Israel"),
        ("וְכִי רָאָה אֶת-עָנְיָם", "ונצ'ר לצ'עפהם",
         "and had looked upon their affliction"),
        ("וַיִּקְּדוּ", "פכ'רו", "they bowed down"),
        ("וַיִּשְׁתַּחֲווּ", "וסגדו", "and prostrated themselves"),
    ],
}
