"""Hand-authored alignment triples for Shemot chapter 27."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְעָשִׂיתָ אֶת-הַמִּזְבֵּחַ עֲצֵי שִׁטִּים",
         "ואצנע מד'בח אלקראבין מן כ'שב אלסנט",
         "And make the altar of offerings from acacia wood"),
        ("חָמֵשׁ אַמּוֹת אֹרֶךְ וְחָמֵשׁ אַמּוֹת רֹחַב",
         "כ'מסה' אד'רע טולה. וכ'מסה' אד'רע ערצה",
         "five cubits its length, and five cubits its width"),
        ("רָבוּעַ יִהְיֶה הַמִּזְבֵּחַ", "וליכון מרבעא",
         "and let it be square"),
        ("וְשָׁלֹשׁ אַמּוֹת קֹמָתוֹ", "ות'לאת'ה' אד'ר'ע סמכה",
         "and three cubits its height."),
    ],
    2: [
        ("וְעָשִׂיתָ קַרְנֹתָיו עַל אַרְבַּע פִּנֹּתָיו",
         "ואצנע ארכאנה. עלי' ארבע גהאתה",
         "And make its horns upon its four sides"),
        ("מִמֶּנּוּ תִּהְיֶיןָ קַרְנֹתָיו", "מנה תכון ארכאנה",
         "from it shall be its horns"),
        ("וְצִפִּיתָ אֹתוֹ נְחֹשֶׁת", "וג'שה בנחס",
         "and overlay it with copper."),
    ],
    3: [
        ("וְעָשִׂיתָ סִּירֹתָיו לְדַשְּׁנוֹ", "ואצנע צנאנה לרמאדה",
         "And make its pots for its ash"),
        ("וְיָעָיו וּמִזְרְקֹתָיו וּמִזְלְגֹתָיו וּמַחְתֹּתָיו",
         "ומג'ארפה וכ'ראנבה ומנאשלה ומגאמרה",
         "and its shovels and its basins and its forks and its fire-pans"),
        ("לְכָל-כֵּלָיו תַּעֲשֶׂה נְחֹשֶׁת", "וגמיע אניתה אצנעהא מן נחאס",
         "all its vessels make from copper."),
    ],
    4: [
        ("וְעָשִׂיתָ לּוֹ מִכְבָּר מַעֲשֵׂה רֶשֶׁת נְחֹשֶׁת",
         "ואצנע לה סרדא. עלי' צנעה' אלשבכה מן נחאס",
         "And make for it a grating, after the fashion of a net, of copper"),
        ("וְעָשִׂיתָ עַל-הָרֶשֶׁת אַרְבַּע טַבְּעֹת נְחֹשֶׁת עַל אַרְבַּע קְצוֹתָיו",
         "ואצנע עלי' אלשבכה. ארבע חלק מן נחאס. פי ארבע אטראפהא",
         "and make upon the net four rings of copper, at its four corners."),
    ],
    5: [
        ("וְנָתַתָּה אֹתָהּ תַּחַת כַּרְכֹּב הַמִּזְבֵּחַ--מִלְּמָטָּה",
         "ואגעלהא. תחת שרגע אלמד'בח מן אספל",
         "And set it beneath the ledge of the altar from below"),
        ("וְהָיְתָה הָרֶשֶׁת עַד חֲצִי הַמִּזְבֵּחַ",
         "פתבלג אלי' נצפה",
         "so that it reaches to its midpoint."),
    ],
    6: [
        ("וְעָשִׂיתָ בַדִּים לַמִּזְבֵּחַ בַּדֵּי עֲצֵי שִׁטִּים",
         "ואצנע דהוקא לאלמד'בח מן כ'שב אלסנט",
         "And make poles for the altar from acacia wood"),
        ("וְצִפִּיתָ אֹתָם נְחֹשֶׁת", "וג'שהא בנחאס",
         "and overlay them with copper."),
    ],
    7: [
        ("וְהוּבָא אֶת-בַּדָּיו בַּטַּבָּעֹת", "ואדכ'ל אלדהוק פי אלחלק",
         "And insert the poles into the rings"),
        ("וְהָיוּ הַבַּדִּים עַל-שְׁתֵּי צַלְעֹת הַמִּזְבֵּחַ--בִּשְׂאֵת אֹתוֹ",
         "ותכון עלי' גאנבי אלמד'בח אד'א חמל",
         "and they shall be upon the two sides of the altar when it is carried."),
    ],
    8: [
        ("נְבוּב לֻחֹת תַּעֲשֶׂה אֹתוֹ", "ואצנעה אלואחא מגוופה",
         "And make it hollow planks"),
        ("כַּאֲשֶׁר הֶרְאָה אֹתְךָ בָּהָר כֵּן יַעֲשׂוּ",
         "כמא אורית פי אלגבל כד'אך יצנעו",
         "as you were shown upon the mountain, so shall they make it."),
    ],
    9: [
        ("וְעָשִׂיתָ אֵת חֲצַר הַמִּשְׁכָּן",
         "ואצנע צראדק אלמסכן",
         "And make the enclosure of the tabernacle"),
        ("לִפְאַת נֶגֶב-תֵּימָנָה", "מן גהה' מהב אלגנוב",
         "from the direction of the south wind"),
        ("קְלָעִים לֶחָצֵר שֵׁשׁ מָשְׁזָר", "קלוע לאלצראדק מן עשר משזור",
         "hanging drapes for the enclosure of fine twisted linen"),
        ("מֵאָה בָאַמָּה אֹרֶךְ לַפֵּאָה הָאֶחָת",
         "מאיה' ד'ראע טולהא. פי אלגהה אלואחדה",
         "a hundred cubits in length on the one side."),
    ],
    10: [
        ("וְעַמֻּדָיו עֶשְׂרִים וְאַדְנֵיהֶם עֶשְׂרִים נְחֹשֶׁת",
         "ועמדהא עשרין. וקואעדהא עשרין מן נחאס",
         "And its pillars twenty, and their bases twenty of copper"),
        ("וָוֵי הָעַמֻּדִים וַחֲשֻׁקֵיהֶם כָּסֶף",
         "וזראפין אלעמד. וטלאהא פצ'ה",
         "and the clasps of the pillars and their coating, silver."),
    ],
    11: [
        ("וְכֵן לִפְאַת צָפוֹן בָּאֹרֶךְ",
         "וכד'אך פי גהה' אלשמאל פי אלטול",
         "And likewise on the north side in length"),
        ("קְלָעִים מֵאָה אֹרֶךְ",
         "קלוע טולהא מאיה' ד'ראע",
         "hanging drapes a hundred cubits in length"),
        ("וְעַמֻּדָו עֶשְׂרִים וְאַדְנֵיהֶם עֶשְׂרִים נְחֹשֶׁת",
         "ועמדהא עשרין. וקואעדהא עשרין מן נחאס",
         "and their pillars twenty, and their bases twenty of copper"),
        ("וָוֵי הָעַמֻּדִים וַחֲשֻׁקֵיהֶם כָּסֶף",
         "וזראפין אלעמד. וטלאהא פצ'ה",
         "and the clasps of the pillars and their coating, silver."),
    ],
    12: [
        ("וְרֹחַב הֶחָצֵר לִפְאַת-יָם קְלָעִים חֲמִשִּׁים אַמָּה",
         "וערץ' אלצראדק מן גהה' אלג'רב. קלוע כ'מסין ד'ראע",
         "And the width of the enclosure on the west side — hanging drapes fifty cubits"),
        ("עַמֻּדֵיהֶם עֲשָׂרָה וְאַדְנֵיהֶם עֲשָׂרָה",
         "עמדהא עשרה. וקואעדהא עשרה",
         "their pillars ten, and their bases ten."),
    ],
    13: [
        ("וְרֹחַב הֶחָצֵר לִפְאַת קֵדְמָה מִזְרָחָה--חֲמִשִּׁים אַמָּה",
         "וערץ' אלצראדק. מן גהה' אלשרק כ'מסין ד'ראע",
         "And the width of the enclosure on the east side — fifty cubits."),
    ],
    14: [
        ("וַחֲמֵשׁ עֶשְׂרֵה אַמָּה קְלָעִים לַכָּתֵף",
         "מנהא כ'מסה' עשר ד'ראע קלוע לאלכם",
         "Of these, fifteen cubits of hanging drapes for the one wing"),
        ("עַמֻּדֵיהֶם שְׁלֹשָׁה וְאַדְנֵיהֶם שְׁלֹשָׁה",
         "עמדהא ת'לאת'ה. וקואעדהא ת'לאת'ה",
         "their pillars three, and their bases three."),
    ],
    15: [
        ("וְלַכָּתֵף הַשֵּׁנִית--חֲמֵשׁ עֶשְׂרֵה קְלָעִים",
         "ולאלכם אלת'אני. קלוע כ'מסה' עשר ד'ראע",
         "And for the second wing, hanging drapes fifteen cubits"),
        ("עַמֻּדֵיהֶם שְׁלֹשָׁה וְאַדְנֵיהֶם שְׁלֹשָׁה",
         "עמדהא ת'לאת'ה. וקואעדהא ת'לאת'ה",
         "their pillars three, and their bases three."),
    ],
    16: [
        ("וּלְשַׁעַר הֶחָצֵר מָסָךְ עֶשְׂרִים אַמָּה",
         "ולבאב אלצראדק. סתר טולה עשרין ד'ראע",
         "And for the gate of the enclosure, a screen twenty cubits in length"),
        ("תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר--מַעֲשֵׂה רֹקֵם",
         "מן אסמאנגון וארגואן. וצבג' קרמז. ועשר משזור. צנעה' ראקם",
         "of blue and purple and scarlet dye, and fine twisted linen — the work of an embroiderer"),
        ("עַמֻּדֵיהֶם אַרְבָּעָה וְאַדְנֵיהֶם אַרְבָּעָה",
         "ולה עמד ארבעה. וקואעדהא ארבעה",
         "and it shall have four pillars and four bases."),
    ],
    17: [
        ("כָּל-עַמּוּדֵי הֶחָצֵר סָבִיב מְחֻשָּׁקִים כֶּסֶף",
         "גמיע עמד אלצראדק מסתדירא מטלייה פצ'ה",
         "All the pillars of the enclosure round about are coated with silver"),
        ("וָוֵיהֶם כָּסֶף וְאַדְנֵיהֶם נְחֹשֶׁת",
         "וזראפינהא פצ'ה. וקואעדהא מן נחאס",
         "their clasps of silver, and their bases of copper."),
    ],
    18: [
        ("אֹרֶךְ הֶחָצֵר מֵאָה בָאַמָּה", "טול אלצראדק מאיה' ד'ראע",
         "The length of the enclosure one hundred cubits"),
        ("וְרֹחַב חֲמִשִּׁים בַּחֲמִשִּׁים", "וערצה כ'מסין באלכ'מסין",
         "and its width fifty by fifty"),
        ("וְקֹמָה חָמֵשׁ אַמּוֹת--שֵׁשׁ מָשְׁזָר", "וסמכה כ'מסה' אד'ר'ע מן עשר משזור",
         "and its height five cubits, of fine twisted linen"),
        ("וְאַדְנֵיהֶם נְחֹשֶׁת", "וקואעדהא מן נחאס",
         "and their bases of copper."),
    ],
    19: [
        ("לְכֹל כְּלֵי הַמִּשְׁכָּן בְּכֹל עֲבֹדָתוֹ",
         "וסאיר אניה' אלמסכן. אלתי פי גמיע כ'דמתה",
         "And the rest of the vessels of the tabernacle in all its service"),
        ("וְכָל-יְתֵדֹתָיו וְכָל-יִתְדֹת הֶחָצֵר נְחֹשֶׁת",
         "וגמיע אותאדה . ואותאד אלצראדק מן נחאס",
         "and all its pegs, and all the pegs of the enclosure — of copper."),
    ],
    20: [
        ("וְאַתָּה תְּצַוֶּה אֶת-בְּנֵי יִשְׂרָאֵל",
         "ואנת פמר בני אסראיל",
         "And you — command the sons of Israel"),
        ("וְיִקְחוּ אֵלֶיךָ שֶׁמֶן זַיִת זָךְ כָּתִית--לַמָּאוֹר",
         "אן יאתוך בדהן זית צאף. מדקוק לאלאצ'אה",
         "that they bring you pure olive oil, beaten, for illumination"),
        ("לְהַעֲלֹת נֵר תָּמִיד", "לתסרג פיה אלסרג דאימא",
         "to kindle therein the lamp continually."),
    ],
    21: [
        ("בְּאֹהֶל מוֹעֵד מִחוּץ לַפָּרֹכֶת אֲשֶׁר עַל-הָעֵדֻת",
         "פי כ'בא אלמחצ'ר פי כ'ארג אלסגף אלד'י עלי' אלשהאדה",
         "In the tent of the assembly, outside the curtain that is by the testimony"),
        ("יַעֲרֹךְ אֹתוֹ אַהֲרֹן וּבָנָיו מֵעֶרֶב עַד-בֹּקֶר--לִפְנֵי יְהוָה",
         "ינצ'דה הרון ובניה. מן אלעשי אלי' אלצבאח בין ידי אללה",
         "Aaron and his sons shall arrange it — from evening until morning before God"),
        ("חֻקַּת עוֹלָם לְדֹרֹתָם מֵאֵת בְּנֵי יִשְׂרָאֵל",
         "רסם אלדהר לאגיאלהם. מן בני אסראיל",
         "a perpetual ordinance unto all ages for their generations, from the sons of Israel."),
    ],
}
