"""Hand-authored alignment triples for Shemot chapter 34."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי'",
         "Then God said to Moses:"),
        ("פְּסָל-לְךָ שְׁנֵי-לֻחֹת אֲבָנִים כָּרִאשֹׁנִים",
         "אנחת לוחי גוהר כאלאוולין",
         "'Hew out two tablets of gemstone like the first ones,"),
        ("וְכָתַבְתִּי עַל-הַלֻּחֹת אֶת-הַדְּבָרִים",
         "חתי' אכתב עליהמא. גמיע אלכלאם",
         "so that I may write upon them all the words"),
        ("אֲשֶׁר הָיוּ עַל-הַלֻּחֹת הָרִאשֹׁנִים אֲשֶׁר שִׁבַּרְתָּ",
         "אלד'י כאן. עלי' אללוחין אלאוולין אלד'י כסרתהמא",
         "which were upon the first two tablets — those that you broke.'"),
    ],
    2: [
        ("וֶהְיֵה נָכוֹן לַבֹּקֶר", "וכן מסתעדא לאלג'דאה",
         "And be ready for the morning;"),
        ("וְעָלִיתָ בַבֹּקֶר אֶל-הַר סִינַי",
         "ואצעד פי אלג'דאה אלי' גבל סיני",
         "and ascend in the morning to Mount Sinai,"),
        ("וְנִצַּבְתָּ לִי שָׁם עַל-רֹאשׁ הָהָר",
         "וקף לי ת'ם עלי' ראס אלגבל",
         "and stand there before Me upon the summit of the mountain."),
    ],
    3: [
        ("וְאִישׁ לֹא-יַעֲלֶה עִמָּךְ", "ואנסאן לא יצעד מעך",
         "And no person shall ascend with you,"),
        ("וְגַם-אִישׁ אַל-יֵרָא בְּכָל-הָהָר",
         "ולא ירא אנסאן פי שיי מן אלגבל",
         "and no person shall be seen in any part of the mountain;"),
        ("גַּם-הַצֹּאן וְהַבָּקָר אַל-יִרְעוּ אֶל-מוּל הָהָר הַהוּא",
         "חתי' אלג'נם ואלבקר לא ירעון. ממא יליה",
         "even the flocks and the herds shall not graze in what is adjacent to it.'"),
    ],
    4: [
        ("וַיִּפְסֹל שְׁנֵי-לֻחֹת אֲבָנִים כָּרִאשֹׁנִים",
         "פנחת לוחי גוהר כאלאוולין",
         "So he hewed out two tablets of gemstone like the first ones;"),
        ("וַיַּשְׁכֵּם מֹשֶׁה בַבֹּקֶר", "ואדלג מוסי' באלג'דאה",
         "and Moses rose early before sunrise"),
        ("וַיַּעַל אֶל-הַר סִינַי כַּאֲשֶׁר צִוָּה יְהוָה אֹתוֹ",
         "וצעד אלי' גבל סיני. כמא אמרה אללה",
         "and ascended to Mount Sinai, as God had commanded him;"),
        ("וַיִּקַּח בְּיָדוֹ שְׁנֵי לֻחֹת אֲבָנִים",
         "ואכ'ד' מעה לוחי אלגוהר",
         "and he took with him the two tablets of gemstone."),
    ],
    5: [
        ("וַיֵּרֶד יְהוָה בֶּעָנָן", "פתגלא אללה באלג'מאם",
         "And God appeared in the cloud,"),
        ("וַיִּתְיַצֵּב עִמּוֹ שָׁם", "ואוקף נורה מעה הנאך",
         "and set His light with him there;"),
        ("וַיִּקְרָא בְשֵׁם יְהוָה", "ונאדא באסם אללה",
         "and He called out in the name of God."),
    ],
    6: [
        ("וַיַּעֲבֹר יְהוָה עַל-פָּנָיו", "פלמא מר נור אללה בין ידיה",
         "And when the light of God passed before him,"),
        ("וַיִּקְרָא יְהוָה יְהוָה אֵל רַחוּם וְחַנּוּן",
         "נאדא אללה. אללה אלטאיק אלרחום אלראוף",
         "God called out: 'God! God! — the Able, the Merciful, the Compassionate,"),
        ("אֶרֶךְ אַפַּיִם", "טויל אלמהל", "long of forbearance,"),
        ("וְרַב-חֶסֶד וֶאֱמֶת", "כת'יר אלפצ'ל ואלאחסאן",
         "abundant in grace and goodness,"),
    ],
    7: [
        ("נֹצֵר חֶסֶד לָאֲלָפִים", "חאפץ' אלפצ'ל לאלוף",
         "keeping grace unto thousands,"),
        ("נֹשֵׂא עָו‍ֹן וָפֶשַׁע וְחַטָּאָה",
         "ג'אפר אלדנב ואלגרם ואלכ'טייה",
         "forgiving iniquity and transgression and sin —"),
        ("וְנַקֵּה לֹא יְנַקֶּה", "ויברי ולא יברי",
         "and He pardons, yet does not pardon —"),
        ("פֹּקֵד עֲו‍ֹן אָבוֹת עַל-בָּנִים וְעַל-בְּנֵי בָנִים",
         "מטאלב בד'נוב אלאבא מע אלבנין",
         "requiring the iniquities of the fathers together with the sons,"),
        ("עַל-שִׁלֵּשִׁים וְעַל-רִבֵּעִים", "ואלת'ואלת' ואלרואבע",
         "and with the third and fourth generations.'"),
    ],
    8: [
        ("וַיְמַהֵר מֹשֶׁה", "פאסרע מוסי'", "And Moses hastened,"),
        ("וַיִּקֹּד אַרְצָה וַיִּשְׁתָּחוּ",
         "וכ'ר עלי' אלארץ' וסגד",
         "and fell upon the ground and bowed down."),
    ],
    9: [
        ("וַיֹּאמֶר", "קאל", "He said:"),
        ("אִם-נָא מָצָאתִי חֵן בְּעֵינֶיךָ אֲדֹנָי",
         "אן ו'גדת חצ'אא ענדך יא רב",
         "'If I have found favor with You, O Lord,"),
        ("יֵלֶךְ-נָא אֲדֹנָי בְּקִרְבֵּנוּ",
         "יסיר נורך פי מא ביננא",
         "let Your light travel among us —"),
        ("כִּי עַם-קְשֵׁה-עֹרֶף הוּא", "אד' הם קום צעאב אלרקאב",
         "for they are a people stiff of neck;"),
        ("וְסָלַחְתָּ לַעֲו‍ֹנֵנוּ וּלְחַטָּאתֵנוּ",
         "פאג'פר ד'נובנא וכ'טאיאנא",
         "so forgive our iniquities and our sins,"),
        ("וּנְחַלְתָּנוּ", "ואצטפנא", "and choose us as Your own.'"),
    ],
    10: [
        ("וַיֹּאמֶר", "קאל", "He said:"),
        ("הִנֵּה אָנֹכִי כֹּרֵת בְּרִית",
         "האנא עאהד עהדא",
         "'Behold, I am making a covenant —"),
        ("נֶגֶד כָּל-עַמְּךָ אֶעֱשֶׂה נִפְלָאֹת",
         "וחד'א גמיע קומך אצנע אעגובאת",
         "before all your people I shall perform wonders"),
        ("אֲשֶׁר לֹא-נִבְרְאוּ בְכָל-הָאָרֶץ וּבְכָל-הַגּוֹיִם",
         "מא לם יכ'לק מת'להא. פי גמיע אלעאלם ופי מא בין אלאמם",
         "the like of which have not been created in all the world nor among the nations;"),
        ("וְרָאָה כָל-הָעָם אֲשֶׁר-אַתָּה בְקִרְבּוֹ אֶת-מַעֲשֵׂה יְהוָה",
         "וינצ'ר גמיע אלקום. אלד'י אנת פי מא בינהם. צנע אללה",
         "and all the people in whose midst you are shall behold the work of God,"),
        ("כִּי-נוֹרָא הוּא אֲשֶׁר אֲנִי עֹשֶׂה עִמָּךְ",
         "אנה מכ'יף. אלד'י אנא צאנעה מעך",
         "that it is awesome — that which I am doing with you."),
    ],
    11: [
        ("שְׁמָר-לְךָ--אֵת אֲשֶׁר אָנֹכִי מְצַוְּךָ הַיּוֹם",
         "פאחפץ' מא אנא אמרך בה אליום",
         "Keep what I am commanding you this day:"),
        ("הִנְנִי גֹרֵשׁ מִפָּנֶיךָ אֶת-הָאֱמֹרִי וְהַכְּנַעֲנִי",
         "האנא טארד מן בין ידיך. אלאמוריין ואלכנעאניין",
         "behold, I am driving out from before you the Amorites and the Canaanites"),
        ("וְהַחִתִּי וְהַפְּרִזִּי וְהַחִוִּי וְהַיְבוּסִי",
         "ואלחתיין ואלפרזיין. ואלחויין ואליבוסיין",
         "and the Hittites and the Perizzites and the Hivites and the Jebusites."),
    ],
    12: [
        ("הִשָּׁמֶר לְךָ פֶּן-תִּכְרֹת בְּרִית לְיוֹשֵׁב הָאָרֶץ",
         "אחד'ר אן תעהד עהדא לאהל אלבלד",
         "Take heed lest you make a covenant with the inhabitants of the land"),
        ("אֲשֶׁר אַתָּה בָּא עָלֶיהָ", "אלד'י אנת צאיר אליה",
         "to which you are going,"),
        ("פֶּן-יִהְיֶה לְמוֹקֵשׁ בְּקִרְבֶּךָ",
         "כלא יכונו והקא פי מא בינך",
         "lest they become a snare in your midst."),
    ],
    13: [
        ("כִּי אֶת-מִזְבְּחֹתָם תִּתֹּצוּן", "בל מד'אבחהם פאנקצ'ו",
         "Rather, their altars — pull them down;"),
        ("וְאֶת-מַצֵּבֹתָם תְּשַׁבֵּרוּן", "ודכאכהם פכסרו",
         "and their pillars — break them;"),
        ("וְאֶת-אֲשֵׁרָיו תִּכְרֹתוּן", "וסואריהם תגדעון",
         "and their cultic-posts you shall cut off."),
    ],
    14: [
        ("כִּי לֹא תִשְׁתַּחֲוֶה לְאֵל אַחֵר",
         "ולא תסגד למעבוד אכ'ר",
         "And you shall not bow down to any other object of worship;"),
        ("כִּי יְהוָה קַנָּא שְׁמוֹ", "לאן אללה אסמה אלמעאקב",
         "for God — His name is 'the Punisher,'"),
        ("אֵל קַנָּא הוּא", "והו יקדר עלי' אן יעאקב",
         "and He has the power to punish."),
    ],
    15: [
        ("פֶּן-תִּכְרֹת בְּרִית לְיוֹשֵׁב הָאָרֶץ",
         "כלא תעהד עהדא מע אהל אלבלד",
         "Lest you make a covenant with the inhabitants of the land,"),
        ("וְזָנוּ אַחֲרֵי אֱלֹהֵיהֶם וְזָבְחוּ לֵאלֹהֵיהֶם",
         "פיטג'ון פי תבע מעבודאתהם. ויד'בחון להא",
         "and they transgress in following after their objects of worship and sacrifice to them,"),
        ("וְקָרָא לְךָ וְאָכַלְתָּ מִזִּבְחוֹ",
         "וידעון בך. פתאכל מן ד'בחה",
         "and they invite you, and you eat of their sacrifice;"),
    ],
    16: [
        ("וְלָקַחְתָּ מִבְּנֹתָיו לְבָנֶיךָ",
         "ותזווג בניך מן בנאתהם",
         "and you wed your sons from their daughters,"),
        ("וְזָנוּ בְנֹתָיו אַחֲרֵי אֱלֹהֵיהֶן",
         "פתטג'י בנאתה פי תבע מעבודאתהם",
         "and their daughters transgress in following after their objects of worship,"),
        ("וְהִזְנוּ אֶת-בָּנֶיךָ אַחֲרֵי אֱלֹהֵיהֶן",
         "ותטג'י בניך איצ'א",
         "and they lead your sons astray as well."),
    ],
    17: [
        ("אֱלֹהֵי מַסֵּכָה לֹא תַעֲשֶׂה-לָּךְ",
         "ומעבודא מסבוכא לא תצנע לך",
         "And a cast object of worship — do not make for yourself."),
    ],
    18: [
        ("אֶת-חַג הַמַּצּוֹת תִּשְׁמֹר",
         "וחג אלפטיר אחפצה",
         "The festival of unleavened bread — keep it;"),
        ("שִׁבְעַת יָמִים תֹּאכַל מַצּוֹת אֲשֶׁר צִוִּיתִךָ",
         "סבעה' איאם תאכל פטירא כמא אמרתך",
         "seven days you shall eat unleavened bread as I have commanded you,"),
        ("לְמוֹעֵד חֹדֶשׁ הָאָבִיב", "פי וקת שהר אלפריך",
         "at the time of the month of the barley-harvest,"),
        ("כִּי בְּחֹדֶשׁ הָאָבִיב יָצָאתָ מִמִּצְרָיִם",
         "לאנך כ'רגת פיה מן מצר",
         "for in it you went out from Egypt."),
    ],
    19: [
        ("כָּל-פֶּטֶר רֶחֶם לִי", "וכל אוול בטן פהו לי",
         "Every firstborn of the womb belongs to Me;"),
        ("וְכָל-מִקְנְךָ תִּזָּכָר פֶּטֶר שׁוֹר וָשֶׂה",
         "ומא ד'כרתה מאשיתך. מן אואיל אלבקר ואלג'נם",
         "and whatever male your livestock brings forth, from the firstborn of the cattle and of the flocks."),
    ],
    20: [
        ("וּפֶטֶר חֲמוֹר תִּפְדֶּה בְשֶׂה",
         "ובכר אלחמיר אפדה בשאה",
         "And the firstborn of the donkeys — redeem it with a ewe-lamb;"),
        ("וְאִם-לֹא תִפְדֶּה וַעֲרַפְתּוֹ",
         "ואן לם תפדה פאקפה",
         "and if you do not redeem it, then slaughter it by the neck."),
        ("כֹּל בְּכוֹר בָּנֶיךָ תִּפְדֶּה",
         "וגמיע בכור בניך תפדיהם",
         "And all the firstborn males of your sons — redeem them;"),
        ("וְלֹא-יֵרָאוּ פָנַי רֵיקָם",
         "ולא יחצ'רו בין ידי פרג'א",
         "and they shall not appear before Me empty."),
    ],
    21: [
        ("שֵׁשֶׁת יָמִים תַּעֲבֹד", "סתה' איאם תכ'דם",
         "Six days you shall labor,"),
        ("וּבַיּוֹם הַשְּׁבִיעִי תִּשְׁבֹּת", "ופי אליום אלסאבע אסבת",
         "and on the seventh day you shall rest —"),
        ("בֶּחָרִישׁ וּבַקָּצִיר תִּשְׁבֹּת",
         "חתי' וקת אלחרת' ואלחצאד תסבת",
         "even at the time of plowing and of harvest, you shall rest."),
    ],
    22: [
        ("וְחַג שָׁבֻעֹת תַּעֲשֶׂה לְךָ בִּכּוּרֵי קְצִיר חִטִּים",
         "וחג אלאסאביע תצנעה לך. וקת בכור חצאד אלחנטה",
         "And the festival of weeks — observe it for yourself, at the time of the first of the wheat harvest;"),
        ("וְחַג הָאָסִיף--תְּקוּפַת הַשָּׁנָה",
         "וחג אלגמע. פי נהאיה' אלסנה",
         "and the festival of the ingathering, at the end of the year."),
    ],
    23: [
        ("שָׁלֹשׁ פְּעָמִים בַּשָּׁנָה", "ת'לאת' מראר פי אלסנה",
         "Three times in the year"),
        ("יֵרָאֶה כָּל-זְכוּרְךָ אֶת-פְּנֵי הָאָדֹן יְהוָה אֱלֹהֵי יִשְׂרָאֵל",
         "יחצ'ר גמיע רגאלך. בין ידי אלסייד אללה אלאה אסראיל",
         "shall all your men appear before the Lord God, the God of Israel."),
    ],
    24: [
        ("כִּי-אוֹרִישׁ גּוֹיִם מִפָּנֶיךָ", "פאני אקרץ' אממא מן בין ידיך",
         "For I shall cut off nations from before you,"),
        ("וְהִרְחַבְתִּי אֶת-גְּבֻלֶךָ", "ואוסע תכ'מך",
         "and I shall widen your territory;"),
        ("וְלֹא-יַחְמֹד אִישׁ אֶת-אַרְצְךָ",
         "ולא יג'צב אחד שייא מן ארצ'ך",
         "and no one shall seize anything from your land"),
        ("בַּעֲלֹתְךָ לֵרָאוֹת אֶת-פְּנֵי יְהוָה אֱלֹהֶיךָ",
         "אד'י צעדת לאלח'צור בין ידי אללה רבך",
         "when you ascend to appear before God your Lord —"),
        ("שָׁלֹשׁ פְּעָמִים בַּשָּׁנָה", "ת'לאת' מראר פי אלסנה",
         "three times in the year."),
    ],
    25: [
        ("לֹא-תִשְׁחַט עַל-חָמֵץ דַּם-זִבְחִי",
         "ולא תד'בח פסחי עלי' כ'מיר",
         "You shall not slaughter My Passover-offering over leaven;"),
        ("וְלֹא-יָלִין לַבֹּקֶר זֶבַח חַג הַפָּסַח",
         "ולא תבית שחום חגי אלי' אלג'דאה",
         "and you shall not leave over the fat of My festival-offering until the morning."),
    ],
    26: [
        ("רֵאשִׁית בִּכּוּרֵי אַדְמָתְךָ תָּבִיא בֵּית יְהוָה אֱלֹהֶיךָ",
         "ואואיל בכור ארצ'ך. תאתי בהא אלי' בית מקדס אללה רבך",
         "The choicest firstfruits of your land — bring them to the house of the sanctuary of God your Lord;"),
        ("לֹא-תְבַשֵּׁל גְּדִי בַּחֲלֵב אִמּוֹ",
         "ולא תאכל לחמא בלבן",
         "and you shall not eat flesh with milk.'"),
    ],
    27: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses:"),
        ("כְּתָב-לְךָ אֶת-הַדְּבָרִים הָאֵלֶּה",
         "אכתב לך הד'א אלכלאם",
         "'Write down for yourself this word,"),
        ("כִּי עַל-פִּי הַדְּבָרִים הָאֵלֶּה כָּרַתִּי אִתְּךָ בְּרִית--וְאֶת-יִשְׂרָאֵל",
         "לאן בסבבה עהדת מעך הד'א אלעהד ומע בני אסראיל",
         "for by means of it I have made this covenant with you and with the sons of Israel.'"),
    ],
    28: [
        ("וַיְהִי-שָׁם עִם-יְהוָה אַרְבָּעִים יוֹם וְאַרְבָּעִים לַיְלָה",
         "פאקאם ת'ם ענד אללה. ארבעין יומא וארבעין לילה",
         "And he remained there before God forty days and forty nights;"),
        ("לֶחֶם לֹא אָכַל וּמַיִם לֹא שָׁתָה",
         "לם יאכל טעאמא ולם ישרב מאא",
         "he ate no food and drank no water;"),
        ("וַיִּכְתֹּב עַל-הַלֻּחֹת אֵת דִּבְרֵי הַבְּרִית",
         "וכתב לה עלי' אללוחין. כלאם אלעהד",
         "and He wrote for him upon the two tablets the words of the covenant —"),
        ("עֲשֶׂרֶת הַדְּבָרִים", "והי אלעשר אלכלמאת",
         "they being the Ten Words."),
    ],
    29: [
        ("וַיְהִי בְּרֶדֶת מֹשֶׁה מֵהַר סִינַי",
         "פלמא נזל מוסי' מן גבל סיני",
         "And when Moses descended from Mount Sinai,"),
        ("וּשְׁנֵי לֻחֹת הָעֵדֻת בְּיַד-מֹשֶׁה בְּרִדְתּוֹ מִן-הָהָר",
         "ולוחי אלשהאדה פי ידה. פי נזולה מן אלגבל",
         "with the two tablets of the testimony in his hand as he descended from the mountain —"),
        ("וּמֹשֶׁה לֹא-יָדַע כִּי קָרַן עוֹר פָּנָיו--בְּדַבְּרוֹ אִתּוֹ",
         "ומוסי' לם יעלם. אנה קד בץ נור וגהה. חין כלמה אללה",
         "Moses did not know that the light of his face had begun to radiate when God had spoken with him."),
    ],
    30: [
        ("וַיַּרְא אַהֲרֹן וְכָל-בְּנֵי יִשְׂרָאֵל אֶת-מֹשֶׁה",
         "פראי' הרון. וסאיר בני אסראיל מוסי'",
         "And Aaron and the rest of the sons of Israel saw Moses —"),
        ("וְהִנֵּה קָרַן עוֹר פָּנָיו", "פאד'י קד בץ נור וגהה",
         "and behold, the light of his face was radiating;"),
        ("וַיִּירְאוּ מִגֶּשֶׁת אֵלָיו", "פכ'אפו אן יתקדמו אליה",
         "and they were afraid to approach him."),
    ],
    31: [
        ("וַיִּקְרָא אֲלֵהֶם מֹשֶׁה", "חתי' דעא בהם מוסי'",
         "Until Moses called to them;"),
        ("וַיָּשֻׁבוּ אֵלָיו אַהֲרֹן וְכָל-הַנְּשִׂאִים בָּעֵדָה",
         "פרגעו אליה. הרון וסאיר אשראף אלגמאעה",
         "and Aaron and the rest of the nobles of the assembly returned to him,"),
        ("וַיְדַבֵּר מֹשֶׁה אֲלֵהֶם", "פכלמהם מוסי'",
         "and Moses spoke with them."),
    ],
    32: [
        ("וְאַחֲרֵי-כֵן נִגְּשׁוּ כָּל-בְּנֵי יִשְׂרָאֵל",
         "ובעד ד'אלך תקדם סאיר בני אסראיל",
         "And after that, the rest of the sons of Israel drew near;"),
        ("וַיְצַוֵּם--אֵת כָּל-אֲשֶׁר דִּבֶּר יְהוָה אִתּוֹ בְּהַר סִינָי",
         "פאמרהם. בגמיע מא כלמה אללה בהא פי גבל סיני",
         "and he commanded them all that God had spoken with him on Mount Sinai."),
    ],
    33: [
        ("וַיְכַל מֹשֶׁה מִדַּבֵּר אִתָּם",
         "פלמא פרג' מוסי' מן מכ'אטבתהם",
         "And when Moses had finished speaking with them,"),
        ("וַיִּתֵּן עַל-פָּנָיו מַסְוֶה", "געל עלי' וגהה ברקעא",
         "he placed a veil over his face."),
    ],
    34: [
        ("וּבְבֹא מֹשֶׁה לִפְנֵי יְהוָה לְדַבֵּר אִתּוֹ",
         "וכאן מוסי'. אד'א דכל בין ידי אללה ליכ'אטבה",
         "And Moses, whenever he entered before God to receive His address,"),
        ("יָסִיר אֶת-הַמַּסְוֶה עַד-צֵאתוֹ",
         "ינזע אלברקע אלי' כ'רוגה",
         "would remove the veil until his departure;"),
        ("וְיָצָא וְדִבֶּר אֶל-בְּנֵי יִשְׂרָאֵל אֵת אֲשֶׁר יְצֻוֶּה",
         "ת'ם יכ'רג ויכלם בני אסראיל. בגמיע מא יומר בה",
         "then he would go out and speak to the sons of Israel all that he was commanded."),
    ],
    35: [
        ("וְרָאוּ בְנֵי-יִשְׂרָאֵל אֶת-פְּנֵי מֹשֶׁה",
         "חתי' ינצ'ר בני אסראיל וגה מוסי'",
         "So that the sons of Israel would see Moses' face —"),
        ("כִּי קָרַן עוֹר פְּנֵי מֹשֶׁה",
         "אן קד בץ נור וגהה",
         "that the light of his face was radiating;"),
        ("וְהֵשִׁיב מֹשֶׁה אֶת-הַמַּסְוֶה עַל-פָּנָיו",
         "ת'ם ירד אלברקע עלי' וגהה",
         "then he would put the veil back upon his face,"),
        ("עַד-בֹּאוֹ לְדַבֵּר אִתּוֹ",
         "אלי' וקת ד'כ'ולה ליכ'אטבה",
         "until the time of his entering to receive His address."),
    ],
}
