"""Hand-authored alignment triples for Shemot chapter 22."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("אִם-בַּמַּחְתֶּרֶת יִמָּצֵא הַגַּנָּב", "ואן וגד אלסארק פי אלנקב",
         "And if the thief be found in the breach"),
        ("וְהֻכָּה וָמֵת", "וצרב וקתל", "and be struck and killed"),
        ("אֵין לוֹ דָּמִים", "פלא תבל לה", "take no account of him."),
    ],
    2: [
        ("אִם-זָרְחָה הַשֶּׁמֶשׁ עָלָיו", "ואן אשרקת עליה אלשמס",
         "And if the sun has shone upon him"),
        ("דָּמִים לוֹ", "פתבל לה", "then take account of him"),
        ("שַׁלֵּם יְשַׁלֵּם", "וליסלם מא סרק", "and he shall deliver what he stole"),
        ("אִם-אֵין לוֹ וְנִמְכַּר בִּגְנֵבָתוֹ", "ואן לם יכון לה. פליבאע בסריקתה",
         "and if he has nothing, then he shall be sold for his theft."),
    ],
    3: [
        ("אִם-הִמָּצֵא תִמָּצֵא בְיָדוֹ הַגְּנֵבָה", "ואן וגדת אלסרקה פי ידה",
         "And if the stolen thing be found in his hand"),
        ("מִשּׁוֹר עַד-חֲמוֹר עַד-שֶׂה", "מן ת'ור אלי' חמאר. אלי' שאה",
         "whether ox or donkey or sheep"),
        ("חַיִּים", "והם אחיא", "and they are alive"),
        ("שְׁנַיִם יְשַׁלֵּם", "פליסלם בדל אלואחד את'נין",
         "he shall deliver two in place of the one."),
    ],
    4: [
        ("כִּי יַבְעֶר-אִישׁ שָׂדֶה אוֹ-כֶרֶם", "ואן ארעא אנסאן ציעה או כרם לה",
         "And if a man grazes a field or a vineyard of his"),
        ("וְשִׁלַּח אֶת-בְּעִירֹה", "פאטלק בהימתה",
         "and lets his beast loose"),
        ("וּבִעֵר בִּשְׂדֵה אַחֵר", "ורעת פי צ'יעה אכ'רי'",
         "and it grazes in another's field"),
        ("מֵיטַב שָׂדֵהוּ וּמֵיטַב כַּרְמוֹ יְשַׁלֵּם",
         "פליסלם מן אגוד צ'יעתה או כרמה",
         "he shall deliver from the best of his field or his vineyard."),
    ],
    5: [
        ("כִּי-תֵצֵא אֵשׁ", "ואן כ'רגת נאר", "And if a fire breaks out"),
        ("וּמָצְאָה קֹצִים", "פוגדת שוכא", "and finds thorns"),
        ("וְנֶאֱכַל גָּדִישׁ אוֹ הַקָּמָה אוֹ הַשָּׂדֶה",
         "ואחרקת כדיסא. או סנבלא קאימא או סאיר מא פי אלצ'יאע",
         "and burns a stack, or standing ears of grain, or the rest of what is in the fields"),
        ("שַׁלֵּם יְשַׁלֵּם הַמַּבְעִר אֶת-הַבְּעֵרָה",
         "פליסלם מא יגב פיה. אלמשעל אלאשעאל",
         "he who kindled the burning shall deliver what is due from him."),
    ],
    6: [
        ("כִּי-יִתֵּן אִישׁ אֶל-רֵעֵהוּ כֶּסֶף אוֹ-כֵלִים לִשְׁמֹר",
         "ואן דפע אנסאן לצאחבה. ורק או אניה ליחפצה לה",
         "And if a man entrusts to his fellow silver or vessels to keep for him"),
        ("וְגֻנַּב מִבֵּית הָאִישׁ", "פסרק ד'אלך מן מנזלה",
         "and that is stolen from his dwelling"),
        ("אִם-יִמָּצֵא הַגַּנָּב יְשַׁלֵּם שְׁנָיִם", "אן וגד אלסארק סלם את'נין",
         "if the thief is found, he shall deliver two."),
    ],
    7: [
        ("אִם-לֹא יִמָּצֵא הַגַּנָּב", "ואן לם יוגד אלסארק",
         "And if the thief is not found"),
        ("וְנִקְרַב בַּעַל-הַבַּיִת אֶל-הָאֱלֹהִים",
         "תקדם מולא אלמנזל אלי' אלחאכם",
         "the master of the dwelling shall come forward to the judge"),
        ("אִם-לֹא שָׁלַח יָדוֹ בִּמְלֶאכֶת רֵעֵהוּ",
         "וחלף אנה לם ימד ידה אלי' מאל צאחבה",
         "and swear that he did not put forth his hand to his fellow's property."),
    ],
    8: [
        ("עַל-כָּל-דְּבַר-פֶּשַׁע", "עלי' כל אמר יגחדה",
         "Regarding every matter he denies"),
        ("עַל-שׁוֹר עַל-חֲמוֹר עַל-שֶׂה עַל-שַׂלְמָה עַל-כָּל-אֲבֵדָה",
         "מן ת'ור אלי' חמאר. אלי' שאה ואלי' ת'וב ואלי' כל צ'אלה",
         "whether ox or donkey or sheep or garment or any lost thing"),
        ("אֲשֶׁר יֹאמַר כִּי-הוּא זֶה", "אן יקול הד'א הו",
         "if one says 'this is it,'"),
        ("עַד הָאֱלֹהִים יָבֹא דְּבַר-שְׁנֵיהֶם", "פאלי' אלחאכם ירפע אמרהמא",
         "the matter of the two of them shall be brought before the judge"),
        ("אֲשֶׁר יַרְשִׁיעֻן אֱלֹהִים יְשַׁלֵּם שְׁנַיִם לְרֵעֵהוּ",
         "פמן צ'למה אלחאכם. סלם את'נין לצאחבה",
         "and whoever the judge finds in the wrong shall deliver two to his fellow."),
    ],
    9: [
        ("כִּי-יִתֵּן אִישׁ אֶל-רֵעֵהוּ חֲמוֹר אוֹ-שׁוֹר אוֹ-שֶׂה וְכָל-בְּהֵמָה--לִשְׁמֹר",
         "ואן דפע אנסאן לצאחבה. חמאר או ת'ור או שאה. או שי מן סאיר אלבהאים ליחפצה",
         "And if a man entrusts to his fellow a donkey, or an ox, or a sheep, or anything of the rest of the beasts, to keep it"),
        ("וּמֵת אוֹ-נִשְׁבַּר אוֹ-נִשְׁבָּה", "פמאת. או אנכסר או סבי",
         "and it dies, or is injured, or is taken captive"),
        ("אֵין רֹאֶה", "בגיר ביינה", "with no clear witness"),
    ],
    10: [
        ("שְׁבֻעַת יְהוָה תִּהְיֶה בֵּין שְׁנֵיהֶם", "פימין אללה תפצל פי מא בינהמא",
         "an oath by God shall decide between the two of them"),
        ("אִם-לֹא שָׁלַח יָדוֹ בִּמְלֶאכֶת רֵעֵהוּ",
         "אנה לם ימד ידה אלי' מאל צאחבה",
         "that he did not put forth his hand to his fellow's property"),
        ("וְלָקַח בְּעָלָיו וְלֹא יְשַׁלֵּם", "ויקבלהא אלצאחב ולא יסלם שייא",
         "and the fellow shall accept it, and he shall deliver nothing."),
    ],
    11: [
        ("וְאִם-גָּנֹב יִגָּנֵב מֵעִמּוֹ", "ואן סרק מן ענדה",
         "And if it was stolen from his keeping"),
        ("יְשַׁלֵּם לִבְעָלָיו", "סלם לה", "he shall deliver to him."),
    ],
    12: [
        ("אִם-טָרֹף יִטָּרֵף", "ואן אפתרס", "And if it was torn by a beast"),
        ("יְבִאֵהוּ עֵד", "פליאת בשאהד", "let him bring a witness"),
        ("הַטְּרֵפָה לֹא יְשַׁלֵּם", "ולא יסלם אלפריסה",
         "and he shall not be liable for the torn animal."),
    ],
    13: [
        ("וְכִי-יִשְׁאַל אִישׁ מֵעִם רֵעֵהוּ", "ואן אסתעאר אנסאן. שיא מן צאחבה",
         "And if a man borrows something from his fellow"),
        ("וְנִשְׁבַּר אוֹ-מֵת", "פאנכסר או מאת", "and it is broken or dies"),
        ("בְּעָלָיו אֵין-עִמּוֹ", "וליס רבה מעה",
         "and its owner was not with him"),
        ("שַׁלֵּם יְשַׁלֵּם", "פליג'רמה", "he shall pay a penalty for it."),
    ],
    14: [
        ("אִם-בְּעָלָיו עִמּוֹ לֹא יְשַׁלֵּם", "ואן כאן רבה מעה פלא יג'רמה",
         "And if its owner was with him, he shall not pay a penalty"),
        ("אִם-שָׂכִיר הוּא בָּא בִּשְׂכָרוֹ", "ואן כאן אגירא. פקד מר באגרתה",
         "and if it was hired, it has already passed with its hire."),
    ],
    15: [
        ("וְכִי-יְפַתֶּה אִישׁ בְּתוּלָה אֲשֶׁר לֹא-אֹרָשָׂה",
         "ואן כ'דע רג'ל גאריה בכר. מא לם תמלך",
         "And if a man deceives a maiden who is a virgin, who has not yet been betrothed"),
        ("וְשָׁכַב עִמָּהּ", "פצ'אגעהא", "and lies with her"),
        ("מָהֹר יִמְהָרֶנָּה לּוֹ לְאִשָּׁה", "פלימהרהא ותכון לה זוגה",
         "he shall pay her bride-price, and she shall be his wife."),
    ],
    16: [
        ("אִם-מָאֵן יְמָאֵן אָבִיהָ לְתִתָּהּ לוֹ", "ואן אבא אביהא אן יזווגהא מנה",
         "And if her father refuses to give her to him in marriage"),
        ("כֶּסֶף יִשְׁקֹל כְּמֹהַר הַבְּתוּלֹת", "פליזן לה מן אלורק. כמהר אלאבכאר",
         "he shall weigh out for him in silver the bride-price of virgins."),
    ],
    17: [
        ("מְכַשֵּׁפָה לֹא תְחַיֶּה", "ואלסאחר פלא תסתבקה",
         "And the sorceress — do not let her live."),
    ],
    18: [
        ("כָּל-שֹׁכֵב עִם-בְּהֵמָה מוֹת יוּמָת",
         "ומן צ'אגע שייא מן אלבהאים פליקתל קתלא",
         "And whoever lies with any of the beasts shall be put to death."),
    ],
    19: [
        ("זֹבֵחַ לָאֱלֹהִים יָחֳרָם", "ומן ד'בח לאלמעבודאת פליתלף",
         "And whoever slaughters to the worshipped ones shall be destroyed"),
        ("בִּלְתִּי לַיהוָה לְבַדּוֹ", "אלא לאסם אללה וחדה",
         "except to the name of God alone."),
    ],
    20: [
        ("וְגֵר לֹא-תוֹנֶה וְלֹא תִלְחָצֶנּוּ", "ואלג'ריב פלא תג'בנה ולא תצ'גטה",
         "And the stranger — do not cheat him nor press him"),
        ("כִּי-גֵרִים הֱיִיתֶם בְּאֶרֶץ מִצְרָיִם",
         "פטאל מא כנתם ג'רבא פי בלד מצר",
         "for how long you were strangers in the land of Egypt."),
    ],
    21: [
        ("כָּל-אַלְמָנָה וְיָתוֹם לֹא תְעַנּוּן", "וכל ארמלה ויתים לא תצ'למון",
         "Every widow and orphan — do not wrong them."),
    ],
    22: [
        ("אִם-עַנֵּה תְעַנֶּה אֹתוֹ", "פאנך אן צ'למתה",
         "For if you wrong him"),
        ("כִּי אִם-צָעֹק יִצְעַק אֵלַי", "וצרך' אליי", "and he cries out to Me"),
        ("שָׁמֹעַ אֶשְׁמַע צַעֲקָתוֹ", "אגבתה ען צראכ'ה",
         "I shall answer him regarding his cry."),
    ],
    23: [
        ("וְחָרָה אַפִּי", "באן ישתד ג'צ'בי", "My anger shall intensify"),
        ("וְהָרַגְתִּי אֶתְכֶם בֶּחָרֶב", "ואקתלכם באלסיף",
         "and I shall kill you by the sword"),
        ("וְהָיוּ נְשֵׁיכֶם אַלְמָנוֹת", "פתציר נסאכם אראמלא",
         "and your wives shall become widows"),
        ("וּבְנֵיכֶם יְתֹמִים", "ובניכם יתאמא", "and your sons orphans."),
    ],
    24: [
        ("אִם-כֶּסֶף תַּלְוֶה אֶת-עַמִּי אֶת-הֶעָנִי עִמָּךְ",
         "ואן אקרצ'ת בעץ' קומי ורקא. לצ'עיף מעך",
         "And if you lend silver to some of My people — to the poor one who is with you"),
        ("לֹא-תִהְיֶה לוֹ כְּנֹשֶׁה", "פלא תכון לה כאלג'רים",
         "do not be to him like a creditor"),
        ("לֹא-תְשִׂימוּן עָלָיו נֶשֶׁךְ", "ולא תצייר עליה עיינה",
         "and do not impose upon him interest."),
    ],
    25: [
        ("אִם-חָבֹל תַּחְבֹּל שַׂלְמַת רֵעֶךָ", "ואן אסתרהנת ת'וב צאחבך",
         "And if you take your fellow's garment as a pledge"),
        ("עַד-בֹּא הַשֶּׁמֶשׁ תְּשִׁיבֶנּוּ לוֹ", "פענד מג'יב אלשמס רדה עליה",
         "return it to him at the setting of the sun."),
    ],
    26: [
        ("כִּי הִוא כְסוּתֹה לְבַדָּהּ", "אן כאנת הי כסותה וחדהא",
         "For it is his only covering"),
        ("הִוא שִׂמְלָתוֹ לְעֹרוֹ", "או הי ת'וב בדנה",
         "it is the garment of his body"),
        ("בַּמֶּה יִשְׁכָּב", "פבמא ד'א ינצ'גע", "with what shall he lie down?"),
        ("וְהָיָה כִּי-יִצְעַק אֵלַי וְשָׁמַעְתִּי", "פאנה אן צרך' אליי. סמעת לה",
         "And if he cries out to Me, I shall hear him"),
        ("כִּי-חַנּוּן אָנִי", "אני ראוף", "for I am compassionate."),
    ],
    27: [
        ("אֱלֹהִים לֹא תְקַלֵּל", "לא תשתמן חאכמא", "Do not revile a judge"),
        ("וְנָשִׂיא בְעַמְּךָ לֹא תָאֹר", "ושריף פי קומך לא תלענה",
         "and a noble among your people — do not curse him."),
    ],
    28: [
        ("מְלֵאָתְךָ וְדִמְעֲךָ לֹא תְאַחֵר", "וסלאפתך ורשחך לא תוכ'רהמא",
         "Your first-pressed yield and your first-drip offering — do not delay them"),
        ("בְּכוֹר בָּנֶיךָ תִּתֶּן-לִי", "ובכור בניך תעטיניהם",
         "the firstborn of your sons you shall give to Me."),
    ],
    29: [
        ("כֵּן-תַּעֲשֶׂה לְשֹׁרְךָ לְצֹאנֶךָ", "כד'אך תצנע בבקרך וג'נמך",
         "So shall you do with your cattle and your flock"),
        ("שִׁבְעַת יָמִים יִהְיֶה עִם-אִמּוֹ", "יקים סבעה איאם מע אמה",
         "it shall remain seven days with its mother"),
        ("בַּיּוֹם הַשְּׁמִינִי תִּתְּנוֹ-לִי", "ואליום אלת'אמן תעטיניה",
         "and on the eighth day you shall give it to Me."),
    ],
    30: [
        ("וְאַנְשֵׁי-קֹדֶשׁ תִּהְיוּן לִי", "ואנאס מקדסין כונו לי",
         "And be for Me a people who are consecrated."),
        ("וּבָשָׂר בַּשָּׂדֶה טְרֵפָה לֹא תֹאכֵלוּ",
         "וחיואן מפתרס פי אלצחרי לא תאכלו",
         "And an animal torn in the open country — do not eat it"),
        ("לַכֶּלֶב תַּשְׁלִכוּן אֹתוֹ", "בל לאלכלב אטרחוה",
         "but throw it to the dog."),
    ],
}
