"""Hand-authored alignment triples for Shemot chapter 17."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּסְעוּ כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל", "ת'ם רחל. גמאעה' בני אסראיל",
         "Then the congregation of the sons of Israel journeyed"),
        ("מִמִּדְבַּר-סִין", "מן בריה' סין", "from the wilderness of Sin"),
        ("לְמַסְעֵיהֶם--עַל-פִּי יְהוָה", "פי מראחלהם עלי' קול אללה",
         "in their stages according to the word of God"),
        ("וַיַּחֲנוּ בִּרְפִידִים", "ונזלו פי רפידים",
         "and they encamped in Rephidim"),
        ("וְאֵין מַיִם לִשְׁתֹּת הָעָם", "ולם יכון מאא ללקום לישרבון",
         "and there was no water for the people to drink"),
    ],
    2: [
        ("וַיָּרֶב הָעָם עִם-מֹשֶׁה", "פכ'אצם אלקום מוסי'",
         "And the people quarreled with Moses"),
        ("וַיֹּאמְרוּ תְּנוּ-לָנוּ מַיִם וְנִשְׁתֶּה", "וקאלו אעטנא מאא ונשרב",
         "and said: 'Give us water that we may drink."),
        ("וַיֹּאמֶר לָהֶם מֹשֶׁה מַה-תְּרִיבוּן עִמָּדִי",
         "קאל להם מוסי'. מא תכ'אצמוני",
         "Moses said to them: 'Why do you quarrel with me?"),
        ("מַה-תְּנַסּוּן אֶת-יְהוָה", "ומא תגרבון אללה",
         "And why do you put God to the test?"),
    ],
    3: [
        ("וַיִּצְמָא שָׁם הָעָם לַמַּיִם", "ולמא עטש ת'ם אלקום לאלמא",
         "And when the people thirsted there for water"),
        ("וַיָּלֶן הָעָם עַל-מֹשֶׁה", "תד'מרו עלי' מוסי'",
         "they murmured against Moses"),
        ("וַיֹּאמֶר לָמָּה זֶּה הֶעֱלִיתָנוּ מִמִּצְרַיִם",
         "וקאלו לה. לם אצעדתנא מן מצר",
         "and said to him: 'Why did you bring us up from Egypt"),
        ("לְהָמִית אֹתִי וְאֶת-בָּנַי וְאֶת-מִקְנַי בַּצָּמָא",
         "לתקתלנא ובנינא ומואשינא באלעטש",
         "to kill us and our children and our livestock with thirst?"),
    ],
    4: [
        ("וַיִּצְעַק מֹשֶׁה אֶל-יְהוָה לֵאמֹר", "פצרך' מוסי' אלי' אללה קאילא",
         "And Moses cried out to God, saying"),
        ("מָה אֶעֱשֶׂה לָעָם הַזֶּה", "מא אצנע בהולאי אלקום",
         "'What shall I do with these people?"),
        ("עוֹד מְעַט וּסְקָלֻנִי", "ען קליל ורגמוני",
         "In a little while they will stone me."),
    ],
    5: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה עֲבֹר לִפְנֵי הָעָם",
         "פקאל אללה לה. מר בין ידי אלקום",
         "And God said to him: 'Go before the people"),
        ("וְקַח אִתְּךָ מִזִּקְנֵי יִשְׂרָאֵל", "וכד' מעך מן משאיכ'הם",
         "and take with you some of their elders"),
        ("וּמַטְּךָ אֲשֶׁר הִכִּיתָ בּוֹ אֶת-הַיְאֹר",
         "ועצאך אלד'י צ'רבת בהא אלניל",
         "and your staff with which you struck the Nile"),
        ("קַח בְּיָדְךָ וְהָלָכְתָּ", "כד'הא בידך ואמץ'",
         "take it in your hand and go."),
    ],
    6: [
        ("הִנְנִי עֹמֵד לְפָנֶיךָ שָּׁם עַל-הַצּוּר בְּחֹרֵב",
         "האנא מוקף דלילא בין ידיך עלי' אלצואן פי חריב",
         "'Behold, I am placing a guide before you upon the flint at Horeb."),
        ("וְהִכִּיתָ בַצּוּר", "פאצ'רב אלצואן", "Strike the flint"),
        ("וְיָצְאוּ מִמֶּנּוּ מַיִם וְשָׁתָה הָעָם",
         "יכ'רג מנה מאא ישרבוה אלקום",
         "and water shall come out from it for the people to drink."),
        ("וַיַּעַשׂ כֵּן מֹשֶׁה", "פצנע כד'אך", "And he did so"),
        ("לְעֵינֵי זִקְנֵי יִשְׂרָאֵל", "בחצ'רה' שיוך' אל אסראיל",
         "in the presence of the elders of the house of Israel."),
    ],
    7: [
        ("וַיִּקְרָא שֵׁם הַמָּקוֹם מַסָּה וּמְרִיבָה",
         "פסמא ד'אלך אלמוצע. ד'ו אלמחנה ואלכצומה",
         "And he named that place the place of trial and quarreling"),
        ("עַל-רִיב בְּנֵי יִשְׂרָאֵל", "עלי' מא כ'אצם בני אסראיל",
         "on account of the quarrel of the sons of Israel"),
        ("וְעַל נַסֹּתָם אֶת-יְהוָה לֵאמֹר", "ואמתחנו אללה קאילין",
         "and their putting God to the test, saying"),
        ("הֲיֵשׁ יְהוָה בְּקִרְבֵּנוּ אִם-אָיִן",
         "הל מוגוד נור אללה פי מא ביננא אם לא",
         "'Is the light of God present among us, or not?"),
    ],
    8: [
        ("וַיָּבֹא עֲמָלֵק", "ת'ם גא עמלק", "Then Amalek came"),
        ("וַיִּלָּחֶם עִם-יִשְׂרָאֵל בִּרְפִידִם",
         "וחארב בני אסראיל פי רפידים",
         "and warred against the sons of Israel in Rephidim."),
    ],
    9: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-יְהוֹשֻׁעַ", "פקאל מוסי' ליהושע",
         "And Moses said to Joshua"),
        ("בְּחַר-לָנוּ אֲנָשִׁים", "אכ'תאר לנא רגאלא",
         "'Choose men for us"),
        ("וְצֵא הִלָּחֵם בַּעֲמָלֵק מָחָר", "ואכ'רג חארב עמלק. ג'דא",
         "and go out to fight Amalek — tomorrow."),
        ("אָנֹכִי נִצָּב עַל-רֹאשׁ הַגִּבְעָה", "אנא ואקף עלי' ראס אליפאע",
         "I shall be standing upon the top of the height"),
        ("וּמַטֵּה הָאֱלֹהִים בְּיָדִי", "ואלעצא אלתי אמר אללה בהא פי ידי",
         "and the staff which God commanded concerning it shall be in my hand."),
    ],
    10: [
        ("וַיַּעַשׂ יְהוֹשֻׁעַ כַּאֲשֶׁר אָמַר-לוֹ מֹשֶׁה",
         "פצנע יהושע. כמא קאל לה מוסי'",
         "And Joshua did as Moses had told him"),
        ("לְהִלָּחֵם בַּעֲמָלֵק", "אן יחארב עמלק", "to fight Amalek."),
        ("וּמֹשֶׁה אַהֲרֹן וְחוּר", "ומוסי' והרון וחור",
         "And Moses and Aaron and Hur"),
        ("עָלוּ רֹאשׁ הַגִּבְעָה", "צעדו אלי' ראס אליפאע",
         "went up to the top of the height."),
    ],
    11: [
        ("וְהָיָה כַּאֲשֶׁר יָרִים מֹשֶׁה יָדוֹ", "פכאן מוסי'. כמא ירפע ידה",
         "And it was so with Moses: whenever he raised his hand"),
        ("וְגָבַר יִשְׂרָאֵל", "יג'לב אל אסראיל",
         "the house of Israel prevailed"),
        ("וְכַאֲשֶׁר יָנִיחַ יָדוֹ", "וכמא יחטהא", "and whenever he lowered it"),
        ("וְגָבַר עֲמָלֵק", "יג'לב אל עמלק",
         "the house of Amalek prevailed."),
    ],
    12: [
        ("וִידֵי מֹשֶׁה כְּבֵדִים", "ולמא ת'קלתא ידי מוסי'",
         "And when Moses' hands grew heavy"),
        ("וַיִּקְחוּ-אֶבֶן וַיָּשִׂימוּ תַחְתָּיו וַיֵּשֶׁב עָלֶיהָ",
         "אכ'דו חגר. פציירוהא תחתה וגלס עליהא",
         "they took a stone and placed it beneath him, and he sat upon it"),
        ("וְאַהֲרֹן וְחוּר תָּמְכוּ בְיָדָיו", "והרון וחור יסנדא ידיה",
         "and Aaron and Hur supported his hands"),
        ("מִזֶּה אֶחָד וּמִזֶּה אֶחָד", "אחדהמא ימנה ואלאכ'ר יסרה",
         "one of them to the right and the other to the left"),
        ("וַיְהִי יָדָיו אֱמוּנָה עַד-בֹּא הַשָּׁמֶשׁ",
         "פכאנתא ידיה. מחצונתאן אלי' מג'יב אלשמס",
         "And so his two hands were held steady until the setting of the sun."),
    ],
    13: [
        ("וַיַּחֲלֹשׁ יְהוֹשֻׁעַ אֶת-עֲמָלֵק וְאֶת-עַמּוֹ",
         "פכדד יהושע. עמלק וקומה",
         "And Joshua wore down Amalek and his people"),
        ("לְפִי-חָרֶב", "בחד אלסיף", "with the edge of the sword."),
    ],
    14: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses"),
        ("כְּתֹב זֹאת זִכָּרוֹן בַּסֵּפֶר", "אכתב הד'ה ד'כר פי כתאב",
         "'Write this as a memorial in a book"),
        ("וְשִׂים בְּאָזְנֵי יְהוֹשֻׁעַ", "ואתלה עלי' יהושע",
         "and recite it to Joshua"),
        ("כִּי-מָחֹה אֶמְחֶה אֶת-זֵכֶר עֲמָלֵק מִתַּחַת הַשָּׁמָיִם",
         "פאני סאמחו ד'כר עמלק. מן תחת אלסמא",
         "for I shall blot out the remembrance of Amalek from beneath the sky."),
    ],
    15: [
        ("וַיִּבֶן מֹשֶׁה מִזְבֵּחַ", "פבנא מוסי' מד'בחא",
         "And Moses built an altar"),
        ("וַיִּקְרָא שְׁמוֹ יְהוָה נִסִּי", "וסמאה אללה עלמי",
         "and called it: 'God is my banner."),
    ],
    16: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("כִּי-יָד עַל-כֵּס יָהּ", "אן אלאזלי אקסם באלכרסי",
         "'The Eternal has sworn by the throne"),
        ("מִלְחָמָה לַיהוָה בַּעֲמָלֵק", "אן תכון ללה חרב פי עמלק",
         "that there shall be war belonging to God against Amalek"),
        ("מִדֹּר דֹּר", "גיל בעד גיל", "generation after generation."),
    ],
}
