"""Hand-authored alignment triples for Shemot chapter 3."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וּמֹשֶׁה הָיָה", "וכאן מוסי", "And Moses was"),
        ("רֹעֶה", "ירעא", "tending"),
        ("אֶת-צֹאן יִתְרוֹ", "ג'נם יתרו", "the flock of Jethro"),
        ("חֹתְנוֹ", "חמוה", "his father-in-law"),
        ("כֹּהֵן מִדְיָן", "אמאם מדין", "the imām of Midian"),
        ("וַיִּנְהַג אֶת-הַצֹּאן", "פסאקהא", "and he led it"),
        ("אַחַר הַמִּדְבָּר", "אלי' טרף אלברייה",
         "to the edge of the wilderness"),
        ("וַיָּבֹא", "חתא גא", "and came"),
        ("אֶל-הַר הָאֱלֹהִים", "אלי' גבל אללה", "to the mountain of God"),
        ("חֹרֵבָה", "אלי' חריב", "to Horeb"),
    ],
    2: [
        ("וַיֵּרָא מַלְאַךְ יְהוָה אֵלָיו", "פתגלא לה מלך אללה",
         "And the angel of God appeared to him"),
        ("בְּלַבַּת-אֵשׁ", "בצרים נאר", "in a flame of fire"),
        ("מִתּוֹךְ הַסְּנֶה", "מן וסט אלסנא",
         "from the midst of the thornbush"),
        ("וַיַּרְא", "פראי'", "And he saw"),
        ("וְהִנֵּה הַסְּנֶה בֹּעֵר בָּאֵשׁ", "אלסנא משתעל באלנאר",
         "and behold, the thornbush was blazing with fire"),
        ("וְהַסְּנֶה אֵינֶנּוּ אֻכָּל", "והו ליס יחתרק",
         "yet it was not being consumed"),
    ],
    3: [
        ("וַיֹּאמֶר מֹשֶׁה", "פקאל מוסי", "And Moses said"),
        ("אָסֻרָה-נָּא", "אמיל אלאן", "Let me turn aside now"),
        ("וְאֶרְאֶה", "ואנצ'ר", "and see"),
        ("אֶת-הַמַּרְאֶה הַגָּדֹל הַזֶּה", "הד'א אלמנצ'ר אלעגיב",
         "this wondrous sight"),
        ("מַדּוּעַ", "מא באל", "why"),
        ("לֹא-יִבְעַר הַסְּנֶה", "אלסנא לם יחתרק",
         "the thornbush is not burning"),
    ],
    4: [
        ("וַיַּרְא יְהוָה", "פעלם אללה", "And God knew"),
        ("כִּי סָר", "אנה קד מאל", "that he had turned aside"),
        ("לִרְאוֹת", "לינצ'ר", "to see"),
        ("וַיִּקְרָא אֵלָיו אֱלֹהִים", "פנאדאה", "and He called to him"),
        ("מִתּוֹךְ הַסְּנֶה", "מן אלסנא", "from the thornbush"),
        ("וַיֹּאמֶר", "וקאל", "and said"),
        ("מֹשֶׁה מֹשֶׁה", "יא מוסי' יא מוסי'", "Moses! Moses!"),
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("הִנֵּנִי", "לביך", "I am at your service"),
    ],
    5: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("אַל-תִּקְרַב הֲלֹם", "לא תתקדם אלי' ההנא",
         "Do not draw near hither"),
        ("שַׁל-נְעָלֶיךָ", "אנזע נעליך", "take off your sandals"),
        ("מֵעַל רַגְלֶיךָ", "ען רגליך", "from your feet"),
        ("כִּי הַמָּקוֹם", "פאן אלמוצ'ע", "for the place"),
        ("אֲשֶׁר אַתָּה עוֹמֵד עָלָיו", "אלד'י אנת ואקף עליה",
         "upon which you are standing"),
        ("אַדְמַת-קֹדֶשׁ הוּא", "מקדס", "is consecrated"),
    ],
    6: [
        ("וַיֹּאמֶר", "ת'ם קאל", "Then He said"),
        ("אָנֹכִי אֱלֹהֵי אָבִיךָ", "אנא אלאה אביך",
         "I am the God of your father"),
        ("אֱלֹהֵי אַבְרָהָם", "אלאה אברהים", "the God of Abraham"),
        ("אֱלֹהֵי יִצְחָק", "יצחק", "Isaac"),
        ("וֵאלֹהֵי יַעֲקֹב", "ויעקוב", "and Jacob"),
        ("וַיַּסְתֵּר מֹשֶׁה פָּנָיו", "פסתר מוסי וגהה",
         "And Moses covered his face"),
        ("כִּי יָרֵא", "אד' כ'אף", "for he was afraid"),
        ("מֵהַבִּיט אֶל-הָאֱלֹהִים", "אן ינצ'ר אלי' נור אללה",
         "to look upon the light of God"),
    ],
    7: [
        ("וַיֹּאמֶר יְהוָה", "וקאל", "And He said"),
        ("רָאֹה רָאִיתִי", "קד נצ'רת", "I have looked"),
        ("אֶת-עֳנִי עַמִּי", "לצ'עף קומי",
         "upon the affliction of my people"),
        ("אֲשֶׁר בְּמִצְרָיִם", "אלד'י במצר", "who are in Egypt"),
        ("וְאֶת-צַעֲקָתָם שָׁמַעְתִּי", "וסמעת צראכ'הם",
         "and I have heard their crying-out"),
        ("מִפְּנֵי נֹגְשָׂיו", "מן קבל גלאוזתהם",
         "because of their taskmasters"),
        ("כִּי יָדַעְתִּי אֶת-מַכְאֹבָיו", "ועלמת באוגאעהם",
         "and I have known their pains"),
    ],
    8: [
        ("וָאֵרֵד", "פתגלית", "So I have appeared"),
        ("לְהַצִּילוֹ", "לאכ'לצהם", "to rescue them"),
        ("מִיַּד מִצְרַיִם", "מן יד אלמצריון",
         "from the hand of the Egyptians"),
        ("וּלְהַעֲלֹתוֹ", "ואצעדהם", "and to bring them up"),
        ("מִן-הָאָרֶץ הַהִוא", "מן ד'אלך אלבלד", "out of that land"),
        ("אֶל-אֶרֶץ טוֹבָה וּרְחָבָה", "אלי' בלד גייד ואסע",
         "to a good and wide land"),
        ("אֶל-אֶרֶץ זָבַת חָלָב וּדְבָשׁ", "בלד יפיץ' אללבן ואלעסל",
         "a land flowing with milk and honey"),
        ("אֶל-מְקוֹם", "אלי' מוצ'ע", "to the place"),
        ("הַכְּנַעֲנִי", "אלכנעאניין", "of the Canaanites"),
        ("וְהַחִתִּי", "ואלחתיין", "and the Hittites"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("וְהַפְּרִזִּי", "ואלפרזיין", "and the Perizzites"),
        ("וְהַחִוִּי", "ואלחויין", "and the Hivites"),
        ("וְהַיְבוּסִי", "ואליבוסיין", "and the Jebusites"),
    ],
    9: [
        ("וְעַתָּה", "ואלאן", "And now"),
        ("הִנֵּה", "הודי'", "behold"),
        ("צַעֲקַת בְּנֵי-יִשְׂרָאֵל", "צראך' בני אסראיל",
         "the cry of the sons of Israel"),
        ("בָּאָה אֵלָי", "קד וצל. אליי", "has reached me"),
        ("וְגַם-רָאִיתִי", "וראית", "and I have seen"),
        ("אֶת-הַלַּחַץ", "אלצ'גט", "the oppression"),
        ("אֲשֶׁר מִצְרַיִם לֹחֲצִים אֹתָם", "אלד'י אלמצריון צ'אג'טוהם",
         "with which the Egyptians are oppressing them"),
    ],
    10: [
        ("וְעַתָּה לְכָה", "פתעאל אלאן", "So come now"),
        ("וְאֶשְׁלָחֲךָ", "אבעת' בך", "and I shall send you"),
        ("אֶל-פַּרְעֹה", "אלי' פרעון", "to Pharaoh"),
        ("וְהוֹצֵא", "ואכ'רג", "and bring out"),
        ("אֶת-עַמִּי", "קומי", "my people"),
        ("בְנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("מִמִּצְרָיִם", "מן מצר", "from Egypt"),
    ],
    11: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָאֱלֹהִים", "קאל מוסי בין ידי אללה",
         "And Moses said before God"),
        ("מִי אָנֹכִי", "מן אנא", "Who am I"),
        ("כִּי אֵלֵךְ אֶל-פַּרְעֹה", "חתא אמצ'י אלי' פרעון",
         "that I should go to Pharaoh"),
        ("וְכִי אוֹצִיא", "ואכ'רג", "and that I should bring out"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("מִמִּצְרָיִם", "מן מצר", "from Egypt"),
    ],
    12: [
        ("וַיֹּאמֶר", "קאל", "He said"),
        ("כִּי-אֶהְיֶה עִמָּךְ", "אנא אכון מעך", "I shall be with you"),
        ("וְזֶה-לְּךָ הָאוֹת", "והד'ה לך איה",
         "and this is the sign for you"),
        ("כִּי אָנֹכִי שְׁלַחְתִּיךָ", "באני בעת'ת בך",
         "that I have sent you"),
        ("בְּהוֹצִיאֲךָ אֶת-הָעָם מִמִּצְרַיִם",
         "אד'א אכ'רגת אלקום מן מצר",
         "when you have brought the people out of Egypt"),
        ("תַּעַבְדוּן אֶת-הָאֱלֹהִים", "אעבדו אללה",
         "you shall worship God"),
        ("עַל הָהָר הַזֶּה", "עלי הד'א אלגבל", "upon this mountain"),
    ],
    13: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָאֱלֹהִים", "קאל מוסי' בין ידי אללה",
         "And Moses said before God"),
        ("הִנֵּה אָנֹכִי בָא", "האנא צאיר", "Behold, I am going"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "אלי' בני אסראיל",
         "to the sons of Israel"),
        ("וְאָמַרְתִּי לָהֶם", "ואקול להם", "and I shall say to them"),
        ("אֱלֹהֵי אֲבוֹתֵיכֶם", "אלאה אבאיאכם",
         "The God of your fathers"),
        ("שְׁלָחַנִי אֲלֵיכֶם", "בעת'ני אליכם", "has sent me to you"),
        ("וְאָמְרוּ-לִי", "פאן סאלוני", "And they shall ask me"),
        ("מַה-שְּׁמוֹ", "מא אסמה", "What is His name"),
        ("מָה אֹמַר אֲלֵהֶם", "מא אקול להם", "What shall I say to them"),
    ],
    14: [
        ("וַיֹּאמֶר אֱלֹהִים אֶל-מֹשֶׁה", "קאל לה", "He said to him"),
        ("אֶהְיֶה אֲשֶׁר אֶהְיֶה", "אלאזלי אלד'י לא יזול",
         "The Eternal who never ceases"),
        ("וַיֹּאמֶר", "ת'ם קאל", "Then He said"),
        ("כֹּה תֹאמַר", "כד'א קל", "Thus shall you say"),
        ("לִבְנֵי יִשְׂרָאֵל", "לבני אסראיל", "to the sons of Israel"),
        ("אֶהְיֶה", "אלאזלי", "The Eternal"),
        ("שְׁלָחַנִי אֲלֵיכֶם", "בעת'ני אליכם", "has sent me to you"),
    ],
    15: [
        ("וַיֹּאמֶר עוֹד אֱלֹהִים אֶל-מֹשֶׁה", "וקאל לה איצ'א",
         "And He said to him further"),
        ("כֹּה-תֹאמַר", "כד'א קל", "Thus shall you say"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "לבני אסראיל",
         "to the sons of Israel"),
        ("יְהוָה", "אללה", "The Lord"),
        ("אֱלֹהֵי אֲבֹתֵיכֶם", "אלאה אבאיכם", "the God of your fathers"),
        ("אֱלֹהֵי אַבְרָהָם", "אלאה אברהים", "the God of Abraham"),
        ("אֱלֹהֵי יִצְחָק", "אלאה יצחק", "the God of Isaac"),
        ("וֵאלֹהֵי יַעֲקֹב", "ואלאה יעקב", "and the God of Jacob"),
        ("שְׁלָחַנִי אֲלֵיכֶם", "בעת'ני אליכם", "has sent me to you"),
        ("זֶה-שְּׁמִי לְעֹלָם", "הד'א אסמי אלי' אלדהר",
         "This is My name forever"),
        ("וְזֶה זִכְרִי", "והד'א ד'כרי", "and this is My memorial"),
        ("לְדֹר דֹּר", "אלי' גיל ואגיאל",
         "unto generation upon generation"),
    ],
    16: [
        ("לֵךְ", "אמץ'", "Go"),
        ("וְאָסַפְתָּ אֶת-זִקְנֵי יִשְׂרָאֵל", "ואגמע שיוך' בני אסראיל",
         "and gather the elders of the sons of Israel"),
        ("וְאָמַרְתָּ אֲלֵהֶם", "וקל להם", "and say to them"),
        ("יְהוָה", "אללה", "The Lord"),
        ("אֱלֹהֵי אֲבֹתֵיכֶם", "אלאה אבאיכם", "the God of your fathers"),
        ("נִרְאָה אֵלַי", "תגלא לי", "has appeared to me"),
        ("אֱלֹהֵי אַבְרָהָם", "אלאה אברהים", "the God of Abraham"),
        ("יִצְחָק", "יצחק", "Isaac"),
        ("וְיַעֲקֹב", "ויעקוב", "and Jacob"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("פָּקֹד פָּקַדְתִּי אֶתְכֶם", "קד ד'כרתכם",
         "I have remembered you"),
        ("וְאֶת-הֶעָשׂוּי לָכֶם בְּמִצְרָיִם", "ומא צנע בכם במצר",
         "and what has been done to you in Egypt"),
    ],
    17: [
        ("וָאֹמַר", "פקלת", "And I have said"),
        ("אַעֲלֶה אֶתְכֶם", "אצעדכם", "I shall bring you up"),
        ("מֵעֳנִי מִצְרַיִם", "מן עד'אב אלמצריון",
         "from the torment of the Egyptians"),
        ("אֶל-אֶרֶץ", "אלי' מוצ'ע", "to the place"),
        ("הַכְּנַעֲנִי", "אלכנעאניין", "of the Canaanites"),
        ("וְהַחִתִּי", "ואלחתיין", "and the Hittites"),
        ("וְהָאֱמֹרִי", "ואלאמוריין", "and the Amorites"),
        ("וְהַפְּרִזִּי", "ואלפרזיין", "and the Perizzites"),
        ("וְהַחִוִּי", "ואלחויין", "and the Hivites"),
        ("וְהַיְבוּסִי", "ואליבוסיין", "and the Jebusites"),
        ("אֶל-אֶרֶץ זָבַת חָלָב וּדְבָשׁ", "אלי' בלד יפיץ' לבנא ועסלא",
         "to a land flowing with milk and honey"),
    ],
    18: [
        ("וְשָׁמְעוּ לְקֹלֶךָ", "פאד'א קבלו מנך",
         "And when they accept from you"),
        ("וּבָאתָ", "אדכל", "you shall enter"),
        ("אַתָּה", "אנת", "you"),
        ("וְזִקְנֵי יִשְׂרָאֵל", "ושיוך' בני אסראיל",
         "and the elders of the sons of Israel"),
        ("אֶל-מֶלֶךְ מִצְרַיִם", "אלי' מלך מצר",
         "to the king of Egypt"),
        ("וַאֲמַרְתֶּם אֵלָיו", "וקולו לה", "and you shall say to him"),
        ("יְהוָה", "אללה", "The Lord"),
        ("אֱלֹהֵי הָעִבְרִיִּים", "אלאה אלעבראניין",
         "the God of the Hebrews"),
        ("נִקְרָה עָלֵינוּ", "ואפאנא אמרה",
         "has caused His decree to come upon us"),
        ("וְעַתָּה", "פאלאן", "So now"),
        ("נֵלְכָה-נָּא דֶּרֶךְ שְׁלֹשֶׁת יָמִים",
         "נסיר מסאפה' ת'לאתה' איאם",
         "let us journey a distance of three days"),
        ("בַּמִּדְבָּר", "פי אלבר", "into the wilderness"),
        ("וְנִזְבְּחָה לַיהוָה אֱלֹהֵינוּ", "ונד'בח ללה רבנא",
         "and let us offer sacrifice to the Lord our God"),
    ],
    19: [
        ("וַאֲנִי יָדַעְתִּי", "ואנא אעלם", "But I know"),
        ("כִּי לֹא-יִתֵּן אֶתְכֶם מֶלֶךְ מִצְרַיִם",
         "אן מלך מצר לא ידעכם",
         "that the king of Egypt will not let you"),
        ("לַהֲלֹךְ", "אן תמצ'ו", "go"),
        ("וְלֹא בְּיָד חֲזָקָה", "ולא ביד ואחדה שדידה",
         "and not [even] under a single strong hand"),
    ],
    20: [
        ("וְשָׁלַחְתִּי אֶת-יָדִי", "פאבעת' בגמיע אפאתי",
         "So I shall send forth all my plagues"),
        ("וְהִכֵּיתִי אֶת-מִצְרַיִם", "ואצר'ב אלמצריון",
         "and shall strike the Egyptians"),
        ("בְּכֹל נִפְלְאֹתַי", "באעגובאתי", "with my wonders"),
        ("אֲשֶׁר אֶעֱשֶׂה בְּקִרְבּוֹ", "אלד'י אצנעהא פי מא בינהם",
         "which I shall do among them"),
        ("וְאַחֲרֵי-כֵן", "ובעד ד'אלך", "and after that"),
        ("יְשַׁלַּח אֶתְכֶם", "יטלקכם", "he shall let you go"),
    ],
    21: [
        ("וְנָתַתִּי", "ואעטי", "And I shall give"),
        ("אֶת-חֵן הָעָם-הַזֶּה", "אלקום חצ'אא", "this people favor"),
        ("בְּעֵינֵי מִצְרָיִם", "ענד אלמצריון",
         "in the eyes of the Egyptians"),
        ("וְהָיָה כִּי תֵלֵכוּן", "פאד'א מצ'יתם",
         "so it shall be, when you go"),
        ("לֹא תֵלְכוּ רֵיקָם", "לא תמצ'ון פרג'א",
         "you shall not go empty-handed"),
    ],
    22: [
        ("וְשָׁאֲלָה אִשָּׁה", "בל תסתוהב אלאמראה",
         "Rather, each woman shall ask as a gift"),
        ("מִשְּׁכֶנְתָּהּ", "מן מסאכנתהא", "from her [woman-]neighbor"),
        ("וּמִגָּרַת בֵּיתָהּ", "ומן גארתהא",
         "and from the dweller in her house"),
        ("כְּלֵי-כֶסֶף", "אניה' פצ'ה", "vessels of silver"),
        ("וּכְלֵי זָהָב", "ואניה' ד'הב", "and vessels of gold"),
        ("וּשְׂמָלֹת", "ות'יאבא", "and garments"),
        ("וְשַׂמְתֶּם", "ותציירוהא", "and you shall set them"),
        ("עַל-בְּנֵיכֶם", "עלי' בניכם", "upon your sons"),
        ("וְעַל-בְּנֹתֵיכֶם", "ובנאתכם", "and upon your daughters"),
        ("וְנִצַּלְתֶּם אֶת-מִצְרָיִם", "ותנתספו אלמצריון",
         "and you shall divest the Egyptians"),
    ],
}
