"""Hand-authored alignment triples for Shemot chapter 21."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאֵלֶּה הַמִּשְׁפָּטִים", "והד'א אלאחכאם", "And these are the ordinances"),
        ("אֲשֶׁר תָּשִׂים לִפְנֵיהֶם", "אלתי תתלוהא עליהם",
         "which you shall recite to them"),
    ],
    2: [
        ("כִּי תִקְנֶה עֶבֶד עִבְרִי", "קל להם אד'א אבתעת עבדא עבראניה",
         "Say to them: If you purchase a Hebrew slave"),
        ("שֵׁשׁ שָׁנִים יַעֲבֹד", "פליכ'דמך סת סנין", "he shall serve you six years"),
        ("וּבַשְּׁבִעִת--יֵצֵא לַחָפְשִׁי חִנָּם", "ופי אלסאבעה. יכ'רג חרא מגאנא",
         "and in the seventh, he shall go out free, without payment"),
    ],
    3: [
        ("אִם-בְּגַפּוֹ יָבֹא בְּגַפּוֹ יֵצֵא", "אן דכ'ל עזבא כ'רג עזבא",
         "If he entered single, he shall go out single"),
        ("אִם-בַּעַל אִשָּׁה הוּא וְיָצְאָה אִשְׁתּוֹ עִמּוֹ",
         "ואן כאן ד'ו זוגה. כ'רגת זוגתה מעה",
         "and if he was possessed of a wife, his wife shall go out with him"),
    ],
    4: [
        ("אִם-אֲדֹנָיו יִתֶּן-לוֹ אִשָּׁה", "ואן זווגה מולאה באמראה",
         "And if his master gave him a woman in marriage"),
        ("וְיָלְדָה-לוֹ בָנִים אוֹ בָנוֹת", "פולדת לה בנין או בנאת",
         "and she bore him sons or daughters"),
        ("הָאִשָּׁה וִילָדֶיהָ תִּהְיֶה לַאדֹנֶיהָ", "פאלאמראה ואולאדהא. יכונו למולאהא",
         "the woman and her children shall belong to his master"),
        ("וְהוּא יֵצֵא בְגַפּוֹ", "והו יכ'רג' עזבא", "and he shall go out single"),
    ],
    5: [
        ("וְאִם-אָמֹר יֹאמַר הָעֶבֶד", "ואן קאל אלעבד", "And if the slave says"),
        ("אָהַבְתִּי אֶת-אֲדֹנִי", "קד אחבבת מולאי", "I have come to love my master"),
        ("אֶת-אִשְׁתִּי וְאֶת-בָּנָי", "וזוגתי ובניי", "and my wife and my children"),
        ("לֹא אֵצֵא חָפְשִׁי", "לא אכ'רג חרא", "I will not go out free"),
    ],
    6: [
        ("וְהִגִּישׁוֹ אֲדֹנָיו אֶל-הָאֱלֹהִים", "פליקדמה מולאה אלי' אלחאכם",
         "then his master shall bring him before the judge"),
        ("וְהִגִּישׁוֹ אֶל-הַדֶּלֶת אוֹ אֶל-הַמְּזוּזָה",
         "ויקדמה אלי' אלמצראע. ואלי' כ'די אלבאב",
         "and shall bring him to the door-leaf and to the doorposts"),
        ("וְרָצַע אֲדֹנָיו אֶת-אָזְנוֹ בַּמַּרְצֵעַ", "ויסם אד'נה במיסאם",
         "and shall mark his ear with a branding iron"),
        ("וַעֲבָדוֹ לְעֹלָם", "ויכ'דמה אלי' אלדהר", "and he shall serve him forever"),
    ],
    7: [
        ("וְכִי-יִמְכֹּר אִישׁ אֶת-בִּתּוֹ לְאָמָה", "ואן באע רגל אבנתה לאמה",
         "And if a man sells his daughter as a maidservant"),
        ("לֹא תֵצֵא כְּצֵאת הָעֲבָדִים", "פלא תכ'רג ככ'רוג אלעביד",
         "she shall not go out as the going-out of the male slaves"),
    ],
    8: [
        ("אִם-רָעָה בְּעֵינֵי אֲדֹנֶיהָ", "אן קבחת ענד מולאהא",
         "If she is displeasing to her master"),
        ("אֲשֶׁר-לא (לוֹ) יְעָדָהּ--וְהֶפְדָּהּ", "אן יתזווג בהא פליפדהא",
         "who had intended to marry her, he shall redeem her"),
        ("לְעַם נָכְרִי לֹא-יִמְשֹׁל לְמָכְרָהּ", "ולבעץ' אלקום ג'ריב. לא יתסלט אן יביעהא",
         "he has no power to sell her to some other person who is a stranger to her"),
        ("בְּבִגְדוֹ-בָהּ", "אד' ג'דר בהא", "since he has been faithless to her"),
    ],
    9: [
        ("וְאִם-לִבְנוֹ יִיעָדֶנָּה", "ואן זווגהא לאבנה", "And if he betroths her to his son"),
        ("כְּמִשְׁפַּט הַבָּנוֹת יַעֲשֶׂה-לָּהּ", "פכסירה' אלבנאת יצנע בהא",
         "he shall deal with her according to the custom due to daughters"),
    ],
    10: [
        ("אִם-אַחֶרֶת יִקַּח-לוֹ", "ואן תזווג באכ'רא", "And if he marries another"),
        ("שְׁאֵרָהּ כְּסוּתָהּ וְעֹנָתָהּ", "פטעאמהא. וכסותהא ואוקאתהא",
         "her food, her clothing, and her appointed times"),
        ("לֹא יִגְרָע", "לא ינקצהא", "he shall not diminish"),
    ],
    11: [
        ("וְאִם-שְׁלָשׁ-אֵלֶּה--לֹא יַעֲשֶׂה לָהּ", "ואן לם יצנע בהא ואחדה מן הד'א אלת'לאת'",
         "And if he does not do for her one of these three things"),
        ("וְיָצְאָה חִנָּם אֵין כָּסֶף", "פלתכ'רג מגאנא בלא ת'מן",
         "then she shall go out without payment, without price"),
    ],
    12: [
        ("מַכֵּה אִישׁ וָמֵת", "ומן צ'רב אנסאן וקתלה",
         "And whoever strikes a person and kills him"),
        ("מוֹת יוּמָת", "פליקתל קתלא", "shall be put to death"),
    ],
    13: [
        ("וַאֲשֶׁר לֹא צָדָה", "ואן לם יעתמד", "But if he did not intend it"),
        ("וְהָאֱלֹהִים אִנָּה לְיָדוֹ", "אן אללה אוצל פי אמרה",
         "rather God brought it about in His decree"),
        ("וְשַׂמְתִּי לְךָ מָקוֹם אֲשֶׁר יָנוּס שָׁמָּה", "אני אצייר לך מוצ'עא. יהרב אליה",
         "I shall designate for you a place to which he may flee"),
    ],
    14: [
        ("וְכִי-יָזִד אִישׁ עַל-רֵעֵהוּ לְהָרְגוֹ בְעָרְמָה",
         "ואן אתקח אנסאן. עלי' צאחבה פקתלה בכ'בת'",
         "And if a man acts presumptuously against his fellow and kills him by stealth"),
        ("מֵעִם מִזְבְּחִי תִּקָּחֶנּוּ לָמוּת", "חתי מן ענד מד'בחי כ'דה ואקתלה",
         "even from beside My altar take him and put him to death"),
    ],
    15: [
        ("וּמַכֵּה אָבִיו וְאִמּוֹ מוֹת יוּמָת", "ומן צ'רב אביה ואמה פליקתל קתלא",
         "And whoever strikes his father or his mother shall be put to death"),
    ],
    16: [
        ("וְגֹנֵב אִישׁ וּמְכָרוֹ", "ומן סרק נפסא מן בני אסראיל פבאעה",
         "And whoever kidnaps a person from the sons of Israel and sells him"),
        ("וְנִמְצָא בְיָדוֹ מוֹת יוּמָת", "או וגד בידה פליקתל קתלא",
         "or is found with him in his possession, shall be put to death"),
    ],
    17: [
        ("וּמְקַלֵּל אָבִיו וְאִמּוֹ מוֹת יוּמָת", "ומן שתם אביה ואמה פליקתל קתלא",
         "And whoever curses his father or his mother shall be put to death"),
    ],
    18: [
        ("וְכִי-יְרִיבֻן אֲנָשִׁים", "ואד'א תכ'אצם אנאס", "And when people quarrel"),
        ("וְהִכָּה-אִישׁ אֶת-רֵעֵהוּ בְּאֶבֶן אוֹ בְאֶגְרֹף",
         "וצ'רב אחדהמא צאחבה. בחגר או בשאדך'",
         "and one of them strikes his fellow with a stone or with a wounding object"),
        ("וְלֹא יָמוּת וְנָפַל לְמִשְׁכָּב", "ולא ימות בל וקע עלי' אלפראש",
         "and he does not die but takes to his bed"),
    ],
    19: [
        ("אִם-יָקוּם וְהִתְהַלֵּךְ בַּחוּץ עַל-מִשְׁעַנְתּוֹ",
         "פאן הו קאם. ומשא פי אלסוק עלי' וכאיה לנפסה",
         "if he rises and walks about in the market on his own supports"),
        ("וְנִקָּה הַמַּכֶּה", "פקד ברי' אלצ'ארב",
         "then the one who struck him is acquitted"),
        ("רַק שִׁבְתּוֹ יִתֵּן", "עדא עטלתה. יעטיה",
         "except for his loss of work, which he shall give him"),
        ("וְרַפֹּא יְרַפֵּא", "ועלאגא יעאלגה", "and for medical treatment he shall treat him"),
    ],
    20: [
        ("וְכִי-יַכֶּה אִישׁ אֶת-עַבְדּוֹ אוֹ אֶת-אֲמָתוֹ בַּשֵּׁבֶט",
         "ואן צ'רב אנסאן עבדה. או אמתה בקצ'יב",
         "And if a person strikes his slave or his maidservant with a rod"),
        ("וּמֵת תַּחַת יָדוֹ", "ומאת תחת ידה", "and he dies under his hand"),
        ("נָקֹם יִנָּקֵם", "פליקאד בה", "he shall be penalized for him"),
    ],
    21: [
        ("אַךְ אִם-יוֹם אוֹ יוֹמַיִם יַעֲמֹד", "ואן אקאם יום או יומין",
         "But if he survives a day or two days"),
        ("לֹא יֻקַּם כִּי כַסְפּוֹ הוּא", "פלא יקאד בה לאנה מאלה",
         "he shall not be penalized for him, for he is his property"),
    ],
    22: [
        ("וְכִי-יִנָּצוּ אֲנָשִׁים", "ואן תנאצא אנאס", "And if people struggle"),
        ("וְנָגְפוּ אִשָּׁה הָרָה", "פצדמו אמראה חאמל",
         "and they strike a pregnant woman"),
        ("וְיָצְאוּ יְלָדֶיהָ", "וכ'רג אולאדהא", "and her child comes out"),
        ("וְלֹא יִהְיֶה אָסוֹן", "ולם תכון מנייה", "and there is no fatality"),
        ("עָנוֹשׁ יֵעָנֵשׁ כַּאֲשֶׁר יָשִׁית עָלָיו בַּעַל הָאִשָּׁה",
         "פליג'רם אלצאדם כמא ילזמה בעלהא",
         "the one who struck her shall be fined as her husband requires of him"),
        ("וְנָתַן בִּפְלִלִים", "ויעטיה באנצאף", "and he shall give it by fair assessment"),
    ],
    23: [
        ("וְאִם-אָסוֹן יִהְיֶה", "ואן תכון מנייה", "But if there is a fatality"),
        ("וְנָתַתָּה נֶפֶשׁ תַּחַת נָפֶשׁ", "ואגעל נפסא בדל נפסא",
         "then impose a life in place of a life"),
    ],
    24: [
        ("עַיִן תַּחַת עַיִן", "ודיה' עין בדל עין", "and the blood-price of an eye in place of an eye"),
        ("שֵׁן תַּחַת שֵׁן", "וסן בדל סן", "and a tooth in place of a tooth"),
        ("יָד תַּחַת יָד", "ויד בדל יד", "and a hand in place of a hand"),
        ("רֶגֶל תַּחַת רָגֶל", "ורגל בדל רגל", "and a foot in place of a foot"),
    ],
    25: [
        ("כְּוִיָּה תַּחַת כְּוִיָּה", "וכי בדל כי", "and a burn in place of a burn"),
        ("פֶּצַע תַּחַת פָּצַע", "ושגה בדל שגה", "and a gash in place of a gash"),
        ("חַבּוּרָה תַּחַת חַבּוּרָה", "וגראחה בדל גראחה", "and a wound in place of a wound"),
    ],
    26: [
        ("וְכִי-יַכֶּה אִישׁ אֶת-עֵין עַבְדּוֹ אוֹ-אֶת-עֵין אֲמָתוֹ",
         "ואן צ'רב אנסאן עין עבדה. או עין אמתה",
         "And if a person strikes the eye of his slave or the eye of his maidservant"),
        ("וְשִׁחֲתָהּ", "פאד'הבהא", "and destroys it"),
        ("לַחָפְשִׁי יְשַׁלְּחֶנּוּ תַּחַת עֵינוֹ", "פליטלקה חרא בדל עינה",
         "he shall set him free as a free person in place of his eye"),
    ],
    27: [
        ("וְאִם-שֵׁן עַבְדּוֹ אוֹ-שֵׁן אֲמָתוֹ יַפִּיל",
         "ואן טרח סן עבדה. או סן אמתה",
         "And if he knocks out the tooth of his slave or the tooth of his maidservant"),
        ("לַחָפְשִׁי יְשַׁלְּחֶנּוּ תַּחַת שִׁנּוֹ", "פליטלקה חרא בדל סנה",
         "he shall set him free as a free person in place of his tooth"),
    ],
    28: [
        ("וְכִי-יִגַּח שׁוֹר אֶת-אִישׁ אוֹ אֶת-אִשָּׁה וָמֵת",
         "ואן נטח תור. רגל או אמראה וקתלה",
         "And if an ox gores a man or a woman and kills him"),
        ("סָקוֹל יִסָּקֵל הַשּׁוֹר", "פלירגם אלת'ור", "the ox shall be stoned"),
        ("וְלֹא יֵאָכֵל אֶת-בְּשָׂרוֹ", "ולא יוכל לחמה", "and its flesh shall not be eaten"),
        ("וּבַעַל הַשּׁוֹר נָקִי", "ורב אלת'ור ברי", "but the owner of the ox is clear"),
    ],
    29: [
        ("וְאִם שׁוֹר נַגָּח הוּא מִתְּמֹל שִׁלְשֹׁם", "ואן כאן ת'ור נטאח מן אמס ומא קבלה",
         "But if the ox was a habitual gorer from yesterday and the day before"),
        ("וְהוּעַד בִּבְעָלָיו וְלֹא יִשְׁמְרֶנּוּ", "ונושד צאחבה ולם יחפצה",
         "and its owner was warned but did not guard it"),
        ("וְהֵמִית אִישׁ אוֹ אִשָּׁה", "וקתל רגל או אמראה",
         "and it kills a man or a woman"),
        ("הַשּׁוֹר יִסָּקֵל", "פלירגם אלת'ור", "the ox shall be stoned"),
        ("וְגַם-בְּעָלָיו יוּמָת", "ויקתל צאחבה איצ'א", "and its owner shall also be put to death"),
    ],
    30: [
        ("אִם-כֹּפֶר יוּשַׁת עָלָיו", "ואן אלזם דיה", "If a blood-price is imposed upon him"),
        ("וְנָתַן פִּדְיֹן נַפְשׁוֹ", "פליעט פדא נפסה", "he shall give the redemption of his life"),
        ("כְּכֹל אֲשֶׁר-יוּשַׁת עָלָיו", "גמיע מא ילזמה", "all that is imposed upon him"),
    ],
    31: [
        ("אוֹ-בֵן יִגָּח אוֹ-בַת יִגָּח", "ואן נטח אבן או אבנה",
         "And if it gores a son or a daughter"),
        ("כַּמִּשְׁפָּט הַזֶּה יֵעָשֶׂה לּוֹ", "פליצנע בה מת'ל הד'א אלחכם",
         "the same ordinance shall be done to it"),
    ],
    32: [
        ("אִם-עֶבֶד יִגַּח הַשּׁוֹר אוֹ אָמָה", "פאן נטח עבד או אמה",
         "If the ox gores a slave or a maidservant"),
        ("כֶּסֶף שְׁלֹשִׁים שְׁקָלִים יִתֵּן לַאדֹנָיו",
         "פליעט מולאה ת'לאתין מת'קאל פצה",
         "he shall give their master thirty shekels of silver"),
        ("וְהַשּׁוֹר יִסָּקֵל", "וירגם אלת'ור", "and the ox shall be stoned"),
    ],
    33: [
        ("וְכִי-יִפְתַּח אִישׁ בּוֹר", "ואן כשף אנסאן בירא", "And if a person uncovers a pit"),
        ("אוֹ כִּי-יִכְרֶה אִישׁ בֹּר--וְלֹא יְכַסֶּנּוּ", "או כרא בירא ולם יג'טיה",
         "or digs a pit and does not cover it"),
        ("וְנָפַל-שָׁמָּה שּׁוֹר אוֹ חֲמוֹר", "פוקע פיה ת'ור או חמאר",
         "and an ox or a donkey falls into it"),
    ],
    34: [
        ("בַּעַל הַבּוֹר יְשַׁלֵּם כֶּסֶף יָשִׁיב לִבְעָלָיו",
         "פליג'רם צאחב אלביר ת'מנה. וירדה אלי' רבה",
         "the owner of the pit shall pay its price and restore it to its owner"),
        ("וְהַמֵּת יִהְיֶה-לּוֹ", "ואלמיית יכון לה", "and the dead animal shall be his"),
    ],
    35: [
        ("וְכִי-יִגֹּף שׁוֹר-אִישׁ אֶת-שׁוֹר רֵעֵהוּ וָמֵת",
         "ואן צדם ת'ור אנסאן. ת'ור צאחבה ומאת",
         "And if one man's ox strikes his fellow's ox and it dies"),
        ("וּמָכְרוּ אֶת-הַשּׁוֹר הַחַי וְחָצוּ אֶת-כַּסְפּוֹ",
         "פליביעו אלת'ור אלחי ויקתסמו ת'מנה",
         "they shall sell the living ox and divide its price"),
        ("וְגַם אֶת-הַמֵּת יֶחֱצוּן", "ואיצ'א אלמיית יקתסמונה",
         "and the dead one they shall also divide"),
    ],
    36: [
        ("אוֹ נוֹדַע כִּי שׁוֹר נַגָּח הוּא מִתְּמוֹל שִׁלְשֹׁם",
         "פאן ערף. אנה ת'ור נטאח מן אמס ומא קבלה",
         "But if it was known that it was a habitual gorer from yesterday and the day before"),
        ("וְלֹא יִשְׁמְרֶנּוּ בְּעָלָיו", "ולם יחפצה צאחבה",
         "and its owner did not guard it"),
        ("שַׁלֵּם יְשַׁלֵּם שׁוֹר תַּחַת הַשּׁוֹר", "פליסלם ת'ורא בדל ת'ורה",
         "he shall deliver an ox in place of his ox"),
        ("וְהַמֵּת יִהְיֶה-לּוֹ", "ואלמיית יכון לה", "and the dead one shall be his"),
    ],
    37: [
        ("כִּי יִגְנֹב-אִישׁ שׁוֹר אוֹ-שֶׂה", "ואן סרק אנסאן ת'ור או שאה",
         "And if a person steals an ox or a sheep"),
        ("וּטְבָחוֹ אוֹ מְכָרוֹ", "פד'בחה או באעה", "and slaughters it or sells it"),
        ("חֲמִשָּׁה בָקָר יְשַׁלֵּם תַּחַת הַשּׁוֹר",
         "פליסלם בדל אלת'ור כ'מסה",
         "he shall deliver five in place of the ox"),
        ("וְאַרְבַּע-צֹאן תַּחַת הַשֶּׂה", "ובדל אלשאה ארבעה",
         "and four in place of the sheep"),
    ],
}
