"""Hand-authored alignment triples for Shemot chapter 39."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וּמִן-הַתְּכֵלֶת וְהָאַרְגָּמָן וְתוֹלַעַת הַשָּׁנִי עָשׂוּ בִגְדֵי-שְׂרָד לְשָׁרֵת בַּקֹּדֶשׁ",
         "ומן אלאסמאנגון ואלארגואן ואלצבג' אלקרמז. צנעו ת'יאב אלושי לאלכ'דמה פי אלקדס",
         "And from the blue and the purple and the scarlet dye, they made embroidered garments for service in the sanctuary"),
        ("וַיַּעֲשׂוּ אֶת-בִּגְדֵי הַקֹּדֶשׁ אֲשֶׁר לְאַהֲרֹן",
         "וצנעו ת'יאב אלקדס אלד'י להרון",
         "and they made the sacred garments which are for Aaron"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    2: [
        ("וַיַּעַשׂ אֶת-הָאֵפֹד", "וצנע אלצדרה", "And he made the ephod"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי--וְשֵׁשׁ מָשְׁזָר",
         "מן ד'הב ואסמאנגון וארגואן. וצבג' קרמז ועשר משזור",
         "of gold, and blue, and purple, and scarlet dye, and twisted fine linen."),
    ],
    3: [
        ("וַיְרַקְּעוּ אֶת-פַּחֵי הַזָּהָב וְקִצֵּץ פְּתִילִם",
         "וד'אלך באן ארקו אלצפאיח אלד'הב וקצוהא סלוכא",
         "And that was by beating out the sheets of gold thin, and cutting them into threads"),
        ("לַעֲשׂוֹת בְּתוֹךְ הַתְּכֵלֶת וּבְתוֹךְ הָאַרְגָּמָן וּבְתוֹךְ תּוֹלַעַת הַשָּׁנִי וּבְתוֹךְ הַשֵּׁשׁ",
         "וג'זלוהא מע אלאסמאנגון ואלארגואן. ואלצבג' אלקרמז ואלעשר",
         "and weaving them together with the blue and the purple and the scarlet dye and the fine linen"),
        ("מַעֲשֵׂה חֹשֵׁב", "צנעה' חאד'ק", "the work of a skilled craftsman."),
    ],
    4: [
        ("כְּתֵפֹת עָשׂוּ-לוֹ חֹבְרֹת", "וצנעו להא גיבאן מכ'ייטאן",
         "And they made for it two sewn pockets"),
        ("עַל-שְׁנֵי קצוותו (קְצוֹתָיו) חֻבָּר", "כ'ייטוהמא פי טרפיה",
         "and sewed them onto its two edges."),
    ],
    5: [
        ("וְחֵשֶׁב אֲפֻדָּתוֹ אֲשֶׁר עָלָיו מִמֶּנּוּ הוּא כְּמַעֲשֵׂהוּ",
         "ושפשג אלצדרה אלד'י עליה. מתלה כצנעתה",
         "And the binding-straps of the ephod which are upon it — like it and of its workmanship"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי וְשֵׁשׁ מָשְׁזָר",
         "מן ד'הב ואסמאנגון וארגואן. וצבג' קרמז ועשר משזור",
         "of gold and blue and purple and scarlet dye and twisted fine linen"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    6: [
        ("וַיַּעֲשׂוּ אֶת-אַבְנֵי הַשֹּׁהַם מֻסַבֹּת מִשְׁבְּצֹת זָהָב",
         "וצנעו חגארי אלבלור. יחיט בהא עיון מן ד'הב",
         "And they made the crystal stones, with settings of gold encircling them"),
        ("מְפֻתָּחֹת פִּתּוּחֵי חוֹתָם עַל-שְׁמוֹת בְּנֵי יִשְׂרָאֵל",
         "מנקוש עליהא כנקש אלכ'אתם. אסמא בני אסראיל",
         "engraved upon them as the engraving of a signet — the names of the sons of Israel."),
    ],
    7: [
        ("וַיָּשֶׂם אֹתָם עַל כִּתְפֹת הָאֵפֹד--אַבְנֵי זִכָּרוֹן לִבְנֵי יִשְׂרָאֵל",
         "וגעלהם עלי' גיבי אלצדרה. חגאר ד'כר לבני אסראיל",
         "And he set them upon the two pockets of the ephod — stones of remembrance for the sons of Israel"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    8: [
        ("וַיַּעַשׂ אֶת-הַחֹשֶׁן מַעֲשֵׂה חֹשֵׁב כְּמַעֲשֵׂה אֵפֹד",
         "וצנע אלבדנה. צנעה' חאד'ק כצנעה אלצדרה",
         "And he made the breastpiece, the work of a skilled craftsman, like the workmanship of the ephod"),
        ("זָהָב תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי--וְשֵׁשׁ מָשְׁזָר",
         "מן ד'הב ואסמאנגון וארגואן. וצב'ג קרמז ועשר משזור",
         "of gold and blue and purple and scarlet dye and twisted fine linen."),
    ],
    9: [
        ("רָבוּעַ הָיָה כָּפוּל עָשׂוּ אֶת-הַחֹשֶׁן",
         "וכאנת אד' צנעוהא מרבעה מצ'אעפה",
         "And it was, when they made it, square and doubled"),
        ("זֶרֶת אָרְכּוֹ וְזֶרֶת רָחְבּוֹ כָּפוּל", "טולהא שבר וערצ'הא שבר",
         "its length a span, and its width a span."),
    ],
    10: [
        ("וַיְמַלְאוּ-בוֹ--אַרְבָּעָה טוּרֵי אָבֶן",
         "ונצ*כ'מו פיהא ארבעה סטור מן אלגוהר",
         "And they set in it four rows of gems in order"),
        ("טוּר אֹדֶם פִּטְדָה וּבָרֶקֶת--הַטּוּר הָאֶחָד",
         "אלסטר אלאוול יאקות אחמר. וזמרד ואצפר",
         "the first row — a red ruby, and an emerald, and a yellow one."),
    ],
    11: [
        ("וְהַטּוּר הַשֵּׁנִי--נֹפֶךְ סַפִּיר וְיָהֲלֹם",
         "ואלסטר אלת'אני. כחלי ומהא ובהרמאן",
         "And the second row — a deep-blue one, and a white gleaming one, and a bahraman."),
    ],
    12: [
        ("וְהַטּוּר הַשְּׁלִישִׁי--לֶשֶׁם שְׁבוֹ וְאַחְלָמָה",
         "ואלסטר אלת'אלת'. גזע וסבג ופירוזג",
         "And the third row — an agate, and a jet, and a turquoise."),
    ],
    13: [
        ("וְהַטּוּר הָרְבִיעִי--תַּרְשִׁישׁ שֹׁהַם וְיָשְׁפֵה",
         "ואלסטר אלראבע. אזרק ובלור ויסף",
         "And the fourth row — a sea-blue, and a crystal, and a jasper"),
        ("מוּסַבֹּת מִשְׁבְּצֹת זָהָב בְּמִלֻּאֹתָם",
         "יחיט בהא עיון מן ד'הב פי נצ'אמהא",
         "with settings of gold encircling them, in their arrangement."),
    ],
    14: [
        ("וְהָאֲבָנִים עַל-שְׁמֹת בְּנֵי-יִשְׂרָאֵל הֵנָּה שְׁתֵּים עֶשְׂרֵה",
         "וכאן עלי' אלחגארה אסמא בני אסראיל. לאנהא את'ני עשר",
         "And upon the stones were the names of the sons of Israel — for they are twelve"),
        ("עַל-שְׁמֹתָם פִּתּוּחֵי חֹתָם אִישׁ עַל-שְׁמוֹ לִשְׁנֵים עָשָׂר שָׁבֶט",
         "נצ'יר אסמאיהם. כנקש אלכ'אתם אסם כל ואחד עלי' חגר. כד'אך לאת'ני עשר סבט",
         "corresponding to their names — the name of each one engraved as the engraving of a signet upon a stone; thus for the twelve tribes."),
    ],
    15: [
        ("וַיַּעֲשׂוּ עַל-הַחֹשֶׁן שַׁרְשְׁרֹת גַּבְלֻת מַעֲשֵׂה עֲבֹת זָהָב טָהוֹר",
         "וצנעו עלי'אלבדנה. סלסלתין מעתדלין צנעה' צ'פר. מן ד'הב",
         "And they made upon the breastpiece two chains, even and straight, of braided workmanship, of pure gold."),
    ],
    16: [
        ("וַיַּעֲשׂוּ שְׁתֵּי מִשְׁבְּצֹת זָהָב וּשְׁתֵּי טַבְּעֹת זָהָב",
         "וחלקתין מן ד'הב",
         "And they made settings of gold and two rings of gold"),
        ("וַיִּתְּנוּ אֶת-שְׁתֵּי הַטַּבָּעֹת עַל-שְׁנֵי קְצוֹת הַחֹשֶׁן",
         "ו'געלו אלחלקתין. פי טרפי אלבדנה",
         "and placed the two rings at the two edges of the breastpiece."),
    ],
    17: [
        ("וַיִּתְּנוּ שְׁתֵּי הָעֲבֹתֹת הַזָּהָב עַל-שְׁתֵּי הַטַּבָּעֹת--עַל-קְצוֹת הַחֹשֶׁן",
         "ועלקו אלצ'פירתין פי אלחלקתין. פי טרפי אלבדנה",
         "And they hung the two braided chains upon the two rings, at the two edges of the breastpiece."),
    ],
    18: [
        ("וְאֵת שְׁתֵּי קְצוֹת שְׁתֵּי הָעֲבֹתֹת נָתְנוּ עַל-שְׁתֵּי הַמִּשְׁבְּצֹת",
         "וטרפי אלצ'פירתין אלאכ'רתין עלקוהא עלי' אלעיון",
         "And the two other ends of the two braided chains they hung upon the settings"),
        ("וַיִּתְּנֻם עַל-כִּתְפֹת הָאֵפֹד אֶל-מוּל פָּנָיו",
         "וגעלוהא. עלי' גיבי אלצדרה מן מקדמהא",
         "and placed them upon the two pockets of the ephod, on its front side."),
    ],
    19: [
        ("וַיַּעֲשׂוּ שְׁתֵּי טַבְּעֹת זָהָב", "וצנעו איצ'א חלקתין מן ד'הב",
         "And they also made two rings of gold"),
        ("וַיָּשִׂימוּ עַל-שְׁנֵי קְצוֹת הַחֹשֶׁן עַל-שְׂפָתוֹ--אֲשֶׁר אֶל-עֵבֶר הָאֵפֹד בָּיְתָה",
         "וציירוהמא פי טרפי אלבדנה. פי חאשיתהא. אלי' גאנב אלצדרה מן דאכ'ל",
         "and set them at the two edges of the breastpiece, on its border, toward the side of the ephod on the inner side."),
    ],
    20: [
        ("וַיַּעֲשׂוּ שְׁתֵּי טַבְּעֹת זָהָב וַיִּתְּנֻם עַל-שְׁתֵּי כִתְפֹת הָאֵפֹד מִלְּמַטָּה",
         "ת'ם צנעו איצ'א חלקתין מן ד'הב וגעלוהמא. באיזא גיב אלצדרה מן אספל",
         "Then they also made two rings of gold and placed them opposite the two pockets of the ephod, on their lower part"),
        ("מִמּוּל פָּנָיו לְעֻמַּת מַחְבַּרְתּוֹ--מִמַּעַל לְחֵשֶׁב הָאֵפֹד",
         "מן מקדמהא. אמאם תאליפהא. פוק שפשגהא",
         "toward the front of the ephod, facing its joining, above its binding-straps."),
    ],
    21: [
        ("וַיִּרְכְּסוּ אֶת-הַחֹשֶׁן מִטַּבְּעֹתָיו אֶל-טַבְּעֹת הָאֵפֹד בִּפְתִיל תְּכֵלֶת",
         "וחבכו אלבדנה. מן חלקהא אלי' חלק אלצדרה בסלך אסמאנגון",
         "And they fastened the breastpiece from its rings to the rings of the ephod with a cord of blue"),
        ("לִהְיֹת עַל-חֵשֶׁב הָאֵפֹד וְלֹא-יִזַּח הַחֹשֶׁן מֵעַל הָאֵפֹד",
         "לתכון פוק שפשגהא. ולא תזול מנהא",
         "so that it would be above its binding-straps and the breastpiece would not come loose from the ephod"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    22: [
        ("וַיַּעַשׂ אֶת-מְעִיל הָאֵפֹד מַעֲשֵׂה אֹרֵג כְּלִיל תְּכֵלֶת",
         "וצנע ממטר אלצדרה צנעה' חאיך. גמלתה אסמאנגון",
         "And he made the robe of the ephod, the work of a weaver, entirely of blue."),
    ],
    23: [
        ("וּפִי-הַמְּעִיל בְּתוֹכוֹ כְּפִי תַחְרָא", "וכאן ראסה פי וסטה כפם אלדרע",
         "And its opening was in the middle of it, like the opening of a coat of mail"),
        ("שָׂפָה לְפִיו סָבִיב לֹא יִקָּרֵעַ", "וחאשיה תחיט בפאה ללא יכ'תרק",
         "with a border encircling its opening, so that it would not tear."),
    ],
    24: [
        ("וַיַּעֲשׂוּ עַל-שׁוּלֵי הַמְּעִיל רִמּוֹנֵי תְּכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי--מָשְׁזָר",
         "וצנעו פי ד'ילה רמאמין. מן אסמאנגון וארגואן וצבג' קרמז משזור",
         "And they made in its hem pomegranates of blue and purple and scarlet dye, twisted."),
    ],
    25: [
        ("וַיַּעֲשׂוּ פַעֲמֹנֵי זָהָב טָהוֹר", "וצנעו גלאגל מן ד'הב כ'אלץ",
         "And they made bells of pure gold"),
        ("וַיִּתְּנוּ אֶת-הַפַּעֲמֹנִים בְּתוֹךְ הָרִמֹּנִים עַל-שׁוּלֵי הַמְּעִיל סָבִיב--בְּתוֹךְ הָרִמֹּנִים",
         "וגעלוהא פי מא בין אלרמאמין. פי ד'יל אלממטר מסתדירא. פי מא בין אלרמאמין",
         "and placed them between the pomegranates, in the hem of the robe, all around, between the pomegranates."),
    ],
    26: [
        ("פַּעֲמֹן וְרִמֹּן פַּעֲמֹן וְרִמֹּן עַל-שׁוּלֵי הַמְּעִיל סָבִיב לְשָׁרֵת",
         "גלגל ורמאנה גלגל ורמאנה. פי ד'יל אלממטר מסתדירא. ליכ'דם בה",
         "A bell and a pomegranate, a bell and a pomegranate — in the hem of the robe, all around, for him to serve in it"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    27: [
        ("וַיַּעֲשׂוּ אֶת-הַכָּתְנֹת שֵׁשׁ מַעֲשֵׂה אֹרֵג לְאַהֲרֹן וּלְבָנָיו",
         "וצנעו אלתואני מן עשר צנעה' חאיך. להרון ולבניה",
         "And they made the tunics of fine linen, the work of a weaver, for Aaron and for his sons."),
    ],
    28: [
        ("וְאֵת הַמִּצְנֶפֶת שֵׁשׁ", "ואלעמאמה מן עשר", "And the turban of fine linen"),
        ("וְאֶת-פַּאֲרֵי הַמִּגְבָּעֹת שֵׁשׁ", "ואלקלאנס אלפאכ'רה מן עשר",
         "and the splendid head-coverings of fine linen"),
        ("וְאֶת-מִכְנְסֵי הַבָּד שֵׁשׁ מָשְׁזָר", "ואלסראויל מן עשר משזור",
         "and the trousers of twisted fine linen."),
    ],
    29: [
        ("וְאֶת-הָאַבְנֵט שֵׁשׁ מָשְׁזָר וּתְכֵלֶת וְאַרְגָּמָן וְתוֹלַעַת שָׁנִי",
         "ואלזנאר מן עשר משזור. ואסמאנגון וארגואן. וצבג' קרמז",
         "And the sash of twisted fine linen and blue and purple and scarlet dye"),
        ("מַעֲשֵׂה רֹקֵם", "צנעה' ראקם", "the work of an embroiderer"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי''",
         "as God had commanded Moses."),
    ],
    30: [
        ("וַיַּעֲשׂוּ אֶת-צִיץ נֵזֶר-הַקֹּדֶשׁ זָהָב טָהוֹר",
         "וצנעו עצאבה' תאג אלקדס מן ד'הב כ'אלץ",
         "And they made the diadem-band of the sacred crown of pure gold"),
        ("וַיִּכְתְּבוּ עָלָיו מִכְתַּב פִּתּוּחֵי חוֹתָם--קֹדֶשׁ לַיהוָה",
         "ונקשו עליהא כתאב כנקש אלכ'אתם. קדש ליי'",
         "and engraved upon it a writing as the engraving of a signet: 'Holy to God.'"),
    ],
    31: [
        ("וַיִּתְּנוּ עָלָיו פְּתִיל תְּכֵלֶת", "ועלקוהא בסלך אסמאנגון",
         "And they hung it with a cord of blue"),
        ("לָתֵת עַל-הַמִּצְנֶפֶת מִלְמָעְלָה", "לתוצ'ע עלי' אלעמאמה פוק אלגבהה",
         "to be placed upon the turban above the forehead"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה", "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    32: [
        ("וַתֵּכֶל--כָּל-עֲבֹדַת מִשְׁכַּן אֹהֶל מוֹעֵד",
         "פכמלת. גמיע צנעה' אלמסכן כ'בא אלמחצ'ר",
         "And all the work of the tabernacle, the tent of assembly, was completed"),
        ("וַיַּעֲשׂוּ בְּנֵי יִשְׂרָאֵל--כְּכֹל אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה כֵּן עָשׂוּ",
         "וצנעו בני אסראיל. כגמיע מא אמר אללה מוסי' כד'אך צנעו",
         "and the sons of Israel made it according to all that God had commanded Moses — so they made it."),
    ],
    33: [
        ("וַיָּבִיאוּ אֶת-הַמִּשְׁכָּן אֶל-מֹשֶׁה", "פאתו באלמסכן אלי' מוסי'",
         "And they brought the tabernacle to Moses"),
        ("אֶת-הָאֹהֶל וְאֶת-כָּל-כֵּלָיו", "אלכ'בא וגמיע אניתה", "the tent and all its vessels"),
        ("קְרָסָיו קְרָשָׁיו בְּרִיחָו וְעַמֻּדָיו וַאֲדָנָיו",
         "שצ'צ'ה. ותכ'אתגה ואמהאגה ועמדה וקואעדה",
         "its clasps, its planks, its bars, its pillars, and its bases."),
    ],
    34: [
        ("וְאֶת-מִכְסֵה עוֹרֹת הָאֵילִם הַמְאָדָּמִים", "וג'טא אלגלוד אלכבאש אלאדים",
         "And the covering of the tanned ram-skins"),
        ("וְאֶת-מִכְסֵה עֹרֹת הַתְּחָשִׁים", "וג'טא אלגלוד אלדארש",
         "and the covering of the daresh-skins"),
        ("וְאֵת פָּרֹכֶת הַמָּסָךְ", "ואלסגף אלמסתור", "and the screening veil."),
    ],
    35: [
        ("אֶת-אֲרוֹן הָעֵדֻת וְאֶת-בַּדָּיו", "וצנדוק אלשהאדה ודהוקה",
         "And the ark of the testimony and its poles"),
        ("וְאֵת הַכַּפֹּרֶת", "ואלג'שא", "and the cover."),
    ],
    36: [
        ("אֶת-הַשֻּׁלְחָן אֶת-כָּל-כֵּלָיו", "ואלמאידה וגמיע אניתהא",
         "And the table and all its vessels"),
        ("וְאֵת לֶחֶם הַפָּנִים", "ואלכ'בז אלמווגה", "and the bread of presentation."),
    ],
    37: [
        ("אֶת-הַמְּנֹרָה הַטְּהֹרָה אֶת-נֵרֹתֶיהָ נֵרֹת הַמַּעֲרָכָה",
         "ואלמנארה אלכ'אלצה וסרגהא. סרג אלנצ'ד",
         "And the pure lampstand, its lamps — the lamps of the arrangement"),
        ("וְאֶת-כָּל-כֵּלֶיהָ וְאֵת שֶׁמֶן הַמָּאוֹר", "וגמיע אניתהא. ודה'ן אלאצ'אה",
         "and all its vessels, and the oil of illumination."),
    ],
    38: [
        ("וְאֵת מִזְבַּח הַזָּהָב", "ומד'בח אלד'הב", "And the golden altar"),
        ("וְאֵת שֶׁמֶן הַמִּשְׁחָה וְאֵת קְטֹרֶת הַסַּמִּים", "ודה'ן אלמסח. ובכ'ור אלצמוג'",
         "and the anointing oil, and the resinous incense"),
        ("וְאֵת מָסַךְ פֶּתַח הָאֹהֶל", "וסתר באב אלכ'בא",
         "and the curtain for the entrance of the tent."),
    ],
    39: [
        ("אֵת מִזְבַּח הַנְּחֹשֶׁת וְאֶת-מִכְבַּר הַנְּחֹשֶׁת אֲשֶׁר-לוֹ",
         "ומד'בח אלנחאס ואלסרד אלנחאס אלד'י לה",
         "And the bronze altar and its bronze grating"),
        ("אֶת-בַּדָּיו וְאֶת-כָּל-כֵּלָיו", "ודהוקה וגמיע אניתה", "its poles and all its vessels"),
        ("אֶת-הַכִּיֹּר וְאֶת-כַּנּוֹ", "ואלחוץ' ומקעדה", "and the basin and its stand."),
    ],
    40: [
        ("אֵת קַלְעֵי הֶחָצֵר אֶת-עַמֻּדֶיהָ וְאֶת-אֲדָנֶיהָ",
         "וקלוע אלצראדק ועמדהא וקואעדהא",
         "And the hangings of the court-enclosure, its pillars and its bases"),
        ("וְאֶת-הַמָּסָךְ לְשַׁעַר הֶחָצֵר אֶת-מֵיתָרָיו וִיתֵדֹתֶיהָ",
         "וסתר באבהא ואטנאבהא ואותאדה",
         "and the curtain of its gate and its cords and its pegs"),
        ("וְאֵת כָּל-כְּלֵי עֲבֹדַת הַמִּשְׁכָּן--לְאֹהֶל מוֹעֵד",
         "וסאיר אניה' עמל אלמסכן לכ'בא אלמחצ'ר",
         "and the rest of the vessels of the work of the tabernacle, for the tent of assembly."),
    ],
    41: [
        ("אֶת-בִּגְדֵי הַשְּׂרָד לְשָׁרֵת בַּקֹּדֶשׁ", "ותיאב אלושי לאלכ'דמה פי אלקדס",
         "And the embroidered garments for service in the sanctuary"),
        ("אֶת-בִּגְדֵי הַקֹּדֶשׁ לְאַהֲרֹן הַכֹּהֵן", "ות'יאב אלקדס להרון אלאמאם",
         "and the sacred garments for Aaron the imam"),
        ("וְאֶת-בִּגְדֵי בָנָיו לְכַהֵן", "ות'יאב בניה לאלאמאמה",
         "and the garments of his sons for the imamate."),
    ],
    42: [
        ("כְּכֹל אֲשֶׁר-צִוָּה יְהוָה אֶת-מֹשֶׁה", "כגמיע מא אמר אללה מוסי'",
         "According to all that God had commanded Moses"),
        ("כֵּן עָשׂוּ בְּנֵי יִשְׂרָאֵל אֵת כָּל-הָעֲבֹדָה",
         "כד'אך צנעו בני אסראיל. גמיע אלעמל",
         "so the sons of Israel made all the work."),
    ],
    43: [
        ("וַיַּרְא מֹשֶׁה אֶת-כָּל-הַמְּלָאכָה", "פלמא ראא מוסי' גמיע אלעמל",
         "And when Moses saw all the work"),
        ("וְהִנֵּה עָשׂוּ אֹתָהּ--כַּאֲשֶׁר צִוָּה יְהוָה כֵּן עָשׂוּ",
         "ואד'א בהם קד צנעוהא. כמא אמר אללה. בארך עלי'הם מוסי'",
         "and behold, they had made it as God had commanded — Moses bestowed blessing upon them."),
    ],
}
