"""Hand-authored alignment triples for Shemot chapter 10."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי'", "Then God said to Moses"),
        ("בֹּא אֶל-פַּרְעֹה", "אדכ'ל אלי' פרעון", "Go in to Pharaoh"),
        ("כִּי-אֲנִי הִכְבַּדְתִּי אֶת-לִבּוֹ וְאֶת-לֵב עֲבָדָיו",
         "פאני קד קוית קלבה וקלוב קואדה",
         "for I have strengthened his heart and the hearts of his officers"),
        ("לְמַעַן שִׁתִי אֹתֹתַי אֵלֶּה בְּקִרְבּוֹ",
         "לכי אחל אפאתי הד'ה בהם",
         "so that I may bring these my plagues upon them"),
    ],
    2: [
        ("וּלְמַעַן תְּסַפֵּר בְּאָזְנֵי בִנְךָ וּבֶן-בִּנְךָ",
         "ולכי תקץ עלי' אבנך ואבן אבנך",
         "And so that you may recount to your son and to your son's son"),
        ("אֵת אֲשֶׁר הִתְעַלַּלְתִּי בְּמִצְרַיִם", "מא בטשת באלמצריון",
         "what I have struck the Egyptians with by force"),
        ("וְאֶת-אֹתֹתַי אֲשֶׁר-שַׂמְתִּי בָם", "ואפאתי אלתי אחללת בהם",
         "and my plagues which I have brought upon them"),
        ("וִידַעְתֶּם כִּי-אֲנִי יְהוָה", "ותעלמון אני אללה",
         "that you may know that I am God"),
    ],
    3: [
        ("וַיָּבֹא מֹשֶׁה וְאַהֲרֹן אֶל-פַּרְעֹה", "פדכ'ל מוסי' והרון אלי' פרעון",
         "And Moses and Aaron went in to Pharaoh"),
        ("וַיֹּאמְרוּ אֵלָיו כֹּה-אָמַר יְהוָה אֱלֹהֵי הָעִבְרִים",
         "וקאלא לה. כד'א קאל אללה אלאה אלעבראניין",
         "and said to him: 'Thus says God, the God of the Hebrews"),
        ("עַד-מָתַי מֵאַנְתָּ לֵעָנֹת מִפָּנָי", "אלי' כם אבית. אן תד'ען מן בין ידיי",
         "How long will you refuse to submit before Me"),
        ("שַׁלַּח עַמִּי וְיַעַבְדֻנִי", "אטלק קומי יעבדוני",
         "Release my people, that they may serve Me"),
    ],
    4: [
        ("כִּי אִם-מָאֵן אַתָּה לְשַׁלֵּחַ אֶת-עַמִּי",
         "פאנך אן אבית אן תטלק קומי",
         "For if you refuse to release my people"),
        ("הִנְנִי מֵבִיא מָחָר אַרְבֶּה בִּגְבֻלֶךָ",
         "האנא אתי באלג'דאה. אלגראד פי תכ'מך",
         "behold, I am bringing at daybreak the locusts within your territory"),
    ],
    5: [
        ("וְכִסָּה אֶת-עֵין הָאָרֶץ", "פיג'טי עין אלארץ'",
         "and they shall cover the eye of the land"),
        ("וְלֹא יוּכַל לִרְאֹת אֶת-הָאָרֶץ", "ולא יטיק אחד אן ינצר אליהא",
         "so that no one shall be able to look upon it"),
        ("וְאָכַל אֶת-יֶתֶר הַפְּלֵטָה הַנִּשְׁאֶרֶת לָכֶם מִן-הַבָּרָד",
         "ויאכל באקי אלפליתה. אלתי תבקת לכם מן אלברד",
         "and they shall eat the remainder of the remnant that was left to you from the hail"),
        ("וְאָכַל אֶת-כָּל-הָעֵץ הַצֹּמֵחַ לָכֶם מִן-הַשָּׂדֶה",
         "ויאכל גמיע אלשגר. אלנאבת לכם מן אלצחרי'",
         "and they shall eat every tree growing for you from the wilderness"),
    ],
    6: [
        ("וּמָלְאוּ בָתֶּיךָ וּבָתֵּי כָל-עֲבָדֶיךָ וּבָתֵּי כָל-מִצְרַיִם",
         "תמתלי מנה ביותך. וביות קואדך וביות סאיר אלמצריון",
         "And your houses shall be filled with them, and the houses of your officers and the houses of the rest of the Egyptians"),
        ("אֲשֶׁר לֹא-רָאוּ אֲבֹתֶיךָ וַאֲבוֹת אֲבֹתֶיךָ",
         "מא לם ירא מת'לה אבאיך ואבא אבאיך",
         "the like of which your fathers and your fathers' fathers have not seen"),
        ("מִיּוֹם הֱיוֹתָם עַל-הָאֲדָמָה עַד הַיּוֹם הַזֶּה",
         "מנד' כונהם עלי' אלארץ'. אלי' הד'א אליום",
         "since their being upon the earth until this day"),
        ("וַיִּפֶן וַיֵּצֵא מֵעִם פַּרְעֹה", "ת'ם ולא וכ'רג מן ענד פרעון",
         "Then he turned and went out from before Pharaoh"),
    ],
    7: [
        ("וַיֹּאמְרוּ עַבְדֵי פַרְעֹה אֵלָיו", "פקאל קואד פרעון לה",
         "And the officers of Pharaoh said to him"),
        ("עַד-מָתַי יִהְיֶה זֶה לָנוּ לְמוֹקֵשׁ",
         "אלי' כם יכון הד'א לנא והקא",
         "How long shall this be a snare about our necks"),
        ("שַׁלַּח אֶת-הָאֲנָשִׁים וְיַעַבְדוּ אֶת-יְהוָה אֱלֹהֵיהֶם",
         "אטלק אלקום. יעבדו אללה רבהם",
         "Release the people, that they may serve God their Lord"),
        ("הֲטֶרֶם תֵּדַע כִּי אָבְדָה מִצְרָיִם", "קבל אן תשאהד מצר קד באדת",
         "before you see Egypt utterly destroyed"),
    ],
    8: [
        ("וַיּוּשַׁב אֶת-מֹשֶׁה וְאֶת-אַהֲרֹן אֶל-פַּרְעֹה",
         "פארד מוסי' והרון אלי' פרעון",
         "So Moses and Aaron were brought back to Pharaoh"),
        ("וַיֹּאמֶר אֲלֵהֶם לְכוּ עִבְדוּ אֶת-יְהוָה אֱלֹהֵיכֶם",
         "וקאל. להמא אמצ'ו אעבדו אללה רבכם",
         "and he said to them: 'Go, serve God your Lord"),
        ("מִי וָמִי הַהֹלְכִים", "מן ומן אלמאציון",
         "But who and who are those who are going"),
    ],
    9: [
        ("וַיֹּאמֶר מֹשֶׁה בִּנְעָרֵינוּ וּבִזְקֵנֵינוּ נֵלֵךְ",
         "קאל מוסי'. בצביאננא ובשיוכ'נא נמצ'י",
         "Moses said: 'With our young and with our elders we shall go"),
        ("בְּבָנֵינוּ וּבִבְנוֹתֵנוּ", "בבנינא ובבנאתנא",
         "with our sons and with our daughters"),
        ("בְּצֹאנֵנוּ וּבִבְקָרֵנוּ נֵלֵךְ", "בג'נמנא ובקרנא נמצ'י",
         "with our flock and with our cattle we shall go"),
        ("כִּי חַג-יְהוָה לָנוּ", "לאן חג אללה לנא",
         "for the festival of God belongs to us"),
    ],
    10: [
        ("וַיֹּאמֶר אֲלֵהֶם יְהִי כֵן יְהוָה עִמָּכֶם",
         "קאל להם. יכון כדאך אללה מעכם",
         "He said to them: 'So be it — may God be with you"),
        ("כַּאֲשֶׁר אֲשַׁלַּח אֶתְכֶם וְאֶת-טַפְּכֶם", "כמא אטלקכם ואטפאלכם",
         "just as I would release you and your children"),
        ("רְאוּ כִּי רָעָה נֶגֶד פְּנֵיכֶם", "הוד'י ארא אלשר חד'א וגוהכם",
         "Behold, I see evil facing you"),
    ],
    11: [
        ("לֹא כֵן לְכוּ-נָא הַגְּבָרִים וְעִבְדוּ אֶת-יְהוָה",
         "ליס כד'אך. ימצ'י אלרגאל מנכם יעבדו אללה",
         "It is not thus. Let the men among you go and serve God"),
        ("כִּי אֹתָהּ אַתֶּם מְבַקְשִׁים", "פאנכם אנמא תטלבונה",
         "for that is indeed what you are seeking"),
        ("וַיְגָרֶשׁ אֹתָם מֵאֵת פְּנֵי פַרְעֹה", "וטרדהם מן בין ידי פרעון",
         "And he drove them out from before Pharaoh"),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה למוסי'", "And God said to Moses"),
        ("נְטֵה יָדְךָ עַל-אֶרֶץ מִצְרַיִם בָּאַרְבֶּה",
         "מד ידך. עלי' בלד מצר בסבב אלגראד",
         "Stretch out your hand over the land of Egypt on account of the locusts"),
        ("וְיַעַל עַל-אֶרֶץ מִצְרָיִם", "פיצעד עלי בלד מצר",
         "that they may come up over the land of Egypt"),
        ("וְיֹאכַל אֶת-כָּל-עֵשֶׂב הָאָרֶץ אֵת כָּל-אֲשֶׁר הִשְׁאִיר הַבָּרָד",
         "ויאכל גמיע עשבהא. גמיע מא בקאה אלברד",
         "and eat all its herbage — all that the hail left"),
    ],
    13: [
        ("וַיֵּט מֹשֶׁה אֶת-מַטֵּהוּ עַל-אֶרֶץ מִצְרַיִם",
         "פמד מוסי' עצאה עלי' בלד מצר",
         "And Moses stretched out his staff over the land of Egypt"),
        ("וַיהוָה נִהַג רוּחַ-קָדִים בָּאָרֶץ כָּל-הַיּוֹם הַהוּא וְכָל-הַלָּיְלָה",
         "וסאק אללה ריח אלקבול פי אלבלד. טול דאלך אלנהאר ולילה",
         "and God drove the qibla-wind through the land all that day and its night"),
        ("הַבֹּקֶר הָיָה--וְרוּחַ הַקָּדִים נָשָׂא אֶת-הָאַרְבֶּה",
         "פלמא כאנת אלג'דאה. חמל ריח אלקבול אלגראד",
         "and when morning came, the qibla-wind carried the locusts"),
    ],
    14: [
        ("וַיַּעַל הָאַרְבֶּה עַל כָּל-אֶרֶץ מִצְרַיִם",
         "פצעד אלגראד פי גמיע בלד מצר",
         "And the locusts came up over all the land of Egypt"),
        ("וַיָּנַח בְּכֹל גְּבוּל מִצְרָיִם כָּבֵד מְאֹד",
         "ואסתקר פי גמיע תכמהא. עצ'ים גדא",
         "and settled throughout all its territory — very greatly"),
        ("לְפָנָיו לֹא-הָיָה כֵן אַרְבֶּה כָּמֹהוּ וְאַחֲרָיו לֹא יִהְיֶה-כֵּן",
         "מא לם יכון קבלה גראד מת'לה. ובעדה לא יכון כדאך",
         "before it there had been no such locusts as these, and after it there shall not be so"),
    ],
    15: [
        ("וַיְכַס אֶת-עֵין כָּל-הָאָרֶץ וַתֶּחְשַׁךְ הָאָרֶץ",
         "פג'טא עין גמיע אלבלד חתי' אצ'לם",
         "And it covered the eye of all the land until it was darkened"),
        ("וַיֹּאכַל אֶת-כָּל-עֵשֶׂב הָאָרֶץ וְאֵת כָּל-פְּרִי הָעֵץ אֲשֶׁר הוֹתִיר הַבָּרָד",
         "ואכל גמיע עשבה. וגמיע תמר אלשגר. אלד'י בקאה אלברד",
         "and it ate all the herbage of the land, and all the fruit of the trees that the hail had left"),
        ("וְלֹא-נוֹתַר כָּל-יֶרֶק בָּעֵץ וּבְעֵשֶׂב הַשָּׂדֶה בְּכָל-אֶרֶץ מִצְרָיִם",
         "ולם יבק שי מן אלכצ'רה פי אלשגר. ועשב אלצחרי' פי גמיע בלד מצר",
         "and there remained nothing of the green in the trees or in the herbage of the wilderness throughout all the land of Egypt"),
    ],
    16: [
        ("וַיְמַהֵר פַּרְעֹה לִקְרֹא לְמֹשֶׁה וּלְאַהֲרֹן",
         "ת'ם אסרע פרעון. ודעי במוסי' והרון",
         "Then Pharaoh hastened and called for Moses and Aaron"),
        ("וַיֹּאמֶר חָטָאתִי לַיהוָה אֱלֹהֵיכֶם--וְלָכֶם",
         "וקאל. קד אכ'טאת ללה רבכמא ולכמא",
         "and said: 'I have sinned against God your Lord, and against you"),
    ],
    17: [
        ("וְעַתָּה שָׂא נָא חַטָּאתִי אַךְ הַפַּעַם",
         "ואלאן פאחתמלא דנבי הד'ה אלמרה",
         "And now — bear my sin this time"),
        ("וְהַעְתִּירוּ לַיהוָה אֱלֹהֵיכֶם", "ואשפעא אלי אללה רבכמא",
         "and intercede with God your Lord"),
        ("וְיָסֵר מֵעָלַי רַק אֶת-הַמָּוֶת הַזֶּה",
         "אן יזיל עני. הד'א אלמות אלמחץ'",
         "that He remove from me this sheer death"),
    ],
    18: [
        ("וַיֵּצֵא מֵעִם פַּרְעֹה", "פלמא כ'רג מן ענדה", "And when he went out from before him"),
        ("וַיֶּעְתַּר אֶל-יְהוָה", "שפע אלי' אללה", "he interceded with God"),
    ],
    19: [
        ("וַיַּהֲפֹךְ יְהוָה רוּחַ-יָם חָזָק מְאֹד", "פקלב אללה ריחא גרבייא שדידא גדא",
         "And God turned a very fierce west wind"),
        ("וַיִּשָּׂא אֶת-הָאַרְבֶּה", "פחמל אלגראד", "and it carried the locusts"),
        ("וַיִּתְקָעֵהוּ יָמָּה סּוּף", "וצך בה בחר אלקלזם",
         "and the Sea of Qulzum (Red Sea) received them"),
        ("לֹא נִשְׁאַר אַרְבֶּה אֶחָד בְּכֹל גְּבוּל מִצְרָיִם",
         "לם תבק גראדה ואחדה. פי גמיע בלד מצר",
         "not a single locust remained in all the land of Egypt"),
    ],
    20: [
        ("וַיְחַזֵּק יְהוָה אֶת-לֵב פַּרְעֹה", "פשדד אללה קלב פרעון",
         "And God hardened Pharaoh's heart"),
        ("וְלֹא שִׁלַּח אֶת-בְּנֵי יִשְׂרָאֵל", "ולם יטלק בני אסראיל",
         "and he did not release the sons of Israel"),
    ],
    21: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "וקאל אללה למוסי'", "And God said to Moses"),
        ("נְטֵה יָדְךָ עַל-הַשָּׁמַיִם", "מד ידך נחו אלסמא",
         "Stretch out your hand toward the sky"),
        ("וִיהִי חֹשֶׁךְ עַל-אֶרֶץ מִצְרָיִם", "יכון צ'לאם עלי' גמיע בלד מצר",
         "there shall be darkness over all the land of Egypt"),
        ("וְיָמֵשׁ חֹשֶׁךְ", "בעד זואל צ'לאם אלליל",
         "after the fading of the darkness of night"),
    ],
    22: [
        ("וַיֵּט מֹשֶׁה אֶת-יָדוֹ עַל-הַשָּׁמָיִם", "פמד מוסי' ידה נחו אלסמא",
         "And Moses stretched out his hand toward the sky"),
        ("וַיְהִי חֹשֶׁךְ-אֲפֵלָה בְּכָל-אֶרֶץ מִצְרַיִם",
         "פכאן צ'לאם אפל. פי גמיע בלד מצר",
         "and there was a thick darkness throughout all the land of Egypt"),
        ("שְׁלֹשֶׁת יָמִים", "ת'לאת'ה' איאם", "three days"),
    ],
    23: [
        ("לֹא-רָאוּ אִישׁ אֶת-אָחִיו", "לם ירא אנסאן צאחבה",
         "No person saw his fellow"),
        ("וְלֹא-קָמוּ אִישׁ מִתַּחְתָּיו--שְׁלֹשֶׁת יָמִים",
         "ולם יקום אנסאן מן מכאנה ת'לאת'ה' איאם",
         "and no person rose from his place for three days"),
        ("וּלְכָל-בְּנֵי יִשְׂרָאֵל הָיָה אוֹר בְּמוֹשְׁבֹתָם",
         "ולגמיע בני אסראיל. כאן נור פי מסאכנהם",
         "but for all the sons of Israel there was light in their dwellings"),
    ],
    24: [
        ("וַיִּקְרָא פַרְעֹה אֶל-מֹשֶׁה", "פדעי' פרעון במוסי",
         "And Pharaoh called for Moses"),
        ("וַיֹּאמֶר לְכוּ עִבְדוּ אֶת-יְהוָה", "וקאל אמצ'ו אעבדו אללה",
         "and said: 'Go, serve God"),
        ("רַק צֹאנְכֶם וּבְקַרְכֶם יֻצָּג", "לכן ג'נמכם ובקרכם דעוהא",
         "only your flock and your cattle leave behind"),
        ("גַּם-טַפְּכֶם יֵלֵךְ עִמָּכֶם", "ואטפאלכם תמצ'י מעכם",
         "your children may go with you"),
    ],
    25: [
        ("וַיֹּאמֶר מֹשֶׁה גַּם-אַתָּה תִּתֵּן בְּיָדֵנוּ זְבָחִים וְעֹלֹת",
         "קאל לה מוסי'. בל אנת. תעטינא ד'באיחא וצואעדא",
         "Moses said to him: 'Nay, you yourself shall give us sacrifices and burnt offerings"),
        ("וְעָשִׂינוּ לַיהוָה אֱלֹהֵינוּ", "נקרבהא ללה רבנא",
         "that we may offer them to God our Lord"),
    ],
    26: [
        ("וְגַם-מִקְנֵנוּ יֵלֵךְ עִמָּנוּ לֹא תִשָּׁאֵר פַּרְסָה",
         "ומואשינא איצ'א תמצ'י מענא. לא יבק מנהא צ'לף",
         "And our livestock shall go with us too — not a hoof shall remain from them"),
        ("כִּי מִמֶּנּוּ נִקַּח לַעֲבֹד אֶת-יְהוָה אֱלֹהֵינוּ",
         "לאן מנהא נאכ'ד נעבד אללה רבנא",
         "for from them we shall take to serve God our Lord"),
        ("וַאֲנַחְנוּ לֹא-נֵדַע מַה-נַּעֲבֹד אֶת-יְהוָה עַד-בֹּאֵנוּ שָׁמָּה",
         "ונחן לא נעלם. כם מקדאר מא נעבד בה אללה. אלי' אן נציר אלי' ת'ם",
         "and we do not know how great a measure of what we shall serve God with, until we arrive there"),
    ],
    27: [
        ("וַיְחַזֵּק יְהוָה אֶת-לֵב פַּרְעֹה", "פשדד אללה קלבה",
         "And God hardened his heart"),
        ("וְלֹא אָבָה לְשַׁלְּחָם", "ולם ישא אטלאקהם",
         "and he did not will to release them"),
    ],
    28: [
        ("וַיֹּאמֶר-לוֹ פַרְעֹה לֵךְ מֵעָלָי", "קאל לה פרעון אמץ' עני",
         "Pharaoh said to him: 'Go from me"),
        ("הִשָּׁמֶר לְךָ אַל-תֹּסֶף רְאוֹת פָּנַי",
         "אחד'ר אן תעאוד תרא וגהי",
         "beware lest you see my face again"),
        ("כִּי בְּיוֹם רְאֹתְךָ פָנַי תָּמוּת",
         "פאנך פי יום תרא וגהי תקתל",
         "for on the day you see my face, you shall be put to death"),
    ],
    29: [
        ("וַיֹּאמֶר מֹשֶׁה כֵּן דִּבַּרְתָּ", "קאל לה מוסי' נעמא קלת",
         "Moses said to him: 'You have spoken rightly"),
        ("לֹא-אֹסִף עוֹד רְאוֹת פָּנֶיךָ", "לא אעאוד אן ארא וגהך",
         "I shall not see your face again"),
    ],
}
