"""Hand-authored alignment triples for Shemot chapter 2."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֵּלֶךְ אִישׁ מִבֵּית לֵוִי", "תם מצ'י רגל מן אל לוי",
         "Then a man of the family of Levi went"),
        ("וַיִּקַּח אֶת-בַּת-לֵוִי", "ותזווג אבנה' לוי",
         "and married the daughter of Levi"),
    ],
    2: [
        ("וַתַּהַר הָאִשָּׁה", "פחמלת אלאמראה", "And the woman conceived"),
        ("וַתֵּלֶד בֵּן", "וולדת אבנא", "and bore a son"),
        ("וַתֵּרֶא אֹתוֹ כִּי-טוֹב הוּא", "פלמא ראתה חסנא",
         "and when she saw that he was fair"),
        ("וַתִּצְפְּנֵהוּ", "אכ'פתה", "she hid him"),
        ("שְׁלֹשָׁה יְרָחִים", "ת'לאת'ה' אשהר", "for three months"),
    ],
    3: [
        ("וְלֹא-יָכְלָה עוֹד", "ולם תטיק עאד", "And she could no longer"),
        ("הַצְּפִינוֹ", "אן תכ'פיה", "hide him"),
        ("וַתִּקַּח-לוֹ", "פאכ'דת לה", "so she took for him"),
        ("תֵּבַת גֹּמֶא", "תאבותא מן ברדי", "an ark of papyrus"),
        ("וַתַּחְמְרָה", "וקפרתהא", "and sealed it"),
        ("בַחֵמָר וּבַזָּפֶת", "באלקפר ואלזפת", "with bitumen and pitch"),
        ("וַתָּשֶׂם בָּהּ אֶת-הַיֶּלֶד", "וציירת פיהא אלצבי",
         "and she set the babe inside it"),
        ("וַתָּשֶׂם בַּסּוּף", "וציירתהא פי אלדיס",
         "and set it in the reed-thicket"),
        ("עַל-שְׂפַת הַיְאֹר", "עלי' שאטי אלניל", "upon the bank of the Nile"),
    ],
    4: [
        ("וַתֵּתַצַּב אֲחֹתוֹ", "פוקפת א'כ'תה", "And his sister stood"),
        ("מֵרָחֹק", "מן בעיד", "at a distance"),
        ("לְדֵעָה", "לתנצ'ר", "to see"),
        ("מַה-יֵּעָשֶׂה לוֹ", "מא יצנע בה", "what would be done with him"),
    ],
    5: [
        ("וַתֵּרֶד בַּת-פַּרְעֹה", "פנזלת אבנה' פרעון",
         "And Pharaoh's daughter came down"),
        ("לִרְחֹץ", "לתג'סל", "to bathe"),
        ("עַל-הַיְאֹר", "פי אלניל", "in the Nile"),
        ("וְנַעֲרֹתֶיהָ", "וגוארהא", "and her maids"),
        ("הֹלְכֹת", "ימשין", "walked"),
        ("עַל-יַד הַיְאֹר", "עלי' שאטה", "along its bank"),
        ("וַתֵּרֶא אֶת-הַתֵּבָה", "פראת אלתאבות", "She saw the ark"),
        ("בְּתוֹךְ הַסּוּף", "פי וסט אלדיס",
         "in the midst of the reed-thicket"),
        ("וַתִּשְׁלַח אֶת-אֲמָתָהּ", "פמדת ידהא",
         "and she stretched out her hand"),
        ("וַתִּקָּחֶהָ", "ואכ'ד'תהא", "and took it"),
    ],
    6: [
        ("וַתִּפְתַּח", "פפתחת", "And she opened it"),
        ("וַתִּרְאֵהוּ אֶת-הַיֶּלֶד", "וראתה", "and saw him"),
        ("וְהִנֵּה-נַעַר בֹּכֶה", "פאד'אה צבי יבכי",
         "behold, a babe was crying"),
        ("וַתַּחְמֹל עָלָיו", "פאשפקת עליה",
         "and she had compassion on him"),
        ("וַתֹּאמֶר", "וקאלת", "and said"),
        ("מִיַּלְדֵי הָעִבְרִים זֶה", "הד'א מן אולאד אלעבראניין",
         "This is one of the children of the Hebrews"),
    ],
    7: [
        ("וַתֹּאמֶר אֲחֹתוֹ אֶל-בַּת-פַּרְעֹה", "קאלת להא",
         "She said to her"),
        ("הַאֵלֵךְ", "אאמצ'י", "Shall I go"),
        ("וְקָרָאתִי לָךְ", "ואדעי לך", "and call for you"),
        ("אִשָּׁה מֵינֶקֶת", "באמראה מרצ'עה", "a nursing woman"),
        ("מִן הָעִבְרִיֹּת", "מן אלעבראנייאת", "from the Hebrews"),
        ("וְתֵינִק לָךְ אֶת-הַיָּלֶד", "תרצ'עה לך",
         "that she may nurse him for you"),
    ],
    8: [
        ("וַתֹּאמֶר-לָהּ בַּת-פַּרְעֹה", "קאלת להא אבנה' פרעון",
         "Pharaoh's daughter said to her"),
        ("לֵכִי", "אמצ'י", "Go"),
        ("וַתֵּלֶךְ הָעַלְמָה", "פמצ'ת אלגאריה", "And the maiden went"),
        ("וַתִּקְרָא אֶת-אֵם הַיָּלֶד", "ודעת באם אלצבי",
         "and called the mother of the babe"),
    ],
    9: [
        ("וַתֹּאמֶר לָהּ בַּת-פַּרְעֹה", "פקאלת להא אבנה' פרעון",
         "And Pharaoh's daughter said to her"),
        ("הֵילִיכִי אֶת-הַיֶּלֶד הַזֶּה", "הא לך הד'א אלצבי",
         "Here, take this babe"),
        ("וְהֵינִקִהוּ לִי", "ארצ'עיה לי", "nurse him for me"),
        ("וַאֲנִי אֶתֵּן אֶת-שְׂכָרֵךְ", "ואנא אעטיך אגרתך",
         "and I will give you your wage"),
        ("וַתִּקַּח הָאִשָּׁה", "פאכ'ד'ת אלאמראה", "And the woman took"),
        ("הַיֶּלֶד", "אלצבי", "the babe"),
        ("וַתְּנִיקֵהוּ", "וארצ'עתה", "and nursed him"),
    ],
    10: [
        ("וַיִּגְדַּל הַיֶּלֶד", "ולמא כבר אלצבי", "And when the babe grew"),
        ("וַתְּבִאֵהוּ לְבַת-פַּרְעֹה", "גאת בה אלי' אבנה' פרעון",
         "she brought him to Pharaoh's daughter"),
        ("וַיְהִי-לָהּ לְבֵן", "פצאר להא כאבן",
         "and he became to her like a son"),
        ("וַתִּקְרָא שְׁמוֹ מֹשֶׁה", "ואסמתה מוסי'",
         "And she named him Moses"),
        ("וַתֹּאמֶר", "קאלת", "saying"),
        ("כִּי מִן-הַמַּיִם מְשִׁיתִהוּ", "לאני נשלתה מן אלמא",
         "For I drew him out from the water"),
    ],
    11: [
        ("וַיְהִי בַּיָּמִים הָהֵם", "וכאן פי תלך אלאיאם",
         "And it was in those days"),
        ("וַיִּגְדַּל מֹשֶׁה", "אן מוסי' כבר", "that Moses grew up"),
        ("וַיֵּצֵא אֶל-אֶחָיו", "וכרג אלי' אכ'ותה",
         "and he went out to his brothers"),
        ("וַיַּרְא בְּסִבְלֹתָם", "ונצ'ר בנקלהם",
         "and he looked upon their burdens"),
        ("וַיַּרְא", "פאד'א", "And behold"),
        ("אִישׁ מִצְרִי", "ברג'ל מצרי", "an Egyptian man"),
        ("מַכֶּה", "יצ'רב", "was striking"),
        ("אִישׁ-עִבְרִי", "רג'ל עבראני", "a Hebrew man"),
        ("מֵאֶחָיו", "מן אכ'ותה", "one of his brothers"),
    ],
    12: [
        ("וַיִּפֶן", "פאלתפת", "And he turned"),
        ("כֹּה וָכֹה", "ימנה ויסרה", "right and left"),
        ("וַיַּרְא", "פראי'", "and saw"),
        ("כִּי אֵין אִישׁ", "אנה ליס אנסאן",
         "that there was no one [about]"),
        ("וַיַּךְ אֶת-הַמִּצְרִי", "פצ'רב אלמצרי",
         "and he struck the Egyptian"),
        (None, "פמאת", "and he died"),
        ("וַיִּטְמְנֵהוּ", "ודפנה", "and he buried him"),
        ("בַּחוֹל", "פי אלרמל", "in the sand"),
    ],
    13: [
        ("וַיֵּצֵא", "וכ'רג", "And he went out"),
        ("בַּיּוֹם הַשֵּׁנִי", "פי אליום אלת'אני", "on the second day"),
        ("וְהִנֵּה", "פאד'י", "and behold"),
        ("שְׁנֵי-אֲנָשִׁים עִבְרִים", "ברגלין עבראניין",
         "two Hebrew men"),
        ("נִצִּים", "יתנאציאן", "were quarreling"),
        ("וַיֹּאמֶר", "פקאל", "And he said"),
        ("לָרָשָׁע", "לאלצ'אלם מנהמא", "to the unjust one of them"),
        ("לָמָּה תַכֶּה", "לם תצ'רב", "Why do you strike"),
        ("רֵעֶךָ", "צאחבך", "your companion"),
    ],
    14: [
        ("וַיֹּאמֶר", "וקאל", "And he said"),
        ("מִי שָׂמְךָ", "מן ציירך", "Who set you"),
        ("לְאִישׁ שַׂר וְשֹׁפֵט עָלֵינוּ", "רגלא רייסא וחאכמא עלינא",
         "a chief and a judge over us"),
        ("הַלְהָרְגֵנִי אַתָּה אֹמֵר", "אתריד אן תקתלני",
         "Do you intend to kill me"),
        ("כַּאֲשֶׁר הָרַגְתָּ אֶת-הַמִּצְרִי", "כמא קתלת אלמצרי",
         "as you killed the Egyptian"),
        ("וַיִּירָא מֹשֶׁה", "פפזע מוסי'", "And Moses was alarmed"),
        ("וַיֹּאמַר", "וקאל", "and said"),
        ("אָכֵן", "איקינא", "Indeed"),
        ("נוֹדַע הַדָּבָר", "קד ערף אלכ'בר",
         "the matter has become known"),
    ],
    15: [
        ("וַיִּשְׁמַע פַּרְעֹה", "ולמא סמע פרעון",
         "And when Pharaoh heard"),
        ("אֶת-הַדָּבָר הַזֶּה", "בהד'א אלכ'בר", "of this matter"),
        ("וַיְבַקֵּשׁ לַהֲרֹג אֶת-מֹשֶׁה", "טלב אן יקתל מוסי'",
         "he sought to kill Moses"),
        ("וַיִּבְרַח מֹשֶׁה", "פהרב מוסי'", "And Moses fled"),
        ("מִפְּנֵי פַרְעֹה", "מן בין ידיה", "from before him"),
        ("וַיֵּשֶׁב בְּאֶרֶץ-מִדְיָן", "וצאר אלי' בלד מדין",
         "and came to the land of Midian"),
        ("וַיֵּשֶׁב עַל-הַבְּאֵר", "וגלס עלי' אלביר", "and sat by the well"),
    ],
    16: [
        ("וּלְכֹהֵן מִדְיָן", "וכאן לאמאם מדין",
         "And the imām of Midian had"),
        ("שֶׁבַע בָּנוֹת", "סבע בנאת", "seven daughters"),
        ("וַתָּבֹאנָה", "פגאת", "and they came"),
        ("וַתִּדְלֶנָה", "ודלאת", "and drew water"),
        ("וַתְּמַלֶּאנָה אֶת-הָרְהָטִים", "ומלאת אלחיאץ'",
         "and filled the troughs"),
        ("לְהַשְׁקוֹת צֹאן אֲבִיהֶן", "לתסקי ג'נם אביהן",
         "to water their father's flock"),
    ],
    17: [
        ("וַיָּבֹאוּ הָרֹעִים", "פגאו אלרעאה",
         "And the shepherds came"),
        ("וַיְגָרְשׁוּם", "וטרדוהן", "and drove them away"),
        ("וַיָּקָם מֹשֶׁה", "פקאם מוסי", "and Moses arose"),
        ("וַיּוֹשִׁעָן", "ואג'אתהן", "and aided them"),
        ("וַיַּשְׁקְ אֶת-צֹאנָם", "וסקי' ג'נמהן", "and watered their flock"),
    ],
    18: [
        ("וַתָּבֹאנָה אֶל-רְעוּאֵל אֲבִיהֶן",
         "פלמא גאת אלי' רעואל אביהן",
         "And when they came to Reuel their father"),
        ("וַיֹּאמֶר", "קאל", "he said"),
        ("מַדּוּעַ", "מא באלכן", "What is your concern"),
        ("מִהַרְתֶּן בֹּא הַיּוֹם", "אסרעתן באלמגי אליום",
         "that you have hurried to come today"),
    ],
    19: [
        ("וַתֹּאמַרְןָ", "פקאלא לה", "And they said to him"),
        ("אִישׁ מִצְרִי", "רגל מצרי", "An Egyptian man"),
        ("הִצִּילָנוּ", "כ'לצנא", "rescued us"),
        ("מִיַּד הָרֹעִים", "מן יד אלרעאה",
         "from the hand of the shepherds"),
        ("וְגַם-דָּלֹה דָלָה לָנוּ", "ואיצ'א דלא לנא מא",
         "and he also drew water for us"),
        ("וַיַּשְׁקְ אֶת-הַצֹּאן", "וסקי' אלג'נם", "and watered the flock"),
    ],
    20: [
        ("וַיֹּאמֶר אֶל-בְּנֹתָיו", "קאל לה'ן", "He said to his daughters"),
        ("וְאַיּוֹ", "ואין הו", "And where is he"),
        ("לָמָּה זֶּה עֲזַבְתֶּן אֶת-הָאִישׁ", "לם תרכתן אלרגל",
         "Why have you left the man"),
        ("קִרְאֶן לוֹ", "אדעוה", "Call him"),
        ("וְיֹאכַל לָחֶם", "יאכל טעאמא", "that he may eat a meal"),
    ],
    21: [
        ("וַיּוֹאֶל מֹשֶׁה", "פלמא אמען מוסי'", "And Moses consented"),
        ("לָשֶׁבֶת", "פי אלמקאם", "to dwell"),
        ("אֶת-הָאִישׁ", "ענד אלרגל", "with the man"),
        ("וַיִּתֵּן אֶת-צִפֹּרָה בִתּוֹ לְמֹשֶׁה", "זווגה בצפורה אבנתה",
         "and he gave him Zipporah his daughter [in marriage]"),
    ],
    22: [
        ("וַתֵּלֶד בֵּן", "פולדת אבנא", "And she bore a son"),
        ("וַיִּקְרָא אֶת-שְׁמוֹ גֵּרְשֹׁם", "וסמאה גרשום",
         "and he named him Gershom"),
        ("כִּי אָמַר", "לאנה קאל", "for he said"),
        ("גֵּר הָיִיתִי", "צרת ג'ריבא", "I became a stranger"),
        ("בְּאֶרֶץ נָכְרִיָּה", "פי בלד ג'רבה", "in a strange land"),
    ],
    23: [
        ("וַיְהִי בַיָּמִים הָרַבִּים הָהֵם",
         "וכאן איצ'א פי תלך אלאיאם אלטוילה",
         "And it was also in those long days"),
        ("וַיָּמָת מֶלֶךְ מִצְרַיִם", "אן מלך מצר מאת",
         "that the king of Egypt died"),
        ("וַיֵּאָנְחוּ בְנֵי-יִשְׂרָאֵל", "פתנהד בני אסראיל",
         "and the sons of Israel groaned"),
        ("מִן-הָעֲבֹדָה", "מן כ'דמתהם אלצעבה",
         "because of their hard service"),
        ("וַיִּזְעָקוּ", "וצרכ'ו", "and they cried out"),
        ("וַתַּעַל שַׁוְעָתָם", "פצעד תג'וותהם", "and their plea ascended"),
        ("אֶל-הָאֱלֹהִים", "אלי' אללה", "to God"),
        ("מִן-הָעֲבֹדָה", "מן אלכ'דמה", "from the [hard] service"),
    ],
    24: [
        ("וַיִּשְׁמַע אֱלֹהִים", "פסמע אללה", "And God heard"),
        ("אֶת-נַאֲקָתָם", "שהיקהם", "their groaning"),
        ("וַיִּזְכֹּר אֱלֹהִים אֶת-בְּרִיתוֹ", "וד'כר עהדה",
         "and remembered His covenant"),
        (None, "אלד'י מע", "which was with"),
        ("אֶת-אַבְרָהָם", "אברהים", "Abraham"),
        ("אֶת-יִצְחָק", "ויצחק", "Isaac"),
        ("וְאֶת-יַעֲקֹב", "ויעקוב", "and Jacob"),
    ],
    25: [
        ("וַיַּרְא אֱלֹהִים", "פנצ'ר אללה", "And God beheld"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "להם", "them"),
        ("וַיֵּדַע אֱלֹהִים", "ורחמהם", "and had mercy on them"),
    ],
}
