"""Hand-authored alignment triples for Shemot chapter 7."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה לה", "And God said to him"),
        ("רְאֵה", "אנצ'ר", "Look"),
        ("נְתַתִּיךָ אֱלֹהִים לְפַרְעֹה", "קד געלתך אסתאדא פי אמר פרעון",
         "I have made you a master in the matter of Pharaoh"),
        ("וְאַהֲרֹן אָחִיךָ יִהְיֶה נְבִיאֶךָ", "והרון אכ'יך יכון תרגמאנך",
         "and Aaron your brother shall be your spokesman"),
    ],
    2: [
        ("אַתָּה תְדַבֵּר אֵת כָּל-אֲשֶׁר אֲצַוֶּךָּ", "אנת תכלם הרון אכ'יך בגמיע מא אמרך בה",
         "You shall speak to Aaron your brother with all that I command you"),
        ("וְאַהֲרֹן אָחִיךָ יְדַבֵּר אֶל-פַּרְעֹה", "והרון אכ'יך יכלם פרעון",
         "and Aaron your brother shall speak to Pharaoh"),
        ("וְשִׁלַּח אֶת-בְּנֵי-יִשְׂרָאֵל מֵאַרְצוֹ", "ליטלק בני אסראיל מן בלדה",
         "that he may release the sons of Israel from his land"),
    ],
    3: [
        ("וַאֲנִי אַקְשֶׁה אֶת-לֵב פַּרְעֹה", "ואנא אצעב קלב פרעון",
         "And I shall harden the heart of Pharaoh"),
        ("וְהִרְבֵּיתִי אֶת-אֹתֹתַי וְאֶת-מוֹפְתַי", "ואכת'ר איאתי. ובראהיני",
         "and multiply My signs and My proofs"),
        ("בְּאֶרֶץ מִצְרָיִם", "פי בלד מצר", "in the land of Egypt"),
    ],
    4: [
        ("וְלֹא-יִשְׁמַע אֲלֵכֶם פַּרְעֹה", "ולא יקבל מנכם פרעון",
         "And Pharaoh shall not accept from you"),
        ("וְנָתַתִּי אֶת-יָדִי בְּמִצְרָיִם", "חתי' אחל אפתי באלמצריון",
         "until I bring My plagues upon the Egyptians"),
        ("וְהוֹצֵאתִי אֶת-צִבְאֹתַי אֶת-עַמִּי בְנֵי-יִשְׂרָאֵל מֵאֶרֶץ מִצְרַיִם",
         "ואכ'רג גיושי. קומי בני אסראיל מן בלד מצר",
         "and bring forth My hosts — My people, the sons of Israel — from the land of Egypt"),
        ("בִּשְׁפָטִים גְּדֹלִים", "באחכאם ]עט'ימה] עצ'ימה", "with great judgments"),
    ],
    5: [
        ("וְיָדְעוּ מִצְרַיִם כִּי-אֲנִי יְהוָה", "ויעלמון אלמצריון אני אללה",
         "And the Egyptians shall know that I am God"),
        ("בִּנְטֹתִי אֶת-יָדִי עַל-מִצְרָיִם", "אד'א אטלקת אפאתי עליהם",
         "when I release My plagues upon them"),
        ("וְהוֹצֵאתִי אֶת-בְּנֵי-יִשְׂרָאֵל מִתּוֹכָם", "ואכ'רגת בני אסראיל מן בינהם",
         "and bring out the sons of Israel from among them"),
    ],
    6: [
        ("וַיַּעַשׂ מֹשֶׁה וְאַהֲרֹן", "פצנע מוסי' והרון", "And Moses and Aaron did"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֹתָם", "כמא אמרהמא אללה", "as God had commanded them"),
        ("כֵּן עָשׂוּ", "כד'אך צנעו", "so they did"),
    ],
    7: [
        ("וּמֹשֶׁה בֶּן-שְׁמֹנִים שָׁנָה", "וכאן מוסי' אבן ת'מאנין סנה",
         "And Moses was eighty years of age"),
        ("וְאַהֲרֹן בֶּן-שָׁלֹשׁ וּשְׁמֹנִים שָׁנָה", "והרון אבן ת'לאת'ה ות'מאנין סנה",
         "and Aaron eighty-three years of age"),
        ("בְּדַבְּרָם אֶל-פַּרְעֹה", "חין כלמו פרעון",
         "when the two of them spoke to Pharaoh"),
    ],
    8: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר", "ת'ם קאל אללה. למוסי והרון קאילא",
         "Then God said to Moses and Aaron, saying"),
    ],
    9: [
        ("כִּי יְדַבֵּר אֲלֵכֶם פַּרְעֹה לֵאמֹר תְּנוּ לָכֶם מוֹפֵת",
         "כ) אד'א כלמכם פרעון. וקאל אעטוני ברהאנא",
         "When Pharaoh speaks to you and says: Give me a proof"),
        ("וְאָמַרְתָּ אֶל-אַהֲרֹן קַח אֶת-מַטְּךָ", "פקל להרון כ'ד עצאך",
         "then say to Aaron: Take your staff"),
        ("וְהַשְׁלֵךְ לִפְנֵי-פַרְעֹה--יְהִי לְתַנִּין", "ואטרחהא בין ידיה תציר תנינא",
         "and throw it before him; it shall become a serpent"),
    ],
    10: [
        ("וַיָּבֹא מֹשֶׁה וְאַהֲרֹן אֶל-פַּרְעֹה", "פדכ'ל מוסי' והרון אלי פרעון",
         "And Moses and Aaron went in to Pharaoh"),
        ("וַיַּעֲשׂוּ כֵן כַּאֲשֶׁר צִוָּה יְהוָה", "וצנעא כד'אך כמא קאל אללה",
         "and did so, as God had said"),
        ("וַיַּשְׁלֵךְ אַהֲרֹן אֶת-מַטֵּהוּ לִפְנֵי פַרְעֹה וְלִפְנֵי עֲבָדָיו",
         "וטרח הרון עצאה. בין ידי פרעון וקואדה",
         "and Aaron threw his staff before Pharaoh and his officers"),
        ("וַיְהִי לְתַנִּין", "פצארת תנינא", "and it became a serpent"),
    ],
    11: [
        ("וַיִּקְרָא גַּם-פַּרְעֹה לַחֲכָמִים וְלַמְכַשְּׁפִים",
         "ת'ם דעא פרעון. באלחכמא ואלסחרה",
         "Then Pharaoh called for the sages and the sorcerers"),
        ("וַיַּעֲשׂוּ גַם-הֵם חַרְטֻמֵּי מִצְרַיִם בְּלַהֲטֵיהֶם--כֵּן",
         "וצנעו כד'אך. עלמא מצר בכ'פיהם",
         "and the learned men of Egypt did the same with their secret arts"),
    ],
    12: [
        ("וַיַּשְׁלִיכוּ אִישׁ מַטֵּהוּ וַיִּהְיוּ לְתַנִּינִם",
         "טרח כל רגל עצאה. פצארת כאלתנאנין",
         "Each man threw his staff, and they became like serpents"),
        ("וַיִּבְלַע מַטֵּה-אַהֲרֹן אֶת-מַטֹּתָם", "פאבתלעת עצא הרון עצייהם",
         "but Aaron's staff swallowed their staves"),
    ],
    13: [
        ("וַיֶּחֱזַק לֵב פַּרְעֹה", "פאשתד קלב פרעון", "And Pharaoh's heart was hardened"),
        ("וְלֹא שָׁמַע אֲלֵהֶם", "ולם יקבל מנהמא", "and he did not accept from them"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה", "כמא קאל אללה", "as God had said"),
    ],
    14: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'", "And God said to Moses"),
        ("כָּבֵד לֵב פַּרְעֹה", "קד ת'קל קלב פרעון", "The heart of Pharaoh has grown heavy"),
        ("מֵאֵן לְשַׁלַּח הָעָם", "ואבא אן יטלק אלקום", "and he has refused to release the people"),
    ],
    15: [
        ("לֵךְ אֶל-פַּרְעֹה בַּבֹּקֶר", "אמץ' אליה באלג'דאה", "Go to him in the morning"),
        ("הִנֵּה יֹצֵא הַמַּיְמָה", "הוד'אה כ'ארג אלי' אלמא",
         "behold, he is going out to the water"),
        ("וְנִצַּבְתָּ לִקְרָאתוֹ עַל-שְׂפַת הַיְאֹר",
         "וקף תלקאה עלי' שאטי אלניל",
         "and stand to meet him on the shore of the Nile"),
        ("וְהַמַּטֶּה אֲשֶׁר-נֶהְפַּךְ לְנָחָשׁ תִּקַּח בְּיָדֶךָ",
         "ואלעצא. אלד'י אנקלבת ת'עבאנא כ'ד'הא בידך",
         "and the staff which turned into a serpent, take it in your hand"),
    ],
    16: [
        ("וְאָמַרְתָּ אֵלָיו", "וקל לה", "And say to him"),
        ("יְהוָה אֱלֹהֵי הָעִבְרִים שְׁלָחַנִי אֵלֶיךָ", "אללה אלאה אלעבראניין בעת'ני אליך",
         "God, the God of the Hebrews, has sent me to you"),
        ("שַׁלַּח אֶת-עַמִּי", "אטלק קומי", "Release my people"),
        ("וְיַעַבְדֻנִי בַּמִּדְבָּר", "יעבדוני פי אלבר",
         "that they may serve me in the open country"),
        ("וְהִנֵּה לֹא-שָׁמַעְתָּ עַד-כֹּה", "והוד'אך לם תקבל אלי' אלאן",
         "and behold, you have not accepted until now"),
    ],
    17: [
        ("כֹּה אָמַר יְהוָה", "כד'א קאל אללה", "Thus says God"),
        ("בְּזֹאת תֵּדַע כִּי אֲנִי יְהוָה", "בהד'ה אלכ'לה תעלם. אני אללה אלמעאקב",
         "By this means shall you know that I am God, the One who punishes"),
        ("הִנֵּה אָנֹכִי מַכֶּה בַּמַּטֶּה אֲשֶׁר-בְּיָדִי",
         "האנא צ'ארב באלעצא אלתי פי ידי",
         "behold, I am striking with the staff that is in my hand"),
        ("עַל-הַמַּיִם אֲשֶׁר בַּיְאֹר--וְנֶהֶפְכוּ לְדָם",
         "אלמא אלד'י פי אלניל פינקלב דמא",
         "the water which is in the Nile, and it shall turn to blood"),
    ],
    18: [
        ("וְהַדָּגָה אֲשֶׁר-בַּיְאֹר תָּמוּת", "ואלסמך אלד'י פי אלניל . יתמאות",
         "And the fish that are in the Nile shall perish"),
        ("וּבָאַשׁ הַיְאֹר", "וינתן אלניל", "and the Nile shall stink"),
        ("וְנִלְאוּ מִצְרַיִם לִשְׁתּוֹת מַיִם מִן-הַיְאֹר",
         "ויעגז אלמצריון. אן ישרבון מאא מן אלניל",
         "and the Egyptians shall be unable to drink water from the Nile"),
    ],
    19: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "ת'ם קאל אללה למוסי", "Then God said to Moses"),
        ("אֱמֹר אֶל-אַהֲרֹן קַח מַטְּךָ", "קל להרון. כ'ד' עצאך", "Say to Aaron: Take your staff"),
        ("וּנְטֵה-יָדְךָ עַל-מֵימֵי מִצְרַיִם עַל-נַהֲרֹתָם עַל-יְאֹרֵיהֶם וְעַל-אַגְמֵיהֶם",
         "ומד ידך עלי' מיאת אלמצריון. ואנהארהם וכ'לגאנהם ואגאמהם",
         "and stretch out your hand over the waters of the Egyptians — over their rivers and their inlets and their marshes"),
        ("וְעַל כָּל-מִקְוֵה מֵימֵיהֶם--וְיִהְיוּ-דָם",
         "וסאיר מלאם מיאהם פתציר דמא",
         "and the rest of the gatherings of their waters — that they may turn to blood"),
        ("וְהָיָה דָם בְּכָל-אֶרֶץ מִצְרַיִם וּבָעֵצִים וּבָאֲבָנִים",
         "ויכון דם פי גמיע בלד מצר. ופי אואני אלכ'שב ואלחגארה",
         "and there shall be blood throughout all the land of Egypt, and in vessels of wood and of stone"),
    ],
    21: [
        ("וְהַדָּגָה אֲשֶׁר-בַּיְאֹר מֵתָה", "ואלסמך אלד'י פי אלניל תמאות",
         "And the fish that were in the Nile perished"),
        ("וַיִּבְאַשׁ הַיְאֹר", "ונתן אלניל", "and the Nile stank"),
        ("וְלֹא-יָכְלוּ מִצְרַיִם לִשְׁתּוֹת מַיִם מִן-הַיְאֹר",
         "ועגז אלמצריון. אן ישרבו מנה מאא",
         "and the Egyptians were unable to drink water from it"),
        ("וַיְהִי הַדָּם בְּכָל-אֶרֶץ מִצְרָיִם", "פצאר אלדם פי גמיע בלד מצר",
         "and blood was throughout all the land of Egypt"),
    ],
    22: [
        ("וַיַּעֲשׂוּ-כֵן חַרְטֻמֵּי מִצְרַיִם בְּלָטֵיהֶם",
         "פצנע כד'אך עלמא מצר בכ'פיהום",
         "And the learned men of Egypt did the same with their secret arts"),
        ("וַיֶּחֱזַק לֵב-פַּרְעֹה", "פאשתד קלב פרעון",
         "and Pharaoh's heart was hardened"),
        ("וְלֹא-שָׁמַע אֲלֵהֶם", "ולם יקבל מנהמא", "and he did not accept from them"),
        ("כַּאֲשֶׁר דִּבֶּר יְהוָה", "כמא קאל אללה", "as God had said"),
    ],
    23: [
        ("וַיִּפֶן פַּרְעֹה וַיָּבֹא אֶל-בֵּיתוֹ", "ת'ם ולא פרעון. ודכ'ל אלי' מנזלה",
         "Then Pharaoh turned away and entered his house"),
        ("וְלֹא-שָׁת לִבּוֹ גַּם-לָזֹאת", "ולם ירד באלה אלי' הד'א איצ'א",
         "and did not set his mind to this either"),
    ],
    24: [
        ("וַיַּחְפְּרוּ כָל-מִצְרַיִם סְבִיבֹת הַיְאֹר מַיִם לִשְׁתּוֹת",
         "ואחתפר גמיע אלמצריון. חואלי אלניל אבארא לישרבו מנהא",
         "And all the Egyptians dug wells around the Nile to drink from them"),
        ("כִּי לֹא יָכְלוּ לִשְׁתֹּת מִמֵּימֵי הַיְאֹר",
         "אד' לם יטיקו אן ישרבו. מן מא אלניל",
         "since they could not bear to drink from the water of the Nile"),
    ],
    25: [
        ("וַיִּמָּלֵא שִׁבְעַת יָמִים", "ולמא כמלת סבעה' איאם",
         "And when seven days had been completed"),
        ("אַחֲרֵי הַכּוֹת-יְהוָה אֶת-הַיְאֹר", "בעד מא צ'רב אללה אלניל בד'אלך",
         "after God had struck the Nile — thereafter"),
    ],
    26: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'", "God said to Moses"),
        ("בֹּא אֶל-פַּרְעֹה", "אדכ'ל אלי פרעון", "Go in to Pharaoh"),
        ("וְאָמַרְתָּ אֵלָיו כֹּה אָמַר יְהוָה", "וקל לה. כד'א קאל אללה",
         "and say to him: Thus says God"),
        ("שַׁלַּח אֶת-עַמִּי וְיַעַבְדֻנִי", "אטלק קומי יעבדוני",
         "release my people, that they may serve me"),
    ],
    27: [
        ("וְאִם-מָאֵן אַתָּה לְשַׁלֵּחַ", "פאן אבית אן תטלקהום",
         "And if you refuse to release them"),
        ("הִנֵּה אָנֹכִי נֹגֵף אֶת-כָּל-גְּבוּלְךָ--בַּצְפַרְדְּעִים",
         "האנא צאדם תכ'מך באלצ'פאדע",
         "behold, I am about to strike your territory with frogs"),
    ],
    28: [
        ("וְשָׁרַץ הַיְאֹר צְפַרְדְּעִים", "ותסעי מן אלניל אלצ'פאדע",
         "And the frogs shall move forth from the Nile"),
        ("וְעָלוּ וּבָאוּ בְּבֵיתֶךָ וּבַחֲדַר מִשְׁכָּבְךָ וְעַל-מִטָּתֶךָ",
         "ותצעד ותדכ'ל פי ביתך. ופי כ'דר מצ'געך ועלי' סרירך",
         "and shall ascend and enter into your house, and into the inner chamber of your bed and upon your bed"),
        ("וּבְבֵית עֲבָדֶיךָ", "ופי תנאנירך", "and into your ovens"),
        ("וּבְתַנּוּרֶיךָ וּבְמִשְׁאֲרוֹתֶיךָ", "ומעאגנך",
         "and your kneading-troughs"),
    ],
    29: [
        ("וּבְכָה וּבְעַמְּךָ וּבְכָל-עֲבָדֶיךָ", "ופי גסמך וגסם קומך וקואדך",
         "And upon your person and upon the person of your people and your officers"),
        ("יַעֲלוּ הַצְפַרְדְּעִים", "תצעד אלצ'פאדע", "the frogs shall ascend"),
    ],
}
