"""Hand-authored alignment triples for Shemot chapter 13."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, a [full] speaking."),
    ],
    2: [
        ("קַדֶּשׁ-לִי כָל-בְּכוֹר", "אקדס לי כל בכר",
         "Consecrate to Me every firstborn"),
        ("פֶּטֶר כָּל-רֶחֶם", "פאתח כל בטן",
         "the first to open every womb"),
        ("בִּבְנֵי יִשְׂרָאֵל", "מן בני אסראיל",
         "among the sons of Israel"),
        ("בָּאָדָם וּבַבְּהֵמָה לִי הוּא", "מן אלנאס ואלבהאים. לי הם",
         "of humans and of beasts — they are Mine."),
    ],
    3: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָעָם", "פקאל מוסי' לאלקום",
         "And Moses said to the people"),
        ("זָכוֹר אֶת-הַיּוֹם הַזֶּה", "אד'כרו הד'א אליום",
         "Remember this day"),
        ("אֲשֶׁר יְצָאתֶם מִמִּצְרַיִם", "אלד'י כ'רגתם פיה מן מצר",
         "on which you went out from Egypt"),
        ("מִבֵּית עֲבָדִים", "מן בית אלעבודייה",
         "from the house of bondage"),
        ("כִּי בְּחֹזֶק יָד הוֹצִיא יְהוָה אֶתְכֶם מִזֶּה", "לאן בשדה' יד. אכ'רגכם אללה מן ההנא",
         "for it was by strength of hand that God brought you out from here"),
        ("וְלֹא יֵאָכֵל חָמֵץ", "ולא יוכל כ'מירא",
         "and no leavened bread shall be eaten."),
    ],
    4: [
        ("הַיּוֹם אַתֶּם יֹצְאִים", "אליום אנתם כ'ראגין",
         "Today you are going out"),
        ("בְּחֹדֶשׁ הָאָבִיב", "פי שהר אלפריך",
         "in the month of the roasted grain."),
    ],
    5: [
        ("וְהָיָה כִי-יְבִיאֲךָ יְהוָה", "וכמא ידכ'לך אללה",
         "And when God brings you"),
        ("אֶל-אֶרֶץ הַכְּנַעֲנִי וְהַחִתִּי וְהָאֱמֹרִי וְהַחִוִּי וְהַיְבוּסִי",
         "אלי' בלד אלכנעאניין. ואלחתיין ואלאמוריין ואלחויין ואליבוסיין",
         "into the land of the Canaanites, and the Hittites, and the Amorites, and the Hivites, and the Jebusites"),
        ("אֲשֶׁר נִשְׁבַּע לַאֲבֹתֶיךָ לָתֶת לָךְ", "כמא אקסם לאבאיאך אן יעטיכאה",
         "as He swore to your fathers that He would give it to you"),
        ("אֶרֶץ זָבַת חָלָב וּדְבָשׁ", "בלד יפיץ' אללבן ואלעסל",
         "a land flowing with milk and honey"),
        ("וְעָבַדְתָּ אֶת-הָעֲבֹדָה הַזֹּאת בַּחֹדֶשׁ הַזֶּה", "פאצנע הד'ה אלצנעה פי הד'א אלשהר",
         "then you shall perform this observance in this month."),
    ],
    6: [
        ("שִׁבְעַת יָמִים תֹּאכַל מַצֹּת", "סבעה' איאם כל פטירא",
         "Seven days eat unleavened bread"),
        ("וּבַיּוֹם הַשְּׁבִיעִי חַג לַיהוָה", "ואליום אלסאבע חג ללה",
         "and the seventh day is a festival to God."),
    ],
    7: [
        ("מַצּוֹת יֵאָכֵל אֵת שִׁבְעַת הַיָּמִים", "ואד'א יוכל פטירא. פי הד'ה אלסבעה' אלאיאם",
         "And unleavened bread shall be eaten during these seven days"),
        ("וְלֹא-יֵרָאֶה לְךָ חָמֵץ", "פלא ירא לך כ'מיר",
         "no leavened bread shall be seen in your possession"),
        ("וְלֹא-יֵרָאֶה לְךָ שְׂאֹר--בְּכָל-גְּבֻלֶךָ", "ולא מכמר פי גמיע תכ'מך",
         "nor any leavening agent, in all your territory."),
    ],
    8: [
        ("וְהִגַּדְתָּ לְבִנְךָ בַּיּוֹם הַהוּא לֵאמֹר", "ואכ'בר אבנך. פי ד'אלך אליום קאילא",
         "And you shall tell your son on that day, saying"),
        ("בַּעֲבוּר זֶה עָשָׂה יְהוָה לִי בְּצֵאתִי מִמִּצְרָיִם",
         "הד'א בסבב מא צנע אללה לי. פי כ'רוגי מן מצר",
         "This is on account of what God did for me when I went out from Egypt."),
    ],
    9: [
        ("וְהָיָה לְךָ לְאוֹת עַל-יָדְךָ", "וליכון לך איה עלי' ידך",
         "And it shall be for you as a sign upon your hand"),
        ("וּלְזִכָּרוֹן בֵּין עֵינֶיךָ", "וד'כרא בין עיניך",
         "and as a remembrance between your eyes"),
        ("לְמַעַן תִּהְיֶה תּוֹרַת יְהוָה בְּפִיךָ", "לכי תכון שריעה' אללה פי פאך",
         "so that the law of God may be in your mouth"),
        ("כִּי בְּיָד חֲזָקָה הוֹצִאֲךָ יְהוָה מִמִּצְרָיִם",
         "לאן ביד שדידה. אכ'רגך אללה מן מצר",
         "for it was by a mighty hand that God brought you out from Egypt."),
    ],
    10: [
        ("וְשָׁמַרְתָּ אֶת-הַחֻקָּה הַזֹּאת לְמוֹעֲדָהּ", "ואחפץ' הד'א אלרסם פי וקתה",
         "And observe this ordinance at its appointed time"),
        ("מִיָּמִים יָמִימָה", "מן חול אלי' חול",
         "from year to year."),
    ],
    11: [
        ("וְהָיָה כִּי-יְבִאֲךָ יְהוָה אֶל-אֶרֶץ הַכְּנַעֲנִי", "וכד'אך אד'א אדכ'לך אללה אלי' בלד אלכנעאניין",
         "And so it shall be when God brings you into the land of the Canaanites"),
        ("כַּאֲשֶׁר נִשְׁבַּע לְךָ וְלַאֲבֹתֶיךָ", "כמי' קסם לך ולאבאיך",
         "as He swore to you and to your fathers"),
        ("וּנְתָנָהּ לָךְ", "ואעטאה לך",
         "and gives it to you"),
    ],
    12: [
        ("וְהַעֲבַרְתָּ כָל-פֶּטֶר-רֶחֶם לַיהוָה", "פאעזל כל פאתח בטן ללה",
         "set apart every firstborn of the womb for God"),
        ("וְכָל-פֶּטֶר שֶׁגֶר בְּהֵמָה אֲשֶׁר יִהְיֶה לְךָ הַזְּכָרִים--לַיהוָה",
         "וכל אוול נתאג אלבהאים אלד'י יכון לך מן אלדכור ללה",
         "and every first issue of the beasts that shall be yours, of the males — for God."),
    ],
    13: [
        ("וְכָל-פֶּטֶר חֲמֹר תִּפְדֶּה בְשֶׂה", "ובכר אלחמיר אפדה בשאה",
         "And every firstborn of donkeys you shall redeem with a sheep"),
        ("וְאִם-לֹא תִפְדֶּה וַעֲרַפְתּוֹ", "ואן לם תפדה פאקפה",
         "and if you do not redeem it, then break its neck"),
        ("וְכֹל בְּכוֹר אָדָם בְּבָנֶיךָ תִּפְדֶּה", "וכל בכר ד'כר. מן בניך פאפדה",
         "And every firstborn male among your sons you shall redeem."),
    ],
    14: [
        ("וְהָיָה כִּי-יִשְׁאָלְךָ בִנְךָ מָחָר--לֵאמֹר מַה-זֹּאת",
         "ואד'א סאלך אבנך. ג'דא קאילא מא הד'א",
         "And when your son asks you tomorrow, saying: 'What is this?'"),
        ("וְאָמַרְתָּ אֵלָיו--בְּחֹזֶק יָד הוֹצִיאָנוּ יְהוָה",
         "פקל לה. בשדה' יד. אכ'רגנא אללה",
         "then say to him: 'By strength of hand God brought us out"),
        ("מִמִּצְרַיִם מִבֵּית עֲבָדִים", "מן מצר מן בית אלעבודייה",
         "from Egypt, from the house of bondage."),
    ],
    15: [
        ("וַיְהִי כִּי-הִקְשָׁה פַרְעֹה לְשַׁלְּחֵנוּ", "פלמא תצעב פרעון פי אן יטלקנא",
         "For when Pharaoh was stubborn about releasing us"),
        ("וַיַּהֲרֹג יְהוָה כָּל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם", "קתל אללה כל בכר פי בלד מצר",
         "God slew every firstborn in the land of Egypt"),
        ("מִבְּכֹר אָדָם וְעַד-בְּכוֹר בְּהֵמָה", "מן בכור אלנאס אלי' בכור אלבהאים",
         "from the firstborn of humans to the firstborn of beasts"),
        ("עַל-כֵּן אֲנִי זֹבֵחַ לַיהוָה כָּל-פֶּטֶר רֶחֶם הַזְּכָרִים",
         "לד'אלך אנא ד'אבח ללה. כל פאתח בטן מן בכור אלבהאים",
         "therefore I sacrifice to God every firstborn of the womb from the firstborn of the beasts"),
        ("וְכָל-בְּכוֹר בָּנַי אֶפְדֶּה", "וגמיע בכור בניי אפדיהם",
         "and all the firstborn of my sons I redeem."),
    ],
    16: [
        ("וְהָיָה לְאוֹת עַל-יָדְכָה", "פתכון איה עלי' ידך",
         "And it shall be as a sign upon your hand"),
        ("וּלְטוֹטָפֹת בֵּין עֵינֶיךָ", "ומנשורא בין עיניך",
         "and displayed between your eyes"),
        ("כִּי בְּחֹזֶק יָד הוֹצִיאָנוּ יְהוָה מִמִּצְרָיִם",
         "לאן בשדה' יד. אכ'רגנא אללה מן מצר",
         "for it was by strength of hand that God brought us out from Egypt."),
    ],
    17: [
        ("וַיְהִי בְּשַׁלַּח פַּרְעֹה אֶת-הָעָם", "פכאן למא אטלק פרעון אלקום",
         "And it was, when Pharaoh released the people"),
        ("וְלֹא-נָחָם אֱלֹהִים דֶּרֶךְ אֶרֶץ פְּלִשְׁתִּים כִּי קָרוֹב הוּא",
         "אן אללה לם יסיירהם טריק בלד פלסטין. לאנה קריב",
         "that God did not lead them by the road of the land of the Philistines, although it was near"),
        ("כִּי אָמַר אֱלֹהִים פֶּן-יִנָּחֵם הָעָם בִּרְאֹתָם מִלְחָמָה--וְשָׁבוּ מִצְרָיְמָה",
         "לאן אללה קאל. כלא ינדם אלקום. אד'א ראו אלחרב פירגעו אלי' מצר",
         "for God said: 'Lest the people regret, when they see war, and return to Egypt.'"),
    ],
    18: [
        ("וַיַּסֵּב אֱלֹהִים אֶת-הָעָם דֶּרֶךְ הַמִּדְבָּר יַם-סוּף",
         "פאדארהם אללה. טריק אלבר אלי' בחר אלקלזם",
         "And God turned them by the road of the wilderness toward the Sea of Qulzum (Red Sea)"),
        ("וַחֲמֻשִׁים עָלוּ בְנֵי-יִשְׂרָאֵל מֵאֶרֶץ מִצְרָיִם",
         "ומתעביין. צעדו בני אסראיל מן בלד מצר",
         "and in battle formation the sons of Israel went up from the land of Egypt."),
    ],
    19: [
        ("וַיִּקַּח מֹשֶׁה אֶת-עַצְמוֹת יוֹסֵף עִמּוֹ", "פאכ'ד מוסי. עצ'אם יוסף מעה",
         "And Moses took the bones of Joseph with him"),
        ("כִּי הַשְׁבֵּעַ הִשְׁבִּיעַ אֶת-בְּנֵי יִשְׂרָאֵל לֵאמֹר",
         "לאנה כאן אחלף בני אסראיל קאילא",
         "for he had made the sons of Israel swear, saying"),
        ("פָּקֹד יִפְקֹד אֱלֹהִים אֶתְכֶם", "אד'א ד'כרכם אללה",
         "When God remembers you"),
        ("וְהַעֲלִיתֶם אֶת-עַצְמֹתַי מִזֶּה אִתְּכֶם", "פאצעדו בעצ'אמי מן ההני מעכם",
         "then bring up my bones from here with you."),
    ],
    20: [
        ("וַיִּסְעוּ מִסֻּכֹּת", "פלמא רחלו מן סכות", "And when they set out from Sukkot"),
        ("וַיַּחֲנוּ בְאֵתָם בִּקְצֵה הַמִּדְבָּר", "נזלו פי איתם. פי טרף אלברייה",
         "they encamped at Etham, at the edge of the wilderness."),
    ],
    21: [
        ("וַיהוָה הֹלֵךְ לִפְנֵיהֶם יוֹמָם בְּעַמּוּד עָנָן לַנְחֹתָם הַדֶּרֶךְ",
         "ואללה סאיר בין ידיהם נהארא. בעמוד מן ג'מאם לידלהם עלי' אלטריק",
         "And God was going before them by day in a pillar of cloud, to guide them on the road"),
        ("וְלַיְלָה בְּעַמּוּד אֵשׁ לְהָאִיר לָהֶם", "ופי אלליל בעמוד מן נאר ליצ'י להם",
         "and by night in a pillar of fire, to give them light"),
        ("לָלֶכֶת יוֹמָם וָלָיְלָה", "פיסירו נהארא ולילא",
         "so that they could travel by day and by night."),
    ],
    22: [
        ("לֹא-יָמִישׁ עַמּוּד הֶעָנָן יוֹמָם", "לא יזול עמוד אלג'מאם נהארא",
         "The pillar of cloud did not depart by day"),
        ("וְעַמּוּד הָאֵשׁ לָיְלָה--לִפְנֵי הָעָם", "ועמוד אלנאר לילא. מן בין ידי אלקום",
         "nor the pillar of fire by night, from before the people."),
    ],
}
