"""Hand-authored alignment triples for Shemot chapter 24."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאֶל-מֹשֶׁה אָמַר", "ת'ם קאל למוסי'", "Then He said to Moses"),
        ("עֲלֵה אֶל-יְהוָה אַתָּה וְאַהֲרֹן נָדָב וַאֲבִיהוּא",
         "אצעד אלי' אללה. אנת והרון נדב ואביהוא",
         "'Go up to God — you, and Aaron, Nadab and Abihu"),
        ("וְשִׁבְעִים מִזִּקְנֵי יִשְׂרָאֵל", "וסבעין מן שיוך' בני אסראיל",
         "and seventy of the elders of the sons of Israel"),
        ("וְהִשְׁתַּחֲוִיתֶם מֵרָחֹק", "ואסגדו מן בעיד",
         "and bow down from afar."),
    ],
    2: [
        ("וְנִגַּשׁ מֹשֶׁה לְבַדּוֹ אֶל-יְהוָה", "ויתקדם מוסי' וחדה אלי' אללה",
         "And Moses alone shall draw near to God"),
        ("וְהֵם לֹא יִגָּשׁוּ", "והם לא יתקדמון", "but they shall not draw near"),
        ("וְהָעָם לֹא יַעֲלוּ עִמּוֹ", "ואלקום. לא יצעדו מעה",
         "and the people shall not go up with him."),
    ],
    3: [
        ("וַיָּבֹא מֹשֶׁה וַיְסַפֵּר לָעָם אֵת כָּל-דִּבְרֵי יְהוָה וְאֵת כָּל-הַמִּשְׁפָּטִים",
         "פגא מוסי'. וקץ עלי' אלקום גמיע כלאם אללה. וגמיע אלאחכאם",
         "And Moses came and recounted to the people all the words of God and all the ordinances"),
        ("וַיַּעַן כָּל-הָעָם קוֹל אֶחָד וַיֹּאמְרוּ",
         "פאגאבה גמיע אלקום. בצות ואחד וקאלו",
         "and all the people answered with one voice and said"),
        ("כָּל-הַדְּבָרִים אֲשֶׁר-דִּבֶּר יְהוָה נַעֲשֶׂה",
         "גמיע אלכלאם. אלד'י אמר אללה נצנעה",
         "'All the words which God has commanded, we shall do."),
    ],
    4: [
        ("וַיִּכְתֹּב מֹשֶׁה אֵת כָּל-דִּבְרֵי יְהוָה", "פכתב מוסי' גמיע כלאם אללה",
         "And Moses wrote down all the words of God"),
        ("וַיַּשְׁכֵּם בַּבֹּקֶר", "ואדלג באלג'דאה",
         "and he rose early in the morning"),
        ("וַיִּבֶן מִזְבֵּחַ תַּחַת הָהָר", "ובנא מד'בח פי תחת אלגבל",
         "and built an altar at the foot of the mountain"),
        ("וּשְׁתֵּים עֶשְׂרֵה מַצֵּבָה לִשְׁנֵים עָשָׂר שִׁבְטֵי יִשְׂרָאֵל",
         "ואת'ני עשר דכה. באזא את'ני עשר אסבאט אסראיל",
         "and twelve platforms, corresponding to the twelve tribes of Israel."),
    ],
    5: [
        ("וַיִּשְׁלַח אֶת-נַעֲרֵי בְּנֵי יִשְׂרָאֵל", "ובעת' בכור בני אסראיל",
         "And he sent the firstborn of the sons of Israel"),
        ("וַיַּעֲלוּ עֹלֹת", "וקרבו צואעדא", "and they brought up offerings"),
        ("וַיִּזְבְּחוּ זְבָחִים שְׁלָמִים לַיהוָה--פָּרִים",
         "וד'בחו ד'באיח סלאמה. ללה מן אלבקר",
         "and slaughtered peace-offerings to God from the cattle."),
    ],
    6: [
        ("וַיִּקַּח מֹשֶׁה חֲצִי הַדָּם וַיָּשֶׂם בָּאַגָּנֹת",
         "פאכ'ד' מוסי' בעץ' אלדם. וגעלה פי אגאגין ודפנה",
         "And Moses took some of the blood, and placed it in basins and buried it"),
        ("וַחֲצִי הַדָּם זָרַק עַל-הַמִּזְבֵּחַ", "ובאקיה רשה עלי' אלמד'בח",
         "and the remainder of it he sprinkled upon the altar."),
    ],
    7: [
        ("וַיִּקַּח סֵפֶר הַבְּרִית", "ואכ'ד' כתאב אלעהד",
         "And he took the book of the covenant"),
        ("וַיִּקְרָא בְּאָזְנֵי הָעָם", "וקראה עלי' אלקום",
         "and read it aloud to the people"),
        ("וַיֹּאמְרוּ כֹּל אֲשֶׁר-דִּבֶּר יְהוָה נַעֲשֶׂה וְנִשְׁמָע",
         "וקאלו גמיע מא אמר אללה נקבלה ונצנעה",
         "and they said: 'All that God has commanded, we shall accept and do."),
    ],
    8: [
        ("וַיִּקַּח מֹשֶׁה אֶת-הַדָּם וַיִּזְרֹק עַל-הָעָם",
         "ואכ'ד' מוסי' מן אלדם. ורשה עלי אלקום",
         "And Moses took some of the blood, and sprinkled it upon the people"),
        ("וַיֹּאמֶר הִנֵּה דַם-הַבְּרִית", "וקאל. הד'א דם אלעהד",
         "and said: 'This is the blood of the covenant"),
        ("אֲשֶׁר כָּרַת יְהוָה עִמָּכֶם", "אלד'י עהדה אללה מעכם",
         "which God has made with you"),
        ("עַל כָּל-הַדְּבָרִים הָאֵלֶּה", "עלי גמיע הד'ה אלאחכאם",
         "concerning all these ordinances."),
    ],
    9: [
        ("וַיַּעַל מֹשֶׁה וְאַהֲרֹן", "ת'ם צעד מוסי' והרון",
         "Then Moses and Aaron went up"),
        ("נָדָב וַאֲבִיהוּא", "נדב ואביהוא", "Nadab and Abihu"),
        ("וְשִׁבְעִים מִזִּקְנֵי יִשְׂרָאֵל", "וסבעין מן שיוך' בני אסראיל",
         "and seventy of the elders of the sons of Israel."),
    ],
    10: [
        ("וַיִּרְאוּ אֵת אֱלֹהֵי יִשְׂרָאֵל", "פנצ'רו נור אלאה אסראיל",
         "And they beheld the light of the God of Israel"),
        ("וְתַחַת רַגְלָיו כְּמַעֲשֵׂה לִבְנַת הַסַּפִּיר",
         "ומן דונה. כצנעה' ביאץ' אלמהא",
         "and beneath it was like a fashioning of the whiteness of sapphire"),
        ("וּכְעֶצֶם הַשָּׁמַיִם לָטֹהַר", "וכד'את אלסמא פי אלנקא",
         "and like the very sky in its purity."),
    ],
    11: [
        ("וְאֶל-אֲצִילֵי בְּנֵי יִשְׂרָאֵל לֹא שָׁלַח יָדוֹ",
         "ועלי' נקבא בני אסראיל. לם יבעת' אפתה",
         "And upon the chosen ones of the sons of Israel He did not send His affliction"),
        ("וַיֶּחֱזוּ אֶת-הָאֱלֹהִים", "פנצ'רו נור אללה ועאשו",
         "and they beheld the light of God and lived"),
        ("וַיֹּאכְלוּ וַיִּשְׁתּוּ", "ואכלו ושרבו", "and they ate and drank."),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה", "פקאל אללה למוסי'",
         "And God said to Moses"),
        ("עֲלֵה אֵלַי הָהָרָה--וֶהְיֵה-שָׁם", "אצעד אליי אלי' אלגבל וקם ת'ם",
         "'Go up to Me to the mountain, and remain there"),
        ("וְאֶתְּנָה לְךָ אֶת-לֻחֹת הָאֶבֶן", "אעטיך לוחי אלגוהר",
         "I shall give you the two tablets of gem"),
        ("וְהַתּוֹרָה וְהַמִּצְוָה אֲשֶׁר כָּתַבְתִּי לְהוֹרֹתָם",
         "ואלשראיע ואלוצאיא. אלד'י כתבתהא לאדלהם בהא",
         "and the laws and the commandments which I have written, to guide them by them."),
    ],
    13: [
        ("וַיָּקָם מֹשֶׁה וִיהוֹשֻׁעַ מְשָׁרְתוֹ", "פקאם מוסי' ויהושע כ'אדמה",
         "And Moses arose, and Joshua his attendant"),
        ("וַיַּעַל מֹשֶׁה אֶל-הַר הָאֱלֹהִים", "וצעד מוסי' אלי' גבל אללה",
         "and Moses went up to the mountain of God."),
    ],
    14: [
        ("וְאֶל-הַזְּקֵנִים אָמַר", "וקאל לאלשיוך'",
         "And he said to the elders"),
        ("שְׁבוּ-לָנוּ בָזֶה עַד אֲשֶׁר-נָשׁוּב אֲלֵיכֶם",
         "אגלסו לנא ההנא. אלי' אן נרגע אליכם",
         "'Sit here for us until we return to you"),
        ("וְהִנֵּה אַהֲרֹן וְחוּר עִמָּכֶם", "והוד'י הרון וחור מעכם",
         "and behold, Aaron and Hur are with you"),
        ("מִי-בַעַל דְּבָרִים יִגַּשׁ אֲלֵהֶם", "מן כאן לה אמר תקדם אליהם",
         "whoever has a matter, let him approach them."),
    ],
    15: [
        ("וַיַּעַל מֹשֶׁה אֶל-הָהָר", "פצעד מוסי' אלי' אלגבל",
         "And Moses went up to the mountain"),
        ("וַיְכַס הֶעָנָן אֶת-הָהָר", "פג'טא אלג'מאם אלגבל",
         "and the cloud covered the mountain."),
    ],
    16: [
        ("וַיִּשְׁכֹּן כְּבוֹד-יְהוָה עַל-הַר סִינַי", "וסכן נור אללה עלי' גבל סיני",
         "And the light of God settled upon Mount Sinai"),
        ("וַיְכַסֵּהוּ הֶעָנָן שֵׁשֶׁת יָמִים", "וג'טאה אלג'מאם סת איאם",
         "and the cloud covered it six days"),
        ("וַיִּקְרָא אֶל-מֹשֶׁה בַּיּוֹם הַשְּׁבִיעִי מִתּוֹךְ הֶעָנָן",
         "ודעא במוסי'. פי אליום אלסאבע מן וסט אלג'מאם",
         "and He called to Moses on the seventh day from within the cloud."),
    ],
    17: [
        ("וּמַרְאֵה כְּבוֹד יְהוָה כְּאֵשׁ אֹכֶלֶת",
         "וכאן רויא נור אללה. כנאר אכאלה",
         "And the appearance of the light of God was like a consuming fire"),
        ("בְּרֹאשׁ הָהָר", "פי ראס אלגבל", "at the top of the mountain"),
        ("לְעֵינֵי בְּנֵי יִשְׂרָאֵל", "בחצ'רה' בני אסראיל",
         "in the presence of the sons of Israel."),
    ],
    18: [
        ("וַיָּבֹא מֹשֶׁה בְּתוֹךְ הֶעָנָן", "אד' דכ'ל מוסי' פי וסט אלג'מאם",
         "When Moses entered into the midst of the cloud"),
        ("וַיַּעַל אֶל-הָהָר", "למא צעד אלי' אלגבל",
         "upon going up to the mountain"),
        ("וַיְהִי מֹשֶׁה בָּהָר אַרְבָּעִים יוֹם וְאַרְבָּעִים לָיְלָה",
         "אקאם פיה ארבעין יום. וארבעין לילה",
         "he remained in it forty days and forty nights."),
    ],
}
