"""Hand-authored alignment triples for Shemot chapter 31."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "ת'ם כלם אללה מוסי תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("רְאֵה", "אנצ'ר", "See —"),
        ("קָרָאתִי בְשֵׁם בְּצַלְאֵל", "קד שרפת אסם בצלאל",
         "I have already honored Bezalel"),
        ("בֶּן-אוּרִי בֶן-חוּר", "אבן אורי אבן חור",
         "son of Uri son of Hur"),
        ("לְמַטֵּה יְהוּדָה", "מן סבט יהודה", "of the tribe of Judah,"),
    ],
    3: [
        ("וָאֲמַלֵּא אֹתוֹ רוּחַ אֱלֹהִים", "ואכמלת פיה עלם מן ענד אללה",
         "and I have made complete in him a knowledge from God"),
        ("בְּחָכְמָה", "בחכמה", "in wisdom,"),
        ("וּבִתְבוּנָה וּבְדַעַת", "ופהם ומערפה", "and understanding, and skill"),
        ("וּבְכָל-מְלָאכָה", "בגמיע אלצנאיע",
         "in all the crafts —"),
    ],
    4: [
        ("לַחְשֹׁב מַחֲשָׁבֹת", "חאד'ק באלמהן",
         "expert in the trades,"),
        ("לַעֲשׂוֹת בַּזָּהָב וּבַכֶּסֶף וּבַנְּחֹשֶׁת",
         "בצנעה' אלד'הב ואלפ'צה ואלנחאס",
         "in the working of gold and silver and copper,"),
    ],
    5: [
        ("וּבַחֲרֹשֶׁת אֶבֶן לְמַלֹּאת", "ובכ'רט אלגוהר. לאלנצ'אם",
         "and in the cutting of gems for setting,"),
        ("וּבַחֲרֹשֶׁת עֵץ", "ונגר אלכ'שב", "and in the carpentry of wood,"),
        ("לַעֲשׂוֹת בְּכָל-מְלָאכָה", "ועמל סאיר אלצנאיע",
         "and in the making of all the rest of the crafts."),
    ],
    6: [
        ("וַאֲנִי הִנֵּה נָתַתִּי אִתּוֹ אֵת אָהֳלִיאָב בֶּן-אֲחִיסָמָךְ לְמַטֵּה-דָן",
         "ואנא פקד צ'ממת אליה. אהליאב אבן אחיסמך מן סבט דן",
         "And I, for my part, have joined to him Oholiab son of Ahisamakh of the tribe of Dan;"),
        ("וּבְלֵב כָּל-חֲכַם-לֵב נָתַתִּי חָכְמָה",
         "ופי קלב כל חכים קד געלת חכמה",
         "and in the heart of every skilled man I have placed wisdom,"),
        ("וְעָשׂוּ אֵת כָּל-אֲשֶׁר צִוִּיתִךָ",
         "אן יצנעו גמיע מא אמרתך",
         "that they may make all that I have commanded you:"),
    ],
    7: [
        ("אֵת אֹהֶל מוֹעֵד", "כ) כ'בא אלמחצ'ר", "the tent of the assembly,"),
        ("וְאֶת-הָאָרֹן לָעֵדֻת", "וצנדוק אלשהאדה", "and the ark of the testimony,"),
        ("וְאֶת-הַכַּפֹּרֶת אֲשֶׁר עָלָיו", "ואלג'שא אלד'י עליה",
         "and the cover which is upon it,"),
        ("וְאֵת כָּל-כְּלֵי הָאֹהֶל", "וסאיר אניה' אלכ'בא",
         "and all the rest of the vessels of the tent,"),
    ],
    8: [
        ("וְאֶת-הַשֻּׁלְחָן וְאֶת-כֵּלָיו", "ואלמאידה ואניתהא",
         "and the table and its vessels,"),
        ("וְאֶת-הַמְּנֹרָה הַטְּהֹרָה וְאֶת-כָּל-כֵּלֶיהָ",
         "ואלמנארה אלטאהרה וגמיע אניתהא",
         "and the pure lampstand and all its vessels,"),
        ("וְאֵת מִזְבַּח הַקְּטֹרֶת", "ומד'בח אלבכור",
         "and the altar of incense,"),
    ],
    9: [
        ("וְאֶת-מִזְבַּח הָעֹלָה וְאֶת-כָּל-כֵּלָיו",
         "ומד'בח אלצעידה וגמיע אניתה",
         "and the altar of the offering and all its vessels,"),
        ("וְאֶת-הַכִּיּוֹר וְאֶת-כַּנּוֹ", "ואלחוץ' ומקעדה",
         "and the laver and its base,"),
    ],
    10: [
        ("וְאֵת בִּגְדֵי הַשְּׂרָד", "ות'יאב אלושי",
         "and the embroidered garments,"),
        ("וְאֶת-בִּגְדֵי הַקֹּדֶשׁ לְאַהֲרֹן הַכֹּהֵן",
         "ות'יאב אלקדס להרון אלאמאם",
         "and the sacred garments for Aaron the imām,"),
        ("וְאֶת-בִּגְדֵי בָנָיו לְכַהֵן",
         "ות'יאב בניה לאלאמאמה",
         "and the garments of his sons for the imāmate,"),
    ],
    11: [
        ("וְאֵת שֶׁמֶן הַמִּשְׁחָה", "ודה'ן אלמסח", "and the anointing oil,"),
        ("וְאֶת-קְטֹרֶת הַסַּמִּים לַקֹּדֶשׁ",
         "ובכור אלצמוג' לאלקדס",
         "and the incense of the resins for the sacred place —"),
        ("כְּכֹל אֲשֶׁר-צִוִּיתִךָ יַעֲשׂוּ",
         "כגמיע מא אמרתך יצנעון",
         "according to all that I commanded you, they shall make."),
    ],
    12: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר", "וקאל אללה למוסי' קאילא",
         "And God said to Moses, saying:"),
    ],
    13: [
        ("וְאַתָּה דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "ואנת פמר בני אסראיל וקל להם",
         "'And you — command the sons of Israel and say to them:"),
        ("אַךְ אֶת-שַׁבְּתֹתַי תִּשְׁמֹרוּ", "אמא סבותי פאחפצוהא",
         "As for My sabbaths, you shall keep them;"),
        ("כִּי אוֹת הִוא בֵּינִי וּבֵינֵיכֶם לְדֹרֹתֵיכֶם",
         "לאנהא עלאמה. ביני ובינכם לאגיאלכם",
         "for they are a sign between Me and you throughout your generations,"),
        ("לָדַעַת כִּי אֲנִי יְהוָה מְקַדִּשְׁכֶם",
         "לתעלמו. אני אללה מקדסכם",
         "that they may know that I am God who sanctifies you."),
    ],
    14: [
        ("וּשְׁמַרְתֶּם אֶת-הַשַּׁבָּת", "ואחפצו אלסבת",
         "And keep the Sabbath,"),
        ("כִּי קֹדֶשׁ הִוא לָכֶם", "פאנהא מקדסה לכם",
         "for it is consecrated to you;"),
        ("מְחַלְלֶיהָ מוֹת יוּמָת", "ובאד'להא יקתל קתלא",
         "and he who profanes it shall surely be put to death —"),
        ("כִּי כָּל-הָעֹשֶׂה בָהּ מְלָאכָה וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִקֶּרֶב עַמֶּיהָ",
         "וכל מן יעמל פיהא עמלא. ינקטע ד'אלך אלאנסאן מן קומה",
         "and anyone who performs labor on it, that person shall be cut off from his people."),
    ],
    15: [
        ("שֵׁשֶׁת יָמִים יֵעָשֶׂה מְלָאכָה", "סתה' איאם תצנע אלצנאיע",
         "Six days shall the crafts be done,"),
        ("וּבַיּוֹם הַשְּׁבִיעִי שַׁבַּת שַׁבָּתוֹן קֹדֶשׁ לַיהוָה",
         "ופי אליום אלסאבע. עטלה הי סבת מקדסה ללה",
         "but on the seventh day there is a cessation: it is a Sabbath consecrated to God;"),
        ("כָּל-הָעֹשֶׂה מְלָאכָה בְּיוֹם הַשַּׁבָּת מוֹת יוּמָת",
         "וכל מן עמל עמלא פיהא יקתל",
         "whoever performs labor on it shall be put to death."),
    ],
    16: [
        ("וְשָׁמְרוּ בְנֵי-יִשְׂרָאֵל אֶת-הַשַּׁבָּת", "ויחפצו בני אסראיל. אלסבת",
         "And the sons of Israel shall keep the Sabbath"),
        ("לַעֲשׂוֹת אֶת-הַשַּׁבָּת לְדֹרֹתָם", "ויקימו בהא. לאגיאלהם",
         "and abide by it throughout their generations —"),
        ("בְּרִית עוֹלָם", "עהד אלדהר", "a covenant forever."),
    ],
    17: [
        ("בֵּינִי וּבֵין בְּנֵי יִשְׂרָאֵל--אוֹת הִוא לְעֹלָם",
         "אד' הי עלאמה ביני ובין בני אסראיל",
         "For it is a sign between Me and the sons of Israel:"),
        ("כִּי-שֵׁשֶׁת יָמִים עָשָׂה יְהוָה אֶת-הַשָּׁמַיִם וְאֶת-הָאָרֶץ",
         "לאן פי סתה' איאם. צנע אללה אלסמאואת ואלארץ'",
         "for in six days God made the heavens and the earth,"),
        ("וּבַיּוֹם הַשְּׁבִיעִי שָׁבַת וַיִּנָּפַשׁ",
         "ופי אליום אלסאבע. עטלהא ואראחהא",
         "and on the seventh day He desisted from it and gave it rest.'"),
    ],
    18: [
        ("וַיִּתֵּן אֶל-מֹשֶׁה כְּכַלֹּתוֹ לְדַבֵּר אִתּוֹ בְּהַר סִינַי",
         "ת'ם דפע אלי' מוסי. חין פרג' מן מכ'אטבתה עלי' גבל סיני",
         "Then He delivered to Moses — when He had finished speaking with him upon Mount Sinai —"),
        ("שְׁנֵי לֻחֹת הָעֵדֻת", "לוחי. אלשהאדה",
         "the two tablets of the testimony:"),
        ("לֻחֹת אֶבֶן כְּתֻבִים בְּאֶצְבַּע אֱלֹהִים",
         "לוחי גוהר. מכתובין בקדרה' אללה",
         "tablets of stone, written by the power of God."),
    ],
}
