"""Hand-authored alignment triples for Shemot chapter 12."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן", "וקאל אללה למוסי והרון",
         "And God said to Moses and Aaron"),
        ("בְּאֶרֶץ מִצְרַיִם", "פי בלד מצר", "in the land of Egypt"),
        ("לֵאמֹר", "קאילא", "saying"),
    ],
    2: [
        ("הַחֹדֶשׁ הַזֶּה לָכֶם רֹאשׁ חֳדָשִׁים", "הד'א אלשהר לכם אוול אלשהור",
         "This month shall be for you the first of months"),
        ("רִאשׁוֹן הוּא לָכֶם", "יכון לכם אוולא",
         "it shall be for you the first"),
        ("לְחָדְשֵׁי הַשָּׁנָה", "לשהור אלסנה", "of the months of the year"),
    ],
    3: [
        ("דַּבְּרוּ אֶל-כָּל-עֲדַת יִשְׂרָאֵל לֵאמֹר", "כלמא גמאעה' בני אסראיל קאילא",
         "Speak to the assembly of the sons of Israel, saying"),
        ("בֶּעָשֹׂר לַחֹדֶשׁ הַזֶּה", "פי אלעאשר מנה", "on the tenth of it"),
        ("וְיִקְחוּ לָהֶם אִישׁ שֶׂה לְבֵית-אָבֹת",
         "אן יתכ'ד' לה כל פריק. ראס לביות אבאיהם",
         "let every company take for itself a head — a head of the households of their fathers"),
        ("שֶׂה לַבָּיִת", "ראסא מנהא לכל בית", "one head for each household"),
    ],
    4: [
        ("וְאִם-יִמְעַט הַבַּיִת מִהְיוֹת מִשֶּׂה",
         "פאן קל אהל אלבית מן אלחאגה אלי' ראס",
         "But if the people of the household are too few for the need of a head"),
        ("וְלָקַח הוּא וּשְׁכֵנוֹ הַקָּרֹב אֶל-בֵּיתוֹ",
         "פליאכ'ד' הו וגארה. אלאקרב אלי' מנזלה",
         "then let him and his neighbor who is nearest to his dwelling take one together"),
        ("בְּמִכְסַת נְפָשֹׁת", "במואסאה מן אלנפוס", "in equal shares among the souls"),
        ("אִישׁ לְפִי אָכְלוֹ תָּכֹסּוּ עַל-הַשֶּׂה",
         "כל אמר עלי' קדר טעאמה תתואסוה",
         "each man according to the measure of his food shall you reckon it"),
    ],
    5: [
        ("שֶׂה תָמִים זָכָר בֶּן-שָׁנָה יִהְיֶה לָכֶם",
         "וליכון לכם ראסא. צחיחא ד'כרא אבן סנתה",
         "And let there be for you a head — one that is sound, a male of its year"),
        ("מִן-הַכְּבָשִׂים וּמִן-הָעִזִּים תִּקָּחוּ", "מן אלצ'אן ואלמאעז תאכ'דונה",
         "from the sheep and the goats you shall take it"),
    ],
    6: [
        ("וְהָיָה לָכֶם לְמִשְׁמֶרֶת", "יכון ענדכם ]מחפוט'א] מחפוצ'א",
         "It shall be kept by you"),
        ("עַד אַרְבָּעָה עָשָׂר יוֹם לַחֹדֶשׁ הַזֶּה",
         "אלי' יום ארבעה' עשר מן הד'א אלשהר",
         "until the fourteenth day of this month"),
        ("וְשָׁחֲטוּ אֹתוֹ כֹּל קְהַל עֲדַת-יִשְׂרָאֵל",
         "יד'בחה גמאעה' גוק בני אסראיל",
         "and the whole company of the assembly of the sons of Israel shall slaughter it"),
        ("בֵּין הָעַרְבָּיִם", "בין אלג'רובין", "between the two twilights"),
    ],
    7: [
        ("וְלָקְחוּ מִן-הַדָּם", "ויאכ'דו מן דמה", "And they shall take of its blood"),
        ("וְנָתְנוּ עַל-שְׁתֵּי הַמְּזוּזֹת וְעַל-הַמַּשְׁקוֹף",
         "ויגעלונה עלי' כ'די אלבאב ואלמטל",
         "and place it upon the two cheeks of the door and upon the lintel"),
        ("עַל הַבָּתִּים אֲשֶׁר-יֹאכְלוּ אֹתוֹ בָּהֶם",
         "עלי' אלביות. אלד'י יאכלונה פיהא",
         "upon the houses in which they shall eat it"),
    ],
    8: [
        ("וְאָכְלוּ אֶת-הַבָּשָׂר בַּלַּיְלָה הַזֶּה", "ויאכלון לחמה פי תלך אללילה",
         "And they shall eat its flesh that night"),
        ("צְלִי-אֵשׁ", "שיא נאר", "roasted over fire"),
        ("וּמַצּוֹת עַל-מְרֹרִים יֹאכְלֻהוּ", "ופטיר. מע מראר יאכלונה",
         "and unleavened bread; with bitter herbs they shall eat it"),
    ],
    9: [
        ("אַל-תֹּאכְלוּ מִמֶּנּוּ נָא", "לא תאכלו מנה ניא", "Do not eat of it raw"),
        ("וּבָשֵׁל מְבֻשָּׁל בַּמָּיִם", "ולא טביך' מנצג במא",
         "nor cooked by boiling in water"),
        ("כִּי אִם-צְלִי-אֵשׁ", "אלא משוי באלנאר", "but only roasted over fire"),
        ("רֹאשׁוֹ עַל-כְּרָעָיו וְעַל-קִרְבּוֹ", "ראסה ואכארעה וגופה",
         "its head and its legs and its inner parts"),
    ],
    10: [
        ("וְלֹא-תוֹתִירוּ מִמֶּנּוּ עַד-בֹּקֶר", "ולא תבקו מנה שייא אלי' אלג'דאה",
         "And you shall leave nothing of it until the morning"),
        ("וְהַנֹּתָר מִמֶּנּוּ עַד-בֹּקֶר בָּאֵשׁ תִּשְׂרֹפוּ",
         "פאן יבקי מנה שייא. אלי אלג'דאה אחרקוה באלנאר",
         "and if anything remains of it until the morning, then burn it with fire"),
    ],
    11: [
        ("וְכָכָה תֹּאכְלוּ אֹתוֹ", "וכד'א פכלוה",
         "And in this manner shall you eat it"),
        ("מָתְנֵיכֶם חֲגֻרִים", "תכון חקואכם משדודה", "your loins girded firmly"),
        ("נַעֲלֵיכֶם בְּרַגְלֵיכֶם", "ונעאלכם פי ארגלכם", "your sandals on your feet"),
        ("וּמַקֶּלְכֶם בְּיֶדְכֶם", "ועצייכם פי אידיכם", "and your staffs in your hands"),
        ("וַאֲכַלְתֶּם אֹתוֹ בְּחִפָּזוֹן", "וכלוה בחפז", "and eat it in haste"),
        ("פֶּסַח הוּא לַיהוָה", "הו פסח ללה", "it is the Passover unto God"),
    ],
    12: [
        ("וְעָבַרְתִּי בְאֶרֶץ-מִצְרַיִם בַּלַּיְלָה הַזֶּה",
         "פאתגלא פי בלד מצר פי תלך אללילה",
         "For I shall appear in the land of Egypt that night"),
        ("וְהִכֵּיתִי כָל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם", "ואקתל כל בכר פיה",
         "and I shall slay every firstborn within it"),
        ("מֵאָדָם וְעַד-בְּהֵמָה", "מן אנסאן אלי' בהימה", "from human to beast"),
        ("וּבְכָל-אֱלֹהֵי מִצְרַיִם אֶעֱשֶׂה שְׁפָטִים",
         "ובגמיע מעבודאת אלמצריון. אצנע אחכאמא",
         "and upon all the objects of worship of the Egyptians I shall execute judgments"),
        ("אֲנִי יְהוָה", "אנא אללה אלואחד", "I am God, the One"),
    ],
    13: [
        ("וְהָיָה הַדָּם לָכֶם לְאֹת", "פיכון אלדם לכם עלאמה",
         "And the blood shall be for you a sign"),
        ("עַל הַבָּתִּים אֲשֶׁר אַתֶּם שָׁם", "עלי' אלביות אלד'י אנתם פיהא",
         "upon the houses in which you are"),
        ("וְרָאִיתִי אֶת-הַדָּם וּפָסַחְתִּי עֲלֵכֶם", "אנצ'רה וארת'א לכם",
         "I shall look upon it and have compassion for you"),
        ("וְלֹא-יִהְיֶה בָכֶם נֶגֶף לְמַשְׁחִית", "ולא יחל בכם ובא מהלך",
         "and no lethal pestilence shall befall you"),
        ("בְּהַכֹּתִי בְּאֶרֶץ מִצְרָיִם", "אד' צ'רבת אהל בלד מצר",
         "when I strike the people of the land of Egypt"),
    ],
    14: [
        ("וְהָיָה הַיּוֹם הַזֶּה לָכֶם לְזִכָּרוֹן", "ויכון הד'א אליום לכם ד'כרא",
         "And this day shall be for you a memorial"),
        ("וְחַגֹּתֶם אֹתוֹ חַג לַיהוָה", "תחגו פיה חג ללה",
         "you shall celebrate it as a festival unto God"),
        ("לְדֹרֹתֵיכֶם", "לאגיאלכם", "for your generations"),
        ("חֻקַּת עוֹלָם תְּחָגֻּהוּ", "רסם אלדהר תחג'ונה",
         "it is an ordinance forever that you shall celebrate it"),
    ],
    15: [
        ("שִׁבְעַת יָמִים מַצּוֹת תֹּאכֵלוּ", "סבעה' איאם תאכלו פטירא",
         "Seven days you shall eat unleavened bread"),
        ("אַךְ בַּיּוֹם הָרִאשׁוֹן תַּשְׁבִּיתוּ שְּׂאֹר מִבָּתֵּיכֶם",
         "אמא פי אליום אלאוול. פעטלו אלמכ'מר מן ביותכם",
         "but on the first day you shall remove the leavening agent from your houses"),
        ("כִּי כָּל-אֹכֵל חָמֵץ וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִיִּשְׂרָאֵל",
         "לאן כל מן אכל כ'מיר. ינקטע ד'אלך אלאנסאן מן בין אל אסראיל",
         "for whoever eats leavened bread, that person shall be cut off from among the house of Israel"),
        ("מִיּוֹם הָרִאשֹׁן עַד-יוֹם הַשְּׁבִעִי", "מן אליום אלאוול אלי' אליום אלסאבע",
         "from the first day until the seventh day"),
    ],
    16: [
        ("וּבַיּוֹם הָרִאשׁוֹן מִקְרָא-קֹדֶשׁ", "ואליום אלאוול. אסם מקדס",
         "And the first day shall be a consecrated name"),
        ("וּבַיּוֹם הַשְּׁבִיעִי מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם",
         "ואליום אלסאבע. אסם מקדס יכון לכם",
         "and the seventh day shall be a consecrated name for you"),
        ("כָּל-מְלָאכָה לֹא-יֵעָשֶׂה בָהֶם", "ולא יצנע פיהמא שייא מן אלצנאיע",
         "no labor whatsoever shall be done on either of them"),
        ("אַךְ אֲשֶׁר יֵאָכֵל לְכָל-נֶפֶשׁ", "אלא מא יוכל לכל נפס",
         "except only what is to be eaten for every soul"),
        ("הוּא לְבַדּוֹ יֵעָשֶׂה לָכֶם", "הו וחדה יצנע לכם",
         "that alone may be done for you"),
    ],
    17: [
        ("וּשְׁמַרְתֶּם אֶת-הַמַּצּוֹת", "ואחפצו אלפטיר",
         "And keep the unleavened bread"),
        ("כִּי בְּעֶצֶם הַיּוֹם הַזֶּה הוֹצֵאתִי אֶת-צִבְאוֹתֵיכֶם מֵאֶרֶץ מִצְרָיִם",
         "פאן פי ד'את הד'א אליום. אכ'רגת גיושכם מן בלד מצר",
         "for on the very substance of this day I brought out your hosts from the land of Egypt"),
        ("וּשְׁמַרְתֶּם אֶת-הַיּוֹם הַזֶּה לְדֹרֹתֵיכֶם",
         "ואחפצ'ו הד'א אליום. לאגיאלכם",
         "so keep this day for your generations"),
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "as an ordinance forever"),
    ],
    18: [
        ("בָּרִאשֹׁן בְּאַרְבָּעָה עָשָׂר יוֹם לַחֹדֶשׁ בָּעֶרֶב",
         "פי אלשהר אלאוול. פי יום ארבעה' עשר מנה באלעשי",
         "In the first month, on the fourteenth day of it at eventide"),
        ("תֹּאכְלוּ מַצֹּת", "כלו פטירא", "eat unleavened bread"),
        ("עַד יוֹם הָאֶחָד וְעֶשְׂרִים לַחֹדֶשׁ--בָּעָרֶב",
         "אלי' יום ואחד ועשרין מנה באלעשי",
         "until the twenty-first day of it at eventide"),
    ],
    19: [
        ("שִׁבְעַת יָמִים", "סבעה' איאם", "Seven days"),
        ("שְׂאֹר לֹא יִמָּצֵא בְּבָתֵּיכֶם", "לא יוגד כ'מירא פי ביותכם",
         "no leaven shall be found in your houses"),
        ("כִּי כָּל-אֹכֵל מַחְמֶצֶת וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעֲדַת יִשְׂרָאֵל",
         "וכל מן אכל מכ'מרא. ינקטע ד'אלך אלאנסאן מן גמאעה' אל אסראיל",
         "for whoever eats anything leavened, that person shall be cut off from the assembly of the house of Israel"),
        ("בַּגֵּר וּבְאֶזְרַח הָאָרֶץ", "מן אלג'ריב וצריח אלבלד",
         "whether he be a stranger or a native of the land"),
    ],
    20: [
        ("כָּל-מַחְמֶצֶת לֹא תֹאכֵלוּ", "שייא מן אלמכ'מר לא תאכלו",
         "Anything leavened you shall not eat"),
        ("בְּכֹל מוֹשְׁבֹתֵיכֶם תֹּאכְלוּ מַצּוֹת", "פי גמיע מסאכנכם. כלו פטירא",
         "in all your dwellings eat unleavened bread"),
    ],
    21: [
        ("וַיִּקְרָא מֹשֶׁה לְכָל-זִקְנֵי יִשְׂרָאֵל",
         "פדעא מוסי'. בגמיע שיוך' בני אסראיל",
         "And Moses called for all the elders of the sons of Israel"),
        ("וַיֹּאמֶר אֲלֵהֶם", "וקאל להם", "and said to them"),
        ("מִשְׁכוּ וּקְחוּ לָכֶם צֹאן לְמִשְׁפְּחֹתֵיכֶם",
         "אמתדו. וכדו לכם ג'נמא. לעשאירכם",
         "'Go forth and take for yourselves a flock for your clans"),
        ("וְשַׁחֲטוּ הַפָּסַח", "ואד'בחו אלפסח", "and slaughter the Passover"),
    ],
    22: [
        ("וּלְקַחְתֶּם אֲגֻדַּת אֵזוֹב", "וכדו באקה מן צעתר",
         "And take a bundle of hyssop"),
        ("וּטְבַלְתֶּם בַּדָּם אֲשֶׁר-בַּסַּף", "ואג'מסוהא פי אלדם אלד'י פי אלטסת",
         "and dip it in the blood which is in the basin"),
        ("וְהִגַּעְתֶּם אֶל-הַמַּשְׁקוֹף וְאֶל-שְׁתֵּי הַמְּזוּזֹת מִן-הַדָּם אֲשֶׁר בַּסָּף",
         "ואדנו עלי' אלמטל וכ'די אלבאב. מן ד'אלך אלדם",
         "and apply it to the lintel and to the two cheeks of the door from that blood"),
        ("וְאַתֶּם לֹא תֵצְאוּ אִישׁ מִפֶּתַח-בֵּיתוֹ--עַד-בֹּקֶר",
         "ולא יכ'ר'ג אנסאן מנכם. מן באב מנזלה אלי' אלג'דאה",
         "and let no person among you go out from the door of his dwelling until the morning"),
    ],
    23: [
        ("וְעָבַר יְהוָה לִנְגֹּף אֶת-מִצְרַיִם", "פיתגלא אללה ליצדם אלמצריון",
         "For God shall appear to strike the Egyptians"),
        ("וְרָאָה אֶת-הַדָּם עַל-הַמַּשְׁקוֹף וְעַל שְׁתֵּי הַמְּזוּזֹת",
         "וינצ'ר אלדם עלי אלמטל וכדי אלבאב",
         "and shall see the blood upon the lintel and the two cheeks of the door"),
        ("וּפָסַח יְהוָה עַל-הַפֶּתַח", "פירת'י למן דאכלה",
         "and shall have compassion for whoever is within"),
        ("וְלֹא יִתֵּן הַמַּשְׁחִית לָבֹא אֶל-בָּתֵּיכֶם לִנְגֹּף",
         "ולא ידע אלמהלך. אן ידכ'ל אלי' ביותכם פיהלככם",
         "and He shall not permit the destroyer to enter into your houses to bring ruin"),
    ],
    24: [
        ("וּשְׁמַרְתֶּם אֶת-הַדָּבָר הַזֶּה", "ואחפצו הד'א אלאמר",
         "And keep this matter"),
        ("לְחָק-לְךָ וּלְבָנֶיךָ עַד-עוֹלָם", "רסם לכם ולאגיאלכם אלי' אלדהר",
         "as an ordinance for you and for your generations forever"),
    ],
    25: [
        ("וְהָיָה כִּי-תָבֹאוּ אֶל-הָאָרֶץ אֲשֶׁר יִתֵּן יְהוָה לָכֶם--כַּאֲשֶׁר דִּבֵּר",
         "ואד'א דכ'לתם אלי' אלבלד. אלד'י יעטיכם אללה כמא ועד",
         "And when you enter the land which God shall give you as He has promised"),
        ("וּשְׁמַרְתֶּם אֶת-הָעֲבֹדָה הַזֹּאת", "פאחפצו הד'ה אלצנעה",
         "then keep this rite"),
    ],
    26: [
        ("וְהָיָה כִּי-יֹאמְרוּ אֲלֵיכֶם בְּנֵיכֶם", "ויכון אד'א קאלו לכם בניכם",
         "And it shall be, when your children say to you"),
        ("מָה הָעֲבֹדָה הַזֹּאת לָכֶם", "מא הד'ה אלצנעה לכם",
         "What is this rite for you?"),
    ],
    27: [
        ("וַאֲמַרְתֶּם זֶבַח-פֶּסַח הוּא לַיהוָה", "קולו הו דבח ארת'א ללה",
         "It is a slaughter of compassion unto God"),
        ("אֲשֶׁר פָּסַח עַל-בָּתֵּי בְנֵי-יִשְׂרָאֵל בְּמִצְרַיִם",
         "כמא ארת'א לביות בני אסראיל במצר",
         "for He showed compassion for the houses of the sons of Israel in Egypt"),
        ("בְּנָגְפּוֹ אֶת-מִצְרַיִם וְאֶת-בָּתֵּינוּ הִצִּיל",
         "אד' צדם אלמצריון וכ'לץ ביותנא",
         "when He struck the Egyptians and delivered our houses"),
        ("וַיִּקֹּד הָעָם וַיִּשְׁתַּחֲווּ", "וכ'ר אלקום וסגדו",
         "And the people bowed down and prostrated themselves"),
    ],
    28: [
        ("וַיֵּלְכוּ וַיַּעֲשׂוּ בְּנֵי יִשְׂרָאֵל", "פמצ'ו בני אסראיל וצנעו",
         "And the sons of Israel went and did"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה וְאַהֲרֹן", "כמא אמר אללה מוסי והרון",
         "as God had commanded Moses and Aaron"),
        ("כֵּן עָשׂוּ", "כד'אך צנעו", "so they did"),
    ],
    29: [
        ("וַיְהִי בַּחֲצִי הַלַּיְלָה", "ולמא כאן פי נצף אלליל",
         "And when it was at the middle of the night"),
        ("וַיהוָה הִכָּה כָל-בְּכוֹר בְּאֶרֶץ מִצְרַיִם", "קתל אללה כל בכר פי בלד מצר",
         "God slew every firstborn in the land of Egypt"),
        ("מִבְּכֹר פַּרְעֹה הַיֹּשֵׁב עַל-כִּסְאוֹ", "מן בכר פרעון אלגאלס עלי' כרסיה",
         "from the firstborn of Pharaoh who sat upon his throne"),
        ("עַד בְּכוֹר הַשְּׁבִי אֲשֶׁר בְּבֵית הַבּוֹר", "אלי' בכר אלסבי אלד'י פי אלחבס",
         "to the firstborn of the captive who was in the prison"),
        ("וְכֹל בְּכוֹר בְּהֵמָה", "וגמיע בכור אלבהאים",
         "and all the firstborn of the beasts"),
    ],
    30: [
        ("וַיָּקָם פַּרְעֹה לַיְלָה הוּא וְכָל-עֲבָדָיו וְכָל-מִצְרַיִם",
         "פקאם פרעון לילא. הו וגמיע עבידה וסאיר אלמצריון",
         "And Pharaoh arose in the night — he and all his servants and the rest of the Egyptians"),
        ("וַתְּהִי צְעָקָה גְדֹלָה בְּמִצְרָיִם", "וכאן צראך' עצ'ים במצר",
         "and there was a great cry in Egypt"),
        ("כִּי-אֵין בַּיִת אֲשֶׁר אֵין-שָׁם מֵת", "אד' ליס בית. ליס פיה מיית",
         "since there was no house in which there was not a dead one"),
    ],
    31: [
        ("וַיִּקְרָא לְמֹשֶׁה וּלְאַהֲרֹן לַיְלָה", "ודעא במוסי' והרון לילא",
         "And he called for Moses and Aaron in the night"),
        ("וַיֹּאמֶר קוּמוּ צְּאוּ מִתּוֹךְ עַמִּי", "וקאל קומא אכ'רגא מן בית קומי",
         "and said: 'Arise, go out from among my people"),
        ("גַּם-אַתֶּם גַּם-בְּנֵי יִשְׂרָאֵל", "אנתמא ובני אסראיל",
         "you two and the sons of Israel"),
        ("וּלְכוּ עִבְדוּ אֶת-יְהוָה כְּדַבֶּרְכֶם", "ואמצ'ו. אעבדו אללה כמא קלתם",
         "and go forth; serve God as you have said"),
    ],
    32: [
        ("גַּם-צֹאנְכֶם גַּם-בְּקַרְכֶם קְחוּ כַּאֲשֶׁר דִּבַּרְתֶּם",
         "ואיצ'א ג'נמכם ובקרכם כ'דוהא. כמא קלתם",
         "'Also your flocks and your herds — take them, as you have said"),
        ("וָלֵכוּ", "ואמצ'ו", "and go"),
        ("וּבֵרַכְתֶּם גַּם-אֹתִי", "ואגעלוני פי חל",
         "and release me from obligation"),
    ],
    33: [
        ("וַתֶּחֱזַק מִצְרַיִם עַל-הָעָם", "פשדד אלמצריון עלי' אלקום",
         "And the Egyptians pressed upon the people"),
        ("לְמַהֵר לְשַׁלְּחָם מִן-הָאָרֶץ", "ליסרעו יטלקונהם מן אלבלד",
         "to hasten to send them out from the land"),
        ("כִּי אָמְרוּ כֻּלָּנוּ מֵתִים", "לאנהם קאלו כלנא מאיתין",
         "for they said: 'We are all dying"),
    ],
    34: [
        ("וַיִּשָּׂא הָעָם אֶת-בְּצֵקוֹ טֶרֶם יֶחְמָץ",
         "פחמל אלקום. עגינהם קבל אן יכ'תמר",
         "And the people carried their dough before it had leavened"),
        ("מִשְׁאֲרֹתָם צְרֻרֹת בְּשִׂמְלֹתָם עַל-שִׁכְמָם",
         "וכאנת מעאגנהם. מצרורה פי ת'יאבהם עלי' אענאקהם",
         "and their kneading-bowls were bound up in their garments upon their necks"),
    ],
    35: [
        ("וּבְנֵי-יִשְׂרָאֵל עָשׂוּ כִּדְבַר מֹשֶׁה",
         "וצנעו בני אסראיל חיניד' כמא אמרהם מוסי'",
         "And the sons of Israel did at that time as Moses had commanded them"),
        ("וַיִּשְׁאֲלוּ מִמִּצְרַיִם כְּלֵי-כֶסֶף וּכְלֵי זָהָב וּשְׂמָלֹת",
         "ואסתוהבו מן אלמצריון. אניה' פצ'ה. ואניה' ד'הב ות'יאבא",
         "and asked as gifts from the Egyptians vessels of silver, and vessels of gold, and garments"),
    ],
    36: [
        ("וַיהוָה נָתַן אֶת-חֵן הָעָם בְּעֵינֵי מִצְרַיִם",
         "ואללה אעטא אלקום חצ'אא. ענד אלמצריון",
         "And God gave the people favor before the Egyptians"),
        ("וַיַּשְׁאִלוּם", "פוהבוהא להם", "and they gave these as gifts to them"),
        ("וַיְנַצְּלוּ אֶת-מִצְרָיִם", "ואנתספו אלמצריון",
         "and so the Egyptians were stripped"),
    ],
    37: [
        ("וַיִּסְעוּ בְנֵי-יִשְׂרָאֵל מֵרַעְמְסֵס סֻכֹּתָה",
         "ת'ם רחל בני אסראיל מן עין שמס אלי' סכות",
         "Then the sons of Israel journeyed from Ein Shams (Raamses) to Succoth"),
        ("כְּשֵׁשׁ-מֵאוֹת אֶלֶף רַגְלִי הַגְּבָרִים",
         "שביה בסת מאיה' אלף רגל רגאל",
         "numbering about six hundred thousand on foot, adult men"),
        ("לְבַד מִטָּף", "מא כ'לא אלאטפאל", "besides the little ones"),
    ],
    38: [
        ("וְגַם-עֵרֶב רַב עָלָה אִתָּם", "ואיצ'א כ'לט כת'יר צעד מעהם",
         "And also a great mixed multitude went up with them"),
        ("וְצֹאן וּבָקָר מִקְנֶה כָּבֵד מְאֹד", "וג'נם ובקר. מואשי ע'צימה גדא",
         "and flocks and cattle — a very great quantity of livestock"),
    ],
    39: [
        ("וַיֹּאפוּ אֶת-הַבָּצֵק אֲשֶׁר הוֹצִיאוּ מִמִּצְרַיִם",
         "פאכ'תבזו אלעגין. אלד'י אכ'רגוה מן מצר",
         "And they baked the dough which they had brought out from Egypt"),
        ("עֻגֹת מַצּוֹת", "מלילא פטירא", "as flat unleavened cakes"),
        ("כִּי לֹא חָמֵץ", "אד' לם אכ'תמר", "for it had not leavened"),
        ("כִּי-גֹרְשׁוּ מִמִּצְרַיִם וְלֹא יָכְלוּ לְהִתְמַהְמֵהַּ",
         "למא טרדו מן מצר. ולם יטיקו אן יתלבתו",
         "since they had been driven out from Egypt and had not been able to linger"),
        ("וְגַם-צֵדָה לֹא-עָשׂוּ לָהֶם", "חתא זאדא לם יצנעו להם",
         "and even provisions they had not prepared for themselves"),
    ],
    40: [
        ("וּמוֹשַׁב בְּנֵי יִשְׂרָאֵל אֲשֶׁר יָשְׁבוּ בְּמִצְרָיִם",
         "וכאן מקאם בני אסראיל. אלד'י אקאמו פי אעמאל מצר",
         "And the sojourn of the sons of Israel, which they sojourned in the labors of Egypt"),
        ("שְׁלֹשִׁים שָׁנָה וְאַרְבַּע מֵאוֹת שָׁנָה", "ארבע מאיה ות'לאת'ין סנה",
         "was four hundred and thirty years"),
    ],
    41: [
        ("וַיְהִי מִקֵּץ שְׁלֹשִׁים שָׁנָה וְאַרְבַּע מֵאוֹת שָׁנָה",
         "פלמא כאן בעד ארבע מאיה ות'לאת'ין סנה",
         "And when it was after four hundred and thirty years"),
        ("וַיְהִי בְּעֶצֶם הַיּוֹם הַזֶּה", "פי ד'את ד'אלך אליום",
         "on the very substance of that day"),
        ("יָצְאוּ כָּל-צִבְאוֹת יְהוָה מֵאֶרֶץ מִצְרָיִם",
         "כ'רגו גמיע גיוש אללה מן בלד מצר",
         "all the hosts of God went out from the land of Egypt"),
    ],
    42: [
        ("לֵיל שִׁמֻּרִים הוּא לַיהוָה לְהוֹצִיאָם מֵאֶרֶץ מִצְרָיִם",
         "וכמא כאן ליל חפץ' ללה. ליכ'רגהם מן בלד מצר",
         "And just as there had been a night of watching unto God, to bring them out from the land of Egypt"),
        ("הוּא-הַלַּיְלָה הַזֶּה לַיהוָה", "כד'אך הד'א אלליל", "so this night"),
        ("שִׁמֻּרִים לְכָל-בְּנֵי יִשְׂרָאֵל לְדֹרֹתָם",
         "מחפוצ'א לבני אסראיל לאגיאלהם",
         "is kept for the sons of Israel throughout their generations"),
    ],
    43: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה וְאַהֲרֹן", "ת'ם קאל אללה למוסי' והרון",
         "Then God said to Moses and Aaron"),
        ("זֹאת חֻקַּת הַפָּסַח", "הד'א רסם אלפסח",
         "'This is the ordinance of the Passover"),
        ("כָּל-בֶּן-נֵכָר לֹא-יֹאכַל בּוֹ", "כל אגנבי לא יאכל מנה",
         "no foreigner shall eat of it"),
    ],
    44: [
        ("וְכָל-עֶבֶד אִישׁ מִקְנַת-כָּסֶף", "וכל עבד לאנסאן משתרא בת'מן",
         "But every slave belonging to a man, purchased for a price"),
        ("וּמַלְתָּה אֹתוֹ", "פאכ'תנה", "circumcise him"),
        ("אָז יֹאכַל בּוֹ", "וחיניד' יאכל מנה", "and then he may eat of it"),
    ],
    45: [
        ("תּוֹשָׁב וְשָׂכִיר לֹא-יֹאכַל בּוֹ", "ואלצ'יף ואלאגיר לא יאכלאן מנה",
         "The sojourner and the hired laborer shall not eat of it"),
    ],
    46: [
        ("בְּבַיִת אֶחָד יֵאָכֵל", "ופי מנזל ואחד יוכל",
         "In one dwelling shall it be eaten"),
        ("לֹא-תוֹצִיא מִן-הַבַּיִת מִן-הַבָּשָׂר חוּצָה",
         "לא תכ'רגו מן אלבית. מן אללחם כ'ארגא",
         "you shall not carry out from the house any of the flesh to the outside"),
        ("וְעֶצֶם לֹא תִשְׁבְּרוּ-בוֹ", "ו עצ'ם לא תכסרו מנה",
         "and a bone you shall not break of it"),
    ],
    47: [
        ("כָּל-עֲדַת יִשְׂרָאֵל יַעֲשׂוּ אֹתוֹ",
         "כד'אך אכת'ר גמאעה' בני אסראיל יצנעונה",
         "Thus shall the greater part of the assembly of the sons of Israel do it"),
    ],
    48: [
        ("וְכִי-יָגוּר אִתְּךָ גֵּר וְעָשָׂה פֶסַח לַיהוָה",
         "ואד'א דכ'ל מעכם ג'ריב. ואראד אן יצנע פסחא ללה",
         "And when a stranger sojourns among you and wishes to make a Passover unto God"),
        ("הִמּוֹל לוֹ כָל-זָכָר", "פליכ'תתן כל ד'כר פי נאחיתה",
         "let every male in his vicinity be circumcised"),
        ("וְאָז יִקְרַב לַעֲשֹׂתוֹ", "וחיניד' יתקדם ליצנעה",
         "and then let him come forward to make it"),
        ("וְהָיָה כְּאֶזְרַח הָאָרֶץ", "אד' יציר כצריח אלבלד",
         "for he shall become as a native of the land"),
        ("וְכָל-עָרֵל לֹא-יֹאכַל בּוֹ", "וכל אקלף לא יאכל מנ'ה",
         "but any uncircumcised person shall not eat of it"),
    ],
    49: [
        ("תּוֹרָה אַחַת יִהְיֶה לָאֶזְרָח", "שריעה ואחדה. תכון לאלצריח",
         "One law shall there be for the native"),
        ("וְלַגֵּר הַגָּר בְּתוֹכְכֶם", "ואלג'ריב אלדכ'יל פי מא בינכם",
         "and for the stranger who has entered among you"),
    ],
    50: [
        ("וַיַּעֲשׂוּ כָּל-בְּנֵי יִשְׂרָאֵל", "פצנעו בני אסראיל",
         "And the sons of Israel did"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה וְאֶת-אַהֲרֹן", "כמא אמר אללה מוסי והרון",
         "as God had commanded Moses and Aaron"),
        ("כֵּן עָשׂוּ", "כד'אך צנעו", "so they did"),
    ],
    51: [
        ("וַיְהִי בְּעֶצֶם הַיּוֹם הַזֶּה", "ולמא כאן פי ד'את ד'אלך אליום",
         "And when it was on the very substance of that day"),
        ("הוֹצִיא יְהוָה אֶת-בְּנֵי יִשְׂרָאֵל מֵאֶרֶץ מִצְרַיִם",
         "אכ'רג אללה בני אסראיל. מן בלד מצר",
         "God brought out the sons of Israel from the land of Egypt"),
        ("עַל-צִבְאֹתָם", "עלי' ג'יושהם", "by their hosts"),
    ],
}
