"""Hand-authored alignment triples for Vayikra chapter 9.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings. Words Saadia adds with no Hebrew source (glosses, expansions) carry
he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "פלמא", "And it was"),
        (None, "כאן", "on"),
        ("בַּיּוֹם", "פי אליום", "the eighth day"),
        ("הַשְּׁמִינִי", "אלת'אמן", "—"),
        ("קָרָא", "דעא", "called"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("לְאַהֲרֹן", "בהרון", "to Aaron"),
        ("וּלְבָנָיו", "ובניה", "and his sons"),
        ("וּלְזִקְנֵי", "ואשיאך'", "and to the elders"),
        ("יִשְׂרָאֵל", "בני אסראיל", "of the sons of Israel"),
    ],
    2: [
        ("וַיֹּאמֶר", "וקאל", "And he said"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("קַח-לְךָ", "כ'ד'", "Take"),
        ("עֵגֶל", "עגלא", "a calf"),
        ("בֶּן-בָּקָר", "מן אלבקר", "from the cattle"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification-offering"),
        ("וְאַיִל", "וכבשא", "and a ram"),
        ("לְעֹלָה", "לאלצעידה", "for the ascent-offering"),
        ("תְּמִימִם", "צחיחאן", "both without blemish"),
        ("וְהַקְרֵב", "וקרבהמא", "and bring them near"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    3: [
        ("וְאֶל-בְּנֵי יִשְׂרָאֵל", "ומר בני אסראיל", "And command the sons of Israel"),
        ("תְּדַבֵּר", "קאילא", "saying"),
        ("קְחוּ", "כ'ד'ו", "Take"),
        ("שְׂעִיר-עִזִּים", "עתודא מן אלמאעז", "a he-goat from the goats"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification-offering"),
        ("וְעֵגֶל", "ועגלא", "and a calf"),
        ("וָכֶבֶשׂ", "וכרופא", "and a lamb"),
        ("בְּנֵי-שָׁנָה", "אבני סנה", "sons of a year"),
        ("תְּמִימִם", "צחיחאן", "without blemish"),
        ("לְעֹלָה", "לאלצעידה", "for the ascent-offering"),
    ],
    4: [
        ("וְשׁוֹר", "ות'ורא", "and a bull"),
        ("וָאַיִל", "וכבשא", "and a ram"),
        ("לִשְׁלָמִים", "לאלסלאמה", "for the well-being offering"),
        ("לִזְבֹּחַ", "יד'בחאן", "to be slaughtered"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("וּמִנְחָה", "והדייה", "and a gift-offering"),
        ("בְּלוּלָה", "מלתותה", "mixed"),
        ("בַשָּׁמֶן", "בדהן", "with oil"),
        ("כִּי", "לאן", "for"),
        ("הַיּוֹם", "אליום", "today"),
        ("יְהוָה", "אללה", "God"),
        ("נִרְאָה", "יתגלא", "shall reveal Himself"),
        ("אֲלֵיכֶם", "לכם", "to you"),
    ],
    5: [
        (None, "פקדמו", "And they brought forward"),
        ("אֵת אֲשֶׁר", "מא", "what"),
        ("צִוָּה", "אמר בה", "had commanded"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-פְּנֵי אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר", "to the entrance of the tent of the assembly"),
        ("וַיִּקְרְבוּ", "ותקדם", "drew near"),
        ("כָּל-הָעֵדָה", "גמיע אלגמע", "all the congregation"),
        ("וַיַּעַמְדוּ", "ווקפו", "and stood"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    6: [
        ("וַיֹּאמֶר", "וקאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("זֶה", "הד'י", "This is"),
        ("הַדָּבָר", "אלאמר", "the matter"),
        ("אֲשֶׁר-צִוָּה", "אלד'י אמרכם", "which God has commanded you"),
        ("יְהוָה", "אללה", "—"),
        ("תַּעֲשׂוּ", "בה אעמלוה", "do it"),
        ("וְיֵרָא", "ויתגלא", "shall reveal itself"),
        ("אֲלֵיכֶם", "לכם", "to you"),
        ("כְּבוֹד יְהוָה", "כרם אללה", "the munificence of God"),
    ],
    7: [
        ("וַיֹּאמֶר", "וקאל", "And he said"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("קְרַב", "תקדם", "Draw near"),
        ("אֶל-הַמִּזְבֵּחַ", "אלי' אלמד'בח", "to the altar"),
        ("וַעֲשֵׂה", "ואעמל", "and perform"),
        ("אֶת-חַטָּאתְךָ", "ד'כותך", "your purification-offering"),
        ("וְאֶת-עֹלָתֶךָ", "וצעידתך", "and your ascent-offering"),
        ("וְכַפֵּר", "ואסתג'פר", "and seek forgiveness"),
        ("בַּעַדְךָ", "ענך", "for yourself"),
        ("וּבְעַד הָעָם", "וען אלקום", "and for the people"),
        ("וַעֲשֵׂה", "ואעמל", "then perform"),
        ("אֶת-קָרְבַּן הָעָם", "קרבאנהם", "their offering"),
        ("וְכַפֵּר", "ואסתג'פר", "and seek forgiveness"),
        ("בַּעֲדָם", "ענהם", "for them"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה", "כמא אמר אללה", "as God has commanded"),
    ],
    8: [
        ("וַיִּקְרַב", "פתקדם", "drew near"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("אֶל-הַמִּזְבֵּחַ", "אלי' אלמד'בח", "to the altar"),
        ("וַיִּשְׁחַט", "פד'בח", "and slaughtered"),
        ("אֶת-עֵגֶל הַחַטָּאת", "עגל אלדכוה", "the calf of the purification-offering"),
        ("אֲשֶׁר-לוֹ", "אלד'י לה", "which was his"),
    ],
    9: [
        ("וַיַּקְרִבוּ", "פקדם", "brought"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("אֶת-הַדָּם אֵלָיו", "אליה אלדם", "the blood to him"),
        ("וַיִּטְבֹּל", "פג'מס", "and he dipped"),
        ("אֶצְבָּעוֹ", "אצבעה", "his finger"),
        ("בַּדָּם", "פיה", "in it"),
        ("וַיִּתֵּן", "וגעל", "and placed it"),
        ("עַל-קַרְנוֹת", "עלי' ארכאן", "upon the corners"),
        ("הַמִּזְבֵּחַ", "אלמד'בח", "of the altar"),
        ("וְאֶת-הַדָּם", "ובאקי אלדם", "and the remainder of the blood"),
        ("יָצַק", "צבה", "he poured out"),
        ("אֶל-יְסוֹד הַמִּזְבֵּחַ", "ענד אסאסה", "at its base"),
    ],
    11: [
        ("וְאֶת-הַבָּשָׂר", "ולחמה", "And its flesh"),
        ("וְאֶת-הָעוֹר", "וגל'דה", "and its hide"),
        ("שָׂרַף", "אחרקה", "he burned"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
        ("מִחוּץ לַמַּחֲנֶה", "כ'ארג אלעסכר", "outside the encampment"),
    ],
    12: [
        (None, "ת'ם", "Then"),
        ("וַיִּשְׁחַט", "ד'בח", "he slaughtered"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the ascent-offering"),
        ("וַיַּמְצִאוּ", "ובלג'", "conveyed"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("אֶת-הַדָּם", "אלדם", "the blood"),
        ("אֵלָיו", "אליה", "to him"),
        ("וַיִּזְרְקֵהוּ", "ורשה", "and he sprinkled it"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    13: [
        ("וְאֶת-הָעֹלָה", "ובלג'ו אליה", "And they conveyed to him"),
        ("הִמְצִיאוּ אֵלָיו לִנְתָחֶיהָ", "אעצ'א אלצעידה", "the limbs of the ascent-offering"),
        ("וְאֶת-הָרֹאשׁ", "מע אלראס", "together with the head"),
        ("וַיַּקְטֵר", "וקתר ד'אלך", "and he burned them in fire"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
    ],
    14: [
        ("וַיִּרְחַץ", "וג'סל", "And he washed"),
        ("אֶת-הַקֶּרֶב", "אלגוף", "the entrails"),
        ("וְאֶת-הַכְּרָעָיִם", "ואלאכארע", "and the legs"),
        ("וַיַּקְטֵר", "וקתר ד'אלך", "and burned them in fire"),
        ("עַל-הָעֹלָה הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
    ],
    15: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he brought forward"),
        ("קָרְבַּן הָעָם", "קרבאן אלקום", "the offering of the people"),
        ("וַיִּקַּח", "ואכ'ד'", "and took"),
        ("אֶת-שְׂעִיר הַחַטָּאת", "עתוד אלדכוה", "the he-goat of the purification-offering"),
        ("אֲשֶׁר לָעָם", "אלד'י להם", "which was theirs"),
        ("וַיִּשְׁחָטֵהוּ", "פד'בחה", "and slaughtered it"),
        ("וַיְחַטְּאֵהוּ", "וד'כא בה", "and performed the purification with it"),
        ("כָּרִאשׁוֹן", "כאלאוול", "as with the first"),
    ],
    16: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he brought forward"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the ascent-offering"),
        ("וַיַּעֲשֶׂהָ", "ועמלהא", "and performed it"),
        ("כַּמִּשְׁפָּט", "כאלסירה", "according to the established practice"),
    ],
    17: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he brought forward"),
        ("אֶת-הַמִּנְחָה", "אלהדייה", "the gift-offering"),
        ("וַיְמַלֵּא", "ומלא", "and filled"),
        ("כַפּוֹ", "כפה", "his palm"),
        ("מִמֶּנָּה", "מנהא", "from it"),
        ("וַיַּקְטֵר", "וקתר ד'אלך", "and burned it in fire"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("מִלְּבַד", "מא כ'לא", "in addition to"),
        ("עֹלַת הַבֹּקֶר", "צעידה' אלג'דאה", "the morning ascent-offering"),
    ],
    18: [
        ("וַיִּשְׁחַט", "וד'בח", "And he slaughtered"),
        ("אֶת-הַשּׁוֹר", "אלת'ור", "the bull"),
        ("וְאֶת-הָאַיִל", "ואלכבש", "and the ram"),
        ("זֶבַח הַשְּׁלָמִים", "ד'בח אלסלאמה", "the well-being sacrifice"),
        ("אֲשֶׁר לָעָם", "אלד'י לאלקום", "belonging to the people"),
        ("וַיַּמְצִאוּ", "ובלג'", "conveyed"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("אֶת-הַדָּם", "אלדם", "the blood"),
        ("אֵלָיו", "אליה", "to him"),
        ("וַיִּזְרְקֵהוּ", "ורשה", "and he sprinkled it"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    19: [
        ("וְאֶת-הַחֲלָבִים", "ואלשחום", "And the fats"),
        ("מִן-הַשּׁוֹר", "מן אלת'ור", "from the bull"),
        ("וּמִן-הָאַיִל", "ומן אלכבש", "and from the ram"),
        ("הָאַלְיָה", "אלאליה", "the broad tail"),
        ("וְהַמְכַסֶּה", "ואלמג'טי", "and what covers"),
        (None, "אלגוף", "the entrails"),
        ("וְהַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְיֹתֶרֶת הַכָּבֵד", "וזיאדה' אלכבד", "and the lobe of the liver"),
    ],
    20: [
        ("וַיָּשִׂימוּ", "וציירו", "they placed"),
        ("אֶת-הַחֲלָבִים", "אלשחם", "the fat"),
        ("עַל-הֶחָזוֹת", "מע אלקצוץ", "together with the breasts"),
        ("וַיַּקְטֵר", "וקתר", "and he burned"),
        ("הַחֲלָבִים", "אלשחום", "the fats"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "in fire upon the altar"),
    ],
    21: [
        ("וְאֵת הֶחָזוֹת", "ואלקצוץ", "And the breasts"),
        ("וְאֵת שׁוֹק הַיָּמִין", "ואלסאק אלאימן", "and the right thigh"),
        ("הֵנִיף", "חרכהא", "waved them"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("תְּנוּפָה", "תחריכא", "in a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("כַּאֲשֶׁר צִוָּה", "כמא אמר", "as Moses had commanded"),
        ("מֹשֶׁה", "מוסי'", "—"),
    ],
    22: [
        (None, "ת'ם", "Then"),
        ("וַיִּשָּׂא", "של", "lifted up"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("אֶת-יָדָו", "ידיה", "his hands"),
        ("אֶל-הָעָם", "אלי' אלקום", "toward the people"),
        ("וַיְבָרְכֵם", "ובארך עליהם", "and blessed them"),
        (None, "בעד אן", "and he descended"),
        ("מֵעֲשֹׂת", "נזל מן עמל", "from performing"),
        ("הַחַטָּאת", "אלדכוה", "the purification-offering"),
        ("וְהָעֹלָה", "ואלצעידה", "and the ascent-offering"),
        ("וְהַשְּׁלָמִים", "וד'בח אלסלאמה", "and the well-being sacrifice"),
    ],
    23: [
        ("וַיָּבֹא", "פדכ'ל מוסי' והרון", "And Moses and Aaron entered"),
        ("אֶל-אֹהֶל מוֹעֵד", "אלי' כ'בא אלמחצ'ר", "into the tent of the assembly"),
        ("וַיֵּצְאוּ", "וכ'רגא", "and they came out"),
        ("וַיְבָרְכוּ אֶת-הָעָם", "ובארכא עלי' אלקום", "and blessed the people"),
        ("וַיֵּרָא", "פתגלא", "revealed itself"),
        ("כְבוֹד-יְהוָה", "כרם אללה", "the munificence of God"),
        ("אֶל-כָּל-הָעָם", "להם", "to them"),
    ],
    24: [
        (None, "באן", "For"),
        ("וַתֵּצֵא", "כ'רגת", "came forth"),
        ("אֵשׁ", "נארא", "a fire"),
        ("מִלִּפְנֵי יְהוָה", "מן ענד אללה", "from the presence of God"),
        ("וַתֹּאכַל", "פאכלת", "and consumed"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the ascent-offering"),
        ("וְאֶת-הַחֲלָבִים", "ואלשחום", "and the fats"),
        ("וַיַּרְא", "פנצ'ר", "saw"),
        (None, "דא'לך", "this"),
        ("כָּל-הָעָם", "אלקום", "the people"),
        ("וַיָּרֹנּוּ", "ורנו", "they cried out"),
        ("וַיִּפְּלוּ", "ווקעו", "and fell"),
        ("עַל-פְּנֵיהֶם", "עלי' וגוההם", "upon their faces"),
    ],
}
