"""Hand-authored alignment triples for Vayikra chapter 21.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיֹּאמֶר", "קאל", "said"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "למוסי.", "to Moses:"),
        ("אֱמֹר", "מר", "Command"),
        ("אֶל-הַכֹּהֲנִים", "אלאימה", "the imāms,"),
        ("בְּנֵי", "בני", "the sons of"),
        ("אַהֲרֹן", "הרון.", "Aaron,"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them:"),
        ("לֹא-יִטַּמָּא", "לא ינגס", "become impure"),
        (None, "כל ואחד מנכם", "Let no one among you"),
        ("לְנֶפֶשׁ", "במיית", "through a dead person"),
        ("בְּעַמָּיו", "מן קומה", "of his people —"),
    ],
    2: [
        (None, "אלא", "except"),
        ("לִשְׁאֵרוֹ", "לנסיבה.", "for his next of kin,"),
        ("הַקָּרֹב", "אלאקרב", "who is close"),
        ("אֵלָיו", "אליה.", "to him:"),
        ("לְאִמּוֹ", "אמה", "his mother"),
        ("וּלְאָבִיו", "ואביה.", "and his father,"),
        ("וְלִבְנוֹ", "ואבנה", "and his son"),
        ("וּלְבִתּוֹ", "ואבנתה", "and his daughter"),
        ("וּלְאָחִיו", "ואכ'יה", "and his brother,"),
    ],
    3: [
        ("וְלַאֲחֹתוֹ", "ואכ'תה", "and his"),
        ("הַבְּתוּלָה", "אלבכר", "virgin sister"),
        ("הַקְּרוֹבָה", "אלאקרב", "who is closest"),
        ("אֵלָיו", "אליה.", "to him —"),
        (None, "והי", "she"),
        ("אֲשֶׁר", "אלתי", "who"),
        ("לֹא-הָיְתָה", "לם תציר", "has not yet become"),
        ("לְאִישׁ", "לרגל.", "belonging to a man;"),
        ("לָהּ", "פבהא", "for her"),
        ("יִטַּמָּא", "ינגס", "he shall become impure, as is obligatory."),
    ],
    4: [
        (None, "ולא", "But"),
        ("לֹא יִטַּמָּא", "ינגס", "he shall not become impure"),
        ("בַּעַל", "בכ'טיר", "through a person of consequence"),
        ("בְּעַמָּיו", "מן קומה.", "from his people,"),
        (None, "לאנה", "as that would"),
        ("לְהֵחַלּוֹ", "תבד'לה", "debase him."),
    ],
    5: [
        ("לֹא-יקרחה", "לא ינתפו", "They shall not pluck"),
        ("קָרְחָה", "נתפא", "a plucking"),
        ("בְּרֹאשָׁם", "מן שער רוסהם.", "from the hair of their heads,"),
        ("וּפְאַת", "וזואיא", "the corners of"),
        ("זְקָנָם", "לחאהם", "their beards,"),
        ("לֹא יְגַלֵּחוּ", "לא יחלקוהא.", "nor shall they shave"),
        ("וּבִבְשָׂרָם", "ופי אבדאנהם.", "upon their bodies."),
        ("לֹא יִשְׂרְטוּ", "לא יכ'דשון", "nor shall they scratch"),
        ("שָׂרָטֶת", "כ'דשא", "a scratch"),
    ],
    6: [
        ("קְדֹשִׁים יִהְיוּ", "וליכונו מקדסין", "And they shall be consecrated"),
        ("לֵאלֹהֵיהֶם", "לרבהם.", "to their Lord,"),
        ("וְלֹא", "ולא", "and shall not"),
        ("יְחַלְּלוּ", "יבד'לו", "debase"),
        ("שֵׁם", "אסם", "the name of"),
        ("אֱלֹהֵיהֶם", "רבהם.", "their Lord —"),
        (None, "פאנהם", "for,"),
        (None, "למא", "inasmuch as"),
        (None, "הם", "they are"),
        ("מַקְרִיבִם", "מקרבין", "those who offer"),
        ("אֶת-אִשֵּׁי", "קראבין", "the offerings of"),
        ("יְהוָה", "אללה", "God"),
        ("לֶחֶם אֱלֹהֵיהֶם", "רבהם", "their Lord"),
        (None, "אלדאימה", "continually,"),
        ("וְהָיוּ", "יכונו", "they shall be"),
        ("קֹדֶשׁ", "מקדסין", "consecrated."),
    ],
    7: [
        (None, "באמראה", "With"),
        ("אִשָּׁה זֹנָה", "פאגרה", "a wanton"),
        ("וַחֲלָלָה", "ומבד'ולה", "and debased woman"),
        ("לֹא יִקָּחוּ", "לא יתזווגו.", "they shall not marry,"),
        (None, "ובאמראה", "and with a woman"),
        ("וְאִשָּׁה גְּרוּשָׁה", "מטלקה", "divorced"),
        ("מֵאִישָׁהּ", "מן בעלהא", "from her husband"),
        ("לֹא יִקָּחוּ", "לא יתזווגו.", "they shall not marry —"),
        (None, "פאן", "for"),
        (None, "כל ואחד מנהם", "every one of them"),
        ("כִּי-קָדֹשׁ הוּא לֵאלֹהָיו", "מקדס לרבה", "is consecrated to his Lord."),
    ],
    8: [
        ("וְקִדַּשְׁתּוֹ", "וקדסה", "And you shall consecrate him,"),
        (None, "באלאלזאם.", "as is obligatory —"),
        (None, "לאנה", "for"),
        ("הוּא מַקְרִיב", "יקרב", "he offers"),
        ("כִּי-אֶת-לֶחֶם", "קרבאן", "the offering of"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "אלדאים.", "the Eternal;"),
        (None, "פליכון", "he shall therefore be"),
        ("קָדֹשׁ יִהְיֶה-לָּךְ", "לך מקדסא.", "consecrated to you,"),
        (None, "כמא", "even as"),
        ("אֲנִי", "אני", "I,"),
        ("יְהוָה", "אללה", "God,"),
        ("מְקַדִּשְׁכֶם", "מקדסכם", "consecrate you."),
    ],
    9: [
        ("וּבַת", "ואיי אבנה'", "And whichever daughter of"),
        ("אִישׁ", "רג'ל", "a man"),
        ("כֹּהֵן", "אמאם.", "who is an imām"),
        (None, "תבד'לת", "has debased herself"),
        ("כִּי תֵחֵל לִזְנוֹת", "פפגרת.", "and acted wantonly —"),
        ("הִיא מְחַלֶּלֶת", "פקד פצ'חת", "she has brought public disgrace"),
        ("אֶת-אָבִיהָ", "אביהא", "upon her father;"),
        ("בָּאֵשׁ", "באלנאר", "with fire."),
        ("תִּשָּׂרֵף", "פלתחרק", "she shall be burned"),
    ],
    10: [
        ("וְהַכֹּהֵן", "ואלאמאם", "And the"),
        ("הַגָּדוֹל", "אלכביר", "great imām"),
        ("מֵאֶחָיו", "מן אכ'ותה.", "among his brothers,"),
        ("אֲשֶׁר-יוּצַק", "אלדי י'צב", "upon whose head"),
        ("עַל-רֹאשׁוֹ", "עלי' ראסה", "is poured"),
        ("שֶׁמֶן הַמִּשְׁחָה", "דהן אלמסח", "the anointing oil"),
        (None, "ויכמל ואגבה", "and whose obligation is fulfilled"),
        ("וּמִלֵּא", "בלבס", "by the wearing of"),
        ("אֶת-הַבְּגָדִים", "אלת'יאב.", "the vestments —"),
        ("לֹא יִפְרָע", "פלא ישעת", "he shall not dishevel"),
        ("אֶת-רֹאשׁוֹ", "ראסה.", "his head,"),
        ("וּבְגָדָיו לֹא יִפְרֹם", "ות'יאבה לא ימזקהא", "nor shall he tear his garments."),
    ],
    11: [
        ("וְעַל כָּל-נַפְשֹׁת", "ועלי אי אנסאן", "Over any"),
        ("מֵת", "מיית", "dead person"),
        ("לֹא יָבֹא", "לא ידכ'ל.", "he shall not enter;"),
        (None, "חתא", "even"),
        ("לְאָבִיו", "באביה", "for his father"),
        ("וּלְאִמּוֹ", "ואמה", "and his mother"),
        ("לֹא יִטַּמָּא", "לא ינגס", "he shall not become impure."),
    ],
    12: [
        ("וּמִן-הַמִּקְדָּשׁ", "ומן אלמקדס", "And from the sanctuary"),
        ("לֹא יֵצֵא", "לא יכ'רג", "he shall not go out"),
        (None, "וראהמא.", "after them,"),
        ("וְלֹא", "ולא", "nor"),
        ("יְחַלֵּל", "יבד'ל", "shall he debase"),
        ("אֵת מִקְדַּשׁ", "קדס", "the consecration of"),
        ("אֱלֹהָיו", "רבה.", "his Lord —"),
        (None, "לאן", "for,"),
        (None, "למא", "inasmuch as"),
        ("כִּי נֵזֶר", "תאג", "the crown of"),
        ("שֶׁמֶן מִשְׁחַת אֱלֹהָיו", "דהן מסח רבה", "his Lord's anointing oil"),
        ("עָלָיו", "עליה.", "is upon him,"),
        ("אֲנִי", "אנא", "I,"),
        ("יְהוָה", "אללה", "God,"),
        (None, "שרפתה", "have honored him."),
    ],
    13: [
        ("וְהוּא", "והו", "And he —"),
        (None, "פלא יתזווג אלא", "he shall marry none but"),
        ("אִשָּׁה בִבְתוּלֶיהָ יִקָּח", "באמראה בכר", "a virgin woman."),
    ],
    14: [
        (None, "אמא", "As for"),
        ("אַלְמָנָה", "ארמלה", "a widow,"),
        (None, "או", "or"),
        ("וּגְרוּשָׁה", "מטלקה", "a divorced woman,"),
        ("וַחֲלָלָה", "ומבד'ולה", "or a debased woman,"),
        ("זֹנָה", "ופאגרה.", "or a wanton woman —"),
        ("לֹא יִקָּח", "פלא יתזווג", "he shall not marry"),
        (None, "באחדי'", "any of"),
        ("אֶת-אֵלֶּה", "מן הולאי.", "these;"),
        (None, "אלא", "only"),
        ("בְּתוּלָה", "באמראה בכר", "a virgin woman"),
        ("מֵעַמָּיו", "מן קומה", "from his people"),
        ("יִקַּח אִשָּׁה", "יתזווג", "shall he marry."),
    ],
    15: [
        ("וְלֹא-יְחַלֵּל", "ולא יבד'ל", "And he shall not debase"),
        ("זַרְעוֹ", "נסלה", "his offspring"),
        (None, "בסואהא", "through any other than her"),
        ("בְּעַמָּיו", "מן קומה", "from his people —"),
        (None, "לאני", "for I,"),
        ("כִּי אֲנִי יְהוָה", "אללה", "God,"),
        ("מְקַדְּשׁוֹ", "מקדסה", "consecrate him.'"),
    ],
    16: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech."),
    ],
    17: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("לֵאמֹר", "וקל לה.", "and say to him:"),
        (None, "אי", "Any"),
        ("אִישׁ", "רגל", "man"),
        ("מִזַּרְעֲךָ", "מן נסלך", "from your offspring,"),
        ("לְדֹרֹתָם", "עלי' מר אגיאלהם.", "throughout their generations,"),
        ("אֲשֶׁר יִהְיֶה בוֹ", "יכון פיה", "in whom there is"),
        ("מוּם", "עיב.", "a blemish —"),
        ("לֹא יִקְרַב", "לא יתקדם.", "he shall not come forward"),
        ("לְהַקְרִיב", "ליקרב", "to offer"),
        ("לֶחֶם", "קרבאן", "the offering of"),
        ("אֱלֹהָיו", "רבה", "his Lord."),
    ],
    18: [
        (None, "לאן", "For"),
        ("כִּי כָל-אִישׁ", "כל רגל", "every man"),
        ("אֲשֶׁר-בּוֹ מוּם", "פיה עיב", "in whom there is a blemish"),
        ("לֹא יִקְרָב", "לא יתקדם.", "shall not come forward."),
        (None, "פמן ד'אלך", "Among such:"),
        ("אִישׁ עִוֵּר", "אלאעמא", "the blind"),
        ("אוֹ פִסֵּחַ", "ואלאזמן.", "and the lame,"),
        ("אוֹ חָרֻם", "ואלאכ'רם", "and one with a cleft nose"),
        ("אוֹ שָׂרוּעַ", "ואלכ'אמע", "and one who limps,"),
    ],
    19: [
        (None, "או", "or"),
        ("אוֹ אִישׁ", "רגל", "a man"),
        ("אֲשֶׁר-יִהְיֶה בוֹ", "יכון פיה", "in whom there is"),
        ("שֶׁבֶר רָגֶל", "כסר רגל.", "a broken leg"),
        (None, "או", "or"),
        ("אוֹ שֶׁבֶר יָד", "כסר יד", "a broken arm,"),
    ],
    20: [
        (None, "או", "or"),
        ("אוֹ-גִבֵּן", "אחדב", "a hunchback,"),
        ("אוֹ-דַק", "או אכ'פש.", "or one of dim sight,"),
        ("אוֹ תְּבַלֻּל בְּעֵינוֹ", "או כת'יב פי עינה.", "or one with a cataract in his eye,"),
        (None, "או בה", "or in whom there is"),
        ("אוֹ גָרָב", "גרב", "mange"),
        ("אוֹ יַלֶּפֶת", "או חזאז.", "or thick scaling of the head,"),
        ("אוֹ מְרוֹחַ אָשֶׁךְ", "או אדר", "or one with a crushed testicle —"),
    ],
    21: [
        (None, "כד'אך", "so too"),
        ("כָּל-אִישׁ", "כל רג'ל", "every man"),
        ("אֲשֶׁר-בּוֹ מוּם", "פיה עיב.", "in whom there is a blemish,"),
        ("מִזֶּרַע", "מן נסל", "from the offspring of"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām:"),
        ("לֹא יִגַּשׁ", "לא יתקדם", "he shall not come forward"),
        ("לְהַקְרִיב", "ליקרב", "to offer"),
        ("אֶת-אִשֵּׁי יְהוָה", "קרבאן אללה.", "the offering of God;"),
        (None, "ומהמא ד'אלך", "and whatever that"),
        ("מוּם בּוֹ", "אלעיב פיה.", "blemish be in him,"),
        (None, "פקרבאן", "the offering of"),
        ("לֶחֶם אֱלֹהָיו", "רבה.", "his Lord"),
        ("לֹא יִגַּשׁ לְהַקְרִיב", "לא יתקדם ליקרבה", "he shall not come forward to offer."),
    ],
    22: [
        (None, "לאכן", "However,"),
        ("לֶחֶם", "רזק", "the provision of"),
        ("אֱלֹהָיו", "רבה.", "his Lord —"),
        ("מִקָּדְשֵׁי הַקֳּדָשִׁים", "מן כ'ואץ אלאקדאס.", "from the choicest of the holy things"),
        ("וּמִן-הַקֳּדָשִׁים", "ועואמהא", "and from the general portions thereof —"),
        ("יֹאכֵל", "יאכל", "he may eat."),
    ],
    23: [
        (None, "אמא", "But"),
        ("אַךְ אֶל-הַפָּרֹכֶת", "אלי' אלסגף", "into the curtain"),
        ("לֹא יָבֹא", "פלא ידכ'ל.", "he shall not enter,"),
        ("וְאֶל-הַמִּזְבֵּחַ", "ואלי אלמד'בח.", "and to the altar"),
        ("לֹא יִגַּשׁ", "פלא יתקדם", "he shall not come forward,"),
        (None, "אד'", "since"),
        (None, "פיה", "there is"),
        ("כִּי-מוּם בּוֹ", "עיב.", "a blemish in him;"),
        ("וְלֹא", "ולא", "and he shall not"),
        ("יְחַלֵּל", "יבד'ל", "debase"),
        ("אֶת-מִקְדָּשַׁי", "מקאדסי.", "My sacred things —"),
        (None, "לאני", "for I,"),
        ("אֲנִי יְהוָה", "אללה", "God,"),
        ("מְקַדְּשָׁם", "מקדסהמא", "consecrate them.'"),
    ],
    24: [
        (None, "פאמר", "And"),
        ("וַיְדַבֵּר מֹשֶׁה", "מוסי' בד'אלך", "Moses commanded thereby"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה.", "and his sons,"),
        ("וְאֶל-כָּל-בְּנֵי", "וסאיר בני", "and the rest of the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel."),
    ],
}
