"""Hand-authored alignment triples for Vayikra chapter 15.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי''", "to Moses"),
        (None, "ו", "and"),
        ("וְאֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("לֵאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("דַּבְּרוּ", "כלמא", "Speak"),
        ("אֶל-בְּנֵי", "בני", "to the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וַאֲמַרְתֶּם", "וקולא", "and say"),
        ("אֲלֵהֶם", "להמא", "to them"),
        ("אִישׁ", "אי", "any"),
        ("אִישׁ", "רגל", "man"),
        ("כִּי יִהְיֶה זָב", "כאן ד'איבא", "who has a discharge"),
        ("מִבְּשָׂרוֹ", "מן אחלילה", "from his member"),
        ("זוֹבוֹ", "פד'ובה", "his discharge"),
        (None, "ד'אך", "—"),
        ("הוּא", "הו", "is"),
        ("טָמֵא", "נגס", "impure"),
    ],
    3: [
        (None, "ו", "And"),
        ("וְזֹאת", "הד'ה", "this"),
        (None, "צפה'", "is the description"),
        ("בְּזוֹבוֹ", "ד'ובה", "of his discharge"),
        ("תִּהְיֶה טֻמְאָתוֹ", "אלד'י תכון בה נגאסתה", "by which his impurity occurs"),
        ("רָר בְּשָׂרוֹ", "אמא אן יגעל אחלילה אלד'וב", "whether his member lets the discharge flow"),
        (None, "כאלריאל", "like a coin"),
        ("אוֹ-הֶחְתִּים", "או ינכ'תם", "or it becomes sealed"),
        ("מִזּוֹבוֹ", "מנה", "from it"),
        ("טֻמְאָתוֹ", "פתלך", "that is"),
        ("הִוא", "נגאסתה", "his impurity"),
    ],
    4: [
        (None, "ו", "And"),
        (None, "חכמה", "his ruling"),
        (None, "אן יכון", "is that"),
        ("כָּל-הַמִּשְׁכָּב", "כל מצ'גע", "every bed"),
        ("אֲשֶׁר יִשְׁכַּב עָלָיו", "ינצ'גע עליה", "upon which he lies"),
        ("יִטְמָא", "ינגס", "shall become impure"),
        ("וְכָל-הַכְּלִי", "וכל אנא", "and every vessel"),
        ("אֲשֶׁר-יֵשֵׁב עָלָיו", "יגלס עליה", "upon which he sits"),
        ("יִטְמָא", "ינגס", "shall become impure"),
    ],
    5: [
        ("וְאִישׁ", "ואי אנסאן", "And any person"),
        ("אֲשֶׁר יִגַּע", "דנא", "who approaches"),
        ("בְּמִשְׁכָּבוֹ", "מן מצ'געה", "his bed"),
        ("יְכַבֵּס", "פליג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    6: [
        ("וְהַיֹּשֵׁב", "ומן גלס", "And whoever sits"),
        ("עַל-הַכְּלִי", "עלי' אלאנא", "upon the vessel"),
        ("אֲשֶׁר-יֵשֵׁב עָלָיו", "אלד'י יגלס עליה", "upon which"),
        ("הַזָּב", "אלד'איב", "the one with a discharge sits"),
        ("יְכַבֵּס", "פליג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    7: [
        ("וְהַנֹּגֵעַ", "ומן דנא", "And whoever approaches"),
        ("בִּבְשַׂר הַזָּב", "בגסמה", "him bodily"),
        ("יְכַבֵּס", "פליג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    8: [
        ("וְכִי-יָרֹק", "ואד'א בצק", "And if the one with"),
        ("הַזָּב", "אלד'איב", "a discharge spits"),
        ("בַּטָּהוֹר", "עלי' אלטאהר", "upon the pure person"),
        ("וְכִבֶּס", "פליג'סל", "he shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    10: [
        ("וְכָל-הַנֹּגֵעַ", "ומן דנא", "And whoever approaches"),
        ("בְּכֹל אֲשֶׁר", "בשי מן מא", "anything that"),
        ("יִהְיֶה תַחְתָּיו", "יכון תחתה", "was beneath him"),
        ("יִטְמָא", "ינג'ס", "shall be made impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
        ("וְהַנּוֹשֵׂא", "ומן חמל", "and whoever carries"),
        ("אוֹתָם", "שי מנהא", "any of those things"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    11: [
        ("וְכֹל אֲשֶׁר יִגַּע-בּוֹ", "וכל מן דנא בה", "And everyone whom"),
        ("הַזָּב", "אלד'איב", "the one with a discharge approaches"),
        ("וְיָדָיו", "וד'אתה", "he himself"),
        ("לֹא-שָׁטַף", "לם יג'סל", "not having washed"),
        ("בַּמָּיִם", "באלמא", "in water"),
        ("וְכִבֶּס", "פליג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינג'ס", "and be made impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    12: [
        ("וּכְלִי-חֶרֶשׂ", "ואי אנא כ'זף", "And any earthenware vessel"),
        ("אֲשֶׁר-יִגַּע-בּוֹ", "דנא בה", "which the one with"),
        ("הַזָּב", "אלד'איב", "a discharge approaches"),
        ("יִשָּׁבֵר", "פליכסר", "shall be broken"),
        ("וְכָל-כְּלִי-עֵץ", "ואי אנא כ'שב", "and any wooden vessel"),
        ("יִשָּׁטֵף", "פליג'סל", "shall be washed"),
        ("בַּמָּיִם", "באלמא", "in water"),
    ],
    13: [
        (None, "פ", "And"),
        ("וְכִי-יִטְהַר", "אד'א הו טהר", "when he is purified"),
        ("מִזּוֹבוֹ", "מן ד'ובה", "from his discharge"),
        ("וְסָפַר לוֹ", "פליחץ", "he shall count off"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("לְטָהֳרָתוֹ", "לטהרה", "for his purification"),
        ("וְכִבֶּס", "ויג'סל", "and wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בְּשָׂרוֹ", "בדנה", "his body"),
        ("בְּמַיִם חַיִּים", "במא מן נביע", "in water from a spring"),
        ("וְטָהֵר", "ויטהר", "and he shall be pure"),
    ],
    14: [
        ("וּבַיּוֹם", "ופי אליום", "And on the"),
        ("הַשְּׁמִינִי", "אלת'אמן", "eighth day"),
        ("יִקַּח-לוֹ", "יאתי ב", "he shall bring"),
        ("שְׁתֵּי תֹרִים", "שפנינין", "two turtledoves"),
        ("אוֹ", "או", "or"),
        ("שְׁנֵי בְּנֵי יוֹנָה", "פרכ'י חמאם", "two young pigeons"),
        ("וּבָא", "ויאתי", "and come"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("וּנְתָנָם", "ויסלמהא", "and deliver them"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the priest"),
    ],
    15: [
        ("וְעָשָׂה", "ויעמל", "And"),
        ("אֹתָם הַכֹּהֵן", "אלאמאם", "the priest shall make"),
        ("אֶחָד", "אחדהמא", "one of them"),
        ("חַטָּאת", "ד'כוה", "a purification-offering"),
        ("וְהָאֶחָד", "ואלאכ'ר", "and the other"),
        ("עֹלָה", "צעידה", "a burnt-offering"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek forgiveness"),
        ("עָלָיו", "ענה", "for him"),
        ("הַכֹּהֵן", "בין ידי", "before"),
        ("לִפְנֵי יְהוָה", "אללה", "God"),
        ("מִזּוֹבוֹ", "מן ד'ובה", "on account of his discharge"),
    ],
    16: [
        ("וְאִישׁ", "ואיי רגל", "And any man"),
        ("כִּי-תֵצֵא", "כ'רגת", "goes forth"),
        ("מִמֶּנּוּ", "מנה", "from whom"),
        ("שִׁכְבַת-זָרַע", "נטפה' אנסאל", "a drop of seed of propagation"),
        ("וְרָחַץ", "פליג'סל", "shall wash"),
        ("אֶת-כָּל-בְּשָׂרוֹ", "גמיע", "all"),
        (None, "בדנה", "his body"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    17: [
        ("וְכָל-בֶּגֶד", "ואיי ת'וב", "And any garment"),
        ("וְכָל-עוֹר", "או גלד", "or skin"),
        ("אֲשֶׁר-יִהְיֶה עָלָיו", "צאר עליה", "upon which"),
        ("שִׁכְבַת-זָרַע", "מנה שי", "anything from it has fallen"),
        ("וְכֻבַּס", "פליג'סל", "shall be washed"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    18: [
        ("וְאִשָּׁה", "ואייה' אמראה", "And any woman"),
        ("אֲשֶׁר יִשְׁכַּב", "צ'אגעהא", "with whom"),
        ("אִישׁ", "רג'ל", "a man"),
        ("שִׁכְבַת-זָרַע", "בנטפה", "lies with a drop of seed"),
        ("וְרָחֲצוּ", "פלירחצ'א", "both of them shall bathe"),
        ("בַמַּיִם", "באלמא", "in water"),
        ("וְטָמְאוּ", "וינגסא", "and be made impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    19: [
        ("וְאִשָּׁה", "אייה' אמראה", "Any woman"),
        ("כִּי-תִהְיֶה זָבָה", "כאנת ד'איבה", "who has a discharge"),
        (None, "ו", "that is"),
        (None, "הו אן יכון", "when"),
        ("דָּם", "אלדם", "blood"),
        ("יִהְיֶה זֹבָהּ", "ינחל", "flows"),
        ("בִּבְשָׂרָהּ", "מן פרגהא", "from her opening"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("תִּהְיֶה בְנִדָּתָהּ", "פי חיצ'תהא", "in her menstrual period"),
        (None, "פלתקים", "she shall remain"),
        ("וְכָל-הַנֹּגֵעַ", "וכל מן דנא", "and everyone who approaches"),
        ("בָּהּ", "בהא", "her"),
        ("יִטְמָא", "ינג'ס", "shall be made impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    20: [
        ("וְכֹל אֲשֶׁר", "וגמיע מא", "And everything upon which"),
        ("תִּשְׁכַּב עָלָיו", "תנצ'גע עליה", "she lies"),
        ("בְּנִדָּתָהּ", "פי חיצ'תהא", "during her menstrual period"),
        ("יִטְמָא", "ינג'ס", "shall become impure"),
        ("וְכֹל", "וגמיע", "and every"),
        ("אֲשֶׁר-תֵּשֵׁב עָלָיו", "אלא'נא אלד'י תגלס עליה", "vessel upon which she sits"),
        ("יִטְמָא", "ינגס", "shall become impure"),
    ],
    21: [
        ("וְכָל-הַנֹּגֵעַ", "וכל מן דנא", "And everyone who approaches"),
        ("בְּמִשְׁכָּבָהּ", "במצ'געהא", "her bed"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    22: [
        ("וְכָל-הַנֹּגֵעַ", "וכל מן דנא", "And everyone who approaches"),
        (None, "בשי", "anything"),
        ("בְּכָל-כְּלִי", "מן אלאניה", "from the vessels"),
        ("אֲשֶׁר-תֵּשֵׁב עָלָיו", "אלד'י תגלס עליה", "upon which she sits"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    23: [
        ("וְאִם", "ואן", "And if"),
        (None, "כאן", "there is"),
        ("עַל-הַמִּשְׁכָּב", "עלי' מצ'געהא", "whether upon her bed"),
        ("אוֹ", "או", "or"),
        ("עַל-הַכְּלִי", "עלי' אלאנא", "upon the vessel"),
        ("אֲשֶׁר-הִוא יֹשֶׁבֶת-עָלָיו", "אלתי הי גאלסה עליה", "upon which she is sitting"),
        ("בְּנָגְעוֹ-בוֹ", "ממאסה לה", "contact with it"),
        ("יִטְמָא", "פלינגס", "he shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    24: [
        (None, "ו", "And"),
        ("וְאִם", "אן", "if"),
        ("שָׁכֹב יִשְׁכַּב", "צ'אגעהא", "lies with her"),
        ("אִישׁ", "רג'ל", "a man"),
        ("וּתְהִי נִדָּתָהּ עָלָיו", "פקד צאר חכם חיצ'תהא עליה", "then the ruling of her menstrual period comes upon him"),
        ("וְטָמֵא", "וינגס", "and he shall be impure"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("וְכָל-הַמִּשְׁכָּב", "וכל מצ'גע", "and every bed"),
        ("אֲשֶׁר-יִשְׁכַּב עָלָיו", "ינצ'גע עליה", "upon which he lies"),
        ("יִטְמָא", "ינגס", "shall become impure"),
    ],
    25: [
        ("וְאִשָּׁה", "ואייה' אמראה", "And any woman"),
        ("כִּי-יָזוּב זוֹב דָּמָהּ", "פאץ' דמהא", "whose blood flows"),
        ("יָמִים רַבִּים", "אייאמא כתירה", "for many days"),
        ("בְּלֹא עֶת-נִדָּתָהּ", "פי ג'יר וקת חיצ'תהא", "outside the time of her menstrual period"),
        ("אוֹ", "או", "or"),
        ("כִי-תָזוּב עַל-נִדָּתָהּ", "בעקבה", "following upon it"),
        ("כָּל-יְמֵי", "פגמיע אייאם", "all the days"),
        ("זוֹב טֻמְאָתָהּ", "פיץ' נגאסתהא", "of the flow of her impurity"),
        ("כִּימֵי נִדָּתָהּ", "כאייאם חיצ'תהא", "as in the days of her menstrual period"),
        ("תִּהְיֶה", "פלתכון פיהא", "she shall be in it"),
        ("טְמֵאָה הִוא", "נגסה", "impure"),
    ],
    26: [
        ("כָּל-הַמִּשְׁכָּב", "וגמיע אלמצ'גע", "And every bed"),
        ("אֲשֶׁר-תִּשְׁכַּב עָלָיו", "אלד'י תנצ'גע עליה", "upon which she lies"),
        ("כָּל-יְמֵי זוֹבָהּ", "טול אייאם פיצ'האכ", "throughout the days of her flow"),
        ("כְּמִשְׁכַּב נִדָּתָהּ", "כמצ'גע חיצ'תהא", "as her bed during her menstrual period"),
        ("יִהְיֶה-לָּהּ", "פלתכון להא", "shall be to her"),
        ("וְכָל-הַכְּלִי", "וגמיע אלאנא", "and every vessel"),
        ("אֲשֶׁר תֵּשֵׁב עָלָיו", "אלד'י תגלס עליה", "upon which she sits"),
        ("טָמֵא יִהְיֶה", "פליכון נגסא", "shall be impure"),
        ("כְּטֻמְאַת נִדָּתָהּ", "כנגאסתה פי חיצ'תהא", "as its impurity during her menstrual period"),
    ],
    27: [
        ("וְכָל-הַנּוֹגֵעַ", "וכל מן דנא", "And everyone who approaches"),
        ("בָּם", "בשי מנהא", "anything of hers"),
        ("יִטְמָא", "ינגס", "shall become impure"),
        ("וְכִבֶּס", "פיג'סל", "and he shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until sunset"),
    ],
    28: [
        (None, "פ", "But"),
        ("וְאִם-טָהֲרָה", "אן טהרת", "if she is purified"),
        ("מִזּוֹבָהּ", "מן פיצ'הא", "from her flow"),
        ("וְסָפְרָה לָּהּ", "פלתחץ", "she shall count off"),
        ("שִׁבְעַת יָמִים", "סבעה אייאם", "seven days"),
        ("וְאַחַר", "ובעד ד'אלך", "and after that"),
        ("תִּטְהָר", "תטהר", "she shall be pure"),
    ],
    29: [
        ("וּבַיּוֹם", "ופי אליום", "And on the"),
        ("הַשְּׁמִינִי", "אלת'אמן", "eighth day"),
        ("תִּקַּח-לָהּ", "תאכ'ד'", "she shall take"),
        ("שְׁתֵּי תֹרִים", "שפנינין", "two turtledoves"),
        ("אוֹ", "או", "or"),
        ("שְׁנֵי בְּנֵי יוֹנָה", "פרכ'י חמאם", "two young pigeons"),
        ("וְהֵבִיאָה", "ותאתי בהמא", "and bring them"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the priest"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
    ],
    30: [
        ("וְעָשָׂה", "ויעמל", "And"),
        ("הַכֹּהֵן", "אלאמאם", "the priest shall make"),
        ("אֶת-הָאֶחָד", "אחדהמא", "one of them"),
        ("חַטָּאת", "ד'כוה", "a purification-offering"),
        ("וְאֶת-הָאֶחָד", "ואלאכ'ר", "and the other"),
        ("עֹלָה", "צעידה", "a burnt-offering"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek forgiveness"),
        ("עָלֶיהָ", "ענהא", "for her"),
        ("הַכֹּהֵן", "בין ידי", "before"),
        ("לִפְנֵי יְהוָה", "אללה", "God"),
        ("מִזּוֹב טֻמְאָתָהּ", "מן פיץ' נגאסתהא", "on account of the flow of her impurity"),
    ],
    31: [
        (None, "פ", "It is therefore"),
        (None, "יגב אן", "required that"),
        ("וְהִזַּרְתֶּם", "תגאנבא", "be kept apart"),
        ("אֶת-בְּנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("מִטֻּמְאָתָם", "מן נגאסתהם", "from their impurity"),
        ("וְלֹא יָמֻתוּ", "ולא יהלכון", "so that they do not perish"),
        ("בְּטֻמְאָתָם", "בנגאסתהם", "through their impurity"),
        (None, "אד'", "for"),
        ("בְּטַמְּאָם", "הם נגסו", "they would defile"),
        ("אֶת-מִשְׁכָּנִי", "מסכני", "My dwelling"),
        ("אֲשֶׁר בְּתוֹכָם", "אלד'י פי מא בינהם", "that is among them"),
    ],
    32: [
        ("זֹאת", "הד'ה", "This"),
        ("תּוֹרַת הַזָּב", "שריעה' אלד'איב", "is the ordinance of the one with a discharge"),
        ("וַאֲשֶׁר", "ומן", "and of him from whom"),
        ("תֵּצֵא מִמֶּנּוּ", "תכ'ר'ג מנה", "goes forth"),
        ("שִׁכְבַת-זֶרַע", "נטפה", "a drop of seed"),
        ("לְטָמְאָה-בָהּ", "לאלתנגס בהא", "causing impurity"),
    ],
    33: [
        ("וְהַדָּוָה", "ואלחאיץ'", "And of the menstruating woman"),
        ("בְּנִדָּתָהּ", "פי טמת'הא", "in her menstruation"),
        ("וְהַזָּב", "ואלפאיץ'", "and of the one with a flow"),
        ("אֶת-זוֹבוֹ", "פי ד'ובה", "in his discharge"),
        ("לַזָּכָר", "מן ד'כר", "male"),
        ("וְלַנְּקֵבָה", "ואנת'י", "and female"),
        ("וּלְאִישׁ", "ורג'ל", "and of a man"),
        ("אֲשֶׁר יִשְׁכַּב", "יצ'אגע", "who lies"),
        ("עִם-טְמֵאָה", "נגסה", "with an impure woman"),
    ],
}
