"""Hand-authored alignment triples for Vayikra chapter 4."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר",
         "מר בני אסראיל קאילא",
         "Command the sons of Israel, saying"),
        ("נֶפֶשׁ כִּי-תֶחֱטָא בִשְׁגָגָה מִכֹּל מִצְו‍ֹת יְהוָה אֲשֶׁר לֹא תֵעָשֶׂינָה",
         "אי אנסאן אכ'טא בסהו מן פראיץ' אללה. אלתי לא תעמל",
         "any person who errs through inattention regarding the commandments of God which are not to be done"),
        ("וְעָשָׂה מֵאַחַת מֵהֵנָּה",
         "פעמל וחדה מנהם",
         "and does one of them —"),
    ],
    3: [
        ("אִם הַכֹּהֵן הַמָּשִׁיחַ יֶחֱטָא לְאַשְׁמַת הָעָם",
         "אן אכ'טא אלאמאם אלממסוח. עלי' סביל כ'טא אלנאס",
         "if the anointed imām errs in the manner of the people's error"),
        ("וְהִקְרִיב עַל חַטָּאתוֹ אֲשֶׁר חָטָא פַּר בֶּן-בָּקָר תָּמִים לַיהוָה--לְחַטָּאת",
         "פליקרב. עלי' כ'טייתה אלתי אכ'טא. רת'א מן אלבקר צחיחא. ללה ד'כוה",
         "let him bring, for his transgression which he transgressed, a bull from the cattle, sound, as an offering to God."),
    ],
    4: [
        ("וְהֵבִיא אֶת-הַפָּר אֶל-פֶּתַח אֹהֶל מוֹעֵד--לִפְנֵי יְהוָה",
         "ויאתי באלרת'. אלי' באב כ'בא אלמחצ'ר בין ידי אללה",
         "And he shall bring the bull to the entrance of the tent of the assembly, before God"),
        ("וְסָמַךְ אֶת-יָדוֹ עַל-רֹאשׁ הַפָּר וְשָׁחַט אֶת-הַפָּר לִפְנֵי יְהוָה",
         "ויסנד ידה עלי' ראסה. ויד'בחה בין ידי אללה",
         "and he shall lean his hand upon its head, and shall slaughter it before God."),
    ],
    5: [
        ("וְלָקַח הַכֹּהֵן הַמָּשִׁיחַ מִדַּם הַפָּר",
         "ויאכד' אלאמאם אלממסוח מן דמה",
         "And the anointed imām shall take of its blood"),
        ("וְהֵבִיא אֹתוֹ אֶל-אֹהֶל מוֹעֵד",
         "וידכלה אלי' כ'בא אלמחצ'ר",
         "and bring it into the tent of the assembly."),
    ],
    6: [
        ("וְטָבַל הַכֹּהֵן אֶת-אֶצְבָּעוֹ בַּדָּם",
         "ויג'מס אצבעה פי אלדם",
         "And he shall dip his finger in the blood"),
        ("וְהִזָּה מִן-הַדָּם שֶׁבַע פְּעָמִים לִפְנֵי יְהוָה אֶת-פְּנֵי פָּרֹכֶת הַקֹּדֶשׁ",
         "וינצח מנה. סבע מראר בין ידי אללה. קבאלה' סגף אלקדס",
         "and sprinkle from it seven times before God, facing the veil of the sanctuary."),
    ],
    7: [
        ("וְנָתַן הַכֹּהֵן מִן-הַדָּם עַל-קַרְנוֹת מִזְבַּח קְטֹרֶת הַסַּמִּים לִפְנֵי יְהוָה אֲשֶׁר בְּאֹהֶל מוֹעֵד",
         "ת'ם יצע אלאמאם מן אלדם. עלי' ארכאן מד'בח בכור אלצמוג' בין ידי אללה. אלד'י פי כ'בא אלמחצ'ר",
         "Then the imām shall put of the blood upon the horns of the altar of the incense of resins, before God, which is in the tent of the assembly"),
        ("וְאֵת כָּל-דַּם הַפָּר יִשְׁפֹּךְ אֶל-יְסוֹד מִזְבַּח הָעֹלָה אֲשֶׁר-פֶּתַח אֹהֶל מוֹעֵד",
         "ובאקי אלדם. יצ'בה ענד אסאס מד'בח אלצעידה אלד'י ענד באב כ'בא אלמחצ'ר",
         "and the remainder of the blood he shall pour out at the base of the altar of the burnt-offering which is at the entrance of the tent of the assembly."),
    ],
    8: [
        ("וְאֶת-כָּל-חֵלֶב פַּר הַחַטָּאת יָרִים מִמֶּנּוּ--אֶת-הַחֵלֶב הַמְכַסֶּה עַל-הַקֶּרֶב",
         "וגמיע שחם רת' אלד'כוה ינזעה מנה. אלת'רב אלמג'טי אלגוף",
         "And all the fat of the bull of the offering he shall remove from it — the caul covering the entrails"),
        ("וְאֵת כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב",
         "וסאיר אלשחם. אלד'י עלי' אלגוף",
         "and the rest of the fat which is upon the entrails,"),
    ],
    9: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת וְאֶת-הַחֵלֶב אֲשֶׁר עֲלֵיהֶן אֲשֶׁר עַל-הַכְּסָלִים",
         "ואלכלותין. ואלשחם אלד'י עליהמא. אלד'י עלי' אלאחשא",
         "and the two kidneys, and the fat which is upon them, which is upon the viscera"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד עַל-הַכְּלָיוֹת יְסִירֶנָּה",
         "וזיאדה' אלכבד. מע אלכלי'' ינזעהא",
         "and the lobe of the liver — together with the kidneys he shall remove them."),
    ],
    10: [
        ("כַּאֲשֶׁר יוּרַם מִשּׁוֹר זֶבַח הַשְּׁלָמִים וְהִקְטִירָם הַכֹּהֵן עַל מִזְבַּח הָעֹלָה",
         "כמא ירפע. מן ת'ור ד'בח אלסלאמה. ויקתרה עלי' מד'בח אלצעידה",
         "As it is raised from the bull of the peace-offering; and the imām shall burn them in smoke upon the altar of the burnt-offering."),
    ],
    11: [
        ("וְאֶת-עוֹר הַפָּר וְאֶת-כָּל-בְּשָׂרוֹ עַל-רֹאשׁוֹ וְעַל-כְּרָעָיו וְקִרְבּוֹ וּפִרְשׁוֹ",
         "וגלד אלת'ור וגמיע לחמה. מע ראסה ואכארעה. ובטנה ופרתה",
         "And the hide of the bull and all its flesh, together with its head and its legs, and its belly and its dung —"),
    ],
    12: [
        ("וְהוֹצִיא אֶת-כָּל-הַפָּר אֶל-מִחוּץ לַמַּחֲנֶה אֶל-מָקוֹם טָהוֹר אֶל-שֶׁפֶךְ הַדֶּשֶׁן",
         "ויכ'רג גמיע ד'אלך. אלי' כ'ארג אלעסכר. אלי' מוצ'ע טאהר אלי' מטרח אלרמאד",
         "he shall carry all of it outside the camp, to a clean place, to the place where the ash is cast"),
        ("וְשָׂרַף אֹתוֹ עַל-עֵצִים בָּאֵשׁ עַל-שֶׁפֶךְ הַדֶּשֶׁן יִשָּׂרֵף",
         "ויחרקה עלי' חטב באלנאר. פי מוצ'ע מטרח אלרמאד יחרק",
         "and shall burn it upon wood with fire; at the place where the ash is cast it shall be burned."),
    ],
    13: [
        ("וְאִם כָּל-עֲדַת יִשְׂרָאֵל יִשְׁגּוּ וְנֶעְלַם דָּבָר מֵעֵינֵי הַקָּהָל",
         "ואן סהי' גמע מן גמיע אל אסראיל. וג'בי אמר מן עיון אלגוק",
         "And if a congregation from all the house of Israel errs, and a matter is hidden from the eyes of the assembly"),
        ("וְעָשׂוּ אַחַת מִכָּל-מִצְו‍ֹת יְהוָה אֲשֶׁר לֹא-תֵעָשֶׂינָה--וְאָשֵׁמוּ",
         "פעמלו. ואחדה מן פראיץ' אללה. אלתי לא תעמל פאת'מו",
         "and they do one of the commandments of God which are not to be done, and they sin —"),
    ],
    14: [
        ("וְנוֹדְעָה הַחַטָּאת אֲשֶׁר חָטְאוּ עָלֶיהָ",
         "ת'ם ערפת אלכ'טייה. אלתי אכ'טו בהא",
         "then the transgression which they committed becomes known"),
        ("וְהִקְרִיבוּ הַקָּהָל פַּר בֶּן-בָּקָר לְחַטָּאת וְהֵבִיאוּ אֹתוֹ לִפְנֵי אֹהֶל מוֹעֵד",
         "פליקרב אלגוק. רת'א מן אלבקר לאלד'כוה. ויאתו בה. אלי' באב כ'בא אלמחצ'ר",
         "let the assembly bring a bull from the cattle as an offering, and bring it to the entrance of the tent of the assembly."),
    ],
    15: [
        ("וְסָמְכוּ זִקְנֵי הָעֵדָה אֶת-יְדֵיהֶם עַל-רֹאשׁ הַפָּר--לִפְנֵי יְהוָה",
         "ויסנד. שיוך' אלגמאעה אידיהם. עלי' ראס אלת'ור בין ידי אללה",
         "And the elders of the congregation shall lean their hands upon the head of the bull before God"),
        ("וְשָׁחַט אֶת-הַפָּר לִפְנֵי יְהוָה",
         "ויד'בחה בין ידי אללה",
         "and it shall be slaughtered before God."),
    ],
    16: [
        ("וְהֵבִיא הַכֹּהֵן הַמָּשִׁיחַ מִדַּם הַפָּר אֶל-אֹהֶל מוֹעֵד",
         "וידכ'ל. אלאמאם אלממסוח מן דמה. אלי' כ'בא אלמחצ'ר",
         "And the anointed imām shall bring of its blood into the tent of the assembly."),
    ],
    17: [
        ("וְטָבַל הַכֹּהֵן אֶצְבָּעוֹ מִן-הַדָּם וְהִזָּה שֶׁבַע פְּעָמִים לִפְנֵי יְהוָה אֵת פְּנֵי הַפָּרֹכֶת",
         "ויג'מס אצבעה פיה. וינצח מנה. סבע מראר בין ידי אללה. קבאלה' אלסגף",
         "And he shall dip his finger in it, and sprinkle from it seven times before God, facing the veil."),
    ],
    18: [
        ("וּמִן-הַדָּם יִתֵּן עַל-קַרְנֹת הַמִּזְבֵּחַ אֲשֶׁר לִפְנֵי יְהוָה אֲשֶׁר בְּאֹהֶל מוֹעֵד",
         "ומנה. יצע עלי' ארכאן אלמד'בח. אלד'י בין ידי אללה. אלד'י פי כ'בא אלמחצ'ר",
         "And from it he shall put upon the horns of the altar which is before God, which is in the tent of the assembly"),
        ("וְאֵת כָּל-הַדָּם יִשְׁפֹּךְ אֶל-יְסוֹד מִזְבַּח הָעֹלָה אֲשֶׁר-פֶּתַח אֹהֶל מוֹעֵד",
         "ובאקיה יצבה ענד אסאס מד'בח אלצעידה. אלד'י ענד באב כ'בא אלמחצ'ר",
         "and the remainder of it he shall pour out at the base of the altar of the burnt-offering which is at the entrance of the tent of the assembly."),
    ],
    19: [
        ("וְאֵת כָּל-חֶלְבּוֹ יָרִים מִמֶּנּוּ וְהִקְטִיר הַמִּזְבֵּחָה",
         "וגמיע שחמה ירפעה מנה. ויקתרה עלי' אלמד'בח",
         "And all its fat he shall remove from it, and burn it in smoke upon the altar."),
    ],
    20: [
        ("וְעָשָׂה לַפָּר--כַּאֲשֶׁר עָשָׂה לְפַר הַחַטָּאת כֵּן יַעֲשֶׂה-לּוֹ",
         "ויעמל בה כמא עמל ברת' אלדכוה. כד'אך יעמל בה",
         "And he shall do with it as he did with the bull of the offering — thus shall he do with it"),
        ("וְכִפֶּר עֲלֵהֶם הַכֹּהֵן וְנִסְלַח לָהֶם",
         "ויסתג'פר ענהם. אלאמאם ויג'פר להם",
         "and the imām shall seek forgiveness for them, and they shall be forgiven."),
    ],
    21: [
        ("וְהוֹצִיא אֶת-הַפָּר אֶל-מִחוּץ לַמַּחֲנֶה וְשָׂרַף אֹתוֹ כַּאֲשֶׁר שָׂרַף אֵת הַפָּר הָרִאשׁוֹן",
         "ויכ'רג גמיע אלת'ור אלי' כ'ארג אלעסכר. ויחרקה. כמא אחרק אלת'ור אלאוול",
         "And he shall carry all of the bull outside the camp, and shall burn it, as he burned the first bull —"),
        ("חַטַּאת הַקָּהָל הוּא",
         "הו ד'כוה' אלגוק",
         "it is the offering of the assembly."),
    ],
    22: [
        ("אֲשֶׁר נָשִׂיא יֶחֱטָא וְעָשָׂה אַחַת מִכָּל-מִצְו‍ֹת יְהוָה אֱלֹהָיו אֲשֶׁר לֹא-תֵעָשֶׂינָה בִּשְׁגָגָה--וְאָשֵׁם",
         "ואן אכ'טא שריף. ועמל ואחדה מן פראיץ' אללה רבה. אלתי לא תעמל. סהוא פאת'מו",
         "And if a noble errs, and does one of the commandments of God his Lord which are not to be done, inadvertently, and so sins —"),
    ],
    23: [
        ("אוֹ-הוֹדַע אֵלָיו חַטָּאתוֹ אֲשֶׁר חָטָא בָּהּ",
         "ת'ם עלם בכ'טייתה אלד'י אכ'טא",
         "then his transgression which he transgressed becomes known"),
        ("וְהֵבִיא אֶת-קָרְבָּנוֹ שְׂעִיר עִזִּים זָכָר תָּמִים",
         "פליאת בקרבאנה. עתוד מן אלמאעז ד'כר צחיח",
         "let him bring his offering, a he-goat from the goats, a male, sound."),
    ],
    24: [
        ("וְסָמַךְ יָדוֹ עַל-רֹאשׁ הַשָּׂעִיר וְשָׁחַט אֹתוֹ",
         "ויסנד ידה עלי' ראסה. ויד'בחה",
         "And he shall lean his hand upon its head, and shall slaughter it"),
        ("בִּמְקוֹם אֲשֶׁר-יִשְׁחַט אֶת-הָעֹלָה לִפְנֵי יְהוָה חַטָּאת הוּא",
         "פי מוצ'ע יד'בח אלצעידה בין ידי אללה. כד'אך מא יכון ד'כוה",
         "in the place where the burnt-offering is slaughtered, before God — such is what constitutes an offering."),
    ],
    25: [
        ("וְלָקַח הַכֹּהֵן מִדַּם הַחַטָּאת בְּאֶצְבָּעוֹ וְנָתַן עַל-קַרְנֹת מִזְבַּח הָעֹלָה",
         "ויאכ'ד' אלאמאם מן דמה באצבעה. ויגעל. עלי' ארכאן מד'בח אלצעידה",
         "And the imām shall take of its blood with his finger, and shall place it upon the horns of the altar of the burnt-offering"),
        ("וְאֶת-דָּמוֹ יִשְׁפֹּךְ אֶל-יְסוֹד מִזְבַּח הָעֹלָה",
         "וסאיר דמה. יצבה ענד אסאסה",
         "and the rest of its blood he shall pour out at its base."),
    ],
    26: [
        ("וְאֶת-כָּל-חֶלְבּוֹ יַקְטִיר הַמִּזְבֵּחָה כְּחֵלֶב זֶבַח הַשְּׁלָמִים",
         "וגמיע שחמה יקתרה עלי' אלמד'בח. כשחם ד'בח אלסלאמה",
         "And all its fat he shall burn in smoke upon the altar, like the fat of the peace-offering"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן מֵחַטָּאתוֹ וְנִסְלַח לוֹ",
         "ויסתג'פר ענה אלאמאם. מן כ'טייתה אלד'י אכ'טא ויג'פר לה",
         "and the imām shall seek forgiveness for him from the transgression he transgressed, and he shall be forgiven."),
    ],
    27: [
        ("וְאִם-נֶפֶשׁ אַחַת תֶּחֱטָא בִשְׁגָגָה מֵעַם הָאָרֶץ בַּעֲשֹׂתָהּ אַחַת מִמִּצְו‍ֹת יְהוָה אֲשֶׁר לֹא-תֵעָשֶׂינָה--וְאָשֵׁם",
         "ואן אכ'טא אנסאן ואחד מן עואם אלבלד סהוא. פעמל. ואחדה מן פראיץ' אללה. אלתי לא תעמל פאת'ם",
         "And if a single person from among the common people of the land errs inadvertently, and does one of the commandments of God which are not to be done, and sins —"),
    ],
    28: [
        ("אוֹ הוֹדַע אֵלָיו חַטָּאתוֹ אֲשֶׁר חָטָא",
         "ת'ם ערף. בכ'טייתה אלד'י אכ'טא",
         "then his transgression which he transgressed becomes known"),
        ("וְהֵבִיא קָרְבָּנוֹ שְׂעִירַת עִזִּים תְּמִימָה נְקֵבָה עַל-חַטָּאתוֹ אֲשֶׁר חָטָא",
         "פליאת בקרבאנה. שאה מן אלמאעז צחיחה אנת'י. עלי' כ'טייתה אלד'י אכ'טא",
         "let him bring his offering, a she-goat from the goats, sound, a female, for his transgression which he transgressed."),
    ],
    29: [
        ("וְסָמַךְ אֶת-יָדוֹ עַל רֹאשׁ הַחַטָּאת וְשָׁחַט אֶת-הַחַטָּאת בִּמְקוֹם הָעֹלָה",
         "ויסנד ידה עלי' ראסהא. ויד'בחהא. פי מו'צע אלצעידה",
         "And he shall lean his hand upon its head, and shall slaughter it at the place of the burnt-offering."),
    ],
    30: [
        ("וְלָקַח הַכֹּהֵן מִדָּמָהּ בְּאֶצְבָּעוֹ וְנָתַן עַל-קַרְנֹת מִזְבַּח הָעֹלָה",
         "ויאכ'ד' אלאמאם מן דמהא באצבעה. ויגעל. עלי' ארכאן מד'בח אלצעידה",
         "And the imām shall take of its blood with his finger, and shall place it upon the horns of the altar of the burnt-offering"),
        ("וְאֶת-כָּל-דָּמָהּ יִשְׁפֹּךְ אֶל-יְסוֹד הַמִּזְבֵּחַ",
         "וסאיר דמהא יצ'בה. ענד אסאס אלמד'בח",
         "and the rest of its blood he shall pour out at the base of the altar."),
    ],
    31: [
        ("וְאֶת-כָּל-חֶלְבָּהּ יָסִיר כַּאֲשֶׁר הוּסַר חֵלֶב מֵעַל זֶבַח הַשְּׁלָמִים",
         "וגמיע שחמהא ינזעה. כמא נזע שחם אלמאעז מן ד'בח אלסלאמה",
         "And all its fat he shall remove, as the fat of the goats is removed from the peace-offering"),
        ("וְהִקְטִיר הַכֹּהֵן הַמִּזְבֵּחָה לְרֵיחַ נִיחֹחַ לַיהוָה",
         "ויקתרה אלאמאם עלי' אלמד'בח. עלי' קראבין אללה",
         "and the imām shall burn it in smoke upon the altar, above the offerings to God"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן וְנִסְלַח לוֹ",
         "ויסתג'פר ענה. אלאמאם ויג'פר לה",
         "and the imām shall seek forgiveness for him, and he shall be forgiven."),
    ],
    32: [
        ("וְאִם-כֶּבֶשׂ יָבִיא קָרְבָּנוֹ לְחַטָּאת--נְקֵבָה תְמִימָה יְבִיאֶנָּה",
         "ואן הו גאב קרבאנא מן אלצ'אן לאלד'כוה. פליאת בה אנת'י צחיחה",
         "And if he brings his offering from the flock as an offering, let him bring it as a female, sound."),
    ],
    33: [
        ("וְסָמַךְ אֶת-יָדוֹ עַל רֹאשׁ הַחַטָּאת וְשָׁחַט אֹתָהּ לְחַטָּאת בִּמְקוֹם אֲשֶׁר יִשְׁחַט אֶת-הָעֹלָה",
         "ויסנד ידה עלי' ראסהא. ויד'בחהא לאלד'כוה. פי מוצ'ע אלצעידה",
         "And he shall lean his hand upon its head, and shall slaughter it as an offering, at the place of the burnt-offering."),
    ],
    34: [
        ("וְלָקַח הַכֹּהֵן מִדַּם הַחַטָּאת בְּאֶצְבָּעוֹ וְנָתַן עַל-קַרְנֹת מִזְבַּח הָעֹלָה",
         "ויאכד מן דמהא באצבעה. ויצ'ע. עלי' ארכאן מד'בח אלצעידה",
         "And he shall take of its blood with his finger, and shall place it upon the horns of the altar of the burnt-offering"),
        ("וְאֶת-כָּל-דָּמָהּ יִשְׁפֹּךְ אֶל-יְסוֹד הַמִּזְבֵּחַ",
         "וסאיר דמהא יצ'בה. ענד אסאסה",
         "and the rest of its blood he shall pour out at its base."),
    ],
    35: [
        ("וְאֶת-כָּל-חֶלְבָּהּ יָסִיר כַּאֲשֶׁר יוּסַר חֵלֶב-הַכֶּשֶׂב מִזֶּבַח הַשְּׁלָמִים",
         "וגמיע שחמהא ינזעה. כמא ינזע שחם אלצ'אן מן ד'בח אלסלאמה",
         "And all its fat he shall remove, as the fat of the sheep is removed from the peace-offering"),
        ("וְהִקְטִיר הַכֹּהֵן אֹתָם הַמִּזְבֵּחָה עַל אִשֵּׁי יְהוָה",
         "ויקתרהא אלאמאם עלי' אלמד'בח. עלי' קראבין אללה",
         "and the imām shall burn them in smoke upon the altar, above the offerings to God"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן עַל-חַטָּאתוֹ אֲשֶׁר-חָטָא וְנִסְלַח לוֹ",
         "ויסתג'פר ענה אלאמאם. ען כ'טייתה אלד'י אכ'טא פיג'פר לה",
         "and the imām shall seek forgiveness for him from his transgression which he transgressed — and he shall be forgiven."),
    ],
}
