"""Hand-authored alignment triples for Vayikra chapter 19."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-כָּל-עֲדַת בְּנֵי-יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר גמאעה' בני אסראיל. וקל להם",
         "Command the assembly of the sons of Israel, and say to them:"),
        ("קְדֹשִׁים תִּהְיוּ כִּי קָדוֹשׁ אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "כונו מקדסין. לאני אללה רבכם אלקדוס",
         "Be consecrated, for I am God your Lord, the Holy One."),
    ],
    3: [
        ("אִישׁ אִמּוֹ וְאָבִיו תִּירָאוּ",
         "ליכאף כל אנסאן אמה ואביה",
         "Let every person fear his mother and his father;"),
        ("וְאֶת-שַׁבְּתֹתַי תִּשְׁמֹרוּ",
         "ואחפצו סבותי",
         "and keep My Sabbaths."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אגאזיכם כ'ירא",
         "I am God your Lord — I shall recompense you with good."),
    ],
    4: [
        ("אַל-תִּפְנוּ אֶל-הָאֱלִילִם",
         "לא תולו אלי' אלאות'אן",
         "Do not turn toward the idols;"),
        ("וֵאלֹהֵי מַסֵּכָה לֹא תַעֲשׂוּ לָכֶם",
         "ומעבודאת מסבוכה. לא תצנעו לכם",
         "and molten objects of worship — do not make for yourselves."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אלואחד",
         "I am God your Lord, the One."),
    ],
    5: [
        ("וְכִי תִזְבְּחוּ זֶבַח שְׁלָמִים לַיהוָה",
         "ואדא ד'בחתם ד'בח סלאמה ללה",
         "And when you slaughter a sacrifice of well-being to God,"),
        ("לִרְצֹנְכֶם תִּזְבָּחֻהוּ",
         "פעלי' מא ירתצ'א מנכם אד'בחוה",
         "slaughter it in the manner that is acceptable from you."),
    ],
    6: [
        ("בְּיוֹם זִבְחֲכֶם יֵאָכֵל וּמִמָּחֳרָת",
         "אן יכון יוכל פי יום ד'בחכם ומן ג'ד",
         "It is to be eaten on the day of your slaughter and on the morrow;"),
        ("וְהַנּוֹתָר עַד-יוֹם הַשְּׁלִישִׁי בָּאֵשׁ יִשָּׂרֵף",
         "ומא בקי אלי' אליום אלת'אלת'. פליחרק באלנאר",
         "and whatever remains until the third day shall be burned in the fire."),
    ],
    7: [
        ("וְאִם הֵאָכֹל יֵאָכֵל בַּיּוֹם הַשְּׁלִישִׁי",
         "ואן אכל מנה שי פי אליום אלת'אלת'",
         "And if anything of it is eaten on the third day,"),
        ("פִּגּוּל הוּא לֹא יֵרָצֶה",
         "פהו כאלאכ'ס לא יקבל",
         "it is like the repulsive thing — it shall not be accepted."),
    ],
    8: [
        ("וְאֹכְלָיו עֲו‍ֹנוֹ יִשָּׂא כִּי-אֶת-קֹדֶשׁ יְהוָה חִלֵּל",
         "ואכלה פקד חמל וזרה. למא בד'ל קדס אללה",
         "And he who eats it has borne his burden of guilt, for he has debased what is consecrated to God;"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעַמֶּיהָ",
         "וינקטע ד'אלך אלאנסאן מן בין קומה",
         "and that person shall be cut off from among his people."),
    ],
    9: [
        ("וּבְקֻצְרְכֶם אֶת-קְצִיר אַרְצְכֶם לֹא תְכַלֶּה פְּאַת שָׂדְךָ לִקְצֹר",
         "ואדא חצדתם זרע בלאדכם. פלא תסתקץ טרה' צ'יעתך פתחצדהא",
         "And when you harvest the grain of your lands, do not exhaust the edge of your field by harvesting it,"),
        ("וְלֶקֶט קְצִירְךָ לֹא תְלַקֵּט",
         "ולקיט זרעך פלא תלקטה",
         "and the gleanings of your grain — do not gather them."),
    ],
    10: [
        ("וְכַרְמְךָ לֹא תְעוֹלֵל וּפֶרֶט כַּרְמְךָ לֹא תְלַקֵּט",
         "וכרמך פלא תמושה. ומפרוט כרמך פלא תלקטה",
         "And your vineyard — do not strip it; and the fallen grapes of your vineyard — do not gather them;"),
        ("לֶעָנִי וְלַגֵּר תַּעֲזֹב אֹתָם",
         "בל אתרכהא לאלצ'עיף ואלג'ריב",
         "but leave them for the weak and the stranger."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אגאזיכם כ'ירא",
         "I am God your Lord — I shall recompense you with good."),
    ],
    11: [
        ("לֹא תִּגְנֹבוּ",
         "לא תסרקו",
         "Do not steal;"),
        ("וְלֹא-תְכַחֲשׁוּ וְלֹא-תְשַׁקְּרוּ אִישׁ בַּעֲמִיתוֹ",
         "ולא יגחד ולא ינכת' כל אמר בצאחבה",
         "and let no man deny nor break faith with his fellow."),
    ],
    12: [
        ("וְלֹא-תִשָּׁבְעוּ בִשְׁמִי לַשָּׁקֶר",
         "ולא תחלפו באסמי באטלא",
         "And do not swear by My name falsely —"),
        ("וְחִלַּלְתָּ אֶת-שֵׁם אֱלֹהֶיךָ",
         "פאנך אד'א בד'לת אסם רבך",
         "for you would then have debased the name of your Lord."),
        ("אֲנִי יְהוָה",
         "אנא אללה אלמעאקב",
         "I am God, the Punisher."),
    ],
    13: [
        ("לֹא-תַעֲשֹׁק אֶת-רֵעֲךָ וְלֹא תִגְזֹל",
         "לא תג'שם צאחבך ולא תג'צ'בה",
         "Do not defraud your fellow nor rob him;"),
        ("לֹא-תָלִין פְּעֻלַּת שָׂכִיר אִתְּךָ--עַד-בֹּקֶר",
         "ולא תבית אגרה' אלאגיר. ענדך אלי' אלג'דאה",
         "and do not let the wages of a hired hand stay overnight with you until the morning."),
    ],
    14: [
        ("לֹא-תְקַלֵּל חֵרֵשׁ--וְלִפְנֵי עִוֵּר לֹא תִתֵּן מִכְשֹׁל",
         "לא תשתם אצמא. ובין ידי אעמא. לא תצייר מעת'רא",
         "Do not revile the deaf; and before a blind person do not place a stumbling block;"),
        ("וְיָרֵאתָ מֵּאֱלֹהֶיךָ אֲנִי יְהוָה",
         "וכ'ף רבך אנא אללה אלמעאקב",
         "and fear your Lord. I am God, the Punisher."),
    ],
    15: [
        ("לֹא-תַעֲשׂוּ עָוֶל בַּמִּשְׁפָּט--לֹא-תִשָּׂא פְנֵי-דָל וְלֹא תֶהְדַּר פְּנֵי גָדוֹל",
         "לא תצנעו גורא פי אלחכם. ולא תחאבון פקירא. ולא תבתהגון גלילא",
         "Do not commit injustice in judgment; do not favor the poor, and do not defer to the great —"),
        ("בְּצֶדֶק תִּשְׁפֹּט עֲמִיתֶךָ",
         "בל אחכם פי מא בין קומך באלעדל",
         "but judge among your people with equity."),
    ],
    16: [
        ("לֹא-תֵלֵךְ רָכִיל בְּעַמֶּיךָ",
         "לא תמץ מאהלא בקומך",
         "Do not go about in leisurely prying among your people;"),
        ("לֹא תַעֲמֹד עַל-דַּם רֵעֶךָ",
         "ולא תקום עלי' דם צאחבך",
         "and do not stand against the blood of your fellow."),
        ("אֲנִי יְהוָה",
         "אנא אללה אלמעאקב",
         "I am God, the Punisher."),
    ],
    17: [
        ("לֹא-תִשְׂנָא אֶת-אָחִיךָ בִּלְבָבֶךָ",
         "לא תשן אכ'יך פי קלבך",
         "Do not hate your brother in your heart;"),
        ("הוֹכֵחַ תּוֹכִיחַ אֶת-עֲמִיתֶךָ",
         "בל עצ'ה[ועט'א[ ועצ'א",
         "but admonish him with admonition —"),
        ("וְלֹא-תִשָּׂא עָלָיו חֵטְא",
         "ולא תחמל ענה וזרא",
         "and do not bear on his account a burden of guilt."),
    ],
    18: [
        ("לֹא-תִקֹּם וְלֹא-תִטֹּר אֶת-בְּנֵי עַמֶּךָ",
         "לא תנקם ולא תחקד עלי' קומך",
         "Do not take revenge and do not bear a grudge against your people;"),
        ("וְאָהַבְתָּ לְרֵעֲךָ כָּמוֹךָ",
         "ואחבב לצאחבך מת'ל נפסך",
         "and love for your fellow what you love for yourself."),
        ("אֲנִי יְהוָה",
         "אנא אללה אגאזיך כ'ירא",
         "I am God — I shall recompense you with good."),
    ],
    19: [
        ("אֶת-חֻקֹּתַי תִּשְׁמֹרוּ",
         "רסומי [פאחפט'והא[ פאחפצ'והא",
         "My statutes — keep them."),
        ("בְּהֶמְתְּךָ לֹא-תַרְבִּיעַ כִּלְאַיִם שָׂדְךָ לֹא-תִזְרַע כִּלְאָיִם",
         "בהאימך לא תנזוהא מן נועין. וצ'יאעך לא תזרעהא מן נועין",
         "Your beasts — do not mate them from two kinds; and your fields — do not sow them from two kinds;"),
        ("וּבֶגֶד כִּלְאַיִם שַׁעַטְנֵז לֹא יַעֲלֶה עָלֶיךָ",
         "ות'וב מן נועין מלחמין. לא יעלו עליך",
         "and a garment of two kinds intertwined — let it not come upon you."),
    ],
    20: [
        ("וְאִישׁ כִּי-יִשְׁכַּב אֶת-אִשָּׁה שִׁכְבַת-זֶרַע וְהִוא שִׁפְחָה נֶחֱרֶפֶת לְאִישׁ",
         "ואי רגל צ'אגע אמראה מצ'אגעה' אנסאל. והי אמה מכ'טובה לאי רגל כאן",
         "And any man who lies with a woman in the manner of procreation, and she is a maidservant betrothed to any man,"),
        ("וְהָפְדֵּה לֹא נִפְדָּתָה אוֹ חֻפְשָׁה לֹא נִתַּן-לָהּ",
         "ופדא לם תפדא. ועתקהא לם ידפע אליהא",
         "and a ransom has not been paid for her and her freedom has not been given to her —"),
        ("בִּקֹּרֶת תִּהְיֶה לֹא יוּמְתוּ כִּי-לֹא חֻפָּשָׁה",
         "פלתכון מחדודה. ולא יקתלא אד' לם תעתק",
         "then she shall be subject to punishment, and they shall not be put to death, since she has not been freed."),
    ],
    21: [
        ("וְהֵבִיא אֶת-אֲשָׁמוֹ לַיהוָה אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "פליאת בקרבאנה ללה. אלי' באב כ'בא אלמחצ'ר",
         "And he shall bring his offering to God, to the entrance of the tent of the assembly —"),
        ("אֵיל אָשָׁם",
         "כבשא לקרבאן אלאת'ם",
         "a ram as a guilt offering."),
    ],
    22: [
        ("וְכִפֶּר עָלָיו הַכֹּהֵן בְּאֵיל הָאָשָׁם לִפְנֵי יְהוָה עַל-חַטָּאתוֹ אֲשֶׁר חָטָא",
         "פיסתג'פר ענה אלאמאם בין ידי אללה. ען כ'טייתה אלד'י אכ'טא",
         "And the imām shall seek forgiveness for him before God for his sin which he has sinned;"),
        ("וְנִסְלַח לוֹ מֵחַטָּאתוֹ אֲשֶׁר חָטָא",
         "פיג'פר לה ד'אלך",
         "and it shall be forgiven him."),
    ],
    23: [
        ("וְכִי-תָבֹאוּ אֶל-הָאָרֶץ וּנְטַעְתֶּם כָּל-עֵץ מַאֲכָל",
         "ומד' תדכ'לון אלי' אלבלד. פתג'רסון כל שגר מטעם",
         "And from the time you enter the land and plant any food-bearing tree,"),
        ("וַעֲרַלְתֶּם עָרְלָתוֹ אֶת-פִּרְיוֹ שָׁלֹשׁ שָׁנִים יִהְיֶה לָכֶם עֲרֵלִים--לֹא יֵאָכֵל",
         "פתחרמו ת'מרה תחרימא. ת'לאת' סנין. יכון עליכם מחרמא לא יוכל",
         "you shall declare its fruit forbidden with a full prohibition — three years it shall be forbidden to you, not to be eaten."),
    ],
    24: [
        ("וּבַשָּׁנָה הָרְבִיעִת יִהְיֶה כָּל-פִּרְיוֹ",
         "ופי אלסנה אלראבעה. יכון גמיע ת'מרה",
         "And in the fourth year, all its fruit"),
        ("קֹדֶשׁ הִלּוּלִים לַיהוָה",
         "מקדסא מוהלא ללה",
         "shall be consecrated, dedicated to God."),
    ],
    25: [
        ("וּבַשָּׁנָה הַחֲמִישִׁת תֹּאכְלוּ אֶת-פִּרְיוֹ",
         "ופי אלסנה אלכ'אמסה. תאכלו ת'מרה",
         "And in the fifth year you may eat its fruit —"),
        ("לְהוֹסִיף לָכֶם תְּבוּאָתוֹ אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "פאני אללה רבכם אזיד לכם פי ג'לתה",
         "for I am God your Lord, I shall increase for you its yield."),
    ],
    26: [
        ("לֹא תֹאכְלוּ עַל-הַדָּם",
         "לא תאכלו עלי' אלדם",
         "Do not eat over the blood;"),
        ("לֹא תְנַחֲשׁוּ וְלֹא תְעוֹנֵנוּ",
         "לא תתטיירו ולא תתפאולו",
         "do not take omens and do not seek auguries."),
    ],
    27: [
        ("לֹא תַקִּפוּ פְּאַת רֹאשְׁכֶם",
         "ולא תחדקו בזואיא רוסכם",
         "And do not shave the corners of your heads,"),
        ("וְלֹא תַשְׁחִית אֵת פְּאַת זְקָנֶךָ",
         "ולא תסתאצל זואיא לחיתך",
         "and do not uproot the corners of your beard."),
    ],
    28: [
        ("וְשֶׂרֶט לָנֶפֶשׁ לֹא תִתְּנוּ בִּבְשַׂרְכֶם",
         "וכ'דשא עלי' מיית. לא תגעלו פי אבדאנכם",
         "And a scratch for the dead — do not place on your bodies;"),
        ("וּכְתֹבֶת קַעֲקַע לֹא תִתְּנוּ בָּכֶם",
         "וכתאבה' ושם. לא תגעלו פיכם",
         "and tattooed writing — do not place on yourselves."),
        ("אֲנִי יְהוָה",
         "אנא אללה אלמעאקב",
         "I am God, the Punisher."),
    ],
    29: [
        ("אַל-תְּחַלֵּל אֶת-בִּתְּךָ לְהַזְנוֹתָהּ",
         "ולא תבד'ל אבנתך לאלפגור",
         "And do not give over your daughter to debauchery,"),
        ("וְלֹא-תִזְנֶה הָאָרֶץ וּמָלְאָה הָאָרֶץ זִמָּה",
         "כלא יפגר אהל אלארץ'. פתמתלי פואחשא",
         "lest the people of the land fall into debauchery and it fill with lewdness."),
    ],
    30: [
        ("אֶת-שַׁבְּתֹתַי תִּשְׁמֹרוּ",
         "סבותי [פאחפט'והא[ פאחפצ'והא",
         "My Sabbaths — keep them;"),
        ("וּמִקְדָּשִׁי תִּירָאוּ",
         "ומקדסי פהאבוה",
         "and My sanctuary — hold it in awe."),
        ("אֲנִי יְהוָה",
         "אנא אללה שרפתהמא",
         "I am God who has honoured them."),
    ],
    31: [
        ("אַל-תִּפְנוּ אֶל-הָאֹבֹת וְאֶל-הַיִּדְּעֹנִים",
         "ולא תולו אלי' אלמשעוד'ין ואלעראפין",
         "Do not turn toward the conjurers and the diviners;"),
        ("אַל-תְּבַקְשׁוּ לְטָמְאָה בָהֶם",
         "ולא תטלבו אן תעצוני בהא",
         "and do not seek to disobey Me by means of them."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם עאלם אלג'יב",
         "I am God your Lord, the Knower of what is hidden."),
    ],
    32: [
        ("מִפְּנֵי שֵׂיבָה תָּקוּם וְהָדַרְתָּ פְּנֵי זָקֵן",
         "מן בין ידי ד'ו אלשיבה פקם ואבתהג וגה אלשיך'",
         "Before one possessed of grey hair — rise; and show gladness toward the face of the elder;"),
        ("וְיָרֵאתָ מֵּאֱלֹהֶיךָ אֲנִי יְהוָה",
         "וכף רבך אנא אללה",
         "and fear your Lord. I am God."),
    ],
    33: [
        ("וְכִי-יָגוּר אִתְּךָ גֵּר בְּאַרְצְכֶם",
         "ואדא סכן מעכם ג'ריב פי בלדכם",
         "And when a stranger settles among you in your land,"),
        ("לֹא תוֹנוּ אֹתוֹ",
         "פלא תצ'הדוה",
         "do not oppress him."),
    ],
    34: [
        ("כְּאֶזְרָח מִכֶּם יִהְיֶה לָכֶם הַגֵּר הַגָּר אִתְּכֶם וְאָהַבְתָּ לוֹ כָּמוֹךָ",
         "וליכון מעכם כצריח מנכם. אלג'ריב אלדכ'יל פי מא בינכם. ואחבב לה כנפסך",
         "The stranger who has come to dwell among you shall be to you as a native among you; and love for him as for yourself —"),
        ("כִּי-גֵרִים הֱיִיתֶם בְּאֶרֶץ מִצְרָיִם",
         "לאנה טאל מא כנתם ג'רבא פי בלד מצר",
         "for you were long strangers in the land of Egypt."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אגמעין",
         "I am God your Lord of all of you."),
    ],
    35: [
        ("לֹא-תַעֲשׂוּ עָוֶל בַּמִּשְׁפָּט בַּמִּדָּה בַּמִּשְׁקָל וּבַמְּשׂוּרָה",
         "לא תצנעו ג'שא פי אלחכם. ולא פי אלמסאחה ואלוזן ואלמכיאל",
         "Do not commit fraud in judgment, nor in measurement, nor in weight, nor in measure."),
    ],
    36: [
        ("מֹאזְנֵי צֶדֶק אַבְנֵי-צֶדֶק אֵיפַת צֶדֶק וְהִין צֶדֶק--יִהְיֶה לָכֶם",
         "בל מיאזין עאדלה וצנגאת עאדלה. ואכיאל עאדלה. ואקסאט עאדלה תכון לכם",
         "But just scales and just weights and just dry measures and just liquid measures shall be yours."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם אֲשֶׁר-הוֹצֵאתִי אֶתְכֶם מֵאֶרֶץ מִצְרָיִם",
         "אנא אללה רבכם אלעדל. אלמכ'רגכם מן בלד מצר",
         "I am God your Lord, the Just — who brought you out from the land of Egypt."),
    ],
    37: [
        ("וּשְׁמַרְתֶּם אֶת-כָּל-חֻקֹּתַי וְאֶת-כָּל-מִשְׁפָּטַי וַעֲשִׂיתֶם אֹתָם",
         "ואחפצו גמיע רסומי ואחכאמי. ואעמלו בהא",
         "And keep all My statutes and all My ordinances, and act according to them."),
        ("אֲנִי יְהוָה",
         "אנא אללה אגאזיכם כ'ירא",
         "I am God — I shall recompense you with good."),
    ],
}
