"""Hand-authored alignment triples for Vayikra chapter 22.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה", "and his sons"),
        ("וְיִנָּזְרוּ", "באן יגאנבו", "that they keep away from"),
        ("מִקָּדְשֵׁי", "אקדאס", "the holy things of"),
        ("בְנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("וְלֹא יְחַלְּלוּ", "ולא יבד'לו", "and not treat lightly"),
        ("אֶת-שֵׁם קָדְשִׁי", "מא סמיתה קדסא", "what I have called by the name of holy"),
        ("אֲשֶׁר", "ממא", "of what"),
        ("הֵם מַקְדִּשִׁים", "הם מקדסוה", "they are consecrating"),
        ("לִי", "לי", "to Me"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "שרפתה", "who has honored it"),
    ],
    3: [
        ("אֱמֹר", "קל", "Say"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("כָּל-אִישׁ", "אי רגל", "any man"),
        ("מִכָּל-זַרְעֲכֶם", "מן נסלכם", "from your lineage"),
        (None, "עלי'", "throughout"),
        ("לְדֹרֹתֵיכֶם", "מר אגיאלכם", "the passing of your generations"),
        ("אֲשֶׁר-יִקְרַב", "תקדם", "who approaches"),
        ("אֶל-הַקֳּדָשִׁים", "אלי' אלאקדאס", "the holy things"),
        ("אֲשֶׁר יַקְדִּישׁוּ", "אלדי יקדסוהא", "which"),
        ("בְנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("לַיהוָה", "ללה", "consecrate to God"),
        ("וְטֻמְאָתוֹ עָלָיו", "והו פי חד נגס ילזמה", "while he is in a state of impurity that clings to him"),
        ("וְנִכְרְתָה", "פתכ'תרם", "shall be cut off"),
        ("הַנֶּפֶשׁ הַהִוא", "תלך אלנפס", "that soul"),
        ("מִלְּפָנַי", "מן עאלמי", "from My world"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    4: [
        ("אִישׁ אִישׁ", "אי רג'ל", "Any man"),
        ("מִזֶּרַע אַהֲרֹן", "מן נסל הרון", "of the lineage of Aaron"),
        ("וְהוּא צָרוּעַ", "פי מא הו אברץ", "who is afflicted with a skin-disease"),
        ("אוֹ זָב", "או ד'איב", "or has a discharge"),
        ("בַּקֳּדָשִׁים לֹא יֹאכַל", "פלא יאכ'ל מן אלאקדאס", "shall not eat of the holy things"),
        ("עַד אֲשֶׁר יִטְהָר", "אלי' אן יטהר", "until he is purified"),
        ("וְהַנֹּגֵעַ", "ומן מס", "and whoever touches"),
        ("בְּכָל-טְמֵא-נֶפֶשׁ", "נגיס במיית", "one who is impure through contact with a dead person"),
        ("אוֹ אִישׁ", "או", "or"),
        ("אֲשֶׁר-תֵּצֵא מִמֶּנּוּ שִׁכְבַת-זָרַע", "כ'רגת מנה נטפה' אנסאל", "from whom a drop of seminal emission has issued"),
    ],
    5: [
        ("אוֹ-אִישׁ", "ואי רג'ל", "and any man"),
        ("אֲשֶׁר יִגַּע", "דנא", "who has approached"),
        ("בְּכָל-שֶׁרֶץ", "בכל דביב", "any creeping thing"),
        ("אֲשֶׁר יִטְמָא-לוֹ", "סבילה אן ינגס מנה", "by which he may become impure"),
        ("אוֹ", "או", "or"),
        ("בְאָדָם", "באנסאן", "a person"),
        (None, "סבילה אן ינגס מנה", "by whom he may become impure"),
        ("לְכֹל טֻמְאָתוֹ", "עלי' צ'רוב נגאסתה", "according to the ways of his impurity"),
    ],
    6: [
        ("נֶפֶשׁ אֲשֶׁר תִּגַּע-בּוֹ", "פאי אנסאן דנא בשי מן ד'אלך", "any person who has approached any such thing"),
        ("וְטָמְאָה", "פלינגס", "shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלליל", "until the night"),
        ("וְלֹא יֹאכַל", "ולא יאכל", "and shall not eat"),
        ("מִן-הַקֳּדָשִׁים", "מן אלאקדאס", "of the holy things"),
        ("כִּי אִם-רָחַץ", "אלא אן ג'סל", "unless he has washed"),
        ("בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַּמָּיִם", "באלמא", "with water"),
    ],
    7: [
        ("וּבָא הַשֶּׁמֶשׁ", "פאד'א ג'אבת אלשמס", "And when the sun has set"),
        ("וְטָהֵר", "פקד טהר", "he is then purified"),
        ("וְאַחַר", "ובעד ד'אלך", "and after that"),
        ("יֹאכַל", "יאכל", "he may eat"),
        ("מִן-הַקֳּדָשִׁים", "מן אלאקדאס", "of the holy things"),
        ("כִּי לַחְמוֹ הוּא", "לאנה טעאמה", "for it is his food"),
    ],
    8: [
        ("נְבֵלָה", "ואלנבילה", "The carcass"),
        ("וּטְרֵפָה", "ואלסקימה", "and the diseased animal"),
        ("לֹא יֹאכַל", "לא יאכלהא", "he shall not eat"),
        ("לְטָמְאָה-בָהּ", "פיעציני בהא", "lest he disobey Me through it"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    9: [
        ("וְשָׁמְרוּ", "פליחפצו", "They shall guard"),
        ("אֶת-מִשְׁמַרְתִּי", "מא אסתחפצ'תהם", "what I have entrusted to their guardianship"),
        ("וְלֹא-יִשְׂאוּ עָלָיו חֵטְא", "ולא יחמלו ענה וזרא", "and shall not bear sin because of it"),
        ("וּמֵתוּ בוֹ", "פיהלכון", "lest they be destroyed"),
        ("כִּי יְחַלְּלֻהוּ", "אד' הם תבד'לוה", "when they have treated it lightly"),
        ("אֲנִי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("מְקַדְּשָׁם", "מקדסהם בד'אלך", "who sanctifies them thereby"),
    ],
    10: [
        ("וְכָל-זָר", "וכל אגנבי", "And no outsider"),
        ("לֹא-יֹאכַל", "לא יאכל", "shall eat"),
        ("קֹדֶשׁ", "קדסא", "of a holy thing"),
        ("תּוֹשַׁב כֹּהֵן", "חתא צ'יף אלאמאם", "not even the guest of the priest"),
        ("וְשָׂכִיר", "ואגירה", "nor his hired worker"),
        ("לֹא-יֹאכַל", "לא יאכ'ל", "shall eat"),
        ("קֹדֶשׁ", "קדסא", "of a holy thing"),
    ],
    11: [
        ("וְכֹהֵן", "ואי אמאם", "But any priest"),
        ("כִּי-יִקְנֶה נֶפֶשׁ", "אשתרא אנסאן", "who has purchased a person"),
        ("קִנְיַן כַּסְפּוֹ", "שראא במאלה", "by purchase with his money"),
        ("הוּא יֹאכַל בּוֹ", "פהו יאכל מנה", "he may eat of it"),
        ("וִילִיד בֵּיתוֹ", "וכד'אלך תיאליד ביתה", "and likewise those born into his household"),
        ("הֵם יֹאכְלוּ", "הם יאכלון", "they may eat"),
        ("בְלַחְמוֹ", "מן טעאמה", "of his food"),
    ],
    12: [
        ("וּבַת-כֹּהֵן", "ואייה' אבנה' אמאם", "And any daughter of a priest"),
        ("כִּי תִהְיֶה לְאִישׁ זָר", "תזווגת רגלא אגנבייא", "who has married an outsider man"),
        ("הִוא", "פהי", "she"),
        ("בִּתְרוּמַת הַקֳּדָשִׁים", "מן רפאיע אלאקדאס", "of the elevated portions of the holy things"),
        ("לֹא תֹאכֵל", "לא תאכל", "shall not eat"),
    ],
    13: [
        ("וּבַת-כֹּהֵן", "ואייה' אבנה' אמאם", "But any daughter of a priest"),
        ("כִּי תִהְיֶה אַלְמָנָה", "צארת ארמלה", "who has become a widow"),
        ("וּגְרוּשָׁה", "או מטלקה", "or been divorced"),
        ("וְזֶרַע אֵין לָהּ", "ולא נסל להא", "and has no offspring"),
        ("וְשָׁבָה", "פלתעוד", "let her return"),
        ("אֶל-בֵּית אָבִיהָ", "אלי' בית אביהא", "to her father's house"),
        ("כִּנְעוּרֶיהָ", "כחכם צבאיהא", "as in the rule of her girlhood"),
        ("מִלֶּחֶם אָבִיהָ", "ומן טעאמה", "and of his food"),
        ("תֹּאכֵל", "תאכל", "she may eat"),
        ("וְכָל-זָר", "וסאיר אלאגנביין", "and the rest of the outsiders"),
        ("לֹא-יֹאכַל בּוֹ", "לא יאכלו מנה", "shall not eat of it"),
    ],
    14: [
        ("וְאִישׁ", "ואי אנסאן", "And any person"),
        ("כִּי-יֹאכַל קֹדֶשׁ", "אכל שייא מן אלאקדאס", "who has eaten of the holy things"),
        ("בִּשְׁגָגָה", "סהוא", "inadvertently"),
        ("וְיָסַף חֲמִשִׁיתוֹ", "פליזיד עליה מת'ל כמסה", "shall add to it the like of its fifth"),
        ("וְנָתַן", "וידפעה", "and shall pay it"),
        ("לַכֹּהֵן", "אלי' אלאמאם", "to the priest"),
        ("אֶת-הַקֹּדֶשׁ", "ען אלקדס", "for the holy thing"),
    ],
    15: [
        ("וְלֹא יְחַלְּלוּ", "ולא יבד'לו", "And they shall not treat lightly"),
        ("אֶת-קָדְשֵׁי בְּנֵי יִשְׂרָאֵל", "אקדאס בני אסראיל", "the holy things of the sons of Israel"),
        ("אֵת אֲשֶׁר-יָרִימוּ לַיהוָה", "ומא ירפעונה ללה", "and what they present to God"),
    ],
    16: [
        ("וְהִשִּׂיאוּ אוֹתָם", "פיחמלו ענהא", "For they would bear"),
        ("עֲו‍ֹן", "ד'נובא", "sins"),
        ("אַשְׁמָה", "ואת'אמא", "and guilt"),
        ("בְּאָכְלָם", "אד'א אכלו", "when they ate"),
        (None, "כד'אך", "thus"),
        ("אֶת-קָדְשֵׁיהֶם", "אקדאסהם", "of their holy things"),
        ("כִּי אֲנִי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("מְקַדְּשָׁם", "מקדסהם", "who sanctifies them"),
    ],
    17: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    18: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה", "and his sons"),
        ("וְאֶל כָּל-בְּנֵי יִשְׂרָאֵל", "וסאיר אל אסראיל", "and the rest of the house of Israel"),
        ("וְאָמַרְתָּ אֲלֵהֶם", "וקל להם", "and say to them"),
        ("אִישׁ אִישׁ", "אי רג'ל", "any man"),
        ("מִבֵּית יִשְׂרָאֵל", "מן אל אסראיל", "of the house of Israel"),
        ("וּמִן-הַגֵּר", "או מן אלג'רבא", "or of the strangers"),
        ("בְּיִשְׂרָאֵל", "אלדאכ'לין פיהם", "who have entered among them"),
        ("אֲשֶׁר יַקְרִיב", "שא אן יקרב", "who wills to bring"),
        ("קָרְבָּנוֹ", "קרבאנא", "an offering"),
        ("לְכָל-נִדְרֵיהֶם", "עלי' צ'רוב מן נדורהם", "according to any manner of their vows"),
        ("וּלְכָל-נִדְבוֹתָם", "ותברעהם", "and their freewill gifts"),
        ("אֲשֶׁר-יַקְרִיבוּ", "אלתי יקרבונהא", "which they bring"),
        ("לַיהוָה", "ללה", "to God"),
        ("לְעֹלָה", "צעידה", "as a burnt offering"),
    ],
    19: [
        ("לִרְצֹנְכֶם", "פלמרתצ'א מנכם", "that which is acceptable from you"),
        (None, "אן יכון", "shall be"),
        ("זָכָר", "ד'כרא", "male"),
        ("תָּמִים", "צחיחא", "a sound"),
        ("בַּבָּקָר", "מן אלבקר", "from the cattle"),
        ("בַּכְּשָׂבִים", "ואלצאן", "the sheep"),
        ("וּבָעִזִּים", "ואלמאעז", "or the goats"),
    ],
    20: [
        ("כֹּל אֲשֶׁר-בּוֹ מוּם", "וכל מא פיה עיב", "But anything that has a blemish"),
        ("לֹא תַקְרִיבוּ", "לא תקרבוה", "you shall not offer"),
        ("כִּי-לֹא לְרָצוֹן יִהְיֶה לָכֶם", "פאנה לא ירתצ'א מנכם", "for it shall not be acceptable from you"),
    ],
    21: [
        (None, "וכד'אלך", "And likewise"),
        ("וְאִישׁ", "אי אנסאן", "any person"),
        ("כִּי-יַקְרִיב", "שא אן יקרב", "who wills to bring"),
        ("זֶבַח-שְׁלָמִים", "ד'בח סלאמה", "a peace-offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("לְפַלֵּא-נֶדֶר", "תסויג' נד'רא", "in fulfillment of a vow"),
        ("אוֹ לִנְדָבָה", "או תברעא", "or as a freewill gift"),
        ("בַּבָּקָר", "מן אלבקר", "from the cattle"),
        ("אוֹ בַצֹּאן", "או מן אלג'נם", "or from the flock"),
        ("תָּמִים", "פאלצחיח", "the sound one"),
        ("יִהְיֶה לְרָצוֹן", "הו אלמרתצ'א מנה", "is what is acceptable from it"),
        ("כָּל-מוּם", "שי מן אלעיוב", "blemish of any kind"),
        ("לֹא יִהְיֶה-בּוֹ", "לא יכון פיה", "there shall be no"),
    ],
    22: [
        ("עַוֶּרֶת", "מן עורא", "Whether blind"),
        ("אוֹ שָׁבוּר", "או מכסורה", "or broken"),
        ("אוֹ-חָרוּץ", "או מבתורה", "or severed"),
        ("אוֹ-יַבֶּלֶת", "או ד'את ת'אלול", "or having a wart"),
        ("אוֹ גָרָב", "או בה גרב", "or with mange"),
        ("אוֹ יַלֶּפֶת", "או חזאז", "or scurf"),
        ("לֹא-תַקְרִיבוּ", "פלא תקרבוהא", "you shall not offer these"),
        ("אֵלֶּה לַיהוָה", "ללה", "to God"),
        ("וְאִשֶּׁה לֹא-תִתְּנוּ", "ולא תגעלו מנהא", "and you shall not make from them"),
        ("מֵהֶם", "קרבאנא", "an offering"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' מד'בח", "upon the altar"),
        (None, "אללה", "of God"),
    ],
    23: [
        ("וְשׁוֹר", "ואי ת'ור", "And any ox"),
        ("וָשֶׂה", "או שאה", "or sheep"),
        ("שָׂרוּעַ", "כאנת גאמזה", "that is lame"),
        ("וְקָלוּט", "או מדמג'ה", "or stunted"),
        ("נְדָבָה תַּעֲשֶׂה אֹתוֹ", "פאצנעה עלי' גהה' אלתברע", "you may make it for a freewill gift"),
        ("וּלְנֵדֶר", "ואמא עלי' גהה' אלנד'ר", "but as regards a vow"),
        ("לֹא יֵרָצֶה", "פלא ירתצ'א", "it shall not be acceptable"),
    ],
    24: [
        ("וּמָעוּךְ", "ואלממרוס", "The bruised"),
        ("וְכָתוּת", "ואלמדקוק", "or the crushed"),
        ("וְנָתוּק", "ואלמנצול", "or the torn-out"),
        ("וְכָרוּת", "ואלמקטוע", "or the severed"),
        ("לֹא תַקְרִיבוּ", "פלא תקרבוהא", "you shall not offer these"),
        ("לַיהוָה", "ללה", "to God"),
        ("וּבְאַרְצְכֶם", "ופי בלדאנכם", "and in your lands"),
        ("לֹא תַעֲשׂוּ", "לא תצנעוהא", "you shall not do this"),
    ],
    25: [
        ("וּמִיַּד בֶּן-נֵכָר", "ומן יד אלאמם", "And from the hand of the nations"),
        ("לֹא תַקְרִיבוּ", "לא תקרבו", "you shall not offer"),
        ("אֶת-לֶחֶם אֱלֹהֵיכֶם", "קרבאן רבכם אלדאים", "the perpetual offering of your Lord"),
        (None, "ופיה שייא מן הד'א אלעיוב", "when there is any of these blemishes in it"),
        ("כִּי מָשְׁחָתָם בָּהֶם", "לאן פסאדהא מעהא", "for their corruption is with them"),
        ("מוּם בָּם", "והו אלעיב אלד'י פיהא", "that is the blemish which is in them"),
        ("לֹא יֵרָצוּ לָכֶם", "פלא תרתצ'א מנכם", "they shall not be acceptable from you"),
    ],
    26: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    27: [
        ("שׁוֹר", "ואי עגל", "Any calf"),
        ("אוֹ-כֶשֶׂב", "או חמל", "or lamb"),
        ("אוֹ-עֵז", "או גדי", "or kid"),
        ("כִּי יִוָּלֵד", "אד'א יולד", "when it is born"),
        ("וְהָיָה שִׁבְעַת יָמִים", "פליקם סבעה' אייאם", "let it remain seven days"),
        ("תַּחַת אִמּוֹ", "מע אמה", "with its mother"),
        ("וּמִיּוֹם הַשְּׁמִינִי", "ומן אליום אלת'אמן", "and from the eighth day"),
        ("וָהָלְאָה", "פצאעדא", "onward"),
        ("יֵרָצֶה", "ירתצ'א", "it shall be acceptable"),
        ("לְקָרְבַּן אִשֶּׁה", "אן יקרב קרבאנא", "to be brought as an offering"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    28: [
        ("וְשׁוֹר", "ואלבקרה", "And the cow"),
        ("אוֹ-שֶׂה", "ואלנעגה", "and the ewe"),
        ("אֹתוֹ", "הי", "it"),
        ("וְאֶת-בְּנוֹ", "וולדהא", "and its young"),
        ("לֹא תִשְׁחֲטוּ", "לא תד'בחוהמא", "you shall not slaughter both of them"),
        ("בְּיוֹם אֶחָד", "פי יום ואחד", "on one day"),
    ],
    29: [
        ("וְכִי-תִזְבְּחוּ", "ואד'א ד'בחתם", "And when you slaughter"),
        ("זֶבַח-תּוֹדָה", "ד'בח שכר", "a thanksgiving sacrifice"),
        ("לַיהוָה", "ללה", "to God"),
        ("לִרְצֹנְכֶם", "פעלי' מא ירתצ'א מנכם", "in the manner that is acceptable from you"),
        ("תִּזְבָּחוּ", "אד'בחוה", "slaughter it"),
    ],
    30: [
        (None, "אן", "It shall be"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אליום", "on that day"),
        ("יֵאָכֵל", "יוכל", "eaten"),
        (None, "פקט", "only"),
        ("לֹא-תוֹתִירוּ מִמֶּנּוּ", "לא יבקו מנה", "you shall leave none of it"),
        ("עַד-בֹּקֶר", "אלי' אלג'דאה", "until the morning"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אמרת בד'אלך", "who commanded this"),
    ],
    31: [
        ("וּשְׁמַרְתֶּם", "פאחפצו", "Guard"),
        ("מִצְו‍ֹתַי", "וצאיאי", "My commandments"),
        ("וַעֲשִׂיתֶם", "ואעמלו", "and act"),
        ("אֹתָם", "בהא", "according to them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אגאזיכם כ'ירא", "who rewards you with good"),
    ],
    32: [
        ("וְלֹא תְחַלְּלוּ", "ולא תבד'לו", "And do not treat lightly"),
        ("אֶת-שֵׁם קָדְשִׁי", "אסם קדסי", "My holy name"),
        ("וְנִקְדַּשְׁתִּי", "בל אתקדס", "but rather I shall be sanctified"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "פי מא בין בני אסראיל", "among the sons of Israel"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("מְקַדִּשְׁכֶם", "מקדסכם", "who sanctifies you"),
    ],
    33: [
        ("הַמּוֹצִיא אֶתְכֶם", "אלמכ'רגכם", "who brought you out"),
        ("מֵאֶרֶץ מִצְרַיִם", "מן בלד מצר", "from the land of Egypt"),
        ("לִהְיוֹת לָכֶם לֵאלֹהִים", "לאכון לכם אלאהא", "to be your God"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
}
