"""Hand-authored alignment triples for Vayikra chapter 4.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("לֵאמֹר", "קאילא", "saying"),
        (None, "אי", "any"),
        ("נֶפֶשׁ", "אנסאן", "person"),
        ("כִּי-תֶחֱטָא", "אכ'טא", "who errs"),
        ("בִשְׁגָגָה", "בסהו", "through inattention"),
        ("מִכֹּל", "מן", "regarding"),
        ("מִצְו‍ֹת", "פראיץ'", "the commandments of"),
        ("יְהוָה", "אללה", "God which"),
        ("אֲשֶׁר", "אלתי", "are not"),
        ("לֹא תֵעָשֶׂינָה", "לא תעמל", "to be done"),
        ("וְעָשָׂה", "פעמל", "and does"),
        ("מֵאַחַת", "וחדה", "one of"),
        ("מֵהֵנָּה", "מנהם", "them"),
    ],
    3: [
        ("אִם", "אן", "if"),
        ("יֶחֱטָא", "אכ'טא", "errs"),
        ("הַכֹּהֵן", "אלאמאם", "anointed"),
        ("הַמָּשִׁיחַ", "אלממסוח", "imām"),
        ("לְאַשְׁמַת", "עלי' סביל כ'טא", "in the manner of"),
        ("הָעָם", "אלנאס", "the people's error"),
        ("וְהִקְרִיב", "פליקרב", "let him bring"),
        ("עַל חַטָּאתוֹ", "עלי' כ'טייתה", "for his transgression"),
        ("אֲשֶׁר חָטָא", "אלתי אכ'טא", "which he transgressed"),
        ("פַּר", "רת'א", "a bull"),
        ("בֶּן-בָּקָר", "מן אלבקר", "from the cattle"),
        ("תָּמִים", "צחיחא", "sound"),
        ("לַיהוָה", "ללה", "to God."),
        ("לְחַטָּאת", "ד'כוה", "as an offering"),
    ],
    4: [
        ("וְהֵבִיא", "ויאתי", "And he shall bring"),
        ("אֶת-הַפָּר", "באלרת'", "the bull"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("וְסָמַךְ", "ויסנד", "and he shall lean"),
        ("אֶת-יָדוֹ", "ידה", "his hand"),
        ("עַל-רֹאשׁ הַפָּר", "עלי' ראסה", "upon its head"),
        ("וְשָׁחַט אֶת-הַפָּר לִפְנֵי יְהוָה", "ויד'בחה בין ידי אללה", "and shall slaughter it before God"),
    ],
    5: [
        ("וְלָקַח", "ויאכד'", "shall take"),
        ("הַכֹּהֵן הַמָּשִׁיחַ", "אלאמאם אלממסוח", "the anointed imām"),
        ("מִדַּם הַפָּר", "מן דמה", "of its blood"),
        ("וְהֵבִיא אֹתוֹ", "וידכלה אלי'", "and bring it into"),
        ("אֶל-אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
    ],
    6: [
        ("וְטָבַל הַכֹּהֵן", "ויג'מס אצבעה", "And he shall dip his finger"),
        ("אֶת-אֶצְבָּעוֹ", "פי אלדם", "in the blood"),
        ("וְהִזָּה", "וינצח", "and sprinkle"),
        ("מִן-הַדָּם", "מנה", "from it"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֶת-פְּנֵי פָּרֹכֶת הַקֹּדֶשׁ", "קבאלה' סגף אלקדס", "facing the veil of the sanctuary"),
    ],
    7: [
        (None, "ת'ם", "Then"),
        ("וְנָתַן הַכֹּהֵן", "יצע אלאמאם", "the imām shall put"),
        ("מִן-הַדָּם", "מן אלדם", "of the blood"),
        ("עַל-קַרְנוֹת", "עלי' ארכאן", "upon the horns of"),
        ("מִזְבַּח קְטֹרֶת הַסַּמִּים", "מד'בח בכור אלצמוג'", "the altar of the incense of resins"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֲשֶׁר בְּאֹהֶל מוֹעֵד", "אלד'י פי כ'בא אלמחצ'ר", "which is in the tent of the assembly"),
        ("וְאֵת כָּל-דַּם הַפָּר", "ובאקי אלדם", "and the remainder of the blood"),
        ("יִשְׁפֹּךְ", "יצ'בה", "he shall pour out"),
        ("אֶל-יְסוֹד", "ענד אסאס", "at the base of"),
        ("מִזְבַּח הָעֹלָה", "מד'בח אלצעידה", "the altar of the burnt-offering"),
        ("אֲשֶׁר-פֶּתַח אֹהֶל מוֹעֵד", "אלד'י ענד באב כ'בא אלמחצ'ר", "which is at the entrance of the tent of the assembly"),
    ],
    8: [
        ("וְאֶת-כָּל-חֵלֶב", "וגמיע שחם", "And all the fat of"),
        ("פַּר הַחַטָּאת", "רת' אלד'כוה", "the bull of the offering"),
        ("יָרִים", "ינזעה", "he shall remove"),
        ("מִמֶּנּוּ", "מנה", "from it"),
        ("אֶת-הַחֵלֶב הַמְכַסֶּה", "אלת'רב אלמג'טי", "the caul covering"),
        ("עַל-הַקֶּרֶב", "אלגוף", "the entrails"),
        ("וְאֵת כָּל-הַחֵלֶב", "וסאיר אלשחם", "and the rest of the fat"),
        ("אֲשֶׁר עַל-הַקֶּרֶב", "אלד'י עלי' אלגוף", "which is upon the entrails"),
    ],
    9: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("אֲשֶׁר עֲלֵיהֶן", "אלד'י עליהמא", "which is upon them"),
        ("אֲשֶׁר עַל-הַכְּסָלִים", "אלד'י עלי' אלאחשא", "which is upon the viscera"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד", "וזיאדה' אלכבד", "and the lobe of the liver"),
        ("עַל-הַכְּלָיוֹת יְסִירֶנָּה", "מע אלכלי'' ינזעהא", "together with the kidneys he shall remove them"),
    ],
    10: [
        ("כַּאֲשֶׁר יוּרַם", "כמא ירפע", "As it is raised"),
        ("מִשּׁוֹר זֶבַח הַשְּׁלָמִים", "מן ת'ור ד'בח אלסלאמה", "from the bull of the peace-offering"),
        ("וְהִקְטִירָם הַכֹּהֵן", "ויקתרה", "the imām shall burn them in smoke"),
        ("עַל מִזְבַּח הָעֹלָה", "עלי' מד'בח אלצעידה", "upon the altar of the burnt-offering"),
    ],
    11: [
        ("וְאֶת-עוֹר הַפָּר", "וגלד אלת'ור", "And the hide of the bull"),
        ("וְאֶת-כָּל-בְּשָׂרוֹ", "וגמיע לחמה", "and all its flesh"),
        ("עַל-רֹאשׁוֹ", "מע ראסה", "together with its head"),
        ("וְעַל-כְּרָעָיו", "ואכארעה", "and its legs"),
        ("וְקִרְבּוֹ", "ובטנה", "and its belly"),
        ("וּפִרְשׁוֹ", "ופרתה", "and its dung"),
    ],
    12: [
        ("וְהוֹצִיא", "ויכ'רג", "he shall carry"),
        ("אֶת-כָּל-הַפָּר", "גמיע ד'אלך", "all of it"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "outside the camp"),
        ("אֶל-מָקוֹם טָהוֹר", "אלי' מוצ'ע טאהר", "to a clean place"),
        ("אֶל-שֶׁפֶךְ הַדֶּשֶׁן", "אלי' מטרח אלרמאד", "to the place where the ash is cast"),
        ("וְשָׂרַף", "ויחרקה", "and shall burn it"),
        ("עַל-עֵצִים", "עלי' חטב", "upon wood"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
        ("עַל-שֶׁפֶךְ הַדֶּשֶׁן", "פי מוצ'ע מטרח אלרמאד", "at the place where the ash is cast"),
        ("יִשָּׂרֵף", "יחרק", "it shall be burned"),
    ],
    13: [
        ("וְאִם", "ואן", "And if"),
        ("כָּל-עֲדַת יִשְׂרָאֵל", "גמע מן גמיע אל אסראיל", "a congregation from all the house of Israel"),
        ("יִשְׁגּוּ", "סהי'", "errs"),
        ("וְנֶעְלַם", "וג'בי", "and a matter is hidden"),
        ("דָּבָר", "אמר", "from the eyes"),
        ("מֵעֵינֵי הַקָּהָל", "מן עיון אלגוק", "of the assembly"),
        ("וְעָשׂוּ", "פעמלו", "and they do"),
        ("אַחַת", "ואחדה", "one of"),
        ("מִכָּל-מִצְו‍ֹת יְהוָה", "מן פראיץ' אללה", "the commandments of God"),
        ("אֲשֶׁר לֹא-תֵעָשֶׂינָה", "אלתי לא תעמל", "which are not to be done"),
        ("וְאָשֵׁמוּ", "פאת'מו", "and they sin"),
    ],
    14: [
        (None, "ת'ם", "then"),
        ("וְנוֹדְעָה", "ערפת", "becomes known"),
        ("הַחַטָּאת", "אלכ'טייה", "the transgression"),
        ("אֲשֶׁר חָטְאוּ עָלֶיהָ", "אלתי אכ'טו בהא", "which they committed"),
        ("וְהִקְרִיבוּ", "פליקרב", "let the assembly bring"),
        ("הַקָּהָל", "אלגוק", "a bull from the cattle"),
        ("פַּר בֶּן-בָּקָר", "רת'א מן אלבקר", "as an offering"),
        ("לְחַטָּאת", "לאלד'כוה", "and bring it"),
        ("וְהֵבִיאוּ אֹתוֹ", "ויאתו בה", "to the entrance"),
        ("לִפְנֵי אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר", "of the tent of the assembly"),
    ],
    15: [
        ("וְסָמְכוּ", "ויסנד", "And the elders"),
        ("זִקְנֵי הָעֵדָה", "שיוך' אלגמאעה", "of the congregation shall lean"),
        ("אֶת-יְדֵיהֶם", "אידיהם", "their hands"),
        ("עַל-רֹאשׁ הַפָּר", "עלי' ראס אלת'ור", "upon the head of the bull"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("וְשָׁחַט אֶת-הַפָּר לִפְנֵי יְהוָה", "ויד'בחה בין ידי אללה", "and it shall be slaughtered before God"),
    ],
    16: [
        ("וְהֵבִיא", "וידכ'ל", "shall bring"),
        ("הַכֹּהֵן הַמָּשִׁיחַ", "אלאמאם אלממסוח", "the anointed imām"),
        ("מִדַּם הַפָּר", "מן דמה", "of its blood"),
        ("אֶל-אֹהֶל מוֹעֵד", "אלי' כ'בא אלמחצ'ר", "the tent of the assembly"),
    ],
    17: [
        ("וְטָבַל הַכֹּהֵן", "ויג'מס אצבעה", "And he shall dip his finger"),
        ("אֶצְבָּעוֹ", "פיה", "in it"),
        ("וְהִזָּה", "וינצח", "and sprinkle"),
        ("מִן-הַדָּם", "מנה", "from it"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֵת פְּנֵי הַפָּרֹכֶת", "קבאלה' אלסגף", "facing the veil"),
    ],
    18: [
        ("וּמִן-הַדָּם", "ומנה", "And from it"),
        ("יִתֵּן", "יצע", "he shall put"),
        ("עַל-קַרְנֹת הַמִּזְבֵּחַ", "עלי' ארכאן אלמד'בח", "upon the horns of the altar"),
        ("אֲשֶׁר לִפְנֵי יְהוָה", "אלד'י בין ידי אללה", "which is before God"),
        ("אֲשֶׁר בְּאֹהֶל מוֹעֵד", "אלד'י פי כ'בא אלמחצ'ר", "which is in the tent of the assembly"),
        ("וְאֵת כָּל-הַדָּם", "ובאקיה", "and the remainder of it"),
        ("יִשְׁפֹּךְ", "יצבה", "he shall pour out"),
        ("אֶל-יְסוֹד", "ענד אסאס", "at the base of"),
        ("מִזְבַּח הָעֹלָה", "מד'בח אלצעידה", "the altar of the burnt-offering"),
        ("אֲשֶׁר-פֶּתַח אֹהֶל מוֹעֵד", "אלד'י ענד באב כ'בא אלמחצ'ר", "which is at the entrance of the tent of the assembly"),
    ],
    19: [
        ("וְאֵת כָּל-חֶלְבּוֹ", "וגמיע שחמה", "And all its fat"),
        ("יָרִים", "ירפעה", "he shall remove"),
        ("מִמֶּנּוּ", "מנה", "from it"),
        ("וְהִקְטִיר", "ויקתרה", "and burn it in smoke"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
    ],
    20: [
        ("וְעָשָׂה", "ויעמל", "And he shall do"),
        ("לַפָּר", "בה", "with it"),
        ("כַּאֲשֶׁר עָשָׂה", "כמא עמל", "as he did"),
        ("לְפַר הַחַטָּאת", "ברת' אלדכוה", "with the bull of the offering"),
        ("כֵּן יַעֲשֶׂה-לּוֹ", "כד'אך יעמל בה", "thus shall he do with it"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        ("עֲלֵהֶם", "ענהם", "for them"),
        ("הַכֹּהֵן", "אלאמאם", "and the imām"),
        ("וְנִסְלַח לָהֶם", "ויג'פר להם", "and they shall be forgiven"),
    ],
    21: [
        ("וְהוֹצִיא", "ויכ'רג", "And he shall carry"),
        ("אֶת-הַפָּר", "גמיע אלת'ור", "all of the bull"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "outside the camp"),
        ("וְשָׂרַף אֹתוֹ", "ויחרקה", "and shall burn it"),
        ("כַּאֲשֶׁר שָׂרַף", "כמא אחרק", "as he burned"),
        ("אֵת הַפָּר הָרִאשׁוֹן", "אלת'ור אלאוול", "the first bull"),
        ("חַטַּאת הַקָּהָל הוּא", "הו ד'כוה' אלגוק", "it is the offering of the assembly"),
    ],
    22: [
        ("אֲשֶׁר", "ואן", "And if"),
        ("נָשִׂיא יֶחֱטָא", "אכ'טא שריף", "a noble errs"),
        ("וְעָשָׂה", "ועמל", "and does"),
        ("אַחַת", "ואחדה", "one of"),
        ("מִכָּל-מִצְו‍ֹת", "מן פראיץ'", "the commandments of"),
        ("יְהוָה אֱלֹהָיו", "אללה רבה", "God his Lord"),
        ("אֲשֶׁר לֹא-תֵעָשֶׂינָה", "אלתי לא תעמל", "which are not to be done"),
        ("בִּשְׁגָגָה", "סהוא", "inadvertently"),
        ("וְאָשֵׁם", "פאת'מו", "and so sins"),
    ],
    23: [
        (None, "ת'ם", "then"),
        ("אוֹ-הוֹדַע", "עלם", "becomes known"),
        ("אֵלָיו חַטָּאתוֹ", "בכ'טייתה", "his transgression"),
        ("אֲשֶׁר חָטָא בָּהּ", "אלד'י אכ'טא", "which he transgressed"),
        ("וְהֵבִיא", "פליאת", "let him bring"),
        ("אֶת-קָרְבָּנוֹ", "בקרבאנה", "his offering"),
        ("שְׂעִיר", "עתוד", "a he-goat"),
        ("עִזִּים", "מן אלמאעז", "from the goats"),
        ("זָכָר", "ד'כר", "a male"),
        ("תָּמִים", "צחיח", "sound"),
    ],
    24: [
        ("וְסָמַךְ", "ויסנד", "And he shall lean"),
        ("יָדוֹ", "ידה", "his hand"),
        ("עַל-רֹאשׁ הַשָּׂעִיר", "עלי' ראסה", "upon its head"),
        ("וְשָׁחַט", "ויד'בחה", "and shall slaughter it"),
        ("בִּמְקוֹם", "פי מוצ'ע", "in the place"),
        ("אֲשֶׁר-יִשְׁחַט אֶת-הָעֹלָה", "יד'בח אלצעידה", "where the burnt-offering is slaughtered"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("חַטָּאת הוּא", "כד'אך מא יכון ד'כוה", "such is what constitutes an offering"),
    ],
    25: [
        ("וְלָקַח הַכֹּהֵן", "ויאכ'ד' אלאמאם", "And the imām shall take"),
        ("מִדַּם הַחַטָּאת", "מן דמה", "of its blood"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("וְנָתַן", "ויגעל", "and shall place it"),
        ("עַל-קַרְנֹת", "עלי' ארכאן", "upon the horns of"),
        ("מִזְבַּח הָעֹלָה", "מד'בח אלצעידה", "the altar of the burnt-offering"),
        ("וְאֶת-דָּמוֹ", "וסאיר דמה", "and the rest of its blood"),
        ("יִשְׁפֹּךְ", "יצבה", "he shall pour out"),
        ("אֶל-יְסוֹד מִזְבַּח הָעֹלָה", "ענד אסאסה", "at its base"),
    ],
    26: [
        ("וְאֶת-כָּל-חֶלְבּוֹ", "וגמיע שחמה", "And all its fat"),
        ("יַקְטִיר", "יקתרה", "he shall burn in smoke"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("כְּחֵלֶב זֶבַח הַשְּׁלָמִים", "כשחם ד'בח אלסלאמה", "like the fat of the peace-offering"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן", "ויסתג'פר ענה אלאמאם", "and the imām shall seek forgiveness for him"),
        ("מֵחַטָּאתוֹ", "מן כ'טייתה", "from the transgression"),
        (None, "אלד'י אכ'טא", "he transgressed"),
        ("וְנִסְלַח לוֹ", "ויג'פר לה", "and he shall be forgiven"),
    ],
    27: [
        ("וְאִם-נֶפֶשׁ אַחַת", "ואן אכ'טא אנסאן ואחד", "And if a single person"),
        ("מֵעַם הָאָרֶץ", "מן עואם אלבלד", "from among the common people of the land"),
        ("בִשְׁגָגָה", "סהוא", "inadvertently"),
        ("בַּעֲשֹׂתָהּ", "פעמל", "and does"),
        ("אַחַת", "ואחדה", "one of"),
        ("מִמִּצְו‍ֹת יְהוָה", "מן פראיץ' אללה", "the commandments of God"),
        ("אֲשֶׁר לֹא-תֵעָשֶׂינָה", "אלתי לא תעמל", "which are not to be done"),
        ("וְאָשֵׁם", "פאת'ם", "and sins"),
    ],
    28: [
        (None, "ת'ם", "then"),
        ("אֵלָיו", "בכ'טייתה", "his transgression"),
        ("חַטָּאתוֹ", "אלד'י אכ'טא", "which he transgressed"),
        ("אוֹ הוֹדַע", "ערף", "becomes known"),
        ("וְהֵבִיא", "פליאת", "let him bring"),
        ("קָרְבָּנוֹ", "בקרבאנה", "his offering"),
        ("שְׂעִירַת עִזִּים", "שאה מן אלמאעז", "a she-goat from the goats"),
        ("תְּמִימָה", "צחיחה", "sound"),
        ("נְקֵבָה", "אנת'י", "a female"),
        ("עַל-חַטָּאתוֹ אֲשֶׁר חָטָא", "עלי' כ'טייתה אלד'י אכ'טא", "for his transgression which he transgressed"),
    ],
    29: [
        ("וְסָמַךְ", "ויסנד", "And he shall lean"),
        ("אֶת-יָדוֹ", "ידה", "his hand"),
        ("עַל רֹאשׁ הַחַטָּאת", "עלי' ראסהא", "upon its head"),
        ("וְשָׁחַט", "ויד'בחהא", "and shall slaughter it"),
        ("אֶת-הַחַטָּאת", "פי מו'צע", "at the place of"),
        ("בִּמְקוֹם הָעֹלָה", "אלצעידה", "the burnt-offering"),
    ],
    30: [
        ("וְלָקַח הַכֹּהֵן", "ויאכ'ד' אלאמאם", "And the imām shall take"),
        ("מִדָּמָהּ", "מן דמהא", "of its blood"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("וְנָתַן", "ויגעל", "and shall place it"),
        ("עַל-קַרְנֹת", "עלי' ארכאן", "upon the horns of"),
        ("מִזְבַּח הָעֹלָה", "מד'בח אלצעידה", "the altar of the burnt-offering"),
        ("וְאֶת-כָּל-דָּמָהּ", "וסאיר דמהא", "and the rest of its blood"),
        ("יִשְׁפֹּךְ", "יצ'בה", "he shall pour out"),
        ("אֶל-יְסוֹד הַמִּזְבֵּחַ", "ענד אסאס אלמד'בח", "at the base of the altar"),
    ],
    31: [
        ("וְאֶת-כָּל-חֶלְבָּהּ", "וגמיע שחמהא", "And all its fat"),
        ("יָסִיר", "ינזעה", "he shall remove"),
        ("כַּאֲשֶׁר הוּסַר חֵלֶב", "כמא נזע שחם", "as the fat of the goats is removed"),
        ("מֵעַל זֶבַח הַשְּׁלָמִים", "אלמאעז מן ד'בח אלסלאמה", "from the peace-offering"),
        ("וְהִקְטִיר הַכֹּהֵן", "ויקתרה אלאמאם", "and the imām shall burn it in smoke"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("לְרֵיחַ נִיחֹחַ לַיהוָה", "עלי' קראבין אללה", "above the offerings to God"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן", "ויסתג'פר ענה. אלאמאם", "and the imām shall seek forgiveness for him"),
        ("וְנִסְלַח לוֹ", "ויג'פר לה", "and he shall be forgiven"),
    ],
    32: [
        ("וְאִם-כֶּבֶשׂ", "ואן הו גאב קרבאנא מן אלצ'אן", "And if he brings his offering from the flock"),
        ("יָבִיא קָרְבָּנוֹ לְחַטָּאת", "לאלד'כוה", "as an offering"),
        ("נְקֵבָה תְמִימָה יְבִיאֶנָּה", "פליאת בה אנת'י צחיחה", "let him bring it as a female, sound"),
    ],
    33: [
        ("וְסָמַךְ", "ויסנד", "And he shall lean"),
        ("אֶת-יָדוֹ", "ידה", "his hand"),
        ("עַל רֹאשׁ הַחַטָּאת", "עלי' ראסהא", "upon its head"),
        ("וְשָׁחַט אֹתָהּ לְחַטָּאת", "ויד'בחהא לאלד'כוה", "and shall slaughter it as an offering"),
        ("בִּמְקוֹם אֲשֶׁר יִשְׁחַט אֶת-הָעֹלָה", "פי מוצ'ע אלצעידה", "at the place of the burnt-offering"),
    ],
    34: [
        ("וְלָקַח הַכֹּהֵן", "ויאכד", "And he shall take"),
        ("מִדַּם הַחַטָּאת", "מן דמהא", "of its blood"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("וְנָתַן", "ויצ'ע", "and shall place it"),
        ("עַל-קַרְנֹת", "עלי' ארכאן", "upon the horns of"),
        ("מִזְבַּח הָעֹלָה", "מד'בח אלצעידה", "the altar of the burnt-offering"),
        ("וְאֶת-כָּל-דָּמָהּ", "וסאיר דמהא", "and the rest of its blood"),
        ("יִשְׁפֹּךְ", "יצ'בה", "he shall pour out"),
        ("אֶל-יְסוֹד הַמִּזְבֵּחַ", "ענד אסאסה", "at its base"),
    ],
    35: [
        ("וְאֶת-כָּל-חֶלְבָּהּ", "וגמיע שחמהא", "And all its fat"),
        ("יָסִיר", "ינזעה", "he shall remove"),
        ("כַּאֲשֶׁר יוּסַר", "כמא ינזע", "as the fat of the sheep is removed"),
        ("חֵלֶב-הַכֶּשֶׂב", "שחם אלצ'אן", "from the peace-offering"),
        ("מִזֶּבַח הַשְּׁלָמִים", "מן ד'בח אלסלאמה", "and the imām shall burn them in smoke upon the altar"),
        ("וְהִקְטִיר הַכֹּהֵן אֹתָם הַמִּזְבֵּחָה", "ויקתרהא אלאמאם עלי' אלמד'בח", "above the offerings to God"),
        ("עַל אִשֵּׁי יְהוָה", "עלי' קראבין אללה", "and the imām shall seek forgiveness for him"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן", "ויסתג'פר ענה אלאמאם", "from his transgression which he transgressed"),
        ("עַל-חַטָּאתוֹ אֲשֶׁר-חָטָא וְנִסְלַח לוֹ", "ען כ'טייתה אלד'י אכ'טא פיג'פר לה", "and he shall be forgiven"),
    ],
}
