"""Hand-authored alignment triples for Vayikra chapter 19.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        (None, "גמאעה'", "the assembly of"),
        ("אֶל-כָּל-עֲדַת בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("קְדֹשִׁים", "כונו", "Be"),
        ("תִּהְיוּ", "מקדסין", "consecrated"),
        ("כִּי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלקדוס", "the Holy One"),
    ],
    3: [
        ("אִישׁ", "ליכאף כל אנסאן", "Let every person fear"),
        ("אִמּוֹ", "אמה", "his mother"),
        ("וְאָבִיו", "ואביה", "and his father"),
        ("וְאֶת-שַׁבְּתֹתַי", "ואחפצו סבותי", "and keep My Sabbaths"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good"),
    ],
    4: [
        ("אַל-תִּפְנוּ", "לא תולו", "Do not turn"),
        ("אֶל-הָאֱלִילִם", "אלי' אלאות'אן", "toward the idols"),
        ("וֵאלֹהֵי", "ומעבודאת", "and molten objects of"),
        ("מַסֵּכָה", "מסבוכה", "worship"),
        ("לֹא תַעֲשׂוּ", "לא תצנעו", "do not make"),
        ("לָכֶם", "לכם", "for yourselves"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלואחד", "the One"),
    ],
    5: [
        (None, "ואדא", "And when"),
        ("וְכִי תִזְבְּחוּ", "ד'בחתם", "you slaughter"),
        ("זֶבַח", "ד'בח", "a sacrifice of"),
        ("שְׁלָמִים", "סלאמה", "well-being"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "פעלי'", "in"),
        ("לִרְצֹנְכֶם", "מא ירתצ'א", "the manner that is acceptable"),
        (None, "מנכם", "from you"),
        ("תִּזְבָּחֻהוּ", "אד'בחוה", "slaughter it"),
    ],
    6: [
        (None, "אן", "It is to be"),
        ("יֵאָכֵל", "יוכל", "eaten"),
        (None, "פי", "on"),
        ("בְּיוֹם", "יום", "the day of"),
        ("זִבְחֲכֶם", "ד'בחכם", "your slaughter"),
        ("וּמִמָּחֳרָת", "ומן ג'ד", "and on the morrow"),
        ("וְהַנּוֹתָר", "ומא בקי", "and whatever remains"),
        ("עַד-יוֹם", "אלי' אליום", "until the"),
        ("הַשְּׁלִישִׁי", "אלת'אלת'", "third day"),
        (None, "פליחרק", "shall be burned"),
        ("בָּאֵשׁ", "באלנאר", "in the fire"),
    ],
    7: [
        (None, "ואן", "And if"),
        ("הֵאָכֹל יֵאָכֵל", "אכל", "is eaten"),
        (None, "מנה", "of it"),
        (None, "שי", "anything"),
        (None, "פי", "on"),
        ("בַּיּוֹם הַשְּׁלִישִׁי", "אליום אלת'אלת'", "the third day"),
        (None, "פהו", "it is"),
        (None, "כאלאכ'ס", "like the repulsive thing"),
        ("לֹא יֵרָצֶה", "לא יקבל", "it shall not be accepted"),
    ],
    8: [
        ("וְאֹכְלָיו", "ואכלה", "And he who eats it"),
        (None, "פקד", "has"),
        ("יִשָּׂא", "חמל", "borne"),
        ("עֲו‍ֹנוֹ", "וזרה", "his burden of guilt"),
        ("כִּי", "למא", "for"),
        (None, "בד'ל", "he has debased"),
        ("קֹדֶשׁ", "קדס", "what is consecrated to"),
        ("יְהוָה", "אללה", "God"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ", "וינקטע ד'אלך אלאנסאן", "and that person shall be cut off"),
        ("מֵעַמֶּיהָ", "מן בין קומה", "from among his people"),
    ],
    9: [
        (None, "ואדא", "And when"),
        ("וּבְקֻצְרְכֶם", "חצדתם", "you harvest"),
        ("אֶת-קְצִיר", "זרע", "the grain of"),
        ("אַרְצְכֶם", "בלאדכם", "your lands"),
        ("לֹא תְכַלֶּה", "פלא תסתקץ", "do not exhaust"),
        ("פְּאַת", "טרה'", "the edge of"),
        ("שָׂדְךָ", "צ'יעתך", "your field"),
        ("לִקְצֹר", "פתחצדהא", "by harvesting it"),
        ("וְלֶקֶט", "ולקיט", "and the gleanings of"),
        ("קְצִירְךָ", "זרעך", "your grain"),
        ("לֹא תְלַקֵּט", "פלא תלקטה", "do not gather them"),
    ],
    10: [
        ("וְכַרְמְךָ", "וכרמך", "And your vineyard"),
        ("לֹא תְעוֹלֵל", "פלא תמושה", "do not strip it"),
        ("וּפֶרֶט", "ומפרוט", "and the fallen grapes of"),
        ("כַּרְמְךָ", "כרמך", "your vineyard"),
        ("לֹא תְלַקֵּט", "פלא תלקטה", "do not gather them"),
        (None, "בל", "but"),
        ("תַּעֲזֹב", "אתרכהא", "leave them"),
        ("לֶעָנִי", "לאלצ'עיף", "for the weak"),
        ("וְלַגֵּר", "ואלג'ריב", "and the stranger"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good"),
    ],
    11: [
        ("לֹא תִּגְנֹבוּ", "לא תסרקו", "Do not steal"),
        ("וְלֹא-תְכַחֲשׁוּ", "ולא יגחד", "and let no"),
        ("וְלֹא-תְשַׁקְּרוּ", "ולא ינכת'", "nor break faith"),
        ("אִישׁ", "כל אמר", "man deny"),
        ("בַּעֲמִיתוֹ", "בצאחבה", "with his fellow"),
    ],
    12: [
        ("וְלֹא-תִשָּׁבְעוּ", "ולא תחלפו", "And do not swear"),
        ("בִשְׁמִי", "באסמי", "by My name"),
        ("לַשָּׁקֶר", "באטלא", "falsely"),
        (None, "פאנך", "for you"),
        (None, "אד'א", "would then"),
        ("וְחִלַּלְתָּ", "בד'לת", "have debased"),
        ("אֶת-שֵׁם", "אסם", "the name of"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    13: [
        ("לֹא-תַעֲשֹׁק", "לא תג'שם", "Do not defraud"),
        ("אֶת-רֵעֲךָ", "צאחבך", "your fellow"),
        ("וְלֹא תִגְזֹל", "ולא תג'צ'בה", "nor rob him"),
        ("לֹא-תָלִין", "ולא תבית", "and do not let"),
        ("פְּעֻלַּת", "אגרה'", "the wages of"),
        ("שָׂכִיר", "אלאגיר", "a hired hand"),
        ("אִתְּךָ", "ענדך", "with you"),
        ("עַד-בֹּקֶר", "אלי' אלג'דאה", "until the morning"),
    ],
    14: [
        ("לֹא-תְקַלֵּל", "לא תשתם", "Do not revile"),
        ("חֵרֵשׁ", "אצמא", "the deaf"),
        ("וְלִפְנֵי", "ובין ידי", "and before"),
        ("עִוֵּר", "אעמא", "a blind person"),
        ("לֹא תִתֵּן", "לא תצייר", "do not place"),
        ("מִכְשֹׁל", "מעת'רא", "a stumbling block"),
        ("וְיָרֵאתָ", "וכ'ף", "and fear"),
        ("מֵּאֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    15: [
        ("לֹא-תַעֲשׂוּ", "לא תצנעו", "Do not commit"),
        ("עָוֶל", "גורא", "injustice"),
        ("בַּמִּשְׁפָּט", "פי אלחכם", "in judgment"),
        ("לֹא-תִשָּׂא", "ולא תחאבון", "do not favor"),
        ("פְנֵי-דָל", "פקירא", "the poor"),
        ("וְלֹא תֶהְדַּר", "ולא תבתהגון", "and do not defer to"),
        ("פְּנֵי גָדוֹל", "גלילא", "the great"),
        (None, "בל", "but"),
        ("בְּצֶדֶק", "באלעדל", "with equity"),
        ("תִּשְׁפֹּט", "אחכם", "judge"),
        (None, "פי מא בין", "among"),
        ("עֲמִיתֶךָ", "קומך", "your people"),
    ],
    16: [
        ("לֹא-תֵלֵךְ", "לא תמץ", "Do not go about"),
        ("רָכִיל", "מאהלא", "in leisurely prying"),
        ("בְּעַמֶּיךָ", "בקומך", "among your people"),
        ("לֹא תַעֲמֹד", "ולא תקום", "and do not stand"),
        ("עַל-דַּם", "עלי' דם", "against the blood of"),
        ("רֵעֶךָ", "צאחבך", "your fellow"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    17: [
        ("לֹא-תִשְׂנָא", "לא תשן", "Do not hate"),
        ("אֶת-אָחִיךָ", "אכ'יך", "your brother"),
        ("בִּלְבָבֶךָ", "פי קלבך", "in your heart"),
        (None, "בל", "but"),
        ("הוֹכֵחַ", "עצ'ה", "admonish"),
        (None, "[ועט'א[", "him"),
        ("תּוֹכִיחַ", "ועצ'א", "with admonition"),
        ("וְלֹא-תִשָּׂא", "ולא תחמל", "and do not bear"),
        (None, "ענה", "on his account"),
        ("עָלָיו חֵטְא", "וזרא", "a burden of guilt"),
    ],
    18: [
        ("לֹא-תִקֹּם", "לא תנקם", "Do not take revenge"),
        ("וְלֹא-תִטֹּר", "ולא תחקד", "and do not bear a grudge"),
        ("אֶת-בְּנֵי עַמֶּךָ", "עלי' קומך", "against your people"),
        ("וְאָהַבְתָּ", "ואחבב", "and love"),
        ("לְרֵעֲךָ", "לצאחבך", "for your fellow"),
        ("כָּמוֹךָ", "מת'ל נפסך", "what you love for yourself"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אגאזיך כ'ירא", "I shall recompense you with good"),
    ],
    19: [
        ("אֶת-חֻקֹּתַי", "רסומי", "My statutes"),
        ("תִּשְׁמֹרוּ", "פאחפצ'והא", "keep them"),
        ("בְּהֶמְתְּךָ", "בהאימך", "Your beasts"),
        ("לֹא-תַרְבִּיעַ", "לא תנזוהא", "do not mate them"),
        ("כִּלְאַיִם", "מן נועין", "from two kinds"),
        ("שָׂדְךָ", "וצ'יאעך", "and your fields"),
        ("לֹא-תִזְרַע", "לא תזרעהא", "do not sow them"),
        (None, "מן נועין", "from two kinds"),
        ("וּבֶגֶד", "ות'וב", "and a garment of"),
        (None, "מן נועין", "two kinds"),
        (None, "מלחמין", "intertwined"),
        ("לֹא יַעֲלֶה", "לא יעלו", "let it not come"),
        ("עָלֶיךָ", "עליך", "upon you"),
    ],
    20: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "רגל", "man"),
        ("כִּי-יִשְׁכַּב", "צ'אגע", "who lies with"),
        ("אֶת-אִשָּׁה", "אמראה", "a woman"),
        ("שִׁכְבַת-זֶרַע", "מצ'אגעה' אנסאל", "in the manner of procreation"),
        ("וְהִוא", "והי", "and she is"),
        ("שִׁפְחָה", "אמה", "a maidservant"),
        ("נֶחֱרֶפֶת", "מכ'טובה", "betrothed"),
        ("לְאִישׁ", "לאי רגל כאן", "to any man"),
        ("וְהָפְדֵּה", "ופדא", "and a ransom"),
        ("לֹא נִפְדָּתָה", "לם תפדא", "has not been paid for her"),
        ("אוֹ חֻפְשָׁה", "ועתקהא", "and her freedom"),
        ("לֹא נִתַּן-לָהּ", "לם ידפע אליהא", "has not been given to her"),
        ("בִּקֹּרֶת תִּהְיֶה", "פלתכון מחדודה", "then she shall be subject to punishment"),
        ("לֹא יוּמְתוּ", "ולא יקתלא", "and they shall not be put to death"),
        ("כִּי-לֹא חֻפָּשָׁה", "אד' לם תעתק", "since she has not been freed"),
    ],
    21: [
        (None, "פליאת", "And he shall bring"),
        ("וְהֵבִיא", "בקרבאנה", "his offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("אֵיל", "כבשא", "a ram"),
        ("אָשָׁם", "לקרבאן אלאת'ם", "as a guilt offering"),
    ],
    22: [
        ("הַכֹּהֵן", "אלאמאם", "And the imām"),
        ("וְכִפֶּר", "פיסתג'פר", "shall seek forgiveness"),
        (None, "ענה", "for him"),
        (None, "בין ידי", "before"),
        ("לִפְנֵי יְהוָה", "אללה", "God"),
        ("עַל-חַטָּאתוֹ", "ען כ'טייתה", "for his sin"),
        ("אֲשֶׁר חָטָא", "אלד'י אכ'טא", "which he has sinned"),
        ("וְנִסְלַח", "פיג'פר לה ד'אלך", "and it shall be forgiven him"),
    ],
    23: [
        (None, "ומד'", "And from the time"),
        ("וְכִי-תָבֹאוּ", "תדכ'לון", "you enter"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("וּנְטַעְתֶּם", "פתג'רסון", "and plant"),
        ("כָּל-עֵץ", "כל שגר", "any"),
        ("מַאֲכָל", "מטעם", "food-bearing tree"),
        ("וַעֲרַלְתֶּם", "פתחרמו", "you shall declare"),
        ("עָרְלָתוֹ", "ת'מרה", "its fruit"),
        (None, "תחרימא", "forbidden with a full prohibition"),
        ("שָׁלֹשׁ שָׁנִים", "ת'לאת' סנין", "three years"),
        ("יִהְיֶה לָכֶם", "יכון עליכם", "it shall be"),
        ("עֲרֵלִים", "מחרמא", "forbidden to you"),
        ("לֹא יֵאָכֵל", "לא יוכל", "not to be eaten"),
    ],
    24: [
        ("וּבַשָּׁנָה", "ופי אלסנה", "And in the"),
        ("הָרְבִיעִת", "אלראבעה", "fourth year"),
        ("יִהְיֶה", "יכון", "shall be"),
        ("כָּל-פִּרְיוֹ", "גמיע ת'מרה", "all its fruit"),
        ("קֹדֶשׁ", "מקדסא", "consecrated"),
        ("הִלּוּלִים", "מוהלא", "dedicated"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    25: [
        ("וּבַשָּׁנָה", "ופי אלסנה", "And in the"),
        ("הַחֲמִישִׁת", "אלכ'אמסה", "fifth year"),
        ("תֹּאכְלוּ", "תאכלו", "you may eat"),
        ("אֶת-פִּרְיוֹ", "ת'מרה", "its fruit"),
        ("לְהוֹסִיף", "פאני", "for I am"),
        ("אֲנִי יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אזיד", "I shall increase"),
        (None, "לכם", "for you"),
        ("תְּבוּאָתוֹ", "פי ג'לתה", "its yield"),
    ],
    26: [
        ("לֹא תֹאכְלוּ", "לא תאכלו", "Do not eat"),
        ("עַל-הַדָּם", "עלי' אלדם", "over the blood"),
        ("לֹא תְנַחֲשׁוּ", "לא תתטיירו", "do not take omens"),
        ("וְלֹא תְעוֹנֵנוּ", "ולא תתפאולו", "and do not seek auguries"),
    ],
    27: [
        ("לֹא תַקִּפוּ", "ולא תחדקו", "And do not shave"),
        ("פְּאַת", "בזואיא", "the corners of"),
        ("רֹאשְׁכֶם", "רוסכם", "your heads"),
        ("וְלֹא תַשְׁחִית", "ולא תסתאצל", "and do not uproot"),
        ("אֵת פְּאַת", "זואיא", "the corners of"),
        ("זְקָנֶךָ", "לחיתך", "your beard"),
    ],
    28: [
        ("וְשֶׂרֶט", "וכ'דשא", "And a scratch"),
        ("לָנֶפֶשׁ", "עלי' מיית", "for the dead"),
        ("לֹא תִתְּנוּ", "לא תגעלו", "do not place"),
        ("בִּבְשַׂרְכֶם", "פי אבדאנכם", "on your bodies"),
        ("וּכְתֹבֶת", "וכתאבה'", "and tattooed"),
        ("קַעֲקַע", "ושם", "writing"),
        ("לֹא תִתְּנוּ", "לא תגעלו", "do not place"),
        ("בָּכֶם", "פיכם", "on yourselves"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    29: [
        ("אַל-תְּחַלֵּל", "ולא תבד'ל", "And do not give over"),
        ("אֶת-בִּתְּךָ", "אבנתך", "your daughter"),
        ("לְהַזְנוֹתָהּ", "לאלפגור", "to debauchery"),
        ("וְלֹא-תִזְנֶה", "כלא יפגר", "lest the people of the land fall into debauchery"),
        ("הָאָרֶץ", "אהל אלארץ'", "and"),
        ("וּמָלְאָה", "פתמתלי", "it fill"),
        ("הָאָרֶץ זִמָּה", "פואחשא", "with lewdness"),
    ],
    30: [
        ("אֶת-שַׁבְּתֹתַי", "סבותי", "My Sabbaths"),
        ("תִּשְׁמֹרוּ", "פאחפצ'והא", "keep them"),
        ("וּמִקְדָּשִׁי", "ומקדסי", "and My sanctuary"),
        ("תִּירָאוּ", "פהאבוה", "hold it in awe"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "שרפתהמא", "who has honoured them"),
    ],
    31: [
        ("אַל-תִּפְנוּ", "ולא תולו", "Do not turn"),
        ("אֶל-הָאֹבֹת", "אלי' אלמשעוד'ין", "toward the conjurers"),
        ("וְאֶל-הַיִּדְּעֹנִים", "ואלעראפין", "and the diviners"),
        ("אַל-תְּבַקְשׁוּ", "ולא תטלבו", "and do not seek"),
        ("לְטָמְאָה", "אן תעצוני", "to disobey Me"),
        ("בָהֶם", "בהא", "by means of them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "עאלם אלג'יב", "the Knower of what is hidden"),
    ],
    32: [
        ("מִפְּנֵי", "מן בין ידי", "Before"),
        ("שֵׂיבָה", "ד'ו אלשיבה", "one possessed of grey hair"),
        ("תָּקוּם", "פקם", "rise"),
        ("וְהָדַרְתָּ", "ואבתהג", "and show gladness toward"),
        ("פְּנֵי", "וגה", "the face of"),
        ("זָקֵן", "אלשיך'", "the elder"),
        ("וְיָרֵאתָ", "וכף", "and fear"),
        ("מֵּאֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
    ],
    33: [
        (None, "ואדא", "And when"),
        ("וְכִי-יָגוּר", "סכן", "settles"),
        (None, "מעכם", "among you"),
        ("גֵּר", "ג'ריב", "a stranger"),
        ("בְּאַרְצְכֶם", "פי בלדכם", "in your land"),
        ("לֹא תוֹנוּ", "פלא תצ'הדוה", "do not oppress him"),
    ],
    34: [
        (None, "וליכון", "shall be"),
        (None, "מעכם", "to you"),
        ("כְּאֶזְרָח", "כצריח", "as a native"),
        (None, "מנכם", "among you"),
        ("הַגֵּר", "אלג'ריב", "The stranger"),
        ("הַגָּר", "אלדכ'יל", "who has come to dwell"),
        (None, "פי מא בינכם", "among you"),
        ("וְאָהַבְתָּ", "ואחבב", "and love"),
        ("לוֹ", "לה", "for him"),
        ("כָּמוֹךָ", "כנפסך", "as for yourself"),
        ("כִּי-גֵרִים", "לאנה טאל מא", "for you were long"),
        ("הֱיִיתֶם", "כנתם", "strangers"),
        (None, "ג'רבא", ""),
        ("בְּאֶרֶץ", "פי בלד", "in the land of"),
        ("מִצְרָיִם", "מצר", "Egypt"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגמעין", "of all of you"),
    ],
    35: [
        ("לֹא-תַעֲשׂוּ", "לא תצנעו", "Do not commit"),
        ("עָוֶל", "ג'שא", "fraud"),
        ("בַּמִּשְׁפָּט", "פי אלחכם", "in judgment"),
        (None, "ולא", "nor"),
        ("בַּמִּדָּה", "פי אלמסאחה", "in measurement"),
        ("בַּמִּשְׁקָל", "ואלוזן", "nor in weight"),
        ("וּבַמְּשׂוּרָה", "ואלמכיאל", "nor in measure"),
    ],
    36: [
        (None, "בל", "But"),
        ("מֹאזְנֵי צֶדֶק", "מיאזין עאדלה", "just scales"),
        ("אַבְנֵי-צֶדֶק", "וצנגאת עאדלה", "and just weights"),
        ("אֵיפַת צֶדֶק", "ואכיאל עאדלה", "and just dry measures"),
        ("וְהִין צֶדֶק", "ואקסאט עאדלה", "and just liquid measures"),
        ("יִהְיֶה לָכֶם", "תכון לכם", "shall be yours"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלעדל", "the Just"),
        (None, "אלמכ'רגכם", "who brought you out"),
        (None, "מן בלד", "from the land of"),
        ("מֵאֶרֶץ מִצְרָיִם", "מצר", "Egypt"),
    ],
    37: [
        ("וּשְׁמַרְתֶּם", "ואחפצו", "And keep"),
        ("אֶת-כָּל-חֻקֹּתַי", "גמיע רסומי", "all My statutes"),
        ("וְאֶת-כָּל-מִשְׁפָּטַי", "ואחכאמי", "and all My ordinances"),
        ("וַעֲשִׂיתֶם", "ואעמלו", "and act"),
        ("אֹתָם", "בהא", "according to them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good"),
    ],
}
