"""Hand-authored alignment triples for Vayikra chapter 17.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה", "and his sons"),
        ("וְאֶל כָּל-בְּנֵי יִשְׂרָאֵל", "וסאיר בני אסראיל.", "and the rest of the sons of Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵיהֶם", "להם.", "to them"),
        ("זֶה הַדָּבָר", "הדא אלאמר", "This is the matter"),
        ("אֲשֶׁר-צִוָּה", "אלד'י אמר בה", "which"),
        ("יְהוָה", "אללה", "God has commanded"),
    ],
    3: [
        ("אִישׁ אִישׁ", "אי רגל", "Any man"),
        ("מִבֵּית יִשְׂרָאֵל", "מן בני אסראיל.", "from the sons of Israel"),
        ("אֲשֶׁר יִשְׁחַט", "יד'בח", "who slaughters"),
        ("שׁוֹר", "ת'ורא", "an ox"),
        ("אוֹ-כֶשֶׂב", "או כבשא.", "or a ram"),
        ("אוֹ-עֵז", "או ענזא", "or a goat"),
        ("בַּמַּחֲנֶה", "פי אלעסכר.", "in the camp"),
        ("אוֹ אֲשֶׁר יִשְׁחַט מִחוּץ לַמַּחֲנֶה", "או פי כ'ארגה", "or outside of it"),
    ],
    4: [
        ("וְאֶל-פֶּתַח", "ולם יאתי בה אלי' באב", "and did not bring it to the entrance"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר.", "of the tent of the assembly"),
        (None, "פיקרבה", "to offer it"),
        (None, "אד'", "since"),
        (None, "הו", "it is"),
        ("קָרְבָּן", "קרבאן", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("מִשְׁכַּן יְהוָה", "מסכנה.", "His dwelling"),
        ("דָּם יֵחָשֵׁב", "פהו יחסב עליה", "it shall be reckoned against him"),
        (None, "כמן", "as one who has"),
        ("דָּם שָׁפָךְ", "ספך' דם", "shed"),
        (None, "אנסאן.", "human blood"),
        ("וְנִכְרַת", "וינקטע", "shall be cut off"),
        ("הָאִישׁ הַהוּא", "ד'אלך אלאנסאן", "that person"),
        ("מִקֶּרֶב עַמּוֹ", "מן בין קומה", "from among his people"),
    ],
    5: [
        ("לְמַעַן", "לכי", "This is so that"),
        ("אֲשֶׁר יָבִיאוּ", "יאתון", "may bring"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל.", "the sons of Israel"),
        ("אֶת-זִבְחֵיהֶם", "בד'באיחהם", "their sacrifices"),
        ("אֲשֶׁר הֵם זֹבְחִים", "אלתי לעלהם אן יד'בחונהא", "those which they might slaughter"),
        ("עַל-פְּנֵי הַשָּׂדֶה", "עלי' וגה אלצחרא.", "upon the face of the wilderness"),
        ("וֶהֱבִיאֻם", "פיגו בהא", "and bring them"),
        ("לַיהוָה", "בין ידי אללה.", "before God"),
        ("אֶל-פֶּתַח אֹהֶל מוֹעֵד", "אלי' באב כ'בא אלמחצ'ר", "to the entrance of the tent of the assembly"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם.", "to the priest"),
        ("וְזָבְחוּ", "פיד'בחוהא", "and slaughter them"),
        ("זִבְחֵי שְׁלָמִים", "ד'באיח סלאמה", "as peace-offerings"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    6: [
        ("וְזָרַק", "וירש", "shall sprinkle"),
        ("הַכֹּהֵן", "אלאמאם", "And the priest"),
        ("אֶת-הַדָּם", "דמהא", "their blood"),
        ("עַל-מִזְבַּח יְהוָה", "עלי' מד'בח אללה.", "upon the altar of God"),
        ("פֶּתַח אֹהֶל מוֹעֵד", "אלד'י ענד באב כ'בא אלמחצ'ר.", "which is at the entrance of the tent of the assembly"),
        ("וְהִקְטִיר", "ויקתר", "and burn"),
        ("הַחֵלֶב", "שחמהא.", "their fat"),
        (None, "מקבולא", "acceptable"),
        (None, "מרצ'ייא", "and pleasing"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    7: [
        ("וְלֹא-יִזְבְּחוּ", "ולא יד'בחו", "And they shall"),
        ("עוֹד", "אבדא", "nevermore slaughter"),
        ("אֶת-זִבְחֵיהֶם", "ד'באיחהם.", "their sacrifices"),
        ("לַשְּׂעִירִם", "לאלשיאטין.", "to the demons"),
        ("אֲשֶׁר הֵם", "אלד'י הם", "after which they"),
        ("זֹנִים", "יטגון", "go astray"),
        ("אַחֲרֵיהֶם", "פי תבעהא.", "in following them"),
        (None, "פיכון", "This shall be"),
        (None, "ד'אלך", "for them"),
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "a statute forever"),
        ("תִּהְיֶה-זֹּאת לָהֶם", "להם.", "for their"),
        ("לְדֹרֹתָם", "לאגיאלהם", "generations"),
    ],
    8: [
        ("וַאֲלֵהֶם תֹּאמַר", "וקל להם.", "And say to them"),
        ("אִישׁ אִישׁ", "אי רגל", "Any man"),
        ("מִבֵּית יִשְׂרָאֵל", "מן בני אסראיל.", "from the sons of Israel"),
        ("וּמִן-הַגֵּר", "ומן אלג'ריב", "or from the stranger"),
        ("אֲשֶׁר-יָגוּר", "אלדכ'יל", "who has come in"),
        ("בְּתוֹכָם", "פי מא בינהם.", "among them"),
        ("אֲשֶׁר-יַעֲלֶה עֹלָה", "יחרק צעידה", "who burns an offering"),
        ("אוֹ-זָבַח", "או ד'בחא", "or a sacrifice"),
    ],
    9: [
        ("וְאֶל-פֶּתַח", "ואלי' באב", "and did not bring it to the entrance"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "of the tent of the assembly"),
        ("לֹא יְבִיאֶנּוּ", "לם יאתי בה.", "to offer it"),
        ("לַעֲשׂוֹת אֹתוֹ", "ליקרבה כד'אך", "thus"),
        ("לַיהוָה", "ללה.", "to God"),
        ("וְנִכְרַת", "פינקטע", "shall be cut off"),
        ("הָאִישׁ הַהוּא", "ד'אלך אלאנסאן", "that person"),
        ("מֵעַמָּיו", "מן קומה", "from his people"),
    ],
    10: [
        ("וְאִישׁ אִישׁ", "ואי רגל", "And any man"),
        ("מִבֵּית יִשְׂרָאֵל", "מן אל אסראיל.", "from the house of Israel"),
        ("וּמִן-הַגֵּר הַגָּר", "ומן אלג'ריב אלדכ'יל", "or from the stranger who has come in"),
        ("בְּתוֹכָם", "פי מא בינהם.", "among them"),
        ("אֲשֶׁר יֹאכַל כָּל-דָּם", "יאכל שייא מן אלדם.", "who eats anything of blood"),
        ("וְנָתַתִּי פָנַי", "אחללת ג'צ'בי", "I shall unleash My wrath"),
        ("בַּנֶּפֶשׁ הָאֹכֶלֶת", "פיה.", "upon him"),
        ("וְהִכְרַתִּי", "וקטעתה", "and shall cut him off"),
        ("מִקֶּרֶב עַמָּהּ", "מן בין קומה", "from among his people"),
    ],
    11: [
        ("כִּי", "לאן", "For"),
        ("נֶפֶשׁ הַבָּשָׂר", "נפס גמיע אלבשריון", "the soul of all fleshly beings"),
        ("בַּדָּם", "אלדם", "blood"),
        ("הִוא", "מסכנהא.", "is its dwelling"),
        ("וַאֲנִי נְתַתִּיו", "ולד'אלך געלתה", "and therefore I have appointed it"),
        ("לָכֶם", "לכם", "for you"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח.", "upon the altar"),
        ("לְכַפֵּר", "ליסתג'פר בה", "that forgiveness may be sought by it"),
        ("עַל-נַפְשֹׁתֵיכֶם", "ען אנפסכם.", "for your souls"),
        ("כִּי-הַדָּם", "לאן אלדם", "for blood"),
        ("הוּא בַּנֶּפֶשׁ יְכַפֵּר", "יכפר ען אלנפס", "makes atonement for the soul"),
    ],
    12: [
        ("עַל-כֵּן", "ולד'אלך", "Therefore"),
        ("אָמַרְתִּי", "קלת", "I have said"),
        ("לִבְנֵי יִשְׂרָאֵל", "לבני אסראיל.", "to the sons of Israel"),
        ("כָּל-נֶפֶשׁ", "כל אנסאן", "no person"),
        ("מִכֶּם", "מנכם", "among you"),
        ("לֹא-תֹאכַל דָּם", "לא יאכל דמא.", "shall eat blood"),
        ("וְהַגֵּר הַגָּר", "חתי' אלג'ריב אלדכ'יל", "and even the stranger who has come in"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
        ("לֹא-יֹאכַל דָּם", "לא יאכל דמא", "shall not eat blood"),
    ],
    13: [
        ("וְאִישׁ אִישׁ", "ואי רגל", "And any man"),
        ("מִבְּנֵי יִשְׂרָאֵל", "מן בני אסראיל.", "from the sons of Israel"),
        ("וּמִן-הַגֵּר הַגָּר", "ומן אלג'ריב אלדכ'יל", "or from the stranger who has come in"),
        ("בְּתוֹכָם", "פי מא בינהם.", "among them"),
        ("אֲשֶׁר יָצוּד", "אצטאד", "who hunts"),
        ("צֵיד", "צידא", "game"),
        ("חַיָּה", "מן אלוחש", "from the wild creatures"),
        ("אוֹ-עוֹף", "או מן אלטאיר", "or from the birds"),
        ("אֲשֶׁר יֵאָכֵל", "אלד'י אכלה חלאל.", "whose eating is permitted"),
        ("וְשָׁפַךְ", "פליצב", "let him pour out"),
        ("אֶת-דָּמוֹ", "דמה.", "its blood"),
        ("וְכִסָּהוּ", "ויוארה", "and cover it"),
        ("בֶּעָפָר", "באלתראב", "with earth"),
    ],
    14: [
        ("כִּי-נֶפֶשׁ", "לאן נפס", "For the soul"),
        ("כָּל-בָּשָׂר", "גמיע אלבשריון.", "of all fleshly beings"),
        (None, "כל ואחד", "each one"),
        ("דָּמוֹ בְנַפְשׁוֹ הוּא", "פי דמה.", "resides in its blood"),
        ("וָאֹמַר", "ולאני קלת", "and since I have said"),
        ("לִבְנֵי יִשְׂרָאֵל", "לבני אסראיל.", "to the sons of Israel"),
        ("דַּם כָּל-בָּשָׂר", "דם כל בשרי", "the blood of every creature of flesh"),
        ("לֹא תֹאכֵלוּ", "לא תאכלו.", "you shall not eat"),
        ("כִּי", "אד'", "for"),
        ("נֶפֶשׁ כָּל-בָּשָׂר", "נפס כל בשרי", "the soul of every creature of flesh"),
        ("דָּמוֹ הִוא", "אלדם מסכנהא.", "blood is its dwelling"),
        ("כָּל-אֹכְלָיו", "וכל מן אכלה", "and whoever eats it"),
        ("יִכָּרֵת", "ינקטע", "shall be cut off"),
    ],
    15: [
        ("וְכָל-נֶפֶשׁ", "ואי אנסאן", "And any person"),
        ("אֲשֶׁר תֹּאכַל", "אכל", "who eats"),
        ("נְבֵלָה", "נבילה", "what has died of itself"),
        ("וּטְרֵפָה", "או סקימה.", "or what is diseased"),
        ("בָּאֶזְרָח", "מן אלצריח", "whether native-born"),
        ("וּבַגֵּר", "ואלג'ריב.", "or stranger"),
        ("וְכִבֶּס", "פליג'סל", "let him wash"),
        ("בְּגָדָיו", "ת'יאבה.", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("בַּמַּיִם", "באלמא.", "in water"),
        ("וְטָמֵא", "וינגס", "and he shall be impure"),
        ("עַד-הָעֶרֶב", "אלי' אלמג'יב", "until the evening"),
        ("וְטָהֵר", "ויטהר", "and then be pure"),
    ],
    16: [
        ("וְאִם", "פאן", "But if"),
        ("לֹא יְכַבֵּס", "הו לם יג'סלה.", "he does not wash them"),
        ("וּבְשָׂרוֹ", "או לם ירחץ' בדנה.", "or does not bathe his body"),
        ("לֹא יִרְחָץ", "פקד", "he shall have"),
        ("וְנָשָׂא עֲו‍ֹנוֹ", "חמל וזרה", "borne his guilt"),
    ],
}
