"""Hand-authored alignment triples for Vayikra chapter 12.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Instruct"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("אִשָּׁה", "אמראה", "woman"),
        (None, "אייה'", "Any"),
        ("כִּי תַזְרִיעַ", "עלקת", "who has conceived"),
        ("וְיָלְדָה", "פולדת", "and borne"),
        ("זָכָר", "ד'כרא", "a male"),
        ("וְטָמְאָה", "פלתנגס", "she shall be impure"),
        ("שִׁבְעַת", "סבעה'", "seven"),
        ("יָמִים", "איאם", "days"),
        ("כִּימֵי", "כאיאם", "as in the days"),
        (None, "בעד", "following"),
        ("נִדַּת", "חיצ'תהא", "her menstrual separation"),
        (None, "יכון", "shall be"),
        (None, "חכם", "the ruling of"),
        ("תִּטְמָא", "נגאסתהא", "her impurity"),
    ],
    3: [
        ("וּבַיּוֹם", "ופי אליום", "And on the"),
        ("הַשְּׁמִינִי", "אלת'אמן", "eighth day"),
        ("יִמּוֹל", "תכ'תן", "shall be circumcised"),
        ("בְּשַׂר עָרְלָתוֹ", "קלפה' אחלילה", "the foreskin of his member"),
    ],
    4: [
        ("וּשְׁלֹשִׁים יוֹם וּשְׁלֹשֶׁת יָמִים", "ות'לאת'ה ות'לאתין יומא", "thirty-three days"),
        ("תֵּשֵׁב", "תקים", "she shall remain"),
        (None, "פי", "in"),
        ("בִּדְמֵי", "דם", "the blood of"),
        ("טָהֳרָה", "אלטהר", "purification"),
        ("בְּכָל-קֹדֶשׁ", "אלאקדאס", "anything of the sacred things"),
        ("לֹא-תִגָּע", "ולא תלאמס שייא מן", "she shall not touch"),
        ("וְאֶל-הַמִּקְדָּשׁ", "אלקדס", "the sanctuary"),
        ("לֹא תָבֹא", "ולא תדכל אלי'", "nor enter into"),
        ("עַד-מְלֹאת", "אלי' כמאל", "until the completion of"),
        ("יְמֵי", "איאם", "the days of"),
        ("טָהֳרָהּ", "טהרהא", "her purification"),
    ],
    5: [
        ("וְאִם-נְקֵבָה", "פאן ולדת אנתי'", "But if she bears a female"),
        ("וְטָמְאָה", "פלתנגס", "she shall be impure"),
        ("שְׁבֻעַיִם", "אסבועין", "two weeks"),
        ("כְּנִדָּתָהּ", "כחכם חיצ'תהא", "according to the ruling of her menstrual separation"),
        ("וְשִׁשִּׁים יוֹם וְשֵׁשֶׁת יָמִים", "וסתה וסתין יומא", "sixty-six days"),
        ("תֵּשֵׁב", "תקים", "she shall remain"),
        ("עַל-דְּמֵי", "עלי' דם", "upon the blood of"),
        ("טָהֳרָה", "אלטהר", "purification"),
    ],
    6: [
        ("וּבִמְלֹאת", "וענד תמאם", "And upon the completion of"),
        ("יְמֵי", "איאם", "the days of"),
        ("טָהֳרָהּ", "טהרהא", "her purification"),
        ("לְבֵן", "לאבן", "for a son"),
        (None, "כאן", "whether"),
        ("אוֹ", "או", "or"),
        ("לְבַת", "אבנה", "for a daughter"),
        ("תָּבִיא", "תאתי", "she shall bring"),
        ("כֶּבֶשׂ בֶּן-שְׁנָתוֹ", "בכ'רוף אבן סנתה", "a yearling lamb"),
        ("לְעֹלָה", "לאלצעידה", "for the ascent-offering"),
        ("וּבֶן-יוֹנָה", "ופרך' חמאם", "and a young pigeon"),
        ("אוֹ-תֹר", "או שפנינא", "or a turtledove"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification-offering"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל-מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמם", "to the imām"),
    ],
    7: [
        ("וְהִקְרִיבוֹ", "ויקרבה", "And he shall present it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek atonement"),
        ("עָלֶיהָ", "ענהא", "on her behalf"),
        ("וְטָהֲרָה", "ותטהר", "and she shall be purified"),
        ("מִמְּקֹר", "מן נביע", "from the flowing of"),
        ("דָּמֶיהָ", "דמהא", "her blood"),
        ("זֹאת", "הד'ה", "This is"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הַיֹּלֶדֶת", "אלואלדה", "the woman who gives birth"),
        ("לַזָּכָר", "ד'כר", "to a male"),
        ("אוֹ", "או", "or"),
        ("לַנְּקֵבָה", "אנת'י", "a female"),
    ],
    8: [
        ("וְאִם-לֹא", "ואן לם", "And if"),
        ("תִמְצָא", "תנאל", "does not attain"),
        ("יָדָהּ", "ידהא", "her hand"),
        ("דֵּי שֶׂה", "מקדאר שאה", "the value of a ewe"),
        ("וְלָקְחָה", "פלתאכד'", "then she shall take"),
        ("שְׁתֵּי-תֹרִים", "שפנינין", "two turtledoves"),
        ("אוֹ", "או", "or"),
        ("שְׁנֵי בְּנֵי יוֹנָה", "פרכ'י חמאם", "two young pigeons"),
        ("אֶחָד לְעֹלָה", "אחדהמא לאלצעידה", "one of them for the ascent-offering"),
        ("וְאֶחָד לְחַטָּאת", "ואלאכ'ר לאלד'כוה", "and the other for the purification-offering"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek atonement"),
        ("עָלֶיהָ", "ענהא", "on her behalf"),
        ("וְטָהֵרָה", "ותטהר", "and she shall be purified"),
    ],
}
