"""Hand-authored alignment triples for Vayikra chapter 27."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי תכלימא",
         "Then God spoke to Moses in [divine] speech."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל וקל להם",
         "Command the sons of Israel and say to them:"),
        ("אִישׁ כִּי יַפְלִא נֶדֶר--בְּעֶרְכְּךָ נְפָשֹׁת לַיהוָה",
         "אי אנסאן סווג' נד'רא. מן אלנפוס ללה",
         "any person who has vowed a vow of souls to God —"),
    ],
    3: [
        ("וְהָיָה עֶרְכְּךָ הַזָּכָר מִבֶּן עֶשְׂרִים שָׁנָה וְעַד בֶּן-שִׁשִּׁים שָׁנָה",
         "פיכון קימה' אלדכר. מן אבן עשרין סנה. ואלי' אבן סתין סנה",
         "the valuation of the male, from twenty years of age to sixty years of age,"),
        ("וְהָיָה עֶרְכְּךָ חֲמִשִּׁים שֶׁקֶל כֶּסֶף--בְּשֶׁקֶל הַקֹּדֶשׁ",
         "פליכון קימתה. כ'מסין מת'קאל פצ'ה במת'קאל אלקדס",
         "shall be fifty mithqals of silver by the mithqal of the sanctuary;"),
    ],
    4: [
        ("וְאִם-נְקֵבָה הִוא--וְהָיָה עֶרְכְּךָ שְׁלֹשִׁים שָׁקֶל",
         "ואן כאנת אנת'א. פקימתהא ת'לאת'ין",
         "and if it be a female, her valuation shall be thirty;"),
    ],
    5: [
        ("וְאִם מִבֶּן-חָמֵשׁ שָׁנִים וְעַד בֶּן-עֶשְׂרִים שָׁנָה",
         "ואן כאן מן אבן כ'מס סנין. ואלי' אבן עשרין סנה",
         "and if it be from five years of age to twenty years of age,"),
        ("וְהָיָה עֶרְכְּךָ הַזָּכָר עֶשְׂרִים שְׁקָלִים וְלַנְּקֵבָה עֲשֶׂרֶת שְׁקָלִים",
         "פקימה' אלד'כר עשרין מת'קאל. ואלאנת'א עשרה",
         "the valuation of the male shall be twenty mithqals, and the female ten;"),
    ],
    6: [
        ("וְאִם מִבֶּן-חֹדֶשׁ וְעַד בֶּן-חָמֵשׁ שָׁנִים",
         "ואן כאן מן אבן שהר. ואלי' אבן כ'מס סנין",
         "and if it be from one month of age to five years of age,"),
        ("וְהָיָה עֶרְכְּךָ הַזָּכָר חֲמִשָּׁה שְׁקָלִים כָּסֶף וְלַנְּקֵבָה עֶרְכְּךָ שְׁלֹשֶׁת שְׁקָלִים כָּסֶף",
         "פקימה' אלד'כר כ'מסה מת'אקיל פצ'ה. ואלאנת'א ת'לאת'ה",
         "the valuation of the male shall be five mithqals of silver, and the female three;"),
    ],
    7: [
        ("וְאִם מִבֶּן-שִׁשִּׁים שָׁנָה וָמַעְלָה אִם-זָכָר",
         "ואן כאן מן אבן סתין סנה פצאעדא",
         "and if it be from sixty years of age and upward,"),
        ("וְהָיָה עֶרְכְּךָ חֲמִשָּׁה עָשָׂר שָׁקֶל וְלַנְּקֵבָה עֲשָׂרָה שְׁקָלִים",
         "פקימה' אלד'כר כ'מסה' עשר מת'קאל. ואלאנת'א עשרה",
         "the valuation of the male shall be fifteen mithqals, and the female ten;"),
    ],
    8: [
        ("וְאִם-מָךְ הוּא מֵעֶרְכֶּךָ--וְהֶעֱמִידוֹ לִפְנֵי הַכֹּהֵן",
         "ואן כאן מהינא מן אלקימה. פליוקף בין ידי אלאמאם",
         "and if he be too lowly for the valuation, he shall stand before the imām,"),
        ("וְהֶעֱרִיךְ אֹתוֹ הַכֹּהֵן עַל-פִּי אֲשֶׁר תַּשִּׂיג יַד הַנֹּדֵר--יַעֲרִיכֶנּוּ הַכֹּהֵן",
         "ויקימה חסב מא תנאל יד אלנאד'ר. כד'אך יקימה אלאמאם",
         "and the imām shall value him according to what the hand of the one who vowed can reach — thus shall the imām value him."),
    ],
    9: [
        ("וְאִם-בְּהֵמָה--אֲשֶׁר יַקְרִיבוּ מִמֶּנָּה קָרְבָּן לַיהוָה",
         "ואן כאנת בהימה. יצלח אן יקרב מנהא קרבאנא ללה",
         "And if it be a beast from which an offering may be brought near to God,"),
        ("כֹּל אֲשֶׁר יִתֵּן מִמֶּנּוּ לַיהוָה יִהְיֶה-קֹּדֶשׁ",
         "פכל מא יגעל מן ד'אלך ללה יכון קדסא בעינה",
         "then everything they designate of it for God shall itself be sacred."),
    ],
    10: [
        ("לֹא יַחֲלִיפֶנּוּ וְלֹא-יָמִיר אֹתוֹ טוֹב בְּרָע--אוֹ-רַע בְּטוֹב",
         "לא יבדלה ולא יג'יירה. גייד ברדי ולא רדי בגייד",
         "He shall not exchange it nor substitute it — good for inferior, nor inferior for good;"),
        ("וְאִם-הָמֵר יָמִיר בְּהֵמָה בִּבְהֵמָה וְהָיָה-הוּא וּתְמוּרָתוֹ יִהְיֶה-קֹּדֶשׁ",
         "פאן ג'ייר בהימה בבהימה. פקד צאר הו ובדילה קדסא",
         "and if he does substitute one beast for another, then both it and its substitute shall become sacred."),
    ],
    11: [
        ("וְאִם כָּל-בְּהֵמָה טְמֵאָה אֲשֶׁר לֹא-יַקְרִיבוּ מִמֶּנָּה קָרְבָּן לַיהוָה",
         "ואן כאנת בהימה נגסה. או מא לא יקרב מנהא. קרבאנא ללה",
         "And if it be an impure beast, or one from which no offering may be brought near to God,"),
        ("וְהֶעֱמִיד אֶת-הַבְּהֵמָה לִפְנֵי הַכֹּהֵן",
         "פלתוקף בין ידי אלאמאם",
         "it shall be set before the imām;"),
    ],
    12: [
        ("וְהֶעֱרִיךְ הַכֹּהֵן אֹתָהּ בֵּין טוֹב וּבֵין רָע",
         "פיקימהא אלאמאם. עלי' קדר גודתהא או רדאתהא",
         "and the imām shall value it according to its quality, whether good or inferior —"),
        ("כְּעֶרְכְּךָ הַכֹּהֵן כֵּן יִהְיֶה",
         "פליכון אלואגב כמא קים אלאמאם",
         "as the imām values it, so shall it be obligatory."),
    ],
    13: [
        ("וְאִם-גָּאֹל יִגְאָלֶנָּה--וְיָסַף חֲמִישִׁתוֹ עַל-עֶרְכֶּךָ",
         "פאן שא פכאכהא. פליזיד עלי' אלקימה כמסהא",
         "And if he wishes to redeem it, he shall add a fifth of the valuation to it."),
    ],
    14: [
        ("וְאִישׁ כִּי-יַקְדִּשׁ אֶת-בֵּיתוֹ קֹדֶשׁ לַיהוָה",
         "ואי רגל אקדס ביתה קדסא ללה",
         "And whatever man consecrates his house as sacred to God,"),
        ("וְהֶעֱרִיכוֹ הַכֹּהֵן בֵּין טוֹב וּבֵין רָע כַּאֲשֶׁר יַעֲרִיךְ אֹתוֹ הַכֹּהֵן כֵּן יָקוּם",
         "פליקימה אלאמאם. עלי גודתה או רדאתה. כמא יקימה כד'אך יגב",
         "the imām shall value it according to its quality, whether good or inferior — as he values it, so shall it be obligatory."),
    ],
    15: [
        ("וְאִם-הַמַּקְדִּישׁ--יִגְאַל אֶת-בֵּיתוֹ",
         "פאן שא אלמקדס פכאך מנזלה",
         "And if the one who consecrated it wishes to redeem his dwelling,"),
        ("וְיָסַף חֲמִישִׁית כֶּסֶף-עֶרְכְּךָ עָלָיו--וְהָיָה לוֹ",
         "פליזיד עלי' קימתה כ'מסהא ויכון לה",
         "he shall add a fifth to its valuation, and it shall be his."),
    ],
    16: [
        ("וְאִם מִשְּׂדֵה אֲחֻזָּתוֹ יַקְדִּישׁ אִישׁ לַיהוָה",
         "ואן אקדס אנסאן ללה שייא מן צ'יעה' חוזה",
         "And if a person consecrates to God something from the fields of his holding,"),
        ("וְהָיָה עֶרְכְּךָ לְפִי זַרְעוֹ זֶרַע חֹמֶר שְׂעֹרִים בַּחֲמִשִּׁים שֶׁקֶל כָּסֶף",
         "פלתכון אלקימה עלי' קדר בד'רה. כל מבד'ר כור מן שעיר. בכ'מסין מתקאל פצ'ה",
         "the valuation shall be according to the measure of its seed — every unit sown of barley at fifty mithqals of silver."),
    ],
    17: [
        ("אִם-מִשְּׁנַת הַיֹּבֵל יַקְדִּישׁ שָׂדֵהוּ--כְּעֶרְכְּךָ יָקוּם",
         "פאן אקדס צ'יעתה מן סנה' אלאטלאק. פאלקימה ת'אבתה בחאלהא",
         "And if he consecrates his field from the year of release, the valuation shall remain fixed as it is."),
    ],
    18: [
        ("וְאִם-אַחַר הַיֹּבֵל יַקְדִּישׁ שָׂדֵהוּ",
         "ואן אקדסהא בעד סנה' אלאטלאק",
         "But if he consecrates it after the year of release,"),
        ("וְחִשַּׁב-לוֹ הַכֹּהֵן אֶת-הַכֶּסֶף עַל-פִּי הַשָּׁנִים הַנּוֹתָרֹת עַד שְׁנַת הַיֹּבֵל וְנִגְרַע מֵעֶרְכֶּךָ",
         "פליחסב לה אלאמאם אלדראהם. עלי' קדר אלסנין אלבאקיאת. אלי' סנה' אלאטלאק. וינקץ מן אלקימה",
         "the imām shall reckon for him the silver according to the number of years remaining until the year of release, and it shall be deducted from the full valuation."),
    ],
    19: [
        ("וְאִם-גָּאֹל יִגְאַל אֶת-הַשָּׂדֶה הַמַּקְדִּישׁ אֹתוֹ",
         "ואן שא אלרגל אלמקדס אלצ'יעה אן יפתכהא",
         "And if the man who consecrated the field wishes to redeem it,"),
        ("וְיָסַף חֲמִשִׁית כֶּסֶף-עֶרְכְּךָ עָלָיו--וְקָם לוֹ",
         "פליזיד עלי' אלקימה כ'מסהא. ותגב לה",
         "he shall add a fifth to the valuation, and it shall be secured to him."),
    ],
    20: [
        ("וְאִם-לֹא יִגְאַל אֶת-הַשָּׂדֶה וְאִם-מָכַר אֶת-הַשָּׂדֶה לְאִישׁ אַחֵר",
         "ואן לם יפתכהא. ובאעהא אלאמין לרגל אכ'ר",
         "But if he does not redeem it, and the trustee has sold it to another man,"),
        ("לֹא יִגָּאֵל עוֹד",
         "פלא תפתך אבדא",
         "it shall not be redeemed ever."),
    ],
    21: [
        ("וְהָיָה הַשָּׂדֶה בְּצֵאתוֹ בַיֹּבֵל קֹדֶשׁ לַיהוָה",
         "ותכון ענד כ'רוגהא. מן יד אלמשתרי פי סנה' אלאטלאק. קדסא ללה",
         "And it shall be, upon its passing out of the purchaser's hand in the year of release, sacred to God —"),
        ("כִּשְׂדֵה הַחֵרֶם לַכֹּהֵן תִּהְיֶה אֲחֻזָּתוֹ",
         "כצ'יאע אלצואפי. ותציר לאלאמאם",
         "like the lands of the endowments irrevocably devoted — and it shall become the imām's."),
    ],
    22: [
        ("וְאִם אֶת-שְׂדֵה מִקְנָתוֹ אֲשֶׁר לֹא מִשְּׂדֵה אֲחֻזָּתוֹ--יַקְדִּישׁ לַיהוָה",
         "ואן אקדס צ'יעה אשתראהא. וליסת לה בחוז",
         "And if a person consecrates a field he has purchased, which is not his by right of holding —"),
    ],
    23: [
        ("וְחִשַּׁב-לוֹ הַכֹּהֵן אֵת מִכְסַת הָעֶרְכְּךָ עַד שְׁנַת הַיֹּבֵל",
         "פליחסב לה אלאמאם תקסיט אלקימה. מן סנתה אלי' סנה' אלאטלאק",
         "the imām shall reckon for him the installments of the valuation from its year until the year of release,"),
        ("וְנָתַן אֶת-הָעֶרְכְּךָ בַּיּוֹם הַהוּא קֹדֶשׁ לַיהוָה",
         "וידפעהא פי ד'אלך אליום קדסא ללה",
         "and he shall pay it on that day as sacred to God."),
    ],
    24: [
        ("בִּשְׁנַת הַיּוֹבֵל יָשׁוּב הַשָּׂדֶה לַאֲשֶׁר קָנָהוּ מֵאִתּוֹ",
         "ותרגע אלצ'יעה פי סנה' אלאטלאק. לאלבאיע אלד'י אשתראהא מנה",
         "And the field shall revert in the year of release to the seller from whom he purchased it —"),
        ("לַאֲשֶׁר-לוֹ אֲחֻזַּת הָאָרֶץ",
         "אלד'י לה רקבה' אלארץ'",
         "to the one who holds title to the land."),
    ],
    25: [
        ("וְכָל-עֶרְכְּךָ--יִהְיֶה בְּשֶׁקֶל הַקֹּדֶשׁ",
         "וגמיע קימתך. תכון במת'קאל אלקדס",
         "And all your valuations shall be by the mithqal of the sanctuary —"),
        ("עֶשְׂרִים גֵּרָה יִהְיֶה הַשָּׁקֶל",
         "כל מת'קאל עשרין דאנק",
         "every mithqal being twenty dāniqs."),
    ],
    26: [
        ("אַךְ-בְּכוֹר אֲשֶׁר-יְבֻכַּר לַיהוָה בִּבְהֵמָה--לֹא-יַקְדִּישׁ אִישׁ אֹתוֹ",
         "אמא בכר. יבכר ללה מן אלבהאים. פלא יחתאג אן יקדסה אנסאנא",
         "As for a firstborn animal that is made firstborn to God from among the beasts, a person need not consecrate it:"),
        ("אִם-שׁוֹר אִם-שֶׂה לַיהוָה הוּא",
         "אן כאן מן אלבקר או מן אלג'נם. פהו ללה",
         "whether it be from the cattle or from the flock, it already belongs to God."),
    ],
    27: [
        ("וְאִם בַּבְּהֵמָה הַטְּמֵאָה וּפָדָה בְעֶרְכֶּךָ וְיָסַף חֲמִשִׁתוֹ עָלָיו",
         "ואן אקדס שייא מן אלבהאים אלנגסה. פליפדהא בקימתה. ויזיד עליהא כ'מסהא",
         "And if one consecrates something from the impure beasts, he shall redeem it at its valuation and add a fifth to it;"),
        ("וְאִם-לֹא יִגָּאֵל וְנִמְכַּר בְּעֶרְכֶּךָ",
         "ואן לם יפתכה פליבאע בקימתה",
         "and if he does not redeem it, it shall be sold at its valuation."),
    ],
    28: [
        ("אַךְ-כָּל-חֵרֶם אֲשֶׁר יַחֲרִם אִישׁ לַיהוָה מִכָּל-אֲשֶׁר-לוֹ מֵאָדָם וּבְהֵמָה וּמִשְּׂדֵה אֲחֻזָּתוֹ",
         "ואמא כל צואף. יגעלה אלאנסאן ללה מן גמיע מאלה. מן עביד ובהאים וצ'יעה' חוזה",
         "But every irrevocable devotion that a person makes to God from all that he has — whether slaves, or beasts, or the fields of his holding —"),
        ("לֹא יִמָּכֵר וְלֹא יִגָּאֵל כָּל-חֵרֶם קֹדֶשׁ-קָדָשִׁים הוּא לַיהוָה",
         "פלא יבאע ולא יפתך. בל יכון מן כ'ואץ אלאקדאס ללה",
         "shall not be sold and shall not be redeemed; it shall be of the most sacred consecrations to God."),
    ],
    29: [
        ("כָּל-חֵרֶם אֲשֶׁר יָחֳרַם מִן-הָאָדָם--לֹא יִפָּדֶה מוֹת יוּמָת",
         "וכל מתלוף אסתחק אלתלף. מן אלנאס פלא יפדא. בל יקתל קתלא",
         "And every person condemned to destruction who has deserved destruction shall not be redeemed — he shall be put to death."),
    ],
    30: [
        ("וְכָל-מַעְשַׂר הָאָרֶץ מִזֶּרַע הָאָרֶץ מִפְּרִי הָעֵץ",
         "וגמיע עשור אלארץ'. מן חבהא ומן ת'מר אלשגר",
         "And all the tithes of the land — from its grain and from the fruit of the tree —"),
        ("לַיהוָה הוּא קֹדֶשׁ לַיהוָה",
         "פהו ללה קדסא",
         "they belong to God as sacred."),
    ],
    31: [
        ("וְאִם-גָּאֹל יִגְאַל אִישׁ מִמַּעַשְׂרוֹ--חֲמִשִׁיתוֹ יֹסֵף עָלָיו",
         "פאן אפתך אנסאן שייא מן עשורה. פליזיד עליה כ'מס ת'מנה",
         "And if a person redeems any of his tithe, he shall add a fifth of its value to it."),
    ],
    32: [
        ("וְכָל-מַעְשַׂר בָּקָר וָצֹאן כֹּל אֲשֶׁר-יַעֲבֹר תַּחַת הַשָּׁבֶט",
         "וגמיע עשור אלבקר ואלג'נם. מא יגוז תחת אלעצא",
         "And all the tithes of cattle and of the flock — whatever passes under the staff —"),
        ("הָעֲשִׂירִי יִהְיֶה-קֹּדֶשׁ לַיהוָה",
         "פאלעאשר יכון קדסא ללה",
         "the tenth shall be sacred to God."),
    ],
    33: [
        ("לֹא יְבַקֵּר בֵּין-טוֹב לָרַע וְלֹא יְמִירֶנּוּ",
         "לא יפחץ ענה. בין גייד לרדי ולא יג'יירה",
         "He shall not examine it as between good and inferior, nor shall he substitute it;"),
        ("וְאִם-הָמֵר יְמִירֶנּוּ וְהָיָה-הוּא וּתְמוּרָתוֹ יִהְיֶה-קֹּדֶשׁ לֹא יִגָּאֵל",
         "פאן ג'יירה פקד צאר הו ובדילה. קדסא לא יפתך",
         "and if he does substitute it, then both it and its substitute shall become sacred and shall not be redeemed."),
    ],
    34: [
        ("אֵלֶּה הַמִּצְו‍ֹת אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה--אֶל-בְּנֵי יִשְׂרָאֵל בְּהַר סִינָי",
         "הד'ה אלוצאיא. אלתי אמר אללה בהא מוסי. אלי' בני אסראיל פי גבל סיני",
         "These are the commandments which God charged Moses with, to the sons of Israel at Mount Sinai."),
    ],
}
