"""Hand-authored alignment triples for Vayikra chapter 20.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("וְאֶל-בְּנֵי", "ומר בני", "Command the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("תֹּאמַר", "וקל", "and say"),
        (None, "להם", "to them"),
        (None, "אי", "Any"),
        ("אִישׁ", "אנסאן", "person"),
        ("מִבְּנֵי", "מן בני", "from the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וּמִן-הַגֵּר", "ומן אלג'ריב", "or from the stranger"),
        ("הַגָּר", "אלדכ'יל", "who has entered"),
        ("בְּיִשְׂרָאֵל", "פי מא בינהם", "among them"),
        ("אֲשֶׁר יִתֵּן", "יעטי", "who gives"),
        ("מִזַּרְעוֹ", "מן נסלה", "of his offspring"),
        ("לַמֹּלֶךְ", "לאלצנם", "to the idols"),
        ("מוֹת יוּמָת", "פליקתל קתלא", "let him be killed outright"),
        (None, "והו", "that is"),
        (None, "אן", "that"),
        ("עַם הָאָרֶץ", "ירגמוה אהל אלבלד", "the people of the town shall stone him"),
        (None, "באלחגארה", "with stones"),
    ],
    3: [
        ("וַאֲנִי", "ואנא", "And I"),
        ("אֶתֵּן", "אחל", "shall pour out"),
        ("אֶת-פָּנַי", "ג'צ'בי", "My wrath"),
        ("בָּאִישׁ הַהוּא", "בד'אלך אלאנסאן", "upon that person"),
        ("וְהִכְרַתִּי", "פאקטעה", "and cut him off"),
        ("מִקֶּרֶב עַמּוֹ", "מן בין קומה", "from among his people"),
        ("כִּי", "אד'", "since"),
        ("מִזַּרְעוֹ", "אעטא מן נסלה", "he gave of his offspring"),
        ("לַמֹּלֶךְ", "לאלצנם", "to the idols"),
        ("לְמַעַן", "לכי", "in order to"),
        ("טַמֵּא", "ינגס", "defile"),
        ("אֶת-מִקְדָּשִׁי", "מקדסי", "My sanctuary"),
        ("וּלְחַלֵּל", "ויבד'ל", "and to debase"),
        ("אֶת-שֵׁם", "אסמי", "My"),
        ("קָדְשִׁי", "אלמקדס", "holy name"),
    ],
    4: [
        ("וְאִם", "ואן", "And if"),
        ("הַעְלֵם יַעְלִימוּ", "תג'אפל", "should turn a blind eye"),
        ("עַם הָאָרֶץ", "אהל אלבלד", "the people of the town"),
        (None, "תג'אפלא", "looking away"),
        ("מִן-הָאִישׁ הַהוּא", "ען ד'אלך אלרגל", "from that man"),
        ("בְּתִתּוֹ", "מע אעטאיה", "even as he gives"),
        ("מִזַּרְעוֹ", "מן נסלה", "of his offspring"),
        ("לַמֹּלֶךְ", "לאלצנם", "to the idols"),
        ("לְבִלְתִּי הָמִית אֹתוֹ", "ולם יקת'לוה", "and they do not kill him"),
    ],
    5: [
        ("וְשַׂמְתִּי אֲנִי", "אחללת אנא", "I shall pour out"),
        ("אֶת-פָּנַי", "ג'צ'בי", "My wrath"),
        ("בָּאִישׁ הַהוּא", "בד'אלך אלאנסאן", "upon that person"),
        ("וּבְמִשְׁפַּחְתּוֹ", "ובמגאנסיה", "and upon those who are associated with him"),
        ("וְהִכְרַתִּי אֹתוֹ", "וקטעתה", "and cut him off"),
        ("וְאֵת כָּל-הַזֹּנִים", "וגמיע אלטאג'יון", "and all those who rebelliously follow"),
        ("אַחֲרָיו", "תבעה", "after him"),
        ("לִזְנוֹת", "ורא", "after"),
        ("אַחֲרֵי הַמֹּלֶךְ", "אלצנם", "the idol"),
        ("מִקֶּרֶב עַמָּם", "מן בין קומהם", "from among their people"),
    ],
    6: [
        ("וְהַנֶּפֶשׁ אֲשֶׁר", "ואי אנסאן", "And any person who"),
        ("תִּפְנֶה", "ולא", "has turned"),
        ("אֶל-הָאֹבֹת", "אלי' אלמשעוד'ין", "to sorcerers"),
        ("וְאֶל-הַיִּדְּעֹנִים", "ואלעראפין", "and diviners"),
        ("לִזְנֹת", "ליטג'י", "to lead"),
        (None, "אלנאס", "the people"),
        ("אַחֲרֵיהֶם", "פי תבעהם", "astray in following them"),
        ("וְנָתַתִּי", "אחללת", "I shall pour out"),
        ("אֶת-פָּנַי", "ג'צ'בי", "My wrath"),
        ("בַּנֶּפֶשׁ הַהִוא", "בד'אלך אלאנסאן", "upon that person"),
        ("וְהִכְרַתִּי אֹתוֹ", "וקטעתה", "and cut him off"),
        ("מִקֶּרֶב עַמּוֹ", "מן בין קומה", "from among his people"),
    ],
    7: [
        ("וְהִתְקַדִּשְׁתֶּם", "פתקדסו", "So sanctify yourselves"),
        ("וִהְיִיתֶם", "וכונו", "and be"),
        ("קְדֹשִׁים", "מקדסין", "holy"),
        ("כִּי", "לאני", "for I am"),
        ("אֲנִי", "אללה", "God"),
        ("יְהוָה", "רבכם", "your Lord"),
        ("אֱלֹהֵיכֶם", "אלקדוס", "the Holy One"),
    ],
    8: [
        ("וּשְׁמַרְתֶּם", "ואחפצ'ו", "And keep"),
        ("אֶת-חֻקֹּתַי", "רסומי", "My statutes"),
        ("וַעֲשִׂיתֶם", "ואעמלו", "and act"),
        ("אֹתָם", "בהא", "according to them"),
        ("אֲנִי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("מְקַדִּשְׁכֶם", "מקדסכם", "who sanctifies you"),
    ],
    9: [
        (None, "אי", "Any"),
        ("אִישׁ אִישׁ", "אנסאן", "person"),
        ("אֲשֶׁר יְקַלֵּל", "לען", "who has cursed"),
        ("אֶת-אָבִיו", "אביה", "his father"),
        ("וְאֶת-אִמּוֹ", "ואמה", "and his mother"),
        ("מוֹת יוּמָת", "פליקתל קתלא", "let him be killed outright"),
        ("אָבִיו", "למא לען אביה", "since he cursed his father"),
        ("וְאִמּוֹ קִלֵּל", "ואמה", "and his mother"),
        ("דָּמָיו בּוֹ", "פקד חל דמה", "his blood is thereby made forfeit"),
    ],
    10: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִנְאַף", "זנא", "who committed adultery"),
        ("אֶת-אֵשֶׁת", "בזוגה'", "with a man's wife"),
        ("אִישׁ", "רגל", "or committed adultery"),
        ("אֲשֶׁר יִנְאַף אֶת-אֵשֶׁת רֵעֵהוּ", "או זנא באמראה' צאחבה", "with the wife of his fellow"),
        ("מוֹת-יוּמַת הַנֹּאֵף", "פליקתל אלזאן", "let the adulterer"),
        ("וְהַנֹּאָפֶת", "ואלזאניה קתלא", "and the adulteress be killed outright"),
    ],
    11: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִשְׁכַּב", "צ'אגע", "who lay"),
        ("אֵשֶׁת אָבִיו", "זוגה' אביה", "with his father's wife"),
        ("עֶרְוַת", "פקד כשף", "has thereby uncovered"),
        ("אָבִיו גִּלָּה", "סווה' אביה", "his father's nakedness"),
        ("מוֹת-יוּמְתוּ", "פליקתלא גמיעא", "let them both be killed"),
        ("דְּמֵיהֶם בָּם", "פקד חלת דמאהמא בד'אלך", "for their blood is made forfeit by this"),
    ],
    12: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רג'ל", "man"),
        ("אֲשֶׁר יִשְׁכַּב", "צ'אגע", "who lay"),
        ("אֶת-כַּלָּתוֹ", "כנתה", "with his daughter-in-law"),
        ("מוֹת יוּמְתוּ", "פליקתלא גמיעא", "let them both be killed"),
        ("תֶּבֶל עָשׂוּ", "ולמא צנעא דאהיה", "since they did an outrageous thing"),
        ("דְּמֵיהֶם בָּם", "פקד חל דמאהמא", "their blood is thereby made forfeit"),
    ],
    13: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רג'ל", "man"),
        ("אֲשֶׁר יִשְׁכַּב", "צ'אגע", "who lay"),
        ("אֶת-זָכָר", "ד'כרא", "with a male"),
        ("מִשְׁכְּבֵי", "עלי' פן מצאגעה'", "in the manner of lying"),
        ("אִשָּׁה", "אלנסא", "with women"),
        ("תּוֹעֵבָה עָשׂוּ", "פקד צנעא גמיעא כריהה", "they have both together done an abomination"),
        ("מוֹת יוּמָתוּ", "פליקתלא קתלא", "let them be killed outright"),
        ("דְּמֵיהֶם בָּם", "פקד חל דמאהמא", "for their blood is made forfeit"),
    ],
    14: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִקַּח", "אתכ'ד'", "who took"),
        ("אֶת-אִשָּׁה", "אמראה", "a woman"),
        ("וְאֶת-אִמָּהּ", "ואמהא", "and her mother"),
        ("זִמָּה הִוא", "פתלך פאחשה", "that is a vile act"),
        ("בָּאֵשׁ יִשְׂרְפוּ", "פליחרק באלנאר", "be burned with fire"),
        ("אֹתוֹ", "הו", "let him"),
        ("וְאֶתְהֶן", "והן", "and them both"),
        (None, "עלי' אלבדל", "on account of the degradation"),
        ("וְלֹא-תִהְיֶה", "ולא תכון", "and there shall be no"),
        ("זִמָּה", "פאחשה", "vile act"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
    ],
    15: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִתֵּן", "געל", "who directed"),
        ("שְׁכָבְתּוֹ", "מצ'אגעתה", "his lying"),
        ("בִּבְהֵמָה", "מע בהימה", "with a beast"),
        ("מוֹת יוּמָת", "פליקתל קתלא", "let him be killed outright"),
        ("וְאֶת-הַבְּהֵמָה", "ואלבהימה", "and the beast"),
        (None, "איצ'א", "also"),
        ("תַּהֲרֹגוּ", "פאקתלוהא", "kill it"),
    ],
    16: [
        (None, "ואייה'", "And any"),
        ("וְאִשָּׁה", "אמראה", "woman"),
        ("אֲשֶׁר תִּקְרַב", "תקדמת", "who approached"),
        ("אֶל-כָּל-בְּהֵמָה", "אלי' בהימה", "a beast"),
        ("לְרִבְעָה אֹתָהּ", "לתנזוהא", "to be mounted by it"),
        ("וְהָרַגְתָּ", "פאקתל", "kill"),
        ("אֶת-הָאִשָּׁה", "אלאמראה", "the woman"),
        ("וְאֶת-הַבְּהֵמָה", "ואלבהימה", "and the beast"),
        ("מוֹת יוּמָתוּ", "למא צנעא דאהיה", "since they did an outrageous thing"),
        ("דְּמֵיהֶם בָּם", "פקד חל דמאהמא בד'אלך", "their blood is thereby made forfeit"),
    ],
    17: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר-יִקַּח", "אתכ'ד'", "who took"),
        ("אֶת-אֲחֹתוֹ", "אכ'תה", "his sister"),
        ("בַּת-אָבִיו", "אבנה' אביה", "the daughter of his father"),
        ("אוֹ", "או", "or"),
        ("בַת-אִמּוֹ", "אבנה' אמה", "the daughter of his mother"),
        ("וְרָאָה", "פנצ'ר", "and looked"),
        ("אֶת-עֶרְוָתָהּ", "אלי' סוותהא", "upon her nakedness"),
        ("וְהִיא-תִרְאֶה", "ונצ'רת", "and she looked"),
        ("אֶת-עֶרְוָתוֹ", "אלי' כסוותה", "upon his nakedness"),
        ("חֶסֶד הוּא", "פד'אלך עאר", "that is a disgrace"),
        ("וְנִכְרְתוּ", "פינקטעאן", "they shall both be cut off"),
        ("לְעֵינֵי בְּנֵי עַמָּם", "מן חצ'רה' קומהם", "from the presence of their people"),
        ("עֶרְוַת אֲחֹתוֹ גִּלָּה", "למא כשף סווה' אכ'תה", "since he uncovered the nakedness of his sister"),
        ("עֲו‍ֹנוֹ יִשָּׂא", "פקד חמל וזרה", "he has borne his guilt"),
    ],
    18: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר-יִשְׁכַּב", "צ'אגע", "who lay"),
        ("אֶת-אִשָּׁה דָּוָה", "אמראה חאיץ'", "with a menstruating woman"),
        ("וְגִלָּה", "פכשף", "uncovering"),
        ("אֶת-עֶרְוָתָהּ", "סוותהא", "her nakedness"),
        ("אֶת-מְקֹרָהּ הֶעֱרָה", "וערא נביעהא", "and laying bare her spring"),
        ("וְהִוא גִּלְּתָה", "והי איצ'א כשפת", "and she too uncovered"),
        ("אֶת-מְקוֹר דָּמֶיהָ", "נביע דמהא", "the spring of her blood"),
        ("וְנִכְרְתוּ", "פינקטעאן גמיעא", "they shall both be cut off"),
        ("מִקֶּרֶב עַמָּם", "מן בין קומהם", "from among their people"),
    ],
    19: [
        ("וְעֶרְוַת", "וסווה'", "The nakedness of"),
        ("אֲחוֹת אִמְּךָ", "כ'אלתך", "your maternal aunt"),
        ("וַאֲחוֹת אָבִיךָ", "ועמתך", "and your paternal aunt"),
        ("לֹא תְגַלֵּה", "לא תכשף", "you shall not uncover"),
        ("כִּי", "פאן", "for"),
        (None, "מן", "whoever"),
        ("אֶת-שְׁאֵרוֹ", "ערא נסיבה", "bares his kinswoman"),
        ("הֶעֱרָה", "פקד", "has thereby"),
        ("עֲו‍ֹנָם יִשָּׂאוּ", "חמל וזרה", "borne his guilt"),
    ],
    20: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִשְׁכַּב", "צ'אגע", "who lay"),
        ("אֶת-דֹּדָתוֹ", "זוגה' עמה", "with the wife of his paternal uncle"),
        ("עֶרְוַת דֹּדוֹ גִּלָּה", "פקד כשף סווה' עמה", "has thereby uncovered his uncle's nakedness"),
        ("חֶטְאָם יִשָּׂאוּ", "וממא חמלא וזרהמא", "and because they bore their guilt"),
        ("עֲרִירִים יָמֻתוּ", "ימותאן עקימאן", "they shall die childless"),
    ],
    21: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אֲשֶׁר יִקַּח", "אתכ'ד'", "who took"),
        ("אֶת-אֵשֶׁת אָחִיו", "זוגה' אכ'יה", "the wife of his brother"),
        ("נִדָּה הִוא", "אלתי הי מבעדה מנה", "she who has been separated from him"),
        ("עֶרְוַת אָחִיו גִּלָּה", "פלמא כשף סווה' אכ'יה", "since he uncovered his brother's nakedness"),
        ("עֲרִירִים יִהְיוּ", "יכונאן עקימאן", "they shall both be childless"),
    ],
    22: [
        ("וּשְׁמַרְתֶּם", "ואחפצו", "And keep"),
        ("אֶת-כָּל-חֻקֹּתַי", "גמיע רסומי", "all My statutes"),
        ("וְאֶת-כָּל-מִשְׁפָּטַי", "ואחכאמי", "and My ordinances"),
        ("וַעֲשִׂיתֶם", "ואעמלו", "and act"),
        ("אֹתָם", "בהא", "according to them"),
        ("וְלֹא-תָקִיא", "ולא ישתתכם", "and do not let the land scatter you"),
        ("הָאָרֶץ", "אלבלד", "the land"),
        ("אֲשֶׁר", "אלד'י", "into which"),
        ("אֲנִי מֵבִיא", "אנא מדכ'לכם", "I am bringing you"),
        ("אֶתְכֶם שָׁמָּה", "הנאך", "there"),
        ("לָשֶׁבֶת בָּהּ", "לתחוזוה", "to possess it"),
    ],
    23: [
        ("וְלֹא תֵלְכוּ", "ולא תסירו", "And do not walk"),
        ("בְּחֻקֹּת", "פי רסום", "in the statutes of"),
        ("הַגּוֹי", "אלאמם", "the nations"),
        ("אֲשֶׁר-אֲנִי", "אלד'י אנא", "whom I am"),
        ("מְשַׁלֵּחַ", "טארדהם", "driving out"),
        ("מִפְּנֵיכֶם", "מן בין ידיכם", "before you"),
        ("כִּי", "פאנהם", "for"),
        (None, "למא", "since"),
        ("אֶת-כָּל-אֵלֶּה עָשׂוּ", "צנעו גמיע הד'ה", "they did all these things"),
        ("וָאָקֻץ בָּם", "אקליתהם", "I have come to loathe them"),
    ],
    24: [
        ("וָאֹמַר", "וקלת", "And I said"),
        ("לָכֶם", "לכם", "to you"),
        (None, "חאכמא", "decreeing"),
        ("אַתֶּם", "אנתם", "You"),
        ("תִּירְשׁוּ", "תחוזון", "shall possess"),
        ("אֶת-אַדְמָתָם", "בלדהם", "their land"),
        ("וַאֲנִי", "ואנא", "and I"),
        ("אֶתְּנֶנָּה", "אעטיה", "shall give it"),
        ("לָכֶם", "לכם", "to you"),
        ("לָרֶשֶׁת אֹתָהּ", "תחוזוה", "to possess"),
        ("אֶרֶץ זָבַת", "בלד יפיץ'", "a land flowing with"),
        ("חָלָב", "אללבן", "milk"),
        ("וּדְבָשׁ", "ואלעסל", "and honey"),
        (None, "לאני", "for I am"),
        ("אֲנִי", "אללה", "God"),
        ("יְהוָה אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלד'י", "who"),
        ("אֲשֶׁר-הִבְדַּלְתִּי", "אפרזתכם", "has separated you"),
        ("מִן-הָעַמִּים", "מן גמיע אלאמם", "from all the nations"),
    ],
    25: [
        ("וְהִבְדַּלְתֶּם", "פמייזו", "So distinguish"),
        ("בֵּין-הַבְּהֵמָה הַטְּהֹרָה", "אלבהימה אלטאהרה", "between the clean beast"),
        ("לַטְּמֵאָה", "מן אלנגסה", "and the unclean"),
        ("וּבֵין-הָעוֹף הַטָּמֵא", "ואלטאיר אלנגס", "and between the unclean bird"),
        ("לַטָּהֹר", "מן אלטאהר", "and the clean"),
        ("וְלֹא-תְשַׁקְּצוּ", "ולא תרגסו", "and do not make yourselves loathsome"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "with"),
        ("בַּבְּהֵמָה", "באלבהאים", "beasts"),
        ("וּבָעוֹף", "ואלטיור", "and birds"),
        ("וּבְכֹל אֲשֶׁר תִּרְמֹשׂ", "וסאיר מא ידב", "and the rest of what creeps"),
        ("הָאֲדָמָה", "עלי' אלארץ'", "upon the earth"),
        ("אֲשֶׁר-הִבְדַּלְתִּי", "אלד'י אפרזתה", "which I have set apart"),
        ("לָכֶם", "לכם", "for you"),
        ("לְטַמֵּא", "לאלתנגיס", "as unclean"),
    ],
    26: [
        ("וִהְיִיתֶם", "וכונו", "And be"),
        ("לִי", "לי", "unto Me"),
        ("קְדֹשִׁים", "מקדסין", "holy"),
        ("כִּי", "לאני", "for I am"),
        ("יְהוָה", "אללה", "God"),
        ("קָדוֹשׁ אֲנִי", "אלקדוס", "the Holy One"),
        ("וָאַבְדִּל אֶתְכֶם", "אפרזתכם", "I have separated you"),
        ("מִן-הָעַמִּים", "מן אלאמם", "from the nations"),
        ("לִהְיוֹת", "לתכונו", "that you may be"),
        ("לִי", "לי", "Mine"),
        (None, "כ'אצה", "as a special possession"),
    ],
    27: [
        (None, "ואי", "And any"),
        ("אִישׁ", "רגל", "man"),
        ("אוֹ-אִשָּׁה", "או אמראה", "or woman"),
        ("כִּי-יִהְיֶה בָהֶם", "כאן מנהמא", "in whom there is"),
        ("אוֹב", "משעודא", "a sorcerer"),
        ("אוֹ יִדְּעֹנִי", "או עראפא", "or a diviner"),
        ("מוֹת יוּמָתוּ", "פליקתלא קתלא", "let them both be killed outright"),
        ("בָּאֶבֶן יִרְגְּמוּ אֹתָם", "ובאלחגארה ירגמוהמא", "they shall be stoned with stones"),
        ("דְּמֵיהֶם בָּם", "פקד חלת דמאהמא", "their blood is thereby made forfeit"),
    ],
}
