"""Hand-authored alignment triples for Vayikra chapter 13.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("וְאֶל-אַהֲרֹן", "והרון", "and Aaron"),
        ("לֵאמֹר", "תכלימא", "directly"),
    ],
    2: [
        (None, "אי", "Any"),
        ("אָדָם", "אנסאן", "person"),
        (None, "כאן", "in whose"),
        ("בְעוֹר-בְּשָׂרוֹ", "פי גלד בדנה", "skin of his body"),
        ("שְׂאֵת", "שאמה", "there was a mark"),
        ("אוֹ-סַפַּחַת", "או עארצ'ה", "or a blemish"),
        ("אוֹ בַהֶרֶת", "או בקעה", "or a spot"),
        ("וְהָיָה", "או צאר", "or there appeared"),
        ("בְעוֹר-בְּשָׂרוֹ", "פי גלד בדנה", "in the skin of his body"),
        ("לְנֶגַע צָרָעַת", "בלא ברץ", "an affliction of leprosy"),
        ("וְהוּבָא", "פליותא", "he shall be brought"),
        (None, "בה", "to"),
        ("אֶל-אַהֲרֹן", "אלי' הרון", "Aaron"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("אוֹ אֶל-אַחַד", "או אלי' אחד", "or to one of"),
        ("מִבָּנָיו", "מן בניה", "his sons"),
        ("הַכֹּהֲנִים", "אלאימה", "the imāms"),
    ],
    3: [
        ("וְרָאָה הַכֹּהֵן", "פינצ'ר אלאמאם", "And the imām shall inspect"),
        ("אֶת-הַנֶּגַע", "אלבלא", "the affliction"),
        ("בְּעוֹר-הַבָּשָׂר", "פי גלד אלבדן", "in the skin of the body"),
        (None, "פאן", "if"),
        (None, "כאן", "there is"),
        (None, "פיה", "in it"),
        ("וְשֵׂעָר", "שער", "hair"),
        ("הָפַךְ", "קד אנקלב", "that has turned"),
        ("לָבָן", "אביצ'א", "white"),
        ("וּמַרְאֵה", "ומנצ'ר", "and the appearance of"),
        ("הַנֶּגַע", "אלבלא", "the affliction"),
        ("עָמֹק", "עמיק", "is deep"),
        ("מֵעוֹר בְּשָׂרוֹ", "מן גלד בדנה", "from the skin of his body"),
        ("נֶגַע צָרַעַת", "בלא ברץ", "it is an affliction of leprosy"),
        ("הוּא", "פהו", "and when it is seen thus"),
        ("וְרָאָהוּ הַכֹּהֵן", "פאד'י ראה כד'אך", "he shall declare him"),
        ("וְטִמֵּא אֹתוֹ", "פלינגסה", "impure"),
    ],
    4: [
        ("וְאִם", "ואן", "But if"),
        ("בַּהֶרֶת", "בקעה", "the spot"),
        ("לְבָנָה", "ביצ'א", "white"),
        ("הִוא בְּעוֹר בְּשָׂרוֹ", "פי גלד בדנה", "in the skin of his body"),
        ("וְעָמֹק אֵין-מַרְאֶהָ מִן-הָעוֹר", "וליס ומנצ'רהא עמיק מן אלגלד", "and its appearance is not deep from the skin"),
        ("וּשְׂעָרָה", "ושערהא", "and its hair"),
        ("לֹא-הָפַךְ", "לם ינקלב", "has not turned"),
        ("לָבָן", "אביצ'א", "white"),
        ("וְהִסְגִּיר הַכֹּהֵן", "פליוקפה", "he shall confine him"),
        ("שִׁבְעַת", "סבעה'", "for seven"),
        ("יָמִים", "איאם", "days"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        ("וְרָאָהוּ הַכֹּהֵן", "ינצ'רה", "he shall inspect him"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        (None, "פאן", "if"),
        ("הַנֶּגַע", "וקף אלבלא", "the affliction has stood"),
        ("עָמַד בְּעֵינָיו", "בעינה", "as it was"),
        ("לֹא-פָשָׂה הַנֶּגַע בָּעוֹר", "ולם יתפש פי אלגלד", "and has not spread in the skin"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן", "פליוקפה", "he shall confine him"),
        ("שִׁבְעַת יָמִים שֵׁנִית", "סבעה' איאם ת'אניה", "for a second seven days"),
    ],
    6: [
        (None, "ת'ם", "Then"),
        ("וְרָאָה הַכֹּהֵן אֹתוֹ", "ינצ'רה", "he shall inspect him"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        ("שֵׁנִית", "ת'אניה", "a second time"),
        (None, "פאן", "if"),
        ("כֵּהָה הַנֶּגַע", "כבא", "it has dimmed"),
        ("וְלֹא-פָשָׂה הַנֶּגַע בָּעוֹר", "ולם יתפש פי אלגלד", "and has not spread in the skin"),
        ("וְטִהֲרוֹ הַכֹּהֵן", "פליטהרה", "he shall declare him pure"),
        ("מִסְפַּחַת הִוא", "פאנהא עארצ'ה", "for it is a blemish"),
        ("וְכִבֶּס", "ויג'סל", "and he shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְטָהֵר", "ויטהר", "and be pure"),
    ],
    7: [
        ("וְאִם-פָּשֹׂה תִפְשֶׂה הַמִּסְפַּחַת", "ואן תפשת אלעארצ'ה", "But if the blemish spreads"),
        ("בָּעוֹר", "פי אלגלד", "in the skin"),
        ("אַחֲרֵי הֵרָאֹתוֹ", "בעד מא אורי'", "after he was shown"),
        ("אֶל-הַכֹּהֵן", "לאלאמאם", "to the imām"),
        ("לְטָהֳרָתוֹ", "פטהרה", "and he declared him pure"),
        ("וְנִרְאָה", "פליורא", "he shall be shown"),
        (None, "לה", "to him"),
        ("שֵׁנִית", "ת'אניה", "a second time"),
    ],
    8: [
        (None, "פאד'א", "And if"),
        ("וְרָאָה הַכֹּהֵן", "ראהא אלאמאם", "the imām sees"),
        ("וְהִנֵּה פָּשְׂתָה הַמִּסְפַּחַת בָּעוֹר", "קד תפשת פי גלדה", "that it has spread in his skin"),
        ("וְטִמְּאוֹ הַכֹּהֵן", "פלינגסה", "he shall declare him impure"),
        ("צָרַעַת הִוא", "פאנהא ברץ", "for it is leprosy"),
    ],
    9: [
        (None, "פאד'א", "If"),
        ("נֶגַע צָרַעַת", "כאן באנסאן בלא ברץ", "there is on a person an affliction of leprosy"),
        ("כִּי תִהְיֶה בְּאָדָם", "פיותא", "he shall be brought"),
        ("וְהוּבָא", "בה", "to"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "the imām"),
    ],
    10: [
        ("וְרָאָה הַכֹּהֵן", "פינצר אלאמאם", "And the imām shall inspect"),
        (None, "פאד'א", "and behold, if"),
        ("וְהִנֵּה שְׂאֵת-לְבָנָה בָּעוֹר", "בשאמה ביצ'א פי גלדה", "there is a white mark in his skin"),
        ("וְהִיא הָפְכָה שֵׂעָר לָבָן", "וקד אקלבת אלשער אביצ'א", "and the hair has turned white"),
        ("וּמִחְיַת בָּשָׂר חַי בַּשְׂאֵת", "או גז מן אללחם נקי פי אלשאמה", "or there is a portion of raw flesh in the mark"),
    ],
    11: [
        ("צָרַעַת נוֹשֶׁנֶת", "ברץ עתיק", "it is an old leprosy"),
        ("הִוא", "הו", "in"),
        ("בְּעוֹר בְּשָׂרוֹ", "פי גלד בדנה", "the skin of his body"),
        ("וְטִמְּאוֹ הַכֹּהֵן", "פלינגסה אלאמאם", "the imām shall declare him impure"),
        ("לֹא יַסְגִּרֶנּוּ", "ולא יוקפה", "and shall not confine him"),
        ("כִּי טָמֵא הוּא", "אד' הו נגס", "since he is impure"),
    ],
    12: [
        ("וְאִם-פָּרוֹחַ תִּפְרַח הַצָּרַעַת בָּעוֹר", "ואן אנתשר אלברץ פי אלבדן", "And if the leprosy spreads throughout the body"),
        ("וְכִסְּתָה הַצָּרַעַת", "חתי' ג'טא", "until it covers"),
        ("אֵת כָּל-עוֹר הַנֶּגַע", "גמיע גלד אלמבתלא", "all the skin of the afflicted one"),
        ("מֵרֹאשׁוֹ", "מן ראסה", "from his head"),
        ("וְעַד-רַגְלָיו", "אלי' רגליה", "to his feet"),
        ("לְכָל-מַרְאֵה עֵינֵי הַכֹּהֵן", "גמיע מנצ'ר עיני אלאמאם", "entirely within the sight of the imām's eyes"),
    ],
    13: [
        ("וְרָאָה הַכֹּהֵן", "פ לינצ'ר אלאמאם", "the imām shall inspect"),
        (None, "פאד'א", "and if"),
        ("כִסְּתָה הַצָּרַעַת", "קד ג'טא אלברץ", "the leprosy has covered"),
        ("אֶת-כָּל-בְּשָׂרוֹ", "גמיע בדנה", "all his body"),
        ("וְטִהַר אֶת-הַנָּגַע", "פליטהרה", "he shall declare him pure"),
        ("כֻּלּוֹ הָפַךְ לָבָן", "אד' קד אנקלב כלה אביצ'א", "since it has all turned white"),
        ("טָהוֹר הוּא", "פהו טאהר", "he is pure"),
    ],
    14: [
        ("וּבְיוֹם", "ואי יום", "But on whatever day"),
        ("הֵרָאוֹת", "צ'הר", "appears"),
        ("בּוֹ", "פיה", "in him"),
        ("בָּשָׂר חַי", "לחם נקי", "raw flesh"),
        ("יִטְמָא", "פלינגסה", "he shall declare him impure"),
    ],
    15: [
        (None, "באן", "For when"),
        ("וְרָאָה הַכֹּהֵן", "ירא אלאמאם", "the imām sees"),
        ("אֶת-הַבָּשָׂר הַחַי", "אללחם אלנקי", "the raw flesh"),
        ("וְטִמְּאוֹ", "פינגסה", "he shall declare him impure"),
        ("הַבָּשָׂר הַחַי", "לאן גז מן אללחם אלנקי", "for a portion of raw flesh"),
        (None, "מע", "together with"),
        ("טָמֵא הוּא", "אלברץ נגס הו", "the leprosy is impure"),
    ],
    16: [
        ("אוֹ", "ואן", "But if"),
        ("כִי יָשׁוּב", "רגע", "turns back"),
        ("הַבָּשָׂר הַחַי", "אללחם אלנקי", "the raw flesh"),
        ("וְנֶהְפַּךְ לְלָבָן", "ואנקלב אביצ'א", "and becomes white"),
        ("וּבָא", "פליגי", "he shall come"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the imām"),
    ],
    17: [
        (None, "פאד'א", "And if"),
        ("וְרָאָהוּ הַכֹּהֵן", "נצ'ר אלאמאם", "the imām inspects"),
        (None, "אן", "and the affliction"),
        ("הַנֶּגַע", "אלבלא קד אנקלב אביצ'א", "has turned white"),
        ("וְטִהַר הַכֹּהֵן אֶת-הַנֶּגַע", "פליטהרה", "he shall declare him pure"),
        ("טָהוֹר הוּא", "אנה טאהר", "he is pure"),
    ],
    18: [
        (None, "ואי", "And any"),
        ("וּבָשָׂר", "אנסאן", "person"),
        (None, "כאן", "in whose"),
        ("כִּי-יִהְיֶה בוֹ-בְעֹרוֹ", "פי גלד בדנה", "skin of his body"),
        ("שְׁחִין", "קרח", "there was a sore"),
        ("וְנִרְפָּא", "פברא", "and it healed"),
    ],
    19: [
        ("וְהָיָה", "וצאר", "and there appeared"),
        ("בִּמְקוֹם הַשְּׁחִין", "פי מוצ'עה", "in its place"),
        ("שְׂאֵת לְבָנָה", "שאמה ביצ'א", "a white mark"),
        ("אוֹ בַהֶרֶת", "או בקעה", "or a white spot"),
        ("לְבָנָה אֲדַמְדָּמֶת", "ביצ'א מחמרה", "tinged with red"),
        ("וְנִרְאָה", "פליורא", "he shall be shown"),
        ("אֶל-הַכֹּהֵן", "לאלאמאם", "to the imām"),
    ],
    20: [
        (None, "פאד'א", "And if"),
        ("וְרָאָה הַכֹּהֵן", "ראי' אלאמאם", "the imām sees"),
        ("מַרְאֶהָ", "ומנצ'רהא", "that its appearance"),
        ("שָׁפָל מִן-הָעוֹר", "מתספל מן אלגלד", "is sunken below the skin"),
        ("וּשְׂעָרָהּ", "ושערהא", "and its hair"),
        ("הָפַךְ לָבָן", "קד אנקלב אביצ'א", "has turned white"),
        ("וְטִמְּאוֹ הַכֹּהֵן", "פלינגסה", "he shall declare him impure"),
        ("נֶגַע-צָרַעַת הִוא", "לאנהא בלא ברץ", "for it is an affliction of leprosy"),
        ("בַּשְּׁחִין פָּרָחָה", "קד אנתשר פי אלקרח", "that has spread in the sore"),
    ],
    21: [
        ("וְאִם יִרְאֶנָּה הַכֹּהֵן", "ואן הו ינצ'רהא", "But if he inspects it"),
        ("וְהִנֵּה אֵין-בָּהּ שֵׂעָר לָבָן", "ולם יכון פיהא שער אביץ'", "and there is no white hair in it"),
        ("וּשְׁפָלָה אֵינֶנָּה מִן-הָעוֹר", "וליסת מתספלה מן אלגלד", "and it is not sunken below the skin"),
        (None, "בל", "but is rather"),
        ("וְהִיא כֵהָה", "כאביה", "dim"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן", "פליוקפה", "he shall confine him"),
        ("שִׁבְעַת יָמִים", "סבעה' איאם", "for seven days"),
    ],
    22: [
        ("וְאִם-פָּשֹׂה תִפְשֶׂה בָּעוֹר", "ואן הי תפשת פי אלגלד", "And if it spreads in the skin"),
        ("וְטִמֵּא הַכֹּהֵן אֹתוֹ", "פלינגסה", "he shall declare him impure"),
        ("נֶגַע הִוא", "פאנהא בלא", "for it is an affliction"),
    ],
    23: [
        ("וְאִם-תַּחְתֶּיהָ תַּעֲמֹד", "פאן וקפת מכאנהא", "But if it stays in its place"),
        ("לֹא פָשָׂתָה", "ולם תתפש", "and has not spread"),
        ("צָרֶבֶת הַשְּׁחִין הִוא", "פהי מן את'ר אלקרח", "it is from the trace of the sore"),
        ("וְטִהֲרוֹ הַכֹּהֵן", "פליטהרה אלאמאם", "the imām shall declare him pure"),
    ],
    24: [
        (None, "אי", "Any"),
        ("אוֹ בָשָׂר", "אנסאן", "person"),
        (None, "כאן", "in whose"),
        ("כִּי-יִהְיֶה בְעֹרוֹ", "פי גלדה", "skin"),
        ("מִכְוַת-אֵשׁ", "כי נאר", "there was a burn from fire"),
        (None, "ת'ם", "and"),
        ("וְהָיְתָה מִחְיַת הַמִּכְוָה", "צאר גז אלכי", "the part of the burn became"),
        ("בַּהֶרֶת לְבָנָה אֲדַמְדֶּמֶת", "בקעה ביצ'א מחמרה", "a white spot tinged with red"),
        ("אוֹ לְבָנָה", "או ביצ'א פקט", "or white only"),
    ],
    25: [
        ("וְרָאָה אֹתָהּ הַכֹּהֵן", "פלינצ'רהא אלאמאם", "the imām shall inspect it"),
        (None, "פאן", "and if"),
        ("נֶהְפַּךְ שֵׂעָר לָבָן בַּבַּהֶרֶת", "אנקלב אלשער אביצ'א", "the hair has turned white"),
        ("וּמַרְאֶהָ עָמֹק מִן-הָעוֹר", "וכאן ומנצ'רהא עמיק מן אלגלד", "and its appearance is deep from the skin"),
        ("צָרַעַת הִוא בַּמִּכְוָה פָּרָחָה", "פהו ברץ אנתשר פי אלכי", "it is leprosy that has spread in the burn"),
        ("וְטִמֵּא אֹתוֹ הַכֹּהֵן", "פלינגסה אלאמאם", "the imām shall declare him impure"),
    ],
    26: [
        ("וְאִם יִרְאֶנָּה הַכֹּהֵן", "פאן ראהא אלאמאם", "But if the imām sees"),
        ("וְהִנֵּה אֵין-בַּבַּהֶרֶת שֵׂעָר לָבָן", "וליס פיה שער אביץ'", "that there is no white hair in it"),
        ("וּשְׁפָלָה אֵינֶנָּה מִן-הָעוֹר", "וליסת מתספלה מן אלגלד", "and it is not sunken below the skin"),
        (None, "בל", "but is rather"),
        ("וְהִוא כֵהָה", "כאביה", "dim"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן", "פליוקפה", "he shall confine him"),
        ("שִׁבְעַת יָמִים", "סבעה' איאם", "for seven days"),
    ],
    27: [
        (None, "פינצ'רהא", "Then he shall inspect it"),
        ("וְרָאָהוּ הַכֹּהֵן", "פי אליום אלסאבע", "on the seventh day"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פאן תפשת פי אלגלד", "if it has spread in the skin"),
        ("אִם-פָּשֹׂה תִפְשֶׂה בָּעוֹר", "פלינגסה", "he shall declare him impure"),
        ("וְטִמֵּא הַכֹּהֵן אֹתוֹ", "פאנהא בלא ברץ", "for it is an affliction of leprosy"),
    ],
    28: [
        ("וְאִם-תַּחְתֶּיהָ תַעֲמֹד", "ואן וקפת מכאנהא", "But if it stays in its place"),
        ("לֹא-פָשְׂתָה בָעוֹר", "לם תתפש פי אלגלד", "and has not spread in the skin"),
        ("וְהִוא כֵהָה", "והי כאביה", "and it is dim"),
        ("שְׂאֵת הַמִּכְוָה הִוא", "פהי מן את'ר אלכי", "it is from the trace of the burn"),
        ("וְטִהֲרוֹ הַכֹּהֵן", "פליטהרה אלאמאם", "the imām shall declare him pure"),
        ("כִּי-צָרֶבֶת הַמִּכְוָה הִוא", "פאנהא תשייט אלכי", "for it is a scorching of the burn"),
    ],
    29: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "רגל", "man"),
        ("אוֹ אִשָּׁה", "או אמראה", "or woman"),
        (None, "כאן", "in whom"),
        ("כִּי-יִהְיֶה בוֹ", "בה", "there is"),
        ("נָגַע", "בלא ברץ", "an affliction of leprosy"),
        ("בְּרֹאשׁ", "פי ראסה", "in the head"),
        ("אוֹ בְזָקָן", "או פי לחיתה", "or in the beard"),
    ],
    30: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּגַע", "פלינצ'רה אלאמאם", "the imām shall inspect it"),
        (None, "פאן", "and if"),
        ("וְהִנֵּה מַרְאֵהוּ עָמֹק מִן-הָעוֹר", "כאן מנצ'רה עמיק מן אלגלד", "its appearance is deep from the skin"),
        ("וּבוֹ שֵׂעָר צָהֹב דָּק", "ופיה שער אצהב דקיק", "and there is in it thin yellowish hair"),
        ("וְטִמֵּא אֹתוֹ הַכֹּהֵן", "פלינגסה אלאמאם", "the imām shall declare him impure"),
        ("נֶתֶק הוּא", "פאנה כ'לף", "for it is a blight"),
        ("צָרַעַת הָרֹאשׁ אוֹ הַזָּקָן הוּא", "והו ברץ אלראס או אללחיה", "and it is leprosy of the head or the beard"),
    ],
    31: [
        ("וְכִי-יִרְאֶה הַכֹּהֵן אֶת-נֶגַע הַנֶּתֶק", "ואד'א ראה", "But if it is seen"),
        ("וְהִנֵּה אֵין-מַרְאֵהוּ עָמֹק מִן-הָעוֹר", "וליס מנצ'רה עמיק מן אלגלד", "and its appearance is not deep from the skin"),
        ("וְשֵׂעָר שָׁחֹר אֵין בּוֹ", "וליס פיה שער אסוד", "and there is no black hair in it"),
        ("וְהִסְגִּיר הַכֹּהֵן אֶת-נֶגַע הַנֶּתֶק שִׁבְעַת יָמִים", "פליוקפה סבעה' איאם", "he shall confine him for seven days"),
    ],
    32: [
        (None, "ת'ם", "Then"),
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּגַע", "ינצרה", "he shall inspect it"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        (None, "פהו", "if"),
        ("וְהִנֵּה לֹא-פָשָׂה הַנֶּתֶק", "אן לם יתפש", "it has not spread"),
        ("וְלֹא-הָיָה בוֹ שֵׂעָר צָהֹב", "ולם יציר פיה שער אצהב", "and there has not appeared in it yellowish hair"),
        ("וּמַרְאֵה הַנֶּתֶק אֵין עָמֹק מִן-הָעוֹר", "ומנצ'רה ליס עמיק מן אלגלד", "and its appearance is not deep from the skin"),
    ],
    33: [
        ("וְהִתְגַּלָּח", "פיחלק שערה", "he shall shave his hair"),
        (None, "סוא", "except for"),
        ("וְאֶת-הַנֶּתֶק לֹא יְגַלֵּחַ", "מוצ'ע אלכ'לף", "the place of the blight"),
        ("וְהִסְגִּיר הַכֹּהֵן אֶת-הַנֶּתֶק שִׁבְעַת יָמִים שֵׁנִית", "ויוקפה סבעה' איאם ת'אניה", "and he shall confine him for a second seven days"),
    ],
    34: [
        (None, "ת'ם", "Then"),
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּתֶק", "ינצ'רה", "he shall inspect it"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        (None, "פאן", "if"),
        ("וְהִנֵּה לֹא-פָשָׂה הַנֶּתֶק בָּעוֹר", "הו לם יתפש פי אלגלד", "it has not spread in the skin"),
        ("וּמַרְאֵהוּ אֵינֶנּוּ עָמֹק מִן-הָעוֹר", "ומנצ'רה מע ד'אך ליס עמיק מן אלגלד", "and its appearance is moreover not deep from the skin"),
        ("וְטִהַר אֹתוֹ הַכֹּהֵן", "פליטהרה אלאמאם", "the imām shall declare him pure"),
        ("וְכִבֶּס בְּגָדָיו", "ויג'סל ת'יאבה", "and he shall wash his garments"),
        ("וְטָהֵר", "ליטהר", "that he may be pure"),
    ],
    35: [
        ("וְאִם-פָּשֹׂה יִפְשֶׂה הַנֶּתֶק בָּעוֹר", "ואן תפשא אלכ'לף פי בדנה", "But if the blight spreads in his body"),
        ("אַחֲרֵי טָהֳרָתוֹ", "בעד טהרה", "after his purification"),
    ],
    36: [
        ("וְרָאָהוּ הַכֹּהֵן", "פינצ'רה אלאמאם", "the imām shall inspect it"),
        ("וְהִנֵּה פָּשָׂה הַנֶּתֶק בָּעוֹר", "קד תפשא פי אלגלד", "and behold it has spread in the skin"),
        ("לֹא-יְבַקֵּר הַכֹּהֵן לַשֵּׂעָר הַצָּהֹב", "פלא יפחץ ען אלשער אלאצהב", "he need not examine for the yellowish hair"),
        ("טָמֵא הוּא", "בברהאן אנה נגס", "by proof that he is impure"),
    ],
    37: [
        ("וְאִם-בְּעֵינָיו עָמַד הַנֶּתֶק", "ואן הו וקף בעינה", "But if it has stood as it was"),
        ("וְשֵׂעָר שָׁחֹר צָמַח-בּוֹ", "ונבת פיה שער אסוד", "and black hair has grown in it"),
        ("נִרְפָּא הַנֶּתֶק", "פקד ברא", "then it has healed"),
        ("טָהוֹר הוּא", "והו טאהר", "and he is pure"),
        ("וְטִהֲרוֹ הַכֹּהֵן", "פליטהרה אלאמאם", "the imām shall declare him pure"),
    ],
    38: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "רגל", "man"),
        ("אוֹ-אִשָּׁה", "או אמראה", "or woman"),
        (None, "כאן", "in whose"),
        ("כִּי-יִהְיֶה בְעוֹר-בְּשָׂרָם", "פי גלד בדנה", "skin of his body"),
        ("בֶּהָרֹת", "בקע", "there are spots"),
        ("בֶּהָרֹת לְבָנֹת", "בקע ביץ'", "spots that are white"),
    ],
    39: [
        ("וְרָאָה הַכֹּהֵן", "פינצ'ר אלאמאם", "the imām shall inspect"),
        (None, "פאד'א", "and if"),
        ("וְהִנֵּה בְעוֹר-בְּשָׂרָם", "פי גלוד אבדאנהם", "in the skin of their bodies"),
        ("בֶּהָרֹת", "בקע", "the spots"),
        ("כֵּהוֹת לְבָנֹת", "כאביה פי ביאצ'הא", "are dim in their whiteness"),
        ("בֹּהַק הוּא", "פהו בהק", "it is vitiligo"),
        ("פָּרַח בָּעוֹר", "אנתשר פי אלגלד", "that has spread in the skin"),
        ("טָהוֹר הוּא", "והו טאהר", "and he is pure"),
    ],
    40: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "אנסאן", "person"),
        ("כִּי יִמָּרֵט רֹאשׁוֹ", "אנתתף שערה", "whose hair has fallen out"),
        ("קֵרֵחַ הוּא", "פהו אלאצלע", "he is the bald one"),
        ("טָהוֹר הוּא", "והו טאהר", "and he is pure"),
    ],
    41: [
        ("וְאִם", "ואן", "And if"),
        ("מִפְּאַת פָּנָיו יִמָּרֵט רֹאשׁוֹ", "אנתתף מן גהה' וגהה", "it has fallen out from the side of his face"),
        ("גִּבֵּחַ הוּא", "פהו אלאגלח", "he is the forehead-bald one"),
        ("טָהוֹר הוּא", "והו טאהר", "and he is pure"),
    ],
    42: [
        ("וְכִי-יִהְיֶה", "פאן כאן", "But if there is"),
        ("בַקָּרַחַת", "פי אלצלעה", "in the bald patch"),
        ("אוֹ בַגַּבַּחַת", "או פי אלגלחה", "or in the forehead-bald patch"),
        ("נֶגַע לָבָן אֲדַמְדָּם", "בלא ביאץ' מחמר", "a white affliction tinged with red"),
        (None, "פימכן אן יכון", "it may be"),
        ("צָרַעַת פֹּרַחַת הִוא", "ברץ", "leprosy"),
        (None, "קד אנתשר", "that has spread"),
        ("בְּקָרַחְתּוֹ", "פי צלעתה", "in his bald patch"),
        ("אוֹ בְגַבַּחְתּוֹ", "או פי גלחתה", "or his forehead-bald patch"),
    ],
    43: [
        ("וְרָאָה אֹתוֹ הַכֹּהֵן", "פ לינצ'ר אלאמאם", "The imām shall inspect"),
        (None, "אן", "if"),
        ("שְׂאֵת-הַנֶּגַע", "כאנת שאמה' אלבלא", "the mark of the affliction"),
        ("לְבָנָה אֲדַמְדֶּמֶת", "ביצ'א מחמרה", "is white tinged with red"),
        ("בְּקָרַחְתּוֹ", "פי צלעתה", "in his bald patch"),
        ("אוֹ בְגַבַּחְתּוֹ", "או פי גלחתה", "or his forehead-bald patch"),
        ("כְּמַרְאֵה צָרַעַת עוֹר בָּשָׂר", "עלי' סביל מנאצ'ר ברץ סאיר גלד אלבדן ואחכאמהא", "after the manner of the appearances of leprosy of the rest of the skin of the body and its rulings"),
    ],
    44: [
        (None, "פהו", "he is"),
        ("אִישׁ-צָרוּעַ הוּא", "רגל אברץ", "a leprous man"),
        ("טָמֵא הוּא", "והו נגס", "and he is impure"),
        ("טַמֵּא יְטַמְּאֶנּוּ הַכֹּהֵן", "פלינגסה אלאמאם תנגיסא", "the imām shall declare him thoroughly impure"),
        (None, "פאן", "for"),
        ("בְּרֹאשׁוֹ נִגְעוֹ", "בלאה פי ראסה", "his affliction is in his head"),
    ],
    45: [
        ("וְהַצָּרוּעַ", "ואלאברץ", "And the leper"),
        ("אֲשֶׁר-בּוֹ הַנֶּגַע", "אלד'י בה אלבלא", "in whom the affliction is"),
        ("בְּגָדָיו יִהְיוּ פְרֻמִים", "יגב אן תכון ת'יאבה ממזקה", "his garments must be torn"),
        ("וְרֹאשׁוֹ יִהְיֶה פָרוּעַ", "וראסה יכון שעת'א", "and his head shall be disheveled"),
        ("וְעַל-שָׂפָם יַעְטֶה", "ויתלת'ם עלי' שארבה", "and he shall cover over his mustache"),
        ("וְטָמֵא טָמֵא יִקְרָא", "וינאדי אלנגס אלנגס", "and he shall call out: 'Impure! Impure!'"),
    ],
    46: [
        ("כָּל-יְמֵי", "טול מא", "For as long as"),
        (None, "אקאם", "the affliction remains"),
        ("אֲשֶׁר הַנֶּגַע בּוֹ", "פיה אלבלא", "in him"),
        ("יִטְמָא", "ינגס", "he shall be impure"),
        ("טָמֵא הוּא", "פאנה נגס", "for he is impure"),
        ("בָּדָד יֵשֵׁב", "פליגלס פרדא", "he shall dwell alone"),
        ("מִחוּץ לַמַּחֲנֶה", "כ'ארג אלעסכר", "outside the camp"),
        ("מוֹשָׁבוֹ", "יכון מקאמה", "shall be his dwelling-place"),
    ],
    47: [
        (None, "ואי", "And any"),
        ("וְהַבֶּגֶד", "תוב", "garment"),
        (None, "כאן", "in which"),
        ("כִּי-יִהְיֶה בוֹ", "פיה", "there is"),
        ("נֶגַע צָרָעַת", "בלא ברץ", "an affliction of leprosy"),
        ("בְּבֶגֶד צֶמֶר", "מן ת'וב צוף", "whether a garment of wool"),
        ("אוֹ בְּבֶגֶד פִּשְׁתִּים", "או כתאן", "or"),
    ],
    48: [
        ("אוֹ בִשְׁתִי", "או סדא", "or in warp"),
        ("אוֹ בְעֵרֶב", "או לחמה", "or weft"),
        ("לַפִּשְׁתִּים", "מן כתאן", "of linen"),
        ("וְלַצָּמֶר", "וצוף", "or wool"),
        ("אוֹ בְעוֹר", "או פי גלד", "or in hide"),
        ("אוֹ בְּכָל-מְלֶאכֶת עוֹר", "או ממא צנע מנה", "or in anything made from it"),
    ],
    49: [
        ("וְהָיָה הַנֶּגַע", "וכאן אלבלא", "and the affliction is"),
        ("יְרַקְרַק", "אכ'צ'רא", "green"),
        ("אוֹ אֲדַמְדָּם", "או אחמרא", "or red"),
        ("בַּבֶּגֶד", "פי אלתוב", "in the garment"),
        ("אוֹ בָעוֹר", "או אלגלד", "or the hide"),
        ("אוֹ-בַשְּׁתִי", "או אלס'דא", "or the warp"),
        ("אוֹ-בָעֵרֶב", "או אלחמה", "or the weft"),
        ("אוֹ בְכָל-כְּלִי-עוֹר", "או פי שי מן אנא אלגלוד", "or in any article of hides"),
        ("נֶגַע צָרַעַת הוּא", "פד'אלך הו בלא ברץ", "that is an affliction of leprosy"),
        ("וְהָרְאָה אֶת-הַכֹּהֵן", "פליורא לאלאמאם", "it shall be shown to the imām"),
    ],
    50: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנָּגַע", "פאד'א ראה", "When it is seen"),
        ("וְהִסְגִּיר אֶת-הַנֶּגַע", "אוקפה", "he shall confine it"),
        ("שִׁבְעַת יָמִים", "סבעה' איאם", "for seven days"),
    ],
    51: [
        (None, "ת'ם", "Then"),
        ("וְרָאָה אֶת-הַנֶּגַע", "ינצ'רה", "he shall inspect it"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        (None, "פאן", "if"),
        ("כִּי-פָשָׂה הַנֶּגַע", "תפשא אלבלא", "the affliction has spread"),
        ("בַּבֶּגֶד", "פי אלת'וב", "in the garment"),
        ("אוֹ-בַשְּׁתִי", "או אלס'דא", "or the warp"),
        ("אוֹ-בָעֵרֶב", "או אלחמה", "or the weft"),
        ("אוֹ בָעוֹר", "או פי אלגלד", "or in the hide"),
        ("לְכֹל אֲשֶׁר-יֵעָשֶׂה הָעוֹר לִמְלָאכָה", "וסאיר מא יעמל מן אלגלוד מצנועא", "or in the rest of what is made from hides as a manufactured article"),
        ("צָרַעַת מַמְאֶרֶת", "פד'אך בלא ברץ מאחק", "that is a consuming affliction of leprosy"),
        ("טָמֵא הוּא", "והו נגס", "and it is impure"),
    ],
    52: [
        (None, "פליחרק", "He shall burn"),
        ("וְשָׂרַף אֶת-הַבֶּגֶד", "אלת'וב", "the garment"),
        ("אוֹ אֶת-הַשְּׁתִי", "או אלסדא", "or the warp"),
        ("אוֹ אֶת-הָעֵרֶב", "או אללחמה", "or the weft"),
        ("בַּצֶּמֶר", "כאן מן צוף", "whether of wool"),
        ("אוֹ בַפִּשְׁתִּים", "או כתאן", "or linen"),
        ("אוֹ אֶת-כָּל-כְּלִי הָעוֹר", "או גמיע אניה' אלגלוד", "or all the articles of hides"),
        ("אֲשֶׁר-יִהְיֶה בוֹ הַנָּגַע", "אלד'י יכון פיהא אלבלא", "in which the affliction is"),
        ("כִּי-צָרַעַת מַמְאֶרֶת הִוא", "פאנה ברץ מאחק", "for it is a consuming leprosy"),
        ("בָּאֵשׁ תִּשָּׂרֵף", "לד'אלך יחרק באלנאר", "therefore it shall be burned with fire"),
    ],
    53: [
        ("וְאִם יִרְאֶה הַכֹּהֵן", "ואן ראה אלאמאם", "But if the imām sees"),
        (None, "פאד'אה", "that"),
        ("וְהִנֵּה לֹא-פָשָׂה הַנֶּגַע", "לם יתפש", "it has not spread"),
        ("בַּבֶּגֶד", "פי אלת'וב", "in the garment"),
        ("אוֹ בַשְּׁתִי", "או אלסדא", "or the warp"),
        ("אוֹ בָעֵרֶב", "או אללחמה", "or the weft"),
        ("אוֹ בְּכָל-כְּלִי-עוֹר", "או גמיע אניה' אלגלוד", "or in any article of hides"),
    ],
    54: [
        ("וְצִוָּה הַכֹּהֵן", "פליאמר בג'סלה", "he shall command that it be washed"),
        ("וְכִבְּסוּ אֵת אֲשֶׁר-בּוֹ הַנָּגַע", "ויוקפה", "and he shall confine it"),
        ("וְהִסְגִּירוֹ שִׁבְעַת-יָמִים שֵׁנִית", "סבעה' איאם ת'אניה", "for a second seven days"),
    ],
    55: [
        (None, "ת'ם", "Then"),
        ("וְרָאָה הַכֹּהֵן", "ינצ'רה", "he shall inspect it"),
        ("אַחֲרֵי הֻכַּבֵּס", "בעד מא ג'סל", "after it has been washed"),
        (None, "פאן", "if"),
        ("וְהִנֵּה לֹא-הָפַךְ הַנֶּגַע אֶת-עֵינוֹ", "כאן לם ינקלב לונה", "its color has not changed"),
        ("וְהַנֶּגַע לֹא-פָשָׂה", "ולם יתפש", "and it has not spread"),
        ("טָמֵא הוּא", "פהו נגס", "it is impure"),
        ("בָּאֵשׁ תִּשְׂרְפֶנּוּ", "פליחרק באלנאר", "it shall be burned with fire"),
        ("פְּחֶתֶת הִוא", "והי מהלכה", "it was a destructive thing"),
        ("בְּקָרַחְתּוֹ", "כאנת פי סחקתה", "whether in its worn part"),
        ("אוֹ בְגַבַּחְתּוֹ", "או פי זיברתה", "or in its new part"),
    ],
    56: [
        ("וְאִם רָאָה הַכֹּהֵן", "ואן ראה", "But if he sees"),
        ("וְהִנֵּה כֵּהָה הַנֶּגַע אַחֲרֵי הֻכַּבֵּס אֹתוֹ", "קד כבי בעד מא גסל", "that it has dimmed after it was washed"),
        ("וְקָרַע אֹתוֹ מִן-הַבֶּגֶד", "פליכ'רקה מן אלת'וב", "he shall scrape it from the garment"),
        ("אוֹ מִן-הָעוֹר", "או אלגלד", "or the hide"),
        ("אוֹ מִן-הַשְּׁתִי", "ויקטעה מן אלסדא", "and cut it out from the warp"),
        ("אוֹ מִן-הָעֵרֶב", "או אללחמה", "or the weft"),
    ],
    57: [
        ("וְאִם-תֵּרָאֶה עוֹד", "ואן צ'הרת זיאדה", "And if it appears further"),
        ("בַּבֶּגֶד", "פי אלת'וב", "in the garment"),
        ("אוֹ-בַשְּׁתִי", "או אלסדא", "or the warp"),
        ("אוֹ-בָעֵרֶב", "או אללחמה", "or the weft"),
        ("אוֹ בְכָל-כְּלִי-עוֹר", "או גמיע אניה' אלגלוד", "or in any article of hides"),
        ("פֹּרַחַת הִוא", "פהי אלמנתשרה", "it is the spreading one"),
        ("בָּאֵשׁ תִּשְׂרְפֶנּוּ", "פלתחרק באלנאר", "shall be burned with fire"),
        ("אֵת אֲשֶׁר-בּוֹ הַנָּגַע", "אלת'וב אלד'י פי אלבלא", "the garment in which the affliction is"),
    ],
    58: [
        ("וְהַבֶּגֶד", "ואלת'וב", "But the garment"),
        ("אוֹ-הַשְּׁתִי", "או אלסדא", "or the warp"),
        ("אוֹ-הָעֵרֶב", "או אללחמה", "or the weft"),
        ("אוֹ-כָל-כְּלִי הָעוֹר", "או גמיע אנא אלגלוד", "or any article of hides"),
        ("אֲשֶׁר תְּכַבֵּס", "אן ג'סלת", "if they are washed"),
        ("וְסָר מֵהֶם הַנָּגַע", "וזאל ענהא אלבלא", "and the affliction departs from them"),
        ("וְכֻבַּס שֵׁנִית", "פלתג'סל ת'אניה", "they shall be washed a second time"),
        ("וְטָהֵר", "ותטהר", "and they shall be pure"),
    ],
    59: [
        (None, "הד'ה", "This is"),
        ("זֹאת תּוֹרַת", "שריעה'", "the ordinance of"),
        ("נֶגַע-צָרַעַת", "בלא אלברץ", "the affliction of leprosy"),
        ("בֶּגֶד הַצֶּמֶר", "אלכאין פי ת'וב צוף", "in a garment of wool"),
        ("אוֹ הַפִּשְׁתִּים", "או כתאן", "or linen"),
        ("אוֹ הַשְּׁתִי", "או סדא", "or warp"),
        ("אוֹ הָעֵרֶב", "או לחמה", "or weft"),
        ("אוֹ כָּל-כְּלִי-עוֹר", "או שי מן אנא אלגלוד", "or any article of hides"),
        ("לְטַהֲרוֹ", "ליטהר", "to declare it pure"),
        ("אוֹ לְטַמְּאוֹ", "או ינגס", "or to declare it impure"),
    ],
}
