"""Hand-authored alignment triples for Vayikra chapter 14.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly"),
    ],
    2: [
        ("זֹאת", "הד'א", "This"),
        ("תִּהְיֶה", "תכון", "shall be"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הַמְּצֹרָע", "אלאברץ", "the one afflicted with leprosy"),
        (None, "פי", "at"),
        ("בְּיוֹם", "וקת", "the time of"),
        ("טָהֳרָתוֹ", "טהרה", "his purification"),
        (None, "אן", "that"),
        ("וְהוּבָא", "יותא", "be brought"),
        (None, "בכ'ברה", "report of him"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the imām"),
    ],
    3: [
        ("וְיָצָא", "ויכ'רג", "shall go out"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("אֶל-מִחוּץ", "אלי' כ'ארג", "to outside"),
        ("לַמַּחֲנֶה", "אלעסכר", "the camp"),
        (None, "פאד'א", "and if"),
        ("וְרָאָה", "ראי'", "he sees"),
        (None, "אן", "that"),
        ("הַצָּרוּעַ", "אלאברץ", "the one afflicted with leprosy"),
        ("נִרְפָּא", "קד אשפא", "has recovered"),
        (None, "מן בלא אלברץ", "from the affliction of the leprosy,"),
        (None, "אמר פיה במא יגב", "he shall ordain for him what is required"),
    ],
    4: [
        ("וְצִוָּה", "פיאמר", "shall give the order"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("וְלָקַח", "ויאכ'ד'", "and there shall be taken"),
        ("לַמִּטַּהֵר", "לאלמתטהר", "for the one being purified"),
        ("שְׁתֵּי-צִפֳּרִים", "עצפורין", "two clean"),
        ("טְהֹרוֹת", "טאהרין", "sparrows"),
        ("וְעֵץ", "ועוד", "and a rod of"),
        ("אֶרֶז", "ארז", "cedar"),
        ("וּשְׁנִי תוֹלַעַת", "וחריר קרמז", "and crimson silk"),
        ("וְאֵזֹב", "וצעתר", "and hyssop"),
    ],
    5: [
        (None, "ת'ם", "Then"),
        ("וְצִוָּה", "יאמר", "shall give the order"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("וְשָׁחַט", "בד'בח", "to slaughter"),
        ("הָאֶחָת", "אחדהמא", "one of them"),
        (None, "פי", "in"),
        ("אֶל-כְּלִי-חֶרֶשׂ", "אנא מן כ'זף", "a clay vessel"),
        ("עַל-מַיִם", "עלי' מא", "over water"),
        ("חַיִּים", "מן נביע", "from a spring"),
    ],
    6: [
        ("אֶת-הַצִּפֹּר", "וליאכ'ד' אלעצפור", "And he shall take the living"),
        ("הַחַיָּה", "אלחי", "sparrow,"),
        ("וְאֶת-עֵץ", "ואלעוד", "and the cedar"),
        ("הָאֶרֶז", "אלארז", "rod,"),
        ("וְאֶת-שְׁנִי הַתּוֹלַעַת", "וחריר אלקרמז", "and the crimson silk"),
        ("וְאֶת-הָאֵזֹב", "ואלצעתר", "and the hyssop"),
        ("וְטָבַל", "ויג'מס", "and shall dip"),
        ("אוֹתָם", "ד'אלך", "them"),
        ("וְאֵת הַצִּפֹּר הַחַיָּה", "מע אלעצפור אלחי", "together with the living sparrow"),
        ("בְּדַם", "בדם", "in the blood of"),
        ("הַצִּפֹּר הַשְּׁחֻטָה", "אלעצפור אלמד'בוח", "the slaughtered sparrow"),
        ("עַל הַמַּיִם הַחַיִּים", "עלי' אלמא אלד'י מן נביע", "over the water from a spring"),
    ],
    7: [
        ("וְהִזָּה", "וינצ'ח", "And he shall sprinkle"),
        ("עַל הַמִּטַּהֵר", "עלי' אלמתטהר", "upon the one being purified"),
        ("מִן-הַצָּרַעַת", "מן אלברץ", "from the leprosy"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("וְטִהֲרוֹ", "ויטהרה", "and shall declare him pure"),
        ("וְשִׁלַּח", "ויטלק", "and he shall release"),
        ("אֶת-הַצִּפֹּר הַחַיָּה", "אלעצפור אלחי", "the living sparrow"),
        ("עַל-פְּנֵי", "עלי' וגה", "upon the face of"),
        ("הַשָּׂדֶה", "אלצחרי'", "the wilderness"),
    ],
    8: [
        (None, "ת'ם", "Then"),
        ("וְכִבֶּס", "יג'סל", "shall wash"),
        ("הַמִּטַּהֵר", "אלמתטהר", "the one being purified"),
        ("אֶת-בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְגִלַּח", "ויחלק", "and shave off"),
        ("כָּל-שְׂעָרוֹ", "גמיע שערה", "all his hair"),
        ("וְרָחַץ", "וירחץ'", "and shall bathe"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָהֵר", "ויטהר", "and be pure"),
        ("וְאַחַר", "ובעד ד'אלך", "and after that"),
        ("יָבוֹא", "ידכ'ל", "he shall enter"),
        ("אֶל-הַמַּחֲנֶה", "אלי' אלעסכר", "into the camp"),
        ("וְיָשַׁב", "ויקים", "and shall remain"),
        ("מִחוּץ לְאָהֳלוֹ", "כ'ארג מנזלה", "outside his dwelling"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "for seven days"),
    ],
    9: [
        (None, "פאד'א כאן", "And on the"),
        ("בַיּוֹם", "פי אליום", "seventh"),
        ("הַשְּׁבִיעִי", "אלסאבע", "day"),
        ("יְגַלַּח", "יחלק", "he shall shave"),
        ("כָּל-שְׂעָרוֹ", "גמיע שערה", "all the hair of"),
        ("אֶת-רֹאשׁוֹ", "ראסה", "his head"),
        ("וְאֶת-זְקָנוֹ", "ולחיתה", "and his beard"),
        ("גַּבֹּת עֵינָיו", "וחואגב עיניה", "and his eyebrows"),
        ("שְׂעָרוֹ יְגַלֵּחַ", "מע סאיר שערה", "together with the rest of his hair"),
        ("וְכִבֶּס", "ויג'סל", "and he shall wash"),
        ("אֶת-בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and shall bathe"),
        ("אֶת-בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַּמַּיִם", "באלמא", "in water"),
        ("וְטָהֵר", "ויטהר", "and be pure"),
    ],
    10: [
        (None, "ופי", "And on the"),
        ("וּבַיּוֹם", "אליום", "eighth"),
        ("הַשְּׁמִינִי", "אלתאמן", "day"),
        ("יִקַּח", "יקדם", "he shall bring forward"),
        ("שְׁנֵי-כְבָשִׂים", "כ'רופין", "two sound"),
        ("תְּמִימִם", "צחיחין", "rams,"),
        ("וְכַבְשָׂה", "ורכלה", "and one sound"),
        ("אַחַת בַּת-שְׁנָתָהּ", "אבנה' סנתהא", "ewe-lamb in its first"),
        ("תְּמִימָה", "צחיחה", "year,"),
        ("וּשְׁלֹשָׁה", "ותלאתה'", "and three"),
        ("עֶשְׂרֹנִים", "עשור", "tenths of"),
        ("סֹלֶת", "סמד", "fine flour"),
        ("מִנְחָה", "הדייה", "as an offering"),
        ("בְּלוּלָה", "מלתותה", "mixed"),
        ("בַשֶּׁמֶן", "בדהן", "with oil"),
        ("וְלֹג", "ולג", "and a log of"),
        ("שָׁמֶן", "דהן", "oil"),
    ],
    11: [
        ("וְהֶעֱמִיד", "ויוקף", "shall station"),
        ("הַכֹּהֵן הַמְטַהֵר", "אלאמאם אלמטהר", "the purifying imām"),
        ("אֵת הָאִישׁ", "אלרגל", "the purified"),
        ("הַמִּטַּהֵר", "אלמתטהר", "man"),
        ("וְאֹתָם", "והם", "and them"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("פֶּתַח", "ענד באב", "at the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
    ],
    12: [
        ("וְלָקַח", "ויאכ'ד'", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall take"),
        ("אֶת-הַכֶּבֶשׂ הָאֶחָד", "אחד אלכ'רופין", "one of the rams"),
        ("וְהִקְרִיב", "ליקרבה", "to present it"),
        ("לְאָשָׁם", "ען אלאתם", "for the guilt-offering"),
        ("וְאֶת-לֹג הַשָּׁמֶן", "ואלג אלדהן", "along with the log of oil;"),
        ("וְהֵנִיף", "ויחרכהא", "and he shall wave them"),
        ("תְּנוּפָה", "תחריכא", "as a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    13: [
        (None, "ת'ם", "Then"),
        ("וְשָׁחַט", "יד'בחה", "he shall slaughter it"),
        ("בִּמְקוֹם", "פי אלמוצ'ע", "in the place"),
        ("אֲשֶׁר יִשְׁחַט", "אלד'י יד'בח", "where the purification-offering"),
        ("אֶת-הַחַטָּאת", "אלד'כוה", "and the ascending-offering"),
        ("וְאֶת-הָעֹלָה", "ואלצעידה", "are slaughtered"),
        ("בִּמְקוֹם הַקֹּדֶשׁ", "פי מוצ'ע אלקד'ס", "in the holy place"),
        (None, "לאן", "for"),
        ("כִּי כַּחַטָּאת", "קרבאן אלאת'ם", "the guilt-offering"),
        ("הָאָשָׁם", "הו כאלד'כוה", "is like the purification-offering"),
        ("לַכֹּהֵן", "לאלאמאם", "for the imām"),
        ("קֹדֶשׁ קָדָשִׁים", "מן כ'ואץ אלאקדאס", "among the choicest of the holy things"),
    ],
    14: [
        (None, "ת'ם", "Then"),
        ("וְלָקַח", "יאכ'ד'", "he shall take"),
        ("מִדַּם", "מן דמה", "some of its blood"),
        ("וְנָתַן", "ויגעל", "and place it"),
        ("עַל-תְּנוּךְ", "עלי' שחמה'", "on the cartilage of"),
        ("אֹזֶן", "אד'ן", "the earlobe of"),
        ("הַמִּטַּהֵר", "אלמתטהר", "the one being purified"),
        ("הַיְמָנִית", "אלימני", "the right one"),
        ("וְעַל-בֹּהֶן", "ועלי' אבהאם", "and on the thumb of"),
        ("יָדוֹ", "ידה", "his right"),
        ("הַיְמָנִית", "אלימני", "hand,"),
        ("וְעַל-בֹּהֶן", "ואבהאם", "and on the thumb of"),
        ("רַגְלוֹ", "רגלה", "his right"),
        ("הַיְמָנִית", "אלימני", "foot"),
    ],
    15: [
        ("וְלָקַח", "ויאכ'ד'", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall take"),
        ("מִלֹּג", "מן לג", "from the log of"),
        ("הַשָּׁמֶן", "אלדהן", "oil"),
        ("וְיָצַק", "ויצב", "and pour it into"),
        ("עַל-כַּף", "עלי' כפה", "his left"),
        ("הַשְּׂמָאלִית", "אליסרי", "palm"),
    ],
    16: [
        ("וְטָבַל", "ויג'מס", "And he shall dip"),
        ("אֶת-אֶצְבָּעוֹ", "אצבעה", "his right"),
        ("הַיְמָנִית", "אלימני", "finger"),
        ("מִן-הַשֶּׁמֶן", "מן אלד'הן", "from the oil"),
        ("אֲשֶׁר עַל-כַּפּוֹ", "אלד'י עלי' ידה", "that is on his left"),
        ("הַשְּׂמָאלִית", "אליסרי", "hand,"),
        ("וְהִזָּה", "וינצ'ח", "and shall sprinkle"),
        ("מִן-הַשֶּׁמֶן", "מנה", "from it"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    17: [
        (None, "ת'ם", "Then"),
        ("יִתֵּן", "יצ'ע", "he shall place"),
        ("מִיֶּתֶר הַשֶּׁמֶן", "מן באקיה", "some of the remainder"),
        ("עַל-תְּנוּךְ", "עלי' שחמה'", "upon the cartilage of"),
        ("אֹזֶן", "אד'ן", "the earlobe of"),
        ("הַמִּטַּהֵר", "אלמתטהר", "the one being purified"),
        ("הַיְמָנִית", "אלימני", "the right one"),
        ("וְעַל-בֹּהֶן", "ועלי' אבהאם", "and on the thumb of"),
        ("יָדוֹ הַיְמָנִית", "ידה אלימני", "his right hand"),
        ("וְעַל-בֹּהֶן", "ואבהאם", "and on the thumb of"),
        ("רַגְלוֹ הַיְמָנִית", "רגלה אלימני", "his right foot"),
        ("עַל דַּם הָאָשָׁם", "עלי' דם קרבאן אלאת'ם", "upon the blood of the guilt-offering"),
    ],
    18: [
        ("וְהַנּוֹתָר", "ואלפאצ'ל", "And what remains"),
        ("בַּשֶּׁמֶן", "מנה", "of it"),
        ("יִתֵּן", "יצ'עה", "he shall place"),
        ("עַל-רֹאשׁ", "עלי' ראס", "upon the head of"),
        ("הַמִּטַּהֵר", "אלמתטהר", "the one being purified"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek forgiveness"),
        ("עָלָיו", "ענה", "for him"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    19: [
        (None, "ת'ם", "Then"),
        ("וְעָשָׂה", "יעמל", "shall perform"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("אֶת-הַחַטָּאת", "אלד'כוה", "the purification-offering"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek forgiveness"),
        ("עַל-הַמִּטַּהֵר", "ען אלמתטהר", "for the one being purified"),
        ("מִטֻּמְאָתוֹ", "מן נגאסתה", "from his impurity"),
        ("וְאַחַר", "ובעד ד'אלך", "and after that"),
        ("יִשְׁחַט", "יד'בח", "he shall slaughter"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the ascending-offering"),
    ],
    20: [
        (None, "ת'ם", "Then"),
        ("וְהֶעֱלָה", "יצעד", "he shall cause"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the ascending-offering"),
        ("וְאֶת-הַמִּנְחָה", "ואלהדייה", "and the gift-offering"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "to ascend upon the altar;"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        ("עָלָיו", "ענה", "for him,"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("וְטָהֵר", "ויטהר", "and he shall be pure"),
    ],
    21: [
        ("וְאִם", "ואן", "And if"),
        ("דַּל", "כאן פקירא", "he is poor"),
        ("וְאֵין יָדוֹ מַשֶּׂגֶת", "לם תנאל ידה ד'אלך", "his hand not reaching to that"),
        ("וְלָקַח", "פליקרב", "then let him bring"),
        ("כֶּבֶשׂ אֶחָד", "כ'רופא ואחדא", "one ram"),
        ("אָשָׁם", "קרבאן אלאת'ם", "as the guilt-offering"),
        ("לִתְנוּפָה", "לאלתחריך", "for the waving"),
        ("לְכַפֵּר", "ליסתג'פר", "that forgiveness be sought"),
        ("עָלָיו", "ענה", "for him"),
        ("וְעִשָּׂרוֹן", "ועשר", "and one tenth of"),
        ("סֹלֶת", "מן סמד", "fine flour"),
        ("בָּלוּל", "מלתות", "mixed"),
        ("בַּשֶּׁמֶן", "בד'הן", "with oil"),
        ("לְמִנְחָה", "הדייה", "as a gift-offering"),
        ("וְלֹג שָׁמֶן", "ולג דהן", "and a log of oil"),
    ],
    22: [
        ("וּשְׁתֵּי תֹרִים", "ושפנינין", "And two turtle-doves"),
        ("אוֹ", "או", "or"),
        ("שְׁנֵי בְּנֵי יוֹנָה", "פרכ'י חמאם", "two young pigeons"),
        ("אֲשֶׁר תַּשִּׂיג יָדוֹ", "עלי' מא תנאל ידה", "according to what his hand can reach"),
        ("אֶחָד חַטָּאת", "פיכון אחדהמא ד'כוה", "one of them shall be a purification-offering"),
        ("וְהָאֶחָד עֹלָה", "ואלאכ'ר צעידה", "and the other an ascending-offering"),
    ],
    23: [
        ("וְהֵבִיא", "פליאת", "He shall bring"),
        ("אֹתָם", "בהמא", "them"),
        ("בַּיּוֹם הַשְּׁמִינִי", "פי אליום אלת'אמן", "on the eighth day"),
        ("לְטָהֳרָתוֹ", "מן אוול טהרה", "from the beginning of his purification"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the imām"),
        ("אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל-מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    24: [
        ("וְלָקַח", "ויאכ'ד'", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall take"),
        ("אֶת-כֶּבֶשׂ הָאָשָׁם", "כ'רוף קרבאן אלאת'ם", "the ram of the guilt-offering"),
        ("וְאֶת-לֹג הַשָּׁמֶן", "ואללג אלדהן", "and the log of oil,"),
        ("וְהֵנִיף", "ויחרכהא", "and the imām shall wave"),
        ("תְּנוּפָה", "תחריכא", "them as a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    25: [
        (None, "ת'ם", "Then"),
        ("וְשָׁחַט", "יד'בחה", "he shall slaughter it"),
        ("וְלָקַח", "ויאכ'ד", "and he shall take"),
        ("מִדַּם הָאָשָׁם", "מן דמה", "some of its blood"),
        ("וְנָתַן", "ויצע", "and place it"),
        ("עַל-תְּנוּךְ", "עלי' שחמה'", "on the cartilage of"),
        ("אֹזֶן-הַמִּטַּהֵר", "אד'ן אלמתטהר", "the earlobe of the one being purified"),
        ("הַיְמָנִית", "אלימני", "the right one"),
        ("וְעַל-בֹּהֶן", "ועלי' אבהאם", "and on the thumb of"),
        ("רַגְלוֹ הַיְמָנִית", "רגלה אלימני", "his right foot"),
    ],
    26: [
        ("וּמִן-הַשֶּׁמֶן", "ומן אלדהן", "And from the oil"),
        ("יִצֹק", "יצב", "shall pour"),
        (None, "פי כפה אליסרי", "into his left palm"),
    ],
    27: [
        ("וְהִזָּה", "וינצ'ח", "And he shall sprinkle"),
        ("בְּאֶצְבָּעוֹ הַיְמָנִית", "באצבעה אלימני", "with his right finger"),
        ("מִן-הַשֶּׁמֶן", "מן ד'אלך אלד'הן", "from that oil"),
        ("אֲשֶׁר עַל-כַּפּוֹ", "אלד'י עלי' כפה", "which is on his left"),
        ("הַשְּׂמָאלִית", "אליסרי", "palm,"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    28: [
        (None, "ת'ם", "Then"),
        ("וְנָתַן", "יצ'ע", "he shall place"),
        ("מִן-הַשֶּׁמֶן", "מן אלד'הן", "from the oil"),
        ("אֲשֶׁר עַל-כַּפּוֹ", "אלד'י פי כפה", "that is in his palm"),
        ("עַל-תְּנוּךְ", "עלי' שחמה'", "upon the cartilage of"),
        ("אֹזֶן הַמִּטַּהֵר", "אד'ן אלמתטהר", "the earlobe of the one being purified"),
        ("הַיְמָנִית", "אלימני", "the right one"),
        ("וְעַל-בֹּהֶן יָדוֹ", "ועלי' אבהאם ידה", "and on the thumb of his right"),
        ("הַיְמָנִית", "אלימני", "hand,"),
        ("וְעַל-בֹּהֶן רַגְלוֹ", "ועלי' אבהאם רגלה", "and on the thumb of his right"),
        ("הַיְמָנִית", "אלימני", "foot,"),
        ("עַל-מְקוֹם דַּם הָאָשָׁם", "עלי' מוצ'ע דם קרבאן אלאת'ם", "upon the place of the blood of the guilt-offering"),
    ],
    29: [
        ("וְהַנּוֹתָר", "ובאקיה", "And the remainder of it"),
        ("יִתֵּן", "יצ'בה כ", "he shall pour"),
        ("עַל-רֹאשׁ", "עלי' ראס", "upon the head of"),
        ("הַמִּטַּהֵר", "אלמתטהר", "the one being purified"),
        ("לְכַפֵּר עָלָיו", "ויסתג'פר ענה", "and shall seek forgiveness for him"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    30: [
        (None, "ת'ם", "Then"),
        ("וְעָשָׂה", "יעמל", "he shall perform"),
        ("אֶת-הָאֶחָד", "ואחד", "one"),
        ("מִן-הַתֹּרִים", "מן אלשפאנין", "of the turtle-doves"),
        ("אוֹ", "או", "or"),
        ("מִן-בְּנֵי הַיּוֹנָה", "מן פרכ'י אלחמאם", "of the young pigeons"),
        ("מֵאֲשֶׁר תַּשִּׂיג יָדוֹ", "עלי' מא תנאל ידה", "according to what his hand can reach"),
    ],
    31: [
        ("אֵת אֲשֶׁר-תַּשִּׂיג יָדוֹ", "מע מא תנאל ידה", "According to what his hand can reach"),
        ("אֶת-הָאֶחָד חַטָּאת", "אחדהמא ד'כוה", "one of them a purification-offering"),
        ("וְאֶת-הָאֶחָד עֹלָה", "ואלאכ'ר צעידה", "and the other an ascending-offering"),
        ("עַל-הַמִּנְחָה", "מע אלהדייה", "together with the gift-offering"),
        ("וְכִפֶּר", "ויסתג'פר", "and he shall seek forgiveness"),
        (None, "ענה", "for him"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    32: [
        ("זֹאת תּוֹרַת", "הד'ה שריעה'", "This is the law for"),
        ("אֲשֶׁר-בּוֹ נֶגַע", "מן כאן בה בלא", "one who has had the affliction of"),
        ("צָרָעַת", "ברץ", "leprosy"),
        ("אֲשֶׁר לֹא-תַשִּׂיג יָדוֹ", "ולם תנאל ידה", "whose hand has not reached to that"),
        ("בְּטָהֳרָתוֹ", "פי וקת טהרה", "at the time of his purification"),
    ],
    33: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי''", "to Moses"),
        ("וְאֶל-אַהֲרֹן", "והרון", "and Aaron"),
        ("לֵאמֹר", "תכלימא", "directly"),
    ],
    34: [
        ("כִּי תָבֹאוּ", "אד'א דכ'לתם", "When you enter"),
        ("אֶל-אֶרֶץ", "אלי' בלד", "the land of"),
        ("כְּנַעַן", "כנעאן", "Canaan"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("אֲנִי", "אנא", "I"),
        ("נֹתֵן", "מעטיכמוהא", "am giving you"),
        ("לַאֲחֻזָּה", "חוזא", "as a possession"),
        ("וְנָתַתִּי", "פאחללת", "and I bring about"),
        ("נֶגַע צָרַעַת", "בלא ברץ", "an affliction of leprosy"),
        (None, "פי", "in"),
        ("בְּבֵית אֶרֶץ", "בעץ' ביות ארץ'", "some of the houses of the land of"),
        ("אֲחֻזַּתְכֶם", "חוזכם", "your possession"),
    ],
    35: [
        ("וּבָא", "פליאת", "then the owner"),
        ("אֲשֶׁר-לוֹ הַבַּיִת", "אלד'י לה אלבית", "of the house shall come"),
        ("וְהִגִּיד", "ויכ'בר", "and inform"),
        ("לַכֹּהֵן", "אלאמאם", "the imām"),
        ("לֵאמֹר", "קאילא", "saying"),
        ("כְּנֶגַע נִרְאָה לִי", "קד צ'הר לי", "There has appeared to me"),
        ("בַּבָּיִת", "פי אלבית", "in the house"),
        (None, "שבה בלא", "something resembling an affliction"),
    ],
    36: [
        ("וְצִוָּה", "פיאמר", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall give the order,"),
        ("וּפִנּוּ", "וינגלו", "and they shall clear"),
        ("אֶת-הַבַּיִת", "אלבית", "the house"),
        ("בְּטֶרֶם", "קבל אן", "before"),
        ("יָבֹא", "ידכ'ל", "he enters"),
        ("לִרְאוֹת", "לינצר", "to inspect"),
        ("אֶת-הַנֶּגַע", "אלבלא", "the affliction,"),
        ("וְלֹא יִטְמָא", "ולא ינג'ס", "so that nothing in it"),
        ("כָּל-אֲשֶׁר בַּבָּיִת", "גמיע מא פיה", "be made impure;"),
        ("וְאַחַר כֵּן", "ובעד ד'אלך", "and after that"),
        ("יָבֹא", "ידכ'ל", "he shall enter"),
        ("לִרְאוֹת", "וינצ'ר", "and look"),
        ("אֶת-הַבָּיִת", "אליה", "upon it"),
    ],
    37: [
        (None, "פאן", "And if"),
        ("וְרָאָה", "ראי'", "he sees"),
        ("אֶת-הַנֶּגַע", "אלבלא", "the affliction"),
        (None, "פאד'אה", "behold, it is"),
        ("בְּקִירֹת", "פי חיטאן", "in the walls of"),
        ("הַבַּיִת", "אלבית", "the house"),
        ("שְׁקַעֲרוּרֹת יְרַקְרַקֹּת", "כ'טוט מ'כ'צרה", "as streaks of greenish"),
        ("אוֹ", "או", "or"),
        ("אֲדַמְדַּמֹּת", "מחמרה", "reddish hue,"),
        ("וּמַרְאֵיהֶן", "ומנצ'רהן", "and their appearance"),
        ("שָׁפָל", "מסתפל", "is sunken"),
        ("מִן-הַקִּיר", "פי אלחאיט", "in the wall"),
    ],
    38: [
        ("וְיָצָא", "פליכ'רג", "then let him go out"),
        ("מִן-הַבַּיִת", "מן אלבית", "from the house"),
        ("אֶל-פֶּתַח הַבָּיִת", "אלי' באבה", "to its doorway"),
        ("וְהִסְגִּיר", "ויוקפה", "and quarantine it"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "for seven days"),
    ],
    39: [
        (None, "ת'ם", "Then"),
        ("וְשָׁב", "ירגע", "he shall return"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "פי אליום אלסאבע", "on the seventh day"),
        (None, "פאן", "and if"),
        ("וְרָאָה", "ראי'", "he sees"),
        ("הַנֶּגַע", "אלבלא", "the affliction"),
        (None, "קד", "has"),
        ("פָּשָׂה", "תפשא", "spread"),
        ("בְּקִירֹת הַבָּיִת", "פי חיטאן אלבית", "in the walls of the house"),
    ],
    41: [
        ("וְאֶת-הַבַּיִת יַקְצִעַ", "ויקשר אלבית", "And the house shall be scraped"),
        ("מִבַּיִת סָבִיב", "מן דאכ'ל מסתדירא", "on the inside all around"),
        ("וְשָׁפְכוּ", "וירמו", "and they shall cast"),
        ("אֶת-הֶעָפָר", "אלתראב", "the plaster"),
        ("אֲשֶׁר הִקְצוּ", "אלד'י קשרוה", "which they have scraped"),
        ("אֶל-מִחוּץ לָעִיר", "כ'ארג אלקריה", "outside the town"),
        ("אֶל-מָקוֹם טָמֵא", "פי מוצ'ע נגס", "into an impure place"),
    ],
    42: [
        ("וְלָקְחוּ", "ויאכ'דו", "And they shall take"),
        ("אֲבָנִים אֲחֵרוֹת", "חגאר אכ'ר", "other stones"),
        ("וְהֵבִיאוּ", "וידכ'לוהא", "and bring them"),
        ("אֶל-תַּחַת הָאֲבָנִים", "מוצ'ע תלך אלחגארה", "in place of those stones"),
        ("וְעָפָר אַחֵר", "ותראב אכ'ר", "and fresh plaster"),
        ("יִקַּח", "יוכ'ד'", "shall be taken"),
        ("וְטָח", "ויטיין", "and the house shall be"),
        ("אֶת-הַבָּיִת", "אלבית", "re-plastered"),
    ],
    43: [
        ("וְאִם-יָשׁוּב", "ואן עאד", "And if the affliction"),
        ("הַנֶּגַע", "אלבלא", "returns"),
        ("וּפָרַח", "ואנתשר", "and spreads"),
        ("בַּבַּיִת", "פי אלבית", "in the house"),
        ("אַחַר", "בעד מא", "after"),
        ("חִלֵּץ אֶת-הָאֲבָנִים", "כ'לעת אלחגארה", "the stones have been removed"),
        ("וְאַחֲרֵי הִקְצוֹת אֶת-הַבַּיִת", "ובעד מא קשר אלבית", "and after the house has been scraped"),
        ("וְאַחֲרֵי הִטּוֹחַ", "וטיין", "and re-plastered"),
    ],
    44: [
        ("וּבָא", "פדכ'ל", "then the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall enter"),
        ("וְרָאָה", "פנצ'ר", "and look"),
        (None, "פאד'א", "and behold"),
        ("פָּשָׂה הַנֶּגַע", "קד תפשא אלבלא", "if the affliction has spread"),
        ("בַּבַּיִת", "פי אלבית", "in the house"),
        ("צָרַעַת מַמְאֶרֶת", "פהו ברץ מאחק", "it is a consuming leprosy"),
        (None, "פי אלבית", "in the house"),
        ("טָמֵא הוּא", "והו נגס", "it is impure"),
    ],
    45: [
        ("וְנָתַץ", "פלינקצ'ה", "And let him demolish it"),
        ("אֶת-אֲבָנָיו", "מן חגארה", "its stones"),
        ("וְאֶת-עֵצָיו", "וכ'שבה", "and its timber"),
        ("וְאֵת כָּל-עֲפַר הַבָּיִת", "וגמיע תראבה", "and all its plaster"),
        ("וְהוֹצִיא", "וירמי ד'אלך", "and cast that"),
        ("אֶל-מִחוּץ לָעִיר", "אלי' כ'ארג אלקריה", "outside the town"),
        ("אֶל-מָקוֹם טָמֵא", "אלי' מוצ'ע נגס", "into an impure place"),
    ],
    46: [
        ("וְהַבָּא", "ומן דכ'ל", "And whoever enters"),
        ("אֶל-הַבַּיִת", "אלי' אלבית", "the house"),
        ("כָּל-יְמֵי", "טול אלאייאם", "throughout all the days"),
        ("הִסְגִּיר אֹתוֹ", "אלד'י אוקף פיהא", "during which it is in quarantine"),
        ("יִטְמָא", "פלינגס", "shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the evening"),
    ],
    47: [
        ("וְהַשֹּׁכֵב בַּבַּיִת", "ומן אנצ'גע פיה", "And whoever lies down in it"),
        ("יְכַבֵּס אֶת-בְּגָדָיו", "פליג'סל ת'יאבה", "shall wash his garments"),
        (None, "וכד'לך", "and likewise"),
        ("וְהָאֹכֵל בַּבַּיִת", "כל מן אכל פיה", "everyone who eats in it"),
        ("יְכַבֵּס אֶת-בְּגָדָיו", "פליג'סל ת'יאבה", "shall wash his garments"),
    ],
    48: [
        (None, "פאן", "And if"),
        ("בֹּא יָבֹא", "דכ'ל", "enters"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("וְרָאָה", "פנצ'ר", "and looks"),
        ("לֹא-פָשָׂה הַנֶּגַע", "פאד'י לם יתפש אלבלא", "the affliction has not spread"),
        ("בַּבַּיִת", "פי אלבית", "in the house"),
        ("אַחֲרֵי הִטֹּחַ", "בעד מא טיין", "after the plastering"),
        ("וְטִהַר הַכֹּהֵן", "פליטהרה", "then let him declare it pure"),
        ("כִּי נִרְפָּא הַנָּגַע", "פאן אלבלא קד ברא", "for the affliction has healed"),
    ],
    49: [
        ("וְלָקַח", "ויאכ'ד'", "And he shall take"),
        ("לְחַטֵּא", "לתד'כיתה", "for its purification-offering"),
        ("שְׁתֵּי צִפֳּרִים", "עצפורין", "two sparrows"),
        ("וְעֵץ אֶרֶז", "ועוד ארז", "and a cedar rod"),
        ("וּשְׁנִי תוֹלַעַת", "וחריר קרמז", "and crimson silk"),
        ("וְאֵזֹב", "וצעתר", "and hyssop"),
    ],
    50: [
        ("וְשָׁחַט", "ויד'בח", "And he shall slaughter"),
        ("אֶת-הַצִּפֹּר הָאֶחָת", "אחדהמא", "one of them"),
        (None, "פי", "in"),
        ("אֶל-כְּלִי-חֶרֶשׂ", "אנא כ'זף", "a clay vessel"),
        ("עַל-מַיִם חַיִּים", "מע מא מן נביע", "over water from a spring"),
    ],
    51: [
        ("וְלָקַח", "ויאכ'ד'", "And he shall take"),
        ("אֶת-עֵץ-הָאֶרֶז", "עוד אלארז", "the cedar rod"),
        ("וְאֶת-הָאֵזֹב", "ואלצעתר", "and the hyssop"),
        ("וְאֵת שְׁנִי הַתּוֹלַעַת", "וחריר אלקרמז", "and the crimson silk"),
        ("וְאֵת הַצִּפֹּר הַחַיָּה", "ואלעצפור אלחי", "and the living sparrow"),
        ("וְטָבַל אֹתָם", "ויג'מסהא", "and shall dip them"),
        ("בְּדַם", "פי דם", "in the blood of"),
        ("הַצִּפֹּר הַשְּׁחוּטָה", "אלעצפור אלמד'בוח", "the slaughtered sparrow"),
        ("וּבַמַּיִם הַחַיִּים", "ואלמא אלד'י מן נביע", "and in the water from a spring"),
        ("וְהִזָּה", "וינצ'חה", "and shall sprinkle it"),
        ("אֶל-הַבַּיִת", "עלי' אלבית", "upon the house"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
    ],
    52: [
        ("וְחִטֵּא", "ויד'כיה", "And he shall declare it pure"),
        ("בְּדַם הַצִּפּוֹר", "בדם אלעצפור אלמד'בוח", "by means of the blood of the slaughtered sparrow"),
        ("וּבַמַּיִם הַחַיִּים", "ואלמא אלנביע", "and the spring water"),
        ("וּבַצִּפֹּר הַחַיָּה", "ואלעצפור אלחי", "and the living sparrow"),
        ("וּבְעֵץ הָאֶרֶז", "ואלעוד אלארז", "and the cedar rod"),
        ("וּבָאֵזֹב", "ואלצעתר", "and the hyssop"),
        ("וּבִשְׁנִי הַתּוֹלָעַת", "וחריר אלקרמז", "and the crimson silk"),
    ],
    53: [
        ("וְשִׁלַּח", "ויטלק", "And he shall release"),
        ("אֶת-הַצִּפֹּר הַחַיָּה", "אלעצפור אלחי", "the living sparrow"),
        ("אֶל-מִחוּץ לָעִיר", "כ'ארג אלקריה", "outside the town"),
        ("אֶל-פְּנֵי הַשָּׂדֶה", "אלי' וגה אלצחרי", "toward the face of the wilderness"),
        ("וְכִפֶּר", "ויסתג'פר", "and shall seek forgiveness"),
        ("עַל-הַבַּיִת", "ען מא פי אלבית", "for what is in the house"),
        ("וְטָהֵר", "ויטהר", "and it shall be pure"),
    ],
    54: [
        ("זֹאת", "הד'ה", "This"),
        ("הַתּוֹרָה", "שריעה'", "is the law"),
        ("לְכָל-נֶגַע", "גמיע בלא", "for all affliction of"),
        ("הַצָּרַעַת", "אלברץ", "leprosy"),
        ("וְלַנָּתֶק", "ואלכ'לף", "and of the scall"),
    ],
    55: [
        ("וּלְצָרַעַת", "וברץ", "and the leprosy of"),
        ("הַבֶּגֶד", "אלת'יאב", "garments"),
        ("וְלַבָּיִת", "ואלביות", "and of houses"),
    ],
    56: [
        ("וְלַשְׂאֵת", "ואלשאמה", "and the blemish"),
        ("וְלַסַּפַּחַת", "ואלעארצ'ה", "and the spreading mark"),
        ("וְלַבֶּהָרֶת", "ואלבקעה", "and the spot"),
    ],
    57: [
        ("לְהוֹרֹת", "תדל", "to indicate"),
        ("בְּיוֹם הַטָּמֵא", "עלי' וקת אלתנגיס", "the time of becoming impure"),
        ("וּבְיוֹם הַטָּהֹר", "ווקת אלתטהיר", "and the time of purification"),
        ("זֹאת תּוֹרַת הַצָּרָעַת", "וכלהא שראיע אלברץ", "These are all the laws of leprosy"),
    ],
}
