"""Hand-authored alignment triples for Vayikra chapter 11.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "פ", "And"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("וְאֶל-אַהֲרֹן", "והרון", "and Aaron"),
        (None, "וקאל", "and said"),
        ("אֲלֵהֶם", "להמא", "to them"),
    ],
    2: [
        ("דַּבְּרוּ", "כלמא", "Speak"),
        ("אֶל-בְּנֵי", "בני", "to the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("לֵאמֹר", "וקולא", "and say"),
        (None, "להם", "to them"),
        ("זֹאת", "הד'א", "This is"),
        ("הַחַיָּה", "אלחיואן", "the animal"),
        (None, "אלד'י", "which"),
        (None, "יגוז", "it is permitted"),
        (None, "אן", "that"),
        ("תֹּאכְלוּ", "תאכלוה", "you eat"),
        ("מִכָּל", "מן גמיע", "from all"),
        ("הַבְּהֵמָה", "אלבהאים", "the beasts"),
        ("אֲשֶׁר", "אלתי", "that"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "walk upon the earth"),
    ],
    3: [
        ("כֹּל", "כל", "every one"),
        ("מַפְרֶסֶת", "מצ'לפה", "that is hoofed"),
        ("פַּרְסָה", "בצ'לף", "with a hoof"),
        ("וְשֹׁסַעַת", "ומפרק", "and whose hooves are divided"),
        ("שֶׁסַע פְּרָסֹת", "צ'לפהא תפריקא", "in a division"),
        ("מַעֲלַת", "ומצעדה", "and that brings up"),
        ("גֵּרָה", "אגתראר", "cud"),
        ("בַּבְּהֵמָה", "מן אלבהאים", "among the beasts"),
        ("אֹתָהּ תֹּאכֵלוּ", "פכלוהא", "eat it"),
    ],
    4: [
        (None, "ואמא", "But"),
        ("אַךְ אֶת-זֶה", "הד'א", "this"),
        ("לֹא תֹאכְלוּ", "פלא תאכלוה", "you shall not eat, from those that bring up cud"),
        ("מִמַּעֲלֵי הַגֵּרָה", "מן אלמצעדי אלאגתראר", "and those that are divided of hoof"),
        ("וּמִמַּפְרִסֵי הַפַּרְסָה", "ואלמפרק אלצלף", "the camel"),
        ("אֶת-הַגָּמָל", "אלגמל", "for it brings up cud"),
        ("כִּי-מַעֲלֵה גֵרָה", "פאנה מצעד אגתראר", "yet"),
        ("וּפַרְסָה אֵינֶנּוּ מַפְרִיס", "ג'יר מצ'לף בצ'לף", "is not hoofed with a hoof"),
        ("טָמֵא הוּא", "והו נגס", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    5: [
        ("וְאֶת-הַשָּׁפָן", "ואלובר", "And the hyrax"),
        (None, "פ", "for it"),
        (None, "אנה", "brings up"),
        ("כִּי-מַעֲלֵה", "מצעד", "cud"),
        ("גֵרָה", "אגתראר", "yet"),
        ("וּפַרְסָה לֹא יַפְרִיס", "ג'יר מצ'לף בצ'לף", "is not hoofed with a hoof"),
        ("טָמֵא הוּא", "והו נגס", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    6: [
        ("וְאֶת-הָאַרְנֶבֶת", "ואלארנב", "And the hare"),
        (None, "פ", "for"),
        (None, "אנהא", "it"),
        ("כִּי-מַעֲלַת", "מצעדה", "brings up"),
        ("גֵּרָה", "אגתראר", "cud"),
        ("וּפַרְסָה לֹא הִפְרִיסָה", "והי ג'יר מצ'לפה", "yet it is not hoofed"),
        ("טְמֵאָה", "והי נגסה", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    7: [
        ("וְאֶת-הַחֲזִיר", "ואלכ'נזיר", "And the swine"),
        (None, "פ", "for"),
        (None, "אנה", "it"),
        ("כִּי-מַפְרִיס", "מצ'לף", "is hoofed"),
        ("פַּרְסָה", "בצ'לף", "with a hoof"),
        ("וְשֹׁסַע", "וצ'לפה מפרק", "and its hoof is divided"),
        ("שֶׁסַע פַּרְסָה", "תפריקא", "in a division"),
        ("וְהוּא גֵּרָה", "והו אגתראר", "yet it is one"),
        ("לֹא-יִגָּר", "לא יגתר", "that does not chew cud"),
        ("טָמֵא", "פהו נגס", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    8: [
        ("מִבְּשָׂרָם", "מן לחומהא", "Of their flesh"),
        ("לֹא תֹאכֵלוּ", "לא תאכלו", "you shall not eat"),
        ("וּבְנִבְלָתָם", "ובנבאילהא", "and to their carcasses"),
        ("לֹא תִגָּעוּ", "לא תדנו", "you shall not approach"),
        (None, "כד'אך", "thus"),
        ("טְמֵאִים", "הי נגסה", "they are impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    9: [
        ("אֶת-זֶה", "הד'א", "This"),
        (None, "מא", "is what"),
        (None, "יגוז", "it is permitted"),
        (None, "אן", "that"),
        ("תֹּאכְלוּ", "תאכלוה", "you eat"),
        ("מִכֹּל", "מן גמיע", "from all"),
        ("אֲשֶׁר בַּמָּיִם", "מא פי אלמא", "that is in the water"),
        ("כֹּל", "כל", "everything"),
        (None, "מא", "that"),
        ("אֲשֶׁר-לוֹ", "לה", "has"),
        ("סְנַפִּיר", "אגנחה", "fins"),
        ("וְקַשְׂקֶשֶׂת", "ופלוס", "and scales"),
        ("בַּמַּיִם", "פי אלמא", "in the water"),
        ("בַּיַּמִּים", "פי אלבחאר", "in the seas"),
        ("וּבַנְּחָלִים", "ואלאודיה", "and the wadis"),
        ("אֹתָם תֹּאכֵלוּ", "פכלוה", "eat it"),
    ],
    10: [
        ("וְכֹל", "וכל", "But everything"),
        (None, "מא", "that"),
        ("אֲשֶׁר אֵין-לוֹ", "ליס לה", "has no"),
        ("סְנַפִּיר", "אגנחה", "fins"),
        ("וְקַשְׂקֶשֶׂת", "ופלוס", "and scales"),
        ("בַּיַּמִּים", "פי אלבחאר", "in the seas"),
        ("וּבַנְּחָלִים", "ואלאודיה", "and the wadis"),
        ("מִכֹּל", "מן גמיע", "from all"),
        ("שֶׁרֶץ הַמַּיִם", "דביב אלמא", "the creeping things of the water"),
        ("וּמִכֹּל", "וגמיע", "and all"),
        ("נֶפֶשׁ הַחַיָּה", "אלחיואן", "the animals"),
        ("אֲשֶׁר בַּמָּיִם", "אלד'י פי אלמא", "that are in the water"),
        ("שֶׁקֶץ", "פהו רגס", "it is an abomination"),
        ("לָכֶם", "לכם", "for you"),
    ],
    11: [
        ("וְשֶׁקֶץ יִהְיוּ", "וכונהא ארגאס", "Their being abominations"),
        ("לָכֶם", "לכם", "for you"),
        ("מִבְּשָׂרָם", "מן לחומהא", "of their flesh"),
        ("לֹא תֹאכֵלוּ", "לא תאכלו", "you shall not eat"),
        ("וְאֶת-נִבְלָתָם", "ונבאילהא", "and their carcasses"),
        ("תְּשַׁקֵּצוּ", "תרגסו", "you shall treat as abominations"),
    ],
    12: [
        (None, "כד'אך", "Thus"),
        ("כֹּל", "כל", "everything"),
        (None, "מא", "that"),
        ("אֲשֶׁר אֵין-לוֹ", "ליס לה", "has no"),
        ("סְנַפִּיר", "אגנחה", "fins"),
        ("וְקַשְׂקֶשֶׂת", "ופלוס", "and scales"),
        ("בַּמָּיִם", "פי אלמא", "in the water"),
        ("שֶׁקֶץ", "פהו רגס", "it is an abomination"),
        ("לָכֶם", "לכם", "for you"),
    ],
    13: [
        ("וְאֶת-אֵלֶּה", "והד'א", "And these"),
        (None, "מא", "are what"),
        ("תְּשַׁקְּצוּ", "תרגסו", "you shall treat as abominations"),
        ("מִן-הָעוֹף", "מן אלטאיר", "from the birds"),
        ("לֹא יֵאָכְלוּ", "לא יוכלו", "they shall not be eaten"),
        (None, "אנהא", "for they are"),
        ("שֶׁקֶץ הֵם", "ארגאס", "abominations"),
        ("אֶת-הַנֶּשֶׁר", "אלנסר", "the vulture"),
        ("וְאֶת-הַפֶּרֶס", "ואלעקאב", "and the eagle"),
        ("וְאֵת הָעָזְנִיָּה", "ואלענקא", "and the 'anqah"),
    ],
    14: [
        ("וְאֶת-הַדָּאָה", "ואלחדא", "And the kite"),
        ("וְאֶת-הָאַיָּה", "ואלצדא", "and the buzzard"),
        ("לְמִינָהּ", "באצנאפהא", "according to its kinds"),
    ],
    15: [
        ("אֵת כָּל-עֹרֵב", "וגמיע אלג'ראביב", "And all the ravens"),
        ("לְמִינוֹ", "באצנאפהא", "according to their kinds"),
    ],
    16: [
        ("וְאֵת בַּת הַיַּעֲנָה", "ואלנעאמה", "And the ostrich"),
        ("וְאֶת-הַתַּחְמָס", "ואלכ'טאף", "and the swift"),
        ("וְאֶת-הַשָּׁחַף", "ואלסאף", "and the 'saf'"),
        ("וְאֶת-הַנֵּץ", "ואלבאז", "and the hawk"),
        ("לְמִינֵהוּ", "לאצנאפה", "according to its kinds"),
    ],
    17: [
        ("וְאֶת-הַכּוֹס", "ואלבום", "And the owl"),
        ("וְאֶת-הַשָּׁלָךְ", "ואלזמג", "and the cormorant"),
        ("וְאֶת-הַיַּנְשׁוּף", "ואלבאשק", "and the eagle-owl"),
    ],
    18: [
        ("וְאֶת-הַתִּנְשֶׁמֶת", "ואלשאהין", "And the falcon"),
        ("וְאֶת-הַקָּאָת", "ואלקו", "and the pelican"),
        ("וְאֶת-הָרָחָם", "ואלרכ'ם", "and the vulture"),
    ],
    19: [
        ("וְאֵת הַחֲסִידָה", "ואלצקר", "And the saker"),
        ("הָאֲנָפָה", "ואלבג'בג'ה", "and the parrot"),
        ("לְמִינָהּ", "באצנאפהא", "according to its kinds"),
        ("וְאֶת-הַדּוּכִיפַת", "ואלהדהד", "and the hoopoe"),
        ("וְאֶת-הָעֲטַלֵּף", "ואלכ'פאש", "and the bat"),
    ],
    20: [
        ("כֹּל", "וגמיע", "And all"),
        ("שֶׁרֶץ הָעוֹף", "דביב אלטאיר", "the creeping things of the birds"),
        ("הַהֹלֵךְ", "אלסאלך", "that walk"),
        ("עַל-אַרְבַּע", "עלי' ארבע", "on four"),
        ("שֶׁקֶץ", "רגס", "an abomination"),
        (None, "הו", "it is"),
        ("לָכֶם", "לכם", "for you"),
    ],
    21: [
        (None, "ו", "But"),
        ("אַךְ אֶת-זֶה", "הד'א", "this"),
        (None, "מא", "is what"),
        (None, "יגוז", "it is permitted"),
        (None, "אן", "that"),
        ("תֹּאכְלוּ", "תאכלוה", "you eat"),
        ("מִכֹּל", "מן גמיע", "from all"),
        ("שֶׁרֶץ הָעוֹף", "דביב אלטאיר", "the creeping things of the birds"),
        ("הַהֹלֵךְ", "אלסאלך", "that walk"),
        ("עַל-אַרְבַּע", "עלי' ארבע", "on four"),
        (None, "מא", "whatever"),
        ("אֲשֶׁר-לא (לוֹ)", "לה", "has"),
        ("כְרָעַיִם", "כראעין", "two jumping-legs"),
        ("מִמַּעַל", "פוק", "above"),
        ("לְרַגְלָיו", "רגליה", "its feet"),
        ("לְנַתֵּר", "לית'ב", "with which to leap"),
        ("בָּהֵן", "בהמא", "upon"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "the earth"),
    ],
    22: [
        ("אֶת-אֵלֶּה", "הד'א", "These are"),
        (None, "מא", "what"),
        ("תֹּאכֵלוּ", "תאכלוה", "you may eat"),
        ("מֵהֶם", "מנהא", "from them"),
        ("אֶת-הָאַרְבֶּה", "אלגראד", "the locust"),
        ("לְמִינוֹ", "וצנופה", "and its kinds"),
        ("וְאֶת-הַסָּלְעָם", "ואלדבא", "and the duba"),
        ("לְמִינֵהוּ", "וצנופה", "and its kinds"),
        ("וְאֶת-הַחַרְגֹּל", "ואלחרגל", "and the harjal"),
        ("לְמִינֵהוּ", "וצנופה", "and its kinds"),
        ("וְאֶת-הֶחָגָב", "ואלגנדב", "and the grasshopper"),
        ("לְמִינֵהוּ", "וצנופה", "and its kinds"),
    ],
    23: [
        ("וְכֹל", "וסאיר", "And the rest of"),
        ("שֶׁרֶץ הָעוֹף", "דביב אלטאיר", "the creeping things of the birds"),
        ("אֲשֶׁר-לוֹ", "אלד'י לה", "that have"),
        ("אַרְבַּע", "ארבע", "four"),
        ("רַגְלָיִם", "ארגל", "legs"),
        ("שֶׁקֶץ", "פהו רגס", "it is an abomination"),
        ("לָכֶם", "לכם", "for you"),
    ],
    24: [
        ("וּלְאֵלֶּה", "ומן הד'ה", "And by these"),
        ("תִּטַּמָּאוּ", "פאנגסו", "you shall become impure"),
        ("כָּל-הַנֹּגֵעַ", "כל מן דנא", "every one who approaches"),
        ("בְּנִבְלָתָם", "בנבאילהם", "their carcasses"),
        (None, "יג'סל", "shall wash"),
        (None, "ת'יאבה", "his garments"),
        (None, "ו", "and"),
        ("יִטְמָא", "ינגס", "be impure"),
        (None, "אלי'", "until"),
        ("עַד-הָעָרֶב", "אלמגיב", "the setting"),
    ],
    25: [
        ("וְכָל-הַנֹּשֵׂא", "וכל מן חמל", "And every one who carries"),
        ("מִנִּבְלָתָם", "מן נבאילהם", "from their carcasses"),
        ("יְכַבֵּס", "גסל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
    ],
    26: [
        ("לְכָל-הַבְּהֵמָה", "מן גמיע אלבהאים", "From all the beasts"),
        ("אֲשֶׁר הִוא", "אלתי הי", "that are"),
        ("מַפְרֶסֶת", "מצ'לפה", "hoofed"),
        ("פַּרְסָה", "בצ'לף", "with a hoof"),
        ("וְשֶׁסַע אֵינֶנָּה שֹׁסַעַת", "ותפריק ליסהא מפרקה", "yet division is not in them as divided"),
        ("וְגֵרָה אֵינֶנָּה מַעֲלָה", "ואגתראר ליסהא מצעדה", "and cud-chewing is not in them as bringing up"),
        ("טְמֵאִים", "פהי נגסה", "they are impure"),
        ("לָכֶם", "לכם", "for you"),
        ("כָּל-הַנֹּגֵעַ", "כל מן דנא", "every one who approaches"),
        ("בָּהֶם", "בהא", "them"),
        ("יִטְמָא", "ינגס", "shall be impure"),
    ],
    27: [
        ("וְכֹל", "וכל", "And every one"),
        ("הוֹלֵךְ", "סאלך", "that walks"),
        ("עַל-כַּפָּיו", "עלי' כפיה", "on its paws"),
        ("בְּכָל-הַחַיָּה", "מן גמיע אלוחש", "from all the wild creatures"),
        ("הַהֹלֶכֶת", "אלסאלך", "that walk"),
        ("עַל-אַרְבַּע", "עלי' ארבע", "on four"),
        ("טְמֵאִים", "פהו נגס", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
        ("כָּל-הַנֹּגֵעַ", "כל מן דנא", "every one who approaches"),
        ("בְּנִבְלָתָם", "בנבאילהם", "their carcasses"),
        ("יִטְמָא", "ינגס", "shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
    ],
    28: [
        ("וְהַנֹּשֵׂא", "ומן חמל", "And whoever carries"),
        ("אֶת-נִבְלָתָם", "מן נבאילהם", "from their carcasses"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
        (None, "כד'אך", "Thus"),
        ("טְמֵאִים הֵמָּה", "הי אנגאס", "they are impurities"),
        ("לָכֶם", "לכם", "for you"),
    ],
    29: [
        (None, "ו", "And"),
        ("וְזֶה", "הד'א", "this"),
        ("לָכֶם", "לכם", "is what"),
        ("הַטָּמֵא", "אלנגס", "is impure for you"),
        ("בַּשֶּׁרֶץ", "מן אלדביב", "from the creeping things"),
        ("הַשֹּׁרֵץ", "אלדאב", "that creep"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
        ("הַחֹלֶד", "אלכ'לד", "the mole"),
        ("וְהָעַכְבָּר", "ואלפאר", "and the mouse"),
        ("וְהַצָּב", "ואלצ'ב", "and the spiny lizard"),
        ("לְמִינֵהוּ", "ואצנאפה", "according to its kinds"),
    ],
    30: [
        ("וְהָאֲנָקָה", "ואלורל", "And the monitor lizard"),
        ("וְהַכֹּחַ", "ואלחרדון", "and the gecko"),
        ("וְהַלְּטָאָה", "ואלעצ'איה", "and the chameleon"),
        ("וְהַחֹמֶט", "ואלחרבא", "and the agama"),
        ("וְהַתִּנְשָׁמֶת", "ואלסמברץ", "and the skink"),
    ],
    31: [
        ("אֵלֶּה", "הד'א", "These are"),
        ("הַטְּמֵאִים", "אלנגסה", "the impure"),
        ("לָכֶם", "לכם", "for you"),
        ("בְּכָל-הַשָּׁרֶץ", "מן גמיע אלדביב", "from all the creeping things"),
        ("כָּל-הַנֹּגֵעַ", "כל מן דנא", "every one who approaches"),
        ("בָּהֶם", "בהא", "them"),
        (None, "פי", "at"),
        ("בְּמֹתָם", "חאל מותהא", "the time of their death"),
        ("יִטְמָא", "ינגס", "shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
    ],
    32: [
        ("וְכֹל", "וכל", "And everything"),
        (None, "מן", "upon which"),
        ("אֲשֶׁר-יִפֹּל-עָלָיו", "וקע עלי'ה", "falls"),
        ("מֵהֶם", "מנהא", "any of them"),
        ("בְּמֹתָם", "בעד מותהא", "after their death"),
        ("יִטְמָא", "ינגס", "shall be impure"),
        ("מִכָּל-כְּלִי-עֵץ", "מן גמיע אניה' אלכ'שב", "from any vessel of wood"),
        ("אוֹ בֶגֶד", "או ת'וב", "or cloth"),
        ("אוֹ-עוֹר", "או גלד", "or leather"),
        ("אוֹ שָׂק", "או מסח", "or sacking"),
        ("כָּל-כְּלִי", "וכל אניה", "and every vessel"),
        ("אֲשֶׁר-יֵעָשֶׂה מְלָאכָה בָּהֶם", "יעמל בהא צנאעה", "with which work is done"),
        ("בַּמַּיִם יוּבָא", "ידכ'ל פי אלמא", "shall be brought into the water"),
        ("וְטָמֵא", "וינגס", "and shall be impure"),
        ("עַד-הָעֶרֶב", "אלי' אלמג'יב", "until the setting"),
        ("וְטָהֵר", "ויטהר", "and then it shall be pure"),
    ],
    33: [
        ("וְכָל-כְּלִי-חֶרֶשׂ", "וכל אנא כ'זף", "And any earthen vessel"),
        ("אֲשֶׁר-יִפֹּל מֵהֶם אֶל-תּוֹכוֹ", "יקע מנהא שיא אלי' דאכ'לה", "into which anything of them falls"),
        ("כֹּל אֲשֶׁר בְּתוֹכוֹ", "כל מא פי דאכ'לה", "everything within it"),
        ("יִטְמָא", "ינגס", "shall be impure"),
        ("וְאֹתוֹ", "ואייאה", "and it itself"),
        ("תִשְׁבֹּרוּ", "פאכסרו", "you shall break"),
    ],
    34: [
        ("מִכָּל-הָאֹכֶל", "מן גמיע אלטעאם", "From all food"),
        ("אֲשֶׁר יֵאָכֵל", "אלד'י יוכל", "that is eaten"),
        ("אֲשֶׁר יָבוֹא עָלָיו", "ממא ידכ'לה", "if"),
        ("מַיִם", "אלמא", "water enters it"),
        ("יִטְמָא", "ינגס", "it shall be impure"),
        ("וְכָל-מַשְׁקֶה", "וגמיע אלשראב", "and all drink"),
        ("אֲשֶׁר יִשָּׁתֶה", "אלד'י ישרב", "that is drunk"),
        ("בְּכָל-כְּלִי", "פי כל אנא", "in any vessel"),
        ("יִטְמָא", "ינגס", "shall be impure"),
    ],
    35: [
        ("וְכֹל אֲשֶׁר-יִפֹּל מִנִּבְלָתָם עָלָיו", "וכל מא וקע מן נבאילהם עלי'ה", "And everything upon which any of their carcasses falls"),
        ("יִטְמָא", "ינגס", "shall be impure"),
        ("תַּנּוּר", "מן תנור", "whether an oven"),
        ("וְכִירַיִם", "ומסתוקד", "or a stove"),
        ("יֻתָּץ", "פאנקצ'והמא", "demolish them both"),
        (None, "לאנהא", "for they are"),
        ("טְמֵאִים הֵם", "נגסה", "impure"),
        (None, "וכד'אך", "and thus"),
        ("וּטְמֵאִים יִהְיוּ", "הי לכם", "they are impurities"),
        ("לָכֶם", "אנגאס", "for you"),
    ],
    36: [
        (None, "אמא", "But"),
        ("אַךְ מַעְיָן", "אלמעין", "a spring"),
        ("וּבוֹר", "ואלביר", "and a well"),
        ("מִקְוֵה-מַיִם", "ומלאם אלמא", "and a gathering of water"),
        ("יִהְיֶה טָהוֹר", "פיכון טאהרא", "shall remain pure"),
        ("וְנֹגֵעַ", "ומן דנא", "yet whoever approaches"),
        ("בְּנִבְלָתָם", "בנבאילהא", "their carcasses"),
        (None, "פיהא", "in it"),
        ("יִטְמָא", "ינגס", "shall be impure"),
    ],
    37: [
        (None, "ו", "And"),
        ("וְכִי יִפֹּל", "אן וקע", "if any"),
        ("מִנִּבְלָתָם", "מן נבאילהא", "of their carcasses falls"),
        ("עַל-כָּל-זֶרַע", "עלי' שי מן אלנבאת ואלחב", "upon any of the vegetation and grain"),
        ("זֵרוּעַ אֲשֶׁר יִזָּרֵעַ", "אלד'י יזרע", "that is sown"),
        ("טָהוֹר הוּא", "פהו טאהר", "it is pure"),
    ],
    38: [
        (None, "פ", "But"),
        ("וְכִי יֻתַּן-מַיִם", "אן געל מא", "if water has been placed"),
        ("עַל-זֶרַע", "עלי'הא", "upon it"),
        ("וְנָפַל", "ווקע", "and then"),
        ("מִנִּבְלָתָם", "מן נבאילהא", "any of their carcasses falls"),
        ("עָלָיו", "עלי'ה", "upon it"),
        ("טָמֵא", "פהו נגס", "it is impure"),
        ("לָכֶם", "לכם", "for you"),
    ],
    39: [
        (None, "ו", "And"),
        ("וְכִי יָמוּת", "אד'א מאת", "when there dies"),
        ("מִן-הַבְּהֵמָה", "מן אלחיואן", "from the animals"),
        ("אֲשֶׁר-הִיא", "אלד'י הו", "which"),
        (None, "טלק", "it is permitted"),
        ("לָכֶם לְאָכְלָה", "לכם אן תאכלוה", "for you to eat"),
        ("הַנֹּגֵעַ", "מן דנא", "whoever approaches"),
        ("בְּנִבְלָתָהּ", "בנבילתה", "its carcass"),
        ("יִטְמָא", "פינגס", "shall be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
    ],
    40: [
        ("וְהָאֹכֵל", "ומן אכל", "And whoever eats"),
        ("מִנִּבְלָתָהּ", "מנהא", "from it"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
        ("וְהַנֹּשֵׂא", "ומן חמל", "and whoever carries"),
        ("אֶת-נִבְלָתָהּ", "מנהא", "from it"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְטָמֵא", "וינגס", "and be impure"),
        ("עַד-הָעָרֶב", "אלי' אלמג'יב", "until the setting"),
    ],
    41: [
        ("וְכָל-הַשֶּׁרֶץ", "וגמיע אלדביב", "And all the creeping things"),
        ("הַשֹּׁרֵץ", "אלדאב", "that creep"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
        ("שֶׁקֶץ הוּא", "פהו רגס", "it is an abomination"),
        ("לֹא יֵאָכֵל", "לא יוכל", "it shall not be eaten"),
    ],
    42: [
        ("כֹּל הוֹלֵךְ", "וכל סאלך", "Every one that walks"),
        ("עַל-גָּחוֹן", "עלי' צדרה", "on its belly"),
        ("וְכֹל הוֹלֵךְ", "וכל סאלך", "and every one that walks"),
        ("עַל-אַרְבַּע", "עלי' ארבע", "on four"),
        ("עַד כָּל-מַרְבֵּה רַגְלַיִם", "למא כת'רה' ארגלה", "and whatever has many legs"),
        ("לְכָל-הַשֶּׁרֶץ", "מן גמיע אלדביב", "from all the creeping things"),
        ("הַשֹּׁרֵץ", "אלדאב", "that creep"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
        ("לֹא תֹאכְלוּם", "לא תאכלונהם", "do not eat them"),
        (None, "פ", "for"),
        ("כִּי-שֶׁקֶץ הֵם", "אנהם ארגאס", "they are abominations"),
    ],
    43: [
        ("אַל-תְּשַׁקְּצוּ", "ולא תרגסו", "And do not make"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "your souls"),
        (None, "בשי מן", "with anything of"),
        ("בְּכָל-הַשֶּׁרֶץ הַשֹּׁרֵץ", "אלדביב אלדאב", "the creeping things that creep"),
        ("וְלֹא תִטַּמְּאוּ", "ולא תתנגסו", "and do not defile yourselves"),
        ("בָּהֶם", "בהם", "with them"),
        (None, "פ", "lest"),
        ("וְנִטְמֵתֶם", "תעצוני", "you disobey Me"),
        ("בָּם", "בד'אלך", "thereby"),
    ],
    44: [
        (None, "ל", "For"),
        ("כִּי אֲנִי", "אני", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("וְהִתְקַדִּשְׁתֶּם", "פתקדסו", "sanctify yourselves"),
        ("וִהְיִיתֶם", "וכונו", "and be"),
        ("קְדֹשִׁים", "מקדסין", "holy"),
        (None, "פ", "for"),
        ("כִּי קָדוֹשׁ", "אני קדוס", "I am holy"),
        ("וְלֹא תְטַמְּאוּ", "ולא תנגסו", "and do not defile"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "your souls"),
        (None, "בשי מן", "with anything of"),
        ("בְּכָל-הַשֶּׁרֶץ", "אלדביב", "the creeping things"),
        ("הָרֹמֵשׂ", "אלדאב", "that creep"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
    ],
    45: [
        (None, "ל", "For"),
        ("כִּי אֲנִי", "אני", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("הַמַּעֲלֶה אֶתְכֶם", "אלמצעדכם", "who brought you up"),
        ("מֵאֶרֶץ", "מן בלד", "from the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("לִהְיֹת לָכֶם לֵאלֹהִים", "לאכון לכם אלאהא", "to be your God"),
        ("וִהְיִיתֶם", "פכונו", "so be"),
        ("קְדֹשִׁים", "מקדסין", "holy"),
        (None, "ל", "for"),
        ("כִּי קָדוֹשׁ אָנִי", "אני אלקדוס", "I am the Holy One"),
    ],
    46: [
        ("זֹאת", "הד'א", "This is"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הַבְּהֵמָה", "אלבהאים", "the beasts"),
        ("וְהָעוֹף", "ואלטאיר", "and the birds"),
        ("וְכֹל", "וגמיע", "and all"),
        ("נֶפֶשׁ הַחַיָּה", "נפוס אלחייה", "the living souls"),
        ("הָרֹמֶשֶׂת", "אלדאבה", "that creep"),
        ("בַּמָּיִם", "פי אלמא", "in the water"),
        ("וּלְכָל-נֶפֶשׁ", "וסאיר אלנפוס", "and the rest of the souls"),
        ("הַשֹּׁרֶצֶת", "אלדאבה", "that creep"),
        ("עַל-הָאָרֶץ", "עלי' אלארץ'", "upon the earth"),
    ],
    47: [
        ("לְהַבְדִּיל", "תפרז", "that you separate"),
        ("בֵּין הַטָּמֵא", "בין אלנגס", "between the impure"),
        ("וּבֵין הַטָּהֹר", "ואלטאהר", "and the pure"),
        ("וּבֵין הַחַיָּה הַנֶּאֱכֶלֶת", "ובין אלחיואן אלד'י יוכל", "and between the animal that may be eaten"),
        ("וּבֵין הַחַיָּה אֲשֶׁר לֹא תֵאָכֵל", "ואלד'י לא יוכל", "and that which may not be eaten"),
    ],
}
