"""Hand-authored alignment triples for Vayikra chapter 23."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל וקל להם",
         "Command the sons of Israel and say to them:"),
        ("מוֹעֲדֵי יְהוָה אֲשֶׁר-תִּקְרְאוּ אֹתָם מִקְרָאֵי קֹדֶשׁ",
         "אעיאד אללה. אלתי יגב אן תסמוהא באסמא כ'אצה",
         "the festivals of God, which you are obligated to designate by special names"),
        ("אֵלֶּה הֵם מוֹעֲדָי",
         "הד'ה הי אעיאדי",
         "these are My festivals."),
    ],
    3: [
        ("שֵׁשֶׁת יָמִים תֵּעָשֶׂה מְלָאכָה וּבַיּוֹם הַשְּׁבִיעִי שַׁבַּת שַׁבָּתוֹן מִקְרָא-קֹדֶשׁ",
         "סתה' אייאם תצנע אלצנאיע. ופי אליום אלסאבע עטלה הי סבת אסם מקדס",
         "Six days shall labors be performed, and on the seventh day is a desisting — it is a Sabbath, a consecrated name;"),
        ("כָּל-מְלָאכָה לֹא תַעֲשׂוּ שַׁבָּת הִוא לַיהוָה בְּכֹל מוֹשְׁבֹתֵיכֶם",
         "כל צנאעה לא תעמלו. כד'אך הי סבת ללה. פי גמיע מסאכנכם",
         "no labor shall you perform. Such is the Sabbath of God, in all your dwellings."),
    ],
    4: [
        ("אֵלֶּה מוֹעֲדֵי יְהוָה מִקְרָאֵי קֹדֶשׁ",
         "הד'ה אעיאד אללה. אלתי אסמאהא כ'אצה",
         "These are the festivals of God, which are designated by special names,"),
        ("אֲשֶׁר-תִּקְרְאוּ אֹתָם בְּמוֹעֲדָם",
         "אלתי יגב אן תסמוהא פי אוקאתהא",
         "which you are obligated to designate in their appointed times."),
    ],
    5: [
        ("בַּחֹדֶשׁ הָרִאשׁוֹן בְּאַרְבָּעָה עָשָׂר לַחֹדֶשׁ--בֵּין הָעַרְבָּיִם פֶּסַח לַיהוָה",
         "פי אלשהר אלאוול. פי אליום אלראבע עשר מנה בין אלג'רובין. פסחא ללה",
         "In the first month, on the fourteenth day of it, between the two sunsets — a Passover offering to God."),
    ],
    6: [
        ("וּבַחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הַזֶּה חַג הַמַּצּוֹת לַיהוָה",
         "ופי אליום אלכ'אמס עשר מן הד'א אלשהר. חג אלפטיר ללה",
         "And on the fifteenth day of this month is the festival of unleavened bread to God;"),
        ("שִׁבְעַת יָמִים מַצּוֹת תֹּאכֵלוּ",
         "סבעה' אייאם תאכלו פטירא",
         "seven days you shall eat unleavened bread."),
    ],
    7: [
        ("בַּיּוֹם הָרִאשׁוֹן מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם",
         "פי אליום אלאוול מנה. אסם מקדס יכון לכם",
         "On the first day of it, a consecrated name shall be for you;"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "כל צנעה' מכסב לא תעמלו",
         "no labor for profit shall you perform."),
    ],
    8: [
        ("וְהִקְרַבְתֶּם אִשֶּׁה לַיהוָה שִׁבְעַת יָמִים",
         "וקרבו קרבאנא ללה. פי הד'ה אלסבעה' אלאייאם",
         "And offer an offering to God during these seven days;"),
        ("בַּיּוֹם הַשְּׁבִיעִי מִקְרָא-קֹדֶשׁ כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "ופי אליום אלסאבע אסם מקדס. כל צנאעה' מכסב לא תעמלו",
         "and on the seventh day, a consecrated name — no labor for profit shall you perform."),
    ],
    9: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    10: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם כִּי-תָבֹאוּ אֶל-הָאָרֶץ אֲשֶׁר אֲנִי נֹתֵן לָכֶם",
         "מר בני אסראיל וקל להם. אד' תדכ'לון אלי' אלבלד. אלדי אנא מעטיכם",
         "Command the sons of Israel and say to them: when you enter the land which I am giving you,"),
        ("וּקְצַרְתֶּם אֶת-קְצִירָהּ--וַהֲבֵאתֶם אֶת-עֹמֶר רֵאשִׁית קְצִירְכֶם אֶל-הַכֹּהֵן",
         "פאחצדו מן זרעהא. ואיתו בג'מר. אוול חצאדכם אלי' אלאמאם",
         "and you reap its harvest, bring a sheaf of the first of your harvest to the priest."),
    ],
    11: [
        ("וְהֵנִיף אֶת-הָעֹמֶר לִפְנֵי יְהוָה לִרְצֹנְכֶם",
         "פיחרכה בין ידי אללה. עלי' מא ירתצ'א מנכם",
         "And he shall wave it before God, so that it be accepted from you;"),
        ("מִמָּחֳרַת הַשַּׁבָּת יְנִיפֶנּוּ הַכֹּהֵן",
         "וליכון תחריכה לה. מן ג'ד אלעטלה",
         "and its waving shall be on the morrow after the rest-day."),
    ],
    12: [
        ("וַעֲשִׂיתֶם בְּיוֹם הֲנִיפְכֶם אֶת-הָעֹמֶר כֶּבֶשׂ תָּמִים בֶּן-שְׁנָתוֹ לְעֹלָה לַיהוָה",
         "וקרבו פי יום תחריככם לה. חמלא צחיחא אבן סנתה. צעידה ללה",
         "And offer, on the day of your waving of it, an unblemished lamb, a year old, as an ascent-offering to God."),
    ],
    13: [
        ("וּמִנְחָתוֹ שְׁנֵי עֶשְׂרֹנִים סֹלֶת בְּלוּלָה בַשֶּׁמֶן אִשֶּׁה לַיהוָה--רֵיחַ נִיחֹחַ",
         "ומעה מן אלבר. עשרין סמד מלתות בדהן. קרבאנא מקבולא מרצ'ייא ללה",
         "And with it, from wheat, two-tenths of fine flour mixed with oil — an offering acceptable and pleasing to God;"),
        ("וְנִסְכֹּה יַיִן רְבִיעִת הַהִין",
         "ומזאגה מן אלכ'מר רבע קסט",
         "and its libation of wine, a quarter of a qist."),
    ],
    14: [
        ("וְלֶחֶם וְקָלִי וְכַרְמֶל לֹא תֹאכְלוּ עַד-עֶצֶם הַיּוֹם הַזֶּה--עַד הֲבִיאֲכֶם אֶת-קָרְבַּן אֱלֹהֵיכֶם",
         "וכבזא וסויקא ופריכא לא תאכלו. אלי' ד'את הד'א אליום. אלי' אן תאתו בקרבאן רבכם",
         "And bread, and parched grain, and roasted grain, you shall not eat until this very day — until you bring the offering of your Lord."),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם בְּכֹל מֹשְׁבֹתֵיכֶם",
         "רסם אלדהר עלי' מר אגיאלכם. פי גמיע מסאכנכם",
         "A decree forever, throughout the passing of your generations, in all your dwellings."),
    ],
    15: [
        ("וּסְפַרְתֶּם לָכֶם מִמָּחֳרַת הַשַּׁבָּת מִיּוֹם הֲבִיאֲכֶם אֶת-עֹמֶר הַתְּנוּפָה",
         "ואחצו לכם מן ג'ד אלעטלה. מן יום גיתם בג'מר אלתחריך",
         "And count for yourselves, from the morrow after the rest-day, from the day you brought the sheaf of the waving —"),
        ("שֶׁבַע שַׁבָּתוֹת תְּמִימֹת תִּהְיֶינָה",
         "סבעה' אסאביע תאמה תכון",
         "seven complete weeks shall there be."),
    ],
    16: [
        ("עַד מִמָּחֳרַת הַשַּׁבָּת הַשְּׁבִיעִת תִּסְפְּרוּ חֲמִשִּׁים יוֹם",
         "ואלי' ג'ד אלאסבוע אלסאבע. פיכון גמלה' מא תחצונה כ'מסין יומא",
         "Until the morrow of the seventh week; and the total of what you count shall be fifty days."),
        ("וְהִקְרַבְתֶּם מִנְחָה חֲדָשָׁה לַיהוָה",
         "וקרבו. קרבאנא גדידא ללה",
         "And offer a new offering to God."),
    ],
    17: [
        ("מִמּוֹשְׁבֹתֵיכֶם תָּבִיאּוּ לֶחֶם תְּנוּפָה שְׁתַּיִם שְׁנֵי עֶשְׂרֹנִים--סֹלֶת תִּהְיֶינָה חָמֵץ תֵּאָפֶינָה",
         "אן תאתו מן מסאכנכם בכ'בז לאלתחריך. רג'יפין מן עשרין. סמדא יכונאן. וכ'מירא יכ'בזאן",
         "That you bring from your dwellings bread for waving — two loaves, of two-tenths of fine flour shall they be; leavened shall they be baked."),
        ("בִּכּוּרִים לַיהוָה",
         "המא בכור ללה",
         "They are first-fruits to God."),
    ],
    18: [
        ("וְהִקְרַבְתֶּם עַל-הַלֶּחֶם שִׁבְעַת כְּבָשִׂים תְּמִימִם בְּנֵי שָׁנָה וּפַר בֶּן-בָּקָר אֶחָד וְאֵילִם שְׁנָיִם יִהְיוּ עֹלָה לַיהוָה",
         "וקרבו מע אלרג'יפין. סבעה חמלאן צחאחא בני סנה. ות'ורא מן אלבקר וכבשין יכונאן צעידה ללה",
         "And offer with the two loaves seven unblemished lambs, yearlings, and a bull from the cattle, and two rams — they shall be an ascent-offering to God;"),
        ("וּמִנְחָתָם וְנִסְכֵּיהֶם אִשֵּׁה רֵיחַ-נִיחֹחַ לַיהוָה",
         "וברהמא ומזאגהמא. קרבאן מקבול מרצ'י ללה",
         "and their grain-offering and their libations — an offering acceptable and pleasing to God."),
    ],
    19: [
        ("וַעֲשִׂיתֶם שְׂעִיר-עִזִּים אֶחָד לְחַטָּאת",
         "וקרבו איצ'א עתוד מן אלמאעז לאלד'כוה",
         "And offer also a he-goat from the goats for the purification,"),
        ("וּשְׁנֵי כְבָשִׂים בְּנֵי שָׁנָה לְזֶבַח שְׁלָמִים",
         "וחמלין אבני סנה לד'בח אלסלאמה",
         "and two yearling lambs for the well-being sacrifice."),
    ],
    20: [
        ("וְהֵנִיף הַכֹּהֵן אֹתָם עַל לֶחֶם הַבִּכֻּרִים תְּנוּפָה לִפְנֵי יְהוָה עַל-שְׁנֵי כְּבָשִׂים",
         "פיחרך מא יגב מנהא אלאמאם. מע רג'יפי אלבכור תחריכא בין ידי אללה. עלי' אלחמלין",
         "And the priest shall wave what is required of them, together with the two first-fruit loaves, as a waving before God, over the two lambs;"),
        ("קֹדֶשׁ יִהְיוּ לַיהוָה לַכֹּהֵן",
         "ולתכון קדסא ללה. תדפע אלי' אלאמאם",
         "and they shall be a holy portion to God, given over to the priest."),
    ],
    21: [
        ("וּקְרָאתֶם בְּעֶצֶם הַיּוֹם הַזֶּה מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם--כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "ואסמו ד'את ד'אלך אליום. אסמא מקדסא יכון לכם. כל צנעה' מכסב לא תצנעו",
         "And designate that very day by a consecrated name — it shall be for you; no labor for profit shall you perform."),
        ("חֻקַּת עוֹלָם בְּכָל-מוֹשְׁבֹתֵיכֶם לְדֹרֹתֵיכֶם",
         "רסם אלדהר פי גמיע מסאכנכם. עלי' מר אגיאלכם",
         "A decree forever, in all your dwellings, throughout your generations."),
    ],
    22: [
        ("וּבְקֻצְרְכֶם אֶת-קְצִיר אַרְצְכֶם לֹא-תְכַלֶּה פְּאַת שָׂדְךָ בְּקֻצְרֶךָ",
         "ואד'א חצדתם זרע ריאצ'כם. פלא תסתקץ טרה' צ'יעתך פי חצאדך",
         "And when you reap the harvest of your fields, do not cut to the very edge of your estate in your reaping,"),
        ("וְלֶקֶט קְצִירְךָ לֹא תְלַקֵּט לֶעָנִי וְלַגֵּר תַּעֲזֹב אֹתָם",
         "ונת'יר זרעך פלא תלקטה. בל לאלצ'עיף ואלג'ריב אתרכהמא",
         "and the scattered grain of your sowing do not glean — rather, for the poor and the stranger, leave them."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אגאזיכם כ'ירא",
         "I am God your Lord; I shall recompense you with good."),
    ],
    23: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    24: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר בַּחֹדֶשׁ הַשְּׁבִיעִי בְּאֶחָד לַחֹדֶשׁ יִהְיֶה לָכֶם שַׁבָּתוֹן",
         "מר בני אסראיל קאילא. פי אליום אלאוול מן אלשהר אלסאבע. יכון לכם עטלה",
         "Command the sons of Israel, saying: on the first day of the seventh month, there shall be for you a rest-day"),
        ("זִכְרוֹן תְּרוּעָה מִקְרָא-קֹדֶשׁ",
         "ותבויק גלבה אסמא מקדסא",
         "and a sounding of clamor — a consecrated name."),
    ],
    25: [
        ("כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "כל צנאעה' מכסב לא תעמלו",
         "No labor for profit shall you perform;"),
        ("וְהִקְרַבְתֶּם אִשֶּׁה לַיהוָה",
         "וקרבו קרבאנא זאידא ללה",
         "and offer an additional offering to God."),
    ],
    26: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    27: [
        ("אַךְ בֶּעָשׂוֹר לַחֹדֶשׁ הַשְּׁבִיעִי הַזֶּה יוֹם הַכִּפֻּרִים הוּא מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם",
         "אמא פי אליום אלעאשר מן הד'א אלשהר אלסאבע והו יום אלג'פראן. אסמא מקדסא יכון לכם",
         "Now on the tenth day of this seventh month — and it is the Day of Atonement — a consecrated name shall be for you;"),
        ("וְעִנִּיתֶם אֶת-נַפְשֹׁתֵיכֶם וְהִקְרַבְתֶּם אִשֶּׁה לַיהוָה",
         "ואגיעו אנפסכם. וקרבו קרבאנא זאידא ללה",
         "and starve yourselves, and offer an additional offering to God."),
    ],
    28: [
        ("וְכָל-מְלָאכָה לֹא תַעֲשׂוּ בְּעֶצֶם הַיּוֹם הַזֶּה",
         "וכל עמל לא תעמלו. פי ד'את הד'א אליום",
         "And no work at all shall you perform on this very day,"),
        ("כִּי יוֹם כִּפֻּרִים הוּא לְכַפֵּר עֲלֵיכֶם לִפְנֵי יְהוָה אֱלֹהֵיכֶם",
         "לאנה יום ג'פראן לכם. יסתג'פר פיה ענכם. בין ידי אללה רבכם",
         "for it is a day of atonement for you, on which pardon is sought on your behalf before God your Lord."),
    ],
    29: [
        ("כִּי כָל-הַנֶּפֶשׁ אֲשֶׁר לֹא-תְעֻנֶּה בְּעֶצֶם הַיּוֹם הַזֶּה--וְנִכְרְתָה מֵעַמֶּיהָ",
         "וכל אנסאן באלג'. לם יצום פי ד'את הד'א אליום. ינקטע מן קומה",
         "And every adult person who does not fast on this very day shall be cut off from his people."),
    ],
    30: [
        ("וְכָל-הַנֶּפֶשׁ אֲשֶׁר תַּעֲשֶׂה כָּל-מְלָאכָה בְּעֶצֶם הַיּוֹם הַזֶּה--וְהַאֲבַדְתִּי אֶת-הַנֶּפֶשׁ הַהִוא מִקֶּרֶב עַמָּהּ",
         "וכל אנסאן יצנע שייא מן אלצנאיע. פי ד'את ד'אלך אליום. אביד ד'אלך אלאנסאן מן בין קומה",
         "And every person who performs any labor on this very day — I shall destroy that person from among his people."),
    ],
    31: [
        ("כָּל-מְלָאכָה לֹא תַעֲשׂוּ חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם בְּכֹל מֹשְׁבֹתֵיכֶם",
         "וכל צנאעה לא תעמלו. רסם אלדהר עלי' מר אגיאלכם. פי גמיע מסאכנכם",
         "And no labor at all shall you perform. A decree forever, throughout your generations, in all your dwellings."),
    ],
    32: [
        ("שַׁבַּת שַׁבָּתוֹן הוּא לָכֶם וְעִנִּיתֶם אֶת-נַפְשֹׁתֵיכֶם",
         "עטלה הי סבת לכם. ותגיעו אנפסכם",
         "It is a desisting — a Sabbath for you; and you shall starve yourselves,"),
        ("בְּתִשְׁעָה לַחֹדֶשׁ בָּעֶרֶב--מֵעֶרֶב עַד-עֶרֶב תִּשְׁבְּתוּ שַׁבַּתְּכֶם",
         "מן עשייה' אלתאסע פי הד'י אלשהר. אלי' אלעשי אלת'אני תעטלו עמלכם",
         "from the evening of the ninth of this month until the second evening, you shall cease your work."),
    ],
    33: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    34: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר בַּחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הַשְּׁבִיעִי הַזֶּה",
         "מר בני אסראיל קאילא. פי אליום אלכאמס עשר מן אלשהר אלסאבע",
         "Command the sons of Israel, saying: on the fifteenth day of the seventh month"),
        ("חַג הַסֻּכּוֹת שִׁבְעַת יָמִים לַיהוָה",
         "חג אלמצ'אל. סבעה' אייאם ללה",
         "is the festival of booths — seven days to God."),
    ],
    35: [
        ("בַּיּוֹם הָרִאשׁוֹן מִקְרָא-קֹדֶשׁ כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "פי אליום אלאוול אסם מקדס. כל צנאעה' מכסב לא תעמלו",
         "On the first day, a consecrated name; no labor for profit shall you perform."),
    ],
    36: [
        ("שִׁבְעַת יָמִים תַּקְרִיבוּ אִשֶּׁה לַיהוָה",
         "ופי הד'ה אלסבעה' אלאייאם. תקרבו קרבאנא ללה",
         "And during these seven days you shall offer an offering to God;"),
        ("בַּיּוֹם הַשְּׁמִינִי מִקְרָא-קֹדֶשׁ יִהְיֶה לָכֶם וְהִקְרַבְתֶּם אִשֶּׁה לַיהוָה עֲצֶרֶת הִוא--כָּל-מְלֶאכֶת עֲבֹדָה לֹא תַעֲשׂוּ",
         "ופי אליום אלת'אמן. אסם מקדס יכון לכם . וקרבו קרבאנא זאידא ללה ואמכתו פי קדסה. וכל צנאעה' מכסב לא תעמלו",
         "and on the eighth day, a consecrated name shall be for you — and offer an additional offering to God, and remain in its holiness; and no labor for profit shall you perform."),
    ],
    37: [
        ("אֵלֶּה מוֹעֲדֵי יְהוָה אֲשֶׁר-תִּקְרְאוּ אֹתָם מִקְרָאֵי קֹדֶשׁ",
         "הד'ה אעיאד אללה. אלתי יגב אן תסמוהא באסמא כ'אצה",
         "These are the festivals of God, which you are obligated to designate by special names,"),
        ("לְהַקְרִיב אִשֶּׁה לַיהוָה עֹלָה וּמִנְחָה זֶבַח וּנְסָכִים--דְּבַר-יוֹם בְּיוֹמוֹ",
         "ותקרבו פיהא קראבינא ללה. מן צעידה ובר. וד'בח ומזאג ואגב כל יום פי יומה",
         "and in which you shall offer offerings to God — ascent-offering and grain-offering, and sacrifice and libation, the obligation of each day in its day."),
    ],
    38: [
        ("מִלְּבַד שַׁבְּתֹת יְהוָה וּמִלְּבַד מַתְּנוֹתֵיכֶם וּמִלְּבַד כָּל-נִדְרֵיכֶם וּמִלְּבַד כָּל-נִדְבֹתֵיכֶם אֲשֶׁר תִּתְּנוּ לַיהוָה",
         "מא כ'לא סבות אללה. ומא כ'לא עטאיאכם. ונד'ורכם ותברעכם. אלדי תעטוהא ללה",
         "Apart from the Sabbaths of God, and apart from your gifts, and your vows, and your freewill-offerings, which you give to God."),
    ],
    39: [
        ("אַךְ בַּחֲמִשָּׁה עָשָׂר יוֹם לַחֹדֶשׁ הַשְּׁבִיעִי בְּאָסְפְּכֶם אֶת-תְּבוּאַת הָאָרֶץ תָּחֹגּוּ אֶת-חַג-יְהוָה שִׁבְעַת יָמִים",
         "אמא פי אליום אלכ'אמס עשר מן אלשהר אלסאבע. פי אואן גמעכם גלה' אלארץ'. תחגו חג ללה סבעה' אייאם",
         "Now on the fifteenth day of the seventh month, at the season of your gathering in the yield of the land, you shall make a pilgrimage-festival to God for seven days;"),
        ("בַּיּוֹם הָרִאשׁוֹן שַׁבָּתוֹן וּבַיּוֹם הַשְּׁמִינִי שַׁבָּתוֹן",
         "פי אליום אלאוול מנהא עטלה. ופי אליום אלת'אמן עטלה",
         "on the first day of them a rest-day, and on the eighth day a rest-day."),
    ],
    40: [
        ("וּלְקַחְתֶּם לָכֶם בַּיּוֹם הָרִאשׁוֹן פְּרִי עֵץ הָדָר כַּפֹּת תְּמָרִים וַעֲנַף עֵץ-עָבֹת וְעַרְבֵי-נָחַל",
         "וכ'דו לכם פי אליום אלאוול. מן ת'מר שגר אלאתרנג ומן לב אלנכ'ל. ומן אג'צאן עוד אלאס עלי' צנעה' אלצ'פר. ומן ג'רב אלואד",
         "And take for yourselves on the first day, from the fruit of the citron tree, and from the fronds of the palm, and from the branches of the myrtle-wood braided together, and from the willows of the valley —"),
        ("וּשְׂמַחְתֶּם לִפְנֵי יְהוָה אֱלֹהֵיכֶם--שִׁבְעַת יָמִים",
         "ואפרחו בה. בין ידי אללה רבכם סבעה' אייאם",
         "and rejoice with them before God your Lord, seven days."),
    ],
    41: [
        ("וְחַגֹּתֶם אֹתוֹ חַג לַיהוָה שִׁבְעַת יָמִים בַּשָּׁנָה",
         "וחגו ד'אלך חג ללה. סבעה' אייאם פי אלסנה",
         "And celebrate it as a festival to God, seven days in the year —"),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם בַּחֹדֶשׁ הַשְּׁבִיעִי תָּחֹגּוּ אֹתוֹ",
         "רסם אלדהר עלי' מר אגיאלכם. פי אלשהר אלסאבע תחגונה",
         "a decree forever throughout your generations; in the seventh month you shall celebrate it."),
    ],
    42: [
        ("בַּסֻּכֹּת תֵּשְׁבוּ שִׁבְעַת יָמִים",
         "ואגלסו פי אלמצ'אל סבעה' אייאם לאמרי",
         "And dwell in the booths seven days at My command;"),
        ("כָּל-הָאֶזְרָח בְּיִשְׂרָאֵל יֵשְׁבוּ בַּסֻּכֹּת",
         "וכל צריח מן אל אסראיל. יגלסו פי אלמצ'אל",
         "every native-born of the house of Israel shall dwell in the booths —"),
    ],
    43: [
        ("לְמַעַן יֵדְעוּ דֹרֹתֵיכֶם כִּי בַסֻּכּוֹת הוֹשַׁבְתִּי אֶת-בְּנֵי יִשְׂרָאֵל",
         "לכי יעלם אגיאלכם. אני אללה רבכם. אגלסת בני אסראיל פי צ'לאל מכן ג'מאמי",
         "so that your generations may know that I, God your Lord, sheltered the sons of Israel in the shade of My clouds"),
        ("בְּהוֹצִיאִי אוֹתָם מֵאֶרֶץ מִצְרָיִם אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "חין אכ'רגתהם מן בלד מצר. אנא אללה רבכם צאדק אלועד",
         "when I brought them out from the land of Egypt. I am God your Lord, true to My promise."),
    ],
    44: [
        ("וַיְדַבֵּר מֹשֶׁה אֶת-מֹעֲדֵי יְהוָה אֶל-בְּנֵי יִשְׂרָאֵל",
         "פכ'אטב מוסי' באעיאד אללה בני אסראיל",
         "And Moses addressed the sons of Israel concerning the festivals of God."),
    ],
}
