"""Hand-authored alignment triples for Vayikra chapter 3.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואן", "And if"),
        (None, "כאן", "be"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("זֶבַח שְׁלָמִים", "ד'בח סלאמה", "a peace-sacrifice"),
        ("מִן-הַבָּקָר", "מן אלבקר", "from the cattle"),
        ("זָכָר", "ד'כר", "male"),
        (None, "או", "or"),
        ("נְקֵבָה", "אנת'י", "female"),
        ("תָּמִים", "צחיחא", "unblemished"),
        ("יַקְרִיבֶנּוּ", "פליקרבה", "he shall bring it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
    ],
    2: [
        ("וְסָמַךְ", "ויסנד", "And he shall lay"),
        ("יָדוֹ", "ידה", "his hand"),
        ("עַל-רֹאשׁ", "עלי' ראס", "upon the head of"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("וּשְׁחָטוֹ", "ויד'בחה", "and slaughter it"),
        ("פֶּתַח", "ענד באב", "at the door of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("וְזָרְקוּ", "וירשו", "shall sprinkle"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("הַכֹּהֲנִים", "אלאיימה", "the priests"),
        ("אֶת-הַדָּם", "אלדם", "the blood"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    3: [
        ("וְהִקְרִיב", "ויקרב", "And he shall offer"),
        ("מִזֶּבַח הַשְּׁלָמִים", "מן ד'בח אלסלאמה", "from the peace-sacrifice"),
        (None, "קרבאנא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("הַחֵלֶב", "אלת'רב", "the caul-fat"),
        ("הַמְכַסֶּה", "אלמג'טי", "covering"),
        ("אֶת-הַקֶּרֶב", "אלגוף", "the innards"),
        (None, "וסאיר", "and all the rest of"),
        ("הַחֵלֶב", "אלשחם", "the fat"),
        ("אֲשֶׁר", "אלד'י", "which is"),
        ("עַל-הַקֶּרֶב", "עלי' אלגוף", "upon the innards"),
    ],
    4: [
        ("שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("אֲשֶׁר עֲלֵהֶן", "אלד'י עליהמא", "which is upon them"),
        ("אֲשֶׁר עַל-הַכְּסָלִים", "אלד'י עלי' אלאחשא", "which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת", "וזיאדה'", "and the appendage of"),
        ("הַכָּבֵד", "אלכבד", "the liver"),
        ("עַל-הַכְּלָיוֹת", "מע אלכלי'", "together with the kidneys"),
        ("יְסִירֶנָּה", "ינזעהא", "he shall remove them"),
    ],
    5: [
        ("וְהִקְטִירוּ", "ויקתרו", "shall burn"),
        ("אֹתוֹ", "ד'אלך", "that"),
        ("בְנֵי-אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("עַל-הָעֹלָה", "עלי' אלצעידה", "upon the layer"),
        ("אֲשֶׁר עַל-הָעֵצִים", "אלתי עלי' אלחטב", "which is upon the wood"),
        ("אֲשֶׁר עַל-הָאֵשׁ", "אלד'י עלי' אלנאר", "that is upon the fire"),
        ("אִשֵּׁה", "קרבאן", "an offering"),
        ("רֵיחַ נִיחֹחַ", "מקבול מרצ'י", "acceptable and pleasing"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    6: [
        (None, "ואן", "And if"),
        (None, "כאן", "be"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("מִן-הַצֹּאן", "מן אלג'נם", "from the flock"),
        ("לְזֶבַח שְׁלָמִים", "ד'בח סלאמה", "a peace-sacrifice"),
        ("לַיהוָה", "ללה", "to God"),
        ("זָכָר", "ד'כר", "male"),
        ("אוֹ", "או", "or"),
        ("נְקֵבָה", "אנת'י", "female"),
        ("תָּמִים", "צחיחא", "unblemished"),
        ("יַקְרִיבֶנּוּ", "פליקרבה", "he shall bring it"),
    ],
    7: [
        (None, "פאן", "If"),
        (None, "כאן", "be"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("כֶּשֶׂב", "חמלא", "a lamb"),
        ("וְהִקְרִיב אֹתוֹ", "פליקרבה", "he shall bring it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
    ],
    8: [
        ("וְסָמַךְ", "ויסנד", "And he shall lay"),
        ("אֶת-יָדוֹ", "ידה", "his hand"),
        ("עַל-רֹאשׁ", "עלי' ראס", "upon the head of"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("וְשָׁחַט אֹתוֹ", "ויד'בחה", "and slaughter it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("וְזָרְקוּ", "וירשו", "shall sprinkle"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("אֶת-דָּמוֹ", "דמה", "its blood"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    9: [
        ("וְהִקְרִיב", "ויקרב", "And he shall offer"),
        ("מִזֶּבַח הַשְּׁלָמִים", "מן ד'בח אלסלאמה", "from the peace-sacrifice"),
        (None, "קרבאנא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("חֶלְבּוֹ", "אלת'רב", "the caul-fat"),
        ("הָאַלְיָה", "ואלאליה", "and the fat-tail"),
        ("תְמִימָה", "צחיחה", "whole"),
        ("לְעֻמַּת", "אמאם", "before"),
        ("הֶעָצֶה", "אלעצעץ", "the base of the spine"),
        ("יְסִירֶנָּה", "ינזעהא", "removing it"),
        ("הַחֵלֶב", "ואלת'רב", "and the caul-fat"),
        ("הַמְכַסֶּה", "אלמג'טי", "covering"),
        ("אֶת-הַקֶּרֶב", "אלגוף", "the innards"),
        (None, "וסאיר", "and all the rest of"),
        ("הַחֵלֶב", "אלשחם", "the fat"),
        ("אֲשֶׁר עַל-הַקֶּרֶב", "אלד'י עלי' אלגוף", "which is upon the innards"),
    ],
    10: [
        ("שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("אֲשֶׁר עֲלֵהֶן", "אלד'י עליהמא", "which is upon them"),
        ("אֲשֶׁר עַל-הַכְּסָלִים", "אלד'י עלי' אלאחשא", "which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת", "וזיאדה'", "and the appendage of"),
        ("הַכָּבֵד", "אלכבד", "the liver"),
        ("עַל-הַכְּלָיֹת", "מע אלכלי'", "together with the kidneys"),
        ("יְסִירֶנָּה", "ינזעהא", "he shall remove them"),
    ],
    11: [
        ("וְהִקְטִירוֹ", "ויקתר", "shall burn"),
        (None, "ד'אלך", "that"),
        ("הַכֹּהֵן", "אלאמאם", "the priest"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("אִשֶּׁה", "קרבאן", "an offering"),
        (None, "מקבול", "acceptable"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    12: [
        (None, "ואן", "And if"),
        (None, "כאן", "be"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("עֵז", "מן אלמאעז", "from the goats"),
        ("וְהִקְרִיבוֹ", "פליקרבה", "he shall bring it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
    ],
    13: [
        ("וְסָמַךְ", "ויסנד", "And he shall lay"),
        ("אֶת-יָדוֹ", "ידה", "his hand"),
        ("עַל-רֹאשׁוֹ", "עלי' ראסה", "upon its head"),
        ("וְשָׁחַט אֹתוֹ", "ויד'בחה", "and slaughter it"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("וְזָרְקוּ", "וירשון", "shall sprinkle"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("אֶת-דָּמוֹ", "דמה", "its blood"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    14: [
        ("וְהִקְרִיב", "ויקרב", "And he shall offer"),
        ("מִמֶּנּוּ", "מנה", "from it"),
        (None, "קרבאנא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("הַחֵלֶב", "אלת'רב", "the caul-fat"),
        ("הַמְכַסֶּה", "אלמג'טי", "covering"),
        ("אֶת-הַקֶּרֶב", "אלגוף", "the innards"),
        (None, "וסאיר", "and all the rest of"),
        ("הַחֵלֶב", "אלשחם", "the fat"),
        ("אֲשֶׁר עַל-הַקֶּרֶב", "אלד'י עלי' אלגוף", "which is upon the innards"),
    ],
    15: [
        ("שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("אֲשֶׁר עֲלֵהֶן", "אלד'י עליהמא", "which is upon them"),
        ("אֲשֶׁר עַל-הַכְּסָלִים", "אלד'י עלי' אלאחשא", "which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת", "וזיאדה'", "and the appendage of"),
        ("הַכָּבֵד", "אלכבד", "the liver"),
        ("עַל-הַכְּלָיֹת", "מע אלכלי''", "together with the kidneys"),
        ("יְסִירֶנָּה", "ינזעהא", "he shall remove them"),
    ],
    16: [
        ("וְהִקְטִירָם", "ויקתרהא", "shall burn them"),
        ("הַכֹּהֵן", "אלאמאם", "the priest"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        (None, "קרבאנא", "a"),
        (None, "מחרקא", "burnt offering"),
        (None, "מרצ'י", "pleasing"),
        (None, "מקבול", "and acceptable"),
        ("כָּל-חֵלֶב", "כל שחם", "all fat"),
        (None, "כד'אך", "is thus"),
        ("לַיהוָה", "ללה", "for God"),
    ],
    17: [
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "A perpetual ordinance"),
        ("לְדֹרֹתֵיכֶם", "עלי' מר אגיאלכם", "throughout your generations"),
        ("בְּכֹל מוֹשְׁבֹתֵיכֶם", "פי גמיע מסאכנכם", "in all your dwellings"),
        ("כָּל-חֵלֶב", "כל שחם", "no fat"),
        ("וְכָל-דָּם", "וכל דם", "and no blood"),
        ("לֹא תֹאכֵלוּ", "לא תאכלו", "shall you eat"),
    ],
}
