"""Hand-authored alignment triples for Vayikra chapter 9."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְהִי בַּיּוֹם הַשְּׁמִינִי",
         "פלמא כאן פי אליום אלת'אמן",
         "And it was on the eighth day"),
        ("קָרָא מֹשֶׁה לְאַהֲרֹן וּלְבָנָיו",
         "דעא מוסי' בהרון ובניה",
         "Moses called to Aaron and his sons"),
        ("וּלְזִקְנֵי יִשְׂרָאֵל",
         "ואשיאך' בני אסראיל",
         "and to the elders of the sons of Israel."),
    ],
    2: [
        ("וַיֹּאמֶר אֶל-אַהֲרֹן",
         "וקאל להרון",
         "And he said to Aaron:"),
        ("קַח-לְךָ עֵגֶל בֶּן-בָּקָר לְחַטָּאת וְאַיִל לְעֹלָה--תְּמִימִם",
         "כ'ד' עגלא מן אלבקר לאלד'כוה. וכבשא לאלצעידה צחיחאן",
         "'Take a calf from the cattle for the purification-offering, and a ram for the ascent-offering — both without blemish"),
        ("וְהַקְרֵב לִפְנֵי יְהוָה",
         "וקרבהמא בין ידי אללה",
         "— and bring them near before God.'"),
    ],
    3: [
        ("וְאֶל-בְּנֵי יִשְׂרָאֵל תְּדַבֵּר לֵאמֹר",
         "ומר בני אסראיל קאילא",
         "And command the sons of Israel, saying:"),
        ("קְחוּ שְׂעִיר-עִזִּים לְחַטָּאת",
         "כ'ד'ו עתודא מן אלמאעז לאלד'כוה",
         "Take a he-goat from the goats for the purification-offering,"),
        ("וְעֵגֶל וָכֶבֶשׂ בְּנֵי-שָׁנָה תְּמִימִם לְעֹלָה",
         "ועגלא וכרופא אבני סנה. צחיחאן לאלצעידה",
         "and a calf and a lamb, sons of a year, without blemish, for the ascent-offering;"),
    ],
    4: [
        ("וְשׁוֹר וָאַיִל לִשְׁלָמִים לִזְבֹּחַ לִפְנֵי יְהוָה",
         "ות'ורא וכבשא לאלסלאמה. יד'בחאן בין ידי אללה",
         "and a bull and a ram for the well-being offering, to be slaughtered before God;"),
        ("וּמִנְחָה בְּלוּלָה בַשָּׁמֶן",
         "והדייה מלתותה בדהן",
         "and a gift-offering mixed with oil"),
        ("כִּי הַיּוֹם יְהוָה נִרְאָה אֲלֵיכֶם",
         "לאן אליום. אללה יתגלא לכם",
         "— for today God shall reveal Himself to you.'"),
    ],
    5: [
        ("וַיִּקְחוּ אֵת אֲשֶׁר צִוָּה מֹשֶׁה אֶל-פְּנֵי אֹהֶל מוֹעֵד",
         "פקדמו מא אמר בה מוסי'. אלי' באב כ'בא אלמחצ'ר",
         "And they brought forward what Moses had commanded, to the entrance of the tent of the assembly;"),
        ("וַיִּקְרְבוּ כָּל-הָעֵדָה וַיַּעַמְדוּ לִפְנֵי יְהוָה",
         "ותקדם גמיע אלגמע. ווקפו בין ידי אללה",
         "and all the congregation drew near, and stood before God."),
    ],
    6: [
        ("וַיֹּאמֶר מֹשֶׁה זֶה הַדָּבָר אֲשֶׁר-צִוָּה יְהוָה תַּעֲשׂוּ",
         "וקאל מוסי' הד'י אלאמר. אלד'י אמרכם אללה בה אעמלוה",
         "And Moses said: 'This is the matter which God has commanded you — do it,"),
        ("וְיֵרָא אֲלֵיכֶם כְּבוֹד יְהוָה",
         "ויתגלא לכם כרם אללה",
         "and the munificence of God shall reveal itself to you.'"),
    ],
    7: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן קְרַב אֶל-הַמִּזְבֵּחַ",
         "וקאל להרון. תקדם אלי' אלמד'בח",
         "And he said to Aaron: 'Draw near to the altar"),
        ("וַעֲשֵׂה אֶת-חַטָּאתְךָ וְאֶת-עֹלָתֶךָ וְכַפֵּר בַּעַדְךָ וּבְעַד הָעָם",
         "ואעמל. ד'כותך וצעידתך. ואסתג'פר ענך וען אלקום",
         "and perform your purification-offering and your ascent-offering, and seek forgiveness for yourself and for the people;"),
        ("וַעֲשֵׂה אֶת-קָרְבַּן הָעָם וְכַפֵּר בַּעֲדָם כַּאֲשֶׁר צִוָּה יְהוָה",
         "ואעמל קרבאנהם ואסתג'פר ענהם. כמא אמר אללה",
         "then perform their offering and seek forgiveness for them — as God has commanded.'"),
    ],
    8: [
        ("וַיִּקְרַב אַהֲרֹן אֶל-הַמִּזְבֵּחַ",
         "פתקדם הרון אלי' אלמד'בח",
         "And Aaron drew near to the altar,"),
        ("וַיִּשְׁחַט אֶת-עֵגֶל הַחַטָּאת אֲשֶׁר-לוֹ",
         "פד'בח עגל אלדכוה אלד'י לה",
         "and slaughtered the calf of the purification-offering which was his."),
    ],
    9: [
        ("וַיַּקְרִבוּ בְּנֵי אַהֲרֹן אֶת-הַדָּם אֵלָיו וַיִּטְבֹּל אֶצְבָּעוֹ בַּדָּם",
         "פקדם בני הרון אליה אלדם. פג'מס אצבעה פיה",
         "And the sons of Aaron brought the blood to him; and he dipped his finger in it,"),
        ("וַיִּתֵּן עַל-קַרְנוֹת הַמִּזְבֵּחַ",
         "וגעל עלי' ארכאן אלמד'בח",
         "and placed it upon the corners of the altar;"),
        ("וְאֶת-הַדָּם יָצַק אֶל-יְסוֹד הַמִּזְבֵּחַ",
         "ובאקי אלדם. צבה ענד אסאסה",
         "and the remainder of the blood he poured out at its base."),
    ],
    11: [
        ("וְאֶת-הַבָּשָׂר וְאֶת-הָעוֹר שָׂרַף בָּאֵשׁ מִחוּץ לַמַּחֲנֶה",
         "ולחמה וגל'דה. אחרקה באלנאר. כ'ארג אלעסכר",
         "And its flesh and its hide he burned with fire, outside the encampment."),
    ],
    12: [
        ("וַיִּשְׁחַט אֶת-הָעֹלָה",
         "ת'ם ד'בח אלצעידה",
         "Then he slaughtered the ascent-offering;"),
        ("וַיַּמְצִאוּ בְּנֵי אַהֲרֹן אֵלָיו אֶת-הַדָּם וַיִּזְרְקֵהוּ עַל-הַמִּזְבֵּחַ סָבִיב",
         "ובלג' בני הרון אלדם אליה. ורשה עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron conveyed the blood to him, and he sprinkled it upon the altar all around."),
    ],
    13: [
        ("וְאֶת-הָעֹלָה הִמְצִיאוּ אֵלָיו לִנְתָחֶיהָ--וְאֶת-הָרֹאשׁ",
         "ובלג'ו אליה. אעצ'א אלצעידה מע אלראס",
         "And they conveyed to him the limbs of the ascent-offering together with the head;"),
        ("וַיַּקְטֵר עַל-הַמִּזְבֵּחַ",
         "וקתר ד'אלך עלי' אלמד'בח",
         "and he burned them in fire upon the altar."),
    ],
    14: [
        ("וַיִּרְחַץ אֶת-הַקֶּרֶב וְאֶת-הַכְּרָעָיִם",
         "וג'סל אלגוף ואלאכארע",
         "And he washed the entrails and the legs,"),
        ("וַיַּקְטֵר עַל-הָעֹלָה הַמִּזְבֵּחָה",
         "וקתר ד'אלך עלי' אלמד'בח",
         "and burned them in fire upon the altar."),
    ],
    15: [
        ("וַיַּקְרֵב אֵת קָרְבַּן הָעָם",
         "ת'ם קדם קרבאן אלקום",
         "Then he brought forward the offering of the people,"),
        ("וַיִּקַּח אֶת-שְׂעִיר הַחַטָּאת אֲשֶׁר לָעָם וַיִּשְׁחָטֵהוּ וַיְחַטְּאֵהוּ כָּרִאשׁוֹן",
         "ואכ'ד' עתוד אלדכוה אלד'י להם. פד'בחה וד'כא בה כאלאוול",
         "and took the he-goat of the purification-offering which was theirs, and slaughtered it, and performed the purification with it as with the first."),
    ],
    16: [
        ("וַיַּקְרֵב אֶת-הָעֹלָה וַיַּעֲשֶׂהָ כַּמִּשְׁפָּט",
         "ת'ם קדם אלצעידה. ועמלהא כאלסירה",
         "Then he brought forward the ascent-offering, and performed it according to the established practice."),
    ],
    17: [
        ("וַיַּקְרֵב אֶת-הַמִּנְחָה וַיְמַלֵּא כַפּוֹ מִמֶּנָּה",
         "ת'ם קדם אלהדייה. ומלא כפה מנהא",
         "Then he brought forward the gift-offering, and filled his palm from it,"),
        ("וַיַּקְטֵר עַל-הַמִּזְבֵּחַ--מִלְּבַד עֹלַת הַבֹּקֶר",
         "וקתר ד'אלך עלי' אלמד'בח. מא כ'לא צעידה' אלג'דאה",
         "and burned it in fire upon the altar — in addition to the morning ascent-offering."),
    ],
    18: [
        ("וַיִּשְׁחַט אֶת-הַשּׁוֹר וְאֶת-הָאַיִל זֶבַח הַשְּׁלָמִים אֲשֶׁר לָעָם",
         "וד'בח אלת'ור ואלכבש. ד'בח אלסלאמה אלד'י לאלקום",
         "And he slaughtered the bull and the ram — the well-being sacrifice belonging to the people;"),
        ("וַיַּמְצִאוּ בְּנֵי אַהֲרֹן אֶת-הַדָּם אֵלָיו וַיִּזְרְקֵהוּ עַל-הַמִּזְבֵּחַ סָבִיב",
         "ובלג' בני הרון אלדם אליה. ורשה עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron conveyed the blood to him, and he sprinkled it upon the altar all around."),
    ],
    19: [
        ("וְאֶת-הַחֲלָבִים מִן-הַשּׁוֹר וּמִן-הָאַיִל",
         "ואלשחום מן אלת'ור. ומן אלכבש",
         "And the fats from the bull and from the ram —"),
        ("הָאַלְיָה וְהַמְכַסֶּה וְהַכְּלָיֹת וְיֹתֶרֶת הַכָּבֵד",
         "אלאליה ואלמג'טי אלגוף ואלכלותין. וזיאדה' אלכבד",
         "the broad tail, and what covers the entrails, and the two kidneys, and the lobe of the liver —"),
    ],
    20: [
        ("וַיָּשִׂימוּ אֶת-הַחֲלָבִים עַל-הֶחָזוֹת",
         "וציירו אלשחם מע אלקצוץ",
         "they placed the fat together with the breasts;"),
        ("וַיַּקְטֵר הַחֲלָבִים הַמִּזְבֵּחָה",
         "וקתר אלשחום עלי' אלמד'בח",
         "and he burned the fats in fire upon the altar."),
    ],
    21: [
        ("וְאֵת הֶחָזוֹת וְאֵת שׁוֹק הַיָּמִין הֵנִיף אַהֲרֹן תְּנוּפָה לִפְנֵי יְהוָה",
         "ואלקצוץ. ואלסאק אלאימן. חרכהא הרון. תחריכא בין ידי אללה",
         "And the breasts and the right thigh — Aaron waved them in a waving before God,"),
        ("כַּאֲשֶׁר צִוָּה מֹשֶׁה",
         "כמא אמר מוסי'",
         "as Moses had commanded."),
    ],
    22: [
        ("וַיִּשָּׂא אַהֲרֹן אֶת-יָדָו אֶל-הָעָם וַיְבָרְכֵם",
         "ת'ם של הרון ידיה. אלי' אלקום ובארך עליהם",
         "Then Aaron lifted up his hands toward the people and blessed them;"),
        ("וַיֵּרֶד מֵעֲשֹׂת הַחַטָּאת וְהָעֹלָה--וְהַשְּׁלָמִים",
         "בעד אן נזל מן עמל אלדכוה. ואלצעידה וד'בח אלסלאמה",
         "and he descended from performing the purification-offering, and the ascent-offering, and the well-being sacrifice."),
    ],
    23: [
        ("וַיָּבֹא מֹשֶׁה וְאַהֲרֹן אֶל-אֹהֶל מוֹעֵד וַיֵּצְאוּ וַיְבָרְכוּ אֶת-הָעָם",
         "פדכ'ל מוסי' והרון אלי' כ'בא אלמחצ'ר. וכ'רגא. ובארכא עלי' אלקום",
         "And Moses and Aaron entered into the tent of the assembly, and they came out and blessed the people;"),
        ("וַיֵּרָא כְבוֹד-יְהוָה אֶל-כָּל-הָעָם",
         "פתגלא להם כרם אללה",
         "and the munificence of God revealed itself to them."),
    ],
    24: [
        ("וַתֵּצֵא אֵשׁ מִלִּפְנֵי יְהוָה וַתֹּאכַל עַל-הַמִּזְבֵּחַ אֶת-הָעֹלָה וְאֶת-הַחֲלָבִים",
         "באן כ'רגת נארא מן ענד אללה. פאכלת עלי' אלמד'בח. אלצעידה ואלשחום",
         "For a fire came forth from the presence of God, and consumed upon the altar the ascent-offering and the fats;"),
        ("וַיַּרְא כָּל-הָעָם וַיָּרֹנּוּ וַיִּפְּלוּ עַל-פְּנֵיהֶם",
         "פנצ'ר דא'לך אלקום ורנו. ווקעו עלי' וגוההם",
         "and when the people saw this, they cried out, and fell upon their faces."),
    ],
}
