"""Hand-authored alignment triples for Vayikra chapter 15."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי'' והרון תכלימא",
         "Then God spoke to Moses and Aaron directly."),
    ],
    2: [
        ("דַּבְּרוּ אֶל-בְּנֵי יִשְׂרָאֵל וַאֲמַרְתֶּם אֲלֵהֶם",
         "כלמא בני אסראיל. וקולא להמא.",
         "Speak to the sons of Israel, and say to them:"),
        ("אִישׁ אִישׁ כִּי יִהְיֶה זָב מִבְּשָׂרוֹ--זוֹבוֹ טָמֵא הוּא",
         "אי רגל כאן ד'איבא מן אחלילה. פד'ובה ד'אך הו נגס",
         "any man who has a discharge from his member — his discharge is impure."),
    ],
    3: [
        ("וְזֹאת תִּהְיֶה טֻמְאָתוֹ בְּזוֹבוֹ",
         "והד'ה צפה' ד'ובה אלד'י תכון בה נגאסתה.",
         "And this is the description of his discharge by which his impurity occurs:"),
        ("רָר בְּשָׂרוֹ אֶת-זוֹבוֹ",
         "אמא אן יגעל אחלילה אלד'וב כאלריאל.",
         "whether his member lets the discharge flow like a coin,"),
        ("אוֹ-הֶחְתִּים בְּשָׂרוֹ מִזּוֹבוֹ--טֻמְאָתוֹ הִוא",
         "או ינכ'תם מנה. פתלך נגאסתה",
         "or it becomes sealed from it — that is his impurity."),
    ],
    4: [
        ("כָּל-הַמִּשְׁכָּב אֲשֶׁר יִשְׁכַּב עָלָיו הַזָּב--יִטְמָא",
         "וחכמה אן יכון כל מצ'גע ינצ'גע עליה ינגס.",
         "And his ruling is that every bed upon which he lies shall become impure,"),
        ("וְכָל-הַכְּלִי אֲשֶׁר-יֵשֵׁב עָלָיו יִטְמָא",
         "וכל אנא יגלס עליה ינגס",
         "and every vessel upon which he sits shall become impure."),
    ],
    5: [
        ("וְאִישׁ אֲשֶׁר יִגַּע בְּמִשְׁכָּבוֹ--יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "ואי אנסאן דנא מן מצ'געה. פליג'סל ת'יאבה. וירחץ' באלמא",
         "And any person who approaches his bed shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    6: [
        ("וְהַיֹּשֵׁב עַל-הַכְּלִי אֲשֶׁר-יֵשֵׁב עָלָיו הַזָּב--יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "ומן גלס עלי' אלאנא. אלד'י יגלס עליה אלד'איב. פליג'סל ת'יאבה. וירחץ' באלמא",
         "And whoever sits upon the vessel upon which the one with a discharge sits shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    7: [
        ("וְהַנֹּגֵעַ בִּבְשַׂר הַזָּב--יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "ומן דנא בגסמה. פליג'סל ת'יאבה. וירחץ' באלמא",
         "And whoever approaches him bodily shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    8: [
        ("וְכִי-יָרֹק הַזָּב בַּטָּהוֹר--וְכִבֶּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "ואד'א בצק אלד'איב עלי' אלטאהר. פליג'סל ת'יאבה. וירחץ' באלמא",
         "And if the one with a discharge spits upon the pure person, he shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    10: [
        ("וְכָל-הַנֹּגֵעַ בְּכֹל אֲשֶׁר יִהְיֶה תַחְתָּיו--יִטְמָא עַד-הָעָרֶב",
         "ומן דנא בשי מן מא יכון תחתה. ינג'ס אלי' אלמג'יב.",
         "And whoever approaches anything that was beneath him shall be made impure until sunset;"),
        ("וְהַנּוֹשֵׂא אוֹתָם--יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם וְטָמֵא עַד-הָעָרֶב",
         "ומן חמל שי מנהא. יג'סל ת'יאבה. וירחץ' באלמא וינגס אלי' אלמג'יב",
         "and whoever carries any of those things shall wash his garments, and bathe in water, and be impure until sunset."),
    ],
    11: [
        ("וְכֹל אֲשֶׁר יִגַּע-בּוֹ הַזָּב וְיָדָיו לֹא-שָׁטַף בַּמָּיִם",
         "וכל מן דנא בה אלד'איב. וד'אתה לם יג'סל באלמא.",
         "And everyone whom the one with a discharge approaches, he himself not having washed in water,"),
        ("וְכִבֶּס בְּגָדָיו וְרָחַץ בַּמַּיִם וְטָמֵא עַד-הָעָרֶב",
         "פליג'סל ת'יאבה. וירחץ' באלמא וינג'ס אלי' אלמג'יב",
         "shall wash his garments, and bathe in water, and be made impure until sunset."),
    ],
    12: [
        ("וּכְלִי-חֶרֶשׂ אֲשֶׁר-יִגַּע-בּוֹ הַזָּב יִשָּׁבֵר",
         "ואי אנא כ'זף. דנא בה אלד'איב פליכסר.",
         "And any earthenware vessel which the one with a discharge approaches shall be broken;"),
        ("וְכָל-כְּלִי-עֵץ--יִשָּׁטֵף בַּמָּיִם",
         "ואי אנא כ'שב. פליג'סל באלמא",
         "and any wooden vessel shall be washed in water."),
    ],
    13: [
        ("וְכִי-יִטְהַר הַזָּב מִזּוֹבוֹ--וְסָפַר לוֹ שִׁבְעַת יָמִים לְטָהֳרָתוֹ",
         "פאד'א הו טהר מן ד'ובה. פליחץ סבעה' אייאם לטהרה",
         "And when he is purified from his discharge, he shall count off seven days for his purification"),
        ("וְכִבֶּס בְּגָדָיו וְרָחַץ בְּשָׂרוֹ בְּמַיִם חַיִּים וְטָהֵר",
         "ויג'סל ת'יאבה. וירחץ' בדנה. במא מן נביע ויטהר",
         "and wash his garments, and bathe his body in water from a spring, and he shall be pure."),
    ],
    14: [
        ("וּבַיּוֹם הַשְּׁמִינִי יִקַּח-לוֹ שְׁתֵּי תֹרִים אוֹ שְׁנֵי בְּנֵי יוֹנָה",
         "ופי אליום אלת'אמן. יאתי בשפנינין. או פרכ'י חמאם.",
         "And on the eighth day he shall bring two turtledoves or two young pigeons,"),
        ("וּבָא לִפְנֵי יְהוָה אֶל-פֶּתַח אֹהֶל מוֹעֵד וּנְתָנָם אֶל-הַכֹּהֵן",
         "ויאתי בין ידי אללה. אלי' באב כ'בא אלמחצ'ר. ויסלמהא אלי' אלאמאם",
         "and come before God to the entrance of the tent of the assembly, and deliver them to the priest."),
    ],
    15: [
        ("וְעָשָׂה אֹתָם הַכֹּהֵן--אֶחָד חַטָּאת וְהָאֶחָד עֹלָה",
         "ויעמל אלאמאם אחדהמא ד'כוה. ואלאכ'ר צעידה.",
         "And the priest shall make one of them a purification-offering and the other a burnt-offering,"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן לִפְנֵי יְהוָה מִזּוֹבוֹ",
         "ויסתג'פר ענה בין ידי אללה מן ד'ובה",
         "and shall seek forgiveness for him before God on account of his discharge."),
    ],
    16: [
        ("וְאִישׁ כִּי-תֵצֵא מִמֶּנּוּ שִׁכְבַת-זָרַע--וְרָחַץ בַּמַּיִם אֶת-כָּל-בְּשָׂרוֹ",
         "ואיי רגל כ'רגת מנה נטפה' אנסאל. פליג'סל גמיע בדנה באלמא.",
         "And any man from whom a drop of seed of propagation goes forth shall wash all his body in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    17: [
        ("וְכָל-בֶּגֶד וְכָל-עוֹר אֲשֶׁר-יִהְיֶה עָלָיו שִׁכְבַת-זָרַע--וְכֻבַּס בַּמַּיִם",
         "ואיי ת'וב או גלד. צאר עליה מנה שי. פליג'סל באלמא",
         "And any garment or skin upon which anything from it has fallen shall be washed in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    18: [
        ("וְאִשָּׁה אֲשֶׁר יִשְׁכַּב אִישׁ אֹתָהּ שִׁכְבַת-זָרַע--וְרָחֲצוּ בַמַּיִם",
         "ואייה' אמראה צ'אגעהא רג'ל בנטפה. פלירחצ'א באלמא.",
         "And any woman with whom a man lies with a drop of seed — both of them shall bathe in water,"),
        ("וְטָמְאוּ עַד-הָעָרֶב",
         "וינגסא אלי' אלמג'יב",
         "and be made impure until sunset."),
    ],
    19: [
        ("וְאִשָּׁה כִּי-תִהְיֶה זָבָה דָּם יִהְיֶה זֹבָהּ בִּבְשָׂרָהּ",
         "אייה' אמראה כאנת ד'איבה. והו אן יכון אלדם ינחל מן פרגהא.",
         "Any woman who has a discharge — that is, when blood flows from her opening —"),
        ("שִׁבְעַת יָמִים תִּהְיֶה בְנִדָּתָהּ וְכָל-הַנֹּגֵעַ בָּהּ יִטְמָא עַד-הָעָרֶב",
         "פלתקים סבעה' אייאם פי חיצ'תהא. וכל מן דנא בהא ינג'ס אלי' אלמג'יב",
         "she shall remain seven days in her menstrual period; and everyone who approaches her shall be made impure until sunset."),
    ],
    20: [
        ("וְכֹל אֲשֶׁר תִּשְׁכַּב עָלָיו בְּנִדָּתָהּ יִטְמָא",
         "וגמיע מא תנצ'גע עליה פי חיצ'תהא ינג'ס.",
         "And everything upon which she lies during her menstrual period shall become impure,"),
        ("וְכֹל אֲשֶׁר-תֵּשֵׁב עָלָיו יִטְמָא",
         "וגמיע אלא'נא אלד'י תגלס עליה ינגס",
         "and every vessel upon which she sits shall become impure."),
    ],
    21: [
        ("וְכָל-הַנֹּגֵעַ בְּמִשְׁכָּבָהּ--יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "וכל מן דנא במצ'געהא. יג'סל ת'יאבה. וירחץ' באלמא",
         "And everyone who approaches her bed shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    22: [
        ("וְכָל-הַנֹּגֵעַ--בְּכָל-כְּלִי אֲשֶׁר-תֵּשֵׁב עָלָיו יְכַבֵּס בְּגָדָיו וְרָחַץ בַּמַּיִם",
         "וכל מן דנא בשי. מן אלאניה אלד'י תגלס עליה. יג'סל ת'יאבה. וירחץ' באלמא",
         "And everyone who approaches anything from the vessels upon which she sits shall wash his garments, and bathe in water,"),
        ("וְטָמֵא עַד-הָעָרֶב",
         "וינגס אלי' אלמג'יב",
         "and be impure until sunset."),
    ],
    23: [
        ("וְאִם עַל-הַמִּשְׁכָּב הוּא אוֹ עַל-הַכְּלִי אֲשֶׁר-הִוא יֹשֶׁבֶת-עָלָיו",
         "ואן כאן עלי' מצ'געהא. או עלי' אלאנא אלתי הי גאלסה עליה",
         "And if there is contact with it — whether upon her bed or upon the vessel upon which she is sitting —"),
        ("בְּנָגְעוֹ-בוֹ יִטְמָא עַד-הָעָרֶב",
         "ממאסה לה פלינגס אלי' אלמג'יב",
         "he shall be impure until sunset."),
    ],
    24: [
        ("וְאִם שָׁכֹב יִשְׁכַּב אִישׁ אֹתָהּ וּתְהִי נִדָּתָהּ עָלָיו--וְטָמֵא שִׁבְעַת יָמִים",
         "ואן צ'אגעהא רג'ל. פקד צאר חכם חיצ'תהא עליה. וינגס סבעה' אייאם",
         "And if a man lies with her, then the ruling of her menstrual period comes upon him, and he shall be impure seven days;"),
        ("וְכָל-הַמִּשְׁכָּב אֲשֶׁר-יִשְׁכַּב עָלָיו יִטְמָא",
         "וכל מצ'גע ינצ'גע עליה ינגס",
         "and every bed upon which he lies shall become impure."),
    ],
    25: [
        ("וְאִשָּׁה כִּי-יָזוּב זוֹב דָּמָהּ יָמִים רַבִּים בְּלֹא עֶת-נִדָּתָהּ אוֹ כִי-תָזוּב עַל-נִדָּתָהּ",
         "ואייה' אמראה פאץ' דמהא אייאמא כתירה. פי ג'יר וקת חיצ'תהא או בעקבה.",
         "And any woman whose blood flows for many days outside the time of her menstrual period, or following upon it —"),
        ("כָּל-יְמֵי זוֹב טֻמְאָתָהּ כִּימֵי נִדָּתָהּ תִּהְיֶה--טְמֵאָה הִוא",
         "פגמיע אייאם פיץ' נגאסתהא. פלתכון פיהא כאייאם חיצ'תהא נגסה",
         "all the days of the flow of her impurity she shall be in it as in the days of her menstrual period: impure."),
    ],
    26: [
        ("כָּל-הַמִּשְׁכָּב אֲשֶׁר-תִּשְׁכַּב עָלָיו כָּל-יְמֵי זוֹבָהּ--כְּמִשְׁכַּב נִדָּתָהּ יִהְיֶה-לָּהּ",
         "וגמיע אלמצ'גע. אלד'י תנצ'גע עליה טול אייאם פיצ'האכ. פלתכון להא כמצ'גע חיצ'תהא.",
         "And every bed upon which she lies throughout the days of her flow shall be to her as her bed during her menstrual period;"),
        ("וְכָל-הַכְּלִי אֲשֶׁר תֵּשֵׁב עָלָיו--טָמֵא יִהְיֶה כְּטֻמְאַת נִדָּתָהּ",
         "וגמיע אלאנא אלד'י תגלס עליה. פליכון נגסא. כנגאסתה פי חיצ'תהא",
         "and every vessel upon which she sits shall be impure, as its impurity during her menstrual period."),
    ],
    27: [
        ("וְכָל-הַנּוֹגֵעַ בָּם יִטְמָא",
         "וכל מן דנא בשי מנהא ינגס.",
         "And everyone who approaches anything of hers shall become impure;"),
        ("וְכִבֶּס בְּגָדָיו וְרָחַץ בַּמַּיִם וְטָמֵא עַד-הָעָרֶב",
         "פיג'סל ת'יאבה. וירחץ' באלמא וינגס אלי' אלמג'יב",
         "and he shall wash his garments, and bathe in water, and be impure until sunset."),
    ],
    28: [
        ("וְאִם-טָהֲרָה מִזּוֹבָהּ--וְסָפְרָה לָּהּ שִׁבְעַת יָמִים וְאַחַר תִּטְהָר",
         "פאן טהרת מן פיצ'הא. פלתחץ סבעה אייאם ובעד ד'אלך תטהר",
         "But if she is purified from her flow, she shall count off seven days, and after that she shall be pure."),
    ],
    29: [
        ("וּבַיּוֹם הַשְּׁמִינִי תִּקַּח-לָהּ שְׁתֵּי תֹרִים אוֹ שְׁנֵי בְּנֵי יוֹנָה",
         "ופי אליום אלת'אמן. תאכ'ד' שפנינין. או פרכ'י חמאם.",
         "And on the eighth day she shall take two turtledoves or two young pigeons,"),
        ("וְהֵבִיאָה אוֹתָם אֶל-הַכֹּהֵן אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "ותאתי בהמא אלי' אלאמאם. אלי' באב כ'בא אלמחצ'ר",
         "and bring them to the priest, to the entrance of the tent of the assembly."),
    ],
    30: [
        ("וְעָשָׂה הַכֹּהֵן אֶת-הָאֶחָד חַטָּאת וְאֶת-הָאֶחָד עֹלָה",
         "ויעמל אלאמאם אחדהמא ד'כוה. ואלאכ'ר צעידה.",
         "And the priest shall make one of them a purification-offering and the other a burnt-offering,"),
        ("וְכִפֶּר עָלֶיהָ הַכֹּהֵן לִפְנֵי יְהוָה מִזּוֹב טֻמְאָתָהּ",
         "ויסתג'פר ענהא בין ידי אללה. מן פיץ' נגאסתהא",
         "and shall seek forgiveness for her before God on account of the flow of her impurity."),
    ],
    31: [
        ("וְהִזַּרְתֶּם אֶת-בְּנֵי-יִשְׂרָאֵל מִטֻּמְאָתָם וְלֹא יָמֻתוּ בְּטֻמְאָתָם",
         "פיגב אן תגאנבא בני אסראיל מן נגאסתהם. ולא יהלכון בנגאסתהם.",
         "It is therefore required that the sons of Israel be kept apart from their impurity, so that they do not perish through their impurity —"),
        ("בְּטַמְּאָם אֶת-מִשְׁכָּנִי אֲשֶׁר בְּתוֹכָם",
         "אד' הם נגסו מסכני אלד'י פי מא בינהם",
         "for they would defile My dwelling that is among them."),
    ],
    32: [
        ("זֹאת תּוֹרַת הַזָּב וַאֲשֶׁר תֵּצֵא מִמֶּנּוּ שִׁכְבַת-זֶרַע לְטָמְאָה-בָהּ",
         "הד'ה שריעה' אלד'איב ומן תכ'ר'ג מנה נטפה לאלתנגס בהא",
         "This is the ordinance of the one with a discharge, and of him from whom a drop of seed goes forth, causing impurity."),
    ],
    33: [
        ("וְהַדָּוָה בְּנִדָּתָהּ וְהַזָּב אֶת-זוֹבוֹ לַזָּכָר וְלַנְּקֵבָה",
         "ואלחאיץ' פי טמת'הא. ואלפאיץ' פי ד'ובה. מן ד'כר ואנת'י.",
         "And of the menstruating woman in her menstruation, and of the one with a flow in his discharge — male and female —"),
        ("וּלְאִישׁ אֲשֶׁר יִשְׁכַּב עִם-טְמֵאָה",
         "ורג'ל יצ'אגע נגסה",
         "and of a man who lies with an impure woman."),
    ],
}
