"""Hand-authored alignment triples for Vayikra chapter 26.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא-תַעֲשׂוּ", "לא תצנעו", "Do not make"),
        ("לָכֶם", "לכם", "for yourselves"),
        ("אֱלִילִם", "אות'אנא", "idols"),
        (None, "ומנחותה", "and a carved thing"),
        ("וּמַצֵּבָה", "ונצבה", "and a standing-stone"),
        ("לֹא-תָקִימוּ", "לא תקימו", "do not erect"),
        ("לָכֶם", "לכם", "for yourselves"),
        ("וְאֶבֶן", "וחגר", "and an"),
        ("מַשְׂכִּית", "מזכ'רפא", "ornamental stone"),
        ("לֹא תִתְּנוּ", "לא תצנעו", "do not make"),
        ("בְּאַרְצְכֶם", "פי בלאדכם", "in your lands"),
        ("לְהִשְׁתַּחֲו‍ֹת", "לתסגדו", "to bow down"),
        ("עָלֶיהָ", "לה", "to it"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלואחד", "the One"),
    ],
    2: [
        ("אֶת-שַׁבְּתֹתַי", "סבותי", "My sabbaths"),
        ("תִּשְׁמֹרוּ", "פאחפצ'והא", "keep them"),
        ("וּמִקְדָּשִׁי", "ומקדסי", "and My sanctuary"),
        ("תִּירָאוּ", "פהאבוה", "hold it in awe"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אגאזיכם", "I shall recompense you"),
        (None, "כ'ירא", "with good"),
    ],
    3: [
        (None, "אלא", "Only"),
        (None, "אן", "if"),
        ("אִם-בְּחֻקֹּתַי", "סרתם", "you walk"),
        ("תֵּלֵכוּ", "פי רסומי", "in My statutes"),
        ("וְאֶת-מִצְו‍ֹתַי", "וחפצ'תם", "and keep"),
        ("תִּשְׁמְרוּ", "וצאיאי", "My commandments"),
        ("וַעֲשִׂיתֶם", "ועמלתם", "and act"),
        ("אֹתָם", "בהא", "according to them"),
    ],
    4: [
        ("וְנָתַתִּי", "נזלת", "I shall send down"),
        ("גִשְׁמֵיכֶם", "אג'יאתכם", "your rains"),
        ("בְּעִתָּם", "פי אוקאתהא", "in their seasons"),
        ("וְנָתְנָה הָאָרֶץ יְבוּלָהּ", "ואכ'רגת אלארץ' אדאהא", "and the earth shall bring forth its yield"),
        ("וְעֵץ", "ושגר", "and the trees of"),
        ("הַשָּׂדֶה", "אלצחרא", "the wilderness"),
        ("יִתֵּן", "יכ'רג", "shall bring forth"),
        ("פִּרְיוֹ", "תמרה", "their fruit"),
    ],
    5: [
        (None, "חתי'", "until"),
        ("וְהִשִּׂיג", "ידרך", "shall overtake"),
        ("לָכֶם", "לכם", "for you"),
        ("דַּיִשׁ", "אלדוס", "the threshing"),
        ("אֶת-בָּצִיר", "אלקטאף", "the harvest"),
        ("וּבָצִיר", "ואלקטאף", "and the harvest"),
        ("יַשִּׂיג", "ידרך", "shall overtake"),
        ("אֶת-זָרַע", "אלבדאר", "the sowing"),
        ("וַאֲכַלְתֶּם", "ותאכלון", "and you shall eat"),
        ("לַחְמְכֶם", "טעאמכם", "your food"),
        (None, "הנייא", "with pleasure"),
        ("וִישַׁבְתֶּם", "ותקימון", "and you shall dwell"),
        (None, "ואת'קין", "secure"),
        ("בְּאַרְצְכֶם", "פי בלדכם", "in your land"),
    ],
    6: [
        ("וְנָתַתִּי", "ואגעל", "And I shall establish"),
        (None, "לכם", "for you"),
        ("שָׁלוֹם", "אלסלאמה", "peace"),
        ("בָּאָרֶץ", "פי אלבלד", "in the land"),
        ("וּשְׁכַבְתֶּם", "פתנצ'געון", "so that you shall lie down"),
        (None, "וליס", "with nothing"),
        ("וְאֵין מַחֲרִיד", "מזעג", "to disturb you"),
        ("וְהִשְׁבַּתִּי", "ואעטל", "and I shall cause the harm"),
        ("חַיָּה רָעָה", "שר אלחיואן אלמפסד", "of the destructive beast to cease"),
        ("מִן-הָאָרֶץ", "מן אלארץ'", "from the land"),
        ("וְחֶרֶב", "וסיף", "and no sword"),
        ("לֹא-תַעֲבֹר", "לא ימר", "shall pass"),
        ("בְּאַרְצְכֶם", "פי בלדכם", "through your land"),
    ],
    7: [
        (None, "ואד'א", "And when"),
        ("וּרְדַפְתֶּם", "כלבתם", "you hunt down"),
        ("אֶת-אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
        ("וְנָפְלוּ", "וקעו", "they shall fall"),
        ("לִפְנֵיכֶם", "בין אידיכם", "before you"),
        ("לֶחָרֶב", "תחת סיופכם", "under your swords"),
    ],
    8: [
        (None, "חתי'", "Until"),
        ("וְרָדְפוּ מִכֶּם חֲמִשָּׁה", "יכלב מנכם אלכ'מסה", "five of you shall hunt down"),
        ("מֵאָה", "מאיה", "hundreds"),
        ("וּמֵאָה מִכֶּם רְבָבָה יִרְדֹּפוּ", "ואלמאיה תכלב רבווה", "and a hundred of you shall hunt down a multitude"),
        ("וְנָפְלוּ אֹיְבֵיכֶם", "ויקע אעדאיכם", "and your enemies shall fall"),
        ("לִפְנֵיכֶם", "בין אידיכם", "before you"),
        ("לֶחָרֶב", "תחת סיופכם", "under your swords"),
    ],
    9: [
        ("וּפָנִיתִי", "ואקבל", "And I shall turn"),
        ("אֲלֵיכֶם", "אליכם", "toward you"),
        ("וְהִפְרֵיתִי", "ואת'מרכם", "and make you fruitful"),
        ("אֶתְכֶם", "ואכת'רכם", "and multiply you"),
        ("וַהֲקִימֹתִי", "ואפי", "and I shall fulfil"),
        ("אֶת-בְּרִיתִי", "בעהדי", "My covenant"),
        ("אִתְּכֶם", "לכם", "with you"),
    ],
    10: [
        ("וַאֲכַלְתֶּם", "ותאכלון", "And you shall eat"),
        ("יָשָׁן", "אלעתיק", "the aged"),
        ("נוֹשָׁן", "אלמעתק", "long-stored"),
        ("וְיָשָׁן", "ותכ'רגון אלעתיק", "and you shall bring out the aged"),
        ("מִפְּנֵי", "מן חצ'רה'", "to make room for"),
        ("חָדָשׁ", "אלחדית'", "the new"),
    ],
    11: [
        ("וְנָתַתִּי", "ואגעל", "And I shall set"),
        ("מִשְׁכָּנִי", "מסכני", "My dwelling-place"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
        ("וְלֹא-תִגְעַל נַפְשִׁי אֶתְכֶם", "ולא אקלאכם", "and I shall not loathe you"),
    ],
    12: [
        ("וְהִתְהַלַּכְתִּי", "ואסייר", "And I shall cause"),
        (None, "נורי", "My light to move"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
        ("וְהָיִיתִי", "ואכון", "and I shall be"),
        ("לָכֶם", "לכם", "for you"),
        ("לֵאלֹהִים", "אלאהא", "the God"),
        ("וְאַתֶּם", "ואנתם", "and you shall be"),
        ("תִּהְיוּ-לִי", "תכונו לי", "for Me"),
        ("לְעָם", "שעבא", "a special"),
        (None, "כ'אצה", "people"),
    ],
    13: [
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("אֲשֶׁר", "אלד'י", "who"),
        ("הוֹצֵאתִי", "אכ'רגתכם", "brought you out"),
        ("אֶתְכֶם", "מן", "from"),
        ("מֵאֶרֶץ", "בלד", "the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("מִהְיֹת", "מן אן", "from being"),
        ("עֲבָדִים", "עבידא", "slaves"),
        ("לָהֶם", "תכונו להם", "to them"),
        ("וָאֶשְׁבֹּר", "וכסרת", "and I broke"),
        (None, "קראביס", "the yoke-bars of"),
        ("מֹטֹת עֻלְּכֶם", "אצרכם", "your bonds"),
        ("וָאוֹלֵךְ", "וסיירתכם", "and led you forth"),
        ("אֶתְכֶם", "אחרארא", "as free people"),
    ],
    14: [
        (None, "ואן", "But if"),
        ("וְאִם-לֹא", "לם תסמעו", "you do not hearken"),
        ("תִשְׁמְעוּ", "לי", "to Me"),
        ("לִי", "ותטיעו", "and obey"),
        ("וְלֹא תַעֲשׂוּ", "ולם תעמלו", "and do not act"),
        ("אֵת כָּל-הַמִּצְו‍ֹת הָאֵלֶּה", "בגמיע הד'ה אלוצאיא", "according to all these commandments"),
    ],
    15: [
        (None, "בל", "but rather"),
        ("וְאִם-בְּחֻקֹּתַי תִּמְאָסוּ", "זהדתם פי רסומי", "you have turned away from My statutes"),
        ("וְאִם אֶת-מִשְׁפָּטַי", "ואקלאת", "and your souls have come to loathe"),
        ("תִּגְעַל נַפְשְׁכֶם", "אנפסכם אחכאמי", "My ordinances"),
        ("לְבִלְתִּי עֲשׂוֹת", "ללא תעמלו", "so as not to act"),
        ("אֶת-כָּל-מִצְו‍ֹתַי", "וצאיאי", "according to My commandments"),
        ("לְהַפְרְכֶם", "ותפסכו", "and you break"),
        ("אֶת-בְּרִיתִי", "עהדי", "My covenant"),
    ],
    16: [
        ("אַף-אֲנִי", "אנא איצ'א", "I too"),
        ("אֶעֱשֶׂה-זֹּאת", "אצנע בכם", "shall do to you"),
        ("לָכֶם", "הד'ה אלעקובאת", "these punishments"),
        ("וְהִפְקַדְתִּי", "פאוכל בכם", "I shall set over you"),
        ("עֲלֵיכֶם", "עלי'", "in"),
        ("בֶּהָלָה", "סרעה", "haste"),
        ("אֶת-הַשַּׁחֶפֶת", "מן חמא אלסל", "the fever of consumption"),
        ("וְאֶת-הַקַּדַּחַת", "ואלחארה", "and the burning heat"),
        ("מְכַלּוֹת עֵינַיִם", "מא תשכץ עיונכם", "which make your eyes stare"),
        ("וּמְדִיבֹת נָפֶשׁ", "ותד'בל נפוסכם", "and drain away your souls"),
        ("וּזְרַעְתֶּם", "ותזרעון", "and you shall sow"),
        ("זַרְעֲכֶם", "זרעכם", "your seed"),
        ("לָרִיק", "לאלפראג'", "for nothing"),
        ("וַאֲכָלֻהוּ", "ויאכלונה", "shall eat it"),
        ("אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
    ],
    17: [
        ("וְנָתַתִּי", "ואחל", "And I shall bring"),
        ("פָנַי", "ג'צ'בי", "My wrath"),
        ("בָּכֶם", "בכם", "upon you"),
        ("וְנִגַּפְתֶּם", "פתנצדמון", "so that you shall be struck down"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
        ("וְרָדוּ", "ויסתולי", "shall rule"),
        ("בָכֶם", "עליכם", "over you"),
        ("שֹׂנְאֵיכֶם", "שאניכם", "those who hate you"),
        ("וְנַסְתֶּם", "פתפרון", "and you shall flee"),
        ("וְאֵין-רֹדֵף", "ולא כאלב", "with none pursuing"),
        ("אֶתְכֶם", "לכם", "you"),
    ],
    18: [
        (None, "ואן", "And if"),
        ("וְאִם-עַד-אֵלֶּה", "לם תקבלו מני מע הד'ה", "you still do not accept from Me with all this"),
        ("לֹא תִשְׁמְעוּ לִי", "זדתכם", "I shall increase"),
        ("וְיָסַפְתִּי", "פי אלתאדיב", "your chastisement"),
        ("לְיַסְּרָה אֶתְכֶם", "סבע", "sevenfold"),
        ("שֶׁבַע", "עלי'", "upon"),
        ("עַל-חַטֹּאתֵיכֶם", "כטאיאכם", "your sins"),
    ],
    19: [
        ("וְשָׁבַרְתִּי", "ואכסר", "And I shall break"),
        ("אֶת-גְּאוֹן", "אקתדאר", "the might of"),
        ("עֻזְּכֶם", "עזכם", "your pride"),
        ("וְנָתַתִּי", "ואגעל", "and make"),
        ("אֶת-שְׁמֵיכֶם", "סמאכם", "your sky"),
        ("כַּבַּרְזֶל", "כאלחדיד", "like iron"),
        ("וְאֶת-אַרְצְכֶם", "וארצכם", "and your earth"),
        ("כַּנְּחֻשָׁה", "כאלנחאס", "like copper"),
    ],
    20: [
        ("וְתַם לָרִיק כֹּחֲכֶם", "פיפנא קואכם פראג'א", "And your strength shall perish for nothing"),
        ("וְלֹא-תִתֵּן אַרְצְכֶם אֶת-יְבוּלָהּ", "ולא תכ'רג ארצ'כם אדאהא", "and your land shall not bring forth its yield"),
        ("וְעֵץ הָאָרֶץ", "ושגר אלצחרא", "and the trees of the wilderness"),
        ("לֹא יִתֵּן", "לא יכ'רג", "shall not bring forth"),
        ("פִּרְיוֹ", "ת'מרה", "their fruit"),
    ],
    21: [
        (None, "ואן", "And if"),
        ("וְאִם-תֵּלְכוּ", "סלכתם", "you have walked"),
        ("עִמִּי", "מעי", "with Me"),
        ("קֶרִי", "לגאגא", "in contention"),
        ("וְלֹא תֹאבוּ", "ולם תשו", "and have not been willing"),
        ("לִשְׁמֹעַ", "אן תסמעו", "to hearken"),
        ("לִי", "לי", "to Me"),
        ("וְיָסַפְתִּי", "זדתכם", "I shall add"),
        ("עֲלֵיכֶם", "צ'רבה", "upon you"),
        ("מַכָּה", "הי", "a blow"),
        ("שֶׁבַע", "סבע", "sevenfold"),
        ("כְּחַטֹּאתֵיכֶם", "עלי' כטאיאכם", "upon your sins"),
    ],
    22: [
        ("וְהִשְׁלַחְתִּי", "ואטלק", "And I shall release"),
        ("בָכֶם", "פיכם", "against you"),
        ("אֶת-חַיַּת הַשָּׂדֶה", "חיואן אלצחרא", "the beasts of the wilderness"),
        ("וְשִׁכְּלָה", "פית'כל", "and they shall bereave you"),
        ("אֶתְכֶם", "מנכם", "of your children"),
        ("וְהִכְרִיתָה", "ויקטע", "and cut down"),
        ("אֶת-בְּהֶמְתְּכֶם", "מן בהאימכם", "your cattle"),
        ("וְהִמְעִיטָה", "ויקלל", "and reduce"),
        ("אֶתְכֶם", "עדדכם", "your number"),
        ("וְנָשַׁמּוּ", "ותתוחש", "shall become desolate"),
        ("דַּרְכֵיכֶם", "טרקאתכם", "your roads"),
    ],
    23: [
        (None, "ואן", "And if"),
        ("וְאִם-בְּאֵלֶּה", "לם תתאדבו לי", "you are not disciplined toward Me"),
        ("לֹא תִוָּסְרוּ", "בהד'ה אלעקובאת", "by these punishments"),
        ("לִי", "וסלכתם", "and you walk"),
        ("וַהֲלַכְתֶּם", "מעי", "with Me"),
        ("עִמִּי קֶרִי", "לגאגא", "in contention"),
    ],
    24: [
        ("וְהָלַכְתִּי אַף-אֲנִי עִמָּכֶם בְּקֶרִי", "סרת אנא איצ'א מעכם עלי' אללגאג", "I too shall walk with you in contention"),
        ("וְהִכֵּיתִי", "וצ'רבתכם", "and I shall smite you"),
        ("אֶתְכֶם", "בסבע", "sevenfold"),
        ("שֶׁבַע", "עלי'", "upon"),
        ("עַל-חַטֹּאתֵיכֶם", "כטאיאכם", "your sins"),
    ],
    25: [
        ("וְהֵבֵאתִי", "ואג'זיכם", "And I shall recompense you"),
        ("עֲלֵיכֶם", "סיפא", "with a sword"),
        ("חֶרֶב", "מנתקמא", "that avenges"),
        ("נֹקֶמֶת", "נקמה'", "the vengeance of"),
        ("נְקַם-בְּרִית", "אלעהד", "the covenant"),
        ("וְנֶאֱסַפְתֶּם", "פתגתמעון", "and you shall gather"),
        ("אֶל-עָרֵיכֶם", "אלי' קראכם", "into your towns"),
        ("וְשִׁלַּחְתִּי", "ואבעת'", "and I shall send"),
        ("דֶבֶר", "באלובא", "pestilence"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
        ("וְנִתַּתֶּם", "ותסלמון", "and you shall be delivered"),
        ("בְּיַד-אוֹיֵב", "פי יד אלעדו", "into the hand of the enemy"),
    ],
    26: [
        ("בְּשִׁבְרִי", "ואכסר", "And I shall break"),
        ("לָכֶם", "לכם", "for you"),
        ("מַטֵּה-לֶחֶם", "מעין אלטעאם", "the spring of food"),
        (None, "פיכבז", "so that"),
        ("וְאָפוּ", "כתיר", "many"),
        ("עֶשֶׂר נָשִׁים", "מן אלנסא", "women"),
        ("לַחְמְכֶם", "טעאמכם", "your bread"),
        ("בְּתַנּוּר אֶחָד", "פי תנור ואחד", "in one oven"),
        ("וְהֵשִׁיבוּ", "וירדונה", "and they shall return it"),
        ("בַּמִּשְׁקָל", "באלמיזאן", "by weight"),
        ("וַאֲכַלְתֶּם", "ותאכלון", "and you shall eat"),
        ("וְלֹא תִשְׂבָּעוּ", "ולא תשבעון", "and not be satisfied"),
    ],
    27: [
        (None, "ואן", "And if"),
        ("וְאִם-בְּזֹאת", "לם תסמעו לי", "you do not hearken to Me"),
        ("לֹא תִשְׁמְעוּ לִי", "ותטיעו", "and obey"),
        (None, "בהד'ה אלעקובאת", "with all these punishments"),
        ("וַהֲלַכְתֶּם", "וסלכתם", "and you walk"),
        ("עִמִּי", "מעי", "with Me"),
        ("בְּקֶרִי", "לגאגא", "in contention"),
    ],
    28: [
        ("וְהָלַכְתִּי עִמָּכֶם בַּחֲמַת-קֶרִי", "סרת אנא איצ'א מעכם בעקובאת אללגאג", "I too shall walk with you with the punishments of contention"),
        ("וְיִסַּרְתִּי", "ואדבתכם", "and I shall discipline you"),
        ("אֶתְכֶם", "בסבע", "sevenfold"),
        ("שֶׁבַע", "עלי'", "upon"),
        ("עַל-חַטֹּאתֵיכֶם", "כטאיאכם", "your sins"),
    ],
    29: [
        (None, "חתי'", "Until"),
        ("וַאֲכַלְתֶּם", "תאכלון", "you eat"),
        ("בְּשַׂר", "לחום", "the flesh of"),
        ("בְּנֵיכֶם", "בניכם", "your sons"),
        ("וּבְשַׂר בְּנֹתֵיכֶם תֹּאכֵלוּ", "ובנאתכם", "and the flesh of your daughters"),
    ],
    31: [
        ("וְנָתַתִּי", "ואגעל", "And I shall make"),
        ("אֶת-עָרֵיכֶם", "קראכם", "your towns"),
        ("חָרְבָּה", "כ'ראבא", "a ruin"),
        ("וַהֲשִׁמּוֹתִי", "ואוחש", "and cause desolation in"),
        ("אֶת-מִקְדְּשֵׁיכֶם", "מקאדסכם", "your sanctuaries"),
        ("וְלֹא אָרִיחַ", "ולא אקבל ולא ארצ'א", "and I shall neither accept nor be pleased"),
        (None, "קראבינכם", "with your offerings"),
    ],
    32: [
        ("וַהֲשִׁמֹּתִי אֲנִי אֶת-הָאָרֶץ", "ואוחש אנא אלבלד מנכם", "And I shall desolate the land of you"),
        ("וְשָׁמְמוּ", "ויסתוחש", "shall be desolated"),
        ("עָלֶיהָ", "מנהא", "of it"),
        ("אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
        ("הַיֹּשְׁבִים", "אלמקימין", "who dwell"),
        ("בָּהּ", "בהא", "in it"),
    ],
    33: [
        ("וְאֶתְכֶם אֱזָרֶה", "ואד'ריכם", "And I shall scatter you"),
        ("בַגּוֹיִם", "פי מא בין אלאמם", "among the nations"),
        ("וַהֲרִיקֹתִי אַחֲרֵיכֶם חָרֶב", "ואגרד אלסיף וראכם", "and I shall draw the sword after you"),
        ("וְהָיְתָה אַרְצְכֶם שְׁמָמָה", "פתציר ארצכם וחשה", "and your land shall become a waste"),
        ("וְעָרֵיכֶם יִהְיוּ חָרְבָּה", "וקראכם. כ'ראבא", "and your towns a ruin"),
    ],
    34: [
        (None, "חיניד'", "At that time"),
        ("אָז תִּרְצֶה הָאָרֶץ אֶת-שַׁבְּתֹתֶיהָ", "תסתופי אלארץ' עטלהא", "the land shall receive its rest"),
        ("כֹּל יְמֵי הָשַּׁמָּה", "טול אייאם וחשתהא", "all the days of its desolation"),
        ("וְאַתֶּם", "ואנתם", "while you are"),
        ("בְּאֶרֶץ", "פי בלד", "in the land of"),
        ("אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
        (None, "חיניד'", "at that time"),
        ("אָז תִּשְׁבַּת הָאָרֶץ", "תתסייב אלארץ'", "the land shall be left fallow"),
        ("וְהִרְצָת אֶת-שַׁבְּתֹתֶיהָ", "ותסתופי עטלהא", "and receive its rest"),
    ],
    35: [
        (None, "וסבב", "And the reason for"),
        ("כָּל-יְמֵי הָשַּׁמָּה", "טול אייאם וחשתהא", "the length of the days of its desolation"),
        ("תִּשְׁבֹּת", "אן תתעטל", "is that it shall rest"),
        ("אֵת אֲשֶׁר", "כמא", "even as"),
        ("לֹא-שָׁבְתָה", "לם תעטלונהא", "you did not let it rest"),
        ("בְּשַׁבְּתֹתֵיכֶם", "פי עטלכם", "in its rest-times"),
        ("בְּשִׁבְתְּכֶם", "פי מקאמכם", "while you were dwelling"),
        ("עָלֶיהָ", "בהא", "upon it"),
    ],
    36: [
        ("וְהַנִּשְׁאָרִים בָּכֶם", "ואלבאקיון מנכם", "And those of you who remain"),
        ("וְהֵבֵאתִי", "אדכל", "I shall bring"),
        ("מֹרֶךְ", "אלגבן", "cowardice"),
        ("בִּלְבָבָם", "פי קלובהם", "into their hearts"),
        ("בְּאַרְצֹת", "פי בלדאן", "in the lands of"),
        ("אֹיְבֵיהֶם", "אעדאיהם", "their enemies"),
        (None, "חתי'", "so that"),
        (None, "אנה לו", "even if"),
        ("וְרָדַף אֹתָם", "לחקהם", "overtook them"),
        ("קוֹל עָלֶה נִדָּף", "צות ורקה מנדפעה", "the sound of a driven leaf"),
        ("וְנָסוּ", "והרבו", "they would flee"),
        ("מְנֻסַת-חֶרֶב", "כאלהארב מן אלסיף", "as one fleeing from the sword"),
        ("וְנָפְלוּ", "ווקעו", "and they would fall"),
        ("וְאֵין רֹדֵף", "מן ג'יר כאלב", "with none pursuing them"),
    ],
    37: [
        ("וְכָשְׁלוּ", "ויעת'ר", "And they shall stumble"),
        ("אִישׁ-בְּאָחִיו", "בעצהם בבעץ'", "over one another"),
        ("כְּמִפְּנֵי-חֶרֶב", "כמא יכון מן קבל אלסיף", "as happens before the sword"),
        ("וְרֹדֵף אָיִן", "מן ג'יר כאלב", "with none pursuing"),
        ("וְלֹא-תִהְיֶה לָכֶם", "ולא יכון לכם", "and you shall have no"),
        ("תְּקוּמָה", "קואם", "power to stand"),
        ("לִפְנֵי אֹיְבֵיכֶם", "בין ידי אעדאיכם", "before your enemies"),
    ],
    38: [
        ("וַאֲבַדְתֶּם", "ויביד מנכם", "And some of you shall perish"),
        ("בַּגּוֹיִם", "פי מא בין אלאמם", "among the nations"),
        ("וְאָכְלָה", "ויפניכם", "shall consume you"),
        ("אֶרֶץ", "בלד", "the land of"),
        ("אֹיְבֵיכֶם", "אעדאיכם", "your enemies"),
    ],
    39: [
        ("וְהַנִּשְׁאָרִים בָּכֶם", "ואלבאקיון מנכם", "And those of you who remain"),
        ("יִמַּקּוּ", "יכ'סעון", "shall be humbled"),
        ("בַּעֲו‍ֹנָם", "בד'נובהם", "by their sins"),
        ("בְּאַרְצֹת אֹיְבֵיכֶם", "פי בלדאן אעדאיכם", "in the lands of your enemies"),
        ("וְאַף", "ואיצ'א", "and also"),
        ("בַּעֲו‍ֹנֹת", "בד'נוב", "by the sins of"),
        ("אֲבֹתָם", "אבאיהם", "their fathers"),
        ("אִתָּם", "אלד'ין מעהם", "who are with them"),
        ("יִמָּקּוּ", "יכ'סעון", "they shall be humbled"),
    ],
    40: [
        (None, "פאן", "But if"),
        ("וְהִתְוַדּוּ", "אקרו", "they confess"),
        ("אֶת-עֲו‍ֹנָם", "בד'נובהם", "their sins"),
        ("וְאֶת-עֲו‍ֹן", "וד'נוב", "and the sins of"),
        ("אֲבֹתָם", "אבאיהם", "their fathers"),
        ("בְּמַעֲלָם", "בנכת'הם", "in their treachery"),
        ("אֲשֶׁר", "אלד'י", "with which"),
        ("מָעֲלוּ-בִי", "נכתו בי", "they were treacherous against Me"),
        ("וְאַף", "ומא", "and in that"),
        ("אֲשֶׁר-הָלְכוּ", "סלכו", "they walked"),
        ("עִמִּי", "מעי", "with Me"),
        ("בְּקֶרִי", "לגאגא", "in contention"),
        (None, "ולם יתובון", "and did not repent"),
    ],
    41: [
        ("אַף-אֲנִי", "אנא איצ'א", "I too"),
        ("אֵלֵךְ", "אסיר", "shall walk"),
        ("עִמָּם", "מעהם", "with them"),
        ("בְּקֶרִי", "עלי' אללגאג", "in contention"),
        ("וְהֵבֵאתִי", "ואדכ'להם", "and I shall bring them"),
        ("אֹתָם", "אלי' בלדאן", "into the lands of"),
        ("בְּאֶרֶץ", "אעדאיהם", "their enemies"),
        ("אֹיְבֵיהֶם", "אכ'רין", "again"),
        ("אוֹ-אָז יִכָּנַע לְבָבָם הֶעָרֵל", "או אלי' אן ינהזם קלבהם אלג'אש", "or until their obdurate heart is subdued"),
        ("וְאָז יִרְצוּ", "או אלי' אן", "or until they have"),
        ("אֶת-עֲו‍ֹנָם", "יסתופון ד'נובהם", "paid the full price of their sins"),
    ],
    42: [
        (None, "ואד'כר", "Then I shall remember"),
        ("וְזָכַרְתִּי", "להם", "for them"),
        ("אֶת-בְּרִיתִי", "עהדי", "My covenant"),
        ("יַעֲקוֹב", "אלד'י מע יעקוב", "with Jacob"),
        ("וְאַף", "ואיצ'א", "and also"),
        ("אֶת-בְּרִיתִי", "עהדי", "My covenant"),
        ("יִצְחָק", "אלד'י מע יצחק", "with Isaac"),
        (None, "ואיצ'א", "and also"),
        (None, "עהדי", "My covenant"),
        (None, "אלד'י מע אברהים", "with Abraham"),
        ("וְאַף אֶת-בְּרִיתִי אַבְרָהָם", "אדכרה", "I shall remember it"),
        ("אֶזְכֹּר", "להם", "for them"),
        ("וְהָאָרֶץ אֶזְכֹּר", "ולנסלהם", "and for their offspring"),
    ],
    43: [
        ("וְהָאָרֶץ", "ואלארץ'", "And the land"),
        ("תֵּעָזֵב", "אלד'י תרכת", "that was left"),
        ("מֵהֶם", "מנהם", "of them"),
        ("וְתִרֶץ", "ואסתופת", "and received"),
        ("אֶת-שַׁבְּתֹתֶיהָ", "עטלהא", "its rest"),
        ("בָּהְשַׁמָּה", "באסתוחאשהא", "through being desolated"),
        ("מֵהֶם", "מנהם", "of them"),
        ("וְהֵם", "והם", "and they"),
        ("יִרְצוּ", "אסתופו", "paid the full price of"),
        ("אֶת-עֲו‍ֹנָם", "ד'נובהם", "their sins"),
        ("יַעַן", "גזאהם", "as their recompense"),
        ("וּבְיַעַן", "ומן גזאהם", "and part of their recompense"),
        ("בְּמִשְׁפָּטַי", "אד' זהדו פי אחכאמי", "since they had turned away from My ordinances"),
        ("מָאָסוּ", "ורסומי", "My statutes"),
        ("וְאֶת-חֻקֹּתַי גָּעֲלָה נַפְשָׁם", "אקלאתהא אנפסהם", "their souls had loathed"),
    ],
    44: [
        (None, "ואיצ'א", "And also"),
        ("וְאַף-גַּם-זֹאת", "מע הד'ה אלאמור", "along with all these things"),
        ("בִּהְיוֹתָם", "מע כונהם", "even while they are"),
        ("בְּאֶרֶץ", "פי בלדאן", "in the lands of"),
        ("אֹיְבֵיהֶם", "אעדאיהם", "their enemies"),
        ("לֹא-מְאַסְתִּים", "לא אזהד פיהם", "I shall not turn away from them"),
        ("וְלֹא-גְעַלְתִּים", "ולא אקלאהם", "nor shall I loathe them"),
        ("לְכַלֹּתָם", "לאפנאהם", "to destroy them"),
        ("לְהָפֵר", "ולא אפסך'", "nor shall I annul"),
        ("בְּרִיתִי", "עהדי", "My covenant"),
        ("אִתָּם", "מעהם", "with them"),
        ("כִּי אֲנִי יְהוָה אֱלֹהֵיהֶם", "לאני אללה רבהם", "for I am God their Lord"),
    ],
    45: [
        ("וְזָכַרְתִּי", "ואדכר", "And I shall remember"),
        ("לָהֶם", "להם", "for them"),
        ("בְּרִית", "עהד", "the covenant of"),
        ("רִאשֹׁנִים", "אלאוולין", "the first ones"),
        ("אֲשֶׁר", "אלד'ין", "whom"),
        ("הוֹצֵאתִי-אֹתָם", "אכ'רגתהם", "I brought out"),
        ("מֵאֶרֶץ", "מן בלד", "from the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("לְעֵינֵי", "בחצ'רה", "in the presence of"),
        ("הַגּוֹיִם", "אלאמם", "the nations"),
        ("לִהְיוֹת", "לאכון", "to be"),
        ("לָהֶם", "להם", "their"),
        ("לֵאלֹהִים", "אלאהא", "God"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "צאדק אלועד", "true to My promise"),
    ],
    46: [
        ("אֵלֶּה", "הד'ה", "These are"),
        ("הַחֻקִּים", "אלרסום", "the statutes"),
        ("וְהַמִּשְׁפָּטִים", "ואלאחכאם", "and the ordinances"),
        ("וְהַתּוֹרֹת", "ואלדלאיל", "and the guiding principles"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("נָתַן", "געלהא", "established"),
        ("יְהוָה", "אללה", "God"),
        ("בֵּינוֹ", "בינה", "between Him"),
        ("וּבֵין", "ובין", "and"),
        ("בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("בְּהַר", "עלי' טור", "upon Mount"),
        ("סִינַי", "סיני", "Sinai"),
        ("בְּיַד-מֹשֶׁה", "עלי' יד מוסי", "by the hand of Moses"),
    ],
}
