"""Hand-authored alignment triples for Vayikra chapter 8.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    2: [
        ("קַח", "קדם", "Present"),
        ("אֶת-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶת-בָּנָיו", "ובניה", "and his sons"),
        ("אִתּוֹ", "מעה", "with him"),
        ("וְאֵת הַבְּגָדִים", "ואלת'יאב", "and the garments"),
        ("וְאֵת שֶׁמֶן הַמִּשְׁחָה", "ודהן אלמסוחייה", "and the anointing oil"),
        ("וְאֵת פַּר הַחַטָּאת", "ורת' אלדכוה", "and the bull of the purification-offering"),
        ("וְאֵת שְׁנֵי הָאֵילִים", "ואלכבשין", "and the two rams"),
        ("וְאֵת סַל הַמַּצּוֹת", "וסל אלפטיר", "and the basket of unleavened bread"),
    ],
    3: [
        ("וְאֵת כָּל-הָעֵדָה", "וגווק אלגמע", "And assemble the congregation"),
        ("הַקְהֵל אֶל-פֶּתַח", "אלי' באב", "to the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the appointed meeting"),
    ],
    4: [
        ("וַיַּעַשׂ", "פעמל", "did"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמרה", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("וַתִּקָּהֵל", "פתגווק", "assembled"),
        ("הָעֵדָה", "אלגמע", "the congregation"),
        ("אֶל-פֶּתַח", "אלי' באב", "at the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the appointed meeting"),
    ],
    5: [
        ("וַיֹּאמֶר", "פקאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-הָעֵדָה", "להם", "to them"),
        ("זֶה", "הד'א", "This is"),
        ("הַדָּבָר", "אלאמר", "the matter"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("צִוָּה", "אמר", "has commanded"),
        ("יְהוָה", "אללה", "God"),
        ("לַעֲשׂוֹת", "אן תעמלו", "that you do"),
    ],
    6: [
        ("וַיַּקְרֵב", "פקדם", "presented"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶת-בָּנָיו", "ובניה", "and his sons"),
        ("וַיִּרְחַץ אֹתָם", "וג'סלהם", "and washed them"),
        ("בַּמָּיִם", "באלמא", "with water"),
    ],
    7: [
        ("וַיִּתֵּן עָלָיו", "וגעל עליה", "And he put upon him"),
        ("אֶת-הַכֻּתֹּנֶת", "אלתוניה", "the tunic"),
        ("וַיַּחְגֹּר אֹתוֹ", "וקלדה", "and girded him"),
        ("בָּאַבְנֵט", "באלזנאר", "with the sash"),
        ("וַיַּלְבֵּשׁ אֹתוֹ", "ואלבסה", "and clothed him"),
        ("אֶת-הַמְּעִיל", "אלממטר", "with the robe"),
        ("וַיִּתֵּן עָלָיו", "וגעל עליה", "and placed upon him"),
        ("אֶת-הָאֵפֹד", "אלצדרה", "the breastpiece"),
        ("וַיַּחְגֹּר אֹתוֹ", "ושדדה", "and fastened it"),
        ("בְּחֵשֶׁב הָאֵפֹד", "בהמיאנהא", "with its belt"),
        ("וַיֶּאְפֹּד לוֹ בּוֹ", "וצדרה בהא", "and bound him with it"),
    ],
    8: [
        ("וַיָּשֶׂם עָלָיו", "וצייר עליה", "And he set upon him"),
        ("אֶת-הַחֹשֶׁן", "אלבדנה", "the body-piece"),
        ("וַיִּתֵּן", "וגעל", "and placed"),
        ("אֶל-הַחֹשֶׁן", "פיהא", "within it"),
        ("אֶת-הָאוּרִים", "אלאנואר", "the lights"),
        ("וְאֶת-הַתֻּמִּים", "ואלצחאיח", "and the truths"),
    ],
    9: [
        ("וַיָּשֶׂם", "וצייר", "And he set"),
        ("אֶת-הַמִּצְנֶפֶת", "אלעמאמה", "the turban"),
        ("עַל-רֹאשׁוֹ", "עלי' ראסה", "upon his head"),
        ("וַיָּשֶׂם", "וגעל", "and placed"),
        ("עַל-הַמִּצְנֶפֶת", "דונהא", "beneath it"),
        ("אֶל-מוּל פָּנָיו", "ממא ילי וגהה", "on the side facing his face"),
        ("אֵת צִיץ הַזָּהָב", "עצאבה' אלד'הב", "the golden band"),
        ("נֵזֶר הַקֹּדֶשׁ", "תאג אלקדס", "the diadem of holiness"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
    ],
    10: [
        ("וַיִּקַּח", "ואכ'ד'", "took"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-שֶׁמֶן הַמִּשְׁחָה", "דהן אלמסוחייה", "the anointing oil"),
        ("וַיִּמְשַׁח", "ומסח", "and anointed"),
        (None, "מנה", "with it"),
        ("אֶת-הַמִּשְׁכָּן", "אלמסכן", "the tabernacle"),
        ("וְאֶת-כָּל-אֲשֶׁר-בּוֹ", "וגמיע מא פיה", "and all that was in it"),
        ("וַיְקַדֵּשׁ אֹתָם", "וקדסהם", "and consecrated them"),
    ],
    11: [
        ("וַיַּז מִמֶּנּוּ", "ונצ'ח מנה", "And he sprinkled from it"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("וַיִּמְשַׁח", "ומסח", "and anointed"),
        ("אֶת-הַמִּזְבֵּחַ", "אלמד'בח", "the altar"),
        ("וְאֶת-כָּל-כֵּלָיו", "וגמיע מא פיה", "and all that was upon it"),
        ("וְאֶת-הַכִּיֹּר", "ואלחוץ'", "and the laver"),
        ("וְאֶת-כַּנּוֹ", "ומקעדה", "and its bases"),
        ("לְקַדְּשָׁם", "וקדסהם", "and consecrated them"),
    ],
    12: [
        ("וַיִּצֹק", "וצב", "And he poured"),
        ("מִשֶּׁמֶן הַמִּשְׁחָה", "מן דהן אלמסוחייה", "from the anointing oil"),
        ("עַל רֹאשׁ", "עלי' ראס", "upon the head of"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וַיִּמְשַׁח אֹתוֹ", "ומסחה", "and anointed him"),
        ("לְקַדְּשׁוֹ", "וקדסה", "and consecrated him"),
    ],
    13: [
        ("וַיַּקְרֵב", "וקרב", "presented"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("וַיַּלְבִּשֵׁם כֻּתֳּנֹת", "ואלבסהם תואניא", "and clothed them with tunics"),
        ("וַיַּחְגֹּר אֹתָם אַבְנֵט", "וקלדהם בזנאניר", "and girded them with sashes"),
        ("וַיַּחֲבֹשׁ לָהֶם מִגְבָּעוֹת", "וצ'מדהם בקלאנס", "and bound their heads with caps"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
    ],
    14: [
        (None, "ת'ם", "Then"),
        ("וַיַּגֵּשׁ", "קדם", "he presented"),
        ("אֵת פַּר הַחַטָּאת", "רת' אלדכוה", "the bull of the purification-offering"),
        ("וַיִּסְמֹךְ", "ואסנד", "laid"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("אֶת-יְדֵיהֶם", "אידיהם", "their hands"),
        ("עַל-רֹאשׁ פַּר הַחַטָּאת", "עלי' ראסה", "upon its head"),
    ],
    15: [
        ("וַיִּשְׁחָט", "פד'בחה", "And he slaughtered it"),
        ("וַיִּקַּח", "ואכ'ד'", "took"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-הַדָּם", "מן דמה", "some of its blood"),
        ("וַיִּתֵּן", "וגעל", "and placed it"),
        ("עַל-קַרְנוֹת הַמִּזְבֵּחַ", "עלי' ארכאן אלמד'בח", "upon the horns of the altar"),
        ("סָבִיב", "מסתדירא", "going around"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("וַיְחַטֵּא אֶת-הַמִּזְבֵּחַ", "וד'כאה", "and purified it"),
        ("וְאֶת-הַדָּם", "ובאקי אלדם", "and the remaining blood"),
        ("יָצַק", "צבה", "he poured"),
        ("אֶל-יְסוֹד הַמִּזְבֵּחַ", "ענד אסאסה", "at its base"),
        ("וַיְקַדְּשֵׁהוּ", "וקדסה", "and consecrated it"),
        ("לְכַפֵּר עָלָיו", "ואסתג'פר ענה", "and sought atonement for it"),
    ],
    16: [
        ("וַיִּקַּח", "ואכ'ד'", "And he took"),
        ("אֶת-כָּל-הַחֵלֶב", "גמיע אלת'רב", "all the fat"),
        ("אֲשֶׁר עַל-הַקֶּרֶב", "אלד'י עלי' אלגוף", "that was upon the belly"),
        ("וְאֵת יֹתֶרֶת הַכָּבֵד", "וזיאדה' אלכבד", "and the lobe of the liver"),
        ("וְאֶת-שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-חֶלְבְּהֶן", "ושחמהמא", "with their fat"),
        ("וַיַּקְטֵר מֹשֶׁה הַמִּזְבֵּחָה", "וקתרה עלי' אלמד'בח", "and burned it as smoke upon the altar"),
    ],
    17: [
        ("וְאֶת-הַפָּר", "ואלרת'", "But the bull"),
        (None, "מע", "with"),
        ("וְאֶת-עֹרוֹ", "גלדה", "its hide"),
        ("וְאֶת-בְּשָׂרוֹ", "ולחמה", "and its flesh"),
        ("וְאֶת-פִּרְשׁוֹ", "מע פרתה", "and its dung"),
        ("שָׂרַף בָּאֵשׁ", "אחרקה באלנאר", "he burned with fire"),
        ("מִחוּץ לַמַּחֲנֶה", "כ'ארג אלעסכר", "outside the camp"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
    ],
    18: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he presented"),
        ("אֵת אֵיל הָעֹלָה", "כבש אלצעידה", "the ram of the burnt-offering"),
        ("וַיִּסְמְכוּ", "פאסנד", "laid"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("אֶת-יְדֵיהֶם", "אידיהם", "their hands"),
        ("עַל-רֹאשׁ הָאָיִל", "עלי' ראסה", "upon its head"),
    ],
    19: [
        ("וַיִּשְׁחָט", "פד'בחה", "And he slaughtered it"),
        ("וַיִּזְרֹק", "ונצ'ח", "sprinkled"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-הַדָּם", "אלדם", "the blood"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    20: [
        ("וְאֶת-הָאַיִל", "ועצ'א מוסי' אלכבש", "And Moses cut the ram"),
        ("נִתַּח לִנְתָחָיו", "אעצ'אא", "into its pieces"),
        ("וַיַּקְטֵר מֹשֶׁה", "וקתר", "and burned as smoke"),
        ("אֶת-הָרֹאשׁ", "אלראס", "the head"),
        ("וְאֶת-הַנְּתָחִים", "ואלאעצ'א", "and the pieces"),
        ("וְאֶת-הַפָּדֶר", "ואלקצבה", "and the backbone"),
    ],
    21: [
        ("וְאֶת-הַקֶּרֶב", "ואלבטן", "And the belly"),
        ("וְאֶת-הַכְּרָעַיִם", "ואלאכארע", "and the legs"),
        ("רָחַץ בַּמָּיִם", "ג'סלהא באלמא", "he washed with water"),
        ("וַיַּקְטֵר", "וקתר", "burned"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-כָּל-הָאַיִל הַמִּזְבֵּחָה", "גמיע אלכבש עלי' אלמד'בח", "the whole ram as smoke upon the altar"),
        (None, "הו", "it is"),
        ("עֹלָה", "צעידה", "burnt-offering"),
        (None, "מקבול", "accepted"),
        (None, "מרצ'י", "pleasing"),
        ("אִשֶּׁה", "קרבאן", "an offering"),
        (None, "הו", "it is"),
        ("לַיהוָה", "ללה", "to God"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
    ],
    22: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he presented"),
        ("אֶת-הָאַיִל הַשֵּׁנִי", "אלכבש אלת'אני", "the second ram"),
        ("אֵיל הַמִּלֻּאִים", "כבש אלכמאל", "the ram of completion"),
        ("וַיִּסְמְכוּ", "ואסנד", "laid"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("אֶת-יְדֵיהֶם", "אידיהם", "their hands"),
        ("עַל-רֹאשׁ הָאָיִל", "עלי' ראסה", "upon its head"),
    ],
    23: [
        ("וַיִּשְׁחָט", "פד'בחה", "slaughtered it"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("וַיִּקַּח", "ואכ'ד'", "and took"),
        ("מִדָּמוֹ", "מן דמה", "some of its blood"),
        ("וַיִּתֵּן", "וגעל", "and placed it"),
        ("עַל-תְּנוּךְ אֹזֶן-אַהֲרֹן הַיְמָנִית", "עלי' שחמה' אד'ן הרון אלימני", "upon the cartilage of the lobe of Aaron's right ear"),
        ("וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית", "ועלי אבהאם ידה אלימני", "and upon the thumb of his right hand"),
        ("וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית", "ואבהאם רגלה אלימני", "and upon the thumb of his right foot"),
    ],
    24: [
        (None, "ת'ם", "Then"),
        ("וַיַּקְרֵב", "קדם", "he presented"),
        ("אֶת-בְּנֵי אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("וַיִּתֵּן", "וגעל", "and placed"),
        ("מִן-הַדָּם", "מן אלדם", "some of the blood"),
        ("עַל-תְּנוּךְ אָזְנָם הַיְמָנִית", "עלי' שחמאת אד'אנהם אלאיאמן", "upon the lobes of their right ears"),
        ("וְעַל-בֹּהֶן יָדָם הַיְמָנִית", "ועלי אבהאם אידיהם אלאיאמן", "and upon the thumbs of their right hands"),
        ("וְעַל-בֹּהֶן רַגְלָם הַיְמָנִית", "ואבהאם ארגלהם אלאיאמן", "and upon the thumbs of their right feet"),
        ("וַיִּזְרֹק", "ורש", "sprinkled"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶת-הַדָּם", "אלדם", "the blood"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    25: [
        ("וַיִּקַּח", "ואכ'ד'", "And he took"),
        ("אֶת-הַחֵלֶב", "אלת'רב", "the caul"),
        ("וְאֶת-הָאַלְיָה", "ואלאליה", "and the fat-tail"),
        ("וְאֶת-כָּל-הַחֵלֶב", "וגמיע אלשחם", "and all the fat"),
        ("אֲשֶׁר עַל-הַקֶּרֶב", "אלד'י עלי' אלגוף", "that was upon the belly"),
        ("וְאֵת יֹתֶרֶת הַכָּבֵד", "וזיאדה' אלכבד", "and the lobe of the liver"),
        ("וְאֶת-שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-חֶלְבְּהֶן", "ושחמהמא", "with their fat"),
        ("וְאֵת שׁוֹק הַיָּמִין", "ואלסאק אלאימן", "and the right leg"),
    ],
    26: [
        ("וּמִסַּל הַמַּצּוֹת", "ומן סל אלפטיר", "And from the basket of unleavened bread"),
        ("אֲשֶׁר לִפְנֵי יְהוָה", "אלד'י בין ידי אללה", "which was before God"),
        ("לָקַח", "אכ'ד'", "he took"),
        ("חַלַּת מַצָּה אַחַת", "גרדקה ואחדה", "one loaf"),
        ("וַיָּשֶׂם", "וצייר", "and set"),
        (None, "ד'אלך", "that"),
        ("עַל-הַחֲלָבִים", "עלי' אלשחום", "upon the fats"),
        ("וְעַל שׁוֹק הַיָּמִין", "ואלסאק אלאימן", "and the right leg"),
    ],
    27: [
        ("וַיִּתֵּן", "וגעל", "And he placed"),
        ("אֶת-הַכֹּל", "אלכל", "it all"),
        ("עַל כַּפֵּי אַהֲרֹן", "עלי' ידי הרון", "upon the hands of Aaron"),
        ("וְעַל כַּפֵּי בָנָיו", "ועלי' ידי בניה", "and upon the hands of his sons"),
        ("וַיָּנֶף אֹתָם", "וחרכהא", "and waved them"),
        ("תְּנוּפָה", "תחריכא", "in a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    28: [
        (None, "ת'ם", "Then"),
        ("וַיִּקַּח", "אכ'ד'הא", "took them"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("מֵעַל כַּפֵּיהֶם", "מן פוק ידיהם", "from upon their hands"),
        ("וַיַּקְטֵר הַמִּזְבֵּחָה", "וקתרהא עלי' אלמד'בח", "and burned them as smoke upon the altar"),
        ("עַל-הָעֹלָה", "מע אלצעידה", "with the burnt-offering"),
        (None, "לאנהא", "for it is"),
        ("מִלֻּאִים", "קרבאן כמאל", "an offering of completion"),
        (None, "ללה", "to God"),
        (None, "מקבול", "accepted"),
        (None, "מרצ'י", "and pleasing"),
    ],
    29: [
        (None, "ת'ם", "Then"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("וַיִּקַּח", "אכ'ד", "took"),
        ("אֶת-הֶחָזֶה", "אלקץ", "the breast"),
        ("וַיְנִיפֵהוּ", "וחרכה", "and waved it"),
        ("תְנוּפָה", "תחריכא", "in a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        (None, "וכאן", "and it was"),
        ("לְמֹשֶׁה", "למוסי", "Moses's"),
        ("הָיָה לְמָנָה", "נציבא", "portion"),
        ("מֵאֵיל הַמִּלֻּאִים", "מן כבש אלכמאל", "from the ram of completion"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמרה", "had commanded"),
        ("יְהוָה", "אללה", "God"),
    ],
    30: [
        (None, "ת'ם", "Then"),
        ("וַיִּקַּח", "אכ'ד'", "took"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("מִשֶּׁמֶן הַמִּשְׁחָה", "מן דהן אלמסוחייה", "from the anointing oil"),
        ("וּמִן-הַדָּם", "ומן אלדם", "and from the blood"),
        ("אֲשֶׁר עַל-הַמִּזְבֵּחַ", "אלד'י עלי' אלמד'בח", "that was upon the altar"),
        ("וַיַּז", "פנצ'ח", "and sprinkled it"),
        ("עַל-אַהֲרֹן", "עלי'הרון", "upon Aaron"),
        ("עַל-בְּגָדָיו", "ות'יאבה", "and his garments"),
        ("וְעַל-בָּנָיו", "ובניה", "and upon his sons"),
        ("וְעַל-בִּגְדֵי בָנָיו", "ות'יאב בניה", "and the garments of his sons"),
        ("אִתּוֹ", "מעה", "with him"),
        ("וַיְקַדֵּשׁ", "פקדסה", "and he consecrated"),
        ("אֶת-אַהֲרֹן", "ות'יאבה", "him and his garments"),
        ("וְאֶת-בָּנָיו", "ובניה", "and his sons"),
        ("וְאֶת-בִּגְדֵי בָנָיו", "ות'יאב בניה", "and the garments of his sons"),
        ("אִתּוֹ", "מעה", "with him"),
    ],
    31: [
        ("וַיֹּאמֶר", "וקאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה", "and his sons"),
        ("בַּשְּׁלוּ", "אטבכו", "Cook"),
        ("אֶת-הַבָּשָׂר", "הד'י אללחם", "this meat"),
        ("פֶּתַח אֹהֶל מוֹעֵד", "ענד באב כ'בא אלמחצ'ר", "at the entrance of the tent of the appointed meeting"),
        ("וְשָׁם", "ות'ם", "and there"),
        (None, "איצ'א", "also"),
        ("תֹּאכְלוּ אֹתוֹ", "פכלוה", "eat it"),
        ("וְאֶת-הַלֶּחֶם", "מע אלכ'בז", "together with the bread"),
        ("אֲשֶׁר בְּסַל הַמִּלֻּאִים", "אלד'י פי סל אלכמאל", "that is in the basket of completion"),
        ("כַּאֲשֶׁר צִוֵּיתִי", "כמא אמרת", "as I commanded"),
        ("לֵאמֹר", "וקלת", "and said"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("יֹאכְלֻהוּ", "יאכלונה", "shall eat it"),
    ],
    32: [
        ("וְהַנּוֹתָר", "ומא פצ'ל", "And what remains"),
        ("בַּבָּשָׂר", "מן אללחם", "of the meat"),
        ("וּבַלָּחֶם", "ואלכ'בז", "and the bread"),
        ("בָּאֵשׁ תִּשְׂרֹפוּ", "אחרקוה באלנאר", "burn it with fire"),
    ],
    33: [
        (None, "}", ""),
        ("וּמִפֶּתַח אֹהֶל מוֹעֵד", "ומן באב כ'בא אלמחצ'ר", "And from the entrance of the tent of the appointed meeting"),
        ("לֹא תֵצְאוּ", "לא תכ'ר'גו", "you shall not go out"),
        ("שִׁבְעַת יָמִים", "סבעה' איאם", "for seven days"),
        ("עַד יוֹם", "אלי'. יום", "until the day of"),
        ("מְלֹאת יְמֵי מִלֻּאֵיכֶם", "פראג'. איאם כמאלכם", "the completion of the days of your induction"),
        (None, "פאן", "for"),
        ("כִּי שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("יְמַלֵּא אֶת-יֶדְכֶם", "ת'כמל ואגבתכם", "you shall fulfill your obligations"),
    ],
    34: [
        ("כַּאֲשֶׁר", "כמא", "As"),
        ("עָשָׂה", "עמל", "was done"),
        (None, "בכם", "for you"),
        ("בַּיּוֹם הַזֶּה", "אליום", "today"),
        (None, "כד'אך", "so"),
        ("צִוָּה", "אמר", "has commanded"),
        ("יְהוָה", "אללה", "God"),
        ("לַעֲשֹׂת", "אן יעמל", "that it be done"),
        ("לְכַפֵּר עֲלֵיכֶם", "ויסתג'פר ענכם", "to seek atonement for you"),
    ],
    35: [
        ("וּפֶתַח אֹהֶל מוֹעֵד", "וענד באב כ'בא אלמחצ'ר", "And at the entrance of the tent of the appointed meeting"),
        ("תֵּשְׁבוּ", "תגלסו", "you shall sit there"),
        ("יוֹמָם", "לילא", "night"),
        ("וָלַיְלָה", "ונהארא", "and day"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("וּשְׁמַרְתֶּם", "ותחפצ'ו", "and you shall observe"),
        ("אֶת-מִשְׁמֶרֶת יְהוָה", "חפץ' אללה", "the charge of God"),
        ("וְלֹא תָמוּתוּ", "ולא תהלכו", "and you shall not perish"),
        (None, "לאן", "for"),
        (None, "כד'א", "thus"),
        ("כִּי-כֵן צֻוֵּיתִי", "אמרת", "was I commanded"),
    ],
    36: [
        ("וַיַּעַשׂ", "ועמל", "did"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("אֵת כָּל-הַדְּבָרִים", "בגמיע אלאמור", "all the matters"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("בְּיַד-מֹשֶׁה", "מוסי'", "Moses"),
    ],
}
