"""Hand-authored alignment triples for Vayikra chapter 26."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("לֹא-תַעֲשׂוּ לָכֶם אֱלִילִם וּפֶסֶל וּמַצֵּבָה לֹא-תָקִימוּ לָכֶם",
         "לא תצנעו לכם אות'אנא. ומנחותה ונצבה לא תקימו לכם",
         "Do not make for yourselves idols; and a carved thing and a standing-stone do not erect for yourselves;"),
        ("וְאֶבֶן מַשְׂכִּית לֹא תִתְּנוּ בְּאַרְצְכֶם לְהִשְׁתַּחֲו‍ֹת עָלֶיהָ",
         "וחגר מזכ'רפא. לא תצנעו פי בלאדכם. לתסגדו לה",
         "and an ornamental stone do not make in your lands to bow down to it."),
        ("כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אלואחד",
         "I am God, your Lord, the One."),
    ],
    2: [
        ("אֶת-שַׁבְּתֹתַי תִּשְׁמֹרוּ",
         "סבותי [פאחפט'והא[ פאחפצ'והא",
         "My sabbaths — keep them;"),
        ("וּמִקְדָּשִׁי תִּירָאוּ",
         "ומקדסי פהאבוה",
         "and My sanctuary — hold it in awe."),
        ("אֲנִי יְהוָה",
         "אנא אללה אגאזיכם כ'ירא",
         "I am God; I shall recompense you with good."),
    ],
    3: [
        ("אִם-בְּחֻקֹּתַי תֵּלֵכוּ וְאֶת-מִצְו‍ֹתַי תִּשְׁמְרוּ וַעֲשִׂיתֶם אֹתָם",
         "אלא אן סרתם פי רסומי. וחפצ'תם וצאיאי. ועמלתם בהא",
         "Only if you walk in My statutes, and keep My commandments, and act according to them —"),
    ],
    4: [
        ("וְנָתַתִּי גִשְׁמֵיכֶם בְּעִתָּם",
         "נזלת אג'יאתכם פי אוקאתהא",
         "I shall send down your rains in their seasons,"),
        ("וְנָתְנָה הָאָרֶץ יְבוּלָהּ",
         "ואכ'רגת אלארץ' אדאהא",
         "and the earth shall bring forth its yield,"),
        ("וְעֵץ הַשָּׂדֶה יִתֵּן פִּרְיוֹ",
         "ושגר אלצחרא יכ'רג תמרה",
         "and the trees of the wilderness shall bring forth their fruit;"),
    ],
    5: [
        ("וְהִשִּׂיג לָכֶם דַּיִשׁ אֶת-בָּצִיר וּבָצִיר יַשִּׂיג אֶת-זָרַע",
         "חתי' ידרך לכם אלדוס אלקטאף. ואלקטאף ידרך אלבדאר",
         "until the threshing shall overtake for you the harvest, and the harvest shall overtake the sowing;"),
        ("וַאֲכַלְתֶּם לַחְמְכֶם לָשֹׂבַע וִישַׁבְתֶּם לָבֶטַח בְּאַרְצְכֶם",
         "ותאכלון טעאמכם הנייא. ותקימון ואת'קין פי בלדכם",
         "and you shall eat your food with pleasure, and you shall dwell secure in your land."),
    ],
    6: [
        ("וְנָתַתִּי שָׁלוֹם בָּאָרֶץ וּשְׁכַבְתֶּם וְאֵין מַחֲרִיד",
         "ואגעל לכם אלסלאמה פי אלבלד. פתנצ'געון וליס מזעג",
         "And I shall establish peace for you in the land, so that you shall lie down with nothing to disturb you;"),
        ("וְהִשְׁבַּתִּי חַיָּה רָעָה מִן-הָאָרֶץ",
         "ואעטל שר אלחיואן אלמפסד מן אלארץ'",
         "and I shall cause the harm of the destructive beast to cease from the land;"),
        ("וְחֶרֶב לֹא-תַעֲבֹר בְּאַרְצְכֶם",
         "וסיף לא ימר פי בלדכם",
         "and no sword shall pass through your land."),
    ],
    7: [
        ("וּרְדַפְתֶּם אֶת-אֹיְבֵיכֶם",
         "ואד'א כלבתם אעדאיכם",
         "And when you hunt down your enemies,"),
        ("וְנָפְלוּ לִפְנֵיכֶם לֶחָרֶב",
         "וקעו בין אידיכם תחת סיופכם",
         "they shall fall before you under your swords."),
    ],
    8: [
        ("וְרָדְפוּ מִכֶּם חֲמִשָּׁה מֵאָה וּמֵאָה מִכֶּם רְבָבָה יִרְדֹּפוּ",
         "חתי' יכלב מנכם אלכ'מסה מאיה. ואלמאיה תכלב רבווה",
         "Until five of you shall hunt down hundreds, and a hundred of you shall hunt down a multitude;"),
        ("וְנָפְלוּ אֹיְבֵיכֶם לִפְנֵיכֶם לֶחָרֶב",
         "ויקע אעדאיכם. בין אידיכם תחת סיופכם",
         "and your enemies shall fall before you under your swords."),
    ],
    9: [
        ("וּפָנִיתִי אֲלֵיכֶם--וְהִפְרֵיתִי אֶתְכֶם וְהִרְבֵּיתִי אֶתְכֶם",
         "ואקבל אליכם. ואת'מרכם ואכת'רכם",
         "And I shall turn toward you, and make you fruitful and multiply you,"),
        ("וַהֲקִימֹתִי אֶת-בְּרִיתִי אִתְּכֶם",
         "ואפי בעהדי לכם",
         "and I shall fulfil My covenant with you."),
    ],
    10: [
        ("וַאֲכַלְתֶּם יָשָׁן נוֹשָׁן",
         "ותאכלון אלעתיק אלמעתק",
         "And you shall eat the aged, long-stored;"),
        ("וְיָשָׁן מִפְּנֵי חָדָשׁ תּוֹצִיאוּ",
         "ותכ'רגון אלעתיק מן חצ'רה' אלחדית'",
         "and you shall bring out the aged to make room for the new."),
    ],
    11: [
        ("וְנָתַתִּי מִשְׁכָּנִי בְּתוֹכְכֶם",
         "ואגעל מסכני פי מא בינכם",
         "And I shall set My dwelling-place among you,"),
        ("וְלֹא-תִגְעַל נַפְשִׁי אֶתְכֶם",
         "ולא אקלאכם",
         "and I shall not loathe you."),
    ],
    12: [
        ("וְהִתְהַלַּכְתִּי בְּתוֹכְכֶם",
         "ואסייר נורי פי מא בינכם",
         "And I shall cause My light to move among you,"),
        ("וְהָיִיתִי לָכֶם לֵאלֹהִים",
         "ואכון לכם אלאהא",
         "and I shall be the God for you,"),
        ("וְאַתֶּם תִּהְיוּ-לִי לְעָם",
         "ואנתם תכונו לי שעבא כ'אצה",
         "and you shall be for Me a special people."),
    ],
    13: [
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם אֲשֶׁר הוֹצֵאתִי אֶתְכֶם מֵאֶרֶץ מִצְרַיִם מִהְיֹת לָהֶם עֲבָדִים",
         "אנא אללה רבכם. אלד'י אכ'רגתכם מן בלד מצר. מן אן תכונו להם עבידא",
         "I am God your Lord, who brought you out from the land of Egypt, from being slaves to them;"),
        ("וָאֶשְׁבֹּר מֹטֹת עֻלְּכֶם וָאוֹלֵךְ אֶתְכֶם קוֹמְמִיּוּת",
         "וכסרת קראביס אצרכם. וסיירתכם אחרארא",
         "and I broke the yoke-bars of your bonds, and led you forth as free people."),
    ],
    14: [
        ("וְאִם-לֹא תִשְׁמְעוּ לִי וְלֹא תַעֲשׂוּ אֵת כָּל-הַמִּצְו‍ֹת הָאֵלֶּה",
         "ואן לם תסמעו לי ותטיעו. ולם תעמלו. בגמיע הד'ה אלוצאיא",
         "But if you do not hearken to Me and obey, and do not act according to all these commandments —"),
    ],
    15: [
        ("וְאִם-בְּחֻקֹּתַי תִּמְאָסוּ וְאִם אֶת-מִשְׁפָּטַי תִּגְעַל נַפְשְׁכֶם",
         "בל זהדתם פי רסומי. ואקלאת אנפסכם אחכאמי",
         "but rather you have turned away from My statutes, and your souls have come to loathe My ordinances"),
        ("לְבִלְתִּי עֲשׂוֹת אֶת-כָּל-מִצְו‍ֹתַי לְהַפְרְכֶם אֶת-בְּרִיתִי",
         "ללא תעמלו וצאיאי. ותפסכו עהדי",
         "so as not to act according to My commandments, and you break My covenant —"),
    ],
    16: [
        ("אַף-אֲנִי אֶעֱשֶׂה-זֹּאת לָכֶם וְהִפְקַדְתִּי עֲלֵיכֶם בֶּהָלָה אֶת-הַשַּׁחֶפֶת וְאֶת-הַקַּדַּחַת מְכַלּוֹת עֵינַיִם וּמְדִיבֹת נָפֶשׁ",
         "אנא איצ'א אצנע בכם הד'ה אלעקובאת. פאוכל בכם עלי' סרעה מן חמא אלסל ואלחארה. מא תשכץ עיונכם ותד'בל נפוסכם",
         "I too shall do to you these punishments: I shall set over you in haste the fever of consumption and the burning heat, which make your eyes stare and drain away your souls;"),
        ("וּזְרַעְתֶּם לָרִיק זַרְעֲכֶם וַאֲכָלֻהוּ אֹיְבֵיכֶם",
         "ותזרעון זרעכם לאלפראג'. ויאכלונה אעדאיכם",
         "and you shall sow your seed for nothing, and your enemies shall eat it."),
    ],
    17: [
        ("וְנָתַתִּי פָנַי בָּכֶם וְנִגַּפְתֶּם לִפְנֵי אֹיְבֵיכֶם",
         "ואחל ג'צ'בי בכם. פתנצדמון בין ידי אעדאיכם",
         "And I shall bring My wrath upon you, so that you shall be struck down before your enemies;"),
        ("וְרָדוּ בָכֶם שֹׂנְאֵיכֶם",
         "ויסתולי עליכם שאניכם",
         "and those who hate you shall rule over you,"),
        ("וְנַסְתֶּם וְאֵין-רֹדֵף אֶתְכֶם",
         "פתפרון ולא כאלב לכם",
         "and you shall flee with none pursuing you."),
    ],
    18: [
        ("וְאִם-עַד-אֵלֶּה--לֹא תִשְׁמְעוּ לִי",
         "ואן לם תקבלו מני מע הד'ה",
         "And if you still do not accept from Me with all this,"),
        ("וְיָסַפְתִּי לְיַסְּרָה אֶתְכֶם שֶׁבַע עַל-חַטֹּאתֵיכֶם",
         "זדתכם פי אלתאדיב. סבע עלי' כטאיאכם",
         "I shall increase your chastisement sevenfold upon your sins."),
    ],
    19: [
        ("וְשָׁבַרְתִּי אֶת-גְּאוֹן עֻזְּכֶם",
         "ואכסר אקתדאר עזכם",
         "And I shall break the might of your pride,"),
        ("וְנָתַתִּי אֶת-שְׁמֵיכֶם כַּבַּרְזֶל וְאֶת-אַרְצְכֶם כַּנְּחֻשָׁה",
         "ואגעל סמאכם כאלחדיד. וארצכם כאלנחאס",
         "and make your sky like iron and your earth like copper."),
    ],
    20: [
        ("וְתַם לָרִיק כֹּחֲכֶם",
         "פיפנא קואכם פראג'א",
         "And your strength shall perish for nothing;"),
        ("וְלֹא-תִתֵּן אַרְצְכֶם אֶת-יְבוּלָהּ וְעֵץ הָאָרֶץ לֹא יִתֵּן פִּרְיוֹ",
         "ולא תכ'רג ארצ'כם אדאהא. ושגר אלצחרא לא יכ'רג ת'מרה",
         "and your land shall not bring forth its yield, and the trees of the wilderness shall not bring forth their fruit."),
    ],
    21: [
        ("וְאִם-תֵּלְכוּ עִמִּי קֶרִי וְלֹא תֹאבוּ לִשְׁמֹעַ לִי",
         "ואן סלכתם מעי לגאגא. ולם תשו אן תסמעו לי",
         "And if you have walked with Me in contention, and have not been willing to hearken to Me,"),
        ("וְיָסַפְתִּי עֲלֵיכֶם מַכָּה שֶׁבַע כְּחַטֹּאתֵיכֶם",
         "זדתכם צ'רבה. הי סבע עלי' כטאיאכם",
         "I shall add upon you a blow — sevenfold upon your sins."),
    ],
    22: [
        ("וְהִשְׁלַחְתִּי בָכֶם אֶת-חַיַּת הַשָּׂדֶה וְשִׁכְּלָה אֶתְכֶם",
         "ואטלק פיכם. חיואן אלצחרא פית'כל מנכם",
         "And I shall release against you the beasts of the wilderness, and they shall bereave you of your children,"),
        ("וְהִכְרִיתָה אֶת-בְּהֶמְתְּכֶם וְהִמְעִיטָה אֶתְכֶם",
         "ויקטע מן בהאימכם. ויקלל עדדכם",
         "and cut down your cattle, and reduce your number;"),
        ("וְנָשַׁמּוּ דַּרְכֵיכֶם",
         "ותתוחש טרקאתכם",
         "and your roads shall become desolate."),
    ],
    23: [
        ("וְאִם-בְּאֵלֶּה--לֹא תִוָּסְרוּ לִי וַהֲלַכְתֶּם עִמִּי קֶרִי",
         "ואן לם תתאדבו לי בהד'ה אלעקובאת וסלכתם מעי לגאגא",
         "And if you are not disciplined toward Me by these punishments, and you walk with Me in contention —"),
    ],
    24: [
        ("וְהָלַכְתִּי אַף-אֲנִי עִמָּכֶם בְּקֶרִי",
         "סרת אנא איצ'א מעכם עלי' אללגאג",
         "I too shall walk with you in contention,"),
        ("וְהִכֵּיתִי אֶתְכֶם גַּם-אָנִי שֶׁבַע עַל-חַטֹּאתֵיכֶם",
         "וצ'רבתכם בסבע עלי' כטאיאכם",
         "and I shall smite you sevenfold upon your sins."),
    ],
    25: [
        ("וְהֵבֵאתִי עֲלֵיכֶם חֶרֶב נֹקֶמֶת נְקַם-בְּרִית",
         "ואג'זיכם סיפא. מנתקמא נקמה' אלעהד",
         "And I shall recompense you with a sword that avenges the vengeance of the covenant;"),
        ("וְנֶאֱסַפְתֶּם אֶל-עָרֵיכֶם וְשִׁלַּחְתִּי דֶבֶר בְּתוֹכְכֶם",
         "פתגתמעון אלי' קראכם. ואבעת' באלובא פי מא בינכם",
         "and you shall gather into your towns, and I shall send pestilence among you,"),
        ("וְנִתַּתֶּם בְּיַד-אוֹיֵב",
         "ותסלמון פי יד אלעדו",
         "and you shall be delivered into the hand of the enemy."),
    ],
    26: [
        ("בְּשִׁבְרִי לָכֶם מַטֵּה-לֶחֶם וְאָפוּ עֶשֶׂר נָשִׁים לַחְמְכֶם בְּתַנּוּר אֶחָד",
         "ואכסר לכם מעין אלטעאם. פיכבז כתיר מן אלנסא טעאמכם פי תנור ואחד",
         "And I shall break for you the spring of food, so that many women shall bake your bread in one oven,"),
        ("וְהֵשִׁיבוּ לַחְמְכֶם בַּמִּשְׁקָל וַאֲכַלְתֶּם וְלֹא תִשְׂבָּעוּ",
         "וירדונה באלמיזאן ותאכלון ולא תשבעון",
         "and they shall return it by weight; and you shall eat and not be satisfied."),
    ],
    27: [
        ("וְאִם-בְּזֹאת--לֹא תִשְׁמְעוּ לִי",
         "ואן לם תסמעו לי ותטיעו. בהד'ה אלעקובאת",
         "And if you do not hearken to Me and obey, with all these punishments,"),
        ("וַהֲלַכְתֶּם עִמִּי בְּקֶרִי",
         "וסלכתם מעי לגאגא",
         "and you walk with Me in contention —"),
    ],
    28: [
        ("וְהָלַכְתִּי עִמָּכֶם בַּחֲמַת-קֶרִי",
         "סרת אנא איצ'א מעכם בעקובאת אללגאג",
         "I too shall walk with you with the punishments of contention,"),
        ("וְיִסַּרְתִּי אֶתְכֶם אַף-אָנִי שֶׁבַע עַל-חַטֹּאתֵיכֶם",
         "ואדבתכם בסבע עלי' כטאיאכם",
         "and I shall discipline you sevenfold upon your sins."),
    ],
    29: [
        ("וַאֲכַלְתֶּם בְּשַׂר בְּנֵיכֶם וּבְשַׂר בְּנֹתֵיכֶם תֹּאכֵלוּ",
         "חתי' תאכלון לחום בניכם ובנאתכם",
         "Until you eat the flesh of your sons and the flesh of your daughters."),
    ],
    31: [
        ("וְנָתַתִּי אֶת-עָרֵיכֶם חָרְבָּה וַהֲשִׁמּוֹתִי אֶת-מִקְדְּשֵׁיכֶם",
         "ואגעל קראכם כ'ראבא. ואוחש מקאדסכם",
         "And I shall make your towns a ruin, and cause desolation in your sanctuaries,"),
        ("וְלֹא אָרִיחַ בְּרֵיחַ נִיחֹחֲכֶם",
         "ולא אקבל ולא ארצ'א קראבינכם",
         "and I shall neither accept nor be pleased with your offerings."),
    ],
    32: [
        ("וַהֲשִׁמֹּתִי אֲנִי אֶת-הָאָרֶץ",
         "ואוחש אנא אלבלד מנכם",
         "And I shall desolate the land of you,"),
        ("וְשָׁמְמוּ עָלֶיהָ אֹיְבֵיכֶם הַיֹּשְׁבִים בָּהּ",
         "ויסתוחש מנהא אעדאיכם. אלמקימין בהא",
         "and your enemies who dwell in it shall be desolated of it."),
    ],
    33: [
        ("וְאֶתְכֶם אֱזָרֶה בַגּוֹיִם וַהֲרִיקֹתִי אַחֲרֵיכֶם חָרֶב",
         "ואד'ריכם פי מא בין אלאמם. ואגרד אלסיף וראכם",
         "And I shall scatter you among the nations, and I shall draw the sword after you;"),
        ("וְהָיְתָה אַרְצְכֶם שְׁמָמָה וְעָרֵיכֶם יִהְיוּ חָרְבָּה",
         "פתציר ארצכם וחשה. וקראכם. כ'ראבא",
         "and your land shall become a waste, and your towns a ruin."),
    ],
    34: [
        ("אָז תִּרְצֶה הָאָרֶץ אֶת-שַׁבְּתֹתֶיהָ כֹּל יְמֵי הָשַּׁמָּה",
         "חיניד' תסתופי אלארץ' עטלהא. טול אייאם וחשתהא",
         "At that time the land shall receive its rest — all the days of its desolation —"),
        ("וְאַתֶּם בְּאֶרֶץ אֹיְבֵיכֶם אָז תִּשְׁבַּת הָאָרֶץ וְהִרְצָת אֶת-שַׁבְּתֹתֶיהָ",
         "ואנתם פי בלד אעדאיכם. חיניד' תתסייב אלארץ'. ותסתופי עטלהא",
         "while you are in the land of your enemies; at that time the land shall be left fallow, and receive its rest."),
    ],
    35: [
        ("כָּל-יְמֵי הָשַּׁמָּה תִּשְׁבֹּת אֵת אֲשֶׁר לֹא-שָׁבְתָה בְּשַׁבְּתֹתֵיכֶם בְּשִׁבְתְּכֶם עָלֶיהָ",
         "וסבב טול אייאם וחשתהא אן תתעטל. כמא לם תעטלונהא פי עטלכם פי מקאמכם בהא",
         "And the reason for the length of the days of its desolation is that it shall rest, even as you did not let it rest in its rest-times while you were dwelling upon it."),
    ],
    36: [
        ("וְהַנִּשְׁאָרִים בָּכֶם--וְהֵבֵאתִי מֹרֶךְ בִּלְבָבָם בְּאַרְצֹת אֹיְבֵיהֶם",
         "ואלבאקיון מנכם אדכל אלגבן פי קלובהם. פי בלדאן אעדאיהם",
         "And those of you who remain — I shall bring cowardice into their hearts in the lands of their enemies,"),
        ("וְרָדַף אֹתָם קוֹל עָלֶה נִדָּף וְנָסוּ מְנֻסַת-חֶרֶב",
         "חתי' אנה לו לחקהם צות ורקה מנדפעה. והרבו כאלהארב מן אלסיף",
         "so that even if the sound of a driven leaf overtook them, they would flee as one fleeing from the sword,"),
        ("וְנָפְלוּ וְאֵין רֹדֵף",
         "ווקעו מן ג'יר כאלב",
         "and they would fall with none pursuing them."),
    ],
    37: [
        ("וְכָשְׁלוּ אִישׁ-בְּאָחִיו כְּמִפְּנֵי-חֶרֶב וְרֹדֵף אָיִן",
         "ויעת'ר בעצהם בבעץ'. כמא יכון מן קבל אלסיף מן ג'יר כאלב",
         "And they shall stumble over one another, as happens before the sword, with none pursuing;"),
        ("וְלֹא-תִהְיֶה לָכֶם תְּקוּמָה לִפְנֵי אֹיְבֵיכֶם",
         "ולא יכון לכם קואם. בין ידי אעדאיכם",
         "and you shall have no power to stand before your enemies."),
    ],
    38: [
        ("וַאֲבַדְתֶּם בַּגּוֹיִם",
         "ויביד מנכם פי מא בין אלאמם",
         "And some of you shall perish among the nations,"),
        ("וְאָכְלָה אֶתְכֶם אֶרֶץ אֹיְבֵיכֶם",
         "ויפניכם בלד אעדאיכם",
         "and the land of your enemies shall consume you."),
    ],
    39: [
        ("וְהַנִּשְׁאָרִים בָּכֶם יִמַּקּוּ בַּעֲו‍ֹנָם בְּאַרְצֹת אֹיְבֵיכֶם",
         "ואלבאקיון מנכם. יכ'סעון בד'נובהם. פי בלדאן אעדאיכם",
         "And those of you who remain shall be humbled by their sins in the lands of your enemies;"),
        ("וְאַף בַּעֲו‍ֹנֹת אֲבֹתָם אִתָּם יִמָּקּוּ",
         "ואיצ'א בד'נוב אבאיהם אלד'ין מעהם יכ'סעון",
         "and also by the sins of their fathers who are with them they shall be humbled."),
    ],
    40: [
        ("וְהִתְוַדּוּ אֶת-עֲו‍ֹנָם וְאֶת-עֲו‍ֹן אֲבֹתָם בְּמַעֲלָם אֲשֶׁר מָעֲלוּ-בִי",
         "פאן אקרו בד'נובהם וד'נוב אבאיהם. בנכת'הם אלד'י נכתו בי",
         "But if they confess their sins and the sins of their fathers — in their treachery with which they were treacherous against Me,"),
        ("וְאַף אֲשֶׁר-הָלְכוּ עִמִּי בְּקֶרִי",
         "ומא סלכו מעי לגאגא ולם יתובון",
         "and in that they walked with Me in contention and did not repent —"),
    ],
    41: [
        ("אַף-אֲנִי אֵלֵךְ עִמָּם בְּקֶרִי וְהֵבֵאתִי אֹתָם בְּאֶרֶץ אֹיְבֵיהֶם",
         "אנא איצ'א אסיר מעהם עלי' אללגאג. ואדכ'להם אלי' בלדאן אעדאיהם אכ'רין",
         "I too shall walk with them in contention, and I shall bring them into the lands of their enemies again;"),
        ("אוֹ-אָז יִכָּנַע לְבָבָם הֶעָרֵל וְאָז יִרְצוּ אֶת-עֲו‍ֹנָם",
         "או אלי' אן ינהזם קלבהם אלג'אש. או אלי' אן יסתופון ד'נובהם",
         "or until their obdurate heart is subdued, or until they have paid the full price of their sins."),
    ],
    42: [
        ("וְזָכַרְתִּי אֶת-בְּרִיתִי יַעֲקוֹב וְאַף אֶת-בְּרִיתִי יִצְחָק וְאַף אֶת-בְּרִיתִי אַבְרָהָם אֶזְכֹּר",
         "ואד'כר להם עהדי אלד'י מע יעקוב. ואיצ'א עהדי אלד'י מע יצחק. ואיצ'א עהדי אלד'י מע אברהים. אדכרה להם",
         "Then I shall remember for them My covenant with Jacob, and also My covenant with Isaac, and also My covenant with Abraham — I shall remember it for them"),
        ("וְהָאָרֶץ אֶזְכֹּר",
         "ולנסלהם",
         "and for their offspring."),
    ],
    43: [
        ("וְהָאָרֶץ תֵּעָזֵב מֵהֶם וְתִרֶץ אֶת-שַׁבְּתֹתֶיהָ בָּהְשַׁמָּה מֵהֶם",
         "ואלארץ' אלד'י תרכת מנהם ואסתופת עטלהא. באסתוחאשהא מנהם",
         "And the land that was left of them, and received its rest through being desolated of them —"),
        ("וְהֵם יִרְצוּ אֶת-עֲו‍ֹנָם יַעַן וּבְיַעַן--בְּמִשְׁפָּטַי מָאָסוּ וְאֶת-חֻקֹּתַי גָּעֲלָה נַפְשָׁם",
         "והם אסתופו ד'נובהם. גזאהם ומן גזאהם. אד' זהדו פי אחכאמי. ורסומי אקלאתהא אנפסהם",
         "and they, for their part, paid the full price of their sins, as their recompense and part of their recompense — since they had turned away from My ordinances, and their souls had loathed My statutes."),
    ],
    44: [
        ("וְאַף-גַּם-זֹאת בִּהְיוֹתָם בְּאֶרֶץ אֹיְבֵיהֶם לֹא-מְאַסְתִּים וְלֹא-גְעַלְתִּים לְכַלֹּתָם",
         "ואיצ'א מע הד'ה אלאמור. מע כונהם פי בלדאן אעדאיהם. לא אזהד פיהם ולא אקלאהם לאפנאהם",
         "And also, along with all these things — even while they are in the lands of their enemies — I shall not turn away from them, nor shall I loathe them to destroy them,"),
        ("לְהָפֵר בְּרִיתִי אִתָּם כִּי אֲנִי יְהוָה אֱלֹהֵיהֶם",
         "ולא אפסך' עהדי מעהם. לאני אללה רבהם",
         "nor shall I annul My covenant with them; for I am God their Lord."),
    ],
    45: [
        ("וְזָכַרְתִּי לָהֶם בְּרִית רִאשֹׁנִים אֲשֶׁר הוֹצֵאתִי-אֹתָם מֵאֶרֶץ מִצְרַיִם לְעֵינֵי הַגּוֹיִם",
         "ואדכר להם עהד אלאוולין. אלד'ין אכ'רגתהם מן בלד מצר בחצ'רה אלאמם",
         "And I shall remember for them the covenant of the first ones, whom I brought out from the land of Egypt in the presence of the nations,"),
        ("לִהְיוֹת לָהֶם לֵאלֹהִים--אֲנִי יְהוָה",
         "לאכון להם אלאהא. אנא אללה צאדק אלועד",
         "to be their God. I am God, true to My promise."),
    ],
    46: [
        ("אֵלֶּה הַחֻקִּים וְהַמִּשְׁפָּטִים וְהַתּוֹרֹת אֲשֶׁר נָתַן יְהוָה בֵּינוֹ וּבֵין בְּנֵי יִשְׂרָאֵל",
         "הד'ה אלרסום ואלאחכאם ואלדלאיל. אלתי געלהא אללה. בינה ובין בני אסראיל",
         "These are the statutes and the ordinances and the guiding principles which God established between Him and the sons of Israel,"),
        ("בְּהַר סִינַי בְּיַד-מֹשֶׁה",
         "עלי' טור סיני עלי' יד מוסי",
         "upon Mount Sinai, by the hand of Moses."),
    ],
}
