"""Hand-authored alignment triples for Vayikra chapter 13."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה. מוסי' והרון תכלימא",
         "Then God spoke to Moses and Aaron directly."),
    ],
    2: [
        ("אָדָם כִּי-יִהְיֶה בְעוֹר-בְּשָׂרוֹ שְׂאֵת אוֹ-סַפַּחַת אוֹ בַהֶרֶת",
         "אי אנסאן כאן פי גלד בדנה שאמה או עארצ'ה או בקעה",
         "Any person in whose skin of his body there was a mark, or a blemish, or a spot —"),
        ("וְהָיָה בְעוֹר-בְּשָׂרוֹ לְנֶגַע צָרָעַת",
         "או צאר פי גלד בדנה בלא ברץ",
         "or there appeared in the skin of his body an affliction of leprosy —"),
        ("וְהוּבָא אֶל-אַהֲרֹן הַכֹּהֵן אוֹ אֶל-אַחַד מִבָּנָיו הַכֹּהֲנִים",
         "פליותא בה אלי' הרון אלאמאם. או אלי' אחד מן בניה אלאימה",
         "he shall be brought to Aaron the imām, or to one of his sons the imāms."),
    ],
    3: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּגַע בְּעוֹר-הַבָּשָׂר וְשֵׂעָר בַּנֶּגַע הָפַךְ לָבָן",
         "פינצ'ר אלאמאם אלבלא פי גלד אלבדן. פאן כאן פיה שער קד אנקלב אביצ'א",
         "And the imām shall inspect the affliction in the skin of the body; if there is in it hair that has turned white,"),
        ("וּמַרְאֵה הַנֶּגַע עָמֹק מֵעוֹר בְּשָׂרוֹ--נֶגַע צָרַעַת הוּא",
         "ומנצ'ר אלבלא עמיק מן גלד בדנה. פהו בלא ברץ",
         "and the appearance of the affliction is deep from the skin of his body, it is an affliction of leprosy —"),
        ("וְרָאָהוּ הַכֹּהֵן וְטִמֵּא אֹתוֹ",
         "פאד'י ראה כד'אך פלינגסה",
         "and when it is seen thus, he shall declare him impure."),
    ],
    4: [
        ("וְאִם-בַּהֶרֶת לְבָנָה הִוא בְּעוֹר בְּשָׂרוֹ וְעָמֹק אֵין-מַרְאֶהָ מִן-הָעוֹר וּשְׂעָרָה לֹא-הָפַךְ לָבָן",
         "ואן כאנת בקעה ביצ'א פי גלד בדנה. וליס ומנצ'רהא עמיק מן אלגלד. ושערהא לם ינקלב אביצ'א",
         "But if the spot in the skin of his body is white, and its appearance is not deep from the skin, and its hair has not turned white,"),
        ("וְהִסְגִּיר הַכֹּהֵן אֶת-הַנֶּגַע שִׁבְעַת יָמִים",
         "פליוקפה סבעה' איאם",
         "he shall confine him for seven days."),
    ],
    5: [
        ("וְרָאָהוּ הַכֹּהֵן בַּיּוֹם הַשְּׁבִיעִי וְהִנֵּה הַנֶּגַע עָמַד בְּעֵינָיו לֹא-פָשָׂה הַנֶּגַע בָּעוֹר",
         "ת'ם ינצ'רה פי אליום אלסאבע. פאן וקף אלבלא בעינה. ולם יתפש פי אלגלד",
         "Then he shall inspect him on the seventh day; if the affliction has stood as it was and has not spread in the skin,"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן שִׁבְעַת יָמִים שֵׁנִית",
         "פליוקפה סבעה' איאם ת'אניה",
         "he shall confine him for a second seven days."),
    ],
    6: [
        ("וְרָאָה הַכֹּהֵן אֹתוֹ בַּיּוֹם הַשְּׁבִיעִי שֵׁנִית וְהִנֵּה כֵּהָה הַנֶּגַע וְלֹא-פָשָׂה הַנֶּגַע בָּעוֹר",
         "ת'ם ינצ'רה פי אליום אלסאבע ת'אניה. פאן כבא ולם יתפש פי אלגלד",
         "Then he shall inspect him on the seventh day a second time; if it has dimmed and has not spread in the skin,"),
        ("וְטִהֲרוֹ הַכֹּהֵן מִסְפַּחַת הִוא",
         "פליטהרה פאנהא עארצ'ה",
         "he shall declare him pure — for it is a blemish —"),
        ("וְכִבֶּס בְּגָדָיו וְטָהֵר",
         "ויג'סל ת'יאבה ויטהר",
         "and he shall wash his garments and be pure."),
    ],
    7: [
        ("וְאִם-פָּשֹׂה תִפְשֶׂה הַמִּסְפַּחַת בָּעוֹר אַחֲרֵי הֵרָאֹתוֹ אֶל-הַכֹּהֵן לְטָהֳרָתוֹ",
         "ואן תפשת אלעארצ'ה פי אלגלד. בעד מא אורי' לאלאמאם פטהרה",
         "But if the blemish spreads in the skin after he was shown to the imām and he declared him pure,"),
        ("וְנִרְאָה שֵׁנִית אֶל-הַכֹּהֵן",
         "פליורא לה ת'אניה",
         "he shall be shown to him a second time."),
    ],
    8: [
        ("וְרָאָה הַכֹּהֵן וְהִנֵּה פָּשְׂתָה הַמִּסְפַּחַת בָּעוֹר",
         "פאד'א ראהא אלאמאם. קד תפשת פי גלדה",
         "And if the imām sees that it has spread in his skin,"),
        ("וְטִמְּאוֹ הַכֹּהֵן צָרַעַת הִוא",
         "פלינגסה פאנהא ברץ",
         "he shall declare him impure — for it is leprosy."),
    ],
    9: [
        ("נֶגַע צָרַעַת כִּי תִהְיֶה בְּאָדָם וְהוּבָא אֶל-הַכֹּהֵן",
         "פאד'א כאן באנסאן בלא ברץ. פיותא בה אלי' אלאמאם",
         "If there is on a person an affliction of leprosy, he shall be brought to the imām."),
    ],
    10: [
        ("וְרָאָה הַכֹּהֵן וְהִנֵּה שְׂאֵת-לְבָנָה בָּעוֹר וְהִיא הָפְכָה שֵׂעָר לָבָן",
         "פינצר אלאמאם. פאד'א בשאמה ביצ'א פי גלדה. וקד אקלבת אלשער אביצ'א",
         "And the imām shall inspect — and behold, if there is a white mark in his skin and the hair has turned white,"),
        ("וּמִחְיַת בָּשָׂר חַי בַּשְׂאֵת",
         "או גז מן אללחם נקי פי אלשאמה",
         "or there is a portion of raw flesh in the mark,"),
    ],
    11: [
        ("צָרַעַת נוֹשֶׁנֶת הִוא בְּעוֹר בְּשָׂרוֹ",
         "ברץ עתיק הו פי גלד בדנה",
         "it is an old leprosy in the skin of his body;"),
        ("וְטִמְּאוֹ הַכֹּהֵן לֹא יַסְגִּרֶנּוּ כִּי טָמֵא הוּא",
         "פלינגסה אלאמאם. ולא יוקפה. אד' הו נגס",
         "the imām shall declare him impure and shall not confine him, since he is impure."),
    ],
    12: [
        ("וְאִם-פָּרוֹחַ תִּפְרַח הַצָּרַעַת בָּעוֹר וְכִסְּתָה הַצָּרַעַת אֵת כָּל-עוֹר הַנֶּגַע מֵרֹאשׁוֹ וְעַד-רַגְלָיו",
         "ואן אנתשר אלברץ פי אלבדן. חתי' ג'טא גמיע גלד אלמבתלא. מן ראסה אלי' רגליה",
         "And if the leprosy spreads throughout the body, until it covers all the skin of the afflicted one from his head to his feet —"),
        ("לְכָל-מַרְאֵה עֵינֵי הַכֹּהֵן",
         "גמיע מנצ'ר עיני אלאמאם",
         "entirely within the sight of the imām's eyes —"),
    ],
    13: [
        ("וְרָאָה הַכֹּהֵן וְהִנֵּה כִסְּתָה הַצָּרַעַת אֶת-כָּל-בְּשָׂרוֹ",
         "פ לינצ'ר אלאמאם. פאד'א קד ג'טא אלברץ גמיע בדנה",
         "the imām shall inspect; and if the leprosy has covered all his body,"),
        ("וְטִהַר אֶת-הַנָּגַע כֻּלּוֹ הָפַךְ לָבָן טָהוֹר הוּא",
         "פליטהרה. אד' קד אנקלב כלה אביצ'א פהו טאהר",
         "he shall declare him pure, since it has all turned white — he is pure."),
    ],
    14: [
        ("וּבְיוֹם הֵרָאוֹת בּוֹ בָּשָׂר חַי יִטְמָא",
         "ואי יום צ'הר פיה לחם נקי פלינגסה",
         "But on whatever day raw flesh appears in him, he shall declare him impure."),
    ],
    15: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַבָּשָׂר הַחַי וְטִמְּאוֹ",
         "באן ירא אלאמאם. אללחם אלנקי פינגסה",
         "For when the imām sees the raw flesh, he shall declare him impure —"),
        ("הַבָּשָׂר הַחַי טָמֵא הוּא צָרַעַת הוּא",
         "לאן גז מן אללחם אלנקי מע אלברץ נגס הו",
         "for a portion of raw flesh together with the leprosy is impure."),
    ],
    16: [
        ("אוֹ כִי יָשׁוּב הַבָּשָׂר הַחַי וְנֶהְפַּךְ לְלָבָן וּבָא אֶל-הַכֹּהֵן",
         "ואן רגע אללחם אלנקי ואנקלב אביצ'א. פליגי אלי' אלאמאם",
         "But if the raw flesh turns back and becomes white, he shall come to the imām."),
    ],
    17: [
        ("וְרָאָהוּ הַכֹּהֵן וְהִנֵּה נֶהְפַּךְ הַנֶּגַע לְלָבָן",
         "פאד'א נצ'ר אלאמאם. אן אלבלא קד אנקלב אביצ'א",
         "And if the imām inspects and the affliction has turned white,"),
        ("וְטִהַר הַכֹּהֵן אֶת-הַנֶּגַע טָהוֹר הוּא",
         "פליטהרה אנה טאהר",
         "he shall declare him pure — he is pure."),
    ],
    18: [
        ("וּבָשָׂר כִּי-יִהְיֶה בוֹ-בְעֹרוֹ שְׁחִין וְנִרְפָּא",
         "ואי אנסאן. כאן פי גלד בדנה קרח. פברא",
         "And any person in whose skin of his body there was a sore, and it healed —"),
    ],
    19: [
        ("וְהָיָה בִּמְקוֹם הַשְּׁחִין שְׂאֵת לְבָנָה אוֹ בַהֶרֶת לְבָנָה אֲדַמְדָּמֶת",
         "וצאר פי מוצ'עה שאמה ביצ'א או בקעה ביצ'א מחמרה",
         "and there appeared in its place a white mark, or a white spot tinged with red —"),
        ("וְנִרְאָה אֶל-הַכֹּהֵן",
         "פליורא לאלאמאם",
         "he shall be shown to the imām."),
    ],
    20: [
        ("וְרָאָה הַכֹּהֵן וְהִנֵּה מַרְאֶהָ שָׁפָל מִן-הָעוֹר וּשְׂעָרָהּ הָפַךְ לָבָן",
         "פאד'א ראי' אלאמאם. ומנצ'רהא מתספל מן אלגלד. ושערהא קד אנקלב אביצ'א",
         "And if the imām sees that its appearance is sunken below the skin and its hair has turned white,"),
        ("וְטִמְּאוֹ הַכֹּהֵן נֶגַע-צָרַעַת הִוא בַּשְּׁחִין פָּרָחָה",
         "פלינגסה. לאנהא בלא ברץ קד אנתשר פי אלקרח",
         "he shall declare him impure — for it is an affliction of leprosy that has spread in the sore."),
    ],
    21: [
        ("וְאִם יִרְאֶנָּה הַכֹּהֵן וְהִנֵּה אֵין-בָּהּ שֵׂעָר לָבָן וּשְׁפָלָה אֵינֶנָּה מִן-הָעוֹר וְהִיא כֵהָה",
         "ואן הו ינצ'רהא. ולם יכון פיהא שער אביץ'. וליסת מתספלה מן אלגלד. בל כאביה",
         "But if he inspects it and there is no white hair in it, and it is not sunken below the skin but is rather dim,"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן שִׁבְעַת יָמִים",
         "פליוקפה סבעה' איאם",
         "he shall confine him for seven days."),
    ],
    22: [
        ("וְאִם-פָּשֹׂה תִפְשֶׂה בָּעוֹר",
         "ואן הי תפשת פי אלגלד",
         "And if it spreads in the skin,"),
        ("וְטִמֵּא הַכֹּהֵן אֹתוֹ נֶגַע הִוא",
         "פלינגסה פאנהא בלא",
         "he shall declare him impure — for it is an affliction."),
    ],
    23: [
        ("וְאִם-תַּחְתֶּיהָ תַּעֲמֹד הַבַּהֶרֶת לֹא פָשָׂתָה",
         "פאן וקפת מכאנהא ולם תתפש",
         "But if it stays in its place and has not spread,"),
        ("צָרֶבֶת הַשְּׁחִין הִוא וְטִהֲרוֹ הַכֹּהֵן",
         "פהי מן את'ר אלקרח. פליטהרה אלאמאם",
         "it is from the trace of the sore; the imām shall declare him pure."),
    ],
    24: [
        ("אוֹ בָשָׂר כִּי-יִהְיֶה בְעֹרוֹ מִכְוַת-אֵשׁ",
         "אי אנסאן כאן פי גלדה כי נאר",
         "Any person in whose skin there was a burn from fire,"),
        ("וְהָיְתָה מִחְיַת הַמִּכְוָה בַּהֶרֶת לְבָנָה אֲדַמְדֶּמֶת--אוֹ לְבָנָה",
         "ת'ם צאר גז אלכי. בקעה ביצ'א מחמרה או ביצ'א פקט",
         "and the part of the burn became a white spot tinged with red, or white only —"),
    ],
    25: [
        ("וְרָאָה אֹתָהּ הַכֹּהֵן וְהִנֵּה נֶהְפַּךְ שֵׂעָר לָבָן בַּבַּהֶרֶת וּמַרְאֶהָ עָמֹק מִן-הָעוֹר",
         "פלינצ'רהא אלאמאם. פאן אנקלב אלשער אביצ'א וכאן ומנצ'רהא עמיק מן אלגלד",
         "the imām shall inspect it; and if the hair has turned white and its appearance is deep from the skin,"),
        ("צָרַעַת הִוא בַּמִּכְוָה פָּרָחָה וְטִמֵּא אֹתוֹ הַכֹּהֵן נֶגַע צָרַעַת הִוא",
         "פהו ברץ אנתשר פי אלכי. פלינגסה אלאמאם",
         "it is leprosy that has spread in the burn — the imām shall declare him impure."),
    ],
    26: [
        ("וְאִם יִרְאֶנָּה הַכֹּהֵן וְהִנֵּה אֵין-בַּבַּהֶרֶת שֵׂעָר לָבָן וּשְׁפָלָה אֵינֶנָּה מִן-הָעוֹר וְהִוא כֵהָה",
         "פאן ראהא אלאמאם. וליס פיה שער אביץ'. וליסת מתספלה מן אלגלד. בל כאביה",
         "But if the imām sees that there is no white hair in it, and it is not sunken below the skin but is rather dim,"),
        ("וְהִסְגִּירוֹ הַכֹּהֵן שִׁבְעַת יָמִים",
         "פליוקפה סבעה' איאם",
         "he shall confine him for seven days."),
    ],
    27: [
        ("וְרָאָהוּ הַכֹּהֵן בַּיּוֹם הַשְּׁבִיעִי אִם-פָּשֹׂה תִפְשֶׂה בָּעוֹר",
         "פינצ'רהא פי אליום אלסאבע. פאן תפשת פי אלגלד",
         "Then he shall inspect it on the seventh day; if it has spread in the skin,"),
        ("וְטִמֵּא הַכֹּהֵן אֹתוֹ נֶגַע צָרַעַת הִוא",
         "פלינגסה פאנהא בלא ברץ",
         "he shall declare him impure — for it is an affliction of leprosy."),
    ],
    28: [
        ("וְאִם-תַּחְתֶּיהָ תַעֲמֹד הַבַּהֶרֶת לֹא-פָשְׂתָה בָעוֹר וְהִוא כֵהָה",
         "ואן וקפת מכאנהא. לם תתפש פי אלגלד והי כאביה",
         "But if it stays in its place and has not spread in the skin, and it is dim —"),
        ("שְׂאֵת הַמִּכְוָה הִוא וְטִהֲרוֹ הַכֹּהֵן--כִּי-צָרֶבֶת הַמִּכְוָה הִוא",
         "פהי מן את'ר אלכי. פליטהרה אלאמאם. פאנהא תשייט אלכי",
         "it is from the trace of the burn; the imām shall declare him pure, for it is a scorching of the burn."),
    ],
    29: [
        ("וְאִישׁ אוֹ אִשָּׁה כִּי-יִהְיֶה בוֹ נָגַע בְּרֹאשׁ אוֹ בְזָקָן",
         "ואי רגל או אמראה. כאן בה בלא ברץ. פי ראסה או פי לחיתה",
         "And any man or woman in whom there is an affliction of leprosy in the head or in the beard —"),
    ],
    30: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּגַע וְהִנֵּה מַרְאֵהוּ עָמֹק מִן-הָעוֹר וּבוֹ שֵׂעָר צָהֹב דָּק",
         "פלינצ'רה אלאמאם. פאן כאן מנצ'רה עמיק מן אלגלד. ופיה שער אצהב דקיק",
         "the imām shall inspect it; and if its appearance is deep from the skin and there is in it thin yellowish hair,"),
        ("וְטִמֵּא אֹתוֹ הַכֹּהֵן נֶתֶק הוּא צָרַעַת הָרֹאשׁ אוֹ הַזָּקָן הוּא",
         "פלינגסה אלאמאם פאנה כ'לף. והו ברץ אלראס או אללחיה",
         "the imām shall declare him impure — for it is a blight, and it is leprosy of the head or the beard."),
    ],
    31: [
        ("וְכִי-יִרְאֶה הַכֹּהֵן אֶת-נֶגַע הַנֶּתֶק וְהִנֵּה אֵין-מַרְאֵהוּ עָמֹק מִן-הָעוֹר וְשֵׂעָר שָׁחֹר אֵין בּוֹ",
         "ואד'א ראה. וליס מנצ'רה עמיק מן אלגלד. וליס פיה שער אסוד",
         "But if it is seen, and its appearance is not deep from the skin and there is no black hair in it,"),
        ("וְהִסְגִּיר הַכֹּהֵן אֶת-נֶגַע הַנֶּתֶק שִׁבְעַת יָמִים",
         "פליוקפה סבעה' איאם",
         "he shall confine him for seven days."),
    ],
    32: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּגַע בַּיּוֹם הַשְּׁבִיעִי וְהִנֵּה לֹא-פָשָׂה הַנֶּתֶק וְלֹא-הָיָה בוֹ שֵׂעָר צָהֹב וּמַרְאֵה הַנֶּתֶק אֵין עָמֹק מִן-הָעוֹר",
         "ת'ם ינצרה פי אליום אלסאבע. פהו אן לם יתפש. ולם יציר פיה שער אצהב. ומנצ'רה ליס עמיק מן אלגלד",
         "Then he shall inspect it on the seventh day — if it has not spread, and there has not appeared in it yellowish hair, and its appearance is not deep from the skin —"),
    ],
    33: [
        ("וְהִתְגַּלָּח--וְאֶת-הַנֶּתֶק לֹא יְגַלֵּחַ",
         "פיחלק שערה. סוא מוצ'ע אלכ'לף",
         "he shall shave his hair, except for the place of the blight,"),
        ("וְהִסְגִּיר הַכֹּהֵן אֶת-הַנֶּתֶק שִׁבְעַת יָמִים שֵׁנִית",
         "ויוקפה סבעה' איאם ת'אניה",
         "and he shall confine him for a second seven days."),
    ],
    34: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנֶּתֶק בַּיּוֹם הַשְּׁבִיעִי וְהִנֵּה לֹא-פָשָׂה הַנֶּתֶק בָּעוֹר וּמַרְאֵהוּ אֵינֶנּוּ עָמֹק מִן-הָעוֹר",
         "ת'ם ינצ'רה פי אליום אלסאבע. פאן הו לם יתפש פי אלגלד. ומנצ'רה מע ד'אך ליס עמיק מן אלגלד",
         "Then he shall inspect it on the seventh day; if it has not spread in the skin, and its appearance is moreover not deep from the skin,"),
        ("וְטִהַר אֹתוֹ הַכֹּהֵן וְכִבֶּס בְּגָדָיו וְטָהֵר",
         "פליטהרה אלאמאם. ויג'סל ת'יאבה ליטהר",
         "the imām shall declare him pure; and he shall wash his garments, that he may be pure."),
    ],
    35: [
        ("וְאִם-פָּשֹׂה יִפְשֶׂה הַנֶּתֶק בָּעוֹר אַחֲרֵי טָהֳרָתוֹ",
         "ואן תפשא אלכ'לף פי בדנה. בעד טהרה",
         "But if the blight spreads in his body after his purification —"),
    ],
    36: [
        ("וְרָאָהוּ הַכֹּהֵן וְהִנֵּה פָּשָׂה הַנֶּתֶק בָּעוֹר--לֹא-יְבַקֵּר הַכֹּהֵן לַשֵּׂעָר הַצָּהֹב טָמֵא הוּא",
         "פינצ'רה אלאמאם. קד תפשא פי אלגלד. פלא יפחץ ען אלשער אלאצהב. בברהאן אנה נגס",
         "the imām shall inspect it, and behold it has spread in the skin: he need not examine for the yellowish hair — by proof that he is impure."),
    ],
    37: [
        ("וְאִם-בְּעֵינָיו עָמַד הַנֶּתֶק וְשֵׂעָר שָׁחֹר צָמַח-בּוֹ נִרְפָּא הַנֶּתֶק--טָהוֹר הוּא וְטִהֲרוֹ הַכֹּהֵן",
         "ואן הו וקף בעינה. ונבת פיה שער אסוד. פקד ברא והו טאהר. פליטהרה אלאמאם",
         "But if it has stood as it was, and black hair has grown in it, then it has healed and he is pure; the imām shall declare him pure."),
    ],
    38: [
        ("וְאִישׁ אוֹ-אִשָּׁה כִּי-יִהְיֶה בְעוֹר-בְּשָׂרָם בֶּהָרֹת--בֶּהָרֹת לְבָנֹת",
         "ואי רגל או אמראה. כאן פי גלד בדנה בקע בקע ביץ'",
         "And any man or woman in whose skin of his body there are spots — spots that are white —"),
    ],
    39: [
        ("וְרָאָה הַכֹּהֵן וְהִנֵּה בְעוֹר-בְּשָׂרָם בֶּהָרֹת--כֵּהוֹת לְבָנֹת",
         "פינצ'ר אלאמאם. פאד'א פי גלוד אבדאנהם. בקע כאביה פי ביאצ'הא",
         "the imām shall inspect; and if in the skin of their bodies the spots are dim in their whiteness,"),
        ("בֹּהַק הוּא פָּרַח בָּעוֹר טָהוֹר הוּא",
         "פהו בהק. אנתשר פי אלגלד והו טאהר",
         "it is vitiligo that has spread in the skin — and he is pure."),
    ],
    40: [
        ("וְאִישׁ כִּי יִמָּרֵט רֹאשׁוֹ--קֵרֵחַ הוּא טָהוֹר הוּא",
         "ואי אנסאן אנתתף שערה. פהו אלאצלע והו טאהר",
         "And any person whose hair has fallen out — he is the bald one, and he is pure."),
    ],
    41: [
        ("וְאִם מִפְּאַת פָּנָיו יִמָּרֵט רֹאשׁוֹ--גִּבֵּחַ הוּא טָהוֹר הוּא",
         "ואן אנתתף מן גהה' וגהה. פהו אלאגלח והו טאהר",
         "And if it has fallen out from the side of his face, he is the forehead-bald one, and he is pure."),
    ],
    42: [
        ("וְכִי-יִהְיֶה בַקָּרַחַת אוֹ בַגַּבַּחַת נֶגַע לָבָן אֲדַמְדָּם",
         "פאן כאן פי אלצלעה או פי אלגלחה. בלא ביאץ' מחמר",
         "But if there is in the bald patch or in the forehead-bald patch a white affliction tinged with red,"),
        ("צָרַעַת פֹּרַחַת הִוא בְּקָרַחְתּוֹ אוֹ בְגַבַּחְתּוֹ",
         "פימכן אן יכון ברץ. קד אנתשר פי צלעתה או פי גלחתה",
         "it may be leprosy that has spread in his bald patch or his forehead-bald patch."),
    ],
    43: [
        ("וְרָאָה אֹתוֹ הַכֹּהֵן וְהִנֵּה שְׂאֵת-הַנֶּגַע לְבָנָה אֲדַמְדֶּמֶת בְּקָרַחְתּוֹ אוֹ בְגַבַּחְתּוֹ",
         "פ לינצ'ר אלאמאם. אן כאנת שאמה' אלבלא ביצ'א מחמרה. פי צלעתה או פי גלחתה",
         "The imām shall inspect: if the mark of the affliction is white tinged with red, in his bald patch or his forehead-bald patch,"),
        ("כְּמַרְאֵה צָרַעַת עוֹר בָּשָׂר",
         "עלי' סביל מנאצ'ר ברץ סאיר גלד אלבדן ואחכאמהא",
         "after the manner of the appearances of leprosy of the rest of the skin of the body and its rulings —"),
    ],
    44: [
        ("אִישׁ-צָרוּעַ הוּא טָמֵא הוּא",
         "פהו רגל אברץ והו נגס",
         "he is a leprous man and he is impure;"),
        ("טַמֵּא יְטַמְּאֶנּוּ הַכֹּהֵן בְּרֹאשׁוֹ נִגְעוֹ",
         "פלינגסה אלאמאם תנגיסא פאן בלאה פי ראסה",
         "the imām shall declare him thoroughly impure, for his affliction is in his head."),
    ],
    45: [
        ("וְהַצָּרוּעַ אֲשֶׁר-בּוֹ הַנֶּגַע בְּגָדָיו יִהְיוּ פְרֻמִים וְרֹאשׁוֹ יִהְיֶה פָרוּעַ",
         "ואלאברץ אלד'י בה אלבלא. יגב אן תכון ת'יאבה ממזקה וראסה יכון שעת'א",
         "And the leper in whom the affliction is — his garments must be torn and his head shall be disheveled,"),
        ("וְעַל-שָׂפָם יַעְטֶה וְטָמֵא טָמֵא יִקְרָא",
         "ויתלת'ם עלי' שארבה. וינאדי אלנגס אלנגס",
         "and he shall cover over his mustache, and he shall call out: 'Impure! Impure!'"),
    ],
    46: [
        ("כָּל-יְמֵי אֲשֶׁר הַנֶּגַע בּוֹ יִטְמָא--טָמֵא הוּא",
         "טול מא אקאם פיה אלבלא. ינגס פאנה נגס",
         "For as long as the affliction remains in him he shall be impure — for he is impure;"),
        ("בָּדָד יֵשֵׁב מִחוּץ לַמַּחֲנֶה מוֹשָׁבוֹ",
         "פליגלס פרדא. כ'ארג אלעסכר יכון מקאמה",
         "he shall dwell alone, outside the camp shall be his dwelling-place."),
    ],
    47: [
        ("וְהַבֶּגֶד כִּי-יִהְיֶה בוֹ נֶגַע צָרָעַת בְּבֶגֶד צֶמֶר אוֹ בְּבֶגֶד פִּשְׁתִּים",
         "ואי תוב כאן פיה בלא ברץ. מן ת'וב צוף או כתאן",
         "And any garment in which there is an affliction of leprosy — whether a garment of wool or"),
    ],
    48: [
        ("אוֹ בִשְׁתִי אוֹ בְעֵרֶב לַפִּשְׁתִּים וְלַצָּמֶר אוֹ בְעוֹר אוֹ בְּכָל-מְלֶאכֶת עוֹר",
         "או סדא או לחמה. מן כתאן וצוף. או פי גלד. או ממא צנע מנה",
         "of linen, or in warp or weft of linen or wool, or in hide, or in anything made from it —"),
    ],
    49: [
        ("וְהָיָה הַנֶּגַע יְרַקְרַק אוֹ אֲדַמְדָּם בַּבֶּגֶד אוֹ בָעוֹר אוֹ-בַשְּׁתִי אוֹ-בָעֵרֶב אוֹ בְכָל-כְּלִי-עוֹר",
         "וכאן אלבלא. אכ'צ'רא או אחמרא. פי אלתוב או אלגלד. או אלס'דא או אלחמה או פי שי מן אנא אלגלוד",
         "and the affliction is green or red, in the garment or the hide, or the warp or the weft, or in any article of hides —"),
        ("נֶגַע צָרַעַת הוּא וְהָרְאָה אֶת-הַכֹּהֵן",
         "פד'אלך הו בלא ברץ. פליורא לאלאמאם",
         "that is an affliction of leprosy; it shall be shown to the imām."),
    ],
    50: [
        ("וְרָאָה הַכֹּהֵן אֶת-הַנָּגַע וְהִסְגִּיר אֶת-הַנֶּגַע שִׁבְעַת יָמִים",
         "פאד'א ראה אוקפה סבעה' איאם",
         "When it is seen, he shall confine it for seven days."),
    ],
    51: [
        ("וְרָאָה אֶת-הַנֶּגַע בַּיּוֹם הַשְּׁבִיעִי כִּי-פָשָׂה הַנֶּגַע בַּבֶּגֶד אוֹ-בַשְּׁתִי אוֹ-בָעֵרֶב אוֹ בָעוֹר לְכֹל אֲשֶׁר-יֵעָשֶׂה הָעוֹר לִמְלָאכָה",
         "ת'ם ינצ'רה פי אליום אלסאבע. פאן תפשא אלבלא. פי אלת'וב או אלס'דא או אלחמה או פי אלגלד. וסאיר מא יעמל מן אלגלוד מצנועא",
         "Then he shall inspect it on the seventh day; if the affliction has spread in the garment, or the warp or the weft, or in the hide, or in the rest of what is made from hides as a manufactured article —"),
        ("צָרַעַת מַמְאֶרֶת הַנֶּגַע טָמֵא הוּא",
         "פד'אך בלא ברץ מאחק והו נגס",
         "that is a consuming affliction of leprosy, and it is impure."),
    ],
    52: [
        ("וְשָׂרַף אֶת-הַבֶּגֶד אוֹ אֶת-הַשְּׁתִי אוֹ אֶת-הָעֵרֶב בַּצֶּמֶר אוֹ בַפִּשְׁתִּים אוֹ אֶת-כָּל-כְּלִי הָעוֹר אֲשֶׁר-יִהְיֶה בוֹ הַנָּגַע",
         "פליחרק אלת'וב. או אלסדא או אללחמה. כאן מן צוף או כתאן. או גמיע אניה' אלגלוד. אלד'י יכון פיהא אלבלא",
         "He shall burn the garment, or the warp or the weft, whether of wool or linen, or all the articles of hides in which the affliction is —"),
        ("כִּי-צָרַעַת מַמְאֶרֶת הִוא בָּאֵשׁ תִּשָּׂרֵף",
         "פאנה ברץ מאחק. לד'אלך יחרק באלנאר",
         "for it is a consuming leprosy; therefore it shall be burned with fire."),
    ],
    53: [
        ("וְאִם יִרְאֶה הַכֹּהֵן וְהִנֵּה לֹא-פָשָׂה הַנֶּגַע בַּבֶּגֶד אוֹ בַשְּׁתִי אוֹ בָעֵרֶב אוֹ בְּכָל-כְּלִי-עוֹר",
         "ואן ראה אלאמאם. פאד'אה לם יתפש פי אלת'וב. או אלסדא או אללחמה. או גמיע אניה' אלגלוד",
         "But if the imām sees that it has not spread in the garment, or the warp or the weft, or in any article of hides —"),
    ],
    54: [
        ("וְצִוָּה הַכֹּהֵן וְכִבְּסוּ אֵת אֲשֶׁר-בּוֹ הַנָּגַע וְהִסְגִּירוֹ שִׁבְעַת-יָמִים שֵׁנִית",
         "פליאמר בג'סלה. ויוקפה סבעה' איאם ת'אניה",
         "he shall command that it be washed, and he shall confine it for a second seven days."),
    ],
    55: [
        ("וְרָאָה הַכֹּהֵן אַחֲרֵי הֻכַּבֵּס אֶת-הַנֶּגַע וְהִנֵּה לֹא-הָפַךְ הַנֶּגַע אֶת-עֵינוֹ וְהַנֶּגַע לֹא-פָשָׂה--טָמֵא הוּא בָּאֵשׁ תִּשְׂרְפֶנּוּ",
         "ת'ם ינצ'רה בעד מא ג'סל. פאן כאן לם ינקלב לונה ולם יתפש. פהו נגס. פליחרק באלנאר",
         "Then he shall inspect it after it has been washed; if its color has not changed and it has not spread, it is impure — it shall be burned with fire;"),
        ("פְּחֶתֶת הִוא בְּקָרַחְתּוֹ אוֹ בְגַבַּחְתּוֹ",
         "והי מהלכה כאנת פי סחקתה או פי זיברתה",
         "it was a destructive thing, whether in its worn part or in its new part."),
    ],
    56: [
        ("וְאִם רָאָה הַכֹּהֵן וְהִנֵּה כֵּהָה הַנֶּגַע אַחֲרֵי הֻכַּבֵּס אֹתוֹ",
         "ואן ראה קד כבי בעד מא גסל",
         "But if he sees that it has dimmed after it was washed,"),
        ("וְקָרַע אֹתוֹ מִן-הַבֶּגֶד אוֹ מִן-הָעוֹר אוֹ מִן-הַשְּׁתִי אוֹ מִן-הָעֵרֶב",
         "פליכ'רקה מן אלת'וב או אלגלד. ויקטעה מן אלסדא או אללחמה",
         "he shall scrape it from the garment or the hide, and cut it out from the warp or the weft."),
    ],
    57: [
        ("וְאִם-תֵּרָאֶה עוֹד בַּבֶּגֶד אוֹ-בַשְּׁתִי אוֹ-בָעֵרֶב אוֹ בְכָל-כְּלִי-עוֹר--פֹּרַחַת הִוא",
         "ואן צ'הרת זיאדה פי אלת'וב. או אלסדא או אללחמה או גמיע אניה' אלגלוד. פהי אלמנתשרה",
         "And if it appears further in the garment, or the warp or the weft, or in any article of hides — it is the spreading one;"),
        ("בָּאֵשׁ תִּשְׂרְפֶנּוּ אֵת אֲשֶׁר-בּוֹ הַנָּגַע",
         "פלתחרק באלנאר. אלת'וב אלד'י פי אלבלא",
         "the garment in which the affliction is shall be burned with fire."),
    ],
    58: [
        ("וְהַבֶּגֶד אוֹ-הַשְּׁתִי אוֹ-הָעֵרֶב אוֹ-כָל-כְּלִי הָעוֹר אֲשֶׁר תְּכַבֵּס וְסָר מֵהֶם הַנָּגַע",
         "ואלת'וב. או אלסדא או אללחמה או גמיע אנא אלגלוד אן ג'סלת. וזאל ענהא אלבלא",
         "But the garment, or the warp or the weft, or any article of hides — if they are washed and the affliction departs from them,"),
        ("וְכֻבַּס שֵׁנִית וְטָהֵר",
         "פלתג'סל ת'אניה ותטהר",
         "they shall be washed a second time and they shall be pure."),
    ],
    59: [
        ("זֹאת תּוֹרַת נֶגַע-צָרַעַת בֶּגֶד הַצֶּמֶר אוֹ הַפִּשְׁתִּים אוֹ הַשְּׁתִי אוֹ הָעֵרֶב אוֹ כָּל-כְּלִי-עוֹר",
         "הד'ה שריעה' בלא אלברץ. אלכאין פי ת'וב צוף או כתאן. או סדא או לחמה. או שי מן אנא אלגלוד",
         "This is the ordinance of the affliction of leprosy in a garment of wool or linen, or warp or weft, or any article of hides —"),
        ("לְטַהֲרוֹ אוֹ לְטַמְּאוֹ",
         "ליטהר או ינגס",
         "to declare it pure or to declare it impure."),
    ],
}
