"""Hand-authored alignment triples for Vayikra chapter 25."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה בְּהַר סִינַי לֵאמֹר",
         "ת'ם קאל אללה למוסי'. פי טור סיני תכלימא",
         "Then God spoke to Moses, on Mount Sinai, a speaking."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם כִּי תָבֹאוּ אֶל-הָאָרֶץ אֲשֶׁר אֲנִי נֹתֵן לָכֶם",
         "מר בני אסראיל וקל להם. אד'א דכ'לתם אלי' אלבלד אלד'י אנא מעטיכם",
         "Command the sons of Israel and say to them: When you enter the land which I am giving you,"),
        ("וְשָׁבְתָה הָאָרֶץ שַׁבָּת לַיהוָה",
         "פעטלו אלארץ' עטלה ללה",
         "then let the land desist — a desisting for God."),
    ],
    3: [
        ("שֵׁשׁ שָׁנִים תִּזְרַע שָׂדֶךָ וְשֵׁשׁ שָׁנִים תִּזְמֹר כַּרְמֶךָ",
         "אן תכון סת סנין תזרע צ'יעתך. וסת סנין תרפק כרמך",
         "That there be six years in which you sow your estate, and six years in which you tend your vineyard,"),
        ("וְאָסַפְתָּ אֶת-תְּבוּאָתָהּ",
         "ותגמע ג'לתהא",
         "and gather its yield."),
    ],
    4: [
        ("וּבַשָּׁנָה הַשְּׁבִיעִת שַׁבַּת שַׁבָּתוֹן יִהְיֶה לָאָרֶץ--שַׁבָּת לַיהוָה",
         "ופי אלסנה אלסאבעה עטלה לאלארץ'. הי סבת ללה",
         "But in the seventh year there shall be a desisting for the land — it is a sabbath for God;"),
        ("שָׂדְךָ לֹא תִזְרָע וְכַרְמְךָ לֹא תִזְמֹר",
         "לא תזרע צ'יעתך. ולא תרפק כרמך",
         "do not sow your estate, and do not tend your vineyard."),
    ],
    5: [
        ("אֵת סְפִיחַ קְצִירְךָ לֹא תִקְצוֹר",
         "וכ'לף זרעך פלא תחצדה",
         "The aftergrowth of your harvest you shall not reap,"),
        ("וְאֶת-עִנְּבֵי נְזִירֶךָ לֹא תִבְצֹר שְׁנַת שַׁבָּתוֹן יִהְיֶה לָאָרֶץ",
         "ואלפראד מן ענבך פלא תקטפה. לאנהא סנה' עטלה לאלארץ'",
         "and the single grapes of your vineyard you shall not pluck — for it is a year of desisting for the land."),
    ],
    6: [
        ("וְהָיְתָה שַׁבַּת הָאָרֶץ לָכֶם לְאָכְלָה--לְךָ וּלְעַבְדְּךָ וְלַאֲמָתֶךָ וְלִשְׂכִירְךָ וּלְתוֹשָׁבְךָ הַגָּרִים עִמָּךְ",
         "וליכון מא ינבת מן אלארץ' אלמעטלה לכם מאכלא. לך ולעבדך ולאמתך. ולאגירך ולציפך. אלמקימין מעך",
         "And let what grows from the desisted land be for you as food — for you, and for your male slave, and for your female slave, and for your hired worker, and for your guest, who dwell with you."),
    ],
    7: [
        ("וְלִבְהֶמְתְּךָ--וְלַחַיָּה אֲשֶׁר בְּאַרְצֶךָ תִּהְיֶה כָל-תְּבוּאָתָהּ לֶאֱכֹל",
         "ולבהאימך. ולאלוחש אלד'י פי ארצ'ך. תכון גמיע ג'לתהא מאכלא",
         "And for your beasts, and for the wild creatures that are in your land, all its yield shall be for food."),
    ],
    8: [
        ("וְסָפַרְתָּ לְךָ שֶׁבַע שַׁבְּתֹת שָׁנִים--שֶׁבַע שָׁנִים שֶׁבַע פְּעָמִים",
         "ת'ם אחץ סבע סנין עטלה. וד'אלך אלסבע אלסנין סבע מראר",
         "Then count seven years of desisting — and those seven years, seven times —"),
        ("וְהָיוּ לְךָ יְמֵי שֶׁבַע שַׁבְּתֹת הַשָּׁנִים תֵּשַׁע וְאַרְבָּעִים שָׁנָה",
         "פיציר גמלה' ד'אלך תסעה וארבעין סנה",
         "so that the sum of that shall be forty-nine years."),
    ],
    9: [
        ("וְהַעֲבַרְתָּ שׁוֹפַר תְּרוּעָה בַּחֹדֶשׁ הַשְּׁבִעִי בֶּעָשׂוֹר לַחֹדֶשׁ בְּיוֹם הַכִּפֻּרִים",
         "ואצ'רב בבוק מגלב. פי אליום אלעאשר מן אלשהר אלסאבע . והו יום אלג'פראן",
         "And sound a gathering horn on the tenth day of the seventh month — it is the Day of Atonement —"),
        ("תַּעֲבִירוּ שׁוֹפָר בְּכָל-אַרְצְכֶם",
         "אצ'רבו פיה באלבוק פי גמיע בלאדכם",
         "sound it throughout all your lands."),
    ],
    11: [
        ("יוֹבֵל הִוא שְׁנַת הַחֲמִשִּׁים שָׁנָה--תִּהְיֶה לָכֶם לֹא תִזְרָעוּ",
         "ומן שרוט הד'ה סנה' אלאטלאק סנה' אלכ'מסין. אן לא תזרעו פיהא",
         "And among the conditions of this year of release, the year of fifty: you shall not sow in it,"),
        ("וְלֹא תִקְצְרוּ אֶת-סְפִיחֶיהָ וְלֹא תִבְצְרוּ אֶת-נְזִרֶיהָ",
         "ולא תחצדו כ'לפהא. ולא תקטפו פראדהא",
         "and you shall not reap its aftergrowth, and you shall not pluck its single grapes."),
    ],
    12: [
        ("כִּי יוֹבֵל הִוא קֹדֶשׁ תִּהְיֶה לָכֶם",
         "לאנהא סנה' אטלאק. תכון לכם מקדסה",
         "For it is a year of release — it shall be holy for you;"),
        ("מִן-הַשָּׂדֶה--תֹּאכְלוּ אֶת-תְּבוּאָתָהּ",
         "ומן אלצחרא. תאכלו ג'לתהא מבאחא",
         "from the open country you shall eat its yield as that which is freely permitted."),
    ],
    13: [
        ("בִּשְׁנַת הַיּוֹבֵל הַזֹּאת תָּשֻׁבוּ אִישׁ אֶל-אֲחֻזָּתוֹ",
         "ופי הד'ה סנה' אלאטלאק. ירגע כל אמר אלי' חוזה",
         "And in this year of release, every man shall return to his holding."),
    ],
    14: [
        ("וְכִי-תִמְכְּרוּ מִמְכָּר לַעֲמִיתֶךָ אוֹ קָנֹה מִיַּד עֲמִיתֶךָ--אַל-תּוֹנוּ אִישׁ אֶת-אָחִיו",
         "ואד'א בעת ביעא לצאחבך. או אבתעת מנה. פלא יג'בן כל ואחד אכ'אה",
         "And when you sell a sale to your fellow, or buy from him, let no one wrong his brother."),
    ],
    15: [
        ("בְּמִסְפַּר שָׁנִים אַחַר הַיּוֹבֵל תִּקְנֶה מֵאֵת עֲמִיתֶךָ",
         "באחצא סנין מן בעד סנה אלאטלאק. תשתרי מן צאחבך",
         "By the count of years after the year of release you shall buy from your fellow,"),
        ("בְּמִסְפַּר שְׁנֵי-תְבוּאֹת יִמְכָּר-לָךְ",
         "ובאחצא סני ג'לתהא יביעך הו",
         "and by the count of years of its yield he shall sell to you."),
    ],
    16: [
        ("לְפִי רֹב הַשָּׁנִים תַּרְבֶּה מִקְנָתוֹ וּלְפִי מְעֹט הַשָּׁנִים תַּמְעִיט מִקְנָתוֹ",
         "פעלי' קדר כת'רת אלסנין. יגב אן תכת'ר לה אלת'מן. ועלי' קדר קלתהא. יגוז אן תקל לה",
         "According to the abundance of the years, the price must be increased for him; and according to the fewness of them, it is permitted that it be decreased for him —"),
        ("כִּי מִסְפַּר תְּבוּאֹת הוּא מֹכֵר לָךְ",
         "לאנה אנמא יביעך ג'לאת מחצאה",
         "for it is a counted number of yields that he is selling you."),
    ],
    17: [
        ("וְלֹא תוֹנוּ אִישׁ אֶת-עֲמִיתוֹ",
         "ולא יג'בן כל ואחד צאחבה",
         "And let no one wrong his fellow;"),
        ("וְיָרֵאתָ מֵאֱלֹהֶיךָ כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "וכ'ף רבך. פאני אללה רבכם אלמעאקב",
         "and fear your Lord — for I am God, your Lord, who punishes."),
    ],
    18: [
        ("וַעֲשִׂיתֶם אֶת-חֻקֹּתַי וְאֶת-מִשְׁפָּטַי תִּשְׁמְרוּ וַעֲשִׂיתֶם אֹתָם",
         "ואעמלו רסומי ואחכאמי אחפצוהא ואעמלו בהא",
         "And perform My statutes, and My ordinances — keep them and act by them;"),
        ("וִישַׁבְתֶּם עַל-הָאָרֶץ לָבֶטַח",
         "ואסכנו אלבלד ואת'קין בי",
         "and dwell in the land, trusting in Me."),
    ],
    19: [
        ("וְנָתְנָה הָאָרֶץ פִּרְיָהּ וַאֲכַלְתֶּם לָשֹׂבַע",
         "תכ'רג לכם אלארץ' ת'מרהא. פתאכלוה הנייא",
         "The land shall bring forth its fruit for you, and you shall eat it with enjoyment,"),
        ("וִישַׁבְתֶּם לָבֶטַח עָלֶיהָ",
         "ותקימון בהא ואת'קין",
         "and you shall settle therein, trusting."),
    ],
    20: [
        ("וְכִי תֹאמְרוּ מַה-נֹּאכַל בַּשָּׁנָה הַשְּׁבִיעִת הֵן לֹא נִזְרָע וְלֹא נֶאֱסֹף אֶת-תְּבוּאָתֵנוּ",
         "פאן קלתם. מא נאכל פי אלסנה אלסאבעה. אד' לא נזרע. ולא נגמע ג'לתנא",
         "And if you say: What shall we eat in the seventh year, since we do not sow, and do not gather our yield —"),
    ],
    21: [
        ("וְצִוִּיתִי אֶת-בִּרְכָתִי לָכֶם בַּשָּׁנָה הַשִּׁשִּׁית",
         "פאמר בברכתי לכם. פי אלסנה אלסאדסה",
         "I shall command My blessing upon you in the sixth year,"),
        ("וְעָשָׂת אֶת-הַתְּבוּאָה לִשְׁלֹשׁ הַשָּׁנִים",
         "פתכפיכם ג'לתהא ת'לאת' סנין",
         "and its yield shall suffice you for three years."),
    ],
    22: [
        ("וּזְרַעְתֶּם אֵת הַשָּׁנָה הַשְּׁמִינִת וַאֲכַלְתֶּם מִן-הַתְּבוּאָה יָשָׁן עַד הַשָּׁנָה הַתְּשִׁיעִת",
         "ואזרעו פי אלסנה אלת'אמנה. ואנתם תאכלון מן ג'לתהא עתיקא. אלי' אלסנה אלתאסעה",
         "And you shall sow in the eighth year, while you are eating from the old yield — until the ninth year,"),
        ("עַד-בּוֹא תְּבוּאָתָהּ--תֹּאכְלוּ יָשָׁן",
         "אלי'' מגי ג'לתהא. תאכלון עתיקא",
         "until the coming of its yield, you shall eat what is old."),
    ],
    23: [
        ("וְהָאָרֶץ לֹא תִמָּכֵר לִצְמִתֻת--כִּי-לִי הָאָרֶץ",
         "ואלארץ' פלא תבאע בתאתא. לאנהא לי",
         "And the land shall not be sold outright — for it is Mine;"),
        ("כִּי-גֵרִים וְתוֹשָׁבִים אַתֶּם עִמָּדִי",
         "ואנמא אנתם סכאן ואצ'יאף לי",
         "you are but residents and guests with Me."),
    ],
    24: [
        ("וּבְכֹל אֶרֶץ אֲחֻזַּתְכֶם גְּאֻלָּה תִּתְּנוּ לָאָרֶץ",
         "ופי גמיע בלד חוזכם. אגעלו ולאיה לאלארץ'",
         "And throughout all the land of your holding, grant dominion over the land."),
    ],
    25: [
        ("כִּי-יָמוּךְ אָחִיךָ וּמָכַר מֵאֲחֻזָּתוֹ",
         "ואד'א תמאהן אכ'יך. פבאע שייא מן חוזה",
         "And if your brother becomes impoverished and sells something of his holding,"),
        ("וּבָא גֹאֲלוֹ הַקָּרֹב אֵלָיו וְגָאַל אֵת מִמְכַּר אָחִיו",
         "פליאת ולייה אלאקרב אליה. ויתולא ביע אכ'יה",
         "then let his nearest guardian come and take charge of his brother's sale."),
    ],
    26: [
        ("וְאִישׁ כִּי לֹא יִהְיֶה-לּוֹ גֹּאֵל וְהִשִּׂיגָה יָדוֹ וּמָצָא כְּדֵי גְאֻלָּתוֹ",
         "ואי רג'ל לם יכון לה ולי. פנאלת ידה. ואצאב כמקדאר פכאכה",
         "And any man who has no guardian — if his hand reaches, and he finds the measure of his redemption —"),
    ],
    27: [
        ("וְחִשַּׁב אֶת-שְׁנֵי מִמְכָּרוֹ וְהֵשִׁיב אֶת-הָעֹדֵף לָאִישׁ אֲשֶׁר מָכַר-לוֹ",
         "פליחסב סני ביעה. וירד אלפאצ'ל אלי' אלרגל אלד'י באעה",
         "let him reckon the years of his sale, and return the surplus to the man to whom he sold it,"),
        ("וְשָׁב לַאֲחֻזָּתוֹ",
         "וירגע אלי' חוזה",
         "and he shall return to his holding."),
    ],
    28: [
        ("וְאִם לֹא-מָצְאָה יָדוֹ דֵּי הָשִׁיב לוֹ--וְהָיָה מִמְכָּרוֹ בְּיַד הַקֹּנֶה אֹתוֹ עַד שְׁנַת הַיּוֹבֵל",
         "ואן לם תנאל ידה מקדאר מא ירדה עליה. פליבק ביעה. פי יד אלמשתרי מנה. אלי' סנה' אלאטלאק",
         "And if his hand does not reach the measure of what he is to return to him, then his sale shall remain in the hand of its buyer until the year of release;"),
        ("וְיָצָא בַּיֹּבֵל וְשָׁב לַאֲחֻזָּתוֹ",
         "ויכ'רג פיהא וירגע אלי' חוזה",
         "and in that year it shall go out, and he shall return to his holding."),
    ],
    29: [
        ("וְאִישׁ כִּי-יִמְכֹּר בֵּית-מוֹשַׁב עִיר חוֹמָה--וְהָיְתָה גְּאֻלָּתוֹ עַד-תֹּם שְׁנַת מִמְכָּרוֹ",
         "ואי רג'ל באע ביתא מסכנא פי קריה להא סור. פליכון באלכ'יאר. אלי' אנקצ'א סנה מן יום ביעה",
         "And any man who sells a dwelling house in a town that has a wall — he shall have the option until the completion of a year from the day of his sale;"),
        ("יָמִים תִּהְיֶה גְאֻלָּתוֹ",
         "פיכון פכאכה חולא",
         "his redemption shall be a full year."),
    ],
    30: [
        ("וְאִם לֹא-יִגָּאֵל עַד-מְלֹאת לוֹ שָׁנָה תְמִימָה--וְקָם הַבַּיִת אֲשֶׁר-בָּעִיר אֲשֶׁר-לא (לוֹ) חֹמָה לַצְּמִיתֻת לַקֹּנֶה אֹתוֹ לְדֹרֹתָיו",
         "פאן לם יפתכה. אלי' אן כמלת לה סנה תאמה. פקד ת'בת אלבית אלד'י פי אלקריה אלתי להא סור. בתאתא ללמשתרי ולאגיאלה",
         "And if he does not redeem it by the time a full year is completed for him, then the house in the town that has a wall is confirmed outright for the buyer and his generations —"),
        ("לֹא יֵצֵא בַּיֹּבֵל",
         "לא יכ'רג פי סנה' אלאטלאק",
         "it shall not go out in the year of release."),
    ],
    31: [
        ("וּבָתֵּי הַחֲצֵרִים אֲשֶׁר אֵין-לָהֶם חֹמָה סָבִיב--עַל-שְׂדֵה הָאָרֶץ יֵחָשֵׁב גְּאֻלָּה תִּהְיֶה-לּוֹ",
         "וביות אלארבאץ'. אלתי ליס להא סור יחיט בהא. פכמת'ל צ'יאע אלארץ' תחסב. אן יכון להא ולאיה",
         "But houses of the outlying settlements that have no wall surrounding them shall be reckoned like the estates of the open country — dominion shall apply to them,"),
        ("וּבַיֹּבֵל יֵצֵא",
         "ותכ'רג פי סנה' אלאטלאק",
         "and they shall go out in the year of release."),
    ],
    32: [
        ("וְעָרֵי הַלְוִיִּם--בָּתֵּי עָרֵי אֲחֻזָּתָם גְּאֻלַּת עוֹלָם תִּהְיֶה לַלְוִיִּם",
         "ואמא קרי' אלליואניין וביות קרי' חוזהם. פלהם אן יפתכוהא אבדא",
         "But as for the towns of the Levites, and the houses of their towns which are their holding — they have the right to redeem them forever."),
    ],
    33: [
        ("וַאֲשֶׁר יִגְאַל מִן-הַלְוִיִּם וְיָצָא מִמְכַּר-בַּיִת וְעִיר אֲחֻזָּתוֹ בַּיֹּבֵל",
         "ומן ישתרי ד'אלך מנהם. פליכ'רג כל בית מביוע. וקרי' חוז לאייהם כאן פי סנה אלאטלאק",
         "And whoever buys from them — every sold house and the towns of the holding of whichever Levite it may be shall go out in the year of release —"),
        ("כִּי בָתֵּי עָרֵי הַלְוִיִּם הִוא אֲחֻזָּתָם בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "לאן ביותהם וקראהם. הי חוזהם פי מא בין בני אסראיל",
         "for their houses and their towns are their holding among the sons of Israel."),
    ],
    34: [
        ("וּשְׂדֵה מִגְרַשׁ עָרֵיהֶם לֹא יִמָּכֵר כִּי-אֲחֻזַּת עוֹלָם הוּא לָהֶם",
         "ואמא צ'יאע פנא קראהם לא תבאע בתה. לאנהא חוז אלדהר להם",
         "But the estates of the open ground around their towns shall not be sold at all — for it is their holding forever."),
    ],
    35: [
        ("וְכִי-יָמוּךְ אָחִיךָ וּמָטָה יָדוֹ עִמָּךְ--וְהֶחֱזַקְתָּ בּוֹ גֵּר וְתוֹשָׁב וָחַי עִמָּךְ",
         "ואד'א תמאהן אכ'יך. פמאלת ידה מעך. פאשדדה. באן יכון לך סאכנא וצ'יפא. פיעיש מעך",
         "And if your brother becomes impoverished and his hand falters with you, then strengthen him — that he be as a resident and a guest with you — and let him live with you."),
    ],
    36: [
        ("אַל-תִּקַּח מֵאִתּוֹ נֶשֶׁךְ וְתַרְבִּית",
         "לא תאכ'ד' מנה עיינה ולא רבא",
         "Do not take from him a sample-interest nor usury;"),
        ("וְיָרֵאתָ מֵאֱלֹהֶיךָ וְחֵי אָחִיךָ עִמָּךְ",
         "וכ'ף רבך. חתי יעיש אכ'יך מעך",
         "and fear your Lord, so that your brother may live with you."),
    ],
    37: [
        ("אֶת-כַּסְפְּךָ--לֹא-תִתֵּן לוֹ בְּנֶשֶׁךְ וּבְמַרְבִּית לֹא-תִתֵּן אָכְלֶךָ",
         "ולא תדפע אליה ורקך וטעאמך. בעיינה ולא ברבא",
         "And do not advance to him your money or your food at sample-interest, nor at usury."),
    ],
    38: [
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם אֲשֶׁר-הוֹצֵאתִי אֶתְכֶם מֵאֶרֶץ מִצְרָיִם--לָתֵת לָכֶם אֶת-אֶרֶץ כְּנַעַן לִהְיוֹת לָכֶם לֵאלֹהִים",
         "אנא אללה רבכם. אלמכ'רגכם מן בלד מצר. לאעטיכם בלד כנעאן פאכון לכם אלאהא",
         "I am God, your Lord, who brought you out from the land of Egypt, to give you the land of Canaan, that I may be your God."),
    ],
    39: [
        ("וְכִי-יָמוּךְ אָחִיךָ עִמָּךְ וְנִמְכַּר-לָךְ--לֹא-תַעֲבֹד בּוֹ עֲבֹדַת עָבֶד",
         "ואד'א תמאהן אכ'יך מעך. פבאע נפסה לך. לא תסתכ'דמה כ'דמה' אלעביד",
         "And if your brother becomes impoverished with you and sells himself to you, do not press him into the service of slaves."),
    ],
    40: [
        ("כְּשָׂכִיר כְּתוֹשָׁב יִהְיֶה עִמָּךְ עַד-שְׁנַת הַיֹּבֵל יַעֲבֹד עִמָּךְ",
         "בל כאגיר או צ'יף יכון מעך. ואלי' סנה' אלאטלאק יכ'דמך",
         "Rather, as a hired worker or a guest he shall be with you; until the year of release he shall serve you."),
    ],
    41: [
        ("וְיָצָא מֵעִמָּךְ--הוּא וּבָנָיו עִמּוֹ וְשָׁב אֶל-מִשְׁפַּחְתּוֹ וְאֶל-אֲחֻזַּת אֲבֹתָיו יָשׁוּב",
         "ת'ם יכ'רג מן ענדך. הו ובניה מעה. וירגע אלי' עשירתה. ואלי' חוז אביה",
         "Then he shall go out from your presence — he and his sons with him — and return to his clan and to the holding of his father."),
    ],
    42: [
        ("כִּי-עֲבָדַי הֵם אֲשֶׁר-הוֹצֵאתִי אֹתָם מֵאֶרֶץ מִצְרָיִם לֹא יִמָּכְרוּ מִמְכֶּרֶת עָבֶד",
         "לאנהם עבידי. אלד'י אכ'רגתהם מן בלד מצר. פלא יבאעו ביע אלעביד",
         "For they are My servants whom I brought out from the land of Egypt — they shall not be sold in the manner of the sale of slaves."),
    ],
    43: [
        ("לֹא-תִרְדֶּה בוֹ בְּפָרֶךְ וְיָרֵאתָ מֵאֱלֹהֶיךָ",
         "ולא תסתולי עליה באקמא. וכ'ף רבך",
         "And do not hold dominion over him with cruelty; and fear your Lord."),
    ],
    44: [
        ("וְעַבְדְּךָ וַאֲמָתְךָ אֲשֶׁר יִהְיוּ-לָךְ מֵאֵת הַגּוֹיִם אֲשֶׁר סְבִיבֹתֵיכֶם--מֵהֶם תִּקְנוּ עֶבֶד וְאָמָה",
         "ועבדך ואמתך אלד'י יכונו לך. פמן אלאמם אלד'ין חואליכם. מנהם תקתנון עביד ואמא",
         "And your male slave and your female slave who shall be yours — from the nations that are around you, from them you may acquire slaves and maidservants."),
    ],
    45: [
        ("וְגַם מִבְּנֵי הַתּוֹשָׁבִים הַגָּרִים עִמָּכֶם מֵהֶם תִּקְנוּ",
         "ואיצ'א מן בני אלסכאן. אלמקימין מעכם תשתרון מנהם",
         "Also from the children of the residents who dwell with you, you may buy from them;"),
        ("וּמִמִּשְׁפַּחְתָּם אֲשֶׁר עִמָּכֶם אֲשֶׁר הוֹלִידוּ בְּאַרְצְכֶם וְהָיוּ לָכֶם לַאֲחֻזָּה",
         "ומן עשירתהם אלמולודין פי בלדכם. פיכונו לכם חוזא",
         "and from their clans born in your land — and they shall be a holding for you."),
    ],
    46: [
        ("וְהִתְנַחַלְתֶּם אֹתָם לִבְנֵיכֶם אַחֲרֵיכֶם לָרֶשֶׁת אֲחֻזָּה--לְעֹלָם בָּהֶם תַּעֲבֹדוּ",
         "תורתונהם לבניכם מן בעדכם כמיראת' אלחוז. ותסתכ'דמונהם אבדא",
         "You shall bequeath them to your sons after you as an inheritance, and you may press them into service forever;"),
        ("וּבְאַחֵיכֶם בְּנֵי-יִשְׂרָאֵל אִישׁ בְּאָחִיו לֹא-תִרְדֶּה בוֹ בְּפָרֶךְ",
         "ואמא אכ'ותכם בני אסראיל פכל ואחד לא יסתולי עלי' אכ'יה באקמא",
         "but as for your brothers the sons of Israel, no one shall hold dominion over his brother with cruelty."),
    ],
    47: [
        ("וְכִי תַשִּׂיג יַד גֵּר וְתוֹשָׁב עִמָּךְ וּמָךְ אָחִיךָ עִמּוֹ",
         "ואן נאלת יד ג'ריב או סאכן מעך. ותמאהן אכ'יך מעה",
         "And if the hand of a stranger or a resident with you reaches, and your brother becomes impoverished with him,"),
        ("וְנִמְכַּר לְגֵר תּוֹשָׁב עִמָּךְ אוֹ לְעֵקֶר מִשְׁפַּחַת גֵּר",
         "פבאע נפסה לג'ריב או סאכן מעך. או לאצל עשירה' אלג'ריב",
         "and sells himself to a stranger or a resident with you, or to the root of the stranger's clan —"),
    ],
    48: [
        ("אַחֲרֵי נִמְכַּר גְּאֻלָּה תִּהְיֶה-לּוֹ אֶחָד מֵאֶחָיו יִגְאָלֶנּוּ",
         "פבעד מא אנבאע יכון לה פכאך. ואחד מן אכ'ותה יפתכה",
         "after he has been sold there shall be a redemption for him; one of his brothers shall redeem him."),
    ],
    49: [
        ("אוֹ-דֹדוֹ אוֹ בֶן-דֹּדוֹ יִגְאָלֶנּוּ אוֹ-מִשְּׁאֵר בְּשָׂרוֹ מִמִּשְׁפַּחְתּוֹ יִגְאָלֶנּוּ",
         "או עמה או אבן עמה יפתכה. או מן נסיב ד'אתה. מן עשירתה יפתכה",
         "Or his uncle or his uncle's son shall redeem him, or one of the near kinsmen of his own person from his clan shall redeem him;"),
        ("אוֹ-הִשִּׂיגָה יָדוֹ וְנִגְאָל",
         "או נאלת ידה פפך נפסה",
         "or if his hand reaches, he shall redeem himself."),
    ],
    50: [
        ("וְחִשַּׁב עִם-קֹנֵהוּ מִשְּׁנַת הִמָּכְרוֹ לוֹ עַד שְׁנַת הַיֹּבֵל",
         "פליחאסב משתריה. כם מן סנה' אנבאע לה. אלי' סנה' אלאטלאק",
         "And he shall reckon with his buyer how many years he was sold to him until the year of release;"),
        ("וְהָיָה כֶּסֶף מִמְכָּרוֹ בְּמִסְפַּר שָׁנִים כִּימֵי שָׂכִיר יִהְיֶה עִמּוֹ",
         "פיסקט ת'מן ביעה עלי' אחצא אלסנין. וליכון מעה פיהא כאייאם אלאגיר",
         "and the price of his sale shall be apportioned according to the count of the years, and he shall be with him in those years as the days of a hired worker."),
    ],
    51: [
        ("אִם-עוֹד רַבּוֹת בַּשָּׁנִים--לְפִיהֶן יָשִׁיב גְּאֻלָּתוֹ מִכֶּסֶף מִקְנָתוֹ",
         "פאן בקי מן אלסנין כתיר. פעלי' קדרהא ירד פכאכה. מנסובא מן ת'מן שראה",
         "If many years remain, according to their measure he shall return his redemption, proportioned from the price of his purchase."),
    ],
    52: [
        ("וְאִם-מְעַט נִשְׁאַר בַּשָּׁנִים עַד-שְׁנַת הַיֹּבֵל--וְחִשַּׁב-לוֹ כְּפִי שָׁנָיו יָשִׁיב אֶת-גְּאֻלָּתוֹ",
         "ואן בקי מן אלסנין קליל. אלי' סנה' אלאטלאק פליחאסבה. ועלי' קדרהא ירד פכאכה",
         "And if few years remain until the year of release, he shall reckon with him — according to their measure he shall return his redemption."),
    ],
    53: [
        ("כִּשְׂכִיר שָׁנָה בְּשָׁנָה יִהְיֶה עִמּוֹ לֹא-יִרְדֶּנּוּ בְּפֶרֶךְ לְעֵינֶיךָ",
         "ובאלגמלה כאגיר סנה בסנה יכון מעה. לא יסתולי עליה באקמא בחצ'רתך",
         "In sum, as a hired worker year by year he shall be with him; he shall not hold dominion over him with cruelty in your presence."),
    ],
    54: [
        ("וְאִם-לֹא יִגָּאֵל בְּאֵלֶּה--וְיָצָא בִּשְׁנַת הַיֹּבֵל הוּא וּבָנָיו עִמּוֹ",
         "ואן לם יפתך בהד'א אלאמור. פליכ'רג פי סנה' אלאטלאק. הו ובניה מעה",
         "And if he is not redeemed by these means, then he shall go out in the year of release — he and his sons with him."),
    ],
    55: [
        ("כִּי-לִי בְנֵי-יִשְׂרָאֵל עֲבָדִים--עֲבָדַי הֵם אֲשֶׁר-הוֹצֵאתִי אוֹתָם מֵאֶרֶץ מִצְרָיִם",
         "לאן בני אסראיל עביד לי. אד' הם עבידי. אלד'י אכ'רגתהם מן בלד מצר",
         "For the sons of Israel are servants to Me — since they are My servants, whom I brought out from the land of Egypt:"),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אעבדוני",
         "I am God, your Lord; serve Me."),
    ],
}
