"""Hand-authored alignment triples for Vayikra chapter 11."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר אֲלֵהֶם",
         "פכלם אללה מוסי' והרון וקאל להמא",
         "And God spoke to Moses and Aaron, and said to them:"),
    ],
    2: [
        ("דַּבְּרוּ אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר",
         "כלמא בני אסראיל וקולא להם",
         "\"Speak to the sons of Israel, and say to them:"),
        ("זֹאת הַחַיָּה אֲשֶׁר תֹּאכְלוּ מִכָּל-הַבְּהֵמָה אֲשֶׁר עַל-הָאָרֶץ",
         "הד'א אלחיואן אלד'י יגוז אן תאכלוה. מן גמיע אלבהאים אלתי עלי' אלארץ'",
         "This is the animal which it is permitted that you eat, from all the beasts that walk upon the earth:"),
    ],
    3: [
        ("כֹּל מַפְרֶסֶת פַּרְסָה וְשֹׁסַעַת שֶׁסַע פְּרָסֹת מַעֲלַת גֵּרָה בַּבְּהֵמָה--אֹתָהּ תֹּאכֵלוּ",
         "כל מצ'לפה בצ'לף. ומפרק צ'לפהא תפריקא. ומצעדה אגתראר מן אלבהאים. פכלוהא",
         "every one that is hoofed with a hoof, and whose hooves are divided in a division, and that brings up cud, among the beasts — eat it."),
    ],
    4: [
        ("אַךְ אֶת-זֶה לֹא תֹאכְלוּ מִמַּעֲלֵי הַגֵּרָה וּמִמַּפְרִסֵי הַפַּרְסָה",
         "ואמא הד'א פלא תאכלוה מן אלמצעדי אלאגתראר. ואלמפרק אלצלף",
         "But this you shall not eat, from those that bring up cud and those that are divided of hoof:"),
        ("אֶת-הַגָּמָל כִּי-מַעֲלֵה גֵרָה הוּא וּפַרְסָה אֵינֶנּוּ מַפְרִיס--טָמֵא הוּא לָכֶם",
         "אלגמל. פאנה מצעד אגתראר. ג'יר מצ'לף בצ'לף. והו נגס לכם",
         "the camel — for it brings up cud yet is not hoofed with a hoof; it is impure for you."),
    ],
    5: [
        ("וְאֶת-הַשָּׁפָן כִּי-מַעֲלֵה גֵרָה הוּא וּפַרְסָה לֹא יַפְרִיס טָמֵא הוּא לָכֶם",
         "ואלובר פאנה מצעד אגתראר. ג'יר מצ'לף בצ'לף. והו נגס לכם",
         "And the hyrax — for it brings up cud yet is not hoofed with a hoof; it is impure for you."),
    ],
    6: [
        ("וְאֶת-הָאַרְנֶבֶת כִּי-מַעֲלַת גֵּרָה הִוא וּפַרְסָה לֹא הִפְרִיסָה טְמֵאָה הִוא לָכֶם",
         "ואלארנב. פאנהא מצעדה אגתראר. והי ג'יר מצ'לפה. והי נגסה לכם",
         "And the hare — for it brings up cud, yet it is not hoofed; it is impure for you."),
    ],
    7: [
        ("וְאֶת-הַחֲזִיר כִּי-מַפְרִיס פַּרְסָה הוּא וְשֹׁסַע שֶׁסַע פַּרְסָה",
         "ואלכ'נזיר פאנה מצ'לף בצ'לף. וצ'לפה מפרק תפריקא",
         "And the swine — for it is hoofed with a hoof, and its hoof is divided in a division,"),
        ("וְהוּא גֵּרָה לֹא-יִגָּר טָמֵא הוּא לָכֶם",
         "והו אגתראר לא יגתר. פהו נגס לכם",
         "yet it is one that does not chew cud; it is impure for you."),
    ],
    8: [
        ("מִבְּשָׂרָם לֹא תֹאכֵלוּ וּבְנִבְלָתָם לֹא תִגָּעוּ טְמֵאִים הֵם לָכֶם",
         "מן לחומהא לא תאכלו. ובנבאילהא לא תדנו. כד'אך הי נגסה לכם",
         "Of their flesh you shall not eat, and to their carcasses you shall not approach; thus they are impure for you."),
    ],
    9: [
        ("אֶת-זֶה תֹּאכְלוּ מִכֹּל אֲשֶׁר בַּמָּיִם",
         "הד'א מא יגוז אן תאכלוה. מן גמיע מא פי אלמא",
         "This is what it is permitted that you eat from all that is in the water:"),
        ("כֹּל אֲשֶׁר-לוֹ סְנַפִּיר וְקַשְׂקֶשֶׂת בַּמַּיִם בַּיַּמִּים וּבַנְּחָלִים--אֹתָם תֹּאכֵלוּ",
         "כל מא לה אגנחה ופלוס פי אלמא. פי אלבחאר ואלאודיה פכלוה",
         "everything that has fins and scales in the water, in the seas and the wadis — eat it."),
    ],
    10: [
        ("וְכֹל אֲשֶׁר אֵין-לוֹ סְנַפִּיר וְקַשְׂקֶשֶׂת בַּיַּמִּים וּבַנְּחָלִים",
         "וכל מא ליס לה אגנחה ופלוס. פי אלבחאר ואלאודיה",
         "But everything that has no fins and scales, in the seas and the wadis,"),
        ("מִכֹּל שֶׁרֶץ הַמַּיִם וּמִכֹּל נֶפֶשׁ הַחַיָּה אֲשֶׁר בַּמָּיִם--שֶׁקֶץ הֵם לָכֶם",
         "מן גמיע דביב אלמא. וגמיע אלחיואן אלד'י פי אלמא. פהו רגס לכם",
         "from all the creeping things of the water, and all the animals that are in the water — it is an abomination for you."),
    ],
    11: [
        ("וְשֶׁקֶץ יִהְיוּ לָכֶם מִבְּשָׂרָם לֹא תֹאכֵלוּ",
         "וכונהא ארגאס לכם. מן לחומהא לא תאכלו",
         "Their being abominations for you — of their flesh you shall not eat,"),
        ("וְאֶת-נִבְלָתָם תְּשַׁקֵּצוּ",
         "ונבאילהא תרגסו",
         "and their carcasses you shall treat as abominations."),
    ],
    12: [
        ("כֹּל אֲשֶׁר אֵין-לוֹ סְנַפִּיר וְקַשְׂקֶשֶׂת בַּמָּיִם--שֶׁקֶץ הוּא לָכֶם",
         "כד'אך כל מא ליס לה. אגנחה ופלוס פי אלמא. פהו רגס לכם",
         "Thus everything that has no fins and scales in the water — it is an abomination for you."),
    ],
    13: [
        ("וְאֶת-אֵלֶּה תְּשַׁקְּצוּ מִן-הָעוֹף לֹא יֵאָכְלוּ שֶׁקֶץ הֵם",
         "והד'א מא תרגסו מן אלטאיר. לא יוכלו אנהא ארגאס",
         "And these are what you shall treat as abominations from the birds — they shall not be eaten, for they are abominations:"),
        ("אֶת-הַנֶּשֶׁר וְאֶת-הַפֶּרֶס וְאֵת הָעָזְנִיָּה",
         "אלנסר ואלעקאב ואלענקא",
         "the vulture, and the eagle, and the 'anqah."),
    ],
    14: [
        ("וְאֶת-הַדָּאָה--וְאֶת-הָאַיָּה לְמִינָהּ",
         "ואלחדא. ואלצדא באצנאפהא",
         "And the kite, and the buzzard according to its kinds."),
    ],
    15: [
        ("אֵת כָּל-עֹרֵב לְמִינוֹ",
         "וגמיע אלג'ראביב באצנאפהא",
         "And all the ravens according to their kinds."),
    ],
    16: [
        ("וְאֵת בַּת הַיַּעֲנָה וְאֶת-הַתַּחְמָס וְאֶת-הַשָּׁחַף וְאֶת-הַנֵּץ לְמִינֵהוּ",
         "ואלנעאמה. ואלכ'טאף ואלסאף. ואלבאז לאצנאפה",
         "And the ostrich, and the swift and the 'saf', and the hawk according to its kinds."),
    ],
    17: [
        ("וְאֶת-הַכּוֹס וְאֶת-הַשָּׁלָךְ וְאֶת-הַיַּנְשׁוּף",
         "ואלבום ואלזמג ואלבאשק",
         "And the owl, and the cormorant, and the eagle-owl."),
    ],
    18: [
        ("וְאֶת-הַתִּנְשֶׁמֶת וְאֶת-הַקָּאָת וְאֶת-הָרָחָם",
         "ואלשאהין ואלקו ואלרכ'ם",
         "And the falcon, and the pelican, and the vulture."),
    ],
    19: [
        ("וְאֵת הַחֲסִידָה הָאֲנָפָה לְמִינָהּ וְאֶת-הַדּוּכִיפַת וְאֶת-הָעֲטַלֵּף",
         "ואלצקר ואלבג'בג'ה באצנאפהא. ואלהדהד ואלכ'פאש",
         "And the saker and the parrot according to its kinds, and the hoopoe and the bat."),
    ],
    20: [
        ("כֹּל שֶׁרֶץ הָעוֹף הַהֹלֵךְ עַל-אַרְבַּע--שֶׁקֶץ הוּא לָכֶם",
         "וגמיע דביב אלטאיר. אלסאלך עלי' ארבע. רגס הו לכם",
         "And all the creeping things of the birds that walk on four — it is an abomination for you."),
    ],
    21: [
        ("אַךְ אֶת-זֶה תֹּאכְלוּ מִכֹּל שֶׁרֶץ הָעוֹף הַהֹלֵךְ עַל-אַרְבַּע",
         "והד'א מא יגוז אן תאכלוה. מן גמיע דביב אלטאיר. אלסאלך עלי' ארבע",
         "But this is what it is permitted that you eat from all the creeping things of the birds that walk on four:"),
        ("אֲשֶׁר-לא (לוֹ) כְרָעַיִם מִמַּעַל לְרַגְלָיו לְנַתֵּר בָּהֵן עַל-הָאָרֶץ",
         "מא לה כראעין פוק רגליה. לית'ב בהמא עלי' אלארץ'",
         "whatever has two jumping-legs above its feet, with which to leap upon the earth."),
    ],
    22: [
        ("אֶת-אֵלֶּה מֵהֶם תֹּאכֵלוּ",
         "הד'א מא תאכלוה מנהא",
         "These are what you may eat from them:"),
        ("אֶת-הָאַרְבֶּה לְמִינוֹ וְאֶת-הַסָּלְעָם לְמִינֵהוּ וְאֶת-הַחַרְגֹּל לְמִינֵהוּ וְאֶת-הֶחָגָב לְמִינֵהוּ",
         "אלגראד וצנופה. ואלדבא וצנופה. ואלחרגל וצנופה. ואלגנדב וצנופה",
         "the locust and its kinds, and the duba and its kinds, and the harjal and its kinds, and the grasshopper and its kinds."),
    ],
    23: [
        ("וְכֹל שֶׁרֶץ הָעוֹף אֲשֶׁר-לוֹ אַרְבַּע רַגְלָיִם--שֶׁקֶץ הוּא לָכֶם",
         "וסאיר דביב אלטאיר. אלד'י לה ארבע ארגל. פהו רגס לכם",
         "And the rest of the creeping things of the birds that have four legs — it is an abomination for you."),
    ],
    24: [
        ("וּלְאֵלֶּה תִּטַּמָּאוּ כָּל-הַנֹּגֵעַ בְּנִבְלָתָם יִטְמָא עַד-הָעָרֶב",
         "ומן הד'ה פאנגסו. כל מן דנא בנבאילהם. יג'סל ת'יאבה וינגס אלי' אלמגיב",
         "And by these you shall become impure: every one who approaches their carcasses shall wash his garments and be impure until the setting."),
    ],
    25: [
        ("וְכָל-הַנֹּשֵׂא מִנִּבְלָתָם--יְכַבֵּס בְּגָדָיו וְטָמֵא עַד-הָעָרֶב",
         "וכל מן חמל מן נבאילהם. גסל ת'יאבה וינגס אלי' אלמג'יב",
         "And every one who carries from their carcasses shall wash his garments and be impure until the setting."),
    ],
    26: [
        ("לְכָל-הַבְּהֵמָה אֲשֶׁר הִוא מַפְרֶסֶת פַּרְסָה וְשֶׁסַע אֵינֶנָּה שֹׁסַעַת וְגֵרָה אֵינֶנָּה מַעֲלָה--טְמֵאִים הֵם לָכֶם",
         "מן גמיע אלבהאים. אלתי הי מצ'לפה בצ'לף. ותפריק ליסהא מפרקה. ואגתראר ליסהא מצעדה. פהי נגסה לכם",
         "From all the beasts that are hoofed with a hoof, yet division is not in them as divided, and cud-chewing is not in them as bringing up — they are impure for you;"),
        ("כָּל-הַנֹּגֵעַ בָּהֶם יִטְמָא",
         "כל מן דנא בהא ינגס",
         "every one who approaches them shall be impure."),
    ],
    27: [
        ("וְכֹל הוֹלֵךְ עַל-כַּפָּיו בְּכָל-הַחַיָּה הַהֹלֶכֶת עַל-אַרְבַּע--טְמֵאִים הֵם לָכֶם",
         "וכל סאלך עלי' כפיה. מן גמיע אלוחש אלסאלך עלי' ארבע. פהו נגס לכם",
         "And every one that walks on its paws, from all the wild creatures that walk on four — it is impure for you;"),
        ("כָּל-הַנֹּגֵעַ בְּנִבְלָתָם יִטְמָא עַד-הָעָרֶב",
         "כל מן דנא בנבאילהם ינגס אלי' אלמג'יב",
         "every one who approaches their carcasses shall be impure until the setting."),
    ],
    28: [
        ("וְהַנֹּשֵׂא אֶת-נִבְלָתָם--יְכַבֵּס בְּגָדָיו וְטָמֵא עַד-הָעָרֶב",
         "ומן חמל מן נבאילהם. יג'סל ת'יאבה וינגס אלי' אלמג'יב",
         "And whoever carries from their carcasses shall wash his garments and be impure until the setting."),
        ("טְמֵאִים הֵמָּה לָכֶם",
         "כד'אך הי אנגאס לכם",
         "Thus they are impurities for you."),
    ],
    29: [
        ("וְזֶה לָכֶם הַטָּמֵא בַּשֶּׁרֶץ הַשֹּׁרֵץ עַל-הָאָרֶץ",
         "והד'א לכם אלנגס. מן אלדביב אלדאב עלי' אלארץ'",
         "And this is what is impure for you from the creeping things that creep upon the earth:"),
        ("הַחֹלֶד וְהָעַכְבָּר וְהַצָּב לְמִינֵהוּ",
         "אלכ'לד ואלפאר ואלצ'ב ואצנאפה",
         "the mole, and the mouse, and the spiny lizard according to its kinds."),
    ],
    30: [
        ("וְהָאֲנָקָה וְהַכֹּחַ וְהַלְּטָאָה וְהַחֹמֶט וְהַתִּנְשָׁמֶת",
         "ואלורל ואלחרדון ואלעצ'איה ואלחרבא ואלסמברץ",
         "And the monitor lizard, and the gecko, and the chameleon, and the agama, and the skink."),
    ],
    31: [
        ("אֵלֶּה הַטְּמֵאִים לָכֶם בְּכָל-הַשָּׁרֶץ",
         "הד'א אלנגסה לכם מן גמיע אלדביב",
         "These are the impure for you from all the creeping things;"),
        ("כָּל-הַנֹּגֵעַ בָּהֶם בְּמֹתָם יִטְמָא עַד-הָעָרֶב",
         "כל מן דנא בהא. פי חאל מותהא ינגס אלי' אלמג'יב",
         "every one who approaches them at the time of their death shall be impure until the setting."),
    ],
    32: [
        ("וְכֹל אֲשֶׁר-יִפֹּל-עָלָיו מֵהֶם בְּמֹתָם יִטְמָא",
         "וכל מן וקע עלי'ה מנהא בעד מותהא ינגס",
         "And everything upon which any of them falls after their death shall be impure —"),
        ("מִכָּל-כְּלִי-עֵץ אוֹ בֶגֶד אוֹ-עוֹר אוֹ שָׂק כָּל-כְּלִי אֲשֶׁר-יֵעָשֶׂה מְלָאכָה בָּהֶם",
         "מן גמיע אניה' אלכ'שב או ת'וב או גלד או מסח. וכל אניה יעמל בהא צנאעה",
         "from any vessel of wood, or cloth, or leather, or sacking; and every vessel with which work is done"),
        ("בַּמַּיִם יוּבָא וְטָמֵא עַד-הָעֶרֶב וְטָהֵר",
         "ידכ'ל פי אלמא. וינגס אלי' אלמג'יב ויטהר",
         "shall be brought into the water, and shall be impure until the setting, and then it shall be pure."),
    ],
    33: [
        ("וְכָל-כְּלִי-חֶרֶשׂ--אֲשֶׁר-יִפֹּל מֵהֶם אֶל-תּוֹכוֹ",
         "וכל אנא כ'זף. יקע מנהא שיא אלי' דאכ'לה",
         "And any earthen vessel into which anything of them falls —"),
        ("כֹּל אֲשֶׁר בְּתוֹכוֹ יִטְמָא וְאֹתוֹ תִשְׁבֹּרוּ",
         "כל מא פי דאכ'לה. ינגס ואייאה פאכסרו",
         "everything within it shall be impure, and it itself you shall break."),
    ],
    34: [
        ("מִכָּל-הָאֹכֶל אֲשֶׁר יֵאָכֵל אֲשֶׁר יָבוֹא עָלָיו מַיִם--יִטְמָא",
         "מן גמיע אלטעאם אלד'י יוכל. ממא ידכ'לה אלמא ינגס",
         "From all food that is eaten, if water enters it, it shall be impure;"),
        ("וְכָל-מַשְׁקֶה אֲשֶׁר יִשָּׁתֶה בְּכָל-כְּלִי יִטְמָא",
         "וגמיע אלשראב אלד'י ישרב. פי כל אנא ינגס",
         "and all drink that is drunk, in any vessel, shall be impure."),
    ],
    35: [
        ("וְכֹל אֲשֶׁר-יִפֹּל מִנִּבְלָתָם עָלָיו יִטְמָא",
         "וכל מא וקע מן נבאילהם עלי'ה ינגס",
         "And everything upon which any of their carcasses falls shall be impure —"),
        ("תַּנּוּר וְכִירַיִם יֻתָּץ טְמֵאִים הֵם וּטְמֵאִים יִהְיוּ לָכֶם",
         "מן תנור ומסתוקד. פאנקצ'והמא לאנהא נגסה. וכד'אך הי לכם אנגאס",
         "whether an oven or a stove, demolish them both, for they are impure; and thus they are impurities for you."),
    ],
    36: [
        ("אַךְ מַעְיָן וּבוֹר מִקְוֵה-מַיִם יִהְיֶה טָהוֹר",
         "אמא אלמעין ואלביר. ומלאם אלמא פיכון טאהרא",
         "But a spring and a well, and a gathering of water, shall remain pure;"),
        ("וְנֹגֵעַ בְּנִבְלָתָם יִטְמָא",
         "ומן דנא בנבאילהא פיהא ינגס",
         "yet whoever approaches their carcasses in it shall be impure."),
    ],
    37: [
        ("וְכִי יִפֹּל מִנִּבְלָתָם עַל-כָּל-זֶרַע זֵרוּעַ אֲשֶׁר יִזָּרֵעַ--טָהוֹר הוּא",
         "ואן וקע מן נבאילהא. עלי' שי מן אלנבאת ואלחב אלד'י יזרע. פהו טאהר",
         "And if any of their carcasses falls upon any of the vegetation and grain that is sown, it is pure."),
    ],
    38: [
        ("וְכִי יֻתַּן-מַיִם עַל-זֶרַע וְנָפַל מִנִּבְלָתָם עָלָיו--טָמֵא הוּא לָכֶם",
         "פאן געל מא עלי'הא. ווקע מן נבאילהא עלי'ה. פהו נגס לכם",
         "But if water has been placed upon it and then any of their carcasses falls upon it, it is impure for you."),
    ],
    39: [
        ("וְכִי יָמוּת מִן-הַבְּהֵמָה אֲשֶׁר-הִיא לָכֶם לְאָכְלָה",
         "ואד'א מאת מן אלחיואן. אלד'י הו טלק לכם אן תאכלוה",
         "And when there dies from the animals which it is permitted for you to eat,"),
        ("הַנֹּגֵעַ בְּנִבְלָתָהּ יִטְמָא עַד-הָעָרֶב",
         "מן דנא בנבילתה פינגס אלי' אלמג'יב",
         "whoever approaches its carcass shall be impure until the setting."),
    ],
    40: [
        ("וְהָאֹכֵל מִנִּבְלָתָהּ--יְכַבֵּס בְּגָדָיו וְטָמֵא עַד-הָעָרֶב",
         "ומן אכל מנהא. יג'סל ת'יאבה וינגס אלי' אלמג'יב",
         "And whoever eats from it shall wash his garments and be impure until the setting;"),
        ("וְהַנֹּשֵׂא אֶת-נִבְלָתָהּ--יְכַבֵּס בְּגָדָיו וְטָמֵא עַד-הָעָרֶב",
         "ומן חמל מנהא. יג'סל ת'יאבה וינגס אלי' אלמג'יב",
         "and whoever carries from it shall wash his garments and be impure until the setting."),
    ],
    41: [
        ("וְכָל-הַשֶּׁרֶץ הַשֹּׁרֵץ עַל-הָאָרֶץ--שֶׁקֶץ הוּא לֹא יֵאָכֵל",
         "וגמיע אלדביב אלדאב עלי' אלארץ'. פהו רגס לא יוכל",
         "And all the creeping things that creep upon the earth — it is an abomination, it shall not be eaten."),
    ],
    42: [
        ("כֹּל הוֹלֵךְ עַל-גָּחוֹן וְכֹל הוֹלֵךְ עַל-אַרְבַּע עַד כָּל-מַרְבֵּה רַגְלַיִם",
         "וכל סאלך עלי' צדרה. וכל סאלך עלי' ארבע. למא כת'רה' ארגלה",
         "Every one that walks on its belly, and every one that walks on four, and whatever has many legs,"),
        ("לְכָל-הַשֶּׁרֶץ הַשֹּׁרֵץ עַל-הָאָרֶץ--לֹא תֹאכְלוּם כִּי-שֶׁקֶץ הֵם",
         "מן גמיע אלדביב אלדאב עלי' אלארץ'. לא תאכלונהם פאנהם ארגאס",
         "from all the creeping things that creep upon the earth — do not eat them, for they are abominations."),
    ],
    43: [
        ("אַל-תְּשַׁקְּצוּ אֶת-נַפְשֹׁתֵיכֶם בְּכָל-הַשֶּׁרֶץ הַשֹּׁרֵץ",
         "ולא תרגסו אנפסכם. בשי מן אלדביב אלדאב",
         "And do not make your souls abominable with anything of the creeping things that creep,"),
        ("וְלֹא תִטַּמְּאוּ בָּהֶם וְנִטְמֵתֶם בָּם",
         "ולא תתנגסו בהם. פתעצוני בד'אלך",
         "and do not defile yourselves with them, lest you disobey Me thereby."),
    ],
    44: [
        ("כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם וְהִתְקַדִּשְׁתֶּם וִהְיִיתֶם קְדֹשִׁים כִּי קָדוֹשׁ אָנִי",
         "לאני אללה רבכם. פתקדסו וכונו מקדסין. פאני קדוס",
         "For I am God your Lord — sanctify yourselves and be holy, for I am holy;"),
        ("וְלֹא תְטַמְּאוּ אֶת-נַפְשֹׁתֵיכֶם בְּכָל-הַשֶּׁרֶץ הָרֹמֵשׂ עַל-הָאָרֶץ",
         "ולא תנגסו אנפסכם. בשי מן אלדביב אלדאב עלי' אלארץ'",
         "and do not defile your souls with anything of the creeping things that creep upon the earth."),
    ],
    45: [
        ("כִּי אֲנִי יְהוָה הַמַּעֲלֶה אֶתְכֶם מֵאֶרֶץ מִצְרַיִם לִהְיֹת לָכֶם לֵאלֹהִים",
         "לאני אללה. אלמצעדכם מן בלד מצר. לאכון לכם אלאהא",
         "For I am God, who brought you up from the land of Egypt, to be your God —"),
        ("וִהְיִיתֶם קְדֹשִׁים כִּי קָדוֹשׁ אָנִי",
         "פכונו מקדסין. לאני אלקדוס",
         "so be holy, for I am the Holy One."),
    ],
    46: [
        ("זֹאת תּוֹרַת הַבְּהֵמָה וְהָעוֹף וְכֹל נֶפֶשׁ הַחַיָּה הָרֹמֶשֶׂת בַּמָּיִם",
         "הד'א שריעה' אלבהאים ואלטאיר. וגמיע נפוס אלחייה. אלדאבה פי אלמא",
         "This is the law of the beasts and the birds, and all the living souls that creep in the water,"),
        ("וּלְכָל-נֶפֶשׁ הַשֹּׁרֶצֶת עַל-הָאָרֶץ",
         "וסאיר אלנפוס אלדאבה עלי' אלארץ'",
         "and the rest of the souls that creep upon the earth:"),
    ],
    47: [
        ("לְהַבְדִּיל בֵּין הַטָּמֵא וּבֵין הַטָּהֹר",
         "תפרז. בין אלנגס ואלטאהר",
         "that you separate between the impure and the pure,"),
        ("וּבֵין הַחַיָּה הַנֶּאֱכֶלֶת וּבֵין הַחַיָּה אֲשֶׁר לֹא תֵאָכֵל",
         "ובין אלחיואן אלד'י יוכל. ואלד'י לא יוכל",
         "and between the animal that may be eaten and that which may not be eaten.\""),
    ],
}
