"""Hand-authored alignment triples for Vayikra chapter 14."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("זֹאת תִּהְיֶה תּוֹרַת הַמְּצֹרָע בְּיוֹם טָהֳרָתוֹ",
         "הד'א תכון שריעה' אלאברץ. פי וקת טהרה",
         "This shall be the law of the one afflicted with leprosy, at the time of his purification —"),
        ("וְהוּבָא אֶל-הַכֹּהֵן",
         "אן יותא בכ'ברה אלי' אלאמאם",
         "that report of him be brought to the imām."),
    ],
    3: [
        ("וְיָצָא הַכֹּהֵן אֶל-מִחוּץ לַמַּחֲנֶה וְרָאָה הַכֹּהֵן",
         "ויכ'רג אלאמאם אלי' כ'ארג אלעסכר. פאד'א ראי'",
         "And the imām shall go out to outside the camp; and if he sees"),
        ("וְהִנֵּה נִרְפָּא נֶגַע-הַצָּרַעַת מִן-הַצָּרוּעַ",
         "אן אלאברץ קד אשפא מן בלא אלברץ. אמר פיה במא יגב",
         "that the one afflicted with leprosy has recovered from the affliction of the leprosy, he shall ordain for him what is required."),
    ],
    4: [
        ("וְצִוָּה הַכֹּהֵן וְלָקַח לַמִּטַּהֵר שְׁתֵּי-צִפֳּרִים חַיּוֹת טְהֹרוֹת וְעֵץ אֶרֶז וּשְׁנִי תוֹלַעַת וְאֵזֹב",
         "פיאמר אלאמאם. ויאכ'ד' לאלמתטהר. עצפורין טאהרין. ועוד ארז. וחריר קרמז וצעתר",
         "Then the imām shall give the order, and there shall be taken for the one being purified two clean sparrows, and a rod of cedar, and crimson silk, and hyssop."),
    ],
    5: [
        ("וְצִוָּה הַכֹּהֵן וְשָׁחַט אֶת-הַצִּפּוֹר הָאֶחָת--אֶל-כְּלִי-חֶרֶשׂ עַל-מַיִם חַיִּים",
         "ת'ם יאמר אלאמאם בד'בח אחדהמא. פי אנא מן כ'זף עלי' מא מן נביע",
         "Then the imām shall give the order to slaughter one of them, in a clay vessel over water from a spring."),
    ],
    6: [
        ("אֶת-הַצִּפֹּר הַחַיָּה יִקַּח אֹתָהּ וְאֶת-עֵץ הָאֶרֶז וְאֶת-שְׁנִי הַתּוֹלַעַת וְאֶת-הָאֵזֹב",
         "וליאכ'ד' אלעצפור אלחי. ואלעוד אלארז. וחריר אלקרמז ואלצעתר",
         "And he shall take the living sparrow, and the cedar rod, and the crimson silk and the hyssop,"),
        ("וְטָבַל אוֹתָם וְאֵת הַצִּפֹּר הַחַיָּה בְּדַם הַצִּפֹּר הַשְּׁחֻטָה עַל הַמַּיִם הַחַיִּים",
         "ויג'מס ד'אלך מע אלעצפור אלחי. בדם אלעצפור אלמד'בוח. עלי' אלמא אלד'י מן נביע",
         "and shall dip them — together with the living sparrow — in the blood of the slaughtered sparrow, over the water from a spring."),
    ],
    7: [
        ("וְהִזָּה עַל הַמִּטַּהֵר מִן-הַצָּרַעַת--שֶׁבַע פְּעָמִים וְטִהֲרוֹ",
         "וינצ'ח עלי' אלמתטהר. מן אלברץ סבע מראר. ויטהרה",
         "And he shall sprinkle upon the one being purified from the leprosy seven times, and shall declare him pure;"),
        ("וְשִׁלַּח אֶת-הַצִּפֹּר הַחַיָּה עַל-פְּנֵי הַשָּׂדֶה",
         "ויטלק אלעצפור אלחי עלי' וגה אלצחרי'",
         "and he shall release the living sparrow upon the face of the wilderness."),
    ],
    8: [
        ("וְכִבֶּס הַמִּטַּהֵר אֶת-בְּגָדָיו וְגִלַּח אֶת-כָּל-שְׂעָרוֹ וְרָחַץ בַּמַּיִם וְטָהֵר",
         "ת'ם יג'סל אלמתטהר ת'יאבה ויחלק גמיע שערה. וירחץ' באלמא ויטהר",
         "Then the one being purified shall wash his garments and shave off all his hair, and shall bathe in water and be pure;"),
        ("וְאַחַר יָבוֹא אֶל-הַמַּחֲנֶה וְיָשַׁב מִחוּץ לְאָהֳלוֹ שִׁבְעַת יָמִים",
         "ובעד ד'אלך ידכ'ל אלי' אלעסכר. ויקים כ'ארג מנזלה סבעה' אייאם",
         "and after that he shall enter into the camp, and shall remain outside his dwelling for seven days."),
    ],
    9: [
        ("וְהָיָה בַיּוֹם הַשְּׁבִיעִי יְגַלַּח אֶת-כָּל-שְׂעָרוֹ אֶת-רֹאשׁוֹ וְאֶת-זְקָנוֹ וְאֵת גַּבֹּת עֵינָיו וְאֶת-כָּל-שְׂעָרוֹ יְגַלֵּחַ",
         "פאד'א כאן פי אליום אלסאבע יחלק גמיע שערה. ראסה ולחיתה וחואגב עיניה. מע סאיר שערה",
         "And on the seventh day he shall shave all the hair of his head and his beard and his eyebrows, together with the rest of his hair;"),
        ("וְכִבֶּס אֶת-בְּגָדָיו וְרָחַץ אֶת-בְּשָׂרוֹ בַּמַּיִם--וְטָהֵר",
         "ויג'סל ת'יאבה. וירחץ' בדנה באלמא ויטהר",
         "and he shall wash his garments, and shall bathe his body in water and be pure."),
    ],
    10: [
        ("וּבַיּוֹם הַשְּׁמִינִי יִקַּח שְׁנֵי-כְבָשִׂים תְּמִימִם וְכַבְשָׂה אַחַת בַּת-שְׁנָתָהּ תְּמִימָה",
         "ופי אליום אלתאמן יקדם כ'רופין צחיחין. ורכלה אבנה' סנתהא צחיחה",
         "And on the eighth day he shall bring forward two sound rams, and one sound ewe-lamb in its first year,"),
        ("וּשְׁלֹשָׁה עֶשְׂרֹנִים סֹלֶת מִנְחָה בְּלוּלָה בַשֶּׁמֶן וְלֹג אֶחָד שָׁמֶן",
         "ותלאתה' עשור סמד. הדייה מלתותה בדהן. ולג דהן",
         "and three tenths of fine flour as an offering mixed with oil, and a log of oil."),
    ],
    11: [
        ("וְהֶעֱמִיד הַכֹּהֵן הַמְטַהֵר אֵת הָאִישׁ הַמִּטַּהֵר--וְאֹתָם לִפְנֵי יְהוָה פֶּתַח אֹהֶל מוֹעֵד",
         "ויוקף אלאמאם אלמטהר. אלרגל אלמתטהר והם. בין ידי אללה. ענד באב כ'בא אלמחצ'ר",
         "And the purifying imām shall station the purified man — and them — before God, at the entrance of the tent of the assembly."),
    ],
    12: [
        ("וְלָקַח הַכֹּהֵן אֶת-הַכֶּבֶשׂ הָאֶחָד וְהִקְרִיב אֹתוֹ לְאָשָׁם--וְאֶת-לֹג הַשָּׁמֶן",
         "ויאכ'ד' אלאמאם אחד אלכ'רופין. ליקרבה ען אלאתם ואלג אלדהן",
         "And the imām shall take one of the rams, to present it for the guilt-offering, along with the log of oil;"),
        ("וְהֵנִיף אֹתָם תְּנוּפָה לִפְנֵי יְהוָה",
         "ויחרכהא תחריכא בין ידי אללה",
         "and he shall wave them as a waving before God."),
    ],
    13: [
        ("וְשָׁחַט אֶת-הַכֶּבֶשׂ בִּמְקוֹם אֲשֶׁר יִשְׁחַט אֶת-הַחַטָּאת וְאֶת-הָעֹלָה--בִּמְקוֹם הַקֹּדֶשׁ",
         "ת'ם יד'בחה. פי אלמוצ'ע אלד'י יד'בח אלד'כוה. ואלצעידה פי מוצ'ע אלקד'ס",
         "Then he shall slaughter it in the place where the purification-offering and the ascending-offering are slaughtered — in the holy place —"),
        ("כִּי כַּחַטָּאת הָאָשָׁם הוּא לַכֹּהֵן--קֹדֶשׁ קָדָשִׁים הוּא",
         "לאן קרבאן אלאת'ם. הו כאלד'כוה לאלאמאם. מן כ'ואץ אלאקדאס",
         "for the guilt-offering is like the purification-offering for the imām; it is among the choicest of the holy things."),
    ],
    14: [
        ("וְלָקַח הַכֹּהֵן מִדַּם הָאָשָׁם וְנָתַן הַכֹּהֵן עַל-תְּנוּךְ אֹזֶן הַמִּטַּהֵר הַיְמָנִית",
         "ת'ם יאכ'ד' מן דמה. ויגעל עלי' שחמה' אד'ן אלמתטהר אלימני",
         "Then he shall take some of its blood and place it on the cartilage of the earlobe of the one being purified — the right one —"),
        ("וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית",
         "ועלי' אבהאם ידה אלימני. ואבהאם רגלה אלימני",
         "and on the thumb of his right hand, and on the thumb of his right foot."),
    ],
    15: [
        ("וְלָקַח הַכֹּהֵן מִלֹּג הַשָּׁמֶן וְיָצַק עַל-כַּף הַכֹּהֵן הַשְּׂמָאלִית",
         "ויאכ'ד' אלאמאם מן לג אלדהן ויצב עלי' כפה אליסרי",
         "And the imām shall take from the log of oil and pour it into his left palm."),
    ],
    16: [
        ("וְטָבַל הַכֹּהֵן אֶת-אֶצְבָּעוֹ הַיְמָנִית מִן-הַשֶּׁמֶן אֲשֶׁר עַל-כַּפּוֹ הַשְּׂמָאלִית",
         "ויג'מס אצבעה אלימני. מן אלד'הן אלד'י עלי' ידה אליסרי",
         "And he shall dip his right finger from the oil that is on his left hand,"),
        ("וְהִזָּה מִן-הַשֶּׁמֶן בְּאֶצְבָּעוֹ שֶׁבַע פְּעָמִים לִפְנֵי יְהוָה",
         "וינצ'ח מנה באצבעה. סבע מראר בין ידי אללה",
         "and shall sprinkle from it with his finger seven times before God."),
    ],
    17: [
        ("וּמִיֶּתֶר הַשֶּׁמֶן אֲשֶׁר עַל-כַּפּוֹ יִתֵּן הַכֹּהֵן עַל-תְּנוּךְ אֹזֶן הַמִּטַּהֵר הַיְמָנִית וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית--עַל דַּם הָאָשָׁם",
         "ת'ם יצ'ע מן באקיה. עלי' שחמה' אד'ן אלמתטהר אלימני. ועלי' אבהאם ידה אלימני. ואבהאם רגלה אלימני. עלי' דם קרבאן אלאת'ם",
         "Then he shall place some of the remainder upon the cartilage of the earlobe of the one being purified — the right one — and on the thumb of his right hand, and on the thumb of his right foot, upon the blood of the guilt-offering."),
    ],
    18: [
        ("וְהַנּוֹתָר בַּשֶּׁמֶן אֲשֶׁר עַל-כַּף הַכֹּהֵן יִתֵּן עַל-רֹאשׁ הַמִּטַּהֵר",
         "ואלפאצ'ל מנה. יצ'עה עלי' ראס אלמתטהר",
         "And what remains of it he shall place upon the head of the one being purified,"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן לִפְנֵי יְהוָה",
         "ויסתג'פר ענה בין ידי אללה",
         "and shall seek forgiveness for him before God."),
    ],
    19: [
        ("וְעָשָׂה הַכֹּהֵן אֶת-הַחַטָּאת וְכִפֶּר עַל-הַמִּטַּהֵר מִטֻּמְאָתוֹ",
         "ת'ם יעמל אלאמאם אלד'כוה. ויסתג'פר ען אלמתטהר מן נגאסתה",
         "Then the imām shall perform the purification-offering, and shall seek forgiveness for the one being purified from his impurity;"),
        ("וְאַחַר יִשְׁחַט אֶת-הָעֹלָה",
         "ובעד ד'אלך יד'בח אלצעידה",
         "and after that he shall slaughter the ascending-offering."),
    ],
    20: [
        ("וְהֶעֱלָה הַכֹּהֵן אֶת-הָעֹלָה וְאֶת-הַמִּנְחָה הַמִּזְבֵּחָה",
         "ת'ם יצעד אלצעידה ואלהדייה עלי' אלמד'בח",
         "Then he shall cause the ascending-offering and the gift-offering to ascend upon the altar;"),
        ("וְכִפֶּר עָלָיו הַכֹּהֵן וְטָהֵר",
         "ויסתג'פר ענה אלאמאם ויטהר",
         "and the imām shall seek forgiveness for him, and he shall be pure."),
    ],
    21: [
        ("וְאִם-דַּל הוּא וְאֵין יָדוֹ מַשֶּׂגֶת",
         "ואן כאן פקירא. לם תנאל ידה ד'אלך",
         "And if he is poor, his hand not reaching to that,"),
        ("וְלָקַח כֶּבֶשׂ אֶחָד אָשָׁם לִתְנוּפָה לְכַפֵּר עָלָיו",
         "פליקרב כ'רופא ואחדא קרבאן אלאת'ם. לאלתחריך ליסתג'פר ענה",
         "then let him bring one ram as the guilt-offering, for the waving, that forgiveness be sought for him;"),
        ("וְעִשָּׂרוֹן סֹלֶת אֶחָד בָּלוּל בַּשֶּׁמֶן לְמִנְחָה--וְלֹג שָׁמֶן",
         "ועשר מן סמד מלתות בד'הן. הדייה ולג דהן",
         "and one tenth of fine flour mixed with oil as a gift-offering, and a log of oil."),
    ],
    22: [
        ("וּשְׁתֵּי תֹרִים אוֹ שְׁנֵי בְּנֵי יוֹנָה אֲשֶׁר תַּשִּׂיג יָדוֹ",
         "ושפנינין. או פרכ'י חמאם. עלי' מא תנאל ידה",
         "And two turtle-doves or two young pigeons, according to what his hand can reach —"),
        ("וְהָיָה אֶחָד חַטָּאת וְהָאֶחָד עֹלָה",
         "פיכון אחדהמא ד'כוה. ואלאכ'ר צעידה",
         "one of them shall be a purification-offering, and the other an ascending-offering."),
    ],
    23: [
        ("וְהֵבִיא אֹתָם בַּיּוֹם הַשְּׁמִינִי לְטָהֳרָתוֹ--אֶל-הַכֹּהֵן אֶל-פֶּתַח אֹהֶל-מוֹעֵד לִפְנֵי יְהוָה",
         "פליאת בהמא. פי אליום אלת'אמן. מן אוול טהרה אלי' אלאמאם. אלי' באב כ'בא אלמחצ'ר בין ידי אללה",
         "He shall bring them, on the eighth day from the beginning of his purification, to the imām, to the entrance of the tent of the assembly, before God."),
    ],
    24: [
        ("וְלָקַח הַכֹּהֵן אֶת-כֶּבֶשׂ הָאָשָׁם וְאֶת-לֹג הַשָּׁמֶן",
         "ויאכ'ד' אלאמאם. כ'רוף קרבאן אלאת'ם ואללג אלדהן",
         "And the imām shall take the ram of the guilt-offering and the log of oil,"),
        ("וְהֵנִיף אֹתָם הַכֹּהֵן תְּנוּפָה לִפְנֵי יְהוָה",
         "ויחרכהא אלאמאם תחריכא בין ידי אללה",
         "and the imām shall wave them as a waving before God."),
    ],
    25: [
        ("וְשָׁחַט אֶת-כֶּבֶשׂ הָאָשָׁם וְלָקַח הַכֹּהֵן מִדַּם הָאָשָׁם וְנָתַן עַל-תְּנוּךְ אֹזֶן-הַמִּטַּהֵר הַיְמָנִית",
         "ת'ם יד'בחה. ויאכ'ד מן דמה ויצע. עלי' שחמה' אד'ן אלמתטהר אלימני",
         "Then he shall slaughter it; and he shall take some of its blood and place it on the cartilage of the earlobe of the one being purified — the right one —"),
        ("וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית",
         "ועלי' אבהאם רגלה אלימני",
         "and on the thumb of his right hand, and on the thumb of his right foot."),
    ],
    26: [
        ("וּמִן-הַשֶּׁמֶן יִצֹק הַכֹּהֵן עַל-כַּף הַכֹּהֵן הַשְּׂמָאלִית",
         "ומן אלדהן יצב . פי כפה אליסרי",
         "And from the oil the imām shall pour into his left palm."),
    ],
    27: [
        ("וְהִזָּה הַכֹּהֵן בְּאֶצְבָּעוֹ הַיְמָנִית מִן-הַשֶּׁמֶן אֲשֶׁר עַל-כַּפּוֹ הַשְּׂמָאלִית--שֶׁבַע פְּעָמִים לִפְנֵי יְהוָה",
         "וינצ'ח באצבעה אלימני. מן ד'אלך אלד'הן. אלד'י עלי' כפה אליסרי. סבע מראר בין ידי אללה",
         "And he shall sprinkle with his right finger from that oil which is on his left palm, seven times before God."),
    ],
    28: [
        ("וְנָתַן הַכֹּהֵן מִן-הַשֶּׁמֶן אֲשֶׁר עַל-כַּפּוֹ עַל-תְּנוּךְ אֹזֶן הַמִּטַּהֵר הַיְמָנִית וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית",
         "ת'ם יצ'ע מן אלד'הן אלד'י פי כפה. עלי' שחמה' אד'ן אלמתטהר אלימני. ועלי' אבהאם ידה אלימני. ועלי' אבהאם רגלה אלימני",
         "Then he shall place from the oil that is in his palm upon the cartilage of the earlobe of the one being purified — the right one — and on the thumb of his right hand, and on the thumb of his right foot,"),
        ("עַל-מְקוֹם דַּם הָאָשָׁם",
         "עלי' מוצ'ע דם קרבאן אלאת'ם",
         "upon the place of the blood of the guilt-offering."),
    ],
    29: [
        ("וְהַנּוֹתָר מִן-הַשֶּׁמֶן אֲשֶׁר עַל-כַּף הַכֹּהֵן יִתֵּן עַל-רֹאשׁ הַמִּטַּהֵר",
         "ובאקיה יצ'בה כעלי' ראס אלמתטהר",
         "And the remainder of it he shall pour upon the head of the one being purified,"),
        ("לְכַפֵּר עָלָיו לִפְנֵי יְהוָה",
         "ויסתג'פר ענה בין ידי אללה",
         "and shall seek forgiveness for him before God."),
    ],
    30: [
        ("וְעָשָׂה אֶת-הָאֶחָד מִן-הַתֹּרִים אוֹ מִן-בְּנֵי הַיּוֹנָה מֵאֲשֶׁר תַּשִּׂיג יָדוֹ",
         "ת'ם יעמל ואחד מן אלשפאנין. או מן פרכ'י אלחמאם. עלי' מא תנאל ידה",
         "Then he shall perform one of the turtle-doves or of the young pigeons, according to what his hand can reach."),
    ],
    31: [
        ("אֵת אֲשֶׁר-תַּשִּׂיג יָדוֹ אֶת-הָאֶחָד חַטָּאת וְאֶת-הָאֶחָד עֹלָה--עַל-הַמִּנְחָה",
         "מע מא תנאל ידה. אחדהמא ד'כוה. ואלאכ'ר צעידה מע אלהדייה",
         "According to what his hand can reach — one of them a purification-offering, and the other an ascending-offering, together with the gift-offering;"),
        ("וְכִפֶּר הַכֹּהֵן עַל הַמִּטַּהֵר לִפְנֵי יְהוָה",
         "ויסתג'פר ענה בין ידי אללה",
         "and he shall seek forgiveness for him before God."),
    ],
    32: [
        ("זֹאת תּוֹרַת אֲשֶׁר-בּוֹ נֶגַע צָרָעַת אֲשֶׁר לֹא-תַשִּׂיג יָדוֹ בְּטָהֳרָתוֹ",
         "הד'ה שריעה' מן כאן בה בלא ברץ. ולם תנאל ידה פי וקת טהרה",
         "This is the law for one who has had the affliction of leprosy, whose hand has not reached to that, at the time of his purification."),
    ],
    33: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה וְאֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה מוסי'' והרון תכלימא",
         "Then God spoke to Moses and Aaron directly."),
    ],
    34: [
        ("כִּי תָבֹאוּ אֶל-אֶרֶץ כְּנַעַן אֲשֶׁר אֲנִי נֹתֵן לָכֶם לַאֲחֻזָּה",
         "אד'א דכ'לתם אלי' בלד כנעאן. אלד'י אנא מעטיכמוהא חוזא",
         "When you enter the land of Canaan, which I am giving you as a possession,"),
        ("וְנָתַתִּי נֶגַע צָרַעַת בְּבֵית אֶרֶץ אֲחֻזַּתְכֶם",
         "פאחללת בלא ברץ. פי בעץ' ביות ארץ' חוזכם",
         "and I bring about an affliction of leprosy in some of the houses of the land of your possession —"),
    ],
    35: [
        ("וּבָא אֲשֶׁר-לוֹ הַבַּיִת וְהִגִּיד לַכֹּהֵן לֵאמֹר",
         "פליאת אלד'י לה אלבית. ויכ'בר אלאמאם קאילא",
         "then the owner of the house shall come and inform the imām, saying:"),
        ("כְּנֶגַע נִרְאָה לִי בַּבָּיִת",
         "קד צ'הר לי פי אלבית שבה בלא",
         "'There has appeared to me in the house something resembling an affliction.'"),
    ],
    36: [
        ("וְצִוָּה הַכֹּהֵן וּפִנּוּ אֶת-הַבַּיִת בְּטֶרֶם יָבֹא הַכֹּהֵן לִרְאוֹת אֶת-הַנֶּגַע וְלֹא יִטְמָא כָּל-אֲשֶׁר בַּבָּיִת",
         "פיאמר אלאמאם וינגלו אלבית. קבל אן ידכ'ל לינצר אלבלא. ולא ינג'ס גמיע מא פיה",
         "And the imām shall give the order, and they shall clear the house before he enters to inspect the affliction, so that nothing in it be made impure;"),
        ("וְאַחַר כֵּן יָבֹא הַכֹּהֵן לִרְאוֹת אֶת-הַבָּיִת",
         "ובעד ד'אלך ידכ'ל וינצ'ר אליה",
         "and after that he shall enter and look upon it."),
    ],
    37: [
        ("וְרָאָה אֶת-הַנֶּגַע וְהִנֵּה הַנֶּגַע בְּקִירֹת הַבַּיִת שְׁקַעֲרוּרֹת יְרַקְרַקֹּת אוֹ אֲדַמְדַּמֹּת",
         "פאן ראי' אלבלא. פאד'אה פי חיטאן אלבית. כ'טוט מ'כ'צרה. או מחמרה",
         "And if he sees the affliction — behold, it is in the walls of the house as streaks of greenish or reddish hue,"),
        ("וּמַרְאֵיהֶן שָׁפָל מִן-הַקִּיר",
         "ומנצ'רהן מסתפל פי אלחאיט",
         "and their appearance is sunken in the wall —"),
    ],
    38: [
        ("וְיָצָא הַכֹּהֵן מִן-הַבַּיִת אֶל-פֶּתַח הַבָּיִת וְהִסְגִּיר אֶת-הַבַּיִת שִׁבְעַת יָמִים",
         "פליכ'רג מן אלבית אלי' באבה. ויוקפה סבעה' אייאם",
         "then let him go out from the house to its doorway, and quarantine it for seven days."),
    ],
    39: [
        ("וְשָׁב הַכֹּהֵן בַּיּוֹם הַשְּׁבִיעִי וְרָאָה וְהִנֵּה פָּשָׂה הַנֶּגַע בְּקִירֹת הַבָּיִת",
         "ת'ם ירגע פי אליום אלסאבע. פאן ראי' אלבלא קד תפשא פי חיטאן אלבית",
         "Then he shall return on the seventh day; and if he sees that the affliction has spread in the walls of the house,"),
    ],
    41: [
        ("וְאֶת-הַבַּיִת יַקְצִעַ מִבַּיִת סָבִיב וְשָׁפְכוּ אֶת-הֶעָפָר אֲשֶׁר הִקְצוּ אֶל-מִחוּץ לָעִיר אֶל-מָקוֹם טָמֵא",
         "ויקשר אלבית מן דאכ'ל מסתדירא. וירמו אלתראב אלד'י קשרוה. כ'ארג אלקריה פי מוצ'ע נגס",
         "And the house shall be scraped on the inside all around, and they shall cast the plaster which they have scraped outside the town into an impure place."),
    ],
    42: [
        ("וְלָקְחוּ אֲבָנִים אֲחֵרוֹת וְהֵבִיאוּ אֶל-תַּחַת הָאֲבָנִים",
         "ויאכ'דו חגאר אכ'ר. וידכ'לוהא מוצ'ע תלך אלחגארה",
         "And they shall take other stones, and bring them in place of those stones;"),
        ("וְעָפָר אַחֵר יִקַּח וְטָח אֶת-הַבָּיִת",
         "ותראב אכ'ר. יוכ'ד' ויטיין אלבית",
         "and fresh plaster shall be taken and the house shall be re-plastered."),
    ],
    43: [
        ("וְאִם-יָשׁוּב הַנֶּגַע וּפָרַח בַּבַּיִת אַחַר חִלֵּץ אֶת-הָאֲבָנִים וְאַחֲרֵי הִקְצוֹת אֶת-הַבַּיִת וְאַחֲרֵי הִטּוֹחַ",
         "ואן עאד אלבלא ואנתשר פי אלבית. בעד מא כ'לעת אלחגארה. ובעד מא קשר אלבית וטיין",
         "And if the affliction returns and spreads in the house after the stones have been removed, and after the house has been scraped and re-plastered —"),
    ],
    44: [
        ("וּבָא הַכֹּהֵן וְרָאָה וְהִנֵּה פָּשָׂה הַנֶּגַע בַּבָּיִת",
         "פדכ'ל אלאמאם. פנצ'ר. פאד'א קד תפשא אלבלא פי אלבית",
         "then the imām shall enter and look; and behold, if the affliction has spread in the house,"),
        ("צָרַעַת מַמְאֶרֶת הִוא בַּבַּיִת טָמֵא הוּא",
         "פהו ברץ מאחק. פי אלבית והו נגס",
         "it is a consuming leprosy in the house — it is impure."),
    ],
    45: [
        ("וְנָתַץ אֶת-הַבַּיִת אֶת-אֲבָנָיו וְאֶת-עֵצָיו וְאֵת כָּל-עֲפַר הַבָּיִת",
         "פלינקצ'ה. מן חגארה וכ'שבה וגמיע תראבה",
         "And let him demolish it — its stones and its timber and all its plaster —"),
        ("וְהוֹצִיא אֶל-מִחוּץ לָעִיר אֶל-מָקוֹם טָמֵא",
         "וירמי ד'אלך אלי' כ'ארג אלקריה. אלי' מוצ'ע נגס",
         "and cast that outside the town into an impure place."),
    ],
    46: [
        ("וְהַבָּא אֶל-הַבַּיִת כָּל-יְמֵי הִסְגִּיר אֹתוֹ--יִטְמָא עַד-הָעָרֶב",
         "ומן דכ'ל אלי' אלבית. טול אלאייאם אלד'י אוקף פיהא. פלינגס אלי' אלמג'יב",
         "And whoever enters the house throughout all the days during which it is in quarantine shall be impure until the evening."),
    ],
    47: [
        ("וְהַשֹּׁכֵב בַּבַּיִת יְכַבֵּס אֶת-בְּגָדָיו",
         "ומן אנצ'גע פיה פליג'סל ת'יאבה",
         "And whoever lies down in it shall wash his garments;"),
        ("וְהָאֹכֵל בַּבַּיִת יְכַבֵּס אֶת-בְּגָדָיו",
         "וכד'לך כל מן אכל פיה. פליג'סל ת'יאבה",
         "and likewise everyone who eats in it shall wash his garments."),
    ],
    48: [
        ("וְאִם-בֹּא יָבֹא הַכֹּהֵן וְרָאָה וְהִנֵּה לֹא-פָשָׂה הַנֶּגַע בַּבַּיִת אַחֲרֵי הִטֹּחַ אֶת-הַבָּיִת",
         "פאן דכ'ל אלאמאם פנצ'ר. פאד'י לם יתפש אלבלא פי אלבית בעד מא טיין",
         "And if the imām enters and looks, and behold the affliction has not spread in the house after the plastering,"),
        ("וְטִהַר הַכֹּהֵן אֶת-הַבַּיִת כִּי נִרְפָּא הַנָּגַע",
         "פליטהרה. פאן אלבלא קד ברא",
         "then let him declare it pure — for the affliction has healed."),
    ],
    49: [
        ("וְלָקַח לְחַטֵּא אֶת-הַבַּיִת שְׁתֵּי צִפֳּרִים וְעֵץ אֶרֶז וּשְׁנִי תוֹלַעַת וְאֵזֹב",
         "ויאכ'ד' לתד'כיתה עצפורין. ועוד ארז. וחריר קרמז וצעתר",
         "And he shall take for its purification-offering two sparrows, and a cedar rod, and crimson silk and hyssop."),
    ],
    50: [
        ("וְשָׁחַט אֶת-הַצִּפֹּר הָאֶחָת אֶל-כְּלִי-חֶרֶשׂ עַל-מַיִם חַיִּים",
         "ויד'בח אחדהמא. פי אנא כ'זף מע מא מן נביע",
         "And he shall slaughter one of them in a clay vessel over water from a spring."),
    ],
    51: [
        ("וְלָקַח אֶת-עֵץ-הָאֶרֶז וְאֶת-הָאֵזֹב וְאֵת שְׁנִי הַתּוֹלַעַת וְאֵת הַצִּפֹּר הַחַיָּה וְטָבַל אֹתָם בְּדַם הַצִּפֹּר הַשְּׁחוּטָה וּבַמַּיִם הַחַיִּים",
         "ויאכ'ד' עוד אלארז ואלצעתר. וחריר אלקרמז ואלעצפור אלחי. ויג'מסהא פי דם אלעצפור אלמד'בוח. ואלמא אלד'י מן נביע",
         "And he shall take the cedar rod and the hyssop, and the crimson silk and the living sparrow, and shall dip them in the blood of the slaughtered sparrow and in the water from a spring,"),
        ("וְהִזָּה אֶל-הַבַּיִת שֶׁבַע פְּעָמִים",
         "וינצ'חה עלי' אלבית סבע מראר",
         "and shall sprinkle it upon the house seven times."),
    ],
    52: [
        ("וְחִטֵּא אֶת-הַבַּיִת--בְּדַם הַצִּפּוֹר וּבַמַּיִם הַחַיִּים וּבַצִּפֹּר הַחַיָּה וּבְעֵץ הָאֶרֶז וּבָאֵזֹב--וּבִשְׁנִי הַתּוֹלָעַת",
         "ויד'כיה בדם אלעצפור אלמד'בוח. ואלמא אלנביע. ואלעצפור אלחי. ואלעוד אלארז ואלצעתר וחריר אלקרמז",
         "And he shall declare it pure by means of the blood of the slaughtered sparrow, and the spring water, and the living sparrow, and the cedar rod, and the hyssop, and the crimson silk."),
    ],
    53: [
        ("וְשִׁלַּח אֶת-הַצִּפֹּר הַחַיָּה אֶל-מִחוּץ לָעִיר--אֶל-פְּנֵי הַשָּׂדֶה",
         "ויטלק אלעצפור אלחי. כ'ארג אלקריה אלי' וגה אלצחרי",
         "And he shall release the living sparrow outside the town toward the face of the wilderness,"),
        ("וְכִפֶּר עַל-הַבַּיִת וְטָהֵר",
         "ויסתג'פר ען מא פי אלבית ויטהר",
         "and shall seek forgiveness for what is in the house, and it shall be pure."),
    ],
    54: [
        ("זֹאת הַתּוֹרָה לְכָל-נֶגַע הַצָּרַעַת וְלַנָּתֶק",
         "הד'ה שריעה' גמיע בלא אלברץ ואלכ'לף",
         "This is the law for all affliction of leprosy and of the scall,"),
    ],
    55: [
        ("וּלְצָרַעַת הַבֶּגֶד וְלַבָּיִת",
         "וברץ אלת'יאב ואלביות",
         "and the leprosy of garments and of houses,"),
    ],
    56: [
        ("וְלַשְׂאֵת וְלַסַּפַּחַת וְלַבֶּהָרֶת",
         "ואלשאמה ואלעארצ'ה ואלבקעה",
         "and the blemish and the spreading mark and the spot —"),
    ],
    57: [
        ("לְהוֹרֹת בְּיוֹם הַטָּמֵא וּבְיוֹם הַטָּהֹר זֹאת תּוֹרַת הַצָּרָעַת",
         "תדל עלי' וקת אלתנגיס ווקת אלתטהיר. וכלהא שראיע אלברץ",
         "to indicate the time of becoming impure and the time of purification. These are all the laws of leprosy."),
    ],
}
