"""Hand-authored alignment triples for Vayikra chapter 23.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source carry he=None
and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly."),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("מוֹעֲדֵי", "אעיאד", "the festivals of"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלתי", "which"),
        (None, "יגב", "you are obligated"),
        (None, "אן", "to"),
        ("אֲשֶׁר-תִּקְרְאוּ אֹתָם", "תסמוהא", "designate"),
        (None, "באסמא", "by"),
        ("מִקְרָאֵי קֹדֶשׁ", "כ'אצה", "special names"),
        ("אֵלֶּה", "הד'ה", "these"),
        ("הֵם", "הי", "are"),
        ("מוֹעֲדָי", "אעיאדי", "My festivals."),
    ],
    3: [
        ("שֵׁשֶׁת", "סתה'", "Six"),
        ("יָמִים", "אייאם", "days"),
        ("תֵּעָשֶׂה", "תצנע", "shall labors"),
        ("מְלָאכָה", "אלצנאיע", "be performed"),
        (None, "ופי", "and on"),
        ("וּבַיּוֹם", "אליום", "the seventh"),
        ("הַשְּׁבִיעִי", "אלסאבע", "day is"),
        ("שַׁבַּת שַׁבָּתוֹן", "עטלה", "a desisting"),
        ("הִוא", "הי", "it is"),
        ("מִקְרָא-קֹדֶשׁ", "סבת", "a Sabbath"),
        (None, "אסם", "a consecrated"),
        (None, "מקדס", "name"),
        ("כָּל-מְלָאכָה", "כל צנאעה", "no labor"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform"),
        (None, "כד'אך", "Such"),
        ("שַׁבָּת", "הי סבת", "is the Sabbath of"),
        ("לַיהוָה", "ללה", "God"),
        (None, "פי", "in"),
        ("בְּכֹל", "גמיע", "all"),
        ("מוֹשְׁבֹתֵיכֶם", "מסאכנכם", "your dwellings."),
    ],
    4: [
        ("אֵלֶּה", "הד'ה", "These"),
        ("מוֹעֲדֵי", "אעיאד", "are the festivals of"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלתי", "which"),
        (None, "אסמאהא", "are designated by"),
        ("מִקְרָאֵי קֹדֶשׁ", "כ'אצה", "special names"),
        (None, "אלתי", "which"),
        (None, "יגב", "you are obligated"),
        (None, "אן", "to"),
        ("אֲשֶׁר-תִּקְרְאוּ אֹתָם", "תסמוהא", "designate"),
        (None, "פי", "in"),
        ("בְּמוֹעֲדָם", "אוקאתהא", "their appointed times."),
    ],
    5: [
        (None, "פי", "In"),
        ("בַּחֹדֶשׁ", "אלשהר", "the first month"),
        ("הָרִאשׁוֹן", "אלאוול", "on"),
        (None, "פי", "the fourteenth"),
        (None, "אליום", "day"),
        ("בְּאַרְבָּעָה עָשָׂר", "אלראבע עשר", "of it"),
        (None, "מנה", "between"),
        ("בֵּין הָעַרְבָּיִם", "בין אלג'רובין", "the two sunsets"),
        ("פֶּסַח", "פסחא", "a Passover offering"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    6: [
        (None, "ופי", "And on"),
        (None, "אליום", "the fifteenth"),
        ("וּבַחֲמִשָּׁה עָשָׂר", "אלכ'אמס עשר", "day"),
        (None, "מן", "of this"),
        ("הַזֶּה", "הד'א", "month"),
        ("לַחֹדֶשׁ", "אלשהר", "is"),
        ("חַג", "חג", "the festival of"),
        ("הַמַּצּוֹת", "אלפטיר", "unleavened bread"),
        ("לַיהוָה", "ללה", "to God"),
        ("שִׁבְעַת", "סבעה'", "seven"),
        ("יָמִים", "אייאם", "days"),
        ("תֹּאכֵלוּ", "תאכלו", "you shall eat"),
        ("מַצּוֹת", "פטירא", "unleavened bread."),
    ],
    7: [
        (None, "פי", "On"),
        ("בַּיּוֹם", "אליום", "the first"),
        ("הָרִאשׁוֹן", "אלאוול", "day of it"),
        (None, "מנה", "a consecrated"),
        (None, "אסם", "name"),
        ("מִקְרָא-קֹדֶשׁ", "מקדס", "shall"),
        ("יִהְיֶה", "יכון", "be"),
        ("לָכֶם", "לכם", "for you"),
        ("כָּל-מְלֶאכֶת", "כל צנעה'", "no labor"),
        ("עֲבֹדָה", "מכסב", "for profit"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform."),
    ],
    8: [
        ("וְהִקְרַבְתֶּם", "וקרבו", "And offer"),
        ("אִשֶּׁה", "קרבאנא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "פי", "during"),
        ("שִׁבְעַת יָמִים", "הד'ה אלסבעה' אלאייאם", "these seven days"),
        (None, "ופי", "and on"),
        ("בַּיּוֹם הַשְּׁבִיעִי", "אליום אלסאבע", "the seventh day"),
        (None, "אסם", "a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדס", "name"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה", "כל צנאעה' מכסב", "no labor for profit"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform."),
    ],
    9: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly."),
    ],
    10: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        (None, "אד'", "when"),
        ("כִּי-תָבֹאוּ", "תדכ'לון", "you enter"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        (None, "אלדי", "which"),
        ("אֲשֶׁר אֲנִי", "אנא", "I am"),
        ("נֹתֵן", "מעטיכם", "giving"),
        ("לָכֶם", "פאחצדו", "you"),
        ("וּקְצַרְתֶּם", "מן זרעהא", "and you reap its harvest"),
        ("אֶת-קְצִירָהּ", "ואיתו", "bring"),
        ("וַהֲבֵאתֶם", "בג'מר", "a sheaf of"),
        ("אֶת-עֹמֶר", "אוול", "the first"),
        ("רֵאשִׁית קְצִירְכֶם", "חצאדכם", "of your harvest"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the priest."),
    ],
    11: [
        ("וְהֵנִיף", "פיחרכה", "And he shall wave it"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        (None, "עלי'", "so that"),
        ("לִרְצֹנְכֶם", "מא ירתצ'א מנכם", "it be accepted from you"),
        (None, "וליכון", "and its waving"),
        ("מִמָּחֳרַת הַשַּׁבָּת יְנִיפֶנּוּ הַכֹּהֵן", "תחריכה לה. מן ג'ד אלעטלה", "shall be on the morrow after the rest-day."),
    ],
    12: [
        ("וַעֲשִׂיתֶם", "וקרבו", "And offer"),
        (None, "פי", "on"),
        ("בְּיוֹם הֲנִיפְכֶם", "יום תחריככם לה", "the day of your waving of it"),
        ("כֶּבֶשׂ", "חמלא", "an"),
        ("תָּמִים", "צחיחא", "unblemished lamb"),
        ("בֶּן-שְׁנָתוֹ", "אבן סנתה", "a year old"),
        ("לְעֹלָה", "צעידה", "as an ascent-offering"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    13: [
        ("וּמִנְחָתוֹ", "ומעה", "And with it"),
        (None, "מן", "from"),
        (None, "אלבר", "wheat"),
        ("שְׁנֵי עֶשְׂרֹנִים", "עשרין", "two-tenths"),
        ("סֹלֶת", "סמד", "of fine flour"),
        ("בְּלוּלָה", "מלתות", "mixed"),
        ("בַשֶּׁמֶן", "בדהן", "with oil"),
        ("אִשֶּׁה", "קרבאנא", "an offering"),
        ("רֵיחַ נִיחֹחַ", "מקבולא מרצ'ייא", "acceptable and pleasing"),
        ("לַיהוָה", "ללה", "to God"),
        ("וְנִסְכֹּה", "ומזאגה", "and its libation"),
        (None, "מן", "of"),
        ("יַיִן", "אלכ'מר", "wine"),
        ("רְבִיעִת הַהִין", "רבע קסט", "a quarter of a qist."),
    ],
    14: [
        ("וְלֶחֶם", "וכבזא", "And bread"),
        ("וְקָלִי", "וסויקא", "and parched grain"),
        ("וְכַרְמֶל", "ופריכא", "and roasted grain"),
        ("לֹא תֹאכְלוּ", "לא תאכלו", "you shall not eat"),
        (None, "אלי'", "until"),
        ("עַד-עֶצֶם", "ד'את", "this"),
        ("הַיּוֹם הַזֶּה", "הד'א אליום", "very day"),
        (None, "אלי'", "until"),
        (None, "אן", "you"),
        ("עַד הֲבִיאֲכֶם", "תאתו", "bring"),
        ("אֶת-קָרְבַּן", "בקרבאן", "the offering of"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("חֻקַּת", "רסם", "A decree"),
        ("עוֹלָם", "אלדהר", "forever"),
        (None, "עלי'", "throughout"),
        (None, "מר", "the passing of"),
        ("לְדֹרֹתֵיכֶם", "אגיאלכם", "your generations"),
        (None, "פי", "in"),
        ("בְּכֹל מֹשְׁבֹתֵיכֶם", "גמיע מסאכנכם", "all your dwellings."),
    ],
    15: [
        ("וּסְפַרְתֶּם", "ואחצו", "And count"),
        ("לָכֶם", "לכם", "for yourselves"),
        (None, "מן", "from"),
        ("מִמָּחֳרַת הַשַּׁבָּת", "ג'ד אלעטלה", "the morrow after the rest-day"),
        (None, "מן", "from"),
        ("מִיּוֹם הֲבִיאֲכֶם", "יום גיתם", "the day you brought"),
        ("אֶת-עֹמֶר הַתְּנוּפָה", "בג'מר אלתחריך", "the sheaf of the waving"),
        ("שֶׁבַע שַׁבָּתוֹת", "סבעה' אסאביע", "seven"),
        ("תְּמִימֹת", "תאמה", "complete weeks"),
        ("תִּהְיֶינָה", "תכון", "shall there be."),
    ],
    16: [
        (None, "ואלי'", "Until"),
        ("עַד מִמָּחֳרַת", "ג'ד", "the morrow of"),
        ("הַשַּׁבָּת הַשְּׁבִיעִת", "אלסאבע", "the seventh week"),
        (None, "פיכון", "and the total of"),
        ("תִּסְפְּרוּ", "גמלה' מא תחצונה", "what you count"),
        ("חֲמִשִּׁים יוֹם", "כ'מסין יומא", "shall be fifty days"),
        ("וְהִקְרַבְתֶּם", "וקרבו", "And offer"),
        ("מִנְחָה חֲדָשָׁה", "קרבאנא גדידא", "a new offering"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    17: [
        (None, "אן", "That"),
        ("מִמּוֹשְׁבֹתֵיכֶם", "תאתו מן מסאכנכם", "you bring from your dwellings"),
        ("לֶחֶם תְּנוּפָה", "בכ'בז לאלתחריך", "bread for waving"),
        ("שְׁתַּיִם", "רג'יפין", "two loaves"),
        (None, "מן", "of"),
        ("שְׁנֵי עֶשְׂרֹנִים", "עשרין", "two-tenths"),
        ("סֹלֶת", "סמדא", "of fine flour"),
        ("תִּהְיֶינָה", "יכונאן", "shall they be"),
        ("חָמֵץ", "וכ'מירא", "leavened"),
        ("תֵּאָפֶינָה", "יכ'בזאן", "shall they be baked"),
        ("בִּכּוּרִים", "המא בכור", "They are first-fruits"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    18: [
        ("וְהִקְרַבְתֶּם", "וקרבו", "And offer"),
        ("עַל-הַלֶּחֶם", "מע אלרג'יפין", "with the two loaves"),
        ("שִׁבְעַת כְּבָשִׂים", "סבעה חמלאן", "seven"),
        ("תְּמִימִם", "צחאחא", "unblemished lambs"),
        ("בְּנֵי שָׁנָה", "בני סנה", "yearlings"),
        ("וּפַר", "ות'ורא", "and a bull"),
        (None, "מן", "from"),
        ("בֶּן-בָּקָר", "אלבקר", "the cattle"),
        ("וְאֵילִם שְׁנָיִם", "וכבשין", "and two rams"),
        ("יִהְיוּ", "יכונאן", "they shall be"),
        ("עֹלָה", "צעידה", "an ascent-offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("וּמִנְחָתָם", "וברהמא", "and their grain-offering"),
        ("וְנִסְכֵּיהֶם", "ומזאגהמא", "and their libations"),
        ("אִשֵּׁה", "קרבאן", "an offering"),
        ("רֵיחַ-נִיחֹחַ", "מקבול מרצ'י", "acceptable and pleasing"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    19: [
        ("וַעֲשִׂיתֶם", "וקרבו", "And offer"),
        (None, "איצ'א", "also"),
        ("שְׂעִיר-עִזִּים", "עתוד מן אלמאעז", "a he-goat from the goats"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification"),
        ("וּשְׁנֵי כְבָשִׂים", "וחמלין", "and two"),
        ("בְּנֵי שָׁנָה", "אבני סנה", "yearling lambs"),
        ("לְזֶבַח שְׁלָמִים", "לד'בח אלסלאמה", "for the well-being sacrifice."),
    ],
    20: [
        ("וְהֵנִיף", "פיחרך", "And"),
        ("הַכֹּהֵן", "אלאמאם", "the priest"),
        (None, "מא יגב", "shall wave what is required"),
        (None, "מנהא", "of them"),
        ("עַל לֶחֶם הַבִּכֻּרִים", "מע רג'יפי אלבכור", "together with the two first-fruit loaves"),
        ("תְּנוּפָה", "תחריכא", "as a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("עַל-שְׁנֵי כְּבָשִׂים", "עלי' אלחמלין", "over the two lambs"),
        ("קֹדֶשׁ", "ולתכון קדסא", "and they shall be a holy portion"),
        ("לַיהוָה", "ללה", "to God"),
        ("לַכֹּהֵן", "תדפע אלי' אלאמאם", "given over to the priest."),
    ],
    21: [
        ("וּקְרָאתֶם", "ואסמו", "And designate"),
        ("בְּעֶצֶם", "ד'את", "that very"),
        ("הַיּוֹם הַזֶּה", "ד'אלך אליום", "day"),
        (None, "אסמא", "by a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדסא", "name"),
        ("יִהְיֶה", "יכון", "it shall be"),
        ("לָכֶם", "לכם", "for you"),
        ("כָּל-מְלֶאכֶת", "כל צנעה'", "no labor"),
        ("עֲבֹדָה", "מכסב", "for profit"),
        ("לֹא תַעֲשׂוּ", "לא תצנעו", "shall you perform"),
        ("חֻקַּת", "רסם", "A decree"),
        ("עוֹלָם", "אלדהר", "forever"),
        (None, "פי", "in"),
        ("בְּכָל-מוֹשְׁבֹתֵיכֶם", "גמיע מסאכנכם", "all your dwellings"),
        (None, "עלי'", "throughout"),
        (None, "מר", "your"),
        ("לְדֹרֹתֵיכֶם", "אגיאלכם", "generations."),
    ],
    22: [
        (None, "ואד'א", "And when"),
        ("וּבְקֻצְרְכֶם", "חצדתם", "you reap"),
        ("אֶת-קְצִיר", "זרע", "the harvest of"),
        ("אַרְצְכֶם", "ריאצ'כם", "your fields"),
        ("לֹא-תְכַלֶּה", "פלא תסתקץ", "do not cut"),
        (None, "טרה'", "to the very edge of"),
        ("פְּאַת", "צ'יעתך", "your estate"),
        ("שָׂדְךָ בְּקֻצְרֶךָ", "פי חצאדך", "in your reaping"),
        ("וְלֶקֶט", "ונת'יר", "and the scattered grain of"),
        ("קְצִירְךָ", "זרעך", "your sowing"),
        ("לֹא תְלַקֵּט", "פלא תלקטה", "do not glean"),
        (None, "בל", "rather"),
        ("לֶעָנִי", "לאלצ'עיף", "for the poor"),
        ("וְלַגֵּר", "ואלג'ריב", "and the stranger"),
        ("תַּעֲזֹב", "אתרכהמא", "leave them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good."),
    ],
    23: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly."),
    ],
    24: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("לֵאמֹר", "קאילא", "saying"),
        (None, "פי", "on"),
        ("בְּאֶחָד לַחֹדֶשׁ", "אלאוול מן", "the first day of"),
        ("בַּחֹדֶשׁ הַשְּׁבִיעִי", "אלשהר אלסאבע", "the seventh month"),
        ("יִהְיֶה", "יכון", "there shall be"),
        ("לָכֶם", "לכם", "for you"),
        ("שַׁבָּתוֹן", "עטלה", "a rest-day"),
        ("זִכְרוֹן תְּרוּעָה", "ותבויק גלבה", "and a sounding of clamor"),
        (None, "אסמא", "a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדסא", "name."),
    ],
    25: [
        ("כָּל-מְלֶאכֶת עֲבֹדָה", "כל צנאעה' מכסב", "No labor for profit"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform"),
        ("וְהִקְרַבְתֶּם", "וקרבו", "and offer"),
        ("אִשֶּׁה", "קרבאנא", "an"),
        (None, "זאידא", "additional offering"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    26: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly."),
    ],
    27: [
        (None, "אמא", "Now"),
        (None, "פי", "on"),
        ("אַךְ בֶּעָשׂוֹר", "אליום אלעאשר", "the tenth day"),
        (None, "מן", "of"),
        ("לַחֹדֶשׁ", "הד'א", "this"),
        ("הַשְּׁבִיעִי הַזֶּה", "אלשהר אלסאבע", "seventh month"),
        (None, "והו", "and it is"),
        ("יוֹם הַכִּפֻּרִים", "יום אלג'פראן", "the Day of Atonement"),
        (None, "אסמא", "a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדסא", "name"),
        ("יִהְיֶה", "יכון", "shall be"),
        ("לָכֶם", "לכם", "for you"),
        ("וְעִנִּיתֶם", "ואגיעו", "and starve"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "yourselves"),
        ("וְהִקְרַבְתֶּם", "וקרבו", "and offer"),
        ("אִשֶּׁה", "קרבאנא", "an"),
        (None, "זאידא", "additional offering"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    28: [
        ("וְכָל-מְלָאכָה", "וכל עמל", "And no work"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "at all shall you perform"),
        (None, "פי", "on"),
        ("בְּעֶצֶם", "ד'את", "this"),
        ("הַיּוֹם הַזֶּה", "הד'א אליום", "very day"),
        (None, "לאנה", "for it is"),
        ("כִּי", "יום", "a day of"),
        ("יוֹם כִּפֻּרִים", "ג'פראן", "atonement"),
        (None, "לכם", "for you"),
        (None, "יסתג'פר פיה", "on which pardon is sought"),
        (None, "ענכם", "on your behalf"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord."),
    ],
    29: [
        ("כִּי כָל-הַנֶּפֶשׁ", "וכל אנסאן", "And every"),
        (None, "באלג'", "adult person"),
        (None, "לם", "who does not"),
        ("אֲשֶׁר לֹא-תְעֻנֶּה", "יצום", "fast"),
        (None, "פי", "on"),
        ("בְּעֶצֶם", "ד'את", "this"),
        ("הַיּוֹם הַזֶּה", "הד'א אליום", "very day"),
        ("וְנִכְרְתָה", "ינקטע", "shall be cut off"),
        (None, "מן", "from"),
        ("מֵעַמֶּיהָ", "קומה", "his people."),
    ],
    30: [
        ("וְכָל-הַנֶּפֶשׁ", "וכל אנסאן", "And every person"),
        ("אֲשֶׁר תַּעֲשֶׂה", "יצנע", "who performs"),
        (None, "שייא", "any"),
        ("כָּל-מְלָאכָה", "מן אלצנאיע", "labor"),
        (None, "פי", "on"),
        ("בְּעֶצֶם", "ד'את", "this"),
        ("הַיּוֹם הַזֶּה", "ד'אלך אליום", "very day"),
        ("וְהַאֲבַדְתִּי", "אביד", "I shall destroy"),
        (None, "ד'אלך", "that"),
        ("אֶת-הַנֶּפֶשׁ הַהִוא", "אלאנסאן", "person"),
        ("מִקֶּרֶב", "מן בין", "from among"),
        ("עַמָּהּ", "קומה", "his people."),
    ],
    31: [
        ("כָּל-מְלָאכָה", "וכל צנאעה", "And no labor"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "at all shall you perform"),
        ("חֻקַּת", "רסם", "A decree"),
        ("עוֹלָם", "אלדהר", "forever"),
        (None, "עלי'", "throughout"),
        (None, "מר", "your"),
        ("לְדֹרֹתֵיכֶם", "אגיאלכם", "generations"),
        (None, "פי", "in"),
        ("בְּכֹל מֹשְׁבֹתֵיכֶם", "גמיע מסאכנכם", "all your dwellings."),
    ],
    32: [
        ("שַׁבַּת שַׁבָּתוֹן", "עטלה", "It is a desisting"),
        ("הוּא", "הי", "a"),
        ("לָכֶם", "סבת לכם", "Sabbath for you"),
        ("וְעִנִּיתֶם", "ותגיעו", "and you shall starve"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "yourselves"),
        (None, "מן", "from"),
        ("בְּתִשְׁעָה לַחֹדֶשׁ", "עשייה' אלתאסע פי הד'י אלשהר", "the evening of the ninth of this month"),
        (None, "אלי'", "until"),
        ("בָּעֶרֶב--מֵעֶרֶב עַד-עֶרֶב", "אלעשי אלת'אני", "the second evening"),
        ("תִּשְׁבְּתוּ", "תעטלו", "you shall cease"),
        ("שַׁבַּתְּכֶם", "עמלכם", "your work."),
    ],
    33: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "directly."),
    ],
    34: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("לֵאמֹר", "קאילא", "saying"),
        (None, "פי", "on"),
        ("בַּחֲמִשָּׁה עָשָׂר יוֹם", "אלכאמס עשר", "the fifteenth day"),
        (None, "מן", "of"),
        ("לַחֹדֶשׁ הַשְּׁבִיעִי הַזֶּה", "אלשהר אלסאבע", "the seventh month"),
        ("חַג הַסֻּכּוֹת", "חג אלמצ'אל", "the festival of booths"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    35: [
        (None, "פי", "On"),
        ("בַּיּוֹם הָרִאשׁוֹן", "אליום אלאוול", "the first day"),
        (None, "אסם", "a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדס", "name"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה", "כל צנאעה' מכסב", "no labor for profit"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform."),
    ],
    36: [
        (None, "ופי", "And during"),
        ("שִׁבְעַת יָמִים", "הד'ה אלסבעה' אלאייאם", "these seven days"),
        ("תַּקְרִיבוּ", "תקרבו", "you shall offer"),
        ("אִשֶּׁה", "קרבאנא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "ופי", "and on"),
        ("בַּיּוֹם הַשְּׁמִינִי", "אליום אלת'אמן", "the eighth day"),
        (None, "אסם", "a consecrated"),
        ("מִקְרָא-קֹדֶשׁ", "מקדס", "name"),
        ("יִהְיֶה", "יכון", "shall be"),
        ("לָכֶם", "לכם", "for you"),
        ("וְהִקְרַבְתֶּם", "וקרבו", "and offer"),
        ("אִשֶּׁה", "קרבאנא זאידא", "an additional offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("עֲצֶרֶת הִוא", "ואמכתו פי קדסה", "and remain in its holiness"),
        ("כָּל-מְלֶאכֶת עֲבֹדָה", "וכל צנאעה' מכסב", "no labor for profit"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you perform."),
    ],
    37: [
        ("אֵלֶּה", "הד'ה", "These"),
        ("מוֹעֲדֵי", "אעיאד", "are the festivals of"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלתי", "which"),
        (None, "יגב", "you are obligated"),
        (None, "אן", "to"),
        ("אֲשֶׁר-תִּקְרְאוּ אֹתָם", "תסמוהא", "designate"),
        (None, "באסמא", "by"),
        ("מִקְרָאֵי קֹדֶשׁ", "כ'אצה", "special names"),
        ("לְהַקְרִיב", "ותקרבו", "and in which you shall offer"),
        ("אִשֶּׁה", "קראבינא", "offerings"),
        ("לַיהוָה", "ללה", "to God"),
        ("עֹלָה", "צעידה", "ascent-offering"),
        ("וּמִנְחָה", "ובר", "and grain-offering"),
        ("זֶבַח", "וד'בח", "and sacrifice"),
        ("וּנְסָכִים", "ומזאג", "and libation"),
        (None, "ואגב", "the obligation of"),
        ("דְּבַר-יוֹם בְּיוֹמוֹ", "כל יום פי יומה", "each day in its day."),
    ],
    38: [
        (None, "מא כ'לא", "Apart from"),
        ("מִלְּבַד שַׁבְּתֹת", "סבות", "the Sabbaths of"),
        ("יְהוָה", "אללה", "God"),
        (None, "ומא כ'לא", "and apart from"),
        ("וּמִלְּבַד מַתְּנוֹתֵיכֶם", "עטאיאכם", "your gifts"),
        ("וּמִלְּבַד כָּל-נִדְרֵיכֶם", "ונד'ורכם", "and your vows"),
        ("וּמִלְּבַד כָּל-נִדְבֹתֵיכֶם", "ותברעכם", "and your freewill-offerings"),
        ("אֲשֶׁר תִּתְּנוּ", "אלדי תעטוהא", "which you give"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    39: [
        (None, "אמא", "Now"),
        (None, "פי", "on"),
        ("אַךְ בַּחֲמִשָּׁה עָשָׂר יוֹם", "אליום אלכ'אמס עשר", "the fifteenth day"),
        (None, "מן", "of"),
        ("לַחֹדֶשׁ הַשְּׁבִיעִי", "אלשהר אלסאבע", "the seventh month"),
        (None, "פי", "at"),
        (None, "אואן", "the season of"),
        ("בְּאָסְפְּכֶם", "גמעכם", "your gathering"),
        ("אֶת-תְּבוּאַת", "גלה'", "the yield of"),
        ("הָאָרֶץ", "אלארץ'", "the land"),
        ("תָּחֹגּוּ", "תחגו", "you shall make a pilgrimage-festival"),
        ("אֶת-חַג-יְהוָה", "חג ללה", "to God"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "for seven days"),
        (None, "פי", "on"),
        ("בַּיּוֹם הָרִאשׁוֹן", "אליום אלאוול מנהא", "the first day of them"),
        ("שַׁבָּתוֹן", "עטלה", "a rest-day"),
        (None, "ופי", "and on"),
        ("וּבַיּוֹם הַשְּׁמִינִי", "אליום אלת'אמן", "the eighth day"),
        ("שַׁבָּתוֹן", "עטלה", "a rest-day."),
    ],
    40: [
        ("וּלְקַחְתֶּם", "וכ'דו", "And take"),
        ("לָכֶם", "לכם", "for yourselves"),
        (None, "פי", "on"),
        ("בַּיּוֹם הָרִאשׁוֹן", "אליום אלאוול", "the first day"),
        (None, "מן", "from"),
        ("פְּרִי עֵץ הָדָר", "ת'מר שגר אלאתרנג", "the fruit of the citron tree"),
        (None, "ומן", "and from"),
        ("כַּפֹּת תְּמָרִים", "לב אלנכ'ל", "the fronds of the palm"),
        (None, "ומן", "and from"),
        ("וַעֲנַף עֵץ-עָבֹת", "אג'צאן עוד אלאס עלי' צנעה' אלצ'פר", "the branches of the myrtle-wood braided together"),
        (None, "ומן", "and from"),
        ("וְעַרְבֵי-נָחַל", "ג'רב אלואד", "the willows of the valley"),
        ("וּשְׂמַחְתֶּם", "ואפרחו", "and rejoice"),
        (None, "בה", "with them"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days."),
    ],
    41: [
        ("וְחַגֹּתֶם", "וחגו", "And celebrate"),
        (None, "ד'אלך", "it"),
        ("חַג", "חג", "as a festival"),
        ("לַיהוָה", "ללה", "to God"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        (None, "פי", "in"),
        ("בַּשָּׁנָה", "אלסנה", "the year"),
        ("חֻקַּת", "רסם", "a decree"),
        ("עוֹלָם", "אלדהר", "forever"),
        (None, "עלי'", "throughout"),
        (None, "מר", "your"),
        ("לְדֹרֹתֵיכֶם", "אגיאלכם", "generations"),
        (None, "פי", "in"),
        ("בַּחֹדֶשׁ הַשְּׁבִיעִי", "אלשהר אלסאבע", "the seventh month"),
        ("תָּחֹגּוּ אֹתוֹ", "תחגונה", "you shall celebrate it."),
    ],
    42: [
        ("בַּסֻּכֹּת תֵּשְׁבוּ", "ואגלסו פי אלמצ'אל", "And dwell in the booths"),
        ("שִׁבְעַת יָמִים", "סבעה' אייאם", "seven days"),
        (None, "לאמרי", "at My command"),
        ("כָּל-הָאֶזְרָח", "וכל צריח", "every native-born"),
        (None, "מן", "of"),
        ("בְּיִשְׂרָאֵל", "אל אסראיל", "the house of Israel"),
        ("יֵשְׁבוּ בַּסֻּכֹּת", "יגלסו פי אלמצ'אל", "shall dwell in the booths —"),
    ],
    43: [
        (None, "לכי", "so that"),
        ("לְמַעַן יֵדְעוּ", "יעלם", "may know"),
        ("דֹרֹתֵיכֶם", "אגיאלכם", "your generations"),
        (None, "אני", "that I"),
        ("כִּי", "אללה", "God"),
        ("בַסֻּכּוֹת", "רבכם", "your Lord"),
        ("הוֹשַׁבְתִּי", "אגלסת", "sheltered"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        (None, "פי", "in"),
        (None, "צ'לאל", "the shade"),
        (None, "מכן", "of"),
        (None, "ג'מאמי", "My clouds"),
        ("בְּהוֹצִיאִי", "חין אכ'רגתהם", "when I brought them out"),
        (None, "מן", "from"),
        ("מֵאֶרֶץ", "בלד", "the land of"),
        ("מִצְרָיִם", "מצר", "Egypt"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "צאדק אלועד", "true to My promise."),
    ],
    44: [
        ("וַיְדַבֵּר מֹשֶׁה", "פכ'אטב מוסי'", "And Moses addressed"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("אֶת-מֹעֲדֵי", "באעיאד", "concerning the festivals of"),
        ("יְהוָה", "אללה", "God."),
    ],
}
