"""Hand-authored alignment triples for Vayikra chapter 1."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "כ'אטב בני אסראיל וקל להם",
         "Address the sons of Israel and say to them"),
        ("אָדָם כִּי-יַקְרִיב מִכֶּם קָרְבָּן לַיהוָה",
         "אי אנסאן קרב מנכם קרבאנא ללה",
         "any person among you who brings an offering to God"),
        ("מִן-הַבְּהֵמָה מִן-הַבָּקָר וּמִן-הַצֹּאן תַּקְרִיבוּ אֶת-קָרְבַּנְכֶם",
         "מן אלבהאים. פמן אלבקר ואלג'נם תקרבונה",
         "from the beasts, from the cattle and the flock shall you bring it."),
    ],
    3: [
        ("אִם-עֹלָה קָרְבָּנוֹ מִן-הַבָּקָר זָכָר תָּמִים יַקְרִיבֶנּוּ",
         "אן כאן קרבאנה צעידה מן אלבקר. פד'כר צחיח יקרבה",
         "If his offering is an ascent-offering from the cattle, a sound male shall he bring it"),
        ("אֶל-פֶּתַח אֹהֶל מוֹעֵד יַקְרִיב אֹתוֹ לִרְצֹנוֹ לִפְנֵי יְהוָה",
         "פליקדמה אלי' באב כ'בא אלמחצ'ר. עלי' מא ירתצ'א ענה בין ידי אללה",
         "he shall present it at the entrance of the tent of the assembly, according to what shall be acceptable of him before God."),
    ],
    4: [
        ("וְסָמַךְ יָדוֹ עַל רֹאשׁ הָעֹלָה",
         "ויסנד ידה עלי' ראסה",
         "And he shall lean his hand upon its head"),
        ("וְנִרְצָה לוֹ לְכַפֵּר עָלָיו",
         "וירצ'א ענה ויג'פר לה",
         "and it shall be accepted of him and forgiven him."),
    ],
    5: [
        ("וְשָׁחַט אֶת-בֶּן הַבָּקָר לִפְנֵי יְהוָה",
         "ויד'בח אלרת' בין ידי אללה",
         "And he shall slaughter the bullock before God"),
        ("וְהִקְרִיבוּ בְּנֵי אַהֲרֹן הַכֹּהֲנִים אֶת-הַדָּם",
         "ויקרב בני הרון אלאיימה אלדם",
         "and the sons of Aaron, the priests, shall bring the blood near"),
        ("וְזָרְקוּ אֶת-הַדָּם עַל-הַמִּזְבֵּחַ סָבִיב אֲשֶׁר-פֶּתַח אֹהֶל מוֹעֵד",
         "וירשוה עלי' אלמד'בח מסתדירא. אלד'י ענד באב כ'בא אלמחצ'ר",
         "and shall sprinkle it upon the altar all around, which is at the entrance of the tent of the assembly."),
    ],
    6: [
        ("וְהִפְשִׁיט אֶת-הָעֹלָה וְנִתַּח אֹתָהּ לִנְתָחֶיהָ",
         "ויסלך' אלצעידה ויעצ'יהא אעצ'אא",
         "And he shall flay the ascent-offering and divide it into its limbs."),
    ],
    7: [
        ("וְנָתְנוּ בְּנֵי אַהֲרֹן הַכֹּהֵן אֵשׁ--עַל-הַמִּזְבֵּחַ",
         "וישעלון בני הרון אלאמאם. נארא עלי' אלמד'בח",
         "And the sons of Aaron, the priest, shall kindle fire upon the altar"),
        ("וְעָרְכוּ עֵצִים עַל-הָאֵשׁ",
         "וינצ'דון עליהא חטבא",
         "and shall arrange wood upon it."),
    ],
    8: [
        ("וְעָרְכוּ בְּנֵי אַהֲרֹן הַכֹּהֲנִים אֵת הַנְּתָחִים אֶת-הָרֹאשׁ וְאֶת-הַפָּדֶר",
         "וינצ'ד בני הרון אלאיימה. אלאעצ'א ואלראס ואלקצבה",
         "And the sons of Aaron, the priests, shall arrange the limbs, and the head, and the spinal column"),
        ("עַל-הָעֵצִים אֲשֶׁר עַל-הָאֵשׁ אֲשֶׁר עַל-הַמִּזְבֵּחַ",
         "עלי' אלחטב אלד'י עלי' אלנאר. אלד'י עלי' אלמד'בח",
         "upon the wood that is upon the fire, which is upon the altar."),
    ],
    9: [
        ("וְקִרְבּוֹ וּכְרָעָיו יִרְחַץ בַּמָּיִם",
         "וגופה ואכארעה יג'סלהא באלמא",
         "Its innards and its legs shall he wash with water"),
        ("וְהִקְטִיר הַכֹּהֵן אֶת-הַכֹּל הַמִּזְבֵּחָה עֹלָה אִשֵּׁה רֵיחַ-נִיחוֹחַ לַיהוָה",
         "ויקתר אלאמאם אלכל עלי' אלמד'בח. צעידה קרבאן מקבול מרצ'י ללה",
         "and the priest shall burn the whole upon the altar — an ascent-offering, an acceptable and pleasing offering to God."),
    ],
    10: [
        ("וְאִם-מִן-הַצֹּאן קָרְבָּנוֹ מִן-הַכְּשָׂבִים אוֹ מִן-הָעִזִּים לְעֹלָה",
         "ואן כאן קרבאנה מן אלג'נם. פמן אלצ'אן או מן אלמאעז צעידה",
         "And if his offering is from the flock — from the sheep or from the goats — an ascent-offering"),
        ("זָכָר תָּמִים יַקְרִיבֶנּוּ",
         "פליקרבה ד'כרא צחיחא",
         "he shall bring it as a sound male."),
    ],
    11: [
        ("וְשָׁחַט אֹתוֹ עַל יֶרֶךְ הַמִּזְבֵּחַ צָפֹנָה--לִפְנֵי יְהוָה",
         "ויד'בחה עלי' גאנב אלמד'בח. שמאלייא בין ידי אללה",
         "And he shall slaughter it on the side of the altar, northward, before God"),
        ("וְזָרְקוּ בְּנֵי אַהֲרֹן הַכֹּהֲנִים אֶת-דָּמוֹ עַל-הַמִּזְבֵּחַ--סָבִיב",
         "וירש בני הרון אלאיימה דמה. עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron, the priests, shall sprinkle its blood upon the altar all around."),
    ],
    12: [
        ("וְנִתַּח אֹתוֹ לִנְתָחָיו וְאֶת-רֹאשׁוֹ וְאֶת-פִּדְרוֹ",
         "ויעצ'יה אעצ'אא. וראסה וקצבתה",
         "And he shall divide it into its limbs, and its head and its spinal column"),
        ("וְעָרַךְ הַכֹּהֵן אֹתָם עַל-הָעֵצִים אֲשֶׁר עַל-הָאֵשׁ אֲשֶׁר עַל-הַמִּזְבֵּחַ",
         "וינצ'דהא אלאמאם. עלי' אלחטב אלד'י עלי' אלנאר. אלד'י עלי' אלמד'בח",
         "and the priest shall arrange them upon the wood that is upon the fire, which is upon the altar."),
    ],
    13: [
        ("וְהַקֶּרֶב וְהַכְּרָעַיִם יִרְחַץ בַּמָּיִם",
         "ואלגוף ואלאכארע יג'סלהא באלמא",
         "And the innards and the legs shall he wash with water"),
        ("וְהִקְרִיב הַכֹּהֵן אֶת-הַכֹּל וְהִקְטִיר הַמִּזְבֵּחָה--עֹלָה הוּא אִשֵּׁה רֵיחַ נִיחֹחַ לַיהוָה",
         "ויקדם אלאמאם אלכל ויקתרה עלי' אלמד'בח. הו צעידה. קרבאן מקבול מרצ'י ללה",
         "and the priest shall present the whole and burn it upon the altar — it is an ascent-offering, an acceptable and pleasing offering to God."),
    ],
    14: [
        ("וְאִם מִן-הָעוֹף עֹלָה קָרְבָּנוֹ לַיהוָה",
         "ואן כאן קרבאנה מן אלטאיר צעידה ללה",
         "And if his offering to God is an ascent-offering from birds"),
        ("וְהִקְרִיב מִן-הַתֹּרִים אוֹ מִן-בְּנֵי הַיּוֹנָה--אֶת-קָרְבָּנוֹ",
         "פליקרבה מן אלשפאנין. או מן פראך' אלחמאם",
         "he shall bring it from the turtledoves or from the young of the pigeons."),
    ],
    15: [
        ("וְהִקְרִיבוֹ הַכֹּהֵן אֶל-הַמִּזְבֵּחַ וּמָלַק אֶת-רֹאשׁוֹ",
         "ויקדמה אלאמאם אלי' אלמד'בח. ויפצל ראסה",
         "And the priest shall present it to the altar, and shall separate its head"),
        ("וְהִקְטִיר הַמִּזְבֵּחָה וְנִמְצָה דָמוֹ עַל קִיר הַמִּזְבֵּחַ",
         "ת'ם יקתרה עלי' אלמד'בח. וימצ'י דמה. עלי' חאיט אלמד'בח",
         "then he shall burn it upon the altar, and its blood shall drain upon the wall of the altar."),
    ],
    16: [
        ("וְהֵסִיר אֶת-מֻרְאָתוֹ בְּנֹצָתָהּ",
         "וינזע חוצלתה מע קאנצתה",
         "And he shall remove its crop along with its gizzard"),
        ("וְהִשְׁלִיךְ אֹתָהּ אֵצֶל הַמִּזְבֵּחַ קֵדְמָה--אֶל-מְקוֹם הַדָּשֶׁן",
         "ויטרחהא לזק אלמד'בח שרקייא. פי מוצ'ע מטרח אלרמאד",
         "and shall throw them beside the altar on the east side, at the place where the ash is cast."),
    ],
    17: [
        ("וְשִׁסַּע אֹתוֹ בִכְנָפָיו לֹא יַבְדִּיל",
         "ויפצלה מן אגנחתה ולא יפרזה",
         "And he shall split it open by its wings without severing it completely"),
        ("וְהִקְטִיר אֹתוֹ הַכֹּהֵן הַמִּזְבֵּחָה עַל-הָעֵצִים אֲשֶׁר עַל-הָאֵשׁ עֹלָה הוּא אִשֵּׁה רֵיחַ נִיחֹחַ--לַיהוָה",
         "ת'ם יקתרה אלאמאם עלי' אלמד'בח. עלי' אלחטב אלד'י עלי' אלנאר צעידה. קרבאן מקבול מרצ'י ללה",
         "then the priest shall burn it upon the altar, upon the wood that is upon the fire — an ascent-offering, an acceptable and pleasing offering to God."),
    ],
}
