"""Hand-authored alignment triples for Vayikra chapter 8."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("קַח אֶת-אַהֲרֹן וְאֶת-בָּנָיו אִתּוֹ וְאֵת הַבְּגָדִים וְאֵת שֶׁמֶן הַמִּשְׁחָה",
         "קדם הרון ובניה מעה. ואלת'יאב ודהן אלמסוחייה.",
         "'Present Aaron and his sons with him, and the garments and the anointing oil,"),
        ("וְאֵת פַּר הַחַטָּאת וְאֵת שְׁנֵי הָאֵילִים וְאֵת סַל הַמַּצּוֹת",
         "ורת' אלדכוה. ואלכבשין וסל אלפטיר",
         "and the bull of the purification-offering, and the two rams, and the basket of unleavened bread.'"),
    ],
    3: [
        ("וְאֵת כָּל-הָעֵדָה הַקְהֵל אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "וגווק אלגמע. אלי' באב כ'בא אלמחצ'ר",
         "'And assemble the congregation to the entrance of the tent of the appointed meeting.'"),
    ],
    4: [
        ("וַיַּעַשׂ מֹשֶׁה כַּאֲשֶׁר צִוָּה יְהוָה אֹתוֹ",
         "פעמל מוסי'. כמא אמרה אללה.",
         "And Moses did as God had commanded him;"),
        ("וַתִּקָּהֵל הָעֵדָה אֶל-פֶּתַח אֹהֶל מוֹעֵד",
         "פתגווק אלגמע. אלי' באב כ'בא אלמחצ'ר",
         "and the congregation assembled at the entrance of the tent of the appointed meeting."),
    ],
    5: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-הָעֵדָה זֶה הַדָּבָר אֲשֶׁר-צִוָּה יְהוָה לַעֲשׂוֹת",
         "פקאל מוסי' להם. הד'א אלאמר. אלד'י אמר אללה אן תעמלו",
         "And Moses said to them: 'This is the matter which God has commanded that you do.'"),
    ],
    6: [
        ("וַיַּקְרֵב מֹשֶׁה אֶת-אַהֲרֹן וְאֶת-בָּנָיו וַיִּרְחַץ אֹתָם בַּמָּיִם",
         "פקדם מוסי' הרון ובניה. וג'סלהם באלמא",
         "And Moses presented Aaron and his sons, and washed them with water."),
    ],
    7: [
        ("וַיִּתֵּן עָלָיו אֶת-הַכֻּתֹּנֶת וַיַּחְגֹּר אֹתוֹ בָּאַבְנֵט וַיַּלְבֵּשׁ אֹתוֹ אֶת-הַמְּעִיל",
         "וגעל עליה אלתוניה. וקלדה באלזנאר. ואלבסה אלממטר.",
         "And he put upon him the tunic, and girded him with the sash, and clothed him with the robe,"),
        ("וַיִּתֵּן עָלָיו אֶת-הָאֵפֹד וַיַּחְגֹּר אֹתוֹ בְּחֵשֶׁב הָאֵפֹד וַיֶּאְפֹּד לוֹ בּוֹ",
         "וגעל עליה אלצדרה. ושדדה בהמיאנהא. וצדרה בהא",
         "and placed upon him the breastpiece, and fastened it with its belt, and bound him with it."),
    ],
    8: [
        ("וַיָּשֶׂם עָלָיו אֶת-הַחֹשֶׁן וַיִּתֵּן אֶל-הַחֹשֶׁן אֶת-הָאוּרִים וְאֶת-הַתֻּמִּים",
         "וצייר עליה אלבדנה. וגעל פיהא. אלאנואר ואלצחאיח",
         "And he set upon him the body-piece, and placed within it the lights and the truths."),
    ],
    9: [
        ("וַיָּשֶׂם אֶת-הַמִּצְנֶפֶת עַל-רֹאשׁוֹ וַיָּשֶׂם עַל-הַמִּצְנֶפֶת אֶל-מוּל פָּנָיו אֵת צִיץ הַזָּהָב נֵזֶר הַקֹּדֶשׁ",
         "וצייר אלעמאמה עלי' ראסה. וגעל דונהא ממא ילי וגהה. עצאבה' אלד'הב תאג אלקדס.",
         "And he set the turban upon his head, and placed beneath it, on the side facing his face, the golden band — the diadem of holiness —"),
        ("כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "כמא אמר אללה מוסי'",
         "as God had commanded Moses."),
    ],
    10: [
        ("וַיִּקַּח מֹשֶׁה אֶת-שֶׁמֶן הַמִּשְׁחָה וַיִּמְשַׁח אֶת-הַמִּשְׁכָּן וְאֶת-כָּל-אֲשֶׁר-בּוֹ וַיְקַדֵּשׁ אֹתָם",
         "ואכ'ד' מוסי' דהן אלמסוחייה. ומסח מנה אלמסכן וגמיע מא פיה. וקדסהם",
         "And Moses took the anointing oil, and anointed with it the tabernacle and all that was in it, and consecrated them."),
    ],
    11: [
        ("וַיַּז מִמֶּנּוּ עַל-הַמִּזְבֵּחַ שֶׁבַע פְּעָמִים וַיִּמְשַׁח אֶת-הַמִּזְבֵּחַ וְאֶת-כָּל-כֵּלָיו",
         "ונצ'ח מנה. עלי' אלמד'בח סבע מראר. ומסח אלמד'בח וגמיע מא פיה.",
         "And he sprinkled from it upon the altar seven times, and anointed the altar and all that was upon it,"),
        ("וְאֶת-הַכִּיֹּר וְאֶת-כַּנּוֹ--לְקַדְּשָׁם",
         "ואלחוץ' ומקעדה וקדסהם",
         "and the laver and its bases, and consecrated them."),
    ],
    12: [
        ("וַיִּצֹק מִשֶּׁמֶן הַמִּשְׁחָה עַל רֹאשׁ אַהֲרֹן וַיִּמְשַׁח אֹתוֹ לְקַדְּשׁוֹ",
         "וצב מן דהן אלמסוחייה. עלי' ראס הרון. ומסחה וקדסה",
         "And he poured from the anointing oil upon the head of Aaron, and anointed him and consecrated him."),
    ],
    13: [
        ("וַיַּקְרֵב מֹשֶׁה אֶת-בְּנֵי אַהֲרֹן וַיַּלְבִּשֵׁם כֻּתֳּנֹת וַיַּחְגֹּר אֹתָם אַבְנֵט",
         "וקרב מוסי' בני הרון. ואלבסהם תואניא וקלדהם בזנאניר.",
         "And Moses presented the sons of Aaron, and clothed them with tunics and girded them with sashes,"),
        ("וַיַּחֲבֹשׁ לָהֶם מִגְבָּעוֹת--כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "וצ'מדהם בקלאנס. כמא אמר אללה מוסי'",
         "and bound their heads with caps — as God had commanded Moses."),
    ],
    14: [
        ("וַיַּגֵּשׁ אֵת פַּר הַחַטָּאת וַיִּסְמֹךְ אַהֲרֹן וּבָנָיו אֶת-יְדֵיהֶם עַל-רֹאשׁ פַּר הַחַטָּאת",
         "ת'ם קדם רת' אלדכוה. ואסנד הרון ובניה. אידיהם עלי' ראסה",
         "Then he presented the bull of the purification-offering, and Aaron and his sons laid their hands upon its head."),
    ],
    15: [
        ("וַיִּשְׁחָט וַיִּקַּח מֹשֶׁה אֶת-הַדָּם וַיִּתֵּן עַל-קַרְנוֹת הַמִּזְבֵּחַ סָבִיב בְּאֶצְבָּעוֹ וַיְחַטֵּא אֶת-הַמִּזְבֵּחַ",
         "פד'בחה ואכ'ד' מוסי' מן דמה וגעל. עלי' ארכאן אלמד'בח מסתדירא באצבעה. וד'כאה.",
         "And he slaughtered it, and Moses took some of its blood and placed it, going around with his finger, upon the horns of the altar, and purified it;"),
        ("וְאֶת-הַדָּם יָצַק אֶל-יְסוֹד הַמִּזְבֵּחַ וַיְקַדְּשֵׁהוּ לְכַפֵּר עָלָיו",
         "ובאקי אלדם. צבה ענד אסאסה. וקדסה ואסתג'פר ענה",
         "and the remaining blood he poured at its base, and consecrated it and sought atonement for it."),
    ],
    16: [
        ("וַיִּקַּח אֶת-כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב וְאֵת יֹתֶרֶת הַכָּבֵד וְאֶת-שְׁתֵּי הַכְּלָיֹת וְאֶת-חֶלְבְּהֶן וַיַּקְטֵר מֹשֶׁה הַמִּזְבֵּחָה",
         "ואכ'ד' גמיע אלת'רב אלד'י עלי' אלגוף. וזיאדה' אלכבד. ואלכלותין ושחמהמא. וקתרה עלי' אלמד'בח",
         "And he took all the fat that was upon the belly, and the lobe of the liver, and the two kidneys with their fat, and burned it as smoke upon the altar."),
    ],
    17: [
        ("וְאֶת-הַפָּר וְאֶת-עֹרוֹ וְאֶת-בְּשָׂרוֹ וְאֶת-פִּרְשׁוֹ--שָׂרַף בָּאֵשׁ מִחוּץ לַמַּחֲנֶה כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "ואלרת' מע גלדה ולחמה מע פרתה אחרקה באלנאר. כ'ארג אלעסכר. כמא אמר אללה מוסי'",
         "But the bull, with its hide and its flesh and its dung, he burned with fire outside the camp — as God had commanded Moses."),
    ],
    18: [
        ("וַיַּקְרֵב אֵת אֵיל הָעֹלָה וַיִּסְמְכוּ אַהֲרֹן וּבָנָיו אֶת-יְדֵיהֶם--עַל-רֹאשׁ הָאָיִל",
         "ת'ם קדם כבש אלצעידה. פאסנד הרון ובניה. אידיהם עלי' ראסה",
         "Then he presented the ram of the burnt-offering, and Aaron and his sons laid their hands upon its head."),
    ],
    19: [
        ("וַיִּשְׁחָט וַיִּזְרֹק מֹשֶׁה אֶת-הַדָּם עַל-הַמִּזְבֵּחַ סָבִיב",
         "פד'בחה. ונצ'ח מוסי' אלדם. עלי' אלמד'בח מסתדירא",
         "And he slaughtered it, and Moses sprinkled the blood upon the altar all around."),
    ],
    20: [
        ("וְאֶת-הָאַיִל--נִתַּח לִנְתָחָיו וַיַּקְטֵר מֹשֶׁה אֶת-הָרֹאשׁ וְאֶת-הַנְּתָחִים וְאֶת-הַפָּדֶר",
         "ועצ'א מוסי' אלכבש אעצ'אא. וקתר אלראס. ואלאעצ'א ואלקצבה",
         "And Moses cut the ram into its pieces, and burned as smoke the head, and the pieces, and the backbone."),
    ],
    21: [
        ("וְאֶת-הַקֶּרֶב וְאֶת-הַכְּרָעַיִם רָחַץ בַּמָּיִם",
         "ואלבטן ואלאכארע ג'סלהא באלמא.",
         "And the belly and the legs he washed with water,"),
        ("וַיַּקְטֵר מֹשֶׁה אֶת-כָּל-הָאַיִל הַמִּזְבֵּחָה עֹלָה הוּא לְרֵיחַ-נִיחֹחַ אִשֶּׁה הוּא לַיהוָה כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "וקתר מוסי' גמיע אלכבש עלי' אלמד'בח. הו צעידה מקבול מרצ'י קרבאן הו ללה. כמא אמר אללה מוסי'",
         "and Moses burned the whole ram as smoke upon the altar — it is an accepted, pleasing burnt-offering, an offering it is to God — as God had commanded Moses."),
    ],
    22: [
        ("וַיַּקְרֵב אֶת-הָאַיִל הַשֵּׁנִי אֵיל הַמִּלֻּאִים וַיִּסְמְכוּ אַהֲרֹן וּבָנָיו אֶת-יְדֵיהֶם--עַל-רֹאשׁ הָאָיִל",
         "ת'ם קדם אלכבש אלת'אני. כבש אלכמאל. ואסנד הרון ובניה. אידיהם עלי' ראסה",
         "Then he presented the second ram — the ram of completion — and Aaron and his sons laid their hands upon its head."),
    ],
    23: [
        ("וַיִּשְׁחָט--וַיִּקַּח מֹשֶׁה מִדָּמוֹ וַיִּתֵּן עַל-תְּנוּךְ אֹזֶן-אַהֲרֹן הַיְמָנִית",
         "פד'בחה מוסי'. ואכ'ד' מן דמה וגעל. עלי' שחמה' אד'ן הרון אלימני.",
         "And Moses slaughtered it, and took some of its blood and placed it upon the cartilage of the lobe of Aaron's right ear,"),
        ("וְעַל-בֹּהֶן יָדוֹ הַיְמָנִית וְעַל-בֹּהֶן רַגְלוֹ הַיְמָנִית",
         "ועלי אבהאם ידה אלימני. ואבהאם רגלה אלימני",
         "and upon the thumb of his right hand, and upon the thumb of his right foot."),
    ],
    24: [
        ("וַיַּקְרֵב אֶת-בְּנֵי אַהֲרֹן וַיִּתֵּן מֹשֶׁה מִן-הַדָּם עַל-תְּנוּךְ אָזְנָם הַיְמָנִית וְעַל-בֹּהֶן יָדָם הַיְמָנִית וְעַל-בֹּהֶן רַגְלָם הַיְמָנִית",
         "ת'ם קדם בני הרון. וגעל מן אלדם עלי' שחמאת אד'אנהם אלאיאמן. ועלי אבהאם אידיהם אלאיאמן. ואבהאם ארגלהם אלאיאמן.",
         "Then he presented the sons of Aaron, and placed some of the blood upon the lobes of their right ears, and upon the thumbs of their right hands, and upon the thumbs of their right feet;"),
        ("וַיִּזְרֹק מֹשֶׁה אֶת-הַדָּם עַל-הַמִּזְבֵּחַ סָבִיב",
         "ורש מוסי' אלדם. עלי' אלמד'בח מסתדירא",
         "and Moses sprinkled the blood upon the altar all around."),
    ],
    25: [
        ("וַיִּקַּח אֶת-הַחֵלֶב וְאֶת-הָאַלְיָה וְאֶת-כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב וְאֵת יֹתֶרֶת הַכָּבֵד וְאֶת-שְׁתֵּי הַכְּלָיֹת וְאֶת-חֶלְבְּהֶן וְאֵת שׁוֹק הַיָּמִין",
         "ואכ'ד' אלת'רב ואלאליה. וגמיע אלשחם אלד'י עלי' אלגוף. וזיאדה' אלכבד. ואלכלותין ושחמהמא. ואלסאק אלאימן",
         "And he took the caul and the fat-tail, and all the fat that was upon the belly, and the lobe of the liver, and the two kidneys with their fat, and the right leg."),
    ],
    26: [
        ("וּמִסַּל הַמַּצּוֹת אֲשֶׁר לִפְנֵי יְהוָה לָקַח חַלַּת מַצָּה אַחַת",
         "ומן סל אלפטיר. אלד'י בין ידי אללה. אכ'ד' גרדקה ואחדה.",
         "And from the basket of unleavened bread which was before God, he took one loaf,"),
        ("וְרָקִיק אֶחָד וַיָּשֶׂם עַל-הַחֲלָבִים וְעַל שׁוֹק הַיָּמִין",
         "וצייר ד'אלך עלי' אלשחום. ואלסאק אלאימן",
         "and set that upon the fats and the right leg."),
    ],
    27: [
        ("וַיִּתֵּן אֶת-הַכֹּל--עַל כַּפֵּי אַהֲרֹן וְעַל כַּפֵּי בָנָיו וַיָּנֶף אֹתָם תְּנוּפָה לִפְנֵי יְהוָה",
         "וגעל אלכל. עלי' ידי הרון. ועלי' ידי בניה. וחרכהא תחריכא בין ידי אללה",
         "And he placed it all upon the hands of Aaron and upon the hands of his sons, and waved them in a waving before God."),
    ],
    28: [
        ("וַיִּקַּח מֹשֶׁה אֹתָם מֵעַל כַּפֵּיהֶם וַיַּקְטֵר הַמִּזְבֵּחָה עַל-הָעֹלָה",
         "ת'ם אכ'ד'הא מוסי' מן פוק ידיהם. וקתרהא עלי' אלמד'בח מע אלצעידה.",
         "Then Moses took them from upon their hands, and burned them as smoke upon the altar with the burnt-offering —"),
        ("מִלֻּאִים הֵם לְרֵיחַ נִיחֹחַ אִשֶּׁה הוּא לַיהוָה",
         "לאנהא קרבאן כמאל ללה. מקבול מרצ'י",
         "for it is an offering of completion to God, accepted and pleasing."),
    ],
    29: [
        ("וַיִּקַּח מֹשֶׁה אֶת-הֶחָזֶה וַיְנִיפֵהוּ תְנוּפָה לִפְנֵי יְהוָה",
         "ת'ם אכ'ד מוסי' אלקץ. וחרכה תחריכא בין ידי אללה.",
         "Then Moses took the breast and waved it in a waving before God —"),
        ("מֵאֵיל הַמִּלֻּאִים לְמֹשֶׁה הָיָה לְמָנָה כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "וכאן למוסי נציבא. מן כבש אלכמאל. כמא אמרה אללה",
         "and it was Moses's portion from the ram of completion — as God had commanded him."),
    ],
    30: [
        ("וַיִּקַּח מֹשֶׁה מִשֶּׁמֶן הַמִּשְׁחָה וּמִן-הַדָּם אֲשֶׁר עַל-הַמִּזְבֵּחַ וַיַּז עַל-אַהֲרֹן עַל-בְּגָדָיו וְעַל-בָּנָיו וְעַל-בִּגְדֵי בָנָיו אִתּוֹ",
         "ת'ם אכ'ד' מוסי' מן דהן אלמסוחייה. ומן אלדם אלד'י עלי' אלמד'בח. פנצ'ח עלי'הרון ות'יאבה. ובניה. ות'יאב בניה מעה.",
         "Then Moses took from the anointing oil and from the blood that was upon the altar, and sprinkled it upon Aaron and his garments, and upon his sons and the garments of his sons with him;"),
        ("וַיְקַדֵּשׁ אֶת-אַהֲרֹן אֶת-בְּגָדָיו וְאֶת-בָּנָיו וְאֶת-בִּגְדֵי בָנָיו אִתּוֹ",
         "פקדסה ות'יאבה. ובניה. ות'יאב בניה מעה",
         "and he consecrated him and his garments, and his sons and the garments of his sons with him."),
    ],
    31: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן וְאֶל-בָּנָיו בַּשְּׁלוּ אֶת-הַבָּשָׂר פֶּתַח אֹהֶל מוֹעֵד וְשָׁם תֹּאכְלוּ אֹתוֹ",
         "וקאל מוסי' להרון ובניה. אטבכו הד'י אללחם ענד באב כ'בא אלמחצ'ר. ות'ם איצ'א פכלוה.",
         "And Moses said to Aaron and his sons: 'Cook this meat at the entrance of the tent of the appointed meeting, and there also eat it —"),
        ("וְאֶת-הַלֶּחֶם אֲשֶׁר בְּסַל הַמִּלֻּאִים כַּאֲשֶׁר צִוֵּיתִי לֵאמֹר אַהֲרֹן וּבָנָיו יֹאכְלֻהוּ",
         "מע אלכ'בז אלד'י פי סל אלכמאל. כמא אמרת וקלת. הרון ובניה יאכלונה",
         "together with the bread that is in the basket of completion — as I commanded and said: Aaron and his sons shall eat it.'"),
    ],
    32: [
        ("וְהַנּוֹתָר בַּבָּשָׂר וּבַלָּחֶם--בָּאֵשׁ תִּשְׂרֹפוּ",
         "ומא פצ'ל מן אללחם ואלכ'בז. אחרקוה באלנאר",
         "'And what remains of the meat and the bread — burn it with fire.'"),
    ],
    33: [
        ("וּמִפֶּתַח אֹהֶל מוֹעֵד לֹא תֵצְאוּ שִׁבְעַת יָמִים--עַד יוֹם מְלֹאת יְמֵי מִלֻּאֵיכֶם",
         "} ומן באב כ'בא אלמחצ'ר. לא תכ'ר'גו סבעה' איאם. אלי'. יום פראג'. איאם כמאלכם.",
         "'And from the entrance of the tent of the appointed meeting you shall not go out for seven days, until the day of the completion of the days of your induction —"),
        ("כִּי שִׁבְעַת יָמִים יְמַלֵּא אֶת-יֶדְכֶם",
         "פאן סבעה' אייאם. ת'כמל ואגבתכם",
         "for seven days you shall fulfill your obligations.'"),
    ],
    34: [
        ("כַּאֲשֶׁר עָשָׂה בַּיּוֹם הַזֶּה--צִוָּה יְהוָה לַעֲשֹׂת לְכַפֵּר עֲלֵיכֶם",
         "כמא עמל בכם אליום. כד'אך אמר אללה. אן יעמל ויסתג'פר ענכם",
         "'As was done for you today, so God has commanded that it be done, to seek atonement for you.'"),
    ],
    35: [
        ("וּפֶתַח אֹהֶל מוֹעֵד תֵּשְׁבוּ יוֹמָם וָלַיְלָה שִׁבְעַת יָמִים",
         "וענד באב כ'בא אלמחצ'ר. תגלסו לילא ונהארא סבעה' אייאם.",
         "'And at the entrance of the tent of the appointed meeting you shall sit there, night and day, seven days,"),
        ("וּשְׁמַרְתֶּם אֶת-מִשְׁמֶרֶת יְהוָה וְלֹא תָמוּתוּ כִּי-כֵן צֻוֵּיתִי",
         "ותחפצ'ו חפץ' אללה ולא תהלכו לאן כד'א אמרת",
         "and you shall observe the charge of God — and you shall not perish — for thus was I commanded.'"),
    ],
    36: [
        ("וַיַּעַשׂ אַהֲרֹן וּבָנָיו--אֵת כָּל-הַדְּבָרִים אֲשֶׁר-צִוָּה יְהוָה בְּיַד-מֹשֶׁה",
         "ועמל הרון ובניה. בגמיע אלאמור. אלתי אמר אללה מוסי'",
         "And Aaron and his sons did all the matters which God had commanded Moses."),
    ],
}
