"""Hand-authored alignment triples for Vayikra chapter 12."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר",
         "מר בני אסראיל קאילא",
         "Instruct the sons of Israel, saying:"),
        ("אִשָּׁה כִּי תַזְרִיעַ וְיָלְדָה זָכָר",
         "אייה' אמראה עלקת. פולדת ד'כרא",
         "Any woman who has conceived and borne a male"),
        ("וְטָמְאָה שִׁבְעַת יָמִים כִּימֵי נִדַּת דְּו‍ֹתָהּ תִּטְמָא",
         "פלתנגס סבעה' איאם. כאיאם בעד חיצ'תהא יכון חכם נגאסתהא",
         "she shall be impure seven days; as in the days following her menstrual separation shall be the ruling of her impurity."),
    ],
    3: [
        ("וּבַיּוֹם הַשְּׁמִינִי יִמּוֹל בְּשַׂר עָרְלָתוֹ",
         "ופי אליום אלת'אמן. תכ'תן קלפה' אחלילה",
         "And on the eighth day, the foreskin of his member shall be circumcised."),
    ],
    4: [
        ("וּשְׁלֹשִׁים יוֹם וּשְׁלֹשֶׁת יָמִים תֵּשֵׁב בִּדְמֵי טָהֳרָה",
         "ות'לאת'ה ות'לאתין יומא. תקים פי דם אלטהר",
         "And thirty-three days she shall remain in the blood of purification;"),
        ("בְּכָל-קֹדֶשׁ לֹא-תִגָּע וְאֶל-הַמִּקְדָּשׁ לֹא תָבֹא",
         "ולא תלאמס שייא מן אלאקדאס. ולא תדכל אלי' אלקדס",
         "she shall not touch anything of the sacred things, nor enter into the sanctuary,"),
        ("עַד-מְלֹאת יְמֵי טָהֳרָהּ",
         "אלי' כמאל איאם טהרהא",
         "until the completion of the days of her purification."),
    ],
    5: [
        ("וְאִם-נְקֵבָה תֵלֵד וְטָמְאָה שְׁבֻעַיִם כְּנִדָּתָהּ",
         "פאן ולדת אנתי'. פלתנגס אסבועין כחכם חיצ'תהא",
         "But if she bears a female, she shall be impure two weeks according to the ruling of her menstrual separation;"),
        ("וְשִׁשִּׁים יוֹם וְשֵׁשֶׁת יָמִים תֵּשֵׁב עַל-דְּמֵי טָהֳרָה",
         "וסתה וסתין יומא. תקים עלי' דם אלטהר",
         "and sixty-six days she shall remain upon the blood of purification."),
    ],
    6: [
        ("וּבִמְלֹאת יְמֵי טָהֳרָהּ לְבֵן אוֹ לְבַת",
         "וענד תמאם איאם טהרהא. לאבן כאן או אבנה",
         "And upon the completion of the days of her purification — whether for a son or for a daughter —"),
        ("תָּבִיא כֶּבֶשׂ בֶּן-שְׁנָתוֹ לְעֹלָה וּבֶן-יוֹנָה אוֹ-תֹר לְחַטָּאת",
         "תאתי בכ'רוף אבן סנתה לאלצעידה. ופרך' חמאם או שפנינא לאלד'כוה",
         "she shall bring a yearling lamb for the ascent-offering, and a young pigeon or a turtledove for the purification-offering,"),
        ("אֶל-פֶּתַח אֹהֶל-מוֹעֵד אֶל-הַכֹּהֵן",
         "אלי' באב כ'בא אלמחצ'ר. אלי' אלאמם",
         "to the entrance of the tent of the assembly, to the imām."),
    ],
    7: [
        ("וְהִקְרִיבוֹ לִפְנֵי יְהוָה וְכִפֶּר עָלֶיהָ",
         "ויקרבה בין ידי אללה ויסתג'פר ענהא",
         "And he shall present it before God, and shall seek atonement on her behalf;"),
        ("וְטָהֲרָה מִמְּקֹר דָּמֶיהָ",
         "ותטהר מן נביע דמהא",
         "and she shall be purified from the flowing of her blood."),
        ("זֹאת תּוֹרַת הַיֹּלֶדֶת לַזָּכָר אוֹ לַנְּקֵבָה",
         "הד'ה שריעה' אלואלדה. ד'כר או אנת'י",
         "This is the law of the woman who gives birth, whether to a male or a female."),
    ],
    8: [
        ("וְאִם-לֹא תִמְצָא יָדָהּ דֵּי שֶׂה",
         "ואן לם תנאל ידהא מקדאר שאה",
         "And if her hand does not attain the value of a ewe,"),
        ("וְלָקְחָה שְׁתֵּי-תֹרִים אוֹ שְׁנֵי בְּנֵי יוֹנָה אֶחָד לְעֹלָה וְאֶחָד לְחַטָּאת",
         "פלתאכד' שפנינין. או פרכ'י חמאם. אחדהמא לאלצעידה ואלאכ'ר לאלד'כוה",
         "then she shall take two turtledoves or two young pigeons — one of them for the ascent-offering and the other for the purification-offering;"),
        ("וְכִפֶּר עָלֶיהָ הַכֹּהֵן וְטָהֵרָה",
         "ויסתג'פר ענהא. אלאמאם ותטהר",
         "and the imām shall seek atonement on her behalf, and she shall be purified."),
    ],
}
