"""Hand-authored alignment triples for Vayikra chapter 7.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "והד'א", "And these are"),
        ("תּוֹרַת", "שריעה'", "the ordinances of"),
        ("הָאָשָׁם", "קרבאן אלאת'ם", "the guilt-offering"),
        ("הוּא", "הו", "it"),
        (None, "איצ'א", "too"),
        (None, "מן", "is among"),
        ("קֹדֶשׁ קָדָשִׁים", "כ'ואץ אלאקדאס", "the choicest of the consecrated things"),
    ],
    2: [
        (None, "פי", "In"),
        ("בִּמְקוֹם", "מוצ'ע", "the place"),
        ("יִשְׁחֲטוּ", "תד'בח", "where they slaughter"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the elevation-offering"),
        ("יִשְׁחֲטוּ", "יד'בח", "they shall slaughter"),
        ("אֶת-הָאָשָׁם", "קרבאן אלאת'ם", "the guilt-offering"),
        ("וְאֶת-דָּמוֹ", "ודמה", "and its blood"),
        ("יִזְרֹק", "ירש", "shall be sprinkled"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    3: [
        (None, "וגמיע", "And all"),
        ("חֶלְבּוֹ", "שחמה", "its fat"),
        ("יַקְרִיב", "ירפע", "shall be lifted"),
        ("מִמֶּנּוּ", "מנה", "from it"),
        ("הָאַלְיָה", "אלאליה", "the broad tail"),
        ("וְאֶת-הַחֵלֶב", "ואלת'רב", "and the suet"),
        ("הַמְכַסֶּה", "אלמג'טי", "that covers"),
        ("אֶת-הַקֶּרֶב", "אלגוף", "the innards"),
    ],
    4: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת", "ואלכלותין", "and the two kidneys"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("אֲשֶׁר עֲלֵיהֶן", "אלד'י עליהמא", "that is upon them"),
        ("אֲשֶׁר עַל-הַכְּסָלִים", "אלד'י עלי' אלאחשא", "which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת", "וזיאדה'", "and the lobe of"),
        ("עַל-הַכָּבֵד", "אלכבד", "the liver"),
        ("עַל-הַכְּלָיֹת", "מע אלכלי'", "along with the kidneys"),
        ("יְסִירֶנָּה", "ינזעהא", "he shall remove them"),
    ],
    5: [
        ("וְהִקְטִיר", "ויקתרהא", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall burn them"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("אִשֶּׁה", "קרבאנא", "as an offering"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "כד'אך", "thus"),
        (None, "מא", "is"),
        ("אָשָׁם", "יציר קרבאן אלאת'ם", "what the guilt-offering becomes"),
    ],
    6: [
        ("כָּל-זָכָר", "כל ד'כר", "Every male"),
        ("בַּכֹּהֲנִים", "מן אלאיימה", "among the imāms"),
        ("יֹאכְלֶנּוּ", "יאכלה", "may eat it"),
        (None, "פי", "in"),
        ("בְּמָקוֹם קָדוֹשׁ", "מוצ'ע מקדס", "a consecrated place"),
        ("יֵאָכֵל", "יוכל", "it shall be eaten"),
        (None, "לאנה", "for it is"),
        (None, "מן", "among"),
        ("קֹדֶשׁ קָדָשִׁים", "כ'ואץ אלאקדאס", "the choicest of the consecrated things"),
    ],
    7: [
        ("כָּאָשָׁם", "קרבאן אלאת'ם", "The guilt-offering"),
        ("כַּחַטָּאת", "כאלדכוה", "is like the sin-offering"),
        ("תּוֹרָה אַחַת", "שריעה ואחדה", "one ordinance"),
        ("לָהֶם", "להמא", "for them both"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("אֲשֶׁר יְכַפֶּר-בּוֹ", "אלד'י יכפר בה", "who makes atonement through it"),
        ("לוֹ יִהְיֶה", "לה יכון", "to him it shall belong"),
    ],
    8: [
        ("וְהַכֹּהֵן", "ואלאמאם", "And the imām"),
        ("הַמַּקְרִיב", "אלמקרב", "who offers"),
        ("עֹלַת", "צעידה", "an elevation-offering"),
        ("אִישׁ", "ען אמר", "on behalf of a man"),
        ("עוֹר הָעֹלָה", "פגלדהא", "its hide"),
        ("אֲשֶׁר הִקְרִיב", "בעד תקריבהא", "after its having been offered"),
        ("לַכֹּהֵן לוֹ יִהְיֶה", "יכון לה", "shall be his"),
    ],
    10: [
        ("וְכָל-מִנְחָה", "וכל הדייה", "And every gift-offering"),
        ("בְלוּלָה-בַשֶּׁמֶן", "מלתותה בדהן", "mixed with oil"),
        (None, "או", "or"),
        ("וַחֲרֵבָה", "גאפה", "dry"),
        ("לְכָל-בְּנֵי אַהֲרֹן תִּהְיֶה", "לגמיע בני הרון תכון", "shall belong to all the sons of Aaron"),
        ("אִישׁ כְּאָחִיו", "אלואחד כאלאכ'ר", "one the same as another"),
    ],
    11: [
        (None, "והד'א", "And these are"),
        ("תּוֹרַת", "שריעה'", "the ordinances of"),
        ("זֶבַח הַשְּׁלָמִים", "ד'בח אלסלאמה", "the peace-offering sacrifice"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("יַקְרִיב", "יקרבה", "one offers"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    12: [
        (None, "אן", "If"),
        ("יַקְרִיבֶנּוּ", "קרבה", "he offers it"),
        ("עַל-תּוֹדָה", "עלי' שכר", "as a thanksgiving"),
        (None, "פיקרב", "then he shall offer"),
        (None, "מעה", "with it"),
        ("חַלּוֹת מַצּוֹת", "גראדק פטיר", "loaves of unleavened bread"),
        ("בְּלוּלֹת בַּשֶּׁמֶן", "מלתותה בדהן", "mixed with oil"),
        ("וּרְקִיקֵי מַצּוֹת", "ורקאק פטיר", "and wafers of unleavened bread"),
        ("מְשֻׁחִים בַּשָּׁמֶן", "ממסוחה בדהן", "smeared with oil"),
        ("וְסֹלֶת", "וסמד", "fine flour"),
        ("מֻרְבֶּכֶת", "סתותייה", "and layers of"),
        ("חַלֹּת בְּלוּלֹת בַּשָּׁמֶן", "גראדק מלתותה בדהן", "loaves mixed with oil"),
    ],
    13: [
        ("עַל-חַלֹּת לֶחֶם חָמֵץ", "מע גראדק כ'בז כ'מיר", "Together with loaves of leavened bread"),
        ("יַקְרִיב", "יקרב", "he shall offer"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering"),
        ("עַל-זֶבַח תּוֹדַת שְׁלָמָיו", "מע ד'בח שכר סלאמתה", "with the thanksgiving sacrifice of his peace-offering"),
    ],
    14: [
        (None, "פליקרב", "And he shall offer"),
        ("מִמֶּנּוּ", "מן ד'אלך", "from it"),
        ("אֶחָד", "רג'יפא ואחדא", "one loaf"),
        ("מִכָּל-קָרְבָּן", "מן כל קרבאן", "from each offering"),
        ("תְּרוּמָה", "רפיעה", "as an elevation"),
        ("לַיהוָה", "ללה", "to God"),
        ("לַכֹּהֵן", "לאלאמאם", "to the imām"),
        ("הַזֹּרֵק", "אלד'י ינצ'ח", "who sprinkles"),
        (None, "מן", "the blood of"),
        ("אֶת-דַּם הַשְּׁלָמִים", "דם אלסלאמה", "the peace-offering"),
        ("לוֹ יִהְיֶה", "לה יכון", "to him it shall belong"),
    ],
    15: [
        ("וּבְשַׂר", "ולחם", "And the flesh of"),
        ("זֶבַח תּוֹדַת שְׁלָמָיו", "ד'בח שכר אלסלאמה", "the thanksgiving sacrifice of the peace-offering"),
        (None, "פי", "on"),
        ("בְּיוֹם קָרְבָּנוֹ", "יום קרבאנה", "the day of its offering"),
        ("יֵאָכֵל", "יוכל", "shall be eaten"),
        ("לֹא-יַנִּיחַ", "לא יבקי", "he shall not leave"),
        ("מִמֶּנּוּ", "מנה", "any of it"),
        ("עַד-בֹּקֶר", "אלי' אלג'דאה", "until morning"),
    ],
    16: [
        (None, "ואן", "But if"),
        (None, "כאן", "be"),
        ("זֶבַח קָרְבָּנוֹ", "ד'בח קרבאנה", "the sacrifice of his offering"),
        ("נֶדֶר", "נד'רא", "a vow"),
        ("אוֹ", "או", "or"),
        ("נְדָבָה", "תברעא", "a freewill-offering"),
        (None, "פליוכל", "it shall be eaten"),
        (None, "פי", "on"),
        ("בְּיוֹם הַקְרִיבוֹ", "יום תקריבה לה", "the day of his offering it"),
        ("וּמִמָּחֳרָת", "ומן ג'ד", "and on the morrow"),
        ("וְהַנּוֹתָר", "מא פצ'ל", "what remains"),
        ("מִמֶּנּוּ", "מנה", "of it"),
        ("יֵאָכֵל", "יוכל", "shall be eaten"),
    ],
    17: [
        ("וְהַנּוֹתָר", "ואלפאצ'ל", "And what is left"),
        (None, "מן", "of"),
        ("מִבְּשַׂר הַזָּבַח", "לחם אלד'בח", "the flesh of the sacrifice"),
        (None, "פי", "on"),
        ("בַּיּוֹם הַשְּׁלִישִׁי", "אליום אלת'אלת'", "the third day"),
        (None, "פליחרק", "shall be burned"),
        ("בָּאֵשׁ", "באלנאר", "with fire"),
    ],
    18: [
        (None, "ואן", "And if"),
        ("הֵאָכֹל יֵאָכֵל", "אכל אכלא", "any of the flesh"),
        ("מִבְּשַׂר-זֶבַח שְׁלָמָיו", "מן לחם ד'בח אלסלאמה", "of the peace-offering sacrifice"),
        (None, "פי", "be eaten on"),
        ("בַּיּוֹם הַשְּׁלִישִׁי", "אליום אלת'לאת'", "the third day"),
        ("לֹא יֵרָצֶה", "פלא ירתצ'א", "it shall not be accepted"),
        ("הַמַּקְרִיב אֹתוֹ", "ואלמקרב לה", "and the one who offered it"),
        ("לֹא יֵחָשֵׁב לוֹ", "לא יחסב לה", "it shall not be counted to him"),
        (None, "בל", "but"),
        ("פִּגּוּל יִהְיֶה", "יכון כאלאכ'ס", "shall be as something abhorrent"),
        ("וְהַנֶּפֶשׁ", "ואי אנסאן", "and any person"),
        ("הָאֹכֶלֶת מִמֶּנּוּ", "אכל מנה", "who eats of it"),
        ("עֲו‍ֹנָהּ תִּשָּׂא", "פקד חמל וזרה", "shall have borne his burden of guilt"),
    ],
    19: [
        ("וְהַבָּשָׂר", "ולחם אלאקדאס", "And the flesh of the consecrated things"),
        (None, "אן", "if"),
        ("אֲשֶׁר-יִגַּע", "דנא", "it comes near"),
        (None, "בשי מן", "to anything of"),
        ("בְּכָל-טָמֵא", "אלנגאסאת", "the impurities"),
        ("לֹא יֵאָכֵל", "פלא יוכל", "it shall not be eaten"),
        (None, "בל", "but"),
        ("בָּאֵשׁ יִשָּׂרֵף", "יחרק באלנאר", "shall be burned with fire"),
        ("וְהַבָּשָׂר", "ואלטאהר", "and as for what is pure"),
        (None, "מנה", "of it"),
        ("כָּל-טָהוֹר", "פלא יאכלה אלא טאהר", "none but one who is pure shall eat it"),
    ],
    20: [
        (None, "ואי", "And any"),
        ("וְהַנֶּפֶשׁ", "אנסאן", "person"),
        ("אֲשֶׁר-תֹּאכַל", "אכל", "who eats"),
        ("בָּשָׂר", "לחמא", "flesh"),
        ("מִזֶּבַח הַשְּׁלָמִים", "מן ד'בח אלסלאמה", "from the peace-offering sacrifice"),
        ("אֲשֶׁר לַיהוָה", "אלד'י ללה", "that belongs to God"),
        ("וְטֻמְאָתוֹ", "ונגאסתה", "while his impurity"),
        ("עָלָיו", "עליה", "is upon him"),
        ("וְנִכְרְתָה", "פינקטע", "shall be cut off"),
        ("הַנֶּפֶשׁ הַהִוא", "ד'אלך אלאנסאן", "that person"),
        ("מֵעַמֶּיהָ", "מן בין קומה", "from among his people"),
    ],
    21: [
        (None, "ואי", "And any"),
        ("וְנֶפֶשׁ", "אנסאן", "person"),
        ("כִּי-תִגַּע", "לאמס", "who touches"),
        (None, "שייא", "anything"),
        ("בְּכָל-טָמֵא", "מן אלנגאסאת", "of the impurities"),
        ("בְּטֻמְאַת אָדָם", "בנגאסה' אנסאן", "whether the impurity of a human"),
        ("אוֹ", "או", "or"),
        ("בִּבְהֵמָה טְמֵאָה", "בבהימה נגסה", "an impure beast"),
        (None, "או", "or"),
        ("אוֹ בְּכָל-שֶׁקֶץ טָמֵא", "בשי מן אלדביב אלנגס", "anything of impure creeping things"),
        ("וְאָכַל", "ואכל", "and eats"),
        ("מִבְּשַׂר-זֶבַח הַשְּׁלָמִים", "מן לחם ד'בח אלסלאמה", "of the flesh of the peace-offering sacrifice"),
        ("אֲשֶׁר לַיהוָה", "אלד'י ללה", "that belongs to God"),
        ("וְנִכְרְתָה", "פינקטע", "shall be cut off"),
        ("הַנֶּפֶשׁ הַהִוא", "ד'אלך אלאנסאן", "that person"),
        ("מֵעַמֶּיהָ", "מן קומה", "from his people"),
    ],
    22: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי''", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    23: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        (None, "קאילא", "saying"),
        ("כָּל-חֵלֶב", "כל שחם", "All fat"),
        ("שׁוֹר", "בקר", "of cattle"),
        ("וְכֶשֶׂב", "וצ'אן", "and sheep"),
        (None, "ומאעז", "and goats"),
        ("לֹא תֹאכֵלוּ", "לא תאכלו", "you shall not eat"),
    ],
    24: [
        ("וְחֵלֶב נְבֵלָה", "ושחם אלנבילה", "And the fat of a carcass"),
        ("וְחֵלֶב טְרֵפָה", "ואלסקימה", "and the fat of a diseased animal"),
        ("יֵעָשֶׂה לְכָל-מְלָאכָה", "אסתעמלוה פי כל צנעה", "use it for any craft"),
        ("וְאָכֹל לֹא תֹאכְלֻהוּ", "ואכל לא תאכלוה", "but as food you shall not eat it"),
    ],
    25: [
        (None, "פאן", "For"),
        ("כָּל-אֹכֵל", "כל מן יאכל", "anyone who eats"),
        ("חֵלֶב", "שחמא", "any fat"),
        ("מִן-הַבְּהֵמָה", "מן אלבהאים", "of the beasts"),
        ("אֲשֶׁר יַקְרִיב", "אלתי יקרב", "from which an offering"),
        ("מִמֶּנָּה", "מנהא", "is brought"),
        ("אִשֶּׁה לַיהוָה", "קרבאנא ללה", "to God"),
        ("וְנִכְרְתָה", "ינקטע", "shall be cut off"),
        ("הַנֶּפֶשׁ הָאֹכֶלֶת", "ד'אלך אלאנסאן", "that person"),
        ("מֵעַמֶּיהָ", "מן בין קומה", "from among his people"),
    ],
    26: [
        ("וְכָל-דָּם", "וכל דם", "And all blood"),
        ("לֹא תֹאכְלוּ", "לא תאכלו", "you shall not eat"),
        (None, "פי", "in"),
        ("בְּכֹל מוֹשְׁבֹתֵיכֶם", "גמיע מסאכנכם", "all your dwellings"),
        ("לָעוֹף", "מן אלטאיר", "whether of bird"),
        ("וְלַבְּהֵמָה", "ואלבהאים", "or of beasts"),
    ],
    27: [
        (None, "אי", "Any"),
        ("כָּל-נֶפֶשׁ", "אנסאן", "person"),
        ("אֲשֶׁר-תֹּאכַל", "אכל", "who eats"),
        (None, "שייא", "any"),
        ("כָּל-דָּם", "מן אלדם", "of the blood"),
        ("וְנִכְרְתָה", "ינקטע", "shall be cut off"),
        ("הַנֶּפֶשׁ הַהִוא", "ד'אלך אלאנסאן", "that person"),
        ("מֵעַמֶּיהָ", "מן בין קומה", "from among his people"),
    ],
    28: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    29: [
        (None, "כ'אטב", "Address"),
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        (None, "וקל", "and say"),
        (None, "להם", "to them"),
        ("הַמַּקְרִיב", "אלמקרב", "He who offers"),
        ("אֶת-זֶבַח שְׁלָמָיו", "ד'בח אלסלאמה", "the peace-offering sacrifice"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "הו אלד'י", "he is the one who"),
        ("יָבִיא", "יאתי", "shall bring"),
        ("אֶת-קָרְבָּנוֹ", "בקרבאנה", "his offering"),
        (None, "ללה", "to God"),
        ("מִזֶּבַח שְׁלָמָיו", "מן ד'בח סלאמתה", "from the sacrifice of his peace-offering"),
    ],
    30: [
        ("יָדָיו", "ידאה", "His own hands"),
        ("תְּבִיאֶינָה", "תחמל", "shall carry"),
        ("אֵת אִשֵּׁי יְהוָה", "קראבין אללה", "the offerings of God"),
        ("אֶת-הַחֵלֶב", "אלשחם", "the fat"),
        ("עַל-הֶחָזֶה", "מע אלקץ", "together with the breast"),
        ("יְבִיאֶנּוּ", "יאתי מעה", "he shall bring with it"),
        ("תְּנוּפָה", "פיחרכה תחריכא", "and he shall wave it as a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
    ],
    31: [
        ("וְהִקְטִיר", "ויקתר", "And the imām"),
        ("הַכֹּהֵן", "אלאמאם", "shall burn"),
        ("אֶת-הַחֵלֶב", "אלשחם", "the fat"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        ("וְהָיָה", "ויציר", "and"),
        ("הֶחָזֶה", "אלקץ", "the breast"),
        ("לְאַהֲרֹן", "להרון", "shall become Aaron's"),
        ("וּלְבָנָיו", "ובניה", "and his sons'"),
    ],
    32: [
        ("וְאֵת שׁוֹק הַיָּמִין", "ואלסאק אלאימן", "And the right haunch"),
        ("תִּתְּנוּ", "אעטוה", "give it"),
        ("תְרוּמָה", "רפיעה", "as an elevation"),
        ("לַכֹּהֵן", "לאלאמאם", "to the imām"),
        ("מִזִּבְחֵי שַׁלְמֵיכֶם", "מן ד'באיח סלאמתכם", "from the sacrifices of your peace-offerings"),
    ],
    33: [
        ("הַמַּקְרִיב", "אלמקרב", "He among"),
        ("אֶת-דַּם הַשְּׁלָמִים", "דם אלסלאמה", "who offers the blood of the peace-offering"),
        ("וְאֶת-הַחֵלֶב", "ואלשחם", "and the fat"),
        ("מִבְּנֵי אַהֲרֹן", "מן בני הרון", "the sons of Aaron"),
        ("לוֹ תִהְיֶה", "לה יכון", "to him shall belong"),
        ("שׁוֹק הַיָּמִין", "סאק אלאימן", "the right haunch"),
        ("לְמָנָה", "נציבא", "as his portion"),
    ],
    34: [
        (None, "לאן", "For"),
        ("אֶת-חֲזֵה הַתְּנוּפָה", "קץ אלתחריך", "the breast of the waving"),
        ("וְאֵת שׁוֹק הַתְּרוּמָה", "וסאק אלרפיעה", "and the haunch of the elevation"),
        ("לָקַחְתִּי", "אכ'ד'תהא", "I have taken"),
        ("מֵאֵת בְּנֵי-יִשְׂרָאֵל", "מן בני אסראיל", "from the sons of Israel"),
        ("מִזִּבְחֵי שַׁלְמֵיהֶם", "מן ד'באיח סלאמתהם", "from the sacrifices of their peace-offerings"),
        ("וָאֶתֵּן אֹתָם", "ואעטיתהא", "and I have given them"),
        ("לְאַהֲרֹן הַכֹּהֵן", "להרון אלאמאם", "to Aaron the imām"),
        ("וּלְבָנָיו", "ובניה", "and to his sons"),
        ("לְחָק-עוֹלָם", "רסם אלדהר", "an ordinance forever"),
        ("מֵאֵת בְּנֵי יִשְׂרָאֵל", "מן בני אסראיל", "from the sons of Israel"),
    ],
    35: [
        (None, "הד'ה", "This is"),
        ("מִשְׁחַת אַהֲרֹן", "חצה' הרון", "the portion of Aaron"),
        ("וּמִשְׁחַת בָּנָיו", "ובניה", "and his sons"),
        ("מֵאִשֵּׁי יְהוָה", "מן קראבין אללה", "from the offerings of God"),
        (None, "פי", "on"),
        ("בְּיוֹם", "יום", "the day"),
        ("הִקְרִיב אֹתָם", "קדמו", "they were presented"),
        ("לְכַהֵן", "ליאמו", "to serve as imāms"),
        ("לַיהוָה", "ללה", "before God"),
    ],
    36: [
        ("אֲשֶׁר צִוָּה יְהוָה", "אלד'י אמר אללה", "Which God commanded"),
        (None, "בהא", "to be given"),
        (None, "אן יעטוהא", "to them"),
        (None, "פי", "on"),
        ("בְּיוֹם מָשְׁחוֹ אֹתָם", "יום מסחהם", "the day of their anointing"),
        ("מֵאֵת בְּנֵי יִשְׂרָאֵל", "מן בני אסראיל", "from the sons of Israel"),
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "an ordinance forever"),
        ("לְדֹרֹתָם", "לאגיאלהם", "for their generations"),
    ],
    37: [
        (None, "הד'ה", "These are"),
        ("הַתּוֹרָה", "אלשריעה", "the ordinances"),
        ("לָעֹלָה", "לאלצעידה", "for the elevation-offering"),
        ("לַמִּנְחָה", "ואלהדייה", "and the gift-offering"),
        ("וְלַחַטָּאת", "ואלדכוה", "and the sin-offering"),
        ("וְלָאָשָׁם", "וקרבאן אלאת'ם", "and the guilt-offering"),
        ("וְלַמִּלּוּאִים", "וללכמאל", "and for the investiture"),
        ("וּלְזֶבַח הַשְּׁלָמִים", "ולד'בח אלסלאמה", "and for the peace-offering sacrifice"),
    ],
    38: [
        ("אֲשֶׁר צִוָּה יְהוָה", "אלתי אמר אללה", "which God"),
        (None, "בהא", "commanded"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
        ("בְּהַר סִינָי", "פי גבל סיני", "on the mountain of Sinai"),
        (None, "פי", "at"),
        ("בְּיוֹם צַוֹּתוֹ", "וקת אמר", "the time He commanded"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("לְהַקְרִיב", "אן יקרבו", "to offer"),
        ("אֶת-קָרְבְּנֵיהֶם", "קראבינהם", "their offerings"),
        ("לַיהוָה", "ללה", "to God"),
        ("בְּמִדְבַּר סִינָי", "פי ברייה' סיני", "in the wilderness of Sinai"),
    ],
}
