"""Hand-authored alignment triples for Vayikra chapter 17."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאֶל-בָּנָיו וְאֶל כָּל-בְּנֵי יִשְׂרָאֵל",
         "מר הרון ובניה וסאיר בני אסראיל.",
         "Command Aaron and his sons and the rest of the sons of Israel,"),
        ("וְאָמַרְתָּ אֲלֵיהֶם זֶה הַדָּבָר אֲשֶׁר-צִוָּה יְהוָה לֵאמֹר",
         "וקל להם. הדא אלאמר אלד'י אמר בה אללה",
         "and say to them: This is the matter which God has commanded."),
    ],
    3: [
        ("אִישׁ אִישׁ מִבֵּית יִשְׂרָאֵל אֲשֶׁר יִשְׁחַט שׁוֹר אוֹ-כֶשֶׂב אוֹ-עֵז בַּמַּחֲנֶה אוֹ אֲשֶׁר יִשְׁחַט מִחוּץ לַמַּחֲנֶה",
         "אי רגל מן בני אסראיל. יד'בח ת'ורא או כבשא. או ענזא פי אלעסכר. או פי כ'ארגה",
         "Any man from the sons of Israel who slaughters an ox or a ram or a goat — in the camp or outside of it —"),
    ],
    4: [
        ("וְאֶל-פֶּתַח אֹהֶל מוֹעֵד לֹא הֱבִיאוֹ לְהַקְרִיב קָרְבָּן לַיהוָה לִפְנֵי מִשְׁכַּן יְהוָה",
         "ולם יאתי בה אלי' באב כ'בא אלמחצ'ר. פיקרבה אד' הו קרבאן ללה בין ידי מסכנה.",
         "and did not bring it to the entrance of the tent of the assembly to offer it, since it is an offering to God before His dwelling —"),
        ("דָּם יֵחָשֵׁב לָאִישׁ הַהוּא דָּם שָׁפָךְ וְנִכְרַת הָאִישׁ הַהוּא מִקֶּרֶב עַמּוֹ",
         "פהו יחסב עליה כמן קד ספך' דם אנסאן. וינקטע ד'אלך אלאנסאן מן בין קומה",
         "it shall be reckoned against him as one who has shed human blood, and that person shall be cut off from among his people."),
    ],
    5: [
        ("לְמַעַן אֲשֶׁר יָבִיאוּ בְּנֵי יִשְׂרָאֵל אֶת-זִבְחֵיהֶם",
         "לכי יאתון בני אסראיל. בד'באיחהם",
         "This is so that the sons of Israel may bring their sacrifices —"),
        ("אֲשֶׁר הֵם זֹבְחִים עַל-פְּנֵי הַשָּׂדֶה",
         "אלתי לעלהם אן יד'בחונהא עלי' וגה אלצחרא.",
         "those which they might slaughter upon the face of the wilderness —"),
        ("וֶהֱבִיאֻם לַיהוָה אֶל-פֶּתַח אֹהֶל מוֹעֵד אֶל-הַכֹּהֵן וְזָבְחוּ זִבְחֵי שְׁלָמִים לַיהוָה--אוֹתָם",
         "פיגו בהא בין ידי אללה. אלי' באב כ'בא אלמחצ'ר אלי' אלאמאם. פיד'בחוהא ד'באיח סלאמה ללה",
         "and bring them before God, to the entrance of the tent of the assembly, to the priest, and slaughter them as peace-offerings to God."),
    ],
    6: [
        ("וְזָרַק הַכֹּהֵן אֶת-הַדָּם עַל-מִזְבַּח יְהוָה פֶּתַח אֹהֶל מוֹעֵד",
         "וירש אלאמאם דמהא עלי' מד'בח אללה. אלד'י ענד באב כ'בא אלמחצ'ר.",
         "And the priest shall sprinkle their blood upon the altar of God which is at the entrance of the tent of the assembly,"),
        ("וְהִקְטִיר הַחֵלֶב לְרֵיחַ נִיחֹחַ לַיהוָה",
         "ויקתר שחמהא. מקבולא מרצ'ייא ללה",
         "and burn their fat — acceptable and pleasing to God."),
    ],
    7: [
        ("וְלֹא-יִזְבְּחוּ עוֹד אֶת-זִבְחֵיהֶם לַשְּׂעִירִם אֲשֶׁר הֵם זֹנִים אַחֲרֵיהֶם",
         "ולא יד'בחו אבדא ד'באיחהם. לאלשיאטין. אלד'י הם יטגון פי תבעהא.",
         "And they shall nevermore slaughter their sacrifices to the demons, after which they go astray in following them."),
        ("חֻקַּת עוֹלָם תִּהְיֶה-זֹּאת לָהֶם לְדֹרֹתָם",
         "פיכון ד'אלך להם. רסם אלדהר לאגיאלהם",
         "This shall be for them a statute forever, for their generations."),
    ],
    8: [
        ("וַאֲלֵהֶם תֹּאמַר--אִישׁ אִישׁ מִבֵּית יִשְׂרָאֵל וּמִן-הַגֵּר אֲשֶׁר-יָגוּר בְּתוֹכָם",
         "וקל להם. אי רגל מן בני אסראיל. ומן אלג'ריב אלדכ'יל פי מא בינהם.",
         "And say to them: Any man from the sons of Israel, or from the stranger who has come in among them,"),
        ("אֲשֶׁר-יַעֲלֶה עֹלָה אוֹ-זָבַח",
         "יחרק צעידה או ד'בחא",
         "who burns an offering or a sacrifice —"),
    ],
    9: [
        ("וְאֶל-פֶּתַח אֹהֶל מוֹעֵד לֹא יְבִיאֶנּוּ לַעֲשׂוֹת אֹתוֹ לַיהוָה",
         "ואלי' באב כ'בא אלמחצ'ר לם יאתי בה. ליקרבה כד'אך ללה.",
         "and did not bring it to the entrance of the tent of the assembly to offer it thus to God —"),
        ("וְנִכְרַת הָאִישׁ הַהוּא מֵעַמָּיו",
         "פינקטע ד'אלך אלאנסאן מן קומה",
         "that person shall be cut off from his people."),
    ],
    10: [
        ("וְאִישׁ אִישׁ מִבֵּית יִשְׂרָאֵל וּמִן-הַגֵּר הַגָּר בְּתוֹכָם אֲשֶׁר יֹאכַל כָּל-דָּם",
         "ואי רגל מן אל אסראיל. ומן אלג'ריב אלדכ'יל פי מא בינהם. יאכל שייא מן אלדם.",
         "And any man from the house of Israel, or from the stranger who has come in among them, who eats anything of blood —"),
        ("וְנָתַתִּי פָנַי בַּנֶּפֶשׁ הָאֹכֶלֶת אֶת-הַדָּם וְהִכְרַתִּי אֹתָהּ מִקֶּרֶב עַמָּהּ",
         "אחללת ג'צ'בי פיה. וקטעתה מן בין קומה",
         "I shall unleash My wrath upon him, and shall cut him off from among his people."),
    ],
    11: [
        ("כִּי נֶפֶשׁ הַבָּשָׂר בַּדָּם הִוא וַאֲנִי נְתַתִּיו לָכֶם עַל-הַמִּזְבֵּחַ לְכַפֵּר עַל-נַפְשֹׁתֵיכֶם",
         "לאן נפס גמיע אלבשריון אלדם מסכנהא. ולד'אלך געלתה לכם עלי' אלמד'בח. ליסתג'פר בה ען אנפסכם.",
         "For the soul of all fleshly beings — blood is its dwelling; and therefore I have appointed it for you upon the altar, that forgiveness may be sought by it for your souls —"),
        ("כִּי-הַדָּם הוּא בַּנֶּפֶשׁ יְכַפֵּר",
         "לאן אלדם יכפר ען אלנפס",
         "for blood makes atonement for the soul."),
    ],
    12: [
        ("עַל-כֵּן אָמַרְתִּי לִבְנֵי יִשְׂרָאֵל כָּל-נֶפֶשׁ מִכֶּם לֹא-תֹאכַל דָּם",
         "ולד'אלך קלת לבני אסראיל. כל אנסאן מנכם לא יאכל דמא.",
         "Therefore I have said to the sons of Israel: no person among you shall eat blood;"),
        ("וְהַגֵּר הַגָּר בְּתוֹכְכֶם לֹא-יֹאכַל דָּם",
         "חתי' אלג'ריב אלדכ'יל פי מא בינכם לא יאכל דמא",
         "and even the stranger who has come in among you shall not eat blood."),
    ],
    13: [
        ("וְאִישׁ אִישׁ מִבְּנֵי יִשְׂרָאֵל וּמִן-הַגֵּר הַגָּר בְּתוֹכָם אֲשֶׁר יָצוּד צֵיד חַיָּה אוֹ-עוֹף אֲשֶׁר יֵאָכֵל",
         "ואי רגל מן בני אסראיל. ומן אלג'ריב אלדכ'יל פי מא בינהם. אצטאד צידא מן אלוחש או מן אלטאיר אלד'י אכלה חלאל.",
         "And any man from the sons of Israel, or from the stranger who has come in among them, who hunts game — from the wild creatures or from the birds whose eating is permitted —"),
        ("וְשָׁפַךְ אֶת-דָּמוֹ וְכִסָּהוּ בֶּעָפָר",
         "פליצב דמה. ויוארה באלתראב",
         "let him pour out its blood and cover it with earth."),
    ],
    14: [
        ("כִּי-נֶפֶשׁ כָּל-בָּשָׂר דָּמוֹ בְנַפְשׁוֹ הוּא וָאֹמַר לִבְנֵי יִשְׂרָאֵל דַּם כָּל-בָּשָׂר לֹא תֹאכֵלוּ",
         "לאן נפס גמיע אלבשריון. כל ואחד פי דמה. ולאני קלת לבני אסראיל. דם כל בשרי לא תאכלו.",
         "For the soul of all fleshly beings — each one resides in its blood; and since I have said to the sons of Israel: the blood of every creature of flesh you shall not eat —"),
        ("כִּי נֶפֶשׁ כָּל-בָּשָׂר דָּמוֹ הִוא כָּל-אֹכְלָיו יִכָּרֵת",
         "אד' נפס כל בשרי אלדם מסכנהא. וכל מן אכלה ינקטע",
         "for the soul of every creature of flesh, blood is its dwelling — and whoever eats it shall be cut off."),
    ],
    15: [
        ("וְכָל-נֶפֶשׁ אֲשֶׁר תֹּאכַל נְבֵלָה וּטְרֵפָה בָּאֶזְרָח וּבַגֵּר",
         "ואי אנסאן אכל נבילה או סקימה. מן אלצריח ואלג'ריב.",
         "And any person who eats what has died of itself or what is diseased — whether native-born or stranger —"),
        ("וְכִבֶּס בְּגָדָיו וְרָחַץ בַּמַּיִם וְטָמֵא עַד-הָעֶרֶב--וְטָהֵר",
         "פליג'סל ת'יאבה. וירחץ' באלמא. וינגס אלי' אלמג'יב ויטהר",
         "let him wash his garments and bathe in water, and he shall be impure until the evening, and then be pure."),
    ],
    16: [
        ("וְאִם לֹא יְכַבֵּס וּבְשָׂרוֹ לֹא יִרְחָץ--וְנָשָׂא עֲו‍ֹנוֹ",
         "פאן הו לם יג'סלה. או לם ירחץ' בדנה. פקד חמל וזרה",
         "But if he does not wash them, or does not bathe his body, he shall have borne his guilt."),
    ],
}
