"""Hand-authored alignment triples for Vayikra chapter 7."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְזֹאת תּוֹרַת הָאָשָׁם קֹדֶשׁ קָדָשִׁים הוּא",
         "והד'א שריעה' קרבאן אלאת'ם. הו איצ'א מן כ'ואץ אלאקדאס",
         "And these are the ordinances of the guilt-offering — it too is among the choicest of the consecrated things."),
    ],
    2: [
        ("בִּמְקוֹם אֲשֶׁר יִשְׁחֲטוּ אֶת-הָעֹלָה יִשְׁחֲטוּ אֶת-הָאָשָׁם",
         "פי מוצ'ע תד'בח אלצעידה. יד'בח קרבאן אלאת'ם.",
         "In the place where they slaughter the elevation-offering, they shall slaughter the guilt-offering;"),
        ("וְאֶת-דָּמוֹ יִזְרֹק עַל-הַמִּזְבֵּחַ סָבִיב",
         "ודמה ירש עלי' אלמד'בח מסתדירא",
         "and its blood shall be sprinkled upon the altar all around."),
    ],
    3: [
        ("וְאֵת כָּל-חֶלְבּוֹ יַקְרִיב מִמֶּנּוּ--אֵת הָאַלְיָה וְאֶת-הַחֵלֶב הַמְכַסֶּה אֶת-הַקֶּרֶב",
         "וגמיע שחמה ירפע מנה. אלאליה ואלת'רב אלמג'טי אלגוף",
         "And all its fat shall be lifted from it — the broad tail and the suet that covers the innards,"),
    ],
    4: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת וְאֶת-הַחֵלֶב אֲשֶׁר עֲלֵיהֶן אֲשֶׁר עַל-הַכְּסָלִים",
         "ואלכלותין. ואלשחם אלד'י עליהמא. אלד'י עלי' אלאחשא.",
         "and the two kidneys and the fat that is upon them, which is upon the entrails,"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד עַל-הַכְּלָיֹת יְסִירֶנָּה",
         "וזיאדה' אלכבד. מע אלכלי' ינזעהא",
         "and the lobe of the liver — along with the kidneys he shall remove them."),
    ],
    5: [
        ("וְהִקְטִיר אֹתָם הַכֹּהֵן הַמִּזְבֵּחָה אִשֶּׁה לַיהוָה אָשָׁם הוּא",
         "ויקתרהא אלאמאם עלי' אלמד'בח. קרבאנא ללה. כד'אך מא יציר קרבאן אלאת'ם",
         "And the imām shall burn them upon the altar as an offering to God — thus is what the guilt-offering becomes."),
    ],
    6: [
        ("כָּל-זָכָר בַּכֹּהֲנִים יֹאכְלֶנּוּ בְּמָקוֹם קָדוֹשׁ יֵאָכֵל",
         "כל ד'כר מן אלאיימה יאכלה. פי מוצ'ע מקדס יוכל.",
         "Every male among the imāms may eat it; in a consecrated place it shall be eaten,"),
        ("קֹדֶשׁ קָדָשִׁים הוּא",
         "לאנה מן כ'ואץ אלאקדאס",
         "for it is among the choicest of the consecrated things."),
    ],
    7: [
        ("כַּחַטָּאת כָּאָשָׁם--תּוֹרָה אַחַת לָהֶם",
         "קרבאן אלאת'ם כאלדכוה. שריעה ואחדה להמא.",
         "The guilt-offering is like the sin-offering — one ordinance for them both;"),
        ("הַכֹּהֵן אֲשֶׁר יְכַפֶּר-בּוֹ לוֹ יִהְיֶה",
         "אלאמאם. אלד'י יכפר בה לה יכון",
         "the imām who makes atonement through it, to him it shall belong."),
    ],
    8: [
        ("וְהַכֹּהֵן--הַמַּקְרִיב אֶת-עֹלַת אִישׁ עוֹר הָעֹלָה אֲשֶׁר הִקְרִיב לַכֹּהֵן לוֹ יִהְיֶה",
         "ואלאמאם. אלמקרב צעידה ען אמר. פגלדהא בעד תקריבהא יכון לה",
         "And the imām who offers an elevation-offering on behalf of a man — its hide, after its having been offered, shall be his."),
    ],
    10: [
        ("וְכָל-מִנְחָה בְלוּלָה-בַשֶּׁמֶן וַחֲרֵבָה--לְכָל-בְּנֵי אַהֲרֹן תִּהְיֶה אִישׁ כְּאָחִיו",
         "וכל הדייה. מלתותה בדהן או גאפה. לגמיע בני הרון תכון. אלואחד כאלאכ'ר",
         "And every gift-offering mixed with oil or dry shall belong to all the sons of Aaron — one the same as another."),
    ],
    11: [
        ("וְזֹאת תּוֹרַת זֶבַח הַשְּׁלָמִים אֲשֶׁר יַקְרִיב לַיהוָה",
         "והד'א שריעה' ד'בח אלסלאמה. אלד'י יקרבה ללה",
         "And these are the ordinances of the peace-offering sacrifice which one offers to God."),
    ],
    12: [
        ("אִם עַל-תּוֹדָה יַקְרִיבֶנּוּ--וְהִקְרִיב עַל-זֶבַח הַתּוֹדָה חַלּוֹת מַצּוֹת בְּלוּלֹת בַּשֶּׁמֶן",
         "אן קרבה עלי' שכר. פיקרב מעה. גראדק פטיר מלתותה בדהן.",
         "If he offers it as a thanksgiving, then he shall offer with it loaves of unleavened bread mixed with oil,"),
        ("וּרְקִיקֵי מַצּוֹת מְשֻׁחִים בַּשָּׁמֶן וְסֹלֶת מֻרְבֶּכֶת חַלֹּת בְּלוּלֹת בַּשָּׁמֶן",
         "ורקאק פטיר ממסוחה בדהן וסמד סתותייה גראדק מלתותה בדהן",
         "and wafers of unleavened bread smeared with oil, and layers of fine flour — loaves mixed with oil."),
    ],
    13: [
        ("עַל-חַלֹּת לֶחֶם חָמֵץ יַקְרִיב קָרְבָּנוֹ עַל-זֶבַח תּוֹדַת שְׁלָמָיו",
         "מע גראדק כ'בז כ'מיר. יקרב קרבאנה. מע ד'בח שכר סלאמתה",
         "Together with loaves of leavened bread he shall offer his offering, with the thanksgiving sacrifice of his peace-offering."),
    ],
    14: [
        ("וְהִקְרִיב מִמֶּנּוּ אֶחָד מִכָּל-קָרְבָּן תְּרוּמָה לַיהוָה",
         "פליקרב מן ד'אלך רג'יפא ואחדא מן כל קרבאן. רפיעה ללה.",
         "And he shall offer from it one loaf from each offering, as an elevation to God;"),
        ("לַכֹּהֵן הַזֹּרֵק אֶת-דַּם הַשְּׁלָמִים--לוֹ יִהְיֶה",
         "לאלאמאם. אלד'י ינצ'ח מן דם אלסלאמה לה יכון",
         "to the imām who sprinkles the blood of the peace-offering — to him it shall belong."),
    ],
    15: [
        ("וּבְשַׂר זֶבַח תּוֹדַת שְׁלָמָיו--בְּיוֹם קָרְבָּנוֹ יֵאָכֵל לֹא-יַנִּיחַ מִמֶּנּוּ עַד-בֹּקֶר",
         "ולחם ד'בח שכר אלסלאמה. פי יום קרבאנה יוכל לא יבקי מנה אלי' אלג'דאה",
         "And the flesh of the thanksgiving sacrifice of the peace-offering shall be eaten on the day of its offering; he shall not leave any of it until morning."),
    ],
    16: [
        ("וְאִם-נֶדֶר אוֹ נְדָבָה זֶבַח קָרְבָּנוֹ--בְּיוֹם הַקְרִיבוֹ אֶת-זִבְחוֹ יֵאָכֵל",
         "ואן כאן ד'בח קרבאנה. נד'רא או תברעא. פליוכל פי יום תקריבה לה.",
         "But if the sacrifice of his offering be a vow or a freewill-offering, it shall be eaten on the day of his offering it;"),
        ("וּמִמָּחֳרָת וְהַנּוֹתָר מִמֶּנּוּ יֵאָכֵל",
         "ומן ג'ד. מא פצ'ל מנה יוכל",
         "and on the morrow, what remains of it shall be eaten."),
    ],
    17: [
        ("וְהַנּוֹתָר מִבְּשַׂר הַזָּבַח--בַּיּוֹם הַשְּׁלִישִׁי בָּאֵשׁ יִשָּׂרֵף",
         "ואלפאצ'ל מן לחם אלד'בח. פי אליום אלת'אלת'. פליחרק באלנאר",
         "And what is left of the flesh of the sacrifice on the third day shall be burned with fire."),
    ],
    18: [
        ("וְאִם הֵאָכֹל יֵאָכֵל מִבְּשַׂר-זֶבַח שְׁלָמָיו בַּיּוֹם הַשְּׁלִישִׁי לֹא יֵרָצֶה",
         "ואן אכל אכלא. מן לחם ד'בח אלסלאמה. פי אליום אלת'לאת' פלא ירתצ'א.",
         "And if any of the flesh of the peace-offering sacrifice be eaten on the third day, it shall not be accepted;"),
        ("הַמַּקְרִיב אֹתוֹ לֹא יֵחָשֵׁב לוֹ פִּגּוּל יִהְיֶה",
         "ואלמקרב לה. לא יחסב לה בל יכון כאלאכ'ס.",
         "and the one who offered it — it shall not be counted to him, but shall be as something abhorrent;"),
        ("וְהַנֶּפֶשׁ הָאֹכֶלֶת מִמֶּנּוּ עֲו‍ֹנָהּ תִּשָּׂא",
         "ואי אנסאן. אכל מנה פקד חמל וזרה",
         "and any person who eats of it shall have borne his burden of guilt."),
    ],
    19: [
        ("וְהַבָּשָׂר אֲשֶׁר-יִגַּע בְּכָל-טָמֵא לֹא יֵאָכֵל--בָּאֵשׁ יִשָּׂרֵף",
         "ולחם אלאקדאס. אן דנא בשי מן אלנגאסאת פלא יוכל. בל יחרק באלנאר.",
         "And the flesh of the consecrated things — if it comes near to anything of the impurities, it shall not be eaten, but shall be burned with fire;"),
        ("וְהַבָּשָׂר--כָּל-טָהוֹר יֹאכַל בָּשָׂר",
         "ואלטאהר מנה. פלא יאכלה אלא טאהר",
         "and as for what is pure of it, none but one who is pure shall eat it."),
    ],
    20: [
        ("וְהַנֶּפֶשׁ אֲשֶׁר-תֹּאכַל בָּשָׂר מִזֶּבַח הַשְּׁלָמִים אֲשֶׁר לַיהוָה וְטֻמְאָתוֹ עָלָיו",
         "ואי אנסאן אכל לחמא. מן ד'בח אלסלאמה אלד'י ללה. ונגאסתה עליה.",
         "And any person who eats flesh from the peace-offering sacrifice that belongs to God, while his impurity is upon him —"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעַמֶּיהָ",
         "פינקטע ד'אלך אלאנסאן מן בין קומה",
         "that person shall be cut off from among his people."),
    ],
    21: [
        ("וְנֶפֶשׁ כִּי-תִגַּע בְּכָל-טָמֵא בְּטֻמְאַת אָדָם אוֹ בִּבְהֵמָה טְמֵאָה אוֹ בְּכָל-שֶׁקֶץ טָמֵא",
         "ואי אנסאן לאמס שייא מן אלנגאסאת. בנגאסה' אנסאן או בבהימה נגסה או בשי מן אלדביב אלנגס.",
         "And any person who touches anything of the impurities — whether the impurity of a human, or an impure beast, or anything of impure creeping things —"),
        ("וְאָכַל מִבְּשַׂר-זֶבַח הַשְּׁלָמִים אֲשֶׁר לַיהוָה--וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעַמֶּיהָ",
         "ואכל מן לחם ד'בח אלסלאמה אלד'י ללה. פינקטע ד'אלך אלאנסאן מן קומה",
         "and eats of the flesh of the peace-offering sacrifice that belongs to God, that person shall be cut off from his people."),
    ],
    22: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי'' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    23: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר כָּל-חֵלֶב שׁוֹר וְכֶשֶׂב וָעֵז--לֹא תֹאכֵלוּ",
         "מר בני אסראיל קאילא. כל שחם בקר וצ'אן. ומאעז לא תאכלו",
         "Command the sons of Israel, saying: All fat of cattle and sheep and goats — you shall not eat."),
    ],
    24: [
        ("וְחֵלֶב נְבֵלָה וְחֵלֶב טְרֵפָה יֵעָשֶׂה לְכָל-מְלָאכָה וְאָכֹל לֹא תֹאכְלֻהוּ",
         "ושחם אלנבילה ואלסקימה. אסתעמלוה פי כל צנעה. ואכל לא תאכלוה",
         "And the fat of a carcass and the fat of a diseased animal — use it for any craft, but as food you shall not eat it."),
    ],
    25: [
        ("כִּי כָּל-אֹכֵל חֵלֶב מִן-הַבְּהֵמָה אֲשֶׁר יַקְרִיב מִמֶּנָּה אִשֶּׁה לַיהוָה",
         "פאן כל מן יאכל שחמא. מן אלבהאים. אלתי יקרב מנהא. קרבאנא ללה.",
         "For anyone who eats any fat of the beasts from which an offering is brought to God —"),
        ("וְנִכְרְתָה הַנֶּפֶשׁ הָאֹכֶלֶת מֵעַמֶּיהָ",
         "ינקטע ד'אלך אלאנסאן מן בין קומה",
         "that person shall be cut off from among his people."),
    ],
    26: [
        ("וְכָל-דָּם לֹא תֹאכְלוּ בְּכֹל מוֹשְׁבֹתֵיכֶם לָעוֹף וְלַבְּהֵמָה",
         "וכל דם לא תאכלו. פי גמיע מסאכנכם. מן אלטאיר ואלבהאים",
         "And all blood you shall not eat, in all your dwellings, whether of bird or of beasts."),
    ],
    27: [
        ("כָּל-נֶפֶשׁ אֲשֶׁר-תֹּאכַל כָּל-דָּם--וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מֵעַמֶּיהָ",
         "אי אנסאן אכל שייא מן אלדם. ינקטע ד'אלך אלאנסאן מן בין קומה",
         "Any person who eats any of the blood — that person shall be cut off from among his people."),
    ],
    28: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    29: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל לֵאמֹר הַמַּקְרִיב אֶת-זֶבַח שְׁלָמָיו לַיהוָה",
         "כ'אטב בני אסראיל וקל להם. אלמקרב ד'בח אלסלאמה ללה.",
         "Address the sons of Israel and say to them: He who offers the peace-offering sacrifice to God —"),
        ("יָבִיא אֶת-קָרְבָּנוֹ לַיהוָה מִזֶּבַח שְׁלָמָיו",
         "הו אלד'י יאתי בקרבאנה. ללה מן ד'בח סלאמתה",
         "he is the one who shall bring his offering to God from the sacrifice of his peace-offering."),
    ],
    30: [
        ("יָדָיו תְּבִיאֶינָה אֵת אִשֵּׁי יְהוָה אֶת-הַחֵלֶב עַל-הֶחָזֶה יְבִיאֶנּוּ",
         "ידאה תחמל קראבין אללה. אלשחם מע אלקץ יאתי מעה.",
         "His own hands shall carry the offerings of God; the fat together with the breast he shall bring with it,"),
        ("אֵת הֶחָזֶה לְהָנִיף אֹתוֹ תְּנוּפָה לִפְנֵי יְהוָה",
         "פיחרכה תחריכא בין ידי אללה",
         "and he shall wave it as a waving before God."),
    ],
    31: [
        ("וְהִקְטִיר הַכֹּהֵן אֶת-הַחֵלֶב הַמִּזְבֵּחָה",
         "ויקתר אלאמאם. אלשחם עלי' אלמד'בח.",
         "And the imām shall burn the fat upon the altar,"),
        ("וְהָיָה הֶחָזֶה לְאַהֲרֹן וּלְבָנָיו",
         "ויציר אלקץ. להרון ובניה",
         "and the breast shall become Aaron's and his sons'."),
    ],
    32: [
        ("וְאֵת שׁוֹק הַיָּמִין תִּתְּנוּ תְרוּמָה לַכֹּהֵן מִזִּבְחֵי שַׁלְמֵיכֶם",
         "ואלסאק אלאימן. אעטוה רפיעה לאלאמאם. מן ד'באיח סלאמתכם",
         "And the right haunch — give it as an elevation to the imām from the sacrifices of your peace-offerings."),
    ],
    33: [
        ("הַמַּקְרִיב אֶת-דַּם הַשְּׁלָמִים וְאֶת-הַחֵלֶב--מִבְּנֵי אַהֲרֹן לוֹ תִהְיֶה שׁוֹק הַיָּמִין לְמָנָה",
         "אלמקרב דם אלסלאמה. ואלשחם מן בני הרון. לה יכון. סאק אלאימן נציבא",
         "He among the sons of Aaron who offers the blood of the peace-offering and the fat — to him shall belong the right haunch as his portion."),
    ],
    34: [
        ("כִּי אֶת-חֲזֵה הַתְּנוּפָה וְאֵת שׁוֹק הַתְּרוּמָה לָקַחְתִּי מֵאֵת בְּנֵי-יִשְׂרָאֵל מִזִּבְחֵי שַׁלְמֵיהֶם",
         "לאן קץ אלתחריך וסאק אלרפיעה. אכ'ד'תהא מן בני אסראיל. מן ד'באיח סלאמתהם.",
         "For the breast of the waving and the haunch of the elevation I have taken from the sons of Israel, from the sacrifices of their peace-offerings,"),
        ("וָאֶתֵּן אֹתָם לְאַהֲרֹן הַכֹּהֵן וּלְבָנָיו לְחָק-עוֹלָם מֵאֵת בְּנֵי יִשְׂרָאֵל",
         "ואעטיתהא להרון אלאמאם ובניה. רסם אלדהר מן בני אסראיל",
         "and I have given them to Aaron the imām and to his sons — an ordinance forever from the sons of Israel."),
    ],
    35: [
        ("זֹאת מִשְׁחַת אַהֲרֹן וּמִשְׁחַת בָּנָיו מֵאִשֵּׁי יְהוָה בְּיוֹם הִקְרִיב אֹתָם לְכַהֵן לַיהוָה",
         "הד'ה חצה' הרון ובניה. מן קראבין אללה. פי יום קדמו. ליאמו ללה",
         "This is the portion of Aaron and his sons from the offerings of God, on the day they were presented to serve as imāms before God."),
    ],
    36: [
        ("אֲשֶׁר צִוָּה יְהוָה לָתֵת לָהֶם בְּיוֹם מָשְׁחוֹ אֹתָם מֵאֵת בְּנֵי יִשְׂרָאֵל--חֻקַּת עוֹלָם לְדֹרֹתָם",
         "אלד'י אמר אללה בהא אן יעטוהא. פי יום מסחהם. מן בני אסראיל. רסם אלדהר לאגיאלהם",
         "Which God commanded to be given to them on the day of their anointing, from the sons of Israel — an ordinance forever for their generations."),
    ],
    37: [
        ("זֹאת הַתּוֹרָה לָעֹלָה לַמִּנְחָה וְלַחַטָּאת וְלָאָשָׁם",
         "הד'ה אלשריעה לאלצעידה ואלהדייה. ואלדכוה וקרבאן אלאת'ם.",
         "These are the ordinances for the elevation-offering and the gift-offering, and the sin-offering and the guilt-offering,"),
        ("וְלַמִּלּוּאִים--וּלְזֶבַח הַשְּׁלָמִים",
         "וללכמאל. ולד'בח אלסלאמה",
         "and for the investiture, and for the peace-offering sacrifice —"),
    ],
    38: [
        ("אֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה בְּהַר סִינָי בְּיוֹם צַוֹּתוֹ אֶת-בְּנֵי יִשְׂרָאֵל לְהַקְרִיב אֶת-קָרְבְּנֵיהֶם לַיהוָה--בְּמִדְבַּר סִינָי",
         "אלתי אמר אללה בהא מוסי' פי גבל סיני. פי וקת אמר בני אסראיל. אן יקרבו קראבינהם. ללה פי ברייה' סיני",
         "which God commanded Moses on the mountain of Sinai, at the time He commanded the sons of Israel to offer their offerings to God in the wilderness of Sinai."),
    ],
}
