"""Hand-authored alignment triples for Vayikra chapter 2."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְנֶפֶשׁ כִּי-תַקְרִיב קָרְבַּן מִנְחָה לַיהוָה",
         "ואי אנסאן קרב קרבאן הדייה ללה",
         "And whatever person brings an offering of gift to God"),
        ("סֹלֶת יִהְיֶה קָרְבָּנוֹ וְיָצַק עָלֶיהָ שֶׁמֶן",
         "וכאן קרבאנה סמדא. פליצב עליהא דהנא",
         "and his offering is fine flour — let him pour oil upon it"),
        ("וְנָתַן עָלֶיהָ לְבֹנָה",
         "ויגעל עליהא לבאנא",
         "and place frankincense upon it."),
    ],
    2: [
        ("וֶהֱבִיאָהּ אֶל-בְּנֵי אַהֲרֹן הַכֹּהֲנִים וְקָמַץ מִשָּׁם מְלֹא קֻמְצוֹ מִסָּלְתָּהּ וּמִשַּׁמְנָהּ עַל כָּל-לְבֹנָתָהּ",
         "ויאתי בהא. אלי' בעץ' בני הרון אלאיימה. ויקבץ' מל קבצ'תה. מן סמדהא ודהנהא. מע גמיע לבאנהא",
         "And he shall bring it to one of the sons of Aaron the priests; and he shall take a handful from its fine flour and its oil, together with all its frankincense"),
        ("וְהִקְטִיר הַכֹּהֵן אֶת-אַזְכָּרָתָהּ הַמִּזְבֵּחָה--אִשֵּׁה רֵיחַ נִיחֹחַ לַיהוָה",
         "ויקתר פיחהא עלי' אלמד'בח. קרבאן מקבול מרצ'י ללה",
         "and burn its fragrance upon the altar — an offering accepted and pleasing to God."),
    ],
    3: [
        ("וְהַנּוֹתֶרֶת מִן-הַמִּנְחָה--לְאַהֲרֹן וּלְבָנָיו",
         "ואלפאצ'ל מנהא. להרון ובניה",
         "And the remainder of it shall belong to Aaron and his sons"),
        ("קֹדֶשׁ קָדָשִׁים מֵאִשֵּׁי יְהוָה",
         "מן כ'ואץ אלאקדאס מן קראבין אללה",
         "from the choicest of the holy things from the offerings of God."),
    ],
    4: [
        ("וְכִי תַקְרִב קָרְבַּן מִנְחָה מַאֲפֵה תַנּוּר",
         "ואן קרבת הדייה מן כ'בז אלתנור",
         "And if you bring a gift offering from the bread of the oven"),
        ("סֹלֶת חַלּוֹת מַצֹּת בְּלוּלֹת בַּשֶּׁמֶן",
         "פלתכון גראדק סמד פטיר מלתותה בדהן",
         "let it be loaves of fine flour unleavened, kneaded with oil"),
        ("וּרְקִיקֵי מַצּוֹת מְשֻׁחִים בַּשָּׁמֶן",
         "ורקאק פטיר מלתותה בדהן ורקאק פטיר ממסוחה בדהן",
         "and wafers unleavened kneaded with oil, and wafers unleavened smeared with oil."),
    ],
    5: [
        ("וְאִם-מִנְחָה עַל-הַמַּחֲבַת קָרְבָּנֶךָ",
         "ואן כאן קרבאנך הדייה עלי' אלטאבק",
         "And if your offering is a gift offering upon the griddle"),
        ("סֹלֶת בְּלוּלָה בַשֶּׁמֶן מַצָּה תִהְיֶה",
         "פלתכון פטירא מן סמד מלתותה בדהן",
         "let it be unleavened from fine flour, kneaded with oil."),
    ],
    6: [
        ("פָּתוֹת אֹתָהּ פִּתִּים וְיָצַקְתָּ עָלֶיהָ שָׁמֶן",
         "ואת'רדהא ת'רדא. וצב עליהא דהנא",
         "And crumble it into crumbs, and pour oil upon it"),
        ("מִנְחָה הִוא",
         "כד'אך מא יכון הדייה",
         "thus shall it be as a gift offering."),
    ],
    7: [
        ("וְאִם-מִנְחַת מַרְחֶשֶׁת קָרְבָּנֶךָ",
         "ואן כאן קרבאנך הדייה מן צנעה' אלטנגיר",
         "And if your offering is a gift offering from the making of the pot"),
        ("סֹלֶת בַּשֶּׁמֶן תֵּעָשֶׂה",
         "פלתעמל סמד בדהן",
         "let it be made of fine flour with oil."),
    ],
    8: [
        ("וְהֵבֵאתָ אֶת-הַמִּנְחָה אֲשֶׁר יֵעָשֶׂה מֵאֵלֶּה--לַיהוָה",
         "פאית באלהדייה. אלתי קד עמלת מן אחדי' הד'ה ללה",
         "And bring the gift offering that has been prepared from one of these to God"),
        ("וְהִקְרִיבָהּ אֶל-הַכֹּהֵן וְהִגִּישָׁהּ אֶל-הַמִּזְבֵּחַ",
         "ויקדמהא אלי' אלאמאם. יקדמהא אלי' אלמד'בח",
         "and he shall present it to the priest, who shall present it to the altar."),
    ],
    9: [
        ("וְהֵרִים הַכֹּהֵן מִן-הַמִּנְחָה אֶת-אַזְכָּרָתָהּ",
         "וירפע מנהא פיחהא",
         "And he shall lift from it its fragrance"),
        ("וְהִקְטִיר הַמִּזְבֵּחָה--אִשֵּׁה רֵיחַ נִיחֹחַ לַיהוָה",
         "ויקתרה עלי' אלמד'בח. קרבאנא מקבולא מרצ'יא ללה",
         "and burn it upon the altar — an offering accepted and pleasing to God."),
    ],
    11: [
        ("כָּל-הַמִּנְחָה אֲשֶׁר תַּקְרִיבוּ לַיהוָה--לֹא תֵעָשֶׂה חָמֵץ",
         "גמיע אלהדאיא. אלתי תקרבוהא ללה. לא תעמל כ'מירא",
         "All the gift offerings which you bring to God shall not be made leavened"),
        ("כִּי כָל-שְׂאֹר וְכָל-דְּבַשׁ לֹא-תַקְטִירוּ מִמֶּנּוּ אִשֶּׁה לַיהוָה",
         "לאן כל כ'מיר וכל עסל. לא תקרבו מנה. קרבאנא ללה",
         "for all leaven and all honey — you shall not bring thereof as an offering to God."),
    ],
    12: [
        ("קָרְבַּן רֵאשִׁית תַּקְרִיבוּ אֹתָם לַיהוָה",
         "לכן קרבאן אוול. תקרבוהא ללה",
         "But as a firstfruit offering you may bring them to God"),
        ("וְאֶל-הַמִּזְבֵּחַ לֹא-יַעֲלוּ לְרֵיחַ נִיחֹחַ",
         "ואלי' אלמד'בח לא תצעד לקבול מרצ'י",
         "yet to the altar they shall not be brought up for an accepted and pleasing reception."),
    ],
    13: [
        ("וְכָל-קָרְבַּן מִנְחָתְךָ בַּמֶּלַח תִּמְלָח",
         "וגמיע קרבאן הדאיאך אמלחה במלח",
         "And every offering of your gift offerings — salt it with salt"),
        ("וְלֹא תַשְׁבִּית מֶלַח בְּרִית אֱלֹהֶיךָ מֵעַל מִנְחָתֶךָ",
         "ולא תעטל אלמלח. לאנה עהד רבך מן הדייתך",
         "and do not cease from salt; for it is the covenant of your Lord from your gift offering"),
        ("עַל כָּל-קָרְבָּנְךָ תַּקְרִיב מֶלַח",
         "ומע סאיר קראבינך תקרב מלחא",
         "and with the rest of your offerings you shall bring salt."),
    ],
    14: [
        ("וְאִם-תַּקְרִיב מִנְחַת בִּכּוּרִים לַיהוָה",
         "ואן קרבת הדייה' בכור ללה",
         "And if you bring a firstfruit gift offering to God"),
        ("אָבִיב קָלוּי בָּאֵשׁ גֶּרֶשׂ כַּרְמֶל תַּקְרִיב אֵת מִנְחַת בִּכּוּרֶיךָ",
         "פפריך מקלי באלנאר. גריש מן אלהרף קרבהא",
         "bring it as roasted grain parched by fire, coarsely ground from the finest crop."),
    ],
    15: [
        ("וְנָתַתָּ עָלֶיהָ שֶׁמֶן וְשַׂמְתָּ עָלֶיהָ לְבֹנָה",
         "ואגעל עליהא דהנא. וצייר עליהא לבאנא",
         "And place oil upon it, and set frankincense upon it"),
        ("מִנְחָה הִוא",
         "כ'דאך מא תכון הדייה",
         "thus shall it be as a gift offering."),
    ],
    16: [
        ("וְהִקְטִיר הַכֹּהֵן אֶת-אַזְכָּרָתָהּ מִגִּרְשָׂהּ וּמִשַּׁמְנָהּ עַל כָּל-לְבֹנָתָהּ--אִשֶּׁה לַיהוָה",
         "ויקתר אלאמאם פיחהא. מן גרישהא ודהנהא. מע גמיע לבאנהא. קרבאנא ללה",
         "And the priest shall burn its fragrance — from its coarse grains and its oil, together with all its frankincense — as an offering to God."),
    ],
}
