"""Hand-authored alignment triples for Vayikra chapter 24."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("צַו אֶת-בְּנֵי יִשְׂרָאֵל וְיִקְחוּ אֵלֶיךָ שֶׁמֶן זַיִת זָךְ כָּתִית--לַמָּאוֹר",
         "אוץ בני אסראיל. אן יאתוך בדהן זית צאף. מדקוק לאלאצ'אה",
         "Command the sons of Israel that they bring you pure olive oil, pressed for giving light,"),
        ("לְהַעֲלֹת נֵר תָּמִיד",
         "לתסר'ג בה אלסרג דאימא",
         "to kindle the lamp with it continually."),
    ],
    3: [
        ("מִחוּץ לְפָרֹכֶת הָעֵדֻת בְּאֹהֶל מוֹעֵד יַעֲרֹךְ אֹתוֹ אַהֲרֹן מֵעֶרֶב עַד-בֹּקֶר לִפְנֵי יְהוָה--תָּמִיד",
         "כ'ארג סגף אלשהאדה פי כ'בא אלמחצ'ר. ינצ'דה הרון. מן אלעשי אלי' אלצבאח. בין ידי אללה דאימא",
         "Outside the veil of the testimony, in the tent of the presence, Aaron shall arrange it from evening until morning before God continually —"),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם",
         "רסם אלדהר",
         "an ordinance forever."),
    ],
    4: [
        ("עַל הַמְּנֹרָה הַטְּהֹרָה יַעֲרֹךְ אֶת-הַנֵּרוֹת לִפְנֵי יְהוָה תָּמִיד",
         "עלי' אלמנארה אלטאהרה. יצפהא בין ידי אללה דאימא",
         "Upon the pure lampstand shall he set them in order before God continually."),
    ],
    5: [
        ("וְלָקַחְתָּ סֹלֶת--וְאָפִיתָ אֹתָהּ שְׁתֵּים עֶשְׂרֵה חַלּוֹת",
         "וכד' סמדא. ואכ'בזה את'נא עשר גרדקה",
         "And take fine flour, and bake it into twelve loaves,"),
        ("שְׁנֵי עֶשְׂרֹנִים יִהְיֶה הַחַלָּה הָאֶחָת",
         "ולתכון כל גרדקה מן עשרין",
         "and let each loaf be of twenty [parts]."),
    ],
    6: [
        ("וְשַׂמְתָּ אוֹתָם שְׁתַּיִם מַעֲרָכוֹת שֵׁשׁ הַמַּעֲרָכֶת עַל הַשֻּׁלְחָן הַטָּהֹר לִפְנֵי יְהוָה",
         "וציירהמא צפין. סתה פי כל צף. עלי' אלמאידה אלטאהרה בין ידי אללה",
         "And set them in two rows, six in each row, upon the pure table before God."),
    ],
    7: [
        ("וְנָתַתָּ עַל-הַמַּעֲרֶכֶת לְבֹנָה זַכָּה",
         "ואגעל עלי' כל צף לבאנא ד'כייא",
         "And place upon each row pure frankincense,"),
        ("וְהָיְתָה לַלֶּחֶם לְאַזְכָּרָה אִשֶּׁה לַיהוָה",
         "וליכון ען אלכ'בז פיחא. מקרבא ללה",
         "and let it serve as the fragrant portion from the bread — an offering to God."),
    ],
    8: [
        ("בְּיוֹם הַשַּׁבָּת בְּיוֹם הַשַּׁבָּת יַעַרְכֶנּוּ לִפְנֵי יְהוָה--תָּמִיד מֵאֵת בְּנֵי-יִשְׂרָאֵל",
         "ופי כל יום סבת. יצפהא בין ידי אללה דאימא. מן ענד בני אסראיל",
         "And on every Sabbath day he shall arrange them before God continually, from the sons of Israel —"),
        ("בְּרִית עוֹלָם",
         "עהד אלדהר",
         "a covenant forever."),
    ],
    9: [
        ("וְהָיְתָה לְאַהֲרֹן וּלְבָנָיו וַאֲכָלֻהוּ בְּמָקוֹם קָדֹשׁ",
         "ת'ם ידפע אלי' הרון ובניה. יאכלונה פי מוצ'ע מקדס",
         "Then it shall be given over to Aaron and his sons; they shall eat it in a consecrated place,"),
        ("כִּי קֹדֶשׁ קָדָשִׁים הוּא לוֹ מֵאִשֵּׁי יְהוָה--חָק-עוֹלָם",
         "לאנה להם מן כ'ואץ אלאקדאס. מן קראבין אללה רסם אלדהר",
         "for it belongs to them from the choicest of the sacred things, from the offerings to God — an ordinance forever."),
    ],
    10: [
        ("וַיֵּצֵא בֶּן-אִשָּׁה יִשְׂרְאֵלִית וְהוּא בֶּן-אִישׁ מִצְרִי בְּתוֹךְ בְּנֵי יִשְׂרָאֵל",
         "פכ'רג אבן אמראה אסראילייה. והו אבן רגל מצרי. פי מא בין בני אסראיל",
         "And there went out the son of an Israelite woman — he being the son of an Egyptian man — among the sons of Israel;"),
        ("וַיִּנָּצוּ בַּמַּחֲנֶה בֶּן הַיִּשְׂרְאֵלִית וְאִישׁ הַיִּשְׂרְאֵלִי",
         "פתנאצו פי אלעסכר. הד'א אבן אלאסראילייה. ואלרגל אלאסראילי",
         "and they quarreled in the camp, this son of the Israelite woman and the Israelite man."),
    ],
    11: [
        ("וַיִּקֹּב בֶּן-הָאִשָּׁה הַיִּשְׂרְאֵלִית אֶת-הַשֵּׁם וַיְקַלֵּל",
         "פסב אבן אלאמראה אלאסראילייה אלאסם ושתמה",
         "And the son of the Israelite woman reviled the Name and cursed it;"),
        ("וַיָּבִיאוּ אֹתוֹ אֶל-מֹשֶׁה וְשֵׁם אִמּוֹ שְׁלֹמִית בַּת-דִּבְרִי לְמַטֵּה-דָן",
         "פאתו בה אלי' מוסי'. וכאן אסם אמה. שלומית אבנה' דברי מן סבט דן",
         "and they brought him to Moses. Now the name of his mother was Shelomith daughter of Dibri, of the tribe of Dan."),
    ],
    12: [
        ("וַיַּנִּיחֻהוּ בַּמִּשְׁמָר לִפְרֹשׁ לָהֶם עַל-פִּי יְהוָה",
         "פוצ'עוה פי אלחבס. ליביין להם אמרה ען קול אללה",
         "And they placed him in custody, until his case should be made clear to them by the word of God."),
    ],
    13: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    14: [
        ("הוֹצֵא אֶת-הַמְקַלֵּל אֶל-מִחוּץ לַמַּחֲנֶה",
         "אכ'רג אלשאתם אלי' כ'ארג אלעסכר",
         "\"Bring out the reviler to outside the camp,"),
        ("וְסָמְכוּ כָל-הַשֹּׁמְעִים אֶת-יְדֵיהֶם עַל-רֹאשׁוֹ וְרָגְמוּ אֹתוֹ כָּל-הָעֵדָה",
         "ויסנד כל מן סמעה אידיהם עלי' ראסה. ולירגמוה גמיע אהל אלמחצ'ר רגמא",
         "and let all who heard him lay their hands upon his head; and let all the people of the presence stone him with stones.\""),
    ],
    15: [
        ("וְאֶל-בְּנֵי יִשְׂרָאֵל תְּדַבֵּר לֵאמֹר אִישׁ אִישׁ כִּי-יְקַלֵּל אֱלֹהָיו וְנָשָׂא חֶטְאוֹ",
         "ומר בני אסראיל וקל להם. אי אנסאן שתם רבה פקד חמל וזרה",
         "\"And command the sons of Israel, and say to them: any person who curses his Lord shall bear his guilt.\""),
    ],
    16: [
        ("וְנֹקֵב שֵׁם-יְהוָה מוֹת יוּמָת רָגוֹם יִרְגְּמוּ-בוֹ כָּל-הָעֵדָה",
         "ומן סבה כד'אך פליקתל קתלא. לירגמוה גמיע אהל אלמחצ'ר רגמא",
         "\"And whoever reviles Him thus shall be put to death — all the people of the presence shall stone him with stones."),
        ("כַּגֵּר כָּאֶזְרָח--בְּנָקְבוֹ-שֵׁם יוּמָת",
         "אלדכ'יל כאלצריח סוא. אייהמא סב אלאסם פליקתל",
         "The sojourner and the native-born are equal: whichever of them curses the Name shall be put to death.\""),
    ],
    17: [
        ("וְאִישׁ כִּי יַכֶּה כָּל-נֶפֶשׁ אָדָם--מוֹת יוּמָת",
         "ואי אנסאן קתל ואחדה מן נפוס אלנאס פליקתל",
         "\"And any person who kills one of the souls of the people shall be put to death.\""),
    ],
    18: [
        ("וּמַכֵּה נֶפֶשׁ-בְּהֵמָה יְשַׁלְּמֶנָּה--נֶפֶשׁ תַּחַת נָפֶשׁ",
         "ומן קתל בהימה פליסלם מת'להא. ראסא בדל ראס",
         "\"And whoever kills a beast shall render its like — head in place of head.\""),
    ],
    19: [
        ("וְאִישׁ כִּי-יִתֵּן מוּם בַּעֲמִיתוֹ--כַּאֲשֶׁר עָשָׂה כֵּן יֵעָשֶׂה לּוֹ",
         "ואי אנסאן געל עיבא פי אחד מן אמתה. פליצנע בה כמא צנע",
         "\"And any person who inflicts a defect upon one of his fellow countrymen — as he has done, so shall be done to him.\""),
    ],
    20: [
        ("שֶׁבֶר תַּחַת שֶׁבֶר עַיִן תַּחַת עַיִן שֵׁן תַּחַת שֵׁן",
         "לאלכסר בדל אלכסר. ולאלעין בדלהא ולאלסן בדלהא",
         "\"Fracture in place of fracture, and eye in place of eye, and tooth in place of tooth:"),
        ("כַּאֲשֶׁר יִתֵּן מוּם בָּאָדָם כֵּן יִנָּתֶן בּוֹ",
         "כמא יגעל עיבא פי אנסאנא. כד'אך יגעל עליה",
         "as one inflicts a defect upon a person, so shall it be inflicted upon him.\""),
    ],
    21: [
        ("וּמַכֵּה בְהֵמָה יְשַׁלְּמֶנָּה וּמַכֵּה אָדָם יוּמָת",
         "ומן צ'רב בהימה פליג'רם. ומן צ'רב אנסאנא ומאת פליקתל",
         "\"And whoever strikes a beast shall be fined; and whoever strikes a person and causes death shall be put to death.\""),
    ],
    22: [
        ("מִשְׁפַּט אֶחָד יִהְיֶה לָכֶם כַּגֵּר כָּאֶזְרָח יִהְיֶה",
         "וליכון לכם חכם ואחד. יסאוי פיה אלדכ'יל ואלצריח",
         "\"And there shall be one ruling for you, in which the sojourner and the native-born are equal —"),
        ("כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "לאני אללה רבכם אלואחד",
         "for I am God, your Lord, the One.\""),
    ],
    23: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-בְּנֵי יִשְׂרָאֵל וַיּוֹצִיאוּ אֶת-הַמְקַלֵּל אֶל-מִחוּץ לַמַּחֲנֶה וַיִּרְגְּמוּ אֹתוֹ אָבֶן",
         "פכלם מוסי' בד'אלך בני אסראיל. ואכ'רגו אלשאתם אלי' כ'ארג אלעסכר. ורגמוה באלחגארה חתי' מאת",
         "And Moses spoke thereby to the sons of Israel; and they brought out the reviler to outside the camp, and stoned him with stones until he died."),
        ("וּבְנֵי-יִשְׂרָאֵל עָשׂוּ כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "וצנעו בני אסראיל פי סאיר מא נזל עליהם כמא אמר אללה מוסי'",
         "And the sons of Israel acted in all the rest of what had come down to them, as God had commanded Moses."),
    ],
}
