"""Hand-authored alignment triples for Vayikra chapter 6."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, a speaking."),
    ],
    2: [
        ("צַו אֶת-אַהֲרֹן וְאֶת-בָּנָיו לֵאמֹר זֹאת תּוֹרַת הָעֹלָה",
         "מר הרון ובניה קאילא. הד'ה שריעה' אלצעידה.",
         "Command Aaron and his sons, saying: This is the law of the burnt-offering —"),
        ("הִוא הָעֹלָה עַל מוֹקְדָה עַל-הַמִּזְבֵּחַ כָּל-הַלַּיְלָה עַד-הַבֹּקֶר וְאֵשׁ הַמִּזְבֵּחַ תּוּקַד בּוֹ",
         "תוצ'ע עלי' וקיד עלי' אלמד'בח טול אלליל אלי' אלג'דאה. ונאר אלמד'בח תתוקד עליה",
         "it shall be placed upon a fire upon the altar throughout the night until the morning, and the fire of the altar shall burn upon it."),
    ],
    3: [
        ("וְלָבַשׁ הַכֹּהֵן מִדּוֹ בַד וּמִכְנְסֵי-בַד יִלְבַּשׁ עַל-בְּשָׂרוֹ",
         "וילבס אלאמאם קמיץ מן עשר. וסראויל מן עשר ילבס עלי'בדנה.",
         "And the imām shall put on a linen shirt and linen trousers he shall wear upon his body;"),
        ("וְהֵרִים אֶת-הַדֶּשֶׁן אֲשֶׁר תֹּאכַל הָאֵשׁ אֶת-הָעֹלָה עַל-הַמִּזְבֵּחַ וְשָׂמוֹ אֵצֶל הַמִּזְבֵּחַ",
         "וירפע אלרמאד אלתי תאכל נאר אלצעידה עלי'אלמד'בח. ויגעלה לזק אלמד'בח",
         "and he shall remove the ash which the fire of the burnt-offering has consumed upon the altar, and set it beside the altar."),
    ],
    4: [
        ("וּפָשַׁט אֶת-בְּגָדָיו וְלָבַשׁ בְּגָדִים אֲחֵרִים",
         "ת'ם יסלך' ת'יאבה. וילבס ת'יאב אכ'ר.",
         "Then he shall take off his garments and put on other garments,"),
        ("וְהוֹצִיא אֶת-הַדֶּשֶׁן אֶל-מִחוּץ לַמַּחֲנֶה אֶל-מָקוֹם טָהוֹר",
         "ויכ'רג אלרמאד אלי' כ'ארג אלעסכר. אלי' מוצ'ע טאהר",
         "and carry the ash out to the outside of the camp, to a clean place."),
    ],
    5: [
        ("וְהָאֵשׁ עַל-הַמִּזְבֵּחַ תּוּקַד-בּוֹ לֹא תִכְבֶּה",
         "ואלנאר אלד'י עלי' אלמד'בח תקד פיה לא תטפא.",
         "And the fire which is upon the altar shall burn therein — it shall not be extinguished;"),
        ("וּבִעֵר עָלֶיהָ הַכֹּהֵן עֵצִים בַּבֹּקֶר בַּבֹּקֶר וְעָרַךְ עָלֶיהָ הָעֹלָה וְהִקְטִיר עָלֶיהָ חֶלְבֵי הַשְּׁלָמִים",
         "וישעל עליהא אלאמאם. חטבא פי כל ג'דאה. וינצ'ד עליהא אלצעידה. ויקתר עליהא שחום ד'בח אלסלאמה",
         "and the imām shall kindle upon it wood every morning, and arrange upon it the burnt-offering, and burn upon it the fat of the peace-offering."),
    ],
    6: [
        ("אֵשׁ תָּמִיד תּוּקַד עַל-הַמִּזְבֵּחַ--לֹא תִכְבֶּה",
         "וכדאך אלנאר דאימא. תקד עלי' אלמד'בח לא תטפא",
         "And so the fire shall burn upon the altar continually — it shall not be extinguished."),
    ],
    7: [
        ("וְזֹאת תּוֹרַת הַמִּנְחָה הַקְרֵב אֹתָהּ בְּנֵי-אַהֲרֹן לִפְנֵי יְהוָה אֶל-פְּנֵי הַמִּזְבֵּחַ",
         "והד'ה שריעה' אלהדייה. אן יקדמהא בני הרון בין ידי אללה. בין ידי אלמד'בח",
         "And this is the law of the gift-offering: the sons of Aaron shall present it before God, before the altar."),
    ],
    8: [
        ("וְהֵרִים מִמֶּנּוּ בְּקֻמְצוֹ מִסֹּלֶת הַמִּנְחָה וּמִשַּׁמְנָהּ",
         "וירפע מנהא בקבצ'תה. מן סמדהא ודהנהא.",
         "And he shall lift from it with his handful, from its fine flour and its oil,"),
        ("וְאֵת כָּל-הַלְּבֹנָה אֲשֶׁר עַל-הַמִּנְחָה וְהִקְטִיר הַמִּזְבֵּחַ רֵיחַ נִיחֹחַ אַזְכָּרָתָהּ--לַיהוָה",
         "ויקתר פיחהא עלי' אלמד'בח. קבול מרצ'י ללה",
         "and burn its fragrance upon the altar — accepted and pleasing to God."),
    ],
    9: [
        ("וְהַנּוֹתֶרֶת מִמֶּנָּה יֹאכְלוּ אַהֲרֹן וּבָנָיו מַצּוֹת תֵּאָכֵל בְּמָקוֹם קָדֹשׁ",
         "ואלפאצ'ל מנהא. יאכלה הרון ובניה. פטירא תוכל פי מוצ'ע מקדס.",
         "And the remainder of it Aaron and his sons shall eat; it shall be eaten unleavened in a consecrated place —"),
        ("בַּחֲצַר אֹהֶל-מוֹעֵד יֹאכְלוּהָ",
         "פי צחן כ'בא אלמחצ'ר יאכלוהא",
         "in the court of the tent of the presence they shall eat it."),
    ],
    10: [
        ("לֹא תֵאָפֶה חָמֵץ חֶלְקָם נָתַתִּי אֹתָהּ מֵאִשָּׁי",
         "לא תכ'בז כ'מירא. געלתהא קסמהם מן קראביני.",
         "It shall not be baked leavened; I have appointed it as their portion from my offerings —"),
        ("קֹדֶשׁ קָדָשִׁים הִוא כַּחַטָּאת וְכָאָשָׁם",
         "מן כ'ואץ אלאקדאס הי. כאלדכוה וקרבאן אלאתם",
         "it is among the choicest of the sacred things, like the purification-offering and the guilt-offering."),
    ],
    11: [
        ("כָּל-זָכָר בִּבְנֵי אַהֲרֹן יֹאכְלֶנָּה--חָק-עוֹלָם לְדֹרֹתֵיכֶם מֵאִשֵּׁי יְהוָה",
         "כל ד'כר מן בני הרון יאכלהא. רסם אלדהר לאגיאלכם. מן קראבין אללה.",
         "Every male among the sons of Aaron shall eat it — a statute forever for your generations, from the offerings of God;"),
        ("כֹּל אֲשֶׁר-יִגַּע בָּהֶם יִקְדָּשׁ",
         "כל מן לאמסהא תקדס",
         "everyone who touches it shall become consecrated."),
    ],
    12: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, a speaking."),
    ],
    13: [
        ("זֶה קָרְבַּן אַהֲרֹן וּבָנָיו אֲשֶׁר-יַקְרִיבוּ לַיהוָה בְּיוֹם הִמָּשַׁח אֹתוֹ",
         "הד'א קרבאן הרון ובניה אלד'י יקרבה ללה. מן יום מסח.",
         "This is the offering of Aaron and his sons which he shall bring to God on the day of his anointing:"),
        ("עֲשִׂירִת הָאֵפָה סֹלֶת מִנְחָה תָּמִיד מַחֲצִיתָהּ בַּבֹּקֶר וּמַחֲצִיתָהּ בָּעָרֶב",
         "עשר אלויבה סמד. הדייה דאימא. נצפהא באלג'דאה. ונצפהא באלעשא",
         "a tenth of a waybah of fine flour — a gift continually, half of it in the morning and half of it in the evening."),
    ],
    14: [
        ("עַל-מַחֲבַת בַּשֶּׁמֶן תֵּעָשֶׂה--מֻרְבֶּכֶת תְּבִיאֶנָּה תֻּפִינֵי מִנְחַת פִּתִּים תַּקְרִיב רֵיחַ-נִיחֹחַ לַיהוָה",
         "עלי' טאבק בדהן תעמל. סתותייה תאתי בהא רפכ'ה תכון. תקרבהא מקבולא מרצ'ייא ללה",
         "On a pan, with oil it shall be made; in layers you shall bring it — crumbled, it shall be a gift of fragments; you shall present it as accepted and pleasing to God."),
    ],
    15: [
        ("וְהַכֹּהֵן הַמָּשִׁיחַ תַּחְתָּיו מִבָּנָיו יַעֲשֶׂה אֹתָהּ חָק-עוֹלָם לַיהוָה כָּלִיל תָּקְטָר",
         "וכד'אך אלאמאם אלמסתכ'לף בעדה. מן בניה יצנעהא. רסם אלדהר. ללה גמלה תקתר",
         "And likewise the imām who is appointed as his successor from his sons shall make it — a statute forever; it shall be burned entirely to God."),
    ],
    16: [
        ("וְכָל-מִנְחַת כֹּהֵן כָּלִיל תִּהְיֶה לֹא תֵאָכֵל",
         "וסאיר הדאיא אלאמאם. תקתר גמלה ולא תוכל",
         "And the rest of the imām's gift-offerings shall be burned entirely and shall not be eaten."),
    ],
    17: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses, a speaking."),
    ],
    18: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאֶל-בָּנָיו לֵאמֹר זֹאת תּוֹרַת הַחַטָּאת",
         "קל להרון ובניה קאילא. הד'ה שריעה' אלדכוה.",
         "Say to Aaron and his sons, saying: This is the law of the purification-offering —"),
        ("בִּמְקוֹם אֲשֶׁר תִּשָּׁחֵט הָעֹלָה תִּשָּׁחֵט הַחַטָּאת לִפְנֵי יְהוָה--קֹדֶשׁ קָדָשִׁים הִוא",
         "פי מוצ'ע תד'בח אלצעידה. תד'בח אלדכוה בין ידי אללה. מן כ'ואץ אלאקדאס",
         "in the place where the burnt-offering is slaughtered, the purification-offering shall be slaughtered before God; it is among the choicest of the sacred things."),
    ],
    19: [
        ("הַכֹּהֵן הַמְחַטֵּא אֹתָהּ יֹאכְלֶנָּה בְּמָקוֹם קָדֹשׁ תֵּאָכֵל בַּחֲצַר אֹהֶל מוֹעֵד",
         "אלאמאם אלמד'כי בהא יאכלהא. ופי מוצ'ע מקדס תוכל. פי צחן כ'בא אלמחצ'ר",
         "The imām who offers it as a purification-offering shall eat it; it shall be eaten in a consecrated place — in the court of the tent of the presence."),
    ],
    20: [
        ("כֹּל אֲשֶׁר-יִגַּע בִּבְשָׂרָהּ יִקְדָּשׁ",
         "כל מן דנא בלחמהא תקדס.",
         "Everyone who approaches its flesh shall become consecrated;"),
        ("וַאֲשֶׁר יִזֶּה מִדָּמָהּ עַל-הַבֶּגֶד--אֲשֶׁר יִזֶּה עָלֶיהָ תְּכַבֵּס בְּמָקוֹם קָדֹשׁ",
         "ואן אנתצ'ח מן דמהא. אלד'י ינצ'ח מנה עלי'ת'וב. פליג'סל פי מוצ'ע מקדס",
         "and if any of its blood that is sprinkled from it should spatter upon a garment, then it shall be washed in a consecrated place."),
    ],
    21: [
        ("וּכְלִי-חֶרֶשׂ אֲשֶׁר תְּבֻשַּׁל-בּוֹ יִשָּׁבֵר",
         "ואנא אלכ'זף. אלד'י תטבך' פיה יכסר.",
         "And earthenware vessels in which it is cooked shall be broken;"),
        ("וְאִם-בִּכְלִי נְחֹשֶׁת בֻּשָּׁלָה וּמֹרַק וְשֻׁטַּף בַּמָּיִם",
         "ואן טבכ'ת פי אנא נחאס. פלידלך ויגסל באלמא",
         "and if it was cooked in a copper vessel, then it shall be scoured and rinsed with water."),
    ],
    22: [
        ("כָּל-זָכָר בַּכֹּהֲנִים יֹאכַל אֹתָהּ קֹדֶשׁ קָדָשִׁים הִוא",
         "כל ד'כר מן אלאיימה יאכלה. אד' הי מן כ'ואץ אלאקדאס",
         "Every male among the imāms shall eat it, since it is among the choicest of the sacred things."),
    ],
    23: [
        ("וְכָל-חַטָּאת אֲשֶׁר יוּבָא מִדָּמָהּ אֶל-אֹהֶל מוֹעֵד לְכַפֵּר בַּקֹּדֶשׁ--לֹא תֵאָכֵל",
         "וכל דכוה. ידכ'ל מן דמהא. אלי' כ'בא אלמחצ'ר. ליסתג'פר פי אלקדס פלא תוכל.",
         "But every purification-offering of which any blood is brought into the tent of the presence, to seek atonement in the sanctuary — it shall not be eaten;"),
        ("בָּאֵשׁ תִּשָּׂרֵף",
         "בל תחרק באלנאר",
         "rather it shall be burned with fire."),
    ],
}
