"""Hand-authored alignment triples for Vayikra chapter 18.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
    ],
    3: [
        ("כְּמַעֲשֵׂה", "כצנאיע", "as the deeds of"),
        (None, "אהל", "the people of"),
        ("אֶרֶץ", "בלד", "the land of"),
        ("מִצְרַיִם", "מצר", "Egypt"),
        ("אֲשֶׁר", "אלד'י", "in which"),
        ("יְשַׁבְתֶּם-בָּהּ", "אקמתם", "you dwelt"),
        ("לֹא תַעֲשׂוּ", "לא תצנעו", "Do not do"),
        ("וּכְמַעֲשֵׂה", "וכצנאיע", "as the deeds of"),
        (None, "אהל", "the people of"),
        ("אֶרֶץ", "בלד", "the land of"),
        ("כְּנַעַן", "כנעאן", "Canaan"),
        ("אֲשֶׁר", "אלד'י", "to which"),
        ("אֲנִי", "אנא", "I am"),
        ("מֵבִיא אֶתְכֶם", "מדכ'לכם", "bringing you"),
        ("שָׁמָּה", "הנאך", "in there"),
        ("לֹא תַעֲשׂוּ", "לא תצנעו", "do not do"),
        ("וּבְחֻקֹּתֵיהֶם", "וברסומהם", "their customs"),
        ("לֹא תֵלֵכוּ", "לא תסירו", "do not follow"),
    ],
    4: [
        ("אֶת-מִשְׁפָּטַי", "אחכאמי", "My ordinances"),
        ("תַּעֲשׂוּ", "פאצנעו", "you shall carry out"),
        ("וְאֶת-חֻקֹּתַי", "ורסומי", "and My statutes"),
        ("תִּשְׁמְרוּ", "אחפצו", "you shall keep"),
        ("לָלֶכֶת", "וסירו", "and follow"),
        ("בָּהֶם", "בהא", "them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good"),
    ],
    5: [
        ("וּשְׁמַרְתֶּם", "פאחפצו", "Keep"),
        ("אֶת-חֻקֹּתַי", "רסומי", "My statutes"),
        ("וְאֶת-מִשְׁפָּטַי", "ואחכאמי", "and My ordinances"),
        (None, "פאן", "for"),
        (None, "גזא", "the recompense"),
        (None, "אי", "of any"),
        ("הָאָדָם", "אנסאן", "person"),
        ("אֲשֶׁר יַעֲשֶׂה", "עמל", "who acts"),
        ("אֹתָם", "בהא", "according to them"),
        (None, "אן", "is that"),
        ("וָחַי", "יחיא", "he shall live"),
        (None, "אלחיאה אלדאימה", "the everlasting life"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "דאים אלבקא", "enduring in existence"),
    ],
    6: [
        ("אִישׁ", "כל", "Every"),
        ("אִישׁ", "רגל", "man"),
        (None, "מנכם", "among you"),
        ("שְׁאֵר", "נסיב", "a kinswoman"),
        ("בְּשָׂרוֹ", "ד'אתה", "of his own"),
        ("לֹא", "לא", "shall not"),
        ("תִקְרְבוּ", "יתקדם", "approach"),
        ("לְגַלּוֹת", "לכשף", "to uncover"),
        ("עֶרְוָה", "סותהא", "her nakedness"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "נהיתכם ען ד'אלך", "I have forbidden you this"),
    ],
    7: [
        ("עֶרְוַת", "סוות", "The nakedness of"),
        ("אָבִיךָ", "אביך", "your father"),
        ("וְעֶרְוַת", "וסוות", "and the nakedness of"),
        ("אִמְּךָ", "אמך", "your mother"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "אמא", "Now"),
        (None, "וקלת", "when I said"),
        (None, "סוות", "'the nakedness of"),
        (None, "אמך", "your mother'"),
        ("הִוא", "פהי", "she is"),
        ("אִמְּךָ", "אמך", "your mother"),
        (None, "נפסהא", "herself"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֶּה", "תכשפן", "uncover"),
        ("עֶרְוָתָהּ", "סוותהא", "her nakedness"),
    ],
    8: [
        (None, "ואמא", "And as for"),
        ("עֶרְוַת", "סוות", "the nakedness of"),
        ("אָבִיךָ", "אביך", "your father"),
        (None, "פהי", "it is"),
        ("אֵשֶׁת", "זוגה'", "the wife of"),
        ("אָבִיךָ", "אביך", "your father"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֵּה", "תכשפן", "uncover"),
        (None, "סוותהא", "her nakedness"),
    ],
    9: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אֲחוֹתְךָ", "אכ'תך", "your sister"),
        ("בַת", "אבנה'", "the daughter of"),
        ("אָבִיךָ", "אביך", "your father"),
        ("אוֹ", "או", "or"),
        ("בַת", "אבנה'", "the daughter of"),
        ("אִמֶּךָ", "אמך", "your mother"),
        ("מוֹלֶדֶת", "אלמולודה", "whether born"),
        ("בַּיִת", "דאכ'לא", "within"),
        ("אוֹ", "או", "or"),
        ("מוֹלֶדֶת חוּץ", "כ'ארגא", "without"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֶּה", "תכשפן", "uncover"),
        ("עֶרְוָתָן", "סוותהמא", "their nakedness"),
    ],
    10: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("בַּת", "אבנה'", "the daughter of"),
        ("בִּנְךָ", "אבנך", "your son"),
        ("אוֹ", "או", "or"),
        ("בַת", "אבנה'", "the daughter of"),
        ("בִּתְּךָ", "אבנתך", "your daughter"),
        ("לֹא תְגַלֶּה עֶרְוָתָן", "לא תכשפהמא", "you shall not uncover either of them"),
        ("כִּי", "לאנהמא", "for they are"),
        ("עֶרְוָתְךָ", "סוואתך", "your own nakedness"),
    ],
    11: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("בַּת", "אבנה'", "the daughter of"),
        ("אֵשֶׁת", "זוגה'", "the wife of"),
        ("אָבִיךָ", "אביך", "your father"),
        ("מוֹלֶדֶת", "אלמולודה", "born"),
        (None, "מן", "of"),
        ("אָבִיךָ", "אביך", "your father"),
        ("הִוא", "הי", "she is"),
        (None, "אלתי", "the one who"),
        (None, "ביינת", "has been shown"),
        (None, "אנהא", "to be"),
        ("אֲחוֹתְךָ", "אכ'תך", "your sister"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֶּה", "תכשפן", "uncover"),
        ("עֶרְוָתָהּ", "סוותהא", "her nakedness"),
    ],
    12: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אֲחוֹת", "אכ'ת", "sister"),
        ("אָבִיךָ", "אביך", "your father's"),
        ("לֹא", "פלא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "לאנהא", "for she is"),
        ("שְׁאֵר", "נסיבה'", "a kinswoman of"),
        ("אָבִיךָ", "אביך", "your father"),
    ],
    13: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אֲחוֹת", "אכ'ת", "sister"),
        ("אִמְּךָ", "אמך", "your mother's"),
        ("לֹא", "פלא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "לאנהא", "for she is"),
        ("שְׁאֵר", "נסיבה'", "a kinswoman of"),
        ("אִמְּךָ", "אמך", "your mother"),
    ],
    14: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אֲחִי-אָבִיךָ", "עמך", "your uncle"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "וד'אלך אן", "that is"),
        ("לֹא", "לא", "you shall not"),
        ("תִקְרָב", "תתקדם", "approach"),
        ("אֶל-אִשְׁתּוֹ", "אלי' זוגתה", "his wife"),
        (None, "אד'", "for"),
        ("דֹּדָתְךָ", "כעמתך", "she is as your aunt"),
    ],
    15: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("כַּלָּתְךָ", "כנתך", "your daughter-in-law"),
        ("לֹא", "פלא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        ("הִוא", "והי", "she is"),
        ("אֵשֶׁת", "זוגה'", "wife"),
        ("בִּנְךָ", "אבנך", "your son's"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֶּה", "תכשף", "uncover"),
        ("עֶרְוָתָהּ", "סוותהא", "her nakedness"),
    ],
    16: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אֵשֶׁת", "זוגה'", "wife"),
        ("אָחִיךָ", "אכ'יך", "your brother's"),
        ("לֹא", "פלא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "אד' הי", "for she is as"),
        ("עֶרְוַת", "כסוות", "the nakedness of"),
        ("אָחִיךָ", "אכ'יך", "your brother"),
    ],
    17: [
        ("עֶרְוַת", "וסוות", "And the nakedness of"),
        ("אִשָּׁה", "אמראה", "a woman"),
        ("וּבִתָּהּ", "ואבנתהא", "and her daughter"),
        ("לֹא", "לא", "you shall not"),
        ("תְגַלֵּה", "תכשף", "uncover"),
        (None, "וכד'אלך", "likewise"),
        ("בַּת", "אבנה'", "the daughter of"),
        ("בְּנָהּ", "אבנהא", "her son"),
        ("וְאֶת-בַּת", "ואבנה'", "or the daughter of"),
        ("בִּתָּהּ", "אבנתהא", "her daughter"),
        ("לֹא", "לא", "you shall not"),
        ("תִקַּח", "תתכ'ד'", "take her"),
        ("לְגַלּוֹת", "לתכשף", "so as to uncover"),
        ("עֶרְוָתָהּ", "סואתהמא", "their nakedness"),
        (None, "אד'", "for"),
        (None, "הן", "they are"),
        ("שַׁאֲרָה", "נסאיב", "kinswomen of one another"),
        (None, "והי", "and this is"),
        ("זִמָּה", "פאחשה", "lewdness"),
    ],
    18: [
        ("וְאִשָּׁה", "ואמראה", "And a woman"),
        ("אֶל-אֲחֹתָהּ", "מע אכ'תהא", "alongside her sister"),
        ("לֹא", "לא", "you shall not"),
        ("תִקָּח", "תתכ'ד'", "take"),
        ("לִצְרֹר", "לתכון צ'ארתין", "to be a rival to her"),
        ("לְגַלּוֹת", "לתכשף", "to uncover"),
        ("עֶרְוָתָהּ", "סוותהא", "her nakedness"),
        ("עָלֶיהָ", "מעהא", "along with her"),
        ("בְּחַיֶּיהָ", "פי חיאתהא", "in her lifetime"),
    ],
    19: [
        ("וְאֶל", "ואלי'", "And to"),
        ("אִשָּׁה", "אמראה", "a woman"),
        (None, "פי", "in"),
        ("בְּנִדַּת", "חיצ'ה'", "menstrual flow"),
        ("טֻמְאָתָהּ", "נגאסתהא", "the impurity of her"),
        ("לֹא", "לא", "you shall not"),
        ("תִקְרַב", "תתקדם", "approach"),
        ("לְגַלּוֹת", "לתכשף", "to uncover"),
        ("עֶרְוָתָהּ", "סוותהא", "her nakedness"),
    ],
    20: [
        ("וְאֶל", "ומע", "And with"),
        ("אֵשֶׁת", "זוגה'", "the wife of"),
        ("עֲמִיתְךָ", "צאחבך", "your fellow"),
        ("לֹא-תִתֵּן", "לא תגעל", "you shall not make"),
        ("שְׁכָבְתְּךָ", "מצ'אגעתך", "your lying"),
        ("לְזָרַע", "לאנסאל", "for seed"),
        (None, "ולא", "nor"),
        ("לְטָמְאָה", "לאלתנגס", "to defile yourself"),
        ("בָהּ", "בהא", "with her"),
    ],
    21: [
        ("לֹא-תִתֵּן", "לא תעט", "And do not give"),
        ("וּמִזַּרְעֲךָ", "מן נסלך", "of your offspring"),
        ("לְהַעֲבִיר", "לאלתקריב", "for offering"),
        ("לַמֹּלֶךְ", "לאלצנם", "to idols"),
        ("וְלֹא", "ולא", "nor"),
        ("תְחַלֵּל", "תבד'ל", "profane"),
        ("אֶת-שֵׁם", "אסם", "the name of"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        (None, "אלמעאקב", "the Punisher"),
    ],
    22: [
        ("וְאֶת-זָכָר", "ואלד'כר", "And a male"),
        ("לֹא", "פלא", "you shall not"),
        ("תִשְׁכַּב", "תצ'אגעה", "lie with him"),
        (None, "עלי'", "after"),
        (None, "צ'רוב", "the manner of"),
        ("מִשְׁכְּבֵי", "מצ'אגעת", "lying with"),
        ("אִשָּׁה", "אלנסא", "women"),
        (None, "פאנהא", "for it is"),
        ("תּוֹעֵבָה", "כריהה", "an abomination"),
    ],
    23: [
        (None, "ומע", "And with"),
        (None, "שי מן", "any of"),
        ("בְּהֵמָה", "אלבהאים", "the beasts"),
        ("לֹא-תִתֵּן", "לא תגעל", "you shall not make"),
        ("שְׁכָבְתְּךָ", "מצ'אגעתך", "your lying"),
        ("לְטָמְאָה", "לאלתנגס", "so as to defile yourself"),
        ("בָהּ", "בהא", "with it"),
        (None, "וכד'אלך", "and likewise"),
        ("וְאִשָּׁה", "אלאמראה", "a woman"),
        ("לֹא-תַעֲמֹד", "לא תקף", "shall not present herself"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("בְהֵמָה", "בהימה", "a beast"),
        ("לְרִבְעָהּ", "לתנזוהא", "for it to mount her"),
        (None, "פאנהא", "for it is"),
        ("תֶּבֶל", "דאהיה", "a grave calamity"),
    ],
    24: [
        ("אַל-תִּטַּמְּאוּ", "לא תעצוני", "Do not disobey Me"),
        (None, "בשי מן", "in any of"),
        ("בְּכָל-אֵלֶּה", "הד'ה", "these things"),
        ("כִּי", "לאן", "for"),
        ("בְכָל-אֵלֶּה", "במת'להא", "by the like of them"),
        ("נִטְמְאוּ", "עצאני", "disobeyed Me"),
        ("הַגּוֹיִם", "אלאמם", "the nations"),
        ("אֲשֶׁר-אֲנִי", "אלד'י אנא", "those whom I am"),
        ("מְשַׁלֵּחַ", "טארדהם", "expelling"),
        ("מִפְּנֵיכֶם", "מן בין ידיכם", "from before you"),
    ],
    25: [
        (None, "פלמא", "And when"),
        (None, "אהל", "the people of"),
        ("הָאָרֶץ", "אלבלד", "the land"),
        ("וַתִּטְמָא", "נגס", "became defiled"),
        ("וָאֶפְקֹד", "טאלבתהם", "I called them to account"),
        ("עֲו‍ֹנָהּ", "בד'נובהם", "for their sins"),
        ("הָאָרֶץ", "אלבלד", "and the land"),
        ("וַתָּקִא", "פשתת", "scattered"),
        ("אֶת-יֹשְׁבֶיהָ", "אהלה", "its inhabitants"),
    ],
    26: [
        ("וּשְׁמַרְתֶּם", "פאחפצו", "So keep"),
        ("אַתֶּם", "אנתם", "yourselves"),
        ("אֶת-חֻקֹּתַי", "רסומי", "My statutes"),
        ("וְאֶת-מִשְׁפָּטַי", "ואחכאמי", "and My ordinances"),
        ("וְלֹא תַעֲשׂוּ", "ולא תצנעו", "and do"),
        (None, "שייא", "nothing"),
        ("מִכֹּל", "מן", "of all"),
        ("הָאֵלֶּה", "הד'ה", "these"),
        ("הַתּוֹעֵבֹת", "אלמכארה", "abhorrent things"),
        ("הָאֶזְרָח", "אלצריח", "whether the native-born"),
        ("וְהַגֵּר", "ואלג'ריב", "or the stranger"),
        ("הַגָּר", "אלדכ'יל", "who has come to dwell"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
    ],
    27: [
        ("כִּי", "אד'", "For"),
        ("אֶת-כָּל", "גמיע", "all"),
        ("הָאֵל", "הד'ה", "these"),
        ("הַתּוֹעֵבֹת", "אלמכארה", "abhorrent things"),
        ("עָשׂוּ", "צנעהא", "were done by"),
        ("אַנְשֵׁי-הָאָרֶץ", "אהל אלבלד", "the people of the land"),
        ("אֲשֶׁר", "אלד'י", "who were"),
        ("לִפְנֵיכֶם", "מן קבלכם", "before you"),
        ("וַתִּטְמָא", "חתא נגס", "until it became defiled"),
    ],
    28: [
        (None, "ללא", "So that"),
        ("וְלֹא-תָקִיא", "ישתתכם", "shall not scatter you"),
        ("הָאָרֶץ", "אלבלד", "the land"),
        (None, "אלד'י", "to which"),
        ("בְּטַמַּאֲכֶם", "נגסתמוה", "you have brought defilement"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("קָאָה", "שתת", "it scattered"),
        ("אֶת-הַגּוֹי", "אלאמם", "the nations"),
        ("אֲשֶׁר", "אלד'ין", "that were"),
        ("לִפְנֵיכֶם", "קבלכם", "before you"),
    ],
    29: [
        (None, "ואעלמו", "And know"),
        (None, "אן", "that"),
        ("כָּל-אֲשֶׁר", "כל מן", "whoever"),
        ("יַעֲשֶׂה", "יצנע", "does"),
        (None, "שייא", "anything"),
        (None, "מן", "of"),
        ("מִכֹּל", "גמיע", "all"),
        ("הָאֵלֶּה", "הד'ה", "these"),
        ("הַתּוֹעֵבֹת", "אלמכארה", "abhorrent things"),
        ("וְנִכְרְתוּ", "תנקטע", "shall be cut off"),
        (None, "תלך", "those"),
        ("הַנְּפָשׁוֹת", "אלנפוס", "souls"),
        ("הָעֹשֹׂת", "אלצאנעאת", "that do them"),
        ("מִקֶּרֶב", "מן בין", "from among"),
        ("עַמָּם", "קומהא", "their people"),
    ],
    30: [
        ("וּשְׁמַרְתֶּם", "ואחפצו", "And keep"),
        ("אֶת-מִשְׁמַרְתִּי", "מא אסתחפצתכם", "what I have entrusted to you to keep"),
        ("לְבִלְתִּי עֲשׂוֹת", "ללא תצנעו", "so that you do not do"),
        (None, "מן", "any of"),
        ("מֵחֻקּוֹת", "רסום", "the customs of"),
        ("הַתּוֹעֵבֹת", "אלמכארה", "the abhorrent things"),
        ("אֲשֶׁר", "אלתי", "that"),
        ("נַעֲשׂוּ", "צנעת", "were done"),
        ("לִפְנֵיכֶם", "מן קבלכם", "before you"),
        ("וְלֹא תִטַּמְּאוּ", "ולא תעצוני", "and do not disobey Me"),
        ("בָּהֶם", "בהא", "in them"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אגאזיכם כ'ירא", "I shall recompense you with good"),
    ],
}
