"""Hand-authored alignment triples for Vayikra chapter 3."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וְאִם-זֶבַח שְׁלָמִים קָרְבָּנוֹ--אִם מִן-הַבָּקָר הוּא מַקְרִיב אִם-זָכָר אִם-נְקֵבָה",
         "ואן כאן קרבאנה ד'בח סלאמה מן אלבקר. ד'כר או אנת'י",
         "And if his offering be a peace-sacrifice from the cattle — male or female —"),
        ("תָּמִים יַקְרִיבֶנּוּ לִפְנֵי יְהוָה",
         "פליקרבה צחיחא בין ידי אללה",
         "he shall bring it unblemished before God."),
    ],
    2: [
        ("וְסָמַךְ יָדוֹ עַל-רֹאשׁ קָרְבָּנוֹ וּשְׁחָטוֹ פֶּתַח אֹהֶל מוֹעֵד",
         "ויסנד ידה עלי' ראס קרבאנה. ויד'בחה. ענד באב כ'בא אלמחצ'ר",
         "And he shall lay his hand upon the head of his offering, and slaughter it at the door of the tent of the assembly"),
        ("וְזָרְקוּ בְּנֵי אַהֲרֹן הַכֹּהֲנִים אֶת-הַדָּם עַל-הַמִּזְבֵּחַ--סָבִיב",
         "וירשו. בני הרון אלאיימה אלדם. עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron the priests shall sprinkle the blood upon the altar all around."),
    ],
    3: [
        ("וְהִקְרִיב מִזֶּבַח הַשְּׁלָמִים אִשֶּׁה לַיהוָה--אֶת-הַחֵלֶב הַמְכַסֶּה אֶת-הַקֶּרֶב",
         "ויקרב מן ד'בח אלסלאמה קרבאנא ללה. אלת'רב אלמג'טי אלגוף",
         "And he shall offer from the peace-sacrifice an offering to God: the caul-fat covering the innards"),
        ("וְאֵת כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב",
         "וסאיר אלשחם. אלד'י עלי' אלגוף",
         "and all the rest of the fat which is upon the innards,"),
    ],
    4: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת וְאֶת-הַחֵלֶב אֲשֶׁר עֲלֵהֶן אֲשֶׁר עַל-הַכְּסָלִים",
         "ואלכלותין ואלשחם אלד'י עליהמא. אלד'י עלי' אלאחשא",
         "and the two kidneys and the fat which is upon them, which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד עַל-הַכְּלָיוֹת יְסִירֶנָּה",
         "וזיאדה' אלכבד. מע אלכלי' ינזעהא",
         "and the appendage of the liver — together with the kidneys he shall remove them."),
    ],
    5: [
        ("וְהִקְטִירוּ אֹתוֹ בְנֵי-אַהֲרֹן הַמִּזְבֵּחָה עַל-הָעֹלָה אֲשֶׁר עַל-הָעֵצִים אֲשֶׁר עַל-הָאֵשׁ",
         "ויקתרו ד'אלך בני הרון עלי' אלמד'בח. עלי' אלצעידה . אלתי עלי' אלחטב אלד'י עלי' אלנאר",
         "And the sons of Aaron shall burn that upon the altar, upon the layer which is upon the wood that is upon the fire —"),
        ("אִשֵּׁה רֵיחַ נִיחֹחַ לַיהוָה",
         "קרבאן מקבול מרצ'י ללה",
         "an offering acceptable and pleasing to God."),
    ],
    6: [
        ("וְאִם-מִן-הַצֹּאן קָרְבָּנוֹ לְזֶבַח שְׁלָמִים לַיהוָה--זָכָר אוֹ נְקֵבָה",
         "ואן כאן קרבאנה מן אלג'נם. ד'בח סלאמה ללה. ד'כר או אנת'י",
         "And if his offering be from the flock — a peace-sacrifice to God — male or female"),
        ("תָּמִים יַקְרִיבֶנּוּ",
         "פליקרבה צחיחא",
         "he shall bring it unblemished."),
    ],
    7: [
        ("אִם-כֶּשֶׂב הוּא-מַקְרִיב אֶת-קָרְבָּנוֹ--וְהִקְרִיב אֹתוֹ לִפְנֵי יְהוָה",
         "פאן כאן קרבאנה חמלא. פליקרבה בין ידי אללה",
         "If his offering be a lamb, he shall bring it before God."),
    ],
    8: [
        ("וְסָמַךְ אֶת-יָדוֹ עַל-רֹאשׁ קָרְבָּנוֹ וְשָׁחַט אֹתוֹ לִפְנֵי אֹהֶל מוֹעֵד",
         "ויסנד ידה עלי' ראס קרבאנה. ויד'בחה בין ידי כ'בא אלמחצ'ר",
         "And he shall lay his hand upon the head of his offering, and slaughter it before the tent of the assembly"),
        ("וְזָרְקוּ בְּנֵי אַהֲרֹן אֶת-דָּמוֹ עַל-הַמִּזְבֵּחַ--סָבִיב",
         "וירשו בני הרון דמה. עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron shall sprinkle its blood upon the altar all around."),
    ],
    9: [
        ("וְהִקְרִיב מִזֶּבַח הַשְּׁלָמִים אִשֶּׁה לַיהוָה--חֶלְבּוֹ הָאַלְיָה תְמִימָה לְעֻמַּת הֶעָצֶה יְסִירֶנָּה",
         "ויקרב מן ד'בח אלסלאמה קרבאנא ללה. אלת'רב ואלאליה צחיחה . אמאם אלעצעץ ינזעהא",
         "And he shall offer from the peace-sacrifice an offering to God: the caul-fat and the fat-tail, whole, removing it before the base of the spine"),
        ("וְאֶת-הַחֵלֶב הַמְכַסֶּה אֶת-הַקֶּרֶב וְאֵת כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב",
         "ואלת'רב אלמג'טי אלגוף. וסאיר אלשחם. אלד'י עלי' אלגוף",
         "and the caul-fat covering the innards, and all the rest of the fat which is upon the innards,"),
    ],
    10: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת וְאֶת-הַחֵלֶב אֲשֶׁר עֲלֵהֶן אֲשֶׁר עַל-הַכְּסָלִים",
         "ואלכלותין. ואלשחם אלד'י עליהמא. אלד'י עלי' אלאחשא",
         "and the two kidneys and the fat which is upon them, which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד עַל-הַכְּלָיֹת יְסִירֶנָּה",
         "וזיאדה' אלכבד. מע אלכלי' ינזעהא",
         "and the appendage of the liver — together with the kidneys he shall remove them."),
    ],
    11: [
        ("וְהִקְטִירוֹ הַכֹּהֵן הַמִּזְבֵּחָה--לֶחֶם אִשֶּׁה לַיהוָה",
         "ויקתר ד'אלך אלאמאם עלי' אלמד'בח. קרבאן מקבול ללה",
         "And the priest shall burn that upon the altar — an offering acceptable to God."),
    ],
    12: [
        ("וְאִם עֵז קָרְבָּנוֹ--וְהִקְרִיבוֹ לִפְנֵי יְהוָה",
         "ואן כאן קרבאנה מן אלמאעז. פליקרבה בין ידי אללה",
         "And if his offering be from the goats, he shall bring it before God."),
    ],
    13: [
        ("וְסָמַךְ אֶת-יָדוֹ עַל-רֹאשׁוֹ וְשָׁחַט אֹתוֹ לִפְנֵי אֹהֶל מוֹעֵד",
         "ויסנד ידה עלי' ראסה. ויד'בחה. בין ידי כ'בא אלמחצ'ר",
         "And he shall lay his hand upon its head, and slaughter it before the tent of the assembly"),
        ("וְזָרְקוּ בְּנֵי אַהֲרֹן אֶת-דָּמוֹ עַל-הַמִּזְבֵּחַ--סָבִיב",
         "וירשון. בני הרון דמה. עלי' אלמד'בח מסתדירא",
         "and the sons of Aaron shall sprinkle its blood upon the altar all around."),
    ],
    14: [
        ("וְהִקְרִיב מִמֶּנּוּ קָרְבָּנוֹ אִשֶּׁה לַיהוָה--אֶת-הַחֵלֶב הַמְכַסֶּה אֶת-הַקֶּרֶב",
         "ויקרב מנה קרבאנא ללה. אלת'רב אלמג'טי אלגוף",
         "And he shall offer from it an offering to God: the caul-fat covering the innards"),
        ("וְאֵת כָּל-הַחֵלֶב אֲשֶׁר עַל-הַקֶּרֶב",
         "וסאיר אלשחם. אלד'י עלי' אלגוף",
         "and all the rest of the fat which is upon the innards,"),
    ],
    15: [
        ("וְאֵת שְׁתֵּי הַכְּלָיֹת וְאֶת-הַחֵלֶב אֲשֶׁר עֲלֵהֶן אֲשֶׁר עַל-הַכְּסָלִים",
         "ואלכלותין. ואלשחם אלד'י עליהמא. אלד'י עלי' אלאחשא",
         "and the two kidneys and the fat which is upon them, which is upon the entrails"),
        ("וְאֶת-הַיֹּתֶרֶת עַל-הַכָּבֵד עַל-הַכְּלָיֹת יְסִירֶנָּה",
         "וזיאדה' אלכבד. מע אלכלי'' ינזעהא",
         "and the appendage of the liver — together with the kidneys he shall remove them."),
    ],
    16: [
        ("וְהִקְטִירָם הַכֹּהֵן הַמִּזְבֵּחָה--לֶחֶם אִשֶּׁה לְרֵיחַ נִיחֹחַ",
         "ויקתרהא אלאמאם עלי' אלמד'בח. קרבאנא מחרקא מרצ'י מקבול",
         "And the priest shall burn them upon the altar — a burnt offering, pleasing and acceptable"),
        ("כָּל-חֵלֶב לַיהוָה",
         "כל שחם כד'אך ללה",
         "all fat is thus for God."),
    ],
    17: [
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם בְּכֹל מוֹשְׁבֹתֵיכֶם",
         "רסם אלדהר עלי' מר אגיאלכם. פי גמיע מסאכנכם",
         "A perpetual ordinance throughout your generations, in all your dwellings"),
        ("כָּל-חֵלֶב וְכָל-דָּם לֹא תֹאכֵלוּ",
         "כל שחם וכל דם לא תאכלו",
         "no fat and no blood shall you eat."),
    ],
}
