"""Hand-authored alignment triples for Vayikra chapter 16."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה אַחֲרֵי מוֹת שְׁנֵי בְּנֵי אַהֲרֹן",
         "אן כלם אללה מוסי'. בעד מות אבני הרון.",
         "And God spoke to Moses after the death of the two sons of Aaron —"),
        ("בְּקָרְבָתָם לִפְנֵי-יְהוָה וַיָּמֻתוּ",
         "אד' תקדמא בין ידי אללה עלי' מא ביין פמאתא",
         "when they had drawn near before God in a manner that became clear, and they died."),
    ],
    2: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה דַּבֵּר אֶל-אַהֲרֹן אָחִיךָ",
         "וקאל לה. מר הרון אכ'יך.",
         "And He said to him: 'Command Aaron your brother"),
        ("וְאַל-יָבֹא בְכָל-עֵת אֶל-הַקֹּדֶשׁ מִבֵּית לַפָּרֹכֶת--אֶל-פְּנֵי הַכַּפֹּרֶת אֲשֶׁר עַל-הָאָרֹן",
         "באן לא ידכ'ל פי כתיר. מן אלאוקאת אלי' אלקדס. מן דאכ'ל אלסגף. מן חצ'רה' אלג'שא. אלד'י עלי' אלצנדוק",
         "that he shall not enter at many times into the sanctuary from within the veil, near the covering which is upon the ark,"),
        ("וְלֹא יָמוּת כִּי בֶּעָנָן אֵרָאֶה עַל-הַכַּפֹּרֶת",
         "ללא ימות. לאני מתגלי באלג'מאם פוק אלג'שא",
         "lest he die — for I am continually revealing Myself in the cloud above the covering.'"),
    ],
    3: [
        ("בְּזֹאת יָבֹא אַהֲרֹן אֶל-הַקֹּדֶשׁ",
         "בהד'א אלאמור ידכ'ל הרון אלי' אלקדס.",
         "With these matters shall Aaron enter into the sanctuary:"),
        ("בְּפַר בֶּן-בָּקָר לְחַטָּאת וְאַיִל לְעֹלָה",
         "באן יחצ'ר רת'א מן אלבקר. לאלד'כוה וכבשא לאלצעידה",
         "by presenting a bull from the cattle for the purification-offering, and a ram for the ascending-offering."),
    ],
    4: [
        ("כְּתֹנֶת-בַּד קֹדֶשׁ יִלְבָּשׁ וּמִכְנְסֵי-בַד יִהְיוּ עַל-בְּשָׂרוֹ",
         "ואן ילבס תוניה מן עשר מקדסה. בעד אן יכון עלי' בדנה סראויל מן עשר.",
         "And that he shall wear a tunic of fine linen, consecrated; after there are upon his body breeches of fine linen,"),
        ("וּבְאַבְנֵט בַּד יַחְגֹּר וּבְמִצְנֶפֶת בַּד יִצְנֹף בִּגְדֵי-קֹדֶשׁ הֵם",
         "ויתקלד בזנאר מן עשר מחץ' ויתעמם בעמאמה מת'ל ד'אלך פהד'ה הי ת'יאב אלקדס.",
         "and he shall gird himself with a sash of pure fine linen, and shall wind upon his head a turban likewise — these are the garments of the sanctuary;"),
        ("וְרָחַץ בַּמַּיִם אֶת-בְּשָׂרוֹ וּלְבֵשָׁם",
         "יג'סל בדנה באלמא וילבסהא",
         "he shall wash his body with water and put them on."),
    ],
    5: [
        ("וּמֵאֵת עֲדַת בְּנֵי יִשְׂרָאֵל יִקַּח שְׁנֵי-שְׂעִירֵי עִזִּים לְחַטָּאת וְאַיִל אֶחָד לְעֹלָה",
         "וליאכ'ד' מן גמאעה' בני אסראיל. עתודין מן אלמאעז לאלד'כוה. וכבשא לאלצעידה",
         "And he shall take from the assembly of the sons of Israel two he-goats from the goats for the purification-offering, and a ram for the ascending-offering."),
    ],
    6: [
        ("וְהִקְרִיב אַהֲרֹן אֶת-פַּר הַחַטָּאת אֲשֶׁר-לוֹ",
         "פיבתדי אוולא. ויקדם רת' אלד'כוה אלד'י לה.",
         "And he shall begin first, and present the bull of the purification-offering which is his,"),
        ("וְכִפֶּר בַּעֲדוֹ וּבְעַד בֵּיתוֹ",
         "ויסתג'פר ענה וען אלה",
         "and seek forgiveness for himself and for his household."),
    ],
    7: [
        ("וְלָקַח אֶת-שְׁנֵי הַשְּׂעִירִם וְהֶעֱמִיד אֹתָם לִפְנֵי יְהוָה פֶּתַח אֹהֶל מוֹעֵד",
         "ת'ם יאכ'ד' אלעתודין. ויוקפהמא בין ידי אללה. ענד באב כ'בא אלמחצ'ר",
         "Then he shall take the two he-goats and station them before God at the entrance of the tent of the assembly."),
    ],
    8: [
        ("וְנָתַן אַהֲרֹן עַל-שְׁנֵי הַשְּׂעִירִם גֹּרָלוֹת--גּוֹרָל אֶחָד לַיהוָה וְגוֹרָל אֶחָד לַעֲזָאזֵל",
         "וילקי עליהמא סהמין. אחדהמא לבית אללה. ואלאכ'ר לגבל עזאז",
         "And he shall cast upon them two lots — one of the two for the house of God, and the other for Mount Azazel."),
    ],
    9: [
        ("וְהִקְרִיב אַהֲרֹן אֶת-הַשָּׂעִיר אֲשֶׁר עָלָה עָלָיו הַגּוֹרָל לַיהוָה וְעָשָׂהוּ חַטָּאת",
         "פיקדם אלעתוד. אלד'י וקע עליה אלסהם לבית אללה. ויצנעה ד'כוה",
         "And he shall present the he-goat upon which the lot fell for the house of God, and make it a purification-offering."),
    ],
    10: [
        ("וְהַשָּׂעִיר אֲשֶׁר עָלָה עָלָיו הַגּוֹרָל לַעֲזָאזֵל יָעֳמַד-חַי לִפְנֵי יְהוָה לְכַפֵּר עָלָיו",
         "ואלעתוד. אלד'י וקע עליה אלסהם לגבל עזאז. יוקף חייא. בין ידי אללה ליסתג'פר ענדה.",
         "And the he-goat upon which the lot fell for Mount Azazel shall be left standing alive before God, to seek forgiveness thereby;"),
        ("לְשַׁלַּח אֹתוֹ לַעֲזָאזֵל הַמִּדְבָּרָה",
         "ת'ם יטלקה. פי גבל עזאז פי אלבר",
         "then he shall release it on Mount Azazel in the wilderness."),
    ],
    11: [
        ("וְהִקְרִיב אַהֲרֹן אֶת-פַּר הַחַטָּאת אֲשֶׁר-לוֹ וְכִפֶּר בַּעֲדוֹ וּבְעַד בֵּיתוֹ",
         "ויקדם הרון ת'אניה. רת' אלד'כוה אלד'י לה. ויסתג'פר ענה וען אלה.",
         "And Aaron shall present a second time the bull of the purification-offering which is his, and seek forgiveness for himself and for his household;"),
        ("וְשָׁחַט אֶת-פַּר הַחַטָּאת אֲשֶׁר-לוֹ",
         "ת'ם יד'בחה",
         "then he shall slaughter it."),
    ],
    12: [
        ("וְלָקַח מְלֹא-הַמַּחְתָּה גַּחֲלֵי-אֵשׁ מֵעַל הַמִּזְבֵּחַ מִלִּפְנֵי יְהוָה",
         "ת'ם יאכ'ד מל אלמגמרה. גמר נאר. מן פוק אלמד'בח מן בין ידי אללה.",
         "Then he shall take a firepan full of glowing coals of fire from atop the altar before God,"),
        ("וּמְלֹא חָפְנָיו קְטֹרֶת סַמִּים דַּקָּה וְהֵבִיא מִבֵּית לַפָּרֹכֶת",
         "ומל חפניה. מן בכ'ור אלצמוג' אלמדקוק. וידכ'ל אלגמיע אלי' דאכ'ל אלסגף",
         "and two handfuls of finely ground resinous incense, and bring them all within the veil."),
    ],
    13: [
        ("וְנָתַן אֶת-הַקְּטֹרֶת עַל-הָאֵשׁ לִפְנֵי יְהוָה",
         "וילקי ד'אלך אלבכ'ור. עלי' אלנאר בין ידי אללה.",
         "And he shall place that incense upon the fire before God,"),
        ("וְכִסָּה עֲנַן הַקְּטֹרֶת אֶת-הַכַּפֹּרֶת אֲשֶׁר עַל-הָעֵדוּת--וְלֹא יָמוּת",
         "חתי יג'טי צ'באב אלבכ'ור. אלג'שא. אלד'י עלי' אלצנדוק פאנה לא ימות",
         "until the cloud of the incense covers the covering which is upon the ark — and so he shall not die."),
    ],
    14: [
        ("וְלָקַח מִדַּם הַפָּר וְהִזָּה בְאֶצְבָּעוֹ עַל-פְּנֵי הַכַּפֹּרֶת קֵדְמָה",
         "ת'ם יאכ'ד' מן דם אלרת'. וינצ'ח מנה באצבעה. קבאלה' אלג'שא שרקייא מרה ואחדה.",
         "Then he shall take some of the blood of the bull and sprinkle from it with his finger facing the covering on the east side, once;"),
        ("וְלִפְנֵי הַכַּפֹּרֶת יַזֶּה שֶׁבַע-פְּעָמִים מִן-הַדָּם--בְּאֶצְבָּעוֹ",
         "ת'ם ינצ'ח בין ידיה מנה סבע מראר",
         "then he shall sprinkle before it from it seven times."),
    ],
    15: [
        ("וְשָׁחַט אֶת-שְׂעִיר הַחַטָּאת אֲשֶׁר לָעָם וְהֵבִיא אֶת-דָּמוֹ אֶל-מִבֵּית לַפָּרֹכֶת",
         "ת'ם יד'בח עתוד אלד'כוה אלד'י לאלקום. וידכ'ל מן דמה אלי' דאכ'ל אלסגף.",
         "Then he shall slaughter the he-goat of the purification-offering which is for the people, and bring some of its blood within the veil,"),
        ("וְעָשָׂה אֶת-דָּמוֹ כַּאֲשֶׁר עָשָׂה לְדַם הַפָּר וְהִזָּה אֹתוֹ עַל-הַכַּפֹּרֶת וְלִפְנֵי הַכַּפֹּרֶת",
         "ויצנע בה. כמא צנע בדם אלרת'. וינצ'ח מנה. קבאלה' אלג'שא ובין ידיה",
         "and do with it as he did with the blood of the bull; and he shall sprinkle from it facing the covering and before it."),
    ],
    16: [
        ("וְכִפֶּר עַל-הַקֹּדֶשׁ מִטֻּמְאֹת בְּנֵי יִשְׂרָאֵל וּמִפִּשְׁעֵיהֶם לְכָל-חַטֹּאתָם",
         "ויסתג'פר פי אלקדס. ען מעאצי בני אסראיל. וגרומהם וגמיע ד'נובהם.",
         "And he shall seek forgiveness in the sanctuary for the transgressions of the sons of Israel, their offenses and all their sins;"),
        ("וְכֵן יַעֲשֶׂה לְאֹהֶל מוֹעֵד הַשֹּׁכֵן אִתָּם בְּתוֹךְ טֻמְאֹתָם",
         "וכד'אלך יצנע פי אלדמוין. פי כ'בא אלמחצ'ר. אלד'י הו סאכן מעהם. פי מא בין מעאציהם",
         "and likewise he shall do with the two bloods in the tent of the assembly, which is dwelling among them amid their transgressions."),
    ],
    17: [
        ("וְכָל-אָדָם לֹא-יִהְיֶה בְּאֹהֶל מוֹעֵד בְּבֹאוֹ לְכַפֵּר בַּקֹּדֶשׁ--עַד-צֵאתוֹ",
         "ולא יכון אחד מן אלנאס פי כ'בא אלמחצ'ר. חין ידכ'ל ליסתג'פר פי אלקדס אלי' אן יכ'רג.",
         "And no one from the people shall be in the tent of the assembly when he enters to seek forgiveness in the sanctuary, until he comes out,"),
        ("וְכִפֶּר בַּעֲדוֹ וּבְעַד בֵּיתוֹ וּבְעַד כָּל-קְהַל יִשְׂרָאֵל",
         "וקד אסתג'פר ענה וען אלה. וען גמיע גוק אל אסראיל",
         "having sought forgiveness for himself and for his household and for the entire assembly of the house of Israel."),
    ],
    18: [
        ("וְיָצָא אֶל-הַמִּזְבֵּחַ אֲשֶׁר לִפְנֵי-יְהוָה--וְכִפֶּר עָלָיו",
         "ת'ם יכ'רג אלי' אלמד'בח. אלד'י בין ידי אללה פיסתג'פר ענה.",
         "Then he shall go out to the altar which is before God and seek forgiveness for it —"),
        ("וְלָקַח מִדַּם הַפָּר וּמִדַּם הַשָּׂעִיר וְנָתַן עַל-קַרְנוֹת הַמִּזְבֵּחַ סָבִיב",
         "באן יאכ'ד' מן דם אלרת' ומע דם אלעתוד מגמועין. ויצ'ע עלי' ארכאנה מסתדירא",
         "by taking from the blood of the bull together with the blood of the he-goat combined, and placing it upon its horns all around."),
    ],
    19: [
        ("וְהִזָּה עָלָיו מִן-הַדָּם בְּאֶצְבָּעוֹ שֶׁבַע פְּעָמִים",
         "וינצ'ח עלי' סטחה מנה. באצבעה סבע מראר.",
         "And he shall sprinkle upon its surface from it with his finger seven times,"),
        ("וְטִהֲרוֹ וְקִדְּשׁוֹ מִטֻּמְאֹת בְּנֵי יִשְׂרָאֵל",
         "ויטהרה ויקדסה מן מעאצי בני אסראיל",
         "and purify it and sanctify it from the transgressions of the sons of Israel."),
    ],
    20: [
        ("וְכִלָּה מִכַּפֵּר אֶת-הַקֹּדֶשׁ וְאֶת-אֹהֶל מוֹעֵד וְאֶת-הַמִּזְבֵּחַ",
         "פאד'א פרג' מן אלאסתג'פאר פי אלקדס. ופי כ'בא אלמחצ'ר וענד אלמד'בח.",
         "And when he has finished the seeking of forgiveness in the sanctuary, and in the tent of the assembly, and at the altar,"),
        ("וְהִקְרִיב אֶת-הַשָּׂעִיר הֶחָי",
         "יקדם אלעתוד אלחי",
         "he shall present the living he-goat."),
    ],
    21: [
        ("וְסָמַךְ אַהֲרֹן אֶת-שְׁתֵּי יָדָו עַל רֹאשׁ הַשָּׂעִיר הַחַי וְהִתְוַדָּה עָלָיו אֶת-כָּל-עֲו‍ֹנֹת בְּנֵי יִשְׂרָאֵל וְאֶת-כָּל-פִּשְׁעֵיהֶם לְכָל-חַטֹּאתָם",
         "ויסנד ידה עלי' ראסה. ויקר בד'נוב בני אסראיל. וגרומהם וגמיע כ'טאיאהם.",
         "And he shall lean his hand upon its head, and confess the sins of the sons of Israel, their offenses and all their transgressions;"),
        ("וְנָתַן אֹתָם עַל-רֹאשׁ הַשָּׂעִיר וְשִׁלַּח בְּיַד-אִישׁ עִתִּי הַמִּדְבָּרָה",
         "פאד'א תלאהא ענד ראס אלעתוד. בעת' בה מע רגל מעד בה אלי' אלבר",
         "and when he has recited them at the head of the he-goat, he shall send it away with a man appointed for this, into the wilderness."),
    ],
    22: [
        ("וְנָשָׂא הַשָּׂעִיר עָלָיו אֶת-כָּל-עֲו‍ֹנֹתָם אֶל-אֶרֶץ גְּזֵרָה",
         "פהו יחמל אלעתוד עלי' ענקה. ען גמיע ד'נובהם אלי' ארץ' מנקטעה.",
         "And it shall bear upon its neck all their sins to a cut-off land;"),
        ("וְשִׁלַּח אֶת-הַשָּׂעִיר בַּמִּדְבָּר",
         "ת'ם יטלקה פי אלבר",
         "and then he shall release it in the wilderness."),
    ],
    23: [
        ("וּבָא אַהֲרֹן אֶל-אֹהֶל מוֹעֵד וּפָשַׁט אֶת-בִּגְדֵי הַבָּד אֲשֶׁר לָבַשׁ בְּבֹאוֹ אֶל-הַקֹּדֶשׁ וְהִנִּיחָם שָׁם",
         "ת'ם ידכ'ל הרון אלי' כ'בא אלמחצ'ר. פיכ'רג אלמגמרה. ת'ם ינזע ת'יאב אלעשר. אלד'י לבסהא פי דכ'ולה אלי' אלקדס. וידעהא הנאך",
         "Then Aaron shall enter the tent of the assembly and bring out the firepan; then he shall remove there the garments of fine linen which he had worn upon his entry into the sanctuary, and leave them there."),
    ],
    24: [
        ("וְרָחַץ אֶת-בְּשָׂרוֹ בַמַּיִם בְּמָקוֹם קָדוֹשׁ וְלָבַשׁ אֶת-בְּגָדָיו",
         "ת'ם יג'סל בדנה באלמא פי מוצ'ע מקדס. וילבס ת'יאבה אלמעלומה.",
         "Then he shall wash his body with water in a consecrated place and put on his known garments;"),
        ("וְיָצָא וְעָשָׂה אֶת-עֹלָתוֹ וְאֶת-עֹלַת הָעָם וְכִפֶּר בַּעֲדוֹ וּבְעַד הָעָם",
         "ת'ם יכ'רג. ויקרב צואעדה וצואעד אלקום. ויסתג'פר ענה וענהם",
         "then he shall go out and offer his ascending-offerings and the ascending-offerings of the people, and seek forgiveness for himself and for them."),
    ],
    25: [
        ("וְאֵת חֵלֶב הַחַטָּאת יַקְטִיר הַמִּזְבֵּחָה",
         "ושחום אלד'כואת יקתרהא עלי' אלמד'בח",
         "And the fats of the purification-offerings he shall burn as smoke upon the altar."),
    ],
    26: [
        ("וְהַמְשַׁלֵּחַ אֶת-הַשָּׂעִיר לַעֲזָאזֵל--יְכַבֵּס בְּגָדָיו וְרָחַץ אֶת-בְּשָׂרוֹ בַּמָּיִם",
         "ואלמטלק אלעתוד פי גבל עזאז. יג'סל ת'יאבה. וירחץ' בדנה באלמא.",
         "And the one who releases the he-goat on Mount Azazel shall wash his garments and bathe his body with water;"),
        ("וְאַחֲרֵי-כֵן יָבוֹא אֶל-הַמַּחֲנֶה",
         "ובעד ד'אלך ידכ'ל אלי' אלעסכר",
         "and after that he shall enter the camp."),
    ],
    27: [
        ("וְאֵת פַּר הַחַטָּאת וְאֵת שְׂעִיר הַחַטָּאת אֲשֶׁר הוּבָא אֶת-דָּמָם לְכַפֵּר בַּקֹּדֶשׁ--יוֹצִיא אֶל-מִחוּץ לַמַּחֲנֶה",
         "ואמא רת' אלד'כוה ועתוד אלד'כוה. אלד'י אדכ'ל מן דמאהמא לאלאסתג'פאר פי אלקדס. פליכ'רגהא אלי' כ'ארג אלעסכר.",
         "And as for the bull of the purification-offering and the he-goat of the purification-offering, whose blood was brought in to seek forgiveness in the sanctuary — he shall bring them out to outside the camp,"),
        ("וְשָׂרְפוּ בָאֵשׁ אֶת-עֹרֹתָם וְאֶת-בְּשָׂרָם וְאֶת-פִּרְשָׁם",
         "ויחרקו באלנאר. גלודהא ולחומהא ופרת'המא",
         "and they shall be burned with fire: their hides and their flesh and their dung."),
    ],
    28: [
        ("וְהַשֹּׂרֵף אֹתָם--יְכַבֵּס בְּגָדָיו וְרָחַץ אֶת-בְּשָׂרוֹ בַּמָּיִם",
         "ואלמחרקהמא. יגסל ת'יאבה. וירחץ' בדנה באלמא.",
         "And the one who burns them shall wash his garments and bathe his body with water;"),
        ("וְאַחֲרֵי-כֵן יָבוֹא אֶל-הַמַּחֲנֶה",
         "ובעד ד'אלך ידכ'ל אלי' אלעסכר",
         "and after that he shall enter the camp."),
    ],
    29: [
        ("וְהָיְתָה לָכֶם לְחֻקַּת עוֹלָם בַּחֹדֶשׁ הַשְּׁבִיעִי בֶּעָשׂוֹר לַחֹדֶשׁ תְּעַנּוּ אֶת-נַפְשֹׁתֵיכֶם",
         "פיכון ד'אלך לכם רסם אלדהר. פי אליום אלעאשר. מן אלשהר אלסאבע תגיעו אנפסכם.",
         "And this shall be for you a perpetual ordinance: on the tenth day of the seventh month you shall afflict yourselves,"),
        ("וְכָל-מְלָאכָה לֹא תַעֲשׂוּ--הָאֶזְרָח וְהַגֵּר הַגָּר בְּתוֹכְכֶם",
         "ושיי מן אלאעמאל לא תעמלו. אלצריח. ואלג'ריב אלדכ'יל פי מא בינכם",
         "and no work whatsoever shall you do — the native-born and the stranger who sojourns among you."),
    ],
    30: [
        ("כִּי-בַיּוֹם הַזֶּה יְכַפֵּר עֲלֵיכֶם לְטַהֵר אֶתְכֶם",
         "ופי הדא אליום. יסתג'פר ענכם ליטהרכם כמא ביינת.",
         "For on this day he shall seek forgiveness for you to purify you, as I have declared;"),
        ("מִכֹּל חַטֹּאתֵיכֶם לִפְנֵי יְהוָה תִּטְהָרוּ",
         "פמן גמיע כ'טאיאכם. בין ידי אללה תטהרון",
         "from all your sins before God you shall be purified."),
    ],
    31: [
        ("שַׁבַּת שַׁבָּתוֹן הִיא לָכֶם וְעִנִּיתֶם אֶת-נַפְשֹׁתֵיכֶם--חֻקַּת עוֹלָם",
         "וסבת הי עטלה לכם. אד' תגיעון אנפסכם. רסם אלדהר",
         "And it is a Sabbath — a complete rest for you — when you afflict yourselves: a perpetual ordinance."),
    ],
    32: [
        ("וְכִפֶּר הַכֹּהֵן אֲשֶׁר-יִמְשַׁח אֹתוֹ וַאֲשֶׁר יְמַלֵּא אֶת-יָדוֹ לְכַהֵן תַּחַת אָבִיו",
         "וכד'אלך יסתג'פר אלאמאם אלד'י ימסח. ויכמל ואגבה. ליאם מכאן אביה.",
         "And likewise shall the imām who is anointed and completes his obligation to officiate in place of his father seek forgiveness;"),
        ("וְלָבַשׁ אֶת-בִּגְדֵי הַבָּד בִּגְדֵי הַקֹּדֶשׁ",
         "פלילבס ת'יאב אלעשר ת'יאב אלקדס",
         "and he shall put on the garments of fine linen, the garments of the sanctuary."),
    ],
    33: [
        ("וְכִפֶּר אֶת-מִקְדַּשׁ הַקֹּדֶשׁ וְאֶת-אֹהֶל מוֹעֵד וְאֶת-הַמִּזְבֵּחַ יְכַפֵּר",
         "ויסתג'פר פי כ'ואץ' אלאקדאס. ופי כ'בא אלמחצ'ר. וענד אלמד'בח. יסתג'פר פיהא.",
         "And he shall seek forgiveness in the innermost of the sanctuaries, and in the tent of the assembly, and at the altar he shall seek forgiveness therein —"),
        ("וְעַל הַכֹּהֲנִים וְעַל-כָּל-עַם הַקָּהָל יְכַפֵּר",
         "ען אלאימה וען סאיר אלגוק",
         "for the imāms and for the rest of the assembly."),
    ],
    34: [
        ("וְהָיְתָה-זֹּאת לָכֶם לְחֻקַּת עוֹלָם לְכַפֵּר עַל-בְּנֵי יִשְׂרָאֵל מִכָּל-חַטֹּאתָם--אַחַת בַּשָּׁנָה",
         "פתכון הדה לכם רסם אלדהר. אן יסתג'פר כד'אך. ען בני אסראיל מן גמיע כ'טאיאהם. מרה ואחדה פי אלסנה.",
         "And this shall be for you a perpetual ordinance, that forgiveness be sought thus for the sons of Israel from all their sins, once a year.'"),
        ("וַיַּעַשׂ כַּאֲשֶׁר צִוָּה יְהוָה אֶת-מֹשֶׁה",
         "פצנע כמא אמר אללה מוסי'",
         "And he did as God had commanded Moses."),
    ],
}
