"""Hand-authored alignment triples for Vayikra chapter 22."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאֶל-בָּנָיו וְיִנָּזְרוּ מִקָּדְשֵׁי בְנֵי-יִשְׂרָאֵל",
         "מר הרון ובניה. באן יגאנבו אקדאס בני אסראיל",
         "Command Aaron and his sons, that they keep away from the holy things of the sons of Israel,"),
        ("וְלֹא יְחַלְּלוּ אֶת-שֵׁם קָדְשִׁי--אֲשֶׁר הֵם מַקְדִּשִׁים לִי אֲנִי יְהוָה",
         "ולא יבד'לו מא סמיתה קדסא. ממא הם מקדסוה לי. אנא אללה שרפתה",
         "and not treat lightly what I have called by the name of holy — of what they are consecrating to Me. I am God, who has honored it."),
    ],
    3: [
        ("אֱמֹר אֲלֵהֶם לְדֹרֹתֵיכֶם כָּל-אִישׁ אֲשֶׁר-יִקְרַב מִכָּל-זַרְעֲכֶם אֶל-הַקֳּדָשִׁים אֲשֶׁר יַקְדִּישׁוּ בְנֵי-יִשְׂרָאֵל לַיהוָה",
         "קל להם. אי רגל מן נסלכם עלי' מר אגיאלכם. תקדם אלי' אלאקדאס אלדי יקדסוהא בני אסראיל ללה",
         "Say to them: any man from your lineage, throughout the passing of your generations, who approaches the holy things which the sons of Israel consecrate to God,"),
        ("וְטֻמְאָתוֹ עָלָיו וְנִכְרְתָה הַנֶּפֶשׁ הַהִוא מִלְּפָנַי--אֲנִי יְהוָה",
         "והו פי חד נגס ילזמה פתכ'תרם תלך אלנפס מן עאלמי. אנא אללה אלמעאקב",
         "while he is in a state of impurity that clings to him — that soul shall be cut off from My world. I am God, the Punisher."),
    ],
    4: [
        ("אִישׁ אִישׁ מִזֶּרַע אַהֲרֹן וְהוּא צָרוּעַ אוֹ זָב--בַּקֳּדָשִׁים לֹא יֹאכַל עַד אֲשֶׁר יִטְהָר",
         "אי רג'ל מן נסל הרון. פי מא הו אברץ או ד'איב. פלא יאכ'ל מן אלאקדאס. אלי' אן יטהר",
         "Any man of the lineage of Aaron who is afflicted with a skin-disease or has a discharge shall not eat of the holy things until he is purified;"),
        ("וְהַנֹּגֵעַ בְּכָל-טְמֵא-נֶפֶשׁ אוֹ אִישׁ אֲשֶׁר-תֵּצֵא מִמֶּנּוּ שִׁכְבַת-זָרַע",
         "ומן מס נגיס במיית. או כ'רגת מנה נטפה' אנסאל",
         "and whoever touches one who is impure through contact with a dead person, or from whom a drop of seminal emission has issued —"),
    ],
    5: [
        ("אוֹ-אִישׁ אֲשֶׁר יִגַּע בְּכָל-שֶׁרֶץ אֲשֶׁר יִטְמָא-לוֹ",
         "ואי רג'ל דנא. בכל דביב סבילה אן ינגס מנה",
         "and any man who has approached any creeping thing by which he may become impure,"),
        ("אוֹ בְאָדָם אֲשֶׁר יִטְמָא-לוֹ לְכֹל טֻמְאָתוֹ",
         "או באנסאן סבילה אן ינגס מנה. עלי' צ'רוב נגאסתה",
         "or a person by whom he may become impure — according to the ways of his impurity —"),
    ],
    6: [
        ("נֶפֶשׁ אֲשֶׁר תִּגַּע-בּוֹ וְטָמְאָה עַד-הָעָרֶב וְלֹא יֹאכַל מִן-הַקֳּדָשִׁים",
         "פאי אנסאן דנא בשי מן ד'אלך. פלינגס אלי' אלליל. ולא יאכל מן אלאקדאס",
         "any person who has approached any such thing shall be impure until the night, and shall not eat of the holy things"),
        ("כִּי אִם-רָחַץ בְּשָׂרוֹ בַּמָּיִם",
         "אלא אן ג'סל בדנה באלמא",
         "unless he has washed his body with water."),
    ],
    7: [
        ("וּבָא הַשֶּׁמֶשׁ וְטָהֵר",
         "פאד'א ג'אבת אלשמס פקד טהר",
         "And when the sun has set, he is then purified;"),
        ("וְאַחַר יֹאכַל מִן-הַקֳּדָשִׁים כִּי לַחְמוֹ הוּא",
         "ובעד ד'אלך יאכל מן אלאקדאס. לאנה טעאמה",
         "and after that he may eat of the holy things, for it is his food."),
    ],
    8: [
        ("נְבֵלָה וּטְרֵפָה לֹא יֹאכַל לְטָמְאָה-בָהּ",
         "ואלנבילה ואלסקימה. לא יאכלהא פיעציני בהא",
         "The carcass and the diseased animal he shall not eat, lest he disobey Me through it."),
        ("אֲנִי יְהוָה",
         "אנא אללה אלמעאקב",
         "I am God, the Punisher."),
    ],
    9: [
        ("וְשָׁמְרוּ אֶת-מִשְׁמַרְתִּי וְלֹא-יִשְׂאוּ עָלָיו חֵטְא",
         "פליחפצו מא אסתחפצ'תהם. ולא יחמלו ענה וזרא",
         "They shall guard what I have entrusted to their guardianship, and shall not bear sin because of it,"),
        ("וּמֵתוּ בוֹ כִּי יְחַלְּלֻהוּ אֲנִי יְהוָה מְקַדְּשָׁם",
         "פיהלכון אד' הם תבד'לוה. לאני אללה מקדסהם בד'אלך",
         "lest they be destroyed when they have treated it lightly — for I am God who sanctifies them thereby."),
    ],
    10: [
        ("וְכָל-זָר לֹא-יֹאכַל קֹדֶשׁ",
         "וכל אגנבי לא יאכל קדסא",
         "And no outsider shall eat of a holy thing —"),
        ("תּוֹשַׁב כֹּהֵן וְשָׂכִיר לֹא-יֹאכַל קֹדֶשׁ",
         "חתא צ'יף אלאמאם ואגירה לא יאכ'ל קדסא",
         "not even the guest of the priest nor his hired worker shall eat of a holy thing."),
    ],
    11: [
        ("וְכֹהֵן כִּי-יִקְנֶה נֶפֶשׁ קִנְיַן כַּסְפּוֹ--הוּא יֹאכַל בּוֹ",
         "ואי אמאם אשתרא אנסאן שראא במאלה. פהו יאכל מנה",
         "But any priest who has purchased a person by purchase with his money — he may eat of it;"),
        ("וִילִיד בֵּיתוֹ הֵם יֹאכְלוּ בְלַחְמוֹ",
         "וכד'אלך תיאליד ביתה. הם יאכלון מן טעאמה",
         "and likewise those born into his household, they may eat of his food."),
    ],
    12: [
        ("וּבַת-כֹּהֵן--כִּי תִהְיֶה לְאִישׁ זָר הִוא בִּתְרוּמַת הַקֳּדָשִׁים לֹא תֹאכֵל",
         "ואייה' אבנה' אמאם. תזווגת רגלא אגנבייא. פהי לא תאכל מן רפאיע אלאקדאס",
         "And any daughter of a priest who has married an outsider man — she shall not eat of the elevated portions of the holy things."),
    ],
    13: [
        ("וּבַת-כֹּהֵן כִּי תִהְיֶה אַלְמָנָה וּגְרוּשָׁה וְזֶרַע אֵין לָהּ--וְשָׁבָה אֶל-בֵּית אָבִיהָ כִּנְעוּרֶיהָ",
         "ואייה' אבנה' אמאם צארת ארמלה או מטלקה. ולא נסל להא. פלתעוד אלי' בית אביהא כחכם צבאיהא",
         "But any daughter of a priest who has become a widow or been divorced, and has no offspring — let her return to her father's house, as in the rule of her girlhood,"),
        ("מִלֶּחֶם אָבִיהָ תֹּאכֵל וְכָל-זָר לֹא-יֹאכַל בּוֹ",
         "ומן טעאמה תאכל. וסאיר אלאגנביין לא יאכלו מנה",
         "and of his food she may eat; and the rest of the outsiders shall not eat of it."),
    ],
    14: [
        ("וְאִישׁ כִּי-יֹאכַל קֹדֶשׁ בִּשְׁגָגָה--וְיָסַף חֲמִשִׁיתוֹ עָלָיו",
         "ואי אנסאן אכל שייא מן אלאקדאס סהוא. פליזיד עליה מת'ל כמסה",
         "And any person who has eaten of the holy things inadvertently shall add to it the like of its fifth,"),
        ("וְנָתַן לַכֹּהֵן אֶת-הַקֹּדֶשׁ",
         "וידפעה אלי' אלאמאם ען אלקדס",
         "and shall pay it to the priest for the holy thing."),
    ],
    15: [
        ("וְלֹא יְחַלְּלוּ אֶת-קָדְשֵׁי בְּנֵי יִשְׂרָאֵל--אֵת אֲשֶׁר-יָרִימוּ לַיהוָה",
         "ולא יבד'לו אקדאס בני אסראיל. ומא ירפעונה ללה",
         "And they shall not treat lightly the holy things of the sons of Israel, and what they present to God."),
    ],
    16: [
        ("וְהִשִּׂיאוּ אוֹתָם עֲו‍ֹן אַשְׁמָה בְּאָכְלָם אֶת-קָדְשֵׁיהֶם",
         "פיחמלו ענהא ד'נובא ואת'אמא. אד'א אכלו כד'אך אקדאסהם",
         "For they would bear sins and guilt thereby, when they ate thus of their holy things —"),
        ("כִּי אֲנִי יְהוָה מְקַדְּשָׁם",
         "לאני אללה מקדסהם",
         "for I am God who sanctifies them."),
    ],
    17: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    18: [
        ("דַּבֵּר אֶל-אַהֲרֹן וְאֶל-בָּנָיו וְאֶל כָּל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר הרון ובניה. וסאיר אל אסראיל. וקל להם",
         "Command Aaron and his sons, and the rest of the house of Israel, and say to them:"),
        ("אִישׁ אִישׁ מִבֵּית יִשְׂרָאֵל וּמִן-הַגֵּר בְּיִשְׂרָאֵל אֲשֶׁר יַקְרִיב קָרְבָּנוֹ לְכָל-נִדְרֵיהֶם וּלְכָל-נִדְבוֹתָם אֲשֶׁר-יַקְרִיבוּ לַיהוָה לְעֹלָה",
         "אי רג'ל מן אל אסראיל או מן אלג'רבא אלדאכ'לין פיהם. שא אן יקרב קרבאנא עלי' צ'רוב מן נדורהם ותברעהם. אלתי יקרבונהא ללה צעידה",
         "any man of the house of Israel, or of the strangers who have entered among them, who wills to bring an offering, according to any manner of their vows and their freewill gifts which they bring to God as a burnt offering —"),
    ],
    19: [
        ("לִרְצֹנְכֶם תָּמִים זָכָר--בַּבָּקָר בַּכְּשָׂבִים וּבָעִזִּים",
         "פלמרתצ'א מנכם. אן יכון ד'כרא צחיחא מן אלבקר ואלצאן ואלמאעז",
         "that which is acceptable from you shall be a sound male, from the cattle, the sheep, or the goats."),
    ],
    20: [
        ("כֹּל אֲשֶׁר-בּוֹ מוּם לֹא תַקְרִיבוּ כִּי-לֹא לְרָצוֹן יִהְיֶה לָכֶם",
         "וכל מא פיה עיב לא תקרבוה. פאנה לא ירתצ'א מנכם",
         "But anything that has a blemish you shall not offer, for it shall not be acceptable from you."),
    ],
    21: [
        ("וְאִישׁ כִּי-יַקְרִיב זֶבַח-שְׁלָמִים לַיהוָה לְפַלֵּא-נֶדֶר אוֹ לִנְדָבָה בַּבָּקָר אוֹ בַצֹּאן",
         "וכד'אלך אי אנסאן שא אן יקרב ד'בח סלאמה ללה. תסויג' נד'רא או תברעא. מן אלבקר או מן אלג'נם",
         "And likewise, any person who wills to bring a peace-offering to God, in fulfillment of a vow or as a freewill gift, from the cattle or from the flock —"),
        ("תָּמִים יִהְיֶה לְרָצוֹן כָּל-מוּם לֹא יִהְיֶה-בּוֹ",
         "פאלצחיח הו אלמרתצ'א מנה. לא יכון פיה שי מן אלעיוב",
         "the sound one is what is acceptable from it; there shall be no blemish of any kind in it."),
    ],
    22: [
        ("עַוֶּרֶת אוֹ שָׁבוּר אוֹ-חָרוּץ אוֹ-יַבֶּלֶת אוֹ גָרָב אוֹ יַלֶּפֶת--לֹא-תַקְרִיבוּ אֵלֶּה לַיהוָה",
         "מן עורא או מכסורה או מבתורה או ד'את ת'אלול. או בה גרב או חזאז. פלא תקרבוהא ללה",
         "Whether blind, or broken, or severed, or having a wart, or with mange or scurf — you shall not offer these to God,"),
        ("וְאִשֶּׁה לֹא-תִתְּנוּ מֵהֶם עַל-הַמִּזְבֵּחַ--לַיהוָה",
         "ולא תגעלו מנהא קרבאנא עלי' מד'בח אללה",
         "and you shall not make from them an offering upon the altar of God."),
    ],
    23: [
        ("וְשׁוֹר וָשֶׂה שָׂרוּעַ וְקָלוּט--נְדָבָה תַּעֲשֶׂה אֹתוֹ",
         "ואי ת'ור או שאה כאנת גאמזה או מדמג'ה. פאצנעה עלי' גהה' אלתברע",
         "And any ox or sheep that is lame or stunted — you may make it for a freewill gift;"),
        ("וּלְנֵדֶר לֹא יֵרָצֶה",
         "ואמא עלי' גהה' אלנד'ר פלא ירתצ'א",
         "but as regards a vow it shall not be acceptable."),
    ],
    24: [
        ("וּמָעוּךְ וְכָתוּת וְנָתוּק וְכָרוּת לֹא תַקְרִיבוּ לַיהוָה",
         "ואלממרוס ואלמדקוק ואלמנצול ואלמקטוע. פלא תקרבוהא ללה",
         "The bruised, or the crushed, or the torn-out, or the severed — you shall not offer these to God;"),
        ("וּבְאַרְצְכֶם לֹא תַעֲשׂוּ",
         "ופי בלדאנכם לא תצנעוהא",
         "and in your lands you shall not do this."),
    ],
    25: [
        ("וּמִיַּד בֶּן-נֵכָר לֹא תַקְרִיבוּ אֶת-לֶחֶם אֱלֹהֵיכֶם--מִכָּל-אֵלֶּה",
         "ומן יד אלאמם . לא תקרבו. קרבאן רבכם אלדאים ופיה שייא מן הד'א אלעיוב",
         "And from the hand of the nations you shall not offer the perpetual offering of your Lord when there is any of these blemishes in it —"),
        ("כִּי מָשְׁחָתָם בָּהֶם מוּם בָּם לֹא יֵרָצוּ לָכֶם",
         "לאן פסאדהא מעהא והו אלעיב אלד'י פיהא. פלא תרתצ'א מנכם",
         "for their corruption is with them, that is the blemish which is in them; they shall not be acceptable from you."),
    ],
    26: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    27: [
        ("שׁוֹר אוֹ-כֶשֶׂב אוֹ-עֵז כִּי יִוָּלֵד וְהָיָה שִׁבְעַת יָמִים תַּחַת אִמּוֹ",
         "ואי עגל או חמל או גדי אד'א יולד. פליקם סבעה' אייאם מע אמה",
         "Any calf, or lamb, or kid — when it is born, let it remain seven days with its mother;"),
        ("וּמִיּוֹם הַשְּׁמִינִי וָהָלְאָה יֵרָצֶה לְקָרְבַּן אִשֶּׁה לַיהוָה",
         "ומן אליום אלת'אמן פצאעדא. ירתצ'א אן יקרב קרבאנא ללה",
         "and from the eighth day onward, it shall be acceptable to be brought as an offering to God."),
    ],
    28: [
        ("וְשׁוֹר אוֹ-שֶׂה--אֹתוֹ וְאֶת-בְּנוֹ לֹא תִשְׁחֲטוּ בְּיוֹם אֶחָד",
         "ואלבקרה ואלנעגה. הי וולדהא. לא תד'בחוהמא פי יום ואחד",
         "And the cow and the ewe — it and its young — you shall not slaughter both of them on one day."),
    ],
    29: [
        ("וְכִי-תִזְבְּחוּ זֶבַח-תּוֹדָה לַיהוָה--לִרְצֹנְכֶם תִּזְבָּחוּ",
         "ואד'א ד'בחתם ד'בח שכר ללה. פעלי' מא ירתצ'א מנכם אד'בחוה",
         "And when you slaughter a thanksgiving sacrifice to God, slaughter it in the manner that is acceptable from you."),
    ],
    30: [
        ("בַּיּוֹם הַהוּא יֵאָכֵל לֹא-תוֹתִירוּ מִמֶּנּוּ עַד-בֹּקֶר",
         "אן יוכל פי ד'אלך אליום פקט לא יבקו מנה אלי' אלג'דאה",
         "It shall be eaten on that day only; you shall leave none of it until the morning."),
        ("אֲנִי יְהוָה",
         "אנא אללה אמרת בד'אלך",
         "I am God, who commanded this."),
    ],
    31: [
        ("וּשְׁמַרְתֶּם מִצְו‍ֹתַי וַעֲשִׂיתֶם אֹתָם",
         "פאחפצו וצאיאי. ואעמלו בהא",
         "Guard My commandments and act according to them."),
        ("אֲנִי יְהוָה",
         "אנא אללה אגאזיכם כ'ירא",
         "I am God, who rewards you with good."),
    ],
    32: [
        ("וְלֹא תְחַלְּלוּ אֶת-שֵׁם קָדְשִׁי",
         "ולא תבד'לו אסם קדסי",
         "And do not treat lightly My holy name;"),
        ("וְנִקְדַּשְׁתִּי בְּתוֹךְ בְּנֵי יִשְׂרָאֵל אֲנִי יְהוָה מְקַדִּשְׁכֶם",
         "בל אתקדס פי מא בין בני אסראיל. אנא אללה מקדסכם",
         "but rather I shall be sanctified among the sons of Israel. I am God who sanctifies you —"),
    ],
    33: [
        ("הַמּוֹצִיא אֶתְכֶם מֵאֶרֶץ מִצְרַיִם לִהְיוֹת לָכֶם לֵאלֹהִים",
         "אלמכ'רגכם מן בלד מצר. לאכון לכם אלאהא",
         "who brought you out from the land of Egypt, to be your God."),
        ("אֲנִי יְהוָה",
         "אנא אללה אלמעאקב",
         "I am God, the Punisher."),
    ],
}
