"""Hand-authored alignment triples for Vayikra chapter 18."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    2: [
        ("דַּבֵּר אֶל-בְּנֵי יִשְׂרָאֵל וְאָמַרְתָּ אֲלֵהֶם",
         "מר בני אסראיל. וקל להם.",
         "Command the sons of Israel and say to them:"),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם",
         "I am God, your Lord."),
    ],
    3: [
        ("כְּמַעֲשֵׂה אֶרֶץ-מִצְרַיִם אֲשֶׁר יְשַׁבְתֶּם-בָּהּ לֹא תַעֲשׂוּ",
         "כצנאיע אהל בלד מצר. אלד'י אקמתם פיה לא תצנעו.",
         "Do not do as the deeds of the people of the land of Egypt, in which you dwelt;"),
        ("וּכְמַעֲשֵׂה אֶרֶץ-כְּנַעַן אֲשֶׁר אֲנִי מֵבִיא אֶתְכֶם שָׁמָּה לֹא תַעֲשׂוּ",
         "וכצנאיע אהל בלד כנעאן. אלד'י אנא מדכ'לכם הנאך לא תצנעו.",
         "and do not do as the deeds of the people of the land of Canaan, to which I am bringing you in there;"),
        ("וּבְחֻקֹּתֵיהֶם לֹא תֵלֵכוּ",
         "וברסומהם לא תסירו",
         "and do not follow their customs."),
    ],
    4: [
        ("אֶת-מִשְׁפָּטַי תַּעֲשׂוּ וְאֶת-חֻקֹּתַי תִּשְׁמְרוּ לָלֶכֶת בָּהֶם",
         "אחכאמי פאצנעו. ורסומי אחפצו וסירו בהא.",
         "My ordinances you shall carry out, and My statutes you shall keep and follow them."),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "אנא אללה רבכם אגאזיכם כ'ירא",
         "I am God, your Lord — I shall recompense you with good."),
    ],
    5: [
        ("וּשְׁמַרְתֶּם אֶת-חֻקֹּתַי וְאֶת-מִשְׁפָּטַי אֲשֶׁר יַעֲשֶׂה אֹתָם הָאָדָם וָחַי בָּהֶם",
         "פאחפצו רסומי ואחכאמי. פאן גזא אי אנסאן עמל בהא. אן יחיא אלחיאה אלדאימה.",
         "Keep My statutes and My ordinances, for the recompense of any person who acts according to them is that he shall live the everlasting life."),
        ("אֲנִי יְהוָה",
         "אנא אללה דאים אלבקא",
         "I am God, enduring in existence."),
    ],
    6: [
        ("אִישׁ אִישׁ אֶל-כָּל-שְׁאֵר בְּשָׂרוֹ לֹא תִקְרְבוּ לְגַלּוֹת עֶרְוָה",
         "כל רגל מנכם אלי' נסיב ד'אתה. לא יתקדם לכשף סותהא.",
         "Every man among you shall not approach a kinswoman of his own to uncover her nakedness."),
        ("אֲנִי יְהוָה",
         "אנא אללה נהיתכם ען ד'אלך",
         "I am God — I have forbidden you this."),
    ],
    7: [
        ("עֶרְוַת אָבִיךָ וְעֶרְוַת אִמְּךָ לֹא תְגַלֵּה",
         "סוות אביך. וסוות אמך לא תכשף.",
         "The nakedness of your father, and the nakedness of your mother, you shall not uncover."),
        ("אִמְּךָ הִוא לֹא תְגַלֶּה עֶרְוָתָהּ",
         "אמא וקלת סוות אמך פהי אמך נפסהא. לא תכשפן סוותהא",
         "Now when I said 'the nakedness of your mother' — she is your mother herself; you shall not uncover her nakedness."),
    ],
    8: [
        ("עֶרְוַת אֵשֶׁת-אָבִיךָ לֹא תְגַלֵּה עֶרְוַת אָבִיךָ הִוא",
         "ואמא סוות אביך פהי זוגה' אביך. לא תכשפן סוותהא",
         "And as for the nakedness of your father — it is the wife of your father; you shall not uncover her nakedness."),
    ],
    9: [
        ("עֶרְוַת אֲחוֹתְךָ בַת-אָבִיךָ אוֹ בַת-אִמֶּךָ מוֹלֶדֶת בַּיִת אוֹ מוֹלֶדֶת חוּץ--לֹא תְגַלֶּה עֶרְוָתָן",
         "וסוות אכ'תך אבנה' אביך או אבנה' אמך. אלמולודה דאכ'לא או כ'ארגא. לא תכשפן סוותהמא",
         "And the nakedness of your sister, the daughter of your father or the daughter of your mother, whether born within or without — you shall not uncover their nakedness."),
    ],
    10: [
        ("עֶרְוַת בַּת-בִּנְךָ אוֹ בַת-בִּתְּךָ לֹא תְגַלֶּה עֶרְוָתָן כִּי עֶרְוָתְךָ הֵנָּה",
         "וסוות אבנה' אבנך או אבנה' אבנתך. לא תכשפהמא. לאנהמא סוואתך",
         "And the nakedness of the daughter of your son or the daughter of your daughter — you shall not uncover either of them, for they are your own nakedness."),
    ],
    11: [
        ("עֶרְוַת בַּת-אֵשֶׁת אָבִיךָ מוֹלֶדֶת אָבִיךָ אֲחוֹתְךָ הִוא--לֹא תְגַלֶּה עֶרְוָתָהּ",
         "וסוות אבנה' זוגה' אביך אלמולודה מן אביך. הי אלתי ביינת אנהא אכ'תך. לא תכשפן סוותהא",
         "And the nakedness of the daughter of the wife of your father, born of your father — she is the one who has been shown to be your sister; you shall not uncover her nakedness."),
    ],
    12: [
        ("עֶרְוַת אֲחוֹת-אָבִיךָ לֹא תְגַלֵּה שְׁאֵר אָבִיךָ הִוא",
         "וסוות אכ'ת אביך פלא תכשף. לאנהא נסיבה' אביך",
         "And the nakedness of your father's sister you shall not uncover, for she is a kinswoman of your father."),
    ],
    13: [
        ("עֶרְוַת אֲחוֹת-אִמְּךָ לֹא תְגַלֵּה כִּי-שְׁאֵר אִמְּךָ הִוא",
         "וסוות אכ'ת אמך פלא תכשף. לאנהא נסיבה' אמך",
         "And the nakedness of your mother's sister you shall not uncover, for she is a kinswoman of your mother."),
    ],
    14: [
        ("עֶרְוַת אֲחִי-אָבִיךָ לֹא תְגַלֵּה אֶל-אִשְׁתּוֹ לֹא תִקְרָב דֹּדָתְךָ הִוא",
         "וסוות עמך לא תכשף. וד'אלך אן לא תתקדם אלי' זוגתה. אד' הי כעמתך",
         "And the nakedness of your uncle you shall not uncover — that is, you shall not approach his wife, for she is as your aunt."),
    ],
    15: [
        ("עֶרְוַת כַּלָּתְךָ לֹא תְגַלֵּה אֵשֶׁת בִּנְךָ הִוא לֹא תְגַלֶּה עֶרְוָתָהּ",
         "וסוות כנתך פלא תכשף. והי זוגה' אבנך. לא תכשף סוותהא",
         "And the nakedness of your daughter-in-law you shall not uncover — she is your son's wife; you shall not uncover her nakedness."),
    ],
    16: [
        ("עֶרְוַת אֵשֶׁת-אָחִיךָ לֹא תְגַלֵּה עֶרְוַת אָחִיךָ הִוא",
         "וסוות זוגה' אכ'יך פלא תכשף. אד' הי כסוות אכ'יך",
         "And the nakedness of your brother's wife you shall not uncover, for she is as the nakedness of your brother."),
    ],
    17: [
        ("עֶרְוַת אִשָּׁה וּבִתָּהּ לֹא תְגַלֵּה",
         "וסוות אמראה ואבנתהא לא תכשף.",
         "And the nakedness of a woman and her daughter you shall not uncover;"),
        ("אֶת-בַּת-בְּנָהּ וְאֶת-בַּת-בִּתָּהּ לֹא תִקַּח לְגַלּוֹת עֶרְוָתָהּ--שַׁאֲרָה הֵנָּה זִמָּה הִוא",
         "וכד'אלך אבנה' אבנהא ואבנה' אבנתהא. לא תתכ'ד' לתכשף סואתהמא. אד' הן נסאיב והי פאחשה",
         "likewise the daughter of her son or the daughter of her daughter — you shall not take her so as to uncover their nakedness, for they are kinswomen of one another, and this is lewdness."),
    ],
    18: [
        ("וְאִשָּׁה אֶל-אֲחֹתָהּ לֹא תִקָּח לִצְרֹר לְגַלּוֹת עֶרְוָתָהּ עָלֶיהָ--בְּחַיֶּיהָ",
         "ואמראה מע אכ'תהא לא תתכ'ד'. לתכון צ'ארתין. לתכשף סוותהא. מעהא פי חיאתהא",
         "And a woman alongside her sister you shall not take, to be a rival to her, to uncover her nakedness along with her in her lifetime."),
    ],
    19: [
        ("וְאֶל-אִשָּׁה בְּנִדַּת טֻמְאָתָהּ--לֹא תִקְרַב לְגַלּוֹת עֶרְוָתָהּ",
         "ואלי' אמראה פי חיצ'ה' נגאסתהא. לא תתקדם. לתכשף סוותהא",
         "And to a woman in the impurity of her menstrual flow, you shall not approach to uncover her nakedness."),
    ],
    20: [
        ("וְאֶל-אֵשֶׁת עֲמִיתְךָ--לֹא-תִתֵּן שְׁכָבְתְּךָ לְזָרַע לְטָמְאָה-בָהּ",
         "ומע זוגה' צאחבך. לא תגעל מצ'אגעתך לאנסאל. ולא לאלתנגס בהא",
         "And with the wife of your fellow, you shall not make your lying for seed, nor to defile yourself with her."),
    ],
    21: [
        ("וּמִזַּרְעֲךָ לֹא-תִתֵּן לְהַעֲבִיר לַמֹּלֶךְ",
         "ולא תעט מן נסלך לאלתקריב לאלצנם.",
         "And do not give of your offspring for offering to idols,"),
        ("וְלֹא תְחַלֵּל אֶת-שֵׁם אֱלֹהֶיךָ אֲנִי יְהוָה",
         "ולא תבד'ל אסם רבך. אנא אללה אלמעאקב",
         "nor profane the name of your Lord. I am God, the Punisher."),
    ],
    22: [
        ("וְאֶת-זָכָר--לֹא תִשְׁכַּב מִשְׁכְּבֵי אִשָּׁה תּוֹעֵבָה הִוא",
         "ואלד'כר פלא תצ'אגעה עלי' צ'רוב מצ'אגעת אלנסא. פאנהא כריהה",
         "And a male — you shall not lie with him after the manner of lying with women, for it is an abomination."),
    ],
    23: [
        ("וּבְכָל-בְּהֵמָה לֹא-תִתֵּן שְׁכָבְתְּךָ לְטָמְאָה-בָהּ",
         "ומע שי מן אלבהאים. לא תגעל מצ'אגעתך לאלתנגס בהא.",
         "And with any of the beasts, you shall not make your lying so as to defile yourself with it;"),
        ("וְאִשָּׁה לֹא-תַעֲמֹד לִפְנֵי בְהֵמָה לְרִבְעָהּ--תֶּבֶל הוּא",
         "וכד'אלך אלאמראה לא תקף. בין ידי בהימה לתנזוהא פאנהא דאהיה",
         "and likewise a woman shall not present herself before a beast for it to mount her, for it is a grave calamity."),
    ],
    24: [
        ("אַל-תִּטַּמְּאוּ בְּכָל-אֵלֶּה",
         "לא תעצוני בשי מן הד'ה.",
         "Do not disobey Me in any of these things,"),
        ("כִּי בְכָל-אֵלֶּה נִטְמְאוּ הַגּוֹיִם אֲשֶׁר-אֲנִי מְשַׁלֵּחַ מִפְּנֵיכֶם",
         "לאן במת'להא עצאני אלאמם. אלד'י אנא טארדהם מן בין ידיכם",
         "for by the like of them the nations disobeyed Me — those whom I am expelling from before you."),
    ],
    25: [
        ("וַתִּטְמָא הָאָרֶץ וָאֶפְקֹד עֲו‍ֹנָהּ עָלֶיהָ",
         "פלמא נגס אהל אלבלד. טאלבתהם בד'נובהם.",
         "And when the people of the land became defiled, I called them to account for their sins,"),
        ("וַתָּקִא הָאָרֶץ אֶת-יֹשְׁבֶיהָ",
         "פשתת אלבלד אהלה",
         "and the land scattered its inhabitants."),
    ],
    26: [
        ("וּשְׁמַרְתֶּם אַתֶּם אֶת-חֻקֹּתַי וְאֶת-מִשְׁפָּטַי",
         "פאחפצו אנתם רסומי ואחכאמי.",
         "So keep, yourselves, My statutes and My ordinances,"),
        ("וְלֹא תַעֲשׂוּ מִכֹּל הַתּוֹעֵבֹת הָאֵלֶּה הָאֶזְרָח וְהַגֵּר הַגָּר בְּתוֹכְכֶם",
         "ולא תצנעו שייא מן הד'ה אלמכארה. אלצריח. ואלג'ריב אלדכ'יל פי מא בינכם",
         "and do nothing of all these abhorrent things — whether the native-born or the stranger who has come to dwell among you."),
    ],
    27: [
        ("כִּי אֶת-כָּל-הַתּוֹעֵבֹת הָאֵל עָשׂוּ אַנְשֵׁי-הָאָרֶץ אֲשֶׁר לִפְנֵיכֶם וַתִּטְמָא הָאָרֶץ",
         "אד' גמיע הד'ה אלמכארה. צנעהא אהל אלבלד אלד'י מן קבלכם. חתא נגס",
         "For all these abhorrent things were done by the people of the land who were before you, until it became defiled."),
    ],
    28: [
        ("וְלֹא-תָקִיא הָאָרֶץ אֶתְכֶם בְּטַמַּאֲכֶם אֹתָהּ כַּאֲשֶׁר קָאָה אֶת-הַגּוֹי אֲשֶׁר לִפְנֵיכֶם",
         "ללא ישתתכם אלבלד אלד'י נגסתמוה. כמא שתת אלאמם אלד'ין מן קבלכם",
         "So that the land to which you have brought defilement shall not scatter you, as it scattered the nations that were before you."),
    ],
    29: [
        ("כִּי כָּל-אֲשֶׁר יַעֲשֶׂה מִכֹּל הַתּוֹעֵבֹת הָאֵלֶּה",
         "ואעלמו אן כל מן יצנע שייא מן גמיע הד'ה אלמכארה.",
         "And know that whoever does anything of all these abhorrent things —"),
        ("וְנִכְרְתוּ הַנְּפָשׁוֹת הָעֹשֹׂת מִקֶּרֶב עַמָּם",
         "תנקטע תלך אלנפוס אלצאנעאת מן בין קומהא",
         "those souls that do them shall be cut off from among their people."),
    ],
    30: [
        ("וּשְׁמַרְתֶּם אֶת-מִשְׁמַרְתִּי לְבִלְתִּי עֲשׂוֹת מֵחֻקּוֹת הַתּוֹעֵבֹת אֲשֶׁר נַעֲשׂוּ לִפְנֵיכֶם",
         "ואחפצו מא אסתחפצתכם. ללא תצנעו. מן רסום אלמכארה אלתי צנעת מן קבלכם.",
         "And keep what I have entrusted to you to keep, so that you do not do any of the customs of the abhorrent things that were done before you,"),
        ("וְלֹא תִטַּמְּאוּ בָּהֶם אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "ולא תעצוני בהא. אנא אללה רבכם אגאזיכם כ'ירא",
         "and do not disobey Me in them. I am God, your Lord — I shall recompense you with good."),
    ],
}
