"""Hand-authored alignment triples for Vayikra chapter 5.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואי", "And any"),
        ("וְנֶפֶשׁ", "אנסאן", "person"),
        ("כִּי-תֶחֱטָא", "אכ'טא.", "who erred"),
        (None, "באן", "in that"),
        ("וְשָׁמְעָה", "סמע", "he heard"),
        ("קוֹל", "צות", "a voice of"),
        ("אָלָה", "חרג.", "distress,"),
        ("וְהוּא", "והו", "and he was"),
        ("עֵד", "שאהד.", "a witness,"),
        ("אוֹ", "או", "or"),
        ("רָאָה", "ראי", "saw"),
        (None, "ד'אלך", "that,"),
        ("אוֹ", "או", "or"),
        ("יָדָע", "עלם", "came to know"),
        (None, "בה.", "of it,"),
        ("אִם-לוֹא יַגִּיד", "ולם יכ'בר", "and did not report it"),
        ("וְנָשָׂא", "פקד חמל", "he has borne"),
        ("עֲו‍ֹנוֹ", "וזרה", "his burden of guilt."),
    ],
    2: [
        (None, "ואי", "And any"),
        ("אוֹ נֶפֶשׁ", "אנסאן.", "person"),
        ("אֲשֶׁר תִּגַּע", "דנא", "who approached"),
        (None, "בשי", "any of"),
        (None, "מן", "the impure matters,"),
        ("בְּכָל-דָּבָר טָמֵא", "אלאמור אלנגסה", "or the carcass of an impure wild creature,"),
        ("אוֹ בְנִבְלַת חַיָּה טְמֵאָה", "או בנבילה' וחש נגס.", "or the carcass of an impure beast,"),
        ("אוֹ בְּנִבְלַת בְּהֵמָה טְמֵאָה", "או בנבילה' בהימה נגסה.", "or the carcass of any impure creeping thing"),
        ("אוֹ בְּנִבְלַת שֶׁרֶץ טָמֵא", "או בנבילה' שי מן אלדביב אלנגס.", "— and that was hidden from him,"),
        ("וְנֶעְלַם מִמֶּנּוּ", "וג'בי ד'אלך ענה.", "and he is impure"),
        ("וְהוּא טָמֵא", "והו נגס", "— then"),
        ("וְאָשֵׁם", "פאת'ם", "he has sinned."),
    ],
    3: [
        ("אוֹ", "או", "Or"),
        ("כִי יִגַּע", "דנא", "he approached"),
        ("בְּטֻמְאַת", "בנגאסה'", "the impurity of"),
        ("אָדָם", "אנסאן.", "a human,"),
        (None, "בשי", "with something"),
        ("לְכֹל טֻמְאָתוֹ", "מן נגאסתה.", "of his impurity,"),
        ("אֲשֶׁר יִטְמָא בָּהּ", "ממא סבילה אן ינגס בהא.", "of that which is capable of making him impure,"),
        ("וְנֶעְלַם", "פגבי", "and it was concealed"),
        (None, "ענה.", "from him"),
        ("וְאָשֵׁם", "פאת'מו", "then he has sinned,"),
        ("וְהוּא יָדַע", "והו עאלם", "though he knew"),
        (None, "במא", "what"),
        (None, "פעל", "he had done."),
    ],
    4: [
        (None, "ואי", "And any"),
        ("אוֹ נֶפֶשׁ", "אנסאן.", "person"),
        ("כִּי תִשָּׁבַע", "חלף", "who swore"),
        ("לְבַטֵּא", "]בלפט'] בלפץ'", "with the utterance of"),
        ("בִשְׂפָתַיִם", "שפתיה.", "his lips —"),
        ("לְהָרַע", "לאסאה", "to do harm"),
        ("אוֹ", "או", "or"),
        ("לְהֵיטִיב", "אחסאן.", "to do good —"),
        ("לְכֹל", "עלי'", "regarding"),
        ("אֲשֶׁר יְבַטֵּא", "גמיע מא ילפץ'", "all that"),
        ("הָאָדָם", "אלאנסאן.", "a person may utter"),
        ("בִּשְׁבֻעָה", "בימין", "in an oath,"),
        ("וְנֶעְלַם", "וג'בי", "and that was hidden"),
        (None, "ד'אלך", "from"),
        (None, "ענה.", "him,"),
        (None, "ת'ם", "then"),
        ("וְהוּא-יָדַע", "עלם", "he came to know"),
        (None, "במא", "what"),
        (None, "פעל.", "he had done —"),
        ("וְאָשֵׁם", "ואת'ם", "and he has sinned"),
        ("לְאַחַת מֵאֵלֶּה", "בואחדה מן הד'ה", "by one of these."),
    ],
    5: [
        ("וְהָיָה כִי-יֶאְשַׁם", "פאד'א את'ם", "And when he has sinned"),
        ("לְאַחַת מֵאֵלֶּה", "בואחדה מן הד'ה.", "by one of these,"),
        (None, "ת'ם", "then"),
        ("וְהִתְוַדָּה", "אקר", "he shall confess"),
        (None, "במא", "what"),
        ("אֲשֶׁר חָטָא", "אכ'טא", "he erred in."),
    ],
    6: [
        ("וְהֵבִיא", "פליאת", "And he shall bring"),
        (None, "בקרבאנה", "his offering"),
        ("לַיהוָה", "ללה.", "to God"),
        ("עַל חַטָּאתוֹ", "עלי' כ'טאה", "for his transgression"),
        ("אֲשֶׁר חָטָא", "אלד'י אכ'טאה.", "which he transgressed —"),
        ("נְקֵבָה", "אנת'י", "a female"),
        ("מִן-הַצֹּאן", "מן אלג'נם", "from the flock,"),
        ("כִּשְׂבָּה", "נעגה.", "a ewe,"),
        ("אוֹ", "או", "or"),
        ("שְׂעִירַת", "שאה", "a she-goat"),
        ("עִזִּים", "מן אלמאעז", "from the goats,"),
        ("לְחַטָּאת", "לאלד'כוה.", "for the sin-offering;"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        (None, "עליה.", "for him"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("מֵחַטָּאתוֹ", "מן כ'טאיה", "for his sins."),
    ],
    7: [
        ("וְאִם-לֹא תַגִּיעַ", "ואן לם תנאל", "And if his means do not reach"),
        ("יָדוֹ", "ידה", "to"),
        ("דֵּי שֶׂה", "מקדאר שאה.", "the price of a sheep,"),
        ("וְהֵבִיא", "פליאת", "he shall bring"),
        (None, "בקרבאנה", "his offering"),
        ("אֲשֶׁר חָטָא", "עלי' מא אכ'טא.", "for what he erred —"),
        ("שְׁתֵּי תֹרִים", "שפנינין", "two turtledoves"),
        ("אוֹ", "או", "or"),
        ("שְׁנֵי בְנֵי-יוֹנָה", "פרכ'י חמאם", "two young pigeons —"),
        ("לַיהוָה", "ללה.", "to God:"),
        ("אֶחָד לְחַטָּאת", "אחדהמא לאלד'כוה", "one of them for the sin-offering"),
        ("וְאֶחָד לְעֹלָה", "ואלאכ'ר לאלצעידה", "and the other for the burnt-offering."),
    ],
    8: [
        ("וְהֵבִיא אֹתָם", "פאד'י אתי' בהמא", "And when he brings them"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם.", "to the imām,"),
        ("וְהִקְרִיב", "פליקרב.", "he shall present"),
        ("אֶת-אֲשֶׁר לַחַטָּאת", "אלד'י לאלד'כוה", "that which is for the sin-offering"),
        ("רִאשׁוֹנָה", "אוולא.", "first,"),
        ("וּמָלַק", "ויפצ'ל", "and shall separate"),
        ("אֶת-רֹאשׁוֹ", "ראסה.", "its head"),
        ("מִמּוּל עָרְפּוֹ", "ממא ילי קפאה", "from the side of its nape,"),
        ("וְלֹא יַבְדִּיל", "ולא יפרזה", "but shall not sever it completely."),
    ],
    9: [
        ("וְהִזָּה", "וינצ'ח", "And he shall sprinkle"),
        ("מִדַּם הַחַטָּאת", "מן דמה", "some of its blood"),
        ("עַל-קִיר", "עלי' חאיט", "upon the wall of"),
        ("הַמִּזְבֵּחַ", "אלמד'בח.", "the altar,"),
        ("וְהַנִּשְׁאָר", "ואלפאצ'ל", "and the remainder"),
        ("בַּדָּם", "מן אלדם.", "of the blood"),
        ("יִמָּצֵה", "ימצ'יה", "he shall drain out"),
        ("אֶל-יְסוֹד", "עלי' אסאסה.", "at its base —"),
        ("חַטָּאת", "כד'אך מא יכון ד'כוה", "such is what constitutes a sin-offering."),
    ],
    10: [
        ("וְאֶת-הַשֵּׁנִי", "ואלתאני.", "And the second"),
        ("יַעֲשֶׂה עֹלָה", "יעמלה צעידה", "he shall perform as a burnt-offering,"),
        ("כַּמִּשְׁפָּט", "כאלסירה.", "according to the established rite;"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        (None, "ענה", "for him"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām"),
        ("מֵחַטָּאתוֹ", "מן כ'טייתה", "for his transgression"),
        ("אֲשֶׁר-חָטָא", "אלד'י אכ'טא", "which he transgressed,"),
        ("וְנִסְלַח לוֹ", "ויג'פר לה", "and he shall be forgiven."),
    ],
    11: [
        ("וְאִם-לֹא תַשִּׂיג", "ואן לם תנאל", "And if his means do not reach"),
        ("יָדוֹ", "ידה", "to"),
        ("לִשְׁתֵּי תֹרִים", "ת'מן שפנינין.", "the price of two turtledoves"),
        ("אוֹ", "או", "or"),
        ("לִשְׁנֵי בְנֵי-יוֹנָה", "פרכ'י חמאם.", "two young pigeons,"),
        ("וְהֵבִיא", "פליאת", "he shall bring"),
        ("אֶת-קָרְבָּנוֹ", "בקרבאנה", "as his offering"),
        ("אֲשֶׁר חָטָא", "עלי' מא אכ'טא.", "for what he erred —"),
        ("עֲשִׂירִת הָאֵפָה", "עשר אלויבה", "a tenth of a wayba"),
        ("סֹלֶת", "סמד", "of fine flour"),
        ("לְחַטָּאת", "לאלד'כוה.", "for the sin-offering;"),
        ("לֹא-יָשִׂים עָלֶיהָ שֶׁמֶן", "לא יצב עליהא דהנא.", "he shall not pour oil upon it,"),
        ("וְלֹא-יִתֵּן עָלֶיהָ לְבֹנָה", "ולא יגעל עליהא לבאנא.", "nor place frankincense upon it,"),
        ("כִּי חַטָּאת הִוא", "לאנהא ד'כוה", "for it is a sin-offering."),
    ],
    12: [
        ("וֶהֱבִיאָהּ", "פיאתי בהא", "He shall bring it"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם.", "to the imām,"),
        ("וְקָמַץ", "פיקבץ'", "shall take"),
        (None, "מנהא", "from it"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām"),
        ("מְלוֹא קֻמְצוֹ", "מל קבצ'תה.", "a full fistful"),
        ("אֶת-אַזְכָּרָתָהּ", "מן פיחהא", "from its fine portion,"),
        ("וְהִקְטִיר", "עלי' אלמד'בח.", "and burn it upon the altar"),
        (None, "מע", "together with"),
        ("אִשֵּׁי יְהוָה", "קראבין אללה.", "the offerings of God —"),
        ("חַטָּאת הִוא", "כד'אך מא תציר ד'כוה", "such is what becomes a sin-offering."),
    ],
    13: [
        ("וְכִפֶּר", "יסתג'פר", "shall seek forgiveness"),
        ("עָלָיו הַכֹּהֵן", "ענה אלאמאם.", "for him"),
        ("עַל-חַטָּאתוֹ", "ען כ'טייתה", "for his transgression"),
        ("אֲשֶׁר-חָטָא", "אלד'י אכ'טא.", "which he transgressed"),
        ("מֵאַחַת מֵאֵלֶּה", "בואחדה מן הד'ה", "by one of these,"),
        ("וְנִסְלַח לוֹ", "פיג'פר לה.", "and he shall be forgiven;"),
        ("וְהָיְתָה לַכֹּהֵן", "ותציר לאלאמאם", "and it shall belong to the imām"),
        ("כַּמִּנְחָה", "כסאיר אלהדאיא", "like the rest of the gift-offerings."),
    ],
    14: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech."),
    ],
    15: [
        (None, "אי", "Any"),
        ("נֶפֶשׁ", "אנסאן", "person"),
        ("כִּי-תִמְעֹל", "נכת'", "who acted in violation"),
        ("מַעַל", "נכת'א.", "— violating"),
        ("וְחָטְאָה", "ואכ'טא", "and erring"),
        ("בִּשְׁגָגָה", "סהוא.", "inadvertently"),
        (None, "בשי", "in something"),
        ("מִקָּדְשֵׁי", "מן אקדאס", "from the sacred things of"),
        ("יְהוָה", "אללה.", "God —"),
        ("וְהֵבִיא", "פליאת", "he shall bring"),
        ("אֶת-אֲשָׁמוֹ", "בקרבאנה", "his offering"),
        ("לַיהוָה", "ללה", "to God:"),
        ("אַיִל תָּמִים", "כבש צחיח", "a sound ram"),
        ("מִן-הַצֹּאן", "מן אלג'נם.", "from the flock,"),
        ("בְּעֶרְכְּךָ", "בקימתה", "at its value"),
        ("כֶּסֶף-שְׁקָלִים", "מת'אקיל פ'צה", "in weights of silver"),
        ("בְּשֶׁקֶל-הַקֹּדֶשׁ", "במת'קאל אלקדס", "by the weight of the sanctuary,"),
        ("לְאָשָׁם", "לאלקרבאן", "as the offering."),
    ],
    16: [
        ("וְאֵת אֲשֶׁר חָטָא", "ואלד'י אכ'טא", "And that which he erred in"),
        ("מִן-הַקֹּדֶשׁ", "פיה מן אלקדס", "from the sacred things"),
        ("יְשַׁלֵּם", "יסלם", "he shall repay"),
        (None, "מת'לה.", "in its equivalent,"),
        ("וְאֶת-חֲמִישִׁתוֹ", "ויזיד עלי'ה כמסה.", "and add a fifth to it,"),
        ("וְנָתַן אֹתוֹ", "ויעטיה", "and give it"),
        ("לַכֹּהֵן", "לאלאמאם.", "to the imām;"),
        ("וְהַכֹּהֵן יְכַפֵּר", "ויסתג'פר", "shall seek forgiveness"),
        (None, "ענה.", "for him"),
        ("בְּאֵיל הָאָשָׁם", "בכבש אלקרבאן", "with the ram of the offering,"),
        ("וְנִסְלַח לוֹ", "ויג'פר לה", "and he shall be forgiven."),
    ],
    17: [
        (None, "ואי", "And any"),
        ("וְאִם-נֶפֶשׁ", "אנסאן", "person"),
        ("כִּי תֶחֱטָא", "אכ'טא.", "who erred"),
        ("וְעָשְׂתָה", "פעמל.", "and did"),
        ("אַחַת", "ואחדה", "one"),
        ("מִכָּל-מִצְו‍ֹת", "מן פראיץ'", "of the commandments of"),
        ("יְהוָה", "אללה.", "God"),
        ("אֲשֶׁר לֹא תֵעָשֶׂינָה", "אלתי לא תעמל.", "which are not to be done,"),
        ("וְלֹא-יָדַע", "ולם יעלם", "and did not know"),
        (None, "באנה", "that"),
        (None, "קד", "he had"),
        ("וְאָשֵׁם", "את'ם", "already sinned —"),
        ("וְנָשָׂא עֲו‍ֹנוֹ", "וחמל וזרה", "he has borne his burden of guilt."),
    ],
    18: [
        ("וְהֵבִיא", "פליאת", "He shall bring"),
        ("אַיִל תָּמִים", "בכבש צחיח", "a sound ram"),
        ("מִן-הַצֹּאן", "מן אלג'נם.", "from the flock,"),
        ("בְּעֶרְכְּךָ", "בקימתה", "at its value"),
        ("לְאָשָׁם", "לאלקרבאן", "as an offering,"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם.", "to the imām;"),
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        (None, "ענה", "for him"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām"),
        ("עַל שִׁגְגָתוֹ", "ען סהותה", "for his inadvertent act"),
        ("אֲשֶׁר-שָׁגָג", "אלד'י סהא.", "in which he erred,"),
        ("וְהוּא לֹא-יָדַע", "והו לם יעלם", "though he did not know —"),
        ("וְנִסְלַח לוֹ", "ויג'פר לה", "and he shall be forgiven."),
    ],
    19: [
        ("אָשָׁם הוּא", "והו קרבאן אלאת'ם.", "And it is a guilt-offering —"),
        ("אָשֹׁם אָשַׁם", "ען את'מה", "for his guilt"),
        ("לַיהוָה", "אלד'י את'ם ללה", "which he incurred before God."),
    ],
    20: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech."),
    ],
    21: [
        (None, "אי", "Any"),
        ("נֶפֶשׁ", "אנסאן", "person"),
        ("כִּי תֶחֱטָא", "אכ'טא.", "who erred"),
        ("וּמָעֲלָה מַעַל", "ונכת' נכת'א", "and acted in violation"),
        ("בַּיהוָה", "באללה", "before God —"),
        ("וְכִחֵשׁ", "פגחד", "in that he denied"),
        ("בַּעֲמִיתוֹ", "צאחבה", "to his fellow"),
        ("בְּפִקָּדוֹן", "ודיעה", "a deposit"),
        ("אוֹ", "או", "or"),
        ("בִתְשׂוּמֶת יָד", "מעאמלה.", "a financial transaction,"),
        ("אוֹ בְגָזֵל", "או ג'צב", "or seized by force,"),
        ("אוֹ עָשַׁק", "או ג'שם", "or defrauded"),
        ("אֶת-עֲמִיתוֹ", "צאחבה", "his fellow —"),
    ],
    22: [
        ("אוֹ-מָצָא", "או וגד", "or found"),
        ("אֲבֵדָה", "צ'אלה.", "a lost thing"),
        ("וְכִחֶשׁ בָּהּ", "פגחדהא", "and denied it,"),
        ("וְנִשְׁבַּע", "וחלף", "and swore"),
        ("עַל-שָׁקֶר", "עלי' באטל.", "falsely —"),
        ("עַל-אַחַת", "עלי' אי", "regarding any such"),
        ("מִכֹּל", "כ'לה.", "failing,"),
        (None, "מן", "from"),
        ("אֲשֶׁר-יַעֲשֶׂה", "גמיע מא יעמל", "all that"),
        ("הָאָדָם", "אלאנסאן", "a person may do"),
        (None, "פיכ'טי בהא", "and thereby err —"),
    ],
    23: [
        ("וְהָיָה כִּי-יֶחֱטָא", "פאד'א הו אכ'טא", "then, when he has erred"),
        ("וְאָשֵׁם", "ואת'ם.", "and sinned,"),
        ("וְהֵשִׁיב", "פלירד", "he shall return"),
        ("אֶת-הַגְּזֵלָה", "אלג'צב", "the thing seized"),
        ("אֲשֶׁר גָּזָל", "אלד'י ג'צבה.", "which he seized,"),
        ("אוֹ", "או", "or"),
        ("אֶת-הָעֹשֶׁק", "אלג'שם", "the fraud"),
        ("אֲשֶׁר עָשָׁק", "אלד'י ג'שמה.", "which he perpetrated,"),
        ("אוֹ", "או", "or"),
        ("אֶת-הָאֲבֵדָה", "אלצ'אלה", "the lost thing"),
        ("אֲשֶׁר מָצָא", "אלתי וגדהא", "which he found,"),
    ],
    24: [
        ("אוֹ מִכֹּל", "או מא סוי'", "or whatever else"),
        (None, "ד'אלך.", "of that"),
        ("אֲשֶׁר-יִשָּׁבַע", "ממא סבילה אן יחלף", "which it is his way to swear"),
        (None, "עליה", "over"),
        ("לַשֶּׁקֶר", "באטלא.", "falsely —"),
        ("וְשִׁלַּם", "פלירדה", "he shall return it"),
        ("אֹתוֹ בְּרֹאשׁוֹ", "בראסה.", "in full,"),
        ("וַחֲמִשִׁתָיו", "ויזיד עליה אכ'מאסה.", "and add its fifth to it,"),
        ("לַאֲשֶׁר הוּא לוֹ", "ויעטי אלד'י הו לה.", "and give it to the one to whom it belongs,"),
        ("בְּיוֹם", "פי יום", "on the day of"),
        ("אַשְׁמָתוֹ", "אעתראפה בד'נבה", "his confession of his guilt."),
    ],
    25: [
        ("וְאֶת-אֲשָׁמוֹ", "פליאת בקרבאנה", "And he shall bring his offering"),
        ("יָבִיא", "ללה.", "to God —"),
        ("אַיִל תָּמִים", "כבש צחיח", "a sound ram"),
        ("מִן-הַצֹּאן", "מן אלג'נם.", "from the flock,"),
        ("בְּעֶרְכְּךָ", "בקימתה", "at its value"),
        ("לְאָשָׁם", "לאלקרבאן", "as an offering,"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the imām."),
    ],
    26: [
        ("וְכִפֶּר", "ויסתג'פר", "shall seek forgiveness"),
        (None, "ענה", "for him"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God,"),
        ("וְנִסְלַח לוֹ", "ויגפר לה.", "and he shall be forgiven —"),
        ("עַל-אַחַת", "עלי' איית", "for whichever"),
        ("מִכֹּל", "כ'לה.", "failing,"),
        (None, "מן", "from"),
        ("אֲשֶׁר-יַעֲשֶׂה", "גמיע מא יעמל", "all that is done"),
        ("לְאַשְׁמָה", "פיאת'ם", "whereby he incurs guilt"),
        (None, "בהא", "in it."),
    ],
}
