"""Hand-authored alignment triples for Vayikra chapter 6.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תטפא" ↔ "it shall not be extinguished"), and Hebrew construct
reorderings. Words Saadia adds with no Hebrew source (glosses, expansions) carry
he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "a speaking."),
    ],
    2: [
        ("צַו", "מר", "Command"),
        ("אֶת-אַהֲרֹן", "הרון", "Aaron"),
        ("וְאֶת-בָּנָיו", "ובניה", "and his sons"),
        ("לֵאמֹר", "קאילא.", "saying:"),
        ("זֹאת", "הד'ה", "This is"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הָעֹלָה", "אלצעידה.", "the burnt-offering —"),
        ("הִוא הָעֹלָה", "תוצ'ע", "it shall be placed"),
        ("עַל מוֹקְדָה", "עלי'", "upon"),
        (None, "וקיד", "a fire"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("כָּל-הַלַּיְלָה", "טול אלליל", "throughout the night"),
        ("עַד-הַבֹּקֶר", "אלי' אלג'דאה.", "until the morning"),
        ("וְאֵשׁ", "ונאר", "and the fire of"),
        ("הַמִּזְבֵּחַ", "אלמד'בח", "the altar"),
        ("תּוּקַד", "תתוקד", "shall burn"),
        ("בּוֹ", "עליה", "upon it."),
    ],
    3: [
        ("וְלָבַשׁ", "וילבס", "shall put on"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("מִדּוֹ בַד", "קמיץ מן עשר.", "a linen shirt"),
        ("וּמִכְנְסֵי-בַד", "וסראויל מן עשר", "and linen trousers"),
        ("יִלְבַּשׁ", "ילבס", "he shall wear"),
        ("עַל-בְּשָׂרוֹ", "עלי'בדנה.", "upon his body;"),
        ("וְהֵרִים", "וירפע", "and he shall remove"),
        ("אֶת-הַדֶּשֶׁן", "אלרמאד", "the ash"),
        ("הָאֵשׁ", "נאר", "the fire of"),
        ("אֲשֶׁר תֹּאכַל", "אלתי תאכל", "has consumed"),
        ("אֶת-הָעֹלָה", "אלצעידה", "the burnt-offering"),
        ("עַל-הַמִּזְבֵּחַ", "עלי'אלמד'בח.", "upon the altar"),
        ("וְשָׂמוֹ", "ויגעלה", "and set it"),
        ("אֵצֶל הַמִּזְבֵּחַ", "לזק אלמד'בח", "beside the altar."),
    ],
    4: [
        (None, "ת'ם", "Then"),
        ("וּפָשַׁט", "יסלך'", "he shall take off"),
        ("אֶת-בְּגָדָיו", "ת'יאבה.", "his garments"),
        ("וְלָבַשׁ", "וילבס", "and put on"),
        ("בְּגָדִים", "ת'יאב", "garments"),
        ("אֲחֵרִים", "אכ'ר.", "other"),
        ("וְהוֹצִיא", "ויכ'רג", "and carry"),
        ("אֶת-הַדֶּשֶׁן", "אלרמאד", "the ash"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר.", "out to the outside of the camp"),
        ("אֶל-מָקוֹם", "אלי' מוצ'ע", "to a"),
        ("טָהוֹר", "טאהר", "clean place."),
    ],
    5: [
        ("וְהָאֵשׁ", "ואלנאר", "And the fire"),
        (None, "אלד'י", "which is"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("תּוּקַד-בּוֹ", "תקד פיה", "shall burn therein —"),
        ("לֹא", "לא", "it shall not"),
        ("תִכְבֶּה", "תטפא.", "be extinguished;"),
        ("וּבִעֵר", "וישעל", "shall kindle"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("הַכֹּהֵן", "אלאמאם.", "the imām"),
        ("עֵצִים", "חטבא", "wood"),
        ("בַּבֹּקֶר בַּבֹּקֶר", "פי כל ג'דאה.", "every morning"),
        ("וְעָרַךְ", "וינצ'ד", "and arrange"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("הָעֹלָה", "אלצעידה.", "the burnt-offering"),
        ("וְהִקְטִיר", "ויקתר", "and burn"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("חֶלְבֵי", "שחום", "the fat of"),
        ("הַשְּׁלָמִים", "ד'בח אלסלאמה", "the peace-offering."),
    ],
    6: [
        (None, "וכדאך", "And so"),
        ("אֵשׁ", "אלנאר", "the fire"),
        ("תָּמִיד", "דאימא.", "continually —"),
        ("תּוּקַד", "תקד", "shall burn"),
        ("עַל-הַמִּזְבֵּחַ", "עלי' אלמד'בח", "upon the altar"),
        ("לֹא", "לא", "it shall not"),
        ("תִכְבֶּה", "תטפא", "be extinguished."),
    ],
    7: [
        (None, "והד'ה", "And this is"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הַמִּנְחָה", "אלהדייה.", "the gift-offering:"),
        (None, "אן", "shall"),
        ("הַקְרֵב אֹתָהּ", "יקדמהא", "present it"),
        ("בְּנֵי-אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה.", "before God"),
        ("אֶל-פְּנֵי הַמִּזְבֵּחַ", "בין ידי אלמד'בח", "before the altar."),
    ],
    8: [
        ("וְהֵרִים", "וירפע", "And he shall lift"),
        ("מִמֶּנּוּ", "מנהא", "from it"),
        ("בְּקֻמְצוֹ", "בקבצ'תה.", "with his handful"),
        ("מִסֹּלֶת הַמִּנְחָה", "מן סמדהא", "from its fine flour"),
        ("וּמִשַּׁמְנָהּ", "ודהנהא.", "and its oil"),
        ("וְהִקְטִיר", "ויקתר", "and burn"),
        ("רֵיחַ נִיחֹחַ", "פיחהא", "its fragrance"),
        ("הַמִּזְבֵּחַ", "עלי' אלמד'בח.", "upon the altar —"),
        (None, "קבול", "accepted"),
        (None, "מרצ'י", "and pleasing"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    9: [
        ("וְהַנּוֹתֶרֶת", "ואלפאצ'ל", "And the remainder of"),
        ("מִמֶּנָּה", "מנהא.", "it"),
        ("יֹאכְלוּ", "יאכלה", "shall eat;"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה.", "and his sons"),
        ("מַצּוֹת", "פטירא", "unleavened"),
        ("תֵּאָכֵל", "תוכל", "it shall be eaten"),
        ("בְּמָקוֹם קָדֹשׁ", "פי מוצ'ע מקדס.", "in a consecrated place —"),
        ("בַּחֲצַר", "פי צחן", "in the court of"),
        ("אֹהֶל-מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the presence"),
        ("יֹאכְלוּהָ", "יאכלוהא", "they shall eat it."),
    ],
    10: [
        ("לֹא", "לא", "It shall not"),
        ("תֵאָפֶה", "תכ'בז", "be baked"),
        ("חָמֵץ", "כ'מירא.", "leavened;"),
        ("נָתַתִּי", "געלתהא", "I have appointed it"),
        ("חֶלְקָם", "קסמהם", "as their portion"),
        ("מֵאִשָּׁי", "מן קראביני.", "from my offerings —"),
        ("קֹדֶשׁ קָדָשִׁים", "מן כ'ואץ אלאקדאס", "it is among the choicest of the sacred things"),
        ("הִוא", "הי.", "like"),
        ("כַּחַטָּאת", "כאלדכוה", "the purification-offering"),
        ("וְכָאָשָׁם", "וקרבאן אלאתם", "and the guilt-offering."),
    ],
    11: [
        ("כָּל-זָכָר", "כל ד'כר", "Every male"),
        ("בִּבְנֵי אַהֲרֹן", "מן בני הרון", "among the sons of Aaron"),
        ("יֹאכְלֶנָּה", "יאכלהא.", "shall eat it —"),
        ("חָק-עוֹלָם", "רסם אלדהר", "a statute forever"),
        ("לְדֹרֹתֵיכֶם", "לאגיאלכם.", "for your generations"),
        ("מֵאִשֵּׁי יְהוָה", "מן קראבין אללה.", "from the offerings of God;"),
        ("כֹּל אֲשֶׁר-יִגַּע", "כל מן לאמסהא", "everyone who touches it"),
        ("יִקְדָּשׁ", "תקדס", "shall become consecrated."),
    ],
    12: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "a speaking."),
    ],
    13: [
        ("זֶה", "הד'א", "This is"),
        ("קָרְבַּן", "קרבאן", "the offering of"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("אֲשֶׁר-יַקְרִיבוּ", "אלד'י יקרבה", "which he shall bring"),
        ("לַיהוָה", "ללה.", "to God"),
        ("בְּיוֹם", "מן יום", "on the day of"),
        ("הִמָּשַׁח אֹתוֹ", "מסח.", "his anointing:"),
        ("עֲשִׂירִת הָאֵפָה", "עשר אלויבה", "a tenth of a waybah"),
        ("סֹלֶת", "סמד.", "of fine flour —"),
        ("מִנְחָה", "הדייה", "a gift"),
        ("תָּמִיד", "דאימא.", "continually"),
        ("מַחֲצִיתָהּ", "נצפהא", "half of it"),
        ("בַּבֹּקֶר", "באלג'דאה.", "in the morning"),
        (None, "ונצפהא", "and half of it"),
        ("בָּעָרֶב", "באלעשא", "in the evening."),
    ],
    14: [
        ("עַל-מַחֲבַת", "עלי' טאבק", "On a pan"),
        ("בַּשֶּׁמֶן", "בדהן", "with oil"),
        ("תֵּעָשֶׂה", "תעמל.", "it shall be made;"),
        ("מֻרְבֶּכֶת", "סתותייה", "in layers"),
        ("תְּבִיאֶנָּה", "תאתי בהא", "you shall bring it —"),
        ("תֻּפִינֵי", "רפכ'ה תכון.", "crumbled, it shall be"),
        ("מִנְחַת פִּתִּים", "תקרבהא", "you shall present it"),
        ("רֵיחַ-נִיחֹחַ", "מקבולא", "as accepted"),
        (None, "מרצ'ייא", "and pleasing"),
        ("לַיהוָה", "ללה", "to God."),
    ],
    15: [
        (None, "וכד'אך", "And likewise"),
        ("וְהַכֹּהֵן", "אלאמאם", "the imām"),
        ("הַמָּשִׁיחַ תַּחְתָּיו", "אלמסתכ'לף בעדה.", "who is appointed as his successor"),
        ("מִבָּנָיו", "מן בניה", "from his sons"),
        ("יַעֲשֶׂה אֹתָהּ", "יצנעהא.", "shall make it —"),
        ("חָק-עוֹלָם", "רסם אלדהר.", "a statute forever;"),
        ("כָּלִיל תָּקְטָר", "ללה גמלה תקתר", "it shall be burned entirely to God."),
    ],
    16: [
        ("וְכָל-מִנְחַת כֹּהֵן", "וסאיר הדאיא אלאמאם.", "And the rest of the imām's gift-offerings"),
        ("כָּלִיל", "גמלה", "entirely"),
        ("תִּהְיֶה", "תקתר", "shall be burned"),
        ("לֹא", "ולא", "and shall not"),
        ("תֵאָכֵל", "תוכל", "be eaten."),
    ],
    17: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "a speaking."),
    ],
    18: [
        ("דַּבֵּר", "קל", "Say"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("וְאֶל-בָּנָיו", "ובניה", "and his sons"),
        ("לֵאמֹר", "קאילא.", "saying:"),
        ("זֹאת", "הד'ה", "This is"),
        ("תּוֹרַת", "שריעה'", "the law of"),
        ("הַחַטָּאת", "אלדכוה.", "the purification-offering —"),
        ("בִּמְקוֹם", "פי מוצ'ע", "in the place"),
        ("הָעֹלָה", "אלצעידה.", "the burnt-offering"),
        ("אֲשֶׁר תִּשָּׁחֵט", "תד'בח", "is slaughtered"),
        ("תִּשָּׁחֵט", "תד'בח", "shall be slaughtered"),
        ("הַחַטָּאת", "אלדכוה", "the purification-offering"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה.", "before God;"),
        ("קֹדֶשׁ קָדָשִׁים", "מן כ'ואץ אלאקדאס", "it is among the choicest of the sacred things."),
    ],
    19: [
        ("הַכֹּהֵן", "אלאמאם", "The imām"),
        ("הַמְחַטֵּא אֹתָהּ", "אלמד'כי בהא", "who offers it as a purification-offering"),
        ("יֹאכְלֶנָּה", "יאכלהא.", "shall eat it;"),
        ("תֵּאָכֵל", "תוכל.", "it shall be eaten"),
        ("בְּמָקוֹם קָדֹשׁ", "ופי מוצ'ע מקדס", "in a consecrated place —"),
        ("בַּחֲצַר", "פי צחן", "in the court of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the presence."),
    ],
    20: [
        ("כֹּל אֲשֶׁר-יִגַּע", "כל מן דנא", "Everyone who approaches"),
        ("בִּבְשָׂרָהּ", "בלחמהא", "its flesh"),
        ("יִקְדָּשׁ", "תקדס.", "shall become consecrated;"),
        ("וַאֲשֶׁר", "ואן", "and if any"),
        ("מִדָּמָהּ", "מן דמהא.", "of its blood"),
        ("יִזֶּה", "אנתצ'ח", "that is sprinkled"),
        (None, "אלד'י ינצ'ח מנה", "from it should spatter"),
        ("עַל-הַבֶּגֶד", "עלי'ת'וב.", "upon a garment"),
        ("תְּכַבֵּס", "פליג'סל", "then it shall be washed"),
        ("בְּמָקוֹם קָדֹשׁ", "פי מוצ'ע מקדס", "in a consecrated place."),
    ],
    21: [
        ("וּכְלִי-חֶרֶשׂ", "ואנא אלכ'זף.", "And earthenware vessels"),
        ("אֲשֶׁר תְּבֻשַּׁל-בּוֹ", "אלד'י תטבך' פיה", "in which it is cooked"),
        ("יִשָּׁבֵר", "יכסר.", "shall be broken;"),
        ("וְאִם", "ואן", "and if"),
        ("בִּכְלִי נְחֹשֶׁת", "פי אנא נחאס.", "in a copper vessel"),
        ("בֻּשָּׁלָה", "טבכ'ת", "it was cooked"),
        ("וּמֹרַק", "פלידלך", "then it shall be scoured"),
        ("וְשֻׁטַּף", "ויגסל", "and rinsed"),
        ("בַּמָּיִם", "באלמא", "with water."),
    ],
    22: [
        ("כָּל-זָכָר", "כל ד'כר", "Every male"),
        ("בַּכֹּהֲנִים", "מן אלאיימה", "among the imāms"),
        ("יֹאכַל אֹתָהּ", "יאכלה.", "shall eat it"),
        (None, "אד'", "since"),
        ("קֹדֶשׁ קָדָשִׁים", "הי מן כ'ואץ אלאקדאס", "it is among the choicest of the sacred things."),
    ],
    23: [
        ("וְכָל-חַטָּאת", "וכל דכוה.", "But every purification-offering"),
        ("מִדָּמָהּ", "מן דמהא.", "any blood"),
        ("אֲשֶׁר יוּבָא", "ידכ'ל", "is brought"),
        ("אֶל-אֹהֶל מוֹעֵד", "אלי' כ'בא אלמחצ'ר.", "into the tent of the presence"),
        ("לְכַפֵּר", "ליסתג'פר", "to seek atonement"),
        ("בַּקֹּדֶשׁ", "פי אלקדס", "in the sanctuary —"),
        ("לֹא תֵאָכֵל", "פלא תוכל.", "it shall not be eaten;"),
        (None, "בל", "rather"),
        ("תִּשָּׂרֵף", "תחרק", "it shall be burned"),
        ("בָּאֵשׁ", "באלנאר", "with fire."),
    ],
}
