"""Hand-authored alignment triples for Vayikra chapter 2.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations ("לא תצנעו" ↔ "Do not do"), and Hebrew construct reorderings. Words
Saadia adds with no Hebrew source (glosses, expansions) carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ואי", "And whatever"),
        ("וְנֶפֶשׁ", "אנסאן", "person"),
        ("כִּי-תַקְרִיב", "קרב", "brings"),
        ("קָרְבַּן", "קרבאן", "an offering"),
        ("מִנְחָה", "הדייה", "of gift"),
        ("לַיהוָה", "ללה", "to God"),
        (None, "וכאן", "and"),
        ("קָרְבָּנוֹ", "קרבאנה", "his offering is"),
        ("סֹלֶת", "סמדא", "fine flour"),
        ("וְיָצַק", "פליצב", "let him pour"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("שֶׁמֶן", "דהנא", "oil"),
        ("וְנָתַן", "ויגעל", "and place"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("לְבֹנָה", "לבאנא", "frankincense"),
    ],
    2: [
        ("וֶהֱבִיאָהּ", "ויאתי", "And he shall bring"),
        (None, "בהא", "it"),
        ("אֶל-בְּנֵי", "אלי'", "to"),
        (None, "בעץ'", "one of"),
        (None, "בני", "the sons of"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("הַכֹּהֲנִים", "אלאיימה", "the priests"),
        ("וְקָמַץ", "ויקבץ'", "and he shall take"),
        ("מְלֹא קֻמְצוֹ", "מל קבצ'תה", "a handful"),
        ("מִסָּלְתָּהּ", "מן סמדהא", "from its fine flour"),
        ("וּמִשַּׁמְנָהּ", "ודהנהא", "and its oil"),
        (None, "מע", "together with"),
        (None, "גמיע", "all"),
        ("עַל כָּל-לְבֹנָתָהּ", "לבאנהא", "its frankincense"),
        ("וְהִקְטִיר", "ויקתר", "and burn"),
        ("אֶת-אַזְכָּרָתָהּ", "פיחהא", "its fragrance"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        (None, "קרבאן", "an offering"),
        (None, "מקבול", "accepted"),
        (None, "מרצ'י", "and pleasing"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    3: [
        ("וְהַנּוֹתֶרֶת", "ואלפאצ'ל", "And the remainder of"),
        ("מִן-הַמִּנְחָה", "מנהא", "it"),
        ("לְאַהֲרֹן", "להרון", "shall belong to Aaron"),
        ("וּלְבָנָיו", "ובניה", "and his sons"),
        (None, "מן כ'ואץ", "from the choicest of"),
        ("קֹדֶשׁ קָדָשִׁים", "אלאקדאס", "the holy things"),
        ("מֵאִשֵּׁי", "מן קראבין", "from the offerings of"),
        ("יְהוָה", "אללה", "God"),
    ],
    4: [
        (None, "ואן", "And if"),
        ("תַקְרִב", "קרבת", "you bring"),
        ("קָרְבַּן מִנְחָה", "הדייה", "a gift offering"),
        (None, "מן", "from"),
        ("מַאֲפֵה", "כ'בז", "the bread of"),
        ("תַנּוּר", "אלתנור", "the oven"),
        (None, "פלתכון", "let it be"),
        ("חַלּוֹת", "גראדק", "loaves"),
        ("סֹלֶת", "סמד", "of fine flour"),
        ("מַצֹּת", "פטיר", "unleavened"),
        ("בְּלוּלֹת", "מלתותה", "kneaded"),
        ("בַּשֶּׁמֶן", "בדהן", "with oil"),
        ("וּרְקִיקֵי", "ורקאק", "and wafers"),
        ("מַצּוֹת", "פטיר", "unleavened"),
        (None, "מלתותה", "kneaded with oil"),
        ("מְשֻׁחִים", "ממסוחה", "smeared"),
        ("בַּשָּׁמֶן", "בדהן", "with oil"),
    ],
    5: [
        (None, "ואן", "And if"),
        (None, "כאן", "is"),
        ("קָרְבָּנֶךָ", "קרבאנך", "your offering"),
        ("מִנְחָה", "הדייה", "a gift offering"),
        ("עַל-הַמַּחֲבַת", "עלי' אלטאבק", "upon the griddle"),
        (None, "פלתכון", "let it be"),
        ("מַצָּה", "פטירא", "unleavened"),
        (None, "מן", "from"),
        ("סֹלֶת", "סמד", "fine flour"),
        ("בְּלוּלָה", "מלתותה", "kneaded"),
        ("בַשֶּׁמֶן", "בדהן", "with oil"),
    ],
    6: [
        ("פָּתוֹת", "ואת'רדהא", "And crumble it"),
        (None, "ת'רדא", "into crumbs"),
        ("וְיָצַקְתָּ", "וצב", "and pour"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("שָׁמֶן", "דהנא", "oil"),
        (None, "כד'אך", "thus"),
        (None, "מא", "shall"),
        (None, "יכון", "it be"),
        ("מִנְחָה", "הדייה", "as a gift offering"),
    ],
    7: [
        (None, "ואן", "And if"),
        (None, "כאן", "is"),
        ("קָרְבָּנֶךָ", "קרבאנך", "your offering"),
        ("מִנְחַת", "הדייה", "a gift offering"),
        (None, "מן", "from"),
        ("מַרְחֶשֶׁת", "צנעה' אלטנגיר", "the making of the pot"),
        (None, "פלתעמל", "let it be made of"),
        ("סֹלֶת", "סמד", "fine flour"),
        ("בַּשֶּׁמֶן", "בדהן", "with oil"),
    ],
    8: [
        (None, "פאית", "And bring"),
        ("אֶת-הַמִּנְחָה", "באלהדייה", "the gift offering"),
        ("אֲשֶׁר יֵעָשֶׂה", "אלתי", "that"),
        (None, "קד", "has"),
        (None, "עמלת", "been prepared"),
        (None, "מן", "from"),
        ("מֵאֵלֶּה", "אחדי'", "one of"),
        (None, "הד'ה", "these"),
        ("לַיהוָה", "ללה", "to God"),
        ("וְהִקְרִיבָהּ", "ויקדמהא", "and he shall present it"),
        ("אֶל-הַכֹּהֵן", "אלי' אלאמאם", "to the priest"),
        ("וְהִגִּישָׁהּ", "יקדמהא", "who shall present it"),
        ("אֶל-הַמִּזְבֵּחַ", "אלי' אלמד'בח", "to the altar"),
    ],
    9: [
        ("וְהֵרִים", "וירפע", "And he shall lift"),
        ("מִן-הַמִּנְחָה", "מנהא", "from it"),
        ("אֶת-אַזְכָּרָתָהּ", "פיחהא", "its fragrance"),
        ("וְהִקְטִיר", "ויקתרה", "and burn it"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
        (None, "קרבאנא", "an offering"),
        (None, "מקבולא", "accepted"),
        (None, "מרצ'יא", "and pleasing"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    11: [
        ("כָּל-הַמִּנְחָה", "גמיע", "All"),
        (None, "אלהדאיא", "the gift offerings"),
        (None, "אלתי", "which"),
        ("אֲשֶׁר תַּקְרִיבוּ", "תקרבוהא", "you bring"),
        ("לַיהוָה", "ללה", "to God"),
        ("לֹא תֵעָשֶׂה", "לא תעמל", "shall not be made"),
        ("חָמֵץ", "כ'מירא", "leavened"),
        ("כִּי", "לאן", "for"),
        ("כָל-שְׂאֹר", "כל כ'מיר", "all leaven"),
        ("וְכָל-דְּבַשׁ", "וכל עסל", "and all honey"),
        ("לֹא-תַקְטִירוּ", "לא תקרבו", "you shall not bring"),
        ("מִמֶּנּוּ", "מנה", "thereof"),
        (None, "קרבאנא", "as an offering"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    12: [
        (None, "לכן", "But as"),
        ("קָרְבַּן", "קרבאן", "a"),
        ("רֵאשִׁית", "אוול", "firstfruit offering"),
        ("תַּקְרִיבוּ אֹתָם", "תקרבוהא", "you may bring them"),
        ("לַיהוָה", "ללה", "to God"),
        ("וְאֶל-הַמִּזְבֵּחַ", "ואלי' אלמד'בח", "yet to the altar"),
        ("לֹא-יַעֲלוּ", "לא תצעד", "they shall not be brought up"),
        ("לְרֵיחַ נִיחֹחַ", "לקבול מרצ'י", "for an accepted and pleasing reception"),
    ],
    13: [
        (None, "וגמיע", "And every"),
        ("קָרְבַּן", "קרבאן", "offering"),
        ("מִנְחָתְךָ", "הדאיאך", "of your gift offerings"),
        ("בַּמֶּלַח", "במלח", "with salt"),
        ("תִּמְלָח", "אמלחה", "salt it"),
        ("וְלֹא תַשְׁבִּית", "ולא תעטל", "and do not cease from"),
        ("מֶלַח", "אלמלח", "salt"),
        (None, "לאנה", "for it is"),
        ("בְּרִית", "עהד", "the covenant of"),
        ("אֱלֹהֶיךָ", "רבך", "your Lord"),
        ("מֵעַל מִנְחָתֶךָ", "מן הדייתך", "from your gift offering"),
        (None, "ומע", "and with"),
        (None, "סאיר", "the rest of"),
        ("עַל כָּל-קָרְבָּנְךָ", "קראבינך", "your offerings"),
        ("תַּקְרִיב", "תקרב", "you shall bring"),
        ("מֶלַח", "מלחא", "salt"),
    ],
    14: [
        (None, "ואן", "And if"),
        ("תַּקְרִיב", "קרבת", "you bring"),
        ("מִנְחַת בִּכּוּרִים", "הדייה' בכור", "a firstfruit gift offering"),
        ("לַיהוָה", "ללה", "to God"),
        ("אָבִיב", "פפריך", "bring it as"),
        ("קָלוּי", "מקלי", "roasted grain parched"),
        ("בָּאֵשׁ", "באלנאר", "by fire"),
        ("גֶּרֶשׂ", "גריש", "coarsely ground"),
        (None, "מן", "from"),
        ("כַּרְמֶל", "אלהרף", "the finest"),
        ("תַּקְרִיב אֵת מִנְחַת בִּכּוּרֶיךָ", "קרבהא", "crop"),
    ],
    15: [
        ("וְנָתַתָּ", "ואגעל", "And place"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("שֶׁמֶן", "דהנא", "oil"),
        ("וְשַׂמְתָּ", "וצייר", "and set"),
        ("עָלֶיהָ", "עליהא", "upon it"),
        ("לְבֹנָה", "לבאנא", "frankincense"),
        (None, "כ'דאך", "thus"),
        (None, "מא", "shall"),
        (None, "תכון", "it be"),
        ("מִנְחָה", "הדייה", "as a gift offering"),
    ],
    16: [
        ("הַכֹּהֵן", "אלאמאם", "And the priest"),
        ("וְהִקְטִיר", "ויקתר", "shall burn"),
        ("אֶת-אַזְכָּרָתָהּ", "פיחהא", "its fragrance"),
        ("מִגִּרְשָׂהּ", "מן גרישהא", "from its coarse grains"),
        ("וּמִשַּׁמְנָהּ", "ודהנהא", "and its oil"),
        (None, "מע", "together with"),
        (None, "גמיע", "all"),
        ("עַל כָּל-לְבֹנָתָהּ", "לבאנהא", "its frankincense"),
        (None, "קרבאנא", "as an offering"),
        ("לַיהוָה", "ללה", "to God"),
    ],
}
