"""Hand-authored alignment triples for Vayikra chapter 24.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    2: [
        ("צַו", "אוץ", "Command"),
        ("אֶת-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        (None, "אן", "that"),
        ("וְיִקְחוּ", "יאתוך", "they bring you"),
        ("שֶׁמֶן", "בדהן", "oil"),
        ("זַיִת", "זית", "olive"),
        ("זָךְ", "צאף", "pure"),
        ("כָּתִית", "מדקוק", "pressed"),
        ("לַמָּאוֹר", "לאלאצ'אה", "for giving light"),
        ("לְהַעֲלֹת", "לתסר'ג", "to kindle"),
        (None, "בה", "with it"),
        ("נֵר", "אלסרג", "the lamp"),
        ("תָּמִיד", "דאימא", "continually"),
    ],
    3: [
        ("מִחוּץ", "כ'ארג", "Outside"),
        ("לְפָרֹכֶת", "סגף", "the veil of"),
        ("הָעֵדֻת", "אלשהאדה", "the testimony"),
        ("בְּאֹהֶל", "פי כ'בא", "in the tent of"),
        ("מוֹעֵד", "אלמחצ'ר", "the presence"),
        ("יַעֲרֹךְ", "ינצ'דה", "shall arrange it"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("מֵעֶרֶב", "מן אלעשי", "from evening"),
        ("עַד-בֹּקֶר", "אלי' אלצבאח", "until morning"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
        ("תָּמִיד", "דאימא", "continually"),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם", "רסם אלדהר", "an ordinance forever"),
    ],
    4: [
        ("עַל", "עלי'", "Upon"),
        ("הַמְּנֹרָה", "אלמנארה", "lampstand"),
        ("הַטְּהֹרָה", "אלטאהרה", "pure"),
        ("יַעֲרֹךְ אֶת-הַנֵּרוֹת", "יצפהא", "shall he set them in order"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
        ("תָּמִיד", "דאימא", "continually"),
    ],
    5: [
        ("וְלָקַחְתָּ", "וכד'", "And take"),
        ("סֹלֶת", "סמדא", "fine flour"),
        ("וְאָפִיתָ", "ואכ'בזה", "and bake it into"),
        ("שְׁתֵּים עֶשְׂרֵה", "את'נא עשר", "twelve"),
        ("חַלּוֹת", "גרדקה", "loaves"),
        (None, "ולתכון", "and let"),
        (None, "כל", "each"),
        ("הַחַלָּה הָאֶחָת", "גרדקה", "loaf"),
        ("שְׁנֵי עֶשְׂרֹנִים יִהְיֶה", "מן עשרין", "be of twenty [parts]"),
    ],
    6: [
        ("וְשַׂמְתָּ", "וציירהמא", "And set them"),
        ("שְׁתַּיִם מַעֲרָכוֹת", "צפין", "in two rows"),
        ("שֵׁשׁ", "סתה", "six"),
        ("הַמַּעֲרָכֶת", "פי כל צף", "in each row"),
        ("עַל", "עלי'", "upon"),
        ("הַשֻּׁלְחָן", "אלמאידה", "table"),
        ("הַטָּהֹר", "אלטאהרה", "pure"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
    ],
    7: [
        ("וְנָתַתָּ", "ואגעל", "And place"),
        ("עַל-הַמַּעֲרֶכֶת", "עלי' כל צף", "upon each row"),
        ("לְבֹנָה", "לבאנא", "frankincense"),
        ("זַכָּה", "ד'כייא", "pure"),
        (None, "וליכון", "and let it serve"),
        ("לַלֶּחֶם", "ען אלכ'בז", "from the bread"),
        ("לְאַזְכָּרָה", "פיחא", "as the fragrant portion"),
        ("אִשֶּׁה", "מקרבא", "an offering"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    8: [
        ("בְּיוֹם הַשַּׁבָּת", "ופי כל יום סבת", "And on every Sabbath day"),
        ("יַעַרְכֶנּוּ", "יצפהא", "he shall arrange them"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
        ("תָּמִיד", "דאימא", "continually"),
        ("מֵאֵת", "מן ענד", "from"),
        ("בְּנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("בְּרִית עוֹלָם", "עהד אלדהר", "a covenant forever"),
    ],
    9: [
        (None, "ת'ם", "Then"),
        ("וְהָיְתָה", "ידפע", "it shall be given over"),
        ("לְאַהֲרֹן", "אלי' הרון", "to Aaron"),
        ("וּלְבָנָיו", "ובניה", "and his sons"),
        ("וַאֲכָלֻהוּ", "יאכלונה", "they shall eat it"),
        ("בְּמָקוֹם קָדֹשׁ", "פי מוצ'ע מקדס", "in a consecrated place"),
        ("כִּי", "לאנה", "for"),
        (None, "להם", "it belongs to them"),
        ("קֹדֶשׁ קָדָשִׁים", "מן כ'ואץ אלאקדאס", "from the choicest of the sacred things"),
        ("מֵאִשֵּׁי", "מן קראבין", "from the offerings"),
        ("יְהוָה", "אללה", "to God"),
        ("חָק-עוֹלָם", "רסם אלדהר", "an ordinance forever"),
    ],
    10: [
        ("וַיֵּצֵא", "פכ'רג", "And there went out"),
        ("בֶּן-אִשָּׁה יִשְׂרְאֵלִית", "אבן אמראה אסראילייה", "the son of an Israelite woman"),
        ("וְהוּא", "והו", "he being"),
        ("בֶּן-אִישׁ מִצְרִי", "אבן רגל מצרי", "the son of an Egyptian man"),
        ("בְּתוֹךְ", "פי מא בין", "among"),
        ("בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וַיִּנָּצוּ", "פתנאצו", "and they quarreled"),
        ("בַּמַּחֲנֶה", "פי אלעסכר", "in the camp"),
        ("בֶּן הַיִּשְׂרְאֵלִית", "הד'א אבן אלאסראילייה", "this son of the Israelite woman"),
        ("וְאִישׁ הַיִּשְׂרְאֵלִי", "ואלרגל אלאסראילי", "and the Israelite man"),
    ],
    11: [
        ("וַיִּקֹּב", "פסב", "reviled"),
        ("בֶּן-הָאִשָּׁה הַיִּשְׂרְאֵלִית", "אבן אלאמראה אלאסראילייה", "the son of the Israelite woman"),
        ("אֶת-הַשֵּׁם", "אלאסם", "the Name"),
        ("וַיְקַלֵּל", "ושתמה", "and cursed it"),
        ("וַיָּבִיאוּ", "פאתו", "and they brought"),
        (None, "בה", "him"),
        ("אֶל-מֹשֶׁה", "אלי' מוסי'", "to Moses"),
        (None, "וכאן", "Now"),
        ("וְשֵׁם", "אסם", "the name of"),
        ("אִמּוֹ", "אמה", "his mother"),
        ("שְׁלֹמִית", "שלומית", "Shelomith"),
        ("בַּת-דִּבְרִי", "אבנה' דברי", "daughter of Dibri"),
        ("לְמַטֵּה-דָן", "מן סבט דן", "of the tribe of Dan"),
    ],
    12: [
        ("וַיַּנִּיחֻהוּ", "פוצ'עוה", "And they placed him"),
        ("בַּמִּשְׁמָר", "פי אלחבס", "in custody"),
        ("לִפְרֹשׁ", "ליביין", "until"),
        ("לָהֶם", "להם", "to them"),
        (None, "אמרה", "his case should be made clear"),
        ("עַל-פִּי", "ען קול", "by the word of"),
        ("יְהוָה", "אללה", "God"),
    ],
    13: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in speech"),
    ],
    14: [
        ("הוֹצֵא", "אכ'רג", "Bring out"),
        ("אֶת-הַמְקַלֵּל", "אלשאתם", "the reviler"),
        ("אֶל-מִחוּץ", "אלי' כ'ארג", "to outside"),
        ("לַמַּחֲנֶה", "אלעסכר", "the camp"),
        ("וְסָמְכוּ", "ויסנד", "and let"),
        ("כָל-הַשֹּׁמְעִים", "כל מן סמעה", "all who heard him"),
        ("אֶת-יְדֵיהֶם", "אידיהם", "lay their hands"),
        ("עַל-רֹאשׁוֹ", "עלי' ראסה", "upon his head"),
        ("וְרָגְמוּ", "ולירגמוה", "and let all the people"),
        ("כָּל-הָעֵדָה", "גמיע אהל אלמחצ'ר", "of the presence"),
        (None, "רגמא", "stone him with stones"),
    ],
    15: [
        ("וְאֶל-בְּנֵי יִשְׂרָאֵל", "ומר בני אסראיל", "And command the sons of Israel"),
        ("תְּדַבֵּר לֵאמֹר", "וקל להם", "and say to them"),
        ("אִישׁ אִישׁ", "אי אנסאן", "any person"),
        ("כִּי-יְקַלֵּל", "שתם", "who curses"),
        ("אֱלֹהָיו", "רבה", "his Lord"),
        ("וְנָשָׂא", "פקד חמל", "shall bear"),
        ("חֶטְאוֹ", "וזרה", "his guilt"),
    ],
    16: [
        ("וְנֹקֵב", "ומן סבה", "And whoever reviles Him"),
        (None, "כד'אך", "thus"),
        ("מוֹת יוּמָת", "פליקתל קתלא", "shall be put to death"),
        ("רָגוֹם יִרְגְּמוּ-בוֹ", "לירגמוה", "shall stone him"),
        ("כָּל-הָעֵדָה", "גמיע אהל אלמחצ'ר", "all the people of the presence"),
        (None, "רגמא", "with stones"),
        ("כַּגֵּר", "אלדכ'יל", "The sojourner"),
        ("כָּאֶזְרָח", "כאלצריח", "and the native-born"),
        (None, "סוא", "are equal"),
        ("בְּנָקְבוֹ-שֵׁם", "אייהמא סב אלאסם", "whichever of them curses the Name"),
        ("יוּמָת", "פליקתל", "shall be put to death"),
    ],
    17: [
        ("וְאִישׁ", "ואי אנסאן", "And any person"),
        ("כִּי יַכֶּה", "קתל", "who kills"),
        ("כָּל-נֶפֶשׁ", "ואחדה מן נפוס", "one of the souls"),
        ("אָדָם", "אלנאס", "of the people"),
        ("מוֹת יוּמָת", "פליקתל", "shall be put to death"),
    ],
    18: [
        ("וּמַכֵּה", "ומן קתל", "And whoever kills"),
        ("נֶפֶשׁ-בְּהֵמָה", "בהימה", "a beast"),
        ("יְשַׁלְּמֶנָּה", "פליסלם מת'להא", "shall render its like"),
        ("נֶפֶשׁ תַּחַת נָפֶשׁ", "ראסא בדל ראס", "head in place of head"),
    ],
    19: [
        ("וְאִישׁ", "ואי אנסאן", "And any person"),
        ("כִּי-יִתֵּן", "געל", "who inflicts"),
        ("מוּם", "עיבא", "a defect"),
        ("בַּעֲמִיתוֹ", "פי אחד מן אמתה", "upon one of his fellow countrymen"),
        ("כַּאֲשֶׁר עָשָׂה", "כמא צנע", "as he has done"),
        ("כֵּן יֵעָשֶׂה לּוֹ", "פליצנע בה", "so shall be done to him"),
    ],
    20: [
        ("שֶׁבֶר תַּחַת שֶׁבֶר", "לאלכסר בדל אלכסר", "Fracture in place of fracture"),
        ("עַיִן תַּחַת עַיִן", "ולאלעין בדלהא", "and eye in place of eye"),
        ("שֵׁן תַּחַת שֵׁן", "ולאלסן בדלהא", "and tooth in place of tooth"),
        ("כַּאֲשֶׁר יִתֵּן", "כמא יגעל", "as one inflicts"),
        ("מוּם", "עיבא", "a defect"),
        ("בָּאָדָם", "פי אנסאנא", "upon a person"),
        ("כֵּן יִנָּתֶן בּוֹ", "כד'אך יגעל עליה", "so shall it be inflicted upon him"),
    ],
    21: [
        ("וּמַכֵּה בְהֵמָה", "ומן צ'רב בהימה", "And whoever strikes a beast"),
        ("יְשַׁלְּמֶנָּה", "פליג'רם", "shall be fined"),
        ("וּמַכֵּה אָדָם", "ומן צ'רב אנסאנא", "and whoever strikes a person"),
        (None, "ומאת", "and causes death"),
        ("יוּמָת", "פליקתל", "shall be put to death"),
    ],
    22: [
        (None, "וליכון", "And there shall be"),
        ("מִשְׁפַּט אֶחָד", "לכם חכם ואחד", "one ruling for you"),
        ("יִהְיֶה לָכֶם", "יסאוי", "are equal"),
        (None, "פיה", "in which"),
        ("כַּגֵּר", "אלדכ'יל", "the sojourner"),
        ("כָּאֶזְרָח", "ואלצריח", "and the native-born"),
        ("כִּי", "לאני", "for I am"),
        ("אֲנִי יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלואחד", "the One"),
    ],
    23: [
        ("וַיְדַבֵּר מֹשֶׁה", "פכלם מוסי'", "And Moses spoke"),
        (None, "בד'אלך", "thereby"),
        ("אֶל-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "to the sons of Israel"),
        ("וַיּוֹצִיאוּ", "ואכ'רגו", "and they brought out"),
        ("אֶת-הַמְקַלֵּל", "אלשאתם", "the reviler"),
        ("אֶל-מִחוּץ", "אלי' כ'ארג", "to outside"),
        ("לַמַּחֲנֶה", "אלעסכר", "the camp"),
        ("וַיִּרְגְּמוּ", "ורגמוה", "and stoned him"),
        (None, "באלחגארה", "with stones"),
        (None, "חתי'", "until"),
        (None, "מאת", "he died"),
        ("וּבְנֵי-יִשְׂרָאֵל", "וצנעו בני אסראיל", "And the sons of Israel acted"),
        ("עָשׂוּ", "פי סאיר מא נזל עליהם", "in all the rest of what had come down to them"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוָּה", "אמר", "had commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses."),
    ],
}
