"""Hand-authored alignment triples for Vayikra chapter 20."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses directly."),
    ],
    2: [
        ("וְאֶל-בְּנֵי יִשְׂרָאֵל תֹּאמַר אִישׁ אִישׁ מִבְּנֵי יִשְׂרָאֵל וּמִן-הַגֵּר הַגָּר בְּיִשְׂרָאֵל",
         "ומר בני אסראיל וקל להם. אי אנסאן מן בני אסראיל. ומן אלג'ריב אלדכ'יל פי מא בינהם",
         "Command the sons of Israel and say to them: Any person from the sons of Israel, or from the stranger who has entered among them,"),
        ("אֲשֶׁר יִתֵּן מִזַּרְעוֹ לַמֹּלֶךְ מוֹת יוּמָת",
         "יעטי מן נסלה לאלצנם פליקתל קתלא",
         "who gives of his offspring to the idols — let him be killed outright;"),
        ("עַם הָאָרֶץ יִרְגְּמֻהוּ בָאָבֶן",
         "והו אן ירגמוה אהל אלבלד באלחגארה",
         "that is, that the people of the town shall stone him with stones."),
    ],
    3: [
        ("וַאֲנִי אֶתֵּן אֶת-פָּנַי בָּאִישׁ הַהוּא וְהִכְרַתִּי אֹתוֹ מִקֶּרֶב עַמּוֹ",
         "ואנא אחל ג'צ'בי בד'אלך אלאנסאן. פאקטעה מן בין קומה",
         "And I shall pour out My wrath upon that person, and cut him off from among his people —"),
        ("כִּי מִזַּרְעוֹ נָתַן לַמֹּלֶךְ--לְמַעַן טַמֵּא אֶת-מִקְדָּשִׁי וּלְחַלֵּל אֶת-שֵׁם קָדְשִׁי",
         "אד' אעטא מן נסלה לאלצנם. לכי ינגס מקדסי. ויבד'ל אסמי אלמקדס",
         "since he gave of his offspring to the idols, in order to defile My sanctuary and to debase My holy name."),
    ],
    4: [
        ("וְאִם הַעְלֵם יַעְלִימוּ עַם הָאָרֶץ אֶת-עֵינֵיהֶם מִן-הָאִישׁ הַהוּא",
         "ואן תג'אפל אהל אלבלד תג'אפלא ען ד'אלך אלרגל",
         "And if the people of the town should turn a blind eye, looking away from that man"),
        ("בְּתִתּוֹ מִזַּרְעוֹ לַמֹּלֶךְ--לְבִלְתִּי הָמִית אֹתוֹ",
         "מע אעטאיה מן נסלה לאלצנם. ולם יקת'לוה",
         "even as he gives of his offspring to the idols, and they do not kill him —"),
    ],
    5: [
        ("וְשַׂמְתִּי אֲנִי אֶת-פָּנַי בָּאִישׁ הַהוּא וּבְמִשְׁפַּחְתּוֹ וְהִכְרַתִּי אֹתוֹ",
         "אחללת אנא ג'צ'בי. בד'אלך אלאנסאן ובמגאנסיה. וקטעתה",
         "I shall pour out My wrath upon that person and upon those who are associated with him, and cut him off,"),
        ("וְאֵת כָּל-הַזֹּנִים אַחֲרָיו לִזְנוֹת אַחֲרֵי הַמֹּלֶךְ--מִקֶּרֶב עַמָּם",
         "וגמיע אלטאג'יון תבעה ורא אלצנם מן בין קומהם",
         "and all those who rebelliously follow after him after the idol, from among their people."),
    ],
    6: [
        ("וְהַנֶּפֶשׁ אֲשֶׁר תִּפְנֶה אֶל-הָאֹבֹת וְאֶל-הַיִּדְּעֹנִים לִזְנֹת אַחֲרֵיהֶם",
         "ואי אנסאן ולא אלי' אלמשעוד'ין ואלעראפין. ליטג'י אלנאס פי תבעהם",
         "And any person who has turned to sorcerers and diviners, to lead the people astray in following them —"),
        ("וְנָתַתִּי אֶת-פָּנַי בַּנֶּפֶשׁ הַהִוא וְהִכְרַתִּי אֹתוֹ מִקֶּרֶב עַמּוֹ",
         "אחללת ג'צ'בי בד'אלך אלאנסאן. וקטעתה מן בין קומה",
         "I shall pour out My wrath upon that person, and cut him off from among his people."),
    ],
    7: [
        ("וְהִתְקַדִּשְׁתֶּם--וִהְיִיתֶם קְדֹשִׁים",
         "פתקדסו וכונו מקדסין",
         "So sanctify yourselves and be holy,"),
        ("כִּי אֲנִי יְהוָה אֱלֹהֵיכֶם",
         "לאני אללה רבכם אלקדוס",
         "for I am God your Lord, the Holy One."),
    ],
    8: [
        ("וּשְׁמַרְתֶּם אֶת-חֻקֹּתַי וַעֲשִׂיתֶם אֹתָם",
         "ואחפצ'ו רסומי ואעמלו בהא",
         "And keep My statutes and act according to them,"),
        ("אֲנִי יְהוָה מְקַדִּשְׁכֶם",
         "לאני אללה מקדסכם",
         "for I am God who sanctifies you."),
    ],
    9: [
        ("כִּי-אִישׁ אִישׁ אֲשֶׁר יְקַלֵּל אֶת-אָבִיו וְאֶת-אִמּוֹ--מוֹת יוּמָת",
         "אי אנסאן לען אביה ואמה. פליקתל קתלא",
         "Any person who has cursed his father and his mother — let him be killed outright;"),
        ("אָבִיו וְאִמּוֹ קִלֵּל דָּמָיו בּוֹ",
         "למא לען אביה ואמה. פקד חל דמה",
         "since he cursed his father and his mother, his blood is thereby made forfeit."),
    ],
    10: [
        ("וְאִישׁ אֲשֶׁר יִנְאַף אֶת-אֵשֶׁת אִישׁ אֲשֶׁר יִנְאַף אֶת-אֵשֶׁת רֵעֵהוּ",
         "ואי רגל זנא בזוגה' רגל או זנא באמראה' צאחבה",
         "And any man who committed adultery with a man's wife, or committed adultery with the wife of his fellow —"),
        ("מוֹת-יוּמַת הַנֹּאֵף וְהַנֹּאָפֶת",
         "פליקתל אלזאן ואלזאניה קתלא",
         "let the adulterer and the adulteress be killed outright."),
    ],
    11: [
        ("וְאִישׁ אֲשֶׁר יִשְׁכַּב אֶת-אֵשֶׁת אָבִיו--עֶרְוַת אָבִיו גִּלָּה",
         "ואי רגל צ'אגע זוגה' אביה. פקד כשף סווה' אביה",
         "And any man who lay with his father's wife has thereby uncovered his father's nakedness —"),
        ("מוֹת-יוּמְתוּ שְׁנֵיהֶם דְּמֵיהֶם בָּם",
         "פליקתלא גמיעא פקד חלת דמאהמא בד'אלך",
         "let them both be killed, for their blood is made forfeit by this."),
    ],
    12: [
        ("וְאִישׁ אֲשֶׁר יִשְׁכַּב אֶת-כַּלָּתוֹ--מוֹת יוּמְתוּ שְׁנֵיהֶם",
         "ואי רג'ל צ'אגע כנתה. פליקתלא גמיעא",
         "And any man who lay with his daughter-in-law — let them both be killed;"),
        ("תֶּבֶל עָשׂוּ דְּמֵיהֶם בָּם",
         "ולמא צנעא דאהיה פקד חל דמאהמא",
         "since they did an outrageous thing, their blood is thereby made forfeit."),
    ],
    13: [
        ("וְאִישׁ אֲשֶׁר יִשְׁכַּב אֶת-זָכָר מִשְׁכְּבֵי אִשָּׁה--תּוֹעֵבָה עָשׂוּ שְׁנֵיהֶם",
         "ואי רג'ל צ'אגע ד'כרא עלי' פן מצאגעה' אלנסא. פקד צנעא גמיעא כריהה",
         "And any man who lay with a male in the manner of lying with women — they have both together done an abomination;"),
        ("מוֹת יוּמָתוּ דְּמֵיהֶם בָּם",
         "פליקתלא קתלא פקד חל דמאהמא",
         "let them be killed outright, for their blood is made forfeit."),
    ],
    14: [
        ("וְאִישׁ אֲשֶׁר יִקַּח אֶת-אִשָּׁה וְאֶת-אִמָּהּ--זִמָּה הִוא",
         "ואי רגל אתכ'ד' אמראה ואמהא פתלך פאחשה",
         "And any man who took a woman and her mother — that is a vile act;"),
        ("בָּאֵשׁ יִשְׂרְפוּ אֹתוֹ וְאֶתְהֶן",
         "פליחרק באלנאר הו והן עלי' אלבדל",
         "let him and them both be burned with fire, on account of the degradation;"),
        ("וְלֹא-תִהְיֶה זִמָּה בְּתוֹכְכֶם",
         "ולא תכון פאחשה פי מא בינכם",
         "and there shall be no vile act among you."),
    ],
    15: [
        ("וְאִישׁ אֲשֶׁר יִתֵּן שְׁכָבְתּוֹ בִּבְהֵמָה--מוֹת יוּמָת",
         "ואי רגל געל מצ'אגעתה. מע בהימה פליקתל קתלא",
         "And any man who directed his lying with a beast — let him be killed outright;"),
        ("וְאֶת-הַבְּהֵמָה תַּהֲרֹגוּ",
         "ואלבהימה איצ'א פאקתלוהא",
         "and the beast also — kill it."),
    ],
    16: [
        ("וְאִשָּׁה אֲשֶׁר תִּקְרַב אֶל-כָּל-בְּהֵמָה לְרִבְעָה אֹתָהּ--וְהָרַגְתָּ אֶת-הָאִשָּׁה וְאֶת-הַבְּהֵמָה",
         "ואייה' אמראה. תקדמת אלי' בהימה לתנזוהא. פאקתל אלאמראה ואלבהימה",
         "And any woman who approached a beast to be mounted by it — kill the woman and the beast;"),
        ("מוֹת יוּמָתוּ דְּמֵיהֶם בָּם",
         "למא צנעא דאהיה פקד חל דמאהמא בד'אלך",
         "since they did an outrageous thing, their blood is thereby made forfeit."),
    ],
    17: [
        ("וְאִישׁ אֲשֶׁר-יִקַּח אֶת-אֲחֹתוֹ בַּת-אָבִיו אוֹ בַת-אִמּוֹ וְרָאָה אֶת-עֶרְוָתָהּ וְהִיא-תִרְאֶה אֶת-עֶרְוָתוֹ חֶסֶד הוּא",
         "ואי רגל אתכ'ד' אכ'תה. אבנה' אביה או אבנה' אמה. פנצ'ר אלי' סוותהא. ונצ'רת אלי' כסוותה פד'אלך עאר",
         "And any man who took his sister — whether the daughter of his father or the daughter of his mother — and looked upon her nakedness, and she looked upon his nakedness: that is a disgrace;"),
        ("וְנִכְרְתוּ לְעֵינֵי בְּנֵי עַמָּם",
         "פינקטעאן מן חצ'רה' קומהם",
         "they shall both be cut off from the presence of their people,"),
        ("עֶרְוַת אֲחֹתוֹ גִּלָּה עֲו‍ֹנוֹ יִשָּׂא",
         "למא כשף סווה' אכ'תה פקד חמל וזרה",
         "since he uncovered the nakedness of his sister; he has borne his guilt."),
    ],
    18: [
        ("וְאִישׁ אֲשֶׁר-יִשְׁכַּב אֶת-אִשָּׁה דָּוָה וְגִלָּה אֶת-עֶרְוָתָהּ אֶת-מְקֹרָהּ הֶעֱרָה וְהִוא גִּלְּתָה אֶת-מְקוֹר דָּמֶיהָ",
         "ואי רגל צ'אגע אמראה חאיץ'. פכשף סוותהא וערא נביעהא. והי איצ'א כשפת נביע דמהא",
         "And any man who lay with a menstruating woman, uncovering her nakedness and laying bare her spring, and she too uncovered the spring of her blood —"),
        ("וְנִכְרְתוּ שְׁנֵיהֶם מִקֶּרֶב עַמָּם",
         "פינקטעאן גמיעא מן בין קומהם",
         "they shall both be cut off from among their people."),
    ],
    19: [
        ("וְעֶרְוַת אֲחוֹת אִמְּךָ וַאֲחוֹת אָבִיךָ לֹא תְגַלֵּה",
         "וסווה' כ'אלתך ועמתך לא תכשף",
         "The nakedness of your maternal aunt and your paternal aunt you shall not uncover;"),
        ("כִּי אֶת-שְׁאֵרוֹ הֶעֱרָה עֲו‍ֹנָם יִשָּׂאוּ",
         "פאן מן ערא נסיבה פקד חמל וזרה",
         "for whoever bares his kinswoman has thereby borne his guilt."),
    ],
    20: [
        ("וְאִישׁ אֲשֶׁר יִשְׁכַּב אֶת-דֹּדָתוֹ--עֶרְוַת דֹּדוֹ גִּלָּה",
         "ואי רגל צ'אגע זוגה' עמה. פקד כשף סווה' עמה",
         "And any man who lay with the wife of his paternal uncle has thereby uncovered his uncle's nakedness;"),
        ("חֶטְאָם יִשָּׂאוּ עֲרִירִים יָמֻתוּ",
         "וממא חמלא וזרהמא ימותאן עקימאן",
         "and because they bore their guilt, they shall die childless."),
    ],
    21: [
        ("וְאִישׁ אֲשֶׁר יִקַּח אֶת-אֵשֶׁת אָחִיו--נִדָּה הִוא עֶרְוַת אָחִיו גִּלָּה",
         "ואי רגל אתכ'ד' זוגה' אכ'יה. אלתי הי מבעדה מנה. פלמא כשף סווה' אכ'יה",
         "And any man who took the wife of his brother — she who has been separated from him — since he uncovered his brother's nakedness,"),
        ("עֲרִירִים יִהְיוּ",
         "יכונאן עקימאן",
         "they shall both be childless."),
    ],
    22: [
        ("וּשְׁמַרְתֶּם אֶת-כָּל-חֻקֹּתַי וְאֶת-כָּל-מִשְׁפָּטַי וַעֲשִׂיתֶם אֹתָם",
         "ואחפצו גמיע רסומי ואחכאמי. ואעמלו בהא",
         "And keep all My statutes and My ordinances, and act according to them;"),
        ("וְלֹא-תָקִיא אֶתְכֶם הָאָרֶץ אֲשֶׁר אֲנִי מֵבִיא אֶתְכֶם שָׁמָּה לָשֶׁבֶת בָּהּ",
         "ולא ישתתכם אלבלד. אלד'י אנא מדכ'לכם הנאך לתחוזוה",
         "and do not let the land scatter you — the land into which I am bringing you there to possess it."),
    ],
    23: [
        ("וְלֹא תֵלְכוּ בְּחֻקֹּת הַגּוֹי אֲשֶׁר-אֲנִי מְשַׁלֵּחַ מִפְּנֵיכֶם",
         "ולא תסירו פי רסום אלאמם. אלד'י אנא טארדהם מן בין ידיכם",
         "And do not walk in the statutes of the nations whom I am driving out before you;"),
        ("כִּי אֶת-כָּל-אֵלֶּה עָשׂוּ וָאָקֻץ בָּם",
         "פאנהם למא צנעו גמיע הד'ה אקליתהם",
         "for since they did all these things, I have come to loathe them."),
    ],
    24: [
        ("וָאֹמַר לָכֶם אַתֶּם תִּירְשׁוּ אֶת-אַדְמָתָם וַאֲנִי אֶתְּנֶנָּה לָכֶם לָרֶשֶׁת אֹתָהּ",
         "וקלת לכם חאכמא. אנתם תחוזון בלדהם. ואנא אעטיה לכם תחוזוה",
         "And I said to you, decreeing: You shall possess their land, and I shall give it to you to possess —"),
        ("אֶרֶץ זָבַת חָלָב וּדְבָשׁ",
         "בלד יפיץ' אללבן ואלעסל",
         "a land flowing with milk and honey —"),
        ("אֲנִי יְהוָה אֱלֹהֵיכֶם אֲשֶׁר-הִבְדַּלְתִּי אֶתְכֶם מִן-הָעַמִּים",
         "לאני אללה רבכם. אלד'י אפרזתכם מן גמיע אלאמם",
         "for I am God your Lord, who has separated you from all the nations."),
    ],
    25: [
        ("וְהִבְדַּלְתֶּם בֵּין-הַבְּהֵמָה הַטְּהֹרָה לַטְּמֵאָה וּבֵין-הָעוֹף הַטָּמֵא לַטָּהֹר",
         "פמייזו אלבהימה אלטאהרה מן אלנגסה. ואלטאיר אלנגס מן אלטאהר",
         "So distinguish between the clean beast and the unclean, and between the unclean bird and the clean;"),
        ("וְלֹא-תְשַׁקְּצוּ אֶת-נַפְשֹׁתֵיכֶם בַּבְּהֵמָה וּבָעוֹף וּבְכֹל אֲשֶׁר תִּרְמֹשׂ הָאֲדָמָה אֲשֶׁר-הִבְדַּלְתִּי לָכֶם לְטַמֵּא",
         "ולא תרגסו אנפסכם באלבהאים ואלטיור. וסאיר מא ידב עלי' אלארץ'. אלד'י אפרזתה לכם לאלתנגיס",
         "and do not make yourselves loathsome with beasts and birds, and the rest of what creeps upon the earth — which I have set apart for you as unclean."),
    ],
    26: [
        ("וִהְיִיתֶם לִי קְדֹשִׁים כִּי קָדוֹשׁ אֲנִי יְהוָה",
         "וכונו לי מקדסין. לאני אללה אלקדוס",
         "And be holy unto Me, for I am God the Holy One;"),
        ("וָאַבְדִּל אֶתְכֶם מִן-הָעַמִּים לִהְיוֹת לִי",
         "אפרזתכם מן אלאמם לתכונו לי כ'אצה",
         "I have separated you from the nations that you may be Mine as a special possession."),
    ],
    27: [
        ("וְאִישׁ אוֹ-אִשָּׁה כִּי-יִהְיֶה בָהֶם אוֹב אוֹ יִדְּעֹנִי--מוֹת יוּמָתוּ",
         "ואי רגל או אמראה. כאן מנהמא משעודא. או עראפא פליקתלא קתלא",
         "And any man or woman in whom there is a sorcerer or a diviner — let them both be killed outright;"),
        ("בָּאֶבֶן יִרְגְּמוּ אֹתָם דְּמֵיהֶם בָּם",
         "ובאלחגארה ירגמוהמא פקד חלת דמאהמא",
         "they shall be stoned with stones — their blood is thereby made forfeit."),
    ],
}
