"""Hand-authored alignment triples for Vayikra chapter 21."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיֹּאמֶר יְהוָה אֶל-מֹשֶׁה אֱמֹר אֶל-הַכֹּהֲנִים בְּנֵי אַהֲרֹן",
         "ת'ם קאל אללה למוסי. מר אלאימה בני הרון",
         "Then God said to Moses: 'Command the imāms, the sons of Aaron,"),
        ("וְאָמַרְתָּ אֲלֵהֶם לְנֶפֶשׁ לֹא-יִטַּמָּא בְּעַמָּיו",
         "וקל להם לא ינגס כל ואחד מנכם במיית מן קומה",
         "and say to them: Let no one among you become impure through a dead person of his people —"),
    ],
    2: [
        ("כִּי אִם-לִשְׁאֵרוֹ הַקָּרֹב אֵלָיו לְאִמּוֹ וּלְאָבִיו",
         "אלא לנסיבה. אלאקרב אליה. אמה ואביה",
         "except for his next of kin, who is close to him: his mother and his father,"),
        ("וְלִבְנוֹ וּלְבִתּוֹ וּלְאָחִיו",
         "ואבנה ואבנתה ואכ'יה",
         "and his son and his daughter and his brother,"),
    ],
    3: [
        ("וְלַאֲחֹתוֹ הַבְּתוּלָה הַקְּרוֹבָה אֵלָיו אֲשֶׁר לֹא-הָיְתָה לְאִישׁ--לָהּ יִטַּמָּא",
         "ואכ'תה אלבכר אלאקרב אליה. והי אלתי לם תציר לרגל. פבהא ינגס",
         "and his virgin sister who is closest to him — she who has not yet become belonging to a man; for her he shall become impure, as is obligatory."),
    ],
    4: [
        ("לֹא יִטַּמָּא בַּעַל בְּעַמָּיו--לְהֵחַלּוֹ",
         "ולא ינגס בכ'טיר מן קומה. לאנה תבד'לה",
         "But he shall not become impure through a person of consequence from his people, as that would debase him."),
    ],
    5: [
        ("לֹא-יקרחה (יִקְרְחוּ) קָרְחָה בְּרֹאשָׁם וּפְאַת זְקָנָם לֹא יְגַלֵּחוּ",
         "לא ינתפו נתפא מן שער רוסהם. וזואיא לחאהם לא יחלקוהא",
         "They shall not pluck a plucking from the hair of their heads, nor shall they shave the corners of their beards,"),
        ("וּבִבְשָׂרָם--לֹא יִשְׂרְטוּ שָׂרָטֶת",
         "ופי אבדאנהם. לא יכ'דשון כ'דשא",
         "nor shall they scratch a scratch upon their bodies."),
    ],
    6: [
        ("קְדֹשִׁים יִהְיוּ לֵאלֹהֵיהֶם וְלֹא יְחַלְּלוּ שֵׁם אֱלֹהֵיהֶם",
         "וליכונו מקדסין לרבהם. ולא יבד'לו אסם רבהם",
         "And they shall be consecrated to their Lord, and shall not debase the name of their Lord —"),
        ("כִּי אֶת-אִשֵּׁי יְהוָה לֶחֶם אֱלֹהֵיהֶם הֵם מַקְרִיבִם--וְהָיוּ קֹדֶשׁ",
         "פאנהם למא הם מקרבין קראבין אללה רבהם אלדאימה יכונו מקדסין",
         "for, inasmuch as they are those who offer the offerings of God their Lord continually, they shall be consecrated."),
    ],
    7: [
        ("אִשָּׁה זֹנָה וַחֲלָלָה לֹא יִקָּחוּ",
         "באמראה פאגרה ומבד'ולה לא יתזווגו",
         "With a wanton and debased woman they shall not marry,"),
        ("וְאִשָּׁה גְּרוּשָׁה מֵאִישָׁהּ לֹא יִקָּחוּ כִּי-קָדֹשׁ הוּא לֵאלֹהָיו",
         "ובאמראה מטלקה מן בעלהא לא יתזווגו. פאן כל ואחד מנהם מקדס לרבה",
         "and with a woman divorced from her husband they shall not marry — for every one of them is consecrated to his Lord."),
    ],
    8: [
        ("וְקִדַּשְׁתּוֹ--כִּי-אֶת-לֶחֶם אֱלֹהֶיךָ הוּא מַקְרִיב",
         "וקדסה באלאלזאם. לאנה יקרב קרבאן רבך אלדאים",
         "And you shall consecrate him, as is obligatory — for he offers the offering of your Lord the Eternal;"),
        ("קָדֹשׁ יִהְיֶה-לָּךְ--כִּי קָדוֹשׁ אֲנִי יְהוָה מְקַדִּשְׁכֶם",
         "פליכון לך מקדסא. כמא אני אללה מקדסכם",
         "he shall therefore be consecrated to you, even as I, God, consecrate you."),
    ],
    9: [
        ("וּבַת אִישׁ כֹּהֵן כִּי תֵחֵל לִזְנוֹת--אֶת-אָבִיהָ הִיא מְחַלֶּלֶת",
         "ואיי אבנה' רג'ל אמאם. תבד'לת פפגרת. פקד פצ'חת אביהא",
         "And whichever daughter of a man who is an imām has debased herself and acted wantonly — she has brought public disgrace upon her father;"),
        ("בָּאֵשׁ תִּשָּׂרֵף",
         "פלתחרק באלנאר",
         "she shall be burned with fire."),
    ],
    10: [
        ("וְהַכֹּהֵן הַגָּדוֹל מֵאֶחָיו אֲשֶׁר-יוּצַק עַל-רֹאשׁוֹ שֶׁמֶן הַמִּשְׁחָה וּמִלֵּא אֶת-יָדוֹ לִלְבֹּשׁ אֶת-הַבְּגָדִים",
         "ואלאמאם אלכביר מן אכ'ותה. אלדי י'צב עלי' ראסה דהן אלמסח ויכמל ואגבה בלבס אלת'יאב",
         "And the great imām among his brothers, upon whose head the anointing oil is poured and whose obligation is fulfilled by the wearing of the vestments —"),
        ("אֶת-רֹאשׁוֹ לֹא יִפְרָע וּבְגָדָיו לֹא יִפְרֹם",
         "פלא ישעת ראסה. ות'יאבה לא ימזקהא",
         "he shall not dishevel his head, nor shall he tear his garments."),
    ],
    11: [
        ("וְעַל כָּל-נַפְשֹׁת מֵת לֹא יָבֹא",
         "ועלי אי אנסאן מיית לא ידכ'ל",
         "Over any dead person he shall not enter;"),
        ("לְאָבִיו וּלְאִמּוֹ לֹא יִטַּמָּא",
         "חתא באביה ואמה לא ינגס",
         "even for his father and his mother he shall not become impure."),
    ],
    12: [
        ("וּמִן-הַמִּקְדָּשׁ לֹא יֵצֵא וְלֹא יְחַלֵּל אֵת מִקְדַּשׁ אֱלֹהָיו",
         "ומן אלמקדס לא יכ'רג וראהמא. ולא יבד'ל קדס רבה",
         "And from the sanctuary he shall not go out after them, nor shall he debase the consecration of his Lord —"),
        ("כִּי נֵזֶר שֶׁמֶן מִשְׁחַת אֱלֹהָיו עָלָיו--אֲנִי יְהוָה",
         "לאן למא תאג דהן מסח רבה עליה. אנא אללה שרפתה",
         "for, inasmuch as the crown of his Lord's anointing oil is upon him, I, God, have honored him."),
    ],
    13: [
        ("וְהוּא אִשָּׁה בִבְתוּלֶיהָ יִקָּח",
         "והו פלא יתזווג אלא באמראה בכר",
         "And he — he shall marry none but a virgin woman."),
    ],
    14: [
        ("אַלְמָנָה וּגְרוּשָׁה וַחֲלָלָה זֹנָה אֶת-אֵלֶּה לֹא יִקָּח",
         "אמא ארמלה או מטלקה ומבד'ולה ופאגרה. פלא יתזווג באחדי' מן הולאי",
         "As for a widow, or a divorced woman, or a debased woman, or a wanton woman — he shall not marry any of these;"),
        ("כִּי אִם-בְּתוּלָה מֵעַמָּיו יִקַּח אִשָּׁה",
         "אלא באמראה בכר מן קומה יתזווג",
         "only a virgin woman from his people shall he marry."),
    ],
    15: [
        ("וְלֹא-יְחַלֵּל זַרְעוֹ בְּעַמָּיו כִּי אֲנִי יְהוָה מְקַדְּשׁוֹ",
         "ולא יבד'ל נסלה בסואהא מן קומה לאני אללה מקדסה",
         "And he shall not debase his offspring through any other than her from his people — for I, God, consecrate him.'"),
    ],
    16: [
        ("וַיְדַבֵּר יְהוָה אֶל-מֹשֶׁה לֵּאמֹר",
         "ת'ם כלם אללה מוסי' תכלימא",
         "Then God spoke to Moses in speech."),
    ],
    17: [
        ("דַּבֵּר אֶל-אַהֲרֹן לֵאמֹר אִישׁ מִזַּרְעֲךָ לְדֹרֹתָם אֲשֶׁר יִהְיֶה בוֹ מוּם--לֹא יִקְרַב לְהַקְרִיב לֶחֶם אֱלֹהָיו",
         "מר הרון וקל לה. אי רגל מן נסלך עלי' מר אגיאלהם. יכון פיה עיב. לא יתקדם. ליקרב קרבאן רבה",
         "'Command Aaron and say to him: Any man from your offspring, throughout their generations, in whom there is a blemish — he shall not come forward to offer the offering of his Lord."),
    ],
    18: [
        ("כִּי כָל-אִישׁ אֲשֶׁר-בּוֹ מוּם לֹא יִקְרָב",
         "לאן כל רגל פיה עיב לא יתקדם",
         "For every man in whom there is a blemish shall not come forward."),
        ("אִישׁ עִוֵּר אוֹ פִסֵּחַ אוֹ חָרֻם אוֹ שָׂרוּעַ",
         "פמן ד'אלך אלאעמא ואלאזמן. ואלאכ'רם ואלכ'אמע",
         "Among such: the blind and the lame, and one with a cleft nose and one who limps,"),
    ],
    19: [
        ("אוֹ אִישׁ אֲשֶׁר-יִהְיֶה בוֹ שֶׁבֶר רָגֶל אוֹ שֶׁבֶר יָד",
         "או רגל יכון פיה כסר רגל. או כסר יד",
         "or a man in whom there is a broken leg or a broken arm,"),
    ],
    20: [
        ("אוֹ-גִבֵּן אוֹ-דַק אוֹ תְּבַלֻּל בְּעֵינוֹ אוֹ גָרָב אוֹ יַלֶּפֶת אוֹ מְרוֹחַ אָשֶׁךְ",
         "או אחדב או אכ'פש. או כת'יב פי עינה. או בה גרב או חזאז. או אדר",
         "or a hunchback, or one of dim sight, or one with a cataract in his eye, or in whom there is mange or thick scaling of the head, or one with a crushed testicle —"),
    ],
    21: [
        ("כָּל-אִישׁ אֲשֶׁר-בּוֹ מוּם מִזֶּרַע אַהֲרֹן הַכֹּהֵן--לֹא יִגַּשׁ לְהַקְרִיב אֶת-אִשֵּׁי יְהוָה",
         "כד'אך כל רג'ל פיה עיב. מן נסל הרון אלאמאם. לא יתקדם ליקרב קרבאן אללה",
         "so too every man in whom there is a blemish, from the offspring of Aaron the imām: he shall not come forward to offer the offering of God;"),
        ("מוּם בּוֹ--אֵת לֶחֶם אֱלֹהָיו לֹא יִגַּשׁ לְהַקְרִיב",
         "ומהמא ד'אלך אלעיב פיה. פקרבאן רבה. לא יתקדם ליקרבה",
         "and whatever that blemish be in him, the offering of his Lord he shall not come forward to offer."),
    ],
    22: [
        ("לֶחֶם אֱלֹהָיו מִקָּדְשֵׁי הַקֳּדָשִׁים וּמִן-הַקֳּדָשִׁים יֹאכֵל",
         "לאכן רזק רבה. מן כ'ואץ אלאקדאס. ועואמהא יאכל",
         "However, the provision of his Lord — from the choicest of the holy things and from the general portions thereof — he may eat."),
    ],
    23: [
        ("אַךְ אֶל-הַפָּרֹכֶת לֹא יָבֹא וְאֶל-הַמִּזְבֵּחַ לֹא יִגַּשׁ--כִּי-מוּם בּוֹ",
         "אמא אלי' אלסגף פלא ידכ'ל. ואלי אלמד'בח. פלא יתקדם אד' פיה עיב",
         "But into the curtain he shall not enter, and to the altar he shall not come forward, since there is a blemish in him;"),
        ("וְלֹא יְחַלֵּל אֶת-מִקְדָּשַׁי כִּי אֲנִי יְהוָה מְקַדְּשָׁם",
         "ולא יבד'ל מקאדסי. לאני אללה מקדסהמא",
         "and he shall not debase My sacred things — for I, God, consecrate them.'"),
    ],
    24: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-אַהֲרֹן וְאֶל-בָּנָיו וְאֶל-כָּל-בְּנֵי יִשְׂרָאֵל",
         "פאמר מוסי' בד'אלך הרון ובניה. וסאיר בני אסראיל",
         "And Moses commanded thereby Aaron and his sons, and the rest of the sons of Israel."),
    ],
}
