"""Hand-authored alignment triples for Vayikra chapter 16.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "אן", "And"),
        ("יְהוָה", "אללה", "God"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("אֶל-מֹשֶׁה", "מוסי'", "to Moses"),
        ("אַחֲרֵי", "בעד", "after"),
        ("מוֹת", "מות", "the death of"),
        ("שְׁנֵי בְּנֵי", "אבני", "the two sons of"),
        ("אַהֲרֹן", "הרון", "Aaron"),
        ("בְּקָרְבָתָם", "תקדמא", "drawn near"),
        ("לִפְנֵי-יְהוָה", "בין ידי אללה", "before God"),
        (None, "עלי' מא ביין", "in a manner that became clear,"),
        ("וַיָּמֻתוּ", "פמאתא", "and they died"),
    ],
    2: [
        ("וַיֹּאמֶר", "וקאל", "And He said"),
        (None, "לה", "to him"),
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-אַהֲרֹן", "הרון", "Aaron"),
        ("אָחִיךָ", "אכ'יך", "your brother"),
        ("וְאַל-יָבֹא", "באן לא ידכ'ל", "that he shall not enter"),
        ("בְכָל-עֵת", "פי כתיר", "at many times"),
        ("אֶל-הַקֹּדֶשׁ", "אלי' אלקדס", "into the sanctuary"),
        ("מִבֵּית לַפָּרֹכֶת", "מן דאכ'ל אלסגף", "from within the veil"),
        ("אֶל-פְּנֵי הַכַּפֹּרֶת", "מן חצ'רה' אלג'שא", "near the covering"),
        ("אֲשֶׁר עַל-הָאָרֹן", "אלד'י עלי' אלצנדוק", "which is upon the ark"),
        ("וְלֹא יָמוּת", "ללא ימות", "lest he die"),
        ("כִּי", "לאני", "for"),
        ("בֶּעָנָן", "באלג'מאם", "in the cloud"),
        ("אֵרָאֶה", "מתגלי", "revealing Myself"),
        ("עַל-הַכַּפֹּרֶת", "פוק אלג'שא", "above the covering"),
    ],
    3: [
        ("בְּזֹאת", "בהד'א", "With these"),
        (None, "אלאמור", "matters"),
        ("יָבֹא", "ידכ'ל", "shall"),
        ("אַהֲרֹן", "הרון", "Aaron enter"),
        ("אֶל-הַקֹּדֶשׁ", "אלי' אלקדס", "into the sanctuary:"),
        (None, "באן יחצ'ר", "by presenting"),
        ("בְּפַר", "רת'א", "a bull"),
        ("בֶּן-בָּקָר", "מן אלבקר", "from the cattle"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification-offering"),
        ("וְאַיִל", "וכבשא", "and a ram"),
        ("לְעֹלָה", "לאלצעידה", "for the ascending-offering"),
    ],
    4: [
        ("כְּתֹנֶת-בַּד", "תוניה מן עשר", "a tunic of fine linen"),
        ("קֹדֶשׁ", "מקדסה", "consecrated;"),
        ("יִלְבָּשׁ", "ואן ילבס", "And that he shall wear"),
        (None, "בעד אן", "after"),
        ("יִהְיוּ", "יכון", "there are"),
        ("עַל-בְּשָׂרוֹ", "עלי' בדנה", "upon his body"),
        ("וּמִכְנְסֵי-בַד", "סראויל מן עשר", "breeches of fine linen"),
        ("וּבְאַבְנֵט בַּד", "בזנאר מן עשר", "with a sash of"),
        ("יַחְגֹּר", "ויתקלד", "and he shall gird himself"),
        (None, "מחץ'", "pure fine linen,"),
        ("וּבְמִצְנֶפֶת בַּד", "בעמאמה", "a turban"),
        ("יִצְנֹף", "ויתעמם", "and shall wind upon his head"),
        (None, "מת'ל ד'אלך", "likewise"),
        ("בִּגְדֵי-קֹדֶשׁ", "ת'יאב אלקדס", "the garments of the sanctuary"),
        ("הֵם", "פהד'ה הי", "these are"),
        ("וְרָחַץ", "יג'סל", "he shall wash"),
        ("אֶת-בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַּמַּיִם", "באלמא", "with water"),
        ("וּלְבֵשָׁם", "וילבסהא", "and put them on"),
    ],
    5: [
        ("וּמֵאֵת", "מן", "from"),
        ("עֲדַת", "גמאעה'", "the assembly of"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("יִקַּח", "וליאכ'ד'", "And he shall take"),
        ("שְׁנֵי-שְׂעִירֵי", "עתודין", "two he-goats"),
        ("עִזִּים", "מן אלמאעז", "from the goats"),
        ("לְחַטָּאת", "לאלד'כוה", "for the purification-offering"),
        ("וְאַיִל אֶחָד", "וכבשא", "and a ram"),
        ("לְעֹלָה", "לאלצעידה", "for the ascending-offering"),
    ],
    6: [
        ("וְהִקְרִיב", "פיבתדי", "And he shall begin"),
        (None, "אוולא", "first,"),
        ("אַהֲרֹן", "ויקדם", "and present"),
        ("אֶת-פַּר", "רת'", "the bull of"),
        ("הַחַטָּאת", "אלד'כוה", "the purification-offering"),
        ("אֲשֶׁר-לוֹ", "אלד'י לה", "which is his"),
        ("וְכִפֶּר", "ויסתג'פר", "and seek forgiveness"),
        ("בַּעֲדוֹ", "ענה", "for himself"),
        ("וּבְעַד בֵּיתוֹ", "וען אלה", "and for his household"),
    ],
    7: [
        ("וְלָקַח", "ת'ם יאכ'ד'", "Then he shall take"),
        ("אֶת-שְׁנֵי הַשְּׂעִירִם", "אלעתודין", "the two he-goats"),
        ("וְהֶעֱמִיד אֹתָם", "ויוקפהמא", "and station them"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("פֶּתַח", "ענד באב", "at the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
    ],
    8: [
        ("וְנָתַן אַהֲרֹן", "וילקי", "And he shall cast"),
        ("עַל-שְׁנֵי הַשְּׂעִירִם", "עליהמא", "upon them"),
        ("גֹּרָלוֹת", "סהמין", "two lots"),
        ("גּוֹרָל אֶחָד", "אחדהמא", "one of the two"),
        ("לַיהוָה", "לבית אללה", "for the house of God"),
        ("וְגוֹרָל אֶחָד", "ואלאכ'ר", "and the other"),
        ("לַעֲזָאזֵל", "לגבל עזאז", "for Mount Azazel"),
    ],
    9: [
        ("וְהִקְרִיב אַהֲרֹן", "פיקדם", "And he shall present"),
        ("אֶת-הַשָּׂעִיר", "אלעתוד", "the he-goat"),
        ("אֲשֶׁר עָלָה עָלָיו", "אלד'י וקע עליה", "upon which"),
        ("הַגּוֹרָל", "אלסהם", "the lot fell"),
        ("לַיהוָה", "לבית אללה", "for the house of God,"),
        ("וְעָשָׂהוּ", "ויצנעה", "and make it"),
        ("חַטָּאת", "ד'כוה", "a purification-offering"),
    ],
    10: [
        ("וְהַשָּׂעִיר", "ואלעתוד", "And the he-goat"),
        ("אֲשֶׁר עָלָה עָלָיו", "אלד'י וקע עליה", "upon which"),
        ("הַגּוֹרָל", "אלסהם", "the lot fell"),
        ("לַעֲזָאזֵל", "לגבל עזאז", "for Mount Azazel"),
        ("יָעֳמַד-חַי", "יוקף חייא", "shall be left standing alive"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("לְכַפֵּר עָלָיו", "ליסתג'פר ענדה", "to seek forgiveness thereby"),
        ("לְשַׁלַּח אֹתוֹ", "ת'ם יטלקה", "then he shall release it"),
        ("לַעֲזָאזֵל", "פי גבל עזאז", "on Mount Azazel"),
        ("הַמִּדְבָּרָה", "פי אלבר", "in the wilderness"),
    ],
    11: [
        ("וְהִקְרִיב אַהֲרֹן", "ויקדם הרון", "And Aaron shall present"),
        (None, "ת'אניה", "a second time"),
        ("אֶת-פַּר", "רת'", "the bull of"),
        ("הַחַטָּאת", "אלד'כוה", "the purification-offering"),
        ("אֲשֶׁר-לוֹ", "אלד'י לה", "which is his"),
        ("וְכִפֶּר", "ויסתג'פר", "and seek forgiveness"),
        ("בַּעֲדוֹ", "ענה", "for himself"),
        ("וּבְעַד בֵּיתוֹ", "וען אלה", "and for his household"),
        ("וְשָׁחַט", "ת'ם יד'בחה", "then he shall slaughter it"),
    ],
    12: [
        ("וְלָקַח", "ת'ם יאכ'ד", "Then he shall take"),
        ("מְלֹא-הַמַּחְתָּה", "מל אלמגמרה", "a firepan full"),
        ("גַּחֲלֵי-אֵשׁ", "גמר נאר", "of glowing coals of fire"),
        ("מֵעַל הַמִּזְבֵּחַ", "מן פוק אלמד'בח", "from atop the altar"),
        ("מִלִּפְנֵי יְהוָה", "מן בין ידי אללה", "before God"),
        ("וּמְלֹא חָפְנָיו", "ומל חפניה", "and two handfuls"),
        ("קְטֹרֶת סַמִּים", "מן בכ'ור אלצמוג'", "resinous incense,"),
        ("דַּקָּה", "אלמדקוק", "finely ground"),
        ("וְהֵבִיא", "וידכ'ל", "and bring"),
        (None, "אלגמיע", "them all"),
        ("מִבֵּית לַפָּרֹכֶת", "אלי' דאכ'ל אלסגף", "within the veil"),
    ],
    13: [
        ("וְנָתַן", "וילקי", "And he shall place"),
        ("אֶת-הַקְּטֹרֶת", "ד'אלך אלבכ'ור", "that incense"),
        ("עַל-הָאֵשׁ", "עלי' אלנאר", "upon the fire"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("וְכִסָּה", "חתי יג'טי", "until"),
        ("עֲנַן הַקְּטֹרֶת", "צ'באב אלבכ'ור", "the cloud of the incense"),
        ("אֶת-הַכַּפֹּרֶת", "אלג'שא", "the covering"),
        ("אֲשֶׁר עַל-הָעֵדוּת", "אלד'י עלי' אלצנדוק", "which is upon the ark"),
        ("וְלֹא יָמוּת", "פאנה לא ימות", "and so he shall not die"),
    ],
    14: [
        ("וְלָקַח", "ת'ם יאכ'ד'", "Then he shall take"),
        ("מִדַּם הַפָּר", "מן דם אלרת'", "some of the blood of the bull"),
        ("וְהִזָּה", "וינצ'ח", "and sprinkle"),
        ("מִן-הַדָּם", "מנה", "from it"),
        ("בְאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("עַל-פְּנֵי הַכַּפֹּרֶת", "קבאלה' אלג'שא", "facing the covering"),
        ("קֵדְמָה", "שרקייא", "on the east side"),
        (None, "מרה ואחדה", "once"),
        ("וְלִפְנֵי הַכַּפֹּרֶת", "ת'ם ינצ'ח בין ידיה", "then he shall sprinkle before it"),
        ("יַזֶּה", "מנה", "from it"),
        ("שֶׁבַע-פְּעָמִים", "סבע מראר", "seven times"),
    ],
    15: [
        ("וְשָׁחַט", "ת'ם יד'בח", "Then he shall slaughter"),
        ("אֶת-שְׂעִיר הַחַטָּאת", "עתוד אלד'כוה", "the he-goat of the purification-offering"),
        ("אֲשֶׁר לָעָם", "אלד'י לאלקום", "which is for the people"),
        ("וְהֵבִיא", "וידכ'ל", "and bring"),
        ("אֶת-דָּמוֹ", "מן דמה", "some of its blood"),
        ("אֶל-מִבֵּית לַפָּרֹכֶת", "אלי' דאכ'ל אלסגף", "within the veil"),
        ("וְעָשָׂה", "ויצנע", "and do"),
        ("אֶת-דָּמוֹ", "בה", "with it"),
        ("כַּאֲשֶׁר עָשָׂה", "כמא צנע", "as he did"),
        ("לְדַם הַפָּר", "בדם אלרת'", "with the blood of the bull"),
        ("וְהִזָּה אֹתוֹ", "וינצ'ח מנה", "and he shall sprinkle from it"),
        ("עַל-הַכַּפֹּרֶת", "קבאלה' אלג'שא", "facing the covering"),
        ("וְלִפְנֵי הַכַּפֹּרֶת", "ובין ידיה", "and before it"),
    ],
    16: [
        ("וְכִפֶּר", "ויסתג'פר", "And he shall seek forgiveness"),
        ("עַל-הַקֹּדֶשׁ", "פי אלקדס", "in the sanctuary"),
        ("מִטֻּמְאֹת", "ען מעאצי", "for the transgressions of"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("וּמִפִּשְׁעֵיהֶם", "וגרומהם", "their offenses"),
        ("לְכָל-חַטֹּאתָם", "וגמיע ד'נובהם", "and all their sins"),
        ("וְכֵן יַעֲשֶׂה", "וכד'אלך יצנע", "and likewise he shall do"),
        (None, "פי", "with"),
        (None, "אלדמוין", "the two bloods"),
        ("לְאֹהֶל מוֹעֵד", "פי כ'בא אלמחצ'ר", "in the tent of the assembly"),
        ("הַשֹּׁכֵן", "אלד'י הו סאכן", "which is dwelling"),
        ("אִתָּם", "מעהם", "among them"),
        ("בְּתוֹךְ טֻמְאֹתָם", "פי מא בין מעאציהם", "amid their transgressions"),
    ],
    17: [
        ("וְכָל-אָדָם", "ולא יכון אחד מן אלנאס", "And no one from the people shall be"),
        ("בְּאֹהֶל מוֹעֵד", "פי כ'בא אלמחצ'ר", "in the tent of the assembly"),
        ("בְּבֹאוֹ", "חין ידכ'ל", "when he enters"),
        ("לְכַפֵּר", "ליסתג'פר", "to seek forgiveness"),
        ("בַּקֹּדֶשׁ", "פי אלקדס", "in the sanctuary"),
        ("עַד-צֵאתוֹ", "אלי' אן יכ'רג", "until he comes out"),
        ("וְכִפֶּר", "וקד אסתג'פר", "having sought forgiveness"),
        ("בַּעֲדוֹ", "ענה", "for himself"),
        ("וּבְעַד בֵּיתוֹ", "וען אלה", "and for his household"),
        ("וּבְעַד כָּל-קְהַל יִשְׂרָאֵל", "וען גמיע גוק אל אסראיל", "and for the entire assembly of the house of Israel"),
    ],
    18: [
        ("וְיָצָא", "ת'ם יכ'רג", "Then he shall go out"),
        ("אֶל-הַמִּזְבֵּחַ", "אלי' אלמד'בח", "to the altar"),
        ("אֲשֶׁר לִפְנֵי-יְהוָה", "אלד'י בין ידי אללה", "which is before God"),
        ("וְכִפֶּר עָלָיו", "פיסתג'פר ענה", "and seek forgiveness for it"),
        ("וְלָקַח", "באן יאכ'ד'", "by taking"),
        ("מִדַּם הַפָּר", "מן דם אלרת'", "from the blood of the bull"),
        ("וּמִדַּם הַשָּׂעִיר", "ומע דם אלעתוד", "together with the blood of the he-goat"),
        (None, "מגמועין", "combined"),
        ("וְנָתַן", "ויצ'ע", "and placing it"),
        ("עַל-קַרְנוֹת הַמִּזְבֵּחַ", "עלי' ארכאנה", "upon its horns"),
        ("סָבִיב", "מסתדירא", "all around"),
    ],
    19: [
        ("וְהִזָּה", "וינצ'ח", "And he shall sprinkle"),
        ("עָלָיו", "עלי' סטחה", "upon its surface"),
        ("מִן-הַדָּם", "מנה", "from it"),
        ("בְּאֶצְבָּעוֹ", "באצבעה", "with his finger"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        ("וְטִהֲרוֹ", "ויטהרה", "and purify it"),
        ("וְקִדְּשׁוֹ", "ויקדסה", "and sanctify it"),
        ("מִטֻּמְאֹת", "מן מעאצי", "from the transgressions of"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
    ],
    20: [
        ("וְכִלָּה", "פאד'א פרג'", "And when he has finished"),
        ("מִכַּפֵּר", "מן אלאסתג'פאר", "the seeking of forgiveness"),
        ("אֶת-הַקֹּדֶשׁ", "פי אלקדס", "in the sanctuary"),
        ("וְאֶת-אֹהֶל מוֹעֵד", "ופי כ'בא אלמחצ'ר", "and in the tent of the assembly"),
        ("וְאֶת-הַמִּזְבֵּחַ", "וענד אלמד'בח", "and at the altar"),
        ("וְהִקְרִיב", "יקדם", "he shall present"),
        ("אֶת-הַשָּׂעִיר הֶחָי", "אלעתוד אלחי", "the living he-goat"),
    ],
    21: [
        ("וְסָמַךְ אַהֲרֹן", "ויסנד", "And he shall lean"),
        ("אֶת-שְׁתֵּי יָדָו", "ידה", "his hand"),
        ("עַל רֹאשׁ הַשָּׂעִיר הַחַי", "עלי' ראסה", "upon its head,"),
        ("וְהִתְוַדָּה", "ויקר", "and confess"),
        ("אֶת-כָּל-עֲו‍ֹנֹת", "בד'נוב", "the sins of"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("וְאֶת-כָּל-פִּשְׁעֵיהֶם", "וגרומהם", "their offenses"),
        ("לְכָל-חַטֹּאתָם", "וגמיע כ'טאיאהם", "and all their transgressions"),
        (None, "פאד'א תלאהא", "and when he has recited them"),
        ("וְנָתַן אֹתָם עַל-רֹאשׁ הַשָּׂעִיר", "ענד ראס אלעתוד", "at the head of the he-goat"),
        ("וְשִׁלַּח", "בעת' בה", "he shall send it away"),
        ("בְּיַד-אִישׁ עִתִּי", "מע רגל מעד בה", "with a man appointed for this"),
        ("הַמִּדְבָּרָה", "אלי' אלבר", "into the wilderness"),
    ],
    22: [
        ("וְנָשָׂא הַשָּׂעִיר", "פהו יחמל אלעתוד", "And it shall bear"),
        ("עָלָיו", "עלי' ענקה", "upon its neck"),
        ("אֶת-כָּל-עֲו‍ֹנֹתָם", "ען גמיע ד'נובהם", "all their sins"),
        ("אֶל-אֶרֶץ גְּזֵרָה", "אלי' ארץ' מנקטעה", "to a cut-off land"),
        ("וְשִׁלַּח", "ת'ם יטלקה", "and then he shall release it"),
        ("אֶת-הַשָּׂעִיר", "פי", "in"),
        ("בַּמִּדְבָּר", "אלבר", "the wilderness"),
    ],
    23: [
        ("וּבָא", "ת'ם ידכ'ל", "Then"),
        ("אַהֲרֹן", "הרון", "Aaron shall enter"),
        ("אֶל-אֹהֶל מוֹעֵד", "אלי' כ'בא אלמחצ'ר", "the tent of the assembly"),
        (None, "פיכ'רג אלמגמרה", "and bring out the firepan"),
        ("וּפָשַׁט", "ת'ם ינזע", "then he shall remove"),
        ("אֶת-בִּגְדֵי הַבָּד", "ת'יאב אלעשר", "the garments of fine linen"),
        ("אֲשֶׁר לָבַשׁ", "אלד'י לבסהא", "which he had worn"),
        ("בְּבֹאוֹ", "פי דכ'ולה", "upon his entry"),
        ("אֶל-הַקֹּדֶשׁ", "אלי' אלקדס", "into the sanctuary"),
        ("וְהִנִּיחָם שָׁם", "וידעהא הנאך", "and leave them there"),
    ],
    24: [
        ("וְרָחַץ", "ת'ם יג'סל", "Then he shall wash"),
        ("אֶת-בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַמַּיִם", "באלמא", "with water"),
        ("בְּמָקוֹם קָדוֹשׁ", "פי מוצ'ע מקדס", "in a consecrated place"),
        ("וְלָבַשׁ", "וילבס", "and put on"),
        ("אֶת-בְּגָדָיו", "ת'יאבה אלמעלומה", "his known garments"),
        ("וְיָצָא", "ת'ם יכ'רג", "then he shall go out"),
        ("וְעָשָׂה", "ויקרב", "and offer"),
        ("אֶת-עֹלָתוֹ", "צואעדה", "his ascending-offerings"),
        ("וְאֶת-עֹלַת הָעָם", "וצואעד אלקום", "and the ascending-offerings of the people"),
        ("וְכִפֶּר", "ויסתג'פר", "and seek forgiveness"),
        ("בַּעֲדוֹ", "ענה", "for himself"),
        ("וּבְעַד הָעָם", "וענהם", "and for them"),
    ],
    25: [
        ("וְאֵת חֵלֶב הַחַטָּאת", "ושחום אלד'כואת", "And the fats of the purification-offerings"),
        ("יַקְטִיר", "יקתרהא", "he shall burn as smoke"),
        ("הַמִּזְבֵּחָה", "עלי' אלמד'בח", "upon the altar"),
    ],
    26: [
        ("וְהַמְשַׁלֵּחַ", "ואלמטלק", "And the one who releases"),
        ("אֶת-הַשָּׂעִיר", "אלעתוד", "the he-goat"),
        ("לַעֲזָאזֵל", "פי גבל עזאז", "on Mount Azazel"),
        ("יְכַבֵּס", "יג'סל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("אֶת-בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַּמָּיִם", "באלמא", "with water"),
        ("וְאַחֲרֵי-כֵן", "ובעד ד'אלך", "and after that"),
        ("יָבוֹא", "ידכ'ל", "he shall enter"),
        ("אֶל-הַמַּחֲנֶה", "אלי' אלעסכר", "the camp"),
    ],
    27: [
        ("וְאֵת פַּר הַחַטָּאת", "ואמא רת' אלד'כוה", "And as for the bull of the purification-offering"),
        ("וְאֵת שְׂעִיר הַחַטָּאת", "ועתוד אלד'כוה", "and the he-goat of the purification-offering"),
        ("אֲשֶׁר הוּבָא אֶת-דָּמָם", "אלד'י אדכ'ל מן דמאהמא", "whose blood was brought in"),
        ("לְכַפֵּר בַּקֹּדֶשׁ", "לאלאסתג'פאר פי אלקדס", "to seek forgiveness in the sanctuary"),
        ("יוֹצִיא", "פליכ'רגהא", "he shall bring them out"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "to outside the camp"),
        ("וְשָׂרְפוּ", "ויחרקו", "and they shall be burned"),
        ("בָאֵשׁ", "באלנאר", "with fire"),
        ("אֶת-עֹרֹתָם", "גלודהא", "their hides"),
        ("וְאֶת-בְּשָׂרָם", "ולחומהא", "and their flesh"),
        ("וְאֶת-פִּרְשָׁם", "ופרת'המא", "and their dung"),
    ],
    28: [
        ("וְהַשֹּׂרֵף אֹתָם", "ואלמחרקהמא", "And the one who burns them"),
        ("יְכַבֵּס", "יגסל", "shall wash"),
        ("בְּגָדָיו", "ת'יאבה", "his garments"),
        ("וְרָחַץ", "וירחץ'", "and bathe"),
        ("אֶת-בְּשָׂרוֹ", "בדנה", "his body"),
        ("בַּמָּיִם", "באלמא", "with water"),
        ("וְאַחֲרֵי-כֵן", "ובעד ד'אלך", "and after that"),
        ("יָבוֹא", "ידכ'ל", "he shall enter"),
        ("אֶל-הַמַּחֲנֶה", "אלי' אלעסכר", "the camp"),
    ],
    29: [
        ("וְהָיְתָה לָכֶם", "פיכון ד'אלך לכם", "And this shall be for you"),
        ("לְחֻקַּת עוֹלָם", "רסם אלדהר", "a perpetual ordinance"),
        ("בֶּעָשׂוֹר לַחֹדֶשׁ", "פי אליום אלעאשר", "on the tenth day"),
        ("בַּחֹדֶשׁ הַשְּׁבִיעִי", "מן אלשהר אלסאבע", "of the seventh month"),
        ("תְּעַנּוּ", "תגיעו", "you shall afflict"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "yourselves"),
        ("וְכָל-מְלָאכָה", "ושיי מן אלאעמאל", "and no work whatsoever"),
        ("לֹא תַעֲשׂוּ", "לא תעמלו", "shall you do"),
        ("הָאֶזְרָח", "אלצריח", "the native-born"),
        ("וְהַגֵּר הַגָּר", "ואלג'ריב אלדכ'יל", "and the stranger who sojourns"),
        ("בְּתוֹכְכֶם", "פי מא בינכם", "among you"),
    ],
    30: [
        ("כִּי-בַיּוֹם הַזֶּה", "ופי הדא אליום", "For on this day"),
        ("יְכַפֵּר עֲלֵיכֶם", "יסתג'פר ענכם", "he shall seek forgiveness for you"),
        ("לְטַהֵר אֶתְכֶם", "ליטהרכם", "to purify you"),
        (None, "כמא ביינת", "as I have declared"),
        ("מִכֹּל חַטֹּאתֵיכֶם", "פמן גמיע כ'טאיאכם", "from all your sins"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God"),
        ("תִּטְהָרוּ", "תטהרון", "you shall be purified"),
    ],
    31: [
        ("שַׁבַּת שַׁבָּתוֹן", "וסבת הי עטלה", "And it is a Sabbath — a complete rest"),
        ("לָכֶם", "לכם", "for you"),
        ("וְעִנִּיתֶם", "תגיעון", "you afflict"),
        ("אֶת-נַפְשֹׁתֵיכֶם", "אנפסכם", "yourselves"),
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "a perpetual ordinance."),
        (None, "אד'", "when"),
    ],
    32: [
        ("וְכִפֶּר", "יסתג'פר", "seek forgiveness;"),
        ("הַכֹּהֵן", "אלאמאם", "the imām"),
        ("אֲשֶׁר-יִמְשַׁח אֹתוֹ", "אלד'י ימסח", "who is anointed"),
        ("וַאֲשֶׁר יְמַלֵּא אֶת-יָדוֹ", "ויכמל ואגבה", "and completes his obligation"),
        ("לְכַהֵן", "ליאם", "to officiate"),
        ("תַּחַת אָבִיו", "מכאן אביה", "in place of his father"),
        (None, "וכד'אלך", "And likewise"),
        ("וְלָבַשׁ", "פלילבס", "and he shall put on"),
        ("אֶת-בִּגְדֵי הַבָּד", "ת'יאב אלעשר", "the garments of fine linen"),
        ("בִּגְדֵי הַקֹּדֶשׁ", "ת'יאב אלקדס", "the garments of the sanctuary"),
    ],
    33: [
        ("וְכִפֶּר", "ויסתג'פר", "And he shall seek forgiveness"),
        ("אֶת-מִקְדַּשׁ הַקֹּדֶשׁ", "פי כ'ואץ' אלאקדאס", "in the innermost of the sanctuaries"),
        ("וְאֶת-אֹהֶל מוֹעֵד", "ופי כ'בא אלמחצ'ר", "and in the tent of the assembly"),
        ("וְאֶת-הַמִּזְבֵּחַ", "וענד אלמד'בח", "and at the altar"),
        ("יְכַפֵּר", "יסתג'פר פיהא", "he shall seek forgiveness therein"),
        ("וְעַל הַכֹּהֲנִים", "ען אלאימה", "for the imāms"),
        ("וְעַל-כָּל-עַם הַקָּהָל", "וען סאיר אלגוק", "and for the rest of the assembly"),
    ],
    34: [
        ("וְהָיְתָה-זֹּאת לָכֶם", "פתכון הדה לכם", "And this shall be for you"),
        ("לְחֻקַּת עוֹלָם", "רסם אלדהר", "a perpetual ordinance"),
        ("לְכַפֵּר", "אן יסתג'פר", "that forgiveness be sought"),
        (None, "כד'אך", "thus"),
        ("עַל-בְּנֵי יִשְׂרָאֵל", "ען בני אסראיל", "for the sons of Israel"),
        ("מִכָּל-חַטֹּאתָם", "מן גמיע כ'טאיאהם", "from all their sins"),
        ("אַחַת בַּשָּׁנָה", "מרה ואחדה פי אלסנה", "once a year"),
        ("וַיַּעַשׂ", "פצנע", "And he did"),
        ("כַּאֲשֶׁר צִוָּה", "כמא אמר", "as"),
        ("יְהוָה", "אללה", "God had commanded"),
        ("אֶת-מֹשֶׁה", "מוסי'", "Moses"),
    ],
}
