"""Hand-authored alignment triples for Vayikra chapter 27.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings. Words Saadia adds with no Hebrew source carry he=None and link
JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "מוסי", "to Moses"),
        ("לֵּאמֹר", "תכלימא", "in [divine] speech"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        (None, "אי", "any"),
        ("אִישׁ", "אנסאן", "person"),
        ("כִּי יַפְלִא", "סווג'", "who has vowed"),
        (None, "נד'רא", "a vow"),
        ("נְפָשֹׁת", "מן אלנפוס", "of souls"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    3: [
        ("וְהָיָה עֶרְכְּךָ הַזָּכָר", "פיכון קימה' אלדכר", "the valuation of the male"),
        ("מִבֶּן עֶשְׂרִים שָׁנָה", "מן אבן עשרין סנה", "from twenty years of age"),
        ("וְעַד בֶּן-שִׁשִּׁים שָׁנָה", "ואלי' אבן סתין סנה", "to sixty years of age"),
        ("וְהָיָה עֶרְכְּךָ", "פליכון קימתה", "shall be"),
        ("חֲמִשִּׁים", "כ'מסין", "fifty"),
        ("שֶׁקֶל", "מת'קאל", "mithqals"),
        ("כֶּסֶף", "פצ'ה", "of silver"),
        ("בְּשֶׁקֶל הַקֹּדֶשׁ", "במת'קאל אלקדס", "by the mithqal of the sanctuary"),
    ],
    4: [
        ("וְאִם", "ואן", "and if"),
        ("נְקֵבָה", "כאנת אנת'א", "it be a female"),
        (None, "פקימתהא", "her valuation shall be"),
        ("שְׁלֹשִׁים", "ת'לאת'ין", "thirty"),
    ],
    5: [
        ("וְאִם", "ואן", "and if"),
        (None, "כאן", "it be"),
        ("מִבֶּן-חָמֵשׁ", "מן אבן כ'מס", "from five"),
        ("שָׁנִים", "סנין", "years of age"),
        ("וְעַד", "ואלי'", "to"),
        ("בֶּן-עֶשְׂרִים", "אבן עשרין", "twenty"),
        ("שָׁנָה", "סנה", "years of age"),
        (None, "פקימה'", "the valuation of"),
        ("הַזָּכָר", "אלד'כר", "the male"),
        ("עֶשְׂרִים", "עשרין", "shall be twenty"),
        ("שְׁקָלִים", "מת'קאל", "mithqals"),
        ("וְלַנְּקֵבָה", "ואלאנת'א", "and the female"),
        ("עֲשֶׂרֶת", "עשרה", "ten"),
    ],
    6: [
        ("וְאִם", "ואן", "and if"),
        (None, "כאן", "it be"),
        ("מִבֶּן-חֹדֶשׁ", "מן אבן שהר", "from one month of age"),
        ("וְעַד", "ואלי'", "to"),
        ("בֶּן-חָמֵשׁ", "אבן כ'מס", "five"),
        ("שָׁנִים", "סנין", "years of age"),
        (None, "פקימה'", "the valuation of"),
        ("הַזָּכָר", "אלד'כר", "the male"),
        ("חֲמִשָּׁה", "כ'מסה", "shall be five"),
        ("שְׁקָלִים", "מת'אקיל", "mithqals of"),
        ("כָּסֶף", "פצ'ה", "silver"),
        ("וְלַנְּקֵבָה", "ואלאנת'א", "and the female"),
        ("שְׁלֹשֶׁת", "ת'לאת'ה", "three"),
    ],
    7: [
        ("וְאִם מִבֶּן-שִׁשִּׁים שָׁנָה", "ואן כאן מן אבן סתין סנה", "and if it be from sixty years of age"),
        ("וָמַעְלָה", "פצאעדא", "and upward"),
        ("אִם-זָכָר", "פקימה' אלד'כר", "the valuation of the male"),
        ("חֲמִשָּׁה עָשָׂר", "כ'מסה' עשר", "shall be fifteen"),
        ("שָׁקֶל", "מת'קאל", "mithqals"),
        ("וְלַנְּקֵבָה", "ואלאנת'א", "and the female"),
        ("עֲשָׂרָה", "עשרה", "ten"),
    ],
    8: [
        ("וְאִם-מָךְ הוּא", "ואן כאן מהינא", "and if he be too lowly"),
        ("מֵעֶרְכֶּךָ", "מן אלקימה", "for the valuation"),
        (None, "פליוקף", "he shall stand"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("הַכֹּהֵן", "אלאמאם", "the imām,"),
        ("וְהֶעֱרִיךְ אֹתוֹ הַכֹּהֵן", "ויקימה", "and the imām shall value him"),
        (None, "חסב", "according to"),
        ("עַל-פִּי אֲשֶׁר תַּשִּׂיג יַד הַנֹּדֵר", "מא תנאל יד אלנאד'ר", "what the hand of the one who vowed"),
        ("יַעֲרִיכֶנּוּ הַכֹּהֵן", "כד'אך יקימה אלאמאם", "thus shall the imām value him"),
    ],
    9: [
        ("וְאִם-בְּהֵמָה", "ואן כאנת בהימה", "And if it be a beast"),
        (None, "יצלח אן", "from which"),
        ("אֲשֶׁר יַקְרִיבוּ מִמֶּנָּה קָרְבָּן לַיהוָה", "יקרב מנהא קרבאנא ללה", "an offering may be brought near to God"),
        (None, "פכל מא יגעל מן ד'אלך", "then everything they designate of it"),
        ("כֹּל אֲשֶׁר יִתֵּן מִמֶּנּוּ לַיהוָה", "ללה", "for God"),
        ("יִהְיֶה-קֹּדֶשׁ", "יכון קדסא בעינה", "shall itself be sacred"),
    ],
    10: [
        ("לֹא יַחֲלִיפֶנּוּ", "לא יבדלה", "He shall not exchange it"),
        ("וְלֹא-יָמִיר", "ולא יג'יירה", "nor substitute it"),
        ("טוֹב", "גייד", "good"),
        ("בְּרָע", "ברדי", "for inferior"),
        ("אוֹ-רַע", "ולא רדי", "nor inferior"),
        ("בְּטוֹב", "בגייד", "for good"),
        ("וְאִם-הָמֵר יָמִיר", "פאן ג'ייר", "and if he does substitute"),
        ("בְּהֵמָה", "בהימה", "one beast"),
        ("בִּבְהֵמָה", "בבהימה", "for another"),
        (None, "פקד צאר", "then both"),
        ("וְהָיָה-הוּא", "הו", "it"),
        ("וּתְמוּרָתוֹ", "ובדילה", "and its substitute"),
        ("יִהְיֶה-קֹּדֶשׁ", "קדסא", "shall become sacred"),
    ],
    11: [
        ("וְאִם כָּל-בְּהֵמָה טְמֵאָה", "ואן כאנת בהימה נגסה", "And if it be an impure beast"),
        ("אֲשֶׁר לֹא-יַקְרִיבוּ מִמֶּנָּה קָרְבָּן לַיהוָה", "או מא לא יקרב מנהא. קרבאנא ללה", "or one from which no offering may be brought near to God"),
        (None, "פלתוקף", "it shall be set"),
        ("וְהֶעֱמִיד אֶת-הַבְּהֵמָה לִפְנֵי הַכֹּהֵן", "בין ידי אלאמאם", "before the imām"),
    ],
    12: [
        ("וְהֶעֱרִיךְ הַכֹּהֵן אֹתָהּ", "פיקימהא אלאמאם", "and the imām shall value it"),
        ("בֵּין טוֹב", "עלי' קדר גודתהא", "according to its quality,"),
        ("וּבֵין רָע", "או רדאתהא", "whether good or inferior"),
        (None, "פליכון", "so shall it be"),
        ("כְּעֶרְכְּךָ הַכֹּהֵן כֵּן יִהְיֶה", "אלואגב כמא קים אלאמאם", "obligatory."),
    ],
    13: [
        ("וְאִם-גָּאֹל יִגְאָלֶנָּה", "פאן שא פכאכהא", "And if he wishes to redeem it"),
        (None, "פליזיד", "he shall add"),
        ("חֲמִישִׁתוֹ", "עלי' אלקימה כמסהא", "a fifth of the valuation to it"),
    ],
    14: [
        ("וְאִישׁ כִּי-יַקְדִּשׁ", "ואי רגל אקדס", "And whatever man consecrates"),
        ("אֶת-בֵּיתוֹ", "ביתה", "his house"),
        ("קֹדֶשׁ", "קדסא", "as sacred"),
        ("לַיהוָה", "ללה", "to God,"),
        ("וְהֶעֱרִיכוֹ הַכֹּהֵן", "פליקימה אלאמאם", "the imām shall value it"),
        ("בֵּין טוֹב", "עלי גודתה", "according to its quality,"),
        ("וּבֵין רָע", "או רדאתה", "whether good or inferior"),
        ("כַּאֲשֶׁר יַעֲרִיךְ אֹתוֹ הַכֹּהֵן כֵּן יָקוּם", "כמא יקימה כד'אך יגב", "as he values it, so shall it be obligatory"),
    ],
    15: [
        ("וְאִם-הַמַּקְדִּישׁ", "פאן שא אלמקדס", "And if the one who consecrated it wishes"),
        ("יִגְאַל אֶת-בֵּיתוֹ", "פכאך מנזלה", "to redeem his dwelling"),
        (None, "פליזיד", "he shall add"),
        ("וְיָסַף חֲמִישִׁית כֶּסֶף-עֶרְכְּךָ עָלָיו", "עלי' קימתה כ'מסהא", "a fifth to its valuation"),
        ("וְהָיָה לוֹ", "ויכון לה", "and it shall be his"),
    ],
    16: [
        ("וְאִם מִשְּׂדֵה אֲחֻזָּתוֹ יַקְדִּישׁ אִישׁ לַיהוָה", "ואן אקדס אנסאן ללה שייא מן צ'יעה' חוזה", "And if a person consecrates to God something from the fields of his holding"),
        ("וְהָיָה עֶרְכְּךָ", "פלתכון אלקימה", "the valuation shall be"),
        ("לְפִי זַרְעוֹ", "עלי' קדר בד'רה", "according to the measure of its seed"),
        ("זֶרַע חֹמֶר", "כל מבד'ר", "every unit sown"),
        ("שְׂעֹרִים", "מן שעיר", "of barley"),
        ("בַּחֲמִשִּׁים", "בכ'מסין", "at fifty"),
        ("שֶׁקֶל", "מתקאל", "mithqals"),
        ("כָּסֶף", "פצ'ה", "of silver"),
    ],
    17: [
        ("אִם-מִשְּׁנַת הַיֹּבֵל יַקְדִּישׁ שָׂדֵהוּ", "פאן אקדס צ'יעתה מן סנה' אלאטלאק", "And if he consecrates his field from the year of release"),
        ("כְּעֶרְכְּךָ יָקוּם", "פאלקימה ת'אבתה בחאלהא", "the valuation shall remain fixed as it is"),
    ],
    18: [
        ("וְאִם-אַחַר הַיֹּבֵל יַקְדִּישׁ שָׂדֵהוּ", "ואן אקדסהא בעד סנה' אלאטלאק", "But if he consecrates it after the year of release"),
        ("וְחִשַּׁב-לוֹ הַכֹּהֵן", "פליחסב לה אלאמאם", "the imām shall reckon for him"),
        ("אֶת-הַכֶּסֶף", "אלדראהם", "the silver"),
        ("עַל-פִּי הַשָּׁנִים הַנּוֹתָרֹת", "עלי' קדר אלסנין אלבאקיאת", "according to the number of years remaining"),
        ("עַד שְׁנַת הַיֹּבֵל", "אלי' סנה' אלאטלאק", "until the year of release"),
        ("וְנִגְרַע", "וינקץ", "and it shall be deducted"),
        ("מֵעֶרְכֶּךָ", "מן אלקימה", "from the full valuation"),
    ],
    19: [
        ("וְאִם-גָּאֹל יִגְאַל אֶת-הַשָּׂדֶה הַמַּקְדִּישׁ אֹתוֹ", "ואן שא אלרגל אלמקדס אלצ'יעה אן יפתכהא", "And if the man who consecrated the field wishes to redeem it"),
        (None, "פליזיד", "he shall add"),
        ("וְיָסַף חֲמִשִׁית כֶּסֶף-עֶרְכְּךָ עָלָיו", "עלי' אלקימה כ'מסהא", "a fifth to the valuation"),
        ("וְקָם לוֹ", "ותגב לה", "and it shall be secured to him"),
    ],
    20: [
        ("וְאִם-לֹא יִגְאַל אֶת-הַשָּׂדֶה", "ואן לם יפתכהא", "But if he does not redeem it"),
        ("וְאִם-מָכַר אֶת-הַשָּׂדֶה", "ובאעהא אלאמין", "and the trustee has sold it"),
        ("לְאִישׁ אַחֵר", "לרגל אכ'ר", "to another man"),
        ("לֹא יִגָּאֵל עוֹד", "פלא תפתך אבדא", "it shall not be redeemed ever"),
    ],
    21: [
        ("וְהָיָה", "ותכון", "And it shall be"),
        ("הַשָּׂדֶה", "ענד כ'רוגהא", "upon its passing out"),
        ("בְּצֵאתוֹ", "מן יד אלמשתרי", "of the purchaser's hand"),
        ("בַיֹּבֵל", "פי סנה' אלאטלאק", "in the year of release"),
        ("קֹדֶשׁ", "קדסא", "sacred"),
        ("לַיהוָה", "ללה", "to God"),
        ("כִּשְׂדֵה הַחֵרֶם", "כצ'יאע אלצואפי", "like the lands of the endowments irrevocably devoted"),
        ("לַכֹּהֵן", "לאלאמאם", "the imām's"),
        ("תִּהְיֶה", "ותציר", "and it shall become"),
    ],
    22: [
        ("וְאִם", "ואן", "And if"),
        ("יַקְדִּישׁ", "אקדס", "consecrates"),
        ("אֶת-שְׂדֵה מִקְנָתוֹ", "צ'יעה אשתראהא", "a field he has purchased"),
        ("אֲשֶׁר לֹא", "וליסת", "which is not"),
        ("מִשְּׂדֵה אֲחֻזָּתוֹ", "לה בחוז", "his by right of holding"),
    ],
    23: [
        ("וְחִשַּׁב-לוֹ הַכֹּהֵן", "פליחסב לה אלאמאם", "the imām shall reckon for him"),
        ("אֵת מִכְסַת הָעֶרְכְּךָ", "תקסיט אלקימה", "the installments of the valuation"),
        ("עַד שְׁנַת הַיֹּבֵל", "מן סנתה אלי' סנה' אלאטלאק", "from its year until the year of release"),
        ("וְנָתַן אֶת-הָעֶרְכְּךָ", "וידפעהא", "and he shall pay it"),
        ("בַּיּוֹם הַהוּא", "פי ד'אלך אליום", "on that day"),
        ("קֹדֶשׁ", "קדסא", "as sacred"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    24: [
        ("בִּשְׁנַת הַיּוֹבֵל", "ותרגע אלצ'יעה פי סנה' אלאטלאק", "And the field shall revert in the year of release"),
        ("יָשׁוּב הַשָּׂדֶה", "לאלבאיע", "to the seller"),
        ("לַאֲשֶׁר קָנָהוּ מֵאִתּוֹ", "אלד'י אשתראהא מנה", "from whom he purchased it"),
        ("לַאֲשֶׁר-לוֹ אֲחֻזַּת הָאָרֶץ", "אלד'י לה רקבה' אלארץ'", "to the one who holds title to the land"),
    ],
    25: [
        ("וְכָל", "וגמיע", "And all"),
        ("עֶרְכְּךָ", "קימתך", "your valuations"),
        (None, "תכון", "shall be"),
        ("בְּשֶׁקֶל הַקֹּדֶשׁ", "במת'קאל אלקדס", "by the mithqal of the sanctuary"),
        ("עֶשְׂרִים", "כל מת'קאל עשרין", "every mithqal being twenty"),
        ("גֵּרָה", "דאנק", "dāniqs"),
    ],
    26: [
        ("אַךְ-בְּכוֹר", "אמא בכר", "As for a firstborn animal"),
        ("אֲשֶׁר-יְבֻכַּר לַיהוָה בִּבְהֵמָה", "יבכר ללה מן אלבהאים", "that is made firstborn to God from among the beasts,"),
        ("לֹא-יַקְדִּישׁ אִישׁ אֹתוֹ", "פלא יחתאג אן יקדסה אנסאנא", "a person need not consecrate it"),
        ("אִם-שׁוֹר", "אן כאן מן אלבקר", "whether it be from the cattle"),
        ("אִם-שֶׂה", "או מן אלג'נם", "or from the flock"),
        ("לַיהוָה", "פהו ללה", "it already belongs to God"),
    ],
    27: [
        ("וְאִם", "ואן", "And if"),
        ("בַּבְּהֵמָה הַטְּמֵאָה", "אקדס שייא מן אלבהאים אלנגסה", "one consecrates something from the impure beasts"),
        ("וּפָדָה", "פליפדהא", "he shall redeem it"),
        ("בְעֶרְכֶּךָ", "בקימתה", "at its valuation"),
        ("וְיָסַף", "ויזיד", "and add"),
        ("חֲמִשִׁתוֹ", "עליהא כ'מסהא", "a fifth to it"),
        ("וְאִם-לֹא", "ואן לם", "and if he does not"),
        ("יִגָּאֵל", "יפתכה", "redeem it"),
        (None, "פליבאע", "it shall be sold"),
        ("וְנִמְכַּר", "בקימתה", "at its valuation"),
    ],
    28: [
        ("אַךְ-כָּל-חֵרֶם", "ואמא כל צואף", "But every irrevocable devotion"),
        ("אֲשֶׁר יַחֲרִם אִישׁ לַיהוָה", "יגעלה אלאנסאן ללה", "that a person makes to God"),
        ("מִכָּל-אֲשֶׁר-לוֹ", "מן גמיע מאלה", "from all that he has"),
        ("מֵאָדָם", "מן עביד", "whether slaves"),
        ("וּבְהֵמָה", "ובהאים", "or beasts"),
        ("וּמִשְּׂדֵה אֲחֻזָּתוֹ", "וצ'יעה' חוזה", "or the fields of his holding"),
        ("לֹא יִמָּכֵר", "פלא יבאע", "shall not be sold"),
        ("וְלֹא יִגָּאֵל", "ולא יפתך", "and shall not be redeemed"),
        (None, "בל", "it shall be"),
        ("קֹדֶשׁ-קָדָשִׁים הוּא לַיהוָה", "יכון מן כ'ואץ אלאקדאס ללה", "of the most sacred consecrations to God"),
    ],
    29: [
        ("כָּל-חֵרֶם אֲשֶׁר יָחֳרַם מִן-הָאָדָם", "וכל מתלוף אסתחק אלתלף. מן אלנאס", "And every person condemned to destruction who has deserved destruction"),
        ("לֹא יִפָּדֶה", "פלא יפדא", "shall not be redeemed"),
        (None, "בל", "he shall be"),
        ("מוֹת יוּמָת", "יקתל קתלא", "put to death"),
    ],
    30: [
        ("וְכָל-מַעְשַׂר", "וגמיע עשור", "And all the tithes of"),
        ("הָאָרֶץ", "אלארץ'", "the land"),
        ("מִזֶּרַע הָאָרֶץ", "מן חבהא", "from its grain"),
        ("מִפְּרִי הָעֵץ", "ומן ת'מר אלשגר", "and from the fruit of the tree"),
        ("לַיהוָה", "פהו ללה", "they belong to God"),
        ("הוּא קֹדֶשׁ לַיהוָה", "קדסא", "as sacred"),
    ],
    31: [
        ("וְאִם", "פאן", "And if"),
        ("גָּאֹל יִגְאַל", "אפתך", "redeems"),
        ("אִישׁ", "אנסאן", "a person"),
        ("מִמַּעַשְׂרוֹ", "שייא מן עשורה", "any of his tithe"),
        (None, "פליזיד", "he shall add"),
        ("חֲמִשִׁיתוֹ", "כ'מס", "a fifth of"),
        ("עָלָיו", "ת'מנה", "its value to it"),
    ],
    32: [
        ("וְכָל-מַעְשַׂר", "וגמיע עשור", "And all the tithes of"),
        ("בָּקָר", "אלבקר", "cattle"),
        ("וָצֹאן", "ואלג'נם", "and of the flock"),
        ("כֹּל אֲשֶׁר-יַעֲבֹר", "מא יגוז", "whatever passes"),
        ("תַּחַת הַשָּׁבֶט", "תחת אלעצא", "under the staff"),
        ("הָעֲשִׂירִי", "פאלעאשר", "the tenth"),
        (None, "יכון", "shall be"),
        ("יִהְיֶה-קֹּדֶשׁ", "קדסא", "sacred"),
        ("לַיהוָה", "ללה", "to God"),
    ],
    33: [
        ("לֹא יְבַקֵּר", "לא יפחץ", "He shall not examine it"),
        (None, "ענה", "as between"),
        ("בֵּין-טוֹב", "בין גייד", "good"),
        ("לָרַע", "לרדי", "and inferior"),
        ("וְלֹא יְמִירֶנּוּ", "ולא יג'יירה", "nor shall he substitute it"),
        ("וְאִם-הָמֵר יְמִירֶנּוּ", "פאן ג'יירה", "and if he does substitute it"),
        (None, "פקד צאר", "then both"),
        ("וְהָיָה-הוּא", "הו", "it"),
        ("וּתְמוּרָתוֹ", "ובדילה", "and its substitute"),
        ("יִהְיֶה-קֹּדֶשׁ", "קדסא", "shall become sacred"),
        ("לֹא יִגָּאֵל", "לא יפתך", "and shall not be redeemed"),
    ],
    34: [
        ("אֵלֶּה", "הד'ה", "These are"),
        ("הַמִּצְו‍ֹת", "אלוצאיא", "the commandments"),
        ("אֲשֶׁר", "אלתי", "which"),
        ("צִוָּה", "אמר", "charged"),
        ("יְהוָה", "אללה", "God"),
        ("אֶת-מֹשֶׁה", "בהא מוסי", "Moses with"),
        ("אֶל-בְּנֵי", "אלי' בני", "to the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("בְּהַר", "פי גבל", "at Mount"),
        ("סִינָי", "סיני", "Sinai"),
    ],
}
