"""Hand-authored alignment triples for Vayikra chapter 10.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions ("כלם אללה" ↔ "God spoke"), English-fronted
negations, and Hebrew construct reorderings. Words Saadia adds with no Hebrew
source (glosses, expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיִּקְחוּ", "אכ'ד'", "took"),
        ("בְנֵי-אַהֲרֹן", "בני הרון", "the sons of Aaron"),
        ("נָדָב", "נדב", "Nadab"),
        ("וַאֲבִיהוּא", "ואביהוא", "and Abihu"),
        ("אִישׁ", "כל ואחד", "each"),
        ("מַחְתָּתוֹ", "מגמרה", "his fire-pan,"),
        ("וַיִּתְּנוּ", "וגעלא", "and placed"),
        ("בָהֵן", "פיהמא", "in them"),
        ("אֵשׁ", "נארא", "fire"),
        ("וַיָּשִׂימוּ", "וציירא", "and set"),
        ("עָלֶיהָ", "עלי'המא", "upon them"),
        ("קְטֹרֶת", "בכ'ורא", "incense"),
        ("וַיַּקְרִיבוּ", "וקרבא", "and brought"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
        ("אֵשׁ", "נארא", "fire"),
        ("זָרָה", "ג'ריבא", "strange"),
        ("אֲשֶׁר לֹא", "מא לם", "which He had not"),
        ("צִוָּה", "יאמרהם", "commanded"),
        ("אֹתָם", "בהא", "them"),
    ],
    2: [
        ("וַתֵּצֵא", "פכ'רגת", "went forth"),
        ("אֵשׁ", "נאר", "fire"),
        ("מִלִּפְנֵי", "מן ענד", "from before"),
        ("יְהוָה", "אללה", "God"),
        ("וַתֹּאכַל", "פאכלתהמא", "and consumed them,"),
        ("וַיָּמֻתוּ", "ומאתא", "and they died"),
        ("לִפְנֵי", "בין ידי", "before"),
        ("יְהוָה", "אללה", "God"),
    ],
    3: [
        ("וַיֹּאמֶר", "פקאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("הוּא", "הו", "This is"),
        ("אֲשֶׁר-דִּבֶּר", "מא קאל", "what"),
        ("יְהוָה", "אללה", "God said"),
        (None, "אני", "—"),
        ("אֶקָּדֵשׁ", "את עצ'ם", "I shall be exalted"),
        ("בִּקְרֹבַי", "באלמקרבין אליי", "through those who draw near to Me,"),
        ("וְעַל-פְּנֵי", "ובחצ'רה'", "and in the presence of"),
        ("כָל-הָעָם", "גמיע אלקום", "all the people"),
        ("אֶכָּבֵד", "אתקדס", "I shall be honored.'"),
        ("וַיִּדֹּם", "פסכת", "was silent."),
        ("אַהֲרֹן", "הרון", "And Aaron"),
    ],
    4: [
        (None, "ת'ם", "Then"),
        ("וַיִּקְרָא", "דעא", "called"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-מִישָׁאֵל", "במישאל", "Mishael"),
        ("וְאֶל אֶלְצָפָן", "ואלצפן", "and Elzaphan,"),
        ("בְּנֵי עֻזִּיאֵל", "בני עזיאל", "sons of Uzziel"),
        ("דֹּד אַהֲרֹן", "עם הרון", "the uncle of Aaron,"),
        ("וַיֹּאמֶר", "פקאל", "and said"),
        ("אֲלֵהֶם", "להמא", "to them:"),
        ("קִרְבוּ", "תקדמא", "Come forward,"),
        ("שְׂאוּ", "אחמלא", "carry"),
        ("אֶת-אֲחֵיכֶם", "אכ'ותכמא", "your brothers"),
        ("מֵאֵת פְּנֵי-הַקֹּדֶשׁ", "מן בין ידי אלקדס", "from before the sanctuary"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "to outside the camp.'"),
    ],
    5: [
        ("וַיִּקְרְבוּ", "פתקדמא", "And they came forward"),
        ("וַיִּשָּׂאֻם", "וחמלאהמא", "and carried them"),
        ("בְּכֻתֳּנֹתָם", "בתואניהמא", "in their tunics"),
        ("אֶל-מִחוּץ לַמַּחֲנֶה", "אלי' כ'ארג אלעסכר", "to outside the camp,"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("דִּבֶּר", "אמר", "had commanded."),
        ("מֹשֶׁה", "מוסי'", "Moses"),
    ],
    6: [
        ("וַיֹּאמֶר", "וקאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron,"),
        ("וּלְאֶלְעָזָר", "ולאלעזר", "and to Eleazar"),
        ("וּלְאִיתָמָר", "ולאיתמר", "and Ithamar"),
        ("בָּנָיו", "בניה", "his sons:"),
        ("רָאשֵׁיכֶם", "רוסכם", "your heads,"),
        ("אַל-תִּפְרָעוּ", "לא תשעתו", "'Do not dishevel"),
        ("לֹא-תִפְרֹמוּ", "לא תמזקו", "do not tear"),
        ("וּבִגְדֵיכֶם", "ות'יאבכם", "your garments,"),
        ("וְלֹא תָמֻתוּ", "ולא תהלכו", "lest you perish —"),
        ("וְעַל כָּל-הָעֵדָה", "ועלי' גמיע אלגמע", "and upon all the congregation"),
        ("יִקְצֹף", "יכון סכ'ט", "there shall be wrath."),
        ("וַאֲחֵיכֶם", "ואכ'ותכם", "And your brothers,"),
        ("כָּל-בֵּית יִשְׂרָאֵל", "גמיע בני אסראיל", "all the sons of Israel,"),
        ("יִבְכּוּ", "יבכון", "shall weep"),
        ("אֶת-הַשְּׂרֵפָה", "עלי' אלחריק", "over the burning"),
        ("אֲשֶׁר שָׂרַף", "אלד'י אחרקה", "which"),
        ("יְהוָה", "אללה", "God has struck.'"),
    ],
    7: [
        ("וּמִפֶּתַח", "ומן באב", "And from the entrance of"),
        ("אֹהֶל מוֹעֵד", "כ'בא אלמחצ'ר", "the tent of the assembly"),
        ("לֹא תֵצְאוּ", "לא תכ'רגו", "you shall not go out,"),
        ("פֶּן-תָּמֻתוּ", "ללא תהלכו", "lest you perish —"),
        (None, "לאן", "for"),
        ("כִּי-שֶׁמֶן", "דהן", "oil of"),
        ("מִשְׁחַת", "מסוחייה'", "the anointing"),
        ("יְהוָה", "אללה", "God"),
        ("עֲלֵיכֶם", "עלי'כם", "is upon you.'"),
        ("וַיַּעֲשׂוּ", "פעמלו", "And they did"),
        ("כִּדְבַר", "כמא", "as"),
        ("מֹשֶׁה", "אמר מוסי'", "Moses commanded."),
    ],
    8: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "כלם", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-אַהֲרֹן", "הרון", "to Aaron"),
        ("לֵאמֹר", "תכלימא", "directly."),
    ],
    9: [
        ("יַיִן", "כ'מר", "'Wine"),
        ("וְשֵׁכָר", "ומסכר", "and strong drink"),
        ("אַל-תֵּשְׁתְּ", "לא תשרב", "you shall not drink —"),
        ("אַתָּה", "אנת", "you"),
        ("וּבָנֶיךָ", "ובניך", "and your sons"),
        ("אִתָּךְ", "מעך", "with you —"),
        ("בְּבֹאֲכֶם", "פי דכולכם", "when you enter"),
        ("אֶל-אֹהֶל מוֹעֵד", "אלי' כ'בא אלמחצ'ר", "the tent of the assembly,"),
        ("וְלֹא תָמֻתוּ", "ולא תהלכו", "lest you perish."),
        ("חֻקַּת עוֹלָם", "רסם אלדהר", "A statute forever,"),
        ("לְדֹרֹתֵיכֶם", "עלי' מר אגיאלכם", "throughout your generations.'"),
    ],
    10: [
        ("וּלְהַבְדִּיל", "ולתפצלו", "'And that you may separate"),
        ("בֵּין הַקֹּדֶשׁ", "בין אלקדס", "between the sacred"),
        ("וּבֵין הַחֹל", "ואלבד'ל", "and the profane,"),
        ("וּבֵין הַטָּמֵא", "ואלטאהר", "and between the clean"),
        ("וּבֵין הַטָּהוֹר", "ואלנגס", "and the unclean;'"),
    ],
    11: [
        ("וּלְהוֹרֹת", "ולתפתון", "'and that you may give rulings"),
        ("אֶת-בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "to the sons of Israel"),
        ("אֵת כָּל-הַחֻקִּים", "בגמיע אלרסום", "in all the statutes"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("דִּבֶּר", "אמר", "commanded"),
        ("יְהוָה", "אללה", "God"),
        ("אֲלֵיהֶם", "בהא", "through"),
        ("בְּיַד-מֹשֶׁה", "עלי' יד מוסי'", "Moses.'"),
    ],
    12: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "קאל", "said"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("אֶל-אַהֲרֹן", "להרון", "to Aaron"),
        ("קְחוּ", "כ'דו", "Take"),
        ("אֶת-הַמִּנְחָה", "אלהדייה", "the gift"),
        ("הַנּוֹתֶרֶת", "אלפאצ'לה", "remaining"),
        ("מֵאִשֵּׁי יְהוָה", "מן קראבין אללה", "from the offerings of God,"),
        ("וְאִכְלוּהָ", "וכלוהא", "and eat it"),
        ("מַצּוֹת", "פטירא", "unleavened"),
        ("אֵצֶל הַמִּזְבֵּחַ", "לזק אלמד'בח", "beside the altar,"),
        ("כִּי", "לאנהא", "for it is"),
        ("קֹדֶשׁ קָדָשִׁים הִוא", "מן כ'ואץ אלאקדאס", "from among the choicest of the sacred things.'"),
    ],
    13: [
        (None, "וגאיז", "'And it is permitted"),
        (None, "אן", "that"),
        ("וַאֲכַלְתֶּם", "תאכלוהא", "you eat it"),
        ("בְּמָקוֹם קָדוֹשׁ", "פי מוצ'ע מקדס", "in a consecrated place,"),
        ("כִּי", "אד'", "for"),
        ("חָקְךָ", "הי רזקך", "it is your provision"),
        ("וְחָק-בָּנֶיךָ", "ורזק בניך", "and the provision of your sons,"),
        ("הִוא", "מן", "from"),
        ("מֵאִשֵּׁי יְהוָה", "קראבין אללה", "the offerings of God —"),
        ("כִּי-כֵן", "לאן כד'א", "for thus"),
        ("צֻוֵּיתִי", "אמרת", "was I commanded.'"),
    ],
    14: [
        (None, "ואמא", "'And"),
        ("וְאֵת חֲזֵה הַתְּנוּפָה", "קץ אלתחריך", "the portion of the waving"),
        ("וְאֵת שׁוֹק הַתְּרוּמָה", "וסאק אלרפיעה", "and the leg of the elevation-offering —"),
        ("תֹּאכְלוּ", "פכלוהמא", "eat them"),
        ("בְּמָקוֹם טָהוֹר", "פי מוצ'ע טאהר", "in a clean place,"),
        ("אַתָּה", "אנת", "you"),
        ("וּבָנֶיךָ", "ובניך", "and your sons"),
        ("וּבְנֹתֶיךָ", "ובנאתך", "and your daughters"),
        ("אִתָּךְ", "מעך", "with you,"),
        ("כִּי-חָקְךָ", "פאנהא רזקך", "for they are your provision"),
        ("וְחָק-בָּנֶיךָ", "ורזק בניך", "and the provision of your sons,"),
        ("נִתְּנוּ", "קד אעטיתמוהא", "given to you"),
        ("מִזִּבְחֵי שַׁלְמֵי", "מן ד'באיח סלאמה'", "from the well-being sacrifices of"),
        ("בְּנֵי יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel.'"),
    ],
    15: [
        ("שׁוֹק הַתְּרוּמָה", "סאק אלרפיעה", "'The leg of the elevation-offering"),
        ("וַחֲזֵה הַתְּנוּפָה", "וקץ אלתחריך", "and the portion of the waving"),
        ("עַל אִשֵּׁי הַחֲלָבִים", "מע קראבין אלשחום", "shall come together with the fat offerings —"),
        ("יָבִיאוּ", "יאתו בהא", "they shall"),
        ("לְהָנִיף", "פיחרכהא", "wave them"),
        ("תְּנוּפָה", "תחריכא", "as a waving"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God;"),
        ("וְהָיָה לְךָ", "פתכון לך", "and it shall be for you"),
        ("וּלְבָנֶיךָ", "ולבניך", "and your sons"),
        ("אִתְּךָ", "מעך", "with you"),
        ("לְחָק-עוֹלָם", "רסם אלדהר", "a statute forever,"),
        ("כַּאֲשֶׁר צִוָּה", "כמא אמר", "as"),
        ("יְהוָה", "אללה", "God commanded.'"),
    ],
    16: [
        ("דָּרֹשׁ דָּרַשׁ", "ואלתמס", "sought"),
        ("מֹשֶׁה", "מוסי'", "Moses"),
        ("וְאֵת שְׂעִיר הַחַטָּאת", "עתוד אלדכוה", "the he-goat of the purification-offering"),
        ("וְהִנֵּה", "פאד'אה", "and behold,"),
        ("שֹׂרָף", "קד אחרק", "it had already been burned."),
        ("וַיִּקְצֹף", "פסכ'ט", "And he was angered"),
        ("עַל-אֶלְעָזָר", "עלי' אלעזר", "with Eleazar"),
        ("וְעַל-אִיתָמָר", "ואיתמר", "and Ithamar,"),
        ("בְּנֵי אַהֲרֹן", "בני הרון", "sons of Aaron,"),
        ("הַנּוֹתָרִם", "אלבאקיון", "the remaining"),
        ("לֵאמֹר", "קאילא", "saying:"),
    ],
    17: [
        ("מַדּוּעַ", "מא באלכם", "'What is your concern"),
        ("לֹא-אֲכַלְתֶּם", "לם תאכלו", "that you did not eat"),
        ("אֶת-הַחַטָּאת", "אלדכוה", "the purification-offering"),
        ("בִּמְקוֹם הַקֹּדֶשׁ", "פי מוצ'ע מקדס", "in a consecrated place?"),
        ("כִּי", "לאנהא", "For it is"),
        ("קֹדֶשׁ קָדָשִׁים הִוא", "מן כ'ואץ אלאקדאס", "from among the choicest of the sacred things,"),
        ("וְאֹתָהּ נָתַן", "ואללה קד אעטאכם", "and God has already given it"),
        ("לָכֶם", "איאהא", "to you"),
        ("לָשֵׂאת", "לתחמלו", "so that you may bear"),
        ("אֶת-עֲו‍ֹן הָעֵדָה", "וזר אלגמע", "the burden of the congregation's guilt"),
        ("לְכַפֵּר", "ותסתג'פרו", "and seek forgiveness"),
        ("עֲלֵיהֶם", "ענהם", "for them"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God.'"),
    ],
    18: [
        (None, "ואיצ'א", "'Also,"),
        ("הֵן", "הוד'א", "behold —"),
        ("לֹא-הוּבָא", "לם ידכ'ל", "was brought"),
        (None, "מן", "none of"),
        ("אֶת-דָּמָהּ", "דמהא", "its blood"),
        ("אֶל-הַקֹּדֶשׁ", "אלי' אלקדס", "into"),
        ("פְּנִימָה", "אלגוואני", "the inner sanctuary;"),
        (None, "פקד כאן יגב", "it was therefore obligatory"),
        ("אָכוֹל תֹּאכְלוּ", "אן תאכלוהא", "that you eat it"),
        ("בַּקֹּדֶשׁ", "פי אלקדס", "in the sacred precinct,"),
        ("כַּאֲשֶׁר", "כמא", "as"),
        ("צִוֵּיתִי", "אמרתכם", "I commanded you.'"),
    ],
    19: [
        ("וַיְדַבֵּר", "פקאל", "said"),
        ("אֶל-מֹשֶׁה", "לה", "to him:"),
        ("אַהֲרֹן", "הרון", "And Aaron"),
        ("הֵן", "הוד'א", "'Behold,"),
        ("הַיּוֹם", "אליום", "today"),
        ("הִקְרִיבוּ", "קרבו פיה", "they brought"),
        ("אֶת-חַטָּאתָם", "ד'כותהם", "their purification-offering"),
        ("וְאֶת-עֹלָתָם", "וצעידתהם", "and their burnt-offering"),
        ("לִפְנֵי יְהוָה", "בין ידי אללה", "before God,"),
        ("וַתִּקְרֶאנָה", "וואפתני", "have befallen me"),
        ("אֹתִי כָּאֵלֶּה", "מת'ל הד'ה אלמצאיב", "such calamities as these"),
        ("וְאָכַלְתִּי", "פלו אכלת", "and had I eaten"),
        ("חַטָּאת", "אלדכוה", "the purification-offering"),
        ("הַיּוֹם", "אליום", "today,"),
        ("הַיִּיטַב", "הל כאן ד'אלך חסנא", "would that have been good"),
        ("בְּעֵינֵי יְהוָה", "ענד אללה", "in God's sight?'"),
    ],
    20: [
        ("וַיִּשְׁמַע", "פלמא סמע", "And when Moses heard"),
        ("מֹשֶׁה", "ד'אלך מוסי'", "this,"),
        ("וַיִּיטַב", "חסן", "it seemed good"),
        ("בְּעֵינָיו", "ענדה", "to him."),
    ],
}
