"""Hand-authored alignment triples for Vayikra chapter 10."""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        ("וַיִּקְחוּ בְנֵי-אַהֲרֹן נָדָב וַאֲבִיהוּא אִישׁ מַחְתָּתוֹ",
         "ת'ם אכ'ד' בני הרון. נדב ואביהוא כל ואחד מגמרה",
         "Then the sons of Aaron — Nadab and Abihu — each took his fire-pan,"),
        ("וַיִּתְּנוּ בָהֵן אֵשׁ וַיָּשִׂימוּ עָלֶיהָ קְטֹרֶת",
         "וגעלא פיהמא נארא. וציירא עלי'המא בכ'ורא",
         "and placed fire in them, and set incense upon them,"),
        ("וַיַּקְרִיבוּ לִפְנֵי יְהוָה אֵשׁ זָרָה--אֲשֶׁר לֹא צִוָּה אֹתָם",
         "וקרבא בין ידי אללה נארא ג'ריבא. מא לם יאמרהם בהא",
         "and brought before God a strange fire which He had not commanded them."),
    ],
    2: [
        ("וַתֵּצֵא אֵשׁ מִלִּפְנֵי יְהוָה וַתֹּאכַל אוֹתָם",
         "פכ'רגת נאר מן ענד אללה פאכלתהמא",
         "And fire went forth from before God and consumed them,"),
        ("וַיָּמֻתוּ לִפְנֵי יְהוָה",
         "ומאתא בין ידי אללה",
         "and they died before God."),
    ],
    3: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן הוּא אֲשֶׁר-דִּבֶּר יְהוָה לֵאמֹר",
         "פקאל מוסי' להרון. הו מא קאל אללה",
         "And Moses said to Aaron: 'This is what God said —"),
        ("בִּקְרֹבַי אֶקָּדֵשׁ וְעַל-פְּנֵי כָל-הָעָם אֶכָּבֵד",
         "אני את עצ'ם באלמקרבין אליי ובחצ'רה' גמיע אלקום אתקדס",
         "I shall be exalted through those who draw near to Me, and in the presence of all the people I shall be honored.'"),
        ("וַיִּדֹּם אַהֲרֹן",
         "פסכת הרון",
         "And Aaron was silent."),
    ],
    4: [
        ("וַיִּקְרָא מֹשֶׁה אֶל-מִישָׁאֵל וְאֶל אֶלְצָפָן בְּנֵי עֻזִּיאֵל דֹּד אַהֲרֹן",
         "ת'ם דעא מוסי'. במישאל ואלצפן. בני עזיאל עם הרון",
         "Then Moses called Mishael and Elzaphan, sons of Uzziel the uncle of Aaron,"),
        ("וַיֹּאמֶר אֲלֵהֶם קִרְבוּ שְׂאוּ אֶת-אֲחֵיכֶם מֵאֵת פְּנֵי-הַקֹּדֶשׁ אֶל-מִחוּץ לַמַּחֲנֶה",
         "פקאל להמא. תקדמא אחמלא אכ'ותכמא מן בין ידי אלקדס. אלי' כ'ארג אלעסכר",
         "and said to them: 'Come forward, carry your brothers from before the sanctuary to outside the camp.'"),
    ],
    5: [
        ("וַיִּקְרְבוּ וַיִּשָּׂאֻם בְּכֻתֳּנֹתָם אֶל-מִחוּץ לַמַּחֲנֶה",
         "פתקדמא וחמלאהמא בתואניהמא. אלי' כ'ארג אלעסכר",
         "And they came forward and carried them in their tunics to outside the camp,"),
        ("כַּאֲשֶׁר דִּבֶּר מֹשֶׁה",
         "כמא אמר מוסי'",
         "as Moses had commanded."),
    ],
    6: [
        ("וַיֹּאמֶר מֹשֶׁה אֶל-אַהֲרֹן וּלְאֶלְעָזָר וּלְאִיתָמָר בָּנָיו",
         "וקאל מוסי' להרון. ולאלעזר ולאיתמר בניה",
         "And Moses said to Aaron, and to Eleazar and Ithamar his sons:"),
        ("רָאשֵׁיכֶם אַל-תִּפְרָעוּ וּבִגְדֵיכֶם לֹא-תִפְרֹמוּ וְלֹא תָמֻתוּ וְעַל כָּל-הָעֵדָה יִקְצֹף",
         "רוסכם לא תשעתו ות'יאבכם לא תמזקו ולא תהלכו. ועלי' גמיע אלגמע יכון סכ'ט",
         "'Do not dishevel your heads, and do not tear your garments, lest you perish — and upon all the congregation there shall be wrath."),
        ("וַאֲחֵיכֶם כָּל-בֵּית יִשְׂרָאֵל--יִבְכּוּ אֶת-הַשְּׂרֵפָה אֲשֶׁר שָׂרַף יְהוָה",
         "ואכ'ותכם גמיע בני אסראיל. יבכון עלי' אלחריק. אלד'י אחרקה אללה",
         "And your brothers, all the sons of Israel, shall weep over the burning which God has struck.'"),
    ],
    7: [
        ("וּמִפֶּתַח אֹהֶל מוֹעֵד לֹא תֵצְאוּ פֶּן-תָּמֻתוּ",
         "ומן באב כ'בא אלמחצ'ר. לא תכ'רגו ללא תהלכו",
         "And from the entrance of the tent of the assembly you shall not go out, lest you perish —"),
        ("כִּי-שֶׁמֶן מִשְׁחַת יְהוָה עֲלֵיכֶם",
         "לאן דהן מסוחייה' אללה עלי'כם",
         "for the anointing oil of God is upon you.'"),
        ("וַיַּעֲשׂוּ כִּדְבַר מֹשֶׁה",
         "פעמלו כמא אמר מוסי'",
         "And they did as Moses commanded."),
    ],
    8: [
        ("וַיְדַבֵּר יְהוָה אֶל-אַהֲרֹן לֵאמֹר",
         "ת'ם כלם אללה הרון תכלימא",
         "Then God spoke to Aaron directly."),
    ],
    9: [
        ("יַיִן וְשֵׁכָר אַל-תֵּשְׁתְּ אַתָּה וּבָנֶיךָ אִתָּךְ בְּבֹאֲכֶם אֶל-אֹהֶל מוֹעֵד--וְלֹא תָמֻתוּ",
         "כ'מר ומסכר. לא תשרב אנת ובניך מעך. פי דכולכם אלי' כ'בא אלמחצ'ר ולא תהלכו",
         "'Wine and strong drink you shall not drink — you and your sons with you — when you enter the tent of the assembly, lest you perish."),
        ("חֻקַּת עוֹלָם לְדֹרֹתֵיכֶם",
         "רסם אלדהר עלי' מר אגיאלכם",
         "A statute forever, throughout your generations.'"),
    ],
    10: [
        ("וּלְהַבְדִּיל בֵּין הַקֹּדֶשׁ וּבֵין הַחֹל וּבֵין הַטָּמֵא וּבֵין הַטָּהוֹר",
         "ולתפצלו. בין אלקדס ואלבד'ל. ואלטאהר ואלנגס",
         "'And that you may separate between the sacred and the profane, and between the clean and the unclean;'"),
    ],
    11: [
        ("וּלְהוֹרֹת אֶת-בְּנֵי יִשְׂרָאֵל--אֵת כָּל-הַחֻקִּים אֲשֶׁר דִּבֶּר יְהוָה אֲלֵיהֶם בְּיַד-מֹשֶׁה",
         "ולתפתון בני אסראיל. בגמיע אלרסום. אלד'י אמר אללה בהא עלי' יד מוסי'",
         "'and that you may give rulings to the sons of Israel in all the statutes which God commanded through Moses.'"),
    ],
    12: [
        ("וַיְדַבֵּר מֹשֶׁה אֶל-אַהֲרֹן וְאֶל אֶלְעָזָר וְאֶל-אִיתָמָר בָּנָיו הַנּוֹתָרִים",
         "ת'ם קאל מוסי' להרון. כ'דו אלהדייה",
         "Then Moses said to Aaron and to Eleazar and Ithamar, his two remaining sons:"),
        ("קְחוּ אֶת-הַמִּנְחָה הַנּוֹתֶרֶת מֵאִשֵּׁי יְהוָה וְאִכְלוּהָ מַצּוֹת אֵצֶל הַמִּזְבֵּחַ",
         "אלפאצ'לה מן קראבין אללה. וכלוהא פטירא לזק אלמד'בח",
         "'Take the gift remaining from the offerings of God, and eat it unleavened beside the altar,"),
        ("כִּי קֹדֶשׁ קָדָשִׁים הִוא",
         "לאנהא מן כ'ואץ אלאקדאס",
         "for it is from among the choicest of the sacred things.'"),
    ],
    13: [
        ("וַאֲכַלְתֶּם אֹתָהּ בְּמָקוֹם קָדוֹשׁ",
         "וגאיז אן תאכלוהא פי מוצ'ע מקדס",
         "'And it is permitted that you eat it in a consecrated place,"),
        ("כִּי חָקְךָ וְחָק-בָּנֶיךָ הִוא מֵאִשֵּׁי יְהוָה",
         "אד' הי רזקך ורזק בניך. מן קראבין אללה",
         "for it is your provision and the provision of your sons, from the offerings of God —"),
        ("כִּי-כֵן צֻוֵּיתִי",
         "לאן כד'א אמרת",
         "for thus was I commanded.'"),
    ],
    14: [
        ("וְאֵת חֲזֵה הַתְּנוּפָה וְאֵת שׁוֹק הַתְּרוּמָה תֹּאכְלוּ בְּמָקוֹם טָהוֹר--אַתָּה וּבָנֶיךָ וּבְנֹתֶיךָ אִתָּךְ",
         "ואמא קץ אלתחריך וסאק אלרפיעה. פכלוהמא פי מוצ'ע טאהר. אנת ובניך ובנאתך מעך",
         "'And the portion of the waving and the leg of the elevation-offering — eat them in a clean place, you and your sons and your daughters with you,"),
        ("כִּי-חָקְךָ וְחָק-בָּנֶיךָ נִתְּנוּ מִזִּבְחֵי שַׁלְמֵי בְּנֵי יִשְׂרָאֵל",
         "פאנהא רזקך ורזק בניך קד אעטיתמוהא. מן ד'באיח סלאמה' בני אסראיל",
         "for they are your provision and the provision of your sons, given to you from the well-being sacrifices of the sons of Israel.'"),
    ],
    15: [
        ("שׁוֹק הַתְּרוּמָה וַחֲזֵה הַתְּנוּפָה עַל אִשֵּׁי הַחֲלָבִים יָבִיאוּ לְהָנִיף תְּנוּפָה לִפְנֵי יְהוָה",
         "סאק אלרפיעה וקץ אלתחריך. מע קראבין אלשחום יאתו בהא. פיחרכהא תחריכא בין ידי אללה",
         "'The leg of the elevation-offering and the portion of the waving shall come together with the fat offerings — they shall wave them as a waving before God;"),
        ("וְהָיָה לְךָ וּלְבָנֶיךָ אִתְּךָ לְחָק-עוֹלָם כַּאֲשֶׁר צִוָּה יְהוָה",
         "פתכון לך. ולבניך מעך רסם אלדהר. כמא אמר אללה",
         "and it shall be for you and your sons with you a statute forever, as God commanded.'"),
    ],
    16: [
        ("וְאֵת שְׂעִיר הַחַטָּאת דָּרֹשׁ דָּרַשׁ מֹשֶׁה--וְהִנֵּה שֹׂרָף",
         "ואלתמס מוסי'. עתוד אלדכוה פאד'אה קד אחרק",
         "And Moses sought the he-goat of the purification-offering — and behold, it had already been burned."),
        ("וַיִּקְצֹף עַל-אֶלְעָזָר וְעַל-אִיתָמָר בְּנֵי אַהֲרֹן הַנּוֹתָרִם לֵאמֹר",
         "פסכ'ט עלי' אלעזר ואיתמר בני הרון. אלבאקיון קאילא",
         "And he was angered with Eleazar and Ithamar, the remaining sons of Aaron, saying:"),
    ],
    17: [
        ("מַדּוּעַ לֹא-אֲכַלְתֶּם אֶת-הַחַטָּאת בִּמְקוֹם הַקֹּדֶשׁ--כִּי קֹדֶשׁ קָדָשִׁים הִוא",
         "מא באלכם לם תאכלו אלדכוה פי מוצ'ע מקדס. לאנהא מן כ'ואץ אלאקדאס",
         "'What is your concern that you did not eat the purification-offering in a consecrated place? For it is from among the choicest of the sacred things,"),
        ("וְאֹתָהּ נָתַן לָכֶם לָשֵׂאת אֶת-עֲו‍ֹן הָעֵדָה לְכַפֵּר עֲלֵיהֶם לִפְנֵי יְהוָה",
         "ואללה קד אעטאכם איאהא. לתחמלו וזר אלגמע. ותסתג'פרו ענהם בין ידי אללה",
         "and God has already given it to you so that you may bear the burden of the congregation's guilt and seek forgiveness for them before God.'"),
    ],
    18: [
        ("הֵן לֹא-הוּבָא אֶת-דָּמָהּ אֶל-הַקֹּדֶשׁ פְּנִימָה",
         "ואיצ'א הוד'א לם ידכ'ל מן דמהא. אלי' אלקדס אלגוואני",
         "'Also, behold — none of its blood was brought into the inner sanctuary;"),
        ("אָכוֹל תֹּאכְלוּ אֹתָהּ בַּקֹּדֶשׁ כַּאֲשֶׁר צִוֵּיתִי",
         "פקד כאן יגב אן תאכלוהא. פי אלקדס כמא אמרתכם",
         "it was therefore obligatory that you eat it in the sacred precinct, as I commanded you.'"),
    ],
    19: [
        ("וַיְדַבֵּר אַהֲרֹן אֶל-מֹשֶׁה הֵן הַיּוֹם הִקְרִיבוּ אֶת-חַטָּאתָם וְאֶת-עֹלָתָם לִפְנֵי יְהוָה",
         "פקאל לה הרון. הוד'א אליום. קרבו פיה ד'כותהם וצעידתהם בין ידי אללה",
         "And Aaron said to him: 'Behold, today they brought their purification-offering and their burnt-offering before God,"),
        ("וַתִּקְרֶאנָה אֹתִי כָּאֵלֶּה",
         "וואפתני מת'ל הד'ה אלמצאיב",
         "and such calamities as these have befallen me —"),
        ("וְאָכַלְתִּי חַטָּאת הַיּוֹם הַיִּיטַב בְּעֵינֵי יְהוָה",
         "פלו אכלת אלדכוה אליום. הל כאן ד'אלך חסנא ענד אללה",
         "and had I eaten the purification-offering today, would that have been good in God's sight?'"),
    ],
    20: [
        ("וַיִּשְׁמַע מֹשֶׁה וַיִּיטַב בְּעֵינָיו",
         "פלמא סמע ד'אלך מוסי'. חסן ענדה",
         "And when Moses heard this, it seemed good to him."),
    ],
}
