"""Hand-authored alignment triples for Vayikra chapter 25.

Word-level: each JA (Saadia) word is its own group, mapped to the Hebrew word
it renders and its English counterpart. The runtime resolver matches each side
independently (lib/alignment.ts), so words link correctly even across word-order
crossings — verb-subject inversions, English-fronted negations, and Hebrew
construct reorderings. Words Saadia adds with no Hebrew source (glosses,
expansions) carry he=None and link JA↔English only.
"""

ALIGNMENTS: dict[int, list[tuple[str | None, str, str]]] = {
    1: [
        (None, "ת'ם", "Then"),
        ("וַיְדַבֵּר", "קאל", "spoke"),
        ("יְהוָה", "אללה", "God"),
        ("אֶל-מֹשֶׁה", "למוסי'", "to Moses"),
        ("בְּהַר", "פי טור", "on Mount"),
        ("סִינַי", "סיני", "Sinai"),
        ("לֵאמֹר", "תכלימא", "a speaking"),
    ],
    2: [
        ("דַּבֵּר", "מר", "Command"),
        ("אֶל-בְּנֵי", "בני", "the sons of"),
        ("יִשְׂרָאֵל", "אסראיל", "Israel"),
        ("וְאָמַרְתָּ", "וקל", "and say"),
        ("אֲלֵהֶם", "להם", "to them"),
        ("כִּי תָבֹאוּ", "אד'א דכ'לתם", "When you enter"),
        ("אֶל-הָאָרֶץ", "אלי' אלבלד", "the land"),
        ("אֲשֶׁר", "אלד'י", "which"),
        ("אֲנִי", "אנא", "I am"),
        ("נֹתֵן", "מעטיכם", "giving you"),
        (None, "פעטלו", "let"),
        ("הָאָרֶץ", "אלארץ'", "the land"),
        ("שַׁבָּת", "עטלה", "desist — a desisting"),
        ("לַיהוָה", "ללה", "for God"),
    ],
    3: [
        (None, "אן", "That"),
        (None, "תכון", "there be"),
        ("שֵׁשׁ", "סת", "six"),
        ("שָׁנִים", "סנין", "years"),
        ("תִּזְרַע", "תזרע", "you sow"),
        ("שָׂדֶךָ", "צ'יעתך", "your estate"),
        ("וְשֵׁשׁ", "וסת", "and six"),
        ("שָׁנִים", "סנין", "years"),
        ("תִּזְמֹר", "תרפק", "you tend"),
        ("כַּרְמֶךָ", "כרמך", "your vineyard"),
        ("וְאָסַפְתָּ", "ותגמע", "and gather"),
        ("אֶת-תְּבוּאָתָהּ", "ג'לתהא", "its yield"),
    ],
    4: [
        ("וּבַשָּׁנָה", "ופי אלסנה", "But in the seventh"),
        ("הַשְּׁבִיעִת", "אלסאבעה", "year"),
        ("שַׁבַּת שַׁבָּתוֹן", "עטלה", "a desisting"),
        ("לָאָרֶץ", "לאלארץ'", "for the land"),
        ("שַׁבָּת", "הי סבת", "it is a sabbath"),
        ("לַיהוָה", "ללה", "for God"),
        ("שָׂדְךָ", "צ'יעתך", "your estate"),
        ("לֹא תִזְרָע", "לא תזרע", "do not sow"),
        ("וְכַרְמְךָ", "ולא תרפק כרמך", "and do not tend your vineyard"),
    ],
    5: [
        (None, "וכ'לף", "The aftergrowth of"),
        ("אֵת סְפִיחַ", "זרעך", "your harvest"),
        (None, "פלא", "you shall not"),
        ("לֹא תִקְצוֹר", "תחצדה", "reap"),
        ("וְאֶת-עִנְּבֵי", "ואלפראד מן ענבך", "and the single grapes of your vineyard"),
        (None, "פלא", "you shall not"),
        ("לֹא תִבְצֹר", "תקטפה", "pluck"),
        ("שְׁנַת", "לאנהא סנה'", "for it is a year of"),
        ("שַׁבָּתוֹן", "עטלה", "desisting"),
        ("לָאָרֶץ", "לאלארץ'", "for the land"),
    ],
    6: [
        (None, "וליכון", "And let"),
        (None, "מא", "what"),
        (None, "ינבת", "grows"),
        (None, "מן", "from"),
        ("שַׁבַּת הָאָרֶץ", "אלארץ' אלמעטלה", "the desisted land"),
        ("לָכֶם", "לכם", "for you"),
        ("לְאָכְלָה", "מאכלא", "as food"),
        ("לְךָ", "לך", "for you"),
        ("וּלְעַבְדְּךָ", "ולעבדך", "and for your male slave"),
        ("וְלַאֲמָתֶךָ", "ולאמתך", "and for your female slave"),
        ("וְלִשְׂכִירְךָ", "ולאגירך", "and for your hired worker"),
        ("וּלְתוֹשָׁבְךָ", "ולציפך", "and for your guest"),
        ("הַגָּרִים", "אלמקימין", "who dwell"),
        ("עִמָּךְ", "מעך", "with you"),
    ],
    7: [
        ("וְלִבְהֶמְתְּךָ", "ולבהאימך", "And for your beasts"),
        ("וְלַחַיָּה", "ולאלוחש", "and for the wild creatures"),
        ("אֲשֶׁר", "אלד'י", "that are"),
        ("בְּאַרְצֶךָ", "פי ארצ'ך", "in your land"),
        ("תִּהְיֶה", "תכון", "shall be"),
        ("כָל-תְּבוּאָתָהּ", "גמיע ג'לתהא", "all its yield"),
        ("לֶאֱכֹל", "מאכלא", "for food"),
    ],
    8: [
        (None, "ת'ם", "Then"),
        ("וְסָפַרְתָּ", "אחץ", "count"),
        ("שֶׁבַע", "סבע", "seven"),
        ("שַׁבְּתֹת שָׁנִים", "סנין עטלה", "years of desisting"),
        (None, "וד'אלך", "and those"),
        ("שֶׁבַע שָׁנִים", "אלסבע אלסנין", "seven years"),
        ("שֶׁבַע פְּעָמִים", "סבע מראר", "seven times"),
        (None, "פיציר", "so that"),
        (None, "גמלה'", "the sum of"),
        (None, "ד'אלך", "that"),
        ("תֵּשַׁע וְאַרְבָּעִים שָׁנָה", "תסעה וארבעין סנה", "forty-nine years"),
    ],
    9: [
        ("וְהַעֲבַרְתָּ", "ואצ'רב", "And sound"),
        ("שׁוֹפַר", "בבוק", "a gathering"),
        ("תְּרוּעָה", "מגלב", "horn"),
        ("בֶּעָשׂוֹר לַחֹדֶשׁ", "פי אליום אלעאשר מן", "on the tenth day of"),
        ("בַּחֹדֶשׁ הַשְּׁבִעִי", "אלשהר אלסאבע", "the seventh month"),
        ("בְּיוֹם הַכִּפֻּרִים", "והו יום אלג'פראן", "it is the Day of Atonement"),
        ("תַּעֲבִירוּ", "אצ'רבו", "sound"),
        ("שׁוֹפָר", "פיה באלבוק", "it throughout"),
        ("בְּכָל-אַרְצְכֶם", "פי גמיע בלאדכם", "all your lands"),
    ],
    11: [
        (None, "ומן", "And among"),
        (None, "שרוט", "the conditions of"),
        (None, "הד'ה", "this"),
        ("יוֹבֵל הִוא", "סנה' אלאטלאק", "year of release"),
        ("שְׁנַת הַחֲמִשִּׁים שָׁנָה", "סנה' אלכ'מסין", "the year of fifty"),
        (None, "אן", "you shall"),
        ("לֹא תִזְרָעוּ", "לא תזרעו", "not sow"),
        (None, "פיהא", "in it"),
        ("וְלֹא תִקְצְרוּ", "ולא תחצדו", "and you shall not reap"),
        ("אֶת-סְפִיחֶיהָ", "כ'לפהא", "its aftergrowth"),
        ("וְלֹא תִבְצְרוּ", "ולא תקטפו", "and you shall not pluck"),
        ("אֶת-נְזִרֶיהָ", "פראדהא", "its single grapes"),
    ],
    12: [
        ("כִּי", "לאנהא", "For it is"),
        ("יוֹבֵל הִוא", "סנה' אטלאק", "a year of release"),
        ("קֹדֶשׁ", "מקדסה", "holy for you"),
        ("תִּהְיֶה לָכֶם", "תכון לכם", "it shall be"),
        (None, "ומן", "from"),
        ("מִן-הַשָּׂדֶה", "אלצחרא", "the open country"),
        ("תֹּאכְלוּ", "תאכלו", "you shall eat"),
        ("אֶת-תְּבוּאָתָהּ", "ג'לתהא", "its yield"),
        (None, "מבאחא", "as that which is freely permitted"),
    ],
    13: [
        (None, "ופי", "And in"),
        ("בִּשְׁנַת הַיּוֹבֵל", "הד'ה סנה' אלאטלאק", "this year of release"),
        ("תָּשֻׁבוּ", "ירגע", "shall return"),
        ("אִישׁ", "כל אמר", "every man"),
        ("אֶל-אֲחֻזָּתוֹ", "אלי' חוזה", "to his holding"),
    ],
    14: [
        (None, "ואד'א", "And when"),
        ("תִמְכְּרוּ מִמְכָּר", "בעת ביעא", "you sell a sale"),
        ("לַעֲמִיתֶךָ", "לצאחבך", "to your fellow"),
        ("אוֹ קָנֹה", "או אבתעת", "or buy"),
        ("מִיַּד עֲמִיתֶךָ", "מנה", "from him"),
        (None, "פלא", "let"),
        ("אַל-תּוֹנוּ", "יג'בן", "no"),
        ("אִישׁ", "כל ואחד", "one wrong"),
        ("אֶת-אָחִיו", "אכ'אה", "his brother"),
    ],
    15: [
        (None, "באחצא", "By the count of"),
        ("בְּמִסְפַּר שָׁנִים", "סנין", "years"),
        (None, "מן בעד", "after"),
        ("אַחַר הַיּוֹבֵל", "סנה אלאטלאק", "the year of release"),
        ("תִּקְנֶה", "תשתרי", "you shall buy"),
        ("מֵאֵת עֲמִיתֶךָ", "מן צאחבך", "from your fellow"),
        (None, "ובאחצא", "and by the count of"),
        ("בְּמִסְפַּר שְׁנֵי-תְבוּאֹת", "סני ג'לתהא", "years of its yield"),
        ("יִמְכָּר-לָךְ", "יביעך", "shall sell to you"),
        (None, "הו", "he"),
    ],
    16: [
        (None, "פעלי'", "According to"),
        (None, "קדר", "the abundance"),
        ("לְפִי רֹב הַשָּׁנִים", "כת'רת אלסנין", "of the years"),
        (None, "יגב", "the price must"),
        (None, "אן", "be"),
        ("תַּרְבֶּה מִקְנָתוֹ", "תכת'ר לה אלת'מן", "increased for him"),
        (None, "ועלי'", "and according to"),
        (None, "קדר", "the fewness"),
        ("וּלְפִי מְעֹט הַשָּׁנִים", "קלתהא", "of them"),
        (None, "יגוז", "it is permitted"),
        (None, "אן", "that"),
        ("תַּמְעִיט מִקְנָתוֹ", "תקל לה", "it be decreased for him"),
        ("כִּי", "לאנה", "for"),
        (None, "אנמא", "it is a counted number"),
        ("מִסְפַּר תְּבוּאֹת", "יביעך ג'לאת", "of yields"),
        (None, "מחצאה", "that he is selling you"),
    ],
    17: [
        ("וְלֹא תוֹנוּ", "ולא יג'בן", "And let no one"),
        ("אִישׁ", "כל ואחד", "wrong"),
        ("אֶת-עֲמִיתוֹ", "צאחבה", "his fellow"),
        (None, "וכ'ף", "and fear"),
        ("וְיָרֵאתָ מֵאֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "פאני", "for I am"),
        ("אֲנִי יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אלמעאקב", "who punishes"),
    ],
    18: [
        ("וַעֲשִׂיתֶם", "ואעמלו", "And perform"),
        ("אֶת-חֻקֹּתַי", "רסומי", "My statutes"),
        ("וְאֶת-מִשְׁפָּטַי", "ואחכאמי", "and My ordinances"),
        ("תִּשְׁמְרוּ", "אחפצוהא", "keep them"),
        ("וַעֲשִׂיתֶם אֹתָם", "ואעמלו בהא", "and act by them"),
        ("וִישַׁבְתֶּם", "ואסכנו", "and dwell"),
        ("עַל-הָאָרֶץ", "אלבלד", "in the land"),
        (None, "ואת'קין", "trusting"),
        (None, "בי", "in Me"),
    ],
    19: [
        ("וְנָתְנָה", "תכ'רג", "shall bring forth"),
        ("הָאָרֶץ", "אלארץ'", "The land"),
        ("פִּרְיָהּ", "ת'מרהא", "its fruit"),
        (None, "לכם", "for you"),
        ("וַאֲכַלְתֶּם", "פתאכלוה", "and you shall eat it"),
        ("לָשֹׂבַע", "הנייא", "with enjoyment"),
        ("וִישַׁבְתֶּם", "ותקימון", "and you shall settle"),
        ("עָלֶיהָ", "בהא", "therein"),
        (None, "ואת'קין", "trusting"),
    ],
    20: [
        (None, "פאן", "And if"),
        ("וְכִי תֹאמְרוּ", "קלתם", "you say"),
        ("מַה-נֹּאכַל", "מא נאכל", "What shall we eat"),
        ("בַּשָּׁנָה הַשְּׁבִיעִת", "פי אלסנה אלסאבעה", "in the seventh year"),
        ("הֵן", "אד'", "since"),
        ("לֹא נִזְרָע", "לא נזרע", "we do not sow"),
        ("וְלֹא נֶאֱסֹף", "ולא נגמע", "and do not gather"),
        ("אֶת-תְּבוּאָתֵנוּ", "ג'לתנא", "our yield"),
    ],
    21: [
        (None, "פאמר", "I shall command"),
        ("וְצִוִּיתִי אֶת-בִּרְכָתִי", "בברכתי", "My blessing"),
        ("לָכֶם", "לכם", "upon you"),
        ("בַּשָּׁנָה הַשִּׁשִּׁית", "פי אלסנה אלסאדסה", "in the sixth year"),
        ("וְעָשָׂת", "פתכפיכם", "shall suffice you"),
        ("אֶת-הַתְּבוּאָה", "ג'לתהא", "its yield"),
        ("לִשְׁלֹשׁ הַשָּׁנִים", "ת'לאת' סנין", "for three years"),
    ],
    22: [
        ("וּזְרַעְתֶּם", "ואזרעו", "And you shall sow"),
        ("אֵת הַשָּׁנָה הַשְּׁמִינִת", "פי אלסנה אלת'אמנה", "in the eighth year"),
        ("וַאֲכַלְתֶּם", "ואנתם תאכלון", "while you are eating"),
        ("מִן-הַתְּבוּאָה", "מן ג'לתהא", "from the old"),
        ("יָשָׁן", "עתיקא", "yield"),
        ("עַד הַשָּׁנָה הַתְּשִׁיעִת", "אלי' אלסנה אלתאסעה", "until the ninth year"),
        ("עַד-בּוֹא", "אלי'' מגי", "until the coming of"),
        ("תְּבוּאָתָהּ", "ג'לתהא", "its yield"),
        ("תֹּאכְלוּ יָשָׁן", "תאכלון עתיקא", "you shall eat what is old"),
    ],
    23: [
        ("וְהָאָרֶץ", "ואלארץ'", "And the land"),
        ("לֹא תִמָּכֵר", "פלא תבאע", "shall not be sold"),
        ("לִצְמִתֻת", "בתאתא", "outright"),
        ("כִּי-לִי", "לאנהא לי", "for it is Mine"),
        (None, "ואנמא", "you are but"),
        ("כִּי-גֵרִים", "סכאן", "residents"),
        ("וְתוֹשָׁבִים", "ואצ'יאף", "and guests"),
        ("אַתֶּם עִמָּדִי", "לי", "with Me"),
    ],
    24: [
        (None, "ופי", "And throughout"),
        ("וּבְכֹל", "גמיע", "all"),
        ("אֶרֶץ", "בלד", "the land of"),
        ("אֲחֻזַּתְכֶם", "חוזכם", "your holding"),
        ("גְּאֻלָּה", "אגעלו ולאיה", "grant dominion"),
        ("תִּתְּנוּ לָאָרֶץ", "לאלארץ'", "over the land"),
    ],
    25: [
        (None, "ואד'א", "And if"),
        ("כִּי-יָמוּךְ", "תמאהן", "becomes impoverished"),
        ("אָחִיךָ", "אכ'יך", "your brother"),
        ("וּמָכַר", "פבאע", "and sells"),
        (None, "שייא", "something"),
        ("מֵאֲחֻזָּתוֹ", "מן חוזה", "of his holding"),
        (None, "פליאת", "then let"),
        ("וּבָא גֹאֲלוֹ", "ולייה", "his nearest guardian"),
        ("הַקָּרֹב אֵלָיו", "אלאקרב אליה", "come"),
        ("וְגָאַל", "ויתולא", "and take charge of"),
        ("אֵת מִמְכַּר אָחִיו", "ביע אכ'יה", "his brother's sale"),
    ],
    26: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "רג'ל", "man"),
        ("כִּי לֹא יִהְיֶה-לּוֹ", "לם יכון לה", "who has no"),
        ("גֹּאֵל", "ולי", "guardian"),
        (None, "פנאלת", "if his hand"),
        ("וְהִשִּׂיגָה יָדוֹ", "ידה", "reaches"),
        ("וּמָצָא", "ואצאב", "and he finds"),
        ("כְּדֵי גְאֻלָּתוֹ", "כמקדאר פכאכה", "the measure of his redemption"),
    ],
    27: [
        (None, "פליחסב", "let him reckon"),
        ("וְחִשַּׁב", "סני", "the years of"),
        ("אֶת-שְׁנֵי מִמְכָּרוֹ", "ביעה", "his sale"),
        ("וְהֵשִׁיב", "וירד", "and return"),
        ("אֶת-הָעֹדֵף", "אלפאצ'ל", "the surplus"),
        ("לָאִישׁ", "אלי' אלרגל", "to the man"),
        ("אֲשֶׁר מָכַר-לוֹ", "אלד'י באעה", "to whom he sold it"),
        ("וְשָׁב", "וירגע", "and he shall return"),
        ("לַאֲחֻזָּתוֹ", "אלי' חוזה", "to his holding"),
    ],
    28: [
        (None, "ואן", "And if"),
        ("וְאִם לֹא-מָצְאָה", "לם תנאל", "does not reach"),
        ("יָדוֹ", "ידה", "his hand"),
        (None, "מקדאר", "the measure of"),
        ("דֵּי הָשִׁיב לוֹ", "מא ירדה עליה", "what he is to return to him"),
        (None, "פליבק", "then his sale shall"),
        ("וְהָיָה מִמְכָּרוֹ", "ביעה", "remain"),
        ("בְּיַד הַקֹּנֶה אֹתוֹ", "פי יד אלמשתרי מנה", "in the hand of its buyer"),
        ("עַד שְׁנַת הַיּוֹבֵל", "אלי' סנה' אלאטלאק", "until the year of release"),
        ("וְיָצָא", "ויכ'רג", "it shall go out"),
        ("בַּיֹּבֵל", "פיהא", "in that year"),
        ("וְשָׁב", "וירגע", "and he shall return"),
        ("לַאֲחֻזָּתוֹ", "אלי' חוזה", "to his holding"),
    ],
    29: [
        (None, "ואי", "And any"),
        ("וְאִישׁ", "רג'ל", "man"),
        ("כִּי-יִמְכֹּר", "באע", "who sells"),
        ("בֵּית-מוֹשַׁב", "ביתא מסכנא", "a dwelling house"),
        ("עִיר חוֹמָה", "פי קריה להא סור", "in a town that has a wall"),
        (None, "פליכון", "he shall have"),
        ("וְהָיְתָה גְּאֻלָּתוֹ", "באלכ'יאר", "the option"),
        ("עַד-תֹּם שְׁנַת מִמְכָּרוֹ", "אלי' אנקצ'א סנה מן יום ביעה", "until the completion of a year from the day of his sale"),
        (None, "פיכון", "his redemption shall be"),
        ("יָמִים תִּהְיֶה גְאֻלָּתוֹ", "פכאכה חולא", "a full year"),
    ],
    30: [
        (None, "פאן", "And if"),
        ("וְאִם לֹא-יִגָּאֵל", "לם יפתכה", "he does not redeem it"),
        ("עַד-מְלֹאת לוֹ", "אלי' אן כמלת לה", "by the time"),
        ("שָׁנָה תְמִימָה", "סנה תאמה", "a full year is completed for him"),
        (None, "פקד ת'בת", "then"),
        ("וְקָם הַבַּיִת", "אלבית", "the house"),
        ("אֲשֶׁר-בָּעִיר", "אלד'י פי אלקריה", "in the town"),
        ("אֲשֶׁר-לא (לוֹ) חֹמָה", "אלתי להא סור", "that has a wall"),
        ("לַצְּמִיתֻת", "בתאתא", "outright"),
        ("לַקֹּנֶה אֹתוֹ", "ללמשתרי", "for the buyer"),
        ("לְדֹרֹתָיו", "ולאגיאלה", "and his generations"),
        ("לֹא יֵצֵא", "לא יכ'רג", "it shall not go out"),
        ("בַּיֹּבֵל", "פי סנה' אלאטלאק", "in the year of release"),
    ],
    31: [
        ("וּבָתֵּי הַחֲצֵרִים", "וביות אלארבאץ'", "But houses of the outlying settlements"),
        ("אֲשֶׁר אֵין-לָהֶם חֹמָה", "אלתי ליס להא סור", "that have no wall"),
        (None, "יחיט בהא", "surrounding them"),
        (None, "פכמת'ל", "like"),
        ("עַל-שְׂדֵה הָאָרֶץ", "צ'יאע אלארץ'", "the estates of the open country"),
        ("יֵחָשֵׁב", "תחסב", "shall be reckoned"),
        ("גְּאֻלָּה", "אן יכון להא ולאיה", "dominion shall apply to them"),
        ("תִּהְיֶה-לּוֹ", "ותכ'רג", "and they shall go out"),
        ("וּבַיֹּבֵל יֵצֵא", "פי סנה' אלאטלאק", "in the year of release"),
    ],
    32: [
        (None, "ואמא", "But as for"),
        ("וְעָרֵי הַלְוִיִּם", "קרי' אלליואניין", "the towns of the Levites"),
        ("בָּתֵּי עָרֵי אֲחֻזָּתָם", "וביות קרי' חוזהם", "and the houses of their towns which are their holding"),
        (None, "פלהם", "they have"),
        (None, "אן", "the right"),
        ("גְּאֻלַּת עוֹלָם תִּהְיֶה לַלְוִיִּם", "יפתכוהא אבדא", "to redeem them forever"),
    ],
    33: [
        (None, "ומן", "And whoever"),
        ("וַאֲשֶׁר יִגְאַל מִן-הַלְוִיִּם", "ישתרי ד'אלך מנהם", "buys from them"),
        (None, "פליכ'רג", "shall go out"),
        ("וְיָצָא מִמְכַּר-בַּיִת", "כל בית מביוע", "every sold house"),
        ("וְעִיר אֲחֻזָּתוֹ", "וקרי' חוז", "and the towns of the holding"),
        (None, "לאייהם כאן", "of whichever Levite it may be"),
        ("בַּיֹּבֵל", "פי סנה אלאטלאק", "in the year of release"),
        ("כִּי", "לאן", "for"),
        ("בָתֵּי עָרֵי הַלְוִיִּם", "ביותהם וקראהם", "their houses and their towns"),
        ("הִוא אֲחֻזָּתָם", "הי חוזהם", "are their holding"),
        ("בְּתוֹךְ בְּנֵי יִשְׂרָאֵל", "פי מא בין בני אסראיל", "among the sons of Israel"),
    ],
    34: [
        (None, "ואמא", "But"),
        ("וּשְׂדֵה מִגְרַשׁ עָרֵיהֶם", "צ'יאע פנא קראהם", "the estates of the open ground around their towns"),
        ("לֹא יִמָּכֵר", "לא תבאע", "shall not be sold"),
        ("כִּי-אֲחֻזַּת עוֹלָם", "לאנהא חוז אלדהר", "for it is their holding"),
        ("הוּא לָהֶם", "להם", "forever"),
    ],
    35: [
        (None, "ואד'א", "And if"),
        ("וְכִי-יָמוּךְ", "תמאהן", "becomes impoverished"),
        ("אָחִיךָ", "אכ'יך", "your brother"),
        ("וּמָטָה יָדוֹ", "פמאלת ידה", "and his hand falters"),
        ("עִמָּךְ", "מעך", "with you"),
        (None, "פאשדדה", "then strengthen him"),
        ("וְהֶחֱזַקְתָּ בּוֹ", "באן יכון לך", "that he be as"),
        ("גֵּר", "סאכנא", "a resident"),
        ("וְתוֹשָׁב", "וצ'יפא", "and a guest"),
        ("וָחַי עִמָּךְ", "פיעיש מעך", "and let him live with you"),
    ],
    36: [
        ("אַל-תִּקַּח", "לא תאכ'ד'", "Do not take"),
        ("מֵאִתּוֹ", "מנה", "from him"),
        ("נֶשֶׁךְ", "עיינה", "a sample-interest"),
        ("וְתַרְבִּית", "ולא רבא", "nor usury"),
        (None, "וכ'ף", "and fear"),
        ("וְיָרֵאתָ מֵאֱלֹהֶיךָ", "רבך", "your Lord"),
        (None, "חתי", "so that"),
        ("וְחֵי אָחִיךָ", "יעיש אכ'יך", "your brother may live"),
        ("עִמָּךְ", "מעך", "with you"),
    ],
    37: [
        (None, "ולא תדפע", "And do not advance"),
        (None, "אליה", "to him"),
        ("אֶת-כַּסְפְּךָ", "ורקך", "your money"),
        ("אָכְלֶךָ", "וטעאמך", "or your food"),
        ("בְּנֶשֶׁךְ", "בעיינה", "at sample-interest"),
        ("וּבְמַרְבִּית לֹא-תִתֵּן", "ולא ברבא", "nor at usury"),
    ],
    38: [
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        ("אֲשֶׁר-הוֹצֵאתִי", "אלמכ'רגכם", "who brought you out"),
        ("מֵאֶרֶץ מִצְרָיִם", "מן בלד מצר", "from the land of Egypt"),
        ("לָתֵת לָכֶם", "לאעטיכם", "to give you"),
        ("אֶת-אֶרֶץ כְּנַעַן", "בלד כנעאן", "the land of Canaan"),
        (None, "פאכון", "that I may be"),
        ("לִהְיוֹת לָכֶם לֵאלֹהִים", "לכם אלאהא", "your God"),
    ],
    39: [
        (None, "ואד'א", "And if"),
        ("וְכִי-יָמוּךְ", "תמאהן", "becomes impoverished"),
        ("אָחִיךָ", "אכ'יך", "your brother"),
        ("עִמָּךְ", "מעך", "with you"),
        ("וְנִמְכַּר-לָךְ", "פבאע נפסה לך", "and sells himself to you"),
        ("לֹא-תַעֲבֹד בּוֹ", "לא תסתכ'דמה", "do not press him"),
        ("עֲבֹדַת עָבֶד", "כ'דמה' אלעביד", "into the service of slaves"),
    ],
    40: [
        ("כְּשָׂכִיר", "בל כאגיר", "Rather, as a hired worker"),
        ("כְּתוֹשָׁב", "או צ'יף", "or a guest"),
        ("יִהְיֶה עִמָּךְ", "יכון מעך", "he shall be with you"),
        ("עַד-שְׁנַת הַיֹּבֵל", "ואלי' סנה' אלאטלאק", "until the year of release"),
        ("יַעֲבֹד עִמָּךְ", "יכ'דמך", "he shall serve you"),
    ],
    41: [
        (None, "ת'ם", "Then"),
        ("וְיָצָא", "יכ'רג", "he shall go out"),
        ("מֵעִמָּךְ", "מן ענדך", "from your presence"),
        ("הוּא", "הו", "he"),
        ("וּבָנָיו", "ובניה", "and his sons"),
        ("עִמּוֹ", "מעה", "with him"),
        ("וְשָׁב", "וירגע", "and return"),
        ("אֶל-מִשְׁפַּחְתּוֹ", "אלי' עשירתה", "to his clan"),
        ("וְאֶל-אֲחֻזַּת אֲבֹתָיו", "ואלי' חוז אביה", "and to the holding of his father"),
    ],
    42: [
        ("כִּי-עֲבָדַי", "לאנהם עבידי", "For they are My servants"),
        ("אֲשֶׁר-הוֹצֵאתִי", "אלד'י אכ'רגתהם", "whom I brought out"),
        ("מֵאֶרֶץ מִצְרָיִם", "מן בלד מצר", "from the land of Egypt"),
        ("לֹא יִמָּכְרוּ", "פלא יבאעו", "they shall not be sold"),
        ("מִמְכֶּרֶת עָבֶד", "ביע אלעביד", "in the manner of the sale of slaves"),
    ],
    43: [
        ("לֹא-תִרְדֶּה בוֹ", "ולא תסתולי עליה", "And do not hold dominion over him"),
        ("בְּפָרֶךְ", "באקמא", "with cruelty"),
        (None, "וכ'ף", "and fear"),
        ("וְיָרֵאתָ מֵאֱלֹהֶיךָ", "רבך", "your Lord"),
    ],
    44: [
        ("וְעַבְדְּךָ", "ועבדך", "And your male slave"),
        ("וַאֲמָתְךָ", "ואמתך", "and your female slave"),
        ("אֲשֶׁר יִהְיוּ-לָךְ", "אלד'י יכונו לך", "who shall be yours"),
        ("מֵאֵת הַגּוֹיִם", "פמן אלאמם", "from the nations"),
        ("אֲשֶׁר סְבִיבֹתֵיכֶם", "אלד'ין חואליכם", "that are around you"),
        ("מֵהֶם תִּקְנוּ", "מנהם תקתנון", "from them you may acquire"),
        ("עֶבֶד", "עביד", "slaves"),
        ("וְאָמָה", "ואמא", "and maidservants"),
    ],
    45: [
        (None, "ואיצ'א", "Also"),
        ("וְגַם מִבְּנֵי הַתּוֹשָׁבִים", "מן בני אלסכאן", "from the children of the residents"),
        ("הַגָּרִים עִמָּכֶם", "אלמקימין מעכם", "who dwell with you"),
        ("מֵהֶם תִּקְנוּ", "תשתרון מנהם", "you may buy from them"),
        ("וּמִמִּשְׁפַּחְתָּם", "ומן עשירתהם", "and from their clans"),
        ("אֲשֶׁר הוֹלִידוּ", "אלמולודין", "born"),
        ("בְּאַרְצְכֶם", "פי בלדכם", "in your land"),
        ("וְהָיוּ לָכֶם לַאֲחֻזָּה", "פיכונו לכם חוזא", "and they shall be a holding for you"),
    ],
    46: [
        ("וְהִתְנַחַלְתֶּם", "תורתונהם", "You shall bequeath them"),
        ("אֹתָם לִבְנֵיכֶם", "לבניכם", "to your sons"),
        ("אַחֲרֵיכֶם", "מן בעדכם", "after you"),
        ("לָרֶשֶׁת אֲחֻזָּה", "כמיראת' אלחוז", "as an inheritance"),
        ("לְעֹלָם בָּהֶם תַּעֲבֹדוּ", "ותסתכ'דמונהם אבדא", "and you may press them into service forever"),
        (None, "ואמא", "but as for"),
        ("וּבְאַחֵיכֶם", "אכ'ותכם", "your brothers"),
        ("בְּנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        (None, "פכל ואחד", "no one"),
        ("לֹא-תִרְדֶּה בוֹ בְּפָרֶךְ", "לא יסתולי עלי' אכ'יה באקמא", "shall hold dominion over his brother with cruelty"),
    ],
    47: [
        (None, "ואן", "And if"),
        ("וְכִי תַשִּׂיג", "נאלת", "reaches"),
        ("יַד גֵּר", "יד ג'ריב", "the hand of a stranger"),
        ("וְתוֹשָׁב", "או סאכן", "or a resident"),
        ("עִמָּךְ", "מעך", "with you"),
        ("וּמָךְ אָחִיךָ", "ותמאהן אכ'יך", "and your brother becomes impoverished"),
        ("עִמּוֹ", "מעה", "with him"),
        ("וְנִמְכַּר", "פבאע נפסה", "and sells himself"),
        ("לְגֵר תּוֹשָׁב", "לג'ריב או סאכן", "to a stranger"),
        ("עִמָּךְ", "מעך", "with you"),
        ("אוֹ לְעֵקֶר מִשְׁפַּחַת גֵּר", "או לאצל עשירה' אלג'ריב", "or to the root of the stranger's clan"),
    ],
    48: [
        (None, "פבעד מא", "after"),
        ("אַחֲרֵי נִמְכַּר", "אנבאע", "he has been sold"),
        ("גְּאֻלָּה תִּהְיֶה-לּוֹ", "יכון לה פכאך", "there shall be a redemption for him"),
        ("אֶחָד מֵאֶחָיו", "ואחד מן אכ'ותה", "one of his brothers"),
        ("יִגְאָלֶנּוּ", "יפתכה", "shall redeem him"),
    ],
    49: [
        ("אוֹ-דֹדוֹ", "או עמה", "Or his uncle"),
        ("אוֹ בֶן-דֹּדוֹ", "או אבן עמה", "or his uncle's son"),
        ("יִגְאָלֶנּוּ", "יפתכה", "shall redeem him"),
        ("אוֹ-מִשְּׁאֵר בְּשָׂרוֹ", "או מן נסיב ד'אתה", "or one of the near kinsmen of his own person"),
        ("מִמִּשְׁפַּחְתּוֹ", "מן עשירתה", "from his clan"),
        ("יִגְאָלֶנּוּ", "יפתכה", "shall redeem him"),
        ("אוֹ-הִשִּׂיגָה יָדוֹ", "או נאלת ידה", "or if his hand reaches"),
        ("וְנִגְאָל", "פפך נפסה", "he shall redeem himself"),
    ],
    50: [
        (None, "פליחאסב", "And he shall reckon"),
        ("וְחִשַּׁב", "משתריה", "with his buyer"),
        (None, "כם מן", "how many"),
        ("עִם-קֹנֵהוּ", "סנה'", "years"),
        ("מִשְּׁנַת הִמָּכְרוֹ לוֹ", "אנבאע לה", "he was sold to him"),
        ("עַד שְׁנַת הַיֹּבֵל", "אלי' סנה' אלאטלאק", "until the year of release"),
        (None, "פיסקט", "shall be apportioned"),
        ("וְהָיָה כֶּסֶף מִמְכָּרוֹ", "ת'מן ביעה", "the price of his sale"),
        (None, "עלי'", "according to"),
        ("בְּמִסְפַּר שָׁנִים", "אחצא אלסנין", "the count of the years"),
        (None, "וליכון", "and he shall be"),
        (None, "מעה", "with him"),
        (None, "פיהא", "in those years"),
        ("כִּימֵי שָׂכִיר יִהְיֶה עִמּוֹ", "כאייאם אלאגיר", "as the days of a hired worker"),
    ],
    51: [
        (None, "פאן", "If"),
        ("אִם-עוֹד רַבּוֹת בַּשָּׁנִים", "בקי מן אלסנין כתיר", "many years remain"),
        (None, "פעלי'", "according to"),
        ("לְפִיהֶן יָשִׁיב", "קדרהא ירד", "their measure he shall return"),
        ("גְּאֻלָּתוֹ", "פכאכה", "his redemption"),
        ("מִכֶּסֶף מִקְנָתוֹ", "מנסובא מן ת'מן שראה", "proportioned from the price of his purchase"),
    ],
    52: [
        (None, "ואן", "And if"),
        ("וְאִם-מְעַט נִשְׁאַר בַּשָּׁנִים", "בקי מן אלסנין קליל", "few years remain"),
        ("עַד-שְׁנַת הַיֹּבֵל", "אלי' סנה' אלאטלאק", "until the year of release"),
        (None, "פליחאסבה", "he shall reckon with him"),
        (None, "ועלי'", "according to"),
        ("וְחִשַּׁב-לוֹ כְּפִי שָׁנָיו", "קדרהא", "their measure"),
        ("יָשִׁיב אֶת-גְּאֻלָּתוֹ", "ירד פכאכה", "he shall return his redemption"),
    ],
    53: [
        (None, "ובאלגמלה", "In sum"),
        ("כִּשְׂכִיר שָׁנָה בְּשָׁנָה", "כאגיר סנה בסנה", "as a hired worker year by year"),
        ("יִהְיֶה עִמּוֹ", "יכון מעה", "he shall be with him"),
        ("לֹא-יִרְדֶּנּוּ", "לא יסתולי עליה", "he shall not hold dominion over him"),
        ("בְּפֶרֶךְ", "באקמא", "with cruelty"),
        ("לְעֵינֶיךָ", "בחצ'רתך", "in your presence"),
    ],
    54: [
        (None, "ואן", "And if"),
        ("וְאִם-לֹא יִגָּאֵל בְּאֵלֶּה", "לם יפתך בהד'א אלאמור", "he is not redeemed by these means"),
        (None, "פליכ'רג", "then he shall go out"),
        ("וְיָצָא בִּשְׁנַת הַיֹּבֵל", "פי סנה' אלאטלאק", "in the year of release"),
        ("הוּא", "הו", "he"),
        ("וּבָנָיו עִמּוֹ", "ובניה מעה", "and his sons with him"),
    ],
    55: [
        ("כִּי-לִי", "לאן", "For"),
        ("בְנֵי-יִשְׂרָאֵל", "בני אסראיל", "the sons of Israel"),
        ("עֲבָדִים", "עביד לי", "are servants to Me"),
        ("עֲבָדַי הֵם", "אד' הם עבידי", "since they are My servants"),
        ("אֲשֶׁר-הוֹצֵאתִי", "אלד'י אכ'רגתהם", "whom I brought out"),
        ("מֵאֶרֶץ מִצְרָיִם", "מן בלד מצר", "from the land of Egypt"),
        ("אֲנִי", "אנא", "I am"),
        ("יְהוָה", "אללה", "God"),
        ("אֱלֹהֵיכֶם", "רבכם", "your Lord"),
        (None, "אעבדוני", "serve Me"),
    ],
}
