import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  // dictionary-lane.json has grown to 23K+ entries; TypeScript's literal-type
  // inference hits a V8 Map-size limit on Vercel's build workers. The code is
  // type-checked locally (where the TS cache handles it); skip the redundant
  // check in the production build to unblock deploys.
  typescript: { ignoreBuildErrors: true },
  // lib/tafsirIndex.ts reads data/tafsir-{book}-{ch}.json at request time via
  // fs.readFile. The paths are dynamic, so Next's static tracing can't infer
  // them — list them explicitly so Vercel bundles them into the function.
  // The lexicon search + lemma pages (lib/lexicon.ts) read the same files to
  // build their book-aware concordance, so they need the data traced too.
  // Old folio-chunk URLs → real chapter slugs (Emunot re-alignment, 2026-07).
  async redirects() {
    return [
    { source: "/advanced/saadia-emunot-vedeot/m1f1", destination: "/advanced/saadia-emunot-vedeot/m1c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m1f2", destination: "/advanced/saadia-emunot-vedeot/m1c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m1f3", destination: "/advanced/saadia-emunot-vedeot/m1c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m1f4", destination: "/advanced/saadia-emunot-vedeot/m1c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m1f5", destination: "/advanced/saadia-emunot-vedeot/m1c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f1", destination: "/advanced/saadia-emunot-vedeot/m2c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f2", destination: "/advanced/saadia-emunot-vedeot/m2c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f3", destination: "/advanced/saadia-emunot-vedeot/m2c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f4", destination: "/advanced/saadia-emunot-vedeot/m2c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f5", destination: "/advanced/saadia-emunot-vedeot/m2c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f6", destination: "/advanced/saadia-emunot-vedeot/m2c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f7", destination: "/advanced/saadia-emunot-vedeot/m2c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f8", destination: "/advanced/saadia-emunot-vedeot/m2c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f9", destination: "/advanced/saadia-emunot-vedeot/m2c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f10", destination: "/advanced/saadia-emunot-vedeot/m2c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f11", destination: "/advanced/saadia-emunot-vedeot/m2c10", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f12", destination: "/advanced/saadia-emunot-vedeot/m2c11", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f13", destination: "/advanced/saadia-emunot-vedeot/m2c12", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m2f14", destination: "/advanced/saadia-emunot-vedeot/m2c13", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f1", destination: "/advanced/saadia-emunot-vedeot/m3c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f2", destination: "/advanced/saadia-emunot-vedeot/m3c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f3", destination: "/advanced/saadia-emunot-vedeot/m3c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f4", destination: "/advanced/saadia-emunot-vedeot/m3c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f5", destination: "/advanced/saadia-emunot-vedeot/m3c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f6", destination: "/advanced/saadia-emunot-vedeot/m3c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f7", destination: "/advanced/saadia-emunot-vedeot/m3c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f8", destination: "/advanced/saadia-emunot-vedeot/m3c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f9", destination: "/advanced/saadia-emunot-vedeot/m3c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f10", destination: "/advanced/saadia-emunot-vedeot/m3c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m3f11", destination: "/advanced/saadia-emunot-vedeot/m3c10", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f1", destination: "/advanced/saadia-emunot-vedeot/m4c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f2", destination: "/advanced/saadia-emunot-vedeot/m4c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f3", destination: "/advanced/saadia-emunot-vedeot/m4c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f4", destination: "/advanced/saadia-emunot-vedeot/m4c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f5", destination: "/advanced/saadia-emunot-vedeot/m4c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f6", destination: "/advanced/saadia-emunot-vedeot/m4c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m4f7", destination: "/advanced/saadia-emunot-vedeot/m4c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f1", destination: "/advanced/saadia-emunot-vedeot/m5c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f2", destination: "/advanced/saadia-emunot-vedeot/m5c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f3", destination: "/advanced/saadia-emunot-vedeot/m5c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f4", destination: "/advanced/saadia-emunot-vedeot/m5c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f5", destination: "/advanced/saadia-emunot-vedeot/m5c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f6", destination: "/advanced/saadia-emunot-vedeot/m5c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f7", destination: "/advanced/saadia-emunot-vedeot/m5c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m5f8", destination: "/advanced/saadia-emunot-vedeot/m5c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f1", destination: "/advanced/saadia-emunot-vedeot/m6c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f2", destination: "/advanced/saadia-emunot-vedeot/m6c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f3", destination: "/advanced/saadia-emunot-vedeot/m6c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f4", destination: "/advanced/saadia-emunot-vedeot/m6c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f5", destination: "/advanced/saadia-emunot-vedeot/m6c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f6", destination: "/advanced/saadia-emunot-vedeot/m6c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f7", destination: "/advanced/saadia-emunot-vedeot/m6c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m6f8", destination: "/advanced/saadia-emunot-vedeot/m6c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f1", destination: "/advanced/saadia-emunot-vedeot/m7c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f2", destination: "/advanced/saadia-emunot-vedeot/m7c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f3", destination: "/advanced/saadia-emunot-vedeot/m7c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f4", destination: "/advanced/saadia-emunot-vedeot/m7c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f5", destination: "/advanced/saadia-emunot-vedeot/m7c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f6", destination: "/advanced/saadia-emunot-vedeot/m7c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f7", destination: "/advanced/saadia-emunot-vedeot/m7c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f8", destination: "/advanced/saadia-emunot-vedeot/m7c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m7f9", destination: "/advanced/saadia-emunot-vedeot/m7c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f1", destination: "/advanced/saadia-emunot-vedeot/m8c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f2", destination: "/advanced/saadia-emunot-vedeot/m8c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f3", destination: "/advanced/saadia-emunot-vedeot/m8c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f4", destination: "/advanced/saadia-emunot-vedeot/m8c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f5", destination: "/advanced/saadia-emunot-vedeot/m8c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f6", destination: "/advanced/saadia-emunot-vedeot/m8c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f7", destination: "/advanced/saadia-emunot-vedeot/m8c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f8", destination: "/advanced/saadia-emunot-vedeot/m8c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m8f9", destination: "/advanced/saadia-emunot-vedeot/m8c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f1", destination: "/advanced/saadia-emunot-vedeot/m9c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f2", destination: "/advanced/saadia-emunot-vedeot/m9c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f3", destination: "/advanced/saadia-emunot-vedeot/m9c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f4", destination: "/advanced/saadia-emunot-vedeot/m9c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f5", destination: "/advanced/saadia-emunot-vedeot/m9c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f6", destination: "/advanced/saadia-emunot-vedeot/m9c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f7", destination: "/advanced/saadia-emunot-vedeot/m9c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f8", destination: "/advanced/saadia-emunot-vedeot/m9c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f9", destination: "/advanced/saadia-emunot-vedeot/m9c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f10", destination: "/advanced/saadia-emunot-vedeot/m9c10", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m9f11", destination: "/advanced/saadia-emunot-vedeot/m9c10", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f1", destination: "/advanced/saadia-emunot-vedeot/m10c1", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f2", destination: "/advanced/saadia-emunot-vedeot/m10c2", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f3", destination: "/advanced/saadia-emunot-vedeot/m10c3", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f4", destination: "/advanced/saadia-emunot-vedeot/m10c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f5", destination: "/advanced/saadia-emunot-vedeot/m10c4", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f6", destination: "/advanced/saadia-emunot-vedeot/m10c5", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f7", destination: "/advanced/saadia-emunot-vedeot/m10c6", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f8", destination: "/advanced/saadia-emunot-vedeot/m10c7", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f9", destination: "/advanced/saadia-emunot-vedeot/m10c8", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f10", destination: "/advanced/saadia-emunot-vedeot/m10c9", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f11", destination: "/advanced/saadia-emunot-vedeot/m10c10", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f12", destination: "/advanced/saadia-emunot-vedeot/m10c11", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f13", destination: "/advanced/saadia-emunot-vedeot/m10c12", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f14", destination: "/advanced/saadia-emunot-vedeot/m10c13", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f15", destination: "/advanced/saadia-emunot-vedeot/m10c14", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f16", destination: "/advanced/saadia-emunot-vedeot/m10c15", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f17", destination: "/advanced/saadia-emunot-vedeot/m10c16", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f18", destination: "/advanced/saadia-emunot-vedeot/m10c17", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f19", destination: "/advanced/saadia-emunot-vedeot/m10c18", permanent: true },
    { source: "/advanced/saadia-emunot-vedeot/m10f20", destination: "/advanced/saadia-emunot-vedeot/m10c19", permanent: true },
    ];
  },
  outputFileTracingIncludes: {
    "/tafsir/**": ["./data/tafsir-*.json"],
    "/lexicon": ["./data/tafsir-*.json"],
    "/lexicon/**": ["./data/tafsir-*.json"],
  },
};

export default nextConfig;
