/**
 * Gate manifest for the Qirqisānī Kitāb al-Anwār volume.
 *
 * M1 = Maqāla I   (Sectology, babs 1-19)
 * M2 = Maqāla II  (Epistemology, babs 1-28)
 * M3 = Maqāla III (Polemics, babs 1-25)
 * M5 = Maqāla V   (Legal commandments: circumcision + Sabbath, sha'arim 1-40)
 */

export type QGate = {
  /** URL segment, e.g. "m1-bab-1" or "m5-sha-12". */
  slug: string;
  maqala: "I" | "II" | "III" | "V";
  section: string;
  section_ja: string;
  /** Whether a working English translation + aligned file exists. */
  hasEnglish: boolean;
  /** Whether a Hebrew translation file exists. Defaults to false. */
  hasHebrew?: boolean;
};

export const QIRQISANI_GATES: QGate[] = [
  // ─── Maqāla I: Sectology ───────────────────────────────────────
  {
    slug: "m1-bab-1",
    maqala: "I",
    section: "Discourse I · Bab 1: The Book's Opening",
    section_ja: "المقالة الأولى · صدر الكتاب",
    hasEnglish: true,
    hasHebrew: false,
  },
  {
    slug: "m1-bab-2",
    maqala: "I",
    section: "Discourse I · Bab 2: Enumeration of Jewish Sects",
    section_ja: "في ذكر أفاريق اليهود كل فرقة وفرقة",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-3",
    maqala: "I",
    section: "Discourse I · Bab 3: Doctrines Distinctive to the Rabbanites",
    section_ja: "فيما تفرد به الربانيون من القول الذي خالفهم فيه جميع أفاريق اليهود",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-4",
    maqala: "I",
    section: "Discourse I · Bab 4: Rabbanite Non-Legal Doctrines",
    section_ja: "في حكاية بعض ما قالوه في غير الوصايا",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-5",
    maqala: "I",
    section: "Discourse I · Bab 5: Samaritan Doctrine",
    section_ja: "في حكاية قول السامرة",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-6",
    maqala: "I",
    section: "Discourse I · Bab 6: Sadducee Doctrine",
    section_ja: "في حكاية قول الصدوقية",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-7",
    maqala: "I",
    section: "Discourse I · Bab 7: Cave Sect (Maghariyya) Doctrine",
    section_ja: "في حكاية قول المغارية",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-8",
    maqala: "I",
    section: "Discourse I · Bab 8: Jesus and Christian Doctrine",
    section_ja: "في ذكر يسوع وحكاية قول النصارى",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-9",
    maqala: "I",
    section: "Discourse I · Bab 9: Qurʿiyya (Apocryphal Sect)",
    section_ja: "في حكاية قول القرعية",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-10",
    maqala: "I",
    section: "Discourse I · Bab 10: Shāmī vs. Iraqi Rabbanites",
    section_ja: "في ذكر ما يختلف فيه ربانيو الشأم وربانيو العراق",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-11",
    maqala: "I",
    section: "Discourse I · Bab 11: Abū ʿĪsā al-Iṣfahānī (ʿĪsawiyya)",
    section_ja: "في حكاية قول أبي عيسى الإصفهاني",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-12",
    maqala: "I",
    section: "Discourse I · Bab 12: Yudghan al-Rāʿī (Yudghanites)",
    section_ja: "في حكاية قول يودغان وهو الراعي",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-13",
    maqala: "I",
    section: "Discourse I · Bab 13: Anan b. David (Ananites)",
    section_ja: "في حكاية ما تفرد به عانان رأس الجالوت ومن تابعه",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-14",
    maqala: "I",
    section: "Discourse I · Bab 14: Benjamin al-Nahāwandī",
    section_ja: "في ذكر ما تفرد به بنيامين النهاوندي",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-15",
    maqala: "I",
    section: "Discourse I · Bab 15: Ismaʿīl al-ʿUkbarī's Errors",
    section_ja: "في ذكر مساوئ إسماعيل العكبري",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-16",
    maqala: "I",
    section: "Discourse I · Bab 16: Abū ʿImrān al-Tiflīsī and Mālik al-Ramlī",
    section_ja: "في ذكر أبي عمران التفليسي وملك الرملي",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-17",
    maqala: "I",
    section: "Discourse I · Bab 17: Mishawayh al-ʿUkbarī",
    section_ja: "في حكاية ما تفرد به ميشويه",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-18",
    maqala: "I",
    section: "Discourse I · Bab 18: Daniel al-Dāmaghānī",
    section_ja: "في حكاية ما تفرد به دانيال الدامغاني",
    hasEnglish: true,
    hasHebrew: true,
  },
  {
    slug: "m1-bab-19",
    maqala: "I",
    section: "Discourse I · Bab 19: Contemporary Disputes among the Karaites",
    section_ja: "في ذكر ما يختلف فيه القرائين في عصرنا هذا",
    hasEnglish: true,
    hasHebrew: true,
  },

  // ─── Maqāla II: Epistemology ──────────────────────────────────
  { slug: "m2-bab-1",  maqala: "II", section: "Discourse II · Bab 1: On How Knowledge Arises (Diversity of Religious Denominations)",     section_ja: "في اختلاف أهل الديانات في كيفية وقوع العلم",                  hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-2",  maqala: "II", section: "Discourse II · Bab 2: Refutation of Those Who Claim Knowledge Comes Only by the Senses",  section_ja: "في الردّ على من زعم أنه لا يعلم شيئاً إلا بالحسّ",             hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-3",  maqala: "II", section: "Discourse II · Bab 3: Refutation of Those Who Deny Knowledge by Rational Reflection",     section_ja: "في الردّ على من جحد العلم بالاعتبار العقلي",                   hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-4",  maqala: "II", section: "Discourse II · Bab 4: Refutation of Those Who Claim Knowledge Arises Only by Report",     section_ja: "في الردّ على من زعم أن العلم لا يقع إلا بالخبر",               hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-5",  maqala: "II", section: "Discourse II · Bab 5: Confirming Inquiry, Reflection, and Demonstration",                section_ja: "في إثبات البحث والنظر والاستدلال",                             hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-6",  maqala: "II", section: "Discourse II · Bab 6: On Inquiry and Speculation",                                        section_ja: "في البحث والنظر",                                               hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-7",  maqala: "II", section: "Discourse II · Bab 7: On the Obligation of Inquiry",                                      section_ja: "في وجوب البحث",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-8",  maqala: "II", section: "Discourse II · Bab 8: On the Obligatoriness of Inquiry Continued",                        section_ja: "في ذلك",                                                        hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-9",  maqala: "II", section: "Discourse II · Bab 9: On Proving the Existence of the Creator",                           section_ja: "في إثبات وجود البارئ",                                          hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-10", maqala: "II", section: "Discourse II · Bab 10: On the Unity of the Creator",                                      section_ja: "في توحيد البارئ",                                               hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-11", maqala: "II", section: "Discourse II · Bab 11: On the Eternity of the Creator",                                   section_ja: "في قدم البارئ",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-12", maqala: "II", section: "Discourse II · Bab 12: On the Power of the Creator",                                      section_ja: "في قدرة البارئ",                                                hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-13", maqala: "II", section: "Discourse II · Bab 13: On the Knowledge of the Creator",                                  section_ja: "في علم البارئ",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-14", maqala: "II", section: "Discourse II · Bab 14: On the Will of the Creator",                                       section_ja: "في إرادة البارئ",                                               hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-15", maqala: "II", section: "Discourse II · Bab 15: On the Life of the Creator",                                       section_ja: "في حياة البارئ",                                                hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-16", maqala: "II", section: "Discourse II · Bab 16: On the Word of the Creator",                                       section_ja: "في كلام البارئ",                                                hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-17", maqala: "II", section: "Discourse II · Bab 17: On the Speech of the Creator",                                     section_ja: "في قول البارئ",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-18", maqala: "II", section: "Discourse II · Bab 18: On the Justice of the Creator",                                    section_ja: "في عدل البارئ",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-19", maqala: "II", section: "Discourse II · Bab 19: On Creation from Nothing",                                         section_ja: "في الخلق من لا شيء",                                           hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-20", maqala: "II", section: "Discourse II · Bab 20: On the Eternity of the World",                                     section_ja: "في قدم العالم",                                                 hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-21", maqala: "II", section: "Discourse II · Bab 21: On Prophethood",                                                   section_ja: "في النبوة",                                                     hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-22", maqala: "II", section: "Discourse II · Bab 22: On the Miracles of the Prophets",                                  section_ja: "في معجزات الأنبياء",                                            hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-23", maqala: "II", section: "Discourse II · Bab 23: On the Abrogation of the Law",                                     section_ja: "في نسخ الشريعة",                                                hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-24", maqala: "II", section: "Discourse II · Bab 24: On Reward and Punishment",                                         section_ja: "في الثواب والعقاب",                                             hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-25", maqala: "II", section: "Discourse II · Bab 25: On the Resurrection",                                              section_ja: "في البعث",                                                      hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-26", maqala: "II", section: "Discourse II · Bab 26: That Visual Perception of God Is Impossible",                      section_ja: "في نفي رؤية البارئ",                                            hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-27", maqala: "II", section: "Discourse II · Bab 27: On Scriptural Expressions That Suggest Corporeality",              section_ja: "في ما ورد في الكتاب من الألفاظ الموهمة للتجسيم",               hasEnglish: true, hasHebrew: true },
  { slug: "m2-bab-28", maqala: "II", section: "Discourse II · Bab 28: Refutation of Those Who Take Anthropomorphic Expressions Literally",section_ja: "في الردّ على من أخذ بظاهر الألفاظ الموهمة للتجسيم",             hasEnglish: true, hasHebrew: true },

  // ─── Maqāla III: Polemics ─────────────────────────────────────
  { slug: "m3-bab-1",  maqala: "III", section: "Discourse III · Bab 1: Against the Samaritans",                                           section_ja: "الباب الأوّل في الردّ على السامرة",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-2",  maqala: "III", section: "Discourse III · Bab 2: Against Christians — the Trinity",                                 section_ja: "الباب الثاني في الردّ على النصارى في الأصل",                   hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-3",  maqala: "III", section: "Discourse III · Bab 3: Against Christians — the Incarnation",                             section_ja: "الباب الثالث في الردّ على النصارى",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-4",  maqala: "III", section: "Discourse III · Bab 4: Against Christians — the Gospels",                                 section_ja: "الباب الرابع في الردّ على النصارى",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-5",  maqala: "III", section: "Discourse III · Bab 5: Against Christians — the Abrogation Claim",                        section_ja: "الباب الخامس في الردّ على النصارى",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-6",  maqala: "III", section: "Discourse III · Bab 6: Against Islam — the Prophethood of Muḥammad",                     section_ja: "الباب السادس في الردّ على الإسلام",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-7",  maqala: "III", section: "Discourse III · Bab 7: Against Islam — the Quran",                                        section_ja: "الباب السابع في الردّ على الإسلام",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-8",  maqala: "III", section: "Discourse III · Bab 8: Against Islam — the Abrogation Claim",                             section_ja: "الباب الثامن في الردّ على الإسلام",                             hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-9",  maqala: "III", section: "Discourse III · Bab 9: Against Islam — Continued",                                        section_ja: "الباب التاسع",                                                  hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-10", maqala: "III", section: "Discourse III · Bab 10: Against Islam — Continued",                                       section_ja: "الباب العاشر",                                                  hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-11", maqala: "III", section: "Discourse III · Bab 11: Against Islam — Continued",                                       section_ja: "الباب الحادي عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-12", maqala: "III", section: "Discourse III · Bab 12: Against Islam — Continued",                                       section_ja: "الباب الثاني عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-13", maqala: "III", section: "Discourse III · Bab 13: Against Islam — Continued",                                       section_ja: "الباب الثالث عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-14", maqala: "III", section: "Discourse III · Bab 14: Against Islam — Continued",                                       section_ja: "الباب الرابع عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-15", maqala: "III", section: "Discourse III · Bab 15: Against Islam — Continued",                                       section_ja: "الباب الخامس عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-16", maqala: "III", section: "Discourse III · Bab 16: Against Islam — Continued",                                       section_ja: "الباب السادس عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-17", maqala: "III", section: "Discourse III · Bab 17: Against Islam — Continued",                                       section_ja: "الباب السابع عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-18", maqala: "III", section: "Discourse III · Bab 18: Against Islam — Continued",                                       section_ja: "الباب الثامن عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-19", maqala: "III", section: "Discourse III · Bab 19: Against Islam — Continued",                                       section_ja: "الباب التاسع عشر",                                              hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-20", maqala: "III", section: "Discourse III · Bab 20: Against Islam — Continued",                                       section_ja: "الباب العشرون",                                                 hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-21", maqala: "III", section: "Discourse III · Bab 21: Against Islam — Continued",                                       section_ja: "الباب الحادي والعشرون",                                         hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-22", maqala: "III", section: "Discourse III · Bab 22: Against Islam — Continued",                                       section_ja: "الباب الثاني والعشرون",                                         hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-23", maqala: "III", section: "Discourse III · Bab 23: Against Islam — Continued",                                       section_ja: "الباب الثالث والعشرون",                                         hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-24", maqala: "III", section: "Discourse III · Bab 24: Against Islam — Continued",                                       section_ja: "الباب الرابع والعشرون",                                         hasEnglish: true, hasHebrew: false },
  { slug: "m3-bab-25", maqala: "III", section: "Discourse III · Bab 25: Against Islam — Continued",                                       section_ja: "الباب الخامس والعشرون",                                         hasEnglish: true, hasHebrew: false },

  // ─── Maqāla V: Circumcision + Sabbath ────────────────────────────
  {
    slug: "m5-sha-1",
    maqala: "V",
    section: "Discourse V · Ch. 1: Circumcision on the Eighth Day",
    section_ja: "الباب الأول في الختانة في اليوم الثامن",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-2",
    maqala: "V",
    section: "Discourse V · Ch. 2: Obligations of the Uncircumcised",
    section_ja: "الباب الثاني فيما يجب على من لم يختتن",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-3",
    maqala: "V",
    section: "Discourse V · Ch. 3: Circumcising One Who Died Before the Eighth Day",
    section_ja: "الباب الثالث في من مات قبل اليوم الثامن",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-4",
    maqala: "V",
    section: "Discourse V · Ch. 4: Timing of Circumcision for Adults, Converts, and Slaves",
    section_ja: "الباب الرابع في ختانة البالغ والدخيل والعبد",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-5",
    maqala: "V",
    section: "Discourse V · Ch. 5: One Who Enters the Religion Already Circumcised",
    section_ja: "الباب الخامس في من دخل في الدين وهو مختون",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-6",
    maqala: "V",
    section: "Discourse V · Ch. 6: Anan's Argument That Circumcision Must Use Scissors",
    section_ja: "الباب السادس فيما ادعاه عانان من أن الختانة يجب أن تكون بمقراض",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-7",
    maqala: "V",
    section: "Discourse V · Ch. 7: Whether Circumcision May Be Performed by a Non-Israelite",
    section_ja: "الباب السابع في ختانة غير الإسرائيلي",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-8",
    maqala: "V",
    section: "Discourse V · Ch. 8: Circumcision of a Sick Person",
    section_ja: "الباب الثامن في ختانة العليل",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-9",
    maqala: "V",
    section: "Discourse V · Ch. 9: Whether a Woman May Circumcise",
    section_ja: "الباب التاسع في ختانة المرأة",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-10",
    maqala: "V",
    section: "Discourse V · Ch. 10: Anan's View That Only an Israelite May Circumcise",
    section_ja: "الباب العاشر في قول عانان أنه لا يجوز أن يختن إلا إسرائيلي",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-11",
    maqala: "V",
    section: "Discourse V · Ch. 11: Returning to the Sabbath",
    section_ja: "الباب الحادي عشر",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-12",
    maqala: "V",
    section: "Discourse V · Ch. 12: “Remember the Sabbath Day” (Exodus 20:7)",
    section_ja: "الباب الثاني عشر في قوله זכור את יום השבת",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-13",
    maqala: "V",
    section: "Discourse V · Ch. 13: “To Keep It Holy” (Exodus 20:8)",
    section_ja: "الباب الثالث عشر في قوله לקדשו",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-14",
    maqala: "V",
    section: "Discourse V · Ch. 14: Continuation",
    section_ja: "الباب الرابع عشر في ذلك",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-15",
    maqala: "V",
    section: "Discourse V · Ch. 15: “Six Days Shalt Thou Labor” (Exodus 20:9)",
    section_ja: "الباب الخامس عشر في قوله ששת ימים תעבד",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-16",
    maqala: "V",
    section: "Discourse V · Ch. 16: Permissible Actions on the Sabbath",
    section_ja: "الباب السادس عشر في ذكر ما يجوز عمله في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-17",
    maqala: "V",
    section: "Discourse V · Ch. 17: On “Skilled Labor” (Melakhot)",
    section_ja: "الباب السابع عشر في القول على الصنائع",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-18",
    maqala: "V",
    section: "Discourse V · Ch. 18: Carrying Out of the House [lacuna in Nemoy]",
    section_ja: "الباب الثامن عشر في الإخراج من البيوت",
    hasEnglish: false,
  },
  {
    slug: "m5-sha-19",
    maqala: "V",
    section: "Discourse V · Ch. 19: “Your Houses” (Jeremiah 17:22)",
    section_ja: "الباب التاسع عشر في قوله מבתיכם",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-20",
    maqala: "V",
    section: "Discourse V · Ch. 20: Is There a Limit on Forbidden Burdens?",
    section_ja: "الباب العشرون في الحمل المحرم إخراجه هل له حد",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-21",
    maqala: "V",
    section: "Discourse V · Ch. 21: What Falls under the Forbidden Burden",
    section_ja: "الباب الواحد والعشرون فيما يدخل تحت الحمل",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-22",
    maqala: "V",
    section: "Discourse V · Ch. 22: Leaving One's Place on the Sabbath",
    section_ja: "الباب الثاني والعشرون في الخروج من המקום",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-23",
    maqala: "V",
    section: "Discourse V · Ch. 23: The Prohibition of Fire on the Sabbath",
    section_ja: "الباب الثالث والعشرون في تحريم وجود النار",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-24",
    maqala: "V",
    section: "Discourse V · Ch. 24: Circumcision on the Sabbath",
    section_ja: "الباب الرابع والعشرون في الختانة في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-25",
    maqala: "V",
    section: "Discourse V · Ch. 25: Is It Permitted to Rescind an Oath on the Sabbath?",
    section_ja: "الباب الخامس والعشرون في هل يجوز إحلال الأيمان في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-26",
    maqala: "V",
    section: "Discourse V · Ch. 26: Sea Travel on the Sabbath",
    section_ja: "الباب السادس والعشرون في ركوب البحر في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-27",
    maqala: "V",
    section: "Discourse V · Ch. 27: Rivers and the Sabbath",
    section_ja: "الباب السابع والعشرون في كون النهر في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-28",
    maqala: "V",
    section: "Discourse V · Ch. 28: Cooked Food on the Sabbath",
    section_ja: "الباب الثامن والعشرون في الطبخ في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-29",
    maqala: "V",
    section: "Discourse V · Ch. 29: Earning a Living on the Sabbath",
    section_ja: "الباب التاسع والعشرون في التكسب يوم السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-30",
    maqala: "V",
    section: "Discourse V · Ch. 30: Work Done on the Sabbath for After the Sabbath",
    section_ja: "الباب الثلاثون فيما عمل في السبت لبعد السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-31",
    maqala: "V",
    section: "Discourse V · Ch. 31: Using Instruments on the Sabbath",
    section_ja: "الباب الواحد والثلاثون في استعمال الآلات في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-32",
    maqala: "V",
    section: "Discourse V · Ch. 32: Wearing a Ring on the Sabbath",
    section_ja: "الباب الثاني والثلاثون في لبس الخاتم في السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-33",
    maqala: "V",
    section: "Discourse V · Ch. 33: Taking Medicine on the Sabbath",
    section_ja: "الباب الثالث والثلاثون في شرب الدواء في يوم السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-34",
    maqala: "V",
    section: "Discourse V · Ch. 34: Washing on the Sabbath",
    section_ja: "الباب الرابع والثلاثون في الغسل يوم السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-35",
    maqala: "V",
    section: "Discourse V · Ch. 35: Reading Non-Sacred Script on the Sabbath",
    section_ja: "الباب الخامس والثلاثون في قراءة كل خط غير مقدس",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-36",
    maqala: "V",
    section: "Discourse V · Ch. 36: Continuation",
    section_ja: "الباب السادس والثلاثون",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-37",
    maqala: "V",
    section: "Discourse V · Ch. 37: Extinguishing Fire on the Sabbath",
    section_ja: "الباب السابع والثلاثون في طفوء النار يوم السبت",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-38",
    maqala: "V",
    section: "Discourse V · Ch. 38: Continuation",
    section_ja: "الباب الثامن والثلاثون في ذلك",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-39",
    maqala: "V",
    section: "Discourse V · Ch. 39: A Case of the Learned (Sages' Ruling)",
    section_ja: "الباب التاسع والثلاثون في ذكر مسألة من الأمة",
    hasEnglish: true,
  },
  {
    slug: "m5-sha-40",
    maqala: "V",
    section: "Discourse V · Ch. 40: The 39 Categories of Forbidden Labor",
    section_ja: "الباب الأربعون في اثنين وثلاثين نوعًا من الأعمال",
    hasEnglish: true,
  },
];

export const gateBySlug: Record<string, QGate> = Object.fromEntries(
  QIRQISANI_GATES.map((g) => [g.slug, g]),
);

export function gateIndex(slug: string): number {
  return QIRQISANI_GATES.findIndex((g) => g.slug === slug);
}

/** Group gates by maqala for the TOC page. */
export const M1_GATES = QIRQISANI_GATES.filter((g) => g.maqala === "I");
export const M2_GATES = QIRQISANI_GATES.filter((g) => g.maqala === "II");
export const M3_GATES = QIRQISANI_GATES.filter((g) => g.maqala === "III");
export const M5_GATES = QIRQISANI_GATES.filter((g) => g.maqala === "V");
