// Portuguese labels for the Moreh Nevukhim navigation (chapter titles + chrome).
// Generated from the English nav strings; Hebrew-lemma keywords kept identical.
// Keyed by the exact English string used in chapters.ts.
export const MOREH_PT: Record<string, string> = {
  "Atlas of God-language": "Atlas da linguagem divina",
  "Commentators on AlHaTorah ↗": "Comentaristas no AlHaTorah ↗",
  "Guide of the Perplexed · Part I": "Guia dos Perplexos · Parte I",
  "Guide of the Perplexed · Part II": "Guia dos Perplexos · Parte II",
  "Guide of the Perplexed · Part III": "Guia dos Perplexos · Parte III",
  "I:1 · Image & Likeness": "I:1 · Imagem e Semelhança",
  "I:10 · Ascend / Descend": "I:10 · Subir / Descer",
  "I:11 · Yashav": "I:11 · Yashav",
  "I:12 · Qam": "I:12 · Qam",
  "I:13 · ʿAmad": "I:13 · ʿAmad",
  "I:14 · Adam": "I:14 · Adam",
  "I:15 · Natzav & Yatzav": "I:15 · Natzav & Yatzav",
  "I:16 · Tzur": "I:16 · Tzur",
  "I:17 · Concealing Knowledge": "I:17 · Ocultação do Saber",
  "I:18 · Karav, Naga, Nagash": "I:18 · Karav, Naga, Nagash",
  "I:19 · Male": "I:19 · Male",
  "I:2 · Adam's Sin": "I:2 · O Pecado de Adão",
  "I:20 · Ram & Nissa": "I:20 · Ram & Nissa",
  "I:21 · ʿAvar": "I:21 · ʿAvar",
  "I:22 · Bo": "I:22 · Bo",
  "I:23 · Yatza": "I:23 · Yatza",
  "I:24 · Halakh": "I:24 · Halakh",
  "I:25 · Shakhan": "I:25 · Shakhan",
  "I:26 · Language of Men": "I:26 · Linguagem dos Homens",
  "I:27 · Onkelos": "I:27 · Onkelos",
  "I:28 · Regel": "I:28 · Regel",
  "I:29 · Etzev": "I:29 · Etzev",
  "I:3 · Temunah & Tavnit": "I:3 · Temunah & Tavnit",
  "I:30 · Akhol": "I:30 · Akhol",
  "I:31 · Limits of Intellect": "I:31 · Limites do Intelecto",
  "I:32 · Restraint": "I:32 · Contenção",
  "I:33 · Teaching Order": "I:33 · Ordem do Ensino",
  "I:34 · The Five Causes": "I:34 · As Cinco Causas",
  "I:35 · Incorporeality Taught": "I:35 · A Incorporeidade Ensinada",
  "I:36 · Anger & Idolatry": "I:36 · Ira e Idolatria",
  "I:37 · Panim": "I:37 · Panim",
  "I:38 · Achor": "I:38 · Achor",
  "I:39 · Lev": "I:39 · Lev",
  "I:4 · Verbs of Seeing": "I:4 · Verbos de Ver",
  "I:40 · Ruach": "I:40 · Ruach",
  "I:41 · Nefesh": "I:41 · Nefesh",
  "I:42 · Ḥayyim & Mawt": "I:42 · Ḥayyim & Mawt",
  "I:43 · Kanaf": "I:43 · Kanaf",
  "I:44 · ʿAyin": "I:44 · ʿAyin",
  "I:45 · Shemaʿ": "I:45 · Shemaʿ",
  "I:46 · Organs": "I:46 · Órgãos",
  "I:47 · Limits of Language": "I:47 · Limites da Linguagem",
  "I:48 · True Hearing": "I:48 · Audição Verdadeira",
  "I:49 · Angels & Sight": "I:49 · Anjos e Visão",
  "I:5 · Divine Inquiry": "I:5 · Investigação Divina",
  "I:50 · Belief Defined": "I:50 · A Crença Definida",
  "I:51 · Attributes Overview": "I:51 · Panorama dos Atributos",
  "I:52 · Five Attributes": "I:52 · Cinco Atributos",
  "I:53 · Ethical Attributes": "I:53 · Atributos Éticos",
  "I:54 · Attributes of Action": "I:54 · Atributos de Ação",
  "I:55 · No Genus for God": "I:55 · Deus sem Género",
  "I:56 · Existence & Essence": "I:56 · Existência e Essência",
  "I:57 · Negative Attributes": "I:57 · Atributos Negativos",
  "I:58 · Negation & Silence": "I:58 · Negação e Silêncio",
  "I:59 · Silence as Praise": "I:59 · O Silêncio como Louvor",
  "I:6 · Ish & Ishah": "I:6 · Ish & Ishah",
  "I:60 · Prayer & Attributes": "I:60 · Oração e Atributos",
  "I:61 · Divine Names": "I:61 · Nomes Divinos",
  "I:62 · The Tetragrammaton": "I:62 · O Tetragrama",
  "I:63 · Ehyeh Asher Ehyeh": "I:63 · Ehyeh Asher Ehyeh",
  "I:64 · Kavod": "I:64 · Kavod",
  "I:65 · Divine Speech": "I:65 · A Fala Divina",
  "I:66 · Divine Will": "I:66 · A Vontade Divina",
  "I:67 · Sabbath & Creation": "I:67 · Sábado e Criação",
  "I:68 · Intellect Triunity": "I:68 · A Triunidade do Intelecto",
  "I:69 · God as Form": "I:69 · Deus como Forma",
  "I:7 · Yalad": "I:7 · Yalad",
  "I:70 · Kavod & the Chariot": "I:70 · Kavod e a Carruagem",
  "I:71 · Kalām Critique": "I:71 · Crítica do Kalām",
  "I:72 · Universe as Organism": "I:72 · O Universo como Organismo",
  "I:73 · Twenty-Five Premises": "I:73 · Vinte e Cinco Premissas",
  "I:74 · Seven Methods": "I:74 · Sete Métodos",
  "I:75 · Unity Methods": "I:75 · Métodos da Unidade",
  "I:76 · Conclusion": "I:76 · Conclusão",
  "I:8 · Makom": "I:8 · Makom",
  "I:9 · Kisse": "I:9 · Kisse",
  "II:1 · Introduction": "II:1 · Introdução",
  "II:10 · The Four Elements": "II:10 · Os Quatro Elementos",
  "II:11 · The World's Unity": "II:11 · A Unidade do Mundo",
  "II:12 · Emanation": "II:12 · Emanação",
  "II:13 · Three Opinions": "II:13 · Três Opiniões",
  "II:14 · Aristotle on Eternity": "II:14 · Aristóteles sobre a Eternidade",
  "II:15 · Not a Necessity": "II:15 · Não uma Necessidade",
  "II:16 · No Proof for Eternity": "II:16 · Sem Prova da Eternidade",
  "II:17 · No Proof for Creation": "II:17 · Sem Prova da Criação",
  "II:18 · Creation Argument": "II:18 · Argumento da Criação",
  "II:19 · The Divine Will": "II:19 · A Vontade Divina",
  "II:2 · Spheres & Intellects": "II:2 · Esferas e Intelectos",
  "II:20 · Infinite Regress": "II:20 · Regressão Infinita",
  "II:21 · Necessary Being": "II:21 · Ser Necessário",
  "II:22 · Aristotle's Flaws": "II:22 · As Falhas de Aristóteles",
  "II:23 · Interpretation": "II:23 · Interpretação",
  "II:24 · Astronomy & Physics": "II:24 · Astronomia e Física",
  "II:25 · Creation Accepted": "II:25 · A Criação Aceite",
  "II:26 · Torah & Creation": "II:26 · Torá e Criação",
  "II:27 · The World's End": "II:27 · O Fim do Mundo",
  "II:28 · Maimonides' View": "II:28 · A Visão de Maimónides",
  "II:29 · Scripture on Creation": "II:29 · A Escritura sobre a Criação",
  "II:3 · Intelligences": "II:3 · Inteligências",
  "II:30 · The Six Days": "II:30 · Os Seis Dias",
  "II:31 · The Sabbath": "II:31 · O Sábado",
  "II:32 · Prophecy Opinions": "II:32 · Opiniões sobre a Profecia",
  "II:33 · The Sinai Revelation": "II:33 · A Revelação do Sinai",
  "II:34 · Intellectual Fitness": "II:34 · Aptidão Intelectual",
  "II:35 · Moses the Unique": "II:35 · Moisés, o Único",
  "II:36 · Prophecy Defined": "II:36 · A Profecia Definida",
  "II:37 · Prophecy Grades": "II:37 · Graus da Profecia",
  "II:38 · Courage & Vision": "II:38 · Coragem e Visão",
  "II:39 · The Torah Unique": "II:39 · A Torá Única",
  "II:4 · The Spheres": "II:4 · As Esferas",
  "II:40 · Law & Governance": "II:40 · Lei e Governação",
  "II:41 · Dreams & Visions": "II:41 · Sonhos e Visões",
  "II:42 · Angels in Visions": "II:42 · Anjos nas Visões",
  "II:43 · Symbolic Visions": "II:43 · Visões Simbólicas",
  "II:44 · Touch & Prophecy": "II:44 · Toque e Profecia",
  "II:45 · Eleven Degrees": "II:45 · Onze Graus",
  "II:46 · Prophetic Actions": "II:46 · Ações Proféticas",
  "II:47 · Prophetic Hyperbole": "II:47 · Hipérbole Profética",
  "II:48 · Divine Causation": "II:48 · Causação Divina",
  "II:5 · Sphere Motion": "II:5 · Movimento das Esferas",
  "II:6 · Angels as Forms": "II:6 · Anjos como Formas",
  "II:7 · Motion & Movers": "II:7 · Movimento e Motores",
  "II:8 · Celestial Music": "II:8 · Música Celeste",
  "II:9 · The Overflow": "II:9 · A Efusão",
  "III:1 · The Chariot": "III:1 · A Carruagem",
  "III:10 · Evil as Privation": "III:10 · O Mal como Privação",
  "III:11 · Human Self-Harm": "III:11 · Males Autoinfligidos",
  "III:12 · Providence & Evil": "III:12 · Providência e Mal",
  "III:13 · Purpose of the World": "III:13 · O Propósito do Mundo",
  "III:14 · The Sciences": "III:14 · As Ciências",
  "III:15 · The Possible": "III:15 · O Possível",
  "III:16 · Providence Opinions": "III:16 · Opiniões sobre a Providência",
  "III:17 · Five Opinions": "III:17 · Cinco Opiniões",
  "III:18 · Providence & the Mind": "III:18 · A Providência e o Intelecto",
  "III:19 · God's Knowledge": "III:19 · O Conhecimento de Deus",
  "III:2 · Light & Fire": "III:2 · Luz e Fogo",
  "III:20 · Knowledge Equivocal": "III:20 · Conhecimento Equívoco",
  "III:21 · Job & Providence": "III:21 · Jó e a Providência",
  "III:22 · Job Interpreted": "III:22 · Jó Interpretado",
  "III:23 · Job's Resolution": "III:23 · A Resolução de Jó",
  "III:24 · The Aqedah": "III:24 · A Aqedá",
  "III:25 · Purposes of Torah": "III:25 · Propósitos da Torá",
  "III:26 · Reasons for Laws": "III:26 · Razões das Leis",
  "III:27 · Two Perfections": "III:27 · Duas Perfeições",
  "III:28 · Torah's Two Goals": "III:28 · Os Dois Fins da Torá",
  "III:29 · Against Idolatry": "III:29 · Contra a Idolatria",
  "III:3 · The Firmament": "III:3 · O Firmamento",
  "III:30 · Prohibition of Idolatry": "III:30 · Proibição da Idolatria",
  "III:31 · Reasons for Precepts": "III:31 · Razões dos Preceitos",
  "III:32 · Sacrificial Laws": "III:32 · Leis Sacrificiais",
  "III:33 · Moral Laws": "III:33 · Leis Morais",
  "III:34 · Laws for the Many": "III:34 · Leis para a Maioria",
  "III:35 · Fourteen Classes": "III:35 · Catorze Classes",
  "III:36 · Anti-Idolatry Laws": "III:36 · Leis Anti-Idolatria",
  "III:37 · Further Prohibitions": "III:37 · Outras Proibições",
  "III:38 · Symbols & Signs": "III:38 · Símbolos e Sinais",
  "III:39 · Agricultural Laws": "III:39 · Leis Agrícolas",
  "III:4 · The Chariot Vision": "III:4 · A Visão da Carruagem",
  "III:40 · Injuries & Penalties": "III:40 · Lesões e Penas",
  "III:41 · Penal Laws": "III:41 · Leis Penais",
  "III:42 · Property Laws": "III:42 · Leis de Propriedade",
  "III:43 · Holy Days": "III:43 · Dias Santos",
  "III:44 · Sabbath & Festivals": "III:44 · Sábado e Festas",
  "III:45 · Temple Laws": "III:45 · Leis do Templo",
  "III:46 · Sacrifices & Fasts": "III:46 · Sacrifícios e Jejuns",
  "III:47 · Priestly Laws": "III:47 · Leis Sacerdotais",
  "III:48 · Moral Improvements": "III:48 · Aperfeiçoamentos Morais",
  "III:49 · Sexual Laws": "III:49 · Leis Sexuais",
  "III:5 · Ezekiel's Chariot": "III:5 · A Carruagem de Ezequiel",
  "III:50 · Secret Reasons": "III:50 · Razões Secretas",
  "III:51 · The Palace Parable": "III:51 · A Parábola do Palácio",
  "III:52 · Fear & Love of God": "III:52 · Temor e Amor de Deus",
  "III:53 · Four Perfections": "III:53 · Quatro Perfeições",
  "III:54 · Final Perfection": "III:54 · A Perfeição Final",
  "III:6 · The Chariot Allegory": "III:6 · A Alegoria da Carruagem",
  "III:7 · The Chariot Revealed": "III:7 · A Carruagem Revelada",
  "III:8 · Matter as Evil": "III:8 · A Matéria como Mal",
  "III:9 · The Brilliant Light": "III:9 · A Luz Brilhante",
  "Parallel view": "Visão paralela",
  "Part I · Vocabulary & Negative Theology (76 chapters)": "Parte I · Vocabulário e Teologia Negativa (76 capítulos)",
  "Part II · Physics, Creation & Prophecy (48 chapters)": "Parte II · Física, Criação e Profecia (48 capítulos)",
  "Part III · Providence, Law & Perfection (54 chapters)": "Parte III · Providência, Lei e Perfeição (54 capítulos)",
  "Verses index": "Índice de versículos",
};
